### ISSUE TITLE
Feature request: enable live audio playback along with the animation in the Combo Viewer window

### ISSUE THREAD

**Issue by yvanc** [opentoonz/opentoonz#100]
I noticed that imported audio can only be played in the rendering preview window if you click on the button with the music icon on it. It would be nice if you can live audio playback along with your animation in the x-sheet timeline window or in the Combo Viewer. Just add the music icon from the rendering preview window into the Combo Viewer or the x-sheet timeline window.

**Comment by RodneyBaker** [comment]
I realize you are focused on adding the audio toggle to the Combo Viewer but the following part of your initial observation may need a little more refinement:

You said:
<snip>
It would be nice if you can live audio playback along with your animation in the x-sheet timeline window</unsnip>

Audio can play back live in the XSheet by scrubbing up and down on the left side numbering.  This is useful in plotting out frame of animation where sound is  emphasized and I dare say this scrubbing is likely more useful than actual play back in the xsheet as it'd be hard to draw at the speed of playback (although... that might be a bit like mouse capture!).  The audible sound works great in this scrubbing capacity especially when used in conjunction with the visual cue of the waveform in the xsheet column.

I do wonder if in Preferences there couldn't be a master toggle that would turn audio on in all areas of OpenToonz (a master audio on/off button)..  That might be a pain to have on as a default but it would sure help to keep new users from wondering how to find and turn on the audio.  The con might be that of dealing with multiple windows playing back simultaneously.  That amount of sound might be very nerve wracking.

**Comment by odysseywestra** [comment]
@RodneyBaker So technically the feature is in there? If so, it's probably best to close this issue. Later we can revisit this to improve it, but right now we need to focus on getting openToonz stable.
