### ISSUE TITLE
Windows uninstall list displays incorrect version number

### ISSUE THREAD

**Issue by adama357** [opentoonz/opentoonz#1001]
Currently I have OpenToonz version 1.1.2 installed on a Windows 7 computer.  But when I go to "Control Panel" -> "Uninstall a Program", it lists the version number as 1.1.0, both in the "Name" column and the "Version" column:  

![ot_uninstall_wrong_version](https://cloud.githubusercontent.com/assets/20462430/22232927/1872275e-e1b2-11e6-9d34-6c4cd444b4ff.jpg)

I believe version 1.1.0 was previously installed on my computer at some point, but I did a clean install.  (I deleted the OpenToonz "stuff" directories before reinstalling.)  

(By the way, thank you all for working on this wonderful program!!)

**Comment by shun-iwasawa** [comment]
Fixed in [opentoonz/opentoonz_installer_windows#5](https://github.com/opentoonz/opentoonz_installer_windows/pull/5).
