### ISSUE TITLE
Changing level type resets name

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1006]
In the New Level dialog, the Name field starts as "A".  If I change the name to "Gorilla" and then change the level Type, the name reverts to "A". 

(Win 7, nightly build from 2017-01-24)

**Comment by artisteacher** [comment]
This happens on OS X as well.

**Comment by turtletooth** [comment]
Thanks- I'll take a look.

**Comment by turtletooth** [comment]
Fixed in #1011

**Comment by mcjadski** [comment]
Thanks!
