### ISSUE TITLE
Some closed shapes unfillable before switching to Fill Tool

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1007]
Right now the coloring functionality is very easily broken on Toonz Vector Levels.  Here is a very simple example to illustrate:  

![deformed_circle](https://cloud.githubusercontent.com/assets/25377429/22357568/a86f4708-e3fe-11e6-8c36-612066119d89.jpg)

This is a blob named Gorilla.  He's a closed shape:  

![gorilla_connect](https://cloud.githubusercontent.com/assets/25377429/22357647/37ee10bc-e3ff-11e6-9a68-b043d8112da9.jpg)

But Fill Check is turned on, and he is unfillable.  However, if you draw anything to the right of him (on the same level), he becomes fillable, whether the dot is near him or far away:  

![gorilla_fillable](https://cloud.githubusercontent.com/assets/25377429/22357718/9d42a37e-e3ff-11e6-9aa5-be5a6fb520e0.jpg)

If you draw to the left of him, above him, or below him, he remains unfillable (unless you draw something to the right of him):  

![gorilla_not_fillable](https://cloud.githubusercontent.com/assets/25377429/22357756/e7b6ba76-e3ff-11e6-955b-0dc5dc61f7ea.jpg)

As you pull one of the end points downward (always keeping it a closed shape), at some seemingly arbitrary point, he becomes fillable:  

![gorilla_almost_fillable](https://cloud.githubusercontent.com/assets/25377429/22357796/36e97520-e400-11e6-8fde-47f3a510187d.jpg)

![gorilla_suddenly_fillable](https://cloud.githubusercontent.com/assets/25377429/22357817/531e9af4-e400-11e6-9fa9-48902dabbc2f.jpg)

Here are the .tnz and .pli file:  
[gorilla_test.zip](https://github.com/opentoonz/opentoonz/files/734154/gorilla_test.zip)

I tested this file on Win 7 and OSX 10.11 and got the exact same results.  

If such an incredibly simple picture as this can't be filled correctly, imagine how nightmarish it would be to make fillable a complicated drawing...!  

OpenToonz is on the whole an excellent program, and I have HUGE respect for the team;  but this is something of an "Achilles' heel" right now, as it renders the vector functionality all but unusable.

**Comment by turtletooth** [comment]
Confirmed.  I have also ran into weird fill issues.  @shun-iwasawa I don't know anything about vector math.  Do you have any idea what might cause issues like this?  It makes vector levels pretty inconsistent to work with.

**Comment by shun-iwasawa** [comment]
Confirmed.
Is this only the problem of Fill Check? I mean, can you fill the area even if the Fill Check says it is unfillable?

I confirmed that it turns into fillable without touching the image, by just switching to Type tool and then back to another tool. I'm not sure but I think some trigger for updating information of fillable or unfillable is missing.

**Comment by turtletooth** [comment]
@shun-iwasawa In this case it is only a problem of fill check, but I have experienced fully closed shapes that are not fillable until I change a couple of control points even though they were fully closed before the change, or filled shapes that forget their fill after a while.  

I will see if I can create an example file to upload.  I feel like the vector inconsistency is holding back OpenToonz adoption and creating frustration for users.  I wish I knew the math involved so I could work on it.

**Comment by mcjadski** [comment]
Like turtletooth said, there are situations where a shape should be fillable, but you try to fill it with a color, and it refuses to work.  We will have to continue to experiment until we find a reproducible example of this.  

However, I've decided to rename this issue, because it's now clear that this particular example represents a more specific bug; namely, sometimes when you draw closed shapes, they're not fillable, **until** you switch to the Fill Tool.  

Once you switch to the Fill Tool, they become fillable.  Switching to any tool besides the Fill Tool, before you switch to the Fill Tool, does not make them fillable.  Once you've switched to the Fill Tool once, no matter what tool you switch to, all shapes remain fillable forever, UNLESS you revert to a blank canvas via undo or erasing.  

Obviously then, it's impossible to tell whether this is a glitch with the Fill Check specifically, since there's no way to attempt to fill a shape before switching to the Fill Tool.  

If, after switching to the Fill Tool, you Save All and re-open the scene, all remains fillable.  If you then restore the .pli file to a previous state but keep the scene file the same, it goes back to being un-fillable.  

However, if you make it fillable by moving a control point, then move the control point back, it reverts to being unfillable:  

![gorilla_suddenly_fillable_reverts](https://cloud.githubusercontent.com/assets/25377429/22447295/590683ea-e717-11e6-8648-49e2b7b733ef.jpg)

So yeah, I've spent hours and hours drawing random fish... in the futile hope that I might understand how this works.  

One clear pattern I've found is, if the fish faces _away_ from the center, it's fillable, and vice versa:  

![fish_out_vs_in](https://cloud.githubusercontent.com/assets/25377429/22450647/c410b258-e72d-11e6-8c8c-f54c668122ec.jpg)

As for more fish, sometimes it seems to be a pattern:  

![fish_pattern_can_undo](https://cloud.githubusercontent.com/assets/25377429/22450662/d55f3548-e72d-11e6-94f6-52108380e64c.jpg)

But then the next move I make...  

![fish_not_pattern](https://cloud.githubusercontent.com/assets/25377429/22450677/f1f7f4ba-e72d-11e6-83af-90ce37cc6d62.jpg)

And then there's this:  

![fish_almost_pattern_can_undo](https://cloud.githubusercontent.com/assets/25377429/22450682/fa097d7c-e72d-11e6-85a2-2a8ef27e0976.jpg)

And these examples don't really help much, because sometimes when you do seemingly the same thing, you get different results.  I feel like somehow different (blank) scene files have different properties...!  @_@

For instance, in the above cases, if you hit Undo, it goes backwards through the sequence of images I've posted, with fillable shapes going back to being unfillable.  However, sometimes (I promise) even if you hit undo, the shapes remain fillable!  

(This post, I only tested on Win 7.)  

I think it's time for me to give up on understanding how this "works", lol...  I just hope that someone who sees maybe some variable changing behind the scenes can figure out what the problem is...

**Comment by shun-iwasawa** [comment]
https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tvectorimage/tcomputeregions.cpp#L2585
I know it is not the cause of this issue, but I found in the source that very small region (with area less than approx. 0.0001 square inch, 1.26 square pixel in 120dpi scene) will not be registered as fillable region.

**Comment by shun-iwasawa** [comment]
@mcjadski I've partially fixed the problem in the PR above. Please note that it just modifies the Fill Check behavior.

Just now I think I could make the sample for reproducing the "unfillable" problem... Could you please try this ?  [unfillable.zip](https://github.com/opentoonz/opentoonz/files/816428/unfillable.zip)

**Comment by artisteacher** [comment]
I had an similar fill issue going on this week. I was using the automatic tweening feature and on the first frame a closed shape would not fill - but the same area filled on all of the other layers. If I moved the shape away from the location I drew it, suddenly the fill would show. When I moved the shape back, the fill disappeared. I changed projects and worked on something different. Then when I started OpenToonz today, going back to that scene and project, I was able to fill the area.

**Comment by mcjadski** [comment]
@shun-iwasawa  Thank you so much!!  I'm excited to hear progress is being made with this issue!   And I'm happy my "fish" were helpful...  ^^

On Win 7, I did some experimenting with your unfillable.pli file.  For reference, here's the starting position:  

![unfillable_start](https://cloud.githubusercontent.com/assets/25377429/23776461/1d95a764-04f4-11e7-8f45-f3287dd6d780.jpg)

If you adjust the angle of one of the handles like this, the fill swaps to the other region!  (The color is whatever color you had in the other region.)  

![unfillable_swap](https://cloud.githubusercontent.com/assets/25377429/23776547/9ccf494a-04f4-11e7-9bf6-030ec93d54e5.jpg)

If you adjust it to this position, the whole thing becomes unfillable:  

![unfillable_none](https://cloud.githubusercontent.com/assets/25377429/23776599/d5ed768e-04f4-11e7-819c-89db66179159.jpg)

Here, the whole thing becomes filled!  I didn't fill it, it just became all the one color:  

![unfillable_all](https://cloud.githubusercontent.com/assets/25377429/23776627/033b1dc6-04f5-11e7-8811-cfb7c64ce5f7.jpg)

You can color them differently then:  

![unfillable_different](https://cloud.githubusercontent.com/assets/25377429/23776637/141f25f6-04f5-11e7-9b79-273b6bb255dc.jpg)

As you tweek it slightly, the left region will sometimes flash between filled and not filled.  (NOTE:  If you color the left region red, then tweek it so the left region becomes unfilled, then tweek it so it becomes filled again, it will be black, not red.)  

![unfillable_near_all](https://cloud.githubusercontent.com/assets/25377429/23776685/63ea290a-04f5-11e7-9e99-e52df2016f22.jpg)

Making the image large using the Edit Tool has no effect:  

![unfillable_big_edit](https://cloud.githubusercontent.com/assets/25377429/23776694/7379a9fe-04f5-11e7-9bd9-5c7d69c937f6.jpg)

However, making it bigger with the Selection Tool makes the whole thing filled:  

![unfillable_big_selection](https://cloud.githubusercontent.com/assets/25377429/23776705/85fac4dc-04f5-11e7-9dc4-15049db91f59.jpg)

Moving it around with either tool seems to have no effect.

**Comment by mcjadski** [comment]
This can probably be closed, since the problems describe in this issue are fixed in #1079, and a different fill glitch is being discussed in #1093.
