### ISSUE TITLE
Cell input feature problems 

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1014]
This issue was reported by some Japanese animation studio, using OpenToonz as the pencil test tool by activating  `Use Arrow Key to Shift Cell Selection` and `Enable to Input Cells without Double Clicking` preference options.
When using such options, there are some problems as follows:
- "Delete cell" command cannot be used when the input field is shown.
- If a single cell is selected, user cannot drag&move such cell since the side bar of the cell is covered with the input field.

**Comment by turtletooth** [comment]
#1015 merged
