### ISSUE TITLE
Feature request: option to import every nth frame of video

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1018]
When loading a video as a level, it would be great to have the option to load only every 4th frame (or etc.) instead of having every frame load. This could be handy for rotoscoping, animated gifs or etc. Photoshop gives this option when importing a video to layers. 
![image](https://cloud.githubusercontent.com/assets/21159116/22486845/242db496-e7d9-11e6-91cc-7a0bc422e1ef.jpeg)

**Comment by turtletooth** [comment]
You can achieve a similar result by selecting all cells in an xsheet column and choosing each 2, 3, or 4.

I realize that it doesn't have as much control, but it is something for now.

**Comment by artisteacher** [comment]
Thanks - that will definitely do for now. This makes  OpenToonz so much better for making animated gifs (for tutorials) than Photoshop (since it can't handle larger sizes). 

After actual actual importing is added back in, importing every nth frame would still be a helpful feature as it would help keep the project size smaller.

**Comment by artisteacher** [comment]
Closing due to #1207.
