### ISSUE TITLE
Plastic Tool Mesh: Ability to Parent Things to Mesh Bones (Vertex)

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#102]
Right now you can create a mesh over a drawing that is drives the drawing's deformation via bones.

That mesh can be made a child to other things - as it is exposed to the schematic view.
But you can not make anything a child to any of the bones, since they can not be exposed to the schematic view.

As an example lets pretend that you have a character whose torso is driven by the platic tool mesh. You want to attach some arms to that character, to do that you need to make them a child of a specific bone (chest). You cant.

**Comment by blurymind** [comment]
Here is an image to illustrate it:
![meshboneparentexternalobject](https://cloud.githubusercontent.com/assets/6495061/14119745/7e910166-f5e7-11e5-9406-6cfefa029944.PNG)

I want to be able to attach things to mesh bones

**Comment by daniele-pini** [comment]
I remember the original Toonz having several ports on one side of a schematic node with letters and numbers to choose from.

Port letters were bound to pegbar holes (everyone always only used the center one 'B').

Numbers were introduced to bind hooks and plastic skeleton vertexes (the numbers between parenthesis), so you could parent skeleton vertexes of a mesh column to other columns.

Now all I see are a blue and red dot per node, with no other indication. It's probably a feature lost in the open sourcing.


As a workaround, you could try merging the two drawings in one and remesh. The apple should result in a separate mesh component in the same mesh drawing - then you can use a single skeleton to animate both components.

**Comment by digitallysane** [comment]
Yes, hooks are already doing what you need, but from the Harlequin manual it seems indeed that Harlequin's UI is more useful for this.

In the Harlequin manual: http://www.toonz.com/cgi-shl/download/71H/Toonz%20Harlequin%2071%20User%20Guide.pdf
Page 271 (288 of the PDF)

**Comment by blurymind** [comment]
Can we then please get this feature back? I can think of many scenarios
where the workarounds will fail or be a pain in the neck to use!

**Comment by blurymind** [comment]
I think we have enough data to call this an Enhancement feature

**Comment by digitallysane** [comment]
Interesting, if you download the Paperless Tutorial files
http://www.toonz.com/htm/support/suppw.htm
And open the scenes in OT and examine the schematic, you'll see that the
multiple hook connections ARE there.
So at least it can understand them in existing Toonz scenes.
Wondering if there's some shortcut to create them?

**Comment by blurymind** [comment]
@digitallysane - So that means that the functionality IS there, but it is not exposed to the users through the GUI :)
Here it is from the mozart scene file:
![legacyhookz](https://cloud.githubusercontent.com/assets/6495061/14139047/8f282172-f668-11e5-8c59-3bb8b400083d.JPG)

Sounds like a low hanging fruit (no pun intended) that would bring great benefits to the users.
Would it be possible for some programmer to expose this functionality to the gui?

**Comment by digitallysane** [comment]
I suspect ALL the functionality we are talking about (XSheet keys, etc) is
there. I have a hard time believing the guys at Ghibli actually took their
time to completely and utterly delete this stuff out forever.
I'm actually wondering if it's not simply a question of config files
instead of code.

**Comment by blurymind** [comment]
I tested a file from harlequin with a level that is parented to a mesh bone (schematic view).
The parenting works in opentoonz!  The mesh needs to be recreated though ('keep the old level and overwrite processed frames') - otherwise the meshed level is not visible.

The functionality is all there, but not exposed to the schematic view.

**Comment by blurymind** [comment]
It's not a question of config files either :( Or at least it doesnt seem to be in this case.

**Comment by BrundleThwaite** [comment]
what is missing is not the ports but the up and down arrow that should appear when you hover the mouse over them which enable you to choose centers and verteces

**Comment by blurymind** [comment]
It is missing the extra ports and port id indicators. On opentoonz a mesh has only one output port. In toonz harlequin there are two. Also actual ports have a number or a letter showing their id. The up and down arrows change the id. Opentoonz has none of that. I posted the screenshots for a reason you know :p

**Comment by BrundleThwaite** [comment]
your image from already shows the ports. They show up as red dots and do not show the numbers 

![nodes](https://cloud.githubusercontent.com/assets/18170954/14150814/35d10bd2-f6ab-11e5-96b7-c428f81abf7a.png)

unfortunately without the ability to manipulate the vertex info they don't have any use with the plastic tool.

**Comment by blurymind** [comment]
@BrundleThwaite In the case of using a mesh, it has only one port output. See here:
![meshboneparentexternalobject](https://cloud.githubusercontent.com/assets/6495061/14119745/7e910166-f5e7-11e5-9406-6cfefa029944.PNG)
The mesh node has only one output. I invite you to try it for yourself.

Your screenshot is showing a level with hooks - those outputs are hooks.

**Comment by BrundleThwaite** [comment]
You Can't attach hooks to a plastic mesh in harlequin either. I takes a more roundabout route

Here is the procedure from the harlequin 

manual:

> Parenting Plastic levels using vertices and hooks
> 
> For building interesting and complex animations it could be useful and
> time saving to create a Parent -> Children relation between standard
> Toonz levels and Plastic modified levels, or between Plastic modified
> levels, so that the children levels inherit the transformations of the
> parent automatically. It is always possible to link the levels using the
> Pegbar as target but what if something more subtler is needed as using
> hooks? We have already described similar techniques for Toonz standard
> elements (see Linking Objects on page 223 or Using Hooks on page 225),
> but Plastic modified levels works in a slightly different way because the
> Hook tool is not active on this kind of levels. Plastic modified levels use
> their skeleton vertices instead of the hook points.
> To link a standard level to a Plastic modified level
> 1. Select in the Xsheet the level that has to be linked.
> 2. Use the Hook tool in the main viewer to create a hook point on the
> spot that will be used as pivot for the level.
> 3. Go to the Stage Schematic and select the node of the level that has to
> be linked. Click on the small square on its left side, and drag to one of
> the small squares on the right side of the Plastic modified level target of
> the link. Now the two levels are linked but the reference points for the
> link are probably wrong (by default the Pegbar centers are used).
> 4. Hover on the small square on the left side of the node of the standard
> level until two small arrows (pointing up and down) appear.
> 5. Click on the arrows and drag to change the value in the small square.
> Stop when the number of the hook point that has to be used as pivot
> point is reached. In the main viewer the level moves using the point
> selected as new center.
> 6. Do the same procedure of point 5 on the small square on the right of
> the Plastic modified level that was used as target for the link. Select the
> number of the skeleton vertex that has to be used as target reference
> point for the link. Into the main viewer the standard level moves to
> overlap the position of the hook point selected as reference to the
> position of the skeleton vertex selected on the Plastic modified level.
> Note: A mirror procedure can be used for linking a Plastic modified
> level to a standard Toonz level.
> To link Plastic modified levels
> The procedure requires that all the levels involved and that need to be
> linked using determined positions, have at least one skeleton built and
> one of its vertices has to be positioned at the desired spot for the linking.
> As said the Hook tool doesn’t work on the Plastic modified levels so, for
> exact positioning, skeleton vertices are needed as reference points both
> on the source and on the target of the link.
> 1. Go to the Stage Schematic and select the node of the level that has to
> be linked. Click on the small square on its left side, and drag to one of
> the small squares on the right side of the target of the link. Now the two
> levels are linked but the reference points for the link are probably wrong
> (by default the Pegbar centers are used).
> 2. Hover on the small square on the left of the node of the first level
> until two small arrows appear.
> 3. Click on the arrows and drag to change the value in the small square.
> Stop when the number of the skeleton vertex point that has to be used as
> pivot point is reached. In the main viewer the level adjusts its position in
> respect of the new selected center.
> 4. Do the same procedure of point 3 on the small square on the right of
> the Plastic modified level that was used as target for the link. Select the
> number of the skeleton vertex that has to be used as target reference
> point for the link. Into the main viewer the first level moves to overlap
> the position of its selected skeleton vertex to that of the target skeleton
> vertex just selected.

The arrows I am referring to are these:

![arows](https://cloud.githubusercontent.com/assets/18170954/14151500/7197e750-f6ae-11e5-9eb3-6b73ae8568eb.png)

**Comment by blurymind** [comment]
Yes I know :) 
We are on the same page here. In open toonz:
- The slider is missing, the indicators are missing, 
- automatic creation of new output node slots is missing, 
- hook outputs are not placed in a slot line in harlequin - but are all displayed.

See one of my previous posts where I quote the exact same thing.
This is why we really need this feature in order to fully do cut out animation. Otherwise the mesh nodes can only be children, but not have children.

**Comment by BrundleThwaite** [comment]
I am not tying to fight or argue :)
And agree with you completely but the more info we give the easier it is to fix. 
i was just saying that red dots are the nodes (although the numbered labels are understandable) but that without arrows that allow you to manipulate them they are pretty useless and that is the bigger issue.

**Comment by blurymind** [comment]
@BrundleThwaite Yes, you have uncovered another issue connected with the lack of the arrows and indicators on outputs and inputs - hook outputs in opentoonz look like a usability mess. It is hard to tell which is which and when you have a lot of them you would need to count them every time you need a specific one.

**Comment by BrundleThwaite** [comment]
my thought exactly :)

**Comment by SafariMonkey** [comment]
Let's also remember that we don't have to exactly copy Harlequin – if we find a better way of representing things, we could also try that. I don't know whether there's a better way here, but I think it would be a shame to just mindlessly copy Harlequin exactly, without thinking of other possibilities.

**Comment by blurymind** [comment]
In harlequin the user can not directly enter a number or a letter in the
indicator. I think the most obvious way to improve the design is to allow
the user to just write a number or a letter in the output indicator, rather
than using a fiddly scrolly thing

**Comment by psychoanima** [comment]
Yes, no plastic vertex parenting and no output numbers are confusing me. But the most annoying is that keyframes are not visible in Xsheet!.

**Comment by blurymind** [comment]
@psychoanima That is for another bug report. This one is specifically for the missing features in the Schematic view and for the inability to parent things to mesh bones in opentoonz, that is present in toonz harlequin.

**Comment by blurymind** [comment]
Another way that the toonz harlequin design could be improved upon is by using actual human readable names for the input/output slot entries rather than numbers and letters.
An example to look at is blender's menu to select a datablock - it is present everywhere in the software and:
- Shows only existing items that are present and can be used in the node 
- They are named in a human readable language 
- You have a nice search filter
- Adding and removing inputs and output slots is easy and intuitive- more importantly - you can actually do it on nodes where it applies
![blendernode](https://cloud.githubusercontent.com/assets/6495061/14173352/45cc8dc4-f735-11e5-8f5e-1159a1c3c132.PNG)

**Comment by blurymind** [comment]
@digitallysane > You said that you have a hard time believing that the folks at Ghibli took their time to remove the functionality - but that is exactly what seems to have happened:
https://github.com/opentoonz/opentoonz/issues/108
I am now not sure if they want to bring it back :( Will opentoonz be just a cut down version of toonz - with a half broken plastic tool and a schematic view?

**Comment by digitallysane** [comment]
Well, according to the post from one of their programmers, the changes can be reverted. So it means they didn't take them out from the code, just had them hidden.

**Comment by blurymind** [comment]
Hopefully they will revert the changes enough to bring back this functionality :)

We did our best to state why it's an important part of our workflow.
If I was a programmer I would dig into the schematic view code and see if I can find the uncommented lines.

**Comment by digitallysane** [comment]
> If I was a programmer I would dig into the schematic view code and see if I can find any uncommented lines. But I am not one. So it is entirely up to the developers.

It's not very clear who people think the "Developers" are.
There is a sense on entitlement in the air, that *somebody* should do this or that, or else people won't use the software.
This software is not Toonz, it's the version of Toonz tuned for the particular pipeline of Ghibli by Ghibli programmers. They released it as Open-Source, and now it's in the wild for people to do whatever they want with it.

It's not very clear for me what exactly is the relationship between Dwango and Ghibli, and indeed it seems there are some people at Dwango taking care of the software, but I'm wondering if Ghibli is willing to pay their programmers for their time doing stuff to the software that is of no benefit to the Ghibli pipeline.

The software is out there and anybody can tweak it. It's barely been a week. If the development around it takes off, lots of stuff will happen (some of it will be bad, unfortunately), just give it some time. Or, wait a bit until the toonzpremium shop comes online and buy that if it's more suited to your workflow.

**Comment by blurymind** [comment]
People are just afraid that this would end up being a cut down version of
toonz. Only experienced programmers can really do or undo changes.

We simply state what is missing and we need in order to use it in our
pipeline.

Nothing really stops the open source community from forking opentoonz and
undoing the removal of features. Open source is about democracy. If you had
a choice to be a part of a project that supports what you need vs one that
has removed what you need - which one would you support? :)
Open source greatly depends on its userbase, because part of that userbase
are the programmers, another part are those who report bugs found in the
pipeline. The more users a project has- the more likely it is to be
supported.

I too would like to know more about dwango. What are their plans for
opentoonz. What is the development roadmap? Blender foundation is a good
example of transparent development. Its the reason for their success as an
open source project

**Comment by BrundleThwaite** [comment]
It is not a cut down version at all from what i can see all the real changes are cosmetic. With a couple of custom effects added.

But is has been a few years since i did any work with toonz so I may be missing a couple of things.

**Comment by blurymind** [comment]
So it seems, but these cosmetic changes have broken a lot of features and the japanese developer does not look very keen on fixing the regressions. :)

@digitallysane is implying that this might in fact be their plan - to remove the features instead of fixing them, while offering the features in the premium version of toonz. 

This is why I would very much like to know what Dwango has in mind for toonz - The Roadmap. :)
 Dont you want to know too?

**Comment by digitallysane** [comment]
I never implied anything.
I said they are open sourcing this software "as is", and it's up to the community to modify it, and it's a bit unrealistic to expect them to do work that doesn't benefit them.
I also said that alternatively one can look into toonzpremium, which is a completely different thing by a completely different company.
Of course a roadmap or at least a kind of status: this is what we are willing to do, this is what it's up to anyone else, would be most welcome.

**Comment by blurymind** [comment]
@digitallysane You are right. It does not benefit them. But it does benefit the community. so the community can fix these issues.

In the end It's up to Dwango to accept the pull requests or deny them. And up to the community to work on a fork or make pull requests to the main branch.

**Comment by BrundleThwaite** [comment]
Toonz has been loosing ground on Toonboom and TVPaint for years (A lot of which has been to do with marketing). Retas Pro also cornered the japanese market so they have never made huge gains there. With the potential closure of Studio Ghibli they might loose their most prominent client. Going open source would give them access to more development resources than they now have. They are hoping to make money of integration and services rather that product sales because they have already lost the market share battle.

But you can't make a open source Road-map until you have developers on board it will take a few months before anything like that will be a possibility.

**Comment by 3Rton** [comment]
But that makes no sense because OpenToonz and Toonz Premium are still being developed by different entities. Toonz Premium is still (at least to my understanding) being developed by Digital Video in Italy. In other hand OpenToonz is (right now at least) being directed by Dwango which is part of a huge media corporation. Despite that, as fas as I can tell, they have 2 programmers working on OpenToonz. I wouldn't really trust on Studio Ghibli for assistance, they merely opensourced some of the tools they developed in-house. 

It comes down to the fact that we have way more animators/artists than we actually have seasoned coders who could fix things. Second big problem is probably going to be division. All the bigger authorities are concurrently Japanese. I'd assume a lot of the programmers who would be interested and experienced (say those who worked with Ghibli on the software) are also Japanese. While I love the country and lot of their culture, they are notoriously bad at English. Not only that but their presence in western side of Internet is also minimal: they have their equivalents of almost all sites we use. 

To be honest, right now I'm pretty sure the people making a salary working on OpenToonz probably have their hands full trying to get a ground work for the forums and community on place.

It is going to be interesting to see where the community goes and develops, though. We should probably continue this line of discussion on the forum, though. Don't think we can do much about the actual tool before we have someone who might be able to work it on the code side.

**Comment by blurymind** [comment]
I think that for the scope of this conversation we should focus on the issue of the regression bug. We do not have enough information and a lot of what we are talking about here on Dwango and Digital video is pure speculation. So let's not come to conclusions until they speak for themselves.

I do not think that the japanese people are bad with english - one of the main developers spoke out about these regressions and his written english was excellent.

As users what we should do to help is document the bugs, track them down to their source and explain why they are regressions and how they affect workflow. We have done that so far. Hopefully someone with the experience will pick it up and fix this at some point.

**Comment by BrundleThwaite** [comment]
Here as a completely different approach which I would personalty prefer.

You remove the ability to make bones from columns and meshes completely.

And make chains form the pegs (linking the bones to the peg centers) that way you would separate the deforms from the drawings and would have a flexible parenting system. Which if done correctly could also be a lot simpler, provide a clean interface and avoid magic numbers and hidden data.

![untitled-1](https://cloud.githubusercontent.com/assets/18170954/14232159/75b0f414-f99f-11e5-819e-6b3ace7db5a1.png)

**Comment by blurymind** [comment]
@BrundleThwaite > Which tool in opentoonz makes the pegs?
I dont mind the numbers - they are not magic - it's quite clear which is which :)

What you are proposing sounds like a more complicated approach for a solution. correct me if I misunderstood:

original toonz design:
mesh level contains bones. Bones are in a hierarchy and you can directly parent objects(other levels) to bones via the schematic view. You can even animate that relationship by keyframing those magic number slots.

mesh bone --> child level

Your proposal:
Instead of using the mesh node, which was designed to serve that purpose - to directly connect other levels to bones, we:
1. have to Create a peg for each individual bone we want to be a parent of another level.
2. Then make the peg a parent of whatever we want to be parented to the bone.

mesh bone --> peg --> child level

I am against any solution that might introduce extra steps in the character setup process. To me that is not simplifying, but rather overcomplicating it. I dont like the idea of using the pegs in this case - because of the terminology. In every other software out there - be it for 2d or 3d animation - when you smooth bind a mesh - you always bind it to bones.  Pegs serve a completely different functionality.

I think that what you really want here is to have the parent-child relationship of mesh bones exposed to the schematic view- Instead of having all the mesh bones inside a single mesh node.
This is something I can get behind :) The downside of this approach would be having a lot of extra nodes in the schematic view take more space.

The 'magic numbers' output slot design in toonz harlequin is something that can be improved and made very intuitive with a much simpler solution:
https://github.com/opentoonz/opentoonz/issues/102#issuecomment-204160197
One that does not require to redesign and refactor (possibly break even more) entire tools in the software.

Right now I think that we should focus on bringing the broken functionality back first, then improve it's presentation.

**Comment by BrundleThwaite** [comment]
The pegs are a basic part of the schematic and the are used to organize.

> I dont mind the numbers - they are not magic - it's quite clear which is which :)

> I cannot find the vertex numbers anywhere else so I am not sure why they are clear. 
> I am against any solution that might introduce extra steps in the character setup process. To me that is not simplifying, but rather overcomplicating it. I dont like the idea of using the pegs in this case - because of the terminology. In every other software out there - be it for 2d or 3d animation - when you smooth bind a mesh - you always bind it to bones. Pegs serve a completely different functionality.
> 
I personally prefer flexibility in rigging.

The bones in the toonz scene are not bones they are simply a way of organizing the hierarchy. And in referring to them strictly as bones is not universal as some they work differently in all 3D applications (There can be a huge difference in terminology between application). In some applications they are refereed to as defamers and bones are merely a form of visual representation  .

**Comment by blurymind** [comment]
You still need to turn a drawing into a mesh, before you can deform it via bones. You need to assign areas that would be affected by the different bones (or pegs) - that process is universally called 'skinning'. How would that work?

**Comment by BrundleThwaite** [comment]
All you need is the root o the chain parenting the mesh should  should create the base deformation by default there is no reason to change it. In the current system you still do 'Skinning' with the paint rigidity options.

**Comment by blurymind** [comment]
@BrundleThwaite  > It is important to take a careful look in the current design - once it has been fixed. See all the features that it has and it's approach to them.
Then make a list of them and write a design document. :)

But I will elaborate on this with another design.
So basically what you are saying is making me wonder if the skeleton tool is used for the bones and the plastic tool is used only for painting weights.

- The skeleton tool's bones (pegs) drive both smooth binded (deforming via a mesh) and riggid body parts. 
- if more than one pegs (skeleton tool bones) have been assigned to a level (body part), toonz creates a mesh from that body part and the skeleton tool's bones drive it's deformation. This distinguishes between smooth binded and riggid binded body parts.
- The plastic tool is then only used by the user to paint smooth weights and edit mesh geometry of smooth binded levels.
- The skeleton tool bones are all exposed in the schematic view (as suggested)
- There is no longer a mesh level - instead the mesh is stored inside the drawing of the body part that is deforming (how do we then reuse a mesh cage on more than one drawings, how do we create a new mesh cage on drawings that need one?)
- We change parent child relationship via an extra 'reroute' node in the schematic view - one where the user can keyframe which output slot to be driven (its more complicated than toon'z current design though)

**Comment by BrundleThwaite** [comment]
Also note that the only thing that I cannot currently already do to set up this kind of system are.

-A represent bones between pegs.
-link to a single mesh. I can use multiple meshes and use plastic purely for deformation on individual parts but still have the ability to parent whatever i choose.
-IK unfortunately I don't thinks scripting is live if it was creating IK would be trivial. (calculate the interior angles using the law of cosines as you know the length of the bones and the hypotenuse and are only working on a single plane).

It is really just another option. the Current Reverse rotation ordering through the hierarchy is really frustrating as the children rotate the parents half the time in anything but the most basic setup.

**Comment by blurymind** [comment]
for this bug report - my request is simply to revert the changes that broke the original design - and well,  thus simply the ability to parent external levels to individual mesh bones - so as to attach non-deforming levels to the moving parts (bones) of a deforming level.

Redesigning the entire bone/mesh workflow is a whole new huge task.
While we're at it - wouldnt it be great if we can also attach multiple levels to a single mesh?  Would be useful for eyes and mouths.

**Comment by blurymind** [comment]
Following my suggestion to make the mesh node slots more intuitive, I have created a little mockup:

- My suggestion is to only show slots that can be connected. In the case of the mesh node - only show bones that exist.
- Instead of their ID, the user sees the name that was given to them bones.
![bonenames](https://cloud.githubusercontent.com/assets/6495061/14235698/b00abaa6-f9fd-11e5-8a97-276626d03d0f.JPG)
Opentoonz already allows you to name bones, just the schematic view shows their ID (those magic numbers) instead of the names that the user has given to them. My suggestion is to show the names:
![mockup-schematic-mesh](https://cloud.githubusercontent.com/assets/6495061/14235828/0550550e-fa01-11e5-9227-c091b15d03c2.png)
Use slots similar to blender's.

**Comment by blurymind** [comment]
I am closing this issue, @shun-iwasawa has fixed the regression and has also implemented a switch button to enable and disable the slots:
![60e48986-fa9b-11e5-8434-0f1dec4b3e45](https://cloud.githubusercontent.com/assets/6495061/14245785/72d25cbc-fa5b-11e5-9a01-138d5bff96f5.png)
pull request that fixes this issue:

https://github.com/opentoonz/opentoonz/commit/49ff76e3d351ffb5638d370503a56fa620223117
