### ISSUE TITLE
Store palette data in .tlv files instead of externally?

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1020]
When you save a Toonz Raster Level, it creates a separate .tpl file that corresponds to the .tlv file.  Could the palette data instead be stored inside the .tlv file?  

Here are some reasons:

-  Given that there's a 1-to-1 correspondence between the .tlv files and .tpl files, it seems to serve no function to have them as separate files. 

-  Less clutter.  It's harder to look through a folder if there are twice as many files. 

-  That's the way the .pli vector files work too, so it would be more consistent. 

-  It seems odd to have the "drawings" folder filled with palette files, given that there's also a "palettes" folder. 

-  You can already save external palettes via "Save Palette As."  (When I first started using OpenToonz, I got very confused by the two "kinds" of external palettes.) 

I'm interested in what everyone thinks of this idea!  ^^

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
