### ISSUE TITLE
Using loop shortcut can get stuck playing

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1024]
To repeat:
1.  Draw a simple level
2.  Use the L shortcut to start looping playback before you ever hit play in the viewer
3.  Hit the loop button in the viewer
4.  Good luck stopping it

**Comment by artisteacher** [comment]
Some of my students have had a similar issue in OS X. Looping may have been enabled, but when they use the controls in the viewer, pause/stop often has no impact.

**Comment by turtletooth** [comment]
Fixed in #1025
