### ISSUE TITLE
Feature request - plastic tool mesh - ability to use more than one drawing for a mesh

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#103]
The plastic tool creates a mesh for a drawing. If you draw another frame in the same level, the platic tool will not deform it properly.

In this feature request I ask of a way to swap frames/drawings within a mesh - have them all use the same mesh and be deformed by it.

**Comment by odysseywestra** [comment]
This needs more information such as mockups and code examples. Right now it seems pretty vague at the moment.

**Comment by blurymind** [comment]
Nevermind, this is not a bug, but rather another case of confusing gui/missing documentation.

The reason my images were distorting was because one of them had translation values. The leason to take from here is to never mesh something with translations on it

**Comment by RodneyBaker** [comment]
Review of old reports

A general workaround for the shortfall of creating plastic meshes that have a cell translated/transformed is to collapse the columns into a subxsheet and then create the mesh.
