### ISSUE TITLE
accuracy and smoothness absent in new version.

### ISSUE THREAD

**Issue by ewolf201** [opentoonz/opentoonz#1032]
so, I've noticed that in the newer versions, accuracy and smoothness are nowhere to be found. but for some reason, some people were able to get this in this version.

**Comment by artisteacher** [comment]
Do you mean that the accuracy and smoothness settings are missing or that they are not working? At least on OS X, accuracy and smoothness settings are available and seem to be working on vector levels. Giving the developers information that is a little more specific would be helpful.
