### ISSUE TITLE
(WIP) Grouping/Ungrouping problem with Merge Levels

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1036]
Hello! I'm new in Opentoonz. I need your advice. Please watch my little video to understand the problem. Look to desription. It's about ungrouping. I would be grateful to hear your opinion in solving this problem! :)

https://www.youtube.com/watch?v=LhT1WH8_8zI

**Comment by mcjadski** [comment]
For some reason your video doesn't seem to work.

**Comment by artisteacher** [comment]
Are you sure you are trying to fill closed shapes? You might want to enable gap check to see where the gaps are  (shift-c). Sometimes a gap is not easily noticeable. Then you can use the tape tool to fill any gaps.

**Comment by beeheemooth** [comment]
I use only two layers: one doing Merge Levels (to fill the drawing) and the other to morph lines. Each new layer after morphing I combine with the first. Perhaps in this case formed groups within groups. Grouped line is impossible to fill, even if they intersect and form a closed shape. Is there a way to do Merge Levels without grouping? How do I ungroup groups within groups quickly and easily? 
(Thanks for answers, and sorry for my English)

**Comment by artisteacher** [comment]
Using your workflow, I've been able to fill merged levels successfully, but most often after using the tape tool to join gaps together. However, the fill sometimes covers the other lines/areas - due to multiple groups placed in the wrong order. I have run into some cells not filling as expected (#1007), and by erasing the overlapping points and using the tape tool to reconnect, have been able to fill them.

In regards to quickly ungrouping, or merging without groups, I don't have any suggestions. I don't know if there is an easy answer there. Good luck!

**Comment by beeheemooth** [comment]
It's easy to create an animation in OpenToonz this way, but it is very difficult to fill every frame! I wanted clean the drawings animation, and fill in another program, but "Remove Vector Overflow" does not work with groups.

Within half an hour of work, I ungroup just one frame (112 drawings). After ungrouping, I easily painted over 90% closed shapes without the use of "Tape Tool". And the "Remove Vector Overflow" worked well this time.

As a result, I spent about an hour on a single frame. 

Drawings animation with "Merge Levels" (7 frames) I've done about 10 -15 minutes.

**Comment by beeheemooth** [comment]
Excuse my joke, please, but I really need this thing :)) Peace! V.
![ungroups](https://cloud.githubusercontent.com/assets/25724133/23085351/f17410aa-f56f-11e6-9555-fa930533cdf7.jpg)

**Comment by falls2lawrence** [comment]
For a second, I thought your joke was real and I got very excited.

**Comment by beeheemooth** [comment]
: 0  You have the same problem?

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
Reopening this so that it can be properly closed with #2862 is merged.
Thanks for your patience @beeheemooth !

**Comment by beeheemooth** [comment]
@RodneyBaker  I am glad that I have not died of old age, and finally waited for a happy end !

**Comment by RodneyBaker** [comment]
Tagging as 'roadmap' as Add 'Merge Levels Without Groups' Command (#2762) is anticipated to be a part of the v1.4 release.

**Comment by RodneyBaker** [comment]
Should be fixed by #2762
