### ISSUE TITLE
Inbetween button's clickable area is offset. 

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1038]
When using the levels panel to make an automatic tween with the in-betweener, the clickable area is offset to the right. Clicking on the left side of the button results in deselecting instead of tweening. Clicking on the right side of the button, and also the black border to the left of the button, brings up the tween pop-up to choose interpolation type as expected. 

I'm not sure if this is Mac specific or not. Thanks so much for all the progress you all are making!

**Comment by turtletooth** [comment]
I've noticed that too.

**Comment by turtletooth** [comment]
Fixed in #1241
