### ISSUE TITLE
Feature Request: Shift-click to select multiple columns or nodes

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1040]
Holding shift as you add to (or take away from) your selection is a standard behavior which would be helpful to have - particularly for those who are new to opentoonz. Clicking and dragging to select multiple columns and/or nodes is fantastic, however using shift is more expected and in some cases more flexible. Currently, in the viewer both selection methods work in an individual cell. Both selection methods are also available for frames/levels in the xsheet. Having both click & drag and shift-click to select columns and nodes would add to continuity. Thanks for all of the great progress!

**Comment by 2dvision** [comment]
Maybe need Ctrl+click to select columns too (like select nodes with Ctrl+click in Schematic).

**Comment by artisteacher** [comment]
And cmd-click for those of us with osx.

**Comment by artisteacher** [comment]
Closing due to #1207.
