### ISSUE TITLE
Selection Tool. (Select All).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1042]
I think it would be a good idea to add to the Selection Tool (in Standart mode) option "Select All" (Ctrl + A), because only in this mode available "Remove Vector Overflow". Sometimes a lot of drawings are in different areas of the canvas, and select them is problematic.

Often the "Remove Vector Overflow" is used for the same style, but in the "same style" is not available "Remove Vector Overflow".

**Comment by artisteacher** [comment]
Having a shortcut would definitely be handy but while you are waiting, you can use the selection tool to box select as much or as little as you want by clicking and dragging.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
