### ISSUE TITLE
endless png errors - remove bad profiles

### ISSUE THREAD

**Issue by keijukainen** [opentoonz/opentoonz#1046]
After compiling on Linux the application displays hundreds of errors in the console each time it's run.  They are all related to bad png profiles.

Error is either:
iCCP: known incorrect sRGB profile
OR
iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50

To fix:
mogrify file.png
OR
pngcrush -ow -rem allb -reduce file.png

[png_errors.txt](https://github.com/opentoonz/opentoonz/files/780943/png_errors.txt)

**Comment by keijukainen** [comment]
attached bash script to fix png errors.
`mv fixpng.txt fixpng.sh`
`chmod +x fixpng.sh`
`./fixpng.sh`
[fixpng.txt](https://github.com/opentoonz/opentoonz/files/781166/fixpng.txt)

**Comment by blackwarthog** [comment]
I still have tons of png warnigs:
```
...
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'Photoshop ICC profile': 0h: PCS illuminant is not D50
...
```
