### ISSUE TITLE
Feature:  Ability to Group Cells in an Xsheet (Investigation)

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1048]
This is a multi-part request that covers one aspect of a larger whole and there should be some discussion on merits and process of how this would best be implemented but on the surface this feature suggests the use of the xsheet can be expanded through use of Named Groups.

Stated simply:  It would be useful to be able to select a group of cells in the xsheet and assign a name to them for later referencing and recall.

Some aspects of this request already exist in OpenToonz and it is likely that some functionaiity simply needs to be exposed to the user.

Basic/proposed process:
1. Select cells/frames in an xsheet
2. Assign a Name to the cells (which now forms their identity as part of a Group).  
3. Recall this Group as necessary (From a listing, History or seach)

Note1 :  I believe the current equivalent of Named Groups on the (drawing) Canvas is "Styles". This suggests the functionality for Named Groups is already well established in OpenToonz and could be further extended in the xsheet for the purpose of identifying groups.
Note2:  Cells/frames should be able to belong to more than one Group.  I believe this is somewhat at odds with current implementation of 'Styles' which only allows one style assignment and Canvas/Level This proposal might suggest that multiple multiple styles might be applied to an object (selection/line/frame/cell, etc.) but only the style exposed most recently on the hierarchy stack would be used.  In best case scenario properties lower in the hierarchy would flow through to the top if no setting exists in the top level.  (ex:  'Group1', named "Castle Approach" is the highest on the hierarchy but no description is entered for the Group.  'Group2', named "Castle Departure" is assigned to the same cells/frames in the xsheet but includes the Description, "Blur sequence in direction of Hero's travel".  The Group would display/inherit the title "Castle Approach' from Group1 and "Blur sequence in direction of Hero's travel' from Group2.  Hopefully that isn't too confusing.

Exploratory Questions:
Can OpenToonz users currently name the Groups they create on the Canvas?
I don't see any means to name Canvas/Level Groups although the icon in History does suggest there may be a means to crack open the Group to obtain higher level of fidelity.  OpenToonz obviously maintains a listing of Groups internally and has a reference pointer to them but that information does not appear to be currently exposed to users so it cannot be explicitly named/edited by the user.

An underlying premise of this request might be to extend the use of "Styles" to frames in the Xsheet.  This will likely seem odd at the outset because the styles of the Canvan (brushes, colors, etc) wouldn't be applicable to cells/frames but properties such as a Name or description certainly would.  Basic color is an exception to this because use of different colors in the xsheet to identify groupings would in fact be quite useful.  Example:  All frames with a specific character might be named "Hero" and given a basic color (i.e. Blue). A second grouping containing a subsection of those frames might be named "Young Hero" and  another named "Defeated Hero" and yet another "Triumphant Hero".  

Aside for the purpose of discussion:  It is presumed the frames assigned to multiple groups would display only the primary color and not blend colors from multiple groups.  That might be an interesting approach and even useful but is beyond the purpose or scope of this request.  Ideally, the color displayed would be that of the most recently created/position in the hierarchy.  

Longer tail of development/use:
- Establishment and Editing of Groups should be recorded in History such that Users can review changes and even revert to earlier forms if desired.
- A lock would be ideal to prevent unintentional changes from occurring.  This lock could be manually unlocked by the user to effect changes and reset to 'locked' if desired.

Restated/anticipated process:
User selects a sequence of frames (any frames) in the Xsheet
User Right Clicks and Selects 'Group' option (similar workflow to Grouping on the Canvas).
User names the Group 'Run Cycle' (in a properties panel?) and opts initially not to provide a description.
User determines to edit Description of 'Run Cycle' Group based on input received from (animation) director and changes Description to "Blur end of cycle" and "Reuse in Scene 57 with 2X Blur".
User selects 'Run Cycle', copies/pastes into new column (which automatically creates a RunCycle1 group) and renames that group 'Run Cycle Slow Motion'.  User then proceeds to artistically alter the frames to achieve effect of slow motion.  When done, user checks to make sure all frames required are still part of the 'Run Cycle Slow Motion' group, adjusts properties/descriptions/status as necessary and saves their work.

Thanks for your patience with me.
OpenToonz is already outstanding without this feature and I have no reasonable expectation of its implementation but I have convinced myself the general direction described is worth considering.  

Keep up the great work!

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
