### ISSUE TITLE
Feature Request: Convert to Frame By Frame

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#1052]
A feature that's available and handy in animate cc and toonboom harmony is the ability to convert deformed frames (in opentoonz it would be the plastic tool) to a sequence of frame by frame drawings.
I'm unsure how feasible this is to implement in opentoonz but it would be quite handy and would be a pseudo solution to the "mac plastic tool glitchy rendering" problem.

Thanks for all your amazing work. I love this program.

**Comment by artisteacher** [comment]
That would be really helpful.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
