### ISSUE TITLE
rendering issues with plastic tool on linux

### ISSUE THREAD

**Issue by hvfrancesco** [opentoonz/opentoonz#1055]
I have serious rendering problems with plastic tool on linux. Things display perfectly in the working area, but I get superimposed multiple frames and background artifacts both on preview and on rendering.
I tested with all of available rendering formats, but the result is always the same. I've tried on Ubuntu 14.04 and 16.04, 64 bit. Parts animated in other ways render perfectly, I seem only to have this issue with plastic tool meshes and skeleton.
![test 0013](https://cloud.githubusercontent.com/assets/614123/23177055/c50a2d44-f865-11e6-87a3-f32193cf3a21.png)

**Comment by falls2lawrence** [comment]
There is an identical issue for rendering on macs. Currently, I create my animations on mac and then render via a virtual machine running windows 10. It gets the job done.

https://www.microsoft.com/en-us/software-download/windows10ISO

http://www.oracle.com/technetwork/server-storage/virtualbox/overview/index.html

**Comment by ideasman42** [comment]
@hvfrancesco please post the source-files for a simple animation that causes the problem.

**Comment by hvfrancesco** [comment]
here is a super simple animation using plastic tool and a frame rendered on linux showing the problem
[test.zip](https://github.com/opentoonz/opentoonz/files/793318/test.zip)
![test_2 0012](https://cloud.githubusercontent.com/assets/614123/23211256/7c55038e-f901-11e6-9b9e-aabf697a9f6d.png)

**Comment by ideasman42** [comment]
@hvfrancesco with your test file the image didnt load for me.

But I made my own simple test to redo this error on Linux with NVidia (proprietary drivers) and wasn't able to reproduce the bug.

Rendering the output works as expected with no ghosting.

Could someone confirm if this bug is limited to certain OpenGL drivers/hardware? 
@hvfrancesco what graphics card/drivers do you have?

**Comment by hvfrancesco** [comment]
On the Ubuntu 14.04 system I have a GeForce GT 620 with NVIDIA 340.96 driver, but I have exactly the same behavior on a laptop Ubuntu 16.04 with intel integrated GPU too

**Comment by hvfrancesco** [comment]
UPDATE: I have upgraded NVIDIA driver to version 367.57, and the ghosting problem is gone, so it seems is really an issue limited to some OpenGL configurations

**Comment by artisteacher** [comment]
With OS X we can't update the drivers manually, and even with the latest updates (which are rarely feasible  in a school setting), there are still issues with the plastic render. While in the latest update of OS X, the plastic render is more workable, it also means constantly crashing audio...

On a hopefully related note, in Console, I'm getting a coreanimation warning about a deleted thread with uncommitted CATransaction that repeats with each action while building/animating the plastic skeleton and when previewing a plastic level. I know coreanimation is Mac specific, but it's supposed to be built on OpenGL, so perhaps this is relevant.

**Comment by ideasman42** [comment]
OSX is known to have quite bad OpenGL support and are trying to push their own technology

- http://www.geeks3d.com/20150508/os-x-not-a-serious-3d-graphics-development-platform
- https://www.blendernation.com/2015/05/04/an-open-letter-to-tim-cook/

It seems they aren't that serious about OpenGL support, so there is a limit to how easily their bugs can be worked around.
Having said this, I suspect OpenToonz is missing some `glClear` call, its just not something I can look into unless I can redo the errror.

**Comment by hvfrancesco** [comment]
Do you have an idea of which source files could we look into? I still have the issue on my Intel GPU laptop and could use it to work out the problem, but I started looking into source and got almost immediately lost.

**Comment by nzinov** [comment]
I have the same problem running Arch Linux with Intel integrated graphics.

**Comment by artisteacher** [comment]
The latest nightly build finally has resolved the plastic background issue for OS X! Does this build resolve the plastic issue on Linux too?

**Comment by morevnaproject** [comment]
Here is the testing build, which includes fix #1726 by @shun-iwasawa - https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-18.01.24-linux64-466fc.appimage

For my hardware (Intel video card) the problem got fixed. Please test.
