### ISSUE TITLE
Strange pressure behavior when drawing with mouse on vector layer

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1058]
(Tested on **Windows 7**, OpenToonz 1.1.2 nightly build.  None of this seems to happen on Mac.)  

When I draw with the mouse on a Toonz Vector Layer when Pressure is checked, three strange behaviors result:  

- [x] The beginning of the stroke is covered up by this circle:  

![mouse_pressure_01](https://cloud.githubusercontent.com/assets/25377429/23243603/8fb3b7ec-f945-11e6-91d6-a7604ec09f03.jpg)

When I let go of the mouse button, the circle goes away.  However, this can be quite obnoxious to deal with if you're more zoomed in on the canvas, as it obscures your view:  

![mouse_pressure_02](https://cloud.githubusercontent.com/assets/25377429/23243639/baa4f79a-f945-11e6-9991-22a9b66df86b.jpg)

The size of the circle doesn't seem to be based on the Max or Min brush size.  The circle is only visible if the brush size is thinner than the blob shapes.  

Also, once you draw a mark with a pen tablet and then go back to using the mouse, this glitch goes away.  

---

- [x]   Sometimes, when I draw fast strokes, I get these teardrop shapes attached to the beginning.  These **do** remain after letting go of the mouse:  

![mouse_pressure_03](https://cloud.githubusercontent.com/assets/25377429/23243659/e61048a8-f945-11e6-983d-fe0988361056.jpg)

Again, the shapes only appear if the brush size is thinner than the blob shapes, and again, once you draw a mark with a pen tablet and then go back to using the mouse, this glitch goes away.  

---

- [ ]   **Before** drawing a stroke with a tablet, the mouse draws with the **Max** brush thickness.  **After** drawing a stroke with a tablet, the mouse draws with the **Min** brush thickness.   

For consistency, it should always use the **Max** brush thickness, because that's what it does when pressure is turned off, and that's what it does on a Mac (whether or not pressure is turned on or a tablet has been used.)  

EDIT:  This last glitch also occurs on Toonz Raster Levels.

**Comment by artisteacher** [comment]
I've had the same issues with OS X 10.11.6 and 10.12.3

**Comment by artisteacher** [comment]
Here's a gif that shows the glitch in action - it really can be hard to see what you are doing. This is on OS X. 
![cursor](https://cloud.githubusercontent.com/assets/21159116/26476348/19cd7ee8-418c-11e7-8961-d48ca1f12fe1.gif)

**Comment by artisteacher** [comment]
This is still an issue after the mac tablet fix. I'm wondering if it has anything to do with when the tablet is connected or disconnected.

**Comment by artisteacher** [comment]
Just ran into this again with 1.2.

**Comment by RodneyBaker** [comment]
Aside from the larger issue of detecting whether a finger or a mouse is being used I wonder if a viable approach to a solution is to programatically turn off the pressure flag when changing from touch to mouse?

I can only speak from the windows perspective that the end point dot goes away (for mouse drawing) when the pressure option is off.

**Comment by manongjohn** [comment]
Actually, i think its possible that I found and fixed this without realizing it with PR #2005.

I ran into this issue yesterday while looking at the code for something else I was looking into.  I had noticed that there was special code for Toonz Vector/Raster brushes that dealt with an initial click and max pressure (a mouse is considered max pressure when used) and use the min brush setting for size.

For Toonz Vector it was using the wrong value. It was using min brush setting for Toonz Raster Brush incorrectly. So if your Toonz Raster Brush setting was large to begin with, it would appear when you click but then disappear after you stopped drawing.

If this is still an issue in your current version, try downloading the Appveyor Artifact for the PR I mentioned and see if it fixes it.

**Comment by manongjohn** [comment]
Oh.  I think I fixed just the 1st issue.  Not sure about the other 2 issues.  I'll see if I can reproduce and if my fix resolves it.  If not, i might be able to determine what's wrong.

**Comment by artisteacher** [comment]
@RodneyBaker, yes turning pressure off does fix this issue. I don’t think the larger problem is the detection of a finger vs mouse - they are currently treated the same. It’s really about the detection of a tablet vs. a mouse. 

@manongjohn - thanks for taking a look!

**Comment by RodneyBaker** [comment]
@manongjohn I can confirm that I'm not seeing any of the issues via your AppVeyor release.  Of course I was barely seening anything before.   

This could very well be a candidate for consideration in resolving the Mac issue but someone else will have to press forward with that.

**Comment by manongjohn** [comment]
I confirmed my fix corrected number 2 but in the opposite way.  It starts now with min point of Toonz Vector Brush if pressure is checked ON.

The stroke starts small and quickly enlarged to max brush size. 

Not 100% sure why the logic was added to begin with.  We don't do it for regular Raster brush.

**Comment by manongjohn** [comment]
I can't seem to reproduce the 3rd issue using the official release like I can reproduce the other 2.   It is likely there is something else playing into that issue that I am not aware of. 

My PR fixed the 1st 2 issues as far as I am concerned.

**Comment by RodneyBaker** [comment]
@mcjadski Can you confirm this issue is still active using current releases (v1.3 or newer)?
From cursory testing there should no longer be any issue.

**Comment by RodneyBaker** [comment]
Closing as reported resolved by multiple users.
@mcjadski As this is your report, please let us know if you are still experiencing any issues.
