### ISSUE TITLE
InknPaint Workflow Request (Background Color)

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#1061]
Currently we use Clip Studio Paint or Retas for InknPaint, what I find is that the painters I work with prefer to paint on a **neutral gray BG** or **off-white BG** instead of a **pure white BG**.

Navigating frames with the XSheet allows us to disable Camera BG Color using ComboViewer, but navigating frames using the FilmStrip causes a permanent white BG to be displayed.

I'd just like to request adding the ability to either turn the white BG off for FilmStrip or allow the user to pick a color in preferences, if possible.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
