### ISSUE TITLE
Bug: Animation mode shortcut crashes Opentoonz

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1065]
If you use the shortcut key for animation mode when you have the plastic tool selected OpenToonz will crash.

![crash](https://cloud.githubusercontent.com/assets/18170954/23375366/d3b8c9ac-fd30-11e6-9ad3-263c856f328a.gif)

**Comment by turtletooth** [comment]
I found that hitting the shortcut on any tool after the plastic tool has been activated once brings down OT

**Comment by turtletooth** [comment]
A fix for this is changing line 648 on plastictool.cpp,

`m_mode.setId("PlasticSkeletonMode");`

but this disables the shortcuts for mode switching to work at all on the plastic tool (which is better than it works now), but it would be nice to see the shortcuts work.
