### ISSUE TITLE
Feature Request: FX improved area extraction

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1067]
When you use the palette filter node to extract the area colour it will extract the fill up to the center of the line. It would be very useful (with both rigging and effects) to extract only the area up to the edge of the line not the center. While you  can do this to some degree using masks you often end up with with issues at the join of the two colours.

![Uploading Boundary.png…]()

In Toonboom Harmony the node that does this is called the autopatch node.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
