### ISSUE TITLE
Feature request: FX Realtime display of Pallet Filter, Mask, and Over Nodes.

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1068]
While I would like to have real time display of all FX nodes the masking and palette filter nodes can be for cutout rigging and realtime display of those node will make the FX and animation easier to use in conjunction.

For example here is  a joint in the viewport:

![realtime](https://cloud.githubusercontent.com/assets/18170954/23377407/a052a2d8-fd38-11e6-98bb-0acb0f1a9963.png)

and here is the rendered view:

![render](https://cloud.githubusercontent.com/assets/18170954/23377379/8945ebae-fd38-11e6-863a-102d1ce03251.png)

Having realtime display would make it far easier to use this type of rig for animation.

**Comment by shun-iwasawa** [comment]
Since the Matte Fx can be inserted to anywhere in the Fx Schematic, IMO it is difficult to retrieve and render only the Matte Fxs.

Is it not enough to keep the preview button turned on while working?

**Comment by BrundleThwaite** [comment]
This request Is one that I did think twice about posting and it is one that I did not think would happen. Working with the preview render is okay (there is a delay in updating) but not the ideal. Most of my professional work has been working on cutout in tooboom where the realtime display of these types of effects does make a big difference (not all nodes in toonboom are realtime).  

The reason for stating those nodes is that they would be the most practical for rigging. Particles would be the least important (for me) as they have caching.

I did not expect this kind of thing to be worked on because realtime display of effects would require a lot of work on a lot of the software. I almost did not put down the request because of this but I decided to in any case because you never know I someone Is interested in this or if someone wants a pet project.

**Comment by falls2lawrence** [comment]
It would be incredible to have this realtime preview of fx. I also rig this way (also toonboom) on multiple parts of a character and since, on a mac, the plastic tool "freaks out" in previews, once the plastic tool is added to a scene, working with any fx becomes something of a guessing game.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
