### ISSUE TITLE
Feature Request: UI, Dropdown menus awkward for common tools.

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1069]
OpenToonz uses a lot of dropdown menus for very basic an commonly used tools. I certain cases this leads to a awkward workflow especially for beginners. To add to that a lot of these options can be simplified by using a toggle. 

1 - SRT These should really be buttons

![srt](https://cloud.githubusercontent.com/assets/18170954/23378575/4c939f5e-fd3c-11e6-86c4-b98150cf8f78.png)

2 -The Plastic and skeleton tools.

with these tools you could have one option to Toggle rigging or animation. And the the other buttons would only have and effect based off this mode.

For example the skeleton tool would only require 2 buttons. One to toggle animation and one to toggle IK on or off (which is only active if animation is on).

![2 toggle buttons](https://cloud.githubusercontent.com/assets/18170954/23378597/61f6c38a-fd3c-11e6-8987-4d88e34da007.png)

With the plastic tool you would have one button to toggle between rigging and animation and 3 to specify the type of rigging.

![4 buttons](https://cloud.githubusercontent.com/assets/18170954/23378591/5c8d01de-fd3c-11e6-8016-c5c89ca4135c.png)

another option would be a universal button to switch between rigging and animation which would affect all the tools that can do both.

it could also be useful to outline the viewport with a colour to show if you are using a tool for rigging.

![universal button](https://cloud.githubusercontent.com/assets/18170954/23378585/56380e5a-fd3c-11e6-8f0c-b4e398ae673d.png)

**Comment by artisteacher** [comment]
Buttons and toggle modes would probably be more helpful for anyone using a tablet.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
