### ISSUE TITLE
New Tablet Bug: Scribble stuck in viewer when brush is active

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1077]
I've run into a new issue with a wacom Bamboo tablet on OS X 10.11.6 with the nightly build from 2/28. At the moment I am unable to reproduce this on demand but it has happened multiple times. 

After drawing on a new level and undoing to remove the drawing, the pen randomly scribbles (which I know is #756) but then the scribble cannot be undone or erased. It does not display in the level panel or xsheet. The scribble is linked to the viewer but only when the brush tool is active. Moving the cursor outside of the viewer makes the scribble disappear. Moving the cursor back to the viewer returns the scribble. Changing to a different tool hides the scribble. Returning to the brush tool makes the scribble appear again. Once you draw with the brush, the scribble permanently goes away. I'm attaching an animated gif that shows the issue. At the end, the cursor also moves around randomly even though the pen was completely still.

![tablet glitch](https://cloud.githubusercontent.com/assets/21159116/23461468/0bd685b8-fe58-11e6-8ff4-0364f7ba3581.gif)

**Comment by turtletooth** [comment]
I think I've seen that on Windows too.

**Comment by artisteacher** [comment]
I don’t think the scribble part is an issue any longer with the tablet changes in OS X. However a similar behavior can occur with an interrupted stroke (due to auto-save or accidental button press).
