### ISSUE TITLE
Color model doesn't work in most recent nightbuild

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1080]
Rigth clicking on the window doesn't show the options to load a color model. I've found no other button in the system to do so. The feature is basically inactive right now.

**Comment by artisteacher** [comment]
Do you have a level selected? The color model seems to be working fine in OSX.

**Comment by agatre** [comment]
....I didn't. God. I wish I could delete this issue. I'm still really messy with the management of this program.
