### ISSUE TITLE
Full screen mode stops working correctly after the first use

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1081]
Full screen mode works the first time I use the shortcut or the visualization pop-up menu. Exiting full screen mode with the shortcut only works after a tool has been used. Returning to full screen mode with the shortcut only works after using a tool. Using the pop-up menu to leave or return to full screen works without using a tool.  

After entering and leaving full screen mode the first time in a room, returning to full screen mode works incorrectly. The workspace becomes a floating window instead of going full screen. The window can be maximized which then enters true full screen mode. The window can also be closed completely - which results in a viewer with no workspace - obviously problematic. Switching rooms returns full screen mode to the expected behavior, but only for the first use. Changing scenes and projects has no impact. 

I'm using OS X 10.12.3 and the latest nightly build. I know the Harlequin 7.1 manual says that this is a Windows only feature, but since it works the first time it ought to be possible to make it completely functional. Thanks for all the great progress!

**Comment by artisteacher** [comment]
Right now, fullscreen mode (like normal fullscreen) causes an immediate crash in OS X 10.11.6 & 10.12.5.

**Comment by artisteacher** [comment]
This is working properly now! Thanks @turtletooth, @shun-iwasawa & @blackwarthog!

**Comment by turtletooth** [comment]
Great!
