### ISSUE TITLE
Apply Configure Shortcuts crashes Open Toonz 1.1.2

### ISSUE THREAD

**Issue by bebinalpha** [opentoonz/opentoonz#1082]
I open the configure shortcuts window and change a shortcut key and when i hit apply Open Toonz crashes. I was unable to save any shortcut keys. Windows 10, 32 GB Ram , wacom bamboo

**Comment by cartoonMike** [comment]
Had the same thing happen, only when saving a Custom Shortcut file was I able to avoid the crash, but then OpenToons didn't acknowledge any keyboard input after that. Had to delete all of OpenToons 1.1.2 and reinstall to get keyboard inputs working again. MacOS 10.12.3, 16GB RAM, Yinova tablet.

**Comment by leolucca518** [comment]
Me too, i tried to change from opentoolz shortcuts to animate ones and program crashes after a few seconds

**Comment by turtletooth** [comment]
This has been fixed in the nightly builds.
