### ISSUE TITLE
Color model glitch in OS Sierra with night build

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1083]
Sometimes, after selecting "overwrite palette" or other option, the program crashes. Curiously, trying again with the same png file causes no trouble. This seems to be random.

When attempted to move color model window to another location, it displayed images of the program itself when nothing's loaded.

[http://s989.photobucket.com/user/NI-SSiRA/media/Problem%20color%20model_zpsvhy8mkqk.png.html](url)
After moving, the preview of the animation disappeared. Switched to other window and everything looked ok, but switching back to palette made it all appear blank. 

I tried restarting and just had the color model window expanded over all the palette window, so I reinserted it carefully to avoid another crash. Even though it's not happened again, it might be good to see what's causing this unexpected glitch.

**Comment by artisteacher** [comment]
@agatre have you continued to have this crash in later releases?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@agatre Please let us know if you experience related problems.
