### ISSUE TITLE
Inconsistent terminology between vector and toonz raster brushes

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1084]
The vector and toonz raster levels both have line stabilization. In vector levels it is termed accuracy. Vector levels also have a smooth setting which relates to line thickness. However in the toonz raster level, the line stabilization is called smooth. Unless I am misunderstanding something, shouldn't this be termed accuracy as well? Having two different purposes for the smooth setting is confusing to new learners.

**Comment by turtletooth** [comment]
Actually accuracy is how many vector control points are created when drawing to represent the stroke that was made.  The lower the accuracy, the fewer control points (but the less likely to lag the system) and the greater likelihood that your drawing won't look exactly like you drew it.

Smoothing on both tools is just that.  It delays the stroke drawing and adds smoothing to the line.

**Comment by artisteacher** [comment]
Thanks for the explanation. Sounds like this is not actually an issue.

**Comment by RodneyBaker** [comment]
I'll note for the record that vectors exported/saved out of OpenToonz do
appear to have an excessive number of Control Points.  (I'm considering SVG
export... although that might not be the optimal testing format).

This might be something we can investigate in a forum topic and then based
on what we discover put in a Pull Request.
