### ISSUE TITLE
Auto stretch replaced frame in middle of existing time stretched frame

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1085]
Currently if you have a frame time stretched in the Xsheet and you double-click and edit a frame in the middle to replace it with a new one (left image), it only replaces that 1 cell, effectively breaking it up into 2 parts with an odd frame in the middle (middle image).  It would be nice if the newly replaced frame, added in this fashion, would be automatically time stretched to replace the remainder of the old time stretched frame (right image)

![autoextendframe](https://cloud.githubusercontent.com/assets/19245851/23645864/4b5be632-02dc-11e7-8b2e-7c2ecf600948.png)

NOTE: I just realized you can achieve this effect by selecting the cells you want to replace and then double-clicking either the 1st or last cell while holding the shift key.  After editing the cell, the new frame automatically replaces all the selected one, but this just seems like a cumbersome way to do it.

**Comment by artisteacher** [comment]
You can use the shortcuts Q and W to cycle through the drawings in the level for a similar effect. Select the range of cells you want to replace and press Q (to go backward) or W (to go forward) to replace the range with a different, existing drawing. If you want to add an empty frame, add a new frame in the level strip first.

**Comment by turtletooth** [comment]
Also, clicking alt + q or w will change all consecutive images also.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
