### ISSUE TITLE
Horizontal guides not always removable

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1087]
In fullscreen, horizontal guides are not removable from rooms where the viewer or combo viewer are placed on the very left. This also happens in some circumstances out of fullscreen, such as when the left side of the viewer/comboviewer begins at the left edge of the computer screen - without the room divider visible.

**Comment by RodneyBaker** [comment]
Curious is this is still an issue with the latest updates especially #2503.

**Comment by artisteacher** [comment]
Once #2503 is merged, it will definitely help with this issue. The dragging behavior to remove guides will still have problems if the viewer is at the edge of the screen.

**Comment by artisteacher** [comment]
I'm closing since right-clicking to remove does work now.
