### ISSUE TITLE
Selective option for vector brush

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1089]
Any chance of getting the "selective" option for the brush for vector levels like it is in raster levels?

Seems this could be doable since the selective option is available for the eraser in both vector and raster levels.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
