### ISSUE TITLE
Installation bugs - Soapbubble_FX as an example.

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1091]
The following files are not updated during the installation during installation leaving the soap bubble FX to lack the updated menu options.
  
stuff/config/current.txt 
stuff/profiles/layouts/fxs/STD_iwa_SoapBubbleFx.xml 
 When I deleted them manually the installation worked properly. This is not the only time this has happened.

A more efficient system of updating these type of files might be a good idea. 

Once again thanks to shun-iwasawa for the effect, the updates to it are great.

**Comment by shun-iwasawa** [comment]
@BrundleThwaite Added an option to the installer for overwriting all the default settings in the Stuff folder. It will make it easy to update-install the software, but please be careful if you are using customized non-personal data such as reslist.txt or style data. You should keep backup or rename in advance for such kind of data.
