### ISSUE TITLE
Geometric Tool:  End Polyline by pressing Enter

### ISSUE THREAD

**Issue by mcjadski** [opentoonz/opentoonz#1094]
Right now, when using the Geometric Tool's Polyline, you have to double-click to make the line stop.  This is somewhat inconvenient, as double clicking requires you to make the line longer.  

I think it would be more convenient if you could end the polyline by pressing the Enter key.

**Comment by artisteacher** [comment]
Enter to end the polyline would definitely be an expected behavior for anyone familiar with graphics programs.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by mcjadski** [comment]
I would personally classify this as a needed fix.  Without it, the Polyline is difficult to use, and it would be a very quick fix.
