### ISSUE TITLE
OpenToonz crashes when playing audio in level column (on Ubuntu 16.10)

### ISSUE THREAD

**Issue by legocef01** [opentoonz/opentoonz#1097]
Hi everyone,

I loaded an audio file (mono .wav or .aiff file) in opentoonz (appImage build of march 9 2017 - even the one from getdeb) and the program crashes when I read it on a level. 

I'm on ubuntu 16.10

what is the problem?

**Comment by artisteacher** [comment]
Can you play and scrub through the viewer without crashing? I can't play or scrub without crashing on OS X 10.12.3. Previewing audio in the top of the xsheet column works without issue. Just wondering if this is related to #731 or something different.

**Comment by legocef01** [comment]
It's the same for me. Play and scrub audio on level column crashes. But, when previewing audio on top of the level column, there is no problem.

**Comment by chrismedrela** [comment]
I've exactly the same issue on my Ubuntu 16.10: playing and scrubing results in seg faults while previewing audio works.

**Comment by chrismedrela** [comment]
Could you provide me any hints where the bug my lie and any advices how to debug/fix this issue?

**Comment by artisteacher** [comment]
OS X Sierra has the same problem. I've found a few different error notifications in console when scrubbing/playing audio which are posted under #978 but I'm not sure how helpful that is.

**Comment by jpritikin** [comment]
CC @morevnaproject @blackwarthog

**Comment by clawdelle** [comment]
Hi, I have a problem with .wav . Scrubbing or render, I get a segmentation failure. Ubuntu Mate 1.18.0. Tested 1.1.3.9, 1.2.0.1, 1.2.0.2. On different laptops. What can I do ?

detlef@Yoga2:~/Dokumente$ ./OpenToonz-1.2.0.2-morevna-18.01.07-linux64-04bd8.appimage
update stuff
plugin search directory:/home/detlef/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/detlef/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QLayout: Attempting to add QLayout “” to StyleEditor “”, which already has a layout
QLayout: Attempting to add QLayout “” to StyleEditor “”, which already has a layout
QLayout: Attempting to add QLayout “” to StyleEditor “”, which already has a layout
QLayout: Attempting to add QLayout “” to StyleEditor “”, which already has a layout
plugin search directory:/home/detlef/.config/OpenToonz/stuff/plugins
walkDictionary: /home/detlef/.config/OpenToonz/stuff/plugins [dry]
QLayout: Attempting to add QLayout “” to StyleEditor “”, which already has a layout
QLayout: Attempting to add QLayout “” to StyleEditor “”, which already has a layout
PaletteViewerGUI::PaletteTabBar(0x4d06050, name=”PaletteTabBar”) does not have a property named “BottomAboveLineColor”
PaletteViewerGUI::PaletteTabBar(0x4d06050, name=”PaletteTabBar”) does not have a property named “BottomBelowLineColor”
PaletteViewerGUI::PaletteTabBar(0x4c921b0, name=”PaletteTabBar”) does not have a property named “BottomAboveLineColor”
PaletteViewerGUI::PaletteTabBar(0x4c921b0, name=”PaletteTabBar”) does not have a property named “BottomBelowLineColor”
PaletteViewerGUI::PaletteTabBar(0x46ca930, name=”PaletteTabBar”) does not have a property named “BottomAboveLineColor”
PaletteViewerGUI::PaletteTabBar(0x46ca930, name=”PaletteTabBar”) does not have a property named “BottomBelowLineColor”
DVGui::TabBar(0x4cb3630, name=”StyleEditorTabBar”) does not have a property named “BottomAboveLineColor”
DVGui::TabBar(0x4cb3630, name=”StyleEditorTabBar”) does not have a property named “BottomBelowLineColor”
PaletteViewerGUI::PaletteTabBar(0x47b8030, name=”PaletteTabBar”) does not have a property named “BottomAboveLineColor”
PaletteViewerGUI::PaletteTabBar(0x47b8030, name=”PaletteTabBar”) does not have a property named “BottomBelowLineColor”
DVGui::TabBar(0x4967490, name=”StyleEditorTabBar”) does not have a property named “BottomAboveLineColor”
DVGui::TabBar(0x4967490, name=”StyleEditorTabBar”) does not have a property named “BottomBelowLineColor”
PaletteViewerGUI::PaletteTabBar(0x493b5b0, name=”PaletteTabBar”) does not have a property named “BottomAboveLineColor”
PaletteViewerGUI::PaletteTabBar(0x493b5b0, name=”PaletteTabBar”) does not have a property named “BottomBelowLineColor”
DVGui::TabBar(0x4690040, name=”StyleEditorTabBar”) does not have a property named “BottomAboveLineColor”
DVGui::TabBar(0x4690040, name=”StyleEditorTabBar”) does not have a property named “BottomBelowLineColor”
/build/packet/linux-64/opentoonz-testing/build/opentoonz/toonz/sources/toonz/iocommand.cpp:loadScene Progressing:
/build/packet/linux-64/opentoonz-testing/build/opentoonz/toonz/sources/toonz/iocommand.cpp:loadScene end load:
/build/packet/linux-64/opentoonz-testing/build/opentoonz/toonz/sources/toonz/iocommand.cpp:loadScene loadScene() completed :
create context:0x7ff994001d70 [thread:0xa4fa4700]
QString::arg: Argument missing: Always do this action., /home/detlef/Audio/cos.wav
QSettings::setValue: Empty key passed
QSettings::setValue: Empty key passed
QXcbConnection: XCB error: 3 (BadWindow), sequence: 4415, resource id: 9177300, major code: 40 (TranslateCoords), minor code: 0
Segmentation fault (core dumped)
detlef@Yoga2:~/Dokumente$

**Comment by morevnaproject** [comment]
Hello everyone! Unfortunately, at this moment audio playback doesn't works on Linux.

**Comment by turtletooth** [comment]
@morevnaproject If you or @blackwarthog can use the audio fix I did for mac, I think that would work on linux too.

**Comment by morevnaproject** [comment]
@turtletooth Thank you for the hint! Do you mean this one? - #1302 
I thought it is already in master...

**Comment by turtletooth** [comment]
Yes - but it was made as a mac only fix.

**Comment by turtletooth** [comment]
You could probably easy change the "if mac" lines to "if mac or linux"

**Comment by morevnaproject** [comment]
Ah, my bad, I didn't noticed that. ^__^"
Thank you for the hint - will try this! ^__^

**Comment by legocef01** [comment]
Ha! Is it fixed. 
We are impatiently waiting for the release with this fix!!

**Comment by morevnaproject** [comment]
Hello! I have  applied fix for Linux. For me it works well when I compile from source.
But when I build Appimage it doesn't play sound (just a few scratches heard). Though it doesn't crash. Apparently we have to tweak AppImage configuration - investigating that right now.

Until then you can test the appimage on your system, maybe it would work better for you? - 
https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-18.01.24-linux64-466fc.appimage

Feedback is appreciated! ^__^

**Comment by morevnaproject** [comment]
Okay, the fix is here! @blackwarthog fixed an appimage and also rewrote some part of code to achieve better playback quality. Please test this build - https://dev.icystar.com/downloads/OpenToonz-1.2.0.3-morevna-18.01.26-linux64-9a70a.appimage

**Comment by legocef01** [comment]
Hi!

I've tested the Appimage given above. Yes! Now I can scrub Audio files. But now I have problems with the play event. When I load the audio on level, if I click on the audio icon the first time, the audio playback work fine. But if I click to stop and click a second time to play again, nothing happen, there is no sound. 
Things are coming. scrub is now perfect, there is no crash at all! But there is just this problem of clicking on audio icon for playback.

Thanks for your work

**Comment by legocef01** [comment]
Hi!

I've tested the Appimage given above. Yes! Now I can scrub Audio files. But now I have problems with the play event. When I load the audio on level, if I click on the audio icon the first time, the audio playback work fine. But if I click to stop and click a second time to play again, nothing happen, there is no sound. 
Things are coming. scrub is now perfect, there is no crash at all! But there is just this problem of clicking on audio icon for playback.

Thanks for your work

**Comment by legocef01** [comment]
Please can I know if you will put the fix (after perhaps solving the little issue above) in the next release?

**Comment by jpturcotte** [comment]
@morevnaproject & @blackwarthog Does PR #1749 take care of the issue @legocef01 posted 2 messages above?

**Comment by morevnaproject** [comment]
@jpturcotte The PR #1749 does not include the full fix. I have made a PR for a final fix, which provides smooth audio playback - #2244.
