### ISSUE TITLE
feature request: Select closest control point

### ISSUE THREAD

**Issue by dkwroot** [opentoonz/opentoonz#1098]
The control point editor tool should have an option to always select the closest control point when it is used. At the moment, the user has to be very precise with where they click to grab control points which makes working with vectors very difficult.

The user will often click on a control handle, but miss it just slightly causing the program to deselect the curve. This can be very frustrating and time consuming when working on a large amount of vector artwork.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
