### ISSUE TITLE
BUG: Style editor >'Textures' and 'Custom' and 'Vector Brush' - opentoonz is not loading them

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#110]
Textures are definitely there. They exist in ..\openToonzStuff\projects\library\textures

Same for the other resources.

Opentoonz however does not want to load them.
As a result we can not use any. :)

![missing brushes](https://cloud.githubusercontent.com/assets/6495061/14142814/caab2dfe-f67f-11e5-8d3f-3309ea2309be.JPG)

So these tabs are broken:
- 'Textures'
- 'Custom' 
- 'Vector Brush

The style editor can not load any of the resources it's supposed to load in them, even though the files are in the right folders. The user can not use any of the features that they bring. Therefor at least 70% of the brush styling functionality does not work.

**Comment by BrundleThwaite** [comment]
The registry is pointing to the wrong folder in windows. It should be pointing to the project root folder.
here is a video i made it shows a workaround but it should probably be fixed in the registry:

https://vimeo.com/160643981

**Comment by blurymind** [comment]
@BrundleThwaite thank you for this workaround. This is possibly a mistake in the compiler :)
Let's hope it gets fixed by someone with more knowhow

**Comment by shun-iwasawa** [comment]
Fix merged in v1.0.2
