### ISSUE TITLE
Klick the spacebar - oh, no...

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1100]
Why fast releasing or klicking the space bar key does not turn off the "Hand tool"?
When I draw, I constantly need to switch from "Hand Tool" to "Brush Tool" (or another tool) - this is very distracting.
 Is it really important to TURN ON the "hand" tool by clicking the space bar?
 If I want to enjoy the "hand" tool, I'll just press the key "H"! 
I think so: The spacebar is pressed - "Hand Tool", the spacebar is released - switch to last used tool - it is obvious.
Same problem with Zoom Tool and Rotate Tool when them used with spacebar (Shift+Space, Ctrl+Space).
Help me!

**Comment by turtletooth** [comment]
I understand your frustration.  Spacebar is the keyboard shortcut for the hand tool, so fast pressing it triggers the shortcut.  The same is true for the other tools, press and hold enables it temporarily while a fast press switches to the tool.

**Comment by beeheemooth** [comment]
turtletooth,
 look at Krita, or ClipStudioPaint. The spacebar does not start the tool, just switches from tool to hand, and it does not matter, click or hold. But the rest of the tools work the way you said. 

I had to set the pen button on the middle mouse button, because it does not turn ON the hand. The "Z", "X" buttons I have sacrificed for Zoon In, Zoom Out. 

Maybe it makes sense to give the user a choice in the preferences how the space bar should work?

**Comment by artisteacher** [comment]
The spacebar works for me - both click & hold (temporary) and click (permanent). I love the temporary switch!

**Comment by blurymind** [comment]
the temporary switch is extremely useful! Please keep the design

**Comment by RNavega** [comment]
I understand where @beeheemooth is coming from, sometimes you make quick pans and it gets stuck in the hand tool.

The time limit is 500ms (1/2 second). If you hold the navigation keys for less than that then the previous tool is not restored:
https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/toolhandle.cpp#L76

@blurymind I think the issue isn't about removing the temporary design, but making it the only way of activating the navigation by shortcut. A way to please both tastes would be to add a checkbox in the preferences to choose between:
- Navigation tools always temporary, unless selected from the toolbar
- Navigation tools temporary or permanent, depending on keypress time (like it is now)

In Photoshop and Krita the navigation tools are always temporary when activated by shortcut -- if you want to use the tools permanently then you need to select them in the toolbar.
