### ISSUE TITLE
Feature Request: Tapered Vector Line, and improve "Remove Vector Overflow"

### ISSUE THREAD

**Issue by KirbsArt** [opentoonz/opentoonz#1102]
The vector engine is a bit odd and I would like to see a tapered brush and an improved "remove vector overflow" feature so that vertexes of shapes come to a complete point.

**Comment by artisteacher** [comment]
Have you tried using the new vector brushes from #1088?

**Comment by blurymind** [comment]
This is related to my request from a while back:
https://github.com/opentoonz/opentoonz/issues/287

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
