### ISSUE TITLE
Change default level type

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1105]
I would like to propose changing the default level type to Toonz Raster - here's why:

1. There are some consistent issues with some shapes not being fillable in vector levels.
2. Vector levels can bog down the software if a user uses it for sketch type work with too many lines.

Several times this week I have had students cause OT to become unresponsive because they were drawing in a sketch style and I have experienced the frustration of shapes being unfillable on several occasions.

Thoughts?

**Comment by RodneyBaker** [comment]
I'll add my 2 cents as someone who normally would prefer drawing in vector but recently changed to starting with Toonz Raster... and in particular with the Pencil option checked to be on.  

The fill issue has been such that I've been hard pressed to find an ideal and consistent workflow that leads to  shapes that will consistently fill in vector and I've found that starting in raster and then converting that to vector yields good results.  

The reason I've moved to using the Pencil option (in Toonz Raster) is that I get a consistent line whereas if I use brushes sometime I get what I want but sometimes not.

So, for my part, changing the default to Toonz Raster will be fine with me.  We can always adjust that setting in our preferences.

**Comment by turtletooth** [comment]
Additionally- this is the level type where the eraser behaves the most like many would expect- you can erase part of a fill, and erasing part of a line that encloses a fill doesn't erase the fill.

**Comment by artisteacher** [comment]
Both Toonz Vector & Toonz Raster are pretty unstable on Mac Os when using a tablet.

**Comment by VektorHead** [comment]
You can change the default level type by going File | Preferences | Drawing and change the Default Level Type setting to Toonz Raster or Raster Level.

**Comment by turtletooth** [comment]
> You can change the default level type by going File | Preferences | Drawing and change the Default Level Type setting to Toonz Raster or Raster Level.

I am aware of that, I am proposing changing the initial default for new installs.  This way new users might encounter less frustration than they are likely to have with vector..

**Comment by turtletooth** [comment]
Closing - discussion can be found in the PR for this issue at #1233
