### ISSUE TITLE
(feature request) the fill tool barely works 

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#1108]
It barely works because instead of it just creating a physical object, like any other animation program (like it should. This is especially when working with vectors) the fill tool instead works on a super complex algorithm that SOMETIMES works and even when it does work, it doesn't work well.

It's supposed to make animating easier, where you're not fighting strokes and fills at the same time... but with this stupid algorithm based fill technique... you doing STILL doing that, just in a different way.

**Comment by artisteacher** [comment]
This is a known issue #1093 and fortunately it is being worked on. In the meantime, drawing the outlines on a raster layer and then converting to a vector layer should allow you to fill without issue.

**Comment by Orphanlast** [comment]
Being worked on in what way? If it's being developed where it's still a none physical object... I honestly... I can't see that as being fixable.

I've tried the technique you're describing, there's even a tutorial about it: https://youtu.be/Oi2zhiSZmZ8

This technique no longer works

**Comment by artisteacher** [comment]
I actually meant something quite different. Draw the linework directly on a raster level to begin with. Select all of the cells in the level.  Then in the top menu, go to Levels then "Convert to Vectors". 
![image](https://cloud.githubusercontent.com/assets/21159116/24069021/b8c883b6-0b73-11e7-873d-87feac3cc7be.jpeg)
Adjust the settings as necessary (making sure preview is toggled on) and then select convert. 
![image](https://cloud.githubusercontent.com/assets/21159116/24069022/c5f7e5a4-0b73-11e7-9dc4-07142badcb6c.jpeg)
The vector level that is created as a result fills beautifully.

**Comment by turtletooth** [comment]
Closing this as a duplicate.
