### ISSUE TITLE
Feature Request: Convert selected drawing to new level

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1110]
It is useful feature for cut-out animation/animator. [Read more](http://docs.toonboom.com/help/animate/Content/HAR/Stage/011_Character_Building/067_H2_Cutting_in_Pieces.html)

**Comment by artisteacher** [comment]
That is a really interesting feature. However, once the plastic tool is working properly in all OS, would there still be a need for this?

**Comment by 2dvision** [comment]
> would there still be a need for this?

I think yes, Because this way is fast (good) for some works. Plastic tool is ok, but this technique is different.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
