### ISSUE TITLE
Multiple studio palette paths

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1115]
In Mac OS X, the default global palettes are located in stuff/studiopalette/Global Palettes. However, the studio palette links to stuff/projects/studiopalette/Global Palettes (this is also where the browser room links directly. Is this just an oversight, or is there a reason to have multiple studio palette folders?

**Comment by artisteacher** [comment]
It looks like the multiple paths are causing an issue with the cleanup palette.
![screen shot 2017-04-12 at 12 50 18 pm](https://cloud.githubusercontent.com/assets/21159116/24970696/4eecc082-1f83-11e7-8460-0f1c507ffc3e.png)

**Comment by turtletooth** [comment]
PR Submitted, closing.
