### ISSUE TITLE
No solution for audio scrub crash in Sierra yet?

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1116]
Downloaded even the latest nighlty build. Crashed within the first 3 frames of a very short audio file.
I googled for a solution and only found this picture, which points to a solution I can't understand.
https://cloud.githubusercontent.com/assets/21159116/23825275/bbe66c9e-0654-11e7-971c-47bfd7ddca3f.jpeg
Is this what I need? Or is there still development to do?

**Comment by artisteacher** [comment]
It's a known issue #978, but so far no progress - as far as I am aware. Scrubbing often works more successfully when using shift + scroll wheel in the viewer. It usually still crashes, but often I can scrub back and forth a decent amount first.

**Comment by agatre** [comment]
Oh really? I'll pray it lasts long enough to figure out words. Thanks for the tip!

**Comment by turtletooth** [comment]
Closing as a duplicate
