### ISSUE TITLE
Issue - silent crash when using FX and trying to preview.

### ISSUE THREAD

**Issue by OpentoonzTester** [opentoonz/opentoonz#1117]
Instant crash when using caustics, glitter, fireball etc.  Works fine on ToonzPremium, but not on OpenToonz.

I have conformed the two settings (Opentoonz and ToonzPremium) so that they are roughly equal.

Sometimes Opentoonz will crash on render, but sometimes it will let me render, then will display the FX.  Other times rendering is fine, and it will then display the FX, but will crash if I alter any parameter within the FX in display mode.

Any help with this issue?  Side-by side image for reference.  On Toonz Premium no problem.  If I preview in OT, it will crash instantly with no warning. Gone.

Edit: Win7 64 Bit on Boot Camp
![screencap](https://cloud.githubusercontent.com/assets/26611773/24224808/2ba1262e-0f55-11e7-8e72-1410e6293c73.jpg)

**Comment by beeheemooth** [comment]
This may seem strange, but try to install Visual C++2013

**Comment by OpentoonzTester** [comment]
Did a "repair" on Visual Studio 2013 but it didn't help.

Thanks for the suggestion, though.  Keep 'em coming.

**Comment by OpentoonzTester** [comment]
Crash is reproducible on different systems.  One is an HP ZBook with 16G RAM and an AMD card.  One is an Imac running bootcamp with 32G RAM.

Dwango plugins are fine, it's the opentoonz native ones that are the problem.  Particularly Caustics, fireball etc.

Visual C++ 13 does not rectify the issue.

**Comment by turtletooth** [comment]
I think this is actually the same as #413
