### ISSUE TITLE
Failing assert- tcomputeregions.cpp

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1121]
![failing_assert](https://cloud.githubusercontent.com/assets/4576381/24275200/66c5b726-0ff3-11e7-9e54-22e96c3f3c06.PNG)

I get a failing assert in markDeadIntersections that might be related to fill issues.  ( I have no idea if it is or not, but I thought I would include it. )

[dead.zip](https://github.com/opentoonz/opentoonz/files/866513/dead.zip)

To duplicate, drag the circled control point over the bottom line to close the shape.

![control_point](https://cloud.githubusercontent.com/assets/4576381/24275324/3913aa58-0ff4-11e7-9d73-23ec3c76df74.PNG)

**Comment by flurick** [comment]
I believe this issue should have been closed with #619?
