### ISSUE TITLE
Linux Version of tfarm components  uses MAC path for configfarmroot.txt

### ISSUE THREAD

**Issue by damies13** [opentoonz/opentoonz#1125]
Linux Version of tfarm components uses MAC path for configfarmroot.txt

**Comment by damies13** [comment]
Not sure how to change Assignees? please assign to me

**Comment by ideasman42** [comment]
Not sure if the macOS version even works since this points to OpenToonz `1.0` when the version is now 1.1.

I think this should be using one of the functions from `toonz/sources/toonzlib/toonzfolders.cpp`

**Comment by damies13** [comment]
I have fix for this ready to merge in, when I figure out how to do a seperate merge request from th eone I have currently open.

Dave.

**Comment by damies13** [comment]
@ideasman42, the MacOSX version is not currently being shipped in the OpenToonz_1.1.app file, Issues #1127 and #1130 will resolve that, I have fixes ready to merge in for both, so it's coming.

**Comment by damies13** [comment]
Pull Request #1140 provides a fix for this issue;

The basic logic (psudo code) is now:

if windows:
	set registrypath = "SOFTWARE\<AppName>\”<AppName>\<AppVersion>\FARMROOT"
	read regisrty
else:
	if MacOSX:
		set filepath = “./<AppName>_<AppVersion>.app/Contents/Resources/configfarmroot.txt"
	else:
	      set filepath = "/etc/<AppName>/opentoonz.conf"
	end if
	read file
end if

where <AppName> is currently OpenToonz and <AppVersion> is currently 1.1
