### ISSUE TITLE
toonzfarm & OpenToonz on different platforms

### ISSUE THREAD

**Issue by damies13** [opentoonz/opentoonz#1131]
toonzfarm & OpenToonz both compile for Windows, Linux & Mac OSX, however currently you must use the same platform for both your toonzfarm servers and your OpenToonz desktops.

This issue is to track the resolution to this problem as I would like to have a large toonzfarm running on linux that can be accessed by either Windows or Mac desktops.

I have started thinking about this but need to spend more time reviewing the code to work out the best solution for this issue. In the meantime if anyone has suggestions please comment.

**Comment by jpturcotte** [comment]
Best of luck, @damies13! You have done a great job so far working on tfarm. It is appreciated!

**Comment by damies13** [comment]
Thanks @jpturcotte, great to know my efforts are appreciated.

My initial thoughts on this were to break it into 2 phases:

1. Phase one would leave things fairly much the same, still use a common network share, but make minimal changes to the code so that executable names and paths are adjusted for each platform.

In my earlier investigations ( Issue #1070 ) I found this was partially happening already, now I found the code (or at least some of it) where this happens <https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzfarm/tfarm/tfarmtask.cpp> (around Lines 360-365). I notice that code for linux is missing here, but I can fix this easily.

2. Phase two would involve a bigger rewrite of the network protocol between the various components to change the way the data is sent, to enable a variety of features
- Remove the need for a common network share, instead send the project and resources through the network protocol. I still need to investigate the best way to do this.
- Auto configuration of servers and controller, at the moment this is configured by text files on the common network share, take a server offline and it all stops working :( What I would like to happen is you start a server and it registers itself with the controller, stop it and it de-registers itself, Start a task on the controller, the controller assigns work to various servers as available, new server comes on line and some work is redistributed to it, sever goes offline (intentionally or not) and it's work is reallocated.
- multiple farms, this is more a client side change, but I would like to enable a client to change farm configurations to choose between multiple farms.

more ideas coming....

**Comment by damies13** [comment]
I have started working on this issue, but it's no where ready for a pull request for now and after easter my work is going to get busy for for a few months. If the pull requests i have submitted so far are combined there should be enough to get an OpenToonz Farm running on any platform, as long as all parts of the farm use the same platform.

**Comment by OpentoonzTester** [comment]
I am not a coder, so please forgive me if this is not workable.

The idea is that if the project files were to use an SMB share, so that all the scene files were copied to, say, \\share\scenefilestemp then each system would be able to refer to the share natively, as I think that SMB is an "export" protocol.  It does not change the nature of the underlying share.  Each system can then process the files as if they were in the host os.

All that would be needed (hypothetically) is for each system to be pointed to the relevant share, keep scanning for a "trigger" file (render command) in that share and begin processing on receipt of the render command.  They could use a notifier to tell the share (and so the other systems) the frame they are going to process, with a further notifier to tell the share that the frame was complete.  Delete render command and temp files on completion of final frame.

Would that work?

**Comment by damies13** [comment]
Hi @OpentoonzTester,

Thanks for your comments, unfortunately your understanding of SMB is not quite right, but I will try to explain a bit later. 

First using the SMB share is only the second part of the problem, the first part is getting tfarmserver to run the correct executable for tcomposer, there is code to translate the executable name when a Mac or Linux client connects to a Windows Controller, but when you try to go the other way, it will translate the tcomposer executable to a path hard coded with "Toonz_7.1.app/" in it, obviously this doesn't work for Linux, but actually doesn't work for OpenToonz_1.1.app either. I have checked in a fix for this part of the puzzle into my fork already, but with this alone won't get you working (if it would have I would have pushed it up as a PR).

Now before I go into the second part of the problem, here is a quick overview of SMB:

- SMB is not an export protocol it's a file sharing protocol (2 entirely different things)
- SMB is not a "standard" protocol, it is a proprietary protocol owned by Microsoft
- Throughout the history of windows there has been many versions of SMB, they are mostly backwards compatible but not forward compatible.
- SMB over TCP/IP is now known as CIFS (Common Internet Filing Protocol), which despite its name is also not a "standard" protocol, but a proprietary protocol owned by Microsoft
- There is an open source *nix compatible implementation of SMB / CIFS called SAMBA, which was primarily built by reverse engineering the network activity between windows machines
- SAMBA is included in recent versions of Mac OSX to provide connectivity to Windows file shares.
- SAMBA is also commonly used in some Linux distributions (but not all) to provide file sharing with Windows
- SAMBA is used in many NAS's to file sharing with Windows
- Some Linux file browsers in Linux desktops have their own CIFS clients

As you can imagine it's amazing that it all actually works together at all, sometimes it doesn't, but most of the time it does, thanks to the hard work of some smart people on the SAMBA project.

Now to the second part of the problem for cross platform compatibility, the paths (yes there are more than one) that the client sends to the controller (and then subsequently passed from the controller to the server and then the composer) are the full paths to the scene and output file as the client sees them on the workstation it's running on, this is important as if they are not identical on every machine then the path passed through will result in a file not found / directory does not exist type error. Some important things to understand here:
- Windows can access a file share via a method commonly known as a UNC path (\\\\server\\share\\path), this is the best/safest method to use with OpenToonz on Windows, but often hard for users to remember.
- Windows can access a file share via a mapped drive usually a letter E or later in the aplhabet, these look like E:\path and are easier for users to remember
- On Mac OSX there is no concept of a UNC path, to access the shared files in OpenToonz (or any other application) you first need to mount the share, if you did this through the GUI then it will be mounted at /Volumes/share/path, but with some command line trickery you could have it mount at /server/share/path but never  \\\\server\\share\\path. It's also important to note that file paths on OSX are case sensitive which is not the case on Windows.
- Again on Linux there is no concept of a UNC path, to access the shared files in OpenToonz (or any other application) you first need to mount the share, but with linux it's even more tricky than with OSX 
- With SAMBA on Linux the most common places you would find a windows mount are /mnt/share/path or /Media/share/path, but if the user (or distro) has done something else it could be anywhere
- With some file browsers the UNC paths aren't actually hard mounted in the file system (Naulitis on some Ubuntu variants for example) but are transparently soft mounted within the users session, meaning unless OpenToonz uses that desktops file browser plugin the user is unlikely to ever be able to see the file share, even if this was made to work somehow (supporting all these file browsers would be a nightmare) it still wouldn't work for the command line tools like tfarmcontroller, tfarmserver, tcomposer, etc.

Finally these paths do not include the FARMROOT, they may not even be on the same server as the FARMROOT.

I haven't even covered the various authentication mechanisms that could be involved in that SMB share (There are at least 5 at the share level and several more when you count directory and file permissions), or any of the other complications that come into play with file sharing cross platforms, I wanted to keep it simple~ish.

For Phase One, I was planing to fix the First problem (I think I have this covered) and then somehow try and make the client send paths that are relative to FARMROOT, this would also require that the input scene and output file get stored on the same server and share as FARMROOT, so maybe a check that the relative path doesn't stray more than 2-3 levels from FARMROOT might be required? The next part would be then to have tfarmserver translate the FARMROOT path for tcomposer. If tfarmserver does then translation not tfarmcontroller then the controller and servers don't need to be the same OS. This is as far as I was panning to go with phase one, this alone is a big undertaking and i'm still not sure of all the places I need to change code to make this work. I also wanted to limit it to here so at least there would be a working cross platform solution available.

There could possibly be a Phase 1.1 that could go a step further and move the scene and all it's dependant files into the FARMROOT from the client side, but this may also require modifying the paths inside the scene file(s), we would also need to plan this carefully so that files from different clients don't overwrite each other (two completely different files could have the same file name), so there would be a lot to consider before implementing this.
 
So Why Phase 2? well the current Toonz Farm implementation is quite limiting and using SMB shares will always be it's constraint
- SMB is a very chatty protocol and consumes a lot of bandwidth
- SMB is generally slow over WAN and VPN links
- SMB is difficult to secure and shouldn't be internet exposed or used over the internet without being tunnel'ed through a VPN.

The implications of this is that your OpenToonz Farm will need to be in the same building as your animators and there are many reasons you might not want to do this, some examples:
- Noise (lots of hot CPU's with noisy fans and airconditioners)
- Rent, You might want your animation studio in a inner city location where it's convenient for hiring staff but the rent there might be expensive, so you want to put your farm in a remote data centre on the outskirts of the city or a nearby town where rents are cheap.
- Leasing time / CPU power from third party render farms (like you can do with, blender, 3d studio max, etc)

Sorry this was so long winded, but hopefully it gives some insight on where i'm headed with this.

**Comment by OpentoonzTester** [comment]
Thank you for your explanation.  I think I understand.

So what would be needed as a first step is a coherent directory structure for the scene files to ensure that there is no overwriting?  Automatic date and timestamps as part of the naming convention would perhaps assist.

I understand the mount points for SMB readable directories in linux and OSX.  That could be overcome on install of Toonzfarm so that there is a consistent path for each OS.  IIRC both linux and OSX can use symlinks to a fixed directory, which can be referenced from a user directory.  I am not sure if Windows shortcuts work the same way.

Linux has commands and pipes for converting mixed case to a single case, but it's a long time since I played with it.  "grep" springs to mind, but so  does "cat" and I can't really remember.  From your message you have this in hand already.

For linux and OSX I understand the permissions problem.  I am not sure how that sits with windows permissions.  There would perhaps need to be a group, say ToonzFarmers, with a permissions policy for writing of the scenefiles to the relevant directory.  That could be set at admin level on new users coming on board/on install of Opentoonz.  Not sure how to automate that on any of the OSes, but it's easy enough done in the permissions sections manually.

Noted SMB is problematic in terms of resource hogging.  I don't know of any other "cross-party" protocols without partitioning.  However I suppose anyone setting up a dedicated linux render farm should be able to use a multi-OS compatible partitioning system dedicated to OT.  Takes it beyond the home user a bit though, unless they are really keen.

Thanks again for your kind response and I hope I haven't wasted your time.

**Comment by damies13** [comment]
@OpentoonzTester, after reading you message again and thinking about it for a bit, you are right, it might be possible to configure all three platforms to use thee same path for the toonz farm, by using symlinks actually windows allows symlinks as well in windows vista and above (just found this out today, you use the mklink command on the windows command line).

So using the PR's I have already submitted it might be possible to get this working but this workaround is beyond what I would expect the average user to be comfortable with. 

It leaves you with the network limitations of SMB or other file servers, but will hopefully allow cross platform usage with the current versions.

Here are my thoughts on how this could work, if you would like to try it:

Start with the file server for the sake of this example we'll say it's a windows file server located at SMB share \\\\servername\\stuff 

In \\\\servername\\stuff we put (copy) the contents of our OpenToonz 1.1 stuff folder, we also make sure there is a toonzfarm folder at \\\\servername\\stuff\\toonzfarm, create \\\\servername\\stuff\\toonzfarm\\config  and create the config files per the documentation

On windows machines, assuming that OpenToonz is installed to C:\\Program Files\\OpenToonz 1.1 we use mklink to create c:\\stuff linked to \\\\servername\\stuff (on vista you may need to map the network share to a drive e.g. z:\\ and then mklink to create c:\\stuff to z:\\). then when you configure the path to the FARMROOT for each component (tfarm controller, server, or OpenToonz GUI) use the path \\stuff\\toonzfarm (note: this is intentionally missing the c: or \\\\servername\\, this was not a typo)

On a mac we would connect to the file server \\\\servername\\stuff through the finder, this should create /Volumes/stuff, next open a terminal and link /stuff to /Volumes/stuff (ln -s), then configure FARMROOT to /stuff/toonzfarm

On Linux, mount the file server \\\\servername\\stuff using which ever method is best in your distrobution, and figure out where it's mounted, then from a shell link /stuff to your mount location (e.g. /mnt/stuff or /Media/stuff) (again ln -s), then configure FARMROOT to /stuff/toonzfarm

Now all have similar enough paths tfarmcontroller and tfarmserver will convert \\stuff\\toonzfarm to /stuff/toonzfarm and vise versa.

Hopefully this will work, if you try it (especially if it works) let me know, I will update the ToonzFarm documentation that I started.

Dave.

**Comment by gab3d** [comment]
Hi @damies13 
Thank you for your efforts on this subject!
I'm trying to configure tfarm on a Windows net and I have some doubts:
1.
When, in the toonz farm config instructions you say:
"Once you have identified your file share location, copy the OpenToonz Stuff folder to this file share location."
You mean copying "Opentoonz 1.x Stuff" folder inside the network share , or copying its content inside the network share?

2.
when starting the tfarmserver.exe from console (with -console option) it says it couldn't find the "toonzfarm" folder inside the FARMROOT folder. But the folder is in there (and the controller started ok, reading the config file in this folder).
If I copy of the toonzfarm folder inside itself then the server seems to start, but in Opentoonz interface the server appears twice (but the second instance is not functioning).
I don't know if this is a bug in the tfarmserver.exe or what...?
Have you seen something similar to that happen?

Thanks again for you time!

**Comment by damies13** [comment]
Hi @gab3d,

1) It doesn't actually matter, but I would copy the stuff folder to make it obvious what it was (my memory's not that great and visual triggers like this help.

I suggest the following: if you are creating a new share call it OpenToonz so the path is "\\yourserver\OpenToonz\Stuff\" or "\\yourserver\OpenToonz Stuff\", otherwise if your using an existing share make the psath something like "\\yourserver\yourshare\OpenToonz\Stuff\" or "\\yourserver\yourshare\OpenToonz Stuff\", then at some point in the future (maybe 10 years from now?) it'll be obvious :)

2) Since you are using Windows, you will need to fiddle in the registry for this. On each machine where you are running tfarmserver.exe, open regedit and go to HKEY_LOCAL_MACHINE\SOFTWARE\OpenToonz\OpenToonz, here you should find a 1.1 key (looks like a folder) and maybe a 1.0 key, now this is where it gets messy for now, 1.1.2 and below look at the values in the 1.0 key. 
I've submitted a code fix so the exe will look at the right key for it's version, but not sure when that will make it into the release code. 
For now just keep the values in the 1.0 key and the 1.1 key the same to be safe, you should see a whole bunch of string values all starting with "TOONZ......", if the 1.0 key doesn't exist create it and then create all the TOONZ string values from the 1.1 key and make all their values the same. I don't think tfarmserver.exe uses them but better safe than sorry.
Now for the important part, in HKEY_LOCAL_MACHINE\SOFTWARE\OpenToonz\OpenToonz\1.0 make sure there is a string value (REG_SZ) called "FARMROOT" and the value needs to be your network path (see Q1) i'll assume here you used "\\yourserver\OpenToonz\Stuff\", so the value of FARMROOT should be "\\yourserver\OpenToonz\Stuff\toonzfarm" (without the quotes)

Repeat for every server that is running tfarmserver.exe

Now go back to the server that is running your controller and do the same thing, even if the server that is holding the network share is the same as the controller, still use the network path, otherwise it won't work and you'll get errors.

Also make sure you configure the files in "\\yourserver\OpenToonz\Stuff\toonzfarm\config", you need controller.txt and servers.txt, see Issue #1070 for details on what to put in them.

The controller can appear to start with no issue but didn't actually start properly, make sure you see the message "Starting Controller on port 1" (or some other number higher than 0 of you configured it for another port, but to get things working I suggest you use port 1).

Good luck, and feel free to ask more questions if your stuck.
