### ISSUE TITLE
Empty scene in Cleanup room can trigger scene has been modified dialog

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1135]
I know that most often when someone opens OpenToonz, they'll open a scene and start working right away. However, it is possible to be interrupted and leave the start-up pop-up for several minutes. If auto-save is set to a low value (which is imperative with the instabilities on OS X), it will run and bring up the save scene dialog. Closing the dialog and loading an existing scene results in "the current scene has been modified" dialog. Nothing has been modified by the user. Of course you can discard changes to actually load the selected scene - but you shouldn't have to. The default scene shouldn't read as modified when the user has not modified it.

Thanks for all of the time & hard work, it is appreciated!

This seems to be a problem specific to the Cleanup room. I rarely try using Cleanup since it crashes a lot - I wonder if this could be related at all to #654?

To reproduce:
- close OT with the Cleanup room open
- reopen OT
- close the startup dialog or load an existing scene
- close OT without making any changes 

Removing the cleanup settings window from the Cleanup room stops the “current scene has been modified” dialog from occurring improperly.

**Comment by damies13** [comment]
I would like to suggest a slight modification;

As the start up popup can be launched from the help menu, I would suggest that this should not be used to determine if the auto save is active or not. 

How about the auto-save should disabled when no project or scene is loaded, which would (should) be the case when user has launched OT but not selected a scene from the popup, but would not be the case if the user has opened the popup from the help menu.

Dave.

**Comment by artisteacher** [comment]
That is a good point. However, isn't there is an empty scene open by default when OpenToonz is started? Perhaps what we need is for auto-save to start only after the first change in the scene (if this is possible).

**Comment by turtletooth** [comment]
I just tested it and I'm not seeing the save dialog popup.  
I have it set to autosave every minute and on tapp.cpp line 671 it only autosaves if the scene is dirty- which it is not flagged as on startup.

I can't reproduce this.

**Comment by artisteacher** [comment]
I'm not getting the auto-save popping up anymore but I do still get the "current scene has been modified" dialog when trying to load a scene from the start-up pop-up. It's inconsistent, so at this point I can't give reproducible steps.

**Comment by artisteacher** [comment]
I haven’t run into this since last June, so I’m closing the issue.

**Comment by artisteacher** [comment]
I just ran into this again. It seems to be a problem specific to the Cleanup room. I rarely try using Cleanup since it crashes a lot - I wonder if this could be related at all to #654?

To reproduce:
- close OT with the Cleanup room open
- reopen OT
- close the startup dialog or load an existing scene
- close OT without making any changes 

Removing the cleanup settings window from the Cleanup room stops the “current scene has been modified” dialog from occurring improperly.

**Comment by artisteacher** [comment]
This is still an issue with the latest nightly build.

**Comment by artisteacher** [comment]
This seems to be resolved with the latest nightly build. Perhaps #2892 stopping the cleanup palette from loading when column 1 is empty caused the fix.
