### ISSUE TITLE
Feature Request: Simplify/unify conversion between different level types

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1142]
Currently, while it is possible to convert between all 3 level types, the workflow is very inconsistent  and in some cases really inefficient.

There are at least 5 different ways to convert levels:

1. "Convert to vectors" from the top menu works beautifully for toonz raster levels and black only Raster levels. Colored raster levels convert but not as well.
2. Converting both ways between vector and toonz raster levels is possible by copying and pasting frames in the level strip.
3. Converting from vector and/or toonz raster to raster levels is possible but as far as I've found, only on individual frames. The selection tool is needed to select the drawing in the frame. The selected drawing can be copied and then it can be pasted in the raster level. Doing this for every frame in a level is really inefficient.
4. There is also the "convert file" command but that only converts to various image types.
5. Cleanup converts raster levels to toonz raster levels

Is it possible to make a single workflow to change between the different level types?

**Comment by artisteacher** [comment]
Closing due to #1207.

**Comment by turtletooth** [comment]
@artisteacher Please understand that in #1207 I'm not saying I don't want to hear from users- you have been very valuable here and I don't want to lose your voice or anyone's here.  I just think reorganizing the tracker here to be more functional would be useful.
