### ISSUE TITLE
Black viewer and strange behaviors on OS X in recent nightly builds

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1143]
With the latest nightly builds, the viewer stays black in all rooms - making OpenToonz unusable. This has been an issue before #890 but previously it was only for the first room and would start working after changing rooms or entering fullscreen. Changing rooms or entering fullscreen no longer resolves the problem. The color model is also black - which has not happened before. In the style editor, the color wheel area is black unless it is active/the mouse is hovering over it. There are also some redraw issues where some parts of the last open room show through the viewer. The last working build is from March 27th.
![screen shot 2017-04-13 at 8 42 06 am](https://cloud.githubusercontent.com/assets/21159116/25005041/3831b206-2025-11e7-9915-e68d0699504b.png)
This is with 10.11.6. I'll check with 10.12.4 later today.

**Comment by shun-iwasawa** [comment]
Confirmed

**Comment by agatre** [comment]
Add the fact it crashed while editing an scene. Trying to reopen it caused an inmediate crash. 
Other detail: installed earlier version (non nightly) to edit others, and takes strangely more time to open the scene.

**Comment by shun-iwasawa** [comment]
@artisteacher @agatre Thank you for the report. I'll investigate to see that from which release the problem occured.

**Comment by shun-iwasawa** [comment]
The problem seems to be happened when Qt5.6 introduced into Jenkins' nightly build. I'll try reverting Qt5.5.

**Comment by shun-iwasawa** [comment]
Reverted to Qt5.5 as a quick workaround and the problem seems to be resolved.
The issue is still exist with Qt5.6 so I posted another issue #1146 .

@artisteacher Please try the latest nightly build and close this if it works fine.

**Comment by artisteacher** [comment]
I think the issue is resolved - though there is a new problem that makes it difficult to be sure. The latest nightly creates 2 stuff folders - 1.0 and 1.1. There must be a path issue and OpenToonz can no longer find the qss files. So what I get is:
<img width="874" alt="screen shot 2017-04-14 at 10 01 45 am" src="https://cloud.githubusercontent.com/assets/21159116/25045272/6e3e4060-20f9-11e7-976d-80d69d241412.png">
I do think this is a separate issue, so I'll close this.
