### ISSUE TITLE
Docked viewer turns black on OSX version built with Qt5.6 

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1146]
Confirmed with OSX Sierra 10.12.4.

In OpenToonz built with Qt5.6, the viewer (and other OpenGL widgets) turn black when it is docked in the main window. Toggling full screen mode and back to normal window mode aborts the software.

For now OSX version is released with Qt5.5 in order to avoid such malfunction.

**Comment by jpturcotte** [comment]
Is it still an issue on Qt5.9 builds? cc @artisteacher

**Comment by artisteacher** [comment]
All of the black/transparency issues with the viewer, color model and color wheel seem to resolved now!

**Comment by artisteacher** [comment]
This is not an issue in 1.2 - this can probably be closed.

**Comment by jpturcotte** [comment]
Recommend close.

**Comment by artisteacher** [comment]
I don’t think we’re using 5.6 anymore & it’s not an issue in more recent version of QT - this can be closed.

**Comment by RodneyBaker** [comment]
Closing this pending reopening if older systems still experience the problem as some OT users may not be able to update.

@shun-iwasawa This is your report so will defer to you.
