### ISSUE TITLE
Path issue on the latest build on OS X

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1147]
The latest build creates 2 stuff folders - 1.0 and 1.1.
<img width="410" alt="screen shot 2017-04-14 at 10 06 26 am" src="https://cloud.githubusercontent.com/assets/21159116/25045402/2458a250-20fa-11e7-8cdc-2fec093665b6.png">
<img width="419" alt="screen shot 2017-04-14 at 10 06 33 am" src="https://cloud.githubusercontent.com/assets/21159116/25045405/2776163e-20fa-11e7-894f-904be78fe716.png">
It looks like the path to the qss folder is no longer accurate which results in no access to the themes. It's not pretty:
<img width="874" alt="screen shot 2017-04-14 at 10 01 45 am" src="https://cloud.githubusercontent.com/assets/21159116/25045432/610c869e-20fa-11e7-8ecb-6a75f3c51534.png">
When opening the program I get this warning:
<img width="491" alt="screen shot 2017-04-14 at 10 14 40 am" src="https://cloud.githubusercontent.com/assets/21159116/25045653/4e094e82-20fb-11e7-8f27-763e9d3af8a2.png">
The warning displays behind the startup pop-up and has to be closed multiple times before the program can actually load.

**Comment by shun-iwasawa** [comment]
Thank you for the notification and sorry for the trouble. I think I fixed the problem and am building the updated release.
Please check the nightly build to be released tomorrow.

**Comment by shun-iwasawa** [comment]
I noticed that the problem still exists in the current nightly build. I fixed again and it should work in the next build. Sorry for the trouble.

**Comment by artisteacher** [comment]
It's working! Thanks @shun-iwasawa for working to resolve this swiftly. While not as imperative as this fix was, there are several areas where the mac build could really use attention - #856, #978, #756.
