### ISSUE TITLE
OSX brushtool stops working after enabling onionskin.

### ISSUE THREAD

**Issue by Gulwer** [opentoonz/opentoonz#115]
Hi 
When I activate onionskin by ctrl-clicking in the view the brushtool stops working. If I change room to PltEdit it works but not in the layout that I activated onionskin. I have tried to replace the malfunctioning window but it the same problem. The only workaround I have found is changing rooms.

Opentoonz 1.0.1
OSX10.10.5 
MacBook Pro (Retina, 15 tum, mitten 2014) 
2,8 GHz Intel Core i7 
16 GB 1600 MHz DDR3

**Comment by Goofybud16** [comment]
This effects the Linux build at PR #51 as well.

**Comment by trondarild** [comment]
This sounds like a duplicate of #73. Brush stops working no matter which menu item is selected.

**Comment by tomosu** [comment]
Thank you for your report.
We fixed this problem, so please try the latest nightly-build below.
https://github.com/opentoonz/opentoonz/releases

**Comment by Gulwer** [comment]
This seems to solve the problem. Thanks.
