### ISSUE TITLE
dvdirtreeview SEGABRT when collapsing my computer while saveing/loading anything

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1157]
steps to reproduce:

1. file >> load scene
1. click on my computer to expand it
1. click on my computer to collapse it
1. SEGABRT at `dvdirtreeview.cpp:85`

I'm guessing this is a MacOS/Linux thing since they only have one root directory /
I'm also guessing that the same would happen on windows if only drive C:\ existed.

My OS: fedora 25

**Comment by jpturcotte** [comment]
Is this still an issue?

**Comment by turtletooth** [comment]
Yes it is, but I appreciate you checking.  It's good to close out stale issues.

**Comment by lordadamson** [comment]
yes I checked and the issue still persists on ubuntu 16.04. I wonder if my hypothesis is true about the windows thing.

**Comment by jpturcotte** [comment]
I will try to test it on Windows.

**Comment by artisteacher** [comment]
I'm not having this exact issue with OS X but am wondering if it's related to #1227.

**Comment by artisteacher** [comment]
It’s been over a year, is this still an issue? There have been a couple fixes for path issues in the Browser.

**Comment by RodneyBaker** [comment]
This has been abandoned by the OPR as they have deleted their github account (hence the username 'ghost').

Keeping open pending review/resolution..

**Comment by RodneyBaker** [comment]
Closing as abandoned pending further information and/or update.
