### ISSUE TITLE
Icon Assets (Programmer Needed)

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#1159]
These are icon assets. I've been tracing the bitmaps into SVGs for HiDPI displays. Due to limited time and other factors I can't work on the code side, I can only provide the assets for now. Feel free to use or ignore these, IMO it would be good to redesign them but I haven't got the time to do that lately.

Except for a few, they are all closely based on all the original icons (traced). I'm hoping another programmer can pick these up and implement them (or not, its not a super-important issue).

**toonzqt/resources:** [toonzqt-icons-svg.zip](https://github.com/opentoonz/opentoonz/files/931718/toonzqt-icons-svg.zip)

**toonz/resources:** [toonz-icons-svg.zip](https://github.com/opentoonz/opentoonz/files/931723/toonz-icons-svg.zip)

**Sample:**
![tz-ico](https://cloud.githubusercontent.com/assets/19820721/25162818/6445494c-24bd-11e7-946b-0565aca6ad25.png)

This isn't all of them, but most.

**Comment by turtletooth** [comment]
@shun-iwasawa Were all of these icons added already or only partially?

**Comment by shun-iwasawa** [comment]
@turtletooth Finally, I added them all !
