### ISSUE TITLE
Destructors are noexcept by default in gcc 6

### ISSUE THREAD

**Issue by otakuto** [opentoonz/opentoonz#1161]
This project use throw in destructor with implicit noexcept(false). However, implicit noexcept of destructor changed noexcept(true) to noexcept(false) at gcc 6.
It's reported from Gentoo's Bugzilla.
https://bugs.gentoo.org/show_bug.cgi?id=612938
https://gcc.gnu.org/gcc-6/porting_to.html

**Comment by ideasman42** [comment]
Please give info on the actions needed to cause this error.

**Comment by aliceinwire** [comment]
@ideasman42 compile with gcc6

**Comment by ideasman42** [comment]
I'm building with GCC 6.3.1, is this only a problem with older GCC versions?

**Comment by aliceinwire** [comment]
@ideasman42 you can find the error output here https://bugs.gentoo.org/show_bug.cgi?id=612938

**Comment by ideasman42** [comment]
The cxxflags must be defining `-Werror=terminate`, opentoonz is a very big codebase with warnings that would be nice to resolve, but don't consider this a bug. Submit a PR to resolve warnings is generally welcome of course.

Closing.
