### ISSUE TITLE
Resizing issue with latest build & OS X

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1167]
In the latest nightly build, the entire workspace except the viewer almost always turns black when resizing. This used to happen to the viewer #1113 but at least in 10.12.4, that issue seems resolved. When adjusting the size of the viewer/combo-viewer, the viewer overflows the right boundary between windows.

![resizing](https://cloud.githubusercontent.com/assets/21159116/25358524/c966cdfe-290f-11e7-858d-96370637958f.gif)

**Comment by artisteacher** [comment]
It looks like this issue varies dependent on the version of OS. In 10.11.6, while resizing this is the result:
![screen shot 2017-04-25 at 8 15 05 am](https://cloud.githubusercontent.com/assets/21159116/25384791/94b32190-298f-11e7-8516-88c8e19e0291.png)
It's probably at least partially due to the lack of OpenGL support on Macs, but it would be really helpful for someone to take this on. This is a fantastic program and it would be really unfortunate for the increasing bugginess in the Mac build to discourage new users.

**Comment by jpturcotte** [comment]
Is this still an issue?

**Comment by artisteacher** [comment]
It is still an issue in the current nightly build but not in the Morevna Release.

**Comment by artisteacher** [comment]
This glitch is gone with the latest nightly build!
