### ISSUE TITLE
Any way to drag frames and keyframes?

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1168]
Readjusting the levels is tiring. I'm on a mac.

**Comment by agatre** [comment]
I'd be deadly useful to have some sort of edit mode where keys are tied to their current frame.

**Comment by artisteacher** [comment]
It would be great if there was a shortcut to enable this - then you could drag normally to reposition the frames alone or with shift-drag (or etc) you could move both frames and keyframes together.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
