### ISSUE TITLE
Naming of rendered files

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1169]
When rendering using multiple rendering (in my case "FX schematic flows") the rendered image uses the column name but it will also use the column number. 

columnName(Col 1),png

I would prefer:

columnName,png

Because I am using multiple applications and every time I modify the columns the column number in the file name changes and I have to also delete the old files manually.

If the is an option to toggle this please tell me and also consider moving it to the render settings.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
