### ISSUE TITLE
Vector Brush Onion skin

### ISSUE THREAD

**Issue by Joekuli** [opentoonz/opentoonz#1170]
So i was using a custom vector brush and I notice that the onion skin doesn't necessary have the same effect like non vector. With non vector I get the respective light color that distinguishes the previous and next frame with a slight transparency. Is there a way to get same onion effect on vector brush?

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
