### ISSUE TITLE
Show palette keys someplace like the function editor

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1171]
I explored it and found no subcategory that includes it.

**Comment by artisteacher** [comment]
I agree! It would be great to be able to edit the rgba value of the color key as part of the function editor functionality. It would also be super helpful to have the palette keys visible in the x-sheet. Perhaps the existing key icon for the sheet could have a rainbow colored background for cells with a palette key?

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
