### ISSUE TITLE
Opentoonz will not work.

### ISSUE THREAD

**Issue by CaptainVod** [opentoonz/opentoonz#1172]
The issue that I am having with Opentoonz is once fully loaded with all the components visible in the window, it becomes unresponsive. As if I click anywhere nothing happens as if it freezes once loaded. However, I am not running multiple monitors, nor is it my stylus pad as it still happens without it connected. Also by checking their website my PC is fully capable of running it as well. If you have any ideas leave them below so I may try them to get it working 100%. Much appreciated.

**Comment by jpturcotte** [comment]
Can you take a video?

**Comment by CaptainVod** [comment]
@jpturcotte how do you want the video to be seen? via platform

**Comment by jpturcotte** [comment]
If it is not too big, I think you can post it right here by dragging and dropping it, Else, whatever platform you are most comfortable with.

**Comment by CaptainVod** [comment]
[2017-04-25_18-39-56.zip](https://github.com/opentoonz/opentoonz/files/956847/2017-04-25_18-39-56.zip)
The video is inside this Zip you can take a look at it. @jpturcotte

**Comment by CaptainVod** [comment]
@jpturcotte I believe I have found the issue, it was the audio program that came with my computer that was causing the issue. I have closed it and it has had no issues since then. Odd to think that Nahimic can cause an issue like this.

**Comment by jpturcotte** [comment]
Thank you for the video. Can you tell us more about your specs and also Nahimic (what it does, its version...), if that really fixed your problem? I am sorry, but I am not a programmer. I am just trying to get the ball rolling. You will have to wait for someone like @turtletooth or @shun-iwasawa to check it out.

**Comment by CaptainVod** [comment]
@jpturcotte The specs of my laptop are i7-7700HQ, 2.8 Ghz, GeForce® GTX 960M 2gb, 8GB DDR4, 1 tb hdd. The Nahimic program is just an audio enhancer and allows you to control how the audio comes out of headphones, speakers, etc.

**Comment by jpturcotte** [comment]
If you care to do some testing for the benefit of all, could you try either or both the latest nightly (https://github.com/opentoonz/opentoonz_nightlies/releases) or the Morevna Project's release (https://gumroad.com/l/opentoonz, there is also a link to download directly) with Nahimic on and off? Also, from your video, I suppose you are on Windows 10 64-bit. Are you up-to-date? What about your audio and video drivers? It would be great if you could tell us their versions. I can walk you through it, if you want. Thanks a lot!

**Comment by jpturcotte** [comment]
@turtletooth I think this can be closed.
