### ISSUE TITLE
Opentoonz IRC chan is abandoned - this needs to change

### ISSUE THREAD

**Issue by swordsmanz** [opentoonz/opentoonz#1177]
just tried looking for help on freenode in #opentoonz and the official irc room seems totally abandoned, this probably is not the right place to put this, and for that i apologise in advance. but given what good help and support a healthy irc presence can be for learning and using any SW package, i would like very much to offer help turn the room into a place where people can actually get help and advice. 

**good reasons for an active irc chan** 

- learning together is better than learning alone

- documentation is not as good as it could be, but frequently asked question in an irc room could be used to feed content to the documentation team 

- it is a highly effective way to provide real time help

- there are already a bunch of related communities on FN that would likely want to pitch in to help

well i guess that is the reason for this post, I'm more than happy to help with this, if anyone needs me i guess contact here or /msg swordsmanz on freenode thanks for whoever reads for taking the time to consider this

**Comment by RNavega** [comment]
The disadvantage of an IRC channel is that the information is temporary. In this case I think a forum would work better, because it's searchable and the information that people share will stay there for others to see later.

You mentioned lack of documentation, I agree. GitHub gives a wiki page for each project, maybe that could be used for making a fresh documentation?
- https://github.com/opentoonz/opentoonz/wiki
- https://help.github.com/articles/about-github-wikis/

**Comment by tGuMedia** [comment]
How about a Discord server?  :^V

**Comment by artisteacher** [comment]
There is already a [Google Group](https://groups.google.com/forum/#!forum/opentoonz_en/categories) - though I agree that having an active wiki would be beneficial. I've also made a lot of resources for my students that I'm happy to share - [OpenToonz Turtorials](https://docs.google.com/document/d/144eC0-ymtYN3d4UXotRYSKLkt1C2cXjR_9JV1jsGY9Y/edit?usp=sharing)

**Comment by jpturcotte** [comment]
@tGuMedia There is already a Discord server with a populated channel, although it is for users, not devs: https://discord.me/toonroom.
I definitely feel like this community needs a hub to foster discussion and bolster participation, and so I fully support @swordsmanz's initiative.
More than that, I would like to organize a hackathon in my mid-sized North American city. I am confident I can get a good draw. It would also double as an introduction to the software for local animators. As you all know, there are still show-stopping bugs that limit the adoption of the software, especially on macOS. I believe it would be the perfect format to address these issues. Plus, it would mobilize the community around things such as documentation, feature prioritization, and public outreach. I would be extremely grateful to @shun-iwasawa if he could run this through Dwango. What does everyone think?

**Comment by artisteacher** [comment]
Ooh, if the hackathon ended up fixing the os x issues, that would be amazing!

**Comment by jpturcotte** [comment]
@artisteacher Right? We could also discuss with @morevnaproject, @adamearle, and you to gather info from people using OpenToonz in studio environments. The problem I have right now is that I am reluctant to advertise in Mac communities without the consent of the main contributors here.

**Comment by adamearle** [comment]
Hey mate I just set up a discord for OpenToonz. Personally I dont know why
I didn't do it sooner. I think you should totally go ahead with the
hackathon the more minds and interest the better.

*Discord download:  *https://discordapp.com/download

*Server ID: *313439701505933313
*Json API: *
https://discordapp.com/api/guilds/313439701505933313/widget.json
<https://discordapp.com/api/guilds/313439701505933313/widget.json>
*Premade Widget:*   <iframe src="
https://discordapp.com/widget?id=313439701505933313&theme=dark" width="350"
height="500" allowtransparency="true" frameborder="0"></iframe>


*Adam Earle*
<MrAdamEarle@Gmail.com>





>

**Comment by jpturcotte** [comment]
@adamearle Thank you very much for your support! However, the link does not work.

**Comment by adamearle** [comment]
Sorry mate  Invite: https://discord.gg/yuuEk78

Ad

**Comment by morevnaproject** [comment]
Actually, I do not like hanging on chat rooms, because this is a distraction for my work. But I am open for scheduled meeting.

**Comment by jpturcotte** [comment]
@morevnaproject Of course! I do not like it much either, but for very different reasons. How about we make a Doodle to find the best time for everyone to meet?

**Comment by morevnaproject** [comment]
Can you please clarify what do you mean by "Doodle"? (sorry I do not understand the language here) ^__^"

**Comment by jpturcotte** [comment]
It is a pretty nifty meeting-scheduling app that takes into consideration conflicting schedules. Sorry for the lingo!

**Comment by jpturcotte** [comment]
The survey is live! Please check out #1202. Thank you!

**Comment by swordsmanz** [comment]
glad too see the post got ppl talking ! , from reading everyones responses, i think the question then isn't so much , do we need an irc chan a forum a wiki ect. but how we make it happen and how we avoid duplication of effort right ?

**Comment by turtletooth** [comment]
I'm going to close this as unrelated to development.  Communication is a good idea, but this can be hashed out on the Google Group.
