### ISSUE TITLE
Weird fill bug

### ISSUE THREAD

**Issue by deanmoriart** [opentoonz/opentoonz#1179]
This happens time to time. 

https://youtu.be/XSiM-DEutLA

**Comment by artisteacher** [comment]
This looks like an aspect of the fill issue described in #1007. I think a fix was merged fairly recently. Are you using a recent nightly build?

**Comment by deanmoriart** [comment]
Ah okay, sorry unfortunately I can't use the recent versions because this happens. 
 https://github.com/opentoonz/opentoonz/issues/1173

I am using Morevna App Image.
