### ISSUE TITLE
Exported animation plays back as blank, white frames

### ISSUE THREAD

**Issue by Aurane** [opentoonz/opentoonz#1180]
Hello there!

This is my first time using OpenToonz and I'm having a bit of trouble. I've tried searching everywhere but it's very difficult to find an answer to this issue.

I drew some very simple frames in the program itself as a sort of test animation. I was able to download a ffmpeg that would allow me to export it as an mp4 (since this is the format I need for something else I'm doing). I'm successful at rendering the file but, when I go to play it outside of the test play on the program, it's nothing more than empty, white frames. 

I have the following information to give regarding the version of the program I use and the OS:

OS: Windows 8.1
Software version: 1.1.2

Not sure what other information I could give that would be helpful. It seems like the problem might be caused by something small and stupid. But I just can't seem to figure it out. I'd really appreciate any help with this as I've wasted a couple of hours researching and trying to puzzle it out on my own.

**Comment by deanmoriart** [comment]
@Aurane I guess your camera background is transparent ?

Top menu -  Xsheet / Scene settings. set the M to : 255

**Comment by Aurane** [comment]
Hi there! Thanks for replying! Sorry if this is ignorant of me, but I'm unclear as to how to find the "Scene settings". I'm really new to this program. >.<

**Comment by Aurane** [comment]
Okay, I actually figured out where that option is! So scratch that last question. ^^

I'm not sure how to export a single frame but I guess I was able to export a level? It results in three .png images that all sit on my desktop with transparent backgrounds. One image as the first frame lineart and it shows when I open it up as an image file. The second has just...a black dot for some reason. And the third one has the second frame image where the lineart also shows up just fine as a .png file.

**Comment by deanmoriart** [comment]
You can set every detail from the menu File/ Output settings before the render. 
You can also check your levels if they are active or not ? If it's like col2 it won't get rendered. 

![screenshot_2017-05-07_14-27-00](https://cloud.githubusercontent.com/assets/27736315/25780542/6f545508-3331-11e7-84bb-47015e5469b1.png)

**Comment by Aurane** [comment]
I clicked Col1 and that eye icon appeared and the whole thing turned green just like in your screenshot. When I did that and rendered it to mp4, it showed all of the images playing back! It looks like it was a silly little thing causing the problem. Thank you SO much! I really appreciate the help you gave. :)

**Comment by deanmoriart** [comment]
Oh great, no worries. Glad it worked for you : )

**Comment by damies13** [comment]
I had too this when I first used OpenToonz on one of my machines, but I can't remember which one, MacOS or Windows 7, here are some idea's to make things a little easier for newbies:

- if no columns are visible when render is selected pop a warning before rendering something like "No Columns are visible are you sure you want to render?"
- perhaps the visible setting should be on by default, or at least for column 1, or better every column when it's created.

**Comment by artisteacher** [comment]
The warning is a good idea. At least in OS X, visibility is on by default. It is easy to accidentally turn off camera visibility when you are first learning the program but I wouldn't want the render to override my visibility choices.

**Comment by turtletooth** [comment]
Closing- seems to be resolved.
