### ISSUE TITLE
Feature Request: Grid Line

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1181]
I think this feature is helpful for animate game asset, This feature is exist in krita. [Read more](https://docs.krita.org/Grids_and_Guides)

![Grids](https://docs.krita.org/images/c/c5/Grid_sudvision.png)

**Comment by ToonzBoom** [comment]
I want to perspective grid
![image](https://cloud.githubusercontent.com/assets/28530944/25802104/8be4ad30-33f9-11e7-9479-0307b00c2037.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25802110/9195b936-33f9-11e7-9a66-bc2317eeae00.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25802118/97b45b42-33f9-11e7-87a5-d9dc55247b19.png)

**Comment by RodneyBaker** [comment]
It looks like you already did.  :)

**Comment by ToonzBoom** [comment]
Isometric grid

![image](https://cloud.githubusercontent.com/assets/28530944/25823498/efe109a0-3444-11e7-895e-7e9fdea45f59.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25823516/fe97efa4-3444-11e7-8431-eada00bc400a.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25823551/174ecbc6-3445-11e7-8436-26f1897396d2.png)

**Comment by artisteacher** [comment]
While you're waiting, the field guide can give you a decent starting point. You can make a set of levels to use as your own guides.

**Comment by 2dvision** [comment]
I undrestand, but ["field guide"](https://www.tvpaint.com/doc/tvp11/index.php?id=lesson-first-steps-guides-animator-field) is Completely different with ["grid"](https://www.tvpaint.com/doc/tvp11/index.php?id=lesson-first-steps-guides-grid).

Field guide just is rectangle (is not square).

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
