### ISSUE TITLE
Photoshop brushes in OpenToonz

### ISSUE THREAD

**Issue by UpgradeOpenToonz** [opentoonz/opentoonz#1183]
I suggest adding brushes from Photoshop and OpenToonz.

![2](https://cloud.githubusercontent.com/assets/26676791/25800069/6e42984a-33f0-11e7-8684-8f2fff577e27.jpg)

The format of brushes (. ABR) it even transferred to Gimp. We also need the brush settings.

![1](https://cloud.githubusercontent.com/assets/26676791/25800074/74eb16fe-33f0-11e7-88d0-19f76b5151d1.jpg)

**Comment by UpgradeOpenToonz** [comment]
@blackwarthog @lordadamson I can surely cope with this task.

**Comment by UpgradeOpenToonz** [comment]
@blurymind What do you think about this? @turtletooth @2dvision

**Comment by ToonzBoom** [comment]
@RodneyBaker @morevnaproject what do you think ? @kogaki @Emasoft

**Comment by ToonzBoom** [comment]
Similar settings are available in Photooea 
![image](https://cloud.githubusercontent.com/assets/28530944/25800645/db1ea920-33f2-11e7-8b4b-72446ad97f67.png)
https://github.com/photopea/photopea
Can help add them to the Opentoonz. @photopea

**Comment by artisteacher** [comment]
Being able to customize the brushes would be great! I think the raster brushes are probably all set with the MyPaint brushes coming.

**Comment by AntonWern** [comment]
The format of the brushes (.ABR) is very good. 
![image](https://cloud.githubusercontent.com/assets/28532709/25802917/353ee5dc-33fd-11e7-96e7-a05879334cf7.png) 
![image](https://cloud.githubusercontent.com/assets/28532709/25802945/6017c4e0-33fd-11e7-8c52-600b91ab0729.png) 
![image](https://cloud.githubusercontent.com/assets/28532709/25802956/6c0118a6-33fd-11e7-859b-7465f4657409.png) 
![image](https://cloud.githubusercontent.com/assets/28532709/25802978/8124d59c-33fd-11e7-9610-6781fda4d06e.png)

**Comment by lordadamson** [comment]
That sounds like a really cool feature to have :D

**Comment by blurymind** [comment]
Mypaint brushes cant do stencils unfortunatelly.. unlike photoshop's

On 8 May 2017 13:39, "Adam Zahran" <notifications@github.com> wrote:

That sounds like a really cool feature to have :D

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/1183#issuecomment-299855529>,
or mute the thread

**Comment by JunLao** [comment]
Who will cope with this task? @walkerka  @konero

**Comment by tGuMedia** [comment]
but why would we need this, you can just use Krita ,Photoshop and myPaint for painting. this is animation software not painting software.

**Comment by artisteacher** [comment]
Can't we use stencil brushes on the vector levels?

**Comment by tGuMedia** [comment]
@artisteacher sorta yeah.

anyway, i'm very against this. there's no reason for these brushes to be implemented, they'll only clutter the ui.

besides, we already got MyPaint Brushes.

**Comment by blackwarthog** [comment]
The main problem here - is ABR format open?

I have not found ABR-format tn the list published at [Adobe site](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/). At another site I've found on [this specifications](http://oldschoolprg.x10.mx/downloads/ps6ffspecsv2.pdf) of old format of brushes form Photoshop 6.0, and [some guidlines](http://fileformats.archiveteam.org/wiki/Photoshop_brush) for CS2 format.

What is stencil? Did you mean sample (pattern) brushes which created from selected image data using the “Define Brush” command?

**Comment by morevnaproject** [comment]
Gimp and Krita have ***partial*** support for Photoshop brushes. Would that be enough to have?

**Comment by UpgradeOpenToonz** [comment]
An interesting project was CinePaint
http://www.cinepaint.org/more/docs/brushes.html
![image](https://cloud.githubusercontent.com/assets/26676791/25940422/c2cee030-363e-11e7-82db-14e5e58ab3e0.png)

**Comment by RodneyBaker** [comment]
That screen shot from Cinepaint is from a mockup (not operational).
Not sure that ever got implemented.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
