### ISSUE TITLE
Text doesn't have antialiasing

### ISSUE THREAD

**Issue by RNavega** [opentoonz/opentoonz#1185]
Vector graphics created with the Type tool (plain text) don't seem to be rendered antialiased like the vector graphics created with the brush or shape tools.

**Comment by artisteacher** [comment]
The type tool doesn't work at all on Mac OS...

**Comment by turtletooth** [comment]
Are you on Linux?  I just tested on Windows 10 and it does seem to have antialiasing.

**Comment by jpturcotte** [comment]
@turtletooth & @blackwarthog Is it the same issue as #1166?

**Comment by turtletooth** [comment]
That's what I'm wondering.

**Comment by jpturcotte** [comment]
I will try to test it with and without @blackwarthog's fix for #1166, hopefully this afternoon.

**Comment by jpturcotte** [comment]
Here are the results on Xubuntu.
04.15 AppImage:
![testtext 0001](https://cloud.githubusercontent.com/assets/26857126/26420912/1f382e28-4092-11e7-90a3-39bdda3899ec.png)
05.22 AppImage (AA fix):
![testtext2 0001](https://cloud.githubusercontent.com/assets/26857126/26420940/382911a4-4092-11e7-98de-bc9f3c1bc83e.png)
They both look aliased to me.

**Comment by RNavega** [comment]
> Are you on Linux? I just tested on Windows 10 and it does seem to have antialiasing.

I'm not sure how it happened the last time, I should've taken screenshots.
I tested it again today and it is antialiased, like you said. This is embarassing.

Left is viewport, right is rendered output. That looks antialiased to me:
![text_is_antialised](https://cloud.githubusercontent.com/assets/28221053/26439192/991be0c0-4116-11e7-9e40-c4bc3dc9a6de.png)

Thank you all.
