### ISSUE TITLE
Style editor should remember my settings

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#1187]
There are 4 sections on the style editor: Wheel, HSV, Matte & RGB. You can click the buttons at the top of the style editor to show/hide them, but these aren't remembered between runs. I don't use the RGB, so have to click it each time I startup. It's not a big problem, but it'd be helpful if the required sections were stored in the settings file.

**Comment by artisteacher** [comment]
I agree!

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
As a follow up to this report.  Style Sheet settings should save if/when the default settings for Opentoonz are saved.
It would be good to examine this in the next UI Scrub.

Will reopen as feature requests have long since been allowed.
