### ISSUE TITLE
Brush settings not maintained

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#1188]
When I use a preset brush value, then change to another application (to view a model sheet or sample animation), then switch back, the preset changes. The preset says "<custom>" and the values vary, but always different from my setting, so I have to re-select the brush preset each time, which is very annoying.

**Comment by artisteacher** [comment]
If I close out of OpenToonz & open it up again, the brush settings stay the same but is set to <custom>. Switching between programs while  OpenToonz is open does not impact the set preset or the brush settings on my computer.  I did notice that sometimes when I select a preset and the brush changes, the name of the preset does not register as active & still displays as <custom>. In that case, the brush settings do update correctly. Sometimes changing presets does result in the preset name displaying.  I'm using OS X and the nightly build from April 24th. 

I also ended up with a corrupted scene after playing around with the brush presets and the color model. Now opening the scene causes an immediate crash.

**Comment by agatre** [comment]
I got a "corrupted scene too!" I had to remove the ffmpeg for opentoonz to let me open the scene again...

**Comment by RodneyBaker** [comment]
@artisteacher @agatre You may want to open another issue to report the crash related to this as @DarrenTAnims issue is primarily focused on Brush settings being maintained.  Crashes are priority so those deserve the additional attention.

**Comment by RodneyBaker** [comment]
@DarrenTAnims Has this issue been resolved?
I know some work was done with Brush presets so perhaps that addressed your issue as well.

**Comment by RodneyBaker** [comment]
I'm pretty sure this has been resolved.
@DarrenTAnims can you confirm?

**Comment by DarrenTAnims** [comment]
Yes, I've tested this with 1.4rc and it's been resolved. This is a good fix and saves a lot of pain. Nice one
