### ISSUE TITLE
Colour model needs more controls - specifically a pan control

### ISSUE THREAD

**Issue by StudioTea** [opentoonz/opentoonz#1189]
If I load a colour model with more than 1 character in it, I can't zoom in to see all of my model clearly. If you zoom in, it zooms in to the centre of the image. If you imagine 4 characters standing side by side, you can never zoom in on the outer 2. You can't use the arrow keys or the pan control to move around.

The minimum to help this would be to allow the cursor keys to scroll in the view.

The better, more complete solution would be to allow the rotate, hand and zoom controls to work in the view, the same as on the main page, so we could use the same controls.

**Comment by artisteacher** [comment]
With OS X, when I zoom in/out inside the color model, it is based on the location of the cursor, not the center. I don't have a mouse though - I use the touchpad or a tablet. What is your setup/system?

**Comment by shun-iwasawa** [comment]
@StudioTea You can use middle mouse button drag for panning in the Color Model ( just like the same way in the Viewer). Have you try this?

@artisteacher For zooming in/out, in the Color Model it seems to be based on always the center of the pane. The zoom center setting in Preferences>Interface is only for the Viewer / Combo Viewer for now.

**Comment by artisteacher** [comment]
For some reason that is not the case on my computer. The cursor location determines where the color model or viewers zoom.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
