### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by Allbery** [opentoonz/opentoonz#1192]
Hello, recently I installed OpenToonz but when I click to open it this error appear;this application was unable to start correctly 0xc00007b. Click ok to close. At the beginning of the 2016 I have installed and after short time uninstalled but it work perfectly fine, and I can't understand what may be the problem. Hope I will can use it eventually.

**Comment by turtletooth** [comment]
Can you give information about your system?

**Comment by damies13** [comment]
Hi @turtletooth there are more details about this specific issue here:
https://groups.google.com/forum/#!category-topic/opentoonz_en/troubleshooting/g1vsSE4PCbY 

In this case Windows 7 user without SP1.

In some other cases I have encountered it seems that installing Visual C++ Redistributable for Visual Studio 2017 resolved the issue (is this a requirement? I can't find any documentation saying that it is)

There are quite a few threads in the Troubleshooting section of the google groups, by getting people to install Visual C++ 2017, in most cases this resolves the issue and gets them working.

Hope this helps.

Dave.

**Comment by jpturcotte** [comment]
@shun-iwasawa Is that a requirement?

**Comment by RodneyBaker** [comment]
Closing as not reproduceable at this pint in time.
@Allbery if you are still experiencing problems please let us know.
