### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by ElonnX** [opentoonz/opentoonz#1193]
Hello everyone,

We are an art school from France and our animation teacher told us about opentoonz a few months ago.
We are starting to to short animations (few minutes) and encountered quite some problems, although the saving issues  are quite common and losing few hours of work here and there is very frustrating.

https://github.com/opentoonz/opentoonz/issues/123

I've read this issue and it seems that despite the 'save all' we still have the same problems. 
In order to open our project properly we realised that we had to quit the software right after saving.
-> Discard changes --- deletes drawings (the level appears in red and only rythm is kept).
-> ALT F4 ---  the scene screen dissapeared and drawings went red.

When a level goes red, we have to upload the level again in a new collumn and do the rythm again.

We have noticed some more issues but those two are very upsating us ^^
We might be doing something wrong, so now we always save all and save scene and even after doing so we had surprises when opening the project again.

Thank you guys for what you are doing :)

For the second screen shot the problem might come from me: I copied a level onto another collumn and do you think that this is the cause of the bugs? "GO" is on 2 collumns so the software might go crazy or something? 
I mean by this that all the new drawings are replacing the ones in 1,2,3,4,5,6,7. So I undo everything draw them again, save properly, re open the software and here they are messed up again.

![issue1](https://cloud.githubusercontent.com/assets/28653255/26003685/ae32fd00-3733-11e7-8286-d5e2f9fc9e48.jpg)
![issue2](https://cloud.githubusercontent.com/assets/28653255/26003686/ae478eaa-3733-11e7-8385-d75b59ef4821.jpg)

**Comment by artisteacher** [comment]
I use OpenToonz in my animation classes too. I recommend enabling auto-save in the user preferences, if you haven't already. I hope you don't mean that you have to quit every time you save, in order for saving to actually work! What version of OpenToonz are you using, and what is your operating system/version? 

One of the most recent nightly builds removes the closing dialogue if you've saved your work. I'm not sure it will completely fix what is going on, but is worth a try.

**Comment by shun-iwasawa** [comment]
@ElonnX thank you for reporting the problem. I think we need more information to reproduce it...
Looking at the images you uploaded, it is obviously unnatural that the drawing number "65535" appears at the end of Col49 in the last image, unless you set this on purpose. Could you please let us know what operations did you do before you got into this? Did you just copy&paste the cells on xsheet?

**Comment by ElonnX** [comment]
Hello !

Thank you for your answers!

1- i will try with auto save and come back to tell you how it goes:) 
 what i meant about discard changes is for example: you save then try to go on and realise that it's no good so do some ctrl z but too many (there is maybe an undo ctrl z i didnt see it). So now instead of drawing again you want to quit and reload the software with your save : discard changes wont work as the entire collum goes red. This is an example but it can happen for different reasons. I dont know if you see what i mean.

2- i have two cars in my animation. The red car comes from behind the blue one and ends in front of it. I drew the entire red car on one collumn then spliy it to have the last drawings on another one so the blue car appears behind it. I dont thibk i copy/paste, i thibk i dragged the part on the other collumn for the name stayed the same "GO". After saving I saw that the second "GO" collumn was renamed "Go___1" but as i kept going and saved again it kept renaming itszlf "GO____2 , then ____3 until ___5 (so i had 5 different save for one collumn.  Apart from this there came a moment where new drawings naturally had large numbers (now they appear to be millions). I didnt pay much attention with renumbering them at first so i drew 5 drawings on large numbers. I saved, quit and when i came back, the drawings on the large numbers had replaced the first drawings on the original "GO" collumn. 
I dont think i did something special before it happens but i dont know enough of the software to be sure i could have hit a key without seeing it but îve been working on opentoonz about 150hours before it happened and have never encountered this problem. 
I didnt have time to spend on it this weekend but i will update during this week 

Hope it was clear?

**Comment by artisteacher** [comment]
Oh, ok - I didn't realize. One thing that may help you is the history window. You can undo multiple steps at a time or redo if you realize you didn't actually want to undo. CTRL-Y should be the shortcut to redo.

**Comment by ElonnX** [comment]
Thank you, I will check on that ! I was pretty sure I missed something :)

**Comment by turtletooth** [comment]
@ElonnX Can share reproducible steps that we can look at?  I don't have a clear understanding of where things went wrong.  That would be very helpful.

**Comment by RodneyBaker** [comment]
@ElonnX can you provide an update to this issue?   Are you still experiencing Save issues and if so can you provide additional examples?   Thanks!
