### ISSUE TITLE
Add parent in Xsheet 

### ISSUE THREAD

**Issue by Number0001** [opentoonz/opentoonz#1194]
In many programs, you can assign a binding layer directly to Xsheet. ( Toonz Premium, Retas Studio)
![312](https://cloud.githubusercontent.com/assets/27542785/26023234/63ad5edc-37c0-11e7-9dd5-721852b9bcb1.jpeg)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
