### ISSUE TITLE
Expand/Collapse Panels

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1195]
This feature is in Photoshop:
![expand collapse panels - photoshop](https://cloud.githubusercontent.com/assets/16509592/26029290/f22ca644-3820-11e7-9a3c-89932fb30b9c.gif)

and in Inkscape:
![expand collapse panels - inkscape](https://cloud.githubusercontent.com/assets/16509592/26029293/007dc1c4-3821-11e7-9a59-378cb8f7c724.gif)

We'll have more space with this feature.
![expand collapse panels](https://cloud.githubusercontent.com/assets/16509592/26029295/0ab98650-3821-11e7-9bfa-c21d2a4278a1.jpeg)

**Comment by UpgradeOpenToonz** [comment]
So I think it will be better.
![0902](https://cloud.githubusercontent.com/assets/26676791/26032461/0f7b7898-389d-11e7-8d51-524be2ab53e5.jpg)
![9900000](https://cloud.githubusercontent.com/assets/26676791/26032476/98a6e1c0-389d-11e7-8285-13205f06f9b3.jpg)
![00001](https://cloud.githubusercontent.com/assets/26676791/26032488/adc35a3e-389d-11e7-95af-8e165c355fc1.jpg)

**Comment by artisteacher** [comment]
While there is already some expand/collapse capability (double clicking on the window header expands the window while hiding the others), I agree that being able to collapse windows as desired would be really helpful for those of us with smaller screens. It may be a small thing but switching rooms really slows down my workflow. I'd definitely prefer being able to collapse windows I use less often.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
