### ISSUE TITLE
Hook tool storing additional data? Skeleton tool improvement

### ISSUE THREAD

**Issue by DefinitelyaLeo** [opentoonz/opentoonz#1197]
#Feature Request
Is it possible for the hook tool to store additional data such as the stacking order or any other information that would help with rigging full turnarounds of characters?
 While rigging full turnaround I found that the stacking order is useful in determining the hierarchy of the parts as I change the the view of the character is change but this is only achieved by keyframing the stack order but while animating due to interpolation it shifts i find it a bit annoying. If the parts could be set at default via the hook tool that would help alot with rigging cutout characters. 

Is it also possible to have proper ik in the skeleton tool or improving the default ik and make it have driver bones etc.

**Comment by adamearle** [comment]
Great ideas here.

    Just a note on the IK. Personally i think it works really well but
    it to think it needs a few feature thrown at it.

     1. Maintain offset
     2. Setting a IK bone limit range
     3. Hotkey for when you are in animation mode using the edit tool to
        select the IK pivit point. (personally I love that this can be
        moved around at will/ but it truly is buggy as hell)


    I have a lot more that  could say on the subject because of the
    artist in the studio using OT, but for now I will hold my tongue.

    Adam Earle

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
