### ISSUE TITLE
Color changes not saving 

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1198]
One of my students has run into this issue multiple times when working with vector levels on OS X. She'll add/change a color (specifically fills) and saves. The next time she opens the program, the new colors are missing on the levels but still display in the level palette. It is possible this is user error - maybe she thought she saved all but actually saved the scene - but autosave is on. Has anyone else had this occur?

**Comment by mcjadski** [comment]
I feel like I have experienced this before, so I doubt it's user error.

**Comment by artisteacher** [comment]
I think this is actually the same as #2321 but I'll close this one since there is more helpful information there.
