### ISSUE TITLE
Bug: Windows version crashes when Plastic Tool switched to animate mode

### ISSUE THREAD

**Issue by morevnaproject** [opentoonz/opentoonz#1199]
Steps to reproduce:

1. Create any vector shape
2. Choose Plastic Tool and Create Mesh.
3. Make sure you're in Build Skeleton mode and place a few bones.
4. Switch to Animate Mode -> Crash

This bug is happens for current development Windows version of OpenToonz (both MSVC and MinGW build) - commit 0cb7c2d .

How to test: try nightly build - https://github.com/opentoonz/opentoonz/releases/download/nightly/OpenToonzSetup.exe

The bug doesn't happens for Linux version.

**Comment by abdulazizali77** [comment]
hello @morevnaproject, was looking for an issue to start contributing to opentoonz
However i couldnt reproduce it:
Environment: 
- Nightly `2fc36cb` (released 10 hours ago as of this writing)
- Windows 10
- 2.50 Ghz
- 8GB RAM

Steps:
- Created `New Scene`
- Created `New Level` - (tried Toons Raster, Toons Vector, Raster, Scan)
- Created shapes with `Brush` tool
- Selected `Plastic` Tool
- Click `Create Mesh` -> `+` -> drop down select `Build Skeleton`
- Created skeleton
- Drop down select `Animate` -> started keying bones on different frames

What steps did you do to get the crash? Could the latest nightly have fixed it?

**Comment by morevnaproject** [comment]
Hello @abdulazizali77 
Thank you for testing. I have downloaded latest nightly build and made testing again. The crash is still here. The test is made on Windows 7 (on virtual machine). The same crash was reported to me by other user on other machine (I don't know exactly its configuration).

Here is a video I recorded - https://youtu.be/gW9aSZ0hdI4
Tested with 2fc36cb nightly build.

**Comment by jpturcotte** [comment]
I just tested in on Win 7 64-bits with the latest nightly, and it did not crash.
[test-plastic-tool-1199-win-7.zip](https://github.com/opentoonz/opentoonz/files/1016282/test-plastic-tool-1199-win-7.zip)

**Comment by morevnaproject** [comment]
Hmm... Then it seems this is something to do with my system setup. I will try to install clean system and test. Let's close this for now.

**Comment by abdulazizali77** [comment]
thanks @jpturcotte @morevnaproject !

**Comment by morevnaproject** [comment]
I have tested the same version on a clean system - the bug doesn't happen. So, it's something to do with system setup.
