### ISSUE TITLE
Guide display issue 

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1201]
There is a significant display issue with the guides on my high resolution mac. They are offset and have a size issue when zooming. They are also not easy to see. I'm not sure if the issue stems from the resolution or from Sierra 10.12.4
![img_3876](https://cloud.githubusercontent.com/assets/21159116/26058562/5ab54f82-394c-11e7-981d-5c67c756ef59.JPG)

**Comment by shun-iwasawa** [comment]
Thank you for reporting the issue. It seems that I missed something when introducing the high-dpi monitors support. Additionally already I noticed the following problems with high-dpi:

- The Fx gadgets ( handles for adjusting the fx parameters in the viewer ) becomes too small to grasp.

- Double-clicking the title bar of the floating flipbook does not make the panel to be fit with the contents. It becomes double-sized.

**Comment by artisteacher** [comment]
Also, the anchor points for the skeleton tool could probably be a bit larger on high res screens. 

Thank you for adding the high dpi support!

**Comment by shun-iwasawa** [comment]
Fixed in #1206
