### ISSUE TITLE
First Informal OpenToonz Developers' Meeting

### ISSUE THREAD

**Issue by jpturcotte** [opentoonz/opentoonz#1202]
Hello everyone!
Following the discussion we had around issue #1177, I made this survey on Doodle to know when we could meet:
https://doodle.com/poll/vykettu99pxm4sam
We would do an audio chat on Discord. It is free to register, and works in your browser. It is a **developers' meeting**, and as such, while we welcome everyone, we might limit the speaking time of general attendees. Please tell us the points you want to address so we can draft an agenda ahead of time. Also, we would need a **volunteer** to conscientiously **record the minutes** of the meeting. Thank you very much for your interest!
Sincerely,
J.P. Turcotte

**Comment by swordsmanz** [comment]
i might not be able to talk in voice, but I'm happy to listen in and respond over text just so long as someone posts a date date and time a couple days in advance 

given the previous thread, i would like to propose
* getting the irc chan open
* integration of other community resources 
* is there anything swordsie can do to help 

all ass really small topics ^_^

**Comment by ideasman42** [comment]
Would prefer text only chat, avoids problems with time lag (across continents), people talking over each other - and makes putting together meeting notes easier.

**Comment by turtletooth** [comment]
With @shun-iwasawa involved, I will try and make it - I'm available 3-5pm and after 8pm Mountain Time.  I would prefer text also.

**Comment by shun-iwasawa** [comment]
+1 for the text chat.
If it will become the voice chat,  I'm available only 9pm-10pm (in Tokyo, GMT+9) from the options listed in Doodle since I need to use the instruments in my office.

8pm Mountain Time would be fine for me (11am in Tokyo).

**Comment by jpturcotte** [comment]
If everyone prefers text, then let us go with that. Please answer the Doodle, and if nothing fits, I will take the time to do it manually. Thank you!

**Comment by RodneyBaker** [comment]
I believe this can be closed.

From the evidence of ongoing development we can assume this was a successful meeting.

**Comment by jpturcotte** [comment]
@RodneyBaker It has yet to take place, actually. Maybe after 1.1.4 is released?

**Comment by RodneyBaker** [comment]
Perhaps a concentrated gathering can form with a goal to hyper test the pending pending v1.2.1 release candidate.

**Comment by RodneyBaker** [comment]
Recommend closing.
