### ISSUE TITLE
Crash report gif

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1205]
![ezgif-1-7c2d0ab234](https://cloud.githubusercontent.com/assets/25724133/26172717/0a31dbd6-3b52-11e7-9182-183217274109.gif)

**Comment by shun-iwasawa** [comment]
Confirmed. @beeheemooth thank you for reporting the crush!

**Comment by shun-iwasawa** [comment]
Fixed in #1211. Closing.

**Comment by beeheemooth** [comment]
Thank you very much for your work!
