### ISSUE TITLE
Bug: Spritesheet and gif export - several animate part

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1210]
If i have one drawing and animate like this (Separate to two part):
![spritesheet](https://cloud.githubusercontent.com/assets/16509592/26285047/32f2e668-3e37-11e7-9baf-b4de09980033.jpeg)

![spritesheet2](https://cloud.githubusercontent.com/assets/16509592/26285200/a1d23158-3e3a-11e7-82c0-4be6d09593aa.gif)

Export file is wrong (First row one frame is repeat and in last row, animation is not finished):
![spritesheet_opentoonz](https://cloud.githubusercontent.com/assets/16509592/26285050/4a7729f2-3e37-11e7-8315-af3841c02c1e.png)

Sprite sheet should be like this:
![spritesheet_ok](https://cloud.githubusercontent.com/assets/16509592/26285052/545050d4-3e37-11e7-89e3-41d6bcabd143.png)

**Comment by 2dvision** [comment]
This bug exist for export animate GIF too.

**Comment by RodneyBaker** [comment]
I see the workaround would be to close that gap.
Once closed both spritesheets and gifs render as expected.

**Comment by turtletooth** [comment]
How about MP4? I'll take a look at it soon.

**Comment by 2dvision** [comment]
> I see the workaround would be to close that gap.
Once closed both spritesheets and gifs render as expected.

@RodneyBaker I test it, this bug still exist.

> How about MP4?

MP4 have this bug too.

>  I'll take a look at it soon.

@turtletooth Thank you, brother. :)

Now i think OT can not render the key frames separately.
If i create a new level (beside sprite level) and animate that frame by frame, export spritesheet is OK.
![new level](https://cloud.githubusercontent.com/assets/16509592/26315733/9a51e078-3f01-11e7-92f6-fff81e88e1be.jpeg)

**Comment by turtletooth** [comment]
So any images that are the same are being spit out of at the same not, not in order.  I have it fixed for mp4, and gif.  Spritesheet will take a little more thinking.

**Comment by turtletooth** [comment]
Got it fixed.  PR submitted.  Closing.
