### ISSUE TITLE
original psd files deleted

### ISSUE THREAD

**Issue by matitanimata** [opentoonz/opentoonz#1213]
I'm using a lot of psd files, they are characters, so I import them in opentoonz and then I use plastic to make a rig.
I don't know why or when, but often it loses the original psd file, so when I re-open the scene, it is empty,  the original psd is gone, deleted from the disk.
This bug is really bad because when you import something you can only load original elements, you can't import them making copies like in the commercial toonz, so the original files are in danger...
![2017-05-22](https://cloud.githubusercontent.com/assets/20012515/26323049/b075a3e0-3f2d-11e7-8e77-bd41d47ed212.png)

**Comment by artisteacher** [comment]
In one of the recent nightly builds, the option to truly import external files was added back in. Loading a level from outside of the program should result in a pop-up asking if you want to import the file. The imported file is a copy of the original. This probably won't solve the whole problem, but at least you shouldn't lose the original psd files after upgrading. 

What is your operating system and what version of OpenToonz are you using? Are there any repeatable steps that always result in this issue?

**Comment by matitanimata** [comment]
Thanks for your answer, I'm working on windows 10, but I've experienced the same issue on osx El Capitan,
I'm using OT 1.1.2 (on windows is the version with the mypaint brushes inside). Something happens with the psd files and plastic, but I can't find why, I don't know how to repeat it, I'll try to investigate.

**Comment by turtletooth** [comment]
If you figure out how to repeat it, that is our best hope of fixing it.

**Comment by artisteacher** [comment]
I just found out this has been happening to one of my students. She's using a similar workflow - drawing in Photoshop and then adding keyframes in OpenToonz. Some of her scenes have worked without issue and some keep losing the levels. Just loading the psd as columns, saving and then quitting resulted in those missing levels on re-opening. After a bunch of troubleshooting, it actually seems to be a naming issue. Her file name was very long and included symbols - renaming the file to remove any symbols seems to have resolved the issue so far.

**Comment by matitanimata** [comment]
uhm I don't think so, my file was named "lumaca" nothing strange in it. Maybe a name issue on some layer inside the psd? Could be a theory. I've imported the psd on columns with group layers as frames of the column. Unfortunately I have prohibitive deadlines, if I survive I'll do some experiments to find an explanation for this and other bugs I've noticed.

**Comment by artisteacher** [comment]
As far as I know, there were no issues with the original files. No plastic meshes were used since rendering with plastic is not possible on most Macs. However, the psd columns were disappearing and so far renaming has made a difference. If both the file and layer names are not the culprit in your case, maybe it's two different issues causing similar results?

**Comment by matitanimata** [comment]
yes in my opinion are two different issues.

**Comment by matitanimata** [comment]
![2017-05-25](https://cloud.githubusercontent.com/assets/20012515/26440576/3e4e2858-412d-11e7-96e3-3361306c8595.png)
another case of elements disappearing from the x-sheet: if you make "save as" the elements (drawings, etc...) are not copied in the new scene so when you re-open the scene it can't find them (you have to manually copy & paste them from the original scene to the new one).
To have all the material divided by scene I set my projects like in the attached image

**Comment by manongjohn** [comment]
While looking into another PSD related issue/question, I ran into this disappearing PSD file bug.

There might be other paths to recreate this bug, but I am able to recreate this issue repeatedly by doing a Merge Level to create an editable version of the PSD file.

Anyway, steps to reproduce:
1) Started a new scene.

2) Imported a PSD file from another location as Frames.
File will be copied to extras folder...keep an eye on it in another window.
(Probably doesn't matter if you Import or Load, but didn't want the original deleted)

3) Create a new Raster level (regular Raster, not Toonz Raster)

4) Use Xsheet -> Merge Level to merge the PSD level into the new Raster level
Side note: a minor merge related bug - the icons in Level strip on the Raster level doesn't get updated properly after the merge.  Gets updated after save though.  I'm guessing the internal cache didn't get updated. 

5) Save scene
I watched the file get deleted as soon as I did the save scene.

Hopefully fixing this particular bug path with fix all the other potential paths to this bug, or at least determine what to look for and fix them.

**Comment by artisteacher** [comment]
I’ve noticed that the icons in the level strip often don’t update correctly. If you clear drawings in the level strip & then use the inbetweener, the icons don’t update & display as empty.

**Comment by artisteacher** [comment]
I’m not getting a loaded psd deleted when following the steps above so this may be resolved.

**Comment by matitanimata** [comment]
ok, I'm going to close this issue.

**Comment by bobbybutterfly** [comment]
just happened to me. Psd file deleted from disk!

loaded level as frames (psd layered file located in projects "extras" folder)
changed the file in photoshop and saved it
back in Opentoonz "save scene"  
OT asks: 
Quit: the following files have been modified
blabla#frames.psd  What would you like to do?
- save changes (psd file is now deleted from folder and disk)
- quit anyway (psd file stays in folder)
