### ISSUE TITLE
BUG: Saving in opentoonz does not save everything - user loses all drawing data without warning

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#123]
from https://groups.google.com/forum/#!msg/opentoonz_en/JnX9rziI8bY/IpPfqwkNEQAJ

> saving -  in harlequin when I save the scene I save ALL the scene: levels, palettes, etc... I think it's a crazy work to save every single element! We worked on scenes with thousands of levels, this is really a bad, bad thing!

Please add a command to the file menu that saves the entire project - all of the scenes with their levels and palettes. Everything - so as to avoid data loss due to negligence.

**Comment by odysseywestra** [comment]
@blurymind Could you do some research to find out how openToonz saves files and what the steps to save a project entail?

**Comment by blurymind** [comment]
@odysseywestra i will look into it! :)

**Comment by blurymind** [comment]
Ok here is a gist of it:

- Saving a scene (file> save scene) - only saves the scene (level names, their hierarchy and keyframes), but does not save the drawings that are contained in it's levels.
So when you reopen the scene, you get an empty canvas. Mesh levels get lost too.
It loses all the palettes too:
![warningafterscenesave](https://cloud.githubusercontent.com/assets/6495061/14235544/6ae85ad6-f9f9-11e5-8440-c6547ea2d31e.JPG)
So essentially after you save a scene, you close it. Then you load the scene- all of your drawings are gone:
![reopeningascene-nodrawings](https://cloud.githubusercontent.com/assets/6495061/14235552/aea8df66-f9f9-11e5-9861-5a82424e4dfb.JPG)

- If you save your scene, then do file>save level - opentoonz only saves the currently active level. If you reopen the scene - any levels that have not been saved get lost
![lostlevels](https://cloud.githubusercontent.com/assets/6495061/14235567/2d4d0518-f9fa-11e5-98ab-6fcff9ff7888.JPG)
If you try to draw on a level that is in red, nothing happens and opentoonz might even crash 

Essentially every single time you want to save your progress and you have 5 levels(just for example), you need to:
1. save the scene
2. Select level 1, file>save level
3.  Select level 2, file>save level
4.  Select level 3, file>save level
5.  Select level 4, file>save level
6.  Select level 5, file>save level

This is absolute madness! xD
Please make opentoonz also save all the levels when the user saves the scene. That is how toonz harlequin used to do it.

**Comment by blurymind** [comment]
A new command has been added to save all. I am closing this bug.

As a side note: the command should be available in the file menu by default and should be attached to the ctrl+s shortcut.
The default room layouts are stiff user unfriendly too.
