### ISSUE TITLE
PNG image is rendered with premultiplied alpha

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1230]
According to the [PNG Specification](https://www.w3.org/TR/PNG/#6AlphaRepresentation) , it says that PNG should be straight alpha in normal.

>The colour values in a pixel are not premultiplied by the alpha value assigned to the pixel. This rule is sometimes called "unassociated" or "non-premultiplied" alpha. (Another common technique is to store sample values premultiplied by the alpha value; in effect, such an image is already composited against a black background. PNG does not use premultiplied alpha. In consequence an image editor can take a PNG image and easily change its transparency.)

For now OpenToonz renders PNG with premultiplied alpha. It causes problem especially with the loading option recently introduced in #1217.

**Comment by turtletooth** [comment]
@shun-iwasawa I have tried to find where this is in the code, but I can't.

**Comment by turtletooth** [comment]
@shun-iwasawa I don't think this is just related to pngs.

Try this: 
1.  Create a psd with a transparent background and a soft brush.
2.  Import the psd to OT.
3.  Create a new layer below the psd layer
4.  Add a dark gray rectangle to the new layer that is only under half of the psd.
- at this point you will see that the soft (semi-transparent) parts of the psd are actually lighter than they should be
5. Export the file (tif is fine)
- the parts of the tif file where the soft brush is over a transparent section render darker than they should.


![premulttest2 0001](https://user-images.githubusercontent.com/4576381/27156564-d2924dd0-511a-11e7-8be1-0e239cbc127d.png)

**Comment by RodneyBaker** [comment]
@turtletooth  You are correct.  This issue applies to all image formats
that support transparency.

**Comment by turtletooth** [comment]
Is #1249 related?

**Comment by RodneyBaker** [comment]
> Is #1249 related?

That's an interesting premise.  It may very well be.
The fact that the preview doesn't show that however makes me wonder.

I would think a test could be generated where premultiplied images are used (with unpremultiplied turned on in OT) and the resulting halo/line should be white instead of black.

I think I've got that right.
Since OT only renders out premultiplied another program would have to be used to generate the test images.

**Comment by shun-iwasawa** [comment]
@turtletooth I think I understand what is actually the problem.
You probably loaded the PSD with "Load As Single Image" option.

In my test here, with the "single image" option all layers are composited and premultiplied in advance.
In such case the image is displayed as double-premultiplied (by the "Load As Single Image" option and by the level settings option) and has dark edge.

We didn't notify the problem because we always used "Load as Columns" option. The "Load as Columns" and the "Load as Frames" options seem to load the layer images as-is (i.e. with straight alpha) so the level settings option works properly.

**Comment by turtletooth** [comment]
While we're on PSD layers- do you know why when I load this and select to expose groups as columns in subxsheet, it doesn't work?  Ignoring groups works, but creates a mess.  I realize that this psd is not very efficiently put together, but I created it to test the groups feature.


[buildings4.zip](https://github.com/opentoonz/opentoonz/files/1079610/buildings4.zip)

**Comment by turtletooth** [comment]
@shun-iwasawa I have looked in the code for this and saved out a QImage before and after the compute on 988 of trenderer.cpp, but I can't locate where in the compute (and nested functions) the premultiplying is happening.

Any thoughts?

**Comment by jpturcotte** [comment]
Can we have an update on this and #1249? I would like to start a bounty (hopefully combined). cc @morevnaproject, @turtletooth & @shun-iwasawa

**Comment by turtletooth** [comment]
It's probably an easy fix, but I just couldn't find it in the code.  A bounty would definitely be welcome - this one probably wouldn't need a huge bounty.

**Comment by jpturcotte** [comment]
Could anyone look into #242 at the same time? @turtletooth I will initiate it in the coming days.

**Comment by turtletooth** [comment]
That would definitely be a bigger task, and I'm not sure the solution is actually related to the problem here.  This one deals with how pngs are rendered, #242 deals with how they are loaded.

**Comment by jpturcotte** [comment]
No problem, thank you for the explanation. I knew they were unrelated, but I wrongly thought they might overlap.

**Comment by turtletooth** [comment]
This one should definitely receive some attention.  Not having proper png export is a pretty big issue.

**Comment by jpturcotte** [comment]
A bounty has been created for this issue: https://www.bountysource.com/issues/45602432-png-image-is-rendered-with-premultiplied-alpha.
I put in $15 for now. Sorry for the delay!

**Comment by jpturcotte** [comment]
@turtletooth Don't forget to claim the bounty!

**Comment by Pflugshaupt** [comment]
While this fix appears to work when rendering the output, the alpha channel is still premultiplied when using "Export Level.." for both png and tif export formats. The problem is even visible on the preview during the export level configuration. It would be nice if that could also be fixed.

**Comment by morevnaproject** [comment]
@Pflugshaupt I think it's better to open a new issue for that.
