### ISSUE TITLE
Pop-up Hierarchy Incorrect

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1231]
When there are multiple pop-up windows, the most recent does not always display on top. For example, in the last couple nightly builds that I've tried, when I choose a scene from the file browser (when using the start-up pop-up), the file browser displays underneath the startup pop-up. Same thing happens with the output settings pop-up. If I change the output location, the browser displays underneath the output settings pop-up. I've had similar issues before when working with FX, but these are new.
![screen shot 2017-05-26 at 8 42 21 am](https://cloud.githubusercontent.com/assets/21159116/26495301/1cf534ca-41f1-11e7-8d99-2b4dca73b68f.png)

Also, sometimes the pop-ups display on top of other programs when they are active. For example, while rendering to video, if I check my email in a browser, the rendering pop-up stays in view on top of the browser (pre-existing issue at least in OS X)

**Comment by shun-iwasawa** [comment]
@artisteacher Thank you for reporting the issue. Regarding the stacking order of the file browser, I modified them to be non-modal in #1214 . I think this makes some browsers to be put behind another popup with `Qt::WindowStaysOnTopHint` window flag. I'll investigate this next week.

**Comment by turtletooth** [comment]
@shun-iwasawa What are your thoughts on me taking UI based issues for now to free you up to take on other issues?  I can often figure out UI and basic issues, but when it comes to any image processing, vector graphics, fx etc. . . I am pretty useless.

**Comment by shun-iwasawa** [comment]
Fixed.
