### ISSUE TITLE
Usability: navigation tools shouldn't clear the selection

### ISSUE THREAD

**Issue by RNavega** [opentoonz/opentoonz#1236]
If this is more of a feature request than a bug, please let me know and I'll repost it on Google Groups.

While you're editing a stroke with the Control Point Editor Tool, for example, you may want to rotate, zoom or pan the view, and when you do that the selection is cleared.

![opentoonz - navigation deselect bug](https://cloud.githubusercontent.com/assets/28221053/26519987/b52f76b0-42b9-11e7-9ed9-828c0202c83c.gif)

Expected behaviour:
Navigating, especially in this "override" mode (when the previous tool is restored afterwards) should preserve your selection so a user doesn't have to reselect the stroke each time they navigate.

**Comment by turtletooth** [comment]
Right now the spacebar is the shortcut for the hand tool.  Middle click does pan movement also.  The only option I can think of is to hard code the spacebar to also do what the middle click does.  Right now- the hand tool is a full separate tool and not just a temporary navigation button.

Hard coding space bar to do the same as the hand tool would work but the downside is that you couldn't change the shortcut.

**Comment by turtletooth** [comment]
This is actually the same issue as #1235 
I'm going to close this and move the discussion over there.
