### ISSUE TITLE
(Discussion) MacOS Developer Recruitment

### ISSUE THREAD

**Issue by jpturcotte** [opentoonz/opentoonz#1237]
In the spirit of the next development cycle, and following discussions with @morevnaproject and @turtletooth in the Google Group (https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/FnyZJ_E5e_E), I will try to recruit some macOS developers to work on long-standing bugs in OpenToonz. We have already singled out build maintenance, graphics processing, and vector consistency (e.g. vector fill) as general areas of concern, but I would like the developers' help in coming up with an itemized, hopefully prioritized list. I will then hit the forums and mailing lists. I hoped @shun-iwasawa, @ideasman42, and others could provide us with their technical expertise and informed opinion. Thank you!

**Comment by artisteacher** [comment]
Thank you! This is so needed. As a mac user,  graphics processing (which ought to fix the plastic issues #856 #939 and some of the menu issues #902) is definitely super important. Working on vectors will hopefully fix #891 and #705 along with the fill issue - though those are a lower priority. I also think tablet stability #756, audio stability #978 #941, working menus #618 and a working type tool #370 would all be helpful.

**Comment by turtletooth** [comment]
Quick thought- Would there be any interest in supporting a patreon?  I am currently only tackling the issues that are relatively simple or affect me or my students directly.  If there were a patreon supporting me a little, I would be willing to tackle other issues and try and get other issues looked at.  I even have access to a mac but have never built OpenToonz on it, since my students use PCs.  I bet I could tackle a few of the mac issues such as audio playback, menus and maybe tablet support.

I would also increase my focus on stability and start building documentation (which is sorely lacking).

If the interest were there, I would be glad to get it rolling.

**Comment by RNavega** [comment]
For reference, there's also the possibility of a Kickstarter campaign. It's what Krita used to fund [a specific set of new features](https://www.kickstarter.com/projects/krita/krita-2016-lets-make-text-and-vector-art-awesome), representing their next software version.
With the funds they were able to hire full time developers to work on that.

The people who pledged more than a certain amount also [had a right to vote on a predefined set of optional features](https://krita.org/en/kickstarter-voting-instructions/), to pick which of those they would like to see most.

> Would there be any interest in supporting a patreon?

I don't have much experience with this, but I think it'd help to make a definitive roadmap, so people would have something objective to look at and go "hm, would I support this direction?"

**Comment by amotarzi** [comment]
I absolutely agree with all the points above, let's actually do set up a Kickstarter! 

In the next months I will be available to perhaps do a small animation (the traditional Ghibli approach 1:1) maybe create a quick little story outlining the need for developers on the Mac side and if we get the funding hire the necessary developers to commit on the Mac side (if you look at the issues labels the most reports are indeed for macOS!).

**Comment by amotarzi** [comment]
In terms of a roadmap I think we should seriously think about the STUDIO GHIBLI legacy! Making sure that what they achieved in their long history and immense talent + crafting Toonz for this specific traditional, Japanese 2D animation will still be possible to achieve for coming generations and of course free to use!

This already is huge but there are quite a few issues especially on the Mac side that does prevent a few key functions like any type of sound usage, scanned drawings cleanup process causing crashes everytime and overall stability.

If we can achieve this initial round via a Kickstarter and together create a campaign for this, that would be awesome. The only think I have no clue is where to find developers and if there are any interested in this.

**Comment by mcjadski** [comment]
I 100% agree with prioritizing bug-fixing for now.  Right now OT is wonderful and horrible at the same time.  No one I've introduced OT to has continued to use it, which shows the severity of this situation. 

I think the vast majority of indie 2D animators would leap at the chance to use a free, fully-functional, and professional-quality software. Whatever form of crowdfunding we choose, I'm confident we can gain support if we're strategic in seeking it out.  

I have minimal experience with fundraising myself, but for additional food for thought, here are links to [The Krita Foundation](https://krita.org/en/about/krita-foundation/) and the [Blender Development Fund](https://www.blender.org/foundation/development-fund/), as well as [Gimp's donation page](https://www.gimp.org/donating/).

**Comment by morevnaproject** [comment]
> As a mac user, graphics processing (which ought to fix the black window issues, the plastic issues #856 #939 and some of the menu issues #902) is definitely super important. Working on vectors will hopefully fix #891 and #705 along with the fill issue - though those are a lower priority. I also think tablet stability #756, audio stability #978 #941, working menus #618 and a working type tool #370 would all be helpful.

I would suggest to create a GitHub's Project Board for OSX-related issues (https://help.github.com/articles/about-project-boards/). This way they can be arranged by priorities. ^__^

**Comment by morevnaproject** [comment]
> Would there be any interest in supporting a patreon?
From my experience with Patreon (https://www.patreon.com/morevna), it gets a HUGE effort, before you can make significant income with it. For reference: We are maintaining and developing several open-source software packages - Synfig (Windows, Linux, OSX), OpenToonz (Linux), Papagayo-NG (Windows, Linux), RenderChan (Linux) + producing some open-source animation content. Our Patreon page is alive since since Feb 2015.

**Comment by RNavega** [comment]
> In the next months I will be available to perhaps do a small animation (the traditional Ghibli approach 1:1) maybe create a quick little story outlining the need for developers on the Mac side [...].

Finished projects I think are the best way to get more people interested in this software, like a "made with" demo-reel of projects done on OT, with quick cuts, hip music, something that can be shared on social media...

An entire reel of paperless ("tradigital") animation clips made by OT users would be awesome.

**Comment by RNavega** [comment]
In fact, let me register here the need to add a 'User Showcase' section to the OT main website (https://opentoonz.github.io/e/ and the main 日本語 version).
Plus, to add directions in there on how can someone submit their work to be displayed in that section (although the first entries would have to be collected by hand, by searching for artwork that people did on this software).

**Comment by matitanimata** [comment]
Hello, I run a studio in Italy (Rome) since 1996, here is our reel: http://www.matitanimata.it/2017/04/28/show-reel-2017/ almost all our 2D stuff is made with Toonz Harlequin, we are switching to opentoonz (today is better than the commercial toonz) so if we can be helpful in any way let us know! We have also a good relationship with digital video.

**Comment by jpturcotte** [comment]
Hi @matitanimata,
Welcome to our community, and congratulations on transitioning to open source software! This is a very cool reel you have there, and very humbling, since you have been in the business for more than 20 years. We are always looking for input from people who actually use the software in a production environment, so by all means participate in the discussions and raise issues that are important to you. Indeed, we are currently looking to recruit new contributors, especially on the Mac platform, but if you know of any developers on any platform, please send them our way. By the way, which OS(es) do you use in your studio? I look forward to interacting with you in the future!

**Comment by matitanimata** [comment]
Thank you @jpturcotte , 
we use both mac (El Capitan) and pc  (win 10). I'm using OT especially on a wacom companion 2,  unfortunately I can't use it on mac until the plastic render issues aren't solved (I hope soon, in Harlequin there isn't that bug) .
I don't know developers except the digital video's guys, I'll try to search someone interested.
It will be a pleasure to interact, I'll try to explain our toonz pipeline and give some suggestion!

**Comment by jpturcotte** [comment]
I think @morevnaproject is sneakily working on this (I am joking, Konstantin ;)). It might help if you could answer his question in issue #939. I invite you to join [the official forums](https://groups.google.com/forum/#!forum/opentoonz_en) and the unofficial [Discord chat server](https://discord.gg/fMx8qPr). Discussions unrelated to bugs should not be held here on GitHub. I know for a fact a lot of people will be happy if you would describe your pipeline there!

**Comment by RodneyBaker** [comment]
Closing but...
We should continue to encourage/recruit additional developers.
Perhaps we can add some additional incentives in 2020.

**Comment by gab3d** [comment]
Absolutely....
