### ISSUE TITLE
Bug: file > save level on Mesh levels does not work while the plastic tool is active

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#124]
To reproduce this bug:
1. create a level
2. Go to the plastic tool and create a mesh
3. add some bones to the mesh
4. Select the newly created mesh level in the x-sheet, while you are in the Plastic tool
5. File>save level

Expected result: Saves the mesh level and the animations in it. 
Current result: 'Toonz can not save this level'
![meshlevels](https://cloud.githubusercontent.com/assets/6495061/14206009/db835e38-f807-11e5-8d68-24e8cc9f64e6.JPG)

Saving mesh levels while the plastic tool is active does not work.
If you select another tool however you can get the save file dialog, but when you actually do save, opentoonz crashes: https://github.com/opentoonz/opentoonz/issues/198

**Comment by blurymind** [comment]
A user at the blender forum has reported that saving mesh levels does not work at all for him:
http://blenderartists.org/forum/showthread.php?394970-ToonzPremium-(2D-Animation-tool)-now-Open-Sourced&p=3037775&viewfull=1#post3037775

**Comment by Rayek** [comment]
That would be me - I have tried saving the mesh, but to no avail. Blurymind, could you provide a step by step explanation how you save those mesh levels?

**Comment by blurymind** [comment]
You are actually right. In this bug report you can at least get to the save dialog, but when you actually do try to save - opentoonz crashes altogether.

I filed a bug report - as it is much more serious.
https://github.com/opentoonz/opentoonz/issues/198

saving in opentoonz in general is broken at the moment.

**Comment by blurymind** [comment]
This bug has been fixed by @shun-iwasawa
