### ISSUE TITLE
Feature Request : Lock Docker

### ISSUE THREAD

**Issue by tghart** [opentoonz/opentoonz#1248]
Hello, i have an request. this request is **Lock Docker**, when i drawing on opentoonz my docker always disordered.
For example : lock docker like krita
![giphy 4](https://cloud.githubusercontent.com/assets/25517443/26750270/57e524c0-4848-11e7-9485-9569ed053832.gif)

Thanks You

**Comment by adamearle** [comment]
yeah nice idea and a pin docker feature would be great as well along 
with floating windows being able to doc into another floating window

Adam Earle

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by tghart** [comment]
@jpturcotte I'm Sorry. I don't know it. Thanks you For Information

**Comment by jpturcotte** [comment]
@tghart No problem! If you post it in the Google Group, devs will be sure to see it.

**Comment by 2dvision** [comment]
> Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

@shun-iwasawa You can use "[Creating an issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)" and add this information for user.

**Comment by 2dvision** [comment]
@tghart This feature is exist. Go to  **Windows** menu and select **Lock Room Panes**

**Comment by tghart** [comment]
@2dvision thanks you very helpful
