### ISSUE TITLE
Blur Effect Question

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1257]
@shun-iwasawa On Motion Blur Iwa - what goes in to the "back" slot?  I

**Comment by shun-iwasawa** [comment]
The "Back" port is intended to connect the background image.
Contrary to using the Over Fx node, using the "Back" node will composite the motion-blurred foreground and the background on an exposure basis and usually can get better result.

![motionblur_backport](https://user-images.githubusercontent.com/17974955/26864564-da98aa9c-4b93-11e7-9699-5705034f6590.png)

**Comment by turtletooth** [comment]
Thanks for the detailed answer.  You are amazing!
