### ISSUE TITLE
Documentation and Tutorials

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1258]
I think the OpenToonz website would benefit from having a news section and updates.  I have started making tutorials for OpenToonz which I think might also be useful to link to from a news section.  I don't mind keeping the section up to date.  @shun-iwasawa Is there any interest in that?  I would obviously only be able to update the English page, but I think it could improve communication.

**Comment by artisteacher** [comment]
I'd be happy to help, if its needed. I have a bunch of tutorials already for my students.

**Comment by shun-iwasawa** [comment]
We are going to put the twitter embed search timeline (#OpenToonz) on the website for grasping what's new.

**Comment by shun-iwasawa** [comment]
The timeline was introduced. (Thanks @kogaki !)

**Comment by ideasman42** [comment]
Is there a reference manual for Toonz? (assume some documentation would have been written before releasing as opentoonz).

Perhaps it could be released creative commons for the community to maintain for open-toonz.

**Comment by shun-iwasawa** [comment]
@ideasman42 
Please refer to the comment by @digitallysane in the past issue;
https://github.com/opentoonz/opentoonz/issues/102#issuecomment-203073578

**Comment by ideasman42** [comment]
@shun-iwasawa thanks for the link.

Eventually though, if someone makes a change to OpenToonz, that should be documented somewhere.

The user community might not be big enough yet, but eventually it would be good if there was a place for this to be handled.

**Comment by turtletooth** [comment]
I am going to propose that the wiki be used for documentation.
