### ISSUE TITLE
Fullscreen:  Hotkeys for Tool Option Bar don't work

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1266]
Hotkeys assigned to tool options (Type, Mode, Selective, Frame Range ...) do not work when switching to full screen mode (Toggle Maximize Panel). I always have to exit the full-screen mode to change the setting.

**Comment by artisteacher** [comment]
Shortcuts to change colors also do not work in full screen mode.

**Comment by RodneyBaker** [comment]
In light of recent changes that correct issues with full screen mode (and shortcuts) it will be good to revalidate this issue.
@beeheemooth @artisteacher Can you provide any updates?

Also, as a clarification it would be good to know if the shortcuts that fail (if any) are default shortcuts or are personally customized.

**Comment by RodneyBaker** [comment]
Closing as likely resolved as all the shortcuts tested appear to now be working in Full Screen mode.
@beeheemooth If there are any specific shortcut keys (that normally would work) that do not work in Full Screen mode please let us know.
