### ISSUE TITLE
When there are a lot of vector graphics in one cell, accidentally skewing a line locks up OT

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1267]

**Comment by MikioKimura** [comment]
This Bug appeared on these computers

**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz

**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz

**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz

**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by turtletooth** [comment]
Can you give repeatable steps or a sample file this happens on?

**Comment by jpturcotte** [comment]
@MikioKimura Can we have an update, please?

**Comment by RodneyBaker** [comment]
LInks for assistance:
OpenToonz Troubleshooting forum:
https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting

OpenToonz Discords (chatrooms): https://discord.gg/xjZsAfu or https://discord.gg/JA292SR

Closing this issue.
