### ISSUE TITLE
(Proposal) Flip stroke options

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1268]
## **Flip stroke options are needed for stylised strokes. An option to move a graphic along a stroke’s path for  re positioning stylised stroke** 

**Realised this was more of a Feature Request, however, it would be really handy when it comes to drawing and designing with vectors, it is a standard in other programs.**

**I've also noticed that the selection tool has no "Flip Horizontal/Vertical" flip-flop buttons are absolutely dire (Like the mirroring graphics buttons in Krita except this would apply to the selected drawing not cell) A flip and flop column feature should be implemented as this is also needed to be done on a regular basis ie. left arm right arm for character creation.**

**Comment by RodneyBaker** [comment]
Interestingly, some other versions of Toonz use to have the Flip Vertical and Flip Horizontal capability on right on outside of the bounding box of the selection.  Clicking on an icon on the bottom middle flips the selection vertically and clicking on the left middle flips the selection horizontally.  It is indeed quite useful.

A question:  How might the code best handle the order of control points for the flipping of a selection?

**Comment by RodneyBaker** [comment]
It's safe to say this feature request has slipped at least to the 2019 development cycle.

There are several related issue and requests and @turtletooth created a Project to capture some of the various Vector Improvements that can be pursued in 2019 and beyond..
