### ISSUE TITLE
OT Occasionally Freezes when Changing Hotkeys

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1271]

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by RodneyBaker** [comment]
@MikioKimura  Is this still a problem?
@turtletooth tagged this report a bug but beyond that we can use any additional information we can get.

The only hotkey problems I've experienced is conflicts with other programs that interfere with specific hotkey combinations.  The fix there is to reassign the hotkey either in OT or that other program.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@MikioKimura Please let us know if you are still experiencing any issues.
