### ISSUE TITLE
.ini file doesn't load hotkeys??

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1272]
## **Hotkey list becomes empty when  Loading an Exported hotkey file (.ini) from Desktop computer 1 into open toonz on Desktop computer 2, however, when opened in notepad, data seems to remain inside.** 

**(Refer to Computer Specs Below)**

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by turtletooth** [comment]
Can you share an ini file that isn't loading?

**Comment by MikioKimura** [comment]
Here! Sorry for the late reply, we've been busy with client work.
[MikioPSHotkeysV(2).zip](https://github.com/opentoonz/opentoonz/files/1083806/MikioPSHotkeysV.2.zip)

**Comment by turtletooth** [comment]
![loaded](https://user-images.githubusercontent.com/4576381/29006691-3ca45176-7ab2-11e7-9e35-ef8d7e39b754.PNG)

Sorry I haven't checked this earlier.  I just tested the file you shared and it worked fine.  It takes a while, but it worked.

**Comment by jpturcotte** [comment]
Recommend closing.

**Comment by RodneyBaker** [comment]
Closing as this issue should be resolved.
@MikioKimura please advise if that is not the case.
