### ISSUE TITLE
Colour Model only accepts image over 1000pixels?

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1274]

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by Rayek** [comment]
I cannot reproduce this. I saved a 10x10px PNG in Krita, and OT's color model window loads it effortlessly.

**Comment by turtletooth** [comment]
Also can't reproduce.

**Comment by artisteacher** [comment]
I'm not having this problem in OS X.

**Comment by jpturcotte** [comment]
Recommend closing.
