### ISSUE TITLE
(Proposal) SVG Gradient Fills

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1275]
## **SVG files with gradients or groups from various software's doesn't work.** 

**The solution, possibly, is in the style editor a more flexible specials gradient swatch where you can have more colours than just two by adding and subtracting swatches.** 

**Also the settings tab for the gradient swatch in the style editor needs to be able to scale larger than 100, perhaps a 1000, perhaps more, perhaps... infinite?**

**Other vector programs can create groups and opentoonz can do the same so this should be a simpler fix to read grouped vector graphics on import.**

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by artisteacher** [comment]
Grouped svg's from Adobe Illustrator and Affinity Designer work just fine in OT at least in OS X Sierra. Gradients in the svgs display as a solid color.

**Comment by RodneyBaker** [comment]
I note that SVG images converted out of OpenToonz (from PLI to SVG) tend to work much better in other programs than do SVG images from other programs imported into OpenToonz.

A number of SVG PRs are pending which will address the majority of these issues.

Retitling this report "SVG Gradient Fills" to focus on gradient issues that might still be open after the PRs are merged.

**Comment by RodneyBaker** [comment]
This enhancement/refinement to SVG format is slipping to 2019 development cycle.
