### ISSUE TITLE
Option in prefs Doubled for Cell-Dragging Behaviour

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1276]
## **In the Xsheet menu for the preferences window  both options in "Cell-Dragging Behaviour", are repeated in the drop down menu.**

![preferences_xsheet_cell-draggingbehaviour doubles options](https://user-images.githubusercontent.com/19598708/27067974-dcc1d872-5050-11e7-962b-2d17e2723262.png)

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by turtletooth** [comment]
This has been fixed.
