### ISSUE TITLE
Clipping Text when in Selection Mode

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1277]
## **Selection Mode menu can’t be read because it gets cut off sometimes - icons will solve this issue and would be better for other languages.**

![clippingtextin selectionmode](https://user-images.githubusercontent.com/19598708/27068031-37e112a4-5051-11e7-928b-5077e7e136e9.PNG)

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by artisteacher** [comment]
This is related to #1977 - options in the tool option bar can get cut off when other tools are active too.
