### ISSUE TITLE
Popup window annoyances!

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1278]
## **Every popup window/menu should appear in the middle of the main program window for multi-monitor setups; Occasionally a pop up will appear behind a windows toolbar where it is inaccessible.**

![windowpopup](https://user-images.githubusercontent.com/19598708/27068229-4c112254-5052-11e7-9316-853673f42050.png)

**Comment by MikioKimura** [comment]
This Bug appeared on these computers
 
**Desktop Computer 1 specs**
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz
 
**Desktop Computer 2 specs**
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz
 
**Surface Pro Computer specs:**
Operating System: Windows 8
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz
 
**Surface Pro 4 Computer specs:**
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by turtletooth** [comment]
I fixed the inaccessible popups in #1287, but I disagree that all popups should load in the center.  They currently load where they were moved to.  #1287 makes sure that all popups are visible and load on the active monitor every time OpenToonz starts, but if they are moved to a different monitor, they will load there later during that session.
