### ISSUE TITLE
Bug: Cleanup doesn't work

### ISSUE THREAD

**Issue by hraider** [opentoonz/opentoonz#128]
I tried to cleanup some png files I loaded into toonz but no matter what the settings are all I get is a blank tlv file. Also whenever I try to open the info of the tlv file toonz crashes.

I'm using Windows 8.1 thank you very much.

**Comment by odysseywestra** [comment]
@hraider thanks for the bug report. Could you provide a 15-30 video to illustrate what you mean? Plus let us know which version you are using.

**Comment by jay3d** [comment]
Yes, I faced the same issue, then I uninstalled 1.0.1 and reinstalled 1.0, it doesn't happen with v1.0
I think something changed that broke TLV saving in 1.0.1

**Comment by kogaki** [comment]
@jay3d thanks for the report. Could you try latest `nightly build` from https://github.com/opentoonz/opentoonz/releases ? This version fixes some bugs about saving.
If bugs are still there, could you show us sample scanned image if you don't mind?

**Comment by jay3d** [comment]
![image](https://cloud.githubusercontent.com/assets/2527637/14805333/ed5765d4-0b38-11e6-94a6-e727be54937b.png)

I think the issue is fixed! Thanks a lot Keisuke-san :smiley:
