### ISSUE TITLE
Playback Operations Separted between Viewer and Combo Viewer windows

### ISSUE THREAD

**Issue by MikioKimura** [opentoonz/opentoonz#1284]
## **Confusingly if both the viewer and the combo viewer windows are open and playback is initiated in one of these view windows It cannot be paused in the other.**

**Perhaps this is not a bug but I and the artists I work with don't believe playback should work this way.**

**Comment by MikioKimura** [comment]
This Bug appeared on these computers

Desktop Computer 1 specs
Operating System: Windows 7 unlimited SP 1
Ram: 32 gigs of ram
Screens: Wacom Cintiq DTZ 2100, Viano TV, Samsung computer screen
Graphics card; GTX 960
Motherboard Intel core i5-2400 CPU @ 3.1GHz

Desktop Computer 2 specs
Operating System: Windows 10 Pro
Ram: 16 GB
Screens: 2 Dell Monitors and a Huion Gt 220
Graphics Card: GeForce GTX 970
Processor Intel Core i5-6500 @ 3.20GHz 3.20Ghz

Surface Pro Computer specs:
Operating System: Windows 7
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-3317U CPU @ 1.7 GHz 2.6 GHz

Surface Pro 4 Computer specs:
Operating System: Windows 10
Ram: 4 gb
Graphics card: Intel HD Graphics 4000
Processor: Intel Core i5-6300U CPU @ 2.4 GHz 2.5 GHz

**Comment by artisteacher** [comment]
The same thing happens with 2 viewers in the same room.

**Comment by gab3d** [comment]
Perhaps there could be an option in Preferences so that playback only ocurs in the viewer where the Play button is hit (or the active one when the play/loop shortcut pressed).
Just thinking out loud...
