### ISSUE TITLE
Import project folder automatically

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1290]
Windows 7, OT 1.1.3

If i have a project in another computer and i want import that in my computer (by paste project folder in my projects path or if i duplicate a project folder). OT can't recognition project folder.

![import project folder 1](https://user-images.githubusercontent.com/16509592/27264067-032b0094-548c-11e7-9f3d-9473db63f1aa.jpeg)

![import project folder 2](https://user-images.githubusercontent.com/16509592/27264069-0be67632-548c-11e7-9e8f-80d2f1458c1b.jpeg)

**Comment by tghart** [comment]
you cannot import folder. but you can import image sequence in folder, if your image organized.

For example.
i have image sequence.
and i named kuda.0001- kuda.0361

note.

" **.** " and " **0001** "  very important

![giphy](https://user-images.githubusercontent.com/25517443/27311584-12071fca-558c-11e7-92b8-7324824ba07a.gif)

**Comment by artisteacher** [comment]
If the name of the project folder is the same on each computer, does it still not recognize that the imported project is a project? I've had the same problem with trying to duplicate a project folder from the file system but I've been able to move projects between computers without issue. I usually zip/compress the project folder & then unzip on the new computer.

**Comment by 2dvision** [comment]
Sorry guys, It was my fault. The project folder name and XML file name should look similar.

![project folder name](https://user-images.githubusercontent.com/16509592/27836663-a95fd21c-60f5-11e7-93bc-96cf445da25b.jpg)

> It would be great if a non-project folder is selected, a dialog asked if the user would like to make this a project folder & then the normal project settings could be opened.

👍
