### ISSUE TITLE
Is this a bug? (Selection tool)

### ISSUE THREAD

**Issue by MaxMixBug** [opentoonz/opentoonz#1292]
![image](https://user-images.githubusercontent.com/29537858/27277961-b591e8b8-54e8-11e7-94ea-ac466a8f1236.png)
![image](https://user-images.githubusercontent.com/29537858/27277980-caa19cbc-54e8-11e7-86ee-59c270e98cc0.png)
![image](https://user-images.githubusercontent.com/29537858/27277985-cf326d10-54e8-11e7-83e4-b2dd24a81b9e.png)

**Comment by MaxMixBug** [comment]
![image](https://user-images.githubusercontent.com/29537858/27278525-521846cc-54ea-11e7-98c6-9da6285df2fb.png)
![image](https://user-images.githubusercontent.com/29537858/27278532-57e33fbc-54ea-11e7-9f88-f645f74de4b6.png)
![image](https://user-images.githubusercontent.com/29537858/27278540-5e9bdaee-54ea-11e7-8b18-10f1597dd81c.png)

**Comment by beeheemooth** [comment]
Oh... that thing also makes me crazy )

**Comment by tghart** [comment]
If it's raster type, it's like that when in selection tool

**Comment by MaxMixBug** [comment]
@turtletooth Can you fix it?

**Comment by konero** [comment]
What is the bug? I don't follow.

Raster layers have a bounding box which is that white line surrounding the image, that is the canvas size, anything outside of it will be cropped. To make it bigger, right-click the raster column and select **Canvas Size**.

Just think of how it works in Photoshop, its the same principle.

**Comment by MaxMixBug** [comment]
This is terribly inconvenient. In Photoshop at times more convenient. In Photoshop, you can immediately change the size and picture is not circumcised. .

**Comment by turtletooth** [comment]
This isn't a bug.  A raster type is an image of a fixed size.  Dragging a selection outside of the image area is going to crop it.
