### ISSUE TITLE
Images are all over the place

### ISSUE THREAD

**Issue by Shemmet** [opentoonz/opentoonz#1296]
When I import an image, it pops up like this. 
![moon](https://user-images.githubusercontent.com/29632864/27487561-1814fd92-5802-11e7-9585-b8ed263b6117.PNG)
And then when I zoom out it looks like this.
![mooon](https://user-images.githubusercontent.com/29632864/27487601-344d0446-5802-11e7-8bdd-816c9445cf77.PNG)
The pink crosshair stays in the same position, but the image itself changes in size and position with every zoom in/out. Can anyone help?

**Comment by artisteacher** [comment]
Can you give more information? What is your operating system and version of OpenToonz? Is your monitor high-dpi? Does this happen to all imported images or only certain types?

**Comment by Shemmet** [comment]
It happens to all imported images, I'm not sure what my DPI is, but my resolution is 1920x1080. My operating system is a 64-bit operating system, x64-based processor.

**Comment by RNavega** [comment]
Not sure if it makes a difference, but try changing this option: File -> Preferences -> Interface -> Pixels Only (All imported images will use the same DPI).

Reimport the image again after changing that setting.

**Comment by andiroo42** [comment]
I've come across this issue 1.1.3 on MacOS, but it seems to be related to my second display which is a standard resolution monitor. The zooming issue happens when I import a level or open a project on one screen and then drag it over to the other.

**Comment by Shemmet** [comment]
My issue was solved! Thank you!
