### ISSUE TITLE
Change the name of app in OSX to only "OpenToonz"

### ISSUE THREAD

**Issue by dadoprom** [opentoonz/opentoonz#1303]
Now it says "OpenToonz_1.1" - it is not correct and looks ugly :)
Also in OSX the "Quit OpenToonz_1.1" button in menu is inactive, it can not be clicked - not working...

These issues are on latest 1.1.3 OpenToonz...

**Comment by dadoprom** [comment]
![opentoonz-name](https://user-images.githubusercontent.com/19377506/27637275-7277b138-5c0f-11e7-877b-dbf7201834ae.png)

**Comment by artisteacher** [comment]
The quit button not working is part of an existing issue - #618. 

Is there a reason to include the version number in so many places? Most programs only specify the version number in the "About" pop-up. Specifying the version number in fewer places should be less to maintain whenever the program number changes.

**Comment by RodneyBaker** [comment]
Closing this as the version number issue has at least one open report as well as an ongoing PR that is set to address the problem.  The PR is specifically focused on external filenames so we can reopen this issue as necessary.

See:  PR #2410
