### ISSUE TITLE
Adding music

### ISSUE THREAD

**Issue by prinxe210** [opentoonz/opentoonz#1310]
Im new to this program and im starting to get the hang of it the only issue i have right now is that im having trouble importing my music into the project. I have a screen shot of the message I keep getting because its hard to explain in my own words but this is what i've been getting. Does anyone know what this means or know how to help???
![screenshot 21](https://user-images.githubusercontent.com/29809751/27763873-c7626ec4-5e51-11e7-8370-b39f2b23b02f.png)

**Comment by turtletooth** [comment]
It's asking if you want to load the file from its current location or move it to the project folder.

**Comment by prinxe210** [comment]
i know but even when i chose either option nothing loads or imports in it just gives me a blank box

**Comment by RodneyBaker** [comment]
Pleae see ongoing discussion in the forum.
