### ISSUE TITLE
Imported Image Offset

### ISSUE THREAD

**Issue by Shemmet** [opentoonz/opentoonz#1315]
When I import an image into Opentoonz, it doesn't stay in the same place when I zoom in/out, and when I zoom far in enough, the image gets cut off for some reason, like this: https://gyazo.com/346c0e0d240475dc1ec69466d10a0d24

I'm using version 1.1.3 (obviously).

**Comment by turtletooth** [comment]
Duplicate.

**Comment by Shemmet** [comment]
What do you mean duplicate?

**Comment by RodneyBaker** [comment]
> What do you mean duplicate?


The issue (this report) has been reported before so therefore is a known issue and the new report a duplicated report.
