### ISSUE TITLE
Opacity in Animation

### ISSUE THREAD

**Issue by Shemmet** [opentoonz/opentoonz#1320]
I can't seem to figure out how get an imported image to fade in/out.

**Comment by RodneyBaker** [comment]
Look here in the forum for the standard approach:

https://groups.google.com/forum/#!topic/opentoonz_en/dHhGrobj-t8

Tne short answer is to add FX via Schematic.
For step by step instructions see the link above.

The poster of that topic refers to a second option but I'm not sure I follow that short of using the Stage Listing to drill down to the Transparency FX (once added) and then adjust/animate the values.

Closing.
