### ISSUE TITLE
What's the red and green cirlce?

### ISSUE THREAD

**Issue by Shemmet** [opentoonz/opentoonz#1321]
I just don't really know what this is, what it does, or anything at all. 
![image](https://user-images.githubusercontent.com/29632864/27989216-2a7941a8-6402-11e7-81f1-e1bf34fa23a2.png)

**Comment by RodneyBaker** [comment]
As these are not bugs, these questions should be posted in the main forum.  :)

The Red and Green circle is an indicator of the Onion Skn feature in the Xsheet.
Red is for past frames and green is for future frames.
In your image no frames have been identified to display but cliking above or below that red/green circle will turn the various frames on/off.

The red/green circle displays which frame we are currently on.

In this way we can animate with onion skinning directly via the xsheet.

Recommend Closing (I don't appear to be able to close any issues these days)
