### ISSUE TITLE
Impossible to write decimal number with keyboard (Geometry and brush tool) the point is not recognized

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#1326]
Hi,

I don't know why decimal number (with 0) don't works for me. It's seems limited to 0.43. I can't go down below, and the line becomes invisible.

I tried 0.01 untill 0.9 but that don't works. And all decimal number with 0 above 0.43 = 0.43 size. Brush tool has same issue, but it's less problematic than others tools.

In harlequin no problem, I do something in wrong way ?

**Comment by tghart** [comment]
In Vector Level, You can use size brush min. 0 
In Raster Level, You can use size brush min. 1

**Comment by openanim** [comment]
i don't want use 0 on vector level but for exemple 0.1 ? 0.2 and this way that don't works why ? In harlequin we can do until 0.01 on vector level, that why im surprised, and thought i done something in wrong way or there is a bug as that was suggested.

**Comment by tghart** [comment]
can you give me screenshoot when you make 0.1 size geometric tool?

because in my opentoonz can work 0.1

![yes](https://user-images.githubusercontent.com/25517443/28066958-5097cf30-6669-11e7-9f95-1b7798625a93.jpg)

**Comment by RodneyBaker** [comment]
@yghart said:

> can you give me screenshoot when you make 0.1 size geometric tool?
> 
> because in my opentoonz can work 0.1

Can you preview that and still see the lines?
I can work with the sizes mentioned as well BUT... the issue I see (at least with initial testing) is that those sizes don't preview or render.

**Comment by openanim** [comment]
@tghart Are you sure the sizes are different ? Because i can put the decimal number but the render don't change, it's same size as 0.43 size . [https://1drv.ms/v/s!AspsYffPSwbdhuEu_B7kjRqxixAmFQ](url)
[https://1drv.ms/v/s!AspsYffPSwbdhuEtQY7b4WsSBtlK8Q](url)

@RodneyBaker  i just reinstall too but nothing has changed. Are you sure 0.01 - 0.9 the sizes are different ? For me it's the same size like 0.43 size. When you use the cursor the size, what size does it offer after the 0?

**Comment by RodneyBaker** [comment]
Well...
I was getting different thicknesses but I am surely not getting them now.
Perhaps I accidentally was using a different tool.
I had started with .9 and then experimented with random numbers thereafter.

As for this exact moment:
I can confirm that I'm seeing the same thickness for values of 0.01 through 0.09 using the polyline option on geometry tool.

**Comment by tghart** [comment]
this is work :smile: 

do you already click preview button?

![screenshot_1](https://user-images.githubusercontent.com/25517443/28070305-96662d2e-6676-11e7-9c0f-d56e6d5e9819.png)

**Comment by openanim** [comment]
@RodneyBaker i noticed something, when i use cursor size. That works step by step something like that : 
0 - 0.43 - 0.85 - 1.28 - 1.71 etc And when we want use a value between 0 and 0. 43 we obtain the higher value so 0.43 same thing between 1.28 and 1.71 for exemple. if you begin line to 1.28 size then 1.75 and you want then 1.29, you will see same size that 1.71 . same if u go down.  Its very random. 
Can you confirm for you ?

**Comment by RodneyBaker** [comment]
I'm having a hard time confirming as I'm now getting different sizes for
each setting.
I will say though that the differences between some of these small sizes
are so incremental (and tiny) that I'm not entirely sure about the utility
of such refinement.
I need a higher resolution monitor!

We need someone with a view and understanding of the code to look through
that code and see if there might be some rounding or other math that might
be producing inconsistent results.  Perhaps something will stand out to
them.

My last test was drawing a single polyline and then (after making sure I
click on the slider tab) using the arrow key on the keyboard to move up one
increment.
That arrow key movement adjusts the thickness by 0.01.
In each case the drawn line appears to get thicker although it is hard to
see any difference in lines until several hundredths change.

**Comment by openanim** [comment]
look that process to see the difference.
in harlequin : i done 0.9 - 0.5 - 0.43 - 0.2 - 0.1 by using numeric keyboard not the cursor. And that works fine 

https://1drv.ms/v/s!AspsYffPSwbdhuEwv70IDox5fGwX9g

Now in opentoonz look when i use the cursor and when i use numeric keyboead . 
i done 1.75 -1.28 -0.85 - 0.43 - 0 by using cursor and same thing by using numeric keyboard.

Something works wrong.

https://1drv.ms/v/s!AspsYffPSwbdhuEvnSRIdDGX6IjhNQ

**Comment by RodneyBaker** [comment]
I'm not quite getting what you are and I don't seem to be getting closer to
an answer that accounts for the differences.

The good news is... (or bad news depending on perspective) is that I
believe you've adequately demonstrated that -something- is wrong.

**Comment by openanim** [comment]
@RodneyBaker  Other chose, I dont' know if it can help but I notice that when I use the selection tool, I can change the value of the thickness using the point from my numeric keypad to write a decimal number . While for geometry tools, I can't use it. So I was wondering if not being able to use the "point" from the numeric keypad was not the source of the issue ?

**Comment by turtletooth** [comment]
I'm working on the geometry tool anyway today, so I can take a look.  But I can't actually understand what the issue is.  I have tried on the rectangle and polyline typing in values between 0.1 and 0.9 and I seem to be getting different sizes and it all previews fine.  Can someone give step by step instructions about what I'm missing?

**Comment by openanim** [comment]
@turtletooth can i know your process ? when i change the value of thickness with my mouse that works strangely in random way. I tried arc, line, rectangle same thing. 

look that process to see the difference.
in harlequin : i done 0.9 - 0.5 - 0.43 - 0.2 - 0.1 by using numeric keyboard not the cursor. And that works fine

https://1drv.ms/v/s!AspsYffPSwbdhuEwv70IDox5fGwX9g

Now in opentoonz look when i use the cursor and when i use numeric keyboead .
i done 1.75 -1.28 -0.85 - 0.43 - 0 by using cursor and same thing by using numeric keyboard.

https://1drv.ms/v/s!AspsYffPSwbdhuEvnSRIdDGX6IjhNQ

and i tried again with rectangle you can see my process here 

https://1drv.ms/v/s!AspsYffPSwbdhuExayioVhflogpnUA

**Comment by turtletooth** [comment]
Thanks @openanim I'll take a look.

**Comment by turtletooth** [comment]
![line](https://user-images.githubusercontent.com/4576381/28091864-a63797b0-664e-11e7-9594-7274da1a3f64.JPG)

Here is my line tool at 1.75 1.28 0.85 0.43 .1

**Comment by openanim** [comment]
@turtletooth 

Can you repeat the same exercise but with sizes 0.4 0.3 0.2 0.1? or this 
https://1drv.ms/v/s!AspsYffPSwbdhuEwv70IDox5fGwX9g
my aim from the begenning is to be able to draw lines below the size 0.43 like 0.1 - 0.2 - 0.3 and when I try to make the sizes that become either invisible or the lines have the same size 0.43 in opentoonz.

**Comment by turtletooth** [comment]
Here is .9 .5 .43 .2 .1 just like your video:
![line2](https://user-images.githubusercontent.com/4576381/28101832-585ab650-6688-11e7-813d-4ab26418f6e3.JPG)

**Comment by openanim** [comment]
@turtletooth i don't understand....I tried again and again, reinstall again nothing works for me, can you show me your process please. In this video below, you can see all my actions, what im doing wrong ?  Do I know what key you use to write the "point" of the decimal number ? I can't use that from my numeric keypad (azerty).

https://1drv.ms/v/s!AspsYffPSwbdhuE1qwjsCmaKZGL6Mw

My steps :

I launch opentoonz, then:

1 - I chose line in geometry tools

2 - I draw the first line at 1.71

3 - I use my mouse to position my his cursor without erasing the point (because the point key of my numeric keypad is not recognized by opentoonz)

4 - I continue this process to make the following lines but as you can see, I just can't do the same thing as you do.

**Comment by artisteacher** [comment]
Maybe you are doing everything correctly and it is a bug specific to your operating system? In OS X 10.12.5, I'm able to get sizes down to .01. At that scale the difference in sizes is very subtle but is there. 

I've also found that I can't use my period key when trying to set a decimal in the geometric tool. I can in the brush tool, so it might be something to do with how the geometric tool is programed.

**Comment by konero** [comment]
Works OK for me.

Something seems wrong on your end, when the Flipbook widget is docked it shouldn't be displaying the minimize button, should it? I'm curious of what happens if you press it.

**Comment by openanim** [comment]
@artisteacher  
Yes when I use Harlequin I can also reach 0.01 but as you say I don't know  but it seems that the problem comes from my configuration actually. It's somewhat reassuring. I will try to do the windows creator update in the next few days to see.
@konero nothing happen :) 
Ok thank  guys, now it seems obvious that the problem comes from me. I will try to find a solution. Thank you for your patience

**Comment by konero** [comment]
@openanim I discovered the Flipbook minimize button shows up when launching OpenToonz with it already docked. I didn't notice that before, sorry, that's not a problem on your end at least.

**Comment by openanim** [comment]
@konero No problem man ;)

**Comment by openanim** [comment]
I can use the arrow keys from cursor size to use small sizes, (untill 0.01 it's works fine) waiting to see if my windows update will solve the problem with my numeric keypad :)
