### ISSUE TITLE
Pick every colors as different style don't works 

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#1333]
Hi,

In the loading preferences panel we can choose between 2 options for colors models, but the option "pick every colors as different `style" don't works. It's the same result that integrate similar color as one style. Actually nothing change. In harlequin, that works perfectly. It's seems be a bug ? below an exemple.

https://1drv.ms/i/s!AspsYffPSwbdhvJRUqWgFz7TAN2FZA

**Comment by artisteacher** [comment]
I'm getting different results with the 2 different settings in OS X, though I would expect the "integrate similar colors) option to create a smaller number of styles.

**Comment by shun-iwasawa** [comment]
For now, on "pick every colors as different style" mode, if the number of picked colors becomes more than 256, then it stops picking colors and restart picking with the "integrate similar color as one style" mode.
I think the limit can be extended (for instance, to 4000. As the style index cannot be more than 4095 ).

**Comment by shun-iwasawa** [comment]
The limit is set in [here](https://github.com/opentoonz/opentoonz/blob/63610baef46236317dce5f7ecc9a7a80f0b5099c/toonz/sources/toonzlib/palettecmd.cpp#L893).

**Comment by RodneyBaker** [comment]
Review:  This is a known and documented bug not yet assigned.
Status:  Low priority.

Workaround:  Value can be manually changed in the code at known location ([link](https://github.com/opentoonz/opentoonz/blob/63610baef46236317dce5f7ecc9a7a80f0b5099c/toonz/sources/toonzlib/palettecmd.cpp#L893)) prior to build.
