### ISSUE TITLE
Play Animation to Crash

### ISSUE THREAD

**Issue by tghart** [opentoonz/opentoonz#1334]
When I make many Frame and then play Animation, Opentoonz will be crash.
same as when i render animation too.
![goo](https://user-images.githubusercontent.com/25517443/28400549-121b0d72-6d3e-11e7-9543-64da99977c14.png)

**Comment by RodneyBaker** [comment]
@tghart Please let us know if you are still experiencing this issue.
Thanks!

If you need some assistance please visit the Opentoonz forum a discord channel (for chatting) or add an update here.
