### ISSUE TITLE
Glicth using Plastic Tool

### ISSUE THREAD

**Issue by jeneverito** [opentoonz/opentoonz#1337]
By testing the "Plastic tool" I discover an error, the whole image is a glitch to the exception of the image with the active skeleton.
[GlitchPlasticTool_video.zip](https://github.com/opentoonz/opentoonz/files/1166955/GlitchPlasticTool_video.zip)

 under UbuntuStudio 14.04 32 bit and OpenToonz Morevna edition

Thanks in advance

**Comment by turtletooth** [comment]
This is a duplicate of #1096 
Closing.
