### ISSUE TITLE
Timeline UI bugs

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1338]
I'm loving the new timeline variant of the Xsheet - thanks so much @manongjohn for getting this finished! I have noticed a couple small UI issues. Some of these might be OS X specific.

The text in the timeline/xsheet toggle button is slightly cut off on each end:
<img width="92" alt="screen shot 2017-07-20 at 12 54 13 pm" src="https://user-images.githubusercontent.com/21159116/28430045-fc903eaa-6d4c-11e7-91b9-d66b4173b4ef.png">
<img width="74" alt="screen shot 2017-07-20 at 12 54 25 pm" src="https://user-images.githubusercontent.com/21159116/28430046-fea09744-6d4c-11e7-838e-59ffaef77bef.png">

The drawing number can overlap the level name, or the ~ that represents a longer name. Keyframes can also overlap the level name.
<img width="51" alt="screen shot 2017-07-20 at 12 58 58 pm" src="https://user-images.githubusercontent.com/21159116/28433252-eb4bf268-6d58-11e7-8430-0180e63d4837.png">

**Comment by manongjohn** [comment]
Not sure but the button issue is more likely OS X specific in that its a different font used than on Windows so it takes up more room. I sort of happened in Windows when I accidentally shrunk the button.

Unfortunately I don't have a Mac to test on but will see what I need to change to widen that button's text field without changing button width so it looks right on OS X. I think it just needs to be widened about 10px to be safe?

The name issue is in both platforms. Will fix.

I'll wait a little bit on submitting fixes to see if any more things need to be fix.

**Comment by artisteacher** [comment]
10px would probably be fine but after some measuring I recommend 12px. Thanks!

**Comment by 2dvision** [comment]
What do you think if remove timeline/xsheet toggle button and add this to windows menu?

![timeline-ui-01](https://user-images.githubusercontent.com/16509592/28516276-e090623a-7075-11e7-9175-dd4a10219b40.jpg)

 I think we have more horizontal space in timeline.

![timeline-ui-02](https://user-images.githubusercontent.com/16509592/28516275-e07d7cd8-7075-11e7-982f-d1770e766529.jpg)

**Comment by artisteacher** [comment]
@2dvision it may make more sense to rename the xsheet in the window menu to something like Xsheet/Timeline 

@manongjohn, I found another small issue that's only noticeable when using the dark theme. In the xsheet view, there is a border that divides the xsheet from the xsheet toolbar. In the timeline view, the toolbar blends into the timeline. In the other themes the toolbar has a different background color than the timeline so it's not an issue.
<img width="309" alt="screen shot 2017-07-27 at 5 29 06 pm" src="https://user-images.githubusercontent.com/21159116/28693361-3bf21a96-72f2-11e7-96a7-74ec5e4cc6c7.png">

**Comment by manongjohn** [comment]
I was also thinking of changing Xsheet -> Xsheet/Timeline in the Windows menu so people know thats how you get to it, though an entry that immediately puts you in timeline mode is more UI friendly. Hmm...

I'll see what is the best way to fix that issue with dark theme.  Might just be a stylesheet change.

Btw, I think I need to fix the cut off button label with a stylesheet update to change the padding for Macs...once I figure out how to set that up.

**Comment by manongjohn** [comment]
@turtletooth @artisteacher I think I have a stylesheet fix for the xsheet/timeline toggle button text issue, but not sure if it's right since I don't have a mac to test it on.

Would you be able to put the following in the stylesheet of the theme you are using and see if it fixes it in both modes?

#flipOrientationButton {
  padding: 2px 15px;
}

It's the minimal padding I can do that works on my machine. If it does work for mac, I'll included as a general fix in my upcoming PR for xsheet bug fixes.

**Comment by artisteacher** [comment]
Padding: 2px 12px; works on my mac.

**Comment by artisteacher** [comment]
Just noticed this when looking @konero's most updated light theme: the memo button overhangs the other buttons in the timeline.
<img width="86" alt="screen shot 2017-08-04 at 6 29 55 pm" src="https://user-images.githubusercontent.com/21159116/28989417-2fd7a3f0-7943-11e7-8afa-55483754a3bc.png">
This actually occurs in all the themes but stands out in the light one.

**Comment by manongjohn** [comment]
Fixed.
