### ISSUE TITLE
Bug: Viewport drawing - vector and raster levels attached to a mesh node get a black alpha

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#134]
When you attach multiple levels to a mesh level, you get black color instead of alpha in the viewport:
![opentoonz-glithch](https://cloud.githubusercontent.com/assets/6495061/14235397/2835cdee-f9f5-11e5-8d11-f5dfe78f217b.JPG)

This applies to whether you attach a single level or many drawing levels to the mesh level. It is most noticeable when you actually get to see the alpha - on a drawing that is smaller than the mesh.

Fortunately this is only a viewport bug - when you render the scene the alpha renders properly and the black color is gone.

**Comment by blurymind** [comment]
This is definitely a regression bug. The alpha worked on toonz harlequin:
![blackbgregressionmesh](https://cloud.githubusercontent.com/assets/6495061/14704927/124d2dd4-07af-11e6-8955-a9602e633c3c.JPG)

**Comment by Rayek** [comment]
A workaround is to create your character in a sub-sheet. No issues in that case.

**Comment by blurymind** [comment]
@rayek thank you for the workaround. I will try it out. Mighr also be a hint of whats causing the glitch

**Comment by Rayek** [comment]
Unfortunately, in the latest build a subsheet with a mesh animation crashes TOonz instantly!

**Comment by blurymind** [comment]
This was fixed in today's nightly build. The fix however introduced two new serious bugs:
https://github.com/opentoonz/opentoonz/issues/253
https://github.com/opentoonz/opentoonz/issues/254
