### ISSUE TITLE
Interested in starting a bounty for Vanishing point drawing an Mirror drawing tools

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#1341]
It'd be nice to have something like the assistant tool in Krita that can allow users to draw backgrounds in perspective rather easily. All the way up to fisheye perspective tools.

Here's a video that shows some of what the assistant tool is capable of in Krita: https://www.youtube.com/watch?v=Zc7xatDNc4A

This is more with Krita and what it can do:
https://www.youtube.com/watch?v=uByCdWXCyhs

There's also Sketchbook Pro which has similar tools -- but to be honest, it's not as versatile as it is in Krita -- although Sketchbook makes a smoother drawing experience with less features and customization:

https://www.youtube.com/watch?v=r96G15n08Y4&feature=youtu.be

If posed with an option between the two, I'd pick Krita's setup over Sketchbook Pro's.

Also -- the Mirroring and Wrap capabilities in Krita are pretty powerful and it'd be amazing to see something like this in Opentoonz as well.

Wrap tool demo:
https://www.youtube.com/watch?v=q6S2q_or4k4&feature=youtu.be

Morror tool demo
https://www.youtube.com/watch?v=m0r5WbQn9wQ

The main issue is that Opentoonz is experiencing heavy use when it comes to animations, but when creating backgrounds, users are reverting to other software in order to create the backgrounds. With the new Mypaint integration, it seems as though we have the capabilities to make some amazing work of art in Opentoonz, but making backgrounds is still a huge limitation.

Now... I've never made a bounty before. But I AM interested in seeing about getting funding for someone here to work on it. I'd want whoever works on his to get paid WELL, as long as the new features introduced are super stable.

**Comment by jpturcotte** [comment]
I totally support this proposal, and I would be ready to back a bounty too. I think this would also be great for animating. It has already been asked for in the past (see #1181). Is anyone interested?

P.S. @Orphanlast, you might want to close #1349, which seems to me like a duplicate.

**Comment by blurymind** [comment]
It would be useful for drawing backgrouds - especially the perspective/3d
grid stuff

**Comment by turtletooth** [comment]
This has an active bounty here:
https://www.bountysource.com/issues/47570103-interested-in-starting-a-bounty-for-vanishing-point-drawing-an-mirror-drawing-tools

**Comment by jpturcotte** [comment]
Sorry, @turtletooth, I should have checked on Bountysource beforehand. However, I still do not see the difference between this one and #1349. Is the latter more expansive?

**Comment by Orphanlast** [comment]
Let's support my other bounty. Morevna won't support the mirroring tools but will support the assistant tool.

**Comment by morevnaproject** [comment]
@Orphanlast Yes, we can get back to this one after we get Assistant Tool done. ^__^

Issue for Assistant Tool - #1349 
Bounty for Assistant Tool - https://www.bountysource.com/issues/47719781-krita-like-assistant-tool-for-opentoonz

**Comment by manongjohn** [comment]
@Orphanlast You closed this issue back in Aug, but I think there is an unclaimed bounty of $10 on it still, by you. Did you close it in such a way that you got refunded?

**Comment by Orphanlast** [comment]
I did not...

**Comment by morevnaproject** [comment]
@Orphanlast  I believe you can click "Claim bounty" button here - https://www.bountysource.com/issues/47570103-interested-in-starting-a-bounty-for-vanishing-point-drawing-an-mirror-drawing-tools

Since you are the only backer, so you can then accept the "solution" and the bounty will be added to your bountysource balance. I believe you can re-use it for other bounties then.

**Comment by manongjohn** [comment]
Want me to try this? ...I will temporarily reopen this and see if bountysource will reopen automatically. When it reopens, I will add the "Won't fix" label and close it. If their FAQ is correct, Bountysource should then refund you, I believe.
