### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by Shemmet** [opentoonz/opentoonz#1344]
So, I have a laptop I use to animate, and I use it in tablet mode. The issue with this is that I can't find any way to undo something without using CTRL Z. If there's a way to undo something without using the keyboard, I would love to know.

**Comment by RodneyBaker** [comment]
The primary way to Undo is to go to Edit>Undo on the menu.
Control Z is the shortcut to that funcitonality.

**Comment by RodneyBaker** [comment]
It may be appropriate to re-title this issue as "Feature Request:  Undo Button" and then close it as feature requests are to be discussed in the OT Forum where they await a champion that will program the feature.  The feature should be relatively easy to implement and might be a good task to take on by programmers trying to get a feel for coding for OpenToonz.

The forum discussion *could* delve into how to build an optimized Undo with History.  I've seen and use this in another application and it is great stuff... and has related use with camera work too!  In other words, we shouldn't think of Undo so much as History in that we want to be able to scroll forward and backward through time.  The concept of Undo is limited to correcting mistakes/errors which, at least theorectically, is a bad thing as we often learn more (and more deeply) through our mistakes than we do through our successes.  So... yeah.... no Undo button... lets go for the whole enchalada and create an Undo stack that allows us to access our project's History.

![history vs undo](https://user-images.githubusercontent.com/2576432/28811568-c0cc7372-7655-11e7-80f4-4764ed85cd07.png)


The only way I know to Undo without using the keyboard is via the menu, navigating from Edit to Undo.

Recommend closing.
