### ISSUE TITLE
Bug with "Hide All" audiolevels in Xsheet / Timeline

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1354]
When using the command "Hide All" (both in Xsheet and Timeline), the levels containing audio files continue to work when the frames are scrolled. They "hide" when you apply two commands: "Hide All" and "OFF All".
As I recall, this was not before.

The "Soundtrack" button in the Viewer window turns off the sound only when playing a scene. If you scroll frames in Xsheet, the sound is still reproduced. In my opinion this should not be, since the "Soundtrack" button is (as I know) the only one that can turn off the general sound if you have a lot of audio tracks. Sometimes editing frames is easier to do "in silence", and you have to manually turn off (and turn on) all audio levels. Is it possible to mute the sound with the "Soundtrack" button when scrolling frames? Users pressing a button can decide for themselves whether they need to hear the sound at the moment of animation editing, or not.
 (I hope, I correctly stated the idea)

**Comment by manongjohn** [comment]
I just tested the official 1.1.3 release. The sound still plays there also when you "Hide All". It doesn't play sound if you click the button directly to turn it off.  Seems the bug is in "Hide All".  Sound still plays if you turn preview off or use "Off All". Not sure if that is intentional.
