### ISSUE TITLE
Feature Request: Nudge forward/backward (overload current operators)

### ISSUE THREAD

**Issue by snapai** [opentoonz/opentoonz#1358]
Right now, Bring Forward / Send Backward are disabled in the Edit menu when using the Edit/Animate tool, since they currently only function for selected vector elements using the Selection Tool.

Could these commands be enabled for the Edit (Animate) tool, and simply nudge the stacking order forward or back on the current level & frame, say by 0.1?

It'd be useful for sorting layers as they're animated and need to change the order they display in (say an arm moving from behind to in front of a character).

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by jpturcotte** [comment]
Thank you for pointing that out! @shun-iwasawa or @turtletooth, could you make the modification, please?

**Comment by turtletooth** [comment]
Dragging on the label in the edit tool can now change the stacking order without having to type it in.  It's not quite what you asked for but is a workaround for now.
