### ISSUE TITLE
Brush jumps briefly after start of line

### ISSUE THREAD

**Issue by LaylConway** [opentoonz/opentoonz#1367]
Every time I start a new line, I'm getting a very brief moment where my tablet's input isn't registered, followed by quick jumps, resulting in the stabilizer creating a weird rounded straight section. This is happening in a raster level, I have not tested a vector level.

![](http://i.imgur.com/jaLUEFY.png)

I can not reproduce this problem in other drawing software, in for example Microsoft Paint the lines are smooth without issues.

Current workarounds:
- Keep retrying till the line is right
- Hold the pen in place for half a second before making the line

My system specs:
Microsoft Windows 10 Pro (10.0.15063 Build 15063)
Intel Core i7-3770 CPU @ 3.40 GHz
16 GB Physical RAM
NVIDIA GeForce GTX 970

**Comment by LaylConway** [comment]
After testing with vectors, I'm getting a similar but different result
![](http://i.imgur.com/t30tgm8.png)

**Comment by LaylConway** [comment]
Disabling windows ink in my tablet's setting seem to significantly improve this but not entirely eliminate it

**Comment by RodneyBaker** [comment]
Not sure if this is still a problem with the most recently nightly releases
@LaylConway Can you provide an update?

I note an Nvidia card being used in this case and updating the Nvidia driver is known to improve performance on some systems.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@LaylConway Please let us know if you are still experiencing any issues.
