### ISSUE TITLE
Feature Request: Fill tool on Raster Level

### ISSUE THREAD

**Issue by KirbsArt** [opentoonz/opentoonz#1372]
Does not work at the moment. Would be very nice to have.

Possibly add fill tool options seen in other programs like growth of a set amount of pixels when filling.

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
