### ISSUE TITLE
New and ongoing tablet issues on OS X

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1377]
@turtletooth @shun-iwasawa thank you both for your work to resolve the tablet issues. At first when testing out the latest build with the tablet fix, it looked like everything was working really smoothly. Unfortunately it did not last. I'm still getting both the unwanted input on hover and the menus becoming inaccessible, along with some new behaviors.

I do want to mention that even before this fix, I would run into the brush drawing by itself without any tablet being connected. Usually when the cursor left and then returned to the viewer. I don't use a mouse with my laptop, usually just the touchpad, so I can't say if this ever happens with a mouse.

Around when incorrect input started while hovering, a strange behavior occurred where the line I was drawing disappeared when I moved the pen away from the tablet and reappeared when I put it closer. Making a new mark completely replaced the previous one. This happened a few times in a row. This reminded me a little of #1077, but was a different experience.

One time after a hover issue occurred and the menu greyed out, disconnecting the tablet resulted in the brush, fill tools & etc. not working at all, until OT was restarted. 

Once the menu is inaccessible, it is impossible to close, minimize or maximize OT from the program window buttons (top left). An alert sounds, similar to when trying to select a tool or etc. when the startup popup is open. In the console, the following message pops up every time the close button (or minimize/maximize)  is pressed:
<img width="610" alt="screen shot 2017-08-04 at 11 02 32 pm" src="https://user-images.githubusercontent.com/21159116/28992450-56f15fc2-796a-11e7-8001-46c709efedec.png">
Since quit has never worked in the file menu #618, quiting from the docked icon results in a crash #1252, and the quit button in nonfunctional, the only way to quit without issue once this tablet issue occurs, is using the shortcut cmd-q. This really doesn't leave a good impression on tablet users.

Another time the brush was stuck at one thickness and ignored the pressure of the pen. Occasionally a line does draw without pressure but usually the next one draws correctly. In this instance, it would not. It's possible that is an issue with the pen, but it could also be OT.

On a positive note, I haven't run into #1058 yet, so it may be resolved.

The workflow with the tablet does seem to make a big difference. Having no auto-save and/or using shortcuts and the arrow key so that the pen stays in the viewer seems to minimize any issues.

I'll spend more time with the tablet over the weekend. In case anyone wants to quickly replicate the tablet issues:
- set auto-save to 1 minute
- draw on multiple cells in a vector level 
- navigate OT with the pen as much as possible (avoid using the keyboard/shortcuts)
- move the pen in and out of the viewer (or even OT)  frequently

**Comment by artisteacher** [comment]
Toonz raster levels also continue to have the hover and menu glitches, though the menu one occurs more frequently than the hover problem. A variation on the hover issue is that sometimes the fill bucket starts filling while still hovering. If the pen moves across multiple fillable areas while it hovers, they all fill. Sometimes the entire drawing fills with the color. Trying to undo works for a moment but then is filled right back in. The hover issue does seem to occur less often than on vector levels.

**Comment by turtletooth** [comment]
@artisteacher I'm wondering if the changes actually made it to the nightly since it was merged before Jenkins was called.  The fix in @shun-iwasawa PR seems very thorough.

**Comment by artisteacher** [comment]
@turtletooth, @shun-iwasawa, I tried downloading the nightly today and did another clean intall. So far there seems to be a huge difference! After a half hour + using the tablet on a vector level, the menu has not become inaccessible, and there has only been one instance of the hover issue (significantly less than before).  Anyways, I'll spend another day testing just to be sure, but this is very promising. Thank you both so much!

**Comment by artisteacher** [comment]
The menu issue seems to be completely solved! #1058 also has not been an issue. Occasionally the brush ignores the pen pressure on vector lines. Unfortunately I am still getting the hover issue when drawing/filling frame by frame on vector levels. Is anyone else still having issues? Still, this is great progress.

While testing, I let my 5 year old nephew use the tablet for the first time. He didn't have great control over the cursor placement so the sporadic pressure and movement in & out of the viewer triggered the hover issue a decent amount. If I tried to adjust something with the touchpad while he had the pen too close to the tablet, the hover issue was also likely to occur. It seems like user error with the pen definitely exacerbates the hover issue. Since I do run into the same thing with the touchpad, I think beyond user error, there's still something to be resolved in the code. With either the pen or touchpad, I'm most likely to have the hover issue after selecting or adjusting something in the Palette.

**Comment by artisteacher** [comment]
I did have a student run into the greyed out menu issue today, so it is still there but I do think it's much less frequent than before.

**Comment by artisteacher** [comment]
I’ve run into another glitch that seems related to tablet use. A couple times students have had the viewer get get stuck to the cursor. After that point, moving the mouse or stylus causes the drawing to move in sync with the cursor. This glitch makes drawing impossible without restarting. The viewer is not impacted in other rooms.
