### ISSUE TITLE
build warnings

### ISSUE THREAD

**Issue by damies13** [opentoonz/opentoonz#1379]
I noticed when running a build there are heaps and heaps of warnings, many of them look like simple things to fix so this issue is just for that.

None of these warnings cause the build to fail, but some look like they may do so in the future. I've also noticed that sometime the build fails on TravisCI because it takes too long, so resolving some of these may help with that?

When I'm finished with centralising the version number, I'll probably start trying to clean them up, unless someone beats me to them.

Here is some examples, I'll add more of the common ones as I find them:
- "warning: add explicit braces to avoid dangling else"
- "warning: using integer absolute value function 'abs' when argument is of floating point type" &  "note: use function 'std::abs' instead"
- "warning: '&&' within '||' [-Wlogical-op-parentheses]"
- "note: place parentheses around the '&&' expression to silence this warning"
- "warning: ... enumeration values not handled in switch"
- "clang: warning: ..... 'linker' input unused [-Wunused-command-line-argument]"

**Comment by damies13** [comment]
- warning: '...' is deprecated: first deprecated in

**Comment by artisteacher** [comment]
I've gotten a huge number of warnings too. A lot of them are for the same reasons as @damies13 mentioned. I've also seen:
- (35) warning: ... is deprecated: first deprecated in macOS 10.8
- (60) warning: ... is deprecated: first deprecated in macOS 10.9
- (9) warning: ... is deprecated: first deprecated in macOS 10.12
- (197) warning:  expression result unused ...

**Comment by RodneyBaker** [comment]
This issue should be reviewed in light of #3226 being merged.

**Comment by RodneyBaker** [comment]
Closing as the subject of current build warnings should be revisited in light of current code.
