### ISSUE TITLE
MyPaint brush icons really pixelated in the Style swatches (undecipherable)

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1389]
This relates to an ongoing (feature request) topic in OT Forum titled "Style Editor Improvements".  As MyPaint and UI enhancement is an ongoing part of development I submit this issue for consideration via github while discussions continue in the forum on this and other related issues.

The topic can be found here:  
https://groups.google.com/forum/#!category-topic/opentoonz_en/Zjif6kO98EQ

Disclaimer:  The original poster of that topic is championing specific improvements to the Style Editor that I largely don't address here because I see those as falling more into the realm of Palette usage.  Please keep that original intent by @Jane Eyre in mind because what I present here is filtered through me and what I think might be best.  Others can add their thoughts to clarify their positions.  Others will disagree but I don't see the Style Editor as being the ideal place to organize Styles (brushes or otherwise).  I think I see what @Jane Eyre is referencing with regard to pixelated icons at the bottom of the Style Editor and that pixelization is nothing in comparison to that of the icons in the Palettes where every Style that is ever used will be collected.

Firstly, let me say that MyPaint brushes are incredibly powerful and a joy to draw and paint with.  Their usage is only beginning as users discover them.  Perhaps more importantly, MyPaint brushes in OpenToonz are unique from any other application because of OpenToonz approach to color styling and that area will be where I place my emphasis for this issue.  

The Issue at hand:
MyPaint brush icons get really pixelated in the current/previous style swatches **at the bottom of the style editor**.

Note that @Jane Eyre's emphasis is on the icons in the Style Editor.  I'll let those speak for themselves and hope that gets addressed.  I see the pixelation at the bottom of the Style sheet as a minor irritation.  My greater concern would be that the MyPaint icons (Style swatches) **in the Palettes** aren't clear (or large) enough to express their content.  It is in the Palettes that I believe we should focus although see the discussion for other thoughts and emphasis.

Question1:  Can the pixelation of the preview icon at the bottom of the Style Editor (perhaps especially with MyPaint brushes) be assessed and addressed?

Question2:
Can an option for larger (perhaps square) icon swatches (Style icons) be added to the Palettes so MyPaint brushes aren't squashed and pixelated?  The size of the MyPaint brushes in the Style Editor tab appear to be ideal; very clear and decipherable.

Thanks for your consideration and please close this issue as you see fit.  :)

**Comment by artisteacher** [comment]
What about something more like this for the Style Editor? The icon could stay one size & the color could stretch.
![styleswatches](https://user-images.githubusercontent.com/21159116/29126581-c3e9e312-7cec-11e7-8b3f-38b1ed0e1f4b.png)
Similarly for the medium & large swatches in the palette:
![paletteswatch](https://user-images.githubusercontent.com/21159116/29126638-e99a0858-7cec-11e7-8765-e1afce100dd3.png)
The biggest issue with that is there would be less room for custom color names.

**Comment by RodneyBaker** [comment]
@artistteacher  Icon static... color stretch... I like that approach!  I especially like that your example swatch reveals both color and brush clearly.

Obviously the black text on dark blue in your second example won't be optimal.  As far as I can tell there is that mask that appears behind the lettering in the Palette swatches that assists with the reading of conflicting colors so I assume something like that might be used here as well.  

I must assume some aspects of the integration of MyPaint are still ongoing so this issue may be a premature request.    Any discussion about the ongoing use of MyPaint is welcome by me though.  I'm loving those brushes.   :)

**Comment by morevnaproject** [comment]
> Can an option for larger (perhaps square) icon swatches (Style icons) be added to the Palettes so MyPaint brushes aren't squashed and pixelated? The size of the MyPaint brushes in the Style Editor tab appear to be ideal; very clear and decipherable.

It is already possible to choose size in the Palette Panel tab. Just choose "Large Thumbnails View" element in the drop-down menu (button in the top-right)..

**Comment by artisteacher** [comment]
I wasn't paying close enough attention, in the actual palette without any brush set, that color does have white text.

**Comment by RodneyBaker** [comment]
@morevnaproject said:

> It is already possible to choose size in the Palette Panel tab. Just choose "Large Thumbnails View" element in the drop-down menu (button in the top-right)..

Yes, this is understood.  I should have been more specific.
It is those 'large thumbnail views' that actually are not large (or squarish) enough.
In looking at them again the one I see is particularly obscured by the text overlay.

**Comment by artisteacher** [comment]
Also, on high dpi monitors the larger palette swatches are even less clear.

**Comment by blurymind** [comment]
I agree that the stretching looks awful :o

**Comment by adamearle** [comment]
Yep it's pretty poor

Ad

**Comment by artisteacher** [comment]
I’d still like to see this addressed. I’ve been trying to figure out where to make changes to the icon display but haven’t had any success yet. Probably because I know next to nothing about C++... with html/css, this would be a cinch.

**Comment by RodneyBaker** [comment]
@artisteacher   Agreed.  I'd like to see an improvement here as well.
Since this issue was opened by me I figured I should follow my own advice and close it as it's not so much a bug... although inconvenient... as an enhancement.  As such it needs some R&D and we can do that here in this closed issue as well as other places.  Then when we get everything all collected and ready to implement we can open a PR for it and reference this issue (if applicable).

MyPaint integration is an ongoing development and as such it is a pretty broad category.
It will help where we can be as specific as possible.

I will say that the full fix is very likely to be something of a major overhaul of this and other aspects of how we interact with core and custom brushes.  Yet another huge subject.

Thanks for the input @artisteacher!

**Comment by artisteacher** [comment]
The swatches for the Mypaint brushes look to be set in mypaintbrushstyle.cpp in lines 159 - 187. I can’t do much testing because I have a path issue with the mypaint brush icons when I build myself. 

I’d love to see the swatches updated to have the static image + responsive color & for only the current style to display at the bottom of the style editor (when auto-apply is on). As long as the vector/texture styles just repeat across the space, there shouldn’t be any degradation of display quality. Without auto-apply it makes sense having both the current & previous style, but without it, the duplication seems unnecessary & confusing - especially since the previous style is only previous for a fraction of a second before it’s the same as the current style.

**Comment by RodneyBaker** [comment]
It's too bad we don't have a drawing program that we could use to create mockups of what success might look like....  oh.. wait!   :)

For GUI enhancement we should draft up some examples of the ideal look and feel.  There are a few people that are very good with UI coding but they don't want to wade into the UI because of how contentious that can be... no one is every satisfied with UI tweaks... not gonna happen.  Those folks might not care to dive into the deeper OT source but if they see a solid UI target they can hit the mark.

Then we *just* have to have the code connect the dots.

**Comment by artisteacher** [comment]
Large thumbnails + single style for auto-apply. It looked strange having the color stretch out all the way, so I would give it a smaller proportional width.
![7a0eff66-a52c-4ac7-8c0b-5575e55b542e](https://user-images.githubusercontent.com/21159116/48105729-9dcdee00-e206-11e8-946e-b7a9f9d8ebf9.png)

Medium thumbnails, without auto-apply, showing “current” and “previous” styles. 
![5c6cf332-dc78-4e0a-a8b1-10af795f87cf](https://user-images.githubusercontent.com/21159116/48105730-9dcdee00-e206-11e8-94d0-2f10c9e2aff0.png)

I should have added it in the images, but I think the active brush needs a more obvious border - in the style editor (ie. In the Raster tab & etc.). Perhaps the active column color?
