### ISSUE TITLE
Unexpected crash during audio playing of few frames

### ISSUE THREAD

**Issue by sundhar010** [opentoonz/opentoonz#1392]
Created animations for a few frames and added audio to them. While playing the audio, the application crashes and exits. 

Here is a log file from my system for the crash. 
[https://pastebin.com/nvUf2nWP](https://pastebin.com/nvUf2nWP)

Use MacOS Sierra

**Comment by artisteacher** [comment]
This is a known bug with Sierra #978. Fortunately there's a fix from @turtletooth that hopefully can be merged soon.

**Comment by turtletooth** [comment]
Closing as a duplicate.
