### ISSUE TITLE
OTX:  Missing xsheet column icons and left side bar

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1393]
![missing icons](https://user-images.githubusercontent.com/2576432/29168444-84a27c84-7d94-11e7-95e5-539704b07b6b.png)
I had mentioned this in passing in another issue but I'll document it here to see if it is a bug that can be reproduced and addressed.  I am experiencing it in current OTX release as well as prior release.  Note that the icons appear as designed in the latest official nightly release (as it has in all other releases).

I am currently running OTX via USB stick but have also ran it via harddrive.

I am working on Win 10 (creators update).

In the attached image the top view is the official release for comparison.
In the bottom view note that the Column icons are missing as is the drag bar on the left used to grab and reorder columns.  I can (carefully) select a very thin portion of screen on the left that allows me to drag columns left and right but it is quite a challenge.  

I'm trying to think if I perhaps inadvertently adjusted some CSS while investigating the width of xsheet columns but... the OTX installation is a fresh copy placed on a USB stick.  Could the xsheet column header code be pointing to a reference like a style sheet on the harddrive?

**Comment by manongjohn** [comment]
The drag bar is not missing in OTX. The column name doubles as the drag bar. This was intentional. 

I'm still not sure why your icons are missing. That version doesn't control them by stylesheets. Those are PNG icons compiled into executable.

I'll see if I can reproduce to confirm.

**Comment by RodneyBaker** [comment]
Ah, thanks for the reminder about the drag bar.  I do recall that being discussed.  
Thanks for looking into the missing icons.  It's odd.

**Comment by manongjohn** [comment]
I am unable to reproduce this. I downloaded the latest OTX and installed to a USB stick and have run it without issue on a Win 7 and 10 (both Professional) that never had OT on it before.

Have you tried your USB on any other machine? 

I just noticed the Note icon is missing in both your screen shots (button below Xsheet button). That shouldn't be.

I'm wondering if the portable is detecting your setup on HD and running with that. If there was an issue with your stylesheet, it would affect both which it seems to be doing.

**Comment by RodneyBaker** [comment]
Have you tried your USB on any other machine?

No, but I've been meaning to just for general usage and testing so I'll do that right away an report the results.  I should have thought to try that before posting this report.
You may be on to something there.

**Comment by RodneyBaker** [comment]
Good news!  The xsheet icons appear when I run OTX on my laptop.
So, that means something on my desktop is interfering,
While we don't have a specific cause I think we do have enough info to close this issue and I'll add a note if/when I uncover that cause.  If does appear to be isolated to my desktop so that helps isolate the problem.

Thanks @manongjohn for your assistance!

Recommend close.
