### ISSUE TITLE
Style Editor Frozen and color wheel glitch

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1395]
In the Morevna release of OT, the style editor is frozen but only for the page that is active on opening the app. 

In this frozen state, the style editor won't expand by clicking on the header - unless another window has been expanded first. Removing the style editor and adding it in again or just expanding made it editable again. 
<img width="572" alt="screen shot 2017-08-11 at 4 02 43 pm" src="https://user-images.githubusercontent.com/21159116/29230237-0d12f7da-7eb0-11e7-92b5-3cd746fe2470.png">
In addition, the color wheel displays as black or sometimes shows the same area in previously opened rooms until the style editor has been unfrozen.

This is on OS X 10.12.6.

**Comment by blackwarthog** [comment]
I've encountered the same behavior of style editor. As temporary workaround to unfreeze style editor you may to switch to other room and switch back for initial room.

Is this bug exists in the official version OpenToonz?

**Comment by artisteacher** [comment]
I might have run into similar things very occasionally, but I'm not sure. Having this happen every time the app opens is definitely specific to the Morevna release.

**Comment by artisteacher** [comment]
Just ran into this on a couple iMacs running 10.11.6 and the nightly build from 8/14/2017 19:10:07. When the style editor froze, most of the program menu was entirely missing, which was strange. My students were remodeling a couple rooms, so it's possible that had an impact. I haven't been able to update to the more recent builds on the iMacs due to the fullscreen crashing after this build.

**Comment by artisteacher** [comment]
This does not seem to be an issue with the latest couple nightly builds.

**Comment by artisteacher** [comment]
Resolved in the Morevna release as well.
