### ISSUE TITLE
Fullscreen crash

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1396]
In the Morevna release of OT with OS X 10.12.6, I get a crash when trying to go fullscreen (both from the menu and the green button at the top left of the app window). On a positive note, I can briefly see the fullscreen window before the crash and it looks like the double room menu issue #271 is gone.
![fullscreen](https://user-images.githubusercontent.com/21159116/29231048-9b53b7e8-7eb3-11e7-8d7a-0800e34a6f51.gif)

[fullscreencrash.txt](https://github.com/opentoonz/opentoonz/files/1218976/fullscreencrash.txt)

**Comment by blackwarthog** [comment]
I cannot repeat at OS X 10.8.5, and have no this menu item. I've fullscreen button at the top-right corner of window and it works fine.

Is this bug specific for morevna build only?

**Comment by artisteacher** [comment]
Yes, it is specific to the Morevna build.

**Comment by artisteacher** [comment]
I just tested on a much older mac, also using Sierra, and it also has the fullscreen crash. This might be specific to Sierra and not older versions of OS X.

**Comment by artisteacher** [comment]
This is now also occurring in the recent nightly builds.

**Comment by artisteacher** [comment]
@blackwarthog @shun-iwasawa this is not specific to Sierra, I'm also getting this crash with the recent nightly builds in 10.11.6. It looks like this started after the build on 8/14/2017 19:10:07 to fix the camera capture for OS X with QT5.6.

**Comment by artisteacher** [comment]
Even when not in fullscreen, with recent nightly builds,  I'm getting some random crashes with similar crash reports, both in 10.11.6 and in 10.12.6. The reports are also very similar to #1439, but with a few extra lines. Once it happened when working with a pegboard and motion path in the stage, one was when adding new styles to the level palette, once it happened when changing the interpolation in the function editor. It seems to happen more often when I'm experimenting with something but only the fullscreen crash is reproducible. I'm getting at least 1 crash in a 45 minute period, often in the first few minutes after opening. I love the program & there are some amazing new features but the crash rate is getting a little excessive. It would be amazing if this could be resolved before the next official release.
<img width="500" alt="screen shot 2017-09-25 at 9 00 48 pm" src="https://user-images.githubusercontent.com/21159116/30837738-26640366-a235-11e7-8d0d-624759cf0923.png">

**Comment by artisteacher** [comment]
This is from trying to use the style picker on a raster level from a vector level with the build before the 8/14/2017 19:10:07 build.
![screen shot 2017-10-06 at 11 13 45 am](https://user-images.githubusercontent.com/21159116/31287216-84f319f6-aa8e-11e7-8038-d4d352351608.png)

**Comment by artisteacher** [comment]
The fullscreen crash is no longer an issue with the latest nightly build. Thanks so much!

**Comment by turtletooth** [comment]
Awesome!
