### ISSUE TITLE
OpenToonz Forum:  New Categories?

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1398]
This is primarily for @shun-iwasawa  but should be discussed to determine what change (if any) would be appropriate

In the OpenToonz forum we currently have the following categories:
Announcements
Troubleshooting
Feature Requests
Tips and Tricks
Share Your Work
General Discussion

I'd like to propose two new categories and if Google Groups allows such they would work best if they were subcategories.

Troubleshooting (Resolved)   or Troubleshooting (Solved)
Feature Requests (Closed) or Feature Requests (Implemented)

Something to that effect.
I was tempted to move/relabel implemented Feature Requests under the Tips and Tricks category but we lose some historical aspects of the topic if we do that as there is no way forum visitors would easily know that a Tip and Trick was once a Feature Request.  Being able to recategorize a Feature Request as Feature Request (Implemented) would allow for this as well as demonstrate that posting feature requests to the forum works.  Similarly, Troubleshooting issues that move to the category Troubleshooting (Resolved) allow users to review known issues, avoid user error and perhaps most importantly to see and have the satisfaction of knowing their problem has been resolved.  Issues that then stay in the Troubleshooting cue for extended periods of time can then further inform developers because they are still not resolved.

Note also that (unless something has changed) everyone has the ability to change move a topic under another category.  That might have changed after the first big sorting of posts after the forum first started but I think everyone still has that ability.

Several folks recently requested a wiki and although that would be nice we do have an excellent forum for documentation and discussion via the forum.  The formatting might be lacking in many ways** but it remains the best place to go to get information related to OpenToonz.

**I haven't looked into what if any other formatting options Google Groups might provide.

**Comment by shun-iwasawa** [comment]
> I'd like to propose two new categories and if Google Groups allows such they would work best if they were subcategories.

Thank you for your proposal to add the new categories in order to organize the topics. I added them.
Note that they are on the same hierarchical level as existing categories, since Google Groups seems not to allow having subcategories. 

> Note also that (unless something has changed) everyone has the ability to change move a topic under another category.

Thank you for the notification. Fixed.

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa.
That helps a lot and I'm starting to sort through the topics now.

One thing... certainly open for discussion:
I always prefer having the originator of the topic confirm their issue is resolved before 'closing' or in this context moving it to the 'resolved' category.  This is always preferred because I see it as a measure of 'customer satisfaction'.  

When a troubleshooting topic appears to be abandoned in the forum but a likely fix has been suggested it seems appropriate to re-categorize as 'resolved'.  The topic can always be adjusted back to the other category should the topic poster (or anyone else for that matter) post to suggest there is still a problem.  

Unless others suggest otherwise I will consider abandoned topics as 'resolved'.
Of course at any time everyone is free to war on a topic, moving it from 'Troubleshooting' to 'Troubleshooting (Solved)' until it finally and definitively is resolved.  ;)

Recommend closing this issue pending any need for other categories.

**Comment by turtletooth** [comment]
@RodneyBaker I think it is safe to move things to the resolved section as soon as it is fixed unless the original thread is from a regular group commenter.  That will keep things nice and tidy.

**Comment by RodneyBaker** [comment]
Thanks.  Will do.
