### ISSUE TITLE
remove libpng version 1.6 dependency

### ISSUE THREAD

**Issue by xenogenesi** [opentoonz/opentoonz#140]
Currently opentoonz depend from libpng16 only because of few functions used by `libimage` ([toonz/sources/image/png/tiio_png.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/image/png/tiio_png.cpp)), `png_get_current_row_number()`, `png_get_current_pass_number()` and `png_set_longjmp_fn()`.

The `png_get_*` are just simple getters to access `png_structp`, easy to provide for older versions of libpng, the first reference on [png.h](https://github.com/glennrp/libpng/blob/libpng15/png.h)  I've found is on branch 1.5, (`PNG_LIBPNG_VER` = `10527`).

`png_set_longjmp_fn()` I believe is almost useless in current `tiio_png.cpp` implementation:
1. being C++ `try/catch` shouldn't be used instead? As libpng documentation say: `setjmp/longjmp` is a (ANSI)C method to handle errors.
2. libpng16 implementation of `png_error()` (which are fatal and shouldn't return) fall back to the default error handler (`tnz_abort` `tnz_error_fun` are currently used as callback), the default error handler on returning callbacks  end to `PNG_ABORT()` (`abort()` on non windows systems, `ExitProcess()` on windows)

So, if I'm not missing something, the current implementation doesn't really `ignore all fatal errors` as the source comment say (just add a `png_error()` call after `png_set_longjmp_fn()` to check).

With few edit opentoonz can compile, link and run with libpng12, see this [gist](https://gist.github.com/xenogenesi/535e69887c7c1bcf0297b972850175c2) (tested with [linux_fix_wip](https://github.com/ideasman42/opentoonz/tree/linux_fix_wip) branch)

On some linux distro and I guess on some other system, the system libpng version is still 1.2. 
The dependency to 1.6 currently add the need to manually build libpng from the thirdparty, add the side effect to link both libpng versions if 16 isn't the one provided by the system, will add some headache providing a `make install` target with shared libraries.

**Comment by turtletooth** [comment]
Looks fixed.
