### ISSUE TITLE
Brush Stroke Appearing Delay with Surface Book Pen

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1402]
I've used both OpenToonz and ToonBoom and they both had this problem and only ToonBoom had a solution. The problem is that each stroke has a delay before the stroke actually appears, and in some cases if you stroke too quickly the line appears as a straight line. The solution for ToonBoom is here: https://forums.toonboom.com/toon-boom-harmony/support-and-troubleshooting/brush-stroke-appearing-delay-surface-pro-3-pen and the solution seems to be to disable QT Wintab Support (which ToonBoom had in their settings). OpenToonz, however, does not. Both programs had an identical problem, so I'm assuming the solution would be similar, but unfortunately I wasn't able to find a way to replicate the solution in OpenToonz.

**Comment by blackwarthog** [comment]
The problem in OpenToonz may be related with interpolation of strokes, which requires a one extra pointer movement. May you check, are the delays for mouse and for pen different?

**Comment by jpturcotte** [comment]
@blackwarthog From the original post (#1401, now deleted):

> Whenever I make a quick stroke on my Surface Book, there'd be a second delay which is impossible to work with. If I were to just use touch to draw or just use a trackpad, there'd be no delay at all so it only happens when I'm using my Surface Pen. The pens fully functional everywhere else.

**Comment by itsvividly** [comment]
@blackwarthog Yea as jpturcotte quoted, theres no delay with mouse or trackpad input.

**Comment by turtletooth** [comment]
I have a surface pro and don't seem to have the issue.  @itsvividly  Do you have the Wintab drivers installed?

**Comment by jpturcotte** [comment]
@turtletooth There is at least one other person reporting the same problem on Facebook: https://www.facebook.com/groups/190284078019624/permalink/454326168282079/?comment_id=454447661603263&comment_tracking=%7B%22tn%22%3A%22R2%22%7D. Also, if @itsvividly is the person I talked to there, he already tried installing the Wintab drivers.

**Comment by itsvividly** [comment]
@turtletooth Yea, I have the Wintab drivers installed.

**Comment by turtletooth** [comment]
Do you also have the MSVC 2010 runtime installed?  I had to use the links on the Krita page to get my surface pen working properly.
https://docs.krita.org/KritaFAQ#Microsoft_Surface_Pro_and_NTrig

**Comment by RodneyBaker** [comment]
In light of v.1.5 changes this report should be re-evaluated.
@itsvividly Can you confirm the delay you experienced back in 2017 still exists and if so provide any updates to your settings etc.
Thanks!

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
