### ISSUE TITLE
Startup Popup Doesn't Display Correct Pixel Size from Cam Preset

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#1404]
Switch the unit to pixel and then choose a camera preset, the pixel size is showing as incorrect.

If I choose 4K it should display 3840 x 2160 but it displays 1707 x 960 instead.

Perhaps there is a quirk I'm not aware of, or maybe its my configuration.

Can anyone confirm?

**Comment by RodneyBaker** [comment]
This may have been fixed.
I cannot reproduce using current nightly release

**Comment by konero** [comment]
@RodneyBaker Indeed, I installed latest nightly and the issue is gone. 👍
