### ISSUE TITLE
Feature request : automatic upgrader

### ISSUE THREAD

**Issue by Yvaiin** [opentoonz/opentoonz#1408]
Hi!
I think its would be more pratical if in a future version you add a system which check if there is a new update and install automatically this update.
Thanks for reading my request !

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by shun-iwasawa** [comment]
@Yvaiin OpenToonz already has a version checker which will notify when the updated version is released and navigate you to the OpenToonz website. Please note that it will not follow the nightly builds, as they are pre-release versions. 

Closing this.

**Comment by Yvaiin** [comment]
ok thanks for the information

**Comment by adamearle** [comment]
Nightly builds link would be great for testers and getting more people
involved into animation, development and coding.

At t the moment people are still digging for it. This a massive loss to
OpenToonz development.
