### ISSUE TITLE
File Import/Load Popup Bug

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#1411]
Everytime I load a file from the file browser into the scene cast I get the popup that tells me the file doesn't belong to the current project, do I want to **Import** or **Load** the file.

But the files do belong to the current project already, they reside in the project extras folder. Even if I click import and reload later I'm presented with the popup again.

The only project this doesn't happen to is sandbox.

**Comment by turtletooth** [comment]
@konero I just tried this and couldn't duplicate it.  I am probably missing something.
I created a new project.
Dragged a file from my desktop into the scene.
Clicked import.
Saved. 
Closed.
Reopened and loaded the scene.
No dialog.

I also created a new scene for the same project and loaded a file in the project extras folder into OT both through the OpenToonz browser and dragging from Windows Explorer and no dialog.

**Comment by konero** [comment]
I think it happens when the scene hasn't yet been saved, I guess it uses the sandbox or cache at that point?

I place files into the project via Windows explorer, but it makes no difference either way.

- Create New Project
- Create New Scene (don't save yet)
- Load files from Drawings folder
- You get the Popup

TBH it's best practice to save the scene file, a lot of the time I don't since I'm just outputting something minor or running some test. It **doesn't** appear when the scene has been saved before loading levels.

The issue I had once or twice is after loading some levels and clicking import, if I save the scene later, then close OpenToonz, reload the scene, all the levels will be missing from the scene file.

So I'm assuming the scene is a sandbox scene until it's saved, the paths are pointing to sandbox still?
