### ISSUE TITLE
Mac Trackpad controls are frustrating

### ISSUE THREAD

**Issue by RFDaemoniac** [opentoonz/opentoonz#1418]
Trackpad issues that add up to a very poor user experience:

The default behavior of Krita Mac is to zoom on mouse wheel up/down. Trackpad gestures register a two finger as a scroll, which is used to pan around in every other application. But in Krita it zooms because it is interpreted as a mouse wheel. There should be both up and down and side-to-side panning using two finger gestures, and these should be distinguished from mouse wheel up/down.

Krita zoom also doesn't recalculate the zoom until after the user has stopped zooming. In macOS there is acceleration applied to all trackpad gestures, including scrolling. The fact that Krita does not calculate until the acceleration has stopped applying means it takes half a second or more for any change in zoom to be visually rendered (rather than just a number). This makes zooming on a trackpad incredibly frustrating. This occurs with both scroll zooming (which shouldn't be a default behavior on trackpads, since two finger scroll is not a mouse wheel).

There is also no recognition of idle touches or accidental touches. When navigating macOS in other applications I can rest my thumb on the trackpad in preparation of a corner-click, and use my index finger as a single touch to move the mouse position. In Krita this is interpreted as a two finger gesture, often a pinch to zoom.

I have been unable to edit the preferences to account for these issues. There is no ability to add controls to gestures in the Krita preferences interface.

**Comment by artisteacher** [comment]
I'm a little confused, your issue seems to be about Krita and not OpenToonz.

**Comment by RFDaemoniac** [comment]
hahaha, what a fail. Sorry :( You're very correct.
