### ISSUE TITLE
Geometric tool not working on Toonz Raster and Raster Levels

### ISSUE THREAD

**Issue by ullebulle** [opentoonz/opentoonz#142]
As seen on attached video, the geometric tool is not working on raster levels.
I am running OS X 10.11.4 and OT v.1.0 and v.1.0.1
Video:
https://dl.dropboxusercontent.com/u/215022/OT/raster-geometrics%20bug%20OTv.1.0.mov

/Ulrik

**Comment by Rayek** [comment]
This functions properly in the Windows version. No issues.

**Comment by kogaki** [comment]
Hmm... In my OSX environment, it works fine. Is there anyone who faced this bug?

**Comment by ullebulle** [comment]
Ok, I tried again with the latest nightly build and now it's working fine

**Comment by kogaki** [comment]
Good. Thanks.
