### ISSUE TITLE
Preview and Export as White Frames

### ISSUE THREAD

**Issue by LizardLaw974** [opentoonz/opentoonz#1421]
Hello! I've been struggling with previewing and exporting my project. It was working fine a while ago, but it suddenly changed and I have done everything I could think of t get it fixed.

The issue is that whenever I go to preview the project, or if I go to export it, everything is purely white and no animation is exported or shown. The project has a white background to it and I've tried with both that and transparent backgrounds but to no avail. No camera should be interfering with it, all the layers that need to be visible are, I even deleted a lot of the old layers that weren't needed in case they got in the way.  I took away all of the movements that I had added in, nothing. I've changed camera settings, output, preview settings, but nothing is working. This is incredibly discouraging and I wasn't sure if there would be anyone that could help?

I did have Use Sub-Camera checked, and I thought that was the issue, but it didn't change anything when I unchecked it. I use a Acer Laptop, Windows 10, with OpenToonz, being drawn on my Cintiq 22HD.  The issue is still there whether viewing it on the Cintiq screen or laptop screen

**Comment by shun-iwasawa** [comment]
Can you upload a minimum sample data which can reproduce the issue? Thanks.

**Comment by shun-iwasawa** [comment]
> In terms of a picture example or a file example of the export or project?

I would like to reproduce an occurrence of the problem on my environment in order to detect the cause. So the reproducible files (probably a set of scene file and some level files used in the scene) will be very helpful.
Note that it is NOT the exported result image.
