### ISSUE TITLE
Vector levels doesn't show up in camera preview

### ISSUE THREAD

**Issue by ullebulle** [opentoonz/opentoonz#143]
Toonz vector levels does not show up in camera preview
OS X 10.11.4 OT v.1.0 and v.1.0.1
Video:
https://dl.dropboxusercontent.com/u/215022/OT/vector%20not%20shown%20in%20camera%20output.mov
/Ulrik

**Comment by ullebulle** [comment]
Anybody else having this problem on OS X?

**Comment by kogaki** [comment]
#191 must be fixed this problem. I believe it now work in `nightly build`. Thank you.

**Comment by ullebulle** [comment]
Yes it's working now, thank you!
