### ISSUE TITLE
When updating strings, mark them as Unfinished in .ts files

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1443]
I've just made a pull from upstream to update my local .ts files, and saw that one of the files (toonz.ts) had 3 strings that were changed in English, and to my surprise they were also automatically translated into Spanish, AND marked as Done.
The problem is that, even though the word automatically placed was correct, some surrounding words needed to be adjusted to match the gender of the new word (which is not the same as in the previous one).

So I'd like in the future the changed strings to always be marked as Unfinished, so we could see them quickly to re translate them as needed. Currently, this kind of changes would pass unseen and in the long run contribute to undermine the overall quality of the translation.

Thank you!

**Comment by shun-iwasawa** [comment]
AFAIK, if the same phrase appears in the same context, they will be unified in .ts file and will be applied the same translation. Setting `disambiguation` string to the second argument of `tr()` function will avoid it.
[http://doc.qt.io/qt-5/qobject.html#tr](http://doc.qt.io/qt-5/qobject.html#tr)

I don't think there is a way to set some specific phrase to "Unfinished" manually from the source. Correct me if I'm wrong.

**Comment by gab3d** [comment]
@shun-iwasawa thanks for answering, but it isn't related to a disambiguation.

In this case, the original strings (3 in total) were changed from saying "(...) Next Row" to "(...) Next Frame". 
The translations corresponding to those strings were automatically (I assume) updated to the corresponding word for "Frame" in Spanish and kept its status as Translated.
The problem is that simply changing a word for another not always gives a correct translation (in this case it genereted a gender mismatch, as in Spanish the word for "Row" is femenine and the one for "Frame" a masculine one), so I think it'd be safer that updated strings be marked as Untranslated, for us to be able to make a new translation for the updated string. Instead, the current procedure, could lead to wrong translations, effectively "hidden" from the eyes of translators (as they remain marked a Translated strings).

**Comment by shun-iwasawa** [comment]
Ah! Finally I found something.

>The translations corresponding to those strings were automatically (I assume) updated to the corresponding word for "Frame" in Spanish and kept its status as Translated.

It was done not automatically, but manually in the [previous PR](https://github.com/opentoonz/opentoonz/pull/1376/files#diff-8657cc1fb4e7acba19e8f1e8f5225552).
So IMO it's just a matter of correction of mistranslation.

**Comment by manongjohn** [comment]
It was not automatic.  I had done that manually in one of my PRs.  I carefully looked at other instances in the file for the appropriate wording and ran through google translate to verify to make sure, but I guess it didn't care about the gender mismatch. I knew I had to watch for gender and I thought I had it right.

Sorry for the confusion and for translating incorrectly.

If I ever do that again (probably never), I will somehow mark it as "Unfinished" rather than trying to re-translate it myself and leave it to the more fluent speakers of the language.

If you want to send me the correct translations, I can submit the correction. I guess should try and find out if there were issues with the other languages I touched or perhaps go back and mark them as unfinished somehow?

**Comment by gab3d** [comment]
@shun-iwasawa thanks for tracking it down!
@manongjohn, no problem. It's good to know there wasn't some script automatically doing things. ;)
I think I prefer in the future, when such changes happen to strings, for the them to me marked as Untranslated or Unfinished, after all we are here just for taking that kind of work. :)

I've already corrected them, and will push it together with several other corrections I'm making (to my own initial translation, now I know how the software works much better than when I originally done it).

**Comment by shun-iwasawa** [comment]
Solved. I'll close this.
