### ISSUE TITLE
duplicated window title on OSX

### ISSUE THREAD

**Issue by jcome** [opentoonz/opentoonz#1445]
As shown in the attached screenshot, there are duplicated window title
OSX Sierra (10.12.6 ), OpenToonz build Aug 29 2017 10:31:43

<img width="1137" alt="duplicated title" src="https://user-images.githubusercontent.com/417336/29820508-47616700-8cf7-11e7-9e99-f1474c09cfff.png">

**Comment by artisteacher** [comment]
I think this is related to #271

**Comment by artisteacher** [comment]
I have only have this occur on opening when "Show Tab Bar" (under View) is checked. If it is checked after opening, the double room menu displays.

**Comment by artisteacher** [comment]
This looks to be fixed in the latest nightly build.

**Comment by turtletooth** [comment]
Amazing!

**Comment by artisteacher** [comment]
So update, this is not completely fixed. I guess based on the something in the code, MacOS automatically adds “Show Tab Bar” and “Hide Tab Bar” into the View menu. In recent builds, the default behavior is hide - which hides the tab bar/the second title. If you click on the show option, the second title displays again. 

There are directions [here](https://forum.qt.io/topic/82609/remove-native-mac-menu-items-such-as-show-tab-bar/3) to disable the automatic window tabbing, but that’s beyond my capabilities I think. @shun-iwasawa, when you have time, could you take a look?

**Comment by RodneyBaker** [comment]
@artisteacher  Is this double windows title occurrence still an issue on MacOS?

**Comment by artisteacher** [comment]
@RodneyBaker the double window title is still occurring. 

For now, Mac users should avoid enabling "Show Tab Bar" in the View menu.

**Comment by artisteacher** [comment]
QT has an open[ bug report](https://bugreports.qt.io/browse/QTBUG-61707).

**Comment by RodneyBaker** [comment]
Thanks.  At least its good to know it's primarily an upstream issue.

**Comment by MrBlockCat** [comment]
Good news! Looks like the bug report was closed on QTs side, and their bug fix will be included with QT 5.15.0 when it releases (which a stable release should be in a couple months according to [https://wiki.qt.io/Qt_5.15_Release](their wiki))

**Comment by artisteacher** [comment]
This is resolved, due to the changes in the mac build environment - can be closed.
