### ISSUE TITLE
Default camera preset cannot be loaded.

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#145]
Camera preset are listed in combo boxes both in the Output Settings and in the Cleanup Settings.
For now, selecting item from default camera preset does not work.
When you select some item, a warning dialog "Bad camera preset" opens.

This is because in Toonz Ghibli Edition we decided to save in preset string not only pixel size and aspect ratio but also inch size and offset. (Note that offset is saved only for cleanup camera.) And when applying such modification, we did not give priority to keep compatibility with Harlequin's preset data.

**Comment by skitaoka** [comment]
This issue is fixed by https://github.com/opentoonz/opentoonz/pull/146.
