### ISSUE TITLE
Some strings untranslatable.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1458]
Hi there,

I've noticed some strings doesn't seem to be currently translatable (someones correspond to recent changes, but many others do not). 
Following is a list of the ones that I've managed to identify.

- "Toggle XSheet Toolbar" right click menu option
- "Timeline / Xsheet" button
- the word "Table", used in the Xsheet, the Stage Schematic node and the right click menu in the viewer.
- the word "XSheet", used in the FX Schematic node.
- the word "Output", used in the FX Schematic node.
- "Set  Automarkers" in right click menu in Xsheet.
- "untitled", used in Output options for the file name. 
- "untitled", used for untitled  scene name. 
- "inch", "pixels", "A/R" and "<custom>" in Camera Settings and Output Settings panels.
- "Range" and "Snap" in Brush Tool settings.
- "fld" in Edit Tool
- "H, "S", "V", "A", "R", "G", "B", "MyPaint Brush" in Style Editor.
- "[LEVEL]", "Palette" and "#" strings in bottom line of Style Editor.
- "Passive Pick" in Style Selector tool
- "Global Palettes", "Project Palettes" and "Colors" in Studio Palette Editor.
- "Alpha", "Full Alpha" and "Zero Alpha" in Palette Gizmo.
- "Apply and Next", "Easy Inputs", "New", "Character", "Part", "Suffix", "Enter new word" in Style Name Editor.
- Strings in User Preferences panel:    
"Default Import Behavior", "Use Camera DPI for All Imported Images", "Default TLV Caching Behavior", "Column Icon", "Palette Type on Loading Raster Image as Color Model", "New Levels Default to Current Camera Size", "Vector Snapping", "Use Arrow Key to Shift Cell Selection", "Enable to Input Cells without Double Clicking", "Show Toolbar in the XSheet", "Expand Function Editor Header...", "Show Column Numbers in Column Headers".

Thank you!

**Comment by jcome** [comment]
some of them are already avaiable in Japanese .ts files. I've manually updated Simplifed Chinese .ts files based on Japenese ones. it is simple with the tool provided by l[inguist](http://doc.qt.io/qt-5/linguist-manager.html), for example:

```
[jcome@localhost japanese]$ lupdate-qt5 tnztools.ts -ts ../chinese/tnztools.ts 
Updating '../chinese/tnztools.ts'...
    Found 238 source text(s) (7 new and 231 already existing)
    Kept 7 obsolete entries
    Same-text heuristic provided 5 translation(s)
```
it works in most of case but some times we have to manually delete duplicated strings (just in case it has).

I guess the Japanese version of .ts files are mantained by @shun-iwasawa manually. 

It would nice to have **lrelease** tool integration some day as mentioned in #835.

**Comment by gab3d** [comment]
@jcome sorry to ask, but are the "H", "S", "V", "A", "R", "G", "B" sliders strings in the Style Editor already translatable?
And if not, could you please make them so?
Thank you!

**Comment by jcome** [comment]
> are the "H", "S", "V", "A", "R", "G", "B" sliders strings in the Style Editor already translatable?

I think so: https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzqt/styleeditor.cpp#L1237

**Comment by gab3d** [comment]
great! thanks! :)
