### ISSUE TITLE
Marks made using My Paint Brush appear washed out and desaturated when rendered as a PNG

### ISSUE THREAD

**Issue by TiltedAxis** [opentoonz/opentoonz#1463]
This is my image as viewed within OpenToonz 
![printscreenot](https://user-images.githubusercontent.com/30163522/30189246-bf90d458-9400-11e7-9e7b-5be10aaacdfc.png)

And this is that same image rendered as a PNG 
![sketches 0330](https://user-images.githubusercontent.com/30163522/30189280-ef0fe854-9400-11e7-8708-e6776283414d.png)

Issue appears to be specific to PNG. When rendered as JPEG image appears normal and true to form 
![sketches 0330](https://user-images.githubusercontent.com/30163522/30189327-22126240-9401-11e7-8bce-4e7652837213.jpg)
@morevnaproject. cc @KonstantinDmitriev

**Comment by jpturcotte** [comment]
@morevnaproject Any idea?

**Comment by turtletooth** [comment]
It looks like its the transparent parts that are having issues.  This is probably related to #1230 .  I have tried to fix this, but couldn't find where the premultiplication is happening.  This is definitely something for someone like @shun-iwasawa  or @blackwarthog .

**Comment by shun-iwasawa** [comment]
Yes, it seems to be the same issue as #1230 as @turtletooth pointed.

@TiltedAxis 
Do you want to make your scene semi-transparent as shown in PNG result? If not, setting the alpha channel of the Camera BG Color to 255 will solve the problem. 

- Select `Menu bar > Xsheet > Scene Settings...` (for Default room layout)

- Set Camera BG Color to RGBA = (255,255,255,**255**)

- Render the scene with PNG format

Then I think you can obtain the same result as JPG.

If you would like to handle the semi-transparent PNG image rendered with OT, for now another workaround would be to disable premultiply option set in `Level Settings by File Format`. Please note that this is just for displaying PNG files which is rendered with current OT. And it does not follow the official specification of PNG.

- Select `File > Preferences`

- Find an option `Loading category > Level Settings by File Format`

- Select `PNG` in the combo box, and press `Edit`

- Disable `Premultiply` check box in the popup

- Load the semi-transparent rendered result

**Comment by TiltedAxis** [comment]
@shun-iwasawa 
I set the Alpha BG to 255 and that solved the problem.  I don't specifically need the scene to be semi transparent for what I'm working on now, but I could foresee a time when I would in the future.  It should also be noted as I forgot to mention in my initial post that after rendering and previewing the image in the flipbook everything looks normal, it's not until opening the render from an external source outside of  OT that the issue become apparent. Thank you for your help. Cheers!

**Comment by shun-iwasawa** [comment]
OK, I'll close this.
