### ISSUE TITLE
Zooms out every time I use the tablet, Mac OS X

### ISSUE THREAD

**Issue by aniustaluwis** [opentoonz/opentoonz#148]
every time my pen approaches the tablet and is recognized by the tablet (without necessarily touching it and without me pressing any buttons), the interface will zoom out a little bit.

I use on Mac OS 10.9.5 with Wacom Bamboo Create model CTH-670 tablet. After doing a little poking around I discovered someone had the same problem with CTH-470 Wacom, and another person had tried it with 3 different tablets and they all had the same problem. All people shared Mac OS X so I think this may be an issue with the OS X port.

If I were to take a wild guess I think the program is confusing the tablet recognizing my pen with the scrolling action, but I haven't found a way to turn the scrolling zoom feature in toonz off so I can't test it.

EDIT: also the interaction with the tablet is very sticky. sometimes it works, sometimes the little red paint cursor will not follow my pen when I try to draw and does nothing, sometimes it does not stop drawing when I lift the pen.

**Comment by boudewijnrempt** [comment]
We actually have exactly the same problem with the Qt5 port of Krita, so it's quite likely that it's a Qt bug: approaching the tablet seems to generate scroll wheel events, and that's mapped to zoom in Krita, and apparently also in OpenToonz.
-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Comment by aniustaluwis** [comment]
That's very interesting! (And I learned something new today, the existence of Qt)

I also discovered that if I scroll on my trackpad while my tablet recognizes my pen (photoshop habit; which I will need to break in toonz cause scroll-to-zoom, which PS doesn't do, is annoying for me), toonz goes berserk and throws dots everywhere. This supports my theory that scroll wheel events and pen recognition events are confused for each other.

also, related to the sticky interaction issue (unsure whether the scroll-recognition bug is related to this one but it might be), I've found it's easier to work with if I go slowly. I guess it's not fast enough to keep up with me? But apparently Windows users are not having this problem so it shouldn't happen to me either.

**Comment by walkerka** [comment]
The tablet or stylus support of Qt is really bad. I've experinced zigzag line issue on cintiq and move event lost issue on android (fixed on Qt5.5). Some have workaround, others don't. If they don't fix the issue, you have to wait or replace your code with native API (like WinTab)

**Comment by aniustaluwis** [comment]
Is this something toonz developers might be able to fix or will we have to wait for Qt developers to fix the problem? I'd like to patch it myself but I am not a developer at all and don't have that skill.

I did a little poking around online and discovered that apparently Qt has had crappy tablet support for years: https://forum.qt.io/topic/27016/so-how-s-the-tablet-support/14 Somebody tried doing a wintab wrapper for it but it's incomplete and the last commit was 3 years ago.

**Comment by blurymind** [comment]
Would that really solve the issue? Wintab is not available for anything but windows. Perhaps it would be good into looking at how Krita developers have dealt with it. Toonboom can use either wintab or qt for tablet events - its in their preferences window.

**Comment by walkerka** [comment]
No. Wintab is a windows only API. You have to use other APIs on different platforms and create an abstract layer for tablet support, something like SDL. Wintab is not hard to use, not sure about mac/linux.

For my app, I only record the pressure related info in tabletEvent() or touch event and get positions in mouseMoveEvent(). It works for me (windows/mac/android) at the cost of losing high frequency updates of position data. That can be improved by stroke smoothing though.

**Comment by boudewijnrempt** [comment]
Well, as the maintainer of Krita, I've been working with or around Qt's
tablet support for years. It's better with 5.6 than it was, but we still
have our own forks for Windows and Linux, and probably should fork for
OSX. Check https://github.com/KDE/krita/tree/master/libs/ui/input/wintab
for inspiration, but keep in mind that this partly our code and partly
Qt's code, so it's LGPL.
-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Comment by boompowzip** [comment]
all signs point to the scrolling events being incredibly sensitive on a mac. I tried working with my Bamboo CTH-670, nothing worked. 

I found that working with my Mac's tracpad to be a little more forgiving however, the moment i tried to click with two fingers, opentoonz assumed i was trying to zoom or scroll down which made working with the xsheet a living nightmare.

Honestly I don't know if this helps at all but I almost feel as if all my problems would go away if all functions involving two fingers on a Mac were changed whilst in opentoonz

**Comment by ec1oud** [comment]
When you find Qt bugs, you should report them at bugreports.qt.io.  I try to keep on top of the tablet-related bugs.

**Comment by ec1oud** [comment]
Anyway it's https://bugreports.qt.io/browse/QTBUG-52921 now

**Comment by kogaki** [comment]
I believe #206 fixed this problem. If this bug remains in latest build, plz reopen. Thanks.

**Comment by iamelm** [comment]
**Actually, it´s still an issue in Version 3.0 (Mac) with the Wacom Cintiq 21UX (DTK-2100).**
Every time I hold the pen near the Cintiq, the image gets zoomed out. This has a strong impact, as Krita is not usable at all with my configuration.

My specs:
Krita for Mac 3.0
Wacom Cintiq 21UX (DTK-2100)
Intuos 5 Pro large (PTH851)
MacBook Pro (Retina, 13-inch, Early 2015)
3,1 GHz Intel Core i7
16 GB 1867 MHz DDR3
Intel Iris Graphics 6100 1536 MB
512 GB SSD
OS X El Capitan Version 10.11.5
Wacom Driver Version:               6.3.15-3
Wacom Control Panel Version:   6.3.15-3

**Comment by desgraci** [comment]
Can confirm it is still happening, with a BAMBOO PEN, CTL-470/K

**Comment by gasparzilla** [comment]
Same problem here, bamboo CTL-470/K, El Capitan 10.11.5, whenever I lower the pen it zooms out, can't find a way to disable it.

Also couldn't see the cursor, but noticed that there was an option in configurations to enable and set different cursors (currently using crosshair)

**Comment by jpturcotte** [comment]
Is it still happening with [the latest nightly](https://github.com/opentoonz/opentoonz/releases/tag/nightly) (disregard the date)? There have been a lot of improvements to tablet support.
