### ISSUE TITLE
Checking with PVS-Studio static analyser

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [opentoonz/opentoonz#149]
To demonstrate the capabilities of our analyzer, we regularly perform analysis of open source projects. We had recently checked the OpenToonz project.

Here is the link to the article about it: http://www.viva64.com/en/b/0389/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

If you have any questions, or if you are interested in the evaluation of our static analyzer or in any other source code quality control services that our company provides, please contact us at support@viva64.com.

**Comment by blurymind** [comment]
Are you planning to do some commits to put your money where your mouth is, or is this just to advertise viva64's services :)
It's funny you used images from a cartoon show that was made with the tool you are reviewing.

**Comment by SvyatoslavRazmyslov** [comment]
That's why we never send patches. There are a few reasons for that:

We are not familiar with the code and therefore cannot be sure if all the bugs we catch are really bugs. To understand that, we would need to study the project very closely.

Even with obvious bugs, we often can't say for sure how to fix them.

Finally, we pursue but one goal with our articles - to demonstrate the capabilities of the analyzer we develop. That is, we want to prove that our tool can find bugs in a real-life, living code. We don't aim at fixing bugs - we aim at proving that our tool can find them.

[Readers' FAQ on Articles about PVS-Studio](http://www.viva64.com/en/a/0085/)

**Comment by blurymind** [comment]
Ah I see. Thank you for explaining. The tool looks very very useful indeed.

**Comment by walkerka** [comment]
We tried these kind of tools before (Coverity, maybe you heard of it). It did detect many small errors, and potential bugs in rarely executed code path (most are error handling). It still failed to find the random crash we hunted for weeks. IMO these tools improve software quality but don't rely them to fix memory issues.

Valgrind is much better. It detects more memory issues at runtime. It's slow, really slow. Most large apps cannot run with it so you must test module by module. On windows, there's a similar tool "Dr.Memory".

**Comment by musicm122** [comment]
I think the different issue categories presented in the article should be separated into individual issues. e.g. mismatched memory allocation\ deallocation would be considered 1 issue while incorrect exception handling would be another. etc... I'd actual like to try to take on a couple of them myself and I don't want to step on anyone's toes.

**Comment by turtletooth** [comment]
If anyone wants to tackle a specific issue, please make a separate issue instead.
