### ISSUE TITLE
UI:  Unstable panel sizing

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1490]
This thing happens every time you start the program or while minimizing the window.

![ezgif-2-97998ea432](https://user-images.githubusercontent.com/25724133/30871756-8b77068e-a2f0-11e7-9478-af35769915f1.gif)

**Comment by blurymind** [comment]
yeah, it is a really old bug, still not solved :D
I think @turtletooth tried it once

**Comment by turtletooth** [comment]
I made the level strip width fixed based on the thumbnail size in the level strip overhaul PR I made, but undid it since people might want to resize the level strip.  I guess I could make it a preference.

What are your thoughts?

**Comment by blurymind** [comment]
It would be nice if OT saves the width somewhere and loads it when
required. Not only when resizing the window, but also when the application
is restarted

**Comment by blurymind** [comment]
I am actually surprised that it already doesnt do that. Other panels seem
to remember their width and restore it

**Comment by beeheemooth** [comment]
I think that each user can stretch or narrow the panel as he wishes, the main thing is for the program to remember this size. It is not at all necessary to snap the panel size to the size of the thumbnails. 
There are many other panels that also change the size when minimizing or restarting.

**Comment by openanim** [comment]
I also think OT should remember the last workspace of the panels at the closing and opening. Imo, that would be  ideal.

**Comment by 2dvision** [comment]
There is also a bug for the "FX Edit" panel size.

![fx panel size](https://user-images.githubusercontent.com/16509592/30926534-feebd568-a3a4-11e7-8fcf-4089e8e5e564.gif)

**Comment by Orphanlast** [comment]
I agree, this is something that should probably be given some attention.

**Comment by shun-iwasawa** [comment]
@2dvision 
Thanks for pointing, Fx Settings issue would be owed by me. I originally made the popup to be resized to the same as its contents in order to avoid the trouble of having to scroll or resize it manually. But for now it seems to fail.

**Comment by artisteacher** [comment]
It would be great if the icon size was more flexible - ie. based on the width of the level strip. I’d love to be able to set the level strip to a narrower width while still being able to view the entire icon. My icons display significantly larger than they look in the gif from @beeheemooth.

**Comment by Orphanlast** [comment]
Does anyone know if anyone is working on this onem

**Comment by artisteacher** [comment]
It's definitely still an issue.

**Comment by openanim** [comment]
When you have a defined workspace for a room, it will be modified at the next opening of OT.

If closing is done from this room, OT does not take into account the arrangement of the room.

But if you close OT from another room, for example browser, your room will remain unchanged.

There is no possibility to have this behavior from any room ? In order to have rooms that allows for the latest arrangement.

**Comment by turtletooth** [comment]
I am going to try this again tonight.

**Comment by melieconiek** [comment]
Do you need more info on this? I have a workaround for it. 

If you change the windowed mode scale to match your full screen resolution the dock resizing doesn't happen. It would seem the application in momentarily in windowed mode when it starts (or something related,) scrunching up the docks. You can see the same effect if you change the size of the window yourself.

Hope that helps.

**Comment by RodneyBaker** [comment]
@beeheemooth Are you still experiencing the original issue you outlined in this report?
After three merged PRs I'll guess something got resolved.
