### ISSUE TITLE
Opentoonz Get crazy after right click on mac.

### ISSUE THREAD

**Issue by digimikeh** [opentoonz/opentoonz#1493]
Hi!.

When i´m working on OTz, everything work fantastic until i right click on a cell or drawing to copy or create a new layer, after right clicking, spinning wheel keeps on screen and scene panel start to draw randomly everywhere ...

My specs:

iMac late 2013 27" 
OS: OSX Sierra 10.12.6
OpenToonz 1.1.3 (built Sep 10 2017 10:30:46)

Any clues?
Thanks, keep OTz up!..

**Comment by RodneyBaker** [comment]
Will close this but reopen as necessary.
