### ISSUE TITLE
bug: convert to vector window- clicking on enhance ink recognition tickbox and playing with the sliders crashes OT

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#1500]
steps to reproduce- import a big image, try to convert it to vector and enable the ''enhance ink recognition" tickbox, move some slides around..

OT will crash entirely

windows10

**Comment by manongjohn** [comment]
What type of image? How big? Any chance you can share the image causing the crash?

**Comment by RodneyBaker** [comment]
@blurymind 
Closing this as likely resolved and/or abandoned.
If this issue still persists in current releases can you share some project files and perhaps narrow down what a 'big file' is in your specific production pipeline?
Thanks!
