### ISSUE TITLE
Default Style Editor Wheel very small

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1502]
The default size of the Style Editor wheel on a 1920x1080 screen in the Basics Room is really too small to be useful.
![default_styleed_size](https://user-images.githubusercontent.com/18104091/31094389-6ae7a942-a78b-11e7-85bf-5d15d2806b41.png)

yes, perhaps the color wheel design is not the most suitable one for small spaces, but a big part of the problem seems to lay in the fact that both, the sliders and the bottom areas are bigger that they could be, and are not resizable.
![default_styleed_size2](https://user-images.githubusercontent.com/18104091/31094582-17fe872c-a78c-11e7-8e6e-6835b83cc9cd.png)

the bottom part is clearly the one that is wasting more space, in my opinion (it takes a lot of screen real estate for things that could be placed in a lot less room).

**Comment by artisteacher** [comment]
I think the resizing was limited so that the text doesn’t get clipped.  I think #1397 will help with this issue.

**Comment by gab3d** [comment]
@artisteacher, yes, it'd help, but there's still room for saving pixels here and there, like this exercise I just did in Photoshop, proves.

![compact_style_ed](https://user-images.githubusercontent.com/18104091/31103389-0972b1b2-a7ad-11e7-916a-08118fc3654a.png)

**Comment by gab3d** [comment]
I've come again over this issue: The big screen space currently needed for the Style Editor.
Everytime I try to accomodate panels in "a better than default" way I stumble against the unreasonable big space this editor takes for being usable, and I see there are parts (as the bottom part, specially) that takes a LOT of space for things that realy should not.

In this mockup I've managed to reduce its footprint even more by moving the informative text to the title bar (as in other editors like the Visor or Xsheet currently in OT).

If any coder here could dedicate some working hours to this, it could make a big difference in everyday's usability of the UI.

![style_editor_compact](https://user-images.githubusercontent.com/18104091/33281857-6fb115f0-d385-11e7-8a4b-afd446fbdb25.jpg)

**Comment by artisteacher** [comment]
If it’s possible, I think the settings toggle should go in the tab area to the very right. I think the @gab3d’s change for the auto/apply buttons would be a fantastic change. My work computer has a particularly small screen, so I definitely see the benefit. I wonder if the two swatches at the bottom could move into the end of the above row?

**Comment by artisteacher** [comment]
While the wheel can still be very small, #1622 has really helped make the style editor usable on a small screen.

**Comment by gab3d** [comment]
yes, indeed!
