### ISSUE TITLE
XSheet Update Issues. 

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#1506]
I really like the new column headers but there are 2 problems that I am having.

1: I can't select a frame. It always prompt's me to rename the frame and I can only perform other actions by right clicking the behavior should be the other way round this behavior makes it almost impossible to use shortcuts as it is always trying to change the frame name.

2: I can no longer use undo when the cursor is over the XSheet

**Comment by manongjohn** [comment]
That behavior sounds like you have "Enable to Input Cells without Double Clicking" enabled in the Xsheet Preferences.

**Comment by BrundleThwaite** [comment]
Sorry, My bad
