### ISSUE TITLE
Style change shortcuts too low in GUI

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1511]
The style change keyboard shortcuts a little low in the GUI and are somewhat hard to read.

![style](https://user-images.githubusercontent.com/4576381/31325596-0294d6d0-ac7c-11e7-8384-d3ff61e6c852.JPG)

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for creating this issue. Fixed it.
