### ISSUE TITLE
Problem with the key/interpolations, help!

### ISSUE THREAD

**Issue by Gilbert124** [opentoonz/opentoonz#1518]
Hello friend and OpenToonz support, I have a big problem with a project that I tried to do since long time, the problem is that I do not keep the intepolacion or the keys, my doubt is as guado the whole project absolutely as I leave? when I keep it and open it does not appear the movement interpolations
![1234](https://user-images.githubusercontent.com/32717387/31480396-434cb508-aee3-11e7-90de-9ebe9f4bc686.jpg)
![12321](https://user-images.githubusercontent.com/32717387/31480398-4843e40a-aee3-11e7-9f04-d2d1abe7f12e.jpg)
![0](https://user-images.githubusercontent.com/32717387/31480401-4b7bd786-aee3-11e7-9c7f-56ed5a4eb3a3.jpg)

Help me please :"(

**Comment by turtletooth** [comment]
Are you saving the scene or just the levels?  Interpolation is saved in the scene file, not the level files.  The level files only contain the drawing (and sometimes palette) information.  To maintain the interpolation, you need to save the scene too.  Reopen the scene and you should still have the interpolation.  

Note: importing the levels into a new scene will not bring the interpolation with them.

**Comment by Gilbert124** [comment]
But when I try to save the scene this happens 
![default](https://user-images.githubusercontent.com/32717387/31482116-80862130-aeec-11e7-957c-86120314b9d8.jpg)

**Comment by RodneyBaker** [comment]
Closing as likely resolved.
@Gilbert124 Please advise if problems still persist.
