### ISSUE TITLE
Command Bar Refinements 

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1526]
Just a couple thoughts on the command bar/Xsheet toolbar:
- there are a couple commands that don’t seem to work at all when attempted from the command bar (ie. Fit to window, reset view, global key)
- some commands are greyed out when they are not possible (due to active level type, empty cell selection or etc) but others are not 
- when customizing the bar, it can be hard to find the desired command - having a search option (like when setting shortcuts) would be helpful 
- dragging & dropping is sometimes glitchy in OS X (when trying to drag a specific command, often a different command actually moves)
- some commands do have icons elsewhere in the program but the icons don’t display (field guide, fit to window, set key) - though in many cases the commands with existing icons are unlikely to be added to the command bar since they are usually already visible in the UI

Thanks @turtletooth for this great addition! I love the customization possible. Also, do you want icons for other commands? Here are some possibilities for time stretch, load level, and canvas size:
![6e7772d9-8524-4547-ab79-aa8718a86c9f](https://user-images.githubusercontent.com/21159116/31641417-73ec437c-b2b2-11e7-98fe-f9fbd6b6eae3.png)

**Comment by Agnyy** [comment]
I want to make my suggestions.
1. Add a search.
2. Add the ability to upload icons.
3. The ability to resize as in Krita
![untitled-1](https://user-images.githubusercontent.com/25137502/31654300-4bc5065a-b32e-11e7-9714-3ce1c88731a2.jpg)

![2017-10-17-11-20-52](https://user-images.githubusercontent.com/25137502/31654305-5077fc20-b32e-11e7-9d2c-0ef6990ff91a.gif)

**Comment by turtletooth** [comment]
@artisteacher Can I get the files you have for those icons?

**Comment by artisteacher** [comment]
Here you go!
[Possible Icons.zip](https://github.com/opentoonz/opentoonz/files/1513767/Possible.Icons.zip)

**Comment by artisteacher** [comment]
I added another one for the upcoming enabling/disabling touch command and made the stroke of a couple other potential icons consistent with the others.
[More icons.zip](https://github.com/opentoonz/opentoonz/files/1517720/More.icons.zip)

**Comment by DoomDesigner** [comment]
![image](https://user-images.githubusercontent.com/32999433/33664831-0731e400-daa6-11e7-8ffa-a24d9d743b5e.png)

I think I need to add icons (Play, Pause and others). Simply personally, I like the location of the icons from the bottom.
![image](https://user-images.githubusercontent.com/32999433/33664982-6f9aecd0-daa6-11e7-98ab-fdac3afabe38.png)
https://github.com/opentoonz/opentoonz/issues/1637

**Comment by DoomDesigner** [comment]
![image](https://user-images.githubusercontent.com/32999433/33665214-38a2f6ae-daa7-11e7-9434-935a197e1104.png)

Many icons are missing. And some of the functions do not work correctly. very frustrating that "Geometric Shape" does not work.

**Comment by RodneyBaker** [comment]
> Many icons are missing.
Not missing so much as they have not yet been created.
That menu bar is a WIP feature that only recently was added to OpenToonz and @turtletooth put in a request for anyone that desired to create accompanying icons.  That can be found in the PR where the menu bar was created.

I'm not sure about the Geometric Shape not working correctly.  That sounds like a bug/disconnect to me but on the other hand... I'm not entirely sure why it would appear on that menu in the first place.

**Comment by DoomDesigner** [comment]
Tell me where do I send my icons? if I want to be added. @RodneyBaker

**Comment by konero** [comment]
I confess I haven't worked with command bar yet, but wouldn't it be easier working with custom panels instead like TVPaint and Corel Painter instead of a bar like Clip Studio?

![handy-panel](https://user-images.githubusercontent.com/19820721/33669685-0cbfd32e-da9b-11e7-9120-2a0a9ab20c2c.png)

![rwe1](https://user-images.githubusercontent.com/19820721/33669852-75d12da4-da9b-11e7-9c95-62ca78b52a5f.png)

**Comment by shun-iwasawa** [comment]
@DoomDesigner 

>  "Geometric Shape" does not work.

You need to open Tool Option Bar to make the "Geometric Shape" command button to work. 
Because, for now, it does not change directly the tool option, but controls the visible tool option widget.

**Comment by artisteacher** [comment]
It's great having the new icons merged in - thanks @turtletooth. I do think that the icons do need more visual consistency. Timestretch looks way to big compared to the others - at least on a high res screen. Load level looks great but is a little larger and crisper than the new level icons. Perhaps the new level icons should be redone to match the size/contrast of load level?
<img width="232" alt="screen shot 2018-02-21 at 4 18 19 pm" src="https://user-images.githubusercontent.com/21159116/36506041-68704c3e-1723-11e8-9d0f-bb266b22d293.png">

**Comment by RodneyBaker** [comment]
> the new level icons should be redone to match the size/contrast of load level?

Not a high priority but excellent fodder for someone trying to get their feet wet with OpenToonz development.

**Comment by artisteacher** [comment]
@RodneyBaker - I'm giving it a go! #1827

**Comment by RodneyBaker** [comment]
Status check:  Part of this feature request/enhancement of the Command Bar has a bounty associated with it but currently no one actively developing for it.

**Comment by RodneyBaker** [comment]
This enhancement needs additional time for review and development.
As such this update has slipped to the 2019 development cycle.
Tagged with 'roadmap' as implementation appears very likely.
