### ISSUE TITLE
Pen Draws off Canvas with Certain Setups

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1529]
In a setup with multiple monitors with different scaling (I have a surface pro at 200% scaling and other monitors at 100%), drawing - only with the pen - draws off of the canvas.  Drawing with the mouse works fine.  
For example in a vector layer if I draw on the canvas, the drawing is drawn outside of the visible area.  I have to scroll way to the right to find my strokes. 

This only happens when using the pen.  Somewhat related might be that when using the touch controls to zoom, it doesn't zoom to the center between the fingers.

**Comment by RodneyBaker** [comment]
Not sure if this is still an issue.
Likely resolved.

**Comment by RodneyBaker** [comment]
Closing as abandoned (by ghost).
There are a number of related reports open with issues with mutliple monitors with different resolution/scaling.
