### ISSUE TITLE
The problem with SVG work

### ISSUE THREAD

**Issue by DoomDesigner** [opentoonz/opentoonz#1533]
SVG is not working properly 

![new project](https://user-images.githubusercontent.com/32999433/31861206-c8c84a02-b731-11e7-84de-c642edf609d4.png)

![new project 1](https://user-images.githubusercontent.com/32999433/31861210-cb5ab2e6-b731-11e7-9ed5-1f62bef1420e.png)

**Comment by DoomDesigner** [comment]
![design](https://user-images.githubusercontent.com/32999433/31861248-83db00f0-b732-11e7-952c-b20665900056.png)
![new project](https://user-images.githubusercontent.com/32999433/31861249-84cb735a-b732-11e7-99dc-00119c3ddb77.jpg)

**Comment by jpturcotte** [comment]
Possible duplicate of #1009.

**Comment by RodneyBaker** [comment]
See suggested workaround in #1009.
