### ISSUE TITLE
not working on tablet

### ISSUE THREAD

**Issue by vinurd** [opentoonz/opentoonz#1536]
not working on tablet WacomCintiq13HD 
brush off-center, the entire interface is horribly stretched.

**Comment by jpturcotte** [comment]
We would need to know your operating system and your version of OpenToonz, and also see a screenshot or video capture of the problem. Are your Wacom drivers up-to-date? Thank you!

**Comment by vinurd** [comment]
operating system, windows 10. Tablet just bought , driver  new. The center of the pen does not coincide with a center draw. The interface is all stretched
<a href='https://hostingkartinok.com/show-image.php?id=d491fc35c2999bef0509dcc4f041039c' title='бесплатный хостинг картинок'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/10/d491fc35c2999bef0509dcc4f041039c.png' alt='Yes' /></a>
<a href='https://hostingkartinok.com/show-image.php?id=fff6988392834a1278c879a047dfe463' title='загрузить селфи'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/10/fff6988392834a1278c879a047dfe463.png' alt='Yes' /></a>

**Comment by vinurd** [comment]
<a href='https://hostingkartinok.com/show-image.php?id=630fc30ed32286e2244550cd199b8a65' title='share a picture'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/10/630fc30ed32286e2244550cd199b8a65.png' alt='Yes' /></a>

**Comment by shun-iwasawa** [comment]
It seems that the UI is magnified for high dpi displays although the dialog and the title bar are in normal sizes.
Can you check the display scaling ? ( Right-click the desktop > Display settings > "Change the size of text, apps, and other items" ) If it is not 100%, please try to set it to 100%. 
Since WacomCintiq13HD has 1920 x 1080 pixels monitor, I think the normal dpi mode would be suitable.

**Comment by vinurd** [comment]
installed all right, most apps work fine. Tested on 10 programs - all of them works smoothly. The only problem with OpenToolz.

**Comment by jpturcotte** [comment]
Have you tried what @shun-iwasawa told you?
> Can you check the display scaling ? ( Right-click the desktop > Display settings > "Change the size of text, apps, and other items" ) If it is not 100%, please try to set it to 100%.

**Comment by vinurd** [comment]
Yes. installed that way.

**Comment by vinurd** [comment]
TVpaint works perfectly. All graphics programs work. 1 the program does not want to work - open toonz
