### ISSUE TITLE
cant install opentoonz 64bit

### ISSUE THREAD

**Issue by sestinalyric** [opentoonz/opentoonz#154]
im sure im just dumb and cant find the guide in front of my eyes but when i try to install it, it says error, and then it says i cant install 64bit software or something like that?? and i have no idea what this means?? is there some other download link then that is not 64bit?

**Comment by Goofybud16** [comment]
Is this on Windows?

If so, it means you are running a 32 bit version of Windows. OpenToonz requires a 64 bit version of Windows, so you will have to

    1. Upgrade your computer to have a 64 bit processor (if it doesn't)

    2. Reinstall Windows with a 64 bit disk
