### ISSUE TITLE
Issue display with selection tool in freehand

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1544]
Reported by openanim in the forum:
https://groups.google.com/forum/#!msg/opentoonz_en/OJBUHffTcrI/b27NLDoSBgAJ

> I can't see the display of selection with selction tool in freehand. Last OTX on all levels.

<img src="https://lh3.googleusercontent.com/-RP7by-jAGW4/WfYIHjdpt3I/AAAAAAAAAI4/WI1UdG6f2hApBRLoAprVvZX0h23N4DvHgCLcBGAs/s1600/Issue%2Bselection%2Btool%2Bfreehand%2Bdisplay.gif" width=300>

Confirmed that in "Freehand" options of any tools the lines are invisible for now.

**Comment by turtletooth** [comment]
There is a lot of OpenGL code in the PR, that I don't understand fully and therefore can't accurately check.  However, I have tested this and the freehand lines do appear properly.  If you are ok with this type of check, this is ready to be merged.  Thanks @shun-iwasawa for the fix.
