### ISSUE TITLE
Crash:  Lost/Corrupted Level Files (Need help recovering missing files)

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1546]
Need to report a bug, but also at the same time need some help recovering. 

I've been working on an animation for the past 3 days now, despite the crashes in between, but on one of those crashes everything I've worked on so far seems to have disappeared. All the vectors, all the bitmaps and colors, everything seems to have gone from this save. 

What could I do to make sure this doesn't happen again? Also, how do I recover the files / levels again?

![workspace 1_832](https://user-images.githubusercontent.com/5314015/32191609-b39792e4-bdd7-11e7-9799-acecc52fbe4d.png)

**Comment by manongjohn** [comment]
Based on that popup, I suspect that something has corrupted the scene file (.tnz) in a way that it cannot be read properly.  However, your level files may still be there and intact. 

If you've been "importing" stuff into the project, then everything should be somewhere under your main project folder.  If not, your files and anything related to it would be in the original folders you loaded them from.  See if they are still there.  Unfortunately, if they have been physically deleted, they are gone unless you have some backup somewhere.

Can you post your .tnz file to review?  I'm curious to see what may be wrong with it.  If you have an earlier version for comparison, that would be great.

**Comment by tushantin** [comment]
Unfortunately, I do not have the earlier version of the .tnz file. I guess that's my bad, since I always figured that the drawings were probably saved in separate files or something. :/ 

If there's any way I could re-import those levels "and" the animations / node-hierarchies, that would be amazing. Would you happen to know how I could do that? 

[4.tnz.zip](https://github.com/opentoonz/opentoonz/files/1428583/4.tnz.zip)

**Comment by manongjohn** [comment]
Should just be able to select the all the cells for a particular level the Xsheet and use "Replace Level", picking the same file that was there before.

**Comment by tushantin** [comment]
It's weird. "Replace Level" doesn't seem to help here, despite picking the same file. The original files are all there in their own place (at least the "loaded" ones rather than "imported" ones). But they still don't appear in the scene...

**Comment by tushantin** [comment]
UPDATE: Another thing I just noticed is that I'm able to import these levels in another different scene entirely, and "some" of them seem to be able to open up fine. But they won't open in this scene, where all the animations are stored. I don't know what to do. :/

**Comment by manongjohn** [comment]
I took a look at your .tnz file and unfortunately it looks incomplete as if it was in the middle of writing out stuff when it crashed.

Do you know what you might have been doing when it crashed to cause this?

As you are using the Morevna build on a Linux machine (i believe), the issue that caused this might be specific to that build.

**Comment by tushantin** [comment]
Yeah, I remember. OpenToonz seems to be very prone to crashing for me, so I have a habit of constantly saving in-between tasks. I created a mesh for the L Waist level and was in the process of creating a skeleton for it. However, the Root bone didn't seem to respond at that moment, so I decided to hit Ctrl+S, but upon pressing it, OT just crashed. I figured it may have crashed while saving simultaneously. 

But funny enough, I think all the animations "seem" to still be there. I want to know if it's possible to recover all that. 

@morevnaproject Sorry for tagging you out of the blue, but do you think this may be a Morevna-build specific issue?

**Comment by gab3d** [comment]
It'd be very useful to have an "Increment and Save" menu option in the File menu, as other programs have. (I'm thinking of After Effects or Maya here)

When using that option, OT should add 1 to the current scene file name and then save the scene with that name.
For example:
If the file was called MyScene.001.tnz, when using that function for saving, a new MyScene.002.tnz file would be generated.
If the file was called just MyScene.tnz (without any trailing version numbers), then when using that function for saving, a new MyScene.001.tnz file would be generated (default number of digits probably set in a User Preference parameter).

Using such a system, cases as the one reported here should never happen.

**Comment by morevnaproject** [comment]
> @morevnaproject Sorry for tagging you out of the blue, but do you think this may be a Morevna-build specific issue?

It is hard to tell. You can check this by yourself by compiling OT from source and comparing if it will behave better or not. The main problem is that it would be very hard to trigger the problem again.
Anyway, just want to mention that we didn't included any modifications to code related with file saving.

> I'm able to import these levels in another different scene entirely, and "some" of them seem to be able to open up fine.

>  I want to know if it's possible to recover all that.

From the two sentences above I can suggest the following: You can create a new scene and import all levels into it. ^__^

**Comment by tushantin** [comment]
@gab3d Brilliant! I think I should create a separate thread for that specific feature request. 

@morevnaproject 

> You can check this by yourself by compiling OT from source and comparing if it will behave better or not.

Since I wanted to try out the github version of OT, given the issues with the tablet in another thread, I actually tried to compile myself but it ended up giving me a lot of errors, and failed to compile / install. I didn't know how to fix it (I searched around for answers) so I ultimately abandoned the attempt entirely. :/ 

> From the two sentences above I can suggest the following: You can create a new scene and import all levels into it.

Yeah, but see, the problem is that only half of my animations are hand-drawn, while the other half had properties like plastic-mesh, vfx and transform. That's something I'm not entirely sure I can get back in a new scene. :/ But I suppose there's no other choice...

**Comment by morevnaproject** [comment]
> only half of my animations are hand-drawn, while the other half had properties like plastic-mesh, vfx and transform.

For plastic mesh you can just import *.mesh files like ordinary level. Just make sure to connect it properly to corresponding layer in Schematic View ^__^ -

![screenshot_001](https://user-images.githubusercontent.com/332868/32227626-80e2eb80-be7e-11e7-9e62-b56512febe9f.png)

**Comment by artisteacher** [comment]
I just had a student run into the same issue with 1.2 on OS X 10.11.6 (not the Morevna release). The student was drawing on 2 new vector levels going frame by frame and using onionskin. It most likely happened when using the select tool to adjust part of the vector drawing. Auto-save was set to every 7 minutes. After the crash, all of the frames displayed in the Xsheet with the red numbers just like @tushantin's screenshots. The levels themselves are completely missing/non-existent. I have noticed that vector levels seem to cause periodic crashes without any obvious reason. 
[selectcrash.txt](https://github.com/opentoonz/opentoonz/files/1598184/selectcrash.txt)

**Comment by artisteacher** [comment]
I’m still having students run into this periodically - and not always on vector levels. Today a student opened a scene and a raster level was missing. There’s no trace of it on the computer (beyond the red lettered missing level in the Xsheet and scene cast). I’m assuming it’s from a prior crash but we’re not sure when it happened.

@manongjohn were you working on temporary level files?

**Comment by manongjohn** [comment]
@artisteacher Unfortunately, not at the moment.

Oddly, when I briefly looked at temporary save files for levels, all but 1 level type was supposedly using a temporary save file.  However, when I tried to test for it,  I couldn't see the temp file being created even though stepping through the code says it was.

Will try and get back to it when I can, unless someone beats me to it of course.

**Comment by artisteacher** [comment]
@manongjohn thanks for putting this on your list, even if it will be a while.

I tried to find the temporary files too but only saw the temporary scene files being created. There is a temp folder in the Stuff’s cache folder but it seems to only hold empty, untitled & unsaved scene folders. The other cache folders always seem to be empty too. 

On a related note, I recently zipped a project and shared it with a few students in Google Drive to try out a new technique. 4 of the levels were missing when they accessed the scene. It looked like the files were still there in the Browser, but missing any frames. The original project still has everything intact.

**Comment by walderalexandre** [comment]
I'm experiencing a similar issue. In my case, when I reopen the project sometimes my meshed image is not visible, even though I can see it by opening it in the editing mode. Inside the Browser I see the mesh level is in red. What I did, and it worked for me, was selecting the mesh level column and reaplied the mesh command. As I said, my imagem was not corrupted, just the mesh.

**Comment by artisteacher** [comment]
Something that can be helpful is to enable “backup animation levels” in preferences. When you save all, backups of all the levels in the scene are created. If you lose a level or it gets corrupted by a crash, you should still have the backup level (updated with each save) available.

**Comment by RodneyBaker** [comment]
I believe the 'Recovery' part of this issue can be closed as any files desired to be recovered have likely been recovered (or not) by this time.

Is there anything related to the 'Crash' part of this issue that can identify a potential cause?
If not, recommend closing this issue and opening new issue(s) as required.

**Comment by RodneyBaker** [comment]
As the original issue is over two years old... and the recovery issue more a matter of history... closing as a one time problem. (with reports of other similar issues noted!)

@tushantin If you are continuing to experience issues please let us know and/or open a new report.
Thanks!

Everyone else:  If you are still experiencing issues please open a report.
