### ISSUE TITLE
Crash at startup Windows 10

### ISSUE THREAD

**Issue by Larsenges** [opentoonz/opentoonz#155]
Whenever I attempt to open up OpenToonz, within about 10 seconds I get "OpenToonz is not responding."
I've tried uninstalling and reinstalling the program and I'm honestly not sure what else I could do.
![asdadf2e4gfth](https://cloud.githubusercontent.com/assets/18370142/14406074/f7613f16-fe52-11e5-8b12-32d51ba8b731.PNG)
OS: Windows 10 Home
RAM: 8.00 GB
Processor: Intel(R) Pentium(R) CPU N3540 @ 2.16GHz

**Comment by Reptapog** [comment]
#138

**Comment by Tyrvde** [comment]
I am receiving the same error on my Windows 10 machine. I'm running an AMD 6350 @ 3.9GHz with 8GB of RAM.

**Comment by ss23** [comment]
@Larsenges Are you able to try downloading and running https://github.com/ss23/opentoonz/releases/download/qt56/OpenToonz-qt5.6.7z? It's a 7zip archive, but once extracted, you should be able to run it in place.

If it works, it may point to one of the issues that was fixed with Windows 10 on qt5.6.

**Comment by Larsenges** [comment]
@ss23 Thank you!! it works!

**Comment by ss23** [comment]
@Larsenges I'm not an opentoonz developer, so it may be best to leave this issue open until the fix gets merged into the official release :)

**Comment by twinstef** [comment]
Thanks @ss23 ! ,I had the same problem and your solution works for me.

**Comment by kogaki** [comment]
@twinstef @ss23 Now we are building nightly builds with Qt5.6. Could you try them work in your environment?
