### ISSUE TITLE
I wonder your opinion.

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#1552]
Now popularity is gaining extensions with harvested animation inserts for After Effects. 
![image](https://user-images.githubusercontent.com/25137502/32351940-2bc9685a-c030-11e7-9ffc-9fba6b018808.png)
![image](https://user-images.githubusercontent.com/25137502/32352049-9e7d39da-c030-11e7-9ea9-037220156bf9.png)

I think that we can make an extension for our program and make it an animated template. how do you look at it?

https://www.youtube.com/watch?v=oj8fH1tAU3A
https://www.youtube.com/watch?v=lNA9zFfqJtE

**Comment by DarrenTea** [comment]
Will you change the title to include part of the question please, so we can see your question when browsing down the list of issues.

**Comment by RodneyBaker** [comment]
Recommend closing as a feature request pending a developer that desires to take on the work.
Discussion in the OpenToonz forum can collect and refine what is desired and best suited for incorporation into OpenToonz.

@Agnyy what say you?

If you just want to know if people want transitional effects like that the answer is, "yes".  :)
