### ISSUE TITLE
Drawing on the level when "camera ..." toggle is turn off

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1559]
You can drawing on level in viewer, When camera toggle is turn off. I think it is bad, because you maybe change your drawing by mistake.

![camera_toggle](https://user-images.githubusercontent.com/16509592/32508542-973d7a3a-c3e2-11e7-8662-c402113208f8.gif)

For example in photoshop, It does not allow you to drawing on layer when it is hidden.

![drawing_on_hidden_layer](https://user-images.githubusercontent.com/16509592/32508568-a8ae9c4a-c3e2-11e7-8b5c-b8c4c7a8afb4.jpg)

**Comment by artisteacher** [comment]
I completely agree!

**Comment by gab3d** [comment]
I agree with that one.

**Comment by DarrenTea** [comment]
I agree, but what would be better would be to have disabled buttons, so you can't even select the brush tool. There are times (I can't remember off hand) when you can select the brush tool and when you try and paint, you get a popup telling you that you can't paint on this type of level (either raster or vector, I can't remember which).

**Comment by artisteacher** [comment]
What would be the behavior when changing between visible and hidden levels? Ie. changing from a visible level with the brush active to a hidden level?
