### ISSUE TITLE
Additional communication channel request

### ISSUE THREAD

**Issue by musicm122** [opentoonz/opentoonz#156]
Could we possibly have a channel, forum, slack chat or a secondary method of communicating questions or issues related to development of the project? One reason I suggest this is because I've been trying to get the mac build up and running and have found several pull requests and variants that have similar proposed fixes.  Lots of potential energy wasted on solving the same problems over and over.

**Comment by blurymind** [comment]
An irc dev channel would be nice

**Comment by musicm122** [comment]
I'm actually partial to slack myself.

**Comment by RodneyBaker** [comment]
As anyone is free to open a slack chat I'm not sure how this issue relates to the software unless the request is to have chat added into the OpenToonz UI itself.

If maintained perhaps this could be renamed as "Slack Communication Channel Request" perhaps with request for more feedback from @musicm122 to refine the objective.

I note tthat this request has several 'features' that others have echoed in the main forum such  the desire to improve communication relatd to the Mac build.  Reference: Phillip Stumps forum query seeking information on Mac programmers ([LINK](https://groups.google.com/forum/#!category-topic/opentoonz_en/c0nyIcVi7BUvvvv))

Regarding Slack...
It may be useful to discuss some of the benefits slack chat brings to the table especially where it enhances communication over similar methods of communication such as the (current) OpenToonz IRC.   To date not a lot of developers and users have used the IRC so it may be worth identifying where use of slack can increase general communication related to OpenToonz and (with regard to the orginal request) how to use that to resolve outstanding issues related to using OpenToonz on the Mac.

**Comment by turtletooth** [comment]
It seems there is already an opentoonz.slack.com
Does anyone know who is running that one?
I made an opentoonzteam.slack.com in case the first one is abandoned.

**Comment by RodneyBaker** [comment]
> It seems there is already an opentoonz.slack.com
> Does anyone know who is running that one?
> 

That is the channel I just created and linked to above.
Definitely not abandoned.... just not yet used.  ;)

**Comment by turtletooth** [comment]
Would you mind inviting me?  jcbullock at gmail

**Comment by RodneyBaker** [comment]
Done.

A bit weird that invites are needed.
I'd think that random people should be able to drop in.

**Comment by turtletooth** [comment]
That's where IRC is a little easier than slack.
