### ISSUE TITLE
Browser:  Select All and Ctrl+A not working correctly

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#1561]
If you choose Select all, your main folder will be closed.

![select_all](https://user-images.githubusercontent.com/16509592/32508702-0eb824f2-c3e3-11e7-90da-c56da506c7a3.gif)

When you press Ctrl+A, Nothing is selected. But if you move your mouse to bottom and then back, It will work.

![select_all_shortcut](https://user-images.githubusercontent.com/16509592/32508706-15815efc-c3e3-11e7-9106-cc579810f027.gif)

**Comment by RodneyBaker** [comment]
This is still reproducible per @2dvision examples.

**Comment by RodneyBaker** [comment]
The first problem identified appears to be resolved.
Using Select All from the Right Click menu works here.

Although assigned as a shortcut key Ctrl + A still does not work.
