### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by damies13** [opentoonz/opentoonz#1566]
I have been getting this for a while... it stopped me from working on the issues that I was working on, so to confirm it wasn't me I switched back to the master branch and I get the same issue when trying to compile for OSX.

I had hoped it would be resolved quickly but after a month i'm still getting this when trying to compile from master even after getting the latest updates for master. I found that it has also been reported before as issue #40 (Compilation notes for OSX #40) back in 2016. I tried the resolutions listed in that issue, but it didn't seem to help.
I have since upgraded xcode and it's command line tools (in case that was the cause) and have also tried to use the "ci-scripts/osx/travis-install.sh" and "ci-scripts/osx/travis-build.sh" scripts but I still get the same error (below):

[ 51%] Linking CXX shared library libimage.dylib
Undefined symbols for architecture x86_64:
  "_lzma_code", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.o)
      _LZMAPostEncode in libtiff.a(tif_lzma.o)
      _LZMAEncode in libtiff.a(tif_lzma.o)
  "_lzma_end", referenced from:
      _LZMASetupDecode in libtiff.a(tif_lzma.o)
      _LZMASetupEncode in libtiff.a(tif_lzma.o)
      _LZMACleanup in libtiff.a(tif_lzma.o)
  "_lzma_lzma_preset", referenced from:
      _TIFFInitLZMA in libtiff.a(tif_lzma.o)
      _LZMAVSetField in libtiff.a(tif_lzma.o)
  "_lzma_memusage", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.o)
  "_lzma_stream_decoder", referenced from:
      _LZMAPreDecode in libtiff.a(tif_lzma.o)
      _LZMADecode in libtiff.a(tif_lzma.o)
  "_lzma_stream_encoder", referenced from:
      _LZMAVSetField in libtiff.a(tif_lzma.o)
      _LZMAPreEncode in libtiff.a(tif_lzma.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/libimage.dylib] Error 1
make[1]: *** [image/CMakeFiles/image.dir/all] Error 2
make: *** [all] Error 2

Is anyone else getting this when trying to build for OSX? Any suggestions?

I am now on OSX 10.13.1, but I was also getting this error when previously on OSX 10.12.x before updating OSX.

**Comment by jpturcotte** [comment]
Maybe @morevnaproject & @blackwarthog can help?

**Comment by blackwarthog** [comment]
Please try to build libtiff in thirdparty dir manually.

```
cd thirdparty/tiff-4.0.3
./configure
make
```

Clean build directory and run CMake again.

NB. Also may be required to fix line 22 of file `toonz/cmake/FindTIFF.cmake`. Replace **libtiff.a** to **libtiff.dylib**

**Comment by damies13** [comment]
@blackwarthog ok tried those suggestions in this order:

1. make clean in build dir
2. build libtiff in thirdparty dir manually (also did sudo make install)
3. back to build dir, run cmake and then make
- failed same error
4. make clean in build dir
5. modify toonz/cmake/FindTIFF.cmake line 22 to libtiff.dylib
6. run cmake and then make
- failed same error

Is there extra info I can provide to help resolve this?

$ cmake --version
cmake version 3.5.2

$ make -v
GNU Make 3.81

**Comment by damies13** [comment]
Tried to build from opentoonz/master again today, this is no longer an issue for me, will close this issue.

I did have one build error (Issue #1639) which I figured out how to fix, so will submit a PR for it.
