### ISSUE TITLE
Preview and plastic tool regularly causes crash

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1567]
Having preview active in the viewer while the plastic tool or a plastic skeleton is also active seems to be causing numerous crashes in OS X 10.11.6 and 10.13.1. This is with the latest nightly builds but may have begun earlier. A crash occurs when :
- scrubbing the animation (in this case the skeleton tool does not need to be active)
- pressing the first frame button while the animation is playing 
- when trying to move a vertex (in animate mode) - this crash sometimes occurs immediately and sometimes after moving multiple vertices in multiple frames 

I don’t normally try to animate with preview active but I was trying to work around the new vector visibility problem #1543.

<img width="688" alt="55ecc8b0-8c26-4061-8cac-6abb633ae7c3" src="https://user-images.githubusercontent.com/21159116/32580100-c4be4e60-c4b1-11e7-8d75-4ea73a558e4b.png">
<img width="982" alt="16b0dbe3-96c2-4032-9bb8-cdc40db2919e" src="https://user-images.githubusercontent.com/21159116/32580076-aa768716-c4b1-11e7-9e90-dfe0ea2755a5.png">
<img width="1023" alt="59044b7e-3ce5-46e9-85b4-affb7d9b6557" src="https://user-images.githubusercontent.com/21159116/32580077-aa9ce500-c4b1-11e7-85a5-d99e4193d450.png">
<img width="777" alt="b1ce8c50-010c-43f6-a0a3-79e6cca3aac7" src="https://user-images.githubusercontent.com/21159116/32580149-f5e763be-c4b1-11e7-9182-28a2671f3103.png">

**Comment by manongjohn** [comment]
Unfortunately, I tried to duplicate this issue on the Windows build, but couldn't. I tried replicating using the 2nd and 3rd examples. Not sure if I am missing something or if it is specific to OS X.

**Comment by shun-iwasawa** [comment]
I couldn't reproduce the crash on my environment of OSX 10.12.4 ... I may miss something.
@artisteacher can you please upload some simple example ?

**Comment by artisteacher** [comment]
It seems like the crash has been resolved in the later builds - maybe it had to do with the vector visibility issue?

**Comment by artisteacher** [comment]
I’m getting the crash again when trying to move a vertex in the plastic tool’s animate mode in 1.2 and in Morevna’s 1.2 if preview is active. The crash report is the same as before.

To duplicate:
- create a new scene with a single level (1 frame)
- draw a basic shape and give it a fill
- create a plastic mesh
- use build skeleton to add a few vertices
- switch the mode of the plastic tool to animate 
- toggle on preview 
- move the vertices
Usually the crash is pretty immediate though occasionally you need to move vertices for a few minutes before the crash occurs.

**Comment by artisteacher** [comment]
With a clean install & the plastic grid lines fix, I’m no longer getting a crash.
