### ISSUE TITLE
edit tool - edit all mode - bring back the manipulator widget from harlequin 

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#157]
Right now with the edit tool the user has to manually switch between manipulator modes. This is all ok, but it is not quite as fast as just being able to grab a handle on the viewport to rotate and another one to move.
This is how it looks in opentoonz:
![manipulatorgone](https://cloud.githubusercontent.com/assets/6495061/14439071/30131e68-0021-11e6-8d55-76f0ffc41492.JPG)

And this is how it used to look like in toonz harlequin:
![oldmanipulator](https://cloud.githubusercontent.com/assets/6495061/14439084/3e9b863c-0021-11e6-8243-42f73d03d415.JPG)

I feel like this is another lost feature from toonz harlequin - where the design was probably changed in order to reduce the possibility of error in a traditional animation workflow pipeline.

In a cut out animation style however the user has to constantly switch between moving and rotating things. Without this manipulator widget, the workflow becomes really slow as one must constantly switch between modes. With it you can just grab on the widget to rotate and on another to move.

My request is not to bring back the old design from harlequin and replace the current one - but a middle ground. Bring back the old design in the form of a new mode to postition,rotation,scaleshear,center and call it "ALL". In that mode the user can manipulate all the properties just the way they used to in harlequin - with a single widget

**Comment by Rayek** [comment]
I agree - restoring this option would optimize the workflow quite a bit. I really like the "all" option as a middle ground solution.

**Comment by blurymind** [comment]
perhaps @shun-iwasawa or @Banbury could look into it? :)

**Comment by Banbury** [comment]
I did :). But I couldn't find any remnants of the original code. As far as I can tell, someone replaced the edit tool completely.
Writing the manipulator from scratch would take more time, than I currently have.

**Comment by blurymind** [comment]
@Banbury  that is unfortunate. I agree with you that it would be easier for other developers to revert regressions if there was a version of opentoonz before the changes by ghibli on github.
Perhaps @shun-iwasawa  will continue reverting them in a way that fits with the feedback they got from ghibli and other studios.
My hope is that all features will return, but with an improved design that is a middle ground which keeps changes they made to it as well.

**Comment by turtletooth** [comment]
@blurymind What do the bottom parts of the triangle manipulator do?

**Comment by blurymind** [comment]
@turtletooth Apologies, I cropped them last time.
![manipulatorregression2](https://cloud.githubusercontent.com/assets/6495061/15949934/d998b948-2ea2-11e6-8287-1c27b3762dc5.PNG)

**Comment by turtletooth** [comment]
Thanks.  I will look into it.  I have the new level name thing working- will submit a PR tonight.

**Comment by blurymind** [comment]
@turtletooth  awesome stuff! Thank you :D

**Comment by Juls3000** [comment]
After OT v.1.0.3. Really this manipulator widget will be the "icing on the cake".

![animation](https://cloud.githubusercontent.com/assets/19145844/16169954/762ef304-3541-11e6-9b0b-517e7f5bfda1.gif)

**Comment by turtletooth** [comment]
@blurymind would you be able to post a video of this in action so I can see the desired behavior?

**Comment by blurymind** [comment]
@turtletooth Hope this helps
![edittool](https://cloud.githubusercontent.com/assets/6495061/17008496/c63faa02-4ee9-11e6-9134-1152faab61aa.gif)

there was a link to the manual somewhere as well - but i cant find it

**Comment by shun-iwasawa** [comment]
Sorry for not being available to respond to this for a long time.
This gadget is one of the unique UIs in Toonz Harlequin and I agree that having all handles is somewhat useful for making rough transformation. But IMO there is room for improvement in design as follows:
- All handles are close to each other and user may touch by mistake.
- The "Scale" handle is at very near distance to the center(=anchor point). Scale value is computed from ratio between the "handle length" and the "distance from the anchor point to mouse position". So having short handle length makes very sensitive to mouse position, which means it is difficult to adjust value accurately.
- The "Scale" and "Rotate" handle positions are fixed, which means that users need to start dragging from specific position. Sometimes users would like to transform a drawing in order to make a certain part of the drawing to be placed to the position desired. So it would better to enable users to start dragging from anywhere.
- The "Shear" transformation is IMO rarely used compared to the others.

This is why I decided to separate handles for each axis and use shortcut key for switching them.
I would like to get your thoughts on this.

**Comment by Rayek** [comment]
After meditating a while on Shun-Iwasawa's comments, and assigning shortcut keys to each Edit command, I actually agree that the current implementation works really well and fast. I was not aware it was possible to assign keys to these, and I now use G, S, and R (Blender defaults :-)

I have changed my opinion - I now favour Shun-Iwasawa's method. It's quick and effective.

Even so, many users (especially animators) prefer to work with a visual widget. And sometimes it is handy to have both options. Also, do not forget about graphic tablet and Cintiq users: shortcut keys and that dropdown are just too fiddly to smoothly work with.

How about this solution: 

- expose the four options (scaling, rotation, shearing, and center) with the use of four buttons (easy for graphic tablets/Cintiqs). Get rid of that terrible dropdown. And NO checkboxes!!! Buttons.
- one or more buttons can be activated, which will display that part of the on-screen widget. For example, the use can activate both scaling and rotation (buttons will look pressed down in this state). Those controls become visible, while shearing and center remain hidden.
- we should still be able to switch edit tool operation mode with the current shortcut key implementation. 
- ideally an option that allows for the edit tool widget to be scaled - what is more, the edit tool widget's controls are too small for comfortable use on a tablet - those areas should be scale-able as well in the preferences.

This way both workflows can be accommodated, AND users can control which visual widgets are visible in the viewport, if any.

**Comment by blurymind** [comment]
Blender may allow to use bindings like G S and R, but it also leaves the option to have the widget and even have the widget.
![capture](https://cloud.githubusercontent.com/assets/6495061/17073229/cf736162-5066-11e6-8ed0-af71ce7f200d.JPG)

How about we consider bringing back this feature as another mode - as i suggested in my first post?
![mockupmode](https://cloud.githubusercontent.com/assets/6495061/17073348/e6129806-5067-11e6-8d06-d176f4252220.png)

And then instead of scrapping the awesome widget - solving it's design flaws (by increasing its size for example) ?

**Comment by blurymind** [comment]
Blender has this solved in an elegant way:

![blenderexamplewidget](https://cloud.githubusercontent.com/assets/6495061/17073428/af130966-5068-11e6-8bd4-060948360d49.gif)

I hold shift to enable multiple widgets to be visible btw. That is how I get rotate,scale and transform to all be visible

**Comment by blurymind** [comment]
@shun-iwasawa I am not asking to replace your current solution. My request is not going to nullify your current solution - it will bring back the option to have the classic widget. 

Currently the drop down menu is slow. I prefer working with a combined widget and dont like switching

**Comment by Rayek** [comment]
@blurymind The Blender solution is exactly what I proposed as well earlier in this thread. It would allow for both workflows, and combine the workflows as well.

**Comment by blurymind** [comment]
Well the solution is right there - it's up to @shun-iwasawa to try it out and see if he likes it too :)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by jpturcotte** [comment]
Bounty now opened: https://www.bountysource.com/issues/32837292-edit-tool-edit-all-mode-bring-back-the-manipulator-widget-from-harlequin. Currently at $175 of its tentative $400 goal!

**Comment by shun-iwasawa** [comment]
Sorry to have kept you waiting - I'm working on it.

**Comment by blurymind** [comment]
thank you @shun-iwasawa  ! =D

**Comment by jpturcotte** [comment]
About Bountysource & the Edit tool bounty: When an issue is closed on GitHub, the corresponding bounty is marked as closed on Bountysource. That is what happened with this bounty. The money is fine, though. It is just frozen for the time being. The reason no bounty hunter is listed and the bounty has not been claimed in this case is that the person who developed this feature is @shun-iwasawa. Iwasawa-san is a university professor and paid developer on the OpenToonz project, and as such has stated he will not claim any bounty. It is now up to the donors to decide what to do with the money, as the bounty will not be claimed. I hope that clarifies the situation.

**Comment by shun-iwasawa** [comment]
Thank you @jpturcotte for inquiry.
Sorry, I'm quite unfamiliar with Bountysource... But is it possible to refund the bounty to its supporters (or just cancel the bounty) so that they can offer such reward for another issue? If yes, I would like to do so.

P.S. Just to let you know, I'm no longer an assistant professor of university. It has been a year since I started a new carrier as an engineer in DWANGO  :-)

**Comment by RodneyBaker** [comment]
> It has been a year since I started a new carrier as an engineer in DWANGO :-)

A belated CONGRATULATIONS to you!

**Comment by manongjohn** [comment]
I believe if the Issue is closed in GitHub with the label "Won't Do", money goes back to the donator...if I read Bountysource's faq correctly. Though it sounds like you guys can reallocate it yourselves because it's closed and not claimed?

**Comment by jpturcotte** [comment]
@adamearle Any news on where this bounty money is going?

**Comment by phillycheese007** [comment]
Does anybody know if there is an option when using the animate tool (set to all, so as to preserve stacking order option) to set it just to rotate, or position etc? I love the functionality of this tool but it is very frustrating having to click on that tiny dot before i can rotate.  
If this option does not exist...may i suggest making each of these handles checkboxes so lets say you are rotating things you just check the the rotate handle (the green dot would stay pressed until you check a different handle....allowing you freedom of rotating from anywhere on screen without having to thread a needle

**Comment by artisteacher** [comment]
I believe there is a plan to eventually display the mode icons directly in the tool option bar to make switching between modes faster/easier. That will probably get close to the functionality you are looking for.

**Comment by shun-iwasawa** [comment]
@phillycheese007 
Click the "active axis" combo box in the tool options and select any axis you would like to adjust so that you can modify just one axis (position / rotation / scale etc.) by dragging from anywhere on screen.

![image](https://user-images.githubusercontent.com/17974955/44126144-6d3b1c9e-a071-11e8-95c4-a1abcab0529f.png)

You can also assign shortcut keys for changing the active axis ( `File > Configure Shortcuts > Tool Modifiers > Active Axis - Position / Rotation / Scale ...` ).

**Comment by phillycheese007** [comment]
my issue is that the other options w/ the exception of "position" dont have  a stacking order option.

....and my excitement at discovering that the animate tool can pick columns was short-lived when i realized  i can only select a sub-xsheet ....but none of its contents......
If i have a complex character with each limb in its own sub-x....how am i realistically supposed to animate when i have to click into each sub-x to move the pieces of that body part? this seems crazy to me...
I can keep everything on the same sheet but that defeats the purpose of having a sub-x option.

Is there some way to extend the "edit in place" option to allow for selecting components of a sub-x? 


feel like im missing something
