### ISSUE TITLE
I don't know what anyone here can do about this but Bounty source continually has problems

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz#1572]
Every time I try to log into bounty source with my github ID it has some sort of internal server error (it used to be a problem exclusively on my PC but my phone could still access it. Then it was a problem with my phone, but my PC could access it. Now neither can access it).

I created an email login. That seems to work, but it's a stupid work around. I built a reputation with this github login on bounty source... I make bounties, they get funded.

**Comment by shun-iwasawa** [comment]
Please post your issue to the [Bountysource](https://github.com/bountysource/core/issues) repo.
I'm not sure but that [this one](https://github.com/bountysource/core/issues/1147) seems to be related?

**Comment by Orphanlast** [comment]
Okay, so it does look like the issue is going to be addressed there. I'm sorry, I'm still figuring out Github.

**Comment by shun-iwasawa** [comment]
OK, I hope this will be solved soon. I'll close this.
