### ISSUE TITLE
Issue with applying lip sync data to wrong column type

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1577]
I love the new addition of applying lip sync data! Thanks @turtletooth!

However, at least in OS X, if you accidentally try to apply lip sync data to the wrong column - ie. an audio column, a warning pop-up notifies that you can't apply lip sync data to that column type. Once you press "ok", the lip sync window opens anyways. After closing out of the window it is impossible to do any actions in OT. Trying to select a tool, change columns or etc. results in a warning sound but no actual action. The menu is also greyed out. At that point the only way to make OT functional again is to restart.

**Comment by turtletooth** [comment]
I can't debug this since I don't have a mac to develop on anymore.  Perhaps @shun-iwasawa might be able to look at it when he has the chance.

**Comment by shun-iwasawa** [comment]
I could reproduce the problem. Thank you @artisteacher I'll take a look.
