### ISSUE TITLE
New touch controls incompatible with trackpad

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1579]
This may be specific to OS X (10.11.6 and 10.13.1) but the new touch controls make it impossible to make any changes/adjustments to drawings in the viewer for computers with a trackpad - unless using a drawing tablet or mouse. The tools do nothing - though sometimes clicking quickly three times in a row might trigger a fill or selection or text. It is possible that this is related to tablet use. After connecting and disconnecting a tablet I temporarily was able to use the tools in the viewer as expected. However that does not consistently resolve the issue. 

Also, the 1 finger panning keeps getting triggered unintentionally (since normal navigation is done with a single finger with the trackpad). The panning would actually be really great if there was a different trigger.

**Comment by shun-iwasawa** [comment]
You means that you are using the trackpad as a normal pointing device like mouse?
Would you like to have an option for disabling the touch gesture ( just added in #1437 ) ?

**Comment by artisteacher** [comment]
Yes, I am using the trackpad like a mouse. I’d rather keep the touch controls, have panning changed to multiple fingers and have a fix for the tools being disabled. If that’s not possible, then there should definitely be an option to disable the touch gestures.

**Comment by artisteacher** [comment]
This may be related, but at this point I am only able to adjust or animate the plastic tool's skeleton with a mouse.

**Comment by turtletooth** [comment]
Closing- fixed in the latest build.
