### ISSUE TITLE
Keyframes in opentoonz - lost 'cycle' , tween spacing handles and other features from toonz

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#158]
The ability to view keyframes in the x-sheet has been removed in opentoonz.
Here is the x-sheet in opentoonz:
![xsheet-ot](https://cloud.githubusercontent.com/assets/6495061/14439699/68abaef4-0024-11e6-96be-b18871f31ece.JPG)
You can still see your keyframes in the function editor:
![functioneditorot](https://cloud.githubusercontent.com/assets/6495061/14439697/6695c24e-0024-11e6-990a-8811991e1b62.JPG)

Here is the x-sheet editor in toonz harlequin:
![xsheet-toonz](https://cloud.githubusercontent.com/assets/6495061/14439750/a765cee0-0024-11e6-840d-f623c492d9cc.JPG)

For a traditional style animation workflow it makes a lot of sense to hide the keyframes from x-sheet.

- But the removal of this has actually removed the feature to set a post infinity keyframe cycle (<><><><><><>)

- You can also no longer adjust the spacing of your tweens with the little arrows - since there are no arrows any more.

Right off the bat two very useful features have been lost.

**Comment by blurymind** [comment]
And since the curve editor doesnt allow you to edit curves as well (another brken feature?), the user can no longer adjust spacing of tweens

**Comment by CodyEakins** [comment]
I think your post is a little bit confusing as to what exactly is going on...

I know that it is still possible to repeat a selected area of frames within the X-sheet. However, the program does so simplistically (by literally repeating and duplicated the frames down the X-Sheet as indicated variable Z amount of times). 

But you suggest that Toonz Harlequin had a repeat feature where the frames would be duplicated, but in a much more efficient way (not actually having to copy them), and you could set that feature to run infinitely rather than indicating a finite amount of times to repeat.

Right? I haven't been able to even figure out Tweening as of yet, so I have nothing to say about the other problem.

**Comment by blurymind** [comment]
@CodyEakins the repeat feature repeats KEY-frames - not frames. so it is strictly for cutout animation type of workflow. It's that little button at the bottom of the screenshot, just before the <><><><>><>...

Most 3d software calls that 'post infinity cycle'  Look up blender's excellent graph editor - it has the same feature. Such cycle is EXTREMELY useful when you do animation cycles - that way the user does not have to keep track of as many keyframes. The post and pre infinity cycles allow you to offset a copied animation.(from left leg to right leg for example in a walk cycle) - instead of creating extra keys for it.

As for the tween handles - they are even more useful in this case - as they allow you to very quickly adjust the spacing of of all the keyframe interpulations that you have. for example if in a keyframe you have translation x and y, also rotation keys - without this now you have to set them all up individually now. What is worse is that you have to dig to get to them and the curve editor in toonz or opentoonz does not allow the user to operate on more than one curves. So in that regard its way behind blender.

**Comment by iMaxGit** [comment]
It seems that the part just drawing the keyframes in the X-sheet can easily be enabled, but all the functionality for manipulating them (context menu, select, move) does not seem to be there. Although I find some unused functions, which seem to deal with this. Could it be that a relevant part of it has been removed?

**Comment by blurymind** [comment]
@shun-iwasawa might know. In any case it is much more difficult to manipulate keyframes without this feature. It allowed changing the timing of all keyframes on a frame much easier. Copy and pasting entire character poses was much easier. Now in order to do that same thing you have to select a really long list in the functions windows and it is super confusing.
I think the people who removed it should try to do some cutout animation with many body parts in a hierarchy. Only then its value to workflow would become obvious. I suggested bringing it back, but making the keyframes optionally visible in the x-sheet. Much like it was done for the schematic view ports.

**Comment by blurymind** [comment]
Perhaps then the keyframe editing right click menu items could also only be visible when keyframes visibility is toggled on in the x sheet. That way they will not get in the way of traditional animators who do not use keyframing that much.

I think it would be a very ellegant way to bring this feature back and even improve it by letting the user togle it  on and off optionally on all levels.

**Comment by iMaxGit** [comment]
Well, as far I can tell, in xshcellviewer.cpp line 1490 you need to uncomment the call to "drawKeyframe". This makes the keyframes visible. The problem is though, that I would expect in xshcellviewer.cpp "CellArea::contextMenuEvent" to be a check for the keyframe context menu for example. I only see a check for the notes. I assume here at least the code for the context menu is missing. Also, I do not seem to be able to select any keyframes once they are drawn. So that part would be missing as well. But I am not really a programmer, just poking around. So I might be missing something. ;-)

**Comment by iMaxGit** [comment]
Btw, there are things like "CellArea::createKeyMenu" and "CellArea::createKeyLineMenu", but they do not seem to be called from anywhere, hence my conclusion that some code is missing here.

**Comment by blurymind** [comment]
A good example of how it is useful is the ability to edit an object's collection of keyframes by their 'summary' row.

Blender's (and most other animation software's) dopesheet for example has a summary row for all of the character's keyframes.
Then it has a summary row for each body parts - one row that can control the object's  x,y,z location, rotation,scale,etc keyframes by moving a single summary keyframe.

![blender-dope-sheet](https://cloud.githubusercontent.com/assets/6495061/14686520/f6cae084-0730-11e6-9cf6-562fb80cd6d0.png)

Another example of a dopesheet is the timeline in spriter and spine2d:
https://www.youtube.com/watch?v=XMAuQReRy7Q

See how by default it shows a single row - the single row lets you manipulate all of the character object's channels by moving summary keyframes on a single row. That makes adjusting timing of poses much easier. Then going one level further you can adjust the timing of each individual object by expanding the timeline:
https://youtu.be/XMAuQReRy7Q?t=3m17s
Apart of that see how efficiently these keyframes show the timing - how much information in how much screen estate. You dont have to waste time to pan around or scroll too much to get to what you need.

Open toonz does not have a dopesheet, so it is very hard to have a clear overview and manipulate the keyframe timing of a single object, let alone the timing of an entire character that is made out of 90 objects. Toonz had keyframes in the x-sheet and that sort of emulated a dopesheet - a keyframe in it was a summary of all the keyframes that it has on that point in time (location,rotation,scale,etc) of a level. Moving them was a matter of clicking and dragging. 
The function editor in OT - every time you want to move all the keyframes of single point in time, you have to first make their channels visible, you have to select one really long horizontal roll and then ctrl+x,ctrl+v. You will be doing this a lot when animating - so it really adds up and slows down work to a halt.

I guess one way that opentoonz could tackle this even further is by having a real dopesheet.

**Comment by iMaxGit** [comment]
Sure, I completely agree. This should also be aligned with the request to introduce a timeline, because this could potentially be combined in my view. However, I would suggest to take one step at a time and aim for feature parity with Harlequin first, at least where possible and useful and then target potential enhancements.

**Comment by blurymind** [comment]
@shun-iwasawa awesome work! Thank you kindly!

@iMaxGit I found out that we actually already have something akin to a time line. It is tiny and easy to miss. The functions curves editor window:
![timelineot](https://cloud.githubusercontent.com/assets/6495061/14749934/1576e1e2-08ba-11e6-8f3f-1ac297c2f9c9.PNG)

It is quite powerful and acts kind of like maya's timeline. I found that it has some limitations though - which I can explain at a later stage.

The biggest problem is that it's a pop out window and it's very uncomfortable to select which channels to make visible - especially when you are on one monitor.

This is another thing I hope to see reverted.

**Comment by iMaxGit** [comment]
@shun-iwasawa Thank you as well!

@blurymind Yes, I noticed this already and find it useful to move the keyframes. Although a "real" dopesheet/timeline view with the option to collaps and expand the view on individual parameters would be the way to go ideally. It would be a different view of the function editor I would say, which anyway has all the info already (selectable keys and a spreadsheet like view per frame)

**Comment by blurymind** [comment]
Today this has been merged to master.
I am closing the issue.

**Comment by psychoanima** [comment]
Tested and working!
@shun-iwasawa Thank you very much for this!
