### ISSUE TITLE
Broken levels cause constant crashing

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1586]
One of my students has run into an issue where loading or accessing a specific scene causes a crash.  It seems to be a problem with the levels themselves. This started after a crash while working with the build skeleton mode of the skeleton tool with vector levels.  Looking at the levels in the browser, it looks like they are empty but there had been drawings there. The levels and scene had been saved previously with the CMD-S shortcut. This occurred with OS X 10.11.6 and OT nightly build from 8/14 (the computer has since been updated to one of the latest nightly builds). I'm sharing one of the levels and the crash report from trying to access the levels. Is there any way to recover the levels or are they lost?
[Head of Roboto.pli.zip](https://github.com/opentoonz/opentoonz/files/1488327/Head.of.Roboto.pli.zip)
[corruptlevel.txt](https://github.com/opentoonz/opentoonz/files/1488330/corruptlevel.txt)

**Comment by shun-iwasawa** [comment]
This is all I could salvage.
[HeadofRobotSalvaged.zip](https://github.com/opentoonz/opentoonz/files/1489962/HeadofRobotSalvaged.zip)
![image](https://user-images.githubusercontent.com/17974955/33054163-f190dd0a-ceba-11e7-8eb0-1a49da9955f2.png)

**Comment by artisteacher** [comment]
Thank you! Are there steps I can do on my end to recover some of the other levels?

**Comment by Crow1992** [comment]
I encountered the exact same problem in both Windows 8.1 and Windows 10.

-Opentoonz would crash if i try scrolling through the Level Strip or if I play the animation. Levels in Level Strip display red with an error message in them ("No Icon")

However:

If I close the Level Strip, I can playback the animation just fine but if I try to X out of the program, it also gives me a crash on exit.

**Comment by shun-iwasawa** [comment]
As @Crow1992 pointed, crash when opening broken Toonz Raster level may be avoidable by hiding the Level Strip if the defect exists only in thumbnail data in the file.
When I was in Studio Ghibli, in such case I tried to recover the level with the following steps:
- Open the level with the Level Strip being hidden.
- Mark a dot all the frames with Brush Tool, so that OT will update thumbnail data on saving.
- Overwrite the level.
- Try reopen the level with the Level Strip being displayed.
- If it luckily opens, delete all the dots and overwrite the level.

**Comment by Crow1992** [comment]
@shun-iwasawa I've tried your suggestion. The crash still happens even after updating the levels with new data in them.
I'm not really sure what's causing the problem. The faulting module seems ot be tnzcore.dll but I've attached a crash log to this post now.

[opentoonz crash log.txt](https://github.com/opentoonz/opentoonz/files/1635582/opentoonz.crash.log.txt)

I must mention that this error continued to appear even after I reinstalled my system and software.
It might be this version of OT causing issues. I'll see if it still persists in the older install if I can get an older installer somewhere (i have morevna so i might test in there as well)

**Comment by jpturcotte** [comment]
@Crow1992 You can find the previous version here: https://github.com/opentoonz/opentoonz/releases/tag/v1.1.3.

**Comment by artisteacher** [comment]
@shun-iwasawa, thank you for the suggestion. I think ideally, corrupted/missing icons and/or corrupted drawings should generate a warning/error notification when loading instead of causing a crash.

**Comment by Crow1992** [comment]
@shun-iwasawa I tested in Morevna 1.2.0,2.

First I played the animation as normal, without updating the animation. It crashed.
Second time, I added the dot in each level to update it. 
Played the animation twice with the level strip open and it didn't crash.

**Comment by RodneyBaker** [comment]
Likely related to #2408 although there are differences.
It does seem that a common element to the problem is vectors.

See also:  #1586
