### ISSUE TITLE
Function curves editor in open toonz broken - can't move keyframes or their bezier handles

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#159]
Would it be possible to revert changes done to the opentoonz Function editor? It's quite broken in it's current state.
here is the function editor in toonz:
![functeditor-toonz](https://cloud.githubusercontent.com/assets/6495061/14440057/1e016b76-0026-11e6-83de-a0f410c635cb.JPG)

and here it is in opentoonz:
![functioneditorotde](https://cloud.githubusercontent.com/assets/6495061/14439998/dabf6368-0025-11e6-811d-d216a0d70777.JPG)

- You can no longer move keyframes in the graph view! This is the big one.
- You can no longer adjust spacing - the bezier curves can not be moved either. You can select them, but grabbing them does nothing.

All this makes the function editor's graph view incapable of doing anything but display the curves.

**Comment by jay3d** [comment]
You can hold CTRL while dragging around keys and handles to adjust them

**Comment by blurymind** [comment]
@jay3d ah I see. Thank you for telling me about this.

This behavior is strange to me. Why does one have to hold control key now? 
At first I simply thought that it doesnt work. Is this something that can be re-configured?

**Comment by blurymind** [comment]
I would suggest removing the need to hold the ctrl key - as it makes the software much less welcoming to new users. I dont think the hold to do anything in the curves editor design atm is justified. What do we gain by having it? Why was it introduced in the first place?

**Comment by blurymind** [comment]
@jay3d  is there a way to disable the having to hold ctrl behavior in order to edit keyframes?

I see this as a regression from toonz harlequin - where holding control was required only when you need to add keyframes.

**Comment by turtletooth** [comment]
I just read this-  I thought for the longest time that the graph was just broken.  Having to hit Ctrl does seem like a strange thing.  I am glad to know that the function graph actually works.  It just needs to be more user friendly.

**Comment by blurymind** [comment]
Yes indeed. This wasnt the case in toonz harlequin. It should be an easy to revert change - low hanging fruit. I asked why it was introduced to see if @shun-iwasawa would have anything against reverting it and also if keeping the option has any merrits

**Comment by turtletooth** [comment]
#658 and #657

**Comment by shun-iwasawa** [comment]
Merged option 1.

**Comment by blurymind** [comment]
Thank you! :)
