### ISSUE TITLE
Feauture request: Improved frame management 

### ISSUE THREAD

**Issue by ArtsyCosmicDreamer** [opentoonz/opentoonz#1595]
While I love OpenToonz, I find that Opentoonz frames navigation can be a bit difficult. Considering the horizontal timeline came and improvements are already being added to it, I'm sure the team is doing everything they can. But, I find that the lack of these minor features makes using Opentoonz somewhat difficult. I'm not that experienced in animation software outside of OT, but I have tried the trial of Toonboom and I liked how easy it was to move a frame above another or simply insert a frame. With Opentoonz, you have to mess around with levels just to put one frame over another which wastes a lot of time compared to Tooboom in where this process is as easy as selecting a frame and bringing it above another. Same for inserting, as you have to copy a frame and bring the frame in or again, rearrange it compared to Toonboom where you just select the frame and put it in the middle.

I haven't done any merging in Opentoonz, but I use it all the time in a lot of the drawing software I use and it saves a lot of time when you want to bring frames together instead of collapsing an entire collum. Sometimes it just doesn't even work, since when I collapse them, the frames are brought within each other but they aren't merged or only become one frame.

I'm not sure how much money would be necessary to get these much needed features in Opentoonz, but I'm willing to help to get it, whether it be donating or communicating with the developers.

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
