### ISSUE TITLE
Fill tool crashes .

### ISSUE THREAD

**Issue by Toybulldog** [opentoonz/opentoonz#1600]
Hello 
I have the latest master github. 
When I use the Fill tool (vectors) and change from area to line, OP crashes.
![fill](https://user-images.githubusercontent.com/11164330/33224419-926343ac-d169-11e7-9d58-86bb2346d895.png)
![terminal fill tool crash](https://user-images.githubusercontent.com/11164330/33224425-9dda75b6-d169-11e7-95ac-1bc697342aa5.png)

My System
![mintlinux](https://user-images.githubusercontent.com/11164330/33224438-b56c8674-d169-11e7-844f-981aa7636505.png)

Lg peter

**Comment by manongjohn** [comment]
Confirmed bug on Windows as well.
