### ISSUE TITLE
What is interesting in other programs?

### ISSUE THREAD

**Issue by DoomDesigner** [opentoonz/opentoonz#1601]
Let's discuss interesting solutions that exist in other programs.

After Effects is famous for its plaza for plug-ins. A lot of developers come up with interesting instant solutions for quick work.

Here are some.

Duik (Free plugin) 

![20150108013925-autorig](https://user-images.githubusercontent.com/32999433/33230121-973ef10c-d1ee-11e7-875a-e8561576e854.gif)

https://vimeo.com/96444901

https://rainboxprod.coop/en/tools/duik/

RubberHose

![rubberrig_stretch](https://user-images.githubusercontent.com/32999433/33230138-2c0ae1c4-d1ef-11e7-8c9e-84babbdd0f94.gif)
![rubberpin_demo_render](https://user-images.githubusercontent.com/32999433/33230139-2ceb6c08-d1ef-11e7-8b4b-d2cbe96e6f07.gif)
![hosestyling](https://user-images.githubusercontent.com/32999433/33230140-2e85c374-d1ef-11e7-89ca-4ab8a20c8fd7.gif)

https://www.youtube.com/watch?v=PgBo-00_GWc

http://www.battleaxe.co/rubberhose1/

Joysticks 'n Sliders

![default](https://user-images.githubusercontent.com/32999433/33230167-835d4250-d1ef-11e7-8171-ce023b253157.gif)
![pigeon-pigeoff](https://user-images.githubusercontent.com/32999433/33230168-845d9272-d1ef-11e7-88c1-1215fc057335.gif)
![tumblr_o56w6nrmph1tid1ejo1_1280](https://user-images.githubusercontent.com/32999433/33230169-8696a84e-d1ef-11e7-9f98-13dd6dfe0641.gif)

https://www.youtube.com/watch?v=8OoEypt1YXU

https://aescripts.com/joysticks-n-sliders/

**Comment by turtletooth** [comment]
This is better discussed in the Google Group.  It doesn't relate directly to development of OpenToonz.
