### ISSUE TITLE
[Feature Request] key (animate)control points

### ISSUE THREAD

**Issue by bebinalpha** [opentoonz/opentoonz#1607]
It will be nice if we could key(animate) the control points of the shape. example while animating one shape overlaps the other shape it will be nice to move the control points and remove the overlap.

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
