### ISSUE TITLE
Bug: Cleanup processing causes affected image to disappear. 

### ISSUE THREAD

**Issue by CodyEakins** [opentoonz/opentoonz#161]
Hey there, guys.

I've made a video in order to help better explain this phenomenon.
Link: [Cleanup Processing Bug Video (YouTube)] (https://youtu.be/y7AmPfcM7-E)
To summarize the video: If you use clean up processing on an image, the original will disappear, and no resultant image will be displayed.

I discovered this issue while tinkering around with the paper-based 2D animation features within OpenToonz. This problem raises huge concern for any animator hoping to use OpenToonz for paper animation because it halts the cleanup and vectorization processes of their scanned-in frames.

If I am, however, wrong -- and this is not a bug, then shouldn't there be a simpler method/work-flow for this stage of the animation process? I can't imagine Studio Ghibli putting their animators through this...

Encountered while running OpenToonz 1.0.1 on Windows 10 x64-bit.

-Cody

(PS - The reason I had to "drag and drop" my test image in was because I was experiencing a separate problem acquiring the image from my scanner, through the program. Hopefully this is unrelated... But ideally, a paper animator should be able to scan and clean up without any issues!)

**Comment by jay3d** [comment]
I had the same issue in 1.0.1, but it's working fine in 1.0, something broke I think between 1.0 and 1.0.1

**Comment by kogaki** [comment]
Maybe this is duplication of #128 and now fixed in `nightly build` ?

**Comment by CodyEakins** [comment]
I'll install the nightly/most recent build and test if it fixes it... I apologize if this was a repost/a double report.
Thank you, Kogaki.

**Comment by kogaki** [comment]
Thank you for your report. Closed.

**Comment by CodyEakins** [comment]
I just installed the newest build... The problem has been FIXED, but there are a few pitfalls/lack of clarity:
(1) When dragging and dropping an image in that manner I previously demonstrated, it will correctly appear within the document, but it will cause the timeline to automatically select the next level (column) above it. If someone doesn't realize this when they go to preview cleanup/cleanup the document, it will not correctly display the cleanup/do anything. If, however, you click on the correct level, both the preview and cleanup work.
(2) Immediately after cleaning up the image, if your "preview cleanup" setting is still checked, you will see an alias of your cleanup, rather than your intended result. This is because the program thinks you are trying to "cleanup your cleanup". In my case, the alias was in fact smaller in size (somehow, the 2nd cleanup processing was causing the image to shrink by about 10%) than the intended product, which is a little disorienting...

**Comment by kogaki** [comment]
Thank you but your new report is related to usability while this issue is about the lack of functionality. So it is recommended to open NEW issue so that.
