### ISSUE TITLE
Plastic tool render problem - Linux

### ISSUE THREAD

**Issue by tuvia** [opentoonz/opentoonz#1615]
When using the plastic tool in linux (XUbuntu 16.04) , OpenToonz renders the animation showing many frames at the same time, so the animation looks very bad. This does not happen with the skeleton tool. 
I'm attaching a sample animation with the correspondent scene because is difficult to express the end results. It's a simple rectangle that was supposed to go up and down, but this is the result:

![test 0013](https://user-images.githubusercontent.com/4240027/33336334-53eca234-d44e-11e7-9405-c5509d22ee3a.jpg)

[test.zip](https://github.com/opentoonz/opentoonz/files/1511095/test.zip)

**Comment by jpturcotte** [comment]
Possible duplicate of https://github.com/opentoonz/opentoonz/issues/856#issuecomment-281420473?

**Comment by jpturcotte** [comment]
None that I know of for now, sadly.
@morevnaproject Are you currently working on #856?

**Comment by morevnaproject** [comment]
Yes, this is the same as #856.

No, we are not working on that at the moment.

This bug happens with Intel videocards (native OS drivers). For Nvidia cards (proprietary drivers) it doesn't happens.

@tuvia What is the model of your videocard and what drivers are you using?

**Comment by tuvia** [comment]
familia@familia-desktop:~$ lspci -nnk | grep -i vga -A3
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:5912] (rev 04)
	DeviceName:  Onboard IGD
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device [1462:7a72]
	Kernel driver in use: i915

Can I use a different driver so that this problem doesn't happen?

**Comment by morevnaproject** [comment]
You can try to use opensource drivers from Intel website, but I have not tested them myself.

**Comment by artisteacher** [comment]
I wish that was an option for OS X.

**Comment by tuvia** [comment]
Do you mean this? 
INTEL GRAPHICS UPDATE TOOL FOR LINUX* OS V2.0.2
https://01.org/linuxgraphics/downloads/intel-graphics-update-tool-linux-os-v2.0.2

or this?
2017Q3 INTEL GRAPHICS STACK RECIPE
https://01.org/linuxgraphics/downloads/2017q3-intel-graphics-stack-recipe

Thank you!!!!

**Comment by morevnaproject** [comment]
You need INTEL GRAPHICS UPDATE TOOL - https://01.org/linuxgraphics/downloads/intel-graphics-update-tool-linux-os-v2.0.2

The instructions for Ubuntu 16.04 are available on the same page in the "Installing and Running" section.

> I wish that was an option for OS X.

This bug happens because of OpenGL incompatibility. I believe eventually this can be fixed for all platforms by re-writing that part of code (as @blackwarthog  did for antialiasing bug on Linux).

**Comment by jpturcotte** [comment]
> This bug happens because of OpenGL incompatibility. I believe eventually this can be fixed for all platforms by re-writing that part of code (as @blackwarthog did for antialiasing bug on Linux).

Would that eventually warrant a bounty?

**Comment by tuvia** [comment]
I can confirm that it didn't work with INTEL GRAPHICS UPDATE TOOL :(
Do you think of any other solution? Thank you!

**Comment by artisteacher** [comment]
@tuvia, you should give the latest nightly build a try. It seems to fix the transparency issue at least in OS X.

**Comment by morevnaproject** [comment]
We haven't made a build with this fix, but it looks promising! ^__^

**Comment by tuvia** [comment]
@morevnaproject please let us know when you have a build! Thank you for your great work and success in the conference!

**Comment by morevnaproject** [comment]
Here is the testing build, which includes fix #1726 by @shun-iwasawa - https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-18.01.24-linux64-466fc.appimage

For my hardware (Intel video card) the problem got fixed. Please test.

**Comment by tuvia** [comment]
Works great! Thank you so much!!!!!!
