### ISSUE TITLE
(WIP) Multishade brush tool - to take advantage of the opentoonz raster layer's indexed colors

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#1616]
Multishade tool- what is it the basic idea:
1.You set your cell shade gradients 

![gradientindexes](https://user-images.githubusercontent.com/6495061/33345468-5ff24e18-d484-11e7-9827-07d4256f3cd0.JPG)

2. You use a single brush tool to shade the entire layer
It's a brush tool available in cosmigo pro motion that makes it very easy to do cell shading without worrying about separating different colors. Here is a video:
https://youtu.be/iGFmj4TI3pQ?t=2m09s

every time you do a stroke,the tool picks the pixels and moves their color palette index forward or backward (depending if the user wants t lighten an area or darken it)
![multishadebrush](https://user-images.githubusercontent.com/6495061/33345376-1722e9b8-d484-11e7-9da6-45280a62fea9.gif)

Advantages
- no need to select colors while cell shading with a brush
- no need to carefully respect color islands while cell shading between different colored areas

created a bounty here:
https://www.bountysource.com/issues/52074694-multishade-brush-tool-to-take-advantage-of-the-opentoonz-raster-layer-s-indexed-colors

**Comment by gab3d** [comment]
looks useful.

**Comment by blurymind** [comment]
created a bounty here:
https://www.bountysource.com/issues/52074694-multishade-brush-tool-to-take-advantage-of-the-opentoonz-raster-layer-s-indexed-colors

**Comment by RodneyBaker** [comment]
Definitely would be useful.  :)

**Comment by jpturcotte** [comment]
@RodneyBaker Maybe that could work with separate layers? When you use the tool on a layer, it could apply to every visible layer underneath.

**Comment by jpturcotte** [comment]
@blurymind Could you think of any way to make it non destructive? I don't know how the Undo function works in OpenToonz, but it seems quite limited. Also, don't MyPaint brushes have a lighten/darken function already? Maybe @morevnaproject has an idea. Anyway, this is all really interesting!

**Comment by blurymind** [comment]
@jpturcotte well, the idea of having indexed colors allows you to change any of the colors you are using at any time. So there is no point in having different color shades or fills on different levels :/

The tool has undo and redo, it just doesnt work the way you described- what you request is not possible to do with color index shifting on pixels. It's not what is requested here

**Comment by jpturcotte** [comment]
Great, I am looking forward to your bounty!

**Comment by beeheemooth** [comment]
@blurymind I think it's a useful thing. It is possible that @caryoscelus and @Agnyy may be interested in this. Their project (#1370 ) just affects the editing of several colors (styles) simultaneously.

**Comment by artisteacher** [comment]
That’s really interesting. It might be beneficial to have two shortcuts to toggle the active colorstop forward and backward  as desired - like we can use W and Q to switch between drawings in a level.

**Comment by blurymind** [comment]
@artisteacher in pro-motion you only need to set the palette once and from there on there is no need to click on any styles while using the tool. Its wonderful in that simplicity.  It has a pressure sensitive brush size and a two modes- darken(+1 index) and lighten(-1 index)

So my guess is that to do this in Opentoonz, the biggest addition would be the ability to set color style ranges in OT's palette editor and be able to store that when saving the project.

**Comment by caryoscelus** [comment]
@beeheemooth i'm afraid our project is only tangentially related. Currently it doesn't even actually allow direct editing of several colors: it rather allows switching between them. But in any case, i'm not really interested in coding OT-specific things (color chooser is universal Qt widget, i only had to add a bit gluing code to put it into OT).

**Comment by Orphanlast** [comment]
What's it supposed to work on? Raster levels? Toonz Raster levels? Both? A new type of raster level?

**Comment by blurymind** [comment]
@Orphanlast toons raster levels :)

Any layer type that supports color indexing

**Comment by artisteacher** [comment]
This still looks helpful but as a feature request without a bounty, this should probably be closed for now.

**Comment by RodneyBaker** [comment]
I agree that it looks like a logical extension and feature for the future.
Leaving open for now pending feedback from @blurymind

**Comment by RodneyBaker** [comment]
Closing for now as feature likely to be slipping to 2019 development cycle.
