### ISSUE TITLE
REPEATED: Not mouse, trackpad won't draw any line

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#1629]
Literally.

Mouse clicks work perfectly on any part except the canvas: only connecting my tablet works to trace anything on the canvas.
I tried reinstalling on macSierra (not the newest one) and the issue continues. Is there some new preference I have to turn off?

**Comment by shun-iwasawa** [comment]
A "mouse" is literally a mouse, or a trackpad ? 
For now a newly-introduced touch input feature does not work properly with trackpad, reported in #1579 .
As a quick workaround #1621 will make the touch feature optional and can be disabled.

**Comment by agatre** [comment]
Oh, trackpad is the term for the square in laptops... I'm sorry. I repeated the issue then.
Thank you. I'll pay attention to that update. Under which section of "preferences" will it be under?

PD:I haven't tested with a usb mouse.

**Comment by turtletooth** [comment]
The new touch controls are now optional and disabled by default.
