### ISSUE TITLE
styleselection.cpp error:ordered comparison palette->getStylePage(styleId) 

### ISSUE THREAD

**Issue by damies13** [opentoonz/opentoonz#1639]
Tried building from opentoonz/master today on OSX

Got the following error:

`
/Users/dave/Documents/Git/opentoonz/toonz/sources/toonzqt/styleselection.cpp:94:40: error: ordered comparison
      between pointer and zero ('TPalette::Page *' and 'int')
    if (palette->getStylePage(styleId) < 0) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
1 error generated.
`
Did a little searching for getStylePage() to see what the expected output of this function is (I was guessing that this might be a QT function that changed with the newer Qt version?) and found this link which gave me a clue how to fix it:

https://www.viva64.com/en/b/0389/ (v503)

I was actually a little annoyed at the author of the article, in the time it took to write that article criticising the OpenToonz Code, he could have forked it, made the necessary changes and submitted a PR.

**Comment by shun-iwasawa** [comment]
@damies13 Thank you for pointing and fixing this. I'll take a look. 

> I was actually a little annoyed at the author of the article, in the time it took to write that article criticising the OpenToonz Code, he could have forked it, made the necessary changes and submitted a PR.

He once posted [the issue](https://github.com/opentoonz/opentoonz/issues/149) last year.
