### ISSUE TITLE
1.0.1: Crashes when creating new Toonz Raster Level

### ISSUE THREAD

**Issue by AyameLee** [opentoonz/opentoonz#164]
When creating a new **Toonz Raster Level** using OpenToonz **1.0.1** it will crash when pressing OK/Apply.

**This does not happen with 1.0.**

-**Event Info**-

> Faulting application name: **lzocompress.exe**, version: 0.0.0.0, time stamp: 0x56f8c7f6
> Faulting module name: **lzocompress.exe**, version: 0.0.0.0, time stamp: 0x56f8c7f6
> Exception code: 0xc0000005
> Fault offset: 0x0000000000001130
> Faulting process ID: 0x364
> Faulting application start time: 0x01d194da3bf0094b

**Comment by CodyEakins** [comment]
This was previously reported in issue #91.
The event info may help, though.
