### ISSUE TITLE
skeleton Tool cursor not working

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#1641]
in skeleton Tool, Animate Mode, the little red arrows and the cursor disappears and the Rotate mode cursor becomes visible. 

![cursor](https://user-images.githubusercontent.com/29300971/33530069-168bad42-d87a-11e7-8b5d-e1ed8c13d05f.jpg)

so, the Tool is currently unusable

(I am using nightly build Nov 28 2017 20:55:26)

a few weeks ago, this Tool was working properly

**Comment by turtletooth** [comment]
@shun-iwasawa Is this related to the recent icon PR?

**Comment by turtletooth** [comment]
Ok, just tested on the current branch and on OTX.  I can't reproduce the issue.

**Comment by turtletooth** [comment]
@bobbybutterfly It may be that the stuff folder needs to be updated.  I think there is an option to overwrite the stuff folder on install.

**Comment by bobbybutterfly** [comment]
@turtletooth Thanks, works now after reinstall and overwrite the stuff folder
