### ISSUE TITLE
Click + drag to edit values for the Animate Tool only works on one column 

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1646]
I've run into a problem in OS X 10.11.6 and 10.12.1 where clicking and dragging on the label to edit values for the Animate tool only works on the first column where clicking and dragging is attempted. After changing the values on one column and then trying to change the values on a second column, the original column incorrectly accepts those changes and the new column ignores those changes to the value. Manually typing the value continues to work as expected.

**Comment by turtletooth** [comment]
I've confirmed this.  Sorry for not catching it before.  Unfortunately I can't figure out the issue.  The animate tool doesn't send signals the same way the other tools do.  @shun-iwasawa Do you have any insight on why the action is not happening on the selected column?

**Comment by shun-iwasawa** [comment]
I'll take a look

**Comment by turtletooth** [comment]
Thanks @shun-iwasawa - I looked for a couple hours today, but couldn't find it.  It's probably a really simple thing I was just overlooking.

**Comment by shun-iwasawa** [comment]
OK I think I found the cause!
