### ISSUE TITLE
Crash with raster editing (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1650]
This happens only in the Raster and Toonz Raster levels.
1. Draw something in the raster and start editing using the Selection Tool.
2. Close the scene without deselecting.

Perhaps the same crash will happen and when saving the file (I did not dare to check it).

![ezgif-3-ef8e499694](https://user-images.githubusercontent.com/25724133/33583894-54e76496-d965-11e7-8f82-83a66c51e338.gif)

**Comment by artisteacher** [comment]
I can confirm with OS X.

**Comment by shun-iwasawa** [comment]
Thanks @beeheemooth for reporting this. I could reproduce the crash.
