### ISSUE TITLE
Strange behavior of the selection in Raster and Toonz Raster Levels on the left and lower border of the canvas. (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1654]
If you deform the selection on the left or lower border of the canvas in such a way as to go beyond the canvas, then when deselected (or when you switch to another tool), the selected one jumps. CTRL + Z also does not work properly.

![ezgif-3-601ca4604e](https://user-images.githubusercontent.com/25724133/33639250-06169b1a-da33-11e7-9a81-84b6235faa56.gif)

**Comment by shun-iwasawa** [comment]
Confirmed the problem. Thank you @beeheemooth for reporting it.
