### ISSUE TITLE
What is the analogue of F6 (FLASH) in OT.

### ISSUE THREAD

**Issue by DoomDesigner** [opentoonz/opentoonz#1656]
How can I copy a frame. If I copy it then the frame just stretches 
![image](https://user-images.githubusercontent.com/32999433/33663550-78d95cfa-daa1-11e7-8da1-17552d86ad49.png)
. In FLASH, this can be done with F6, and how to do it in OT. 
![image](https://user-images.githubusercontent.com/32999433/33663565-8e3f95e6-daa1-11e7-983f-af6582c74746.png)

**Comment by manongjohn** [comment]
@DoomDesigner 

Please move how-to questions like this to the google group community https://groups.google.com/forum/#!forum/opentoonz_en where other users can answer your questions or provide work-arounds if there isn't a straight forward answer.

**Comment by RodneyBaker** [comment]
Yes, please open a topic in the Google Groups.
There are several ways to copy a frame.
Let's find the way that works best for you.

**Comment by beeheemooth** [comment]
Please leave a link to the discussion (if it was created) @RodneyBaker I would like to hear your opinion on this issue (in the google group)
