### ISSUE TITLE
(WIP) Updating Visual Studio

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1657]
How hard would it be to update to VS 2017?  Unity installs that by default and right now I have two versions of VS installed - which is a lot on a small ssd drive.  It would be great if we could build OT with vs 2017.

**Comment by turtletooth** [comment]
So I tried to build in VS 2017 and I get 24 errors, most of them in sets of 3 like this:

Error	C2678	binary '*': no operator found which takes a left-hand operand of type 'const tcg::cast_iterator<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<TSmartPointerT<TTextureMesh>>>>,TTextureMeshP (__cdecl *)(const TTextureMeshP &),TSmartPointerT<TTextureMesh>,TSmartPointerT<TTextureMesh> &,TSmartPointerT<TTextureMesh> *>' (or there is no acceptable conversion) (compiling source file D:\MyCode\opentoonz\toonz\sources\common\tmeshimage\tmeshimage.cpp)	tnzcore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xmemory	126	


Error	C2100	illegal indirection (compiling source file D:\MyCode\opentoonz\toonz\sources\common\tmeshimage\tmeshimage.cpp)	tnzcore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xmemory	126	


Error	C2062	type 'unknown-type' unexpected (compiling source file D:\MyCode\opentoonz\toonz\sources\common\tmeshimage\tmeshimage.cpp)	tnzcore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xmemory	126

**Comment by RajodiyaShubham** [comment]
Hi,
I am also facing same issue, please help.
How to resolve this issue ?
Thank you

**Comment by turtletooth** [comment]
@shun-iwasawa Are you looking to use VS 2017 anytime soon?  I use VS 2017 with Unity to teach game design, but installing VS 2017 somehow breaks VS 2015 compiling of OpenToonz.  It would be great to only have to use one version of VS.

**Comment by shun-iwasawa** [comment]
Well, yes I agree that we need to migrate to the newer version of VS at some time in the future.
However I myself have to prioritize other tasks like urgent bug fixes and implementing demanded features for now..

Does the errors occur mostly in `tmeshimage.cpp` , or in other sources as well?

**Comment by turtletooth** [comment]
No, they are scattered around.

I understand what you are saying @shun-iwasawa 
The bummer is that I can't build OpenToonz right now to test or fix anything.

For example when I try and compile plastichandle.cpp I get the following output:


------ Build started: Project: tnzext, Configuration: Debug x64 ------
plasticskeleton.cpp
c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\xmemory(217): error C2678: binary '*': no operator found which takes a left-hand operand of type 'const _Iter' (or there is no acceptable conversion)
        with
        [            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>
        ]

c:\mycode\opentoonz\toonz\sources\include\tcg\iterator_ops.h(156): note: could be 'PlasticHandle tcg::cast_iterator<tcg::list<V>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>::operator *(void)'
        with
        [
            V=PlasticSkeletonVertex
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\xmemory(217): note: while trying to match the argument list '(const _Iter)'
        with
        [            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\vector(1823): note: see reference to function template instantiation '_FwdIt *std::_Uninitialized_copy<_Iter,PlasticHandle*,std::allocator<_Ty>>(const _InIt,const _InIt,_FwdIt,_Alloc &)' being compiled
        with
        [
            _FwdIt=PlasticHandle *,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>,
            _Ty=PlasticHandle,
            _InIt=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>,
            _Alloc=std::allocator<PlasticHandle>
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\vector(708): note: see reference to function template instantiation 'PlasticHandle *std::vector<PlasticHandle,std::allocator<_Ty>>::_Ucopy<_Iter>(_Iter,_Iter,PlasticHandle *)' being compiled
        with
        [
            _Ty=PlasticHandle,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\vector(708): note: see reference to function template instantiation 'PlasticHandle *std::vector<PlasticHandle,std::allocator<_Ty>>::_Ucopy<_Iter>(_Iter,_Iter,PlasticHandle *)' being compiled
        with
        [
            _Ty=PlasticHandle,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\vector(723): note: see reference to function template instantiation 'void std::vector<PlasticHandle,std::allocator<_Ty>>::_Range_construct_or_tidy<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=PlasticHandle,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\vector(723): note: see reference to function template instantiation 'void std::vector<PlasticHandle,std::allocator<_Ty>>::_Range_construct_or_tidy<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=PlasticHandle,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>
        ]

c:\mycode\opentoonz\toonz\sources\tnzext\plasticskeleton.cpp(587): note: see reference to function template instantiation 'std::vector<PlasticHandle,std::allocator<_Ty>>::vector<tcg::cast_iterator<tcg::list<V>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>,void>(_Iter,_Iter,const _Alloc &)' being compiled
        with
        [
            _Ty=PlasticHandle,
            V=PlasticSkeletonVertex,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>,
            _Alloc=std::allocator<PlasticHandle>
        ]

c:\mycode\opentoonz\toonz\sources\tnzext\plasticskeleton.cpp(585): note: see reference to function template instantiation 'std::vector<PlasticHandle,std::allocator<_Ty>>::vector<tcg::cast_iterator<tcg::list<V>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>,void>(_Iter,_Iter,const _Alloc &)' being compiled
        with
        [
            _Ty=PlasticHandle,
            V=PlasticSkeletonVertex,
            _Iter=tcg::cast_iterator<tcg::list<PlasticSkeletonVertex>::const_iterator,Func,PlasticHandle,PlasticHandle &,PlasticHandle *>,
            _Alloc=std::allocator<PlasticHandle>
        ]

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\xmemory(217): error C2100: illegal indirection

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\xmemory(217): error C2062: type 'unknown-type' unexpected

Done building project "tnzext.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by turtletooth** [comment]
@shun-iwasawa I was able to get VS 2015 working again.  Installing VS 2017 messes up some stuff with VS 2015 and OT, but I got it sorted out and am up and running.

**Comment by RodneyBaker** [comment]
Suggest we targeting Visual Studio 2019 rather than 2017.
By the time we get to 2017 it will be well past time to move on to 2019.

This of course assumes several things to include that Microsoft will have a release of MSVS 2019 such as a community release or one freely available for open source use.  That's a pretty safe bet *and* with Microsoft now owning github we might expect to see even tighter integration along with associated benefits.

**Comment by manongjohn** [comment]
With the recent release of MSVC 2019, I decided to try my hand at compiling OT on MSVC 2017 as a step to get us closer to it.

I installed/upgraded the following:

1. Microsoft Visual Studio Community 2017
 	- I installed the `Desktop development with C++`
2. Boost 1.69.0
	- Used the latest version in order to get past a compile time error that kept coming up. 
	- Based on some documentation on the error, it was suggested using at least Boost 1.65.0 but I chose the latest instead. Not sure what the minimum version would be.
3. CMake 3.14.1
	- Needed to detect Boost 1.69.0.
4. QT 5.9.7
	- Installed components for `msvc2017_64`

Compiling on MSVC 2017 boils down to 1 issue. Whenever `tcg::make_cast_it()` (iterator_ops.h) is used as argument for `std::vector<X>(Iteratorfirst,Iteratorlast)`, it throws the following compiler error:

>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xmemory(126): **error C2678**: binary '*': no operator found which takes a left-hand operand of type 'const tcg::cast_iterator<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<TSmartPointerT<TTextureMesh>>>>,TTextureMeshP (__cdecl *)(const TTextureMeshP &),TSmartPointerT<TTextureMesh>,TSmartPointerT<TTextureMesh> &,TSmartPointerT<TTextureMesh> *>' (or there is no acceptable conversion) ...

This shows why the problem comes up and how to get around it in a simple case: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2678?view=vs-2019

There are 5 files impacted by this:

**common\tmeshimage\tmeshimage.cpp** (line 313):
```
  Imp(const Imp &other)
      : m_meshes(tcg::make_cast_it(other.m_meshes.begin(), cloneMesh),
                 tcg::make_cast_it(other.m_meshes.end(), cloneMesh))
      , m_dpiX(other.m_dpiX)
      , m_dpiY(other.m_dpiY) {}
```

**tnzext\plasticskeleton.cpp** (line 585):
```
  return std::vector<PlasticHandle>(
      tcg::make_cast_it(m_vertices.begin(), Func()),
      tcg::make_cast_it(m_vertices.end(), Func()));
```

**tnztools\plastictool_build.cpp** (line 578):
```
    m_pressedVxsPos = std::vector<TPointD>(
        tcg::make_cast_it(m_svSel.objects().begin(),
                          tcg::bind1st(&locals::vertexPos, *skel)),
        tcg::make_cast_it(m_svSel.objects().end(),
                          tcg::bind1st(&locals::vertexPos, *skel)));
```

**tnztools\plastictool_meshedit.cpp** (line 1071):
```
    m_pressedVxsPos = std::vector<TPointD>(
        tcg::make_cast_it(m_mvSel.objects().begin(),
                          tcg::bind1st(&Locals::vertexPos, *m_mi)),
        tcg::make_cast_it(m_mvSel.objects().end(),
                          tcg::bind1st(&Locals::vertexPos, *m_mi)));
```

**toonzlib\fxcommand.cpp** (line 2372):
```
  std::vector<TXshColumn *> cols(tcg::make_cast_it(columns.begin(), getCol),
                                 tcg::make_cast_it(columns.end(), getCol));
```
(line 3153)
```
  std::vector<QPair<TFxP, TPointD>>(
      tcg::make_cast_it(m_undoDagPos.begin(), &locals::originalPos),
      tcg::make_cast_it(m_undoDagPos.end(), &locals::originalPos))
      .swap(m_redoDagPos);
```

Unfortunately, my C++11 knowledge isn't quite strong enough to deal with our code, but I will continue to hack at it unless someone with more experience/knowledge can fix it before I do. :)

FYI, Technically, I was able to compile the code successfully if I changed the impacted code to just create empty vector arrays.  So, if we somehow fix this 1 issue, we can move to 2017 and maybe to 2019 in the near future.

**Comment by turtletooth** [comment]
This is awesome!  I have wanted to use VS2017/19 but ran into the same issue.  I don't know enough to fix it.  Thanks @manongjohn for looking into it.

**Comment by shun-iwasawa** [comment]
@otakuto 
Forgive me if I am wrong, but your [working branch](https://github.com/otakuto/opentoonz/tree/remove-make_cast_it) seems to be a big help for the above issue. Is there any problems with your solution?

**Comment by manongjohn** [comment]
Actually, his [2017](https://github.com/otakuto/opentoonz/tree/2017) branch which includes changes from remove make_cast_it branch) appears to be the attempt to move to MSVC 2017.

**Comment by otakuto** [comment]
OK, I will PR.

**Comment by turtletooth** [comment]
Confirmed that OpenToonz now builds with Visual Studio 2017.  Thank you @otakuto for the fix.

**Comment by manongjohn** [comment]
FYi, now that this fix is merged in, I just uconfirmed you can build OT on Visual Studios 2019 but you will need to build with QT MSVC 2017 libraries since QT doesn't have 2019 yet.
