### ISSUE TITLE
Visual beams for a theme.

### ISSUE THREAD

**Issue by DoomDesigner** [opentoonz/opentoonz#1660]
I think you can improve the themes. 

1)  It is necessary to lighten the strips.
![image](https://user-images.githubusercontent.com/32999433/33719222-1b568f96-db71-11e7-9134-497fbbea5388.png)
Then it will become like FLASH or TONOBOM. 
![image](https://user-images.githubusercontent.com/32999433/33719385-906ebbe6-db71-11e7-8a45-000c902f5ee3.png)
![image](https://user-images.githubusercontent.com/32999433/33719403-a1e59eee-db71-11e7-96e1-296050d8b926.png)

**Comment by DoomDesigner** [comment]
2. Lack of strips.
![Uploading image.png…]()

**Comment by DoomDesigner** [comment]
3. Stripe around the layers must be removed.
![image](https://user-images.githubusercontent.com/32999433/33719911-5b218eee-db73-11e7-8c4d-e85956bc7be7.png)
It's much better without it. 
![image](https://user-images.githubusercontent.com/32999433/33719955-8501217a-db73-11e7-9aea-949a6b718fb7.png)

**Comment by turtletooth** [comment]
For now feature requests can be placed in the Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
