### ISSUE TITLE
Brush Behavior Sometimes Unexpected

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1661]
When drawing, especially with Toonz Raster levels in my experience, the brush doesn't seem to accurately track the pen.
![circles](https://user-images.githubusercontent.com/4576381/33741471-b342bcd6-db61-11e7-8a93-63e3e6852aec.PNG)
Notice that some circles have hooks some have some straight sections.  They were all drawn with a similar stroke.
![traster](https://user-images.githubusercontent.com/4576381/33741513-de69e6fa-db61-11e7-8953-a889ec903f43.PNG)
Notice the hooks on the curves.

This is also reported in the Google Group:
https://groups.google.com/forum/#!category-topic/opentoonz_en/IAvj1Z0PmbY

**Comment by turtletooth** [comment]
Note- I get this behavior most when I am testing it in debug mode through Visual Studio, which slows down OpenToonz, so I don't know if this might be related to the performance of people's computers.

**Comment by beeheemooth** [comment]
I noticed the delay at the beginning of the stroke. Sometimes with light and sharp movements of the pen there are only points in places where the pen touches the canvas.

**Comment by RodneyBaker** [comment]
Any updates to this one since last year?

**Comment by RodneyBaker** [comment]
All parties have gone silent on this issue for approaching two years (here and via OT Forum).
Closing as likely resolved.

@turtletooth please feel free to reopen as necessary.
