### ISSUE TITLE
Keys flee being selected with accidental drag! (seen on timeline)

### ISSUE THREAD

**Issue by snapai** [opentoonz/opentoonz#1671]
Selecting keys in multiple columns, where the second click accidentally includes a drag, causes even the unselected keys to "run away" effectively disappearing from the timeline. It also doesn't do this within an undo/redo wrapper, so the result is data loss that must be reverted.
![keyflee](https://user-images.githubusercontent.com/5098372/33808806-5a5bb7d4-ddba-11e7-812b-7d190ae952d6.gif)

Steps to replicate:

1. Have multiple columns with concurrent keyframes on multiple frames.
2. Click one key in a same-frame line of keys.
3. Hold shift and click another key in the same line, with a drag event at the end of the click (ludicrously easy to do on a 2000+ lpi tablet), or click-and-drag again afterwards.
4. Watch your keys (even the unselected ones) fly away, never to return!
5. Notice how undo doesn't bring them back.

**Comment by manongjohn** [comment]
What happens in Xsheet mode? Curious if this is an old bug or something introduced with timeline or timeline flip.

Will try and reproduce when I get a chance.

**Comment by snapai** [comment]
@manongjohn They move in their column, but not in their frame at all. Appears to be specific to timeline view. It does NOT do it in the timeline of the 10-18 build of OTX, so it's at least new since then.

**Comment by manongjohn** [comment]
@snapai Thanks for the follow up. Sounds like it might be due to the timeline flip. I already found and fixed another keyframe movement bug related to timeline flip. Will investigate what you found further.
