### ISSUE TITLE
Blank Viewer/Combo Viewer after installing V1.2

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1674]
A user on google groups originally reported this issue under V1.1.3 recently and saw the same issue after recently isntalling V1.2. (https://groups.google.com/forum/#!category-topic/opentoonz_en/yV8uVafZBxY)

I didn't have the problem with V1.1.3, but when I installed V1.2 today, I noticed the problem also.

We are both running Win7 64 bit.

However, it should be noted that, when I build V1.2 locally with the latest OT master code, the executable that is generated is Opentoonz_1.1.exe and it works normally, but if I renamed it to Opentoonz_1.2.exe the viewers are blank.

Unfortunately, if I rename the officially installed Opentoonz_1.2.exe back to Opentoonz_1.1.exe, it doesn't fix the issue.

Is something in the compiling process not accounting for the executable name change?  Are we missing some registry setting?

**Comment by manongjohn** [comment]
Interestingly enough, I found if I do the following with the installed version, it works properly:

1) Rename executable C:\OpenToonz 1.0\Opentoonz_**1.2.exe**  -> C:\OpenToonz 1.0\Opentoonz_**1.1.exe**
2) Rename folder from C:\OpenToonz **1.2** -> C:\OpenToonz **1.0**

I'm not sure if this is working because I have had prior installations on this machine so I would have registry settings for 1.1.  This would suggest that I am missing registry settings for 1.2.

**Comment by RodneyBaker** [comment]
This may (or may not) be related.
I noticed there were two OT executables in my 1.2 directory after installing 1.2.  One is named 1.1 and the other 1.2.  It wouldn't let me run 1.1 because I'd removed the supporting files/directories.  I deleted that 1.1 executable without problems.

**Comment by manongjohn** [comment]
Update...

I don't know the direct cause but I did manage to fix my problem.

I had to force OT to use the GPU on my graphics card similar to how I fix my problem with pen lag and poor performance.

I'm not sure what change caused this. Maybe the move to QT 5.9?

This should really looked into at some point, but it's currently beyond me.

**Comment by RodneyBaker** [comment]
Glad to see you discovered a fix.

**Comment by shun-iwasawa** [comment]
@RodneyBaker 

> I noticed there were two OT executables in my 1.2 directory after installing 1.2. One is named 1.1 and the other 1.2.

I noticed that there was the old version .exe not deleted from the package folder of the Jenkins server. I'll make a new package without it. Thank you for pointing it.

**Comment by shun-iwasawa** [comment]
I replaced the V1.2.0 installer by an updated one without the older version exe.

**Comment by manongjohn** [comment]
FYI...

I updated my NVIDIA driver to the latest version and even when forcing OT to use it, I still get a blank combo viewer/viewer when running V1.2.  :(  I think whatever change was made to use OpenGL or maybe even 5.9 is causing this.

Now I have to go back to the last supported version for my laptop otherwise my development is dead in the water unless this can be fixed in OT.  In the last supported version for my laptop, forcing OT to use GPU at least fixed it for me.

**Comment by turtletooth** [comment]
@manongjohn Can you try this branch?  It is a reversion of QOpenGl just for this purpose.  I think it would be better in the long run to fix the issues, but this is a temporary solution for people in your situation.

**Comment by manongjohn** [comment]
Yep. I did confirm the reversion fixes the problem and confirmed QOpenGL is the culprit.  I currently have my workaround so I can still develop with the latest code.  I just can't upgrade to the latest video driver for now.  

Not a big deal since I haven't really needed to. Only reason I was testing the latest driver was that I was testing a simple code solution that triggers GPU usage for NVIDIA and AMD video cards who don't have a profile for OT manually entered in their video settings to use it.  I was hoping the latest driver would fix an issue I was seeing, but instead it made my problem worse.

**Comment by turtletooth** [comment]
I'm going to make a temporary portable release for those affected by this issue.

**Comment by turtletooth** [comment]
@manongjohn There is a new version without the latest tablet fix and without QOpenGL to test on gumroad: https://gum.co/ZgxH
