### ISSUE TITLE
Huion GT-191 Pen pressure sensitivity not working

### ISSUE THREAD

**Issue by roboroter** [opentoonz/opentoonz#1675]
Attempting to draw using a huion gt 191 pen monitor and pen pressure sensitivity doesnt seem to work on any brush. Tried both vector and raster layers with no luck.

**Comment by turtletooth** [comment]
I have a gt 191, and it worked fine.  What platform are you on?

**Comment by roboroter** [comment]
Windows 10, open toonz 1,2

**Comment by turtletooth** [comment]
Just tested again on Windows 10, GT 191 and I can't duplicate this.  Do you have the pressure checkbox enabled in the brush settings?

**Comment by roboroter** [comment]
Yeah its checked. The tablet is functioning on other software just not this one, if not replicatable then im probably doing something wrong.

**Comment by shun-iwasawa** [comment]
@roboroter 
Thank you for reporting the problem. According to the [Qt manual](http://doc.qt.io/qt-5.9/qtabletevent.html#notes-for-windows-users), it says;

> Notes for Windows Users
> 
> Tablet support currently requires the WACOM windows driver providing the DLL wintab32.dll to be installed. It is contained in older packages, for example pentablet_5.3.5-3.exe.

Can you please check if `C:\Windows\system32\wintab32.dll` does exist and try installing the Wacom tablet driver?

**Comment by roboroter** [comment]
wintab32.dll was on the computer before installing the wacom drivers. I installed the latest pen display drivers from wacoms site with no luck however, the pressure is still not being picked up.

**Comment by RodneyBaker** [comment]
> wintab32.dll was on the computer before 

That sounds like past tense to me.
I think what @shun-iwasawa is saying is that if that file isn't present (even with your other drivers installed) it needs to be there as OpenToonz (or more properly Qt) will be looking for it.

**Comment by roboroter** [comment]
Yeah sorry, bad phrasing. I was meaning to say its been on all along, and is still on at the moment

**Comment by roboroter** [comment]
Update: issue resolved. Issue with huion drivers after the latest windows update. a simple reinstall has fixed it.
