### ISSUE TITLE
OT 1.2 mac  subxsheet is not visible in animate mode of plastic tool

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#1676]
![subxsheetvanish720new](https://user-images.githubusercontent.com/22670132/33859068-227b8b8c-de87-11e7-9639-1e861f635f0c.gif)

subxsheets are not visible in animate mode of plastic tool once a skeleton is applied.

 In the example there is a drawing, mesh, and skeleton acting normally and next to it is the same drawing collapsed in a subxsheet with the same mesh and skeleton applied. the subxsheet version disappears in animate mode.

The example also shows the same scene open in 1.1.3 nightly build from October where everything works as it should. 

plastic tool disappearance issues have been occurring since the 2017-10-27 nightly build.

 on mac high sierra

**Comment by artisteacher** [comment]
I’m also getting the same crash with animate mode + preview + the subxsheet that was fixed with  #1569 for non-subxsheet levels #1543.

**Comment by shun-iwasawa** [comment]
Confirmed the problem. Thank you for reporting this.

**Comment by artisteacher** [comment]
This was fixed in #1678 and is still working - recommend closing.
