### ISSUE TITLE
Rigpuppets for bitmap/ pixel images??

### ISSUE THREAD

**Issue by scribbloid** [opentoonz/opentoonz#1684]
Since yesterday i found out about rig puppets and i also tried synfig.
With synfig it seems you can create rig puppets for Bitmap Images.

In opentoonz you can create rig puppets and bone sets for vector Levels. Is it possible to create rig puppets for raster Levels too?

would like to do Things like this:
http://www.danfessler.com/blog/thoughts-on-modular-animation

My english is very bad, I apologize.
Thank you for helping me out

**Comment by artisteacher** [comment]
You can use both the skeleton tool and the plastic tool to create rigs for all 3 level types.

**Comment by Jose-Moreno** [comment]
@scribbloid to do modular animation for **games** I'd actually recommend using DragonBones which is free or Blender with the CoaTools add-On which exports a JSON format similar to Spine. 

Synfig is a good choice for digital animation in general, but if you want the animation to be used in game engines, you'll be limited to export your animation as individual images and then you'd have to create your own spritesheets instead. 

If you require it for **webcast or broadcast animation**, Opentoonz can do the job with a bit of effort...but to be quite honest OT's strength does not currently reside with Cut-Out / modular animation just yet.

**Comment by RodneyBaker** [comment]
Closing this as feature request and/or researching available options for cutout puppet animation.
Recommend continuing the discussion in the OpenToonz Forum and/or one of the many online OpenToonz communities.
