### ISSUE TITLE
Scrub timeline with mousewheel

### ISSUE THREAD

**Issue by HamousOnWheels** [opentoonz/opentoonz#1691]
I remember opentoonz 1.1.3 having the ability to scrub the timeline by spinning the mousewheel while holding shift, as described in #695, #994 . I cannot seem to do this in the newest 1.2 release and the 12/5 OTX release, spinning the wheel just zooms the view regardless of keys held.

OS is windows 7, tested with mouse and tablet.

**Comment by manongjohn** [comment]
The commands were altered as part of #1378, and they still work in 1.2.

**Comment by HamousOnWheels** [comment]
Ah I missed this one in my search. That works for me, thank you!
