### ISSUE TITLE
Opentoonz creates drawings with letters in name but doesnt reopen them

### ISSUE THREAD

**Issue by HamousOnWheels** [opentoonz/opentoonz#1693]
When autocreation is set to 'Use Xsheet as Animation Sheet' opentoonz can create drawings with names like 2a, 2b etc, but after saving and reopening the scene does not load them anymore. The drawings themselves are still present in the extras folder, opentoonz just doesnt recognise them. The only workaround is to renumber the level before saving and closing.

![frames](https://user-images.githubusercontent.com/34580619/34054930-4ad0f1dc-e1cd-11e7-8e0b-8b5cf68f28a2.gif)
![image](https://user-images.githubusercontent.com/34580619/34054962-6eeca4c6-e1cd-11e7-868f-84f0f90ecd13.png)

I tried using regular expressions in Level Settings by File Format but it made no difference. This expression should have worked: `.+[0-9a-z]{4,5}\.tif` (#644)

Tested on windows 7 in OT 1.2 and OTX 12/5.

**Comment by BrundleThwaite** [comment]
I will second this. Any drawing where the number is duplicated will get a letter added and will not be saved. Because the drawing is not saved it can not even be salvaged manually.

**Comment by RodneyBaker** [comment]
The very latest OTX (released yesterday - 3Jan2018) appears not to have this problem but... that is with images/frames created with OpenToonz so we'll need to check to see how it handles files from outside of OpenToonz.

The specific feature that was added allows the user to change the way images are created (and inserted) when drawing directly via the xsheet (via Preferences).  The only thing that is still a bit confusing is that while everything appears (and reopens) correctly in the xsheet in the Level Strip duplicates display the same name (i.e. 0002 and 0002a will both display as 0002, etc.)

**Comment by HamousOnWheels** [comment]
I still have the same issue in OTX 1/3/18. One thing I forgot to mention is that this only happens with raster levels. Toonz raster and vector levels are recognised exactly as reported by @RodneyBaker.

**Comment by DarrenTea** [comment]
I came across this earlier today. Here's my reproducable steps:
