### ISSUE TITLE
Raster brush offset on OSX

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#1696]
Hello guys, recently I downloaded the new Open Toonz version (1.2) for OSX. Its working fine, but I realized that when I use the raster brush the stroke is offset, far from the cursor.
These are my specs, and a link to a demonstration video:

Demonstration video:
https://drive.google.com/file/d/17GBI780jktWveMfPeobLDvgX7SrkkpMP/view?usp=sharing

MacOS Sierra 10.12.6
Processor 2.8 GHz Intel Core i5
Memory 8 GB 1600 MHz DDR3
Startup Disk Macintosh HD
Graphics Intel Iris 1536 MB
Cintiq 13HD
  
Thanks in advance for all your work and dedication.

**Comment by artisteacher** [comment]
I haven’t noticed that happening in either 10.11.6 or 10.13.1. Maybe this is an issue related to the Cintiq?

**Comment by NestorAntonio** [comment]
Hi, I tried Jeremy's solution on #1697 of making sure that both screens, the Mac and the Cintiq have the same display scaling. In the case of the Mac it seems that I can't change it too much, unlike the  options for the Cintiq, that provides different resolutions. The only option that both have on common is using a Default resolution for the displays. 

![cintiq](https://user-images.githubusercontent.com/18132742/34234635-51b756ee-e5ba-11e7-918e-fe45862b7fca.png)
<img width="1280" alt="mac" src="https://user-images.githubusercontent.com/18132742/34234636-51c490d4-e5ba-11e7-8f0f-e59ee287a0b0.png">

**Comment by artisteacher** [comment]
Try pressing on the alt key when you press scaled.

**Comment by NestorAntonio** [comment]
If I press the alt key when I select Scaled on the Cintiq it shows more resolutions to choose from, but if I do it on the Mac, nothing happens.

**Comment by artisteacher** [comment]
That’s too bad! In case you haven’t noticed, if you hover over each icon (from larger text to more space) below the preview image on the left, it displays what the resolution looks like. So larger text looks like 1024x640, the next setting looks like 1280x800, the next looks like 1440x900, default looks like 1680x1050, and more space looks like 1920x1200. Are there any resolution options that are equivalent on the Cintiq?

**Comment by adamlukesinger** [comment]
Hi, this is my first post here so please forgive any n00b mistakes :)

I noticed this seems to be the same issue as the following, because I am also experiencing it on Windows with a cintiq:
#1686 

Just to add my info:
I am using Windows 10, and an old cintiq 12wx in a mixed resolution environment as well. My primary monitor is using default windows scaling (150%) on a 3840x2160 screen.
I am also experiencing it with the raster brush only. The vector brush is fine. Raster brush works fine on the high dpi display (not the cintiq) when drawing with the mouse.
It appears the raster strokes are being drawn in an incorrect 3d space, because when I pan the camera the strokes show they are offset in Z space from the canvas. (There is heavy parallax between the strokes and the canvas while panning.)

Thank you for your work on OpenToonz! I am really looking forward to the development of this program.

**Comment by NestorAntonio** [comment]
No, it seems that my Mac Pro only gives to the Cintiq the options described on the first image. Also checked the settings that comes within the Wacom's Desktop Center, but these are the only options I've got: 
![screen shot 2017-12-23 at 10 45 54 pm 2](https://user-images.githubusercontent.com/18132742/34324125-a35288b8-e833-11e7-92a5-20b3d9fb3368.png)

**Comment by NestorAntonio** [comment]
HI adamlukesinger, now that you mention it, even though I use OPT on a different platform the issue only seems to happen when using a raster brush too, unlike the vector level where the brush seems to work fine. Also, I realized that if I draw on the 3D view the problem doesn't happens. 

I made a demonstration video where you can see the comparison between the two types of levels and views, and as adamlukesinger says, at the moment of drawing in the 2D view with the raster brush, there is clearly a camera offset that doesn’t occur in the 3D view. 

https://drive.google.com/file/d/1sUKWogfkbGFSsnIXG9UPIJc5MxPv5WYO/view?usp=sharing

**Comment by NestorAntonio** [comment]
Hello Guys. Recently I was trying again, and also noted that if I draw on the Mac's monitor (changing screens with the Cintiq) the offset doesn't happens. But if I drag Open Toonz's window to the Cintiq's monitor, (I change the screen again) and draw on the tablet the offset keeps happening.

**Comment by NestorAntonio** [comment]
Hello everyone, I solved the  issue on OSX by duplicating the window on the display settings. This way the offset wont happen when using the cintiq.

**Comment by RodneyBaker** [comment]
Resolved according to @NestorAntonio 
If anyone is experiencing related issues please let us know.
