### ISSUE TITLE
Brush delay on OPT 2.0

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#1697]
Hello everyone, I’ve been using Open Toonz on my Mac pro with the aid of Parallels, a virtual box, since I had a bit of trouble with the OS X versions. I was using the Open Toonz Morevna edition 1.1.3 which works great. Recently I’ve downloaded the new Open Toonz’s version (1.2) but noticed that at the time of drawing with the raster brush, the stroke gets a bit delayed (like it drags the cursor) causing a distorted result. 

It feels like the UI of the new OPT is graphically heavier. If this is the problem... is there a way I could switch back OPT 2.0 to the old interface that the Morevna edition 1.1.3 uses? These are my specs:

Windows 7 Ultimate SP1

Processor: Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz 2.80 GHz

Installed memory: 4.00GB

System type: 64-bit Operating System

Pen and Touch: Pen Input Available

Cintiq 13 HD

Running under Parallels Desktop 11 for Mac Business Edition -Version 11.2.0 (32581)- : 

MacOS Sierra 10.12.6

Processor 2.8 GHz Intel Core i5

Memory 8 GB 1600 MHz DDR3

Startup Disk Macintosh HD

Graphics Intel Iris 1536 MB

Also, I uploaded a couple of videos to show the difference when using the two versions. In them I'm trying to draw a curve.

Thanks in advance to everyone.

(Test A: OPT 1.1.3)

https://drive.google.com/file/d/1zKtpq2e-dq81iDqdrrSC5BgaDPT6kVXm/view?usp=sharing

(Test A: OPT 2.0)

https://drive.google.com/file/d/1LXjh27X7o_1RUFgkxZ8AFGze5NFQ3zOk/view?usp=sharing

**Comment by artisteacher** [comment]
Have you tried using 1.2 without Parallels? It’s not perfect but greatly improved from 1.13 on OS X.

**Comment by NestorAntonio** [comment]
I tried but I had an offset problem with the brush, I created a separate thread: #1696

**Comment by NestorAntonio** [comment]
Hello, thanks for the reference on the other threat (#1686) . Using turtletooth's OPT 2.0 Portable version solved the issue, he says that some changes under the hood improves the drawing experience. I tried and it works.

**Comment by RodneyBaker** [comment]
This should be resolved in current nightly release.
@NestorAntonio  can you verify?

**Comment by NestorAntonio** [comment]
Hello Rodney! Thanks, I tried the new release and it is a lot better. There is still a bit of delay, but not because of the software but the graphic capacity of my laptop. With a better set up It should run smoothly.

**Comment by RodneyBaker** [comment]
Given @NestorAntonio 's feedback (see above) recommend this issue be closed.
