### ISSUE TITLE
Missing library for Morevna 1.2 in OS X

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1702]
@morevnaproject, @blackwarthog 
The latest release for Morevna’s version of OT is missing a library, which causes a crash on open.
<img width="622" alt="b5155ef4-9f17-4015-8d4f-27595a91b7cf" src="https://user-images.githubusercontent.com/21159116/34183080-fbdd9888-e4e6-11e7-9c3a-f0b66d5e3dac.png">

**Comment by blackwarthog** [comment]
We've added QtMultimediaWidget.framework into app.

Please check this build:
https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-17.12.22-osx64-55bb3.dmg

**Comment by artisteacher** [comment]
It opens just fine. Thank you!

**Comment by morevnaproject** [comment]
@artisteacher Thanks to you for reporting! ^__^
