### ISSUE TITLE
wacom tablet regression from 1.1.3 to 1.2.0.1

### ISSUE THREAD

**Issue by jpritikin** [opentoonz/opentoonz#1704]
I'm not sure if this is already reported, but on Debian Linux using the Morevna AppImages, the tablet worked great with 1.1.3 and no longer draws with the correct tool in 1.2.0.1. If I select paintbrush, it draws with something else that doesn't stick.

**Comment by jpturcotte** [comment]
What do you mean by "that doesn't stick"?

**Comment by jpritikin** [comment]
On Thu, Dec 21, 2017 at 03:48:43PM +0000, J.P. Turcotte wrote:
>    What do you mean by "that doesn't stick"?

Here's the behavior, https://www.youtube.com/watch?v=SXg3OjL93AQ

Maybe I'm missing something?

**Comment by jpritikin** [comment]
If I do the same action with the mouse then the strokes are recorded in the level. Make sense?

**Comment by jpturcotte** [comment]
Thank you for the precisions (and video)! Sadly, it looks like a bug. cc @morevnaproject

**Comment by jpritikin** [comment]
@blackwarthog CC

**Comment by morevnaproject** [comment]
Hello @jpritikin!

Just want to make sure: Is it possible that you are accidentally pressing one of the stylus buttons (or keyboard) while drawing?

Can you please test if the same issue happens with this special build? - https://sourceforge.net/projects/opentoonz-morevna-edition/files/stable/1.1.3.9/

This issue could be related with #1683

**Comment by jpritikin** [comment]
On Mon, Dec 25, 2017 at 06:22:54AM +0000, Konstantin Dmitriev wrote:
>    Just want to make sure: Is it possible that you are accidentally
>    pressing one of the stylus buttons (or keyboard) while drawing?
> 
>    Can you please test if the same issue happens with this special build?
>    -
>    [2]https://sourceforge.net/projects/opentoonz-morevna-edition/files/sta
>    ble/1.1.3.9/

I tested 1.1.3, 1.2.0.1, and 1.1.3.9 here,

https://www.youtube.com/watch?v=C1pVpla6NF8

In short, 1.1.3.x work great. 1.2.0.1 has trouble.

**Comment by ebarranco** [comment]
@morevnaproject  I have exactly the same issue. And the appimage  does not include the libpng12.so.0 library

**Comment by morevnaproject** [comment]
@jpritikin @ebarranco  Here we have made a special testing build - https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-17.12.27-linux64-8972d.appimage
Can you please check if it still have tablet issue?

**Comment by ebarranco** [comment]
@morevnaproject It's working for me now. Thanks.

**Comment by jpritikin** [comment]
I have not tested exhaustively, but I agree that the issue seems to be solved. Thank you!

**Comment by morevnaproject** [comment]
Fixed in Morevna Edition 1.2.0.2 by reverting changes of #1659. 

Official OpenToonz still affected. See relevant comment - https://github.com/opentoonz/opentoonz/pull/1659#issuecomment-355832631

**Comment by RodneyBaker** [comment]
@jpritikin reports this as resolved.
Please advise if anyone experiences related issues.
Closing.
