### ISSUE TITLE
Same brush each time, can't switch brushes even if i click on a new brush 

### ISSUE THREAD

**Issue by KH2003** [opentoonz/opentoonz#1706]
So basically, the title says it all whenever i try to switch brushes by clicking on a new brush, it always goes back to default. If anyone can help me with this issue it would be appreciated. 

Thanks,
-Katie

**Comment by Orphanlast** [comment]
Toonz vector level?
Toonz Raster level?

Or

Raster Level?

**Comment by KH2003** [comment]
It's either of the two rasters, all I know is it's on Style Editor.

**Comment by KH2003** [comment]
How can you tell which one it is?

**Comment by Orphanlast** [comment]
Are you clicking on the "raster" tab?

If it's a yellow column, it's vector.

**Comment by KH2003** [comment]
It's not yellow, so I'm going to assume it's not vector and it is the
raster tab.

On Dec 24, 2017 2:10 AM, "Orphanlast" <notifications@github.com> wrote:

Are you clicking on the "raster" tab?

If it's a yellow column, it's vector.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/issues/1706#issuecomment-353769290>,
or mute the thread

**Comment by artisteacher** [comment]
Green = toonz raster level, which only has one brush available. Blue = raster level which is the only level type that can use the raster brushes. Which level type are you using?

**Comment by KH2003** [comment]
Blue

**Comment by artisteacher** [comment]
What is your operating system? Could you share a video or animated gif of what you are experiencing?

Do you have the style editor set to auto-apply (the auto-apply button would be a dark grey with the apply button greyed out)?

**Comment by KH2003** [comment]
My operating system is Windows 10 and heres a GIF  consisting of my issue. Also I'm on vector toonz, I just looked in preferences. 

![Uploading 2017-12-25-19-06-16.gif…]()

**Comment by Orphanlast** [comment]
Umm... 

The .GIF doesn't seem to work

**Comment by KH2003** [comment]
Did the GIF work this time? If not here's a video.

**Comment by Orphanlast** [comment]
I'm not seeing it. Maybe it's my phone, but it usually doesn't pose a problem

**Comment by artisteacher** [comment]
I’m not seeing it either.

**Comment by KH2003** [comment]
1. I draw a line (I'm also in vector toonz).
2. I go to the rasters tab and I click the default brush preset and it
draws okay
3. I go to a different brush (with auto apply on at the time), and I go to
a new brush preset. It draws nothing.
4. I turn auto apply off this time and it shows the same brush each time
whether I'm switching presets or not.

**Comment by KH2003** [comment]
I hope this is okay, I couldn't get the pictures.

**Comment by artisteacher** [comment]
If you are drawing on a vector level (sort of a darkish dijon yellow), only vector brushes can be used. If you want a different vector brush, try the vector tab. If you want to use the raster brushes, you’ll need to create a raster level. 

To easily add any level type, you might want to add the command bar (under Windows) or enable the Xsheet toolbar in Preferences. In those toolbars, the first new level button creates vector levels, the 2nd creates toonz raster levels, and the 3rd creates raster levels.

**Comment by KH2003** [comment]
Okay, thank you for the help. :)

**Comment by artisteacher** [comment]
You’re welcome! If you are all set, you should close the issue.
