### ISSUE TITLE
Yiynova tablet not working

### ISSUE THREAD

**Issue by Firestoem** [opentoonz/opentoonz#1714]
Running windows 10 with a Yiynova MSP19U, just installed the latest driver.

The issue might not be entirely Opentooz fault but figured I'd ask if anyone had a similar issue, since this seems to just be my tablet a lot of the time. 

The tablet works fine in PaintTool SAI but won't work on my desktop and it will not work in Opentoonz, it won't even register the pen at all. 

Now I can get it to work if I switch to only one display. however it seems to be an ever so slight delay as well as the fact I can't really sketch, lines seem to big despite the brush being set to a minimum of 0 (doesn't seem to taper at the end?) not sure if thats just how the program works however! 

Any help or suggestions would be appreciated. I really would prefer to work as a duel monitor set-up for references and such.

**Comment by Orphanlast** [comment]
As of saturday, my intuos art series graphics tablet doesn't work properly, regardless of program. I might just have to buy a Huion, and get it over nighted to me, to keep up with my blog

**Comment by RodneyBaker** [comment]
Multiple monitors appears to be a core element of this problem.

**Comment by RodneyBaker** [comment]
This appears to be one of those issues related to drivers, graphics settings and incompatible monitor resolutions.

@Firestoem are you still experiencing the problem and if so have you see the other reports that outline likely solutions?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
