### ISSUE TITLE
Ctrl + Shift Clicking on Cells in XSheet Duplicates them

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#1715]
@manongjohn Any idea if this is expected?  It isn't undoable.

**Comment by manongjohn** [comment]
I can't seem to reproduce

**Comment by turtletooth** [comment]
Can you try it in the newest OTX? https://gum.co/TZmmM

I have merged some of your PRs in there.

**Comment by turtletooth** [comment]
btw - it's clicking on the drag handle of the cell that does it.

**Comment by turtletooth** [comment]
Just tested in the main 1.2 release and it's there too.

**Comment by artisteacher** [comment]
I’m not seeing this in OS X.

**Comment by manongjohn** [comment]
Ah, that's the part I was missing.  Control+Shift+Click-Drag Handle.  I can duplicate it now.  Happens in 1.1.3 version as well.

Will take a look at it.  If anything, the undo should be fixed.

**Comment by manongjohn** [comment]
Apparently that command sequence is valid.  If you click the dragbar within a selection, the entire selection, even across columns, gets duplicated right after the selection.  If you click the dragbar outside a selection, the entire level gets duplicated.

The only issue here is you can't undo/redo, which I can look at fixing.

**Comment by adamearle** [comment]
I know in flash its something like alt click drag. this makes for a super fast workflow especially when it comes time to favoring keys. I could see this being used a lot with the ironing tool and magnet tool for really tight animations
