### ISSUE TITLE
(Morevna Edition) Difference between Appimage 1.2.0.2 and github 1.2.0.2

### ISSUE THREAD

**Issue by Toybulldog** [opentoonz/opentoonz#1721]
Hallo @morevnaproject

I want to show you what problems I have with "open toonz"

Best of all, "Github Opentoonz- commit 75b93877c0abd6a5a005a039d134a584eec7ec8c(1.1.3)" works on LinuxMint 18.3  .
![my system](https://user-images.githubusercontent.com/11164330/34662854-de6bbf2e-f453-11e7-9f6b-cfb24f5c30d8.png)

But since yesterday has changed.
Now I can also use 1.2.0.2
But not problem free .
I would like to show this in my video

https://vimeo.com/250078895

P.s.
I tried the version of  turtletooth (github otx 1.3-18) but it does not work on Linux

lg peter

**Comment by morevnaproject** [comment]
Hello, Peter! please submit a separate report about each problem. This way your problems can be addresed by developers.

**Comment by Toybulldog** [comment]
Hello "Morevnaproject" .
With the video I wanted to point out that my Wacom does not work with the appimage .
I can use the appimage with the mouse. This works, as far as I have tested it,  everything .
But with my Wacom the Appimage does not work, as you can see in the video.

Then I instaled the version of github, which I think you have built the Appimage 1.2.02 with.
So I can serve OT well, except for a few small things I have to use the mous.
So I see the main problem first in the Appimage .
Unfortunately I am not a Hacker, and rather deal with the problems like a craftsman.
And now to list everything, and to name every single point, I do not think it makes sense now.
But I'm very happy with all this and OT is making great progress.

You Fix the linux build 
I just got the github 466fc8e4fc6e73d7595e4073f5344952cf3fd53b install ,
and I am the happiest boy in the moment in the world.
The Plastic tool works, until I can see that far.

Thank you very much to all developers
lg peter

**Comment by morevnaproject** [comment]
I am happy to hear you got this resolved! ^__^

@turtletooth It's OK to close this.

**Comment by Toybulldog** [comment]
Please look at the link, unfortunately Opentoonz crashes when rendering ,when I use plastic tool
https://github.com/opentoonz/opentoonz/issues/1096#issuecomment-359141627
