### ISSUE TITLE
Control points hard to click on

### ISSUE THREAD

**Issue by Zackrobat** [opentoonz/opentoonz#1722]
There appears to be a problem clicking on control points and handles in vector drawings, where sometimes the point gets selected, and sometimes not. I noticed it in Linux, but it seems to exist in Windows too. Here's a video of my experience:

https://www.youtube.com/watch?v=dVpiMIPsRpI

On Google Groups I said:
"It's just me clicking over and over again on a bunch of control points and handles. In a couple cases, I admit I just mess up and click in the wrong place. And in the majority of other cases, there's no problem. But in a significant minority of cases, the problem occurs. And while my clicking may not be absolutely centered on the control points, the control points are always highlighted when I click on them, which to me suggests that clicking on them should work."

And ManongJohn said:
"I can replicate this in Windows as well. After some careful and controlled testing, it seems that after the white box expands as you hover over it, when you click it on it to grab it, the logic doesn't account for the expanded box's dimension.  If you manage to click in the larger box, but outside the original tiny box that is theoretically centered underneath, it will either grab a line (if you are close to one) or nothing and start a selection drag.  The closer you get to the center of the expanded box, the more likely you will grab the box and not the line."

**Comment by artisteacher** [comment]
This sometimes happens in OS X as well. Similarly, it can be challenging to select vector objects by clicking on them with the select tool. Clicking on the fill usually does not result in the shape being selected - just clicking on the outline. The expected behavior is that clicking anywhere on the vector object would select it.
