### ISSUE TITLE
Print Xsheet xml & css templates lost

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1723]
I've found that the XML and CSS templates used by the Print Xsheet command are missing from the instalation files.
These files are: "xsheet.css" and "xsheet_html.xml".

Originally (in Toonz) intended to be placed at:
C:\Toonz 7.x stuff\profiles\layouts\Toonz

I've learned that if I place these two files at:
C:\OpenToonz 1.2 stuff\profiles\layouts\settings
then OpenToonz can use them.

So... could they be included in the standard installation package in future versions?

I leave them here, just in case.
[printxsheet_templates.zip](https://github.com/opentoonz/opentoonz/files/1616372/printxsheet_templates.zip)

Thanks!

**Comment by RodneyBaker** [comment]
Thank you for that!  I knew there had to be something more to 'printed' xsheets than what we were seeing.

Now we need to know more about how to drive more data population into the results via the xml template!

Thanks much for this find.
