### ISSUE TITLE
Rendering Bug with Audio and Vectors

### ISSUE THREAD

**Issue by MaskedDragonLin** [opentoonz/opentoonz#1727]
I recently finished a 4 second long animation. Everything was looking good, I had the audio set right and all the levels visible, so I decided to render it. The animation uses vector layers, an opentoonz raster layer, and a couple normal raster layers, as well as said audio. Anyways, I export it (as an avi file) and then look at my video, but it's been messed up. The visual part of it looks like it's heavily lagging like it does (to a lesser degree) in the program, but the audio is playing normal, making it so that very quickly in, the audio cuts out and leaves the animation slowly ghosting behind. One of the vector levels also malfunctioned in the process and is only showing the filled in shapes, but not the lines- but only one of them, the other one has its lines and everything. The animation also lasts longer than it says it does- the video play bar says 4 seconds, but it reaches the end of the bar, the audio stops, but the ghosting animation keeps going. Also, the white strips outside of the active area in the program showed up in the render, though that might be an issue on my end for not being experienced in animating.

I then tried deleting the exported animation so I could try rendering again, to see if that would solve it, but it said that "The action can't be completed because the file is open in opentoonz 1.1" My opentoonz is still open at this time, so for some reason the file is connected to the program still.

I use Windows 10.

The attached images are both from what the video bar (visible in the top image) claims to be the end of the video, showing how it keeps going. The other issues are also shown in the top image (the cat has no lines, the white strips at top and bottom) I'll try re-rendering it to see if that helps, but help/pointers would be useful.
![render error 2](https://user-images.githubusercontent.com/35390903/34903591-60b1125c-f7e9-11e7-9f83-7faa5d1eb35b.png)
![render error 1](https://user-images.githubusercontent.com/35390903/34903592-60dfbecc-f7e9-11e7-8fec-f2bc8f769489.png)

**Comment by artisteacher** [comment]
You should be able to re-render without deleting the old video. The old video should automatically be deleted when you render again. If that doesn’t happen, you could always change the name for the new video. Do you have the same issue if you render to mp4 (assuming that you have FFmpeg setup)?

**Comment by MaskedDragonLin** [comment]
I can re-render the video, I just can't delete it while Opentoonz is open,
nor can I rename it. That would make sense if it were a part of the
program, but it's just a video avi, so that perplexes me. I don't have the
ffmpeg set up, so I don't know. Changing the dimensions of it also buggy,
I'll change the width and it'll mess with the height, but the dimensions
don't change in proportions to one another.

**Comment by MaskedDragonLin** [comment]
I'll look into that. I figured out the resizing after a little tinkering,
it's different for sure. Hopefully converting it to a mp4 will solve the
messup with the cat's lines.

**Comment by RodneyBaker** [comment]
@MaskedDragonLin This report appears to have gotten lost in the mix.
We'd love to hear about how your testing with ffmpeg and mp4 turned out.

Are you still experiencing any problems with rendering of images and audio?

**Comment by MaskedDragonLin** [comment]
I no longer have that version of open toonz, but i don't think i ever did
get the cats lines to reappear. Sorry about that!

**Comment by RodneyBaker** [comment]
The vast majority of productions add audio in in a dedicated application for that so hopefully you've got  something ideal for that.  Opentoonz generally does an excellent job with audio as a scratch track.

Closing pending additional information.
There are several other audio related issues still open so hopefully we will see some development in that area in the future for Opentoonz.  Barring that perhaps users can outline their best practices for blending Opentoonz with other digital audio applications.
