### ISSUE TITLE
can't find white canvas

### ISSUE THREAD

**Issue by seintcat** [opentoonz/opentoonz#1728]
When install and running opentoonz on my computer, white canvas wasn't displayed.
![image](https://user-images.githubusercontent.com/35403288/34908007-150cb980-f8cc-11e7-810a-1bef4391a7de.png)
how can I fix this problem?

**Comment by manongjohn** [comment]
This is a duplicate of #1674. There is a link in that thread to an OTX version which has a workaround.

**Comment by seintcat** [comment]
I renamed program(verson), but it doesn't work...

**Comment by artisteacher** [comment]
Try installing the OTX release that's linked to in #1674.

**Comment by seintcat** [comment]
now it works! thank you!
