### ISSUE TITLE
Copy/paste crash between frames

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1730]
I find that I can copy and paste raster art from frame to frame. However, if I spend a couple of minutes in between pasting to make adjustments to a frame and then continue pasting I consistently get a crash. It's as if something goes wrong with the image stored in the clipboard.

EDIT: Just to clarify, duplicating entire frames isn't the problem, it's copying part of an image selected with the selection tool.

(Opentoonz 1.2, Windows 10)

**Comment by artisteacher** [comment]
I’ve had some students experience crashes in OS X after trying to copy and paste though I’m not sure about the level type. It may have been vector levels.

**Comment by artisteacher** [comment]
I'm getting this crash repeatedly whenever copying from an existing raster or toonz raster frame and pasting on the next empty frame. Pasting into the next empty frame works perfectly for vector levels without a crash.

1. Create a raster or toonz raster level with one frame
2. Draw with the brush or geometric tool
3. Use the shortcut "S" to change to the select tool
4. Click & drag to select a rectangle around the drawing
5. CMD-C to copy
6. Left-click to exit the selection & then use the right or down arrow key to navigate to the next frame
7. CMD-V to paste = crash

The select mode does not seem to make a difference - ie. rectangular or freehand both crash. Pasting on a pre-existing frame works without issue.
[raster_paste_crash.txt](https://github.com/opentoonz/opentoonz/files/2428828/raster_paste_crash.txt)

**Comment by artisteacher** [comment]
It seems that the crash doesn’t happen if you manually click on the cell in the Xsheet - the crash only happens after navigating the Xsheet with the arrow keys.

**Comment by manongjohn** [comment]
FYI, I can reproduce this crash in Windows.

**Comment by manongjohn** [comment]
Found issue. The down arrow may move it to the next cell, but the focus is still the canvas and it doesn't create a blank frame before pasting and crashes. 

It works with clicking cell first because the focus becomes the xsheet and follows a different set of logic for pasting into blank frame.

Will post fix shortly.
