### ISSUE TITLE
Brush shape and pressure issue

### ISSUE THREAD

**Issue by ediblecheese** [opentoonz/opentoonz#1731]
Hello! After downloading 1.1.2, I ran into a problem with the brush tool. The brush sensitivity doesn't seem to be working properly, with the lines appearing like the image below.

![line problems](https://user-images.githubusercontent.com/35407785/34909895-5300517c-f8a2-11e7-83b9-b130f421c66a.PNG)

The lines begin in a blob, aren't very smooth and have round ends. I've tested my tablet with other software and it's not the problem, as well as the fact that the same thing happens when using the mouse. I've restarted my computer and the problem has persisted. I have pressure sensitivity enabled, and I'm not entirely sure what I'm missing. 

I'm running on Windows 8.1, but didn't have this issue with the previous version of OpenToonz.

This may well be an easy fix and I'm just being stupid (I'm not the most tech-savvy person), but any help is much appreciated.

**Comment by artisteacher** [comment]
The teardrop behavior has been a problem in OS X for a while (#1058). Turning off pressure sensativity or switching vector brushes could help. The line smoothness problem was reported in a comment in #1592. I think there is a fix coming but during the wait, using either the Morevna release or OTX from @turtletooth should hopefully resolve that issue.

**Comment by ediblecheese** [comment]
Thank you!
