### ISSUE TITLE
"Old" Fill Tool crash (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1737]
Another "old" crash. It is present in all versions of the program (1.2, OTX, Morevna)
Hope, it is easy to fix. 

Steps to reproduce:
1. Run OT
2. Select Fill Tool and change to "Line" mode.
3. Close program.
4. Run OT again.
5. Create new Vector Level.
6. Select Fill Tool.
7. OT will crash.

 If the Fill Tool is in any of the other modes (Areas, Lines & Areas), it does not crash.
If the scene or level is not the first after launching, the crash also does not occur, regardless of which mode the Fill Tool is in.

![34687816-8e12e9b6-f4b8-11e7-9fb8-25d41f028db6](https://user-images.githubusercontent.com/25724133/35062824-fd4b110c-fbcd-11e7-9356-760c133999c1.gif)

**Comment by shun-iwasawa** [comment]
Thanks @beeheemooth, I confirmed the crash.
