### ISSUE TITLE
Matte In FX trim slightly too far

### ISSUE THREAD

**Issue by snapai** [opentoonz/opentoonz#1747]
When using the matteIn FX node to cover an object precisely with another layer (in this case an eyelid that needs to be a different color than the head base), it trims the overlaying layer just slightly too far - leaving an antialias-width gap (black in this case because the layer below is black)

(I thought this was the same issue as the Plastic Tool's black contour, but turns out it's different).

Here's a demo, and the source graph that is creating it (ignore the red handles, this is from a real project).
I'm sure I can work around it with a dilate/erode on the matte input, but still would be nice to have it just work correctly!

![image](https://user-images.githubusercontent.com/5098372/35176864-b74147e4-fd49-11e7-9402-24f7ff12dd7f.png)

**Comment by shun-iwasawa** [comment]
You means that you applied MatteInFx and tried to put it above and hide the lower layer which has exactly the same shape as the matte?
If yes, IMO it is not a bug. MatteInFx works relatively simple - it just multiplies alpha value of the matte image to all channels of the source image. At anti-aliased part the pixels will become semi-transparent. and semi-transparent pixels cannot cover the layer below.
I think applying the dilate filter to the matte is reasonable solution.

**Comment by snapai** [comment]
OK. I don't think that fixes it but I guess moves what I was expecting from "bug" to "feature request" since it's just a broken user story rather than broken code. (ie: I was expecting vectors to render like they had perfect mathematically-defined edges- but that would require a complete overhaul of the rendering engine to operate using adaptive supersampling, and antialias only at the end. Not a 'quick fix'.) Guess we can close this one.
