### ISSUE TITLE
Vector Eraser Tool crash

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1748]
I can repeatedly crash OT when erasing on a vector level as follows 

1) Draw 1 or more lines in a vector level
2) Switch to the Eraser Tool and select type "Normal"
3) Erase a part of any line
4) Switch Eraser Tool to Type "Rectangle" or "Freehand"
5) Attempt to erase  -> OT Crashes

This does not happen with "Polyline"

I am able to repeat this on OT 1.1.3 and 1.2 on a Windows.

**Comment by shun-iwasawa** [comment]
Confirmed the crash. Thank you for reporting it.
