### ISSUE TITLE
No canvas at all?

### ISSUE THREAD

**Issue by connorsucks** [opentoonz/opentoonz#1750]
Idk whats going on. I started up the program and its just grey? I've tried setting the background to white and changing the size. Anything i could think of. I really need help because i cant see where I'm drawing. Maybe its default to the program but it doesn't seem this way, so like any help would be fantastic ;v;
![capture](https://user-images.githubusercontent.com/35715006/35255843-ac971200-ffb6-11e7-91a9-ffe274600a16.PNG)

**Comment by artisteacher** [comment]
This is a duplicate of #1674. For now, you should try installing the Morevna release or turtletooth’s OTX.
