### ISSUE TITLE
Column transparency menu extends off screen

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1752]
I have a couple of workflow issues with the transparency button on the levels panel.

Clicking and holding to get the transparency popup is not hugely intuitive, but a bigger problem for me is the fact that the popup doesn't take screen edge into account. When the level is up against the edge of my screen, the popup goes off the right edge of the screen (and I can't adjust the transparency, of course).

A second, minor issue is that when the level display is disabled, the display button itself disappears. This could be confusing for newer users (like me) who have to click in an empty space to get the level to reappear.

**Comment by artisteacher** [comment]
I agree about that the pop-up needs to take the edge of the screen into account! 

In terms of actually accessing the transparency options, if you change the column header layout (Preferences -> Xsheet) to either Compact or to Classic-revised, there is a triangular button to easily access the transparency/filter options.

**Comment by MisterABK** [comment]
That's definitely an improvement. Thanks!

**Comment by RodneyBaker** [comment]
Just a status note addressing the second issue mentioned...

> A second, minor issue is that when the level display is disabled, the display button itself disappears. This could be confusing for newer users (like me) who have to click in an empty space to get the level to reappear.

This is related in another report where it was stated that... at least for the present... no change to current feature is anticipated.

**Comment by RodneyBaker** [comment]
Updating this so it can get some attention in 2020 development cycle/UI scrub.

**Comment by RodneyBaker** [comment]
I've tested PR #3121 and confirm it resolves the issue of the opacity slider going off screen.
Merging of the PR is pending confirmation of some questions related to specific code usage.
If the fix is specifically needed for some reason the Appveyor build is available (for Windows users) and can be downloaded [here](https://ci.appveyor.com/api/buildjobs/s20d6c453ql973gi/artifacts/toonz%2Fx64%2FOpenToonz.zip).
