### ISSUE TITLE
Crash  with Vector Brush in Frame Range mode (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1758]
1. Create new Vector Level with some frames.
2. Move the frames down in Xsheet.
3. Use the Brush Tool with Frame Range option to create an animation.
4. If you try to undo the operation, the program will crash.

![ezgif-2-20c5afdf1c](https://user-images.githubusercontent.com/25724133/35364490-1dfe939c-0178-11e8-96a8-cded604aab8d.gif)

**Comment by artisteacher** [comment]
I’m getting this too. If the level starts at frame 1 there is no crash and undo works as expected. If I create the level further down I get this same crash. I don’t get a crash if I fill in the empty frames at the top of the Xsheet with another level. However in that case, I can’t undo the drawing with frame range. The drawings stay and the previous step is undone instead.
