### ISSUE TITLE
Possible to draw on hidden level

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1767]
At the moment, it's possible to draw when the selected level is hidden / invisible. This means, every so often, I end up drawing on the wrong layer without realising it - only seeing what I drew when the layer is switched back on later. Photoshop doesn't allow drawing on hidden layers for this reason.

**Comment by artisteacher** [comment]
This is a duplicate of #1066. There is actually a fix #1643 from @turtletooth waiting to be merged.

**Comment by MisterABK** [comment]
Apologies for the duplicate, that report only comes up if you search "drawings hidden". I searched "draw hidden".
