### ISSUE TITLE
 TLevelWriterWebm::ffmpegWriter fails to delete on the destruction of TLevelWriterWebm (?)

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1770]
Please forgive me for this random notification. I don't even know if anything is wrong here but I thought I should have someone verify as it's been bugging me.

Immediately after the line here:

https://github.com/opentoonz/opentoonz/blob/2b9d8f3cc866a254bbc637f25c95d08c5fe54c48/toonz/sources/image/ffmpeg/tiio_webm.cpp#L46

Shouldn't there be a curly bracket on the next line?

**Comment by RodneyBaker** [comment]
I believe this can be closed.
I apologize for the distraction.
I'm not sure what I was thinking with this one.

**Comment by shun-iwasawa** [comment]
The line 46 seems to be OK for me. ( It converts the `Quality` value from string to integer. )

I'm more concerning about that the `Ffmpeg* TLevelWriterWebm::ffmpegWriter` created in the line 47 seems to be not deleted on the destruction of `TLevelWriterWebm` .

https://github.com/opentoonz/opentoonz/blob/2b9d8f3cc866a254bbc637f25c95d08c5fe54c48/toonz/sources/image/ffmpeg/tiio_webm.cpp#L46-L47

**Comment by RodneyBaker** [comment]
I believe this has been resolved with the fixing of webm issue https://github.com/opentoonz/opentoonz/pull/2065

@shun-iwasawa your observation about line 47 about lack of deletion upon destruction is the only reason this would remain open.
