### ISSUE TITLE
Unwanted Stroke is Drawn when Using Tablet

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1781]
This problem can be reproduced only with tablet.

- Select Brush tool
- Start drawing a stroke
- Press middle or right button without releasing the pen
- Release the pen
- Release middle or right button
- Try to start drawing another stroke from different position 

In my environment, unwanted line appears connecting from the end point of the first stroke to the start point of the second stroke. This problem occurs both on vector and raster levels.

![line_problem](https://user-images.githubusercontent.com/17974955/35609894-94c01ef4-06a2-11e8-860b-4fc928ac3b98.gif)
I'm not sure this problem is related to the problem mentioned in [this comment](https://github.com/opentoonz/opentoonz/pull/1659#issuecomment-350424961).

**Comment by artisteacher** [comment]
It looks similar, but on the Toonz Raster levels, I specifically get the straight line angled towards whichever tool is being clicked on in the toolbar. It’s possible that it is triggered by unintentional/partial button press.

**Comment by artisteacher** [comment]
I'm still getting this on OS X - though usually after autosave runs. It does not happen every time so it's hard to say exactly what triggers it.
