### ISSUE TITLE
TimeCode Iwa effect - colon separator character.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1784]
I don't know if people using different locales face this, but for me that am using the OS (Win 10) in Spanish, the timecode generated by the effect looks like this:
00;00;00;00
...using semicolon (;) as separator, instead of a colon (:) (which is a more traditional way of displaying it).

It'd be great if the user could select which character to use as separator.
Thanks!

**Comment by artisteacher** [comment]
It looks the same in English. I agree that a colon is preferable.

**Comment by RodneyBaker** [comment]
This was previously reported (by @artisteacher) in the original topic dedicated to the new feature.
Perhaps that can be closed and this opened?

See: #1263

**Comment by manongjohn** [comment]
I'd consider this more a feature request than an error.

**Comment by artisteacher** [comment]
It must be standard in Japan, so is not an error per say. Outside of OT, I’ve only ever seen colons used in timecodes. Since I haven’t seen the semicolon format before, it always looks really wrong to me.

**Comment by RodneyBaker** [comment]
This issue should now be addressed via PR#1995.
It hasn't been scrubbed and merged yet but the appveyor artifact is available for testing purposes:

https://ci.appveyor.com/api/buildjobs/4abrxym8sp32s65s/artifacts/toonz%2Fx64%2FOpenToonz_1.2.zip

**Comment by RodneyBaker** [comment]
I forgot to mention...

This works as advertised as verified on Win10.  
Nice addition.

![timecodeiwa update](https://user-images.githubusercontent.com/2576432/40568935-5d26ed4c-6043-11e8-9f80-478ac35f74bd.png)
