### ISSUE TITLE
Brush performance compared to toonz premium.

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1787]
Hello,

I am so glad that opentoonz improving so fastly and awesomely with your amazing work.

I want to ask what is the big difference between opentoonz and toonz premium when it comes to brush lags. 

I recently downloaded toonz premium to test if I will have the same slugishness while I am drawing in all levels(especially vector level with onion skin enabled is un-usable for me.) And realised toonz premium brushes are smooth and snappy as heavens in all levels whether onion skin enabled or not. Not even a slight lag while drawing. 

Weird thing is I can see that slight lag on almost everyone, when I am watching opentoonz videos on youtube. And everyone seem like it s normal to have that lag. I can minimize that lag with drawing in Toonz Raster level but it s still there. I really want to fully switch to opentoonz but I can't because of this simple reason. (it's probably not simple in coding world) 

Thank you.

**Comment by RodneyBaker** [comment]
Closing this as there are several other reports open addressing optimization and speed issues.
REF:  #1864
