### ISSUE TITLE
when i render my work, it goes transparent

### ISSUE THREAD

**Issue by agenj3** [opentoonz/opentoonz#1788]
i have start to make an animation. i use some plastic tools to it. when its almost done i try to render it. and it become transparent. like this pic. the tail it must be behind the body an left hand.
but it doesn't. and like the tooth. it must be white colour. but it goes to the head colour.
i hope some one can help me. thank you.
![ada apa dengan salam_1 0001](https://user-images.githubusercontent.com/36148123/35790736-797c5522-0a76-11e8-937d-d76db53e4a05.jpg)

**Comment by shun-iwasawa** [comment]
Please check if you are activating `Show Raster Images Darken Blended` preferences option in `Preferences > Interface` category. If it is ON, try deactivating it.

**Comment by agenj3** [comment]
solved. thank you sir

**Comment by shun-iwasawa** [comment]
Great. I'll close this.
