### ISSUE TITLE
WHY DO I NOT HAVE THE TOOL "HARDNESS" AND INSTEAD I HAVE "ACCURACY"?

### ISSUE THREAD

**Issue by ItsM0JI** [opentoonz/opentoonz#1789]
Ok so im a complete noob in animating and yesterday downloaded opentoonz, theres an issue though as i was watching tutorials and stuff and realized everyone had this really usefull option called "hardness" and instead i had "accuracy" which i dont even know what is it used for. Am i doing something wrong? Do i know to buy/download anything? 

Also, i realized i couldnt use the different types of brushes for some reasson.

PLEASE HELP, i dont need that stuff right now cause im learning the very basics, but it stresses me out not having them and not knowing why.

**Comment by norrinra** [comment]
You're in a vector level. Hardness softness can't be applied on vector levels. 

Press  Alt+N   and choose Toonz Raster for the hardness option.
If you want to use those awesome MyPaint brushes you need to use Raster Level. (Not Toonz Raster).

**Comment by ItsM0JI** [comment]
Oooh thanks dude, really apreciate it, thought i had to buy add-ons or
something

**Comment by artisteacher** [comment]
Since this is a question, it would be a better fit for the Google Group.

We are very lucky - everything in the program is free!

**Comment by norrinra** [comment]
Yeah it's too good to be true. : )  Thanks to amazing developers.

**Comment by ItsM0JI** [comment]
Yeah, i mean, i wasnt complaining, opentoonz is already amazing without
that stuff, if you were to tell me it costs extra i would be fine, i just
wanted to know what was happening

**Comment by TheUnique1** [comment]
I am actually having the opposite problem, I see Smooth and Hardness but not accuracy, and it’s getting annoying how squiggly the lines are. Is it something I’m doing?

**Comment by RodneyBaker** [comment]
@TheUnique
We need to get you pointed to some tutorials on Opentoonz use.
 If you are seeing both Hardness and Smooth you are on a Toonz raster level.
Unlike the vector level which will have Accuracy and Smooth settings.
A regular raster level will have only Hardness (next to Opacity).

There are three basic image level types and each has a different toolbar.
