### ISSUE TITLE
No Context Menu on Workspace

### ISSUE THREAD

**Issue by ebarranco** [opentoonz/opentoonz#1790]
The right click of the pen in the graphics tablet does not brings up Context Menu on the workspace in all last versions of morevna opentoonz. I explain the problem [here.](https://www.dropbox.com/s/2xd2u1cj5dstvnx/OpentoonzSecondaryMenu.mp4?dl=0)

**Comment by coreyryanhanson** [comment]
I have the exact same problem with the context menu within the workspace running on CentOs7.4.

**Comment by ebarranco** [comment]
#2388 This seams to be the same issue that I report here  almost a year ago, still not fix.

**Comment by RodneyBaker** [comment]
@ebarranco The primary (Morevna) Linux updates are annual so hopefully you'll see some program in the upcoming release... which I assume will follow shortly after the next official release of Opentoonz.  

In the meantime, it would be good to hear more from those who are building Opentoonz from scratch on Linux.

**Comment by ebarranco** [comment]
I build it from source and unfortunately as I was expecting the problem is there. 

Why I think is not a tablet driver problem?

I have tested two tablets, I have a: 
Wacom CTH 661
Huion Inspiroy H950P
There is not difference. It works with a mouse, with a tablet it doesn't.
Both tablets work perfectly in any other program. 

I'm working now with a different computer since this report.

And finally went to the git releases and build v1.1.3 5b7b9fb and here it's working,  in any other next release is not working any more.

**Comment by wofogen** [comment]
I can confirm, the context menu dont open in the viewer here as well, i did not notice it before because i dont have the pen button, only now I thought of using the tablet keys.

@ebarranco from observing your video I noticed that the cursor seems to be comporting in the same way i reported here #2320 , can you check it?
