### ISSUE TITLE
Most stable installation for Windows 8.1 using 2 drives

### ISSUE THREAD

**Issue by animatedlane** [opentoonz/opentoonz#1791]
Sorry if this info is obvious but I need to know the best practice for putting most of the work files on a different drive than the C: system drive.  I thought I had this figured out with the 'stuff' folder on D: drive - with all the scene files and brushes, etc.  I let OpenToonz create this with the only alteration being the drive designation.  The basic app files were in the usual C: location.  I went to open a project today and the computer crashed, hard.  I can't delete the OpenToonz 1.2 stuff\profiles\layouts even with command prompts as administrator.  It's that messed up.

How do most people set this up with production in mind?  Obviously the C: drive will fill up if left to default settings.

**Comment by RodneyBaker** [comment]
I'll recommend using the OTX release as it is portable and you can place it anywhere you wish.

If you only want to use the official release (or rely on nightly build installations the official releases can be made portable as well by creating a 'portablestuff' folder in the installation directory.  I've found the easiest way to do this is to copy the stuff folder into the installation directory and the rename the stuff folder 'portablestuff' (one word).  Ideally this would be done *before* saving a lot of resources into the stuff folder.

When using two drives this then becomes mostly a matter of pointing OpenToonz to that drive via Preferences.  Then when creating a new Project you can specify that you want it and its directory struture to be on that drive.

**Comment by animatedlane** [comment]
Thank you, Rodney.  After I move and rename, resulting in 'portablestuff' being in toonz parent app directory on C: drive, do I then just make a project specific directory on D: drive, and set preferences to point to it?  Do I need to call the stuff directory on D: something specific, or can it be something like D:\clients\MusicVideoStuff?  Thank you again.

**Comment by RodneyBaker** [comment]
I'm struggling a bit with that myself (finding optimal ways to save and share Projects) but...

Yes.

When OpenToonz opens it should allow for the creation of a new Project.
Alternatively, in OpenToonz use File>New Project and then place that project someplace easy to find.
You will also want to turn on the option in Preferences that allows for Custom Project locations.
That can be found at the bottom of the General tab.
Other options are 'My Documents/OpenToonz' and 'Desktop/OpenToonz'.

**Comment by RodneyBaker** [comment]
Closing this as the discussion can continue in the OpenToonz forum.  ([LINK](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/opentoonz_en))
