### ISSUE TITLE
Use cppcheck on the code base

### ISSUE THREAD

**Issue by romeojulietthotel** [opentoonz/opentoonz#1794]
It is free to use and finds bugs too: https://github.com/danmar/cppcheck
There is also a jenkins plugin for it, but I don't know anything about the plugin.

I ran cppcheck locally against `toonz/sources`. 

I think this is a legitimate bug that it found, see the definition of **val[9]** at 

https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/trop/tconvolve.cpp#L86

_**Array 'val[9]' accessed at index 9, which is out of bounds.**_

https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/trop/tconvolve.cpp#L123

https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/trop/tconvolve.cpp#L128

https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/trop/tconvolve.cpp#L133

https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/trop/tconvolve.cpp#L138

**Comment by romeojulietthotel** [comment]
cppcheck is not perfect and you will see that it has false positives. But I think they are harmless in this context and they are usually obvious. Better to err on the side of caution then to miss things. There are also descriptions/hints in the reports about each finding.

This is a summary:
https://gist.github.com/romeojulietthotel/918cd4e05e143f58ac9bbb8a288a6b71

I `git clone` cppcheck and install in` /usr/local` then I run:

1. `cd /devel/opentoonz`
2. `cppcheck  --enable=all --inconclusive --force --xml-version=2 --xml toonz/sources 2> cppcheck.xml`
3. ` /devel/cppcheck/htmlreport/cppcheck-htmlreport --file=cppcheck.xml --report-dir=cppreport --source-encoding=utf-8`
4. Point your browser at `/devel/opentoonz/cppreport`

**Comment by RodneyBaker** [comment]
While useful, as the website(s) for this program generate 404s this can classified as spam.

Recommend closing.

**Comment by RodneyBaker** [comment]
How about.:  404s don't make any sense either so perhaps those links could be updated.
Or from your own keyboard you write:

**Comment by RodneyBaker** [comment]
I'll add that this appears to be the current website of CPPcheck that has the broken link in other locations:

http://cppcheck.sourceforge.net/

**Comment by romeojulietthotel** [comment]
1. - Is opentoonz code base better or worse for having cppcheck run against it? 
2. - There are flags for cppcheck to adjust what it reports, so it can be made to be less strict or more strict.

The code base to cppcheck is very active, last update was only hours ago and has over 17,000 commits and 58 releases.

**Comment by jpturcotte** [comment]
@RodneyBaker Sourceforge is known to be unreliable. The main repository seems to be on GitHub: https://github.com/danmar/cppcheck. I think this is a great suggestion that should be further discussed. Thank you, @romeojulietthotel!

**Comment by RodneyBaker** [comment]
Any additional updates/recommendations/discussion related to this?

**Comment by rozhuk-im** [comment]
Have no idea why this topic about where to get cppcheck - it is in many distro repos. :)

I check this project with cppcheck and it show many things that can be fixed.
Also clang-scanbuild can do almost same.
Even without this, -Wpedantic and -Weverything (clang) can give many interesting things.

I try to fix most simple C warnings generated by clang, and a bit gcc and msvc in: https://github.com/opentoonz/opentoonz/pull/3226

**Comment by RodneyBaker** [comment]
Closing as #3226 has been merged and cppcheck is being used by developers.
If there are specific ways cppcheck and other similar tools can be utilized better... and I'm sure it can... we should discuss this.

Bottom line:  Cppcheck has been used on the source code.  Let's improve that process even more.  :)
