### ISSUE TITLE
Onion Skin doesn't show when using the Animate Tool OSX

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#1799]
Whenever I use the Animate Tool to rotate, move or scale a drawing, and try to use the onion skin, it doesn't show. 

This issue also happens when I animate with the Skeleton Tool. The onion skin doesn't show after enabling it.

Thanks!

**Comment by artisteacher** [comment]
I'm not having this issue with 10.11.6. I'm using the latest nightly build. Onionskin works normally for you when the brush tool is enabled?

**Comment by DotSilva** [comment]
Yes, when I'm drawing with the Brush Tool, onion skin works as expected.

By the way, how can I download the latest nightly builds? Are nightly builds safe for normal work?

Thanks!

**Comment by artisteacher** [comment]
The latest nightly build is available at the top of this page[https://github.com/opentoonz/opentoonz/releases](url). You can access earlier versions here [https://github.com/opentoonz/opentoonz_nightlies/releases](url) - it is helpful for the developers to know the last version a feature was working.

It's a good idea to backup your work before installing a new version. You can get access to bug fixes and new features sooner, though sometimes new, show-stopping bugs are introduced.

**Comment by DotSilva** [comment]
Thanks a lot!

**Comment by artisteacher** [comment]
@ghost is this still an issue after updating?

**Comment by z-uo** [comment]
Hello, I also got that issue on windows with the latest opentoonz 1.2.1
The onionskin work great for frame by frame animation, but when I use the animate tool I only have onionskin on the previous frame when this frame is a different cell than the active.
![capture](https://user-images.githubusercontent.com/652668/42128385-693c6b7e-7caa-11e8-8cc9-4b4a79479043.PNG)
Here I got the onionskin from the previous frame (which is a different drawing) but not for the next frame (which is the same drawing at a different position)

**Comment by RodneyBaker** [comment]
Closing.  Original reporter = ghost.
For anyone experiencing problems with Onionskin please file a report.
Thanks!
