### ISSUE TITLE
Define Sub-Camera Bounding Box Issue OSX

### ISSUE THREAD

**Issue by DotSilva** [opentoonz/opentoonz#1800]
When I try to define a selection for the Sub-Camera Preview, the bounding box doesn't show. 

I have seen some videos on Youtube (on other OS systems) where a selection appears when dragging the desired image preview zone.

Thanks!

**Comment by artisteacher** [comment]
I’m not having this issue with OSX 10.13.3. Do you have the “define sub-camera” button toggled on?

**Comment by artisteacher** [comment]
I can also define the selection for Sub-Camera Preview on computers running 10.11.6.

As far as your Wacom goes, my Bamboo is not supported in High Sierra but still works as before. I just can't access the Wacom Preferences, so they are stuck permanently as they were set before I updated to 10.13.

**Comment by DotSilva** [comment]
Are you using the 1.2 or the nightly build?

**Comment by artisteacher** [comment]
The nightly build. I don't normally use the sub-camera, so I'm not sure if there has been a change from 1.2.

**Comment by DotSilva** [comment]
Ok. So I tested the latest nightly build and it is solved. It works as expected now! Thanks!

**Comment by shun-iwasawa** [comment]
Great. Probably some recent fix on another openGL-related issue solved this as well. I'll close this.
