### ISSUE TITLE
BokehIwa Effect doesn't work OSX 

### ISSUE THREAD

**Issue by DotSilva** [opentoonz/opentoonz#1805]
Whenever I try to apply the effect, it only displays a white image preview. I have OT 1.2 and OSX 10.12.6.

Appart from that, if I start adjusting the parameters trying to change values, it hangs/freezes not long after.

Thanks for your attention!

**Comment by shun-iwasawa** [comment]
Confirmed the problem and fixed. Thanks!

**Comment by artisteacher** [comment]
I was having the same problem with the white preview - but I think it might have at least partially been a problem with some of my dimensions/settings. A couple things seem to resolve most problems:

- Dependent on other settings, sometimes On-Focus distance only works when set to the same value as one of the layer distances
- Sometimes the Bokeh Amount needs to be increased or decreased
- Shrinking (significantly) or redrawing the iris image sometimes helps

While I can consistently get a great effect without keyframing the fx settings, I haven’t been able to get a good, smooth transition changing the on-focus distance to switch from one layer in focus to another. I keep getting a few frames towards the towards the beginning and end that only show one of the layers (the one most out of focus) which results in a very jumpy transition. It’s possible that it’s user error on my part, but I’m not convinced it is.

I’m not having an issue with the hanging/freezing on my current computer but I can check my computer at school tomorrow which is a lot older & can’t handle as much.

**Comment by DotSilva** [comment]
WOW! That was... fast! Thanks A LOT shun-iwasawa!
