### ISSUE TITLE
Paradoxal Undo - Redo ($50)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1807]
1. Select the vector shape.
2. Copy (Ctrl + C)
3. Move the time slider downward with the hotkey (do not highlight the frames with the cursor)
4. Paste (Ctrl + V) A new frame is created and a shape is inserted.
5. Undo (Ctrl + Z) The inserted form disappears, and the frame does not.
6. Press Undo until the resulting frame disappears. It disappears when the elongated exposure of the first frame is canceled.
7. Now click on the Redo button several times.
In Xsheet, the missing frame does not appear, and in Level Strip redo looks random. The results are different for the same action orders. In one case, both forms return to their Level Strip cells, in the other they are both placed in the first cell. The only difference between these two gifs is that in one I made the circle line a little thicker (before the described actions).

![ezgif-1-52df1cafb0](https://user-images.githubusercontent.com/25724133/36257393-5db8fbc4-125f-11e8-9304-061824586fe6.gif)

![ezgif-1-8e6e5215a6](https://user-images.githubusercontent.com/25724133/36257403-665c39ee-125f-11e8-9546-f3d0f97cf386.gif)

**Comment by jpturcotte** [comment]
A $50 bounty has been posted!

**Comment by RodneyBaker** [comment]
As of this date this is still a bug with a bounty.
See:  https://www.bountysource.com/issues/55087878-paradoxal-undo-redo-gifs
