### ISSUE TITLE
BUG: Preview and Render Glitches on Ubuntu 17.10 / Wayland

### ISSUE THREAD

**Issue by tushantin** [opentoonz/opentoonz#1808]
I wonder if this is due to Wayland (I wasn't able to confirm, because I've been having OS trouble, so can't risk it being screwed up again after this brand-new installation). 

I'm running Ubuntu 17.10, fresh installation, with some old softwares added back. It seems to default to the new Wayland, rather than X. I'm also running the latest Morevna edition. 

The reason I believe this may be because of Wayland is because Shutter, at least "initially", gave me a similar issue at first, but no longer seems to do it now. Even going full-screen on Youtube and exiting seems to briefly flash such an bug, which disappears instantly. 

However, this problem seems to manifest into every image in the sequence while rendering, and even shows inside OT's preview thing. 

![54 0001](https://user-images.githubusercontent.com/5314015/36262682-262bddd2-128e-11e8-9db1-e18d9dc1f11f.jpg)

**Comment by tushantin** [comment]
@morevnaproject Tagging you in here, in case you can help somehow, or guide me through the testing.

**Comment by artisteacher** [comment]
That is just like the render issues that both OS X and Linux had with the plastic tool #856 & #1615.

**Comment by tushantin** [comment]
@artisteacher Well, that's curious. I'll see if I get the same issue by deleting the transparent vectors...

**Comment by tushantin** [comment]
Nothing happened when I deleted the transparent vectors, but I can confirm it's definitely the plastic tool now. 

For the time being, does anybody know a workaround for converting the deformations of the plastic-tool to new vector layer sequence and such?

**Comment by tushantin** [comment]
Alright, update. I switched the drivers from  nvidia-340 to nvidia-384, and the issue seems to have resolved itself. Yay! 

Should I.... close this issue? Or are there any testings I should preferably do?

**Comment by artisteacher** [comment]
If updating the driver fixes the problem you can probably close. I'm glad that worked!
