### ISSUE TITLE
Extra periods in name stops image from loading

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1809]
In OS X, screenshots are named in the following format: “Screen Shot 2018-01-17 at 8.20.15 PM.png”. The placement of the 2 periods prevents OT from recognizing that the png is a png and so they will not load properly. Screenshots are visible in the browser but the icons do not display (just a white square with a zig-zag). After loading the screenshot, the file name displays as red in the scene cast and frame displays as missing in the Xsheet (no icon in the header, nothing visible in the viewer, and red text in the cell).

Screenshots that have been renamed without extra periods, display & load without issue. This is probably related to #1382 and is likely an issue for all OS with any files that have a similar name format (with extra periods).

**Comment by romeojulietthotel** [comment]
Yes, the TFilePath is the problem:
https://github.com/opentoonz/opentoonz/issues/1382#issuecomment-320560810

That comment summarizes the problem correctly. The solution is also proposed but I don't know if that's the correct solution.

**Comment by artisteacher** [comment]
Closing since this is a duplicate of #235.
