### ISSUE TITLE
Plastic tool not working

### ISSUE THREAD

**Issue by Drawsi** [opentoonz/opentoonz#1813]
After i create the mesh and the bones, i try animating the joints, but the drawing does not change it's original form.
Help.

**Comment by artisteacher** [comment]
What is your OS and version of OT? Are you in the correct mode to animate (ie. Animate not build skeleton)?

**Comment by Drawsi** [comment]
I use Windows, I have the latest version of OT and yes,I am on animate mode.

**Comment by artisteacher** [comment]
Does the level type or using plastic on a sub-Xsheet make any difference? Looking in the stage schematic, is the plastic column the parent?
![ca55f1af-5ae0-45be-86fc-d58379031283](https://user-images.githubusercontent.com/21159116/36386376-91104408-1563-11e8-8b3f-db0c84f6bcac.jpeg). If the Mesh level is not the parent, that would stop the plastic tool from working as expected. If that’s not the case, there could be a bug specific to your version of Windows & OT.

What is your version of Windows? By latest version of OT, do you mean 1.2 or the latest nightly build?

**Comment by Drawsi** [comment]
The mesh is the parent.
My OT build is 1.2 and my Windows 10 version is 1703.

**Comment by artisteacher** [comment]
Did the plastic tool work properly in 1.1.3? There have been a few fixes lately for the plastic tool. You could test out the latest nightly build to see if it makes a difference - it works perfectly in OS X.

Anyone else with Windows 10 seeing this issue?

**Comment by gab3d** [comment]
Working as expected here with all three level types.
I'm using Windows 10 notebook, geforce 640M, OT v1.2 (nightly, from last wednesday).

@Drawsi  please check to see if your mesh level is exposed the same amount of frames as the original level.

**Comment by Drawsi** [comment]
It is.

**Comment by RodneyBaker** [comment]
I think...

If you created your mesh while selecting only one or several cells in the xsheet the entire animation (animated mesh) will not deform your image.  Instead you want to make sure you select the column and then Create Mesh.

I have done something like this before where I created a mesh based on one frame and extended it downward only to discover it did not account for deformation of the other frames.

That's my guess.

**Comment by artisteacher** [comment]
If it’s still not working, maybe sharing a video screencapture would help someone identify the problem.

**Comment by Drawsi** [comment]
![screenshot 2](https://user-images.githubusercontent.com/36633561/36748438-8654fa92-1c00-11e8-9b11-5e209c98d7bf.png)

**Comment by RodneyBaker** [comment]
The problem would appear to be that none of your 'bones' overlap the plastic mesh.  Place one or more on top of the green area and that will allow the skeleton to move/deform the mesh.

**Comment by Drawsi** [comment]
ok

**Comment by Drawsi** [comment]
It works! Thank you!

**Comment by RodneyBaker** [comment]
A picture is worth a thousands it works!  :)
Glad that was the problem.

Recommend closing.

**Comment by Drawsi** [comment]
ok
