### ISSUE TITLE
Brush Lag

### ISSUE THREAD

**Issue by NoahFarron** [opentoonz/opentoonz#1816]
I'm experiencing lag when drawing. I don't know since which version this began to happen as I rarely draw with OpenToonz, it didn't used to happen, I remember it was smooth, but I get these jagged corners when drawing curves and circles since at least version 1.2 and all nightly builds since.

It appears to happen with a mouse, so I don't think it's a tablet issue.

_**Note**: I have Windows flicks disabled and double-click set to off under Wacom preferences. OpenToonz is the only app affected_

**OpenToonz Version:** 1.2 Nightly ([93ee582](https://github.com/opentoonz/opentoonz/commit/93ee58256600d1a7c957d65e92961ae5b2cbeee7))
**OS:** Windows 10 Home (1709)
**RAM:** 16GB
**GPU:** Nvidia GTX 1050 Ti (latest)
**Tablet Device:** Wacom Intuos Pro L
**Tablet Driver:** 6.3.27-2 (latest)

![tz_error](https://user-images.githubusercontent.com/36535462/36386959-763247a4-158f-11e8-9fac-bdd0f7c9c5a8.JPG)

**Comment by NoahFarron** [comment]
I tested versions 1.0.0 to 1.1.2, although they all have this issue to some degree, it becomes a LOT more noticeable from 1.1.3 and above.

**Comment by norrinra** [comment]
I have the same issue in Toonz Raster Level.. Raster level works great tho.

**Comment by manongjohn** [comment]
@NoahFarron OT may not be using the GPU of your NVidia card because it doesn't typically trigger usage automatically. Sometimes creating a 3d profile for it in the nvidia control panel helps that. See of that works?

**Comment by NoahFarron** [comment]
@manongjohn Thanks for the tip, I created a 3D profile for OpenToonz, setting it to max performance etc. I also tried the iGPU instead of Nvidia which had the same problem.

Here's what Task Manager looks like after drawing in Toonz for a bit.

![tm](https://user-images.githubusercontent.com/36535462/36982773-94690790-2088-11e8-9822-b0dfb241977d.JPG)

**Comment by manongjohn** [comment]
@NoahFarron What is the your Smooth setting on your brushes?  Although the 3D profile helped me immensely with the drawing lag in general, I still can't have these setting too high.  I actually keep mine at 5.

**Comment by NoahFarron** [comment]
@manongjohn Same, I have smooth set between 0-5.

**Comment by shun-iwasawa** [comment]
I found that when drawing with the toonz raster brush mouse positions are interpolated [here](https://github.com/opentoonz/opentoonz/blob/975eb1fa6fad3476ebbbafadf86814d4fea7dc05/toonz/sources/tnztools/brushtool.cpp#L750-L786). This function adds 8 extra samples to make smoother lines, regardless of the Smooth property of the brush tool.
This interpolation seems to be a main cause of the jagged corners.

**Comment by NoahFarron** [comment]
@shun-iwasawa Thanks for looking into this.
