### ISSUE TITLE
Level Strip InknPaint Navigator Has Delayed Movement

### ISSUE THREAD

**Issue by HaydenFarron** [opentoonz/opentoonz#1817]
When using the _StudioGhibli_ room set and selecting the _InknPaint_ room, the Level Strip window allows canvas navigation by clicking and dragging on the frame image. Since version 1.2 this appears to have a delayed movement for me, it feels like the canvas is 'floating' around and out of sync with my movement.

Even when I change direction, the canvas keeps moving in the direction I was previously moving it to.

![tz_lag2](https://user-images.githubusercontent.com/36535462/36388224-11d8917e-1593-11e8-9a51-fa6352e75173.gif)

**OpenToonz Version:** 1.2 Nightly (93ee582)
**OS:** Windows 10 Home (1709)
**RAM:** 16GB
**GPU:** Nvidia GTX 1050 Ti (latest)
**Tablet Device:** Wacom Intuos Pro L
**Tablet Driver:** 6.3.27-2 (latest)

**Comment by NoahFarron** [comment]
I reinstalled version 1.1.3, there is no issue with this version.

![tz_lag3](https://user-images.githubusercontent.com/36535462/36388924-62252dd4-1595-11e8-80b9-ccbd66337beb.gif)
