### ISSUE TITLE
"Visualize Vector as Raster" glitches (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1818]
Illusion of pixel displacement when drawing strokes.

![ezgif-1-0fc0747ba8](https://user-images.githubusercontent.com/25724133/36445502-25cd4b08-1687-11e8-8c64-9edefc2faa9a.gif)

The same happens when editing a drawing with any editing tool. If you click Undo, the drawing in this mode is not updated.

![ezgif-1-b9f10af73a](https://user-images.githubusercontent.com/25724133/36445541-4b9e1e5c-1687-11e8-85d7-de429cbf8d23.gif)

**Comment by HILGAS** [comment]
#HILGAS

**Comment by RodneyBaker** [comment]
@beeheemooth  Are you still experiencing this issue?

**Comment by RodneyBaker** [comment]
The first part of the issue appears to relate to the bounding box of the strokes that gets updated with each added new stroke.  The addition of the stroke updates the contents of the box and makes the display shift slightly.  Interestingly, I'm only seeing the movement right now when I add strokes higher or lower than those previously drawn.  When adding strokes to the right or left the shift does not occur.

**Try this:**  place two or more vector dots at the top left and bottom right of the space you will draw in and then draw only inside this area.  The displayed image should not shift.

I'm not quite following the second Undo issue but am likely just misunderstanding that part.
It very likely relates to the same bounding area.

**Comment by RodneyBaker** [comment]
I propose a fix to this would be an option to have the creation of vector levels proceed with the creation of a frame.  This would likely be defined by the camera/camera resolution..(edited)
I propose the specific fix for this would be an option to adjust the Raster Bounding Box to the camera and not the vector strokes. 

A larger and more complicated 'fix' that would also address flll issues in vector that will not fill due to lack of external vector boundary to catch the fill would be to have an option to create/place a vector rectangle at the canvas/camera boundary at the time a vector frame is created.

**Comment by melieconiek** [comment]
Some pasting operations and undoing a transformation does not trigger an update to the viewer when using 'Visualize Vector as Raster.' This is the second issue they're describing.

I create all of my projects at double the intended output resolution solely to deal with issues related to 'Visualize Vector as Raster.' This greatly reduces the 'creeping' issue when changing the size of the frame's bounding box and gives an accurate representation of stroke thickness at render time (vector stroke thickness is dependent on render resolution--another issue that makes rendering lower-res previews a pain.) It's easier to see what you're working on too, of course. ;)

This is just a suggestion to elevate the issue, not a fix. 'Visualize Vector as Raster' is essential when working with reasonably complex linework and using onionskin / shift and trace. It would be great to see this get some traction. :D

**Comment by RodneyBaker** [comment]
@melieconiek   Thanks for the insight.  It would be great to hear more of your approach to resolution related issues as there are several waiting in the wings.  I would think for instance that working at double resolution might require considerably more RAM but... a benefit there would be working with vectors that are resolution independent.

Concerning the second issue... I'm pretty sure we have some related reports on that.

**Comment by jeremybullock** [comment]
I'm not seeing the displacement right now, but #1818 just needs a m_tool->notifyImageChanged() at the end of the undo.

**Comment by shun-iwasawa** [comment]
fixed with #4870
