### ISSUE TITLE
Menus turn gray

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1820]
This happens time to time. Restart fixes it. 

![screen shot 2018-02-21 at 8 54 31 am](https://user-images.githubusercontent.com/30438394/36465173-075d5a7e-16e5-11e8-8fbd-7b4ffc1dfd42.jpg)

**Comment by artisteacher** [comment]
This looks like the mac autosave + tablet issue #618. It seems to be resolved in the last couple nightly builds.

**Comment by norrinra** [comment]
I m actually on latest nightly build. Maybe previous installations causing it. I ll make a clean install. Thank you.

I don't know if it's related to same thing or I should create a new issue for it but in latest nightly build, almost all my problems with the tablet fixed except one thing which is, after I alt tab back to opentoonz pressure is not working and brush is laggy until I left click once with a mouse to the canvas. After I left click once with mouse brush lags disappear and pressure starts working again. It's same with all levels.

**Comment by jpturcotte** [comment]
@norrinra I think you should open a new issue.

**Comment by RodneyBaker** [comment]
He just did.  We are in it.

**Comment by norrinra** [comment]
@jpturcotte @RodneyBaker I just opened as new issue. Thank you.

**Comment by artisteacher** [comment]
So I just ran into this in OS X again - so it's not completely fixed but is much less frequent than 1.2.

**Comment by norrinra** [comment]
Problem seems fixed since it s not happening anymore in the latest nightly. So I'm closing it.
