### ISSUE TITLE
Crash with Freehand Erase and Undo

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1821]
Reporting an odd bug here that I confirmed based on steps given by @beeheemooth.

Steps to repeat:

1. On the Raster Level, select the Eraser Tool and change its type to Freehand (this is done so that the next time the OT is started, the eraser is already in Freehand mode, and it does not have to be switched manually)
2. Restart OpenToonz.
3. Create a new raster level
4. Using MyPaint, draw something with a brush.
5. Choose Eraser Tool with HOTKEY (this is important!) and it should already be in Freehand mode.
6. Erase the fragment using this mode.
7. Undo this. The program crashes.

The crash will occur if we change step 7 to read.
7.  Go to WIndows>History (i.e. open the History Window)

So while we see this relates to Undo it doesn't specifically require using Undo keystrokes.

A workaround I observe is to insert a step between 4 and 5 where we create another (safe) event for OT to revert to via Undo.  Example:  Change Freehand to Normal and swipe at the screen to create an undo point.  No crash will occur when attempting the next undo or opening the History window.

Using Win 10 with latest nightly release as of 2/21/2018.

**Comment by shun-iwasawa** [comment]
Confirmed the crash. Thank you @RodneyBaker and @beeheemooth for reporting it !

**Comment by RodneyBaker** [comment]
That was fast. Thank you!
