### ISSUE TITLE
freehand eraser causes program to stop responding/brush lag

### ISSUE THREAD

**Issue by hanasongffs** [opentoonz/opentoonz#1825]
this is the only time I've experienced this program crashing/not responding but I'm almost done rough sketching for a major project so help would be nice. also brush lag has always been a major problem

**Comment by jpturcotte** [comment]
Is it related to #1821?

**Comment by RodneyBaker** [comment]
Hopefully @hanasongffs got the help needed.
If problem was related to #1821 then this should be resolved.
Closing pending additional information.
