### ISSUE TITLE
[Feature Request] normal map fx for layers

### ISSUE THREAD

**Issue by revast** [opentoonz/opentoonz#1828]
I am transferring this feature request over, it was originally posted at
https://blenderartists.org/forum/showthread.php?443266-OpenToonz-v1-2-released!

This youtube video shows a toonboom harmony example how to use map fx  together with aftereffects:
https://youtu.be/RCk6HIxsfYU

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by revast** [comment]
Ok, I will repost there.

**Comment by jpturcotte** [comment]
Thank you for your understanding!

Recommend close.
