### ISSUE TITLE
Add the option to export the animation to SVG format

### ISSUE THREAD

**Issue by Emasoft** [opentoonz/opentoonz#183]
For animations made using the vector layer, it would be convenient to add an option to export them in SVG format. It has the following advantages:
- It is an open standard for vector graphics
- OpenToonz can already import/export vector layers in SVG format
- You can edit the SVG vector layer in other software tools (Inkscape, Open Office, Illustrator, Affinity Designer, Autodesk Graphics, CACANi, etc.)
- You can easily create a playable animation from the SVG frames. Just paste each svg frame as a group in a svg file, and add this animate tag inside each group:

``` xml
<g id="frame60"  style="display:inline">
<animate
       attributeName="display"
       fill="freeze"
       repeatCount="indefinite"
       dur="1.3s"
       keyTimes="0;0.961;0.992;1"
       values="none;inline;none;none" />
...
<g id="frame60content" style="display:inline">
 (...paste the OpenToonz svg frame here...)
</g>
...
</g>
```
- You can preview the vector animation on every browser.

I've made an animation test, joining the exported SVG in Inkscape (I just pasted each frame exported from OpenToonz in SVG as a new inkscape layer, and saved. But a script can do this process much quicker). 

You can playback and download the resulting svg animation from here: 

http://imgh.us/navetta_test.svg

**Comment by blurymind** [comment]
The advantage of embedding the animation this way is smaller file size.
The disadvantage is lack of playback controls.

I would be interested to see a more complicated scene - stretched to a bigger resolution - how it compares to a video file. Does it take more cpu to run it?

CAVANI should be CACANI  btw.
You can import a vector layer to some of the software you listed, but you can not import vector animation. At least not to my knowledge.

**Comment by Emasoft** [comment]
I started working on this feature. If someone wants to help, let me know and I'll create a public fork for working on this feature and test it before submitting it to the main repo.

**Comment by Emasoft** [comment]
This is my fork for working on the SVG export: https://github.com/Emasoft/opentoonz

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by Emasoft** [comment]
Good to know. People finally saw the light. SVG has been the elephant in the room for decades. A perfect open standard vector animation format nobody care to use outside the web because of the baggage of CSS and javascript. But SVG animations do not require CSS or javascript at all. Since the beginning SVG had its own animation system, SMIL.

**Comment by Emasoft** [comment]
I’ve found a very efficient way to encode frame by frame animations in SVG.
Much better than the last code I posted above.






```xml

<svg version="1.1" baseProfile="tiny" id="svg-root"
  width="100%" height="100%" viewBox="0 0 160 160"
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">

<desc>
	SIMPLE FRAME BY FRAME ANIMATION
	Coded by Emasoft for Opentoonz (https://github.com/opentoonz/opentoonz)
	
	Example implementation of basic SVG frame-by-frame animation, for 
	educational purpouses. The frame based animation is easy to export.
	No javascript or CSS, just pure SVG.
	In this way the SVG format is used like an MPEG for vector animations.
	
	This animation has only 3 frames:
	Frame 01 = square
	Frame 02 = circle
	Frame 03 = triangle
	
	This file is divided in two sections:
	
	1) The Definitions (defs) : Here you need to put all frames and clipping paths.
	All frames require an unique id. For example: frame0001, frame0002, etc.
	All elements of a frame must be wrapped in a group with such id.
	Objects written here are not displayed until the animation cycle instances them.
	
	2) The Animation Scene (a group called "animation_scene") : Here you need to put
	the elements on the scene. First the background rectangle (with or without a
	clipping path), then the animated group of objects (called "animated_group").
	The animation element needs the following parameters:
	
	values : the id of the frames, with a leading # char and separated by a ; char.
	The frames must be named in the exact order you need them to be displayed.
	Also the first frame id must be indicated in the "use" element as the href
	(example: xlink:href="#frame0001" ).
	
	begin : the start time delay, in seconds (example: 0s).
	
	repeatCount : this should set on "indefinite" if you want a looping animation. 
	Otherwise on "0" if you want the animation to stop at the last frame. Any other
	number would be the number of repetitions of the entire sequence.
	
	dur : the duration in seconds of each frame. For example: "1.0" means 1 frame
	per second. For 60fps is "0.01667". For 24fps you have "0.04167" seconds.
	(just divide 1 for the number of frames, i.e. 1/60=0.0166666.., aprox: "0.01667").
	
	Please refer to Opentoonz repository on GitHub for any error/issue/question.
	Enjoy.
	
         Gist: https://gist.github.com/Emasoft/e86b227d7acd5b21794a5af1a50126d6

         Codepen:  https://codepen.io/Emasoft/pen/oNomrdr
	
	</desc>
	
	 <defs>

          <clipPath id="_clipPath_background">
            <rect width="512" height="512"/>
          </clipPath>

 <g id="frame0001" style="display:inline">
  <rect
    style="fill:#edd154;fill-opacity:1;stroke:#3c352d;stroke-width:2;stroke-opacity:1;"
    id="square"
    width="100"
    height="100"
    x="30"
    y="30">
  </rect>
	</g>
	
<g id="frame0002" style="display:inline">
  <path
    style="fill:#edd154;fill-opacity:1;stroke:#3c352d;stroke-width:2;stroke-opacity:1;"
    id="circle"
    d="m 125,80 a 45,45 0 1 1 -90,0 45,45 0 1 1 90,0 z">
  </path>
</g>
	
<g id="frame0003" style="display:inline">
  <path
    style="fill:#edd154;fill-opacity:1;stroke:#3c352d;stroke-width:2;stroke-opacity:1;"
    id="triangle"
    d="M 105,105 47,89 89,46 105,105 z">
  </path>
</g>

</defs>

<g id="animation_scene">
 <g id="background" clip-path="url(#_clipPath_background)" style="transform: scale(3); transform-origin: center;">
          <rect x="0" y="0" width="512" height="512" transform="matrix(1,0,0,1,0,0)" fill="rgb(90,145,240)"/>
</g>
<g id="animated_group">
  <use width="160" height="160" xlink:href="url(#frame0001)">
    <animate attributeName="xlink:href" 
      values="
			#frame0001;
			#frame0002;
			#frame0003" 
      begin="0s" repeatCount="indefinite" dur="0.5s"/>
  </use>
	</g>
</g>
</svg>
```

GIST 1 : [basic prototype 3 frames svg smil](https://gist.github.com/Emasoft/e86b227d7acd5b21794a5af1a50126d6)
GIST 2 : [basic walk cycle frame by frame svg smil](https://gist.github.com/Emasoft/662396a8a5ce7c883b6baaf94cbe0617)

CODEPEN 1 : [basic prototype 3 frames svg](https://codepen.io/Emasoft/pen/oNomrdr)
CODEPEN 2 : [basic walk cycle frame by frame in pure smil](https://codepen.io/Emasoft/pen/dyZaBgb)


 ![basic prototype of frame by frame animation in pure smil svg](https://gistcdn.githack.com/Emasoft/e86b227d7acd5b21794a5af1a50126d6/raw/7fa2bc8e71d178a6a0f417a702b8d57e46aad3e0/Basic%20PROTOTYPE%20for%20Frame-by-Frame%20vector%20animation.svg)

 ![walk cycle frame by frame animation in pure smil svg](https://gistcdn.githack.com/Emasoft/662396a8a5ce7c883b6baaf94cbe0617/raw/30ab581aedf1ef0c3dab8bd449cd2562c03cd082/Walk%20Cycle%20PROTOTYPE%20Frame-by-Frame%20animation.svg)

**Comment by RodneyBaker** [comment]
You've got some really interesting things going on here @Emasoft 
Very impressive.

**Comment by RodneyBaker** [comment]
Just adding a related update here...

With the new Export to OCA feature Opentoonz now has a new way to export vector levels to SVG format.
There are some limitations such as the output maintaining a vector strokes thickness.
See current nightly releases for more information.

The default output will convert vectors to raster so in order to get SVG output that option must be turned off:
![image](https://user-images.githubusercontent.com/2576432/181503677-3cec5bf3-ded7-4420-97e6-376a809029c3.png)

There is still an open bug report on the SVG filenaming issue related to sequences of SVG files.
Output from the OCA export must be renamed in order to import back into Opentoonz... which converts the SVG back into PLI files.

**Comment by RodneyBaker** [comment]
Random two frame animation created using SVG images exported with the new OCA exporter:

![gooba](https://user-images.githubusercontent.com/2576432/181785372-15ddae87-c4ef-4c06-a805-a0090ce7cc0d.svg)

**Comment by Emasoft** [comment]
@RodneyBaker 
Wowwowwow! You are a messiah! This is absolutely the greatest news ever!! Was it really exported from the vector layer? It's perfect! I mean, there are many issues, but just let me take from there and I will help fix them. Where is the exporter source code? Let me take a look at it! Things are going to be hot very soon in the animation scene... eheh! 🤩

**Comment by RodneyBaker** [comment]
We've still got a ways to go.
The OCA Exporter outputs SVGs to sequence of SVG files.
I manually placed them into your SVG template that then plays that frame data.

As for the code... @justburner is the developer that implemented the OCA Exporter... along with EXR and SVG output options.
That PR can be found here:  https://github.com/opentoonz/opentoonz/pull/4483

As for the many issues... I'll guess a large part of that is from me just pasting the data from the individual SVG files/frames into the final SVG container.  There are of course other issues such as what the SVG exporter currently supports; for instance variable stroke thickness is not supported.  As far as I know @justburner used QSVG to effect the export.  He can tell you more about the specifics of the process used... but try it for yourself with one of the latest nightly releases that include OCA export.

Aside:  I would have posted a longer animation but didn't feel like copy/pasting that many frames of data into the SVG target file.  ;)

**Comment by Emasoft** [comment]
@RodneyBaker 
You don't need to copy paste in the future. I've almost finished the python script to automatically generate the svg FBFSVG animation from any bunch of static svg files. Its pretty neat, because it even check existing vector elements and reuses them if they are not changed from the last frame. You'll see.
It should not be a problem to run an external python script from Opentoonz, right? I've made it as cross platform as it can be. I'll upload it on Github as soon as I fix the last couple of bugs.
You just focus on saving frames as svg static files. I'll take care of the rest. 😎

**Comment by RodneyBaker** [comment]
Sounds very promising.

As for running external python scripts from Opentoonz...  I'm sure it can be done but to date I don't think it's been done.
Note that the current OCA Exporter doesn't consider any keyframes in it's output so regular keyframed animation and more complex animation such as use of Plastic Tool will be ignored.

I know it isn't your goal but I do note that your same approach can generate SVG files that animate through raster images so... that also should be a consideration.  BUT... I know you have vector goals in mind here.

The current SVG output is in the form of:  levelname.0001.svg where the number is the frame number in the sequence.
The output consists of only actual drawings in the xsheet/timeline and not exposures.

I might be that your process could use the OCA file to gain frame duration data etc.
OCA files are in JSON format.

**Comment by Emasoft** [comment]
@RodneyBaker 
> Sounds very promising.
> Additional Info: Note that the current OCA Exporter doesn't consider any keyframes in it's output so regular keyframed animation and more complex animation such as use of Plastic Tool will be ignored.

Why? As long as the Plastic Tool can interpolate to a specific point in time, that of our frame, and can generate the corresponding distortion meshes, we can perfectly save those meshes in the svg frame and use the svg displacement map filter to match the exact distortion. Svg incorporates 'plastic' morphing aince the beginning, and it is animatable. 
Look at this example:
https://codepen.io/Emasoft/pen/abYVXmj?editors=1100

> I know it isn't your goal but I do note that your same approach can generate SVG files that animate through raster images so... that also should be a consideration. BUT... I know you have vector goals in mind here.

Not at all. I believe that some bitmaps are needed. For example I took care that my tool saved the embedded bitmaps used as background only once, in the first frame, and then just reusing them in the following ones if they do not change. I plan to let them just change position frame by frame, but there will be only one of each in memory, not one per frame. So those bitmaps are not too memory consuming.


> 
> The current SVG output is in the form of: levelname.0001.svg where the number is the frame number in the sequence. The output consists of only actual (vector) drawings in the xsheet/timeline and not exposures.
> 
> I might be that your process could use the OCA file to gain frame duration data etc. OCA files are in JSON format.

OCA seems great! We really do not need variable frame duration. Constant frame duration like movies is ok. But we can use the rich layer mixing and blending effects. SVG can reproduce almost all the OCA / After Effects blending modes:

https://github.com/RxLaboratory/DuIO/blob/01a41fc61e7a081f4fdeeb5b3b1544635d14e045/src-doc/docs/oca-blending-modes.md

> Aside: I might have mentioned that Opentoonz itself does not recognize the filenaming of sequential SVG files that it exports. There is an open bug report on that. I do understand that your process doesn't rely on Opentoonz ingesting the SVG files but mention that for completeness sake.

Opentoonz just need to export the frames and add a suffix the the frame number. Importing back the svg frames is useless.

> So, yes, we've still got a long way to go but every day we move a little closer to the goal.

Of course, but this is a great step forward!

**Comment by RodneyBaker** [comment]
The following is mostly unnecessary but I post it to lay a little groundwork for future discussion.
> Importing (back) the svg frames is useless.

We'll have to agree to disagree there.  And I do disagree.  ;)
The ability to do what I call 'round tripping' is essential in many ways.
I can think of many uses for importing SVG into Opentoonz.
Probably first and formost is simply to effect change/editing on the imagery being manipulated.
I am not a big fan of processes designed as one way streets although I do understand why developers implement features that way.  That can even be appropriate in some cases.  It's also quite necessary in many cases of feeding into proprietary systems.
Bottom line:  Unless specifically required, each 'node' in a system should have both input and output capability.  It will help if this is designed into the system from the beginning.  

But there is merit to the one way street...
My gut feel is that a short term and lasting solution for SVG files in Opentoonz is to have a dedicated (read only) SVG level type.
This would allow SVG data to be layered in with raster, toonz raster and toonz vector layers without the need for editing of the SVG data itself.  Other editing programs for SVG... of which there are many... could then be used in the pipeline as needed.  The next stage (and longer term solution) then would be of two approaches:  1) Improved conversion of the SVG data into PLI format (to take advantage of unique format features of the dedicated format, especially those not supported by SVG)  2) Direct editing of SVG file data (often better handled in a program specifically dedicated to working with SVG files) but an initial success might be to simply display the SVG data in an internal text editor allowing direct interaction and manipulation of the SVG.  GUI Tooling would then be built upon this as needed especially for those processes deemed untenable in or inappropriate for other applicaitons.  While I woudl prefer internal editor I'm not opposed to shelling out the data to a user defined text editor... such as notepad++ or even a browser based editor; Visual Code anybody?

Keep in mind that I still see the most useful editing tool for SVG files to be a text editor.  Python in it's own way is an extenstion of this as would be other programming languages.  Text editors may not be particularly useful for complex work (much like command line processesing versus working with a GUI) but certainly useful for inspection of specific elements, troubleshooting and direct manipulation.

Having said all this... I'm just happy to have a more direct way to expoert SVG files from Opentoonz via the new OCA export option.  I look forward to working with your python process as that is sure to be powerfully useful and a great time saver.

My apologies for the randomness of this post!

**Comment by Emasoft** [comment]
@RodneyBaker 
Not random at all! 
I'm not really against importing the fbfsvg format, but it is an hard task. Because in saving it, all the motion transforms and the spline motion paths are lost. You just have the interpolate result at time t of the frame to save in svg.
But the mpath are just splines, so converting those into bezier and back is not impossible (some control point need to be added each time). And meshes deformations conversion to polygons and displacement filters (and back) is not impossible either (but the resulting imported mesh will be different from the original). Also conversion of keypoints and keyframes, along with interpolation curves, is easily managed by SMIL. So with a lot of code with can create ad additional "section" of the fbfsvg where we can store all those elements, so that we can reproduce back most of the original opentoonz project.
The problem is naturally that it will take times. A good way to speed up things would be to add support for Python as a second script language for opentoonz. Toonzscript sucks anyway, and I guess that just a few python bindings would make development a lot faster. I have a lot of python code ready for handling svg, so it would be possible for me to write an importer/exporter myself. Just think about it. 😎

**Comment by RodneyBaker** [comment]
One can always dream although I don't see python being added as internal scripting any time soon.   
Maybe if we start now we can have it for v2.5 or v3.0  :)

An interim step would appear to proceed as you obvoiusly have... using external python processes to work with SVG.

I might thin about all this but my ability to implement is less than zero so we would need to find a champion or two (or ten) to take on the challenge.  The same thing can be said about most complex updates and additions to Opentoonz of course.

At any rate, I predict we'll have massive python support by v5.0.
We just have to live long enough to enjoy it! :)

**Comment by andeon** [comment]
I was looking for OCA and found this thread.

Since the PySide is now a part of QT it can be considered (not sure, I believe support has improved a lot from late 2018) - https://www.qt.io/qt-for-python

If OT implements support for this API, it allows not only scripts, but also plugins and many other third-party things. The Pyside6 use Qt6 APIs in Python applications.

Krita started around 2017 adopting python at a time when PyQT was more up to date- https://scripting.krita.org/lessons/introduction

**Comment by Emasoft** [comment]
@RodneyBaker Can you share the original svg frames exported by the OCA exporter? Those svg files you merged manually. So I can test my python script with them. If you have other animations exported with it, send them too. The more, the better.

**Comment by RodneyBaker** [comment]
Are you not using Opentoonz?
It's trivial to get a sequence of SVG images exported out via OCA Export.
The file format is of the 'filename.0001.svg' form.

I've attached a 24 frame ball bounce as initial example.
[ballbounce_oca.zip](https://github.com/opentoonz/opentoonz/files/9311417/ballbounce_oca.zip)

**Comment by Emasoft** [comment]
@RodneyBaker  Can you share something more complex? I'm going to reinstall Opentoonz once I finish the script. I'm working on many projects and at the moment my HD is low on space, so I keep things installed on a need-to basis.

**Comment by RodneyBaker** [comment]
Here's a step up in complexity of data with a character expressly created for this testing.**
The atached has a 24 frame sequence in both PNG and SVG format.
![quaticC](https://user-images.githubusercontent.com/2576432/184237756-7403ea3a-fbc1-4f76-b6c5-466f7d965ed2.gif)


**There currently are considerable shortfalls with regard to SVG export via OCA as it does not take into account any keyframing as such this sequence is a rendered output then converted to vector.  If this wasn't done all frames would simply take o
n the first  position of the first key encountered. 
[quaticK_oca.zip](https://github.com/opentoonz/opentoonz/files/9311992/quaticK_oca.zip)

**Comment by RodneyBaker** [comment]
That SVG sequence was pretty glitchy due to the conversion.
Here is another with slightly better output:
[quaticK2_oca.zip](https://github.com/opentoonz/opentoonz/files/9312403/quaticK2_oca.zip)

**Comment by Emasoft** [comment]
good

**Comment by Emasoft** [comment]
@RodneyBaker 
This is the file generated by my python script:  

!()[https://gistcdn.githack.com/Emasoft/4a7f3d46ff4780663cd19c762ad4db54/raw/9ad4ec36de6c6837abadc47b3e0939eb93ae59c8/quaticK2_oca.fbf.svg]

Since the oca exported files are missing both the width/height and the viewBox attributes, my script defaults to 1024x768. I hope the exporter can add those in the future.

**Comment by RodneyBaker** [comment]
Looking good!

Yes, SVG was just a feature added to the OCA Export that wasn't originally planned.
@justburner saw the opportunity and added it.  :)

In time the rough spots will all be smooth.

**Comment by RodneyBaker** [comment]
Transferring this request to Opentoonz-docs repo for general roadmapping purposes...
