### ISSUE TITLE
new issue "No reflection"

### ISSUE THREAD

**Issue by kazkix** [opentoonz/opentoonz#1831]
I dropped new photos,however the left item is no reflection.
what do I should do ?
[3](https://user-images.githubusercontent.com/25191321/36653405-53552242-1af8-11e8-8456-596b40dadfe1.PNG)

**Comment by artisteacher** [comment]
What do you mean by reflection? Is part of an image sequence not exposed in the Xsheet? Is there an animated gif that's only showing the first frame?

**Comment by kazkix** [comment]
I called "no reflection" that it does not appear on "camera".
I do not know how I am doing a beginner, so I screenshot Xsheet.![4](https://user-images.githubusercontent.com/25191321/36671749-3800d4da-1b40-11e8-8a75-2448da774216.PNG)

**Comment by artisteacher** [comment]
Oh, ok. This is a known bug #1674. In the comments for that issue are some links to builds that resolve the issue.

**Comment by manongjohn** [comment]
@kazkix Issue #1674 was fixed and closed.  Can you download the latest nightly and confirm it fixes this issue? If so, please close.  If not, we'll probably need to get more details on what you are seeing.

**Comment by jpturcotte** [comment]
Recommend closing.
