### ISSUE TITLE
Can't import wav files exported from Adobe Audition CC

### ISSUE THREAD

**Issue by artsyhugh** [opentoonz/opentoonz#1839]
For some reason I can't import wav files exported from Adobe Audition CC properly. The audio will only be exposed for 1 frame and cannot be played back. My workaround is to use Format Factory to convert it again, or to export it as aif instead, but still I'd like to know what's the deal here. Thanks in advance.

**Comment by RodneyBaker** [comment]
16bit wav, aiff, and mp3 files should all be compatible with OT.
Although, some of those may require FFMPEG so if you don't have that connected that might reduce your options.

Here's a topic that goes into some detail:

https://groups.google.com/forum/#!msg/opentoonz_en/hznzQQUxcd0/CN1XFKP1DwAJ

**Comment by artsyhugh** [comment]
Weird. Now that I've added ffmpeg I can import it. I have no idea if I accidentally did something else that helped but apparently I can import 32 bit wav files too. Although the audio quality is reduced somewhat, it seems to be a good start. Anyway, thanks for sharing the link but I can't access groups.google.com for some reason.

**Comment by artsyhugh** [comment]
Nope. That was just a fluke. Can't import 32 bit wav now.

**Comment by artisteacher** [comment]
Google groups can be a little fussy if you aren't signed in to your google account (specifically when you have been signed in from that computer/browser before). Try accessing the page from a different browser, or just sign in to your google account.

**Comment by RodneyBaker** [comment]
>  Can't import 32 bit wav 

I'm not sure we ever could.
The documentation I see states 16bit Wav.
If that is the case then you'd have to use a program like Audacity to convert from 32bit to 16bit.

**Comment by artsyhugh** [comment]
I know I know. It's just that I couldn't even export 16b wav at first even when I intentionally configure the file exportation as such in Audition as opposed to when I simply convert it without thought with Format Factory. It seems okay now.
