### ISSUE TITLE
COURAGE THE COWARDLY DOG question

### ISSUE THREAD

**Issue by DemonRem** [opentoonz/opentoonz#1852]
COURAGE THE COWARDLY DOG

character's i can draw with this i mean all the tools that they actually draw COURAGE THE COWARDLY DOG
characters?

**Comment by Orphanlast** [comment]
yes you can draw and animate any character you want with tools comparable to toon boom

**Comment by adamearle** [comment]
That's funny I had a small exchange with the director from that show the other day. I wonder what they did there animation in?

**Comment by Orphanlast** [comment]
But the point is, regardless, Opentoonz can animate anything.

**Comment by RodneyBaker** [comment]
Recommend close pending inclusion of a 'Make Courage the Cowardly Dog' button.

**Comment by shun-iwasawa** [comment]
![courage](https://user-images.githubusercontent.com/17974955/37442488-021fbd4c-284a-11e8-895f-eb77876b7ef1.gif)

**Comment by RodneyBaker** [comment]
Nice!

**Comment by Orphanlast** [comment]
Lol, awesome!
