### ISSUE TITLE
Problems with audio

### ISSUE THREAD

**Issue by VictorGomez1** [opentoonz/opentoonz#1855]
Hello everyone, I have help, I have a problem with inserting the audio, I see that the .wav file is taken care of. Only what I get is an audio frame but it is not the audio that I have inserted an image here

![es](https://user-images.githubusercontent.com/37191786/37171561-e14cac0e-22d3-11e8-87b3-1e8f8cc981c2.png)

I would eternally appreciate your help :)

**Comment by artisteacher** [comment]
That happens to me if I try to load a 32bit audio file. I believe only 16bit files are supported.

**Comment by shun-iwasawa** [comment]
You are right. According to [here](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/sound/wav/tsio_wav.cpp#L257-L289) in the source code seems to accept WAV with only 8. 16 and 24bit per sample.
