### ISSUE TITLE
Crash with zoom (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1860]
Is such a huge zoom required for viewing?

![ezgif-3-e58f453ebf](https://user-images.githubusercontent.com/25724133/37236308-ed09e0e8-240e-11e8-8c81-a995c2c0ef23.gif)

Here I wanted to see if the Higgs bosons were correctly rendered on my drawing, but for some reason OpenToonz crashed ;)

![ezgif-3-ce720c7df4](https://user-images.githubusercontent.com/25724133/37236331-1a813256-240f-11e8-9e5f-4ff5c876b56d.gif)

**Comment by RodneyBaker** [comment]
Interesting problem.

What would be the recommendation for when enough zoom is enough (outside of actually finding the Higgs bosson of course!).

I like the idea of near-infinite canvases but generally they go so far and then continue via a new layer.

Another option (which I don't think I would prefer) would be to zoom in to a point but then pick up (loop( back at the original view.  

In considering this in light of other interests I'd say that perhaps it might be set in preferences where it would be like pressing play and having a variety of options for when the 'end' is reached (replay, ping pong, reverse, etc.).

There is also the matter of raster vs vector which I must assume vector would be expected to require more zoom than raster.
