### ISSUE TITLE
Brushes behave inconsistently on wrong level type

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1871]
It would be helpful to have a consistent, more context sensitive behavior when accidentally using the wrong brush type for a level. The existing behaviors are clearly very confusing for new users.

On a Vector level:
- raster brushes make a dot (which disappears when making a new stroke & displays the actual stroke when the style is changed to a vector style)

On a Toonz Raster level:
- vector brushes are ignored and the brush works normally
- raster brushes make a dot

On a Raster level:
- vector brushes are ignored and the brush works normally (as if the "no brush" style was selected on the raster tab)

I understand that there are some reasons around reusing styles where a completely context sensitive style editor would be inconvenient. However, there could still be a warning notification when trying to set a new raster style on a vector level (& etc.). The warning dialog could be closed and ignored, and the styles would still be accessible but at least the user would understand that they won't work as expected.

In terms of the behavior of the brush itself when the wrong style type is set for a level, I prefer the behavior of the vector styles - where they are ignored if used on the wrong level and the level's default setting for the brush is used instead.

**Comment by jpturcotte** [comment]
Great analysis, with which I completely agree. It causes an inordinate amount of confusion for newcomers.

**Comment by RodneyBaker** [comment]
A slight correct to @artisteacher 's breakdown:

> On a Toonz Raster level:
> vector brushes are ignored and the brush works normally

> > raster brushes make a dot

Standard raster brushes work fine on Toonz Raster levels.
It is the MyPaint Raster brushes that don't work and present a dot on the canvas.

**Comment by artisteacher** [comment]
Yes, the original raster brush (now called “no brush”) works without issue on the toonz raster and vector levels. So it’s really the mypaint brushes that have draw issues when used on the wrong level type. Still, at minimum, the mypaint brush stules should really be ignored on vector and toonz raster levels & the default vector/toonz raster brush stroke should be used instead.

**Comment by artisteacher** [comment]
Now that many of the mypaint brushes work on toonz raster levels, it seems like a good time to revisit this topic. I still think a consistent approach when an unusable style is applied would be beneficial.

On raster levels:
- vector brushes are ignored & use the default "no brush" raster style

On toonz raster levels:
- mypaint brushes draw beautifully except that blending or erasing brushes do nothing
- vector specific brushes do nothing

On vector levels:
- mypaint brushes are ignored but a stroke still appears to draw. After releasing the brush, the stroke "disappears" until the style is changed from a mypaint brush style

 Is it better for a style to be completely ignored when it is for the wrong level type, or is it better for the default brush for the level to be used instead?

**Comment by artisteacher** [comment]
I agree that brush organization as a whole could use some serious consideration - especially the mypaint brushes. I suppose if the organization itself makes the appropriate level type more obvious, the current inconsistencies would matter less. 

I wonder if having color cues in the style editor and possibly the level palette would be helpful? Perhaps something like this or a colored border or even changing the background color?
![a8aad1b2-95a5-46d3-a4d3-e9e4895ca81b](https://user-images.githubusercontent.com/21159116/45526474-37e45d80-b7a5-11e8-950c-a3c7ebc84d47.png)
![1f5758ac-6392-489c-b185-f5578e3f5a5d](https://user-images.githubusercontent.com/21159116/45526475-37e45d80-b7a5-11e8-939b-0f4767b16cdb.png)

Regarding raster levels, having brush categories that can be enabled/disabled, like the 3 vector options would be helpful. If all of the blending & erasing brushes were in a separate category (or 2), the categories themselves could have an * or color coding or etc. to denote that these brushes only work on raster levels. If/when Toonz Rasters gain those capabilities, the * or etc. could be removed. I’d also love to have a category of favorite raster brushes or of frequently or recently used brushes too. There are so many brushes that it is hard to keep track. 

A different approach (specific to the wrong brush - not organization), could be to leave any behaviors as is but add a visual cue. Perhaps a red x (or 🚫) could display on top of the icons in the level palette and/or active style icon in the style editor when the wrong level type is active. That way users would see  that something is wrong before even trying to use the brush/style but it wouldn’t impact shared palettes or etc. It probably wouldn’t stop someone from trying to use the wrong brush, but it might end up less surprising when the stroke doesn’t work or look as intended.

**Comment by artisteacher** [comment]
Also there’s not necessarily a rush, but if blending/erasing brushes won’t be added to Toonz Raster levels before the next release, and a more distant addition, then having some sort of indicator that they won’t work is important - even if it adds another step to remove later on. If there is a temporary indicator, it would obviously be best to be easily added and removed on the coding side.
