### ISSUE TITLE
Animate Tool - lock scale does not work

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1872]
When using the Animate Tool set to "Scale", locking the horizontal or vertical size does not seem to have any impact.
![scalelock](https://user-images.githubusercontent.com/21159116/37481971-6f970074-2859-11e8-8ca0-c657bd4e901c.gif)

**Comment by shun-iwasawa** [comment]
For now the horizontal and vertical size lock buttons have effect on +ctrl dragging, which is for adjusting H and V scale separately.
Dragging without ctrl key will change the global scale.
Also all lock buttons do not protect values from being edited directly in the Tool Option bar.

**Comment by artisteacher** [comment]
Oh, I didn’t know about the shortcut. Thanks!

Still, I think the behavior of locking in the other animate modes is more expected. Dragging in the viewer doesn’t need a modifier when position or skew is locked - though I guess that’s because they don’t have a global value.
