### ISSUE TITLE
Crash with incorrectly named text file (extension .GIF)  FFMPEG

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1876]
I think we almost have this one squashed but I ran into this odd one.

Attached is a text file with the word 'empty' in it.
Place this on your desktop or in a folder and OpenToonz will ignore it.
Rename it to filename.gif (or any filename with .gif extension) and it will cause OT to crash.

The primary way I tested was via xsheet Right Click > Load Level
While browsing move to the directory where the bad file resides.
Entering a directory where the file resides may not cause immediate crash but
Scroll down until
OpenToonz 'sees' the file in the listing.
Crash should occur at this point without every selecting a file.

You should not need the attached text file as any text file with .gif extension should suffice.
The file that did this on my system was apparently html file accidentally given the .gif extension.

Not sure if this is strictly FFMPEG related but it stands to reason that earlier fixes might have got at one part of the problem but there are a few lingering problems.

Confrimed with latest OTX (17 March) and 14 March official releases.

[crasherNot.txt](https://github.com/opentoonz/opentoonz/files/1823525/crasherNot.txt)

**Comment by RodneyBaker** [comment]
Tested also with the majority of other image formats and most passed the test.  One other 

.MP4 extension also fails
.webm fails (I expected it to as I've not had much success using .webm format)

The following pass (no crash) If I don't explain further we might have an undocumented feature here (need to investigate!):

.BMP good
.PNG good
.TGA good
.spritesheet good (I expected this to fail but perhaps it passes because OT is not expecting that format to be one of a sequence of images?)  I think that is why it gets a pass.
.MP3  good (I expected it to crash.. perhaps again related to sequences)
.WAV good (same as .MP3)

**Comment by artisteacher** [comment]
It looks like @shun-iwasawa's symlink fix also resolves this crash for gif, mp4, and webm files. I am getting a crash if I rename the text file to a jpeg.

**Comment by konero** [comment]
Curious, why are you renaming a txt file gif?

**Comment by RodneyBaker** [comment]
Renaming was the easiest way to reproduce and demonstrate the problem.

**Comment by artisteacher** [comment]
I've found that students will occasionally rename files to a different type because they think that renaming will convert the file type.

**Comment by RodneyBaker** [comment]
Closing this as the problem no longer occurs in 1.2.1 and more current releases.
If anyone confirms a related issue I'll gladly reopen.

Thanks!
