### ISSUE TITLE
display misbehavior while changing rooms

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#1880]
i have a combo viewer separated window in my bigger monitor, while leaving the opentoonz main window in another monitor

when i change rooms 1 or 3 times, the display starts malfunctioning and i cannot see what happens in the scene
![2018-03-19_23-21-31](https://user-images.githubusercontent.com/36406840/37632282-44ecc838-2bcc-11e8-83da-8ee84dcc79df.png)
![2018-03-19_23-15-44](https://user-images.githubusercontent.com/36406840/37632283-450d7baa-2bcc-11e8-9ad1-17b1446b34b4.png)

when i use the hand tool to move around it flashes some colours (grey, white and light blue) but does not show anything nor i could draw anything
this also happens with the "viewer" window

but if i click and drag to resize the window (either window tipe) , it turns back to normal
![2018-03-19_23-27-38](https://user-images.githubusercontent.com/36406840/37632473-1a92d0ae-2bcd-11e8-9f3f-bca19238dbce.gif)

**Comment by artisteacher** [comment]
It looks like the viewer gets really, really zoomed in. I can duplicate this with a single display:

1. Set the OpenToonz window open to take up the left side of the screen
2. Add an additional viewer to take up the right side of the screen
3. Change rooms
![screen shot 2018-03-20 at 2 04 38 pm](https://user-images.githubusercontent.com/21159116/37674221-b63d477a-2c48-11e8-8c8b-d3dcd042935e.png)
When this happens, zoom in/out and pan are unusable and fit to window does not work properly.

**Comment by jeremybullock** [comment]
I can't duplicate this.  Is this still an issue?

**Comment by artisteacher** [comment]
I can't duplicate it anymore either. I think it's fixed.

**Comment by RodneyBaker** [comment]
Closing.
@age3rcm If you are still experiencing this issue please let us know and we will give it another look.
Thanks!
