### ISSUE TITLE
Artifacts for AppVeyor Windows builds missing dills

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1882]
When trying to test PRs using artifacts from AppVeyor Windows builds, the following dlls are reported as missing when trying to start OT:

libiconv-2.dll
libintl-8.dll
libjson-c-2.dll
libmypaint-1-4-0.dll

**Comment by shun-iwasawa** [comment]
Confirmed. Thank you for reporting the problem!
