### ISSUE TITLE
Help. Opentoonz doesn't crash anymore.

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1883]
Using latest nightly, 10 hours of heavy animating. Not a single crash occurred. Guess I was addicted to adrenaline rush of sudden crashes. My life is empty now.  

ps: Thank you guys. Most stable version as far as I m concerned.

**Comment by jpturcotte** [comment]
Recommend close so that the secret does not get out!

**Comment by gab3d** [comment]
I detect a Courage the Cowardly Dog meme coming to us briefly. :)
