### ISSUE TITLE
memorySyze & magic number 1048576

### ISSUE THREAD

**Issue by jpturcotte** [opentoonz/opentoonz#1884]
While investigating History/Undo issues with @RodneyBaker, he found what appears to be a typo in "memorySyze", a local variable present in "tundo" and "preferences". On a second look, there is also five occurrences of the magic number 1048576, four of them having a decimal while it seems to deal with integers. I have no idea what it is all about, but I could easily refactor this if it is not critical. Also, should it have a decimal or even be a constant at all? Thank you!
```
toonz\sources\common\tcache\timagecache.cpp(1913):            std::to_string((int)chunkRequested / 1048576.0) + " MB\n";
toonz\sources\common\tcache\timagecache.cpp(1934):            std::to_string((int)cmsize / 1048576.0) + " MB\n";
toonz\sources\common\tcache\timagecache.cpp(1936):            std::to_string((int)cdsize / 1048576.0) + " MB\n";
toonz\sources\common\tcache\timagecache.cpp(1938):            std::to_string((int)udsize / 1048576.0) + " MB\n";
toonz\sources\common\tcore\tundo.cpp(296):  m_imp->m_undoMemorySize = 1048576 * memorySyze;
```

**Comment by shun-iwasawa** [comment]
1048576 = 1024 x 1024 and it seems to be used in expression for conversion from bytes to megabytes.
