### ISSUE TITLE
"Edit All" manipulator becomes too small on high-dpi monitor

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1886]
According to @artisteacher ' s [comment](https://github.com/opentoonz/opentoonz/pull/1870#issuecomment-375503714) :

> On a low res screen, the size of the manipulator is just fine. On a high res screen (at least in OS X), the manipulator is extremely small - ie. barely larger than the tool buttons. This makes it hard to see on darker backgrounds & more challenging to manipulate.

<img src="https://user-images.githubusercontent.com/21159116/37805502-24f8cf76-2e11-11e8-8f1b-373a7f7d3fa8.png" width=107>

**Comment by DarrenTAnims** [comment]
I agree. On mine it's quite small and the amount you move your cursor is so small and the distance it moves is so large that it's sometimes hard to use it. But when it works, it's really good. I prefer to use it than the individual options now. But it'd be good to either have a larger version or to be able to click further away from the UI and still use it.

**Comment by artisteacher** [comment]
It's significantly larger on a normal screen - almost the height of 3 tool buttons! At this size, the manipulator is a lot easier to use.
![screen shot 2018-03-23 at 2 40 34 pm](https://user-images.githubusercontent.com/21159116/37847739-3aa09574-2ea8-11e8-82b7-e2ec9df63519.png)

Beyond needing a useable size across all screen types, it would be great if this was either the default mode, or if the Animate tool could remember the last used mode upon reopening.

**Comment by DarrenTAnims** [comment]
Yes, the total tool size about that size on my screen, but the hit points are the actual small squares/circle/line, which isn't very large and it's the hit points that I think would benefit from having a larger area to select them.

**Comment by turtletooth** [comment]
I can confirm this on a surface pro.

**Comment by artisteacher** [comment]
@turtletooth, do you have any of the high dpi issues from #1216? The loading screen is resolved, but the others are still an issue.
