### ISSUE TITLE
Error install nightly builds 

### ISSUE THREAD

**Issue by Toybulldog** [opentoonz/opentoonz#1887]
Hello ,
I just tried to install the current Nightly Build (opentoonz_nightlies-nightly_d6e79905560895fa2a44ca94a603ed2fee97b109)  and get the following error message .
![error ot23-3-18](https://user-images.githubusercontent.com/11164330/37815671-18f30638-2e70-11e8-8e50-ba71103e0023.png)
![2-error ot23-3-18](https://user-images.githubusercontent.com/11164330/37815676-1dc2930e-2e70-11e8-856d-8be73c7b0f06.png)

My system is Linux Mint 18.3

**Comment by shun-iwasawa** [comment]
The error claims that the function `setWindowFlag()` is not declared.
This function was introduced from Qt 5.9.

It seems that an old settings using Qt 5.6 remains in your makefile. Deleting the cache (CMakeCache.txt) and run cmake again may solve the problem.

**Comment by Toybulldog** [comment]
I've tried this with (CMakeCache.txt) and came to the conclusion that I have no QT 5.9
![qt-5](https://user-images.githubusercontent.com/11164330/37861516-bebb2854-2f3b-11e8-883a-21392e9fd404.png)
Thanks for the effort

**Comment by jpturcotte** [comment]
@Toybulldog Have you tried installing Qt 5.9? Type this in a terminal:
```
wget https://download.qt.io/official_releases/qt/5.9/5.9.4/qt-opensource-linux-x64-5.9.4.run
chmod +x qt-opensource-linux-x64-5.9.4.run
./qt-opensource-linux-x64-5.9.4.run
```

**Comment by Toybulldog** [comment]
Hello,
a heartfelt thank you .
I have a few things to do privately.I have to take care of other things
But thanks for the tip

lg peter

**Comment by jpturcotte** [comment]
Can this issue be closed, then?

**Comment by RodneyBaker** [comment]
Recommend tagging as a Linux issue and review for potential closure.

**Comment by Toybulldog** [comment]
The issue has settled with the new linux Linux Mint 19 Cinnamon. Sorry for the late info.
I think it can be closed
