### ISSUE TITLE
Fill tool not working

### ISSUE THREAD

**Issue by PastorBrianSmith** [opentoonz/opentoonz#1891]
I have downloaded the appimage of opentoonz 1.2.0.2 and the fill tool is not working. I have tried it on a raster level, toonz vector and toonz raster levels. I have tried to use mode: Lines & area, Lines and Areas and no fill. I also tried the appimage 1.2.0.1 and 1.1.3.9 and the fill tool does not work.

I am running Ubuntu 17.10 64 bit.

**Comment by artisteacher** [comment]
The fill tool only works on Toonz Raster and Vector levels. Make sure you are trying to fill a closed shape when on a Vector level. Also, some of the vector styles are only for strokes, so be careful of the style type.

**Comment by PastorBrianSmith** [comment]
Great. Thanks. I never knew that and have found the style that works.
