### ISSUE TITLE
Filled Areas are always under other stroke Lines?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#1893]
On vector levels, filled areas can´t seem to occlude other stroke lines in the same level.
No matter if the filled area´s stroke line is sent to the top.

I understand this is the standard behaviour in OT, still, I wonder if there could be a stroke line property by which a stroke´s fill would ignore other lines in the same cell (i.e: don´t stop at that lines, and occlude other shapes' lines and fills, if the shape to be filled is in front of those other shapes).

I guess now that vector line animation is about to be possible, this could be asked by users doing motion graphics work.

p.s. I realize I don't know where this property would be placed, as currently there is no properties panel for the selected curves/columns/nodes.

**Comment by shun-iwasawa** [comment]
I think you can use "grouping" vectors to put shapes overlapping instead of intersecting each other. 
Please refer to [the manual](http://opentoonz.readthedocs.io/en/latest/drawing_animation_levels.html#grouping-and-ungrouping-vectors) for details.

**Comment by gab3d** [comment]
woow! great!
I didn't know the groups could serve that purpose.
That solves this issue.

Thank you!
