### ISSUE TITLE
Loss of parts of the drawing converting from vector to Toonz Raster

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#1895]
Compound shapes of vector drawings filled with color when copy-paste to Toonz Raster do not display details that are behind transparent closed areas.
![ezgif-2-7ad8c0a688](https://user-images.githubusercontent.com/25724133/38114710-132f1df8-33b2-11e8-8d15-f2a9e7b75d89.gif)

**Comment by artisteacher** [comment]
I'm only having this issue with overlapping shapes made with the geometric tool. This happens with both filled and unfilled shapes.

**Comment by beeheemooth** [comment]
It is strange that this topic has not been closed yet. It is even stranger that the conversion behavior I described now seems completely logical to me.  %)

**Comment by artisteacher** [comment]
I still don't see the logic...
