### ISSUE TITLE
immediate crash when using surface pen

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#1896]
on the current Version OT crashes on the first stroke, when using the the Surface pen on my Surface 3 tablet. It does not Crash when using the mouse.

**Comment by jpturcotte** [comment]
Can you tell us if the same happens with the latest nightly, please? https://github.com/opentoonz/opentoonz/releases/tag/nightly (Disregard the date.)

**Comment by bobbybutterfly** [comment]
ist the latest nightly. i downloaded and installed it an hour ago

**Comment by artisteacher** [comment]
Sharing a crash report could be helpful.

Does having pressure unchecked in the tool option bar (for the brush) make any difference? Does this happen with all level types?

**Comment by jpturcotte** [comment]
Download the correct drivers from [here](https://support.microsoft.com/en-ie/help/4023482/surface-download-drivers-and-firmware-for-surface), and make sure to install the optional WinTab drivers.

**Comment by bobbybutterfly** [comment]
@jpturcotte installed newest Firmware and wintab Driver - no Change

ist open toonz related, my other drawing Software works properly

**Comment by jpturcotte** [comment]
Was it working on older versions?

**Comment by bobbybutterfly** [comment]
@jpturcotte 
yes

**Comment by jpturcotte** [comment]
Would you be ready to help us track down the bug? If you could find the PR (code modification) that introduced the problem, it would be easier to find a solution. Start from the last known working version, and tell us from which nightly the bug appeared: https://github.com/opentoonz/opentoonz_nightlies/releases.

**Comment by bobbybutterfly** [comment]
ok, i went back several nightly Releases to 13 march 10.17.49. still the pen moves the canvas while drawing a line.
but the Crash is only on the newest release

**Comment by jpturcotte** [comment]
Thank you for taking the time to test this! @turtletooth is the only one I know who has a Surface. Maybe he can tell us if he has any problems with the latest nightly?

**Comment by turtletooth** [comment]
Just tested the latest nightly on a 2017 Surface Pro.  No crash.  Sorry I can't duplicate.

**Comment by bobbybutterfly** [comment]
i uninstalled OT, deleted the OT stuff Folder and the env.variables.
now the drawing tool works properly but i completely lost the touch functionality:/

**Comment by bobbybutterfly** [comment]
@turtletooth 
Ok touch works now, but pen tip draws a line 
and moves the canvas at the same time like before

**Comment by manongjohn** [comment]
Is this still an issue? Now that OT has Windows Ink support preference setting, if you are still having this problem, then try turning that on in OT's Tablet Settings and see if the problem still exists.

**Comment by RodneyBaker** [comment]
Closing as the original issue of crashing has been resolved.
