### ISSUE TITLE
bug related to huion tablet on linux

### ISSUE THREAD

**Issue by wofogen** [opentoonz/opentoonz#1897]
Hi, after compiling the last build i'm having problem with the toonz raster brush updating the image.

![bug](https://user-images.githubusercontent.com/33259911/38147247-cfd15b36-3427-11e8-8b91-878894d7981a.gif)

I made some investigation and i'm conviced it happens because a old bug related with huion behavior on linux. Basically the program dont recognize the act of taking off the pen, so it get stuck until i click again, use the mouse or preview the animation.

My OS: Manjaro, kernel 4.9.53-1
Tablet: Huion h610 pro, Drive: libwacom 0.28-2
Opentoonz version: 1.2.0 (built Mar 30 2018)

I messed here with the drives and configs but no luck, so if anyone have any idea give a call ^^

**Comment by shun-iwasawa** [comment]
Thank you for the report. It must be related to the recent update for brush enhancement. In the fix I changed the viewer to be refreshed only at a small region around the brush tip. I'll look into this.
