### ISSUE TITLE
Crash when Zooming In with hotkeys

### ISSUE THREAD

**Issue by xavzz** [opentoonz/opentoonz#1898]
Hello everyone!
My zoom in keyboard combination is Cmd+1 (zoom out Cmd+2). Opentoonz crashes, quite often, when I am zooming in. It does not happen with zooming out.
Opentoonz 1.2, mac os, 10.12.6

**Comment by artisteacher** [comment]
Did you have this problem before 1.2? If you share a crash report, that could be helpful.

With 10.11.6, I'm not getting a crash on zooming in with a shortcut, but the OT does hang. I'm not having any issues zooming in/out if I use the Zoom tool (shift-space) or zoom directly with the trackpad. I'm using the latest nightly build. I'll take a look at this with 10.13.2 tonight and see if there is any difference there.

**Comment by artisteacher** [comment]
With 10.12.3, I can zoom in successfully but if I try to zoom in repeatedly & rapidly, then OT hangs. I may be getting better results due to the gpu. The computer with 10.11.6 is fairly old & lags often. I wonder if this is related to #1860.

@xavzz, try using [the latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly) and see if there is any difference.

**Comment by xavzz** [comment]
@artisteacher, I tried to zoom using Shift+Space and there hasn't been a crash. I think Opentoonz does not approve my choice for a shortcut.
(I am using 10.12.6, you must have misread the version)
Thank you for the feedback

**Comment by artisteacher** [comment]
Interesting. No, I have access to a computer that runs 10.11.6 and one that runs 10.12.

**Comment by xavzz** [comment]
@artisteacher Sorry for bothering again. I wonder if my mac suits the program at all. I have started experiencing slowish painting and erasing after having animated for an hour. According to smcFanControl the temperature sometimes gets 70C. Is it okay? When I switch to something else, not closing it, the temp drops to 45 again. My specs are i5, 2,6 GHz, 8 ГБ, Intel Iris 1536 МБ.

**Comment by artisteacher** [comment]
@xavzz, no problem. I usually only have shorter periods of time to draw/animate, so I'm not sure if that is normal or not.  Macs do tend to run hot when they are doing heavy processing. 

If you return to the same scene later on, is it sluggish from the start? What level type are you using when this occurs?

**Comment by xavzz** [comment]
@artisteacher When I return to a scene, it draws smoothly again for a while. I draw on Raster levels as they are supposed to require less memory. 
I am sorry again for attacking you with questions (and for my clumsy English), when I am copying some part so it is selected, the autosave window pops up for a second and I lose the copied part so that the frame turns empty. I have to recopy or redraw that part (when the Brush is selected and I have not yet finished a line it gets continued to the center of the frame).

**Comment by artisteacher** [comment]
The copy problem should probably be a separate issue.

**Comment by artisteacher** [comment]
Zooming in with a hotkey is still problematic with Mojave (10.14). Zooming slowly is ok but quickly zooming might crash OT or make it hang as @totry1 described.

**Comment by RodneyBaker** [comment]
Will be curious to see if this is an issue related to screen resolution on the Mac which has been addressed in other cases.

**Comment by artisteacher** [comment]
Probably not. I can get a crash on my high resolution monitor. If I open in low resolution, I still can get a crash if I'm zooming in/out very quickly.

**Comment by artisteacher** [comment]
Here's the crash log, in case it helps.
[zoom_crash.txt](https://github.com/opentoonz/opentoonz/files/2738627/zoom_crash.txt)

**Comment by norrinra** [comment]
Here's another log with the same issue. 

[zoom .docx](https://github.com/opentoonz/opentoonz/files/2958272/zoom.docx)

**Comment by MrBlockCat** [comment]
Does this still occur for you guys? I'm not experiencing this on my MacBook's 2560 x 1600 display on a recent nightly build.

**Comment by artisteacher** [comment]
I'm not getting a crash either!

**Comment by MrBlockCat** [comment]
Awesome! I feel like this did lag on my MacBook not all that long ago, so I’m glad it’s fixed now.

**Comment by RodneyBaker** [comment]
Thanks for the follow up guys.
Closing pending someone notifying us that smooth sailing ahead with this is in fact not the case.  :)

@xavzz Let us know if you still have any problems.
