### ISSUE TITLE
Sceneviewer doesn't track movements on intial startup

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#1899]
When I open a scene in OT, immediately switch to a vector tool like magnet then move around viewer without pressing anything, the magnet's circle doesn't move.  It begins moving only after I press anywhere in the viewer.  This happens with both mouse or pen.

Steps to reproduce:
1) Open a scene in OT
2) Click on Magnet Tool
     - The magnet circle appears in the middle of viewer
3) Move mouse/pointer into viewer without pressing anything and move around
     - The magnet circle remains in middle of viewer

- You can switch or use any other tool, like pinch, pump, iron or cutter tools where there is a visual cue and move into the viewer and it still won't track movement.

4) Press anywhere on viewer
     - The magnet circle (or whatever tool you are now on) now starts moving with pointer

It should be noted, that once you press anywhere on the viewer 1x, the issue goes away.  It's only in the initial loading of OT does this happen.

**Comment by artisteacher** [comment]
I'm seeing this in OS X too.

**Comment by gab3d** [comment]
I have this same problem with Windows 10 (latest nightly) too.

To reproduce:
1. Launch OT.
2. Create any level type.
3. Select the Brush tool.
...when you move the mouse cursor over the viewer the brush outline it's at the viewer center and doesn't follow (...until you draw something).
