### ISSUE TITLE
display delay on canvas

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#1901]
Hi,
As said here, I have a problem with the display.
This occurs on the raster level.

https://groups.google.com/forum/#!category-topic/opentoonz_en/troubleshooting/RDpFhM7uk6s

**Comment by artisteacher** [comment]
If you could share information about your OS & etc., that would be helpful. Is this only a problem when using a tablet?

**Comment by openanim** [comment]
no, the problem is there too with the mouse. But only on rasters levels and only on the latest builds.
from this one 

"Disable Auto-Stretch Frame (#1707)

Added option to enable / disable Auto-Stretch Frame". 

I think it's related to that.

Cintiq companion 2 
intel i7
Intel hd Graphics 5100
8 go ram

 same issue on my another desktop computer.
wind 10
