### ISSUE TITLE
Please enable integration with Bountysource for this issue tracker

### ISSUE THREAD

**Issue by morevnaproject** [opentoonz/opentoonz#1908]
I am proposing to enable integration with Bountysource to make sure that bounties are visible here.
This way bounty hunters will be notified  that particular issues have bounties. And also users will be notified about existing bounties. 

On Synfig we have Bountysource linked to GitHub.
Please see how it works  here -
https://github.com/synfig/synfig/issues?q=is%3Aissue+is%3Aopen+label%3Abounty

![screenshot_003](https://user-images.githubusercontent.com/332868/38456986-10f46b1a-3ab5-11e8-98bc-39981bbf52e1.png)

You can see - when some issue have bounty, then it is automatically labeled by "bounty" tag, and also the total bounty amount is added to issue name.
So, everyone can clearly see that particular issues have bounty, that's right from GitHub.

Also, when particular issue is opened, then it have a special remark at its bottom (also added automatically).

See it for specific issue which have bounty -

![screenshot_004](https://user-images.githubusercontent.com/332868/38456990-1b6ac666-3ab5-11e8-90b2-033a3d8311e9.png)

​...and this is for issue without bounty -

![screenshot_005](https://user-images.githubusercontent.com/332868/38456991-234d4ae8-3ab5-11e8-8757-a6c4785513e0.png)

It is easy to enable this Bountysource-GitHub integration, but only repository administrators can do that.

To install the integration, just log in to BountySource, click your profile icon in top-right corner of the screen and choose "Tools" - 
![screenshot_006](https://user-images.githubusercontent.com/332868/38457016-81b3983a-3ab5-11e8-9175-6e45639eebe2.png)

Then you will see a page where you can install integration for any of your repositories - 

![screenshot_007](https://user-images.githubusercontent.com/332868/38457034-a0b8633c-3ab5-11e8-98d0-2650147c6bda.png)

**Comment by jpturcotte** [comment]
That would be extremely helpful. Great suggestion!

**Comment by manongjohn** [comment]
I agree, this would be nice and helpfull.

As @shun-iwasawa is the owner of this repository, I'll leave that to him to decide. If he is ok with it, I believe I can enable it through my bountysource account, unless he has one or will create one to enable it.

**Comment by jpturcotte** [comment]
For @shun-iwasawa: You actually do not need a separate account. You can login safely with your GitHub credentials.

**Comment by shun-iwasawa** [comment]
I agree with the integration if it will motivate developers. Thank you @morevnaproject for the detailed instruction!

Also thank you @manongjohn for kind proposal but I'll try to enable it with my github account.

**Comment by shun-iwasawa** [comment]
OK, done!

**Comment by manongjohn** [comment]
@shun-iwasawa Thanks! 

I removed the Bpuntysource label I had created and assigned since this will do it automatically now.

**Comment by jpturcotte** [comment]
Thanks a lot for this great addition!
