### ISSUE TITLE
Not working with tablet

### ISSUE THREAD

**Issue by onyigirl** [opentoonz/opentoonz#1911]
https://vimeo.com/264347124
See video for example

In the video when i am making marks that are off i am using a mouse.
When i am moving my brush and the circle disappears plus nothing happens I'm using my tablet.

When I move OpenToonz from Artisul display to my laptop display and make markings with my mouse it acts as it should.  

Does that mean I have to use Duplicate Display to use Open Toonz?

Photoshop, Flash, Clip studio paint, and etc work fine on my tablet

**Comment by artisteacher** [comment]
This is might be related to #1686 and #1696. There are currently a few issues with secondary displays.   What operating system are you using? Are you only using a stylus on the tablet or are there touch capabilities? 

If you haven't tried updating to the [latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly), you should give it a try as there are some tablet and brush speed fixes.

**Comment by onyigirl** [comment]
> What operating system are you using? Are you only using a stylus on the tablet or are there touch capabilities?
I use windows 8.1. I use a stylus. No touch capabilities.
How do I update it? Do I just download the exe only or all the files.  I'm new to this

**Comment by artisteacher** [comment]
Download the .exe file and open it to run the installer.

**Comment by onyigirl** [comment]
@artisteacher It still isn't working

**Comment by manongjohn** [comment]
Normally we see this behavior when you have multiple displays and they are not using the same resolution.  I think it mostly happens when one of the monitors is set at a higher resolution than 1920x1080.
