### ISSUE TITLE
Stuff folder placement

### ISSUE THREAD

**Issue by glingy** [opentoonz/opentoonz#1919]
I understand if this would take a little while to change, but it seems a security risk to request permissions to modify the /Applications/ folder to just store temporary/application-specific files. For MacOS, could you have the stuff folder saved in the ~/Application Support/Toonz folder? The Application Support folder is there for this type of file saving and does not need the program to be run with more authorization. I dislike the idea of giving any program those rights, even if it is an open source application.

**Comment by glingy** [comment]
What information is stored there? Could it be moved and a link/menu item added (maybe to help menu) to guide users there if they need to?

**Comment by jpturcotte** [comment]
Settings files, critical files to run the program, and by default, project files are all stored there. The program simply will not run without that folder.

**Comment by glingy** [comment]
Could you save the project files in ~/Documents/OpenToonz and the critical files in ~/Application Support/? That way the user only sees what they might need to change.

**Comment by artisteacher** [comment]
There already is a Preference where additional project locations (Desktop, Documents or etc.) can be enabled. However in that case, the stuff project location is still available/visible. I think in a studio setting it is important for projects to be accessed by multiple users - hence the Applications location. There is a certain level of protection against user error when administrator privileges are required to make certain changes.

I always encourage my students to use the Documents location - but half of the time they forget and that can lead to complications later on. Personally I think it would be helpful to have a new preference - something like "Enable single user access to Projects". With this enabled, Documents could be the new default project location. This would be particularly helpful in a non-studio setting with multiple users. Perhaps user settings should be saved there as well...

**Comment by geloescht** [comment]
Possible duplicate of #1375

**Comment by jpturcotte** [comment]
You are right. @glingy, try posting there. Recommend close.
