### ISSUE TITLE
Cleanup crash

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1923]
Cleanup (raster to toonz raster) makes opentoonz crash on latest nightly. I'm on mac.
You can find the crash report attached.
[41.txt](https://github.com/opentoonz/opentoonz/files/1930010/41.txt)

**Comment by artisteacher** [comment]
Could this be related to #654?

**Comment by norrinra** [comment]
@artisteacher Most likely. Sorry I forgot to search for it before posting a new issue.

**Comment by jpturcotte** [comment]
@norrinra Could you post there, please? Thank you!

Recommend close.
