### ISSUE TITLE
Morevna:   Toolbar stuck in middle of screen

### ISSUE THREAD

**Issue by starzar** [opentoonz/opentoonz#1924]
Hi,
My toolbar is stuck in the middle of the screen in opentoonz1.2.0.2 moverna version .
 It does scale in the horizontal direction but does not move in the vertical direction. Kindly suggest a solution.
Thanks.

**Comment by beeheemooth** [comment]
Unfortunately, the Toolbar does not scale vertically. If you want to place the tools horizontally, create a new Command Bar and select Customize Command Bar from the RMB menu. Insert the tools you need into it.

**Comment by artisteacher** [comment]
The other option is to replace the toolbar & viewer with the comboviewer. With the comboviewer, a horizontal version of the toolbar, the tool option bar, and the viewer are combined together in a single windowpane.

**Comment by RodneyBaker** [comment]
Closing as a known issue with workaround.
Perhaps in the future additional capability will be added to the Toolbar to allow it to move in horizontal configuration.
