### ISSUE TITLE
Decreasing hardness causes crash.(gif)

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#1926]
![untitled](https://user-images.githubusercontent.com/30438394/39103367-05aa152a-46b3-11e8-97e8-57e7042e3900.gif)

[report.txt](https://github.com/opentoonz/opentoonz/files/1936372/report.txt)

**Comment by shun-iwasawa** [comment]
Confirmed crash. Thank you for the report.

**Comment by shun-iwasawa** [comment]
This seems to be resolved with #1904
