### ISSUE TITLE
Crash after converting PNG to TLV

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1932]
Hello. I converted an PNG drawing into a *.tlv. Now Open Toonz crashes often for the scene that has the converted file.

Unhandled exception at 0x00007FF947A1B79E (ucrtbase.dll) in OpenToonz_1.2.exe: Fatal program exit requested. occurred

**Comment by shun-iwasawa** [comment]
You got the same message as #1933 on crash. I'm wondering if they are separate problems.

You means that the crash does not occur for the scene without the converted file?
Is there reproducible steps for this crash?

**Comment by oladitan** [comment]
I converted a *.png to a *.tlv. I imported the converted file. I believe the problem started when I began to delete unwanted styles.

**Comment by RodneyBaker** [comment]
> I converted a *.png to a *.tlv

We may need to look more closely at how you did this conversion.
It sounds to me like it is a corrupted file.

Can you can share a screen capture (video) of the steps you take from conversion to crash?

**Comment by RodneyBaker** [comment]
@oladitan  Please confirm if you experience this problem again.
Closing.
