### ISSUE TITLE
Schematic:  Crash when using nodes

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1933]
I don't know if this helps but I grabbed this from visual studio output

'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\OpenToonz_1.2.exe'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5PrintSupport.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\colorfx.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\image.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\tnztools.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\tnzstdfx.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\tfarm.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\toonzqt.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\sound.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\toonzlib.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Script.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\tnzbase.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\tnzcore.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\tnzext.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5OpenGL.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Widgets.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Gui.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Multimedia.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Network.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Core.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\mpr.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\msvcp140.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\vcruntime140.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msvfw32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\avifil32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\libmypaint-1-4-0.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\winspool.drv'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.16299.371_none_887d866e4ab76531\comctl32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\glew32.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\Qt5Svg.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\netapi32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\glut64.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dnsapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msacm32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\libintl-8.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\libjson-c-2.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\libiconv-2.dll'. Module was built without symbols.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\netutils.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\srvcli.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\platforms\qwindows.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\Wintab32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\Pen_Tablet.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\d3d9.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ig7icd64.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\igdusc64.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\iconengines\qsvgicon.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\DataExchange.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dcomp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\rmclient.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\UIAutomationCore.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\sxs.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\oleacc.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\DWrite.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qgif.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qicns.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qico.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qjpeg.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qsvg.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qtga.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qtiff.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qwbmp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\imageformats\qwebp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\cldapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\aepic.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\fltLib.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\linkinfo.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\rasadhlp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\NapiNSP.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\pnrpnsp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\nlaapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\winrnr.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\FWPUCLNT.DLL'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\bearer\qgenericbearer.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc6.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\bearer\qnativewifibearer.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\wlanapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\igd10iumd64.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ncrypt.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ntasn1.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\winhttp.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\edputil.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\drprov.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\winsta.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ntlanman.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\davclnt.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\davhlpr.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\wkscli.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\cscapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\browcli.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.371_none_15c7d1789365a290\comctl32.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\WindowsCodecs.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\thumbcache.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\wdmaud.drv'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ksuser.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msacm32.drv'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\midimap.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\OneCoreUAPCommonProxyStub.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Storage.Search.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\policymanager.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msvcp110_win.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\ninput.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\mediaservice\dsengine.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\mfplat.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dxva2.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\mf.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\evr.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\mfcore.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\RTWorkQ.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\devenum.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\msdmo.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\dsound.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\quartz.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\mediaservice\qtmedia_audioengine.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\audio\qtaudio_windows.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Program Files\OpenToonz 1.2\audio\qtaudio_wasapi.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\Windows.Devices.Enumeration.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\biwinrt.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\deviceassociation.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\StructuredQuery.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\MSWB7.dll'. Cannot find or open the PDB file.
'OpenToonz_1.2.exe' (Win32): Loaded 'C:\Windows\System32\DevDispItemProvider.dll'. Cannot find or open the PDB file.
The thread 0x1054 has exited with code 0 (0x0).
Unhandled exception at 0x00007FF947A1B79E (ucrtbase.dll) in OpenToonz_1.2.exe: Fatal program exit requested.

**Comment by shun-iwasawa** [comment]
The warnings `Module was built without symbols` and `Cannot find or open the PDB file` seems not to be related to the crash, and can be ignored.
You get such warnings when you use a debug configuration and linked libraries does not contain debug information. 

Can you please let me know steps to reproduce the problem?

**Comment by oladitan** [comment]
I tried parenting nodes so that I could use the Hooks. I was scrolling through the letters and numbers while ports were connected when the crash occurred.

**Comment by oladitan** [comment]
do you know how I can fix visual studio so that it can debug issues properly

**Comment by RodneyBaker** [comment]
@oladitan Are you still experiencing this crash?

**Comment by RodneyBaker** [comment]
Closing as likely fixed and/or abandoned.
@oladitan Please let us know if you are still experiencing the crash.
