### ISSUE TITLE
Switching between tablet and mouse wheel results in massive zoom

### ISSUE THREAD

**Issue by geloescht** [opentoonz/opentoonz#1936]
I use the mouse wheel instead of my graphic tablet's wheel to zoom (because it's broken). Whenever I try to zoom after using the stylus, the zoom factor suddenly jumps to a ridiculously high number (sometimes even overflowing into the negatives). I might have had a crash once or twice when this happened, but usually I can get back to working by zooming out (using the mouse wheel) until I get back to sane zoom factor. Zooming will work normal again until I have used the stylus and switch back to the mouse.
My tablet is an old Wacom Graphire 4 and I am on Ubuntu Linux 17.10. Compiled the latest master myself, but the same happens with 1.2.0.

**Comment by geloescht** [comment]
By debugging I could confirm that the bad values come from Qt. Most likely related to this bug report: https://bugreports.qt.io/browse/QTBUG-40829?attachmentOrder=asc

**Comment by artisteacher** [comment]
I can't replicate this on OS X with a wacom bamboo. As another workaround, you can use the "fit to window" or "reset view" commands.

**Comment by geloescht** [comment]
Thanks for suggesting the workarounds. This happens probably exclusively on Linux / X11 and according to the bug report it is also isolated to Qt 5.x.

**Comment by flurick** [comment]
Can not reproduce. (I did notice something similar in our an other Qt app recently, pencil2d, so I guess there was a patch for opentoonz at some point)
