### ISSUE TITLE
Wiggly lines

### ISSUE THREAD

**Issue by TGGeko** [opentoonz/opentoonz#1945]
I recently downloaded OpenToonz and I have trouble drawing straight lines. See image below. I move the cursor down smoothly, then it starts wiggling. It seems to be contingent upon where I draw relative to the monitor, with lines towards the center being worse than lines drawn closer to the edge of the monitor. But, it's not very predictable. It's not just lines, but any drawing. 

Other issues seem to involve scaling, and my computer is set to "Recommended" which is 100%

![image](https://user-images.githubusercontent.com/6518222/39667147-b1fa0410-507d-11e8-9728-24bd40de1d46.png)

v 1.2.0 (Dec 11 2017)
OS: Windows 10 64-bit
Tablet: Monoprice
Monitor. 1920x1080

**Comment by RodneyBaker** [comment]
Can you please test with the latest nightly release to see if that resolves the problem.  There have been a great number of improvements since the 11 Dec 2017 release.

Link to nightly releases:  https://github.com/opentoonz/opentoonz_nightlies

**Comment by TGGeko** [comment]
Am I missing something? There only appears to be one file, README.md in that link.

**Comment by RodneyBaker** [comment]
Yes, you are missing something.
Lots of somethings.

Here's a direct link to the .exe file:

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_63e8da9d531b0dc5e331858f93392d66fc5f5521/OpenToonzSetup.exe

**Comment by TGGeko** [comment]
Thank you. Below is my attempt again. The issue still persists. These lines were mostly drawn left to right. 
![image](https://user-images.githubusercontent.com/6518222/39668355-ae8912c8-5099-11e8-8c2a-8b1e9f79bbca.png)

v1.20 (May 5 2018)

**Comment by artisteacher** [comment]
If you draw with a mouse instead, do you still get the same inconsistency? Does this happen on all 3 level types (vector= mustard yellow, Toonz Raster = green, raster = blue)? Do the accuracy or smooth settings have any impact?

**Comment by TGGeko** [comment]
Drawing with a mouse does not produce any wiggles. 
Smooth settings to help reduce the wiggle, but they only eliminate them after the smooth settings reach 20+
They show up in Vector, Toon Raster and raster levels.

**Comment by konero** [comment]
Does the same issue happen with other drawing software? For example, [Autodesk SketchBook Pro](https://sketchbook.com/)?

**Comment by TGGeko** [comment]
I have used several other programs including Krita, Paint Tool SAI, Clip Studio Paint, and Fire Alpaca, and none of them have this issue.

**Comment by TGGeko** [comment]
As of the May 7 nightly release, the issue is still present. Should I continue to report with each nightly release? 

Also, looking closely at it, it seems that the wiggles are caused by the red circle from jumping back and forth from the cursor crosshair to some point slightly off from it.

**Comment by TGGeko** [comment]
I can't be sure what happened but this issue resolved itself. I purchased a 2nd monitor and adjusted the tablet settings to just draw on one monitor and the issue is no longer present.

**Comment by RodneyBaker** [comment]
There hasn't been any word on this since May.
Any updates?

**Comment by RodneyBaker** [comment]
As the OPR reports this resolved recommend closing this issue.

**Comment by RodneyBaker** [comment]
Closing.   @TGGeko If you are still experiencing problems related to this issue please let us know.

**Comment by RodneyBaker** [comment]
Reopening based on feedback from #2970
