### ISSUE TITLE
Problems when converting raster image to TLV

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#195]
Reported from Japanese Google groups: Converting non-AA image to TLV file fails with problems as follows:
- When converting PNG with transparency information to unpainted TLV, some pixels unexpectedly have wrong style indices.
- When converting TIF (8bpc, with no alpha channel) to unpainted TLV, Toonz crashes.
https://groups.google.com/forum/?hl=ja#!category-topic/opentoonz/%E4%BD%BF%E3%81%84%E6%96%B9/ibmn1lNt3_A

**Comment by morevnaproject** [comment]
Hi! I wonder, how do you convert from raster to TLV? Do you use "Cleanup" function or there are some other approach? ^__^
