### ISSUE TITLE
Toonz Raster Cursor Display Issue

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#1950]
With the latest nightly build and OS X 10.11.6, there is a new issue with the display of the brush cursor - but only for Toonz Raster levels. The cursor (the red circle) does not update properly and a trail of red fragments is left visible during the stroke. At the end of the stroke, the fragments remain visible indefinitely if the brush does not move. As soon as the brush moves or the frames change, they disappear. Also, is there a reason the cursor is so much larger than the maximum brush size?

![tr brush dispay](https://user-images.githubusercontent.com/21159116/39712762-3b2969e0-51f2-11e8-8b0d-ac77506ec9ee.gif)

**Comment by konero** [comment]
I haven't run a nightly for awhile, but testing the most recent I'm noticing the viewer has this display glitch when you hold the mouse button down with a brush and draw 'under' the console bar.

Not exactly a deal breaker, but wanted to highlight it.

![tz-brush-error](https://user-images.githubusercontent.com/19820721/39716461-58dcc988-5228-11e8-81b6-da333f985334.gif)

However on-topic! I don't have the problem @artisteacher has.

Also, the vector brush, when initially holding down mouse button there is a maximum sized blob, that looks kind of similar to what @artisteacher has here I guess.

![tz-brush-error-vec](https://user-images.githubusercontent.com/19820721/39716723-ff6af3d8-5228-11e8-8e8c-837e2f4de6b5.gif)

**Comment by shun-iwasawa** [comment]
@artisteacher Thank you for posting the issue. 
#1953 will almost solve the problem (the red fragments issue) except that the brush tip becomes larger than the maximum brush size when you draw on an empty cell.
Drawing on an empty cell will create a new frame. Dpi of such frame will be varied depending on the situation. Estimating the frame's dpi before actually creating it may enable to adjust the brush tip size, but for now OT does not so.
With #1953 , the brush tip will change to the proper size as soon as the frame is created.
