### ISSUE TITLE
No "file" in menubar 

### ISSUE THREAD

**Issue by toku-toku** [opentoonz/opentoonz#1965]
![20180510_224858123](https://user-images.githubusercontent.com/39233112/39964805-9a8ca4b8-56c7-11e8-94ec-aa36b770e77d.jpg)

I just downloaded ver1.2 into my iMac(Late 2015), but there are not "file" and so on at the menubar.
What can I do for this problem?

**Comment by artisteacher** [comment]
It’s not at the very top of the screen? I sometimes use OT on iMacs running 10.11.6 and the menu displays without issue. On my MacBook Pro running High Sierra, it also displays just fine at the very top of the screen.

**Comment by toku-toku** [comment]
It's at the very top of the screen.
You can see "Room", "Basics", …on the right side, but there is nothing on the left side.

**Comment by konero** [comment]
Menu items should be on the main system bar at the very top of the screen to the right of the apple. If that's not the case, post a full screenshot of your screen.

> **How to take a screenshot of your entire screen**
> 1. Press Shift-Command (⌘)-3.
> 2. Find the screenshot as a .png file on your desktop.

**Comment by toku-toku** [comment]
![2018-05-14 22 39 32](https://user-images.githubusercontent.com/39233112/40000853-d8efc66c-57c7-11e8-986d-0131ca4409cd.png)
This is the full screenshot.

**Comment by konero** [comment]
Up here:

![mac_scr](https://user-images.githubusercontent.com/19820721/40002439-b153a626-5788-11e8-97ab-4afab1ad2466.PNG)

**Comment by toku-toku** [comment]
Wow!
I understand!
Thank you for answering my basic mistake.
