### ISSUE TITLE
Crash When Re-create the Second Bone with Plastic Tool 

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#1967]
This problem was [reported in the forum](https://groups.google.com/d/msg/opentoonz_en/fyOR_IFIsJA/b7o_5PwgBwAJ).

To reproduce:

1. Choose Plastic tool and create mesh for some level.
1. Create a bone.
1. Create the second bone by clicking `+` button in the tool options bar.
1. Animate the second bone.
1. Delete the second bone by clicking `-` button in the tool options bar.
1. Try to create the second bone by clicking the `+` button again.

**Comment by animating-dino** [comment]
can you fix it please?

**Comment by animating-dino** [comment]
when do you fix this crash??

**Comment by jpturcotte** [comment]
Hi @animating-dino!
Please understand that a very small team is working on this software, and most of them are volunteers. It is okay to revisit issues from time to time, but pay attention to your language. The developers are working hard, and they do not owe you anything. This bug will be fixed when they have the time, which could be never. If you absolutely want it fixed, post a bounty: https://www.bountysource.com/issues/58322355-crash-when-re-create-the-second-bone-with-plastic-tool?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github. Again, this does not mean they are obligated to do anything. Thank you for your understanding!
