### ISSUE TITLE
FX like Palette Filter and Color Blending only apply to swatches on first tab/page? (solved)

### ISSUE THREAD

**Issue by MisterABK** [opentoonz/opentoonz#1968]
I'm not certain if this is a bug, or if I have misunderstood something about how palettes work - but I can't find any answers by searching. I'm trying to get FX nodes that reference colour swatches by their index number to work with swatches that aren't on the first page. But for some reason, they only seem to affect swatches on the original "colors" tab.

These colours are affected:
![image](https://user-images.githubusercontent.com/35302593/40018288-bdc3323e-57b3-11e8-99e4-a2cbecc497d1.png)
I notice the grey box around these colour, but there's no indication of what it means.

These swatches are not affected:
![image](https://user-images.githubusercontent.com/35302593/40018297-c7644602-57b3-11e8-9aa5-0baa7d44fda9.png)

So, in this example, the FX would affect colour 1, but not 4 or 5. 
![image](https://user-images.githubusercontent.com/35302593/40018497-5ba862f8-57b4-11e8-87f2-5597565051fc.png)

**Comment by artisteacher** [comment]
This seems to work without issue in OS X. What OS are you using and which version of OT?

The grey outline shows which color swatches are in the active shortcut area. Numbers 0-9 on the keyboard are hotkeys to quickly change between styles. When you have more than 10 styles, use the tab key to change which group of styles will use the hotkeys.

**Comment by MisterABK** [comment]
Thanks for the info about the grey box!

This is very embarrassing, but you're right. I was reading index numbers from a different palette. It works correctly!
