### ISSUE TITLE
Size fx setting

### ISSUE THREAD

**Issue by Qggh** [opentoonz/opentoonz#1969]
The size of the fx settings changes back  when I changed the frame
![videotogif_2018 05 15_02 03 11](https://user-images.githubusercontent.com/36899777/40027861-a8a1b6b0-57e4-11e8-8e73-ccdc5c7e18a7.gif)

**Comment by artisteacher** [comment]
This is a known issue #1016. It definitely makes working on a smaller screen more challenging.

**Comment by jpturcotte** [comment]
@Qggh Could you post in #1016, please? Thank you!

Recommend close.
