### ISSUE TITLE
FX Schematic exploding and colapsing levels

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#1974]
I believe there is strange behavior when you add fx to a level, collapse the level with other levels, then explode the subxsheet. various types of issues.

fx are not being retained
some levels no longer appear in the fx schematic

i have not tested with the other schematic, only the fx schematic.

**Comment by RodneyBaker** [comment]
When you say:  

> some levels no longer appear in the fx schematic

Would those be those that are collapsed?
I could see it making sense that they might not appear when collapsed.

**Comment by RodneyBaker** [comment]
@oladitan Closing this as a duplicate.
There are a number of Schematic PRs under review at this time.
Look for those to be merged soon and then please give us your feedback so we can address any remaining issues.  Thanks!
