### ISSUE TITLE
open toonz crashes when you save a mesh level

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#198]
This is possibly related to another bug I filed previously.
Open toonz would not allow you to open the save level dialog while you are in the plastic tool and the active level is a mesh level: 
https://github.com/opentoonz/opentoonz/issues/124

It turns out that when you actually do save your level (after selecting another tool), open toonz crashes altogether.
<img width="698" alt="crash-mesh" src="https://cloud.githubusercontent.com/assets/6495061/14621945/661565aa-05be-11e6-8b60-7a29ae221b48.PNG">

This renders it impossible to actually save mesh levels - it renders it impossible to save your progress.
Speaking of which - opentoonz has a serious problem with saving in general. It discourages me and most people from actually doing anything serious with it. The application does not save your progress like any other application. When you save your scene, it doesnt save its levels. To save them, you have to individually select them and save them. And saving a mesh level is impossible because the software would crash!

**Comment by Rayek** [comment]
I can confirm this. Until the saving issues are resolved, it is ill-considered doing any serious work in OpenToonz.

**Comment by blurymind** [comment]
The forum at google groups has been complaining about this too. It is very discouraging losing hours of work. Some people at newgrounds went as far as saying they dont want to use the software ever again and will stick with flash.

**Comment by Rayek** [comment]
As far as I am concerned, the first released version of OT is a beta version, which needs some tender love and care. When I saw Newgrounds immediately posting a competition, I thought it would only drive some users away from coming back to OT later. And unrealistic expectations played their part as well.

OT has brilliant potential, but unless the saving issues are resolved, no-one in his or her right mind would dare use it on an even remotely professional level. 

I wonder, how on earth has Studio Ghibli finished their feature-length productions in OT? It beggars belief.

**Comment by blurymind** [comment]
They dont use mesh levels or cut out at all. Also they probably import their levels from the gts scan tool.

**Comment by Rayek** [comment]
頑張ってください, Shun-iwasawa! Thanks!

**Comment by blurymind** [comment]
Thank you!

**Comment by blurymind** [comment]
@shun-iwasawa has fixed this bug and it is now merged. 
https://github.com/opentoonz/opentoonz/pull/207

Get a nightly build to test.
https://github.com/opentoonz/opentoonz/releases/tag/nightly

**Comment by Rayek** [comment]
Awesome! Now paperless animation has become viable!

**Comment by blurymind** [comment]
well almost :) It's still kind of hard to deal with keyframes and their timing, because of the missing keyframes editing features in x-sheet. 

But opentoonz might get those back. Thats when it will become viable for me at least. I tried a few tests with the function editor and it's still pretty difficult to deal with keyframes of lots of objects.

**Comment by Rayek** [comment]
I believe Shun-Iwasawa has assigned himself to bringing those keys back in the x-sheet.

**Comment by blurymind** [comment]
That is actually amazing!
He has made some of the most valuable contributions in terms of features and bug fixes.
It is also very impressive how quickly he had the mesh saving fixed.

Thank you @shun-iwasawa !!
