### ISSUE TITLE
opentoonz crashing at startup

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#1981]
when I open opentoonz it cause a problem and says "the application has requested the runtime to ternimate it in an unusual way"
and it crash 
and the crash is
"libstdc++-6.dll"

**Comment by artisteacher** [comment]
Which version of OT are you using & what is your OS?

 If you haven’t tried the latest [nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly), it is worth a try.

**Comment by animating-dino** [comment]
opentoonz morevna edition 1.2.0.2
and 1.2.0.1

**Comment by artisteacher** [comment]
In that case hopefully @morevnaproject or @blackwarthog can help.

**Comment by blackwarthog** [comment]
Please try this latest version:

https://dev.icystar.com/downloads/OpenToonz-1.2.0.3-morevna-18.05.17-win64-cfc90.exe

or this for 32-bit architecture: https://dev.icystar.com/downloads/OpenToonz-1.2.0.3-morevna-18.05.17-win32-cfc90.exe

I've checked - "libstdc++-6.dll" is present in both these builds.

**Comment by blackwarthog** [comment]
May be wrong desktop shortcut. Try to start OpenToonz directly from program files.

Open directory` c:\Program Files\OpenTooonzXXXXXX\bin\`
and run `OpenToonz_1.2.exe`

**Comment by animating-dino** [comment]
it didn't work

**Comment by animating-dino** [comment]
see this video that show the problem:
https://youtu.be/Cjv40la6RdY
