### ISSUE TITLE
Crash using Save Curve In Function Editor

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#1983]
Finally getting around to reporting this one.
Sorry for the delay.

I confirm this process works in Toonz Premium but crashes in OpenToonz.

Steps to Reproduce.
- Animate something so that the Function Editor has data to work with such as moving a column North/Sount (N/S).
- Enter the Function Editor and select the animated item from the listing (N/S in this case).
- Right Click and select "Save Curve".
Normally this will save a .curve file out that contains the data associated with the curve/path of the animated object. 
OpenToonz will usually crash at this point.

In Toonz Premium the .curve file saves and reloads (via Load Curve) without issue.

Thanks in advance!
![savecurvecrash](https://user-images.githubusercontent.com/2576432/40256868-9edfa720-5ab1-11e8-8801-3f5c9f19b4a0.png)

**Comment by RodneyBaker** [comment]
Interesting find here.

I tried an earlier release of OpenToonz and exporting/saving the Curve data in v1.1 (5 Aug 2016) does not cause a crash and that curve data can successfully be reimported.

This should be an easy fix if we can just find what changed from those older releases to the current ones.

**Comment by RodneyBaker** [comment]
Also, if someone can tag this a a 'bug' that will be greatly appreciated.

**Comment by manongjohn** [comment]
I could not duplicate

**Comment by manongjohn** [comment]
Actually, I didn't crash on the 1st save, but I did crash on the second save.

**Comment by RodneyBaker** [comment]
Often there is a very long delay before OpenToonz will crash with this issue.  I'm not sure if that delay accounts from why you haven't been able to duplicate on the first save or not @manongjohn.  In some earlier releases (circa 1.1.2) I ocassionally am able to save a .curve file initially but OT will crash soon thereafter on either attempting to load that .curve file or upon attempting to save the .curve again.

The crash does NOT appear to happen via v1.1.1 so appears to have been introduced shortly thereafter.

Thanks @shun-iwasawa for targeting this to be fixed in the next official release.
