### ISSUE TITLE
opentoonz 1.2 crash at startup

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#1984]
when I open opentoonz it crash immediately 
I try every thing
the crash is:
Problem Event Name:	APPCRASH
  Application Name:	OpenToonz_1.2.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a2f7413
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.10586.1412
  Fault Module Timestamp:	5a646311
  Exception Code:	40000015
  Exception Offset:	000000000006994f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	7b29
can you fix it

**Comment by RodneyBaker** [comment]
I think we need more information.
That looks like Windows 10 to me... not sure.

Are you using the latest nightly release:

https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by animating-dino** [comment]
problem:
 A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	OpenToonz_1.2.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b00cd3b
  Hang Signature:	e88b
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Hang Signature 1:	e88b70684e4c30c5b2d1a9099be16823
  Additional Hang Signature 2:	0b45
  Additional Hang Signature 3:	0b458c63a0245d2bdeb04fd2fcd217df
  Additional Hang Signature 4:	e88b
  Additional Hang Signature 5:	e88b70684e4c30c5b2d1a9099be16823
  Additional Hang Signature 6:	0b45
  Additional Hang Signature 7:	0b458c63a0245d2bdeb04fd2fcd217df

**Comment by animating-dino** [comment]
i fix it with another way!!!!!!!

**Comment by RodneyBaker** [comment]
Glad to hear you got it fixed.
Happy animating!

**Comment by jpturcotte** [comment]
@blackwarthog I agree.

**Comment by animating-dino** [comment]
i fix it by downloading api-ms-win-crt-runtime-l1-1-0.dll
