### ISSUE TITLE
Copy Paste in same place

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#1987]
Hello,

I would like to submit a paste copy command that exists in a lot of software. In some cases we would like to hide lines by copying and pasting these lines in the same place. But this isn't possible in Opentoonz.

However, it is possible to cut paste in the same place. Or to copy paste in the same place but in another level. It would be cool to have this feature without fumbling.

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
Definitely open a feature request for this via the OT forum.
It would be very useful to have copy/paste take an offset (or lack thereof) into consideration when pasting.  This would likely be a setting in Preferences > Drawing or other appropriate place.

The default of pasting with an offset is of course standard practice for good reason in that if not offset the user has a hard time validating that anything has been pasted.

In many instances of just needing a same copy for purpose of rendering it should also be noted that simply exposing the image into another column in the xsheet will produce the same effect of pasting without offset.   Another quick method is to just extend the frame down one cell (in the xsheet) then tear off that cell and place it in the next column.  This will only be useful in certain cases of course and creating a Clone is more akin to an actual copy/paste in place.

Concur with recommending closure here pending a feature request in the OpenToonz forum.
Implement as time and priority allows!

**Comment by shun-iwasawa** [comment]
The current behavior seems to be like as follows : On pasting vector stroke data, if the target image already has another stroke which has similar bounding box, OT will add offset before pasting it. ( See [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzqt/strokesdata.cpp#L35-L55) in the source. )

**Comment by RodneyBaker** [comment]
Nice find @shun-iwasawa 
So that bug is officially a feature.  :)

Now we just have to find a good way to reconcile workflow/usage.

**Comment by openanim** [comment]
Sorry, I did not specify that these were the vector levels in the title. I am going to close here and open a request in the forum as suggested.

Thanks a lot, Shun-iwasawa for the information on the offset of 10. At least, it will be easier to correct with shift arrow.
