### ISSUE TITLE
Pinch tool and shift key causes crash in latest build

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#199]
Steps to reproduce:
1) draw a vector stroke.
2) switch to the pinch tool.
3) drag part of the curve with the pinch tool. While performing the action, press the SHIFT key, and let go of either the shift key or the mouse button.

Toonz crashes. This does not happen when the shift key is pressed BEFORE using the pinch tool.

**Comment by shun-iwasawa** [comment]
Fix merged in v1.0.2
