### ISSUE TITLE
bug while moving group of keyframe 

### ISSUE THREAD

**Issue by z-uo** [opentoonz/opentoonz#1999]
If I select a group of keyframe, I can't move them frame by frame.
With 6 keyframes, I can only move them by 6 frames or 12, 18, 24...
The only solution to move them 1 frame before is to select and move them one by one

The bug is the same if you select a groupe of cell and keyframe with ctrl.

I use onpentooz 1.2 on windows and also try the nighty build with the same issue.

**Comment by RodneyBaker** [comment]
Is this in the Timeline only?
I can grab and move keyframes frame by frame in the xsheet.

If the problem is limited to the Timeline then recommend adding 'in Timeline' so that will help hone in on the solution.  

If Timeline only then it likely just hasn't been implemented yet.

**Comment by z-uo** [comment]
I've made a few more test.
The issue is the same in the timeline and the xsheet, but it doesn't appear all the time, only if in your group of keyframes, you have adjacent keyframes like in frame 1 and frame 2, if you have keyframe on frame 1 and frame 3 it works fine.
Also if you select cell and keyframe with ctrl the cell will move fine but the keyframe will move only 2 by 2.

**Comment by artisteacher** [comment]
I'm seeing the same thing in OS X - also only if consecutive keyframes are selected. As long as there is a frame in-between, they move as expected. It looks like selected groups of consecutive keyframes are treated as a single object when moving them in the Xsheet/Timeline. When they are moved, instead of moving each keyframe a single frame they move the entire "block" one keyframe over from the outermost selected keyframe.

**Comment by RodneyBaker** [comment]
I attempted it again with consecutive frames and and get the same results of moving 2 by 2 in both Timeline and xsheet.

**Comment by shun-iwasawa** [comment]
Observing [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/keyframemover.cpp#L119), for now the keyframe can be moved to only cells without keys.
The problem is that cells containing dragging keys (i.e. keys to be moved out) are also regarded as occupied.

**Comment by RodneyBaker** [comment]
I confirm the fix works on Win10 in the latest release.  Thanks!

**Comment by z-uo** [comment]
Yes that work great, thanks
