### ISSUE TITLE
Activating "Minimize Raster Memory Fragmentation" causes raster layers to corrupt the preview

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#200]
I am using the latest Nightly build from 18/04/2016

When "Minimize Raster Memory Fragmentation" is turned ON (checked) in the preferences, raster levels will cause the display of previews in the preview windows and in the combo viewer to be corrupted.

Leaving it turned off fixes this problem. 

Windows 7 64bit, 48gb ram

**Comment by trevorboydsmith** [comment]
i also observe "preview being corrupted"... or as I would describe the issue "the preview has lots of artefacting" behavior on my machine.

- opentoonz version: tagged v1.0.2
- system: windows 10, 64bit, 24gb memory

**Comment by shun-iwasawa** [comment]
modification merged
