### ISSUE TITLE
moving all keys that skip 1 frame (gif)

### ISSUE THREAD

**Issue by spikysaurus** [opentoonz/opentoonz#2004]
i select all these keys and move them
this happens in xsheet mode too
![bandicam 2018-05-24 22-28-35-113](https://user-images.githubusercontent.com/39307011/40496213-70fe1bba-5fa3-11e8-87c8-bcbad1ad1921.gif)

**Comment by artisteacher** [comment]
This looks like a duplicate of #1999. It was actually fixed this morning in the nightly build.

**Comment by RodneyBaker** [comment]
That nightly build can be found here:
