### ISSUE TITLE
(WIP) Constant recording of dialog geometry is redundant

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2006]
I've noticed in the last nightly build (as of May 24th), that when trying to move some dialog windows it gets very slow.
Tese include: Palette Gizmo, (Palette) Name Editor, Tracking, Convert to Vectors, Auto Incput Cell Number, FX Browser, Level Settings, Adjust Levels... well they seem to be a lot indeed.

I'm on Windows 10 (with April 2018 update), i7, Geforce GT650M (with latest drivers).

**Comment by shun-iwasawa** [comment]
This seems to be because OT constantly records the current dialog geometry into the file while moving it. This behavior is redundant and (as you pointed) very slow.
This part has been kept unchanged from Toonz Harlequin. I think this can be modified to record just once when quitting the software.

**Comment by gab3d** [comment]
...or when releasing the LMB, perhaps?

**Comment by RodneyBaker** [comment]
Temporarily closing as this looks to be slipping to the 2019 Development Cycle
