### ISSUE TITLE
Guides disappear if zoom factor is too low

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2007]
It the Viewer is zoomed out, anywhere below 45% zoom, then the guides disappear. When the viewer is zoomed back in, anywhere 45% and above, the guides appear again.

**Comment by shun-iwasawa** [comment]
Thank you @artisteacher for reporting. Confirmed the problem.
Please note that after merging #1645 the guide disappears below 100% zoom.
Also note that this problem seems to occur only on OSX.

**Comment by artisteacher** [comment]
Guides continue to disappear whenever zoom is below 45%.

**Comment by yehjaemin** [comment]
If this issue is still open, I'd like to try fixing it!

**Comment by artisteacher** [comment]
@yehjaemin it's still a problem - if you are able to fix it that would be amazing!

**Comment by yehjaemin** [comment]
@artisteacher Great, I'll start looking into it!

**Comment by yehjaemin** [comment]
@artisteacher sorry, just to clarify, you're talking about when you're in the xhseets tab and you zoom out below 45%, the gray lines disappear? Also, are you working with version 1.2.1?

**Comment by artisteacher** [comment]
@yehjaemin - It doesn't matter if the XSheet or the level strip is active. In the viewer, if any guides have been added (drag out from the ruler markers around the edge of the viewer to add them), they don't display if the zoom factor is too low. This has been a problem for a while, but right now I'm using the RC.

**Comment by yehjaemin** [comment]
@artisteacher That's weird.. I can reproduce your bug on 1.2.1 but not on RC1.3. I add 4 custom guides that disappear below 45% on 1.2.1 but stay visible at any zoom level on 1.3.

**Comment by yehjaemin** [comment]
I'm using 10.14.2. I think it's not a problem with os or resolution then.

Did you build from source or with the package installer? And when you installed 1.3, did you delete 1.2 first? Also, do you have the /Applications/OpenToonz/OpenToonz_stuff folder?

I noticed you had another issue with building on mac. I had a similar issue, and I tried to fix it in PR #2499. If you didn't do a clean uninstall before installing 1.3, it might be that some relics from 1.2.1 are still affecting your 1.3 build.

**Comment by artisteacher** [comment]
When I've built myself, it seems to not be an issue but when i use the installer, it is. A completely clean install doesn't make a difference, but thanks for the suggestion.

**Comment by yehjaemin** [comment]
Huh, I guess one of the most recent commits probably made the difference then. Hopefully the next published version will get rid of the bug completely.

**Comment by artisteacher** [comment]
Hopefully - but there are some other glitches (like some of the problems in #1216) that don't happen when building.

**Comment by artisteacher** [comment]
So this is still a problem with 1.3 - but not a problem when building yourself.

**Comment by artisteacher** [comment]
No longer an issue with the latest nightly build.
