### ISSUE TITLE
Black fill in objects filled with other colors.(opentoonz1.2.0.2 moverna version)

### ISSUE THREAD

**Issue by starzar** [opentoonz/opentoonz#2010]
![otfill](https://user-images.githubusercontent.com/38550930/40528381-7df75a3c-600e-11e8-8ec8-03e2c575d8e8.png)

Hi,
I have been trying to fill closed shapes created by both vector and raster brush as well as the geometric tool,The fill color turns out to be black  eventhough the selected fill colors are  different(eg white & red in my case ).I have turned off autofill and fill check options,still the problem persists.A snapshot of the problem is attached. Please look into the issue.
Thanks.

**Comment by shun-iwasawa** [comment]
It seems that you are selecting the studio palette. Please refer to the comments in #1988
