### ISSUE TITLE
Parts of the program are invisible, usable (not in a  good way), but still invisible

### ISSUE THREAD

**Issue by cosmichentai** [opentoonz/opentoonz#2015]
--Issue Summary--
I can't see what I'm drawing. There's no white screen for me to draw on but it shows up on the frames. And I can't see the color wheel at all but I can still use it, but again, I can't see what I'm doing.

 --Video or Image Reference--
![3](https://user-images.githubusercontent.com/39661240/40581619-3ca36484-6123-11e8-957d-f635cb243b34.PNG)
![2](https://user-images.githubusercontent.com/39661240/40581620-3cced5ce-6123-11e8-91be-3eb51c985b78.PNG)
![capture](https://user-images.githubusercontent.com/39661240/40581621-3ce62cce-6123-11e8-9e03-bc1717a4f089.PNG)

I saw mentions of activating the xsheet and not levels to help, but it changed nothing. No idea why the color wheel is invisible. Tried uninstalling and re-installing but nothing changed. Everything is still invisible and I can't find an older version of OpenToonz.

+OpenToonz Version: 1.2

+ Operating System:
Windows 7 Pro 64 bit
RAM Size  8GB

+Graphics Tablet:
Ugee drawing monitor.

**Comment by manongjohn** [comment]
This is a known issue with the official release and was later fixed. Please download the latest nightly which should correct the issue.

**Comment by RodneyBaker** [comment]
Here's the link to the nighty releases:

https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by cosmichentai** [comment]
It worked. Thank you both. It's much appreciated.

**Comment by RodneyBaker** [comment]
@cosmichentai  Outstanding news.

Recommend closing this issue.
