### ISSUE TITLE
Some strings cannot be translated v1.2.1

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2020]
### --Issue Summary--
There are currently some strings in OT's UI that cannot be translated.
Some of them of newly added features, which are of very high exposure inmediately after release.
So it'd be great if they could be addressed

### --System Information--
+ OpenToonz Version:
1.2.1 release candidate (sort of...)

Here I post a prioritized list of found untranslatable strings, as of the last nightly build.

**HIGH**
- Animate Tool: "All", "fld" (in Z Position input field)
- Fill Tool: "Maximum Gap"
- Style Editor: drop down menu (Wheel, H, S, V, A, R, G, B)
- Preferences > Tools:  Cursor Options both drop down menus options (all)

**MEDIUM**
- Brush Tool: "custom" (brush preset)
- Style Editor window title: the word "Palette" still shows only in English
- "Xsheet" / "Timeline" toggle button in Xsheet
- Ruler Tool: X, Y, W, H, A, L strings
- Tape Tool: "current" (in Style Index option) 
- Rotate tool: "Rotate On Camera Center"
- Scene Cast window: "Cast", "Audio"

**LOW**
- New Level dialog "Type" drop down menu options: (Toonz Vector Level, Toonz Raster Level, Raster Level, Scan Level)
- Level Settings dialog: "Vector level", "Ink&Paint level", "Raster level", and DPI drop down menu options (Image DPI, Custom DPI)
- Camera Settings dialog:  "inch", "A/R", "custom" (camera presets)
- Export Level dialog > Export Options > Vectors Export Box: "Width""Height" (strings are there in the PO file, but apparently disabled).
- Replace Level: warning, when nothing is selected "Nothing to replace: no cells or columns selected."
- Adjust Levels: drop down menu options (RGB, Red, Green, Blue, Alpha)
- Color Fade:  "R", "G", "B", "A"
- Canvas Size: Units drop down menu options (pixel, mm, cm, field, inch)
- Replace Parent Directory: File browser title

**Comment by shun-iwasawa** [comment]
@gab3d Thank you for listing the missing items. I'll try to make them translatable as much as possible.

**Comment by gab3d** [comment]
@shun-iwasawa 
Thank you!

**Comment by gab3d** [comment]
@shun-iwasawa 
I've found some additional cases:
I'll list them here, just to have them in a single place.

**HIGH(ish)**
- Configure Shortcuts window: "Search:", "Preset:", "Delete", "Save As"
- FX Schematic: "Source", "Matte", "Light", "Reference" connector names in effect nodes (at least most common ones).
- Visor RMB menu: word "Table" in option Select Table


**MEDIUM**
- Function Editor > items tree: "Stage", "Table", "FX"
- Function Editor > Interpolation type File options: "File Path:", "Column:", "Unit:"
- Spritesheet settings dialog: "Format", drop down menu options ("Grid", "Vertical", "Horizontal", "Individual"), "Top/Bottom/Left/Right Padding", "Scale", "Trim Empty Space"
- Histogram window: "Picked Color", "R:", "G:", "V:", "Average Color (Ctrl + Drag)"

**LOW**
- Palette Gizmo: "R", "G", "B", "A"
- Style Name Editor: "Character", "Part", "Suffix"
- Configure Shortcuts > Save As dialog: window title, "Preset Name:", "OK", "Cancel"
- Configure Shortcuts > Load dialog: "Setting Shortcuts"
- Configure Shortcuts > Export Current Shortcuts: file browser title
- Flipbook: "Safe Area (Right Click to Select)", "Minimize"
- History window: window title
- Load Task List: file browser title text
- Task window Status texts:  "Suspended", "Completed", etc.

**Comment by shun-iwasawa** [comment]
@gab3d Thank you again for the list. I added them to #2026

**Comment by gab3d** [comment]
@shun-iwasawa
A last one I forgot to mention:

- In all text/number input fields, the RMB menu options are always in English: (Undo, Redo, Cut, Copy, Paste, Select All)

Thanks and sorry for keeping you coming back to this issue! ;)

**Comment by shun-iwasawa** [comment]
↑  Done. :+1:
