### ISSUE TITLE
Tool Options are Not Aware of State of Another Enum Option on Non-English UI

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#2023]
### --Issue Summary--

After introducing #1863 tool option items fails to be aware of state change of other enum options.

### --Steps to reproduce--

This is one example:
- Choose Fill Tool
- Change `Mode` to `Lines` and then to `Areas`
- See `Onion Skin` checkbox becomes disabled when `Lines` is selected
- Change the current language to other than English and try the same procedure

### --Actual Results--

The enable/disable state of `Onion Skin` checkbox does not change.
Same problems occur in many part in Tool Option.

### --Expected Results--

They should update enable/disable state according to the current enum option value.

### --System Information--
+ OpenToonz Version: Current master branch

### --Cause of This Problem--
Looking [here in tooloptions.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/tooloptions.cpp#L1666), OT calls `QComboBox::currentText()` for checking the current property state, but the return values are now already translated. They should be changed to see the current value of `TEnumProperty` directly.

**Comment by artisteacher** [comment]
Maybe this is causing #1799?

**Comment by shun-iwasawa** [comment]
@artisteacher 
I don't think so. #1799 was reported based on the stable release which does not include #1863 .
