### ISSUE TITLE
Link to Online Documentation in Help Menu?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2028]
@manongjohn 
...now that you're into adding menu options. ;) ;)
How about adding a link to the OT's online documentation to the Help Menu?
It seems easy to do and it'd certainly increase the exposure of the online documentation to users, especially new ones.

**Comment by DarrenTAnims** [comment]
While you're at it, it could be worth adding a link to this site for reporting bugs and the other site for suggesting feature requests. That'd certainly get more coming through.
(a little ironic as this site is for bugs and this is a feature request, but thought I'd tack it on as I've just noticed this one)

**Comment by artisteacher** [comment]
I'm not sure I would specifically add a link for feature requests - that might create the expectation that they will be fulfilled. However a link to the forum for help (in addition to the online documentation) could be useful.

This is a little off topic, but in addition to these links, I think the menus in general could use some reorganization. The File menu in particular is excessively long. It would be great to have some submenus to make it easier to find certain commands.

**Comment by DarrenTAnims** [comment]
I agree artisteacher. And I super-strongly agree about re-organising the menus. I struggle to find items, especially in the File menu and Windows menu. They all need grouping better.

**Comment by RodneyBaker** [comment]
Closing as a feature request slipping to 2019 development cycle.
Ideal online locations might be the primary opentoonz site and/or readthedocs.

Note that several Digital Video products have links to local and online html and pdf resources.
One thing to consider is how to best account for links that might break should that resource be removed.. as seen in one of those products.

Recommend testing to see if linking to a local html file which in turn links to the online locations might be ideal as then the user could update and customize the links as desired.

**Comment by gab3d** [comment]
@shun-iwasawa 
could we please add this in the next version of OT?
I think it's really needed...

this is just an example that happened today in Facebook:
![Sin título](https://user-images.githubusercontent.com/18104091/63614553-bc487e80-c5b9-11e9-88ff-5f9eade4a6dd.png)

**Comment by gab3d** [comment]
@RodneyBaker 
could you please reopen it?

**Comment by manongjohn** [comment]
Adding link to on-line help is actually part of PR #2545.  It needs to be reviewed and merged.

**Comment by gab3d** [comment]
great!

**Comment by RodneyBaker** [comment]
Agree that documentation link from the Help menu is important.
If @shun-iwasawa isn't opposed to me merging the other PR i'll be glad to do it.
The issue may be that too many changes are included in #2545.
Perhaps the Help menu documentation link could be separated out and merged by itself?

**Comment by manongjohn** [comment]
I would prefer not to split it out unless none of the other changes will be accepted. It's been sitting out there for many months in which I have been rather patient waiting for a review along with my other PRs that I have been sitting there almost a year...so if its not going to be reviewed or any part accepted, then I'll abandon it instead of constantly watching for and dealing with conflicts.

If someone wants to steal the commit and create a new PR, go ahead.

**Comment by RodneyBaker** [comment]
I'm tempted to try to steal/extract that commit and explore a PR for it.
I hesitate for a number of reasons, first and foremost of which is that I really don't know how to do it.

Another reason I'd hesitate to take on adding the Help menu documentation link is that it seems to me that the user should be able to update or change that link.  I know many will disagree with this but bear with me for a second and I'll explain my rationale.  Links tend to break and a documentation link in the Help menu isn't immune to that possibility.  As such, should the link ever fail, the feature is useless until such a time as the source can be restored or the link refreshed pointing to another source/location.  At least with the ability to change the URL via Preferences (and/or .ini/config file) the URL could be updated to point at a useful location.  The downside of this is that documentation other than 'official' documentation might be linked... but that's also a plus... if/where better documentation might be found.

It is largely for this reason of personalization of the Help Menu documentation that it could be sponsored as a new PR fully focusing on that area of interest.  This would also divorce it from possibly more contentious changes to the menu where everyone has their personal preferences.

For others looking in this might be a good opportunity to conduct some open source training while encouraging others to get involved with Opentoonz development.  

In the end, this documentation link in the Help menu is a small but important change.
Anything we can do to move it forward to implementation will be good in my estimation.

As always @manongjohn thanks for all you are doing and have done.
Opentoonz is a much better program thanks to your contributions.

**Comment by gab3d** [comment]
@manongjohn 
We all really appreciate you efforts on improving OT!!
I understand the frustration that could arise from that fact you mention, I think it's due mainly to either a lack of human resources and/or a proper organization to handle the movements around such a public project like OT, which would only get larger in the future BTW...

So I think it is a great moment to take this opportunity and trigger an open discussion about how to plan and organize the efforts behind OpenToonz for the future. 
Perhaps we can learn a lot from the Blender Foundation or other similar organizations that foster open source projects like ours, obviously with Dwango playing a leading role in it.
Also, devising plans for raising funds and how to assign them, would play an essential role in the development of OT.

So, what do you think about it? any other points of view? suggestions? recommended paths to achieve that?
@shun-iwasawa 
@turtletooth @DarrenTAnims @artisteacher @RodneyBaker @masafumi-inoue @konero @blackwarthog @otakuto @jpturcotte  @morevnaproject 
...and any other sincerely interested minds, really.

As I'm also translator for the Blender project, and if there's interest and permission from Shun and the main parties currently behind OT, I can try to contact someone at the Blender Foundation to see if they can somehow help us with advise on what have worked for them and some effective ways to advance in a similar direction. 🤔 

(If this discussion makes sense to you people, and it takes off, a new issue would be needed by the way)

**Comment by RodneyBaker** [comment]
Start a new Issue and title it something appropriate.
It's not like we have a lot of spam here.

**Comment by gab3d** [comment]
yes, I know, but it will only make sense if there's interest in discussing this matters.
for now let's see how much interest in this there is...

**Comment by RodneyBaker** [comment]
Several discord members have expressed frustration and interest to the point of stating a desire to disconnect from development and community involvement entirely.  As such, it certainly appears to matter.  A question might be whether it matters enough to engage in public discussion as we continue forward with development or to keep such discussions private.  

As Opentoonz is open source it makes sense to keep discussions about it's development as open as reasonably possible.  If there are pressing concerns, we should meet them head on;  attack them like bugs even.  :)

**Comment by gab3d** [comment]
well, yes... I suppose there will be interest in many people...
but I also think the most convenient way of doing it would be going from small to big, first asking for proposals and samples of interest from the core people that are currently more involved (as to be here, in first place), to see if we can come up to something, and then in a second stage the discussion could be opened to span a wider reach.

**Comment by beeheemooth** [comment]
@shun-iwasawa we would like to hear your opinion about the above.

**Comment by shun-iwasawa** [comment]
I posted a new discussion issue #2746 related to this. Thanks!

**Comment by RodneyBaker** [comment]
If there are remaining issues not closed by #2545 please let us know.
