### ISSUE TITLE
Unable to change raster level resolution

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#2030]
### --Issue Summary--

I created a toonz raster level at 1920 x 1080 resolution. I tried to change the raster level resolution via the level settings to 3840 x 1080. It would only allow me to proportionally scale the level.

When I first create the level I am able to use any custom resolution. But once the level is created I can only proportionally change its resolution.

### --Expected Results--

If I want to change the raster level resolution I would like to be able to do that to any custom resolution

### --System Information--
+ OpenToonz Version:

1.2
May 2, 2018

+ Operating System:

windows 10

+ Other Device Info (Optional):

* RAM Size  4GB, 8GB, 16GB:
10GB
* Graphics Tablet:

---

**Comment by gab3d** [comment]
You have to use Canvas Size option (under Level menu) to address that.
It works much like in Photoshop.

**Comment by RodneyBaker** [comment]
@oladitan Do you have any updates?
If all is well this issue can be closed.
