### ISSUE TITLE
Loading "OpenToonz" keyboard shortcut preset loads an older version.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2032]
### --Issue Summary--
If you load the "OpenToonz" Preset for keyboard shortcuts it actually loads an older version of the shortcuts (i.e. Animate Tool (E), Eraser (A), etc...)

### --Steps to reproduce--
1. Go to File > Configure Shortcuts...
2. From the Shortcuts Presets section, select OpenToonz from the dropdown menu.
3. Click Load button.

### --Actual Results--
Old set of shortcuts is loaded.

### --Expected Results--
Current set of shortcuts loaded.

### --System Information--
+ OpenToonz Version:
all

+ Operating System:
all

**Comment by gab3d** [comment]
@shun-iwasawa 
sorry, but this continues to be the case, as of the last nightly build.

**Comment by artisteacher** [comment]
I'm seeing this too in MacOS.

**Comment by manongjohn** [comment]
The config file in the stuffs folder with all the default OT shortcuts probably hasn't been updated in a while or am I missing something?

Do we know what needs updating?
