### ISSUE TITLE
Feature request: Scaleable Xsheet column 

### ISSUE THREAD

**Issue by JoBoernicke** [opentoonz/opentoonz#2033]
Hey,

title pretty much says it. is there the possiblitly to implement a size scaling for xsheet columns?

best regards

**Comment by manongjohn** [comment]
I've seen this asked before.  My question is,   scaled in what way and what happens to the column header,  buttons and all?

**Comment by JoBoernicke** [comment]
i realised that this is more of a feeling and text readability thing, more than an actual workflow-issue.
