### ISSUE TITLE
Viewer Fails to Update When Draw&Create a New Frame with Raster Brush Tool 

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#2035]
### --Issue Summary--

Viewer fails to update contents when creating a new frame by drawing with Raster / Toonz Raster brush tool, setting `Autocreation` preference option to `Use Xsheet as Animation Sheet`.

### --Video or Image Reference--

![brushbug](https://user-images.githubusercontent.com/17974955/40900879-b0b819dc-6808-11e8-9edd-b90213daf3e5.gif)

### --Steps to reproduce--

- Set `Autocreation` preference option to `Use Xsheet as Animation Sheet`
- Select empty cell at frame 1 and draw something on the viewer 
- Select frame 3 and draw something
- Select frame 2 and draw something

### --Actual Results--

As soon as start drawing, level frame 2 is automatically added. However, Viewer remains old content of the frame 1. Viewer partially updates only around the brush tip.

### --Expected Results--

Viewer should be totally refreshed as soon as the new level frame is created.

### --System Information--
+ OpenToonz Version:   current master

+ Operating System:   Win7

**Comment by beeheemooth** [comment]
That also happen in Vector Level when using Brush Tool with Frame Range

![ezgif-3-e818474454](https://user-images.githubusercontent.com/25724133/40908011-40cad70a-67ee-11e8-9aad-43eb619a7a49.gif)
