### ISSUE TITLE
0 byte Webm files

### ISSUE THREAD

**Issue by TGGeko** [opentoonz/opentoonz#2039]
### --Issue Summary--
When rendering a webm, the file produces is 0 bytes, causes VLC player to crash and won't open on Firefox.

### --Video or Image Reference--
These are the settings used when Rendering

![image](https://user-images.githubusercontent.com/6518222/40953284-0ad43cea-684d-11e8-9bac-bdae0157dd92.png)

![image](https://user-images.githubusercontent.com/6518222/40953528-1f4d60ce-684e-11e8-9577-3b40a9ddddcf.png)

### --Steps to reproduce--
Set output file to webm. Press Render. Open resulting file. 

### --Actual Results--
Rendered file has zero bytes, crashes VLC player and won't open on firefox

### --Expected Results--
Expected scene to render in a viewable webm file

### --System Information--
+ OpenToonz Version:
OpenToonz 1.2.0, Built June 4

+ FFMPEG version: 
FFMPEG v4.0 win64 static

+ Operating System:
Windows 10

* RAM Size:
8 GB 

---

**Comment by shun-iwasawa** [comment]
I could reproduce the problem. Thank you @TGGeko for reporting this.
