### ISSUE TITLE
Cannot select and delete points with wacom bamboo tablet.

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#2048]
### --Issue Summary--

Hi. I cannot select and delete points with the control point editor tool when using my wacom bamboo tablet. 

I can however select and delete points with my mouse.

### --Video or Image Reference--

https://www.youtube.com/watch?v=74yfzwqZCJ8&feature=youtu.be

download scene:

http://olladitan.com/download/opentoonz-pink-afro-drawing/

### --Steps to reproduce--

draw with the vector brush
select control point editor tool
tap on points with wacom pen

### --Expected Results--

I wish i could select and delete points when using my mouse or tablet

I like the snapping option in the bush settings. There should be one with the control point editor too.

### --System Information--
+ OpenToonz Version:

open toonz 1.2.0
june 5, 2018
+ Operating System:

windows 10
+ Other Device Info (Optional):

* RAM Size  4GB, 8GB, 16GB:
16
* Graphics Tablet:

wacom bamboo fun

---

**Comment by artisteacher** [comment]
This is probably related to #1722. I can select and delete control points with a Wacom tablet (at least in OS X), but sometimes it takes a few tries to get a control point selected.

**Comment by oladitan** [comment]
Thanks @artisteacher . How do I fix this?

**Comment by artisteacher** [comment]
I put my tablet away & got it back out & now of course I’m having trouble! I have found a workaround - try deleting as you are clicking and holding on the control point.

**Comment by oladitan** [comment]
@artisteacher That seems to work. Thanks. It would be nice if it worked like the mouse. It would be even nicer if multiple points could be selected by holding shift.

**Comment by artisteacher** [comment]
They really should work just the same. With a mouse you can use control/command to select multiple control points at once, but at least right now, it doesn’t seem to be working with a tablet.

This actually seems to be another aspect of #1679. Clicking in the Level strip and then back in the Xsheet makes selecting with the tablet & control point editor work just like with a mouse. By any chance do you have issues with the magnet tool & tape tool (especially after changing their tool options)? If so, I recommend closing this issue and posting in #1679.
