### ISSUE TITLE
Info.plist is missing CFBundleIdentifier on MacOS

### ISSUE THREAD

**Issue by raineszm** [opentoonz/opentoonz#2053]
### --Issue Summary--
The keys which are set in the Info.plist file within OpenToonz_1.2.app do not include all keys [recommended by Apple](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html#//apple_ref/doc/uid/TP40009254-SW4) Cocoa apps.
The biggest problem is that [`CFBundleIdentifier`](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102070) is not set, which breaks compatibility with third party tools such as astropad.

### --System Information--
+ OpenToonz Version:
Using the nightly from May 25, 2018

+ Operating System:
macOS 10.12

The following definition just needs to be added to the Info.plist file.

```xml
<key>CFBundleIdentifier</key>
<string>io.github.opentoonz.OpenToonz</string>
```

The fix is pretty straightforward, and I would be happy to submit a pull request if that would be preferable.

It's probably also worthwhile to set the other keys assuming there's not a good reason why things like `CFBundleName` and `CFBundleVersion` are left blank.

Thank you for all your work on OpenToonz.

**Comment by artisteacher** [comment]
I'm curious, with this fix, how well does astropad work?

**Comment by raineszm** [comment]
I'm using Astropad Studio, and with this fix it works well with OpenToonz. At least for my amateur needs.

To clarify, the issue without the fix is that the shortcuts and tap gestures do not work correctly in astropad with OpenToonz.

With the fix applied everything works except that the panning gesture instead zooms in and out.

**Comment by artisteacher** [comment]
Thanks! Personally, I think it would be great if you could submit a pull request. 

As far as panning goes, at least for 2 finger panning gestures, it is recognized as middle mouse wheel input. In the viewer, middle mouse wheel zooms in and out. With touch enabled, that incorrect zooming behavior during panning gestures is disabled for touchpad devices. I haven’t been able to use a touchscreen device so far but I hadn’t expected that to be an issue. It is possible to disable the zoom during pan gestures for touchscreen devices as well but someone with a touchscreen will need to make sure there are not unintended side effects for people using a mouse too. This can be found in sceneviewerevents.cpp, lines 866 - 868. That should probably be it’s own issue.
