### ISSUE TITLE
Switching the Selection Tool and "No Antialiasing" option. (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2058]
The option "No Antialiasing" always turns off if you switch  the Selection Tool (Raster, Toonz Raster)

![ezgif-1-7f406423b9](https://user-images.githubusercontent.com/25724133/41221959-60243b8e-6d6e-11e8-9be6-72410054e9a1.gif)

**Comment by gab3d** [comment]
confirmed here
