### ISSUE TITLE
Opentoon Inbetween button is a no show

### ISSUE THREAD

**Issue by Amikeyou** [opentoonz/opentoonz#2059]
### --Issue Summary--

The inbetween button does not show up when I highlight my Level Strip (or at all).

### --Video or Image Reference--

![no inbetween](https://user-images.githubusercontent.com/40159563/41226156-4a98167e-6d36-11e8-9067-8b36c9926cde.png)

### --Steps to reproduce--

It's been like this since I downloaded it, and tried downloading it again.
### --Actual Results--

Inbetween button still doesn't show.
### --System Information--
+ OpenToonz Version:

Opentoonz 1.2.0 Dec 11 2017 Build
+ Operating System:

Windows 7 Enterprise

+ Other Device Info (Optional):
64 bit 
* RAM Size:  4GB

* Graphics Tablet:

WACOM Intuos P S

---

**Comment by artisteacher** [comment]
It looks like you have a Toonz Raster level selected. The Inbetween buttons are only available for Vector levels.

**Comment by Amikeyou** [comment]
Thank you, that was the problem.
I thought the tutorial I was watching was on a Toonz Raster level.

**Comment by RodneyBaker** [comment]
Glad you got it figured out.
Recommend closing this issue.

**Comment by shun-iwasawa** [comment]
I'll close this.
