### ISSUE TITLE
Awareness of "Sync Level Strip Drawing Number Changes with the Xsheet" option.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2060]
I think it is important to raise the awareness of this option, as its state could inadvertently affect the users expected results, after inserting new frames in a level already exposed in the Xsheet.

Can this options be either... :
- activated by default?
- include this option in Level Strip RMB menu?
and/or better yet
- include it as a state button in Level Strip header? (similar to the Palette "Active" one)

**Comment by artisteacher** [comment]
I think that as this option could have a really negative impact on some workflows, it probably shouldn't be set as default. Including the option in the context menu is definitely a good idea. I wouldn't put a button directly in the level strip header, but one could work directly to the side of the selected level dropdown. I'm not sure what the icon would look like...

**Comment by gab3d** [comment]
@artisteacher 
1. Would you please comment on the negative impact case you mention?
I'm interested on it, because as I see it normally, I tend to think the other way round to be most common (i.e. you think you have certain cells exposed in the Xsheet, but after inserting some new frames in the level, now that is changed without a notice about the fact).

2. As for the icon of a button for that feature, it could well be a chain or something along that lines.

**Comment by artisteacher** [comment]
There are several arguments against having this setting as a default in the original feature request #471.  One is potential confusion from inconsistency when using a level in multiple scenes. Another is that drawings are often deliberately placed in the Xsheet out of order (i.e.. lip-syncing or etc.) instead of consecutively. In that case, it could be really frustrating to have the drawing order change in the Xsheet if it wasn't intended.

**Comment by gab3d** [comment]
@artisteacher 
Thank for pointing to that discussion, I'd participated on it as well, and exposed very valid point for not currently being the default option.

In spite of that, about the second example you bring here, having the Sync option active when you insert a new frame in the level, is what helps you maintain intact what you've already done in the Xsheet (from a visual point of view), that is: the content of the frames exposed after the insertion are the exact same as they were before the insertion (albeit with a change in their numbers). Whereas in the opposite case (Sync disabled), you'd start seeing an expression shift in all frames already animated.

All in all, I think there are good cases for using both states of that option, and it would make both existing users' life easier and new users life less miserable ;) to have it readily visible in the interface.

**Comment by artisteacher** [comment]
@gab3d - you are totally right. 

I've been thinking about it and I think the command bar or even the Xsheet might be a better place for the button (since the preference changes an Xsheet behavior, not something in the Level Strip).

**Comment by gab3d** [comment]
@artisteacher 
yep, but since the change (the insertion of frames) is triggered from the Level Strip, I still think it to be a better place for the "remainder" (if the Sync mode is ON/OFF) to be placed in.
After all, it may well happen that in a certain (user created) Room the Xsheet would not be at display at all, at the moment of the new frame insertion.

**Comment by RodneyBaker** [comment]
Closing as an enhancment slipping to the 2019 development cycle.
