### ISSUE TITLE
Linked FX malfunction

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2061]
### --Issue Summary--
Adding Linked FXs to several colums does not work properly.

### --Steps to reproduce--
1. Select two columns (in my tests they were Vector ones)
2. Insert an FX to both columns
3. Activate Preview option in Viewer.
4. Change one of the FXs settings.
5. Watch as only one of the columns react to the change.
(always the same column, no matter which level settings is changed)

### --Actual Results--
only the first column reacts to changes.

### --Expected Results--
all of the columns with linked FXs should react accordingly.

### --System Information--
+ OpenToonz Version:
1.2.1 RC

+ Operating System:
Windows 10 Pro

**Comment by artisteacher** [comment]
I'm also seeing in OS X with linked FX. The FX preview in the swatch viewers look as expected & the values in the FX settings do change as expected. However, the preview in the viewer only displays properly after restarting & opening the saved scene.

**Comment by shun-iwasawa** [comment]
Confirmed this problem.
