### ISSUE TITLE
Tracker Tool points number not visible

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2062]
### --Issue Summary--
The number of the points created with the Tracker Tool aren't currently visible.
Note: If you change the active tool to Hook, the numbers become visible.

### --Steps to reproduce--
1. Create a level.
2. Activate the Tracker Tool
3. Create some points.
4. See how you can't view the points numbers. ;)

### --Actual Results--
Points numbers are not visible

### --Expected Results--
Points numbers visible.

### --System Information--
+ OpenToonz Version:
1.2.1 RC

+ Operating System:
Windows 10 Pro

+ Other Device Info (Optional):
* RAM Size  16GB
* Geforce GT650

**Comment by artisteacher** [comment]
I'm seeing this as well. There seems to be a grey rectangle near where the number should be - unless that is something else? Also the scale of the number/letter is really small on a high dpi screen.
<img width="176" alt="screen shot 2018-06-12 at 8 07 57 pm" src="https://user-images.githubusercontent.com/21159116/41323443-5c87aefc-6e7c-11e8-8db8-026f9b2d766e.png"><img width="112" alt="screen shot 2018-06-12 at 8 07 50 pm" src="https://user-images.githubusercontent.com/21159116/41323442-5c796892-6e7c-11e8-9940-98624314c73d.png">
