### ISSUE TITLE
Performance issue while saving/playing back

### ISSUE THREAD

**Issue by MightyWookie** [opentoonz/opentoonz#2064]
--Issue Summary--
Opentoonz takes up a lot of Memory/CPU when saving and playing it back after words.

--Steps to reproduce--
1)- Load Opentoonz and use the Ghibli Rooms.
2)- Create project
3)- Convert .tif images from GTS to a TLV and load it in Opentoonz.
4)- Save scene and press play in preview mode

--Actual Results--
After saving and playing back OT uses 40% CPU and 550MB Memory, but works normally once it plays back a second time.

--Expected Results--
The project should play normally after saving.

--System Information--
OpenToonz Version: 1.2
Operating System: Windows 10
Other Device Info: NVIDIA GTX 1060 and Intel Core i5
RAM Size: 8GB
Available Diskspace  481GB out of 918GB
UI Theme: Light

Graphics Tablet: Wacom Bamboo CTL-480

**Comment by artisteacher** [comment]
Is there any difference playing before saving?

**Comment by MightyWookie** [comment]
Not really. There is still a little lag before saving but not as much when i save the scene.

**Comment by konero** [comment]
Preview renders the frames, so it'll hit the CPU for a bit, that's normal.

After they're rendered they're cached, they can be played back at normal speed.

If you turn on preview and hit play, the scrub handle will turn green when it's rendering a frame.

![playhandle](https://user-images.githubusercontent.com/19820721/41254650-020e356a-6dbc-11e8-8d3d-6528a3850bef.png)

**Comment by MightyWookie** [comment]
Thanks for clearing things up. I wasn't sure this was a normal occurrence or not.
