### ISSUE TITLE
v1.2.1 RC (Two issues):  Pen delay/artifacting and refuses to draw for short strokes

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2066]
### --Issue Summary--
Drawing with Toonz Raster Levels has delay and screen artifacts not seen in prior releases.
This is likely a duplicate report but I am reporting because this is new with the Release Candidate.
The artifacts appear to increase/decrease along with increase/decrease of Smoothness setting.

### --Video or Image Reference--
(See attachment for image)

### --Steps to reproduce--
Draw with pen on canvas using Toonz Raster Level
Observe any inability to draw short strokes and/or visible artifacts left on screen from pen

### --Actual Results--
Strokes won't appear when the duration is short or the stroke very short
Artifacts of prior location of pen appear on screen in red

### --System Information--
+ OpenToonz Version:
v1.2.1 RC 2018/6/12

+ Operating System:
Windows 10
+ Other Device Info (Optional):

* RAM Size  16GB:

* Graphics Tablet:

I am trying to examine my pen settings now to determine what if anything might have changed.
![2issues](https://user-images.githubusercontent.com/2576432/41320763-ad5d5fae-6e66-11e8-834c-79cf3f9f1af2.png)

**Comment by RodneyBaker** [comment]
I've mostly resolved the two issue by tweaking every setting I could in OT until things worked.  The second issue with artifacting definitely seems to related to having the Smoothing settings set too high.  That also appears to effect the creation of the short strokes.

I'll leave this open for now as it may suggest other issues.

**Comment by artisteacher** [comment]
The artifacts look similar to #1950.

**Comment by shun-iwasawa** [comment]
I fixed the brush tip artifacts problem.
Regarding the delay of stroke with large smoothness value, it seems to be unavoidable behavior and I could not find any difference between RC version and the older versions.

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa!  I'm testing the fix now.

As for the delay stroke issue... I'll more thoroughly dig in to that.

**Comment by RodneyBaker** [comment]
I confirm that #2017 fixes the Brush Artifact issue and I can now apply full Smoothness without getting any artifacts.

The delayed stroke issue appears to relate to pen sensitivity so I'll explore that.
Very short strokes/lines won't draw but longer ones draw without issue.

**Comment by RodneyBaker** [comment]
A new observation...

I don't seem to get the remaining issue (that of short stroke lines not drawing on Toonz raster levels) when the Hardness setting is set to maximum value.

![hardnessissue](https://user-images.githubusercontent.com/2576432/41355038-235be610-6ee6-11e8-8f6c-6111b79152cf.png)

Using the same short stroke (covering a very small area) with Hardness set to 100 I get lines as I would expect to see.  With settings less than 100 I tend to get just the initial dot of the line (if anything at all).

**Comment by artisteacher** [comment]
Oh, that would explain why I didn't see the same problem before. The hardness value definitely has an impact on OS X too.

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thanks, now I could reproduce the problem!

**Comment by shun-iwasawa** [comment]
Fixed the short stroke issue and added to the PR #2071

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa !

I'll close this as soon as I can verify.
