### ISSUE TITLE
plastic tool slow performance

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2073]
when I use plastic tool the program become to slow and laggy
I dont no why 
and my laptop specs:
i5
6 gigabit ram
gtx 630m

do I nedd to get a better laptop or not

**Comment by RodneyBaker** [comment]
At 6GB I think I will suggest using the 32bit release.
The minimum for use with 64bit is in my estimate 8GB with 16GB recommended.

Here's the link to the 32bit release:  

https://morevnaproject.org/2017/06/05/opentoonz-32bit-available-download/

**Comment by animating-dino** [comment]
i download it and I use the files of sandbox of opentoonz 64 bit and it still laggy

**Comment by RodneyBaker** [comment]
Yes, with 6GB that will definitely hold you back.
A good portion of that 6BG is likely being used by your operating system and any other programs you ave running such as the browser and any of it's various windows/tabs you leave open.

You'll want to shut down everything you can to free up RAM.

**Comment by animating-dino** [comment]
when I open opentoon monerva project 
the problem is ((runtime error this application has requested the runtime to terminate it in an unusual way))
i don't know the problem in my computer or not
my operating system is (windows)
i reported this issues month ago but i cant fix it

**Comment by RodneyBaker** [comment]
You may want to address the issue to the folks that build the Morevna edition.
Their release usually gets updated immediately after an official release of the main branch of OpenToonz.
That official release should be in a week or so after the current release candidate has been thoroughly tested.

My memory says the runtime error was/is a known issue with the Morevna so they should have a fix for that.

**Comment by animating-dino** [comment]
OK thanks

**Comment by matitanimata** [comment]
I think this issue is the right place, there is actually a performance problem with plastic. I use a wacom companion 2 (i7 and 16 gb ram) or a mac pro (16gb ram) so this isn't an hardware requirements problem.
When I use plastic rigged characters OT becomes extremely slow and unresponsive, I did a test: the same scene in toonz 7.1 plays at 25/25 fps while in OT it runs at 2/25 fps.

![toonz7-1vsot1-2_2](https://user-images.githubusercontent.com/20012515/49327409-89f57d80-f561-11e8-8fe4-cb75d5b7da30.gif)

**Comment by RodneyBaker** [comment]
Several fixes to plastic tool have been implemented since this issue was reported.  Ref:  #2123, #2147, #1864 (and others)  Recommend using a recently nightly release to resolve related problems.
