### ISSUE TITLE
I have a slight delay when I switch to raster level

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2075]
### --Issue Summary--

The passage from levels toonz to another is without delay. But moving from a toonz level to a raster level has a delay.

### --Steps to reproduce--

Create 3 levels with the two toonz levels and a raster, then switch between toonz levels to raster.

### --Actual Results--

Slight delay with raster level

### --Expected Results--

switch whitout delay like others toonz levels

### --System Information--
+ OpenToonz Version:

OT RC 1.2.1 

+ Operating System:

windows 10

+ Other Device Info (Optional):

* RAM Size   8GB

* Graphics Tablet:

cintiq companion 2

---

**Comment by RodneyBaker** [comment]
Just in case... make sure you haven't changed your first two color swatches in the palette to MyPaint brushes.

**Comment by openanim** [comment]
Yes, that was it. I just realized that the editor style was not in auto mode my brush remained on Mypaint. Thanks !! I close the problem.
