### ISSUE TITLE
opentoonz crash 

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2076]
when I  am using opentoonz, I  got a problem than it crash the crash is.....
![3](https://user-images.githubusercontent.com/39278532/41383771-a607194a-6f72-11e8-8cd6-bb8afcbeb3d5.PNG)

it crashed when I am using preview mode

**Comment by gab3d** [comment]
...and I see you also have the Edit in Context button active in the Xsheet.

**Comment by animating-dino** [comment]
what is the function of that

**Comment by artisteacher** [comment]
When a sub-Xsheet is open, it allows you to see the entire scene while you are editing sun-Xsheet levels. If that function is off & the sub-Xsheet is open, you only see the levels in the sub-Xsheet and nothing from the containing scene.

**Comment by animating-dino** [comment]
and it caused the crash or not

**Comment by artisteacher** [comment]
It’s hard to say what caused it without more information. Are there any repeatable steps that always cause the crash? What were you doing before using preview?

**Comment by animating-dino** [comment]
I just open preview move skeleton of plastic tool it crash but I see this crash random

**Comment by animating-dino** [comment]
does i have to download microsoft visuals 2015,2015 82 bit or 64 only

**Comment by gab3d** [comment]
I can't reproduce your crash.
tried to replicate your conditions, preview ON, animate plastic vertices, even with subXsheets. it worked fine for me.

**Comment by animating-dino** [comment]
I just get another crash when i use preview mode i dont know problem with my os or program and 


it's random look at image

![capture](https://user-images.githubusercontent.com/39278532/41389100-45dc3100-6f8f-11e8-9cf0-454c068eb26c.PNG)
and

**Comment by gab3d** [comment]
...perhaps could be something related to OpenGL and your system.
Have you tried upgrading your graphics card drivers to the latest ones?

**Comment by konero** [comment]
I noticed you had a torrent client and CCleaner installed, get rid of them as they can corrupt your Windows installation. Get rid of any other riskware/crapware you may have. You can run a scan of [Emsisoft Emergency Kit](https://www.emsisoft.com/en/software/eek/) to check for any malware.

The faulting module `kernel32.dll` is not a good sign, check [this link](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/random-application-crashes-related-to-kernel32dll/be4b8ce6-151f-4be3-9bbe-f0621e0c2bdf) for a possible solution.

You can try running a Windows integrity check using the `sfc /scannow` and `DISM /Online /Cleanup-Image /RestoreHealth` commands in CMD prompt run as Admin, [click here](https://www.howtogeek.com/222532/how-to-repair-corrupted-windows-system-files-with-the-sfc-and-dism-commands/), and [here](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system) for more info.

**Comment by animating-dino** [comment]
I delete utorrent clean master 
but i cant relace kernal32 because it open in csrss

**Comment by artisteacher** [comment]
I know you’ve heard this before, but once you’ve removed everything that you need to remove, you should probably try a clean install of the most up to date version of OT. Uninstall OT first, rename the stuff folder, & then run the install. You can copy your original projects into the new Stuff folder. I used to have pretty regular crashes if I tried to animate with both the plastic tool and preview active. A completely clean install ended up stopping the crashes in my case. 

On a possibly related note, do you happen to have any FX applied to any levels in your scene? I get much more regular yet still sporadic crashes when I’ve been using FX & preview.

**Comment by animating-dino** [comment]
I reinstall my windows thank you .
