### ISSUE TITLE
opentoonz problems with importing svg

### ISSUE THREAD

**Issue by oladitan** [opentoonz/opentoonz#2078]
### Issue Summary

for simple shapes everything seems to work fine. I think its a great way to import a pallet.

for more complex object there are various issues:

weird swelling tips at lines
impossible to fill shapes

### Screenshot or Video Reference

there is more detail in [THIS VIDEO](https://www.youtube.com/watch?v=HjRYNwc-0RI)

### Expected Results

I import an svg with just lines and fills

open toonz converts and fills as they apear in the svg

### System Information
* **OpenToonz Version**: 
june 5 opentoonz 1.2
* **Operating System**: 
64 bit windows 7 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
This looks like #119 and #1009. Reliable svg import certainly would be helpful.

**Comment by RodneyBaker** [comment]
Until such a time as someone can dedicate themselves to SVG development...
There are a few know workarounds to some of the SVG issues.

One of them... that deals with bulbs on the end of lines or strange thicknesses is as follows:

- Immediately upon importing/converting the SVG select the entire thing and make note of the line thickness appearing in OT's UI.  Remember that value.

- Change the value to 0 (to reset the line/scale factor of line thickness

- Reenter the value

This should give you acceptable lines to work with.

**Comment by artisteacher** [comment]
Recommend closing & posting further in the pre-existing  issues.
