### ISSUE TITLE
Some of the menu bar is hidden

### ISSUE THREAD

**Issue by Qggh** [opentoonz/opentoonz#2079]
### Issue Summary
I don't see whole menu bar

### Screenshot or Video Reference
![2018-06-14 2 _li](https://user-images.githubusercontent.com/36899777/41436594-d7e89e80-702a-11e8-9821-9088ee92221c.jpg)

### Steps to Reproduce
This issue wasn't in the previous version [1.2.0]
(in the previous version The menu was on the left side
And the rooms on the right )

### Expected Results
see the whole menu bar 

### Actual Results
Some of the menu bar is hidden

### System Information
OpenToonz Version: v1.2.1rc
Operating System: windows 10
CPU: intel core i7-5500
Memory: 8 gb
Graphics Card: INTEL HD GRAPHICS 5500

**Comment by shun-iwasawa** [comment]
Tthe layout mirroring does not occur on my environment.
According to the [Qt documentation](http://doc.qt.io/qt-5/qguiapplication.html#layoutDirection-prop) the default layout direction of the interface depends on the application's language. Are you working on right-to-left language environment such as Arabic, Hebrew, Persian or Urdu?

**Comment by Qggh** [comment]
yes. 
hebrew.
![2018-07-03 2](https://user-images.githubusercontent.com/36899777/42239219-f4feb19a-7f0b-11e8-8d27-5aa16a6f39b2.png)

**Comment by shun-iwasawa** [comment]
@Qggh Thank you for the info.
Then I'll try to force OT to have left-to-right layout direction in any language environment, since for now OT seems not yet to be compatible with right-to-left layout in many parts.
