### ISSUE TITLE
Collect Assets does not update path

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2082]
### Issue Summary

The collect assets command in the Browser imports the assets into the relevant directory but the path to the asset does not update. According to the Harlequin manual, the path is supposed to update. It is possible that this is MacOs specific. 
### Steps to Reproduce

1. In the Browser, load a scene from another project (select import)
2. Save the scene
3. In the Browser, right click on the scene & select “Collect Assets”
4. In the scene cast or through the level menu, look at the path for one of the levels in “Info” or “Level Settings”

Levels import but the paths do not change from the original location - even after saving, closing & reopening.
### Expected Results

I expect the level (or etc.) to import into the project & in that project for the path of that level to update to the new imported location. 
### Actual Results

The level or other asset does  import but the path for that resource does not change (ie. if a level was originally in another project, the path continues to reference the old project & does not update to reference the new project)
### System Information
* **OpenToonz Version**: RC - but this has been happening for a long time 
* **Operating System**: 10.13.5
* **CPU**: Intel Core i7
* **Memory**: 16GB
* **Graphics Card**: Radeon Pro 460 & Intel HD Graphics 530
* **Graphics Tablet**:

**Comment by shun-iwasawa** [comment]
`Collect Assets` changes the scene FILE selected in the file browser, but for now it is not reflected to the current scene even if you are opening the same scene.
Please try re-open the same scene after using `Collect Assets`. I tested & confirmed that it works OK on both Win and OSX.

**Comment by artisteacher** [comment]
Oh, so this only works when a different scene is open? I can get this to work when a different scene is active. However, when using "Collect Assets" on an open scene, the assets are imported but the paths do not update - even upon reopening.  I think that it's expected for "Collect Assets" to update the paths in an open scene as well.

**Comment by shun-iwasawa** [comment]
@artisteacher 

> However, when using "Collect Assets" on an open scene, the assets are imported but the paths do not update - even upon reopening.

Hmm. I couldn't reproduce that situation. I just did like as follows:

1.  In the Browser, load a scene from another project (select import)
    - I tested to import a scene from "test" project to "sandbox". After import, the level path becomes like `C:\OpenToonz 1.2 stuff\projects\test\drawings\A.pli` .
1.  Save the scene
1.  In the Browser, right click on the scene & select “Collect Assets”
    - The levels are imported and the selected scene **file** is updated.
    - Note that the level path in the current scene does not change.
1.  **Reopen the scene. In the Browser right click on the same scene & select "Load Scene"**
    - If the scene has been changed (having scene name with asterisk in the title bar) , make sure to discard such changes or you will overwrite the level paths with old ones before opening the scene file. 
1.  In the scene cast or through the level menu, look at the path for one of the levels in “Info” or “Level Settings”
    - The level path becomes like `+drawings\A.pli`.

Please let me know if I miss something.

**Comment by artisteacher** [comment]
Oh, I’ve been saving before reopening. Reopening the scene without saving does result in the correct paths. So if you need to save the scene, it needs to happen before using collect assets. I do think it would be better for saving not to overwrite the new paths with the old paths but I’ll close this issue since it does work.

**Comment by manongjohn** [comment]
It would be nicer and cleaner if the Load Scene Dialog had a checkbox to "Collect Assets Immediately" to be used only with the "Import Scene" or maybe a 3rd button to "Import Scene and Collect Assets" to simplify this process. :)
