### ISSUE TITLE
Can't click and drag a key on the timeline or xsheet

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2086]
### Issue Summary

To move a key on the timeline/xsheet you have to click it once, then release, then you can click and drag it to move it.

### Expected Results

I'd expect to just click and drag it. It's what you'd expect from the UI.

### Actual Results

Clicking and dragging just selects the key. You've then got to move your pen from the tablet and click and drag again. And if you do that too fast the function editor appears on screen and gets in the way! This happens with the mouse too, so isn't a tablet issue.

### System Information
* **OpenToonz Version**: 
I'm using V1.2, but it's happened with all versions
* **Operating System**: 
Windows 10

**Comment by artisteacher** [comment]
I've run into this as well in MacOS. I agree that clicking & dragging a key should work immediately - without needing a click & release first.

**Comment by beeheemooth** [comment]
I also thought about this. But in what way can you drag a few keys in different columns ?

**Comment by artisteacher** [comment]
You can use shift-left-click to select multiple keys or ctrl-left-click. I hadn’t realized it was doing a box-select to grab multiple keys. Gosh, the drag to select is also an expected behavior in OpenToonz. Maybe that behavior should replace the current shift-click behavior?

**Comment by DarrenTAnims** [comment]
Yes, you can use shift, ctrl or right click to select multiple and move them. That works fine. But it'd be handy (and obvious) to be able to just grab one and move it. without selecting, releasing, dragging.

**Comment by RodneyBaker** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
