### ISSUE TITLE
Style # 1 color does not get updated when you apply a new color to it (raster levels)

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#209]
using nightly build https://github.com/opentoonz/opentoonz/releases/tag/nightly
 nightly
 7f1cbfc

expected result: the scribble you drew changes color when you change the color of the style it is using.
current result: color does not change at all.

to reproduce:

1.. create a raster level or a toonz raster level
2.. Select style 1 and scribble something

it should be black when you start, but sometimes the brush draws in red for some reason, even though the style#1's starting color is obviously black.
![stylebug](https://cloud.githubusercontent.com/assets/6495061/14680397/144a5c8c-0715-11e6-9f2b-1ac608066821.JPG)

3.. now go to the style editor window> plain and change the black color of style#1 to something else.
4.. Hit apply 

Nothing happens

5.. toggle on auto apply and change it again

nothing happens

6.. Draw with the brush again 

 still the old black color we started with and not the one you specified

7..create a new drawing (frame)  and scribble on it
- some times it keeps the old first color, 
- some times it uses the current color you have, but when you change it, it doesnt change it on the canvas. So the brush can change color, but the old lines you drew dont  (this could be a useful optional behavior - but in this case its a bug because some times you cant change the color of the brush you are drawing with)

8.. Create a new style (style#2) and try to repeat all steps 
- everything seems to work as normal

**Comment by blurymind** [comment]
not sure if a bug or desired behavior

**Comment by Rayek** [comment]
This works as expected for Toonz raster levels. Regular raster levels do not support this - that is expected behaviour.

**Comment by blurymind** [comment]
@Rayek I am sure that it happened to me with opentoonz raster layer as well for some reason. But now I downloaded the latest nightly build again, erased my opentoonzstuff folder just in case and reinstalled. 

The problem seems to be gone now - so I will close this.
