### ISSUE TITLE
clone subxsheet beahvior

### ISSUE THREAD

**Issue by matitanimata** [opentoonz/opentoonz#2093]
### Issue Summary
EDIT:
the "clone subxsheet" command creates a new subxsheet independent from the original, but, if has other subxsheets inside, those subxsheets won't be cloned. 

### Steps to Reproduce
create a subxsheet 1
create a subxsheet 2 inside 1
cloning sub 1 I wish to clone also the sub 2 that is inside 1, but it won't, if you open and edit the cloned
sub 2 also the original one will be modified.

### Expected Results
I wish to modify the cloned subxsheet and all the stuff  that is inside it (subxsheets included) to create a new version of the original animation (that I want to keep as it is). This is what "clone subxsheet" do in toonz harlequin.

### Actual Results
modifying the cloned sub 2 also the original is modified.

### System Information
* **OpenToonz Version**: 1.2
* **Operating System**: win 10
wacom companion 2
intel i7 - 8gb ram

**Comment by matitanimata** [comment]
thanks for your reply, tried now on the latest version and it seems to work fine also to me, but I swear it didn't, I was quite sure, I'll try to understand what happened.

**Comment by manongjohn** [comment]
What was meant by "modify"?

I took this as modifying the drawing in the sub xsheet by modifying the image, not changing the animation. In this case, altering the image in one sub xsheet alters it in the other because the same level is shared, not copied into new independent levels.

**Comment by matitanimata** [comment]
I think I've understood when the clone subxsheet fails to work as I expected: 
create a subxsheet 1 
create a subxsheet 2 inside 1
cloning sub 1 I wish to clone also the sub 2 that is inside 1, but it won't, if you open and edit the cloned
sub 2 also the original one will be modified. 

![clonesubxsheet](https://user-images.githubusercontent.com/20012515/41782997-1464bc9c-763c-11e8-82b3-264ab10cc90a.gif)

**Comment by turtletooth** [comment]
I'm not sure that would be a bug.  If the instance of xsheet 1 has a reference to xsheet 2, then the clone would naturally also contain a reference to xsheet 2.  

I think this would fall more into a feature request for a deep clone option.

What do you think?

**Comment by matitanimata** [comment]
I think the "deep clone option" would be used in most of the cases. If I need to clone a subxsheet I wish to clone all the stuff inside it, I can't imagine a situation in which I would clone a subxsheet but not the subxsheets inside it. I've just checked: in Toonz Harlequin works in this way so I think it could be considered a bug of OT?

**Comment by turtletooth** [comment]
Thanks for checking Harlequin.  I don't have access to it, so I didn't know that.  I bet it is a change made by Ghibli.  Perhaps @shun-iwasawa knows about the history here.

**Comment by matitanimata** [comment]
here is a test done in Harlequin, the grandma sub contains another sub with a dog.
we've cloned the grandma sub then we have modified the dog inside the second sub, in the original sub the dog remains the same.
![clonesubxsheet](https://user-images.githubusercontent.com/20012515/41789187-c22b0aa4-764e-11e8-9176-306e7c6f6225.gif)

**Comment by shun-iwasawa** [comment]
@matitanimata 
Thank you for notifying it. Now I remember that I changed the behavior not to deep copy by commented out [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/columncommand.cpp#L1074-L1077).  The change was made based on a request from Studio Ghibli but for now I agree it can be preference-optional.

**Comment by matitanimata** [comment]
that would be great, thank you @shun-iwasawa

**Comment by gab3d** [comment]
@shun-iwasawa
I think the best place for this option would be in the Clone dialog that opens just before applying the operation.

**Comment by matitanimata** [comment]
I agree, good idea
