### ISSUE TITLE
Glitches with new Toonz Raster frames

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2095]
### Issue Summary

Drawing a new frame in a Toonz Raster level has 2 visual glitches in the viewer. New frames display with white backgrounds or partially white backgrounds when the level strip is active.

### Screenshot or Video Reference

![screen shot 2018-06-21 at 2 25 33 pm](https://user-images.githubusercontent.com/21159116/41738284-9bc03c58-755f-11e8-883a-7b4900a2af94.png)
### Steps to Reproduce

1. Create a scene with a Toonz Raster level
2. Draw a couple of frames with the Xsheet active
3. Select the last frame in the level strip and see a white background
4. Add a new frame with the level strip still active (using the down arrow to begin a new frame)
5. As you draw, you should see pixelated areas of white around the stroke
### Expected Results

The viewer should stay gray without any white when the level strip is active unless a different background color has been set.
### Actual Results

1. If the new frame is created with the Xsheet active, then the viewer background displays as white when the frame is selected in the level strip. 

2. If the new frame is drawn with the level strip active, then pixelated white blocks follow the stroke. After the cursor leaves the viewer, the entire viewer turns white.
### System Information
* **OpenToonz Version**: RC1 & RC2
* **Operating System**: 10.13.5
* **CPU**: Intel Core i5
* **Memory**: 8GB
* **Graphics Card**: Intel HD Graphics 3000
* **Graphics Tablet**:

**Comment by shun-iwasawa** [comment]
Thank you for reporting! Confirmed the problem.

For now Toonz Raster Level shows white background when the levels trip frame is selected. This behavior was originally requested by Studio Ghibli and is not a bug. I think it would be nice to make the background color adjustable via user preferences, but it will be a separate improvement in the future.

I'll modify the problem with viewer update behavior which only updates around the stroke.

**Comment by artisteacher** [comment]
That was fast! I do think that the background of the viewer when the level strip is active should be consistent for all level types.

**Comment by konero** [comment]
Just to chime in, I posted an issue a long time ago about the white background color in this case ( #1061 ).

**Comment by gab3d** [comment]
I also think it's strange to get that color change when level strip is selected, and it'd be very nice to let users select the background color in preferences (currently it can be changed, but it affects the Table color too, which is annoying)

**Comment by artisteacher** [comment]
The color change can be confusing but is also a good visual cue that you are looking at the level itself without the larger scene. Having a different behavior for toonz raster levels makes it way more confusing though. When it’s possible, it would be great to have one preference to change the background of the viewer for all levels wh the Xsheet is active, another preference to change the viewer background of all levels when the level strip is active, and perhaps a checkbox to “use Xsheet background color when level strip is active.” That way if someone wanted to set a custom color for both, they’d only have to set the color once.

**Comment by gab3d** [comment]
There are other ways to give users a clue of what they are looking at, not necesarilly being a background color change. Some alternatives could be:

- a small "Level" overlay at one corner of the viewer.
- some kind of graphical element (i.e. a frame around the viewer border.

Also, I dont think Toonz Raster levels should have a different treatment regarding this matter.
