### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by rugk** [opentoonz/opentoonz#2098]
It would be great to get a flatpak version, which can be installed on all major Linux distros.

https://github.com/morevnaproject/opentoonz/issues/11

**Comment by RodneyBaker** [comment]
Congratulations!

**Comment by gab3d** [comment]
it´s weird the image shown is from GTS, not OpenToonz.

**Comment by eszlari** [comment]
> it´s weird the image shown is from GTS, not OpenToonz.

Are there some official screenshots (hosted by the developers)?

**Comment by shun-iwasawa** [comment]
Thank you @eszlari for your great work!

> Are there some official screenshots (hosted by the developers)?

How about this? It's a screenshot of the previous version (v1.2.0) but I made this for official announcement of the release of [sample data](https://opentoonz.github.io/e/download/sample.html).

![sample_scene](https://user-images.githubusercontent.com/17974955/42545482-35d0d346-84f3-11e8-9669-8d6d772be955.png)

**Comment by RodneyBaker** [comment]
https://user-images.githubusercontent.com/2576432/49324458-bc689180-f4f3-11e8-8e9d-09ae91d531b9.png
