### ISSUE TITLE
Get it into Linux distro's

### ISSUE THREAD

**Issue by rugk** [opentoonz/opentoonz#2099]
It would be great if you could get it into the major Linux distro's as official packages.

ref https://github.com/morevnaproject/opentoonz/issues/10

**Comment by rugk** [comment]
Is this fixed or what? @RodneyBaker

**Comment by RodneyBaker** [comment]
@rugk  What exactly needs to be fixed?

'Getting into Linux distros' is a bit too broad a category for a bug report.
As far as development goes I agree that promoting OpenToonz by charting a path to inclusion in linux distributions would be a worthy goal.

**Comment by rugk** [comment]
Yeah, I never said it is an easy issue (but it got two upvotes already)… What you can do as an upstream dev is trying to convince package owners/someone else/contributors to support it/bring it there.

It's just about initiating the process/helping there.
What you could e.g. do is keep a ticklist of the (bigger) distros, where you'd like to see it being added and tick it, if it is there.e Then you can direct contributors here or so and suggest them to help by adding it to their favorite/any distro.

I admit, it's no bug and "fix" is certainly the wrong term here. :smile: It's much more (a) meta(-ticket)… :wink:

**Comment by RodneyBaker** [comment]
We need to get all of our various Linux people to champion this and other issues near and dear to the heart and to chart the way forward.  I can't see why anyone would be against having OpenToonz be in linux distros.

One frustration other Linux users have related is the lack of support and promotion for Linux distributions.  I'm confident much of this can and will be resolved in 2019.

We have a somewhat similar situation with Mac specific related issues.  We can always use more people testing and verifying and giving feedback.

**Comment by RodneyBaker** [comment]
OpenToonz is listed on the Flatpak site.
Unfortunately it doesn't appear on the first page of applications so it might be easily missed.

https://flathub.org/apps/search/opentoonz
