### ISSUE TITLE
Provide a way to verify Opentoonz morevna edition download.

### ISSUE THREAD

**Issue by WPFilmmaker** [opentoonz/opentoonz#2104]
Apologies if this is not the right place, but it seems like there is no specify place to discuss about this edition. I would like to request a way to verify the download files which are downloaded from Sourceforge. A Sha256sum or GPG would be great.

**Comment by RodneyBaker** [comment]
I'd imagine you'll have to contact the folks that have forked OpenToonz to the Morevna Edition for that.

Perhaps you can open an issue via their github site:

https://github.com/morevnaproject/morevna-builds/issues

**Comment by artisteacher** [comment]
@morevnaproject, this one’s for you.
