### ISSUE TITLE
OpenGL and OpenCL to be deprecated on Mac

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2106]
### Issue Summary

It looks like OpenGL and OpenCL are both going to be [deprecated](https://developer.apple.com/macos/whats-new/) on MacOS in 10.14 (Mojave).  They should still be usable for a while, but at some point continued support for MacOS probably means using Metal for MacOS instead.  @shun-iwasawa, what are your thoughts on this?

**Comment by shun-iwasawa** [comment]
Transition to Metal from scratch by ourselves will be very tough.
I'm hoping Qt team will take some measures or publish some guideline in the future.

**Comment by artisteacher** [comment]
I’m glad it will be supported!

**Comment by jpturcotte** [comment]
I am happy to hear this as well.

@shun-iwasawa Are the new [pointers handlers](https://blog.qt.io/blog/2017/11/23/say-hello-qt-quick-pointer-handlers/) of any use to simplify and improve touch and tablet support?

**Comment by RodneyBaker** [comment]
Closing as informational with confirmation that Qt 5.12 supports metal for Mac OS.
