### ISSUE TITLE
(WIP) Fullscreen:  Black combo viewer

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2109]
### Issue Summary

This is not a very urgent matter but just to report, I have this command on my command bar it does not work properly, the viewer as well as the editor style are black when i toggle. When the command is hidden behind the double arrow of command bar it may be that the screen freezes, sometimes it is the entire computer that requires a manual start. Nevertheless, the command works on my other computer but with different application dpi.

### Screenshot or Video Reference

It seems that when I make a screenshot, everything is normal. The computer detects that the canvas is white even if I have a black display.

### Steps to Reproduce
Create commande bar with this command

### System Information
* **OpenToonz Version**: 
last
* **Operating System**: 
windows 10
* **CPU**: 
* **Memory**: 
8g
* **Graphics Card**: 
5100 hd graphics
* **Graphics Tablet**: 
cintiq companion

**Comment by artisteacher** [comment]
In MacOS, I’m getting a black flash before entering or exting fullscreen but then the program displays as expected.

**Comment by gab3d** [comment]
Well I can confirm this on my notebook (HP i7 16GB RAM, Geforce GT650M, Windows 10).
When I put the program on Full Screen mode using the shortcut Ctrl + ` the viewer, the level strip and the style editor goes black, the mouse cursor y lost too.
When I press the shortcut again and go out of full screen mode, all returns to normality.

Also confirm that when I try to do a screen capture, the capture shows everything normal (this is strange!).

**Comment by loris16148** [comment]
I can also confirm this error on Toshiba i7 8GB ram, intel intergrated graphics, windows 8.1

**Comment by Heroblah** [comment]
Having this issue, only when I try to open and menus like File or Edit, I cannot see anything. Almost as if the errored version of Opentoonz has overlayed the ok version.

**Comment by RodneyBaker** [comment]
A persistent issue that is moving to the 2019 Development Cycle.
Tagged with 'roadmap'.

**Comment by RodneyBaker** [comment]
@openanim With recent PRs fixing similar problems... has this issue been resolved?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@openanim please let us know if you are still experiencing this issue with current releases.

**Comment by openanim** [comment]
@RodneyBaker This has also been resolved.
