### ISSUE TITLE
Light delay with my paint brushes

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2110]
### Issue Summary

I feel a clear improvement with better response for my paintbrushes it's more fluid. However the first stroke of a pencil, has a slight delay on the canvas, the following do not have it (this happens after opening OT.). It would be nice to be able to remove it for better drawing experience.it is very light but quite noticeable when you give the first stroke.

By the way Big thank you to the entire development team for the great work done and the release of the new version !
### Steps to Reproduce

Create raster level and draw with my paint brush after opening OT 
### Expected Results

No delay
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
I'll guess that delay is because OT has to actually create the (empty) frame prior to placing the stroke on it.
To test this theory you could:

- New Scene
- Create a new (empty) frame (you may need to draw a stroke and then delete it to get the actual frame)
- Save Level as "(empty) level.tlv"
- Save Scene As "(empty) scene.tnz"

Now you will have an empty scene that has an empty frame to choose from when the Startup Popup appears.  

- Select/Open this empty scene and attempt to draw noting if the delay is or is not still present for the initial stroke.

**Comment by RodneyBaker** [comment]
In reconsidering this... while a similar thing could be happening, the fact that this is MyPaint related would likely point to something else, perhaps related to actually activating the brush.

**Comment by openanim** [comment]
I also think it's related to mypaint brush since this is also the case of #2075 if you remember (I wonder if I should not re-open it) .Because in my environment, the last OTX version seems to work without delay in the cases mentioned above.

**Comment by openanim** [comment]
@RodneyBaker 

I ended up deleting my file Opentoonz stuff, to see if it could be related, I still do not know where the problem comes from but I do not have this delay anymore. I strongly suspect, the manual addition of mypaint brush brushes that I had previously made to be the cause related to #2014 Did you also have this pack during your test?

**Comment by RodneyBaker** [comment]
@openanim If you are no longer having this problem this issue can be closed.
We can reopen a new one if we discover root causes for slow down and reference this one.
Or if it can be shown to relate to #2014 we can address it there also.

To answer your question... no... I routinely only use the default brushes that come with OpenToonz installers.  I will look again at those other brushes however.  I do think that before adding too many more MyPaint brushes we may need to investigate how to organize them inside OT a little more efficiently but... that's a feature request for some other time.

**Comment by openanim** [comment]
The problem is still there, the delay is even more important than before. It is related to brush rasters, but difficult for me to know the cause. When I test on a "clean" version of OT. The problem is not there. But after a while of using the brushes, he comes back. But it's especially noticeable when creating an automatic level. Once it's created, it's fluid. But it's impossible to draw the first stroke, correctly in autocreation enabled. 

I do not think it's related to manually adding new brushes, finally. Because I had the same symptoms on the normal configuration. Yes, the problem can be closed, the time to know the exact cause.
