### ISSUE TITLE
Display issue with a raster and vector column.

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2112]
### Issue Summary

I have two columns, one raster with 8 images with low opacity and the other column is a vector level for the lineart of my images. After a few linearts I notice a performance issue, slow, bad display for onoion skin and (guided drawing when enabled) same with the  green snap brush . I do not know if it is reproducible  but it happens to me frequently.

### Screenshot or Video Reference

![issue raster vector](https://user-images.githubusercontent.com/29790512/42066776-c73e014c-7b42-11e8-9070-d27e4a67654c.gif)

### Steps to Reproduce

1- create low opacity raster level with images ( i have 8 images on my exemple)
2 - create vector level for lineart
3- begin the lineart level after level and fly with your brush your work area, then  observe the behavior of the viewer, the brush, onion skin, guided drawing. This seems to affect the entire viewer in fact. The pc becomes slow too.

### System Information
* **OpenToonz Version**: 
Last
* **Operating System**: 
W10
* **CPU**: 
* **Memory**: 
8g
* **Graphics Card**: 
hd graphics 5100 
* **Graphics Tablet**: 
Cintiq companion

**Comment by manongjohn** [comment]
This is the same as #2016 it seems.

**Comment by openanim** [comment]
Probably, I think the performance part is similar but I also have a problem in the viewer update, the problem can appear with only one image per column, every time I try to do a lineart, it becomes complicated to continue. Should I close this issue and check once the other problem is resolved ?

**Comment by shun-iwasawa** [comment]
Confirmed the viewer update problem. It occurs when activating the onion skin via shortcut key while moving the cursor with brush tool being selected.
