### ISSUE TITLE
Levels lost:  0 byte files created when Projects Settings append options on (?)

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2117]
### Issue Summary
0 byte files are being created after importing files (confirmed for now with avi file).
The cause appears to be that the Append options are toggled on in Project Settings.
This causes OpenToonz to append an incorrectly named scene file (the untitled+# designation) instead of the current scene name.  When the scene is reloaded (or OpenToonz restarted) the referenced file cannot be loaded (presumably because while present at the location it is a 0 byte file with no data.

![project settings](https://user-images.githubusercontent.com/2576432/42120166-4e9903be-7bdc-11e8-9c04-075a608e107c.png)
 
### Steps to Reproduce
- Create a new Scene
- Go to File > Project Settings and ensure the Append options are checked (see image).
- Right Click on a cell in the xsheet and Load an AVI file
- Save the Scene with a useful name
- Save All for good measure (and to ensure Levels get saved)
- Shut down OpenToonz
- Restart and load the previously saved Scene
The referenced AVI file should not load and red entries should appear in the xsheet

When the Append options are off in Project Settings the Scene is saved and load as expected.

### System Information
OT version 1.2.1 (latest release)
Windows 10

**Comment by konero** [comment]
I can't reproduce this. Here's what I did...

1. new project > name it > append all > set as default setting
2. new scene > save it
3. drag an mp4 file into the viewer
4. save all, close app, reload scene
5. loads fine

You need to make sure you save the scene before doing anything else, that was the correct way to work in Toonz Harlequin, append won't work otherwise because it doesn't know your scenepath since you haven't created one yet, how will Toonz know where to import to otherwise?

**Comment by RodneyBaker** [comment]
I'm not sure how bad a process that would be.  The shortened version:
Create Project/Scene
Import media (Levels)
Save Project/Scene
Exit

That seems like a very normal way of working in any software.

> You need to make sure you save the scene before doing anything else,

If that is the case.. and it is... the Scene should immediately save itself upon initial creation.
It seems odd to me that creating a scene and making sure it is a solid foundation to build upon would be an extra undocumented step for the user to go through.  Allowing files to be lost despite the user diligently using Saving/Saving As/Saving All.  Something isn't right here.

I'm trying to imagine a case where saving the (empty) scene upon initial creation would be a bad thing. 
I do know that saving the Scene file upon creation would resolve other issues as well (to include that of autosave popping up to ask the user to name the file before it can initiate autosaving... and this after the user has previously entered a name upon creating the scene (via Startup Popup).  

Saving data is the first and best way to safeguard data.  That safeguard must also allow for user error.

But... even given all that... OpenToonz should never generate 0 byte files.   Not without communicating that to the user.   Perhaps a dialog box that engages the user with, "Seriously dude.  You just created  "filename.extension" as a 0 byte file.  You may want to reconsider your workflow."  ;)

We probably should run through a few workflow sessions to iron out some of the rough edges of workflow.  I must assume the average user may create a new scene (via the Startup Popup) using the default 'sandbox' project.   So, I suspect many users aren't creating a new Project right out of the gate.   I know for sketching purposes I just open OpenToonz with the defaults and try to get to work. For what it's worth I believe I can agree with your stated steps in establishing a solid project.   I just don't see anywhere in OT that would suggest that particular step by step process to a new or even average user.  Experience has taught you how not to lose data.  Having said that, I'm not sure we should continue to pursue an approach that suggests to the user... keep losing files until you figure it out for yourself.  

Things are going pretty smoothly these days and lost files have been rare in my experience (although unfortunately a bit more common of late).  Just a little more attention to the matter and perhaps we can resolve the underlying issues that lead users to lose data.

I will reiterate that it appears to me that several issues may be resolved if the (empty) Scene file is immediately saved upon creation rather than waiting for and relying on a manual save (or autosave) that may or may not work.

**Comment by jpturcotte** [comment]
I completely agree with @RodneyBaker on this. What we have currently does not make sense.

**Comment by artisteacher** [comment]
I agree that importing should work properly whether the scene is saved or not - though I would always save the scene first myself. This reminds me a little of #2082 - I wonder if they are related at all. In that case, if you save an open scene after collecting its assets, the new asset path gets overwritten with the old one.

 I’m not sure I want the empty scene saved upon creation. When you open OT, there’s always an empty scene for the current project. What if you are changing projects or loading another scene? Would you end up with an unused scene saved each time you open OT? What if you want to give that scene a name?  What if you are just doing a quick test that you’re planning on discarding?

I think the loading/importing logic just needs some adjustment. It’s interesting that you can create levels in an unsaved scene without having similar issues. How are those treated differently? Personally, I think I’d place everything for the unsaved scene (& have all paths) in a temp folder. Upon saving, the assets would be moved to the correct location & the temp folder paths would be overwritten to use the new location.

**Comment by RodneyBaker** [comment]
I wonder if multiplying by a DPI of 0 (when no DPI is specified in an image) might be the cause of the 0 byte images OpenToonz is creating.

Please reference:
https://github.com/opentoonz/opentoonz/pull/338/commits/15f40d8f69e9c7f500766a93a6ee56664801ed18#diff-ffe5ec4d80ae4d65ef1655b84c507b78R395

@shun-iwasawa is that a likely possibility?

**Comment by RodneyBaker** [comment]
#2225 appears to have resolved this issue.
I'll do some more checking and if I can't replicate the problem will close this issue.

@shun-iwasawa thank you!

**Comment by RodneyBaker** [comment]
Closing as I can no longer replicate the issue.
