### ISSUE TITLE
Crash when using Vector Brush Frame Range with thickness 0 (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2118]
That crash happens only when you use the Brush Tool with a thickness 0

1. Draw first stroke
2. Go to next frame (or more)
3. Click (mouse or stylus)

![ezgif-2-879638ac1e](https://user-images.githubusercontent.com/25724133/42132919-850dbc0c-7d29-11e8-91d0-af1cdeec5563.gif)

**Comment by shun-iwasawa** [comment]
I couldn't reproduce the crash on my Win7 environment.

![noproblem](https://user-images.githubusercontent.com/17974955/42259134-20a8e066-7f9a-11e8-9a8c-aa62c5782cd0.gif)

Am I missing something..?

**Comment by beeheemooth** [comment]
@shun-iwasawa The second line you should not draw, but just put a point.
I'm using Wacom Intuos 4, Windows 8.1

**Comment by beeheemooth** [comment]
That's the difference.
![ezgif-2-be07911aed](https://user-images.githubusercontent.com/25724133/42270489-a893f170-7f89-11e8-9c7d-c41565c67894.gif)

**Comment by shun-iwasawa** [comment]
Now I could reproduce the crash. Thanks!
