### ISSUE TITLE
Is there any benefit to the view changing between the level strip and the viewer?

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2122]
### Issue Summary

It's easy to be able to target things by switching between the viewer view and the level strip but, there is a shift in the view when switching, which sometimes requires a repositioning. Is there any benefit to the view changing between the level strip and the viewer ?

**Comment by RodneyBaker** [comment]
You may need to provide a screen capture/video of the specific changes you reference.
The short answer to the question feels like a 'yes, there are some benefits' at this stage of review.

**Comment by openanim** [comment]
As it's more of a question i'm going to close here and post the topic on the forum
