### ISSUE TITLE
Vector brush lines broken when drawn quickly

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2128]
### Issue Summary
When drawing with vector brush quickly (mouse or pen), the line drawn is broken until you stop and lift the pen/stop mouse button press

### Screenshot or Video Reference
![vector_brush_issue](https://user-images.githubusercontent.com/19245851/42197964-60ba4aca-7e53-11e8-97bc-bab53d70824d.gif)

### Steps to Reproduce
Open an new vector level.  Draw a line quickly and stop without lifting pen or mouse button press. - The line will be broken as in video.  Left pen/stop mouse press, the line becomes solid.

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: Windows 7 and 10

**Comment by openanim** [comment]
I confirme i have this issue too.

**Comment by konero** [comment]
I didn't have the issue at first, until I enabled the smooth setting. Turning smooth off fixes it for me.

**Comment by openanim** [comment]
I did not notice that before because of that too.I also have a display problem with the green cursor of the brush snap.

**Comment by artisteacher** [comment]
I’ve had this issue in MacOS for ages.
