### ISSUE TITLE
Improvement Command Bar

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#2129]
@areckx agreed to help and implement some additions to the Command Bar. This is "The ability to resize as in Krita"
![31654305-5077fc20-b32e-11e7-9d2c-0ef6990ff91a](https://user-images.githubusercontent.com/25137502/42201287-ce24d1f6-7e9f-11e8-98c4-2cc6fd566d8b.gif)

It will cost $ 62.50. I can pay it all out of my money as I did before, but if anyone wants to fold, then I'll be happy. I do not want to collect through bounty, since it can be slow, so here's my Patreon.
https://www.patreon.com/agnyy

**Comment by openanim** [comment]
I like this ability too, but reassure me, it does not lose the ability to move the command bar and dock it where you want ? I can contribute too but I am not yet familiar with patreon, I would like another way.

**Comment by artisteacher** [comment]
I think a responsive command bar would be fantastic! It could also be great for the toolbar at some point.

**Comment by Agnyy** [comment]
The command bar will work as it is now, except that now it can be expanded in different directions. But now in the command bar there is one major drawback, it can not be fixed vertically. I discussed this too, you can do it too, it will cost $ 62.50.
