### ISSUE TITLE
Crash after rightclick followed by click in topfield, Col1 in Xsheet

### ISSUE THREAD

**Issue by Gulwer** [opentoonz/opentoonz#213]
Hi
When I rightclick in the topfield, Col 1 and then clicks two times more in the same field Open toonz crashes every time.
![toonz_click1](https://cloud.githubusercontent.com/assets/18187452/14723800/21fb6610-0813-11e6-946b-88912995ef4b.png)
Rightclick
![toonz_click2](https://cloud.githubusercontent.com/assets/18187452/14723815/2ecbaa94-0813-11e6-9956-9f64ed0c38dc.png)
Click, click
![toonz_click3](https://cloud.githubusercontent.com/assets/18187452/14723824/36242a96-0813-11e6-908c-26bf3e704c69.png)
Crash

Opentoonz nightly build 21/4-2016
OSX 10.10.5
MacBook Pro (Retina, 15 tum, mitten 2014)
2,8 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB

[Opentoonz_levelclickcrash.pdf](https://github.com/opentoonz/opentoonz/files/230723/Opentoonz_levelclickcrash.pdf)

I hope this is helpful.

**Comment by kogaki** [comment]
Seems #285 fixed this.
