### ISSUE TITLE
Automatic switching between layers.

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#2135]
### Issue Summary
Very annoying when you upload images and are already going to animate and then you will find out that you are now col2 instead of col1 this is very confusing. Can it be removed?  

### Screenshot or Video Reference
  https://youtu.be/3-0wQDzHNgY

**Comment by RodneyBaker** [comment]
Can you clarify that this only happens in the Timeline or does it happen in the xsheet as well?

**Comment by artisteacher** [comment]
I'm seeing this too - both with the Xsheet and the Timeline. The selected column/layer definitely shouldn't shift to the right/above after importing.

**Comment by RodneyBaker** [comment]
This may be one of those 'feature not a bug' things in that the presented process would be setting up the user for the next import by moving on to the next column.  I can see it being problematic either way.

In other words, what is to keep a user in the future from suggesting the focus should shift to a new column after import to facilitate the import of the next media asset.

Note that I do find it frustrating that the focus would not remain on the object just imported.
Perhaps if that is in the realm of something that can be controlled when the Edit/Animate Tool is first activated both workflows could be allowed for.  The suggestion being:

Create a test for the Edit/Animate Tool that if found to be in an empty cell in timeline/xsheet it will initially move to the next available column that contains content.  The idea being that generally the Edit/Animate Tool will be used to move content.

Hmm... lots of moving pieces.  But fortunately not as many as other issues.

I am trying to think of any good reason why the Edit/Animate Tool might want to be defaulted to an empty column.  At present I cannot think of one.

**Comment by artisteacher** [comment]
I think this is even worse in the Timeline than in the Xsheet - the focus switches to a column that you can't actually select manually.

**Comment by manongjohn** [comment]
I would consider this a bug. When a new layer is loaded, it will shift any existing levels up (timeline) or right (xsheet) to make room for it. It however also shifts the current cell up. I think it should move it back to where it was prior to any shifting.

Will fix when i get a chance.
