### ISSUE TITLE
Tools improperly disabled for some secondary level frames

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2138]
### Issue Summary

After adding an additional level of a different type to a column/layer, the drawing creation tools are disabled when trying to draw in the next empty cell after that new level's last frame.
### Screenshot or Video Reference

<img width="321" alt="screen shot 2018-07-04 at 10 13 25 am" src="https://user-images.githubusercontent.com/21159116/42282230-d50388bc-7f73-11e8-997a-5f41fa75a29b.png">

### Steps to Reproduce

1. Set autocreation to "Enable" or "use Xsheet as Animation sheet"
2. Create a level of any type & draw a few frames (ie. vector)
3. Later in the same column, create a new level with a single frame of any other level type (ie. toonz raster)
4. Draw in the new level
5. Use the down arrow to move to the next empty cell
6. Try to use the brush tool, geometric tool or etc. 
### Expected Results

For the tools to work and a new frame to be created.
### Actual Results

The disabled tool icon displays and it's impossible to use the tools. Strangely enough, the type tool is the only one to work as expected.
### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: MacOS 10.13.5
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by manongjohn** [comment]
Apparently PR #2087 would fix this but that PR requires some additional work and I don't know when it will go in. 

I'll see if I can extract the code from the PR that fixes this and submit a separate PR for it.

**Comment by openanim** [comment]
https://groups.google.com/forum/#!category-topic/opentoonz_en/troubleshooting/wwZt_toEo7I

I wonder if that does not affect the problem I'm having here as well. In my case, the tools are disabled, directly on the level used (vector or rasters) And I have no choice but to reboot OT. Oddly enough, it seems to be something new.

Artisteacher by doing, your steps, I often get to this state of disabled tools, can you confirm this too?

**Comment by artisteacher** [comment]
@openanim I usually separate out different level types onto their own columns. I haven't run into the issue you described following these steps so far, but I haven't spent a ton of time animating this way.
