### ISSUE TITLE
hide / show Camera Stand Visibility 

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2139]
### Issue Summary

I use shortcuts to quickly alternate on what I want to hide and show, it works pretty well. But to show the column only the command "show selected (and maybe hide selected too) only works if we are on the column header While "show this only" will work like other commands, indiferently where our cursor is positioned (head colum or level), which is convenient.  Can "show selected" also work in the same way as "show this only" and others hide all / show all toggle show / hide ?

### Steps to Reproduce

Put some shortcut for theses commands and try use show selected somewhere diferent of head column

### Expected Results

it should work in the same way as other similar commands

**Comment by shun-iwasawa** [comment]
> the command "show selected (and maybe hide selected too) only works if we are on the column header

`Show / Hide Selected` commands are available only when the columns are selected.
OT can have only one current selection at the same time. As soon as you select some another select-able item such as style, level strip frame, etc. the current selection will moved to it and the column selection will be released.
