### ISSUE TITLE
mesh column visibility changed for mac

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#2141]
### Issue Summary
a few months back mesh columns changed. previously, hiding a mesh layer would hide the mesh but when the plastic tool was active and the column was selected, the skeleton was visible for animation while the mesh stayed hidden. this was not an expected result but it was ideal.

now, the mesh column's visibility must be turned on in order to animate which means the mesh is visible which is distracting. the "show mesh" checkbox will hid the mesh but only while the plastic tool is selected, selecting any other tool reveals the mesh again.

### Screenshot or Video Reference
https://youtu.be/SeW_R2Wek64
in the video, you see the mesh visibility turned off via the checkbox and see how it becomes visible again when the tool is changed to anything except the plastic tool. at the end you see that toggling camera stand visibility to off no longer allows access to the skeleton for animation as it did in previous versions of opentoonz.

### Steps to Reproduce
create mesh, right click viewer and deselect the "show mesh" check box, then switch to any tool except the plastic tool.

### Expected Results
the mesh stays hidden regardless of the active tool

### Actual Results
the mesh reappear when the plastic tool is not activated.

### System Information
  1.2.1
 mac os 10.13.5
2.5 GHz Intel Core i7
16 GB 1600 MHz 
NVIDIA GeForce GT 750M 2048 MB Intel Iris Pro 1536 MB

**Comment by artisteacher** [comment]
I'm seeing the same change. If "show mesh" is deselected, the mesh shouldn't be visible when other tools are active.

**Comment by shun-iwasawa** [comment]
Confirmed the problem on Windows as well.

**Comment by shun-iwasawa** [comment]
After looking into the source, I found that the mesh visibility is reset when the plastic tool is deactivated ([here](https://github.com/opentoonz/opentoonz/blob/7f1e30e1f6f221d25f71c279fbfa0a2816880eac/toonz/sources/tnztools/plastictool.cpp#L1001) in the source). The visibility is reset only for the current active Viewer, so if you open multiple Viewers, mesh will keep hiding in non-active ones even if you change tools. This behavior has already been included from Toonz Harlequin source and I'm not sure what the original intention was.
