### ISSUE TITLE
Can we redo the site?

### ISSUE THREAD

**Issue by 711GM** [opentoonz/opentoonz#2142]
The site of the OpenToonz is good, but not very understandable, we can do it more easily. The site at Pensil2D looks good. On their site you can easily find everything and also find a community in which you can communicate and ask questions.

https://www.pencil2d.org

**Comment by RodneyBaker** [comment]
If I understand correctly Pull Requests for new site data can be made here in github just as with the program code itself.  Have fun!

**Comment by shun-iwasawa** [comment]
As @RodneyBaker commented, the website is built open-source-based as well in another repository.
Please post any suggestions and pull requests to https://github.com/opentoonz/opentoonz.github.io. Thanks!
