### ISSUE TITLE
opentoonz immediately crash

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2144]
When i open opentoonz it just close no crash report. what can i do?

**Comment by artisteacher** [comment]
What version are you using? How far does the opening process get?

**Comment by animating-dino** [comment]
I am using 1.2,1.21 my win is:windows 10 when I open opentoonz it just close it's just 1 second

**Comment by manongjohn** [comment]
Try temporarily turning off any anti-virus software you have running to see if that is killing it?

**Comment by animating-dino** [comment]
I don't have any anitivirus

**Comment by artisteacher** [comment]
Did 1.2.1 ever open successfully? If so, it might help to reinstall. I would rename the stuff folder before reinstalling (in case there is something in the Stuff folder causing the crash).

**Comment by animating-dino** [comment]
when I open opentoonz 1.2.1 it work then another time it close randomly I don't no why and i delete stuff folder and reinstall it

**Comment by manongjohn** [comment]
I wonder if a Win10 update changed something on your machine between when it last worked and when it started closing.

Win10 update seems to sometimes update stuff that messes up drawing programs, not just OT.

I know another OT user whose graphics card somehow got messed up in an update and was having strange issues and immediate crashes. He fixed the graphics driver and it started working again.

Try updating your graphics drivers on your machine and see if that helps.

**Comment by animating-dino** [comment]
can you tell me how to update my graphics driver.

**Comment by animating-dino** [comment]
I get the problem again
