### ISSUE TITLE
A trace from the brush above the area with Plastic deformation (gif)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2147]
The first time you move on the part of any of the windows in addition to the trail brush appears some kind of container.

![ezgif-2-aee195976f](https://user-images.githubusercontent.com/25724133/42414916-dc5c5e2c-8248-11e8-844c-5e0da375d56c.gif)

### System Information
Windows 8.1

**Comment by animating-dino** [comment]
I have this problem too.

**Comment by shun-iwasawa** [comment]
Confirmed that the PR #2123 will also fix this issue.
