### ISSUE TITLE
Crash:  Ctrl-z and x while moving a line

### ISSUE THREAD

**Issue by ble-h** [opentoonz/opentoonz#2148]
### Issue Summary

OpenToonz crashes when I try to remove a vector line using ctrl-x or ctrl-z while moving it. Ctrl-z also doesn’t undo changes to a line properly.

### Steps to Reproduce

Select a vector line using the selection tool. Move it and press ctrl-x while moving it. The line should disappear but OpenToonz will crash instead.

Draw a vector line and then select it using the selection tool. Move it and press ctrl-z while moving it. The line should disappear but OpenToonz will crash instead.

Erase one end of a vector line and then select it using the selection tool. Move it and press ctrl-z while moving it. The line should look like it did before it was partially erased but it will instead look different.

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: Windows 10

**Comment by RodneyBaker** [comment]
@niccoi 
I can confirm the move and delete simultaneously issue here on 1.2.1 Win 10

Interesting problem.
Apparently I've never tried to move and delete a vector line at the same time.
The immediate workaround would appear to be that of delaying the delete operation until the movement is complete.

**Comment by beeheemooth** [comment]
Move line, Ctrl+C, Paste Insert (Ctrl+V), Undo (all this while moving) = dot with lots point

**Comment by beeheemooth** [comment]
the same principle
![ezgif-2-8c35d77978](https://user-images.githubusercontent.com/25724133/42424866-c4595d00-831c-11e8-8280-63fefcfa3dcb.gif)
