### ISSUE TITLE
Crash with Subxsheet / FX  during Preview

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2154]
when collapsing smoke fx with it's level to form sub xsheet in preview mode the program just crash.
my windows is:
win 10
opentoonz version: 1.2.1

**Comment by artisteacher** [comment]
Do you get the same crash with any other FX?

**Comment by animating-dino** [comment]
yes with every other fx

**Comment by RodneyBaker** [comment]
@animating-dino   can you edit your title to correct the spelling a 'crash'.
Thanks!

**Comment by RodneyBaker** [comment]
@animating-dino Can you confirm this is still an issue with current nightly releases?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@animating-dino If you are still experiencing this issue please let us know.
