### ISSUE TITLE
Undo after Fill fails (toonz raster)

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2156]
### Issue Summary

In Toonz Raster Level, you can fill the canvas's working surface, because by default the size of filling box corresponds to the size of the canvas (see the lines of filling box), but if you press "undo" after filling area, the filling box disappears and now to fill enitre area is impossible.
### Screenshot or Video Reference

![ezgif-2-3eddcb7050](https://user-images.githubusercontent.com/25724133/42579511-2c0e8446-8531-11e8-9832-0b33c34b0c44.gif)
### Steps to Reproduce

1. Create a new Toonz Raster Level.
2. Fill it with color (Fill Tool, Normal mode)
3. Undo
4. Repeat step 2. Fills will not occur.
### Expected Results

The filling box should cover the entire work surface if there is nothing in it, or if all the graphic elements (lines, filed areas) have been deleted from the current level frame.
### Actual Results

The filling box disappears after undoing the fill operation, and also after erasing all graphic elements.
Recreating the filling box in this case is possible only in that way:
![ezgif-5-a1d509c946](https://user-images.githubusercontent.com/25724133/42580715-d08bb08c-8533-11e8-9990-fec419db33e1.gif)

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: Windows 8.1
* **Graphics Tablet**: Wacom Intuos 4

**Comment by beeheemooth** [comment]
Unchecking "Minimize Savebox after Editing" solves this problem.

**Comment by manongjohn** [comment]
I would still consider this a bug. Just because you select that option, it shouldn't block an Undo operation.

**Comment by beeheemooth** [comment]
@manongjohn Well, fair remark.

**Comment by RodneyBaker** [comment]
I'm not experiencing this (workaround) bug with unchecking or checking "Minimize Savebox after Editing" in current releases.

Perhaps a recent update resolved the problem?

@beeheemooth @manongjohn  Can you confirm?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
Fill and Undo works fine following the steps outlined above both with and without "Minimize Savebox after Editing" toggled on in Preferences 

@beeheemooth If you are still experiencing this issue please let us know and we'll investigate.
