### ISSUE TITLE
opentoonz.github.io should updated to reflect the fact that you support Linux

### ISSUE THREAD

**Issue by mrbig033** [opentoonz/opentoonz#2161]
### Issue Summary

There's no mention on the website that you support Linux. It gives the impression that you don't support the platform. You could at least add a link to the [build instructions](https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_linux.md).

**Comment by turtletooth** [comment]
This should be posted as an issue on https://github.com/opentoonz/opentoonz.github.io

BTW- There is already a PR requesting that the link to linux be posted.
