### ISSUE TITLE
Autosave causes selection to disappear

### ISSUE THREAD

**Issue by z-uo** [opentoonz/opentoonz#2164]
### Issue Summary
I experienced this bug in different situation, here is one reproducible pattern, but it isn't the only one.

### Steps to Reproduce
Put the autosaving to 1 minute (easier to test)
Create a raster level
draw something
select it with freehand tool
copy on a new frame
select it again
rotate, move
go on another windows on your computer
wait for autosave popup
try to rotate the selection
the selection disapear
try to undo
it doesn't get your drawing back

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**:  windows 10
* **CPU**: amd rizen 7
* **Memory**: 16g
* **Graphics Card**:  nvidia gforce gtx 1050 ti
* **Graphics Tablet**: cintiq 13hd

**Comment by RodneyBaker** [comment]
If I am not mistaken...
This isn't an issue with Autosave as much as it is one with the Undo.
Undo stores the history of activity back to the last Save.
So, therein (in the Undo protocols and logic) lies the issue.

This likely does relate to some other reported issues where Undo skips a step going backward etc.  You may want to search for those here on github.

**Comment by z-uo** [comment]
The bug with the autosave is the most important I think.
But maybe it is 2 different issue, I don't know how the code work.
I also have seen other undo bugs in the software and here in github but not with this pattern.

> Undo stores the history of activity back to the last Save.
Nop, apart from some bugs, undo store the history before the last save.

**Comment by RodneyBaker** [comment]
Dev note:  The area of interest in the code for autosave with consideration for tablets as far as I can tell is:

#L103

**Comment by RodneyBaker** [comment]
@z-uo Any updates on this issue?

**Comment by RodneyBaker** [comment]
We haven't seen any reported issues with Autosave in a very long time.
Perhaps those issues have been resolved?
This may relate somewhat to autosave being off by default and initially set to 15 minutes.
Autosaving every minute is not recommended.

@z-uo Are you still experiencing similar problems?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@z-uo If you are still experiencing this problem with Autosave and Undo please let us know and we will investigate.  Thanks!

**Comment by Bracket-H** [comment]
It happened for me just now.
Autosaved, selection gone.

Perhaps mark the tool as busy to prevent autosaving? Or make the selection tool more robust by giving it a finished state or something (unless it has one but then I don't know it)
What I mean by that is, something like pressing enter to finalize fiddling around, instead of switching to another tool like a brush to 'bake' the result.
