### ISSUE TITLE
undo Merge levels crash OT 

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2166]
### Issue Summary

When you merge multiple levels and you use the cancel function and then repeat and cancel alternately, OT will crash. Vectors levels and rasters levels. On Toonz rasters levels, the problem did not occur.

### Screenshot or Video Reference

![undo merge levels crash](https://user-images.githubusercontent.com/29790512/42846097-37599e58-8a18-11e8-9b15-74bd2490ba7f.gif)

### Steps to Reproduce
merge multiple levels of vectors or rasters and cancel and repeat your actions alternately, at a time OT crash.

### Expected Results
No crash

### System Information w10 cintiq companion 2  8g hd graphics 5100

* **OpenToonz Version**: 1.2.1

**Comment by shun-iwasawa** [comment]
I could reproduce the crash. Thank you for reporting!
