### ISSUE TITLE
Can't Save File With Plastic Tool Mesh

### ISSUE THREAD

**Issue by ominousorb** [opentoonz/opentoonz#2167]
Once I add a skeleton to a mesh with the Plastic Tool I get this error and cannot save my scene:
![image](https://user-images.githubusercontent.com/3278989/42923105-63efcf6a-8ae9-11e8-8cd3-d383b2ee5112.png)

Everything works fine, including adding the mesh, up until adding the skeleton. No difference whether in Build Skeleton or Animate mode.

I am running OpenToonz 1.2.1 on Windows 10

**Comment by shun-iwasawa** [comment]
Unfortunately I couldn't reproduce the problem.
It seems that OT fails to rename temporary scene file `6C.tnz.tmp` to `6C.tnz` ([here ](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tsystem/tsystem.cpp#L386-L387)in the source).
One reason could be that the existing file `6C.tnz` cannot be deleted before renaming the temporary file.

Please check if you can save the scene as a new file at another location.
If you can save the scene, then check if the file permission of `6C.tnz` allows you to delete it.
If you cannot save the scene, then please post the problematic TNZ file here, if possible.

**Comment by ominousorb** [comment]
I discovered that it was a problem inherent to my "OneDrive" cloud connected folder. It's a Microsoft service akin to Dropbox or Google Drive. I imagine it had something to do with how it treats file permissions? Switching to a localized drive solved the problem.
