### ISSUE TITLE
can't make large levels

### ISSUE THREAD

**Issue by HGrrr** [opentoonz/opentoonz#2169]
I want to make animations using levels with a large number of frames. Like 100 to 500. And I want to convert between raster/toonzraster/vector.

The problem is I can't start a toonzraster level of say a 100 frames, opentoonz just stops responding. And converting from raster to toonz raster is also just not happening. Opentoonz stops responding.

Just to make sure I downloaded a trial of toonz (cuz if that had worked I would have totally bought it) but that has the same problem. 
So clearly there is something wrong with my setup or the way I am doing things I seems like some weird memory problem but I'm stumped. And forced to use adobe animate which I sucks.

### System Information
* **OpenToonz Version**: 1.2
* **Operating System**: windows 10
* **CPU**:  i5
* **Memory**: 16
* **Graphics Card**: gforce 960

**Comment by shun-iwasawa** [comment]
Hmm, I succeeded in making Toonz Raster level with 1000 frames in my environment with Win7 - i7 CPU - 16GB RAM - GeForce GTX 970.

**Comment by RodneyBaker** [comment]
@HGrrr  Were you successful in your attempt?
More information... perhaps a sample project that doesn't work to test will be appreciated.

**Comment by artisteacher** [comment]
I’ve made some large levels (both large in resolution & frame number). If the size/resolution settings are extremely large, OT sometimes needs extra time to create the frames. In my case, if I left the computer alone for long enough, the level/frames were created eventually. There may be something else going on, but I’m curious what settings you chose when you created the Toonz Raster level.

**Comment by RodneyBaker** [comment]
Closing pending additional report(s) of reproduceable case.
