### ISSUE TITLE
Toggle bottom bar of style editor also ?

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2170]
### Issue Summary

would not it be better if the bottom bar, (for space especially) was also toggled when switching between vertical and horizontal ?
edit 
But in this case, I do not really know where to place the color squares that some styles can have.
### Screenshot or Video Reference

![style editor toggle2](https://user-images.githubusercontent.com/29790512/42953968-d7029fa4-8b7b-11e8-9745-d196bf5aee3a.png)

**Comment by artisteacher** [comment]
When @turtletooth was working on shrinking the style editor, there was a lot of discussion about somehow getting rid of that last line. One problem is that that with some of the special vector styles, there can be up to 5 or 6 different colors - not just one or 2. Also right now the horizontal orientation only changes the color tab while the last 2 lines of the style editor display for every tab.

**Comment by openanim** [comment]
@artisteacher 
Yes, I had this problem not knowing too much owhere should i placing it. I told myself to either stack the squares on top of each other, or add tilt this line vertically, as well like that 
![style editor toggle3](https://user-images.githubusercontent.com/29790512/42965009-06584386-8b99-11e8-99d3-2f8734c8a10e.png)
But that looks less good.
