### ISSUE TITLE
Copy-pasting the plastic mesh column in Stage Schematic causes a crash (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2171]
![ezgif-2-5ee28bf789](https://user-images.githubusercontent.com/25724133/42969835-295de518-8bb0-11e8-9d88-7cd1a207ce50.gif)

### Steps to Reproduce
Copy and paste the plastic mesh column in the Stage Schematic
### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: Windows 8.1

**Comment by shun-iwasawa** [comment]
I could reproduce the crash. Thank you for reporting!
