### ISSUE TITLE
Palettes:  Viewer fails to update with studio palette

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#2172]
### Issue Summary

The viewer is not updated properly when loading a palette from the studio to the viewer.

### Steps to Reproduce

Put a palette from studio palette to viewer.

**Comment by shun-iwasawa** [comment]
Sorry but I'm not sure what is exactly to "Put a palette from studio palette to viewer".
You mean, dragging some palette from the Studio Palette's tree view and drop it on the Viewer?

**Comment by openanim** [comment]
Sorry for the confusion, I wrote it too fast and I did not have the opportunity to put a gif. Here is the problem, it does not matter if I use the "load into current palette" command or that I drag to the palette window, the viewer is not updated until the cursor is over it.
![studio palette no update](https://user-images.githubusercontent.com/29790512/43012770-5589a98c-8c47-11e8-800f-e4c7bb5627d3.gif)

**Comment by RodneyBaker** [comment]
Possibly another 'focus' issue?

**Comment by artisteacher** [comment]
I've found another focus issue regarding color keyframes, which could be related. If there are multiple color keyframes and you remove a color keyframe, the removed color remains visible until the frame is changed.

**Comment by RodneyBaker** [comment]
@openanim I'm reviewing some of our older issues.
Can you confirm this issue still persists with latest nightly release?
Thanks!

**Comment by openanim** [comment]
@RodneyBaker on retesting , it seems that you still need to have the cursor on the canvas for it to work. However, using the "load to the current palette" command works fine.

**Comment by RodneyBaker** [comment]
Closing this as the originator of the report has ghosted themselves.
