### ISSUE TITLE
opentoonz brushes bugs.

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2179]
### Issue Summary
I have a problem with the brushes when I open it the program gets laggy I will show a screen shot,but I think the problem with style editor

### Screenshot or Video Reference

![capture1](https://user-images.githubusercontent.com/39278532/43038763-fbaab31e-8d1f-11e8-9d86-fc396f24d120.PNG)

![capture](https://user-images.githubusercontent.com/39278532/43038778-36c39b0a-8d20-11e8-9748-f9ea79e55a27.PNG)

![untitled9 _ opentoonz 1 2 1 22_07_2018 11_08_47](https://user-images.githubusercontent.com/39278532/43044082-bf5bb928-8d9f-11e8-8ac3-e21579ea8410.png)

 
![a](https://user-images.githubusercontent.com/39278532/43091543-a1396a24-8eaa-11e8-81f8-8a810030bdd9.gif)

IT'S a video.

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: win 10
* **CPU**: i5
* **Memory**: 6 gb
* **Graphics Card**: gtx 630m
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
We'll have to check in earlier release but I believe some of those vector brushes may be misclasssified.
Unless I am mistaken some are only for use with the Fill Tool and cannot be used for drawing.
That would appear to be the case with the first screenshot 'stained glass window' fill you provided.
I don't see any difference between the first and second screenshot so If I'm missing something there please let us know.

As for the MyPaint Brushes...
There is an anomaly that occurs and slows down the standard raster brushes (especially MyPaint brushes) when the previously used Vector brushes are not reset to the 'no brush' setting.  That's the brush with the red circle and crossbar lined through it.   When the vector brushes are reset that lag with the raster brush should go away.   @shun-iwasawa   not sure if you've seen me comment on that before but I'd say that is a bug.

Back to you @animating-dino !

**Comment by animating-dino** [comment]
I mean when I enter any of the new brushes every thing stopped working and I can't do anything.
but I don't have the problem in opentoonz morevna edition 1.2.0.2
