### ISSUE TITLE
Pump Tool problem with Selection Tool using tablet

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2180]
### Issue Summary

Using the tablet (Intuos 4), in some modes of the Selection Tool (Whole Level, Same Style in Whole Level), when the line is repeatedly selected, the slider for changing the line thickness is not displayed. It also becomes impossible to change the thickness of lines in the input window. When using the mouse, such problems do not arise.
### Screenshot or Video Reference

If you toggle between Standard and Whole Level, the slider becomes available, but only first time until the selection is not deselected.
![ezgif-2-bb29618419](https://user-images.githubusercontent.com/25724133/43046987-9fffa85c-8dd9-11e8-9b07-000da0782ad5.gif)
Mouse and tablet
![ezgif-2-30ce5a9d46](https://user-images.githubusercontent.com/25724133/43046997-d18c1630-8dd9-11e8-9fc2-653a6742c940.gif)

### Steps to Reproduce

1. Using tablet change Selection Tool mode to "Whole Level" and select the vector lines.
2. Deselect them by clicking on the canvas
3. Select again - the slider will disappear

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: Windows 8.1
* **Graphics Tablet**: Intuos 4  PTK - 440

**Comment by artisteacher** [comment]
Should the pump tool slider be visible in all of the selection modes? Even without a tablet, it is only visible for some selection modes on macOS.
