### ISSUE TITLE
Enable redo after a copy key

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2189]
### Issue Summary

I have not found a similar subject but it is possibly a duplicate.

There is a problem when trying to use redo after copying keys.

### Steps to Reproduce

1- Create a column with one or more levels
2- Create one or several keys
3- copy the keys
4- paste the keys on the levels below or on another column
5 - use undo
6- use redo.

It does not work.

W10 OT 1.2.1

**Comment by RodneyBaker** [comment]
@openanim Any update?  The #2398 fix is still pending review/merge but perhaps you can confirm this fixes the issue.

**Comment by openanim** [comment]
Yeah @RodneyBaker, that works perfectly, Thx @manongjohn for fixes ! 👍
