### ISSUE TITLE
display lag

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2198]
I have a problem.
I have two graphic drivers:
intel 4000.
nvidia gtx 630m.
when I use opentoonz with nvidia I cant use use style editor very well.
and in full screen it work but laggy.
when I use intel opentoonz work well,
but in fullscreen doesn't work.
but when I use opentoonz morevna editon ,
it work well everything.

**Comment by manongjohn** [comment]
Use your nvidia card for OT.  Go into NVIDIA control panel  and add OpenToonz executable under the 3D profile configured for High Performance.

**Comment by animating-dino** [comment]
I use it but my style editor not work look at this.
![a](https://user-images.githubusercontent.com/39278532/43224063-5944cd6a-9055-11e8-9056-5e99f11a1a58.gif)
and in fullscreen mode the program gets laggy

**Comment by manongjohn** [comment]
Your animated gif appears to show a bug with the vector brush selection.  While you seem to be moving ok, somehow your brush selection got stuck on something blank.  I managed to somehow recreate that issue once but it took a while before it happened to me.  I managed to get it to work again but not sure what caused it.

I'm try and find to find the proper steps to recreate that bug so we can fix it.

**Comment by manongjohn** [comment]
After some more testing, it appears some of the vector brushes are only good for filling, not for actual drawing.  When you draw with one of these vector brushes, there is no line.  If you chose to fill a shape with that pattern, then you can see the pattern when it fills the shape.

Those vector brushes that are only used for fill maybe should be separated into a different category to avoid confusion.

**Comment by animating-dino** [comment]
but I mean the lag in the style editor in the nad of the gif

**Comment by artisteacher** [comment]
Just to clarify for the vector styles, the generated styles where the swatch is a square are all fills only. The swatches with the diagonal curved mark are all strokes only.

**Comment by gab3d** [comment]
By the way, these swatches always look a bit small to me...
Is there a way in Preferences to make them bigger?
Thanks!

**Comment by DarrenTAnims** [comment]
It sounds like we definitely need a different section for strokes and fills to remove that confusion.

**Comment by RodneyBaker** [comment]
@DarrenTAnims 
It's not entirely clear to me if these particular swatches are intended to be only fills.
When I first posted on the subject I was mainly focusing on what I saw happening with those elements.
It could very well be that those elements are also suppose to be able to be used while drawing.

We need some intrepid explorers to investigate.
- What is the difference between the 'brushes' that can be used to draw strokes and those that (apparently) can only be used as fills?
- For those with access to other versions of Toonz (or handy versions of earlier OpenToonz) can we verify the 'fill brushes' have never been able to be used with strokes?

I'd suggest before separating them we should make a few of those determinations.

Someone to query on this might be @turtletooth as he was involved in reorganizing the Style Editor.  I suspect he mostly just maintained the collected brushes as they already were and just pushed them toward their current location in the tabs.

**Comment by RodneyBaker** [comment]
Regarding the brushes... (sorry... I know there is an important lag element to this topic that is likely more pressing but I don't have specific advice for that beyond what I have already suggested)

OpenToonz currently does not match the documentation with regard to identifying 'Special Styles' vs 'Custom Styles'.  It is my current understanding that we can create Custom Styles but a developer would need to create the Special Styles.  Currently the tabs are labeled 'Generated', 'Trail' and 'Vector Brush'.  Perhaps these could be further modified to specify the differences and to resync again with current documentation.  I will try to consider this in my exploration.

**Comment by gab3d** [comment]
The indicated swatches are the ones ONLY intended for making Fills.

![fill_brushes](https://user-images.githubusercontent.com/18104091/43271022-daac433e-90cc-11e8-87aa-b43a08fa3d0b.png)

**Comment by RodneyBaker** [comment]
Thanks @gab3d !

So if those could be moved down so that space is between them and the 'brushes' that would meet the minimum criteria?   Obviously more could be done but... as a minimum might that suffice?  What say you all?

**Comment by gab3d** [comment]
@RodneyBaker 
yes, I say that'd be a welcome improvement.

**Comment by RodneyBaker** [comment]
I may have responded off list (via email). Sorry about that.  (I won't post that again to keep things brief)
For aspiring developers, in general ColorFX is the source code area all of this falls into:

https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/colorfx

**Comment by artisteacher** [comment]
Getting back to @animating-dino's concerns, the gif definitely shows some visual distortions - both the black to the right in the viewer when resizing and also the fragmented display of the color wheel. This is definitely not an issue in MacOS.

**Comment by manongjohn** [comment]
I couldn't duplicate on my Win7 where I force OT to use nvidia card in High Performace mode or on my Win10 machine. Not sure why the Morevna edition would be different unless they somehow optimized the style editor.

**Comment by animating-dino** [comment]
I dont get this result from opentoonz 1.2 official release

**Comment by artisteacher** [comment]
If the official release is fine and the problem is in the nightly builds, you might want to find the last nightly build without an issue. Older nightly builds can be found [here](https://github.com/opentoonz/opentoonz_nightlies/releases).

**Comment by animating-dino** [comment]
I mean the lag in opentoonz 1.2.1 and I have a problem with fullscreen too.
![bw](https://user-images.githubusercontent.com/39278532/43293259-91138260-9139-11e8-827f-8fe7b08249e8.gif)

**Comment by DarrenTAnims** [comment]
Regarding the fill vs stroke brushes. I'd hope if any work is being done on them, then it shouldn't be too hard to move them to a new, separate ,"Vector Fills" tab/section.

**Comment by animating-dino** [comment]
I don't have any problem in opentoonz 1.0 and 1.1 and 1.1.3

**Comment by manongjohn** [comment]
@animating-dino In your last gif, the difference in playback was because 1 was on full screen (16 fps) vs not (24fps)? That's on your intel card? Not sure why that would be. Might need to check you have the lastest display drivers.

Since 1.2.0, OT started using some OpenGL stuff which unfortunately introduced lag to some users. This is why you wouldn't see it in prior OT versions. This lag you are experiencing is a little strange though.

Also still quite surprised that using your nvidia card doesn't work better than the intel card. Usually its better. When you set to High Performance, did you play with settings or use the defaults?

**Comment by animating-dino** [comment]
the lag in the gif is nvidia card.
but when I use intel card when I toggle full screen the viewer become black

**Comment by animating-dino** [comment]
what if I upgrade my opengl driver can it be fixed?

**Comment by animating-dino** [comment]
for some way a open opentoonz but it fixed but resolution became weird 
is there an option to not use opengl

**Comment by artisteacher** [comment]
The changes to OpenGL actually fixed some display issues in MacOS.

**Comment by animating-dino** [comment]
ok.
do i close the problem?

**Comment by animating-dino** [comment]
I hope it will be fixed soon.

**Comment by animating-dino** [comment]
I will close this problem.
