### ISSUE TITLE
customize menu bar - drag and drop entire menu folders to the menu bar

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#220]
The new menubar customization window in opentoonz.
When I try to drag an item from the 'Menu Items' column to the 'myRoom Menu Bar' column, my mouse cursor is indicating that the operation is not permitted.
![cantdrag](https://cloud.githubusercontent.com/assets/6495061/14743327/f22e0da8-0898-11e6-9eee-787a5d214d43.PNG)

So adding new items doesnt seem to work, or at least I am not understanding how to do it.

You can however reorder existing items in the room by dragging them. You can even nest them as subitems.

Please add the ability to drag entire menu folders, as dragging individual items is a huge pain in the neck and introduces higher chance of error.

**Comment by Blenderbeetle** [comment]
I'm pretty sure you can't drag full folders in. I had to drag individual items when I was customizing the menus.

**Comment by blurymind** [comment]
ooh i get it - you have to right click>insert menu to make a menu. Then drag items one by one because you cant shift select more than one.

 then I guess this is not a bug, but a feature request. Most of the time I just want to have a certain menu included.

**Comment by blurymind** [comment]
I also noticed that some of the items are missing:
https://github.com/opentoonz/opentoonz/issues/387

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
