### ISSUE TITLE
Add clarification to vector styles

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2200]
### Issue Summary

As discussed in #2198, the purpose of generated vector styles are unclear. Some styles work only as fills while others work only as strokes. While the icons do differ for strokes vs. fills, the difference is not readily understandable to many users of OT. It would be helpful to add some visual separation between the 2 style types and perhaps additional labels.

Additionally, as discussed in the previous issue, the current OpenToonz documentation is out of date in regards to the Style Editor and uses the old terms "Special" and "Custom" rather than the more descriptive terms "Generated" and "Trail". The terminology was changed to be more descriptive and informative of the styles themselves and really should be updated in the manual.
### Screenshot or Video Reference

Vector strokes:
<img width="328" alt="screen shot 2018-07-26 at 5 42 44 pm" src="https://user-images.githubusercontent.com/21159116/43290219-6c6aee8c-90fb-11e8-96f1-b06e799246c0.png">

Vector fills:
<img width="332" alt="screen shot 2018-07-26 at 5 42 52 pm" src="https://user-images.githubusercontent.com/21159116/43290209-64af36e4-90fb-11e8-8c71-509c0867a505.png">

### Expected Results

As there is no space between the stroke and fills styles, some users expect the fill styles to work as a stroke. Some users may also expect the stroke styles to work as a fill.
### Actual Results

When trying to use a fill as a stroke, no visible stroke is drawn. After switching to a stroke style, the lines become visible. When trying to use a stroke style as a fill, no fill is visible. Upon switching to a valid fill style, the stroke becomes visible.

**Comment by RodneyBaker** [comment]
Definitely something that needs to be addressed in the future.
Closing for now as Feature Request.
