### ISSUE TITLE
plastic tool problem with the camera

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2201]
### Issue Summary
when I move the camera in opentoonz the skeleton of the plastic tool don't follow it0

### Screenshot or Video Reference
000000
![bwe](https://user-images.githubusercontent.com/39278532/43340627-3f1c7558-91dd-11e8-8f01-4a0bc154a39d.gif)000000

### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by beeheemooth** [comment]
I saw a similar problem in the OpenToonz (English) group on Facebook.

**Comment by animating-dino** [comment]
I find this problem when Ii am doing animation.

**Comment by animating-dino** [comment]
I  figured out that character move by moving the camera. because I am using subsheet.
