### ISSUE TITLE
Crash after level cleanup function

### ISSUE THREAD

**Issue by loris16148** [opentoonz/opentoonz#2203]
### Issue Summary
So the goal is to create a sketch in raster then use cleanup settings to convert it to toonz raster. When I select a level for cleanup the function carries out fine. One thing that I noticed is when i go to the color palette of that level the raster palette is still there mixed in with the toonz raster palette. Obviously the raster palette does not work on toonz raster level so when i try to use it the system crashes. The issue is not the crash but the fact that the raster palette stays on the level after it has been converted to a toonz raster level. 

### Screenshot or Video Reference

![opentoonz 1](https://user-images.githubusercontent.com/6901805/43359051-e27d913c-9250-11e8-82dc-30de9e1970f9.gif)

### Steps to Reproduce
Create raster level, draw something. Ensure that your raster level color palette has a few different colors in it. Go to scan and cleanup option up top, select cleanup. now go back to your drawing which is now a raster level. Go to the color palette. The raster level color palette should still be there. Select one of the raster tools and try to draw, crash.

### Expected Results
I expect the raster palette to disappear once the raster level has been converted to toonz raster. 

### Actual Results
ww3

### System Information
* **OpenToonz Version**:  1.2.1 july 28 build
* **Operating System**: windows 8.1
* **CPU**: i7
* **Memory**: 7gig ddr3
* **Graphics Card**: intel intergrated
* **Graphics Tablet**: wacom cintiq

**Comment by RodneyBaker** [comment]
@loris16148 This appears to be a refresh/focus issue reported previously but we'll leave this open as it has some specific steps we can follow to assess the problem.

Can you confirm the palette stays that way and doesn't update on it's own later?

**Comment by RodneyBaker** [comment]
Closing as likely a temporary issue.
@loris16148 If this hasn't been resolved please let us know and we'll give it another look.
