### ISSUE TITLE
opentoonz resolution problems.

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2204]
### Issue Summary
when I enter full screen and exit it.
the program will have some errors. the display become glitchy.
I am using nvidia geforce 630m. do I have to upgrade it
and when I am intel with full screen. the program goes black

### Screenshot or Video Reference

 
![bwehq](https://user-images.githubusercontent.com/39278532/43421863-3752d5e8-9448-11e8-9c29-c957fe189b63.gif)

### System Information
* **OpenToonz Version**: 1.2.1 lastest
* **Operating System**: win10
* **CPU**: i5 quad core
* **Memory**: 6 gb
* **Graphics Card**: nvidia gtx 630m
* **Graphics Tablet**:

**Comment by animating-dino** [comment]
#1638 problem 
when @turtletooth do the modfied fix it fixes my problem.

**Comment by RodneyBaker** [comment]
Noting that a part of this report references Fullscreen going black; a problem likely related to OpenGL.
Also:  Nvidia graphics.
