### ISSUE TITLE
Getting black Schematics/FX after last update

### ISSUE THREAD

**Issue by wofogen** [opentoonz/opentoonz#2207]
### Issue Summary

After the Schematic UI Update, i'm getting black nodes.

### Screenshot

![schematic1](https://user-images.githubusercontent.com/33259911/43551923-2e3a952c-95bf-11e8-9a28-d22a2fd94a32.jpg)
![schematic2jpg](https://user-images.githubusercontent.com/33259911/43551932-319701e2-95bf-11e8-9cf4-3a71b04321b7.jpg)

### System Information

- **OpenToonz Version: 1.2.1 (build Aug 1 2018)**
- **Arch Linux - Kernel 4.17.11**
- **4gb**
- **Geforce GTX 560 -Drive 390.77**

**Comment by manongjohn** [comment]
You need to reinstall OT but when prompted to update your OpenToonz 1.2 Stuff folder, click Yes. Any personal settings you have will be saved.

**Comment by wofogen** [comment]
thanks @manongjohn, replacing my current Stuff folder with the one that comes with the sources fixed the problem ^^
