### ISSUE TITLE
Cannot load images with simple numerical names

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2209]
This relates to other issues of filenaming convention used by OpenToonz but this report tries to target a specific case.

### Issue Summary
Images named with numerics cannot pass test to allow OpenToonz to load them.
This may occur because OpenToonz sees numeric data as special characters used to increment and sequence images.

### Screenshot or Video Reference
See attached image

### Steps to Reproduce
Name an image 1.png and attempt to load the image into OpenToonz

### Expected Results
Images of any naming convention (short of special characters reserved for operating systems) should load into OpenToonz.

### Actual Results
An error is thrown stating that special characters cannot be used in the filename although only numerics are used.

### System Information
* **Latest Nightly release as of 20180802**: 
* **Win10**: 
![simple filename load](https://user-images.githubusercontent.com/2576432/43600988-b87fd91c-9651-11e8-8153-4d4c8e7607cd.png)

**Comment by animating-dino** [comment]
I try it but It work for me.
