### ISSUE TITLE
function editor bug: typing an expression crashes opentoonz

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#221]
on windows 7 -64 -

to reproduce:
1. create a vector toonz level
2. in the function editor, for interpolation select 'Expression'
3. type anything for the expression

opentoonz will crash:
![expressioncrashbug](https://cloud.githubusercontent.com/assets/6495061/14748741/6793436e-08b3-11e6-870f-ac0d77d0628e.PNG)

I am also attaching some files that might help diagnose the problem:
[bugreport-OT-expressionEditor.zip](https://github.com/opentoonz/opentoonz/files/232240/bugreport-OT-expressionEditor.zip)

**Comment by shun-iwasawa** [comment]
Fix merged in v1.0.2
