### ISSUE TITLE
New Schematic UI without names

### ISSUE THREAD

**Issue by flaviohr** [opentoonz/opentoonz#2211]
### Issue Summary
installing new installation of nightly opentoonz, new schematic ui appear without names

### Screenshot or Video Reference
<img width="849" alt="screen shot 2018-08-03 at 1 48 19 am" src="https://user-images.githubusercontent.com/19403672/43626431-c04bd0f6-96bf-11e8-88e2-3a954f77eb79.png">

### Expected Results
all nodes visible

### Actual Results
Nothing to view, but only selected node

### System Information
* **OpenToonz Version**: 1.2.1 nightly august 03
* **Operating System**: macOSX high Sierra 10.13.3
* **CPU**: intel core i5
* **Memory**: 16 GB ram
* **Graphics Card**: intel iris plus 640
* **Graphics Tablet**: Wacom bamboo Ctl 460

**Comment by shun-iwasawa** [comment]
Please see #2207.

**Comment by flaviohr** [comment]
great, this works too in Mac.
