### ISSUE TITLE
Setting "Level Subsampling" to 0 causes a crash.

### ISSUE THREAD

**Issue by lewislong** [opentoonz/opentoonz#222]
Settings > Level Settings > Subsampling.

Windows 10 64-bit, i7-3820 3.60GHz, 16gb ram, Radeon 7850. Running on a single monitor.

**Comment by Rayek** [comment]
Confirmed!

Windows 7 64bit, 48gb, Nvidia 590GTX

**Comment by shun-iwasawa** [comment]
The modification was merged and will be included in the next version.
