### ISSUE TITLE
pen behavior Windows ink

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#2220]
Condition after implementing Windows ink (build 2018-08-07)
on my Windows 10 Surface Pro 2017 i5 8GB with Surface pen (or Wacom Bamboo ink pen) it has the following flaw:

with Windows ink enabled, the pen now draws like it should, without moving the canvas at the same time, but:
switching from the brush tool to the Hand tool (or Animate tool) and back to the brush tool the pen moves the canvas around while drawing. This behavior stops, when i move the pen away from the screen for lets say 20centimeters. Moving pen back to the screen now draws the brush without moving the canvas.

**Comment by manongjohn** [comment]
Confirmed this happens on my laptop/tablet as well. Will look into fixing it.
