### ISSUE TITLE
Line Thickness Becomes Thicker When Drawing in the Bottom Part of the Viewer_2

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2221]
### Issue Summary

Unfortunately, in my environment, the addition of windows ink support has not solved the problem of thickness. #2017

### Screenshot or Video Reference

![variation thickness_5](https://user-images.githubusercontent.com/29790512/43775795-32de4824-9a4e-11e8-88c8-874a763569a3.gif)

### System Information
Scale display : 150 %
Resolution : 2560x1440

* **OpenToonz Version**:  last NB
* **Operating System**: W 10
* **Memory**: 8g
* **Graphics Card**: intel graphics HD 5100
* **Graphics Tablet**: Cintiq companion 2

**Comment by manongjohn** [comment]
Please close this as a duplicate.  I will re-open #2017 since it was not successfully resolved.

**Comment by openanim** [comment]
Thanks !
