### ISSUE TITLE
opentoonz crash

### ISSUE THREAD

**Issue by animating-dino** [opentoonz/opentoonz#2228]
### Issue Summary
 I am having this crash.
I can't fix it. one day it will be fixed itself. and another day it would crash.

### System Information
* **OpenToonz Version**: all
* **Operating System**: win 10
* **CPU**: i5
* **Memory**: 6
* **Graphics Card**: all my cards intel and nvidia

**Comment by RodneyBaker** [comment]
We'll need more information.
At this point the only recommendation would be to purchase a new computer.

**Comment by animating-dino** [comment]
I just open my laptop the I found it that don't want open no any crash report.
what is your recommendation of new gpu and cpu.

**Comment by RodneyBaker** [comment]
Given your trouble with NVidia cards I would suggest trying something other than NVidea.

Some stores might not care for this but... if they allow... you could take a copy of OpenToonz (as a portable) on a USB stick and run that on the system you want to purchase.  If it works as desired.... you've got yourself an adequate computer and if not... time to test a different one.

DIsclaimer:  Some people I know love NVidia cards so I'm not trying to steer you clear of those.  I can only make suggestions based on the information I have and the common theme would seem to be your NVidia card.  As such I would test other cards and see if you no longer experience your current problems.

If you aren't sure how to make your current installation of OpenToonz into a portable I created a batch file that I use immediately after installation that does that automatically.  I'd be glad to share it but bascially what it does is it takes a copy of the files installed and adds a copy of the stuff directory (renamed as 'portablestuff') and places it in a new location.

**Comment by animating-dino** [comment]
put how toonz work In my computer

**Comment by animating-dino** [comment]
I found this error
Faulting application name: OpenToonz_1.1.exe, version: 0.0.0.0, time stamp: 0x57a44206
Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f83ff
Exception code: 0xc0000409
Fault offset: 0x0000000000074a30
Faulting process id: 0x18e0
Faulting application start time: 0x01d42f68589bad3b
Faulting application path: C:\Program Files\OpenToonz 1.1\OpenToonz_1.1.exe
Faulting module path: C:\Program Files\OpenToonz 1.1\MSVCR120.dll
Report Id: 210d19fe-8a01-4a80-be16-80619ff6a94e
Faulting package full name:

**Comment by manongjohn** [comment]
That's the old version. You shouldn't be running that. I would install all OT and delete all OT folders found in C:\Program Files and reinstall again.

**Comment by animating-dino** [comment]
I try it with every version.

**Comment by animating-dino** [comment]
1.2
----------------------------
Faulting application name: OpenToonz_1.2.exe, version: 0.0.0.0, time stamp: 0x5b1a1618
Faulting module name: ucrtbase.dll, version: 10.0.17134.191, time stamp: 0x5db729cd
Exception code: 0xc0000409
Fault offset: 0x000000000006e77e
Faulting process id: 0x92c
Faulting application start time: 0x01d42f6ef127b6f5
Faulting application path: C:\Program Files\OpenToonz 1.2\OpenToonz_1.2.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 205e481b-abd2-4aac-a299-919c6cc3264c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by manongjohn** [comment]
This is the same issue you reported under #2054.  Please avoid posting duplicate issues.  If it is closed and you are still having issues, please reopen or request to have it reopened.

As far as ucrtbase.dll..in your prior post you said you have multiple versions of MSVS installed.  I'm wondering if the ucrtbase.dll OT is trying to use is from one of the versions that isn't quite compatible with what OT was built on (MSVS 2015)?

Perhaps the MSVS 2017 version of the ucrtbase.dll is causing problems?  Try uninstalling all MSVS versions and only install MSVS 2015?

It's also possible that Windows somehow updated ucrtbase.dll which might be incompatible with OT.  Searching online, I've seen a number of ucrtbase.dll issues affecting various applications.   I would search online for possible fixes for ucrtbase.dll and see which one helps you.  If it does, please let us know what you did.

**Comment by animating-dino** [comment]
ok I will close it.

**Comment by animating-dino** [comment]
can you tell me what is the version of MSVS 2015?

**Comment by manongjohn** [comment]
Whatever the latest version of MSVS 2015 is available will work.

**Comment by animating-dino** [comment]
the latest
--------------------------------
Fault bucket , type 0
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: OpenToonz_1.2.exe
P2: 0.0.0.0
P3: 5b1a1618
P4: ucrtbase.dll
P5: 10.0.17134.191
P6: 5db729cd
P7: 000000000006e77e
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE25F.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_OpenToonz_1.2.ex_ef9ea3fd34c9e94f34fad94be0b01c28121a1e6_88fc3bd1_1a37d63a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 417fc70f-6376-44f1-a86b-f847569f138a
Report Status: 528484
Hashed bucket: 
Cab Guid: 0

**Comment by RodneyBaker** [comment]
@animating-dino 

Did you say you've downloaded and replaced the offending ucrtbase.dll file?

If not you might try downloading it here:

https://www.dll-files.com/ucrtbase.dll.html

**Comment by manongjohn** [comment]
@animating-dino I see you closed this. Were you able to fix the dll problem? If so, what was the solution in case someone else runs into this problem?

**Comment by animating-dino** [comment]
I remember Ii do sfc scan and it work why it work can you tell me.

**Comment by manongjohn** [comment]
Sfc fixes or restores missing dlls. Somehow one of your dlls got corrupted and it was able to fix it.

Blame Win10...seems to mess up a lot of people.
