### ISSUE TITLE
Moving Control Points on polyline adds new control points

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2230]
### Issue Summary

A lot of times when I use the control point editor to move a vertex on a poly-line, and if the space is at all tight a new point appears and others which are not even close to the curve jump around
### Screenshot or Video Reference

![opent](https://user-images.githubusercontent.com/25863731/43988973-6a335e7c-9d0f-11e8-964c-f6b9254d7821.jpg)

### Steps to Reproduce

1.make a poly-line shape with several curves close together
2.try to move these points with control point editor, the point you move will cause its neighbors to "jump" and add a new point or points.
### Expected Results

I expect when editing poly-line curves even in tight spaces for me to be in control even if i want to make impractical, weird curves.
### Actual Results

When editing vector curves in anything close to a tight space new points are added and neighbor vertexes jump around...all seemingly to accommodate new curve.  

### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**: 
Nightly build, but also on 1.2.1
windows 10
intel i5-6300u
16gb ram
Intel HD Graphics 520

**Comment by artisteacher** [comment]
I think there’s definitely an issue with the logic for control points. Similarly, importing svg files results in extra control points added that were not in the original svg.

**Comment by phillycheese007** [comment]
was this an issue on toonz harlequin?

is this an issue w/ their logic overlapping with the logic for converting raster to to vector?
If the logic were totally separate then the problem is with how it alters handles when adding or altering a point..that allows it to add and move points.

  As far as i know in straight vector line drawing the code" is not allowed" to add points..only to change handles.  ..this y i say it sounds like the overlap of logics mite be issue.

Anyone more familiar with where this code lives mite shine some light on this or where these files are?

**Comment by jpturcotte** [comment]
Is this still a problem on the latest nightly?

**Comment by RodneyBaker** [comment]
Good question.
A cursory look doesn't show it happening.

@phillycheese007 Can you confirm or deny?

**Comment by artisteacher** [comment]
I've definitely seen this in the past but so far I'm not seeing this happen on the latest nightly build.

**Comment by GeniyX** [comment]
Additional points also arise during prolonged usage of the control point handles, but only after you release mouse button.
This is a rather strange process, as before a new point appears, the place where the curvature begins on the line gradually shifts from the existing point. As if an extra point already exists there.
![ot_bug_control_point](https://user-images.githubusercontent.com/3868717/69987268-2cb75200-1550-11ea-8ed7-1c49d42b53d5.png)
