### ISSUE TITLE
SVG:  Filenaming error with sequence import

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#2231]
### Issue Summary
The latest build of OpenToonz does not recognize a sequence of SVG files as an image sequence in the file browser (NAME..svg or NAME_.svg). OpenToonz will not convert a sequence of SVGs into a single Toonz Vector level--it can only convert single frames.

When using the 'NAME.0001.svg' naming scheme OpenToonz will display the following error: "FILEPATH\NAME.0001.pli: Error file doesn't exist". This happens even if the sequence is a single image. This does not happen if you use the naming scheme 'NAME_0001.svg'. If a pli file matching that name exists it imports the existing pli file but does not convert the svg.

### Steps to Reproduce
1. Create an SVG image using the NAME.0001.svg scheme.
2. Attempt to import the sequence via drag-and-drop, the "Load Level" command, or by right clicking on it in the file browser and selecting 'Load'.

### Expected Results
SVG image is converted to a pli file and imported into the scene.

### Actual Results
OpenToonz displays the error: "FILEPATH\NAME.0001.pli: Error file doesn't exist". The SVG image is not converted or added to the scene.

### System Information
* **OpenToonz Version**: Nightly Aug 8 2018 10:16:49
* **Operating System**: Windows 10

**Comment by RodneyBaker** [comment]
I can confirm this error.
OpenToonz code for importing of SVG sequences apparently associates the sequence with PLI format instead of SVG and when attempting to load that PLI discovers it missing.

The workaround is to rename the file and import the SVG sequence in... then manually sequence.

**Comment by manongjohn** [comment]
I confirmed OT 1.1.3 used to recognized and SVG files properly.  When loading into the scene, I watched it load into 1 column correctly, though something else caused it to crash a few seconds later. 

OT doesn't associate SVG sequences as PLI, though apparently it is failing to create and load a .pli for the SVG, which it used to do in 1.1.3 also.

**Comment by artisteacher** [comment]
While import issues like #2281 are being looked at by @shun-iwasawa (thanks so much!),  I just want to put out there that svg are still not recognized as a sequence, though they were in earlier releases. If the sequence is named with an underscore, it is not recognized as a sequence and loading the first image loads/imports without the other images. 

Svg sequences named with a period, also are not recognized as a sequence but will not finish importing. A critical warning pops up saying that the file doesn’t exist - because it thinks the file is a .pli.

**Comment by RodneyBaker** [comment]
Related to #1928

**Comment by RodneyBaker** [comment]
This should be resolved now due to porting of fixes from Tahoma2D.
REF:  #5117 and #5122
