### ISSUE TITLE
Selection Tool - Whole Level Mode error.

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#2232]
### Issue Summary
When using the selection tool to transform a vector level across multiple frames entering values into the tool option bar only edits the currently visible frame. Dragging the selection works as intended. This apears to affect any mode option that edits more than one frame.

### Steps to Reproduce

1. Create a Toonz Vector level with multiple frames.
2. Select the 'Whole Level' option on the tool option bar.
3. Select any object on the current frame.
4. Enter 45 in rotation box and press return.

### Expected Results
The entire level is rotated by 45 degrees.

### Actual Results
Only the currently visible frame is rotated by 45 degrees.

### System Information
* **OpenToonz Version**: Latest nightly.
* **Operating System**: Windows 10

**Comment by RodneyBaker** [comment]
@melieconiek  In what ways does this issue relate to #2351?

**Comment by melieconiek** [comment]
@RodneyBaker This is a duplicate.
