### ISSUE TITLE
Animate Tool Lag when text is visible

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2233]
### Issue Summary

I have two columns attached by hooks. When i use the animate tool to rotate these rigged columns the response time is much slower if a text layer is visible in the xsheet.
### Screenshot or Video Reference

![fraz](https://user-images.githubusercontent.com/25863731/43994119-8b2a3578-9d65-11e8-8043-d46c1524012a.gif)

### Steps to Reproduce

parent one column to another. add some text with the type tool on any of these layers or on its own layer. Does your animate tool lag? Now delete or hide the text...is it back to normal?
### Expected Results

No lag if text on screen
### Actual Results

lag if text on screen
### System Information
* **OpenToonz Version**: Nightly build
* **Operating System**: windows 10
* **CPU**: intel i5-6300u
* **Memory**: 16gb ram
* **Graphics Card**: Intel HD Graphics 520
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
That didn't turn on any lightbulbs.
You may need to provide a complete project to test.

As of this moment I haven't been able to reproduce the problem.

**Comment by phillycheese007** [comment]
current view of this issue is that Animate tool "all" does not like meshes.....all the other modes work just fine.....everytime i use "all" mode things get incredibly slow

**Comment by RodneyBaker** [comment]
@phillycheese007  There are a number of fixes that have been implemented related to Plastic Tool and meshes.  Can you confirm this is still an issue for you with the most recently nightly release?

Concerning the ALL mode for Animate Tool...
I wonder if that triggers OT to be ready to key all channels versus the single channel it might expect to trigger for storing of values with the other modes.  I don't think so but it would be good to rule that out.

**Comment by RodneyBaker** [comment]
@phillycheese007 A year later and time for a status check...

Much has changed in this past year.  Opentoonz has even gained a dedicated Text FX that allows editable text via dialogue box and/or NoteLevel columns.  Plastic meshes have gained some additional speed due in part by changes to cache management.

How can we re-attack this issue and get it resolved?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@phillycheese007 Please let us know if you are still experiencing this issue.
