### ISSUE TITLE
Brush lag

### ISSUE THREAD

**Issue by val3340** [opentoonz/opentoonz#2234]
### Issue Summary

Hello (I am going to try my best with the English),
Well, I can not draw short strokes, and I do not know why, it works with the touchpad but not with my graphic tablet (but I can do it in Paint for exemple...). This is the first issue.
Second issue, on the screenshot below, i can not draw a circle, every line I draw starts with this straight line... So it is absolutly impossible to draw properly...
Those issues are on raster and vector. 
Ty
Val

### Screenshot or Video Reference

![39010092_2041822246131203_2635350537930801152_n](https://user-images.githubusercontent.com/42322883/44005161-05219b6e-9e6f-11e8-9e4e-a4e6940a50d0.png)

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by val3340** [comment]
Ok, I found the answer on the google users's forum.
I had to desactivate the windows ink. Now it's perfect.

**Comment by manongjohn** [comment]
I'm guessing you turned Windows Ink off on your tablet? 

Actually, if you download the latest nightly, Windows Ink support is now available by enabling it in OT preferences.

**Comment by val3340** [comment]
No, on my PC.
oh ? in wich tab please ? because I passed a long time in preferences without success.

**Comment by manongjohn** [comment]
You need to download the latest OT nightly to get the setting to turn on Windows Ink Support.

If Windows Ink is supported on your PC, you will see a 'Tablet Settings' tab at the very bottom of the Preferences dialog.

Btw, what version of Windows are yoy on? How are you able to turn off Windows Ink? I couldn't find a setting for that.

**Comment by facelesspanda** [comment]
@manongjohn 
Windows Ink activation is tablet settings, not Windows settings.

Here's where I find it on my Wacom tablet settings window
![](https://puu.sh/Be8RW/d239ca0618.png)

I didn't know Windows Ink was impairing tablet use. I had no issue with Raster so I thought I had a problem with vector levels.

I'll try deactivating Win Ink then.
Thanks you two

**Comment by manongjohn** [comment]
@facelesspanda That works for dedicated tablets but doesn't work for laptop-tablets.  We can't turn Windows Ink off, and I thought someone found away.

Regardless, If you don't want to wait for the next official release (who knows when), you can keep Windows Ink setting on tablet if you download and install the latest nightly which now has a preference setting to allows WinInk support.

**Comment by val3340** [comment]
Hello, no I turn off the "real windows ink", i did not touch the tablet settings.
Here the screenshot of how to do it. 
![img_2592](https://user-images.githubusercontent.com/42322883/44105315-98b856fa-9ff1-11e8-8f4e-1d2a78b6970e.PNG)

**Comment by jpturcotte** [comment]
Hi @val3340 & @facelesspanda,
You can find the nightly release here: https://github.com/opentoonz/opentoonz/releases/tag/nightly. This build should work with Windows Ink thanks to @manongjohn's incredible work.

**Comment by RodneyBaker** [comment]
Closing this issue as @val3340 reports resolution of problem.
