### ISSUE TITLE
Small "animate" cursor in skeleton tool in HiDPI Mac

### ISSUE THREAD

**Issue by flaviohr** [opentoonz/opentoonz#2235]
### Issue Summary
Skeleton tool/animate function, the cursor icon appear small than non HiDPI resolution.

### Screenshot or Video Reference
![screen shot 2018-08-13 at 3 39 29 am](https://user-images.githubusercontent.com/19403672/44018969-7776214e-9eab-11e8-9221-deb6c6859aee.png)
tool in non  HiDPI resolution.

<img width="170" alt="screen shot 2018-08-13 at 3 40 12 am" src="https://user-images.githubusercontent.com/19403672/44018975-79a6560a-9eab-11e8-83b9-475370ffd944.png">
tool in HiDPI resolution

### Steps to Reproduce
- actually in 1650x1080 HiDPI resolution, the tool looks small.
- changing to non HiPDI in the same resolution, the tool appear normal.

### System Information
* **OpenToonz Version**: 1.2.1 
* **Operating System**: MacOSX high Sierra 10.13.3
* **CPU**: 2.3 GHz Intel Core i5
* **Memory**: 16 GB 2133 MHz LPDDR3
* **Graphics Card**: Intel Iris Plus Graphics 640 1536 MB
* **Graphics Tablet**: Wacom bamboo CTL 460

**Comment by artisteacher** [comment]
This is already reported in #1216 - there are quite a few high dpi issues still.

**Comment by jpturcotte** [comment]
@flaviohr You should post in #1216 as @artisteacher said.

Recommend close.

**Comment by flaviohr** [comment]
allright
