### ISSUE TITLE
(Particles) Trail + Render = Problem

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#2236]
### Issue Summary
Hello, in the process of studying the program I encountered a problem. It consists in the parameter Trail in Fx Settings in the Birth Params tab and Render - as a result of the rendering, the tail of the characters for some reason moves abruptly, although with the preview everything is fine.

### Screenshot or Video Reference

Render result https://youtu.be/GEoZ7yyUNfc
Preview screencast https://youtu.be/KRVaWIFYScs

### Steps to Reproduce

maybe I can leave the sandbox folder
[SandboxButRenamed.zip](https://github.com/opentoonz/opentoonz/files/2283604/SandboxButRenamed.zip)

### Expected Results
smooth, uninterrupted trails

### Actual Results
trails end in certain frames

### System Information
I made the whole scene and render in OpenToonz 1.1.3 (Regular version).
Then I tried to render in OpenToonz 1.2.0.2 (Morevna version)
Ubuntu 16.04, 64-bit
AMD A9-9400 RADEON R5, 5 COMPUTE CORES 2C+3G × 2 
8 gb memory
AMD STONEY (DRM 3.2.0 / 4.4.0-131-generic, LLVM 6.0.0)
No graphics tablet

**Comment by ARTROSENROT** [comment]
I added links to YouTube

**Comment by RodneyBaker** [comment]
Keeping this issue open for now although the author has deleted their github account.

**Comment by RodneyBaker** [comment]
This issue could use a champion as the original poster is now a github ghost (i.e. account deleted and report abandoned).  The video links still work.

.This issue may be resolved now that the Matte Color feature has been added.
See Preferences > Savings.

This may also be a duplicate report as similar issues were reported by @wolfinabowl.

**Comment by RodneyBaker** [comment]
I am curious if #4491 resolves this issue.

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
