### ISSUE TITLE
Preview window only displays partial canvas

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2237]
Very often, when I open the "Preview" window, only a quarter of the canvas is displayed. If I zoom out on the canvas, then when it is distant, it completely disappears.
If I use "Clone Preview", then the cloned window works well.
### Screenshot or Video Reference

![ezgif-4-1adfaa052e](https://user-images.githubusercontent.com/25724133/44048467-0c1318a0-9f3a-11e8-9edd-a1be3e15ac2c.gif)
### Steps to Reproduce

I could not figure out why this happens, it seems, it happens randomly, and lasts until the end of the OpenToonz session. After restarting this problem, there may not be some time, then it reappears. Or not.
But it happens quite often and at the most inappropriate moment.

### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1
* **Memory**: 4 GB
* **Graphics Card**: NVIDIA GeForce 9500 GT

**Comment by beeheemooth** [comment]
It is possible that this thing is somehow related to  "Snapshot " and
 "Compare to Snapshot "

**Comment by beeheemooth** [comment]
It seems that I found a way to reproduce this bug: if I switch between "Rooms" when the "Preview" window is active.
![ezgif-4-9d9bd88df1](https://user-images.githubusercontent.com/25724133/45055461-82285900-b098-11e8-838a-084581888420.gif)

**Comment by turtletooth** [comment]
Confirmed

**Comment by RodneyBaker** [comment]
I'm curious if checking the option to "Apply Shrink to Main Viewer' in Preview Settings effects this.

![preview settings](https://user-images.githubusercontent.com/2576432/50084132-8f86d080-01bb-11e9-9763-459fa537dd54.png)

**Comment by artisteacher** [comment]
Just ran into this in 1.3 after using the “fit to window” command from the context window.

**Comment by RodneyBaker** [comment]
I looked for the PR related to potential fix for this but didn't find it.
@beeheemooth can you confirm this is still an issue?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@beeheemooth please let us know if you are still experiencing this issue.
