### ISSUE TITLE
Undo after a drawing paste leave a null cell

### ISSUE THREAD

**Issue by z-uo** [opentoonz/opentoonz#2243]
### Steps to Reproduce
draw on a cell
Select part of the drawing with the select tool - Ctrl C
Go to a blank frame - Ctrl V
The drawing is pasted
Undo the action

### Expected Results
The cell should disappear from the xsheet and the level (same as when you create a cell by drawing on the canvas and you undo that)

### Actual Results
The drawing is deleted from the level but it leave a null cell on the xsheet

**Comment by RodneyBaker** [comment]
Closing this as it appears to be resolved in current nightly releases.
@z-uo  Please advise if that is not the case.

There does appear to be a refresh issue after undo where the frame in the level strip does not immediately disappear.  This might relate to the observed issue with focus/refresh.
