### ISSUE TITLE
Serious lag time w/ rig combining plastic and non plastic bone animation

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2248]
### Issue Summary

Ok so I followed this tutorial to the T.  https://www.youtube.com/watch?v=vxENRJ-_5wY
Everything good.  The rig consists of separate torso, arms, legs, and head and hands.  The torso, arms and legs all have plastic meshes. The hands and torso are attached w/ hooks and use an expression to add all the vertices of their specific bone chain so as to get the final rotation. The "plastic animate" setting responds very quickly......................
However when I try to do anything with the regular "skeleton tool" (set to animate) things get alarmingly, unusably slow.  U can see in the video..i am just trying to swap a drawing on the hand..which apparently is too much to ask 
### Screenshot or Video Reference

![fraz2](https://user-images.githubusercontent.com/25863731/44302269-308b7a80-a2f3-11e8-9556-cbb380910884.gif)

### Steps to Reproduce

Create a multi part plastic mesh rig.. leave at least one piece non plastic i guess for clarity sake...now try to use the skelton tool to animate this piece.....
### Expected Results

For the skelton tool to work at the same speed as the plastic animate tool
### Actual Results

you wait for 1 minute for cursor to even move
### System Information
* **OpenToonz Version**: nightly before the current one
* **Operating System**: windows 10
* **CPU**: intel i5-6300u
* **Memory**: 16gb ram
* **Graphics Card**: Intel HD Graphics 520
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
How many frames do you have in that level to select from?
If there is only one frame that would explain why when you attempt to select another frame it refuses... because there isn't any to choose from.

Not sure but that's my first thought.

**Comment by phillycheese007** [comment]
2 Frames.  I should have been more clear...the lag starts the second i even click the skeleton tool...like before i can even make my way over to click the "animate" option

**Comment by phillycheese007** [comment]
Is this just my computer or is this opentoonz? 
anyone else having same issue?

**Comment by phillycheese007** [comment]
I am moving this issue into a more general issue about The animate tool in "ALL" mode being very slow...if meshes are present
