### ISSUE TITLE
Animated "Guided Drawing" option needs to be removed.

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#2251]
With the new update to the viewer only updating pixels that have changed, the animated guided drawing option needs to be removed.  The static arrows still work, but the animated lines don't update properly.

I would remove it myself, but I can't get my build environment to work.

**Comment by openanim** [comment]
Can not this be repaired rather than removed ? I remember that there was also a problem updating with the 2nd guided mode and that Shun iwasawa had managed to fix it. Is the problem here different ?

**Comment by konero** [comment]
If someone works on this, can you please make the arrow color adjustable? 🙏

**Comment by turtletooth** [comment]
Right now, only part of the viewer is being updated every frame.  I'm not sure how that works, so I don't know how to fix it.  If @shun-iwasawa would like to, awesome.  Do we need 2 different views for doing the same thing though?
@shun-iwasawa I have my build setup working again, so if you decide it should be removed, I can do that.

**Comment by openanim** [comment]
Personally, I use the arrows, so my workflow is not affected by that. Nevertheless, I remember that at the time when you put this in place some people had asked to also keep this mode, a matter of preference I guess.

**Comment by RodneyBaker** [comment]
I wouldn't remove it as it is still working (if only slightly) when hovering over the line.
