### ISSUE TITLE
Imported levels from photoshop are locked

### ISSUE THREAD

**Issue by agatre** [opentoonz/opentoonz#2252]
Placed a psd file and choosing to make layers into columns.
![captura de pantalla 2018-08-21 a la s 7 12 59 p m](https://user-images.githubusercontent.com/25806183/44435729-ea464d80-a576-11e8-81ab-d49d65c06585.png)

This error window appeared 
![captura de pantalla 2018-08-21 a la s 7 13 03 p m](https://user-images.githubusercontent.com/25806183/44435734-efa39800-a576-11e8-93a1-3efcc637296f.png)

Didn't see a problem until I tried to use a tool like the eraser button.
Opentoonz claims the frame is locked. 
![captura de pantalla 2018-08-21 a la s 7 16 31 p m](https://user-images.githubusercontent.com/25806183/44435741-f5997900-a576-11e8-853f-2cf9c8cd5e4c.png)

I hope I'm being dumb and there is a quick way to undo this on all levels, because saving all parts of a puppet as pngs and dropping them on the timeline is much more time consuming than dropping the psd file. Clicking around and finding no option to unlock frame. I remember once using photoshop image files and being able to edit them.

### System Information
* **OpenToonz Version**: 1.2 latest
* **Operating System**: MacOS
* **CPU**:  MacBook Pro
* **Memory**: 120 GB
* **Graphics Card**: Intel HD Graphics 4000 1536 MB
* **Graphics Tablet**: No tablet. Using USB mouse.

**Comment by artisteacher** [comment]
I thought they’d always been locked. A workaround is to make a level with the same number of frames (placed to the left of each psd level) and use the merge levels command. The resulting levels should be editable.

**Comment by shun-iwasawa** [comment]
Unfortunately saving PSD files does not implemented in OpenToonz.

**Comment by agatre** [comment]
So it's a matter of format. Good to know for the next time. Thank you. 
This makes me wonder if renaming a psd layer xxx.png will make it show as a png or still as a psd file.
