### ISSUE TITLE
Crash on "Load Level" (Surface Pro)

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#2256]
Surface pro 2017 i5 8GB

crash on "Load Level" when Load Level window appears

**Comment by RodneyBaker** [comment]
Is this a one time occurrence, random or persistent with every attempt to use Load Level?
A video/screen capture of the process you are using will be helpful in troubleshooting and resolving the problem.

**Comment by RodneyBaker** [comment]
@bobbybutterfly Are you still experiencing this issue?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@bobbybutterfly Please let us know if you are still experiencing similar issues.
