### ISSUE TITLE
Auto-Save: Dragging Node Connection Freezes Program

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2260]
### Issue Summary

I have auto save set to every 5 Minutes...If it happens to start saving while I am dragging a node line/connection the program freezes..forcing me to quit
### Screenshot or Video Reference

here is a screenshot of the application error i got
![aaaacapture](https://user-images.githubusercontent.com/25863731/44633907-6c5fb900-a95f-11e8-8320-ba7cacb140fb.PNG)

### Steps to Reproduce

hmmm....drag node lines until auto save kicks in :)
### Expected Results

no freeze
### Actual Results

freezes
### System Information
* **OpenToonz Version**:  the last nightly
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
@phillycheese007  After all the various Schematic updates have been merged that are currently pending it will be good to reassess this issue and see if it is still a problem.  There are quite a few that have already been merged but others are still pending.

cc @manongjohn

**Comment by RodneyBaker** [comment]
Closing as stale, likely resolved and or abandoned.
@phillycheese007 Please let us know if you are still experiencing issues.

Also, as there have been a number of issues reported with use of Autosave there may be other reports that sufficiently capture this general issue of processessing concurrently while Autosave is working.  That may be a good place to add a reference to this   report.
