### ISSUE TITLE
The handle for moving the frames in timeline view is hard to click

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#2262]
This may be just me, but I have a hard time clicking the handle for moving frames when in timeline view.  It's a pretty small target especially when using a pen vs a mouse.  @manongjohn Is there any way to get a couple more pixels of height in there to improve the target?

**Comment by z-uo** [comment]
I agree, with a tablet, it is very small. Keyframe are also very small, I tend to take my mouse to move these.

Is there a need for a handle, maybe the whole cell can be draggable?

**Comment by konero** [comment]
@turtletooth I recommended the same thing awhile back, though can't remember what the problem was.

**Comment by manongjohn** [comment]
@konero probably me being stubborn and wanting to keep similar behaviors between xsheet and timeline. 😁

Whatever change is made will probably also impact the Column Header drag bar.

**Comment by gab3d** [comment]
@turtletooth I'd have no problem at all with such a system, but I suspect the japanesse animation studios currently using OT would have to give their agreement as well for that to be included.

**Comment by artisteacher** [comment]
Would that interfere with renaming or inputting frame numbers?

**Comment by phillycheese007** [comment]
what would being able to click directly on the cell to move interfere with? if it's just a matter of consistency i would place that at lower priority than ease of use. a little info in the docs to take care of any confusion

**Comment by artisteacher** [comment]
I think that would interfere with click & drag to select multiple cells.

**Comment by konero** [comment]
The only feature it would interfere with is **Enable to Input Cells without Double Clicking**, found under the Xsheet settings in the Preferences panel, I think.

I wonder if this could be solved with a cursor change? For example when you hover the handle the cursor changes to the hand icon, this is what happens in Clip Studio.

![csp_cursor](https://user-images.githubusercontent.com/19820721/44947107-e8df1580-adff-11e8-9c45-cda41e00fc5b.gif)

Clip Studio's handle is 7px.

**Comment by gab3d** [comment]
@z-uo  I agree. This should be fairly intuitive in most cases.
- if the desireds cells are not selected the action (click+drag) would allow you to select them.
- if they are already selected the same action (click+drag) o one of them would allow you to move them. I see this second step logical, because you already have the desired cells selected anyway.

the solution proposed above by @konero (changing the cursor icon) would give the user the perfect feedback to know what to expect in his/her next action.

**Comment by artisteacher** [comment]
Changing the cursor is a great idea.
