### ISSUE TITLE
Menus go greyed out

### ISSUE THREAD

**Issue by norrinra** [opentoonz/opentoonz#2265]
This still happen time to time. 
Latest Nightly on Osx. 

![screen shot 2018-08-31 at 6 52 36 am](https://user-images.githubusercontent.com/30438394/44891702-7e3bb600-ace9-11e8-9d0b-610f09d86751.jpg)

**Comment by artisteacher** [comment]
Does this ever happen without autosave being enabled or without a tablet?

I haven’t run into this recently, but when I did, it seemed to happen when auto-save interrupted a process/input. Auto-save shouldn’t interrupt stylus input anymore, but if autosave (or something else) is still interrupting some sort of process/input, that may be the problem.

**Comment by norrinra** [comment]
I will try to test that.  It happens so randomly everytime. It's really hard to distinguish why it happens.

**Comment by RodneyBaker** [comment]
@norrinra Any update?  Are you still experiencing the problem?

**Comment by norrinra** [comment]
@RodneyBaker I didn't see this happening for a long time. I totally forgot about that bug. Should I close it ?

**Comment by norrinra** [comment]
@RodneyBaker Thanks a lot

**Comment by artisteacher** [comment]
I just had a student run into this today while using a tablet. So it looks like the greyed out menu is still a very infrequent issue.
