### ISSUE TITLE
(WIP) Camera Capture and Playback on Same Window

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#2266]
@shun-iwasawa Do you know if it would be possible to playback the scene in the Camera Capture window?  Right now it takes going back and forth to see the playback.

**Comment by turtletooth** [comment]
@shun-iwasawa You guessed it.  It would be for stop motion.  It would be nice to be able to watch the progress of the stop motion periodically without switching between the Camera Capture window and the main window.

**Comment by gab3d** [comment]
I second that too.
When in a stop motion session, it's a natural task to review the progress so far and ending with the live frame, to be able to see the arcs, etc.
So a button that allow you to play, say, the last 10 frames and end displaying the live view would be godsend for stop-motion work.

**Comment by artisteacher** [comment]
Also, I'd love to be able to use our Canon DSLR's at school with camera capture...

**Comment by RodneyBaker** [comment]
Temporarily closing as this moves to the 2019 Development Cycle.
Tagged with 'roadmap'.
