### ISSUE TITLE
memorized the last style used instead of style 1 ?

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2267]
### Issue Summary

Sorry if this is a duplicate,

Is it possible for a level to remember the last style used when changing columns ?

Currently, I have style 1 which is chosen each time. Which is not very practical, I think. I do not know if there is a way around this so that it is the last style that is stored for each level even if i change the column?

For example, if I work with style 3 on column 2 and go back to column 1, style 1 will be used automatically (even if I was on style 5 before). If I go back to column 2, style 1 will be used too, instead of 3. It is not very impacting if we work in black by default, but as soon as it's different, it's very frustrating. In my opinion, the ideal would be that the last style specific to a level is memorized. I hope it's understable.

### Steps to Reproduce

1. Create 2 columns or more with severals styles.
2. Use a different style than the first by default.
3. Go to another column and come back.

You will not be on the style you were using.

### Expected Results

Last style memorized

**Comment by gab3d** [comment]
indeed!
that'd be very useful.
...and the program would only need to remember this during an open session, so it wouldn't be something to store in a file, either.

**Comment by artisteacher** [comment]
This would be great!

**Comment by openanim** [comment]
Ok, I'm going to close my issues that are more like features request.

**Comment by RodneyBaker** [comment]
@openanim  Thanks for closing stray topics as that frees up high priority issue to receive full attention.

If there isn't a related feature request in the OpenToonz forum please post the request there.
Shun and other watch for those and grab them as they find opportunity. : )

**Comment by openanim** [comment]
Rodney i close it as duplicate of this one #1757
