### ISSUE TITLE
Crash upon opening

### ISSUE THREAD

**Issue by sunnyzhp22** [opentoonz/opentoonz#2269]
### Issue Summary
I just got a new computer (hp envy, windows 10) and after trying to download opentoonz on it, I can't open the program and work with it. I have looked through the boards and have not been able to find out how to fix the issue.

### System Information
* **OpenToonz Version**: v.1.2.1 (as well as the recent versions of Morenda and the nightly builds)
* **Operating System**:  windows 10
* **Memory**: 8 gb

**Comment by animating-dino** [comment]
try to do write sfc/scannow In command prompt and to check the error open the event viewer to view 
the error.

**Comment by sunnyzhp22** [comment]
it seems to be that the windows 10 update removed OpenGL from it's graphics card and that is causing opentoonz to crash, is there anyway to deal with this?

**Comment by RodneyBaker** [comment]
it seems to be that the windows 10 update removed OpenGL from it's graphics card and that is causing opentoonz to crash, is there anyway to deal with this?

You should determine what graphics card you are using and then visit the site for that manufacturer.
They will have drivers for all of their hardware and usually have software that can be run to determine current status.   If you provide information about your graphics card we can help you find an appropriate driver link.

The most common graphics cards would be Intel Graphics, NVidia and AMD.

**Comment by sunnyzhp22** [comment]
I am using an intel CORE i5 8th gen and the driver model seems to be WDDM 2.4

**Comment by RodneyBaker** [comment]
@sunnyzhp22  Are you still having issues?

**Comment by RodneyBaker** [comment]
Closing as possibly resolved and/or abandoned.
@SaierMe Are you still experiencing this issue?
If so please let us know.

**Comment by sunnyzhp22** [comment]
I am still having issues and is unable to open the program at all

**Comment by RodneyBaker** [comment]
Give the OTX release a try and see if that makes any difference.
Here's the direct link:

https://github.com/manongjohn/OTX/releases/download/OTX-nightly-2019-12-06/OpenToonz-OTX-win.zip

This is a portable application so all you have to do is unzip the file and run the Opentoonz.exe inside.
Files will be saved in the 'portablestuff' directory unless otherwise directed.

Here's a link to all the OTX release (those released by @manongjohn) if you prefer not to click on unknown links and choose the file personally:
https://github.com/manongjohn/OTX/releases

Former OTX releases prior to that are located elsewhere.

**Comment by sunnyzhp22** [comment]
I am able to open and make the OTX version work!

**Comment by RodneyBaker** [comment]
That suggests to me that you need to perform a clean install with the normal (official) release in order to get it working.

I'd be happy to walk you through the clean install process if you want to give that a try.

**Comment by sunnyzhp22** [comment]
I would like that, would you be free to do it now?

**Comment by RodneyBaker** [comment]
Sure thing.

Steps coming up in this post (I'll edit them in).

**Comment by manongjohn** [comment]
If I had to guess, i think your `C:\OpenToonz stuff` folder may not be editable. You might need to grant permission to yourself so you can write to it.

**Comment by sunnyzhp22** [comment]
:)
