### ISSUE TITLE
Wacom Tablet not recognized

### ISSUE THREAD

**Issue by Victorious3** [opentoonz/opentoonz#227]
(Windows 10, 64 bit)

The tablet is a CTF-420, which runs with the Bamboo drivers, 5.3.5-3, latest version.
Toonz only recognizes its mouse input, which creates a half a second delay before it starts to draw a line, making it practically unusable. Other tools such as Gimp or SAI work perfectly fine with it.

**Comment by kogaki** [comment]
Sorry but this problem might be related to incompatibility between Wacom's old tablet and drivers. We can't reproduce the issue with recent tablets.
