### ISSUE TITLE
opentoonz does not come up after built on ubuntu 18

### ISSUE THREAD

**Issue by coolblock** [opentoonz/opentoonz#2272]
Everything built successfully. Result of command line running is:

/opt/opentoonz/bin/opentoonz
plugin search directory:/home/ddp/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/ddp/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
plugin search directory:/home/ddp/.config/OpenToonz/stuff/plugins
walkDictionary: /home/ddp/.config/OpenToonz/stuff/plugins [dry]
QFileSystemWatcher::addPath: path is empty
terminate called after throwing an instance of 'TFontCreationError'
Aborted (core dumped)

### System Information
OpenToonz Version**: 1,2 
* **Operating System**: linux ubuntu 18 bionic (in virtualbox)
* **CPU**: Xeon
* **Memory**: 8

**Comment by manongjohn** [comment]
Pull #2227 changes into your local repo and rebuild. The fix for that issue has not been merged into the nightly code yet.

**Comment by coolblock** [comment]
git pull #2227 says 
Already up to date.

**Comment by manongjohn** [comment]
Where are you pulling from? If you are pulling from OT's main branch, you'd likely need to pull the branch for this PR from my repository since it isn't merged into main OT branch yet.

To work around this issue without code changes, manually edit C:\OpenToonz 1.2 stuff\profiles\layouts\settings.username\preferences.ini (well the ubuntu version for you)

Change the entry for interfaceFont= to a valid font on your system.

As this issue is already recorded under #2226 I recommend closing this as a duplicate.

**Comment by coolblock** [comment]
I tried some valid fonts in the user/.config file. That did not work. Same symptom.

Remember this is ubuntu

**Comment by manongjohn** [comment]
Try this. Not sure how you are putting in the value in the file. Open an older version of OT, if you can, open Preferences and change your font there then save and close. Theb open in the latest version and see if that helps?

Other way to fix that is to download the code from the PR i mentioned or pull it in from my repository and recompile.

**Comment by coolblock** [comment]
I built using your repo. I must be doing something wrong. I will put in my build script see if you see what is wrong

**Comment by coolblock** [comment]
sudo apt-get install -y git
sudo apt-get install -y mlocate
sudo apt-get install -y build-essential git cmake pkg-config libboost-all-dev qt5-default qtbase5-dev libqt5svg5-dev qtscript5-dev qttools5-dev qttools5-dev-tools libqt5opengl5-dev qtmultimedia5-dev libsuperlu-dev liblz4-dev libusb-1.0-0-dev liblzo2-dev libpng-dev libjpeg-dev libglew-dev freeglut3-dev libsdl2-dev libfreetype6-dev libjson-c-dev
sudo apt-get install -y libmypaint-dev
cd
rm -rf opentoonz
rm -rf $HOME/.config/OpenToonz
 
git clone https://github.com/manongjohn/opentoonz.git
#git clone https://github.com/opentoonz/opentoonz

mkdir -p $HOME/.config/OpenToonz
cp -r opentoonz/stuff $HOME/.config/OpenToonz/
cd
cp -r opentoonz/stuff $HOME/.config/OpenToonz/
cat << EOF > $HOME/.config/OpenToonz/SystemVar.ini
[General]
OPENTOONZROOT="$HOME/.config/OpenToonz/stuff"
OpenToonzPROFILES="$HOME/.config/OpenToonz/stuff/profiles"
TOONZCACHEROOT="$HOME/.config/OpenToonz/stuff/cache"
TOONZCONFIG="$HOME/.config/OpenToonz/stuff/config"
TOONZFXPRESETS="$HOME/.config/OpenToonz/stuff/projects/fxs"
TOONZLIBRARY="$HOME/.config/OpenToonz/stuff/projects/library"
TOONZPROFILES="$HOME/.config/OpenToonz/stuff/profiles"
TOONZPROJECTS="$HOME/.config/OpenToonz/stuff/projects"
TOONZROOT="$HOME/.config/OpenToonz/stuff"
TOONZSTUDIOPALETTE="$HOME/.config/OpenToonz/stuff/studiopalette"
EOF
cd
cd opentoonz/thirdparty/tiff-4.0.3
./configure --with-pic --disable-jbig
make -j$(nproc)
cd ../../
cd toonz
mkdir build
cd build
cmake ../sources
make -j$(nproc)
cd
cd opentoonz/
cd toonz
cd build/
sudo make install
/opt/opentoonz/bin/opentoonz

**Comment by coolblock** [comment]
It builds fine but won't run

/opt/opentoonz/bin/opentoonz
plugin search directory:/home/ddp/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/ddp/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
plugin search directory:/home/ddp/.config/OpenToonz/stuff/plugins
walkDictionary: /home/ddp/.config/OpenToonz/stuff/plugins [dry]
QFileSystemWatcher::addPath: path is empty
terminate called after throwing an instance of 'TFontCreationError'
Aborted (core dumped)

**Comment by manongjohn** [comment]
After 'git clone .....' my repo, you need to 'git checkout font_loading_crash_fix' to build the specific branch that has this fix.

**Comment by coolblock** [comment]
ok works now with
git checkout font_loading_crash_fix
