### ISSUE TITLE
Transform ink chek and shift and trace for Colors Markers / letters markers K,B,I in level strip

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2276]
### Issue Summary

Currently memo and note level only works for the xsheet.

So, I was wondering if we could transform the following features to have an official way to mark the drawings during a tweening process because it is not always easy to recognize his keys, after several tweens.

1) Personally I use inkchek # 1 for this because it highlights the strokes in red but only on the level strip (unlike inkchek). Even if it does not seem to be done for that, it works well with vector levels and it's almost usable already. But it requires adjustments for more comfort. See the mini gif below.

![colors marks opentoonz](https://user-images.githubusercontent.com/29790512/45126663-c426cd00-b174-11e8-95b2-a002dd88227f.gif)

- If you want to mark in red, activate inkchek # 1 before starting to draw what will be a key for example. And disable or undo to switch to black. Delete a drawing then enable or disable inkcheck according to the color you want.

- Would it be possible to duplicate the command inkchek # 1 in 3 color markers for example red, blue and black in order to be able to mark the drawings that one wishes without having to play with the delete, undo key or inkcheks state.

- When you mark in red the last drawing of the level trip and then undo several steps or insert 1 or more drawings, it happens that the drawing changes color and becomes black, we can prevent this by activating inkchek # 1 before inserting the drawings or severals undo. It would be nice if it worked without so much care.

- The marked drawings are lost during a save. It would be cool if the markers could also be saved.

2) Another option would be to use the fixed onion placement of the level strip to mark the drawings, much like the new shift and trace markers. 

![letters markspng](https://user-images.githubusercontent.com/29790512/45125200-b3bf2400-b16d-11e8-9c57-4efa10fad614.png)
- And that the markers can synchronize with the drawing on which it is. 

This request is something similar to this feature request #325 and in forum https://groups.google.com/forum/#!searchin/opentoonz_en/complex%7Csort:date/opentoonz_en/fYbQtJeLdFU/Zf9iL98_BAAJ also.

is it something that would be difficult to transform ?

**Comment by jpturcotte** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by mwerezak** [comment]
> Personally I use inkchek # 1 for this because it highlights the strokes in red but only on the level strip (unlike inkchek). Even if it does not seem to be done for that, it works well with vector levels and it's almost usable already. But it requires adjustments for more comfort. See the mini gif below.

I've been trying to figure out what "Ink #1 Check" does and this page is the only reference I can find. What does "Ink #1 Check" do?

**Comment by RodneyBaker** [comment]
@mwerezak In the Palette there are two default styles zero and one (0 and 1).
Those are present in every palette.
With "Ink No.1 Check" the check will only display that default color no. 1 style and not other lines (ink) created with other styles.

Thanks my understanding of it.
I don't quite understand the previous refererence to "...but only on the level strip (unlike inchek)...".  I'm not sure what Jeremy (ghost) is referring to here outside of thoughts for enhancing other features.

Hope that makes sense.

**Comment by gab3d** [comment]
Ink #1 Check, shows in red all lines drawn using the color number 1 (most usually black). All other lines are also shown in their normal colors.

Ink Check does the same but with the selected Palette color.
(if you have Color 1 selected in the Palette, both checks will work just the same)

**Comment by mwerezak** [comment]
Ok, so that's what it is. Thanks
