### ISSUE TITLE
Error 5: Access Denied is all i see when i try to download OpenToonz

### ISSUE THREAD

**Issue by LonelyHeart66** [opentoonz/opentoonz#228]
Every time i try to download OpenToonz, i only see the "error 5: Access Denied" error box. ive tried to maybe clear up space to try and make it so opentoonz will download, but each time i try to download it i get that error and it shuts the download down and doesnt change anything. i have no idea what to do.

**Comment by kogaki** [comment]
I think this isn't related to OpenToonz but your settings on windows system. Is the following url about this problem ? <http://www.personalcomputerfixes.com/general-errors/how-to-fix-system-error-5-–-“access-is-denied”/>

**Comment by LonelyHeart66** [comment]
that didnt seem to help :/

**Comment by kogaki** [comment]
Sorry but we can't help because this is not opentoonz specific problem. You could ask at User Forum. Thanks.
