### ISSUE TITLE
Import issue with underscore and image sequences

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2281]
### Issue Summary

Importing an image sequence only partially works. The images do import into the project but do not display in the viewer or level strip. Maybe it's another naming issue?
### Screenshot or Video Reference

![screen shot 2018-09-07 at 10 29 40 am](https://user-images.githubusercontent.com/21159116/45224824-f88bad80-b288-11e8-8846-a8b1934df3f9.png)

### Steps to Reproduce

Import an image sequence using the name format name_0001.jpg using load level in the XSheet or through drag and drop
### Expected Results

The image sequence should be visible in the level strip and Xsheet and an icon should be visible in the column header. 
### Actual Results

A level is displayed in the XSheet but any display of the images/icons is missing. The level also displays in red text in the Scene Cast and without an icon the schematic. If using drag and drop with the first frame, only a single frame displays in the Xsheet. Loading works as expected.
### System Information
* **OpenToonz Version**: latest nightly build
* **Operating System**: MacOS 10.13.6
* **CPU**: 2.5GHz Intel Core i5
* **Memory**: 8GB
* **Graphics Card**: AMD Radeon HD 6750M
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
As a workaround, dragging & dropping the image sequence directly into the extras folder through the Browser and then loading the level from the Browser, works as expected. For some reason imported sequences are not including the _ or . as part of the image names which breaks the path.

Imported sequence:
![screen shot 2018-09-07 at 1 57 59 pm](https://user-images.githubusercontent.com/21159116/45235209-29c6a680-b2a6-11e8-8e95-13f45530abf5.png)

Loaded sequence:
![screen shot 2018-09-07 at 1 58 15 pm](https://user-images.githubusercontent.com/21159116/45235219-2f23f100-b2a6-11e8-9f15-b29688eab5a5.png)

**Comment by artisteacher** [comment]
At home I’m only having trouble importing an image sequence with an underscore, so periods might be ok (I’ll double check in school after the long weekend). Changing the path in the level settings to include the _ instead of the first . allows the level to display properly. 

Strangely, when importing a sequence that uses an _ in front of the number, if the sequence does not start at 01 (or etc.) and begins at something like name_1235.jpg, the image numbers that display in the Xsheet starts at 1. In that case, after fixing the path, the images still do not display since the numbering is wrong. Of course they can be added from the level strip at that point.

Also, I haven’t tried to import any image sequences in several months, so I’m not sure how long this has been going on.

**Comment by artisteacher** [comment]
Naming conventions with a period work just fine. The naming/path issue on import only occurs with an underscore - ie. name_01.jpg

**Comment by artisteacher** [comment]
With the fix in #2324, now importing the sequence from the load level dialog works fine until reopening the saved scene. Then the sequence displays as missing due to a name/path issue. 

If the sequence is imported through drag and drop instead, the sequence immediately displays as missing.

**Comment by shun-iwasawa** [comment]
@artisteacher 
I tried the following steps:

- Load `name_0001.jpg` via load level command
- Save the scene
- Restart OT and load the scene

It worked with no problem on my windows 7 environment.
Am I missing something, or does it seem to be a OSX specific problem?

**Comment by shun-iwasawa** [comment]
@artisteacher 

>Choose import from the import/load dialog

That's it! I could reproduce the problem. Thanks!
