### ISSUE TITLE
Data issue when writing scene file caused failure to load later

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2284]
A user had reported a problem reloading a scene which resulted in assets in xsheet appearing as missing (red) but they were actually in the Project folders.

Upon detailed analysis of the .tnz file, I found that some data was written out incorrectly. It had written out some characters instead of numbers. When it tried to load this data, OT stopped loading the rest of the scene.

Here is the snippet of the scene file causing the issue.

>       <pegbar id="Col4">
>        <parent handle="B" id="Table" parentHandle="B">
>          </parent>
>        <name>
>          "Temp portal"
>        </name>
>        <isOpened>
>          0
>        </isOpened>
>        <center>
>          -nan(ind) -nan(ind) nan nan
>        </center>

The `<center>` values should be numeric.  Changing them to `0 0 0 0` corrected the loading issue.

Aside from trying to figure out why it wrote out essentially garbage and prevent it from doing that again, In my opinion OT should be fixed to trap odd errors like this, replace with a default value, provide the user a warning that a correction was made, but still load the scene as much as possible.

**Comment by shun-iwasawa** [comment]
`nan` (=NaN) means "Not A Number" and `-nan(ind)` means "Negative indefinite NaN" .
There must be invalid arithmetic operation in the source, like add positive infinity and negative infinity, or take the square root of a negative number.

Anyway I totally agree with you to add a fail-safe, which enables to open the scene when the scene contains invalid values.

**Comment by RodneyBaker** [comment]
@manongjohn do you know if anything ever happened on this one?
I've tagged this as a known issue as it is something users should look for if they run in to the problem.

Also, I have a vague memory of a Reset Center fix and wonder if that might have altered/resolved this.

**Comment by RodneyBaker** [comment]
Closing as resolved in current releases but users still operating with v1.4 may experience this problem.
