### ISSUE TITLE
low quality vector lines on linux. Test (png vs svg) [Win vs linux]

### ISSUE THREAD

**Issue by teury** [opentoonz/opentoonz#2285]
### Inkscape SVG
![inscape svg](https://fotos.subefotos.com/1fcf8401c545a5b047c9b8721ad82dc4o.png)

### Inkscape export in png (Each part) and rendered by OP
![Inkscape export in png ](https://fotos.subefotos.com/7f389234500835e31789d65d223fb8c2o.png)

### OT SVG Render
![OP SVG](https://fotos.subefotos.com/c717201b22be4378a67b21f1e861574co.png)

I have obtained multiple errors when rendering the vector lines, which should be of a high quality, but for some reason I have seen that vector lines are exported with very low quality mainly in linux.

### Render win 10 vs linux ubuntu.
![win vs linux](https://fotos.subefotos.com/2878b80c1b12d9b6b1be1cc9948b7de8o.png)

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: Linux ubuntu 64bits
* **CPU**: i5 3ra
* **Memory**: 8 GB
* **Graphics Card**:  Intel G. 400
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
That’s a pretty big difference in quality. Maybe @morevnaproject and @blackwarthog can help.

**Comment by shun-iwasawa** [comment]
@teury 
Does OT render all Toonz Vector Levels with jagged appearance in your Linux environment, or is this occurs only when importing SVG ?
OT renders vector lines in two steps. The first step is drawing anti-aliased outline and the second one is filling inside of the stroke. (In [here](https://github.com/opentoonz/opentoonz/blob/25d3db05fd57aed51d666455ac8dbc44067a4cea/toonz/sources/common/tvrender/tsimplecolorstyles.cpp#L466-L470) in the source). Your result seems to fail in the former step.

**Comment by blackwarthog** [comment]
@teury please try to check how your OpenGL driver draws the lines by the simple test from this post: https://github.com/opentoonz/opentoonz/issues/2285#issuecomment-419763378

**Comment by morevnaproject** [comment]
@teury As it is mentioned by @blackwarthog in https://github.com/opentoonz/opentoonz/issues/2285#issuecomment-419773471 - the problem is with your drivers.

Please run a test from this post - https://github.com/opentoonz/opentoonz/issues/2285#issuecomment-419763378 - and post results here.

**Comment by blackwarthog** [comment]
Also you may check linux appimage from Morevna Poject:
https://github.com/morevnaproject/opentoonz/releases
https://github.com/morevnaproject/opentoonz/releases/download/v1.2.0.3-morevna/OpenToonz-1.2.0.3-morevna-18.06.17-linux64-b8b54.appimage

Seems aliasing is related with implementation of GL_LINE in different drivers. In Morevna edition of OpenToonz we implemented drawing of lines by other way without using of GL_LINE.
