### ISSUE TITLE
FFMPEG path

### ISSUE THREAD

**Issue by adrienlabigne** [opentoonz/opentoonz#2293]
### Issue Summary
Hello, I have to add ffmpeg path to 200+ Mac for the school I work to, but don't have the time to do it manually on each (they are used all day).
Is there a config file or a command line to talk to OpenToonZ where ffmpeg is stored on computer ?
What if I put ffmpeg folder into OpenToonz.app/Contents/Framework ?

Thanks in advance!

### System Information
* **OpenToonz Version**: 1.2
* **Operating System**: macOS 10.13

**Comment by adrienlabigne** [comment]
Hey, that's exactly what I was looking for :)

Unfortunatly I still can't find this file.. Do you have a path & name for it ? Is it in 1.2 (not 1.2.1) ?

Thanks.

**Comment by RodneyBaker** [comment]
I'm not sure on the Mac but on windows the preference.ini file is located:

C:\OpenToonz 1.2 stuff\profiles\layouts\settings.logged in username here

This could be problematic if we don't first set up a default.
I'm not sure that plays out across networks.

**Comment by adrienlabigne** [comment]
> This could be problematic if we don't first set up a default.

Hm... On each computer, I have by default 2 users. Witch is the "default" one ? :D

**Comment by RodneyBaker** [comment]
The smartest one.

**Comment by adrienlabigne** [comment]
LOL.

So, the preferences.ini is copied from the first user, to each new ? So if I put the correct info into my 2 created preferences.ini, new ones will have correct informations you think ?

I'll try that on monday, I have to quit now. But thanks a lot for your quick replies !

**Comment by artisteacher** [comment]
Just an fyi, the path is written a little different in MacOS. In my own preferences.ini file, I've placed the ffmpeg folder in my documents directory:
ffmpegPath=/Users/myusername/Documents/ffmpeg

**Comment by RodneyBaker** [comment]
Thanks for closing the loop on that @manongjohn !

Somewhat off topic:
I'm hoping that somewhere in the future the default installation might input a ghosted/prepopulated ffmpeg location for use as I have to resupply that with every clean installation of OpenToonz.  

I think via discord (concerning windows) we made a determination the ideal location would be "..\\ffmpeg\\bin".   Then OT would automatically use ffmpeg if installed in the same Program Files directory that OpenToonz is also installed in and a common place for portables would be back out one directory relative to the current installation directory.    (hope that makes sense)

**Comment by adrienlabigne** [comment]
Problem solved !

The solution, for someone who got the same : write the good path into one preferences.ini file from one user, copy and paste it into "settings" folder. This will become the template for new users ;)

Thanks a lot to everyone here to help me, you will make our users happy ;)

**Comment by RodneyBaker** [comment]
Reopening this with an eye to refine the initial user experience so that it isn't quite as hard to connect to FFMPEG.  There have been a number of suggestions and please note the useful tip by @adrienlabigne above for getting the default set for all users.

A question or two:

- Can we supply a default location that Opentoonz always initially expects to find ffmpeg in and perhaps add that as as soft entry in the ffmpeg address in Preferences?
- Barring that can we adjust the default Preference.ini to allow for a default?

This would be especially useful in testing as ffmpeg has to be 'reattached' every time a new clean build is used.  In the code I noted what appeared to be an attempt to look in specific directories but I've yet to see that be successful in the wild.

**Comment by artisteacher** [comment]
For MacOS, the OpenToonz directory (Applications/OpenToonz) which is the parent directory of the Stuff folder, could be a good default location. I also think the default timeout should be increased a lot. I always have my students increase timeout to 600 when setting up ffmpeg. 

Would it be possible/desirable to set the ffmpeg path from the installer?

**Comment by RodneyBaker** [comment]
> Would it be possible/desirable to set the ffmpeg path from the installer?


We've been discussion this and haven't come to any consensus.
There may even be a separate PR for it.

In the interim there are a few hacks I've been using such as:

Move the most important three ffmpeg files into the root OpenToonz directory.
In preferences enter a period/dot.  On windows this tells OT to look in the root directory.

There are others but it would be nice if there was at least one or two default locations preloaded... perhaps in a drop down so they can at least easily be selected without retyping.

In our tests I think we arrived at an address that worked well across Mac, PC and Linux.
I'll have to check to see what that was but it was basicially:  \\ffmeg\\bin
@jpturcotte might have a better memory than me.

**Comment by artisteacher** [comment]
On my mac (with the ffmpeg directory in the same directory as OT),  ./ffmpeg/bin doesn’t work but ./ffmpeg does. I never see bin as part of a path on a mac.

**Comment by RodneyBaker** [comment]
Closing (for now) as enhancements to ffmpeg integration with Opentoonz has slipped to 2019 development cycle.

**Comment by RodneyBaker** [comment]
Note to self to review the ffmpeg path default setting in Preferences (for PC, Mac and Linux) in 2020 development cycle.

**Comment by RodneyBaker** [comment]
Please reference:  #3688 (for a fix with ffmpeg path on snap distros for Ubuntu)

**Comment by RodneyBaker** [comment]
Closing this as resolved with expectation another report will be opened to identify potential solutions for FFMPEG to include resolving path issues.
