### ISSUE TITLE
QT 5.9 DLLs question

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2294]
I recently noticed that OT (Windows) is being released with QT 5.9.2 DLLs (i.e QT5Gui.dll, etc) but aren't we compiling against QT 5.9.4?  Shouldn't the releases be pulling the 5.9.4 DLLs?

Are we still compiling with 5.9.4 or are we actually on a later revision?

The only reason I ask is I've been experiencing some random OT crashes in QT5Gui.dll lately which seemed odd as I've never seen it crash there before.  In cases when I crashed, I think all I did was just touch OT with my pen other than the canvas and it would just suddenly disappear.

Please note that most of my crashes were in a locally built OT version that I compiled with QT 5.9.4, the version we are supposedly using here.  I think I had 1 official OT crash in the same DLL some time ago. My locally built OT contains the lastest OT + some of my unmerged PRs that are not GUI related.  I've replaced my QT5*.dlls with the 5.9.4 versions and I haven't crashed yet.

**Comment by jpturcotte** [comment]
Also, why are we not using the latest Qt 5.9 version, v5.9.6?

**Comment by RodneyBaker** [comment]
It looks like we very well should be moving to Qt 5.12 in 2019.
Official support for 5.9 is planned to be dropped by March.
The assumption being that few updates/patches will be made to 5.9 code.

Ref:  http://blog.qt.io/blog/2018/12/06/qt-5-12-lts-released/

**Comment by manongjohn** [comment]
Can we get some confirmation of what QT version the Appveyor and nightly Windows builds are using? Can we move up to 5.11 or 5.12 to match the Mac/Linux builds?

I recall a change was made to the builds so when Appveyor upgraded QT it didnt cause us to fail but with that change i cant tell what version we are actually on. Either way, the dlls included in the install are still 5.9.2 and probably should be updated.

**Comment by shun-iwasawa** [comment]
Appveyor build uses Qt 5.9.7
https://www.appveyor.com/docs/windows-images-software/#qt

Travis - Linux build uses Qt 5.9.1 for now.
https://github.com/opentoonz/opentoonz/blob/master/ci-scripts/linux/travis-install.sh#L1
It seems that we can update it to 5.9.6
https://launchpad.net/~beineri

Travis- OSX build uses Qt 5.12.0
https://formulae.brew.sh/formula/qt

As @jpturcotte pointed, it is reasonable to move to the latest patch of 5.9 as an immediate goal.
Then I think it would better to migrate to 5.12 as it becomes LTS.

> Official support for 5.9 is planned to be dropped by March.

It's the end of the support of Qt5.6 LTS. 5.9 will be still supported.
http://blog.qt.io/blog/2018/11/29/support-qt-5-6-lts-ends-march-2019/

**Comment by RodneyBaker** [comment]
Thanks for the information... and the correction Shun.
I got my wire crossed in the references.

**Comment by artisteacher** [comment]
Should the cmake file and build directions be updated to use the correct versions of QT?

**Comment by RodneyBaker** [comment]
@manongjohn  Did this question get answered to your satisfaction?
