### ISSUE TITLE
The "Auto Input Cell Number" window can not be moved (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2295]
### Issue Summary

This window appears in the upper left corner of the monitor and I can not move it to another location because the panel to move the window (if it exists) is outside the access range. Does anyone have the same problem?
### Screenshot or Video Reference

![ezgif-1-b51eab1f1f](https://user-images.githubusercontent.com/25724133/45584860-80a23080-b8e3-11e8-843b-7bef1b9d3749.gif)

### System Information
* **Operating System**: Windows 8.1
* **Monitor**: LG Flatron W2042T

**Comment by RodneyBaker** [comment]
I have had that happen in the past but not recently.

To get the window to behave correctly grab the right side (and/or the bottom) and move it toward the left of the screen (in the opposite direction of where we might think we should move it).   This should allow the window to be resized and placed normally.  Once rescued from that position I haven't had it reappear there again.

**Comment by beeheemooth** [comment]
@RodneyBaker I can not grab it (bootom/side/corner), that's the problem. It looks like this is a type of window that can not be resized.

**Comment by manongjohn** [comment]
Close all windows except OT and try cascading the windows on your desktop and see if it will bring it down.

**Comment by RodneyBaker** [comment]
Sorry, I can't demo how to do this because I can't get the window into that position to troubleshoot it.
I recall it was an illusive problem for me for quite awhile then one day I just grabbed it and moved it in a different way.

**Comment by konero** [comment]
Do what @manongjohn suggested.

🖱 Right-click taskbar
🖱 Cascade windows

**Comment by beeheemooth** [comment]
@manongjohn Thank you! It worked! This window no longer goes beyond reach. Thank you all!
