### ISSUE TITLE
memory access error by rendering

### ISSUE THREAD

**Issue by michael1234567891011** [opentoonz/opentoonz#2301]
### Issue Summary
Open toonz crashes if i start rendering.

### Screenshot or Video Reference

> michael@BOSECK:~$ opentoonz >> output 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
PaletteViewerGUI::PaletteTabBar(0x2112600, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x2112600, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x2350350, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x2350350, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x2c15ca0, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x2c15ca0, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
DVGui::TabBar(0x26f77e0, name="StyleEditorTabBar")  does not have a property named  "BottomAboveLineColor"
DVGui::TabBar(0x26f77e0, name="StyleEditorTabBar")  does not have a property named  "BottomBelowLineColor"
DVGui::TabBar(0x23cb440, name="StyleEditorTabBar")  does not have a property named  "BottomAboveLineColor"
DVGui::TabBar(0x23cb440, name="StyleEditorTabBar")  does not have a property named  "BottomBelowLineColor"
DVGui::TabBar(0x2130ec0, name="StyleEditorTabBar")  does not have a property named  "BottomAboveLineColor"
DVGui::TabBar(0x2130ec0, name="StyleEditorTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x2b4e2d0, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x2b4e2d0, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
PaletteViewerGUI::PaletteTabBar(0x25eeff0, name="PaletteTabBar")  does not have a property named  "BottomAboveLineColor"
PaletteViewerGUI::PaletteTabBar(0x25eeff0, name="PaletteTabBar")  does not have a property named  "BottomBelowLineColor"
Speicherzugriffsfehler (Speicherabzug geschrieben)

### Steps to Reproduce

File -> open Recent scene file  
File -> Render

### Expected Results

Expected output of png files.

Thanks for your Help.

### Actual Results

The process crashes.

### System Information
* **1.1.3**: 
* **Operating System**: 
* **Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz**: 
* **8GB**: 
* **NVIDIA Corporation GK208 [GeForce GT 730]**:

**Comment by RodneyBaker** [comment]
No other similar reports have been filed but I note the following:

8GB
NVIDIA

Recommendations: 

Test OpenToonz install on another system to validate it it working for you.

Use the latest nightly release if earlier release aren't working (they have have a fix the earlier release didn't have)  

Link to Nightly releases:  https://github.com/opentoonz/opentoonz_nightlies/releases  

8GB is a not a lot of RAM for heavy lifting of rendering and processing.
NVIDIA graphics card:  Make sure drivers are up to date (and/or optimal for the current system)

If the current system is not sufficient to run OpenToonz you may wish to test the 32bit release of OpenToonz.

Link to download page:  https://morevnaproject.org/2017/06/05/opentoonz-32bit-available-download/
