### ISSUE TITLE
Importing an image renames it incorrectly

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2306]
### Issue Summary
Drag an image that isn't in your project's folder from a Windows Explorer window into OpenToonz (I can't remember if I dropped it onto the timeline, xsheet or the table) and it'll ask if you want to import or load. Choose load. The image appears to load correctly and you can work with it, but if you restart OpenToonz, the image column text is shown in red and the image isn't visible on the table.

The reason this happens is the image copied in the Extras folder has been renamed with an appended underscore.
E.g. If you drag in: **"image.png"**
The .tnz file, it references: **"+extras\\image.png"**
but on disk, in the Extras folder is an image named: **image_.png**

You can fix it by closing OpenToonz, renaming the files (just delete the underscore) then restarting OpenToonz.

Note, this doesn't happen every time. I just tried it with 1 more file, to upload a video reference of the issue and and it worked fine.

### Screenshot or Video Reference
![image](https://user-images.githubusercontent.com/28575907/46250707-49319900-c438-11e8-9390-010251d5c6b8.png)

### System Information
I'm on Windows10 using the latest OTX version.

**Comment by DarrenTAnims** [comment]
I've now got a reproducible workflow and gif (below) that show this. To repeat it:

- Start a new project
- Start a new scene
- Drag an image file from outside the project (in this case, from the desktop) to the drawing table.
- You're asked if you want to import or load it. Choose Import and you see the file copied to the extras folder.
- Choose Save All. Nothing changes.
- Draw on the image, Save All. Nothing changes.
- Reload the project. Save All. Nothing changes.
- Make an edit to the image (draw on it). Save All. The filename changes to include an underscore !!
- Look into the scene file and it has the original filename in it. Now that when you reload it, the image isn't visible because it's trying to load the original filename and not the one with an underscore in it.

![screencapture](https://user-images.githubusercontent.com/28575907/46747736-f2368a00-cca9-11e8-9e6e-4d690edfb4de.gif)

**Comment by shun-iwasawa** [comment]
I'll tackle with this. Thank you for reporting the bug!

**Comment by shun-iwasawa** [comment]
OK, I found a probable cause.

**Comment by artisteacher** [comment]
That was fast! Any chance it is also impacting the image sequence import for sequences with an underscore?

**Comment by RodneyBaker** [comment]
I'm still getting the underscore with the image in the extras directory as outline above:

If you drag in: "image.png"
The .tnz file, it references: "+extras\image.png"
but on disk, in the Extras folder is an image named: image_.png

The steps are as outlined in the report although I'm using these specific steps:

Launch Opentoonz
Via Startup Popup... create new project and new scene.
drag drop image.png into xsheet.
Save All
Draw onto the exposed image (on canvas).
Save All
Using Recent Files listing reopen the current Scene
The cell in the xsheet should be red indicating the referenced image wasn't found.
Look in extras directory and note the image is named 'image_.png' 

I'm using the just now published nightly release that lists this issue as fixed.  Perhaps the merger just didn't take or it just didn't fully fix the issue.

**Comment by shun-iwasawa** [comment]
Sorry for the trouble, confirmed the issue. I'll look into this again.

**Comment by DarrenTAnims** [comment]
Thanks for looking into this so quickly @shun-iwasawa.
