### ISSUE TITLE
Spelling error: 'Flip Viewer Horiontally' (Should be: Horizontally)

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2307]
I was trying to set the keyboard shortcut for flipping the canvas and typed "horiz" and nothing appeared. Deleting the Z showed the option. The word Horizontal is spelt wrong

### Screenshot or Video Reference
![image](https://user-images.githubusercontent.com/28575907/46258877-f94ee280-c4c8-11e8-9d48-ebe3aae52a0b.png)

Also, it'd be good if it was in a menu, so users knew it was an option and if it had a default keyboard shortcut.

**Comment by RodneyBaker** [comment]
This is a great candidate for developers new to OpenToonz coding!

I see two instances of this spelling error in two documents:

https://github.com/opentoonz/opentoonz/search?q=horiontally&unscoped_q=horiontally

**Comment by DarrenTAnims** [comment]
This was going to be my first 'dip my toe in the water' dev task, once I get setup.

**Comment by beeheemooth** [comment]
Really? 
I saw what was written "horiontally", and thought it was correct in English.
My brain need to be updated.
