### ISSUE TITLE
Ability to control Onion Skin settings directly in the XSheet is missing

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#231]
This problem is mentioned by AyameLee in the discussion of the issue #108 
Now the onion skin interface is only available in the level strip, but in xsheet.

**Comment by blurymind** [comment]
Has this been merged into trunk? I cant wait to try it out.

Thank you @shun-iwasawa

**Comment by psychoanima** [comment]
Oh boy! Can't wait to see this option!

**Comment by kogaki** [comment]
Seems to be fixed.
