### ISSUE TITLE
Crash with Vector level corruption

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2310]
### Issue Summary
After finishing animating one day, I hit save all and shut down. The next day I loaded the scene and it played fine. However, when I tried editing the animation a little and hit save, it crashed. After speaking with ManongJohn and him looking at my project, he tracked it down to one particular level. I've attached it to this report and you can replicate the issue following the steps below.

### Screenshot or Video Reference
[BrokenLevel.zip](https://github.com/opentoonz/opentoonz/files/2435633/BrokenLevel.zip)

### Steps to Reproduce
Start a new project
Start a new scene
Hit save All
Download the zip file from this report and unzip it. You should find a G.pli file.
Copy G.pli to the Drawings folder of your new scene
In OpenToonz, right click on an empty cell in the timeline/xsheet and choose Load Level.
Browse to G.pli
Hitting Save All now works fine.
Edit any drawing (e.g. using the brush tool, draw a line)
Hit Save All.
CRASH!!

### Expected Results
The scene should save. The drawing will be updated in G.pli.

### Actual Results
OpenToonz closes.

### System Information
I'm on Windows 10, using the latest OTX

**Comment by beeheemooth** [comment]
@DarrenTAnims I looked at the G.pli level and by an exception method I found that the problem in it starts at frame 53 (Level Strip - 364) and it is somehow linked with the display of icons in the Flipbook or Level Strip.
![ezgif-1-cbfc2f962c](https://user-images.githubusercontent.com/25724133/46321213-b84eef00-c5ea-11e8-88b3-871ad283c530.gif)
![ezgif-1-6b8f797fe3](https://user-images.githubusercontent.com/25724133/46321232-dae10800-c5ea-11e8-8546-292e3b6a3a7c.gif)

**Comment by artisteacher** [comment]
I wonder if this is related to #1586.

**Comment by RodneyBaker** [comment]
I confirm the steps specified produce a crash.

I'm not sure what we can do specifically here short of getting rid of the corrupted level and looking in to how OpenToonz can recognize a corrupted level and either warm the user of the problem

There is also the root matter of trying to determine to what extent the vector level PLI file is corrupted and how to prevent a similar corruption.

**Comment by artisteacher** [comment]
Getting to the root problem is definitely important but will probably take a long time. In general, solving as many crash issues as possible should help. Fewer crashes = fewer opportunities for file corruption?

In the meantime, there definitely needs to be a way for OT to not load levels that are corrupted or unreadable or have path issues like #1992 & give a warning instead.
