### ISSUE TITLE
plastic mesh visibility

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#2317]
### Issue Summary
this is actually a resurfacing of a fixed bug. unchecking the "show mesh" checkbox only works when the plastic tool is the active tool. selecting any other tool causes the mesh to reappear.

### Screenshot or Video Reference

https://youtu.be/dTGd9CvpQrE
### Steps to Reproduce

create a plastic mesh, add skeleton, uncheck "show mesh" check box, and change the active tool to any other than the plastic tool.

### Expected Results
the expected result is that the mesh stays hidden

### Actual Results
the actual result is that the mesh reappears.

### System Information
* **OpenToonz Version**: 1.2.1 nightly from a few weeks back as well as the latest nightly
* **Operating System**:  mac 10.13.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: NVIDIA GeForce GT 750M 2048 MB Intel Iris Pro 1536 MB
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
I'm seeing this too. I agree that the mesh should stay hidden.
