### ISSUE TITLE
Missing Nodes In FXSchematic

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2318]
### Issue Summary

I have lost my nodes in FX Schematic
### Screenshot or Video Reference

this would be a pic of an empty box or a video of me scrolling in an empty box
### Steps to Reproduce

not exactly sure but seems to be some combo of 1)taking things in/out of sub-xsheets 2)grouping/ungrouping in FXschematic 3)clicking "reorder node"
### Expected Results

For one of the tools to get my nodes back into view sized reasonably

### Actual Results

I cant find the nodes in this particular sub x sheet, none of the helper buttons work either(reorder, zoom to fit etc) i am either zoomed out or in way to far on some weird spot.  (i can go on a mission to get these nodes visible again but this is an issue.

related to this issue perhaps, the "reorder nodes" breaking layout in FX schematic sometimes(so u cant see output and xsheet anymore) and also to issue of sometimes when opening group the group opens to cover everything in the viewport.

1.totally missing nodes(no buttons work to get into view)
2.opening group expands to cover entire viewport making everything unclickable
3."Reorder Nodes" button sends xsheet and output nodes impossibly far to the right.(clicking reorder usually doesnt work.....saving >close/reopen >then click reorder... usually does work)

*sometimes the stage schematic has issues like above but the reorder node button seems to work better than it does when in FXschematic.

p.s. I run into the above issues very frequently. lots of closing program and reopening hoping that clicking reorder nodes will work and i willnt have to reconnect or explode/collapse things to fix schematic
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
I'll guess you are still using:

windows 10
intel i5-6300u
16gb ram
Intel HD Graphics 520

**Comment by RodneyBaker** [comment]
Short of you sharing a project file I'm not sure what can be done short of having others who experience the same thing outline their experiences too.

**Comment by manongjohn** [comment]
Try this combo to see if you can get at least 1 node back into view:

1. Xsheet/Timeline: Click a column to make it current
2. FX Schematic: Click on "Reset Size"
3. FX Schematic: Click on "Focus on Current"

That should hopefully bring that node into view.

**Comment by phillycheese007** [comment]
tried that:(

Im kinda surprised i dont see this issue popping up for more people?

should i attach a copy of the scene file or something?

**Comment by RodneyBaker** [comment]
It would help to attach the Scene file but you mentioned subxsheets so there is very likely more than one Scene file and of course there are the levels too so Ideally the entire project folder is needed to get the full view.

Having said that having the main Scene file is a starting place and might provide a clue.

**Comment by RodneyBaker** [comment]
To share the entire Project:
Go to your Browser Room and navigate to your Scene then...
- Right Click on the Scene's filename in the listing and choose Export Scene
- At the bottom choose New Project and enter a useful and Descriptive name for the Project file you want to share
- Export the Scene
- This will create a new Project with all the assets of the current Project in the default Projects directory.
This will be in a location like:  C:\OpenToonz 1.2 stuff\projects\<name of Project here>
- Compress/zip that entire Project directory and share the resulting zip file.

If you can reproduce the same problem in a file with fewer resources that is always preferred.
Especially where your Project might contained things you don't wish to be shared.

**Comment by phillycheese007** [comment]
[share1.zip](https://github.com/opentoonz/opentoonz/files/2453969/share1.zip)
the problem is in the Head sub-x sheet which is in column55

**Comment by RodneyBaker** [comment]
I see a whole lot of nodes in the opened subxsheet after it is opened and *after* I ungroup them (via Right Click > Ungroup).
What is it we should be seeing?

P.S.  Thanks for sharing the Project.  That helps tremendously.

**Comment by phillycheese007** [comment]
Open the scene scroll to column 55 and open that sub-x sheet....u can see
the nodes in the stage schematic but they are missing from FX

**Comment by RodneyBaker** [comment]
I see the nodes in both stage and FX schematic views:
![fxshematic](https://user-images.githubusercontent.com/2576432/46587959-d2a92280-ca59-11e8-95d5-143c50673afb.png)

**Comment by manongjohn** [comment]
I am able to duplicate/see the issue.  I will look into it and see what I find

**Comment by manongjohn** [comment]
It appears this issue might be stemmed from the fact that you have empty columns.

I was able to get things to appear again by doing the following:
1) Right click Column Headers and "Remove Empty Columns"
2) Click "Reorder Nodes" in FX Schematic

See if that helps.

**Comment by manongjohn** [comment]
Hmm. after reloading the screen somehow this sequence doesn't work...continuing to investigate

**Comment by manongjohn** [comment]
Ok...maybe try this sequence:

1. Right click Column Headers and "Remove Empty Columns"
2. Click "Reorder Nodes" in FX Schematic
3. Click "Focus on Current" in FX Schematic
4. Click "Fit to Window" in FX Schematic

**Comment by phillycheese007** [comment]
thanks @manongjohn..that did the trick..really appreciate you guys looking
into this...a little sad cus i was using empty columns to organize...i
suppose itll have to be empty note levels if i want the same

**Comment by phillycheese007** [comment]
Ill have to do some testing in the future to see if this problem (unable to
keep empty columns for sub-x) ..is solved by just grouping all of the sub-x
FX nodes....have a feeling that should do it

**Comment by phillycheese007** [comment]
NM...that woud be a weird workaround...grouping and ungrouping things
everytime u collapse/explode.   this is still an issue albeit one with a
reltively simple fix(which im sure i will forget at some point!

The empty column thing is really important to me if i have a sheet with
20,30 etc columns...i like to separate as much as i think will be needed
right off the bat(torso on 10s legs on 20s arms on 30s) helps me quite a
bit w/ organization

**Comment by RodneyBaker** [comment]
You can still have those columns there.
Just add a single frame where you place a tiny dot.

That should allow you to press on as you currently are.

**Comment by phillycheese007** [comment]
@rodney not sure how to pace a dot in an empty column

@manongjohn the way im setting up this rig ...sub-x sheets would really get
in way of animation speed and access to vertices/hook points

**Comment by RodneyBaker** [comment]
> @rodney not sure how to place a dot in an empty column

You could also draw a smiley face but then it might appear in the final product.
Instead you just draw a really tiny dot.
As long as something is exposed in the column that should suffice.

**Comment by phillycheese007** [comment]
i gotcha you just talking about 1 level exposed with a dot on those
columns? Of course i would prefer not  to have to create levels just as
place holders...but that works :)

**Comment by artisteacher** [comment]
You could create a single placeholder level & then copy & paste it into your empty columns.

**Comment by manongjohn** [comment]
You don't need to put a dot. A blank frame should suffice.

Regardless if it's blank or has a dot in it, if you toggle off the Preview and Camera Stand buttons, they won't render out or even show in previews.
