### ISSUE TITLE
(Huion) Viewer window focus misbehavior

### ISSUE THREAD

**Issue by wofogen** [opentoonz/opentoonz#2320]
### Issue Summary

Theres a problem with OT viewer window that prevents it from focusing by drawing in the cavans, it only affects the pen tablet and get worse. If I accidentally draw in a hidden column, after closing the error message, i cant draw anymore using the pen, using the mouse enables drawing again

### Screenshot or Video Reference

Viewer focus bug
![focusbug1](https://user-images.githubusercontent.com/33259911/46608437-2c056600-cadb-11e8-8d22-0b9acd28b06e.gif)
Hidden column bug
![focusbug2](https://user-images.githubusercontent.com/33259911/46608450-3162b080-cadb-11e8-9fbb-8ffe362aa922.gif)

### Steps to Reproduce

For the focus bug
1 - Click anywhere outside the viewer using the pen
2 - Go back for drawing

For the hidden column bug
1 - Try to draw in a hidden column

### Expected Results
Being able to use certains shortcuts after using xsheet or something else

### Actual Results
I cant use especifics shortcuts like "Reset Viewer" and "Flip Viewer Horizontal" unless I click in the viewer top bar. None of these problems occur using the mouse.

### System Information
* **OpenToonz Version**: 1.2.1 (built Sep 18 2018)
* **Operating System**: Arch Linux - Kernel 4.18.10
* **CPU**: Intel Core 2 Quad Q8400 - 2.66GHz
* **Memory**: 4gb
* **Graphics Card**:  Geforce GTX 560 - Drive 390.87
* **Graphics Tablet**: Huion H610 Pro

Update: Hidden Column bug was fixed

**Comment by shun-iwasawa** [comment]
Unfortunately I couldn't reproduce the issue with my Win7 environment with Wacom Intuos CTH-690 tablet. Probably the problem is specific with Linux or with some types of tablet.

**Comment by wofogen** [comment]
In the moment i dont have windows or a different tablet to test, but my guess is it certally is a linux bug, maybe related to this old issue #1897 
A thing i dont said but can be seen in the second gif is i'm using a cross cursor but it turn into the default cursor when it unfocus, and the cursor outline get stuck all the time unless i'm pressing the pen or using the mouse.

**Comment by artisteacher** [comment]
The problem with the cursor not updating properly is an issue with MacOS as well - it seems that hovering with a stylus is not currently recognized. You might want to add to the discussions in #1951, #1796, or #1853 about cursor/hovering issues.

**Comment by artisteacher** [comment]
This is a duplicate of a larger issue #1796 where OT does not recognize hovering when using a tablet stylus to navigate OT.

**Comment by RodneyBaker** [comment]
Agree that it is related.  However before considering it a duplicate we need to update the larger issue to describe how  the larger issue is more than just Mac OS, which is what the other report focuses on.  We don't want to lose any of the information in the process of identifying duplicates.

How best to proceed?  Start a new report that encapsulates all of the others?

**Comment by artisteacher** [comment]
Maybe? Does Windows have any of these issues or are they all Mac/Linux specific? Can any Linux users replicate the hovering issues #1796 or #2397 or etc.? If any of the issues are only MacOS specific, they should continue to be tracked separately. If they’re all just tablet issues across multiple OS, they should probably be consolidated.

**Comment by wofogen** [comment]
Today I discovered some new things, first the context menu only open in the viewer using the mouse right click, like reported in #1790 .

Another interesting one is that detaching the viewer window made the focus work correctly (but it dont fix the context menu problem)

and i'm not having the hidden column bug for a while so that was fixed

**Comment by RodneyBaker** [comment]
Adding this complete quote from another report:

> The common theme with Huion tablets appears to be bad drivers.
> In more than one case a problem has been resolved by REPLACING the current driver.
> Note that this does not necessarily mean updating to the latest driver as that has been reported to cause problems in some cases and resolve them in others.  It may be appropriate to dial back to an earlier driver where the current driver causes problems.
> 
> Bottom line reported from other Huion users:  Deleting the driver fixes the problem

**Comment by wofogen** [comment]
can confirm bug was fixed on linux with #4860 pull
