### ISSUE TITLE
Hiding a column with hotkeys does not block the action of the tools (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2323]
### Issue Summary

Hiding a column with hotkeys does not block the action of the tools, and sometimes confuses when they should be applied.
### Screenshot or Video Reference

![ezgif-1-120c1dbc7621](https://user-images.githubusercontent.com/25724133/46765281-46139400-cce7-11e8-8dfc-975a2f3edbbd.gif)

### Steps to Reproduce

Try to switch the level display with hotkeys (Hide Selected, Show All). It does matter if the cursor is over the canvas, or over the Xsheet.

### Expected Results

The tools must be blocked
### Actual Results

The tools is not blocked
### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by artisteacher** [comment]
I’m not seeing this in MacOS  - maybe it’s Windows specific.

**Comment by manongjohn** [comment]
I can reproduce this with both Hide and Lock shortcuts but it only happens if I use the shortcut while on the canvas and remain on the canvas.  The moment I leave canvas and come back then it blocks the tool again.
