### ISSUE TITLE
White background on Level Strip with ToonzRaster levels

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2327]
### Issue Summary
When clicking on a frame on the Levl Strip to edit it, its background is not transparent, but white nstead.

This is true when having any of the following tools active: Select, Brush, Geometry, Text, Fill, Paint Brush, Eraser, Tape, Finger, Style Picker, RGB Picker, Ruler, Tracker, Hook, Zoom, Rotate, Hand.
On the contrary, activating any of the tools that can't be directly used on the Level Strip or on this type of level (i.e. Animate, Control Point Editor, Pinch, Pump, Magnet, Bender, Iron, Cutter, Skeleton, Plastic) does show the background as transparent.

This is true only for Toonz Raster levels, the other two types of level work as expected.

**Comment by artisteacher** [comment]
Re @shun-iwasawa:
> For now Toonz Raster Level shows white background when the levels trip frame is selected ( here in the source code ). This behavior was originally requested by Studio Ghibli and is not a bug. I think it would be nice to make the background color adjustable via user preferences, but it will be a separate improvement in the future.

That’s interesting that the background differs depending on disabled/enabled tools.

**Comment by gab3d** [comment]
ah... ok, a known issue then.
it'd be interesting that:
1. all level types behave in a same manner.
2. the background color could be decided by a user preference.
👍

**Comment by artisteacher** [comment]
I also would like to see all level types behave in the same manner. There's already a preference for the viewer background - but only for when the level strip is active & Toonz Raster levels ignore it.

What if there was one preference for the "Scene's" viewer background and a separate preference for a "Single Level's" viewer background - with an option to keep them synced or un-synced depending on if we want everything white (or etc.) or not? In this case I would think that Japanese studios would just set the backgrounds as synced if that is still their preference.

**Comment by gab3d** [comment]
@artisteacher the problem with the current Viewer background color is that it also affects the Camera Stand color, which if you change it (to white for example) looks just horrible.

To me, any viewer background option, independent from the camera stand background, would be a great improvement.

**Comment by artisteacher** [comment]
You are right - that does look horrible!
