### ISSUE TITLE
Crash , undo antialias on toonz raster level

### ISSUE THREAD

**Issue by imhundk** [opentoonz/opentoonz#2328]
### Screenshot or Video Reference
[VIDEO](https://youtu.be/HW8XHypu2_A)

### Steps to Reproduce
- Draw with pencil mode
- select level/frame, 
- add antialias and apply
> then undo it <ctrl-z>

### Expected Results
the drawing back to binary/pencil

### Actual Results
i hit undo, it freeze and crashed

### System Information
* **OpenToonz Version**:  1.2.1 OTX
* **Operating System**: Windows 10

**Comment by RodneyBaker** [comment]
I can confirm a crash here.

Workaround:  Avoid Undo after adjusting Antialiasing on Toonz raster levels.
