### ISSUE TITLE
Arch linux is not compiled opentoonz

### ISSUE THREAD

**Issue by ave4** [opentoonz/opentoonz#2335]
Already like more than a month, opentoonz does not compile. If you try to compile it, it will throw out an error due to the lack of mypaint-brush.h, although it is in `/usr/include/libmypaint`. Tried to install from the repositories libmypaint, mypaint-brushes and libmypaint-git.
Stable OpenToonz 1.2.1 compiles fine.
[log_build.txt](https://github.com/opentoonz/opentoonz/files/2484100/log_build.txt)
[PKGBUILD.txt](https://github.com/opentoonz/opentoonz/files/2484112/PKGBUILD.txt)

**Comment by wofogen** [comment]
did you try to paste all files from libmypaint to ".../toonz/sources/toonzlib/"?

**Comment by ave4** [comment]
Surprisingly, after copying all the files, the compilation went further. And I was even glad, but then again this error appeared.
[log2.txt](https://github.com/opentoonz/opentoonz/files/2486582/log2.txt)

**Comment by wofogen** [comment]
You will not belive, you have to copy the content from libmypaint to "/toonz/sources/include/" as well, i think it is because the new toonz raster mypaint implementation.

**Comment by ave4** [comment]
**Happened**! Although I tried to copy it to sources/include/toonz was not compiled.

**Comment by wofogen** [comment]
it need to be in /sources/include dir, not in the /sources/include/toonz
