### ISSUE TITLE
Project palette not loaded in level after save

### ISSUE THREAD

**Issue by lealeelu** [opentoonz/opentoonz#2346]
### Issue Summary
Opentoonz isn't saving all my level palettes, especially ones from my project palette.

### Steps to Reproduce
I created a project palette with a few tabs and colors, nothing too crazy. I created my level and dragged and dropped that palette into my level palette. I go ahead and draw on that level with those colors with no problem, and then save all. I close opentoonz, open it back up to that scene file and the level shows up all red. In the level palette, all I see is the default colors tab and it's missing all of the project palette tabs that I imported.

The same thing happens for each of the different types of import I try: Merge to current palette, dragging and dropping on the tabs, dragging and dropping on the colors section of the level palette, and Load into current palette.

If I merge the project palette into the level palette again, the colors come back. This has been my workaround for now.
I also noticed that it will save the level palette if you are in the level when you save.

### Expected Results
I would expect the colors that I merged to stay.

### Actual Results
The level palette goes back to a default palette after I load.

### System Information
* **OpenToonz Version**: nightly build https://github.com/opentoonz/opentoonz/commit/cc8bfe7b330892f24f19e2a0dfe9ab904392e42b
* **Operating System**: Windows 10
* **CPU**: i7-4771
* **Memory**: 32gb
* **Graphics Card**:  GeForce GTX 970
* **Graphics Tablet**: Wacom Cintique

**Comment by RodneyBaker** [comment]
Thanks @lealeelu 
Can you share a video/screen capture of what you are experiencing?
There are aspects of this that suggest some normal operation of palettes while other information is missing...such as what type of level you are using... and seeing what you are seeing would tell the tale.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@lealeelu please let us know if you are still experiencing the problem.
