### ISSUE TITLE
Is vector doesn't for plastic tool?

### ISSUE THREAD

**Issue by leegov** [opentoonz/opentoonz#2348]
### Issue Summary  
In my test , I  knew the raster layer can't fill color; or the vector level cannot "autopaint for lines" maybe also cannot make plastic tool?  but I don't know why. 
So help me understand about Toonz raster / raster / vector. (Not paint, for function, for tools)
### Screenshot or Video Reference
![](https://raw.githubusercontent.com/leegov/hangzhou-bicycle/master/ooo.JPG)

### System Information
* **OpenToonz Version**: 1.2.1
* **Operating System**: win 10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by leegov** [comment]
This level with a hook point, that is why I said vector level doen't work when I add plastic. My misstake.

**Comment by artisteacher** [comment]
In that case this issue can probably be closed. Good luck with your exploration of OT.
