### ISSUE TITLE
How Copy Layer frames alone, I need Change the color?

### ISSUE THREAD

**Issue by leegov** [opentoonz/opentoonz#2349]
### Issue Summary
 I need outline of many frames, I copy and change the fill of them. But the original frames changed too.

### Screenshot or Video Reference
![](https://raw.githubusercontent.com/leegov/leegov.github.io/master/jjjj.0001.jpg)

### Steps to Reproduce
I make matte for the **mouth** and ### teeth. I need outline of **mouth**, So I copy the **mouth** layer, and changed it's color that inside fill. now I got a outline.
BUT BUT BUT
I found the original **mouth** changed its too. **I can't only change one of it after copy a levels.**
What can I do? how to duplicate many frames as new one？

### Expected Results
get new frames only with outline.  I need original with fill color, and new copy changed fill (alpha 0, only line)

### Actual Results
all the original one and duplicate were changed 

### System Information
* **OpenToonz Version**: new
* **Operating System**: win10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
As you’ve discovered, copy creates a linked copy. You actually want to use the clone command instead of copy. Select all of the cells in the level you want to duplicate (click on the left edge of the level in the Xsheet or the top edge in the Timeline), then in the top menu, go to Cells -> Clone.

**Comment by RodneyBaker** [comment]
@Leegov,
Recommend closing this issue.

Don't forget, explorations and troubleshootings can be pursued via the OpenToonz Forum without opening bug reports on github.  Link:

https://groups.google.com/forum/#!forum/opentoonz_en/categories
