### ISSUE TITLE
Xsheet:  Column transparency not applied consistently

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#2353]
### Issue Summary

I turned down the opacity on my column and it is not applying to all drawings
(alpha is at 100% for all styles involved)
### Screenshot or Video Reference

![sheet2](https://user-images.githubusercontent.com/25863731/47809978-8da2a400-dd18-11e8-98ad-a3efa578b1fa.gif)
### Steps to Reproduce

im not sure :(
### Expected Results

opacity applied evenly for everything in column
### Actual Results

seems random?
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
As the Column Transparency can only have one setting some other influencer must be at play such as an FX node, Plastic Tool etc.

**Comment by phillycheese007** [comment]
unfortunately no...  ..no meshes...no transparency FX

**Comment by artisteacher** [comment]
Does that level have the same issue if it is imported into a new project?

**Comment by RodneyBaker** [comment]
Closing as this issue cannot be reproduced at this time.
If encountered again please provide additional information such as a Project file with all related assets for examination and resolution of the problem.
