### ISSUE TITLE
Crashed Application

### ISSUE THREAD

**Issue by felixsuttonk** [opentoonz/opentoonz#2356]
I was drawing with Toonz Raster level and I tried to make another layer and it crashed the application. I've been drawing for 2 hours and I haven't saved it. Is there anyway I can get it back or find it?

I'm really salty because I spent so long trying to make an animation and it randomly crashed without saving.

**Comment by artisteacher** [comment]
That's always frustrating! Maybe someone has a better answer, but if you haven't saved the level, I'm not aware of a way to recover it. I've looked for temp files before, and haven't had luck finding them. If you have saved the file previously, and it's no longer displaying, you can take a look in the File Browser & see if the last saved version is there. Toonz raster levels are stored your project's "Drawings" directory by default.

To avoid this issue in the future, saving regularly is important. OpenToonz is a lot more stable than it was even a year ago but there can still be unexpected crashes. You can enable auto-save at regular intervals in either preferences or the startup pop-up window. Auto-save sometimes interrupts though, so it is often better to just develop the habit of saving regularly with the save-all shortcut (CMD-S on Mac or Ctrl-S on Windows).  Another helpful preference is to enable "Backup Animation Levels when Saving" (under the General preferences). The benefit is that if something goes wrong and you unexpectedly lose a previously saved level, you can restore it with the last saved backup.

Just an fyi, when you have a question, [the OT forum](https://groups.google.com/forum/#!categories/opentoonz_en) is really the place to ask it. If you find repeatable steps that always cause a crash/bug, this is the place to let the developers know. In that case, sharing the crash report & information about your system/version of OT would also be helpful.

**Comment by RodneyBaker** [comment]
We'll need some additional information in order to determine what has happened and to restore any data.

Hopefully you've found the files and have been able to recreate the scene.

**Comment by RodneyBaker** [comment]
Please visit the OpenToonz forum where there is a Troubleshooting area that can be used to explore your problem. Similarly there are several OpenToonz discords (chatrooms) where live assistance can be found and others OpenToonz users are able to assist in recovering data. 

LInks:
OpenToonz Troubleshooting forum:
https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting

OpenToonz Discords: https://discord.gg/xjZsAfu or https://discord.gg/JA292SR

Closing this issue.

Closing this issue.
