### ISSUE TITLE
Option to use hand tool with drawing tools

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#2360]
Many times when I am working on big shapes I have need not only to zoom out with my mouse wheel but also to pan working area with space button + mouse click.

Thing that I found irritating is that I can't use hand tool for panning when I am drawing with geometry tools, because space button/hand tool automatically deactivates active drawing . It will be very useful to have option to use hand tool when holding space button, and to have back active drawing tool and drawing shape when space button is released.

**Comment by manongjohn** [comment]
The ability to temporarily use the hand/zoom/pan tool while pressing and holding their respective shortcut and then letting go to return to the current tool already exists. It works will all tools.

It should be noted that I believe there is a QT bug that prevents this from working on some linux systems, but may occur in other systems. It does work for Windows systems.

**Comment by artisteacher** [comment]
It’s not that temporarily using a tool doesn’t work, it’s that once you’re returned to the original tool, if you were in the process of creating a polyline shape or etc., the in-progress shape is gone. Similarly, the selected control point is no longer selected when returning from temporarily panning or etc. Temporary tool switching works, it could be even better though if the original tool’s in-progress/focus state could be maintained after switching.

**Comment by psychoanima** [comment]
Yes, at some point it's a bug for me, because almost every drawing software that I know is not interrupting drawing process when panning. So, if OpenToonz was planned from very beginning to work this way then yes, it's a feature request. 
I should say that this is a mandatory thing to have by every vector illustrator. 


https://1drv.ms/v/s!AtMv1SrHrjT38mtojvgNgY4qxQ4S
