### ISSUE TITLE
Shift + Drag/Drop into OT with Load... Deletes files

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2363]
### Issue Summary
Using Shift + Drag/Drop to bring files into OpenToonz brings up the Import/Load dialog.
This 'moves' the file into OpenToonz directory structure.
Opting for Import works as expected.
Opting for 'Load' can easily lead to loss of the files.

### Steps to Reproduce
Drag/Drop one or more images (PNG is good option) into OpenToonz and use import or load from the dialog.  This should work as desired.
Use Shift + Drag/Drop to do the same thing also using Import option.
This should work as desired.
Use Shift + Drag/Drop and use the Load option and note that the original is moved to Recycle Bin (deleted) and the image is place in OpenToonz but a Save All will not place the file in the /extras directory.  After reopening the Scene (via Recent Used Scenes listing or other method) the link will be displayed as red (broken link)

### Expected Results
Shift + Drag/Drop should move the file(s) to the target directories (i.e. copy the file(s) and then delete the originals upon successful copy) and then update the Level reference to the new location.

or

Load should be refactored or made to not be an option while 'moving' via Shift + Drag/Drop.

 
### Actual Results
Files are not moved but sent to the Recycle Bin (deleted!).

### System Information
* **OpenToonz Version:  Most current nightly release as of 20181105 
* **Operating System:  Win10 

Thanks!

**Comment by RodneyBaker** [comment]
It would be good to validate this unintended result is happening as users files will be deleted  AS IN GONE FOREVER if they don't think to recover the files from Recycle Bin with this process.

I confirm this is still a problem with latest nightly release.

Can anyone else confirm?

**Comment by shun-iwasawa** [comment]
Confirmed the problem. It seems to be different from #2556 . I'll look into it. Thanks!

**Comment by RodneyBaker** [comment]
Possibly related to #2870

**Comment by RodneyBaker** [comment]
This is still very much an issue and hints at something deeper than just ffmpeg (as addressed in #2876 and #2882)

Steps to reproduce
- Launch Opentoonz
- Locate a PNG image to bring into Opentoonz and open a window containing that file (for purpose of viewing the file but also for selecting and drag/dropping)
- Hold down shift key while dragging and dropping a PNG image into Opentoonz
- Choose Load as the option (as opposed to Import)
- Watch as the original file is deleted 
- Look in Windows Recylce Bin to find/restore the file

**Comment by artisteacher** [comment]
Using shift when dragging and dropping seems to be ignored in macOS. Nothing is deleted, but the files are not moved either.

**Comment by manongjohn** [comment]
In Windows, Shift + Drag/Drop is supposed to Move the object, so upon successful drop, it removes the old file.  As OT is accepting the drop, Windows deletes the file after the acceptance because it thinks it was successfully moved.  OT won't write it back out unless a change is made to it.

What should probably happen here is OT needs to block a "move" Drag/Drop, but still allow a "copy" Drag/Drop or even a "link" (ALT) Drag/Drop.
