### ISSUE TITLE
Crash when Z camera position = 0 in Preview

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#2372]
### Issue Summary
OpenToonz crashes in preview mode when Z coordinate of camera reach bellow 0. 
edit: crash occurs when **Camera Stand View** and **Preview mode** are activated 

### Screenshot or Video Reference
https://1drv.ms/v/s!AtMv1SrHrjT38m-OYR9dbAZbItzl

### Steps to Reproduce
Select Animate tool. Choose Camera from drop down list. Choose Position option from drop down list. Activate Preview mode. Select **Camera Stand View**.  Scroll camera Z parameter to negative value. 

### Expected Results
Camera to move into negative space

### Actual Results
OpenToonz crashes

### System Information
* **OpenToonz Version**: 1.2.1 (built jun 28)
* **Operating System**: Windows 10 Pro
* **CPU**: i7 2630QM
* **Memory**: 20 gb
* **Graphics Card**: NVidia Quadro 1000m

**Comment by shun-iwasawa** [comment]
It seems that the crash occurs when Z = 0.

**Comment by psychoanima** [comment]
@shun-iwasawa sometime I am able to reach in minus, depending how fast I am pulling the slider.

**Comment by shun-iwasawa** [comment]
You can try directly typing negative value in the Z field and it will cause the crash. And OT will crash once you type 0. I think zero dividing occurs somewhere in the source.

**Comment by psychoanima** [comment]
Yes, and addition to that, I also  discover that crash at 0 is happening when **Preview** mode is activated together with **Camera stand view**. When **Camera view** is activated there is no crash. I will add that to **Issue Summary**
