### ISSUE TITLE
Pencil Mode has no effect on Polyline or Freehand Eraser types

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2377]
### Issue
When using the Polyline or Freehand types with the eraser, while it is in pencil mode, the result exhibits anti-aliasing, this is not consistent with the Normal eraser type nor the Brush tool.

### Image example
![polyline issue](https://user-images.githubusercontent.com/42905003/48314634-08df4200-e5c4-11e8-9814-d21e0fb77400.PNG)

The left gap was produced by the polyline eraser in Pencil Mode, the right gap had pencil mode disabled - both results are the same.

### Steps to Reproduce
1. Create a ToonzRaster level, draw a line (preferably in Pencil Mode).
2. Set the eraser's type to Polyline or to Freehand and enable Pencil Mode.
3. Erase part of the drawn line.

### Expected Results
Use of the eraser in Pencil Mode should produce aliased results regardless of its type.

### Actual Results
Use of the eraser in Pencil Mode produces anti-aliased results when its type is set to Polyline or Freehand, this is not the case when the type is set to Normal.

**Comment by artisteacher** [comment]
I'm seeing this as well in MacOS. It definitely would be better for the eraser to behave the same with all types.

**Comment by WolfInABowl** [comment]
Closing this issue as it has been adressed by #2838

**Comment by RodneyBaker** [comment]
@WolfInABowl Thanks.  I was just about to look into this.

I know this seems a bit odd but we may want to reopen this in order to properly have it be closed by the merging of #2838.  In this way github will properly accredit the fix.

We should be able to get that by adding 'fixes #2377' to a post in the PR.

Hope that makes sense.

**Comment by manongjohn** [comment]
Not really necessary for a PR to have to auto close something. Just a nice thing to do if it is still open. A reference comment would suffice.

**Comment by RodneyBaker** [comment]
Will close again to see if there is any difference in the guts of git/github when the 'fixes' tag is added after a merge.

**Comment by manongjohn** [comment]
You have to have `fixes #...` in the description of the PR in order for the PR to automatically close it or even to have it listed as being fixed by the PR.

**Comment by RodneyBaker** [comment]
Yes.  This is what I added but have now deleted to get it back to the state it was in when @WolfInABowl closed this issue.  The post I added and removed was in its entirety:  'fixes #2377'.

**Comment by manongjohn** [comment]
Not sure what you mean by first post. It's the PR description box (below subject line) where that needs to be added.  It can be added any time while the PR is open.  See any of my PRs that I say "fixes X".
