### ISSUE TITLE
Crash when switching Toonz Raster levels containing MyPaint style (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2380]
_Sorry if I haven’t carefully reviewed the Toonz Raster Levels issues, but it looks like there is no description of this problem. It is possible that this problem is present here:_ #2356

### Issue Summary

When switching Toonz Raster levels that contain MyPaint styles, the program is crashed.
### Screenshot or Video Reference

![ezgif-5-087a39876d53](https://user-images.githubusercontent.com/25724133/48585330-fbfc7e80-e934-11e8-85ce-e01bc47114b9.gif)

### Steps to Reproduce

1. Create two ToonzRaster levels.
2. In one level add new color style and select MyPaint style (or use default black style for that like i do on video)
3. Draw something using MyPaint style.
4. Switch to another Toonz Raster level - the program will crash.
### Expected Results

no crash
### Actual Results

crash
### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by manongjohn** [comment]
I confirmed this crash. I tracked it back to the change made for #2367.

**Comment by shun-iwasawa** [comment]
I'll look into this.

**Comment by shun-iwasawa** [comment]
I could reproduce the crash as well and found a probable cause. Thank you !
