### ISSUE TITLE
Black onion skins only

### ISSUE THREAD

**Issue by disqusnut** [opentoonz/opentoonz#2383]
This is not really an issue. More like a tiny bug report with a potential solution.
For some reason, I currently get only black onion skins. No matter what previous or following color is in "Preferences > Onion Skin", I only get black. I know what I am seeing in the next frame is the onion skin, even if it looks exactly the previous frame becuase:
- selecting Deactive Onion Skin makes it disappear
- erasing with the Eraser toll does not erase it

I tried other stuff like deleting the entire project and starting a new one but the color persisted. I was only able to return to the normal color setting by uninstalling Opetoonz. My previous version was 1.2.0 but I ended up installing 1.2.1

Not sure what the steps to recreate are. It happened while I was messing about trying to get Toonz Raster levels to be converted to Toonz Vector level. The black form showed up in the new Vector level and I ended up seeing it in Toonz Raster level also. I" did not check the pure Raster level.

**Comment by RodneyBaker** [comment]
Make sure you don't have Transparency check on under the View menu.

**Comment by disqusnut** [comment]
Wow! Thanks Rodney! That WAS my issue since I was able to recreate my problem in the new installation doing just that! Dont know when I clicked it but your solution is notably faster than re-installation.....

**Comment by RodneyBaker** [comment]
Glad it wasn't anything more serious. :)
