### ISSUE TITLE
Style Editor tabs missing on open 

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2385]
### Issue Summary

When first opening OT, only the color and settings tab are visible in the Style Editor, even if there is an active/selected level & styles associated with that level.

### Screenshot or Video Reference

![screen shot 2018-11-20 at 11 15 05 am](https://user-images.githubusercontent.com/21159116/48787089-1d06fb80-ecb6-11e8-9811-17d2a0ffbd06.png)
### Steps to Reproduce

Open an existing scene when you open OT.
### Expected Results

For the tabs to be visible if a level is active/selected.
### Actual Results

Only color and settings tabs are visible. To see the tabs, you have to switch to another style.
### System Information
* **OpenToonz Version**: nightly build & 1.2.1
* **Operating System**: MacOS 10.13.5, 10.14
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
This is also a problem when loading a different scene, when OT is already open.

**Comment by artisteacher** [comment]
Styleeditor.cpp and styleditor.h both have “enabledFirstAndLastTab” which seems to be causing this issue on open. Is there anywhere that we actually need only the first and last tabs visible? It would be easy enough to remove...

**Comment by RodneyBaker** [comment]
https://github.com/opentoonz/opentoonz/blob/25d3db05fd57aed51d666455ac8dbc44067a4cea/toonz/sources/include/toonzqt/styleeditor.h#L702

**Comment by artisteacher** [comment]
I guess that in an empty scene, or when an empty column is active, there only needs to be the color and settings tabs.

**Comment by RodneyBaker** [comment]
Ah.  Very interesting.
I take it this can be closed then.
Let me know if otherwise.

**Comment by RodneyBaker** [comment]
Closing this as a feature request pending possible reopening in the 2019 development cycle.

**Comment by artisteacher** [comment]
I hope it will be reopened! It's strange having context sensitivity where it isn't actually helpful...

**Comment by RodneyBaker** [comment]
Maybe we need to start one of those measurement tools where we continuously survey:  On a scale from 1 to 10 how do you rate your pain?

I jest but actually quite serious in that there are some things we run into that while they might not work optimally will hardly slow us down in production, if at all.  Is this one of those?  I don't know.  It can be very hard to measure someone else's tolerance level. Having been a burn victim I can attest that the scale of 1 to 10 does work quite well though! 

In this case we might alter that measurement a little and ask a slightly different question:

On a scale from 1 to 10 how strange would you rate this? :)

**Comment by artisteacher** [comment]
It depends on the point of the semester! When I have a new batch of students, it's pretty painful! The rest of the time it is obnoxious but usually bearable.

Some further thoughts on the subject:
If auto creation or "xsheet as animation sheet" are enabled, there should always be access to the brushes & etc. in the style editor - whether or not there is a level active. In both of those cases, any frame is potentially a level or part of one. If we aren't going to have context sensitivity for the different level types, it really doesn't make sense to have it here.

**Comment by RodneyBaker** [comment]
I'd love to see a screen recording of the workflow involved here as that would illustrate the obstacle your students are facing more clearly.  Something that we should look at also in the future is various resouces for teachers such as yourself to include outlines, project files and other learning resources.

Regarding context sensitivity...
Context sensitivity for everything in all instances is a rather tall order and fraught with the potential for creating new problems.  I love context sensitivity but mostly where it's given a very solid context.  In many cases that usually means Right Clicking and getting relevant content.  My concern is that there are new context sensitivity features coming online even as we type these posts and a lack of context sensitivity does not constitute an emergency nor should it and yet that's where these new features take us if we overplay our hand.  Teaching new students is painful... of that there is no doubt.  It's part of the learning process and as a teacher you know that all too well.  I do however worry a little about students that cannot overcome very simple obstacles.

If it's not prying might I inquire... What are the ages of your students?

**Comment by artisteacher** [comment]
High schoolers - so generally 14 to 18. This is really the biggest issue when we start using raster levels and are still learning the very basics. After that point, they've learned the workaround or are savvy enough to figure it out on their own. Many of the students are coming into the course with little to no experience with animation or graphics programs. It's not that they can't overcome obstacles, it's just that OpenToonz is a little overwhelming to them at first.

 Literally they open a scene, have a raster level in the first column that they want to continue working with and want to switch the first style to a different raster brush. However you have to switch out of the level and back, or to another style and back before the raster tab (with the vector & texture tabs) will display. This is only a problem when you first open a scene, if you want to change the brush for the first style. 

This isn't necessarily a big thing but it can create a less positive first impression. Why should you need to change levels or change styles to see the different tabs? It's not really a step that makes logical sense. It's not that I'm arguing for more context sensitivity, it's more that I'd rather not have it where it doesn't help. With the current capabilities, unless an audio, note, mesh, or fx level is active, all tabs should be visible in the style editor at all times. 

I love OpenToonz - I'm just passionate about my students having the best experience possible with it - so that they'll appreciate it too.

**Comment by manongjohn** [comment]
Was somewhat looking into this. What basically is happening is when loading a scene, it shows the current palette which is the scene's [CLEANUP] palette read in from the tnz file. Its not until you actually select an appropriate level that it has a [LEVEL] palette to display.

What should likely happen is after loading the scene, the current [CLEANUP] palette should be cleared out and not show anything.

**Comment by RodneyBaker** [comment]
As this sounds like a pressing concern reopening.

**Comment by artisteacher** [comment]
Still an issue after #2558.

**Comment by artisteacher** [comment]
> Was somewhat looking into this. What basically is happening is when loading a scene, it shows the current palette which is the scene's [CLEANUP] palette read in from the tnz file. Its not until you actually select an appropriate level that it has a [LEVEL] palette to display.

@manongjohn - in that case, why does the palette for the Xsheet's leftmost/first level, display in the Level Palette window, when an existing scene is first opened? That first level looks/behaves active, though it hasn't been specifically selected. 

I would think that the Style Editor's tabs should be based on the active palette in the Level Palette window, instead of the cleanup one. It seems especially strange in scenes that have never used cleanup. It also seems strange when you don't even have a cleanup room or any cleanup windows in your workspace.

**Comment by manongjohn** [comment]
The Cleanup palette is always loaded upon start up since it comes directly from the scene file. Likely when OT is loading in a scene for the 1st time, it isn't telling the Style Editor to refresh and load the palette of the current level so it loads the last palette it had in memory. 

I'll try and look a little more at it when I get a chance.
