### ISSUE TITLE
SWF format needed

### ISSUE THREAD

**Issue by 711GM** [opentoonz/opentoonz#2390]
Hello! You can add the format SWF. The fact is that in our studio we use this format and because of its absence we cannot switch to OpenToonz

There is even where to get all this. 
JPEXS Free Flash Decompiler
https://www.free-decompiler.com/flash/

GitHub
https://github.com/jindrapetrik/jpexs-decompiler

**Comment by 711GM** [comment]
As far as I know, the SWF format was before.

**Comment by RodneyBaker** [comment]
@711GM you stated:

>  ...in our studio we use this format and because of its absence we cannot switch to OpenToonz...
This is quite a statement.

I'm all for all the formats we can get in OT but SWF is a tough one to support as almost no one is supporting it not even Adobe

As you are some who expressly states current need and usage you are perhaps the perfect person to assist in outlining the way forward for this effort.

My personal opinion is that external tools and an external pipleline leveraging OpenToonz assets is going to be the best approach.  I don't see any other way forward at this point short of a new lease on life being given to the SWF format.

One very basic question that would be good to have answered is:  Does the commercial Toonz still support SWF output?  If the answer to that is yes then perhaps very basic... very very very basic... support of SWF could be brought into OpenToonz.

Where are all the champions of the SWF format?
We need you to weigh in on the subject beyond just saying, 'Yeah, we need it.'
In what ways do you use SWF?
Please be as detailed as possible.

**Comment by turtletooth** [comment]
I'm going to go out on a limb and say that is isn't going to happen.  OpenToonz can already output in the relevant formats used today.  There are probably swf converters out there if you really need a swf.

**Comment by RodneyBaker** [comment]
Thanks @turtletooth Much appreciated.

@711GM  Don't let this discourage you.
Start up a topic in the OT Forum and dive deeply into your needs and wants.
The industry is ripe right now for some new formats to leverage the various technological approaches.
I'm not sure what those formats will be but they very likely will be open standards.

**Comment by 711GM** [comment]
I speak English poorly and therefore it is difficult to communicate my thoughts. Therefore, I answer so long. The format is needed for some reason. We immerse these files in After Effects and they have high quality because of the program as it reads them as vector objects and I can easily increase them, I’m not afraid to spoil the quality, but what alternative can you offer? Other formats are not suitable at all; there is not just one vector video format, but ush, all the more that supported After Effect.

**Comment by 711GM** [comment]
The company Digital video used to add this format. He was exactly in the program " The Tab ".

![image](https://user-images.githubusercontent.com/40460266/49577321-3071c200-f958-11e8-8da9-1ee32428b3bc.png)


https://www.youtube.com/watch?v=7SwNUoVlbmo
