### ISSUE TITLE
 Crash switching Eraser Tool types in Vector Levels

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2391]
### Issue Summary

If you erase with the Eraser Tool and at the same time hold the button that switches the types "Freehand" and "Normal" (i use F5 for this), then a crash occurs.
### Screenshot or Video Reference

![ezgif-5-72561d49df79](https://user-images.githubusercontent.com/25724133/48950074-aaf71680-ef42-11e8-838c-cd9fc66df01c.gif)

### Steps to Reproduce

1. Assign hotkeys to switch between "Normal" and "Freehand" types (for me is F5) Since the same button switches between two modes, by holding the key you start their cyclic selection. (Intuitively, it seems to me that while holding a button I want to temporarily switch to another type)

2. If you try to erase a vector drawing while holding the type switching hotkey, a crash will occur.

### Expected Results

Holding down the type toggle button should not switch types cyclically. I think that the same behavior would be appropriate here as when switching tools (when you press a button, you switch to the next type, while holding the button, temporarily switch to the next type) Well, the “hold button to switch types” looks more like a function request, I would like to hear other opinions on this issue.
### Actual Results

Crash
### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by manongjohn** [comment]
I am able to reproduce this in 2 different ways:

Crash 1:
1) Create new Vector layer
2) Draw a short line
3) Switch to Eraser and select "Freehand" type
4) Circle entire line then stop but do not lift pen
5) Switch to "Normal" with shortcut
6) Continue to erase and cross line to erase a portion -> crash

Crash 2:
1) Create new Vector layer
2) Draw a short line
3) Switch to Eraser and select "Normal" type
4) Erase in the middle of the line to make 2 lines
5) Switch to "Freehand" type
6) Circle only 1 line segment to erase but do not lift pen
7) Switch back to "Normal" with shortcut
8) Lift pen -> crash

I can also do this in Rectangle and Polyline modes as well.

**Comment by RodneyBaker** [comment]
Boy, you guys find some obscure bugs!

Confirmed the two crashes @manongjohn outlined.
Also confirm those same two processes do not crash with the current appveyor release for PR #2396 

Mostly unrelated:  I am seeing persistent line appearing from the previous Freehand erasure in both latest nightly release as well as the PR.  I've never noticed that before.

**Comment by RodneyBaker** [comment]
This seems related to an earlier report #1209
