### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by janisozaur** [opentoonz/opentoonz#240]
Hi,
It appears that the code everywhere is formatted using various styles.
Would you accept a PR with a clang-format file for auto-formating and applying this style over all code base?

What style would you like? Please see http://clang.llvm.org/docs/ClangFormat.html and http://zed0.co.uk/clang-format-configurator/

**Comment by janisozaur** [comment]
Given three :+1: emojis, two of them from @skitaoka and @kogaki, who I believe are admins, I've decided to go on with the change in question. I will prepare PR in a moment.

**Comment by kogaki** [comment]
Yes, we also think code style should be defined. But we feel strict format let developers to be hesitate to submit PRs. Anyway, at least showing recommended format is a good manner. Thanks.

**Comment by kogaki** [comment]
We pertially performed formatting with `clang-format -style="{BasedOnStyle: llvm, IndentWidth: 4, UseTab: Always, BreakBeforeBraces: Linux, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, TabWidth: 4}"` at once, just for information.

**Comment by janisozaur** [comment]
I wasn't that far off with https://github.com/opentoonz/opentoonz/pull/249/commits/56a0108d3e6aa5417f80a9bc96c64d5ab5a8a262

```

---
BasedOnStyle: LLVM
AlignAfterOpenBracket: 'true'
AllowShortFunctionsOnASingleLine: Inline
BreakBeforeBraces: Linux
ColumnLimit: '100'
IndentCaseLabels: 'false'
IndentWidth: '4'
MaxEmptyLinesToKeep: '2'
Standard: Cpp11
TabWidth: '4'
UseTab: Always

...
```

Will you accept it or do you want me to apply the bits you had as well?

**Comment by kogaki** [comment]
No, I also think there aren't big difference. LGTM.

But... we are now planning to build next release soon. So could you wait a bit for merge?

**Comment by kogaki** [comment]
No, I also think there aren't big difference. LGTM.

But... we are now planning to build the next stable release soon. So could you wait a bit for merge?

**Comment by ideasman42** [comment]
Core formatting can mess with `git blame`, (even telling git to ignore white-space changes), and it annoys people working on branches too (even though it can be mitigated by applying auto-formatting on the branch before merging).
If its going to be applied to all files, suggest to apply early. Otherwise it can be applied more selectively later on.

**Comment by janisozaur** [comment]
Ideally, `clang-format` should be merged into the pipeline by being run on travis, so new patches conform to the style as well. `clang-format`, I believe, can format patches as well, so if a patch fails, a correct version can be presented to the submitter.

**Comment by metellius** [comment]
Make it a script that takes no parameters (ie. ./bin/clang_format_entire_codebase)  that can be easily and consistently applied so pull request authors can easily avoid merge conflicts on their pull requests like ideasman says. With all the pull requests waiting around, doing a global clang-format commit is going to be a big annoyance.

**Comment by billyquith** [comment]
Please *don't use tabs* in the source code. Github uses 8 space tabs so all of the code will look badly indented. Use spaces everywhere.

**Comment by ideasman42** [comment]
Formatting has been applied and beautification scripts in git, closing.
