### ISSUE TITLE
Increasing Maximum Fill Tool Line Gap

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#2401]
### Issue Summary
The maximum line gap for the fill tool is only 10 right now, which while certainly better than nothing isn't very big. Would it be possible to increase the max to something bigger, like maybe 50 or even 100? Better yet, maybe there could be a check box next to the max gap slider to disable checking for line gaps altogether when filling (the default behavior in Adobe Illustrator)? Thanks!

**Comment by turtletooth** [comment]
The second request is impossible with the way OpenToonz handles fill.  The first request is pretty easy to do, but I'm not sure it is actually needed.  It will take some discussion to see what others think.

**Comment by artisteacher** [comment]
10 is usually more than sufficient when I'm changing the maximum gap size. Depending on the drawing, there can be some very strange fill behaviors when the value is set that high. I wouldn't recommend going significantly higher due to those behaviors.

**Comment by turtletooth** [comment]
@artisteacher That's what I thought.  The reason I capped it at 10 was that I was getting sometimes strange results at that setting.

**Comment by RodneyBaker** [comment]
Would it be reasonable to leave the slider as is but allow the user to input higher values manually?  In other words, the 'safe' limit is specified by the slider but the user can decide to override.

**Comment by turtletooth** [comment]
I don't think the coding for the tool controls will allow a value that can't be shown in the slider.

**Comment by MrBlockCat** [comment]
I've seen cases where this would be very useful, like drawing Gumball from The Amazing World of Gumball's arm (what I wish could be an open line is circled in red)
![tawog open line fill example](https://user-images.githubusercontent.com/37186692/49610485-b3047c80-f96c-11e8-870e-8959df79894d.jpg)

Right now, I need to make a shape that is colored like the fill and curve it where the line is so it appears to be an open line with rounded caps, because the distance between the two caps would otherwise be too big. That said, I like RodneyBaker's idea of allowing higher numbers to be put in manually. If that can't be done, what if there were a setting (with a warning about odd behavior) inside Preferences to increase the maximum line gap to whatever value the user chooses?

**Comment by turtletooth** [comment]
@MrBlockCat That would be a good use case for a line with zero thickness.

**Comment by RodneyBaker** [comment]
Something to consider as well is scaling.
Because vector lines are resolution independent we an scale considerably to the point where a large gap is actually a rather small one.

**Comment by MrBlockCat** [comment]
I tried using a zero-thickness line and it worked like a charm, why didn't I think of that workaround! Thank you for your time, I'll close this issue as this approach works great.
