### ISSUE TITLE
Squiggle Vision

### ISSUE THREAD

**Issue by val3340** [opentoonz/opentoonz#2406]
### Issue Summary
 
Hello, 
I would like to know if it is possible to do this in Opentoonz, or in the next release ? It is so helpful... 
thank you, val
### Screenshot or Video Reference
 
https://vimeo.com/17863639

### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
The specific feature of squigglevision is not currently available in OpenToonz.
You can likely replicate the effect using available FX such as distort nodes in the Schematic.
