### ISSUE TITLE
Palette gizmo closes program with empty level palette

### ISSUE THREAD

**Issue by arh2009** [opentoonz/opentoonz#2411]
selecting Palette gizmo will force to close the program when no styles in level palette
![image](https://user-images.githubusercontent.com/20434396/49735835-00f5e900-fcbb-11e8-91d8-219f39471aa8.png)

**Comment by arh2009** [comment]
it will close the program when i change the scale or shift
![image](https://user-images.githubusercontent.com/20434396/49735979-5b8f4500-fcbb-11e8-8fca-fc8a87468639.png)

**Comment by beeheemooth** [comment]
I confirm this  (Windows 8.1)

**Comment by manongjohn** [comment]
It crashes when you try to open Palette gizmo when there is no palette or it comes up but crashes when you click on +/- when no palette has loaded?
