### ISSUE TITLE
(WIP)  Additional Portable options

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2420]
(Proposal)  Note:  This only effects Windows builds at this time.
This is an attempt to update #447 in a few ways to speed access to OpenToonz releases for purpose of testing, demonstration and research and development.

There are two tracks to this proposal:

Windows installer
1.  Add option to create OpenToonz as a portable during installation.
- [ ] Rather than regular installation this specifies a location other than Program Files for OpenToonz to be installed into.  (portables cannot run from the Program Files directory in Windows)
- [ ] Rather than creating/updating the stuff director at root of C:Drive installer would create the stuff directory inside the OpenToonz directory with the name "portablestuff".

This would make create a portable of OpenToonz for the user to move to any location desired such as external drive, USB, etc.

2.  Enhance automated Appveyor builds to make them portable
(this one needs some research and development)

Desired outcome:  The zipfile downloaded can be built with the above option to make Opentoonz portable on and therefore the appveyor download will be a self contained portable release for testing and demonstration purpose.

Currently I do the following with the appveyor release  (I don't currently use the debug release):
- Download the appveyor zip.
- Name the download something easy to remember such as "Opentoonz 1.2 (Text FX)":
- Unzip the file (This uncompresses the files into a directory named "Opentoonz 1.2 (Test FX)".
- Copy a prestaged copy of the stuff directory renamed as "portable stuff" into the newly created directory.

This creates a fairly stable and useable self contained portable of that specific release.
If testing with current stuff directory is desired I can just temporarily rename the portablestuff directory.

One reason this would be better automated is that currently appveyor builds that update any file in the stuff directory will not get that update because the appveyor releases are not installed... just downloaded.

I understand that there might need to be a flag to allow appveyors to be portable while still allowing nightly builds to fully install with Windows registry entries.

This is only an initial look at the viability of further streamlining the use of Opentoonz portable releases.  It is understood that this proposal may not be optimal or desired.

**Comment by RodneyBaker** [comment]
I don't think Macs use portables.

The primary aspect of programs being portable on  Windows is whether they store any information in the Windows registry.  This usually equates to drivers (DLL). 

With portables the instructions/settings that would be in the registry are repackaged as DLLs and placed in the directory structure along with the application.

**Comment by artisteacher** [comment]
So portable apps don't need to be installed per say and can run from anywhere? We totally can have that on MacOS as well - it just doesn't seem to be well documented.

**Comment by manongjohn** [comment]
At a minimum, you'd need to copy the OpenToonz_1.2.app to the USB, as well as the stuff folder renamed as 'portablestuff'. They'd need to be in the same directory on the USB drive.

I'd be curious to known if that's all it takes to make it portable on a mac or linux systems.

**Comment by artisteacher** [comment]
@manongjohn - that totally works! I'll have to spend some time testing to make sure it is completely functional. Changing preferences & saving is slow but that's probably not surprising. This is making me wonder if the issue I've had with creating the stuff folder when building myself #2292 has to do with the different locations of the newly created build and stuff folder.

For any other MacOS users that want to try this out - just make sure you put the actual stuff folder (from Applications -> OpenToonz -> OpenToonz_1.2_stuff) - not the general OpenToonz folder on the USB.

As far as testing goes, it would be great to not have to always have to build manually to test pr's on MacOS and Linux.

**Comment by RodneyBaker** [comment]
This is very good news.
If we can reduce the footprint of builds to where one release can be tested on all three platforms that would be very welcome.

Keep in mind that running from a USB is going to be slower so putting that directory on the harddrive or even external drive will have Opentoonz running faster.  In my estimation the primary reason to put Opentoonz on a USB is so that it can be taken to another system and copied along with all the Project files all in one fell swoop.

**Comment by RodneyBaker** [comment]
Note also that appveyor supports Linux so that is worth investigating as well.
I don't know why appveyor doesn't support Macs but that information is likely on their website.

**Comment by RodneyBaker** [comment]
Closing this for now as a feature slipping to 2019 development cycle.
We can continue discussing how best to implement and the various benefits.

**Comment by RodneyBaker** [comment]
I'm adding this here but it's more of a requirement for standard installation.
However, the addition would also assist with the creation of portable releases of Opentoonz on the client side.

During installation we currently can specify where the OpenToonz stuff directory will reside but we cannot specify were executable will be installed.

For reference see install documentation:  https://opentoonz.readthedocs.io/en/latest/installing_opentoonz.html#installing-on-windows

Note that the steps allow for routing the stuff directory to custom location but there is no option to specify location for Opentoonz itself.  I understand that one common location is optimal but for cases where multiple installations of Opentoonz may be required an option to enter that location is desirable .
