### ISSUE TITLE
Exploding/Opening macro node sometimes causes all nodes to be stacked

### ISSUE THREAD

**Issue by Wolfinabowl** [opentoonz/opentoonz#2421]
### Issue Summary
As the title describes, Macro FX nodes may sometimes seem to lose the positions of their child nodes.

### Screenshot or Video Reference

![image](https://user-images.githubusercontent.com/42905003/50028102-78db5080-ffe6-11e8-9964-635a3a7d00b6.png)
Left: The issue | Right: Expected

### Steps to Reproduce
1. Place a macro FX node
2. Choose 'Open Macro FX' or 'Explode Macro FX'
There is a chance that all of the nodes will be stacked on top of each other.

I have not found a way to trigger this behavior consistently, at this time, it appears to be random; even when placing two of the same Macro FX in a row, one may open correctly and the other may not.

Notes:
One an instance of a Macro FX opens as a stack, it is **guaranteed** to continue to do so.
This applies in cases such as; closing & reopening, cut & pasting, copying & pasting (all pasted nodes will be afflicted), and reloading the scene.

Repeat steps 1 & 2 for each Macro FX you have, some may exhibit the issue while some may not:
![image](https://user-images.githubusercontent.com/42905003/50028657-534f4680-ffe8-11e8-986a-f6535f7228dc.png)
Here the 'Outline' Macro FX did not open correctly while the 'Fire 1' Macro FX did this time.

### System Information
1.2.1 (Nov 26 2018)
Windows 10
I7 5820l
16gb ddr4
GTX 980 4gb

Let me know if you need more information

**Comment by Wolfinabowl** [comment]
Here is a gif of this issue:
![ezgif-5-4acd823b7d99](https://user-images.githubusercontent.com/42905003/50032674-42550400-ffed-11e8-97a5-01c9b2becca0.gif)

**Comment by manongjohn** [comment]
Changes I made in PR #2407 should address this. If you want to test it out, download the Appveyor build and see if it fixes it for you.

**Comment by RodneyBaker** [comment]
I'll guess we may need to have all the PRs related to the Schematic merged before we can properly assess what is still remaining.   Keep in mind also tht some changes in the Schematic rely on files in the stuff directory and appveyor releases don't emplace anything in the stuff directory.

Note:  I don't know of any PR that is specifically trying to address this particular issue.

**Comment by manongjohn** [comment]
Ok.  I see what's going on.  It's when you move it before opening it that it recalculates the position  improperly.

I have a bit of a fix for this which I will include in #2407.

**Comment by Wolfinabowl** [comment]
Further testing confirms that moving the node before opening it does indeed cause the incorrect positioning.
I suppose the cause seemed more random due to the fact that a node can be dragged with the RMB, and so I would accidently drag the node very slightly before opening it.

**Comment by RodneyBaker** [comment]
Outstanding.  Thanks for the confirmation @Wolfinabowl
