### ISSUE TITLE
Motion Path Schematic UI icons do not scale with zoom

### ISSUE THREAD

**Issue by snapai** [opentoonz/opentoonz#2422]
The two mode buttons that appear when using a motion path do not scale with the UI.
To be honest, I have no idea what these switches do since I haven't worked with motion paths, but their visual appearance is broken, so it's a bug. :)
From default zoom up to this size, they appear normal:
![image](https://user-images.githubusercontent.com/5098372/50044115-ea4dea00-004c-11e9-9ecf-67b6853a8871.png)
![image](https://user-images.githubusercontent.com/5098372/50044125-fe91e700-004c-11e9-86d8-92bfd722d063.png)

However beyond this point, they no longer scale with the UI, shrinking to the top left corner of the box
![image](https://user-images.githubusercontent.com/5098372/50044109-da360a80-004c-11e9-8162-7277f8f209e1.png)

This doesn't affect me much as the box is enormous on my screen at this zoom, but for someone using a high-DPI monitor like an Apple Retina Display this might actually affect normal use.

**Comment by RodneyBaker** [comment]
I can't speak to the resolution issue but...

Those tiny icons at the bottom appear to be for orientation and alignment to the motion path.
To explore set up a column (ideally with something to view exposed inside it) and create/attach a motion path for it.  Then with the Animate Tool activated watch what appears and happens as you move the column along the path while flipping those icon/switches on/off.

**Comment by RodneyBaker** [comment]
Closing as an enhancement of low priority slipping to 2019 development cycle.

**Comment by gab3d** [comment]
@RodneyBaker  @manongjohn 
just came across this one today, perhaps this could be reopened now? 
it's still present

**Comment by gab3d** [comment]
Another related issue is that both of these buttons lack any tooltip, 
what makes it harder for new users to know what they do.

**Comment by manongjohn** [comment]
Reopened as I consider it a bug that it does not resize properly.
