### ISSUE TITLE
changing tools

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#2423]
Hello everyone, I realized that, for example if I'm using the brush tool, then I hold the space bar a moment to pan the view, and then I release the key to continue drawing, it doesn't always comes back to the brush tool. 

I think this wouldn't be a matter of a bug, but of an adjustment of the minimum time a key has to be hold to come back to the previous tool. This could make a better experience when drawing.

These are my specs:

-Open Toonz (nightly_e28b5ed088fe4a3fb8baaddb8d4d30641cc9dfe0)
-Windows 10 Home edition 
-Intel i7-8700 
-16GB of Ram
-NVIDIA GeForce GTX 1070 8GB

Thanks in advance for all your work on Open Toonz.

**Comment by RodneyBaker** [comment]
Yes.  This is a reported observation with several tools and hopefully will have a fix very soon.
Look for it!

**Comment by RodneyBaker** [comment]
This reports relates to #2360 I think enough to call it a duplicate.
Closing.  @NestorAntonio Keep an eye on #2360 and other similar updates to make sure it addresses your need.
