### ISSUE TITLE
Directional blur is not calculated correctly

### ISSUE THREAD

**Issue by snapai** [opentoonz/opentoonz#2434]
The directional blur FX node appears to combine the blur with a copy of the original artwork.
Below is an example - using a circle with a thick border and a different fill color
![image](https://user-images.githubusercontent.com/5098372/50263781-9729bd80-03e5-11e9-9b6e-df3fc3df3ecf.png)
Original art

![image](https://user-images.githubusercontent.com/5098372/50263737-65b0f200-03e5-11e9-8256-d76be5879a22.png)
OpenToonz's directional blur node applied with an angle of 90 degrees and distance of 20 pixels

![image](https://user-images.githubusercontent.com/5098372/50263750-76f9fe80-03e5-11e9-8f70-c405411e4806.png)
Krita's "motion blur" applied with an angle of 90 degrees and distance of 20 pixels.

The original artwork appears to be being mixed erroneously with the blurred result in the OpenToonz version.

**Comment by snapai** [comment]
This was present in the latest nightly build as of this posting.
Note: OpenToonz "Motion Blur" is unrelated, applying a blur based on layer motion, not based on a direction and magnitude.

**Comment by RodneyBaker** [comment]
We likely need more information to assess what a correct calculation is.
Does Krita have a DIrectional Blur that can be used for comparison purposes for instance and not just Motion blur?

When considering calculations, keep in  mind that Opentoonz also has the Directional Blur Iwa FX which has additional parameters such as Linear, Gaussian and Flat and also allows input of a reference source/image.

So a question might be whether the Directional Blur FX is designed to be the way it is on purpose so as not to incur additional calcuculations whereas the Dirextional Blur Iwa FX allows a broader scope.

Image:  Just a random image rendered with Directional Blur FX while looking into this.
![directionalblur](https://user-images.githubusercontent.com/2576432/50317008-f38ceb80-047e-11e9-8642-c54c8e22ebee.png)

**Comment by snapai** [comment]
Oh, it's the I-W-A blur. My mistake, I missed it - general advice in the community is that those are special-use for studios and not to touch them.
