### ISSUE TITLE
Crash when Motion Blur FX is applied to level deformed by Plastic Tool

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2440]
### Screenshot or Video Reference

![ezgif-1-6d1462d59ee3](https://user-images.githubusercontent.com/25724133/50344291-1aa4f500-0533-11e9-96db-97473e7ded33.gif)

### Steps to Reproduce

1. Create an animation level with plastic deformation
2. Apply Motion Blur FX to level
3. Turn on Preview

### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by Wolfinabowl** [comment]
Can reproduce on Master and LNB
