### ISSUE TITLE
 Tools become disabled/unusable 

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#2442]
### Issue Summary

Posted on forum : https://groups.google.com/forum/#!category-topic/opentoonz_en/troubleshooting/wwZt_toEo7I

several tools (eraser, selection, point editor, brush, magnet tool etc...) become unusable as deactivated.

The problem seems to appear in several ways ... This one is reproducible:

1 - create a column with a drawing
2- create a second column with another drawing
3- hide the 1st column 
4- try to draw on hidden column
5- close pupup
6 -go to 2nd column
7- try to use your different editing tools ...

the tools are disabled or work intermittently. The only solution is to restart the program.

Note: The mouse does not seem to have a problem, seems to be a problem with the stylus.

### Screenshot or Video Reference

![tools become unusable](https://user-images.githubusercontent.com/29790512/50405850-13901800-07bb-11e9-913d-21f97b61f4fb.gif)

* **OpenToonz Version**: NB dec 19 2018 15.01.20
* **Operating System**: w10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 5100 hd graphics
* **Graphics Tablet**: Cintiq companion 2

**Comment by manongjohn** [comment]
@openanim I can't seem to duplicate this myself.  However, I think I know what's causing this and I believe #2087 will also fix this issue.  Can you try it out?

**Comment by openanim** [comment]
@manongjohn I just tried with the appveyor version and the problem still seems there. Same steps with the appveyor:
![tools become unusable](https://user-images.githubusercontent.com/29790512/50406499-2d832800-07c6-11e9-8468-04547f4b0cfa.gif)

**Comment by openanim** [comment]
The problem also appears  just by hiding a column, closing the pop up and reactivating the camera stand visibility. Shorter than the previous steps.

**Comment by shun-iwasawa** [comment]
@openanim Can you please try #2431 ? It fixes stylus + warning popup issue.

**Comment by openanim** [comment]
@shun-iwasawa Yes ! it works . Thanks, I close the problem.
