### ISSUE TITLE
Level names are not visible in FX Schematic

### ISSUE THREAD

**Issue by ave4** [opentoonz/opentoonz#2451]
Somewhere a month ago, there was such a problem: elements in FX Schematic are displayed incorrectly in Linux. They are all black.
I recently collected a stable release of Opentoonz 1.2.1 from git and everything is displayed normally there.
### 
OpenToonz master
![2018-12-28 22-59-03](https://user-images.githubusercontent.com/35303790/50524121-bb784f00-0af5-11e9-92e0-d64f78047d87.png)

![2018-12-28 22-59-21](https://user-images.githubusercontent.com/35303790/50524127-c7641100-0af5-11e9-86c7-5b10c7c0337e.png)

### OpenToonz 1.2.1

![2018-12-28 22-57-47](https://user-images.githubusercontent.com/35303790/50524142-dfd42b80-0af5-11e9-9ba7-8cd13d754bdb.png)

![2018-12-28 23-00-03](https://user-images.githubusercontent.com/35303790/50524144-e5317600-0af5-11e9-9c27-0b2e4b2b58f2.png)

### System Information

* **Operating System**: Arch Linux, Debian
* **CPU**: Intel i3-3220
* **Memory**: 6 GB
* **Graphics Card**: Intel

**Comment by RodneyBaker** [comment]
@ave4 So you are reporting this apparently has been fixed?

**Comment by manongjohn** [comment]
There were qss changes for a PR that updated the schematic view.

When installing, the OpenToonz 1.2 stuff folder must be updated with the changes or they appear black as you see.

As you are on a Linux system, I'm not sure how OT is installing for you. If you reinstall and are given a choice to update the stuff folder, select yes.

**Comment by ave4** [comment]
For me, copying OpenToonz components to a working directory is not a good idea. Still, it would be better if these files were stored in system directories and OpenToonz accessed them directly.
