### ISSUE TITLE
ParticleFX crash

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2456]
There seems to be an issue with the ParticleFX node when using a Vector Level as the 'Texture' input with 'Perspective Distribution' enabled.

Steps:
1. Create a new ToonzVector level
2. Instance a ParticleFX node in the FX Schematic graph
3. Connect the level to the 'Texture' input
4. Inside the ParticleFX's 'Birth Params' section, enable 'Perspective Distribution'
5. Attempt to render or preview - OT will crash

You may also see the message 'Ran out of contiguous physical memory: please save all and restart Toonz!' though this doesn't seem to appear every time.

Edit, 2nd Jan:
Further testing shows that this issue only occurs when the 'Texture' input is a ToonzVector level (the 'Control' input doesn't matter, nor does the index); other level types don't seem to result in a crash when following the above steps.

**Comment by gab3d** [comment]
confirmed here.
no need to render, just preview and OT disappears.

**Comment by shun-iwasawa** [comment]
Confirmed the crash. It occurs only when inputting the blank level, right?
In my Win8 environment, it does not crash if I input the vector level with some drawing.
OTOH when I input the blank level, it always crash regardless of the "Perspective Distribution" option.

**Comment by Wolfinabowl** [comment]
I seem to have discovered another issue, it seems related.
It is possible to cause a crash when using a ToonzVector, even if it is not blank, as the 'Control' input with perspective distribution enabled.

Note: The Texture input being connected to a level does not matter for this crash, OT will crash in either case

Repro steps:
1. Create a new ToonzVector level, draw something on it
2. Instance a ParticleFX node in the FX Schematic graph
3. Connect the level to the 'Control' input
4. Inside the ParticleFX's 'Source' section, set the 'Control Image' index to 1
5. Inside the ParticleFX's 'Birth Params' section, enable 'Perspective Distribution'
6. Attempt to render or preview - OT will crash

**Comment by gab3d** [comment]
@shun-iwasawa 
When I originally tried it, I've had the same type of crash @Wolfinabowl had, with a vector level (not empty) connected as control image and Perspective Distribution activated.

**Comment by gab3d** [comment]
@shun-iwasawa 
I've just tested again with a vector level.
It does crashes, just not an inmediate crash. I can start to preview the sequence and after 100 frames or so OT dissappears.

**Comment by shun-iwasawa** [comment]
Thank you @Wolfinabowl and @gab3d for clarification.
I confirmed the other crash and also fixed in #2459 .
