### ISSUE TITLE
Resizing the new text effect resizes it around the centre instead of being able to move each corner separately

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2462]
### Issue Summary
When I resize the size of the text effect by dragging the corner handles, the whole shape resizes around the centre point. I can see this being useful in some circumstances, but that should only happen if you hold Ctrl or shift or some other modifier. I'd expect the default behaviour to work the same as resizing your drawing, using the selection tool. Drag the top right corner and the other 3 corners sit still.

### Screenshot or Video Reference
Here is the resizing of the text area:
![screencapture](https://user-images.githubusercontent.com/28575907/50737647-e5033b80-11c3-11e9-9c94-3209cb0959aa.gif)

Here's how the resizing using the select tool works (I'd expect the text area to work this way too):
![screencapture](https://user-images.githubusercontent.com/28575907/50737691-31e71200-11c4-11e9-915e-2ed06b0af092.gif)

### OpenToonz Version ###
I'm using a nightly build from 14/12/18

**Comment by shun-iwasawa** [comment]
It is not only the behavior with the TextIwa Fx, but also all other Fx using rectangle parameter.
The Fx parameter gadgets for specifying rectangle are separated into two parts; size and center.
It is true that the dragging behavior is inconsistent with one of the Selection tool, but I think it can prevent setting unwanted key frame to the center value when you edit the size.
