### ISSUE TITLE
Crash attempting to convert FX to Vector etc. 

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2466]
There are two easy ways to crash OT with the new TextIwa FX.

Steps:
1. Instance a new TextIwa node in the FX Schematic
2. With the newly created level selected, choose either 'Vectors to Toonz Raster' or 'Replace Vectors with Simplified Vectors' from the 'Level' drop-down
3. OT will crash when either command is chosen

**Edit**:
These crashes are also present on any levels created by FX e.g. ParticleFX, Clouds, ColorCard, TimeCodeIwa, any gradient FX, etc.

Some checks need to be put in place to prevent these commands being run on levels that have been created by FX.

Any node with this color can be used:
![image](https://user-images.githubusercontent.com/42905003/50791975-612c7a80-12bb-11e9-82cd-c554e8b6e440.png)

Checks are already in place in other circumstances as if the above commands are run on a non-Vector level this message appears:
![image](https://user-images.githubusercontent.com/42905003/50792086-b9fc1300-12bb-11e9-99ba-7c42123b8f8e.png)

It seems that these checks are not run in the case that the selected level was an FX-created level.

**Comment by RodneyBaker** [comment]
Confirmed the crash.
It's curious that I don't get the crash if I use 'Convert to Vector'.
Perhaps there is a check present there that is not for the other options "Convert to Toonz raster" and "Simplify Vectors".

**Comment by RodneyBaker** [comment]
It's not low priority as much as it's not likely to get the attention it needs short of you resolving the problem.  I didn't think assigning it to you would be appropriate... yet.  :)

I will defer to you and other contributors who can freely adjust labels as they see fit.
We have approx. 250 open reports.  I'm merely suggesting they can't all be of the same priority.
