### ISSUE TITLE
It's possible to lose the Curves node's handles

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2480]
Gif example:
![curves issue](https://user-images.githubusercontent.com/42905003/51251158-90fd1180-1990-11e9-9340-2addbc995154.gif)

As you can see, it is possible to move the Curves node handles into an area that is unclickable; this results in the user being unable to retrieve the handle.

A suggestion for fixing this issue would be to add cursor-key controls to selected handles and holding shift would increase the distance at which the handles move.
Alternatively, it would make sense to lock the handles within the clickable area, though this comparatively limits their movement range.

**Comment by RodneyBaker** [comment]
For those interested in this issue please see comments and concerns in PR #2480.
Your feedback will be appreciated.

**Comment by RodneyBaker** [comment]
Closing as being addressed #2799 
After exploring several approaches it was decided to allow the curve handles to extend out of window but the curve points can be recovered via use of arrow keys.

For those that wish to prevent the curve handles from exiting the window entirely via their own build, @martinvanzijl provided code to do just that in #2480 which was not merged into master.
