### ISSUE TITLE
Toonz Raster crash selecting frame in 2nd level of a column

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2484]
Getting a crash in 1.3RC when selecting a blank frame on Toonz Raster level when it is the second level in the same column

To recreate:

Using pen
Autocreation mode =  Xsheet As Animation Sheet with Auto-stretch enabled

1) Open new scene and select Brush tool
2) Select Frame 1 on xsheet and draw to create a Vector level
3) Select Frame 13 in xsheet and create a new Toonz Raster level and draw something
4) Select Frame 15 in xsheet and draw something
7) Select Frame 16 or 17 -> Crash 
    If it doesn't crash right away, draw something then try selecting another Frame. 1 or 2 away from the previous.

This only crashes when the 2nd level is the Toonz Raster level and when using a pen.

### System Information
* **OpenToonz Version**: 1.3RC. Also seen in 1/2/19 Nightly, but does not happen in official release
* **Operating System**: Win7 w/ XP-Pen tablet and Win10 laptop-tablet

**Comment by beeheemooth** [comment]
Yes, it seems that this does not happen if you use the mouse. A frame is created without a drawing.
