### ISSUE TITLE
Combo Viewer not working with Duet software

### ISSUE THREAD

**Issue by Buttbag89** [opentoonz/opentoonz#2493]
### Issue Summary

Trying to use Duet (Ipad to Pc screen projector, Pro version lets you use Ipad pencil sensitivity and tilt on drawing apps.) and when I download the app the combo viewer stops working, and when I try to expand and pull down at all it creates a bunch of duplicate screens that don't work ( see attached image.) I know for a fact it's a duet/Opentoonz issue because when I uninstall duet it works perfectly fine.  
### Screenshot or Video Reference

![d59d6f61-cedd-4dfd-9a48-7610a87d523b 1](https://user-images.githubusercontent.com/18090288/51585877-e7d28180-1e8f-11e9-8dbc-d403d53de4ba.png)

### Steps to Reproduce

1. download open toonz
2. download duet 
 
Opentoonz combo viewer will stop working completely. Even with your mouse. I don't think you even need to try it with the ipad pencil and Ipad

### Expected Results

should be able to use Apple pencil as stylus on I pad

### Actual Results

Combo viewer crashes

### System Information
* **OpenToonz Version**:  1.2
* **Operating System**:  windows 10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:  Ipad and Ipad pencil

**Comment by Buttbag89** [comment]
The viewer too, anything that has to do with the drawing aspect of the app.

**Comment by artisteacher** [comment]
You might want to try the [release candidate](https://github.com/opentoonz/opentoonz/releases/tag/v1.3.0rc2) - there have been a lot of bug fixes since 1.2. You also could try updating the drivers for your graphics card.

**Comment by Buttbag89** [comment]
Ok I’m not even sure I have a graphics card haha my brother built it and he
started me off with a lot of ram and a solid state but I think we ended up
not putting in a graphics card Or (if you have to have one, one that’s very
bottom of the line.)  I’ve been able to use opentoonz seemlessly before
without issue so maybe it’s time to get a good/new one. I will ask my
brother and if he did put one in I’ll try updating the drivers and
installing the new release candidate. I’ll let you know how it turns out!
Thanks for the advice.

**Comment by RodneyBaker** [comment]
@Buttbag89  Any updates on your effort to use Duet with Opentoonz?

**Comment by RodneyBaker** [comment]
Duet has had several updates since this report was opened.
For those interested, recommend updating Duet and testing.

https://www.duetdisplay.com/help-center/windows-release-notes

(I do not have an iPad so cannot test this)

**Comment by RodneyBaker** [comment]
Closing as part of general housekeeping.
This report is labeled a research as the prospect of having Opentoonz working on various systems such as Duet is intriguing.
@Buttbag89 Please keep us posted as you make progress.
