### ISSUE TITLE
OSX 10.14.2 local build failure

### ISSUE THREAD

**Issue by yehjaemin** [opentoonz/opentoonz#2496]
### Edit 1
I found some closed issues from a couple years ago that go over this problem but their fixes don't work for me. Specifically, #40 Compilation notes for OSX and #1566 Undefined symbols for architecture x86_64 mention running make clean and changing toonz/cmake/FindTIFF.cmake line 22 from libtiff.a to libtiff.dylib, which seemed to work for them but isn't working on my current version of OS X.

### Edit 2 - Working
After hard deleting the build directory and remaking it, I was able to successfully run make! It seems that the edit to FindTIFF.cmake did the trick. If no one minds, I'd like to submit a pull request that changes the file.

### Issue Summary
When building on Mac Mojave 10.14.2 using the local build instructions, I run into an error on the final make step. Everything works fine beforehand, although I noticed that when installing Qt that I had to check the custom installation boxes for Sources and Qt Script.

### Screenshot or Video Reference
This is the output of calling make in the opentoonz/toonz/build folder. I think some of the build steps are missing because this is the second time trying to build.
```
[  7%] Built target tnzcore
[  7%] Linking CXX shared library libtnzbase.dylib
[ 10%] Built target tnzbase
[ 10%] Linking CXX shared library libtnzext.dylib
[ 12%] Built target tnzext
[ 12%] Linking CXX shared library libtoonzlib.dylib
[ 38%] Built target toonzlib
[ 38%] Linking CXX shared library libtfarm.dylib
[ 39%] Built target tfarm
[ 39%] Linking CXX shared library libtnzstdfx.dylib
[ 48%] Built target tnzstdfx
[ 48%] Linking CXX shared library libsound.dylib
[ 48%] Built target sound
[ 48%] Linking CXX shared library libcolorfx.dylib
[ 50%] Built target colorfx
[ 50%] Linking CXX shared library libimage.dylib
Undefined symbols for architecture x86_64:
  "_lzma_code", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.o)
      _LZMAPostEncode in libtiff.a(tif_lzma.o)
      _LZMAEncode in libtiff.a(tif_lzma.o)
  "_lzma_end", referenced from:
      _LZMASetupDecode in libtiff.a(tif_lzma.o)
      _LZMASetupEncode in libtiff.a(tif_lzma.o)
      _LZMACleanup in libtiff.a(tif_lzma.o)
  "_lzma_lzma_preset", referenced from:
      _TIFFInitLZMA in libtiff.a(tif_lzma.o)
      _LZMAVSetField in libtiff.a(tif_lzma.o)
  "_lzma_memusage", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.o)
  "_lzma_stream_decoder", referenced from:
      _LZMAPreDecode in libtiff.a(tif_lzma.o)
      _LZMADecode in libtiff.a(tif_lzma.o)
  "_lzma_stream_encoder", referenced from:
      _LZMAVSetField in libtiff.a(tif_lzma.o)
      _LZMAPreEncode in libtiff.a(tif_lzma.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/libimage.dylib] Error 1
make[1]: *** [image/CMakeFiles/image.dir/all] Error 2
make: *** [all] Error 2
```

### Steps to Reproduce
Follow the steps in the local build instructions for OS X, installing Sources and Qt Script during the installation for Qt. The problem should occur at the second to last step, when calling make.

### Expected Results
make should have produced the OpenToonz.app executable

### Actual Results
The build process exited at 50%. There specifically seems to be a problem with libimage.dylib. I think there was another issue, #2468, that found a problem with another .dylib file in OS X, but I'm not sure if that's actually related to this one.

### System Information
* **OpenToonz Version**: 
* **Operating System**: Mojave 10.14.2
* **CPU**: 2.3 GHz Intel Core i5
* **Memory**: 8GB
* **Graphics Card**: Intel Iris Graphics Plus 640
* **Graphics Tablet**: n/a

Edit: there is a closed issue from 2016 (#40 Compilation notes for OSX) and one from 2017 (#1566 Undefined symbols for architecture x86_64) that references the problem that I'm running into but they were both resolved without posting clear instructions on how to fix the problem. So far, I've tried
- make clean && make -j4 in the build directory
- replacing libtiff.a with libtiff.dylib in FindTIFF.cmake
and I run into the problem with libtiff.a again.

**Comment by lordadamson** [comment]
What am I missing. Was this resolved? I'm facing the same issue apparently for the same reason. Why is this issue closed?

**Comment by manongjohn** [comment]
The LZMA errors can be fixed by disabling LZMA in this step:

> $ cd ../tiff-4.0.3
> $ ./configure --disable-lzma && make

**Comment by lordadamson** [comment]
Okay great. Shouldn't that be modified in the docs?
