### ISSUE TITLE
Opentoonz loading scene issue

### ISSUE THREAD

**Issue by Gibson46** [opentoonz/opentoonz#2498]
Opentoonz scene is not loading properly only 1 column is showing instead of 2

### Issue Summary
I tried to load the scene which was given by my employer to cleanup and coloring but the its opening only 1 column instead of 2 columns (background column to edit it) as employer mentioned. Could anyone help me to resolve this issue I tried reinstalling the software after deleting all supporting files from C drive but still not working.

------
To: @Gibson46 
I edited your post as the texts were commented out. (shun-iwasawa)

**Comment by artisteacher** [comment]
@Gibson46 - what issue are you having specifically around loading scenes? Information about your operating system and version of OT are always helpful too.

**Comment by manongjohn** [comment]
What error message, if any, are you getting? A screenshot or short video might help us understand the issue you are encountering so we can help you.

**Comment by artisteacher** [comment]
Is there a specific scene not loading at all? No scenes will load? Loading any scene causes a crash or hanging? Loading a specific scene causes a crash or hanging?

**Comment by artisteacher** [comment]
In that case, do you see 2 columns in the Xsheet/Timeline or just 1? If both columns are there but not visible in the viewer, it could be that visibility is turned off.
Render/preview (eye icon) and camera stand visibility turned on:
![screen shot 2019-01-28 at 11 38 43 am](https://user-images.githubusercontent.com/21159116/51851224-76f8f280-22f1-11e9-9bf2-db033c259689.png)
Render and camera stand visibility turned off:
![screen shot 2019-01-28 at 11 38 59 am](https://user-images.githubusercontent.com/21159116/51851281-9001a380-22f1-11e9-8cb8-71db3451467b.png)

If only one column is visible in the Xsheet - or if one column has red lettering/numbers (this happens for missing levels), you can take a look in the Browser room to see if the missing level is in either the extras or drawing folders for your project.
![screen shot 2019-01-28 at 11 41 59 am](https://user-images.githubusercontent.com/21159116/51851525-128a6300-22f2-11e9-83c6-319b3318533c.png)

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Gibson46 Please let us know if you are still experiencing similar issues.
