### ISSUE TITLE
Using old "Opentoonz Stuff" Folder after an upgrade

### ISSUE THREAD

**Issue by PomPom9876** [opentoonz/opentoonz#2502]
I'm on a MacBook Pro 15", MacOS Mojave v10.14.2

When I upgrade to Opentoonz 1.3 (from 1.2) can I simply replace the new Opentoonz Stuff folder with my older one and have all my projects show up? Is this a good practice, going forward, for each updated version that will be released? Thanks...

**Comment by manongjohn** [comment]
No, or you will lose anything added new to the configs for 1.3

If anything, copy the OpenToonz_1.2_stuff and rename it to OpenToonz_stuff, then reinstall 1.3 so any new changes will overlay older ones. Personal preferences should not be impacted.

After 1.3, this will not be an issue.

**Comment by PomPom9876** [comment]
Thank you!
