### ISSUE TITLE
Visual bug with Fill Check view and ToonzRaster level

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2504]
Repro steps:
1. Create a new ToonzRaster level
2. Enable fill check view
3. Draw an enclosed, fillable shape e.g. a circle

Result:
![fill check issue](https://user-images.githubusercontent.com/42905003/52004131-5631c800-24be-11e9-8fd7-90b4309fdc85.gif)
You can see that the dark color denoting that the area is fillable does not appear correctly.
Refreshing the screen causes it (or some parts of it) to become visible, either by moving the canvas, moving the cursor inside the fillable area, causing a UI refresh, etc.

Additional details:
This issue does not occur if the fillable area is created with the Geometric Tool.
This issue does not seem to occur with ToonzVector levels.
This issue only occurs if the Fill Check view is enabled at the time the fillable area is drawn.

Environment:
OS: Windows 10
CPU: I7 5820k
GPU: GTX 980
Version: 1.3 RC2

**Comment by artisteacher** [comment]
This happens on macOS too.
