### ISSUE TITLE
Import Magpie File window bad layout

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2511]
### Issue Summary
Hi,
When updating screenshots for the documentation I've come through this problem.
The options window for the **Import Magpie File...** function has a bad layout.

### Screenshot or Video Reference
![magpie_import](https://user-images.githubusercontent.com/18104091/52280104-cbc3eb00-2939-11e9-9f0e-61500751ae0e.png) ![magpie_import_orig](https://user-images.githubusercontent.com/18104091/52280642-1a25b980-293b-11e9-9dc7-1655702f80af.png)

### Steps to Reproduce
- File > Import Magpie File...
- Load a .TLS file.
- The options window shows.

**Comment by RodneyBaker** [comment]
Fixed via #2821
