### ISSUE TITLE
Sugested features for stopmotion: webcam support and increment editor

### ISSUE THREAD

**Issue by charliemartinez** [opentoonz/opentoonz#2515]
Issue Summary:

I am developing a custom Debian distribution to be used in animated film schools in Argentina and there is a tool that we have not yet been able to replace with any specialized stop motion application. 

I'm talking about Dragonframe. qStopmotion works well, but the most similar tool to Dragonframe is OpenToonz, thanks to its x-sheet and its"camera capture" function. Apart from the fact that we still can't make any webcam work with this function, we're sure you'll be able to fix that soon. 

Just in case the following information is useful to you: I have ever tried opentoonz from an AUR repository, how much I used Manjaro, and the webcam worked. 

However, the current functionality of opentoonz  is still insufficient for school teachers to accept it as a replacement, because of all the tools that have Dragonframe there is one that they consider essential: the increment editor, feature that shows movement along a path in time. It can be used to plan out simple motion paths. (automatic animation scales along a guide stroke drawn with the mouse).

This feature, also present in previous versions of Dragonframe, is explained on pages 62 and 63 of the version 4 online manual: 

https://www.dragonframe.com/download/Using%20Dragonframe%204.pdf 

I'm sure if they could program a similar feature, animation schools in my country would use OpenToonz instead of Dragonframe.

Greetings and thank you very much. 

Screenshot or Video Reference:
https://vimeopro.com/user8154042/dragonframe/video/30053311 

Expected Results:
To achieve, with that and the function of editor of increase, that the system is adopted by the Argentine schools of animation, that at the moment do not use open source. 

Actual Results:
-Webcam not work, 
-Absence of an increment editor for stopmotion like Dragonframe.

System Information:
OpenToonz Version: Actual Official and Morvenga.
Operating System: Debian 9 Stretch
CPU: i5
Memory: 8 GB ram,  8GB Swap
Graphics Card intel graphics onboard
Graphics Tablet fujitsu lifebook 
Webcam: Logitech C922

**Comment by artisteacher** [comment]
I'm hoping that there will be more support for cameras in the future - for stop motion or other hands on techniques. I'd love to be able to use my Canon DSLR's with my students directly connected to OpenToonz.

While there is not an increment editor per say, the Function Editor does have a curve editor that might provide some of the functionality you are looking for.
![screen shot 2019-02-12 at 11 13 08 am](https://user-images.githubusercontent.com/21159116/52649915-37b4cf00-2eb7-11e9-9338-07a613162dec.png)

**Comment by charliemartinez** [comment]
> I'm hoping that there will be more support for cameras in the future - for stop motion or other hands on techniques. I'd love to be able to use my Canon DSLR's with my students directly connected to OpenToonz.
> 
> While there is not an increment editor per say, the Function Editor does have a curve editor that might provide some of the functionality you are looking for.
> ![screen shot 2019-02-12 at 11 13 08 am](https://user-images.githubusercontent.com/21159116/52649915-37b4cf00-2eb7-11e9-9338-07a613162dec.png)

Thank you very much for your reply.  I'm glad to know that liveview reflex cameras are recognized. What strikes me is that in the AUR repositories of Manjaro (or Arch) webcams are recognized by Opentoonz, so I understand that there is something different in the code of those repositories. Something that, I suppose, could be transferred to snap. Maybe it has to do with some library, I don't know.  

The function editor is wonderful for regulating the timing of elements worked with the cut-out or motion graphics technique and it is, without a doubt, an excellent tool similar to those incorporated by its commercial alternatives. But... it cannot be applied to the taking of photographs frame by frame used in stopmotion, unless the elements are worked, for example, as if they were cut out puppets on chroma. 

I understand that my suggestion points to a characteristic that is not essential, but rather a luxury. But it's a luxury that most animators are used to and it's the only one that doesn't encourage them to use software other than Dragonframe. 

Greetings.

Translated with www.DeepL.com/Translator (I speak spanish).

**Comment by RodneyBaker** [comment]
Closing this as a feature request.
Discussion can of course continue here as well as in the Opentoonz forum.

Note1  There are a number of open items on @shun-iwasawa PR that still may be added.
See PR #1314 and other related PRs for more information.

Note2:  @turtletooth has implemented features related to stopmotion that bring the Canon DSLR API into Opentoonz.  See PR #2635 for more information.
