### ISSUE TITLE
Brush Issue on Toonz Raster/Vector Levels

### ISSUE THREAD

**Issue by xavzz** [opentoonz/opentoonz#2527]
Issue Summary
Brush and Eraser work fine on Raster Lvl. They will not work on other levels. The red dot underneath the stylus will not move when I press it and move on the display. When I stop drawing nothing happens but then suddenly a line appeared somewhere else. The tools work fine with touchpad.

System Information
OpenToonz Version: 1-2-0-3 Morevna Edition
Operating System: macOS Mojave 10.14.2
CPU: 2,6 GHz Intel Core i5
Memory: 8
Graphics Card: Intel Iris 1536
Graphics Tablet: Wacom Cintiq Pro 16

**Comment by manongjohn** [comment]
I would suggest installing the official OpenToonz 1.3 version and see if the issue still exists.

**Comment by xavzz** [comment]
I have an unfinished project and I am afraid I will lose some of the scenes installing the latest version.

**Comment by artisteacher** [comment]
Installing the latest version shouldn't impact existing scenes - there will be a new version of the stuff folder created, and the old stuff folder will be left alone. You can copy the project from the old project folder to the new project folder. Or if you've been using an alternate project location, you'll just need to re-enable that preference. If you do try the new release, make sure to delete your current OT app first.

The latest release still has issues, but is more stable on macOS than it was before. The raster brushes for Toonz Raster levels, and the editable text FX are definitely worth the update!

**Comment by xavzz** [comment]
I installed the latest version and it works well, none of the issues listed above are relevant anyway.

**Comment by artisteacher** [comment]
Great! It sounds like this issue can be closed then.
