### ISSUE TITLE
Keeping playback FPS scene based[feature request]

### ISSUE THREAD

**Issue by LalaGhost** [opentoonz/opentoonz#2529]
### Issue Summary
The FPS setting resets after reopening to 24 FPS.

### Screenshot or Video Reference
![screenshot_1](https://user-images.githubusercontent.com/43962138/53080453-0496bf00-34f9-11e9-9d3e-95bf00a14eee.png)

### Steps to Reproduce
Create a new scene, change the FPS settings to something different. Save scene, close the program, reopen the scene. The FPS setting is reseted to 24 FPS.

### Expected Results
I expected that the FPS settings will stay the same after reopening the scene.

### Actual Results
The FPS setting was reseted to 24 FPS.

### System Information
* **OpenToonz Version**: OpenToonz 1.3
* **Operating System**:  Windows 10
* **CPU**: Intel Core i7-5820K
* **Memory**: 4 x 4GB DDR4(so total 16GB)
* **Graphics Card**: Radeon R9 280X
* **Graphics Tablet**: Bamboo Pen & Touch

**Comment by gab3d** [comment]
but this Viewer control is intended only for ocassionally testing something at other frame speeds, if you want to have your scene always play at 14fps you should set it accordingly in the Xsheet > **Scene Settings...** dialog
