### ISSUE TITLE
bug regression: Create mesh preview window doesnt work in nightly build - pitch black

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#253]
Today's nightly build - create mesh window preview:
![createmeshbug](https://cloud.githubusercontent.com/assets/6495061/14835317/12e0eeb0-0c01-11e6-92dc-0a8b145e8397.JPG)

we get a pitch black in the preview window. This is a regression as the last build didnt have this bug

**Comment by tomosu** [comment]
This problem sometimes occurs, so reopend this issue.

**Comment by skitaoka** [comment]
The window can show previews by manually moving the separate bar of the center. We plan to fix this issue in future releases.

**Comment by blurymind** [comment]
@skitaoka the problem still occurs in 1.0.2
Tested today

**Comment by skitaoka** [comment]
Yes. We plan to fix this in future releases.

**Comment by blurymind** [comment]
thank you for fixing the mesh drawing issues in the viewport.

**Comment by Juls3000** [comment]
If you change the position and size of preview window it changes to white, and searchig you see the mesh but very small:

![cats](https://cloud.githubusercontent.com/assets/19145844/15049832/b1f5f2de-12f0-11e6-9086-c7cd3c3ec76b.jpg)

**Comment by blurymind** [comment]
The mesh preview window still does not work - its a persistent bug. It used to work in the very early builds.
