### ISSUE TITLE
Can't Set Shortcut Key to Locator Window

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#2531]
### Issue Summary
As far as I can see I cannot set a shortcut key to the **Locator** window, which is launched from the console play bar by clicking the magnifying glass icon.

### Expected Results
Should be able to set a shortcut key to the **Locator** window.

### System Information
* **OpenToonz Version**: 1.3.0r

**Comment by RodneyBaker** [comment]
Closing as a feature request.
Will be very appropriate to flag this during the UI scrub going into v1.4 release.

Aside:  I noted a speedup in recent OT release which has (to me) seemed to make drawing slightly more difficult in that I know note more jitter while drawing.  The Locator is a very useful tool for seeing this jitter up close.
