### ISSUE TITLE
Crash when applying the Eraser Tool (Frame Range) (gif).

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2538]
### Issue Summary

When creating a level, if the level was not created in the first Xsheet frame, or if the frames were shifted down and the animation in them was created using Vector Brush (Frame Range), then using the Eraser Tool (Ractengular, Freehand, Polyline) in Frame Range mode crashes the program.
### Screenshot or Video Reference

![ezgif-1-6cf27a6b42fb](https://user-images.githubusercontent.com/25724133/53642316-2ea75a00-3c3a-11e9-931e-ee33f1c3b8ba.gif)

### Steps to Reproduce

1. Create a new vector layer with several frames (not in the first frame).
2. Using Vector Brush with Frame Range, create a simple animation.
3. Use the Eraser Tool (Ractengular, Freehand, Polyline) in Frame Range mode to erase the lines.
4. The program will crash.

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Windows 8.1

**Comment by beeheemooth** [comment]
The program will not crash if you use the Eraser Tool (Frame Range) inside the Level Strip. Apparently this is somehow related to the location of the frames on the Xsheet, or to the mismatch of the frame numbers.
If you apply Autorenumber to frames on Xsheet, there will also be no crashes.
![ezgif-1-01fadb4f267d](https://user-images.githubusercontent.com/25724133/53643365-8646c500-3c3c-11e9-812c-f753edc8ba72.gif)

**Comment by RodneyBaker** [comment]
Just adding a note...

The Frame Range feature appears to have been originally designed only to work with the Level Strip.  It therefore doesn't catch errors outside of that context.
