### ISSUE TITLE
[Question] Algorithm for Raster to Vector

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [opentoonz/opentoonz#2542]
As this issue was a question so I avoided the template.
I am working on an open source software and I wish to implement raster to vector conversion. On searching, I came to know that there is no developer documentation for opentoonz :(
I was reading the code to get some idea on it and I appreciate If someone here tells me about the algorithmic approach used in this process.
Thanks :)

**Comment by ankit-kumar-dwivedi** [comment]
closing this as i got my answer :)

**Comment by RodneyBaker** [comment]
@ankit-kumar-dwivedi 

I'd love to know more about what you discovered!

**Comment by ankit-kumar-dwivedi** [comment]
@RodneyBaker I got the file structure using git grip but I'm still struggling to find where the exact algorithm resides. 
:disappointed:

**Comment by ankit-kumar-dwivedi** [comment]
@RodneyBaker any help is appreciated !
