### ISSUE TITLE
Vector guided drawing does not work correctly

### ISSUE THREAD

**Issue by einfachfelixverdammt** [opentoonz/opentoonz#2547]
if i try to redraw a frame with vector guided drawing often times the program seems to "forget" about some of the previous lines. 

f.e. i draw a simple drawing with four lines:
it usually gets the first line right.
the second line is suddenly split into 2 or more different vectors.
the 3rd line wont be shown
the fourth line is normal again, but if i generate inbetweens the vector turns around / changes directions.

sometimes if i hit ctrl+z and redraw previous vectors it suddenly works again...
[video.zip](https://github.com/opentoonz/opentoonz/files/2930551/video.zip)
in this videos you can see what i mean

my drawing settings are:
size: 2.02 - 3.64
accuracy: 9.43
smooth: 0
break: true
pressure: true
range: off
snap: false
preset: custom

draw 2 drawings with vector guided drawing enabled. 

inbetweening wont work correctly and vectors wont be shown correctly

### System Information
version 1.3
windows 10
AMD FX 6300
8GB RAM
?
xp pen artist 22 hd

**Comment by beeheemooth** [comment]
@einfachfelixverdammt  At the edge of your first video, I see that the "Break" option is turned on - turn it off and the vector will not be divided into parts where a solid vector forms a more or less acute angle.

**Comment by RodneyBaker** [comment]
@einfachfelixverdammt  A follow up here...
Did you have any luck figuring out the issue with vector guided drawing?

**Comment by RodneyBaker** [comment]
Closing as abandoned and/or likely resolved.
@einfachfelixverdammt Please let us know if you are still experiencing any problems.
