### ISSUE TITLE
RGBA Cut FX setting has wrong label

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2548]
### Issue Summary

The tab inside the RGBA Cut FX setting is still written as RGBM Cut
### Screenshot or Video Reference

![screen shot 2019-03-08 at 10 58 03 am](https://user-images.githubusercontent.com/21159116/54039597-54c87f00-4191-11e9-85a5-81a2bb726bd6.png)

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
Note:  There are some 77 references to RGBM in the source:

https://github.com/opentoonz/opentoonz/search?q=RGBM&unscoped_q=RGBM

**Comment by artisteacher** [comment]
Most of those look to be just the name on the code end of things - not anything that actually displays. The only other thing that looks like it might have been left out is:

<img width="785" alt="Screen Shot 2019-03-09 at 9 03 18 PM" src="https://user-images.githubusercontent.com/21159116/54079673-f1347380-42ae-11e9-9b95-184841a85239.png">
