### ISSUE TITLE
Crash when dragging to switch ports on Particles node

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2552]
Found by Gab3d
https://github.com/opentoonz/opentoonz/issues/2550#issuecomment-471331016

Repro Steps:
1. Create a Particles node
2. Create a node of any type and connect it to the Particle node's Texture input
3. Click and drag the Texture port to the Source port - this is supposed to switch the inputs

The connection line will be frozen in place and shortly after, OT will crash

Visual example:
![Swizzle Crash](https://user-images.githubusercontent.com/42905003/54090807-1f2dbc80-4370-11e9-9934-443b4549daca.gif)

**Comment by manongjohn** [comment]
I can duplicate the frozen line and the crash, though it crashes only when clicking in the empty space then trying to do a box selection to select the 2 nodes.

I can put in a fix to prevent the crash due to a null pointer access.  The issue of the disappearing link will likely be a separate fix.
