### ISSUE TITLE
OT deletes psd files on save command

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#2556]
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by bobbybutterfly** [comment]
referring to closed #1213 issue
this serious bug persists and is not resolved!

just happened to me. Psd file deleted from disk!
Opentoonz 1.3
loaded level as frames (psd layered file located in projects "extras" folder)
changed the file in photoshop and saved it
back in Opentoonz "save scene"
OT asks:
Quit: the following files have been modified
blabla#frames.psd What would you like to do?
save changes (psd file is now deleted from folder and disk)
quit anyway (psd file stays in folder)
 
save all command also deletes psd files you worked with

**Comment by shun-iwasawa** [comment]
Confirmed the problem. I'll look into it. Thanks!

**Comment by shun-iwasawa** [comment]
@bobbybutterfly 

> changed the file in photoshop and saved it
> back in Opentoonz "save scene"

Did you run `Reload` command between the above two steps?
If yes, I found a probable cause of the problem.

**Comment by bobbybutterfly** [comment]
@shun-iwasawa 
yes, i used the reload command e few times until i realized, that it is not neccessary.
if i move a drawing substitution cel in the time line, OT reloads automatically and the altered picture is updated (and visible in the viewer), as soon as you drag the cel,
and, of course, in both cases of reloading the file will be deleted

**Comment by RodneyBaker** [comment]
This seems to vaguely relate to #2363.
