### ISSUE TITLE
Alpha strokes issue with PNG render

### ISSUE THREAD

**Issue by ricolandia** [opentoonz/opentoonz#2561]
### Issue Summary

As I have published on Discord, an issue apeared with the rendering png files. I do not know if you have seen this before. 

The lines I've used the alpha for the strokes are "buggy" when rendered.
All the strokes with 100% alpha( to hide then) are like this:

### Screenshot or Video Reference

[Link to Image file](https://www.ricolandia.com/wp-content/uploads/2019/03/test.jpg)

### Steps to Reproduce

Some strokes( guides or color division strokes ) with 100 alpha are rendered with this issue in PNG ( image sequence ). A screenshot:
[Link to opentoonz screenshot](https://www.ricolandia.com/wp-content/uploads/2019/03/Captura-de-tela_2019-03-12_18-33-48.png)

### Expected Results

These strokes are rendered with this issue showed with the image above.
### Actual Results

The solution was to render the image sequences( for all scenes ) in Tiff format. Suggested by manongjohn and RAHBOOTS on Discord! Thanks!
### System Information
* **OpenToonz Version**:  OT 1.3
* **Operating System**: Xubuntu 18.04
* **CPU**: core i5
* **Memory**: 4GB
* **Graphics Card**: Intel Graphics
* **Graphics Tablet**: Wacom one

**Comment by RodneyBaker** [comment]
Just to check...

Are you rendering to 8bit PNG?
There are known issues with the 8bit PNG format that have not yet been addressed.

**Comment by ricolandia** [comment]
Hi, @RodneyBaker .
I do not have many options via Linux. I just have PNG and : with alpha or without. 
For now, it's ok to render in TIFF. Thanks!

**Comment by RodneyBaker** [comment]
In Windows there is an option for 'Channel Width' that allows for 8 and 16 bit.
That option should be there for Mac and Linux as well.
Perhaps not but worth looking for should the need for PNG ever arise.

Glad to hear TIFF is working well for you.
That's a good format to work with.

**Comment by RodneyBaker** [comment]
Leaving this open for now as perhaps someone can reproduce the problem and share additional information.

**Comment by artisteacher** [comment]
I'm not seeing this happen in macOS so far. In the meantime, you could try using zero-thickness lines to separate color regions when you want png.

**Comment by RodneyBaker** [comment]
@ricolandia If you are still monitoring this issue there are two PNG files in the other report (#242)that can be tested.  The 8bit PNG should be expected to render incorrectly while the other should render correctly.

As for this report...
Workaround that resolved the surface problem was to use another image format.
It will be good to resolve the underlying issue if/when we can reproduce the problem.

We don't like to close reports where the reporter isn't satisfied with the outcome so let us know if you continue to experience problems.

**Comment by RodneyBaker** [comment]
Closing as resolved via a workaround with not enough information to investigate any deeper problem.
Noting that the user originally had problems with use of alpha channel with PNG image format on Linux platform.

@ricolandia Please let us know if you can provide any additional information.
