### ISSUE TITLE
brush lag

### ISSUE THREAD

**Issue by abysspop** [opentoonz/opentoonz#2562]
I have a huge problem with openToonz.
the tool bush lag as hell!
smooth is to 0, and my graphic tablet is an old faithful Silver Crest.
I really need help, it is pretty handicapping....

**Comment by manongjohn** [comment]
What os are you on? What video card do you have?

**Comment by RodneyBaker** [comment]
Closing this as no additional information has been added since March.
This may be a good topic to explore in the Opentoonz forum 'Troubleshooting' category.
Once additional information is collected the problem can then be addressed.

@abysspop 
Do you have any more information to add to the issue?
