### ISSUE TITLE
16bit Plastic render duplicated in green

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2563]
### Issue Summary

In the output settings, if you change the channel from 8bit to 16bit, plastic modified levels are duplicated in the render and display incorrectly in green. I've seen this in .mp4, .gif, and .tif but haven't checked other formats yet.
### Screenshot or Video Reference

Preview:
<img width="685" alt="Screen Shot 2019-03-13 at 6 25 29 PM" src="https://user-images.githubusercontent.com/21159116/54318746-b176d000-45bd-11e9-8859-00fedb591f6b.png">
Render:
<img width="685" alt="Screen Shot 2019-03-13 at 6 26 24 PM" src="https://user-images.githubusercontent.com/21159116/54318750-b471c080-45bd-11e9-8a0f-8b638b4b4b80.png">

### Steps to Reproduce

1. Use the plastic tool to add basic movement to a level (don't use any green so the color distortion will be obvious)
2. In the Output Settings, change the channel from 8bit to 16bit
3. Render
### Expected Results

Only one occurrence of the plastic modified level & for colors to display as they do in preview
### Actual Results

Green double vision! Non-plastic levels display normally.
### System Information
* **OpenToonz Version**: Latest nightly build
* **Operating System**: macOS Mojave & High Sierra
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
I've tested several more formats - .jpg, .nol, .bmp & .webm and they all have this issue.

**Comment by RodneyBaker** [comment]
I'm not able to duplicate this on Windows so am wondering if this is only related to Mac and/or Linux.
I'm not entirely sure I tested correctly and thoroughly enough so more testing is needed.

Also:  There is a known issue with artifacting with 8bit PNGs but that doesn't appear to be closely related to this issue.

**Comment by artisteacher** [comment]
A lot of the issues with plastic rendering have been specific to Mac & Linux, so I wouldn’t be surprised if this isn’t a problem for Windows.

**Comment by artisteacher** [comment]
This is an issue with macOS Catalina as well.

**Comment by ABadShow** [comment]
I can verify that problem exists on Windows 10 64bit as well.  Running a brand new installation of OpenToonz v1.4 64bit.  Tried extracting as avi, mp4, and png.  Non-messed elements render normally.

My Render Settings:
1920x1080
Resample Balance: Improved
Channel Width: 16
(All other Settings Left as Default)

Setting the channel width back to 8 renders everything normally.  So, it looks like that's what I'm going to roll with.

Thanks for an awesome program!
