### ISSUE TITLE
Crash when deactivating Pixels Only option.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2565]
### Issue Summary
I´ve got a consistent crash when trying to disable the **Pixels Only** option (that gets activated when chosing pixels as units of measure).

The catch is that it happens when using the UI in certain languages (but not all of them).
*Good*: English, Deutsch, Japanese
*Crash*: all others...

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Windows (any)

**Comment by RodneyBaker** [comment]
@gab3d @martinvanzijl 
Did this issue ever get addressed?
I see references to the issue and the (unmerged) commit.
I cannot reproduce the crash but have not investigated very deeply.

**Comment by gab3d** [comment]
The crash is gone for me. 👍

**Comment by RodneyBaker** [comment]
Thanks @gab3d 
Closing

**Comment by martinvanzijl** [comment]
@RodneyBaker Yes, this was fixed in a different PR, so I closed my branch. Thanks for checking.
