### ISSUE TITLE
Some windows cannot adapt to show extra settings.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2566]
### Issue Summary
1. While using OpenToonz UI in any other language than English, the **Output** settings window can't correctly show the **Other Settings** section.
(i.e. it can't seem to correctly accomodate the extra content in the available space, or expand the window)
If the window bottom border is manually expanded, the settings finally get to show correctly.

2. This same problem happens also in the File > Convert... options window, when trying to convert to TLV (this time it happens even in English).

### Screenshot or Video Reference
![output](https://user-images.githubusercontent.com/18104091/54466508-d22a5b80-475e-11e9-9b00-b1b3b98b0150.png)
![convert](https://user-images.githubusercontent.com/18104091/54466515-d5bde280-475e-11e9-9e2d-563a07a3d866.png)

Windows (any)
OpenToonz 1.x

**Comment by artisteacher** [comment]
I have a similar issue on a MacBook Pro with a smallish, lower resolution screen - with English. If I minimize the Camera settings, then there's enough room to see the other settings.

**Comment by RodneyBaker** [comment]
There are still a few more popups/dialog windows that have the scaling issue.
I ran across one some time ago in a seldom used location but forgot to make note of it.
Two popups that initially might appear to scale correctly but won't if resized are:

Level Settings (opened from any location... scale the vertical height of the window and the text fields should all meld together)

Clean up window

![Dialog Field Scaling Level Settings Popup (multiple places)](https://user-images.githubusercontent.com/2576432/63320409-4c997180-c2e3-11e9-9d3a-08af0b9c054d.jpg)
![Dialog Field Scaling Cleanup popup](https://user-images.githubusercontent.com/2576432/63320408-4c997180-c2e3-11e9-818a-6aaf23bf5eef.jpg)

**Comment by RodneyBaker** [comment]
I was looking in the LESS/QSS to see if any of these spacing issues might be resolved there but it seems to me those elements are hard coded.

Can anyone point to the location/example for UI window/field scaling settings?
I'll find them eventually but perhaps someone that already knows can point us there.

**Comment by artisteacher** [comment]
Also the function editor & etc. in #1078.

**Comment by RodneyBaker** [comment]
Thanks @artisteacher 
A previous fix by @turtletooth suggests to me that some of this (if not all) can be resolved by adjusting the LESS files.  If that is the case then... good news.

**Comment by artisteacher** [comment]
On a related note, the Tool option bar, especially when the Plastic tool or Select tool (with vector level settings) are active, can have a lot of horizontal clipping issues. The All mode of the Animate tool behaves differently then the rest - tool options display full size & you use an arrow at the end to show/hide additional tool options that won't fit within the window size. That behavior would be better than the extreme clipping that happens now on smaller screens. Personally I prefer the behavior in Blender's properties panel. If there is not enough room for all of the property tabs to display, scrolling moves them in/out of view. A fusion of the 2 behaviors might be best.

**Comment by RodneyBaker** [comment]
It's looking like most of the cosmetic UI issues will very likely slip into 2020 development cycle but... there is time to get many into v1.4.  The good news is that we are closing in on all the various UI display issues and it's just a matter of time before they are resolved.

If there is anyone up to the task it might be ideal to write down a list of the various UI clipping/scrolling issues and then do a run through with video/screencapture highlighting each in turn.  Yes there are open reports on many of them but the various reports aren't unified... yet.

@artistteacher  How do we get 'bug reporting' added to the curriculum for your students.  They all need to know how to document and report issues no?  (kidding  I think!).  :)

**Comment by gab3d** [comment]
There should be a **Report a bug...** entry in the Help menu.
...there should also be a **Donate...** entry in the Help menu, as well.

If our release cycle has 1 year, *now* is the time to think of what we want for the next year.
Do we want to make it easier for people to report bugs?
Do we want to make it easier for people to donate money to have more resources for development?
If we don't have a standardized way of receiving donations setup yet (which we don't), then we could link to a temporary **Donations page** in the official website, and then think of how to handle it, but we should include the link in 1.4, if we want it to have effect during 2020.

I think those are super easy actions we can take now to help improve the interaction with users. 🤔 

For reference, this is how Blender handles these things inside the app. For us the Help menu seems to be the place for such kind of things, but the important thing is to somehow raise visibility inside the program:
![imagen](https://user-images.githubusercontent.com/18104091/70850274-3a7da900-1e67-11ea-8878-41efdf2adf5e.png)
![imagen](https://user-images.githubusercontent.com/18104091/70850254-0c986480-1e67-11ea-99be-4a91b6274896.png)
![imagen](https://user-images.githubusercontent.com/18104091/70850144-b971e200-1e65-11ea-9b79-8cae52bbf950.png)

**Comment by RodneyBaker** [comment]
The topic has been brought up a few times.
Here's a recent iteration in the OT Forum:  [LINK](https://groups.google.com/forum/#!category-topic/opentoonz_en/general-discussion/VAZ2gygoynM)

**Comment by gab3d** [comment]
> A decision on whether to continue to point people to the OT Forum versus link to github will likely need to be made.

I think for bug reporting, GitHub Issues should be the correct place to land.
Perhaps we could also include another entry in the Help menu that reads something like **User Community** (like Blender also has in its Help menu) linking to the Google Forum?

I know for donations to really happen, a system has to be in place, and that is not so easy. 
**But**, sometimes decisions have to be made in a timely manner. 
If we do not include it in 1.4, we'll have to wait a full year trip to be able to do something about it. 
On the other hand, if we manage to include it in time for 1.4 (even using some link to a temporary "work in progress" page), then I know we could make it work in much less than a year, if nothing else because I bet people will start to poke on us to make it work to be able to effectively donate. 😄 
The worst case would be what? A donations page that doesn't allow to donate? IMO that's not worse than not having a **Donate...** link. The net result would be the same, with the difference that whenever we manage to get it working, people could instantly arrive there from 1.4

**Comment by RodneyBaker** [comment]
> ,,,If we do not include it in 1.4,,,

Last minute additions are always controversial and stressful...  ;)

A reasonable beginning would be to create a landing page in the documentation; a 'Support Opentoonz' page with a link to it via Help Menu.  Initially that page could point to current links such as:

- Developers github information
- Build Testing information (github)
- Opentoonz BountySource page

A bug reporting page could also be created via documenation and highlight:

- Opentoonz Troubleshooting Forum
- Opentoonz Feature Request Forum
- Github Bug Reporting

If these two pages exist it will be trivial to add the links to the pages.

I would suggest that intially rather than 'Donations' the terminology of the Link be 'Support Opentoonz" because while money is very important there are many ways in which the Opentoonz Community can show their support.  Then as the support infrastructure is established for finanaces the link can be updated.

We are off topic so this likely should be discussed in a more obvious location.  :)

**Comment by gab3d** [comment]
I totally agree with that plan. 👍

**Comment by gab3d** [comment]
@shun-iwasawa could we have something like that?

**Comment by RodneyBaker** [comment]
I've opened a 'ticket' for the 'Support Opentoonz' page in the docs repo:

https://github.com/opentoonz/opentoonz_docs/issues/90

**Comment by RodneyBaker** [comment]
Similar request opened for  landing page for 'Report Bug' link:

https://github.com/opentoonz/opentoonz_docs/issues/91

**Comment by gab3d** [comment]
:clap: :clap: :clap:
