### ISSUE TITLE
Tablet pen input cursor

### ISSUE THREAD

**Issue by andeon** [opentoonz/opentoonz#2569]
I originally opened here: https://github.com/morevnaproject/opentoonz/issues/19 but I found more details about this problem and also here is the correct place to report this.

### Issue Summary
When you move / focus the cursor out of the drawing area with the tablet, it changes the cursor depending on where the cursor is pointing. It returns the correct if you point to the "locator" window,  use the mouse or the touchpad, sometimes press the shift or ctrl keys, and if have a window detached like toolbar and move cursor in front of this.

And I noted that the right click of the pen does not work as reported here https://github.com/opentoonz/opentoonz/issues/1790

I tested the version appimage 1.1.3 (https://sourceforge.net/projects/opentoonz-morevna-edition/files/stable/1.1.3/) and it really has no problem with cursor tablets, I did not find this version here to test, but I know they use the same master code, then. I'm not sure now which release this broke.

It's not just a visual cursor problem, I recorded a video, tools like "**Magnet**", "**Tape**" lose functions and generally work only if you click the mouse or the touch pad, then the tablet works another time with these tools, well until you move again the cursor out of the drawing area.

### Screenshot or Video Reference

Click to watch the video:

[![](http://img.youtube.com/vi/FApN4vil0QY/0.jpg)](http://www.youtube.com/watch?v=FApN4vil0QY "")
http://www.youtube.com/watch?v=FApN4vil0QY 
### Steps to Reproduce

With the graphics tablet just open the program and start painting, move the cursor out the drawing viewer. Back to drawing viewer to paint or switch to another tool, look that the cursor does not back to the correct state.

ps: Krita developers have frequent problems with MacOs versions, they may be related and you can help each other. Since you are using similar tools for development.

### System Information
* **OpenToonz Version**: 1.3, 1.2.0.3
* **Operating System**: Linux 64 bits (Kde Neon)
* **CPU**: Intel core i7-7500U
* **Memory**: 8GB
* **Graphics Card**: Nvidia
* **Graphics Tablet**: Wacom Intuos Draw CTL490DW, Genius MousePen 8x6 (UC-Logic Tablet WP8060U)

**Comment by artisteacher** [comment]
This looks like it's related to known issues: #1951, #1796 and #1679.

**Comment by andeon** [comment]
The issue is gone with this fix https://github.com/opentoonz/opentoonz/pull/4860, thanks!
