### ISSUE TITLE
Snap version on Lubuntu: FFmpeg path not recognized

### ISSUE THREAD

**Issue by its-thomas** [opentoonz/opentoonz#2578]
### Issue Summary
According to the output of the terminal command `which ffmpeg`, the path to FFmpeg on my Lubuntu 16.04 system is `/usr/bin/ffmpeg`. So OpenToonz v.1.3 (snap version via [https://snapcraft.io/opentoonz](https://snapcraft.io/opentoonz)) should recognize the FFmpeg Path `/usr/bin` entered under File -> Preferences -> Import/Export. But unfortunately, it is not recognized and so the option "Fast Render to MP4" tells me: "FFmpeg not found, please set the location in the Preferences and restart."

I also have OpenToonz (Morevna Edition) v.1.3 installed as an AppImage from [https://sourceforge.net/projects/opentoonz-morevna-edition/files/stable/1.3.0/](https://sourceforge.net/projects/opentoonz-morevna-edition/files/stable/1.3.0/) and here, the FFmpeg Path `/usr/bin` is recognized without any problems and the option "Fast Render to MP4" works. So, I assume there is an issue specifically with the snap version from [https://snapcraft.io/opentoonz](https://snapcraft.io/opentoonz).

### System Information
* **OpenToonz Version**: 1.3 (snap version via [https://snapcraft.io/opentoonz](https://snapcraft.io/opentoonz))
* **Operating System**: Lubuntu 16.04 LTS

**Comment by artisteacher** [comment]
At least on a mac, I have to make sure that I’ve selected the parent directory of the ffmpeg files (ffmpeg, ffprobe...).  So if usr/bin/ is the path where your ffmpeg files are contained, then there’s definitely something wrong. On the other hand, if usr/bin/ is the parent directory of your ffmpeg directory, then you’d need to use usr/bin/ffmpeg/ as the path (assuming that the ffmpeg parent directory is called ffmpeg).

**Comment by its-thomas** [comment]
@artisteacher `/usr/bin` is the parent directory of the ffmpeg file. Otherwise the path `/usr/bin` wouldn't work on OpenToonz (Morevna Edition) v.1.3 either.

**Comment by artisteacher** [comment]
In that case, maybe @pixelr0 can help.

**Comment by manongjohn** [comment]
Try copying the ffmpeg executable to the same location as the OpenToonz executable.

When OpenToonz cannot find the ffmpeg executable in the directory specified in Preferences, it does try to look in the same folder as the OpenToonz executable.

I confirmed this works in Windows.

**Comment by its-thomas** [comment]
@manongjohn I would try your suggestion, but to me, it's not really clear where the OpenToonz executable is located. With a snap installation in Ubuntu, it's not as easy to check as it is in Windows...

**Comment by manongjohn** [comment]
I think its might be found here: /opt/opentoonz/bin

**Comment by its-thomas** [comment]
@manongjohn Unfortunately, there is no opentoonz-folder in `/opt` on my system.

**Comment by manongjohn** [comment]
I confirmed this is an issue with the snap and how it works with Ubuntu's AppArmor security settings. 

I moved the ffmpeg to a directory that opentoonz should have been able to read and execute it from, but AppArmor blocked it.  I also temporarily removed all AppArmor profiles and reenabled snapd to "complain" mode and verified it worked fine after that.

This needs to be addressed with the original snap creator. They need to do something with the AppArmor profile as part of the snap for opentoonz to allow it to see and run the ffmpeg executable where they have it. 

As this is not an OT issue, I am closing it.

**Comment by its-thomas** [comment]
@snapcrafters, as the creator of the OpenToonz snap image, you may want to have a look at this thread.

**Comment by Sentoki** [comment]
Hi all. Is this problem still not solved?

**Comment by manongjohn** [comment]
This is a snap or snap configuration issue, not an OT issue.

**Comment by Sentoki** [comment]
> This is a snap or snap configuration issue, not an OT issue.
> 
> Edit: we do not maintain the snap.

Understood! So I will try build it.

**Comment by manongjohn** [comment]
@Sentoki You might want to download the OTX version. It's a portable version of OT (with some additional stuff). There is a Linux version in the form of an AppImage you can use.

**Comment by MagmaBois** [comment]
Mine still not working

**Comment by blazfemo** [comment]
download FFmpeg Static Builds from 

https://johnvansickle.com/ffmpeg/

unzip and put on an accessible path.
change the FFmpeg in opentoonz, restart and enjoy

**Comment by VinceFINET** [comment]
I have the exact same issue on my Ubuntu with all new upgrades. Is the last post the solution really or an update is coming soon...? Thank you

**Comment by VinceFINET** [comment]
Hi all just to come back to you about this issue

The new version of the snapcraft opentoonz has a fix about this, thanks to @popey

Please refer to https://github.com/opentoonz/opentoonz/issues/3688 and https://github.com/snapcrafters/opentoonz/issues/9

Remember to update the snap if already installed with `snap refresh opentoonz`
And set the path of FFmpeg in preferences to `/snap/opentoonz/current/usr/bin`
