### ISSUE TITLE
Opentoonz crashes at startup on Windows 10

### ISSUE THREAD

**Issue by MilodeCreta** [opentoonz/opentoonz#2584]
### Issue Summary

Opentoonz crashes at startup on Windows 10. Sometimes it doesn't crash at the beginning until I tried to create a scene or open an old one and it crashes again.

###Image File
![Sem título](https://user-images.githubusercontent.com/49213552/55440093-02566480-557d-11e9-9792-3b7e9e960673.png)

### Expected Results

The program must open correctly and stops crashing.

### Actual Results

It isn't working properly. 

### System Information
* **OpenToonz 1.3**: 
* **Windows 10 64 bits**: 
* **Intel Pentium E2180**: 
* **6,00GB Dual-Channel DDR3 @ 399MHz (6-6-6-15)**: 
* **Intel G41 Express Chipset (Gigabyte)**:

**Comment by MilodeCreta** [comment]
Please guys! Help me!

**Comment by manongjohn** [comment]
Did you just recently upgrade? What version were you using before?

Can you look in the Windows Event Viewer and look for an Application crash log for OpenToonz.exe at the time of the crash. It may offer some insight into why it is crashing.

**Comment by artisteacher** [comment]
Sometimes a clean install can help if there's a problem after updating. It might be worth uninstalling OT and renaming the stuff folder before running the install again. If it works, you'd need to update your preferences and possibly move old projects or etc. back into the new stuff folder (unless you've been using an alternate project location).

**Comment by MilodeCreta** [comment]
> Did you just recently upgrade? What version were you using before?
> 
> Can you look in the Windows Event Viewer and look for an Application crash log for OpenToonz.exe at the time of the crash. It may offer some insight into why it is crashing.

I just recently upgraded. I was using Windows 7 before but the same crash was happening. It was the main reason I upgraded to Windows 10. 

I am going to look in the Windows Event Viewer later (I am at work right now) and report it here asap.

Thanks!

**Comment by MilodeCreta** [comment]
> Sometimes a clean install can help if there's a problem after updating. It might be worth uninstalling OT and renaming the stuff folder before running the install again. If it works, you'd need to update your preferences and possibly move old projects or etc. back into the new stuff folder (unless you've been using an alternate project location).

I've already tried to install in different locations unsucessfully but I haven't tried to rename the folder yet. I'll give it a try. Thanks!

**Comment by manongjohn** [comment]
I was more wondering what OT version you upgraded from using before 1.3?

Can you still run the prior OT version you were using?

It's interesting to know that you did have this problem on Win7 and Win10 though. I'm assuming you upgraded the same machine from 7 to 10 or did you also get a new machine?

**Comment by MilodeCreta** [comment]
> ``

> I was more wondering what OT version you upgraded from using before 1.3?
> 
> Can you still run the prior OT version you were using?
> 
> It's interesting to know that you did have this problem on Win7 and Win10 though. I'm assuming you upgraded the same machine from 7 to 10 or did you also get a new machine?

I always used the 1.3 OT version and the morevna one. It was working with minor bugs in other machine with Windows 7 before the PC stopped working, It's an old "new" one. In this one, the 1.3 OT version has never worked.

**Comment by manongjohn** [comment]
Do you know what video card you have? Make sure the driver is up-to-date for Win10.

**Comment by MilodeCreta** [comment]
> Do you know what video card you have? Make sure the driver is up-to-date for Win10.

I am not using a GPU off board. I"m using the Intel G41 Express Chipset. Can it be the problem? Do I need to have an off board graphic card?

**Comment by manongjohn** [comment]
No. It's not required. I just suggested it just in case, because i've seen similar crashes on win10 due to video drivers. Granted, I recall other crashes on Win10 because it either updates or delete's something that somehow impacts OT. We'll have to see if the event log points to anything in particular.

**Comment by MilodeCreta** [comment]
> Did you just recently upgrade? What version were you using before?
> 
> Can you look in the Windows Event Viewer and look for an Application crash log for OpenToonz.exe at the time of the crash. It may offer some insight into why it is crashing.

Here it goes:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-04-03T20:25:40.748453500Z" /> 
  <EventRecordID>1873</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Leadership</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>OpenToonz.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ca2b8da</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000000000</Data> 
  <Data>1b7c</Data> 
  <Data>01d4ea5b5b3c7762</Data> 
  <Data>D:\OpenToonz\OpenToonz.exe</Data> 
  <Data>unknown</Data> 
  <Data>01dbcad8-9e28-48e9-b0b7-2956b624297a</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by MilodeCreta** [comment]
> Sometimes a clean install can help if there's a problem after updating. It might be worth uninstalling OT and renaming the stuff folder before running the install again. If it works, you'd need to update your preferences and possibly move old projects or etc. back into the new stuff folder (unless you've been using an alternate project location).

I've tried to install in a different location and I've also changed the folder's name but the issue persists.

**Comment by MilodeCreta** [comment]
> Do you know what video card you have? Make sure the driver is up-to-date for Win10.

I've verified the situation of the drivers and the result is: all of them are up-to-date.

**Comment by MilodeCreta** [comment]
More informations:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-04-03T22:13:38.565782400Z" /> 
  <EventRecordID>1993</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Leadership</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>BEX64</Data> 
  <Data>Não disponível</Data> 
  <Data>0</Data> 
  <Data>OpenToonz.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ca2b8da</Data> 
  <Data>StackHash_ac46</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>PCH_47_FROM_ntdll+0x00000000000A01C4</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000000008</Data> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER305E.tmp.mdmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3233.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3263.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3261.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER32A1.tmp.txt</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OpenToonz.exe_fe134165ae6c11433de2d4398cad5c790d1f47e_dc42dc10_08763714</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>e97fd891-40bd-4308-abb4-2e332d64e473</Data> 
  <Data>97</Data> 
  <Data /> 
  <Data>0</Data> 
  </EventData>
  </Event>

More yet:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-04-03T22:14:26.556781200Z" /> 
  <EventRecordID>1994</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Leadership</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>OpenToonz.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ca2b8da</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000000000</Data> 
  <Data>1694</Data> 
  <Data>01d4ea6a7ef78a58</Data> 
  <Data>C:\Program Files\OpenToonz\OpenToonz.exe</Data> 
  <Data>unknown</Data> 
  <Data>57151294-e14f-4e50-bb57-a252515b1069</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by MilodeCreta** [comment]
Anyone?

**Comment by manongjohn** [comment]
From what I can tell from that log, it's failing due to BEX64 error in module "StackHash_ac46". 

Looking on-line there are a number of people who have encountered this on other applications, so it's not specific to OT.  One suggests it might be due to anti-virus.   Try disabling any anti-virus software you have running and see if that still happens?

If not, it's something else on your system that's causing this.  Look online to see how others have handled this particular error and see what fixes it.

If you find out, please let us know in case someone else runs into it.

**Comment by artisteacher** [comment]
Sorry, I can only semi understand MacOS crash reports. They usually specify what thread crashed & the processes that were triggered leading up to the crash. Is that the entire crash log? If not, you might want to copy the entire log & paste it into a text document to add here.

**Comment by konero** [comment]
@MilodeCreta That's a very old machine you have, I can't remember the last time I see LGA 775, 2005? The Intel G41 Express Chipset is not supported on Windows 10. Even the LGA 1155 (2600K) iGPU is not supported on Windows 10, the CPU runs fine but it needs a discrete GPU.

You can try another GPU if you got one spare. I'd also recommend activating Windows.

**Comment by MAX-RAY** [comment]
I think your problem from your GPU because when I uninstall my GPU driver I cant run OT (crash when start up).
I think opentoonz use "opengl" so make sure u install ur GPU working.

**Comment by RodneyBaker** [comment]
@MilodeCreta Are you still experiencing issues running Opentoonz on your system?

For troubleshooting of specific setups this topic may be more appropriate for the Opentoonz forum's Troubleshooting section. 

Link:  https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting

You might also be interested in live discussion via chat on the Opentoonz discord where other users can work with you in real time to resolve setup with your specific computer.

Opentoonz discord (chat):  https://discord.gg/N7UTVjs

Keeping this issue open for now due to its report of crashing.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@MilodeCreta Please let us know if you are still experiencing this issue.

**Comment by lectura** [comment]
Am experiencing the same problem with windows 10, any lead?

**Comment by RodneyBaker** [comment]
The most likely solution to startup issues is to perform a clean install with a recent release.
If you need download links please let us know.

**Comment by lectura** [comment]
Thank you l. I did uninstall and deleted the entire folder. I have also realized in vector level when you want to pick color it crushes again but i have opted to saving after every three minutes to avoid loss of data.Thank you.

Sent from Yahoo Mail on Android 
 
  On Sun, 15 Dec 2019 at 17:50, Rodney<notifications@github.com> wrote:   
The most likely solution to startup issues is to perform a clean install with a recent release.
If you need download links please let us know.
