### ISSUE TITLE
Will I get a virus if I download GTS??

### ISSUE THREAD

**Issue by YEEmeme** [opentoonz/opentoonz#2587]
### Issue Summary

download from the official website

By the way, in gts.exe, the word "gen: transformation."Rash.468146" came out.

Please help me solve the problem.

### Screenshot or Video Reference

 https://ibb.co/VY3NgLx

 https://ibb.co/CVWwMBy

 https://ibb.co/bbWkWgp

 https://ibb.co/Qmg6nwB

### Expected Results

We've been running a vaccine program for you since the virus broke out. 

Each time it was done, the virus came out. 

### Actual Results

The virus disappears and the safe use of a program called GTS. 

### System Information
* **OpenToonz Version**: Download to Official Site around March 2019.
* **Operating System**: Windows7 64-bit。
* **CPU**: 
* **Memory**: 8192MB RAM
* **Graphics Card**: Intel 
* **Graphics Tablet**: Wacom

**Comment by artisteacher** [comment]
I think you actually need to report this issue at the [GTS repository](https://github.com/opentoonz/GTS/issues).

**Comment by konero** [comment]
Just for the record, I also ran into GTS being detected as malware at work. The engine they use is Emsisoft or Sophos.

**Comment by RodneyBaker** [comment]
Closing as this relates to GTS.
