### ISSUE TITLE
OS10.11.3: broken preview image in plastic tools

### ISSUE THREAD

**Issue by tomosu** [opentoonz/opentoonz#259]
Preview image goes broken in the operation reported in https://github.com/opentoonz/opentoonz/issues/254 ,on Mac OSX.

**Comment by artisteacher** [comment]
If this is about the black preview, that is no longer an issue. Though preview/rendering is still pretty broken with the plastic tool in mac os and linux -  #780 #939 #856 #533 and #1096 which all look like variations of the same issue.

**Comment by artisteacher** [comment]
This is now working with the latest nightly build and OS X 10.13!

**Comment by artisteacher** [comment]
This is resolved, recommend closing.
