### ISSUE TITLE
Locator button crash with Toonz raster

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2592]
### Issue Summary

Clicking on the viewer's locator button causes an immediate crash, if there is a toonz raster level in the scene.
### Screenshot or Video Reference

[locator_crash.txt](https://github.com/opentoonz/opentoonz/files/3066067/locator_crash.txt)

### Steps to Reproduce

1. Create a new scene
2. Create a toonz raster level (no need to draw on it)
3. Click on the locater button
### Expected Results

I expected to use the locater window
### Actual Results

Immediate crash
### System Information
* **OpenToonz Version**: Latest nightly build, pretty sure it happens with 1.3 too
* **Operating System**: macOS 10.14.3 & 10.13.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by jrhyme** [comment]
If in Macos, it is better to specify in the topic header)

**Comment by artisteacher** [comment]
I prefer not to specify unless it's been confirmed that it's only an issue on macOS. Often Mac & Linux have the same problems. I've found some issues that applied to Windows too.

**Comment by jrhyme** [comment]
> I prefer not to specify unless it's been confirmed that it's only an issue on macOS. Often Mac & Linux have the same problems. I've found some issues that applied to Windows too.

I indicated in my topic, because I checked it through macos, and suddenly there was the same problem in Windows, hmmm

**Comment by manongjohn** [comment]
Unable to duplicate in Windows.

**Comment by artisteacher** [comment]
That figures!

**Comment by manongjohn** [comment]
Confirmed using official 1.3 on a macOS VM.  I can only duplicate this on Mojave. Does not happen on High Sierra.

**Comment by manongjohn** [comment]
I was able to confirm this crash using the official 1.3 installation, but when I try to compile and debug on the same machine with newer libraries, it doesn't crash.  I wonder if there is an issue with some incompatibility on Mojave because the official build was compiled on an older os/library?

@shun-iwasawa 
Travis builds currently use macOS 10.12.6 (Sierra), xcode 8.3, qt 5.12.2, boost 1.65.1 to build, though we can't really test those artifacts.

What do the Official and Nightly builds use to build the macOS version?

**Comment by artisteacher** [comment]
I do get a crash on High Sierra too.

**Comment by manongjohn** [comment]
I just tried again on High Sierra and this time it crashed for the same reason.

**Comment by artisteacher** [comment]
>  when I try to compile and debug on the same machine with newer libraries, it doesn't crash.

Same for me. It's like how some of the high resolution glitches (selection boxes or etc.) #1216 are not a problem when compiling.

**Comment by shun-iwasawa** [comment]
@manongjohn 
>Travis builds currently use macOS 10.12.6 (Sierra), xcode 8.3, qt 5.12.2, boost 1.65.1 to build, though we can't really test those artifacts.

Travis CI throws away the build artifacts by default. [It seems to have an addon to upload them to Amazon S3, but it is not available for pull request builds](https://docs.travis-ci.com/user/uploading-artifacts/).

> What do the Official and Nightly builds use to build the macOS version?

Both the Official and the Nightly builds are using Qt5.9.2.

**Comment by manongjohn** [comment]
@shun-iwasawa What about macOS version and xcode version? I'm assuming it's still using boost 1.55.0? Should we consider ugrading to newer versions?

**Comment by shun-iwasawa** [comment]
macOS version : 10.11.6 (El Capitan)
Xcode version : 7.3.1

> Should we consider upgrading to newer versions?
Yes, regarding Qt version. I think I can introduce the newer version once we move to it.
OTOH I'm bit reluctant to upgrade macOS version (except when absolutely necessary) as it may mess up our "abused" Mac mini.

**Comment by artisteacher** [comment]
The Mac mini would have to be at least late 2012 to be able to upgrade to Mojave. There are several aspects of Mojave that I really like, though there are drawbacks. For instance, I can't use my Adobe Creative Suite CS5 programs since I won't install legacy java. Fortunately I prefer Serif's Affinity programs, so that's mostly a non-issue. A few programs are sort of hidden now, that weren't before. Overall I would think the biggest risk would be losing access to older software - especially once 32bit programs stop working with 10.15. 

There's always the virtual machine option...
