### ISSUE TITLE
Hand and rotate tools: options for more traditional behaviour

### ISSUE THREAD

**Issue by ReturnMinusOne** [opentoonz/opentoonz#2601]
### Issue Summary
Hello,

The canvas navigation tools in OpenToonz work similarly to those of other graphics programs: hold Space to pan, Shift+Space to rotate the view, Ctrl+Space to zoom.

However, letting go of the shortcut key(s) within a short time (less than 0.5 seconds) will leave the tool active, rather than reverting to the previous one.

I can understand how some might find this useful, but personally I often pan and zoom quickly and repeatedly when drawing, and would prefer canvas navigation tools to always be temporary, regardless of how long the shortcut keys were held down.

Would it be possible to add an option for this in the preferences, perhaps in the Tools section?

Thank you.

### Steps to Reproduce
Press the Space bar to display the "Hand" icon, and let go within half a second.

### Expected Results
The hand would switch back to the previous tool.

### Actual Results
The hand remains as the active tool.

### System Information
* **OpenToonz Version**: 1.3 (Jan 30 2019)
* **Operating System**: Windows 10
* **CPU**: Intel i7 8700K
* **Memory**: 16 GB
* **Graphics Card**: Sapphire Radeon HD 7950
* **Graphics Tablet**: Wacom Bamboo Fun

**Comment by beeheemooth** [comment]
#1100

**Comment by ReturnMinusOne** [comment]
Indeed, it seems I'm not the first to request this option.

Hopefully this issue will be addressed in future releases.
