### ISSUE TITLE
English names of languages in interface

### ISSUE THREAD

**Issue by Savraska2** [opentoonz/opentoonz#2604]
I am a translator into Russian and I am intend to rename the folders with Czech and Russian translations, now they are named fully or partially in English and this is affect in the interface.
![Screenshot_20190424_145459](https://user-images.githubusercontent.com/34054456/56642971-408e0200-66ab-11e9-86fb-0493394c05e4.png)
It will be approximately like this:
![Screenshot_20190424_113614](https://user-images.githubusercontent.com/34054456/56643015-56032c00-66ab-11e9-8440-feaf520311be.png)
![Screenshot_20190424_113455](https://user-images.githubusercontent.com/34054456/56643034-60bdc100-66ab-11e9-9069-4e94b2891f01.png)
But I am not sure that "Čeština" will be the correct translation in this context, and not "Český" or any other. @pafri help me, please.

**Comment by pafri** [comment]
"Čeština" is the **noun** and "Český" is the **adjective**. Also the usage depends on what is expected in that combobox (any way, probably not a great problem to solve :).

I see "Pусский" in the list, also I guess "Český" (adjective) could be the the choice. But tha´s not that simply, when for example "Italiano" is the same for noun as well as for adjective, and "Pусский" could be the thing of coincidence (the choice made by the translator). So the goal is noun or adjective in that combo?

**Comment by Savraska2** [comment]
I think the experience of Russian here will not help much here, as in most languages there are no specialized words to denote languages, unlike Czech. This is quite a rare situation, reminiscent of Russian, which has separate words for representatives of different nationalities.) In the combo box list of the most of the European languages are adjectives, but there are nouns as you noted, or both in the languages of the Far East. It depends on the particular language, and I was afraid to change there something on my own without knowledge of the Czech, though the name and minor detail.)
I have hardly ever met  "Český " and  "Český Jezyk ", almost everywhere  "Čeština ", but I was embarrassed by the tautology in combination  "Jezyk: Čeština ", although I may be mistaken. Which option are you more inclined to?

**Comment by pafri** [comment]
I think, it´s all the stylistics - I don´t see the problem, both could be used. First, small fix for citation - translation of "Czech language": "Český jazyk" (second word: small lettre).

Firts option "Jazyk: **Čeština**", look good, :-) , second option "Jazyk: **Český**", it´s fine for me too. :-) Maybe we should use the coin? :)

**Comment by Savraska2** [comment]
My coin likes the first option :-)

**Comment by manongjohn** [comment]
Personally, I would consider this combo box a list of nouns rather than adjectives.

Can you find out how Czech is listed in other software that supports multiple languages?

**Comment by Savraska2** [comment]
Almost all the software I know uses the option "Čeština", except Blender.

**Comment by pafri** [comment]
Yes, both could be seen. I don't consider it big problem. When the noun is said to be suitable, I say yes. :)
