### ISSUE TITLE
Parents/UnParent/Reparent in timeline

### ISSUE THREAD

**Issue by mikecohen12** [opentoonz/opentoonz#2609]
I'd like to request a feature that would allow parent, reparent and unparent of objects in timeline.

Although there are other 2d animations that allow this, Spriter explains it best on its trailer
https://www.youtube.com/watch?v=6-lDwfIix28 at 1:15

Example would be switching a gun's parent from the spine area to the hand.
Another example would be a skeleton warrior having all its body fall apart.

**Comment by RodneyBaker** [comment]
Closing this issue as feature requests are not generally posted to OpenToonz github without a developer attached.  Developmental discussion of this and related features can continue here even though the issue itself is closed or a topic can be opened in the OpenToonz Feature Request category ([LINK](https://groups.google.com/forum/#!categories/opentoonz_en/feature-requests)).

@mikecohen12  Is there a particular reason using Spriter in addition to Opentoonz for the desired outcome is not ideal?

**Comment by mikecohen12** [comment]
@RodneyBaker Spriter doesn't use vector which Opentoonz does, so it would be nice if it's possible to do it in opentoonz.
