### ISSUE TITLE
regression bug - pressure sensitivity no longer works

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#261]
in Today's build - 27 apr 2016 - 1.0.2 - pressure sensitivity is broken.
https://github.com/opentoonz/opentoonz/releases/tag/v1.0.2

Pressure sensitivity worked in previous nightly buid, but is broken in today's.
windows 7, wacom

stylus buttons also no longer work as expected

**Comment by turtletooth** [comment]
It's working here.  Windows 7 Pro.  1.0.2 with Wacom.  Tried closing and restarting to see if it breaks after first use, but still works.

**Comment by blurymind** [comment]
confirmed. After system restart the drivers started working again. I am closing this now.
