### ISSUE TITLE
import scene as subscene

### ISSUE THREAD

**Issue by mikecohen12** [opentoonz/opentoonz#2610]
To improve reuse, I usually create characters and save it to make it a sort of a character library

The problem however is importing it into another scene means I have to import them one by one then fix their size and position before I could get them functioning the way they should.

Therefore, I believe being able to import the whole scene as a subsheet of a scene would be a time saver, since you get to reuse everything you've made.

**Comment by manongjohn** [comment]
You can load a scene as a sub-xsheet into another scene. Just Load Level and select the .tnz (scene) file.

When prompted to Import or Load the scene, Import will make new copies of levels so you can edit drawings without updating the original scene's drawings. Load reuses the existing levels so drawing changes will apply to the original scene.

**Comment by mikecohen12** [comment]
@mikecohen12 Thanks! I didn't know! I thought it's only applicable to drawings.
