### ISSUE TITLE
touch pinch zoom offset 

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#2611]
pinch zoom on pen tablets is offset from centre of the touch gesture on Cintiq pro 32, Surface pro 2017, Surface 3 since i can remember.

But: on OTX 3-22-19 the problem is somehow fixed and pinch zoom works properly on all devices.

Since i cant find release notes on OTX 3-22-19 i want to bring this to attention and hope, that this fix is soon merged into the nightly build

Thank you

**Comment by manongjohn** [comment]
Though it doesn't mention it in the PR details, I had fixed it as part of #2175 which is in OTX.

**Comment by bobbybutterfly** [comment]
Thats great, thank you @manongjohn
