### ISSUE TITLE
Cannot download windows version

### ISSUE THREAD

**Issue by ricky-dodo77** [opentoonz/opentoonz#2616]
the installer download link found here:
https://opentoonz.github.io/e/download/opentoonz.html

points to this file:
https://github.com/opentoonz/opentoonz/releases/download/v1.3.0/OpenToonzSetup.exe

which is not present in git folders. This results in a download that never completes.

**Comment by manongjohn** [comment]
I just now went to the Opentoonz site using Chrome and successully downloaded the Windows installer.

**Comment by ricky-dodo77** [comment]
tried chrome too before posting, it keeps failing for some reason.

**Comment by manongjohn** [comment]
Check anti-virus software, any browser checker like AdBlocker and/or Chrome security setting to make sure it isn't blocking your downloads.

**Comment by ricky-dodo77** [comment]
disabled uBlock and BitDefender I'll try downloading it from my phone.

**Comment by ricky-dodo77** [comment]
from phone it works, using the same newtwork connection, so there must be something going on my PC
