### ISSUE TITLE
File level Version Control status and options not showing on most files

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2618]
### Issue Summary

After setting up and configuring Version Control, I pushed a project to SVN repository which marked all the files in the project as Read-Only (expected). 

When looking at the files in OT's browser, most files do not have the Version Control icon and more importantly, do not have the context menu options allowing us to "Edit" and unlock the files. You cannot work on those files from within OT without first going outside of OT and using SVN tools/commands to unlock them.

The only files that appear to have the icon and context menu are sequenced files (.tif, .png, .mesh).  Scene file and other image files like vector/toonz raster are not.

Additionally, if I "Edit" the sequenced files to work on them, the files no longer show up as version controlled, though at least they are unlocked and editable.

### Screenshot or Video Reference

After pushing to remote:

![image](https://user-images.githubusercontent.com/19245851/57569435-028b2080-73c3-11e9-826a-0586219a792d.png)

### Steps to Reproduce

1) Installed SVN and created remote repository

Tools: Tortoise SVN w/ command line options installed
Repo: https://svn.riouxsvn.com/otprojects  on (https://riouxsvn.com) 

2) Configured the versioncontrol.xml and permissions.xml per documentation

My`<localPath>` is set to to my Project Root folder (i.e C:\OpenToonzProjects) so all new projects could be pushed to repo.

3) Connected my localRepo to my Project Repo using Tortoise SVN tools
4) Configured OT to use Version Control, then quit and restart
5) Created a new Project/scene in C:\OpenToonzProjects with several different image file types.
6) Opened OT's File Browser and navigated to the Version Control folder 
7) Push all changes to SNV repo.
I verified my commit was found on remote repo.  Also verified all files were locked and could not be edited.
8) Navigated to files in the Version Controlled folder. Only sequenced files have Version Control status and context menu.  Scene file, vector/toonz raster/palette files do not have any version controls. Furthermore, all these files are currently locked (marked Read-Only) and cannot be editted any more.
9) Located sequenced files then Right-clicked and selected Version Control -> Edit
After I click on "Edit" button, the Version Control status icon and context menu commands disappear from the file.  But the files are at least editable.

### Expected Results

Ability to use Version Control on all project files from within OT as described in the documents

Here is a mocked up version of what I expect to see under a version controlled project:

![image](https://user-images.githubusercontent.com/19245851/57569446-251d3980-73c3-11e9-910a-063512ce5a36.png)

### System Information
* **OpenToonz Version**: Verified on 1.0 to present
* **Operating System**: Windows 7 & 10

**Comment by manongjohn** [comment]
After some additional research, I discovered why SVN does not work with files in subfolders anymore.

The SVN 1.7 release centralized the meta data to be stored under the root .svn folder instead of each subfolder having its own .svn folder.

OT still expects .svn directories to be found in every subfolder. When it doesn't find one, it cannot accurately track the status of the files and therefore doesn't enable version control on the files.

Changes will be needed to work against the centralized .svn folders if a local .svn folder is not found.

Until then, users who wish to use SVN will need to know that they must install SVN 1.6.x for it to work properly.

**Comment by RodneyBaker** [comment]
Nice discovery @manongjohn 
Thanks for clearing that up.
That certainly explains why SVN was no longer working in that aspect as expected.
