### ISSUE TITLE
Discussion: How do you add a tool to the program in a plugin?

### ISSUE THREAD

**Issue by merlin2v** [opentoonz/opentoonz#2629]
Is there any way I can create a plugin/add-in that will allow me to add custom tools?
I want to create a vector shape paintbrush and was wondering If there is any way for me to do that?
(I basically want to copy the paint tool and run something to convert the vector line into a shape when the line is finished drawing)

**Comment by artisteacher** [comment]
Do you mean you want the vector object to sort of auto-close? It would be great to have that option added directly to the brush tool without a plugin! 

It seems to me, that there are really 2 components - joining connected strokes and then closing the shape at the end.  The new tool option could allow new strokes to "join" the previous if the endpoints are in close enough proximity (perhaps there'd be gap range dial like for the fill tool). Auto-close would likely enable if the 2 endpoints for a stroke overlapped. 

A variation would be to separate the options out and having an "auto-close" checkbox become enabled only if the "join" checkbox were checked.

**Comment by gab3d** [comment]
@artisteacher  No, he wants to substitute the "normal style" with something else, I think.
@merlin2v  If that's the case, you should explore the different ways to create vector styles in OT.
*Generated* styles are the most powerful ones I think, and perhaps you can code some specific ones for your needs.
Then you also have *Trail* and *Vector Brush* styles that are rather simplistic, but could be useful in certain cases. In particular I miss a **Repetitions** option for Vector Brushes, that could make it a much more useful style type (currently it just stretches a vector drawing along the full length of the vector stroke you are drawing).
You can check [here](https://opentoonz.readthedocs.io/en/latest/managing_palettes_and_styles.html#generated-styles) to see a reference to the different style types.

**Comment by artisteacher** [comment]
You can create your own trail and vector brush styles pretty easily. It works best to duplicate one of the existing brushes in the library (under either the vector brushes folder or custom brushes folder). That way the new brush is the correct size & already loaded with the other styles. The icon of the new brush won't update until you re-open OT - though it's still usable.

**Comment by konero** [comment]
Difficult to know what it is you're requesting, not enough info.

You can draw shapes using flat colors with Toonz Raster and then convert those to a vector outline shape with fills included, if I'm guessing right you're looking for something like the outline brush in Toon Boom or Flash? Here's an example...

![chi12](https://user-images.githubusercontent.com/19820721/58636227-b8bd9800-82e7-11e9-9bb5-70e0014db93c.gif)

But I don't know what the purpose is of you wanting it to happen automatically with each line you draw, sounds like a waste of resources and time to me, but do elaborate if you can.

**Comment by RodneyBaker** [comment]
Closing pending addition information from @merlin2v at which time we can reopen.
The discussion can also continue as necessary in the Opentoonz Forum:

Link:  https://groups.google.com/forum/#!forum/opentoonz_en/categories
