### ISSUE TITLE
Feature regression: Edit Subsheet in Place

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#264]
It is no longer possible to edit a subsheet in context. This is quite essential to have when working on slightly more complex paperless animation projects. 
In addition, the buttons to navigate the subsheet hierarchy were removed.
![subsheet buttons](https://lh3.googleusercontent.com/-X-riLjLK1Mc/VyG_kquMcoI/AAAAAAAABfQ/5FmFMBuQ66AHLaELXSiP7rj4SID9XaY_ACLcB/s1600/cats.jpg)

More importantly, the following function is missing:

> "To edit a sub-xsheet in its context:
Right-click the related xsheet icon on the right of the menu bar, and
choose Enable Edit in Place from the menu that opens."

Editing a subsheet in context really is the last essential missing piece for paperless cut-out animation in OpenTOonz. Please consider restoring it.

**Comment by blurymind** [comment]
I agree with @Rayek . This and the handicapped curves function editor :)

**Comment by Juls3000** [comment]
As one Toonz user from 2000 confirms here (*) , open sub-xsheets in place (context) this is a really important fuctionally.

> Yes this is really an important feature in paperless workflow, especially if you want to animate in digital cut-out because every character can be composed by several layers, so it's  a good idea to make subsheet for each character in the scene.

Of course without the "edit in place" function we can't set the right pose for the character in the scene, because we can't see the background and the other characters on the stage.<

[message in users forum](https://groups.google.com/d/msg/opentoonz_en/uhNUVvTEaEE/oK6s9kf3AwAJ)

**Comment by Juls3000** [comment]
@blurymind What you mean with handicapped curves function editor ? I think it works ok now.

**Comment by blurymind** [comment]
@Juls3000 please see: #234 where I list features missing from harlequin.
it might work now, but its missing some of the features in harlequin and the interface has been cut down and made more difficult to deal with on laptop screens.

**Comment by Juls3000** [comment]
@blurymind I sent there https://github.com/opentoonz/opentoonz/issues/234 my observations

**Comment by Juls3000** [comment]
Here another reason why this fuctionality is esential: https://github.com/opentoonz/opentoonz/issues/218#issuecomment-216582703

The workflow to animate several levels with only one plastic mesh is to make this mesh, from a sub-Xsheet. But then you leave this animated element without context.

**Comment by blurymind** [comment]
@Juls3000 indeed when solving the issue by using a sub xsheet, the ability to animate its levels in place is key to changing their frames when their are bind to the mesh. Without it we cant really benefit from setting it up on separate levels in a subsheet.

I am quite surprised actually that ghibli decided to remove that feature. They didnt even keep it in the x-sheet menu either. 

@shun-iwasawa please bring this feature back and make it optionally visible if it bothers classical animators so much.

**Comment by Juls3000** [comment]
Great ! Thank you @shun-iwasawa!
