### ISSUE TITLE
accidentally closed camera  help?

### ISSUE THREAD

**Issue by ClizieRose** [opentoonz/opentoonz#2640]
### Issue Summary
 I just downloaded opentoonz and was watching an instructional video on how to use it when i accidentally closed out the camera on the animation window/room and i found out some way to put it back but the layout is weird and not like before. i tried uninstalling it and reinstalling it but its still weird. i'm using the 1.3 windows version i think? whatever came directly from the site. can someone guide me to how to put it back like it would've been before please?

### Screenshot or Video Reference

![help](https://user-images.githubusercontent.com/51771279/59401544-eaa31580-8d4f-11e9-831b-07dea1a8309b.jpg)

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**:  windows 10 home 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**: Huion

**Comment by artisteacher** [comment]
Up in the program window under "Windows" go to "Reset to Default Rooms" at the bottom.
![Screen Shot 2019-06-13 at 8 55 10 AM](https://user-images.githubusercontent.com/21159116/59434234-20c8af80-8db9-11e9-8415-a2e3188c0bb7.png)
Afterwards, close out of OpenToonz and reopen. When you are back in OpenToonz, under "Windows" check "Lock Room Panes" which will stop the windows from accidentally pulling out when you resize them.
![Screen Shot 2019-06-13 at 8 58 37 AM](https://user-images.githubusercontent.com/21159116/59434380-769d5780-8db9-11e9-88aa-40699f9a119b.png)

In the future, you should use the [Google Group](https://groups.google.com/forum/#!forum/opentoonz_en) when you have questions. There's also an [online manual](https://opentoonz.readthedocs.io/en/latest/index.html) which can be very helpful.

**Comment by ClizieRose** [comment]
Thanks for your help! I will definitely take your advice
