### ISSUE TITLE
Extend the 'Selective' option for fill and paint brush modes

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#2643]
For the fill tool and paint brush tools, there's a selective option tickbox. Currently:
- If unticked, you can paint anywhere and your colour is painted over the top.
- If ticked, you can only paint where there isn't any paint.

This suggested improvement is to change the tickbox for a dropdown and to add an extra option to fill only where you have already filled. This will help when adding detail with the paint brush (shadows, highlights, accents) and when combining the other fill tools options. This, surely will use the logic that's already coded to work out whether to apply the colour.

So with this new option, the drop down would have:
1. Fill any area - Equivalent to the current unticked option
2. Fill unfilled - Equivalent to the current ticked option
3. Fill already filled - The new option that only applies paint where there is paint already

Obviously, the names written in the dropdown are open for review.

**Comment by RodneyBaker** [comment]
Closing per current guidance on posting feature requests.
Please feel free to continue to discuss here and/or elsewhere (OT Forum/OT Discord).
We'll open this when a developer takes on  the request.

Personally, I like the idea of posting feature requests here in github as long as they are closed immediately thereafter (pending someone taking on the coding/development task).  Maybe we should review the feature request policy and see if the developers are willing to accept that.
