### ISSUE TITLE
Crash with Convert to Vectors

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2649]
### Issue Summary
I have created this issue on behalf of @beeheemooth who mentioned it on the Discord channel.

Sometimes when converting from Toonz Raster to Vector, OT crashes.

In the video shown below, a vector was converted to Toonz Raster and then the Toonz Raster converted back to Vector. When the Preview swatch was enabled, OT would crash. I found later, when Preview swatch was not enabled, OT would still crash during conversion.

I am not sure if the original issue is caused by some Vector->Toonz Raster conversion bug or it's just a Toonz Raster->Vector conversion bug. Either way, the conversion should not crash.

### Screenshot or Video Reference
![ezgif-1-4d46106418f7](https://user-images.githubusercontent.com/19245851/59977732-048bf600-95a3-11e9-8b35-8cacdb9632f7.gif)

### Steps to Reproduce
Following the exact steps in the video didn't always produce the crash. It was rather random but I was able to reproduce the issue every so often.

Attached is a Toonz Raster level that was generated by the  "Vectors to Toonz Raster" which causes a crash when you try to use "Convert to Vectors" on it.

[tlv_level_crash.zip](https://github.com/opentoonz/opentoonz/files/3317981/tlv_level_crash.zip)

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**:  Windows 8, 10

**Comment by ave4** [comment]
I checked under Linux. It really crashes.

**Comment by beeheemooth** [comment]
@manongjohn Thanks for opening this issue.

Please note that if you don't rotate the intersecting lines to their original position (+), but leave it in the inclined position (x), the program will not crash.

To reproduce the error, use the Geometric Tool (Line)

**Comment by RodneyBaker** [comment]
Perhaps some form of divide by zero error when the lines return to their original position (?)
