### ISSUE TITLE
Add a link to the OpenToonz subreddit to the Community Section of the Read Me

### ISSUE THREAD

**Issue by CodyEakins** [opentoonz/opentoonz#265]
I was trying to make a pull request for this, but It wouldn't let me create a separate branch to work from, and file uploads are disabled so:

Someone please add a link to the OpenToonz subreddit to the Community Section of the Read Me so that we may further develop support for the program on Reddit.

Just, like, one line in the README.md that says:
" - Check out the OpenToonz subreddit at [r/OpenToonz](https://www.reddit.com/r/OpenToonz/) "

Again, I apologize for not being able to do it myself... I followed GitHub's guide to do it, but perhaps things are permission locked?

Thanks,
-- Cody (One of r/OpenToonz's Mods)

**Comment by Juls3000** [comment]
You are here from the very beginning: https://workflowy.com/s/JtI13Zub8a#/1007a465c752

**Comment by CodyEakins** [comment]
That does not resolve the issue at all. 
Very fewer NEW users ever see that document/link you just showed me. When someone googles "opentoonz" the first two links they see are (1) the OT website hosted by github, and (2) the OT github repository. The website does not have a community section, but the repository does. It is necessary ONLY to add a link to our Reddit there (on the readme - a.k.a. the pseudo "home page" of the repository).

**Comment by Juls3000** [comment]
It is Ok. I don´t mean that, to be cited in the Index of the OpenToonz official users forum, will be any kind of solution. Just to inform.

**Comment by CodyEakins** [comment]
I think I'm going to close this issue now... 
I want to make it clear that I still believe the other communities supporting OpenToonz deserve recognition. However, ever since I created this post, about four similar threads have appeared, all of which have derailed the topic entirely.

Let's focus on development here.
