### ISSUE TITLE
Images Disappearing when moved - Mac

### ISSUE THREAD

**Issue by Nv7-GitHub** [opentoonz/opentoonz#2664]
I am trying to make an image of hot chocolate show up in my drawing. It shows up fine, but when I resize, rotate, or move it, it disappears.
Find my screen recording [here](https://my.pcloud.com/publink/show?code=XZXM937ZBf5NRaFUYY4oaWHepfQQ1JDdl4ik). 
I am using Mac OS Mojave, I **think** I have v1.3
Thanks for the help!

**Comment by artisteacher** [comment]
I think what's going on is that raster images have set boundaries - a "canvas" that contains the image. When you use the select tool, you have been moving the image off of the canvas - out of the boundaries of the image. If your jpg was the same size as the camera, and filled the entire space, then when you selected and resized the mug and repositioned it, you wouldn't lose the image. To resize the canvas, with the level selected, you can use "Level -> Canvas Size".   Alternatively, you could move the picture with the Animate tool.

This is likely not a bug. However, it could be a great addition to have a new tool option for the select tool that allows you to impact the image's canvas.

**Comment by Nv7-GitHub** [comment]
But the option to change canvas size is grayed out, how can I change it?
![Image](https://i.ibb.co/P9wMRzH/Screen-Shot-2019-07-06-at-1-40-41-PM.png)

**Comment by artisteacher** [comment]
Click on the raster level's cell in the Xsheet and then go to the menu.

**Comment by Nv7-GitHub** [comment]
Thank You!
