### ISSUE TITLE
Crash programs when unchecking

### ISSUE THREAD

**Issue by jrhyme** [opentoonz/opentoonz#2667]
In the Russian interface, clicking on the tick pixels only, the program crashes, it is impossible to remove the tick, as soon as I change the interface to English, everything works. This is in Windows 10, in others I have not checked it yet.
![caed809b8e85b718](https://user-images.githubusercontent.com/49364531/61143482-04fd1a00-a4db-11e9-9aa8-c01e823a26ac.png)

**Comment by shun-iwasawa** [comment]
Confirmed the crash. Thank you @jrhyme for reporting this.

**Comment by gab3d** [comment]
I think this one was already reported elsewhere.
