### ISSUE TITLE
Style Editor Menu uses the wrong icon

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#2669]
The Autopaint for lines checkbox text string is not interactive and the menu icon in the Style Editor uses the wrong icon. There's also a black underline along with the layout switch button. The correct icon can be found [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzqt/Resources/options.svg).

![Annotation 2019-07-15 123953](https://user-images.githubusercontent.com/19820721/61213696-ae235a80-a6fd-11e9-99d0-d8ea948199e0.png)

**Comment by RodneyBaker** [comment]
@konero I've renamed this issue to facilitate addressing the issues going into v1.4 release and (for now) yo place the emphasis on the Style Editor menu icon.

Will likely need to add a new issue to capture and describe the Autopaint for Lines issue.
