### ISSUE TITLE
Add useful links to OpenToonz community resources

### ISSUE THREAD

**Issue by Emasoft** [opentoonz/opentoonz#267]
Add those useful links to OpenToonz community resources to the Read Me file:

For setting up toonz use these files: (you will have hot keys)
https://groups.google.com/forum/#!category-topic/opentoonz_en/tips--tricks/AmtDQIxUs8c

Community web page:
http://www.youropentoonz.com/

OpenToonz Users forum
https://groups.google.com/forum/#!forum/opentoonz_en

Wikia for OpenToonz
http://opentoonz.wikia.com/wiki/OpenToonz_Wikia

Google Plus OpenToonz discussion group:
https://plus.google.com/u/0/communities/117328766497043417332?hl=en

Official Reddit feed
https://www.reddit.com/r/OpenToonz/

Tutorials:
1. https://vimeo.com/160517233
2. https://vimeo.com/160545723
3. https://vimeo.com/160629659
4. https://vimeo.com/160643981
5. https://vimeo.com/160739139
6. https://vimeo.com/160886701
7. https://vimeo.com/161098629
8. https://vimeo.com/161295575
9. https://vimeo.com/161543515
   1. https://vimeo.com/161549422
   2. https://vimeo.com/161981979
   3. https://vimeo.com/162104350

Getting Started playlist on you tube:
https://www.youtube.com/playlist?list=PLLTVJ_gf8ucqyWPSyjkqQzWHve2ZWZEgW

Some older Tuts but still relevant: 
1. https://www.youtube.com/playlist?list=PLOxeQtho2yW6H5Iglv0W96qTbQmPePM0_
2. https://www.youtube.com/watch?v=M7ckY4ZyH-g
3. https://www.youtube.com/watch?v=M7ckY4ZyH-g
4. https://www.youtube.com/watch?v=T50aOjWUr6E

PDF Links to tutorials and manuals:
 1.http://www.toonz.com/htm/support/tutorials/Toonz_TW_Tutorial_Workbook.pdf
 2.http://www.toonz.com/htm/support/tutorials/tutbasiccutout.pdf
 3.http://www.toonz.com/pdf/Toonz71BravoDS.pdf
 4.http://www.toonz.com/htm/support/tutorials/Toonz_TW_Tutorial_Workbook.pdf
1. http://www.toonz.com/htm/support/tutorials/tutbasiccutout.pdf
2.  http://www.toonz.com/htm/support/tutorials/tutadvancedcutout.pd
3. http://www.toonz.com/cgi-shl/download/71H/Toonz%20Harlequin%2071%20User%20Guide.pdf

Workflowy: https://workflowy.com/s/JtI13Zub8a

OpenToonz Development Road Map:
https://docs.google.com/drawings/d/1Rr81BgpUCABqV6ZDXPXoDzVqfTz7AbToBYMm6_MpwVI/edit?usp=sharing﻿

BUG Reporting: https://github.com/opentoonz/opentoonz/issue

**Comment by blurymind** [comment]
The roadmap should be made by the opentoonz key devs. People who actually
know the code and are dedicated to implementing new features

**Comment by CodyEakins** [comment]
I guess our Reddit doesn't matter? Shame on you! Check out Issue #265

**Comment by blurymind** [comment]
the reddit page is pretty darn cool! Kudos to whoever set it up

**Comment by CodyEakins** [comment]
@blurymind - Ah shucks; I did a lot of the customization/design, but it was ultimately down to the users and senior mod for all the quality content. Couldn't have made it "cool" without them. ^ - ^

**Comment by Juls3000** [comment]
I think that as many OT spaces will be created, better, this will mean that the sofware works and users comunity are growing. But I also think that we have to know in what stage we are now. In this moment the critical mass of users to really support OpenToonz developers is in the OpenToonz Official Users Forum. 1300 today.

So that, without exclude others incipients initiatives, I think that the priorities now has to be :

1
To care OpenToonz Official Users Forum, to keep communication there as fluid has been till now, and with so good results.

2
Based on regresion to Toonz Harlequin lost fuctionalities, get, in the beginning, as good software as possible for paper and paperless animation.

3
Show to the world soon results, in matter of  appealing examples of work done with OT.

I think that this will bring to the sofware the amount of users needed to address future developments.

Based on the above, for example, I propose that, logically, the first item in the list of community resources will be the OpenToonz Official Users Forum.

**Comment by adamearle** [comment]
Your OpenToonz is now www.YourOpenToonz.com




*Adam Earle*

**Comment by Emasoft** [comment]
Ok, I've update the first post with your suggetions. Reddit and google forum added. Now somebody should create a pull request with the updated ReadMe.

**Comment by Emasoft** [comment]
Can we do this? The current readme is a joke. People are just downloading the software and going away, instead of joining the community. We are loosing human resources.

**Comment by Juls3000** [comment]
"Community Google Discussion Group" is not the name given by its owners to this forum, the authentic name is: "OpenToonz Users forum". It will be better to correct.

**Comment by Emasoft** [comment]
@Juls3000 Done.

**Comment by Juls3000** [comment]
better use standart link, not mobile one (chrome will do the rest): https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by Emasoft** [comment]
@Juls3000 Right, thank you. Any other modifications?

**Comment by Juls3000** [comment]
I don´t understand the semantics of this to link to the Forum, can you explain please
![cats](https://cloud.githubusercontent.com/assets/19145844/15009966/ecf67aaa-11e9-11e6-88c3-3de0e9253e95.jpg)

**Comment by Emasoft** [comment]
@Juls3000 Yeah, a balloon would be better to communicate the idea of a forum. Adam is the page mantainer, we should ask him to change the icon. @adamearle

**Comment by Juls3000** [comment]
I don´t want to tell anybody how to do things. This is just to explain my concept: I think it will be more appropriated some kind of graphism which stimulate participation and collaboration, as you can see, that is what fortunately is being forum now. 

I repeat, of couse not this, just to explain the idea:

![cats1-horz](https://cloud.githubusercontent.com/assets/19145844/15010328/bb010b94-11eb-11e6-9a3b-4eb5fc291dc0.jpg)

**Comment by Juls3000** [comment]
Workflowy is precisely [the index of OpenToonz Users Forum](https://workflowy.com/s/JtI13Zub8a#/e27233a53488), I think it will clarify to explain it, and maybe to put it close to Open toonz Users Forum item.

**Comment by adamearle** [comment]
Great idea I will get on it tomorrow *(Just so you know i am doing this in
my spare time - pfff sneaking it in between work).*

Honestly the more people that want to make this page better than I think
great. I am hoping that in the end there can be a group of people
maintaining it.

Nothing is set in stone here so feel free to raise your hand be apart of
it. If some thinks of a better way than I am happy for that as along as it
can remain open for the community.

Just a note on the mind map as well. I have noticed it would be great if
there was a way collate information from the forums ans git hub and put it
into a mind map and some how come up with a way that people could vote
developement up and down. Perhaps a google sheets?

I am really open for suggestion on this. Like I said I am fitting all of
this around my day job.

Adam Earle

**Comment by blurymind** [comment]
Imo we should make a website like:

https://rightclickselect.com/p/

**Comment by adamearle** [comment]
I agree that is a great system though i think its still very closed and and
the information is kind of hard to filter.

Google form where everyone can review the results would be great the tough
part is keeping tabs on who submitted the form. Perhaps it's can hook into
github somehow?

Link to potential future bug report

*Adam Earle*

**Comment by Juls3000** [comment]
@blurymind I see something like this the future of actual "OpenToonz Users Forum", once achieved the three objectives I think now are priorities : https://github.com/opentoonz/opentoonz/issues/267#issuecomment-216126205

**Comment by blurymind** [comment]
@adamearle i dont think you looked at it carefully. It does show who made the feature proposal and does do all the things + its more suited to the task than google docs

**Comment by Juls3000** [comment]
@blurymind that's thrue, rightclickselect.com has a good system to evaluate and manage proposals. This is esential. 

Tags and categories help a lot to find things there, and even so, you can do google-search by domain. e.g. ("Animate textures" site:...etc)  > [see google results](https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22animate%20textures%22%20site%3Ahttps%3A%2F%2Frightclickselect.com)

**Comment by CodyEakins** [comment]
While I AGREE that useful links should be added, I think that most of those that you have included are NOT necessary. e.i - links to tutorials, key bindings, etc.

Just include some of the major sites -- they will house further resources for the users who visit them.
**We don't need to turn our readme into the Encyclopedia Britannica, mate.**

(This is a good list of resources, though. It just deserves to be elsewhere...)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
