### ISSUE TITLE
Palette - Remove Unused Styles command missing?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2674]
I've just found the **Remove Unused Styles** command is not displayed, neither in the Edit command, nor in the Palette right click menu.

Was it purportedly removed or it's just some UI bug?

(I'm using last nightly build on Windows).

**Comment by RodneyBaker** [comment]
While I think the OT documentation states 'Remove Unused Styles' I find it is termed 'Delete Unused Styles' in the shortcuts.

You are right about the option not being available via Right Click menu in the palette.
I can confirm the menu option appears to be missing.

**Comment by manongjohn** [comment]
Looking at the code, it appears the option was commented out from the palette viewer's context menu before OT went open source as it was commented out in the 1st commit to this repo.

**Comment by jeremybullock** [comment]
This has been fixed in #3053

**Comment by RodneyBaker** [comment]
Closing as resolved.

Aside:  The option to remove unused styles can be hard to discover even when present and working as designed.  It is not clear how to best make the option more obvious short of adding a button to the palette toolbar.
