### ISSUE TITLE
save scene , save all, create raster level crash on mac OS X 10.11.4

### ISSUE THREAD

**Issue by agbarrows** [opentoonz/opentoonz#268]
as the title, i have continuous crashes on saving scenes (the app crashes, the file is been written but if i open it all drawing are lost, even i save them)

the same thing happens on creating a raster level scene, i know there are known issues (#162 #181) 

it doesn't happen in version 1.0

i attach the report logs
[savescene crash report.txt](https://github.com/opentoonz/opentoonz/files/244266/savescene.crash.report.txt)
[toonzrasterlevel_crash report.txt](https://github.com/opentoonz/opentoonz/files/244267/toonzrasterlevel_crash.report.txt)

thanks

**Comment by kogaki** [comment]
I reopened #162 . Let's continue discussion there.
