### ISSUE TITLE
I cant draw with my tablet using brush tools  

### ISSUE THREAD

**Issue by MAX-RAY** [opentoonz/opentoonz#2689]
### Issue Summary
When I use brush sometimes it move in wrong position so i can't draw nice clean line or circle.

### Screenshot or Video Reference
![opentoonz bug](https://user-images.githubusercontent.com/32533968/62372709-dbb33500-b540-11e9-9667-1ff271036bab.png)

### Steps to Reproduce
zoom in and zoom out and move camera can fix for some spot and not all of them.

### Expected Results
Bad result,I cant draw with it. 

### Actual Results
it's really bad, you can use OT but it will waste your time for zoom in/out.

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Win 10 64 bit
* **CPU**:  Intell i5 Gen3
* **Memory**: 4GB ram
* **Graphics Card**: Gtx 550ti
* **Graphics Tablet**: Huion H610PRO v2

**Comment by RodneyBaker** [comment]
Also, doublecheck your Huion drivers to make sure they are current.
In the past Huion tablets were problematic if not running the latest drivers.

Link to Huion drivers:
https://www.huion.com/download/

**Comment by MAX-RAY** [comment]
> 
> 
> Are you using multiple monitors and one of them is high res?
> 
> If you do, make sure they are all using the same resolution.

yes but for Opentoonz I just work in 1 display,Anyway I set both of them as same reslotion and restart my OS after that I got same problem.

**Comment by MAX-RAY** [comment]
> 
> 
> Also, doublecheck your Huion drivers to make sure they are current.
> In the past Huion tablets were problematic if not running the latest drivers.
> 
> Link to Huion drivers:
> https://www.huion.com/download/

yeah i install latest update (not beta)
![tablet driver](https://user-images.githubusercontent.com/32533968/62381985-525a2d80-b555-11e9-834a-eedc63ab17c9.png)

**Comment by MAX-RAY** [comment]
I don't have any problem with Ms paint and Krita
![krita](https://user-images.githubusercontent.com/32533968/62382666-b4676280-b556-11e9-9776-fdc5a2491c5d.png)
![paint](https://user-images.githubusercontent.com/32533968/62382668-b4fff900-b556-11e9-8889-50dc50d89cfd.png)

**Comment by RodneyBaker** [comment]
Are you running the most recent nightly release of Opentoonz and/or OTX?

For nightlies (look under Assets dropdown):
https://github.com/opentoonz/opentoonz_nightlies/releases

OTX (under assets):
https://github.com/manongjohn/OTX/releases

When troubleshooting issues it's aways good to try the most recent update possible as they will contain all the latest fixes.

**Comment by artisteacher** [comment]
Have you tried changing some of the brush settings? Try lowering the accuracy and maybe also slightly increase the smoothness. Do you have the same issue with the Raster or Toonz Raster levels?

**Comment by manongjohn** [comment]
Not sure if this will help in anyway, but if you have Windows Ink support enabled in your Huion tablet settings, try enabling Windows Ink support in OT..or disable it in tablet.

**Comment by MAX-RAY** [comment]
> Are you running the most recent nightly release of Opentoonz and/or OTX?
> 
> For nightlies (look under Assets dropdown):
> https://github.com/opentoonz/opentoonz_nightlies/releases
> 
> OTX (under assets):
> https://github.com/manongjohn/OTX/releases
> 
> When troubleshooting issues it's aways good to try the most recent update possible as they will contain all the latest fixes.

Both of them doesn't fix my problem.

**Comment by MAX-RAY** [comment]
> 
> 
> Have you tried changing some of the brush settings? Try lowering the accuracy and maybe also slightly increase the smoothness. Do you have the same issue with the Raster or Toonz Raster levels?

`Have you tried changing some of the brush settings? Try lowering the accuracy and maybe also slightly increase the smoothness.`
Yes and didn't fix it yet.
`. Do you have the same issue with the Raster or Toonz Raster levels?`
I test in :
1-Raster 
2-Toonz raster 
3-Toonz Vector levels
and all have the same problem.

**Comment by MAX-RAY** [comment]
> Not sure if this will help in anyway, but if you have Windows Ink support enabled in your Huion tablet settings, try enabling Windows Ink support in OT..or disable it in tablet.

unfortunately didn't help.

**Comment by MAX-RAY** [comment]
Fore more detail you can watch this video with English subtitle.
https://www.youtube.com/watch?v=JSPOw1VRNVc

**Comment by manongjohn** [comment]
By any chance, do you have another set of tablet drivers installed on the same machine?

**Comment by MAX-RAY** [comment]
> 
> 
> By any chance, do you have another set of tablet drivers installed on the same machine?

No.This only tablet I have.

**Comment by RodneyBaker** [comment]
Closing as abandoned or likely resolved.
@MAX-RAY Please let us know if you are still experiencing any problems.
