### ISSUE TITLE
Small freeze when saving/loading/exporting after certain interval

### ISSUE THREAD

**Issue by Kanjuro** [opentoonz/opentoonz#2691]
### Issue Summary
Already posted my issue on [reddit](https://www.reddit.com/r/OpenToonz/comments/ckro15/speed_up_saving/), but since nothing works:
When I start the program and wait for a minute or less, **saving all/the scene**, **loading** and **exporting**, momentarily freezes the program for 15 to 60 seconds. After that, all the above work nearly instantaneously, but start to freeze the program again after another minute passes, and so on. Also happens when starting the program and waiting, before selecting a project/scene.
Once, it randomly started working, but reopening reintroduced the issue.

### Screenshot or Video Reference
[YouTube](https://youtu.be/A-4Yh5Mb6yU)

### Steps to Reproduce
Happens always on my system, but didn't find any steps to reproduce on others.
Tried it on my father's laptop (Win10, same AV) and it seemed to work.

### Expected Results
Saving/loading/exporting should only take 1 or 2 seconds on an empty or small project,
all without freezing the program.

### Actual Results
The program freezes for 15 to 60 seconds and disrupts workflow, even when not changing anything in the scene/on a level. The program **doesn't crash**!

### System Information
* **OpenToonz Version**: OpenToonz 1.3
* **Operating System**: Windows 10 Pro, 64Bit, Version 1809
* **CPU**: AMD Ryzen 7 1700 8-Core @ 3.7GHz
* **Memory**: 2yo SSD + 16GB DDR4 RAM @ 3000MHz
* **Graphics Card**: GeForce GTX 1070
* **Graphics Tablet**: -

### Things I've tried
* Checking SSD health (= OK)
* Running as administrator/with compatibilities, disabling firewall, creating an exception in my AV program for OpenToonz/the whole directory, disabling AV, disabling internet
* Using Morevna version
* Reinstalling in default directory/on different SSD
* Testing, whether other programs have issues in the same directory (which they don't)
* Starting OpenToonz through USB
* Importing audio/video into scene
* Assigning only 1 or 2 cores
* Force the program to use my GPU

**Comment by artisteacher** [comment]
It may not make a difference, but you should try the [OTX release](https://github.com/manongjohn/OTX/releases/tag/OTX-nightly-2019-07-02). OTX has more of the upcoming bug fixes and new features than Morevna or the official nightly builds. It is also portable.

**Comment by Kanjuro** [comment]
Sadly, the OTX release introduces the same issue.

**Comment by artisteacher** [comment]
There's a preference under "version control" that checks to see if there's a more recent version of OpenToonz upon launching. That should be the only place OT is accessing the internet. On a similar note, it might be worth turning off "Watch file system and update file browser automatically" in general preferences too, in case that makes an impact.

**Comment by Kanjuro** [comment]
I already had a hunch that the file system had to do something with it (since freezes came from functions using it), but I must have overlooked that option. **Turning off "Watch file system and update file browser automatically"** seems to solve the issue (or at least circumvent it, I personally don't care), so thank you for your time.
