### ISSUE TITLE
regression from nightly: acceleration range handles no longer visible in x-sheet

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#270]
The keyframe tween handles in the x-sheet seem to be gone in 1.0.2 https://github.com/opentoonz/opentoonz/releases/tag/v1.0.2
They worked in nightly.

Here they are in nightly:
![missingcurvesfeature](https://cloud.githubusercontent.com/assets/6495061/14836054/5c108bd2-0c05-11e6-979c-b899048a3301.JPG)

And here they are in 27 april 2016 1.0.2 release:
![missingtweenhandles-ot](https://cloud.githubusercontent.com/assets/6495061/14953760/7f31a7e6-1064-11e6-8d08-f4263891a66c.PNG)

Can someone confirm this - or is something wrong with my set up again

**Comment by Juls3000** [comment]
@blurymind loock at this please : https://github.com/opentoonz/opentoonz/issues/234#issuecomment-216239920

**Comment by blurymind** [comment]
ah I see, my mistake. Closing this now
