### ISSUE TITLE
CLI option to execute toonscript

### ISSUE THREAD

**Issue by IPv6** [opentoonz/opentoonz#2702]
Please, add CLI option to execute ToonzScript file without opening whole application and diggin into menus, etc. To allow script execution to be embedded into no-UI, batch-file-only workflows

**Comment by shun-iwasawa** [comment]
Will introducing #2659 fullfill your demand?

**Comment by IPv6** [comment]
Yes, sounds like exactly what is needed :) Sorry for duplicate, didn`t find it at first glance. Will wait for next update with this feature then, thanks!
