### ISSUE TITLE
Mesh with Skeleton effect node use Preview button, OT crashes 

### ISSUE THREAD

**Issue by Toybulldog** [opentoonz/opentoonz#2704]
I used a mesh with skeleton, if I click in the effect node on Preview button or Camera Preview button  OpenToonz crashes.

(https://vimeo.com/352944954)

My system is Linux Mint 19
AMD FX-8370E Eight-Core Processor × 4
Radeon RX 460

**Comment by Toybulldog** [comment]
I use Flatpak 1.3.0

**Comment by manongjohn** [comment]
I confirmed this happens on Windows as well.

**Comment by RodneyBaker** [comment]
We are zeroing in on this one.
Possibly related to one of the oldest crash reports still open:  #638
Reference also:  #2154

**Comment by RodneyBaker** [comment]
Review note:  Most of the referenced reports for this have been closed although #2745 is still open.
