### ISSUE TITLE
(Cmake )Is it possible to give the preferred OpenBLAS library name via command line?

### ISSUE THREAD

**Issue by Lovewyrm** [opentoonz/opentoonz#2705]
I'm not that good at cmake, and this is pretty much a cmake question and not an OT one, but...
It would make things easier, and would do away with the need to have a diff monkey sitting on my back when pulling from master.
```

diff --git a/toonz/sources/CMakeLists.txt b/toonz/sources/CMakeLists.txt
index d9b0c34c..3a8f248b 100644
--- a/toonz/sources/CMakeLists.txt
+++ b/toonz/sources/CMakeLists.txt
@@ -428,7 +428,7 @@ elseif(BUILD_ENV_UNIXLIKE)
     endif()
 
     # TODO: check for them properly in some sane order with pkg-config
-    find_library(OPENBLAS_LIB NAMES cblas gslcblas openblas blas)
+    find_library(OPENBLAS_LIB NAMES openblas blas)
     message("OpenBLAS:" ${OPENBLAS_LIB})
 
     set(JPEG_LIB ${JPEG_LIBRARY})

```
I'd like that have openblas the first choice cause that's what I use, hehe.
Any way to do that with a variable or something?

**Comment by RodneyBaker** [comment]
Closing this as out of scope for Opentoonz although perhaps someone can still drop by and make suggestions.
@Lovewyrm If you discovered the answer to your question... we'd love to know too!
