### ISSUE TITLE
Scene persistently rendering blank

### ISSUE THREAD

**Issue by guisincofat** [opentoonz/opentoonz#2706]
I hope this is the right place to ask, I can't find anywhere better. I'm trying to render this scene, but even though it registers all the frames and comes out to the right time length and resolution, it just puts out blank frames. All search results had to say was to set the camera background to white, to make sure my columns were visible, and that multiple rendering was off, did them all, no dice.

I've rendered successfully with (mostly) no problems in Opentoonz 1.2 several times before, and updated to 1.3 just now to try to fix this issue. Same computer, same OS (Windows 8). Preview is also blank, but as you can see it appears and plays just fine on the actual canvas:

![image](https://user-images.githubusercontent.com/53979420/62825514-d453e300-bb61-11e9-8129-513470d2a3ec.png)

I've double quadruple checked my scene/camera/render settings at this point, nothing out of place that I could figure out. Here's a zip with the scene file in question, please don't mind the strange and mediocre animation. I'm hoping someone can just open it, try to render, and tell me what check boxes I don't have ticked or whatever. I tried .gif, mp4, and .png, all blank white.

[meow.zip](https://github.com/opentoonz/opentoonz/files/3489201/meow.zip)

Thanks for looking, and sorry if this is the wrong place for this.

**Comment by RodneyBaker** [comment]
In your screenshot the column in the xsheet appears to be grey.
This is an indication that your column isn't connected.

To inspect that, open a Schematic window and look to see if you column node is connected to the xsheet node.

Once connected it should render correctly.

**Comment by guisincofat** [comment]
Thanks for the fast reply. I don't know what I'm looking at here, I have a basic understanding of node setups from using Blender but there doesn't seem to be an output option. I connected the column to the camera and the render and preview were still blank.

![image](https://user-images.githubusercontent.com/53979420/62825769-c1431200-bb65-11e9-8ad7-24212e9766c6.png)

Also oops, thanks. I'll add it if fixing the nodes doesn't work, not sure where they're stored and my brain feels like it's been deep fried right now if I'm being honest.

**Comment by RodneyBaker** [comment]
Hmmm.... looks to be connected there but just in case...
Down at the lower right corner there is an icon that will change the Schematic view.
That view should have the Output node.

If the nodes are connected at least we know that isn't the problem.
The gray I was seeing before might just be your screen captures being overly saturated or the effect of the Theme you are using.

**Comment by guisincofat** [comment]
![image](https://user-images.githubusercontent.com/53979420/62825973-09176880-bb69-11e9-8ace-67e9280959ea.png)

Yeah, alright, guess it's not that. Is meow.pli the level file? Thanks again for helping.

**Comment by RodneyBaker** [comment]
Yes, 'meow.pli' looks to be the vector level that is missing from the zip file.

**Comment by guisincofat** [comment]
Alright, here it is.
[meow.zip](https://github.com/opentoonz/opentoonz/files/3489235/meow.zip)

**Comment by RodneyBaker** [comment]
Thanks for that.

Ah, it appears that all of your vector lines are zero thickness.
As such they are rendering with no thickness.

One way to adjust all the frames at the same time would be to activate the Selection Tool but change the menu option to 'Same Style on Whole Level' then select a line in one of the frames.  Then go up to the menu on the right and enter '1' as the value for Line thickness... which you should see is set to zero.

**Comment by guisincofat** [comment]
Oh, nice! Thank you so much. I don't know if I would have figured it out without you.
