### ISSUE TITLE
The whole system crashes when I run opentoonz 1.4

### ISSUE THREAD

**Issue by Gilraiser** [opentoonz/opentoonz#2709]
**Issue Summary**

The whole system crashes when I run opentoonz. This happens in this version and the Morevna project version.

**Steps to Reproduce**

The problem occurs when I run opentoonz having installed it either from appimage, flatpak or from the official Archlinux repositories.

**System Information**

OpenToonz Version: 1.4.0 Duango 
Operating System: Archlinux 64x
CPU: Amd athlon 5150 APU. 4 cores, 4 threads
Memory: 12 GB
Graphics Card: Nvidia Gforce GT 610

I hope the information is useful.
see you soon

**Comment by RodneyBaker** [comment]
The official release doesn't run on Linux so I think we may be missing something about your setup.
Looks like you are using Linux across the board.

I'll recommend trying with the OTX Linux release just to see if anything changes.
It's 'experimental' but worth taking a look.
Look under the Assets dropdown here:  https://github.com/manongjohn/OTX/releases

**Comment by Gilraiser** [comment]
Hi, thanks for answering. I did the test with the version you indicated and the following error appears: 

**varName:TOONZROOT TOONZROOT not set...
terminate called after throwing an instance of 'TSystemException'
Abortado (`core' generado)**

I hope the information is helpful. Thank you for releasing and maintaining this software.

**Comment by manongjohn** [comment]
@Gilraiser If you used OTX, when you download the Linux version, just uncompress it. It extracts a folder called OpenToonzPortable. It sounds like you might have taken the AppImage out and ran it. You need to keep everything in that folder together.

**Comment by Gilraiser** [comment]
Hi, that's exactly what I did and I gave him permission to run sudo chmod 775 -R / folder-opentoonz.

**Comment by Gilraiser** [comment]
At no time did I separate the appImage from the portablestuff folder

**Comment by manongjohn** [comment]
Try this 777 on the portablestuff folder and contents

**Comment by Gilraiser** [comment]
Yes, this way it already worked. In the previous way 775 I have other applications run but with this appImage I didn't want to work. Thanks a lot friend. As far as I have tried it works without blocking.

**Comment by Gilraiser** [comment]
Hello, I wish you are very well. I was further testing opentoonz and it happened again that the whole system was paralyzed. This time I reproduced the error in archlinux and also in lubuntu. The error tends to happen using the tools to modify nodes, for example the magnet tool.

 I hope the information is helpful.

 Thank you.

**Comment by Gilraiser** [comment]
Hi, recently opentoonz is available to install from the official archlinux repositories. With the nvidia drivers it worked without any problem, however with the nouveau drivers the program closes but no longer locks the whole system.

**Comment by Gilraiser** [comment]
Hi, the problem persists even though opentoonz can now be installed from the official archlinux repositories. I assumed that maybe it was missing from the opencl libraries, since Enve, 2D animation software, also crashes. But the problem is solved by installing opencl for the official nvidia drivers in this case. I have tried opentoonz again with both the official nvidia drivers and the free nouveau drivers. Thank you very much.

**Comment by RodneyBaker** [comment]
I somehow missed this being resolved.
Thanks for the follow up @Gilraiser
