### ISSUE TITLE
Save previewed frames - can't choose file format?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2712]
@shun-iwasawa 
While translating the manual into Spanish I've found this explanation in the [Previewing Animation](https://opentoonz.readthedocs.io/en/latest/rendering_the_animation.html#previewing-frames-in-the-viewer) section:
> **To save previewed frames:**
> 1. Do one of the following:
>    - Click the Save Images button (save) in the Viewer bottom bar.
>    - Right-click in the Viewer, and choose Save Previewed Frames from the menu that opens.
> 2. Use the Browser to choose a name, a format and a location for the file to be saved.
 
...in step 2 it says that you can choose the file format, but currently the file browser that opens does not give that option, and it seems to only save in TIF format.

Should I update the text in the manual to accurately describe the current behavior, or is this a bug and should be fixed?

**Comment by shun-iwasawa** [comment]
The default file format (and format option) depends on the current output settings.
You can alter the output file format by typing the extension in the "File name" field in the browser popup.

Please note that the previewed image will always be saved in 8 bit per channel even if you set the channel width to 16bit in the output settings.
Also please note that the format option can only be changed via the output settings popup.

**Comment by gab3d** [comment]
Thanks.
So I'll update the manual text to reflect this.

**Comment by RodneyBaker** [comment]
Closing.  (with update to manual text pending)

**Comment by gab3d** [comment]
manual text update, done. 👌
