### ISSUE TITLE
Crash when try to activate cycle in Function Editor.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2713]
### Issue Summary

A crash occurs whether there is a key animation or not.
### Screenshot or Video Reference

![ezgif-1-04290faf4604](https://user-images.githubusercontent.com/25724133/63268205-4c29b800-c29c-11e9-9acb-fa8a949e4479.gif)

### System Information
* **OpenToonz Version**: 2019-08-19 09:11:01 UTC
* **Operating System**: Windows 8.1

**Comment by shun-iwasawa** [comment]
Thank you for reporting the issue. I'll fix it right away.
