### ISSUE TITLE
Alt+0, Alt+9, N, only work on main Viewer

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2715]
The view shortcuts only seem to be working on the main Viewer, even if the focused panel is the Flipbook, Graph Editor, Schematic, etc...

I'm on Windows 10
latest nightly

**Comment by manongjohn** [comment]
Removed labels as this is not an Enhancement.  This should be normal behavior when compared to the original 1.3 release.

Having said that, I tested Alt+0 and Alt+9 on Flipbook and Schematic on the most recent nightly and it worked as expected.  Can you verify if this is still an issue?

**Comment by artisteacher** [comment]
In most cases the shortcuts are working for me on macOS. I'm not seeing anything happen when using alt+9 in the graph editor.

**Comment by gab3d** [comment]
Perhaps was something to do with upgrading and maintaining the same stuff folder in the past?
I've made a clean install now and it seems to be working ok.
Thanks for checking it!
