### ISSUE TITLE
please, can anyone help?. i have a problem at the leve of export.

### ISSUE THREAD

**Issue by willy-oss** [opentoonz/opentoonz#2718]
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
Sure, everyone will be glad to help.
Post additional information describing the problem here and others will jump in and try to resolve the issue:

https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting
