### ISSUE TITLE
Create in GitHub OpenToonz Website a wiki page with useful links

### ISSUE THREAD

**Issue by Juls3000** [opentoonz/opentoonz#272]
I am new here but I guess that I have not permissions to do this.

As @CodyEakins says here https://github.com/opentoonz/opentoonz/issues/265#issuecomment-216412445: When someone [googles "opentoonz"](https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=opentoonz) the first two links they see are 1) the OT website hosted by github, and 2) the OT github repository. 

Perhaps it will be useful to create here, in GitHub OpenToonz Website, a wiki page with links to Opentoonz resources. It will be logic that this list will began with the Official OpenToonz Users Forum (*).

This forum, right now is a live comunity of more than 1300 members and 550 threads which is working fine.

(*)
Official OpenToonz Users Forum:
https://groups.google.com/forum/#!forum/opentoonz_en
Index of Official OpenToonz Users Forum:
https://workflowy.com/s/JtI13Zub8a

**Comment by adamearle** [comment]
Do you mean like *www.YourOpenToonz.com*
<http://www.YourOpenToonz.com>



*Adam Earle*

**Comment by Juls3000** [comment]
@adamearle That could also be in the list

**Comment by adamearle** [comment]
If you can put the the links in here that you would like to see i can add
them in and create a wiki page on YourOpenToonz.com

I know that someone has set this up:
http://opentoonz.wikia.com/wiki/OpenToonz_Wikia

Just a side note it would be a good thing to do up a google form so people
can just answer the questions and then it can all feed into a google sheet.
That people can easily review it for all those people who are doing
development.

The information can be sorted and over time the bug report sheet can be
refined to start introducing dropdowns like operating systems.

Here is a link for a first draft feel free to add to it
https://drive.google.com/open?id=1fTlD0nSYQSOSfhljaX1W5T_GEpe4txD1528jJhJC15Q

Perhaps this kind of thing could be used for feature request as well? I
don't know how this could tie into github though. Any ideas anyone?






*Adam Earle*

**Comment by Juls3000** [comment]
@adamearle 

This "bug report questionary" has to be a tool for the developers, so that, the most important here, is their oppinion about it.

Meanwhile my proposed questions:

1
Degree of knowledgement of the software (1,2,3,4)
2
Your oppinión about the priority of this bug (1.2.3.4)
3
Date and Versión of OT that you are using when bug appears.
4 (*)
If necessary, put here link to your message in the OpenToonz Users Forum or in OpenToonz GitHub , where you complete your explanations with screen captures, videos, animated gif, etc.
5 (**)
If possibe, put here link(s) to messages in the OpenToonz Users Forum or in OpenToonz GitHub, with users discussions, related to this bug.
------------------------------
(*) as you can see in OpenToonz Forum and GitHub issues, one important part of discussions need rich media support.
(**) synergy generated in conversations is very important in collective inteligence generation

**Comment by adamearle** [comment]
Is there a reason why you haven't made changes to the document to reflect
 what you are talking about?

Can you edit it?

Please let me strongly encourage you to go for it and make changes they can
always be rolled back because of it being google doc.

Loving the collaboration on this project.

*Adam Earle*

.

**Comment by Juls3000** [comment]
@adamearle not any special reason, just waiting to the inputs of developers and others.

**Comment by adamearle** [comment]
Maybe I should just put it up on the site? and see what happens I can
always just put a note on there that this is a test to see if it will help
the devs.


*Adam Earle*
<MrAdamEarle@Gmail.com>

**Comment by Juls3000** [comment]
I should wait to developers opinion, if you look it well, issues management in GitHub is a developed bug management system. As per the results in last weeks we can say that this system has been working well  for OpenToonz. Why not priorize other initiatives?

There is plenty of work to do, to positioning OT between animators comunity, as best as possible.

Basically, (as many things in the Net) I think is not matter to collect more information, rather to process it.

e.g. Take care of newcomers, they want to know if it is worth to invest time to learn this software, but they don´t have resouces to get motivate in the first steps. Why not to create a section, in this Web, called "Newcomers zone" and there try to resolve it's problems?, if it works sure they will be very thankful.

Just one thing as example: it is not the same to tell those newcomers about a playlist os 200 videotutorials, that to provide them a plan with  a list of commented videotutorials and the recommended order to see it by means of several needs.

etc

**Comment by adamearle** [comment]
I am not sure to go wit you on that. I am not sure how to integrate what
you are saying into www.YourOpenToonz.com. Google Groups is doing a pretty
good job as a forum for helping newbies and the tutorial listing is up on
there for people to request tutorials and people to make them to help users
out. I kinda feel as if it early days though.

The software has only been out for 2 months.

Can you clarify your point more? Really want to help. Also i am pretty sure
its just me and you reading this (lol).

Adam Earle

**Comment by Juls3000** [comment]
Put yourself in a newcomer shoes and try to imagine what do you want to see, just arriving to this web. What will result for you more motivating, see it from this point of view. Sure like this you will find ideas.

Not pretend that the web has to born big, less is more, question is that everything there keep tunned with visitors.

First are some individuals and their goal, then comes the comunity, this is the order of the things. 

Now the web must show (with somethin more than its title) that there are behind some individuals that know well what they are looking for.

Persons and ideas first, thechnology after.

Sorry, I just can give you conceptual ideas, hope that it helps.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
