### ISSUE TITLE
Cleanup - Line Processing - None. Bring it back?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2729]
@shun-iwasawa 
@manongjohn 

Could it be possible to bring back the **None** option for the Line Processing mode in the Cleanup Settings panel?
It's useful for just stabilizing drawings without touching anything else in the image.

Of course you can stabilize them while you clean them up, but that does not cover all use cases, for example the following one:

- I've got some scanned drawings of a character, and I want to be able to overlay, to a certain extent, the original drawings over the cleaned up ones just to give the final image a more natural and rough look.
The problem is that without the **None** option, I can only stabilize the cleaned up level, but the original scanned one is not stabilized, so to be able to do it I have to resource to other software like After Effects, for example.

If OT could allow again to stabilize without further processing of the image, this could also be resolved inside OT, which of course would be better.

Thanks!!

**Comment by RodneyBaker** [comment]
It's actually painful to close some of these feature requests as most would be so very useful...

Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
