### ISSUE TITLE
Curves FX node does not clamp alpha values correctly

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2730]
When using the Curves node, it is possible to exceed the maximum alpha value due to the tangents of the handles, as can be seen with the upper right point in this image.

![image](https://user-images.githubusercontent.com/42905003/63654880-5e807780-c71c-11e9-9b83-3176e1959816.png)

When this happens, visual artifacts result. As you can see in the below example, the inner section of the ring, which should be a solid black, is instead rendered fully transparent.
![image](https://user-images.githubusercontent.com/42905003/63654872-2ed16f80-c71c-11e9-86a6-1c5430a4d02c.png)

Repro steps:
1. Create a solid shape using any Level type
2. Apply a Blur node to it
3. Use a Curves node and create a shape like the one shown in the first image
4. Make sure the line exceeds the upper bounds of the curve editor

**Comment by RodneyBaker** [comment]
This issue should now be resolved.
@WolfInABowl If this is not the case please let us know.
