### ISSUE TITLE
Shortcut Ctrl + F doubly assigned so won't work for either process

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2738]
# Issue Summary
The Shortcut key Control + F appears to be assigned to both New FX and New Output commands at the same time preventing either option from executing.

### Steps to Reproduce
Enter FX Schematic and use Control + F shortcut
Note that nothing happens.

### Expected Results
Control + F shortcut should execute either the New FX or the New Output command
I am not sure which is preferred but New FX is likely used more often.

### Actual Results
Neither the new FX dialog popup nor a new Output node are created.

If either New FX or New Output is assigned another shortcut... such as Ctrl + Space + F... both shortcuts will work.

**Comment by RodneyBaker** [comment]
@manongjohn  Was your comment a confirmation that the default shortcuts are in fact duplicated in the .ini file?

I ask because if it wasn't just some odd double assigning on my end that will be a pretty straight fotward fix.

**Comment by manongjohn** [comment]
This is a code issue, not in the .ini, that needs to be fixed and it's very straight forward. Just need to know what the other command (New Output) should be assigned to or maybe it should just be cleared.

**Comment by RodneyBaker** [comment]
I'm for Alt + O for New Output as that makes good sense.
Alt + O is used primarily as a shortcut for File > Open but Opentoonz doesn't have that so it would appear to be free (at least until sometime in the future where a File > Open is created).

Any other thoughts on the use of Alt + O to resolve this issue?

**Comment by gab3d** [comment]
it sounds good to me.
