### ISSUE TITLE
Please support the Vuescan Twain driver in OpenTOonz

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#274]
Unless specific twain drivers and/or scanners are found, OpenTOonz will not support scanning drawings directly into OpenTOonz.

Many perfectly fine scanners receive rather poor support from the manufacturers. My Canon scanner, for example, is not supported in Windows 7, 8 or 10. 

Vuescan ( https://www.hamrick.com/ ) solves this issue: it works with just about any scanner model out there, and is available as an alternative twain driver for Windows, Mac, and Linux. It is inexpensive, and just works.

Please add support for the Vuescan twain driver in OpenTOonz: it would solve the scanning problem for most of us. I asked the Vuescan developer initially, and he answered this must be supported in the host program itself - OpenTOonz.

**Comment by Juls3000** [comment]
Perhaps this can help for the moment: https://workflowy.com/s/JtI13Zub8a#/ab9e39880c27

**Comment by Rayek** [comment]
I am bumping this once more: I have the vuescan Twain driver installed, and it works in any application - except in OpenTOonz. It seems that this is an issue in OT.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
