### ISSUE TITLE
Do you provide installer for Linux?

### ISSUE THREAD

**Issue by CHJ85** [opentoonz/opentoonz#2747]
Hi. I went to your website and could only find installers for Windows and Mac.
I did some digging and I found a snap installer. But installing snap adds a ton of bloat.
So is there a normal installer, like Flatpak or a DEB file or whatever. Just not snap.

**Comment by RodneyBaker** [comment]
The official Opentoonz github does not provide a Linux installer but there are several options.

OTX
Opentoonz Experimental is largely the official release but with additional Pull Requests that have not been merged added.  It builds for PC, Mac and Linux.

Link:  https://github.com/manongjohn/OTX/releases

Morevna
The Morevna release takes the core code of Opentoonz and adds some additional features while largely reforming the installation.  There are releases for PC, Mac and Linux.  Morevna currently releases the only Windows 32bit version of Opentoonz.  Some major features such as Mypaint brushes have begun in the Morevna branch and worked their way into the official release.

Link:  https://morevnaproject.org/opentoonz/

Flathub
There is a flatpak release of Opentoonz available.

Link:  https://flathub.org/apps/details/io.github.OpenToonz

There is some additional information on installers available via the official Opentoonz documentation:

Link to Linux installation instructions (via ReadtheDocs):  https://opentoonz.readthedocs.io/en/latest/installing_opentoonz.html#installing-on-linux

**Comment by CHJ85** [comment]
Thanks. But then how come you don't have that on your download page next to windows and mac?

**Comment by RodneyBaker** [comment]
The simplest answer is that there is no official support by Dwango or Digital Video for Linux so it would be wrong to add a suggestion of official support at that location.

This likely relates more to licensing constraints than anything else where issues of Linux licensing can run afoul of commercial aspects of Toonz and Opentoonz use.

Although the official Opentoonz does not directly support Linux the code base itself does to the greatest extent possible.

The workaround for now is to plus up and to highlight Linux releases via the documentation and to point people there.

**Comment by CHJ85** [comment]
I see. Well, thanks for your help!
