### ISSUE TITLE
English Version - Spelling errors

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#275]
I should probably try to fix these myself but I haven't had the time to set up compilation yet

![sensibility](https://cloud.githubusercontent.com/assets/18170954/15030827/e5b1f3c6-1254-11e6-85f4-c82417c09588.png)

Sensibility -> Sensitivity.

![languages](https://cloud.githubusercontent.com/assets/18170954/15030844/038ba2ac-1255-11e6-9e7c-56470726a623.png)

english -> English
french -> French
italian -> Italian
japanese -> 日本語 or Japanese (although I prefer the kanji)
spanish -> Spanish

**Comment by AyameLee** [comment]
In the case of kanji, then shouldn't we write all language names in their local script?

- English (English)
- español (Spanish)
- français (French)
- italiano (Italian)
- 日本語 (Japanese)

Then please note, español, français and italiano should not be capitalized.

**Comment by BrundleThwaite** [comment]
I would prefer that. 
The options are for the native speakers in any case. If however you decide to stay with the English versions then they should all have capitals as they are proper nouns.

**Comment by kogaki** [comment]
By @skitaoka, now it has been fixed as @AyameLee's suggestion. Thanks all.

**Comment by kogaki** [comment]
And typo is also fixed by @turtletooth .

**Comment by BrundleThwaite** [comment]
Thanks.
