### ISSUE TITLE
Erode/Dilate effect - Set frame color?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2752]
It'd be useful being able to set a color for the frame inserted around a column content, when using the Erode/Dilate effect with positive values.
Currently it just inserts a black outline.

**Comment by RodneyBaker** [comment]
Closing as a feature request.
Perhaps we should look at allowing feature requests to stay open?

**Comment by gab3d** [comment]
yeah, I know it could technically be seen as a "feature request", but the fact that it only inserts a black outline in fact causes problems most of the times one would want to use this effect for one of its two sole purposes (eroding or dilating), which could also be seen as a bug (sort of...) for 50% of its functionality.

**Comment by RodneyBaker** [comment]
Opening for review and decision to work into v1.4 or move to 2020 development cycle.
