### ISSUE TITLE
Vector Level - Pasting a stroke onto a vector level does not register it as changed, paste is not saved.

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#2759]
### Issue Summary
Pasting a stroke into a vector level does not register the level as changed-the stroke you pasted is not saved. If any other changes are made to the level, say if a new palette style is added along with the paste, it will save.

### Steps to Reproduce
- Create a new vector level with two drawings.
- Draw a stroke on the first frame.
- 'Save All' (important.)
- Copy and paste the stroke from the first drawing onto the second drawing--make sure you do nothing else.
- 'Save All' again and revert.

### Expected Results
The stroke you pasted should be on the second drawing.

### Actual Results
The stroke you pasted onto the second drawing is missing.

### System Information
* **OpenToonz Version**: Lastest nightly
* **Operating System**: Windows

**Comment by RodneyBaker** [comment]
In that last step where you state:  Save Scene and Revert
Are you using 'Save Scene' or 'Save All'?
If 'Save Scene' then the vector levels are not being saved.
It is 'Save All' (or saving the levels separately) that will secure those.

Aside:  It does make good sense that there should be an option that allows 'Save Scene' to also save the Levels.  The early days of Opentoonz issues with unspecified saving taught me to use 'Save All' rather than the other options unless only specific saves are desired.

**Comment by gab3d** [comment]
Perhaps when using **Save Scene** command with currently unsaved levels, there could be a popup requesting to optionally save them together in that same operation (also with a checkbox to don't warn anymore during the current session).

**Comment by melieconiek** [comment]
@RodneyBaker My mistake, it should say 'Save All' there. It's definitely a bug.

**Comment by RodneyBaker** [comment]
Thanks for the clarification @melieconiek .
I wasn't able to reproduce the issue on first few tests but I'm still testing/trying.

**Comment by RodneyBaker** [comment]
@melieconiek  Can you verify this is still an issue for you?
When I test and make a change of a vector level (copy/pasting or palette change) and then save only the scene Opentoonz prompts me to make a decision regarding the unsaved level change.   If I do a Save All... the change in the vector level is saved.

**Comment by melieconiek** [comment]
My mistake, I assumed this was still happening without testing it. I confirmed this bug in the last build of OT I was running (before I jumped ship to Tahoma,) but it seems to have since been fixed. I can no longer replicate this in the latest OT or Tahoma.

Thank you for checking, @RodneyBaker.
