### ISSUE TITLE
bug: exploding a sub-xsheet that is connected to a mesh node crashes open toonz

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#276]
to reproduce the bug:

1.  create a scene with two levels and save it
2. Create a new scene and load the scene from step 1 by using the 'load level' command in the x-sheet
3. Using the plastic tool, create a mesh on the sub-xsheet 

4.in the schematic view - right click on the loaded subxsheet node and select 'explode' - i used 'bring only columns option'
![explodebug](https://cloud.githubusercontent.com/assets/6495061/15044734/76035edc-12ce-11e6-8912-e521eb128c8e.PNG)

OT will crash

Here are the log fifes created by the crash:
[subX-crash.zip](https://github.com/opentoonz/opentoonz/files/250455/subX-crash.zip)

This is perhaps related to a regression from harlequin - #264 which also causes a problem when we try this #218

**Comment by kogaki** [comment]
This might be fixed
