### ISSUE TITLE
MyPaint libmypaint 1.4.0 released recently

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2768]
This issue is part Enhancement Request and part crash acknowledgement/prevention.

Crash:
MyPaint 2.0 is currently in alpha release. If you install that and import the recommended brush set that showcases the new features, OT on Widows systems, will detect the new brush set and attempt to load it. Through testing I found that if OT loads a bush using either new Input property "Attack_Angle" or "Brush_Radius" from MyPaint 2.0, OT crashes. I know this happened to Discord user a few months ago. I just got around to confirming it.

Enhancement/Fix (hopefully):
On 9/2, MyPaint released libmypaint1.4.0 source, backporting some features in 2.0 to 1
4.0 in order to address some issues.

We need to get libmypaint.dll for Windows systems updated with the latest code, which I am hoping will fix the crash.

I know this affects OT Windows users because we provide the libmypaint.dll with the release. MacOS and Linux pull the lib from external sources when its build so the nightlies/releases will be updated when those sources are updated. They might have been updated already.

@blackwarthog, forgive the direct request...since you originally incorporated mypaint to OT, are you able to easily upgrade our libmypaint.dll version for OT? There is no clear instruction on how to build it for Windows and I am having a difficult time setting up a mingw64 build environment in Windows to do it myself. I'll keep trying if you can't for whatever reason.

**Comment by blackwarthog** [comment]
for libmypaint i've only a cross-compilation script for mingw under linux
it may be applicable for mingw in windows, but i've not tested

i've updated the build scripts and rebuilt the latest version of libmypaint-1.4:
https://dev.icystar.com/downloads/libmypaint-1.4.0-19.09.12-win.zip

copy of used sources:
https://dev.icystar.com/downloads/libmypaint-1.4.0-19.09.12-src.zip
