### ISSUE TITLE
Open Toonz crashes after a while 

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#277]
Hello everyone! Lately i've been having some crashes on OpenToonz, after I just use it for a while, for example I open it, draw a few raster lines, rotate the stand view and so on, and suddenly just crashes. It's weird, already tried to use different computers with windows 7 and 8 and other compatibility modes, but nothing. Have this happened to you? Thanks in advance. 

Greetings, and thanks in advance. 

These are the details:

 Problem Event Name:    APPCRASH
  Application Name: OpenToonz_1.0.exe
  Application Version:  0.0.0.0
  Application Timestamp:    572097a0
  Fault Module Name:    toonzlib.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   57209676
  Exception Code:   c0000005
  Exception Offset: 000000000012ff53
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: 5d31
  Additional Information 2: 5d31d5920e4f1ca59debb85d57195124
  Additional Information 3: b0bd
  Additional Information 4: b0bda9ef073d9c97b12ea7116fed1bc5

**Comment by blurymind** [comment]
when it crashes, it generates a bunch of files in your tmp folder. If you let it frozen for a while, without closing it, a window will pop out and show you where the files are.

If you can zip them up and drag and drop them here - it might help the devs.

**Comment by NestorAntonio** [comment]
Hello blurymind, thanks for the tip. Once OPT crashed I kept waiting, but nothing comes up after the error message. 
![screen shot 2016-05-06 at 14 30 53 2](https://cloud.githubusercontent.com/assets/18132742/15082743/4a11b4fc-1393-11e6-8000-0b7fe9878d37.png)

**Comment by blurymind** [comment]
Why did you close the issue? Its not solved

**Comment by NestorAntonio** [comment]
It's weird, perhaps I did accidentally

**Comment by blurymind** [comment]
try to reproduce it :)

**Comment by NestorAntonio** [comment]
I just re-open it

**Comment by turtletooth** [comment]
Closing for now.  If you can provide steps on how to reproduce it, we can reopen.
