### ISSUE TITLE
Vector drawings are sometimes hard to select

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2775]
Vector shapes/drawings can be difficult to select. Currently a vector object can only be selected by clicking on the center of the stroke. Clicking on a fill doesn't select anything. Similarly, if the viewer is zoomed in too much, clicking on the edge of a stroke will not select it. Groups have the same problem.

It's pretty standard to be able to select closed shapes by clicking anywhere on the shape - whether it is the fill or the edge of an outline.

**Comment by age3rcm** [comment]
adobe programs have developed neat ways to vector workflow, as someone who has been with these programs for 5 or so years, i feel that opentoonz is missing on a feature like this, to be able to select the vector from what you see as a stroke. maybe selecting the fill itself is too much for opentoonz way, but something as selecting vectors easier will improve vector workflow

**Comment by artisteacher** [comment]
It is hard to say what would be the best way forward with this - especially since fillable vector regions can be created by any number of strokes (some of which may be part of other fillable areas).

I do think that at minimum, clicking anywhere on a stroke should select that stroke (no matter how close to the edge when zoomed in). Also clicking anywhere inside a group (whether it is stroke or fill) should select that group. If a group is entered with a double-click (or etc.), then the individual parts of the group can always be selected normally.

Otherwise, perhaps if a fillable region is selected, any boundaries to that region could also be selected when clicking on the fill. Or perhaps, transparent regions shouldn't be selected? In that case, if a region with a fill (other than transparent) is detected, then any boundaries to that region could also be selected when clicking on the fill. Though if clicking to select a stroke was more reliable, I probably wouldn't care about selecting through clicking on the fill...

**Comment by artisteacher** [comment]
Selecting the stroke (but not the control points) can also be challenging with the control point editor if the viewer is zoomed in too much.

**Comment by RodneyBaker** [comment]
Closing as fixed by #2809.

**Comment by artisteacher** [comment]
It's so much better! Selecting strokes with the control point editor can still be difficult when zoomed in too much.
