### ISSUE TITLE
After merging levels, the drawings icons in Level Strip are not updated.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2777]
### Screenshot or Video Reference

![ezgif-2-f372d4970876](https://user-images.githubusercontent.com/25724133/65082254-23393780-d9ae-11e9-862f-b59ee02aef1e.gif)

### Steps to Reproduce

1. Merge two vector levels (as in the video)
2. The operation always succeeds, but no changes are visible in Level Strip.

(This may not always happen when you merge vector levels). In order for the drawing icons to be updated, you need to work on them with some kind of editing tool.

Incorrect display of drawing icons (as well as column icons) is often confusing.

### Expected Results

drawing icons updated
### Actual Results

drawing icons are not updated
### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by RodneyBaker** [comment]
I believe PR #2762 will resolve this.

**Comment by melieconiek** [comment]
@RodneyBaker There *shouldn't* be anything in that PR that address this issue.

**Comment by manongjohn** [comment]
Not sure that will fix. You can verify that now with the Appveyor build. You would need to test both commands.

**Comment by RodneyBaker** [comment]
Apologies for any confusion.
I was likely thinking of a discussion on discord where I had commented about the column preview not updating but others might have been talking about the need (or not) of a menu icon.  
I was noting in that discussion that the column preview wasn't updating and thought the end of your merge process would flag the icon as dirty/unsaved and thereby initiate the updating of the preview..

**Comment by doko-desuka** [comment]
That's the confusing part, it does flag the level as dirty:  
https://github.com/opentoonz/opentoonz/blob/eb319f801dad0d85ae54bb2a3624bac754cddfd6/toonz/sources/toonz/mergecolumns.cpp#L407-L411

I have no idea what it could be.  
The code that flags the level frame as dirty when using a drawing tool (like you used the Eraser in your GIF) is different, it's in here:
https://github.com/opentoonz/opentoonz/blob/e347adcb20cdb6535a45ea098255e28e68000b42/toonz/sources/tnztools/tool.cpp#L557-L601

**Comment by RodneyBaker** [comment]
Icons should now refresh as fixed by #2975
