### ISSUE TITLE
Status Check:  Bug Hunt

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2782]
In the Discussion on OpenToonz development (#2746), stability was mentioned and this Bug Hunt is designed to place a focus on that aspect of development.  The best place to provide feedback on bugs is in individually reported issues but here we want to get a larger view of issues and patterns  impacting stability in Opentoonz.

### Crash ([LINK](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3ACrash))
All issues currently tagged with 'crash'

### Bugs  ([LINK](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3ABug))
All issues currently tagged as 'bug'

### Troubleshooting  ([LINK](https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting))
The Opentoonz forum is a good place to highlight and resolve issues that approach being a bug or crash but need assistance in resolving such as determining exact steps to reproduce the bug or crash.  Most issues also have workarounds so while awaiting the resolution of a problem it will be good to use known workarounds

### User Interface ([UI](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3AUI)), User Experience ([UX](https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3A%22UX+Enhancement%22)) and Workflow issues
These are frustrating and in need of optimization but don't generally meet the criteria of being a bug.  They are however still important and may even provide vital clues to why a process isn't functioning optimally.  Report these issues with the same attention to detail as you would a bug or crash report but be patient as priorities will favor a bug.

### Showstopping Bugs  ([Project Link](https://github.com/opentoonz/opentoonz/projects/1))

There is a Github Project for 'showstopping bugs and crashes'.  For the most part a showstopping bug will be readily evident and will get fixed immediately.  For issues that approach being showstoppers... always look for an interim workaround.  Perhaps it's not a complete showstopper after all.

As bugs and crashes are championed for extermination we'll try to add them here and in the Project kanban.

**Want to help?**
All issues are important but stability highly depends on finding and resolving bugs; especially those that lead to crashes, corrupt data and interference with production.  When you have time read through the issue titles and see if any stand out.   Your experience might provide a vital piece in solving the problem.  When bug hunting:

- Look for other reported issues that are similar or the same as yours.  Your feedback might help resolve the problem for everyone.  
- Fill in the issue template provided when opening an issue as best as you can.  Help others resolve your problem.
- Look for precise steps that can be listed to replicate the bug.  
- Report specific information about computer, operating system and anything that might help isolate the bug.  Do you have access to another computer?  Does the problem happen there also?
- Monitor your report and update it as necessary.  
- Finally, close your report (and thank those who helped) when the problem is resolved.  

As always, thank you for your feedback and for helping our community keep Opentoonz stable and reliable.

**Comment by RodneyBaker** [comment]
### Bug Listing

reserved post

**Comment by RodneyBaker** [comment]
If anyone on Mac is having issues with the new Catalina release it would be good to know about it.

Most reported issues relate to Apple no longer supporting 32bit applications.
Sometimes 64bit programs run afoul of this constraint because they run 32bit programs/processes.
To date we have not had any reported issues of problems with running Opentoon on Mac Catalina.

**Comment by artisteacher** [comment]
32bit applications won't run at all. The icons in Finder actually show a disabled state. It's not a surprise - there was a warning dialog in Mojave every time you opened a 32bit app.

**Comment by RodneyBaker** [comment]
Closing this as it can still be accessed and discussions can continue in closed topics.
