### ISSUE TITLE
Nightly builds missing macOS builds

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2788]
macOS versions are missing in the Nightly builds.

The last time a macOS was included in a nightly was 9/10.

**Comment by RodneyBaker** [comment]
I looked back a few times to see what might have cause the problem but nothing stood out.

**Comment by shun-iwasawa** [comment]
Thank you for the report. I just rebooted the Jenkins machine. Let's see how it goes.

**Comment by shun-iwasawa** [comment]
Hmm, it seems to still have an error. I'll look into this tonight again.

**Comment by manongjohn** [comment]
I'm guessing this is fixed now. I see the OT nightly on the most recent merge has a macOS package now.

I'll close this and reopen if we see issues over the new few days again.

**Comment by shun-iwasawa** [comment]
I think I could fixed Jenkins script. The probable cause was that Jenkins failed to add remote repository to `opentoonz_nightlies` before uploading the package.
