### ISSUE TITLE
BUG: Pinned Center is not working correctly

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#279]
During InverseKinematics Pinned Center is not working correctly.

I am aware how Pinned Center is working since Harlequin version and this is what I've noticed in OpenToonz:
- changing Pinned Center in IK animation is not working all the time. You can set pinned bone and IK children in particular frame and it will work, but if you go back and forth trough Xsheet you can notice that some pinned bones are not pinned(locked) anymore, although the color for that pin (blue square) is showed in the viewport.
- If you do more then two pin switching (let's say different pinning on frame 1, frame 24 and frame 48), and you make few (sometimes even one) undo's, it will destroy all the pins. Again visually in the viewport colors for the pins are changing but in practice they are not locking the bones.

**Comment by RodneyBaker** [comment]
I don't believe this issue (tagged as a bug by @ideasman42 ) has changed since May 2016.
Recommend Review and update of status.

@psychoanima Has status changed?

**Comment by psychoanima** [comment]
@RodneyBaker 
Pinned centar is still a mess. It works in a very mysterious ways. 

If someone is actually willing to fix this tool I would be more than happy to record strange behaviors that pinned centar produces.

**Comment by artisteacher** [comment]
Once there are known steps to easily reproduce a bug, it's definitely more likely to get fixed - though it may take some time depending on the complexity.

**Comment by psychoanima** [comment]
I revisit the problem and record a video about it, it's addressed in a new topic

https://github.com/opentoonz/opentoonz/issues/2368
