### ISSUE TITLE
Output Settings window is not scalable and scrollable

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#2794]
### Issue Summary

It is not important, just for the report.

If you expand all section in **Output Settings** window and if you have a small screen, You can't see all this window easily.

### Screenshot or Video Reference

![Output Setting wondow is not scalable and scrolable](https://user-images.githubusercontent.com/16509592/65342856-dee5ab80-dbe8-11e9-8be3-16434ec418d6.jpg)

**Comment by RodneyBaker** [comment]
Thanks for reporting this. 
Hopefully this will be fixed as part of the UI scrub going into v1.4.

This particular issue could likely be resolved by allowing the Output settings window to be scaled and resized.  There is something of a problem with scaling and resizing though that would still leave an issue.

Another approach (in addition to allowing rescale/resizing) might be to place the Other Settings portion of the window to the right of the Camera Settings and File Settings area.  This would result in a dialog box wider than tall which would resolve the deeper issue of not being able to see all the options at the same time.

**Comment by gab3d** [comment]
the scheme of Preferences window couls also be used. with categories to the left and options to the right.

or, alternatively, tabs could be used also...

there are several possibilities, really, for accomodating those options.

**Comment by RodneyBaker** [comment]
@gab3d This might be a good time to discuss some of our collective approach to development.

Your comment is more of a suggestion to redo the Output Settings dialog... to fix it for good! :)
Such should be an ongoing development topic and we need a designated place for those.... but here is a good place too.

Most of what I focus on in my reviews is short term fixes that can be implemented rapidly (or at least more rapidly than major UI overhauls).  This is largely triage but can carry us through until the larger development is locked in and pursued.

The initial report is the triggering that let's us know that 'something isn't right here'.
Far from being a bad thing report of issues are great opportunities.
My interest is in how we can rapidly address the surface issue (resolving the users problem) while triggering the deeper look into underlying issues and opportunities.

So far so good!  :)

**Comment by gab3d** [comment]
@RodneyBaker 
yeah, I get it and agree.
mine, was just a comment.

**Comment by RodneyBaker** [comment]
@gab3d I mostly posted that for others looking in that don't know the process.
I know you know... but this is the type of thing I wish I knew when I was first getting started.

Heck, maybe everyone already knows the process and can clue me in.  :)

**Comment by hayoko** [comment]
Just add a QScrollArea? 🤔

**Comment by RodneyBaker** [comment]
Relates tangentially to #2566
