### ISSUE TITLE
It's hard to see the Pivot circle - Selection Tool

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#2795]
### Issue Summary

Pivot circle is not clear to see. Sometimes it's hard to see that.

### Screenshot or Video Reference

Pivot in OT
![pivot_ot](https://user-images.githubusercontent.com/16509592/65343093-6fbc8700-dbe9-11e9-9f0a-35ed35480680.jpg)

Pivot in Krita
![pivot_kr](https://user-images.githubusercontent.com/16509592/65343136-8a8efb80-dbe9-11e9-86b1-081324db8f6d.jpg)

Pivot in Photoshop
![pivot_ps](https://user-images.githubusercontent.com/16509592/65343143-8ebb1900-dbe9-11e9-9e4b-713fbed85516.jpg)

**Comment by RodneyBaker** [comment]
Agree the pivot can be very hard to see even to the point sometimes when the user doesn't know it is present.  

This should be an adjustable setting in Preferences but rather than add all the various things required to Preferences it might be better to add a Cursory Magnification factor in Preferences and then multiply the hardcoded value by that factor.

**Comment by doko-desuka** [comment]
@RodneyBaker the pivot widget of the selection tool seems to be drawn with GL commands, in here: https://github.com/opentoonz/opentoonz/blob/ed7dcd58739dd496bfa75b974981bde60230d47f/toonz/sources/tnztools/selectiontool.cpp#L1228

The color is hardcoded to (127,127,127), set a few lines above that one.

Krita's pivot looks like a circle + two crossing segments.
The circle is already in there, so the two segments could be done with [tglDrawSegment](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/common/tgl/tgl.cpp#L117), and all of this drawn twice: once with bright gray (maybe 170,170,170) and a +1 pixel offset from the center, and once with flat black. Something like this (untested):

```
if (!isLevelType() && !isSelectedFramesType())
    const TPointD center = getCenter();
    const double offsetSize = pixelSize * 4.0 * 2.0;    

    tglColor(TPixel32(170,170,170)); // Bright gray.
    TPointD offset = TPointD(1.0, 1.0)
    tglDrawCircle(center + offset, pixelSize * 4);
    offset.x = offsetSize + 1.0
    offset.y = 0.0;
    tglDrawSegment(center - offset, center + offset);
    offset.x = 0.0;
    offset.y = offsetSize + 1.0;
    tglDrawSegment(center - offset, center + offset);
    
    tglColor(TPixel32(0, 0, 0)); // Black.
    tglDrawCircle(center, pixelSize * 4);
    offset.y = offsetSize;
    tglDrawSegment(center - offset, center + offset);
    offset.x = offsetSize;
    offset.y = 0.0;
    tglDrawSegment(center - offset, center + offset);
```

**Comment by manongjohn** [comment]
Just a case of poor color choice in making that circle is my guess. Perhaps also in line weight. It could stand to be a little wider.

It should just be a true black circle with an outer or inner true white circle so it shows better when there is something light or dark behind it.

Let's not make preference/qss entry for every little color choice.

**Comment by 2dvision** [comment]
It's worse, When pivot is on the handle.

![pivot-handle](https://user-images.githubusercontent.com/16509592/65395776-3d0ebc00-ddac-11e9-86d7-89ac0d65f83e.jpg)

**Comment by 2dvision** [comment]
Currently, Animate Tool have a pivot (For example, When you choose Center in Tool Option Bar). Is it possible replace that with Selection Tool pivot?

![pivot-animate-tool](https://user-images.githubusercontent.com/16509592/65429419-0031dc00-de23-11e9-9ab2-1a0de3fdcac0.jpg)

**Comment by manongjohn** [comment]
Fyi, I am currently working on fixing this, making the pivot and drag handles (boxes) more visible against different colored backgrounds.

Will be posting PR with details soon.
