### ISSUE TITLE
 (Discussion) Opentoonz Github Projects

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2797]
[**Opentoonz Projects**](https://github.com/opentoonz/opentoonz/projects)

**Comment by RodneyBaker** [comment]
Here is the place to discuss issues with github Opentoonz Projects.

**Comment by manongjohn** [comment]
We are only allowed 3 things to pin. We don't need this pinned.

**Comment by hayoko** [comment]
There's literally a tab at the top of the page for projects.

**Comment by manongjohn** [comment]
Yes, that's what the discussion is about. How we might want to configure it so it's somewhat useful.

In the end it might not be. *shrugs*

**Comment by RodneyBaker** [comment]
This is figuratively the place where we are discussing the future of those
Projects.

**Comment by RodneyBaker** [comment]
It's only pinned until something else needs to be pinned.
It looked unbalanced with two pinned items over to the left.  ;)

**Comment by RodneyBaker** [comment]
I've temporarily added a [UI Scrub (v1.4)](https://github.com/opentoonz/opentoonz/projects/8) project mostly just to remind myself of the options and constraints of Projects.  I figure I might as well be reviewing some UI related issues in the process...

**Comment by RodneyBaker** [comment]
Closing this as it can still be accessed and discussions can continue in closed topics.
