### ISSUE TITLE
InknPaint Auto-Fill Trace Line Areas

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#2798]
A friend of mine came up with this idea of being able to automatically paint contiguous areas separated by color trace lines using pre-prepared palettes. Unfortunately, this was once a prototype built on some old Gif code, but I no longer have access to the source and he has sadly passed.

When processing animation frames using the color trace line method popularized in Japan the idea is that by filling in a base color, the contiguous shadow and highlight colors are painted automatically in a single click.

By studying this diagram, the start position is our base color, the blue, red and green boxes specify that those regions are separated by corresponding line colors. The F1-3 just denotes that you can use shortcut keys to switch any color as the base fill, so when you click you can fill just the shadow, etc.

![FlowFinal](https://user-images.githubusercontent.com/19820721/60138591-d7a63180-97a2-11e9-8808-4df030c665af.png)

And as you can see here, how each palette group may react.

![Pal_Flow](https://user-images.githubusercontent.com/19820721/60225154-72733e80-987d-11e9-912a-61ecadc4e346.png)

This is a visual sample painting a cleaned frame from Mary and the Witches Flower. Only one-click is necessary to automatically paint three tones (up to four). Simply click wherever the base color is required.

![MA_GIF1](https://user-images.githubusercontent.com/19820721/60138636-fc020e00-97a2-11e9-8488-6bcff0fcad63.gif) ![MA_GIF2](https://user-images.githubusercontent.com/19820721/60138639-fdcbd180-97a2-11e9-9c12-df67ef182b35.gif)

Some interface concepts.

![UI_CONCEPT2](https://user-images.githubusercontent.com/19820721/60138680-294ebc00-97a3-11e9-903c-2d4ca9b0d173.png)

You may create a group by pressing the new group button, or by dragging a color chip from the top to the bottom which will initiate a popup window to allow you to configure the palette group.

![POPUP](https://user-images.githubusercontent.com/19820721/60138834-a7ab5e00-97a3-11e9-9a6f-08de02110653.png)

I originally posted this in #690 but was suggested to make it its own thread.

**Comment by artisteacher** [comment]
I think I said this before, but if this could be implemented, it would make cel shading very quick - especially when combined with frame range filling.

It would be nice if the macro group dialog could have a certain level of automation. When a group is created, any new styles could automatically be added into the level palette after saving the palette - unless the colors can be completely independent from the level palette.

**Comment by shun-iwasawa** [comment]
@konero 
This is a quick note that the similar-looking technique was just issued as a patent in Japan by Celsys last month:
https://ipforce.jp/patent-jp-B9-6580220
(Sorry but it is written in Japanese.)

You wrote that the idea was based on your friend's development from a long time ago. I wonder if it had been published somewhere.

**Comment by konero** [comment]
@shun-iwasawa Wow, Celsys! But no, he never published anything he made as he was not fond of coding. I'm no expert and understanding the patent is difficult being in Japanese, should I remove my posts in-case somebody tries to develop it?

**Comment by jpturcotte** [comment]
@konero Please don't. Actually, there might be legal implications of this idea having been discussed in public before this patent was filled. In the US & Canada, for example, this patent could be nullified.

**Comment by hayoko** [comment]
@jpturcotte Looks like Celsys put in their application on July 24 2018, konero made his first post on June 14 2019 three months earlier than the patent being published on September 25 2019.

We need @shun-iwasawa or a Japanese speaker to advise, but looks like we won't be able to do this, which will suck because Celsys won't release it outside Japan.

**Comment by artisteacher** [comment]
That's really too bad! Is there a direction we could shift this in that won't violate the patent but would allow for faster cel shading?

**Comment by RodneyBaker** [comment]
Closing as slipping to 2020 Development cycle and beyond... as no one is currently attached and actively developing this feature. Anticipate reopening on the other side of 2019 after v1.4 release.

This would be a good opportunity to thoroughly document any current workaroundsas well as other workflows achieving similar results.

Tagging as 'roadmap' to highlight current level of interest.
