### ISSUE TITLE
Scene and Color Picker are blacked out with MS-Software-OpenGL

### ISSUE THREAD

**Issue by kusano** [opentoonz/opentoonz#28]
QtはOpenGLが使用できない場合に、ソフトウェア実装のOpenGLにフォールバックするようになっている。
http://doc.qt.io/qt-5/windows-requirements.html

このソフトウェア実装のOpenGLでは添付の図のようにQGLWidgetを使用しているシーンやカラピッカーが表示されない。

現在一部のハードウェアではブラックリストのためにDesktop OpenGLが使用されず、描画に失敗するため、下記のコードでDesktop OpenGLを強制している。
https://github.com/opentoonz/opentoonz/blob/b74bc3fb800d91958269542570fc63e081d6b009/toonz/sources/toonz/main.cpp#L370

この部分を削除し、環境変数`QT_OPENGL`に`software`を指定することで、Software OpenGLが使われ、問題が再現する。

![image](https://cloud.githubusercontent.com/assets/1194653/14026478/5bbad0b8-f236-11e5-8f4f-3bdc90650eba.png)

正常なカラーピッカーの描画。
![image](https://cloud.githubusercontent.com/assets/1194653/14027038/1263dcae-f239-11e5-9ed6-65e7b3cee882.png)

**Comment by odysseywestra** [comment]
@kusano If you can, could you translate this into English, so the rest of us can understand the bug report?

**Comment by Goofybud16** [comment]
@odysseywestra I threw this into Google Translate quickly, and the text comes out as

> Qt if OpenGL is not available, so as to fall back to OpenGL software implementation. http://doc.qt.io/qt-5/windows-requirements.html to have scenes and Karapikka does not appear that you are using the QGLWidget as OpenGL in the accompanying illustration of this software implementation. Not currently used Desktop OpenGL for the black list in the part of the hardware, due to the failure of the drawing, it is to force the Desktop OpenGL in the following code. https://github.com/opentoonz/opentoonz/blob/b74bc3fb800d91958269542570fc63e081d6b009/toonz/sources/toonz/main.cpp#L395 to delete this part, by specifying the software to the environment variable QT_OPENGL, Software OpenGL is used, the problem recurs.

From what I understand, it comes down to "Software OpenGL doesn't seem to work," however that  may not be correct depending on how accurate Google Translate is.

**Comment by kusano** [comment]
@odysseywestra translated.

Qt fall back to software implemented OpenGL if OpenGL cannot be used.
http://doc.qt.io/qt-5/windows-requirements.html

In Software OpenGL QGLWidgets (Scene and Color picker) are blacked out as attached screenshot.

Currently Desktop OpenGL is not used due to the black list in some hardware.
We force Qt to use Desktop OpenGL as the following code.
https://github.com/opentoonz/opentoonz/blob/b74bc3fb800d91958269542570fc63e081d6b009/toonz/sources/toonz/main.cpp#L370

By removing the code and setting enviromental variable QT_OPENGL to "software", you can reproduce this issue.

**Comment by kusano** [comment]
For software OpenGL, we have to call OpenGL functions via QOpenGLFunctions.
It's hard since OpenToonz depend on GLU and GLUT :frowning:

**Comment by turtletooth** [comment]
Is this still an issue or can this be closed?

**Comment by ideasman42** [comment]
Unless there are plans to support Win32 software opengl, suggest to close as unsupported.

Note that Mesa Software-OpenGL works, so if someone really wants software-opengl, its an option.
