### ISSUE TITLE
Reset Position/Rotation/Zoom buttons on tools option bar not working.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2800]
just that,
Currently the "Reset Position", "Reset Rotation", "Reset Zoom" buttons on the tools option bar are there, but not doing anything when pressed.

tested in the last nightly.
window 10

**Comment by RodneyBaker** [comment]
Are there "Reset Position", "Reset Rotation", "Reset Zoom" buttons on the tools option bar?
I'm not seeing any.

**Comment by gab3d** [comment]
to the far right, yes
