### ISSUE TITLE
Tablet use sometimes disables menus

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2807]
### Issue Summary

Sometimes when using a tablet the menus still become disabled and greyed out (related to #2265) 
### Steps to Reproduce

This is really hard to track, since you don't know it has happened until you open a menu. Previously, we thought it may be related to interrupted input (via auto-save or etc.). #1753 had seemed to fix the issue but I've had 2 students run into this in the last couple days.
### Expected Results

A working menu...
### Actual Results

Sometimes the menu is greyed out and inaccessible
### System Information
* **OpenToonz Version**: Nightly build from 9/20/19
* **Operating System**: macOS 10.13.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**: Wacom Intuos CTH-490

**Comment by sozz7** [comment]
I have the latest OpenToonz on the latest OSX and keep getting the greyed menu, and when this happens I loose all of the drawings done, this time the Level file is one hour behind, though I have autosave set to 15 minutes

**Comment by artisteacher** [comment]
Are there any steps that you can identify that always cause the greyed out menu? If we could narrow down the cause, we'd be more likely to get a fix.

It sounds like auto-save is blocked from running when the menu is disabled. You might be able to save-all manually though. Try using CMD+S to save next time this happens.
