### ISSUE TITLE
The brush does not unlock after stopping playback.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2817]
### Issue Summary

Stopping the animation with a shortcut ("Loop") blocks the brush. The lock disappears if you remove the cursor from the canvas and return it back.
### Screenshot or Video Reference

![ezgif-4-380f685ffae6](https://user-images.githubusercontent.com/25724133/66168736-be850a80-e646-11e9-939e-022505c6b209.gif)

### Expected Results

After the animation has stopped playing with the shortcut, the brush should be available for use.
### Actual Results

The brush is locked and you cannot draw with it
### System Information
* **OpenToonz Version**:  latest
* **Operating System**: Windows 8.1

**Comment by artisteacher** [comment]
I can trigger this on macOS too. Using a shortcut for pause instead of loop has the same result.
