### ISSUE TITLE
Feature request: Ability to see keyframes for Pinned Center

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#282]
When you animate with Inverse Kinematics Pinned Center keyframes for those pins are stored somewhere in the memory, outside XSheet. That means if you re-time something by moving keyframes, pinned center is still staying at the frame where it was originally created, there is no option to to see it/move it/delete it. There is only an option to reset all pins. It's frustrating.

**Comment by blurymind** [comment]
That is a good one. Toonboom has it and allows to animate pivot

**Comment by psychoanima** [comment]
Yes. And I really don't understand why guys from DigitalVideo hide keyframes for pinned center? It's a real mess to work with Inverse Kinematics without option to see on which keyframe pins are stored.

Is it hard to make this option available, anyone? :)

**Comment by psychoanima** [comment]
Here's one visual idea how to show pinned center keyframes:

To make it clear, OpenToonz allows only one Pin Center per Column. With that in mind it's not a good idea to show Pin icon/keyframe in xsheet columns - If model is built from too many columns it can be frustrating to locate where is the keyframe for Pinned Center.

Why not then to show Pin gadget next to the onion skin?

Here's the video mockup I made: https://onedrive.live.com/redir?resid=F734AEC72AD52FD3!5508&authkey=!AOtBKAR4sUKfFws&ithint=video%2cmp4


Deal breaker is to show this gadget only when Inverse Kinematics menu is selected. That way it won't disturb ppl who are not using this technique.

And as I said, because only one pinned center can be activated per column it's a good place to locate it fast and to manipulate with it. Similar like with the onion skin.

**Comment by kogaki** [comment]
#369 has fixed this issue. Thank you all for clarifying the idea.
