### ISSUE TITLE
Scene playback in File Browser results in crash

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2826]
### Issue Summary

When in the file browser (set to icon view), playing a scene by using the playback controls on the scene icon usually causes a crash.
### Screenshot or Video Reference

<img width="96" alt="Screen Shot 2019-10-08 at 8 53 22 AM" src="https://user-images.githubusercontent.com/21159116/66397111-21f59c00-e9a9-11e9-84a5-1d6c47d5bcd1.png">

[fb_crash.txt](https://github.com/opentoonz/opentoonz/files/3702432/fb_crash.txt)

### Steps to Reproduce

1. Open the File Browser and set the view to "icon"
2. In the scene folder for the active project, left-click on a scene to select it
3. Click on the tiny play button on the bottom right of the icon
### Expected Results

Scene playback without a crash
### Actual Results

The scene starts to play but usually OT crashes before playback finishes. Really short scenes can often play all the way through, but longer scenes all seem to crash.
### System Information
* **OpenToonz Version**: nightly builds from 10/7/19, 9/21/19, 9/19/19
* **Operating System**: macOS 10.15 and 10.14.6 and 10.13.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by piotrnikov** [comment]
Yup.
This crashes on my Mac also.

**Comment by artisteacher** [comment]
When running a build from Xcode, I'm not getting a crash.

**Comment by artisteacher** [comment]
I'm not getting a crash anymore. Closing.
