### ISSUE TITLE
Quotations in level name result in empty scene on open

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2827]
### Issue Summary

If quotation marks are part of a level name, the entire scene is empty after re-opening OT.

### Screenshot or Video Reference

<img width="714" alt="Screen Shot 2019-10-08 at 3 52 39 PM" src="https://user-images.githubusercontent.com/21159116/66428501-225f5880-e9e4-11e9-8eb8-c1f14c2aa8c2.png">
<img width="267" alt="Screen Shot 2019-10-08 at 3 56 59 PM" src="https://user-images.githubusercontent.com/21159116/66428572-49b62580-e9e4-11e9-80c8-cf825644061d.png">
<img width="303" alt="Screen Shot 2019-10-08 at 4 02 01 PM" src="https://user-images.githubusercontent.com/21159116/66429126-62730b00-e9e5-11e9-9797-7cfaed52064b.png">
<img width="335" alt="Screen Shot 2019-10-08 at 4 02 09 PM" src="https://user-images.githubusercontent.com/21159116/66429128-643cce80-e9e5-11e9-9330-57531aaafb65.png">

### Steps to Reproduce

1. Load raster levels into a scene where the name includes " and "
2. Also load levels without any " in the name
3. Save all
4. Close and re-open OT
5. Load the scene
### Expected Results

The scene to load normally
### Actual Results

There is a warning notification that there is a problem with the scene and that some files may be missing. The entire Xsheet/timeline is empty - not even properly named levels or "missing levels" with red text. The levels names do still display in the Scene Cast but without any frame numbers. The levels do still display normally in the File Browser.

I know it's not a best practice to name using symbols & etc. but it's weird that the wrong name format impacted the display of the entire scene including properly named levels.
### System Information
* **OpenToonz Version**: 1.3 and latest nightly build
* **Operating System**: macOS 10.14.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
I agree that if Opentoonz accepts them in the first case it should allow for them later.
Another thing to consider along with the growing list of filenaming issues.

On the positive side, we only have to do this once or twice before we are cured of doing it again. ;)

I can see some other alternatives and exceptions but in general applications should reject the quotes as being a valid part of a filename.

**Comment by artisteacher** [comment]
>  in general applications should reject quotes as an invalid part of a filename.

I completely agree!

**Comment by manongjohn** [comment]
Listing this as a macOS only bug, for now. Might be a Linux bug too.  

Normally you can't create files on Windows with double-quotes.  Though there is a way I can force the creation of names with " in them in Windows but the OS handles them in such a way that OT has no problems with it.

**Comment by artisteacher** [comment]
So it looks like when loading from the Xsheet, OT recognizes that there's a problem with the level name and won't let it be loaded. 
<img width="495" alt="Screen Shot 2019-10-08 at 9 50 03 PM" src="https://user-images.githubusercontent.com/21159116/66445695-9e25c900-ea15-11e9-854b-d0e883b6f64e.png">

When loading directly from the File Browser, the level is permitted to load without warning.
