### ISSUE TITLE
Edit tool crash when trying to move level on Z

### ISSUE THREAD

**Issue by Gulwer** [opentoonz/opentoonz#283]
Hi
Opentoonz crashes when I try to move a level in Camera Stand View along the Z axis. Moving works in the 3d view but when I try the same thing in the Camera Stand View it results in a crash.
To reproduce draw something in Camera Stand View, then change tool to edit tool press Cmd+click to move the drawing on Z, crash.

OpenToonz_1.0 [35783]
MacBook Pro 
2,8 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB
[Movetool_chrash.docx](https://github.com/opentoonz/opentoonz/files/257247/Movetool_chrash.docx)

**Comment by kogaki** [comment]
Seems to work now
