### ISSUE TITLE
Opentoonz crashes on animate

### ISSUE THREAD

**Issue by Inuit95** [opentoonz/opentoonz#2834]
### Issue Summary
Opentoonz crashes

### Expected Results
render finish the animate 

### Actual Results
crashes and just quits

### System Information
1.3
windows 10
3.2 GHZ
252 SSD
GTX 1060
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
Two things I can think to check.
 
1) Make sure your Opentoonz is current.  ([Link to latest nightly release for Windows as of 20191012](https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_76d093f2f4532e3f1f2a63ff675d8a7d15ec8a17/OpenToonzSetup.exe))

2) Make sure you have ffmpeg installed (with all 3 files in proper place) and it is connected to Opentoonz via Preferences:  [Link to static FFMPEG download](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20191011-71d9ae1-win64-static.zip)
While you can place practically anywhere I will recommend placing it at C:\ffmpeg.  That way it will be easy to find.  Point Opentoonz to that C:\ffmpeg\bin.

There are other things that can be done to optimize and stabilize Opentoonz but those two are good starting places.  Additionally:

If you haven't refreshed your Opentoonz Stuff directory in a long time recommend renaming that directory something like "Opentoonz Stuff (Backup)" and then when you reinstall Opentoonz it will create a new Opentoonz Stuff directory.  Note that any drawing/animation you created before will be located in the Opentoonz Stuff directory so you can retrieve them from there.

Prior to a reinstallation of Opentoonz, consider uninstalling Opentoonz via the uninstaller located in the same directory as Opentoonz.exe.  This is usually C:\Program Files\Opentoonz.

Also, please let us know more detail about what settings you are using when animating/rendering.  If you can share a screen capture or a video even better.

If you need some live help via chat try:  https://discord.gg/jXFx6jt
Many problems get resolved there.

**Comment by RodneyBaker** [comment]
Closing pending more information from @Inuit95
