### ISSUE TITLE
Bug: Crash Magnet tool

### ISSUE THREAD

**Issue by phamvinh** [opentoonz/opentoonz#284]
Description:

- use Geometric tool to draw 2 lines, then use Magnet tool and drag across them -> crashed and not responding, close program.

- restart program -> unable to recovery shapes on current level (current column) of X-Sheet (they are lost). Solution: try catch global exceptions => save all unsaved items.

- then, create new level (new column) on X-Sheet with old name -> "The level name specified is already used: please choose a different level name".

Bug in version 1.0.2

**Comment by Juls3000** [comment]
Also crashing program using Magnet Tool here, over a Brush Tool line, zoom : 500%

**Comment by shun-iwasawa** [comment]
Oh, now I noticed that the issue #319 was duplicated of this issue.
PR https://github.com/opentoonz/opentoonz/pull/324 will solve this problem.
