### ISSUE TITLE
Pinch & Magnet Tool size sliders are non-linear.

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#2844]
The size sliders for the Pinch and Magnet tools are non-linear--is this intended?

I think this change makes sense for the brush and eraser tool--non-linear sliders give them more precision at the lower end where they're most often used. Other tools like the Pinch and Magnet tool require more precision at higher values.

Tested in nightly.

**Comment by gab3d** [comment]
perhaps holding a modifier key while adjusting it to switch to linear? 🤔

**Comment by melieconiek** [comment]
I've already switched them back--don't want to sound dramatic, but they were unusable. I had to enter the value in the box instead.

**Comment by melieconiek** [comment]
...and I should have looked at the PR beforehand, the change was intended. What are feelings on reverting this, though?

**Comment by shun-iwasawa** [comment]
Switching the slider to non-linear is supposed to be introduced with decupling (x10) the maximum values. But I decided not to expand the maximum value for the Pinch tool and I only quintupled (x5) for the Magnet tool. It may be a reason of your feeling of user-unfriendliness.
I'll try making  both sliders with proper maximum values and would like to get some feedback.

**Comment by RodneyBaker** [comment]
@melieconiek Did this resolve the issues you were having?
Will reopen this issue if it did not.
