### ISSUE TITLE
Style Editor missing in Basic room on initial install

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#2850]
### Issue Summary
After installing a OT for the 1st time and then starting it, the default room is the Basic room and the Style Editor (and Level Strip) appear to be missing.  In it's place is a blank pane.

Resizing the window slightly makes it come back, though too much hides it again.

This started after #2814 was merged.

### Screenshot or Video Reference

![image](https://user-images.githubusercontent.com/19245851/67216874-ea97de00-f3f1-11e9-90dd-ee362d10fb9c.png)

### Steps to Reproduce

1) Uninstall existing OpenToonz installation and remove stuff folder.
- Can also rename `C:\Program Files\OpenToonz` folder and `C:\OpenToonz stuff` folder to temporarily move it aside
2) Download and install latest nightly
3) Launch newly installed OpenToonz

### System Information
* **OpenToonz Version**: Latest nightly
* **Operating System**: Windows 10

**Comment by artisteacher** [comment]
This is also a problem with macOS.
