### ISSUE TITLE
Bug fill Sponge Shading 

### ISSUE THREAD

**Issue by zarco1794** [opentoonz/opentoonz#2851]
I try use Sponge Shading to fill, but happening a issue if not preview activeted (preview render)

![7](https://user-images.githubusercontent.com/39812147/67243956-18e7de80-f42f-11e9-8c3a-1bcd38c7b5da.JPG)

Try fill use Sponge Shading. Click in icono "Preview" later changhe setting of de valor Sponge Shading. Then I deactivate the "preview" icon and the error appears

https://tenor.com/view/gif-15357766

other effects
![7](https://user-images.githubusercontent.com/39812147/67251529-d1208180-f445-11e9-83fe-047202226b0f.JPG)
![9](https://user-images.githubusercontent.com/39812147/67251532-d382db80-f445-11e9-875d-b3965b32afdc.JPG)

### System Information
Opentoonz nightly build 2019-14-10
Window 7 64bits
Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
DDR3  Ram 8 gb
AMD Radeon R7 200 Series
Wacon intuos

**Comment by RodneyBaker** [comment]
It's hard to tell based on your screenshot but...

Makes sure you are in a (standard) raster level (blue cell color in Timeline/Xsheet) and not a toonz raster level (green color).  The blurs, smudges and erasers have not yet been added to toonz raster levels.

If this is your problem you can copy/paste from a toonz raster level to a standard raster level.
Be careful though as we cannot directly copy back (for that we have to clean up or convert).

**Comment by gab3d** [comment]
I can use the Sponge style to fill areas without problem...

I can't recognize that kind of problem shown either, sorry. perhaps is something to do with the graphics card controller?

**Comment by RodneyBaker** [comment]
Perhaps you are attempting to use the vector tools on a toonz raster level?

Not sure.

**Comment by zarco1794** [comment]
Change the Sponge Shading settings with "preview" active

**Comment by gab3d** [comment]
> Change the Sponge Shading settings with "preview" active

it works as expected for me.

**Comment by gab3d** [comment]
![imagen](https://user-images.githubusercontent.com/18104091/67250636-85200d80-f442-11e9-91ff-f67df7884bcd.png)

**Comment by gab3d** [comment]
the only problem I see is the little resemblance between the rendered dot size and the OpenGL ones.

![imagen](https://user-images.githubusercontent.com/18104091/67250689-c31d3180-f442-11e9-9c1f-d2df28886c09.png)

**Comment by zarco1794** [comment]
https://media1.tenor.com/images/820c8bfbfdff1ea900a070bf6df00e92/tenor.gif?itemid=15357766

**Comment by gab3d** [comment]
well, so that's the same problem I've found?
is that it?

**Comment by manongjohn** [comment]
Do you have the option `Visualize Vector As Raster` turned on? If so, try turning it off?

**Comment by gab3d** [comment]
...I didn't have it On when I took those captures.

**Comment by manongjohn** [comment]
Sorry. That question was for @zarco1794. In the video, after making changes im Settings tab and then turning off Sub-camera Preview, the blobs of colors bleeding outside the lines and such look like that when that option is turned on.

**Comment by artisteacher** [comment]
I don't see this problem on macOS. Though I do see the tiny dots (like in @gab3d's first screenshot) without preview on, if I'm too zoomed in.

**Comment by gab3d** [comment]
ah... ok, sorry.
I can't make the dots go outside the shape limits without that option turned Off. 
When it's On they do go outside. 👍

**Comment by RodneyBaker** [comment]
@zarco1794 Were you ever able to get past this problem?
