### ISSUE TITLE
Shortcut/command bar configuration windows based on old menu organization

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2857]
### Issue Summary

It's a little confusing using the old menu structure to organize commands in both the "Configure Shortcuts" window and in the "Customize Xsheet Toolbar" window.
### Screenshot or Video Reference

<img width="363" alt="Screen Shot 2019-10-24 at 5 55 46 PM" src="https://user-images.githubusercontent.com/21159116/67528851-804c9b00-f688-11e9-8eaa-5495b691aa2d.png">
<img width="486" alt="Screen Shot 2019-10-24 at 5 57 04 PM" src="https://user-images.githubusercontent.com/21159116/67528857-83478b80-f688-11e9-9dac-643c742d3f6b.png">
<img width="263" alt="Screen Shot 2019-10-24 at 6 03 41 PM" src="https://user-images.githubusercontent.com/21159116/67528901-a6723b00-f688-11e9-9880-9a2e58b16b86.png">

### Expected Results

The command organization to be the same as the current menu.
### Actual Results

The command organization is still based on the old menu. At least when configuring shortcuts, there is a search option to easily find what you are looking for. The command bar customization relies completely on knowing where to find the different commands - that's difficult when the menu doesn't match.
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
Reference file:
https://github.com/opentoonz/opentoonz/blob/master/stuff/profiles/layouts/rooms/Default/menubar_template.xml

**Comment by RodneyBaker** [comment]
Added this to the UI Scrub as a likely candidate to fix before v1.4 release.
There isn't currently a tag to identify issues that are easy to fix by anyone with time on their hands and an interest but this issue might be a good example of such.  

In this case it appears the xml files simply have to be updated to reflect the current menu layout.
Once updated those files can then replace the ones currently in source.

In the R&D category:
Where exactly does Opentoonz get it's listing(s) for customization of menus via Shortcut and Xsheet Toobar from and can this be better documented for the future when similar updates are necessary?

**Comment by manongjohn** [comment]
The Command/Toolbar and Shortcut customization screens are not driven by xml files.  Each command is coded to be assigned to a group so a code change is required to line them up to the default menu layouts.

This would need to be done for Customize Menu Bar of Room (Windows only), Customize XSheet Toolbar and Configure Shortcuts.

Additionally it should account for the fact that StudioGhibli default menu layout is different.
