### ISSUE TITLE
(WIP) Various Typos - Mostly Cosmetic

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2869]
This is to capture various typos in the UI and source.

Example:
Horizontal rather than Holizontal
https://github.com/opentoonz/opentoonz/blob/6817df33ac50b6be01a2e7b060ea04be5f70f742/stuff/config/current.txt#L1265

Reference also open issues:
#44 

Add reports of other typos (other than those related to translation) below and they can be addressed.   Translation issue can be handled within the Translation scrub.

Developers:  Feel free to include these typo fixes in PRs as you see fit and we will remove them from the list.

**Comment by hayoko** [comment]
So, why not fix them instead? 🤔

**Comment by RodneyBaker** [comment]
Not really a typo but there is a general agreement to use RGBA instead of RGBM (alpha vs matte) in Opentoonz.  REF:  #2725

**Comment by RodneyBaker** [comment]
Status update:  I've had some issues with github of late and so some of the easy fixes related to wording/spelling/typos are waiting on me getting that worked out.

**Comment by RodneyBaker** [comment]
@luzpaz has picked up the torch of fixing (mostly cosmetic) typos.
REF:  #6387

Note:  These almost invariably do not effect running code but may fix elements in the interface.  Most are in code comments.  

Here's a general policy to consider when referring typos to be 'fixed':

Typo Fix Policy

✔️ Safe to fix: UI text, localization strings, documentation, comments, tooltips, help messages.

⚠️ Review required: Any change to identifiers (variable names, function names, class names, file names), macro names, enum keys, or data used by other parts of the program.

❌ Avoid unless justified: “Correcting” spelling inside code that compiles or is referenced elsewhere (e.g., renaming functions, changing include paths, public APIs, or constants) unless it is causing bugs or has strong justification. These change signatures and break references.

If anyone spots a typo not yet identified please submit that in #6387 for consideration.
