### ISSUE TITLE
We need smarter vector Erase Tool functions -  'Remove vector overflow' is highly ineffective!

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#287]
This is my second major feature request to improve the drawing tools in opentoonz, after this one:
#81

Very often when cleaning an ink drawing, the artist will need to clean up line overshoots. A good example of this is hair, but it applies to many places in a drawing.
In vector software, we tend to favor line overshoots, because that way we know for sure that our shapes will be closed off and ready for the bucket tool.
This is where the 'Remove Vector Overflow' command is supposed to come in and save the day.

It however hardly works. Very often it does noting at all.In fact almost 80% of the time when you select two overshooting individual lines, nothing happens, or it erases parts of the lines you want to keep.

![bettervectoroverflow](https://cloud.githubusercontent.com/assets/6495061/15185154/d719f5da-178f-11e6-8d1e-02be1cd6dada.PNG)

My suggestion here is to add two new modes to the eraser tool - when you are using it on a vector level. These two modes can already be found in other software such as toonboom, clip paint studio and last but not least - inkscape:

**A.  Erase up to intersection** - This can be found in both Toonboom and clip paint studio. What it does is it erases the lines up to the intersection point - where they intersect with another line. Clip paint studio has it as an eraser tool mode and it works excellently.
![func_comic_06](https://cloud.githubusercontent.com/assets/6495061/15185642/fc5f40b4-1791-11e6-94f8-dd5e3e8496e7.jpg)

![vectoreraser](https://cloud.githubusercontent.com/assets/6495061/15186218/15e1cd48-1794-11e6-8713-e17476328297.gif)

Toonboom has two strategies to deal with this. One is the one clip paint uses. But as a second strategy - there is an option in the brush tool - to always create a new node where the stroke you drew overlapped another stroke. From there on it is easy to erase all the nodes exactly to that point and you dont need to move nodes around to get them to overlap.

Another strategy with the brush tool is to automatically snap the beginning and end of a line to a closeby node of another line or the line itself (toonboom). Inkscape  allows you to continue previously drawn lines - but unfortunately works at the end points of lines and is very limited.

**B. Object mode eraser**\- very often the artist would require to erase entire strokes of a drawing - every stroke is a vector object. Right now in OT you have to go to the select tool, select the strokes and hit delete, then go back to the eraser tool to continue working. In inkscape the eraser tool can also erase entire strokes like this:
![eraserobjectmode](https://cloud.githubusercontent.com/assets/6495061/15185579/bf3c77ba-1791-11e6-990b-34757f00851f.gif)
this is a much better/faster way to do it.

**Comment by blurymind** [comment]
Here is an example of the remove vector overflow command failing:
![vecoverflowfail](https://cloud.githubusercontent.com/assets/6495061/15187038/642c5c4a-1797-11e6-8c60-07afcfded9c0.gif)

I also notice that all the lines on the level can affect it - not just the ones you select. If your drawing has too many lines, the ones you do select to be cleaned up - will not work. The tool will not work at all until you erase some of the lines on the level.

It is just not very intelligent the way it works. In clip paint and toonboom the artist can point to the tool which part of the lines need to be erased. In OT - you dont give the software that information and it tries to figure it out (very poorly)

**Comment by Juls3000** [comment]
I agree, all this could improve. Here my observations about "Romove Vector Overflow":

a) Just working for closed perimeters.

b) Works better with lines drawn with [Tool Option Bar > Break: Off] (1). [Break: on] breaks in two parts lines with very sharp angles (2) this could originate confusión to the "Romove Vector Overflow" command.

![cats](https://cloud.githubusercontent.com/assets/19145844/15255208/df94d494-193a-11e6-8c34-01b4026ef5be.jpg)

Anyway this command not always works ok.

**Comment by blurymind** [comment]
The one in OT almost never works in practice. It works when you draw a simple square like that, but when you draw a character and start trying it out - the one in clip paint does the job , while vector overflow in open toonz fails 

I wonder how clip paint does it. It's the best one I've seen so far. Strokes there dont create nodes at intersections - so they must be somehow figuring out where the intersecting point is:

Here is my theory

--when the stylus starts a stroke in vector eraser mode:
1. Vector erase stroke collects a list of lines (like inkscape does in example B.) that you touched during the stroke.

--On release the following happens:
2. Instead of deleting the entire lines (which is an option also), it splits them all up at intersections points (cache result)
3. Using the result from step 2 , It marks the parts of the lines that your stroke has touched and deletes them
4. The lines that were split up (in step 2) are connected again
5. All the lines in the list of lines from step one are deleted and in their place are created the lines created by this operation.

**Comment by BrundleThwaite** [comment]
This is actually the feature I want the most in OpenToonz especially with the eraser workflow like in clip studio.

**Comment by blurymind** [comment]
There was some interest to this feature by one of inkscape's devs at the mailing list.

**Comment by Banbury** [comment]
Link?

**Comment by blurymind** [comment]
@Banbury it's a mailing list. All I could get is this screenshot:

![capture](https://cloud.githubusercontent.com/assets/6495061/15507385/4d260fce-21c3-11e6-898b-25d79bd63071.PNG)

doesnt look like much, but the guy who replied just had implemented a new mode for the eraser tool - to erase multiple objects

**Comment by Banbury** [comment]
Here's the link: https://sourceforge.net/p/inkscape/mailman/message/35106095/

**Comment by blurymind** [comment]
@Banbury Thank you for finding it. :+1: 
and also for the fixes you committed recently. The contributions you make are felt in the community.

Such an eraser tool mode definitely makes cleanup work much easier in any vector app that has it. It's just a shame none has implemented it yet.

Can you give us some insight on how vector overflow works in opentoonz? Perhaps some of the code there can be used towards achieving this?

**Comment by Banbury** [comment]
Up to now my 'contributions' were mostly one liners. But thanks anyway.
I'll give it a look as soon as I can, but I won't promise anything. Cleaning up vector lines might be more complicated than adding a checkbox. :)

**Comment by Banbury** [comment]
As promised I had a short look at the remove overflow function. But I'm afraid, it won't help you in it's current form.
The function only works with closed shapes. For every vector layer there's a list of strokes. Every time you draw a line, you get new stroke (TStroke). The the program will look for new closed regions created by that new stroke. Strokes that are part of a closed shape, have a list of edges (TEdge), that define which part of the stroke encloses the shape.
Remove overflow will the cut off any part of a stroke, that isn't part of that closed shape.
All the relevant code for this is in tnzcore/tcomputeregions.cpp. There are some interesting functions in there, like TVectorImage::Imp::findIntersections(), that might help with what you want to achieve.

To implement this, one would have to
1. create a new tool, that works like the one in Toonboom. That's not exactly difficult, but a lot of work.
2. the new tool would create list of strokes, that should be cleaned, and a list of points, where the tool crossed those stroke (the purple arrow in your picture). 
3. with this information it would look for the closest intersection point between those strokes and then split the strokes at that point.
4. finally the strokes have to be deleted, that lie between the intersection point and the crossing point from step 2.

Since the code to find the intersections already exists, I would guess, it's something any half-decent C++ developer should be able to write in about 5-10 person days. Sadly I don't have that time available.

**Comment by blurymind** [comment]
@Banbury excellent review. Perhaps a google summer of code or a kickstarter could help fun someone improve the drawing tools. If there is interest and an actual developer who can pull it off and has a solid plan, i can help out with putting together a campaign

**Comment by blurymind** [comment]
I used remove vector overflow for much longer now and here are some of my observations:

 it is not useless - i definitely use it a lot now , but it is limited:
- being able to remove overflow only on closed shapes means its not possible to use it on non-closed features inside the silhouette 
- Sometimes it is not very clear which shapes are closed - so even when you expect it to work - it doesnt until you close them. If it doesnt - you get the hint that it needs to be closed first. You can use "fill check" to find shapes that are not closed. This makes it tricky to use on things like hair or anything too complicated
- As mentioned sometimes it erases the wrong side of a line - if you have more than one line crossing  - that increases that chance of that happening. If it does one must readjust the lines.

it would definitely be better if it was smarter, but it is not useless.

@turtletooth @shun-iwasawa Would it be possible to set a default keyboard for this feature- as its repeated use requires a lot of right clicking and is better to have a keyboard button for it - I set mine to be the "R" key.

**Comment by blurymind** [comment]
Here are case examples where vector overflow does not work, but this tool would work:
 
![overflowdoesntworkexamples](https://cloud.githubusercontent.com/assets/6495061/16421837/2f6b973c-3d4e-11e6-956b-9002ec3bb861.PNG)


1. If you want to clip the outside (left) half of the line - nothing is going to happen, because the line is not forming a closed shape. It is not a part of a closed shape.

2. If you want to turn the X into a V by clipping its ears, in this case it is not going to do anything - because the X is not a closed shape

3 and 4. These two are a part of a single line - however if you want to clip only 3, it will also clip 4. You want to keep 4 - but it will clip it with 3. This is due to vector flow not knowing which part of the line you want clipped- so it clips all. This is both a pro and a con. Its a pro when you want to clip lines at both ends as it saves an extra step. It's a con when you want to clip only specific parts of a line.

5. Another con of the current command is that it is impossible to clip the part of the line between 3 and 4 - which is marked as 5 here. It will always preserve 5 - whereas in many cases you would want to clip 5 but keep 3 and 4.

**Comment by blurymind** [comment]
Here is a mockup of how the eraser tool options bar GUI can work with the proposed features here-
You would need to add a new drop down list:
![mockup-erasertoolmodes](https://cloud.githubusercontent.com/assets/6495061/16439111/6aa83f62-3dad-11e6-9f2d-e60e67fb32d8.png)
- Brush - In this mode the eraser tool behaves in the standard way that it behaves right now.
- Lines - In this mode the eraser tool deletes entire lines that the stroke touches (https://github.com/opentoonz/opentoonz/issues/287#issue-154270413 -B. Object mode eraser)
- Overflow - In this mode the eraser tool erases lines up to an intersection - as described here 
( https://github.com/opentoonz/opentoonz/issues/287#issue-154270413 - A. Erase up to intersection )

**Comment by 2dvision** [comment]
Cutter Tool in Toonboom:
![optimize cutter tool](https://cloud.githubusercontent.com/assets/16509592/16408712/40457cd6-3d2f-11e6-9296-aa0f5691edbe.gif)

I think "Cutter Tool" will be better for this. it can identify the vector lines now. Maybe optimize that will be easier for developers.

**Comment by blurymind** [comment]
@2dvision My suggestion is exactly for the same tool :) 
But have it available as a mode of the eraser tool instead of a whole new tool.
The reason I am suggesting to nest this functionality as a mode under the eraser tool is the current lack of space in the toolbox. It is that way in clip paint studio

**Comment by walkerka** [comment]
I didn't see the code yet but there're some issues:

1. The "Brush" tool of OT is not the "Brush" of Harmony. It's actually the "Pencil" in Harmony. 
It means the vector image is composed of strokes (curve with thickness) rather than closed path. As a result, you can't get precise shapes at the intersection. The Harmony "Cutter" only erases the line segments to the intersection but it doens't change the thickness of the intersection point. The result may not be what you expected.

![cut](https://raw.githubusercontent.com/walkerka/anim_builder/master/doc/overshooting_cut.png)

2. There may be performance issues. (depends on the data structure)
First you must find the exact intersected strokes with the cutter stroke. Then you need to find the intersection of the selected strokes with all the other strokes (including self-intersecting strokes). Please note that each stroke is composed of many sub segments so the intersection test between strokes is not a cheap operation.

**Comment by blurymind** [comment]
@walkerka Please note that the operation does not need to constantly run while the stroke is being created - so no need to be in real time. During the stroke - all that is required is to collect the lines.

1. The actual clipping operation can then be executed once when the user releases the stylus  (at the end of a stroke). Even if it takes 1-2 seconds to apply - then that is not such a big performance problem.

2. generally it is not likely that the user will collect a big number of lines. Considering that this action is done during the cleanup stage - and it is done for overshoots - it is more likely that 1-5 lines are clipped per stroke. I personally clip one or two maximum.

On the thickness problem - that is something that doesnt need to be tackled at this stage - as we have the exact same issue when using the vector overflow command as well - and it's not really that big of a problem. For as long as we end up with a closed shape that can be filled - its not a problem.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
A part of this proposal was implemented.
Please see reports and pull requests related to Segment Erase.

Reopening primarily for purpose of review.
