### ISSUE TITLE
Add Version to .app bundle for OS X

### ISSUE THREAD

**Issue by rustymyers** [opentoonz/opentoonz#288]
We manage our software using systems that rely on the CFBundleShortVersionString key in the Info.plist of an App bundle. OpenToonZ does not have any of the version values entered into the Info.plist, making it difficult for us to manage the application.

Please include the application version (e.g. 1.0) in the CFBundleShortVersionString key of the Info.plist inside the app bundle.

**Comment by RodneyBaker** [comment]
@rustymyers was this issue ever resolved for you?

**Comment by rustymyers** [comment]
@RodneyBaker No, this issue is still present in the latest releases of OpenToonz.
Inside the OpenToonz.app/Contents/ folder is an Info.plist file with the following keys:

CFBundleVersion
CFBundleShortVersionString

Currently, both of those keys are empty, which causes the system to report the app without a version.

**Comment by jpturcotte** [comment]
@rustymyers The next nightly should fix this. Please test it if you can.

**Comment by rustymyers** [comment]
@jpturcotte Thanks very much! Versions are working as expected.

**Comment by jpturcotte** [comment]
You are welcome!
