### ISSUE TITLE
Crash when turn out Global Key in Plastic Tool

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2881]
### Screenshot or Video Reference

![ezgif-1-f375a09c6753](https://user-images.githubusercontent.com/25724133/68896951-2e51df00-0735-11ea-9a11-82025a234fbe.gif)

### Steps to Reproduce

1. Turn on Animate mode (Plastic Tool)
2. Turn on Global Key
3. Turn out Global Key

### System Information
* **OpenToonz Version**: 2019-11-13 23:11:15 UTC
* **Operating System**: Windows 8.1

**Comment by gab3d** [comment]
That only happens to me if I put a Global Key button on the Xsheet Toolbar, like you did.
If I use the Global Key option in the Plastic tool options bar it all goes smooth.

I think that perhaps that Global Key function you can put in the Xsheet toolbar is not the same function as the one in the Plastic tool?
Still, it shouldn't crash.

**Comment by beeheemooth** [comment]
@gab3d Really. In my case, there are two "Global Key" switches, one on the Tool Option Bar, the second on the Xsheet Toolbar. Apparently the conflict arises due to the fact that these switches are not consistent.
Maybe these are not the only switches that conflict.

**Comment by RodneyBaker** [comment]
I'm not sure we currently have a method for validating which options are valid for use with the customization of tool bars.

One method might be to only accept those explicitly allowed but that leads to higher maintenance as new options/features are added.  Still, this seems to be the only way to prevent users from creating incompatibilities.  

Right now it would appear the burden of customization lies with the user to validate what will work in any given situation and refrain from using those that don't.

As for the crash, perhaps for all customizable menus there can be a means to catch errors and at least prevent a crash.

**Comment by artisteacher** [comment]
I get a crash in macOS too.
