### ISSUE TITLE
Crash after a while, Raster pen gets red after saving

### ISSUE THREAD

**Issue by mm-gh** [opentoonz/opentoonz#2886]
### Issue Summary
The app drops after a while when I draw on raster levels. Before it happens, raster black pen becomes red after hitting Ctrl+S to save changes. The red drawings are saved as red, not just visual glitch in the viewer.
Levels the scene contains are approximately 40 with 5-10 frames each. It seemed this crash never happened when I had 5-6 levels and keyframes.

### Screenshot or Video Reference
Alternatively to screenshots or video I have error logs:

> Fault bucket 1847789359808747383, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0
>
> Problem signature:
P1: OpenToonz.exe
P2: 0.0.0.0
P3: 5c50fbf9
P4: tnzcore.dll
P5: 0.0.0.0
P6: 5c47d40d
P7: c0000005
P8: 0000000000127cea
P9: 
P10: 
>
> Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCA2F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCBA7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCBC8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCBC6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCBE6.tmp.txt
>
> These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OpenToonz.exe_1f912d13a88f9e8027ac6efe9e9653302c941949_5ea4e6b0_c7fbad4e-93c9-41eb-b84a-716b78fd7b27
>
> Analysis symbol: 
Rechecking for solution: 0
Report Id: ba0ff4cd-70f4-4599-9614-150665ff8312
Report Status: 268435456
Hashed bucket: 934511a3fbae65b4b9a4aaa1fb259777
Cab Guid:  #0

_

### Steps to Reproduce
Install OpenToonz, Change some environments & preferences & keyboard shortcuts
Create a new scene, New raster level, draw 40+ levels, make frames for inbetweens on each keyframes (a single column)
Ctrl+S to save & Hotkeys to jump around the keys & Toggle onion skins (many times while drawing)

### Expected Results
No more crashes! So I wouldn't have to clear Temp & re-open every 10 minutes...

### Actual Results
App keeps dropping about every 10 minutes

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Windows 10
* **CPU**: Intel Core i7-8650U CPU 1.9GHz & 2.11GHz
* **Memory**: 16GB
* **Graphics Card**: Intel UHD Graphics 620
* **Graphics Tablet**: Surface Pro 6, Surface Pen, Wintab

**Comment by artisteacher** [comment]
If you've been using 1.3, I would recommend trying [the latest nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly). There have been a huge amount of bug fixes. Due to certain updates, you'll want a clean install. I would rename your stuff folder before installing so that you have a backup & can move projects or etc. to the new stuff folder as needed.

**Comment by RodneyBaker** [comment]
Largely unrelated but just for informational purposes...
Are you using Autosave and if so how frequent is the setting?

**Comment by mm-gh** [comment]
Thank you guys! I will definitely check out the Nightly Build ver.
Apparently the crash surprise less often happens now (Only when I operate
it multiple for a second while OT works on the prev action)
Rodney I don't use Autosave but Ctrl+S is my habit and I do almost every
minute after a few changes.

2019年11月19日(火) 5:52 Rodney <notifications@github.com>:

**Comment by RodneyBaker** [comment]
@mm-gh Did you get better results with the nightly release?

**Comment by RodneyBaker** [comment]
The color change sounds a little like this #1122 although there are several other things that we should rule out also.

**Comment by artisteacher** [comment]
If the color change refers to toonz raster (green) rather than standard raster (blue), it could be a palette issue. I recently was dragging and dropping a palette from the studio palette & then using it on multiple levels. The next time I opened the scene, all of those styles displayed as red. I hadn't realized drag & drop didn't actually load the palette...

**Comment by mm-gh** [comment]
Thank you everybody. Somehow I haven't encountered any crush or red pen
issue anymore since then, but once I spot it I will definitely go for the
nightly versions and these workarounds. Thank you!

M

2019年12月5日(木) 6:33 artisteacher <notifications@github.com>:
