### ISSUE TITLE
All Layers Not Rendering

### ISSUE THREAD

**Issue by Nitren27** [opentoonz/opentoonz#2895]
My animation around 1850 frames is not rendering all of my layers when I finished the animation. I have a few raster levels and Toonz raster levels and some normal ones. But the first time I preview my animation, you could only see one level. I played with Opentoonz adjusting some things and then when I previewed it again you just couldn't see anything. I've also had some issues were text tool will always change your text, even when you select a different color, to red in the inside. (Which I believe is related to my fill in tool which is stuck on red as well and I can't change it for some reason)

https://www.youtube.com/watch?v=dKYyXp_8s2A&feature=youtu.be Here is a video if that helps :D

**Comment by artisteacher** [comment]
You may want to remove the private setting from the video - it's not currently viewable.

There are a few reasons why some of your levels may not render:
- In the column header, make sure preview/render visibility is turned on (green eye icon)
- If "show lines with thickness 0" is turned on in Preferences -> Visualization, any vector lines drawn with the brush size at zero will be visible in the workspace but not display in the render. You can use the select tool set to "Whole Level" and use the pump function (black line in the bottom right corner of the selection box) to increase the line thickness above 0
- If any columns got disconnected from the XSheet in the FX Schematic window, they would not display in the render
- Certain FX can impact visibility, depending on how they are used

As far as the red fill goes, I'm not sure what's going on. A first step in troubleshooting would be to deselect all of the checks under the View menu to see if that has any effect.

**Comment by Nitren27** [comment]
Thanks! I tried everything and made sure the preview/render visibility was turned on but your second bullet/idea/suggestion I couldn't really understand and find. Also did you get the video? It should work now... Please reply back soon!

**Comment by Nitren27** [comment]
Oh! and when you suggested turning off all selected checks under view menu, the paint/fill in tool is now working properly so thank you so much for that!

**Comment by manongjohn** [comment]
Look in the Fx Schematic window and make sure all nodes lead to the same Output node and the node is Active (blue).

**Comment by Nitren27** [comment]
wat?

**Comment by manongjohn** [comment]
In OT:  Windows menu -> Schematic
In Schematic window, click on bottom right button to switch to the Fx Schematic.

All your nodes should eventually lead to 1 active Output node.  Something like this:

![image](https://user-images.githubusercontent.com/19245851/69485889-3552ae80-0e13-11ea-937e-413360b93762.png)

Usually only have 1 Output, but it's possible you might have created a second one. The blue one is the active one.

**Comment by Nitren27** [comment]
WAIT watttttttttttttttttttttt

**Comment by Nitren27** [comment]
I was playing with that and I got it to work but then now it's not working XD

**Comment by Nitren27** [comment]
for some reason when I was adjusting that it worked but then when I tried it again it didn't ;(

I'm trying to fast render it because when I rendered it out as seperate jpegs it had all of the levels except towards the end were I stopped it, so I'm gona check to see if it will work...

**Comment by Nitren27** [comment]
I DID IT!!!!!!!! I mean you did it!!! thanks soooooooooooo much! I guess It all wasn't connected! You saved sooo much time! Thank you soo much!

**Comment by Nitren27** [comment]
I have been trying to fix it with my father but he and I couldn't figure it out for 2 weeks XD

**Comment by manongjohn** [comment]
Glad you figured it out. :)

For future reference, the best place for troubleshooting help would be to use [Google Forum](https://groups.google.com/forum/#!forum/opentoonz_en).  There are also other community driven OpenToonz sites (Discord, Reddit, Facebook) where you can get help as well.
