### ISSUE TITLE
Insert Multiple Keys Crash

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2896]
### Issue Summary

Using the "Insert Multiple Keys" command from the context menu in the Xsheet, sometimes results in a crash.
### Screenshot or Video Reference

[multiple_key_crash.txt](https://github.com/opentoonz/opentoonz/files/3880060/multiple_key_crash.txt)

### Steps to Reproduce

Right-click on the frame number area for a frame that is not active/selected and select "Insert Multiple Keys"
### Expected Results

Multiple keys to be inserted
### Actual Results

A crash
### System Information
* **OpenToonz Version**: recent nightly builds
* **Operating System**: macOS 10.14.6
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
I confirm the crash when following the steps you outline:

**Comment by artisteacher** [comment]
Yeah, I wasn't getting crashing right away either. Hopefully this is a little more clear - the trick is to try to insert multiple keys for a frame that isn't active. Ie. if a cell is selected for any level/column in the first row and you try to insert multiple keys for row 32, you get a crash. If you select a cell in row 32 before trying to add multiple keys at frame 32, no crash.

It's usually my students that find the problems! They all seem to have a talent in finding ways to crash OT. The big issue is that it's often not clear what the crash is actually from.
