### ISSUE TITLE
Phantom Fill Check

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2902]
### Issue Summary

When you collapse multiple columns in sub-xsheet, empty columns with the same numbers still show the “Fill Check” data for the old columns. If you create new columns in place of the old ones, then in addition to the closed areas of the current level, they will also display gray shading of those levels that are in the sub-Xsheet in the columns with the same numbers.
### Screenshot or Video Reference

![ezgif-1-0cd537627a3d](https://user-images.githubusercontent.com/25724133/69494792-5f19dd00-0ec8-11ea-8843-c7bcfe615c2a.gif)

Moving columns inside sub-Xsheet also affects columns outside sub-Xsheet.

![ezgif-1-49504e7ffd04](https://user-images.githubusercontent.com/25724133/69494797-6e008f80-0ec8-11ea-9712-1f3d4643d013.gif)

### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by RodneyBaker** [comment]
Assuming this might be a refresh issue, do you get the same results if you Save All after the merge and then navigate around the columns?
