### ISSUE TITLE
(Discussion) Ideas for improving Palette

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#2909]
I have two suggestions on how to improve this panel.

1. Let's add small square color icons? Now the smallest icon is a rectangle. Square icons help put more, as is done in the Premium version.

### Screenshot or Video Reference
![image](https://user-images.githubusercontent.com/25137502/69826106-bdc1bc80-1222-11ea-9c8f-d273ed452681.png)
![image](https://user-images.githubusercontent.com/25137502/69826114-c7e3bb00-1222-11ea-873a-9a5650453a63.png)

2. I think it would be more convenient for new users to add the "New Style" through the rendered icon with a plus sign. This will be clearer for new users.  This system is used in some programs and this facilitates understanding.

### Screenshot or Video Reference
![image](https://user-images.githubusercontent.com/25137502/69826364-d8486580-1223-11ea-93ae-6b363cbe158d.png)
![image](https://user-images.githubusercontent.com/25137502/69826386-edbd8f80-1223-11ea-826b-4fe7c7dfd21b.png)

**Comment by RodneyBaker** [comment]
Closing but please continue discussion here in this topic.
There is much that can be done to improve the user experience with Opentoonz palette workflow.

**Comment by artisteacher** [comment]
I think the tricky thing is that the swatches are styles - not strictly colors. The swatches need to be have room to show the color and the brush at the same time.

Adding new styles and possibly also new tabs would be better with a plus button directly next to the last style (or tab).
