### ISSUE TITLE
Black Camera Capture view

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2922]
### Issue Summary

The Camera Capture view window is always black. The feature does function - photos can be taken, but you can't see what you are doing. This could be related to #1834.
### Screenshot or Video Reference

<img width="911" alt="Screen Shot 2019-12-05 at 9 43 17 AM" src="https://user-images.githubusercontent.com/21159116/70245372-f510fb80-1743-11ea-9fe7-a24876e715fe.png">
For some reason the screenshot shows white instead of black...

### Steps to Reproduce

1. Open the camera capture window
2. Select the internal camera

### Expected Results

To see what the camera sees.
### Actual Results

The window stays black. Using onion skin makes no difference.
### System Information
* **OpenToonz Version**: latest nightly build
* **Operating System**: macOS 10.14.6, 10.15.1
* **CPU**: 
* **Memory**: 
* **Graphics Card**: Intel UHD Graphics 617 1536 MB; Radeon Pro 460 & Intel HD Graphics 530 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
I'm not seeing this issue on a PC with latest nightly release.
Just in case...
If you haven't tested on a nightly AFTER a quick fix for the recent Preferences update please try again.
There were some problems that slipped through that needed to be addressed.

**Comment by artisteacher** [comment]
Still an issue on macOS - at least for Mojave & Catalina.

**Comment by piotrnikov** [comment]
Hello,
I can confirm that this is still not working on my setup also (Macbook Pro 16, Catalina 10.15.2.

**Comment by shun-iwasawa** [comment]
I could reproduce the problem. It is probably due to changes done by me.
Sorry for the trouble, I'll look into it.
