### ISSUE TITLE
(Discussion) Reorganize Preferences

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#2923]
Now that #2894 (Overhaul Preferences) has been merged it will be good to take a look at the organization of tab, menus and workflow.  There are three primary timeframes to consider in this:

**Short Term** (Reorganize Preferences for v1.4 release
- [ ] Correct any typos and irregularities
- [ ] Move color option on Saving tab to Color tab (as appropriate)
- [ ] Research Best Practices for Preferences
etc.

**Mid Term**
- [ ] Fully document Preferences (what options available, what they control, etc.)
- [ ] FFMPEG:  Resolve path issue for PC, Mac and Linux
- [ ] All tab:  Repeat every Preference option all via a single tab with scrollable options (if desired)
- [ ] Determine best way to organize/present options that require restart
- [ ] Research ways to allow Preferences that require restart to be changed without restart
etc.

**Long Term**
- [ ] Search function, full customization and Optimization
- [ ] Initiate Best Practices tailored to Opentoonz users
- [ ] Present cutting edge implementation of Preferences; be the example for other software to follow
etc.

As suggestions are made we'll update this listing.
Items listed are for discussion and consideration... not necessarily for implementation.
Short, mid and long term timeframes are defined by developers.
Items can move between terms based on interest and feasibility.
There is no guarantee that any item will be implemented.

**Comment by artisteacher** [comment]
I agree that some reorganization might be beneficial. I think the challenge is that some of the categories have a lot of overlap. Under "Loading" there are a lot of import options yet there's also "Import/Export" which is FFmpeg related. Similarly, while there is a "Colors" tab, there are also colors under "Saving", "Xsheet", "Preview", and "Onion Skin".

**Comment by RodneyBaker** [comment]
Regarding the Import/Export tab...

If there are no legal considerations preventing such a thing, it would be nice to have a dedicated FFMPEG tab.  This might seem to be overkill for the number of options there currently but considering the ffmpeg and the long term there is much more that can be added to an FFMPEG tab.

Having a dedicated FFMPEG tab would then free up Import/Export to either be removed or to inherit options from other tabs.  IO (input/output) operations are many and varied and I can see that tab as (eventually) being a very useful.

**Comment by RodneyBaker** [comment]
Closing this but the discussion can continue.
It isn't likely that much of this will take place until 2020 development cycle.

**Comment by RodneyBaker** [comment]
Keeping this closed as @manongjohn has stated he plans to open a report on updating Preferences.

**Comment by MrBlockCat** [comment]
The Preferences typos/irregularities should be fixed with #3187!
