### ISSUE TITLE
Allow Manual Re-Timing of a Keyframe Sequence in X-Sheet with Predictable Results

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#293]
Please create the option for selecting and dragging a series of selected Keyframes in the X-Sheet that perform and encompass the following behaviours:

1)  Keyframe selections can be made by means of the Shift key or the Ctrl key (Cmd on Mac) - whether a frame is highlighted or not, in the X-Sheet.  (It should be the click on the Keyframe symbol that informs the software that a Keyframe operation is commencing).

2)  After a Keyframe sequence is selected, Left Clicking and dragging this selection of Keyframes moves that sequence anywhere in the Column without disturbing the position of other Keyframes in that Column.  (this behaviour already exists).

3)  (Alternately), if a sequence of selected Keyframes is Left-Clicked and dragged while the "Alt" key is held down, all successive Keyframes are "pushed" downward in the X-Sheet Column, maintaining their existing distance from the last Keyframe in the selected Sequence. (As a result, a "Hold" is placed on the last Keyframe that precedes the first selected Keyframe in the Sequence in question).

4)  Middle Clicking and dragging a selected sequence of Keyframes "stretches" this sequence of Keyframes proportionately, thus lengthening or shortening it - and having the additional behaviour of "pushing" or "pulling" the successive Keyframes with it - maintaining their previous "distance" from the last Keyframe in that selected sequence.

Implementing these features in the X-Sheet will give OpenToonz all the power of those "competing" applications that utilize a powerful Timeline and its associated functions, while maintaining a familiar X-Sheet based animation interface.

If more clarification is needed, please ask.

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
