### ISSUE TITLE
The program does not start and gives an error. 

### ISSUE THREAD

**Issue by Acaunt** [opentoonz/opentoonz#2933]
The program does not start and gives an error. Previously, this was not a problem, it appeared about two weeks ago.

### Screenshot or Video Reference
![image](https://user-images.githubusercontent.com/58738349/70539238-73bace00-1b74-11ea-9adc-af2f37b183e6.png)

### System Information
* **OpenToonz Version**: The latest version of the nightly build.
* **Operating System**: - windows 10

**Comment by artisteacher** [comment]
You may have already done so, but I recommend trying a clean install. Rename the stuff folder as a backup, uninstall the current OpenToonz installation, and then try installing the latest nightly build.

**Comment by RodneyBaker** [comment]
It does look as if you got a bad installer or the installation somehow was corrupted.
The notification of 'Available platform plugins are:  minimal, offscreen, windows' is particularly odd.

Please update us on your progress with the results of a new (preferrably clean) install at your earliest opportunity.

Here's a link to one of the most recent nightlies:
https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_664f79d5a63c4e0df707ea33a5a4919bbe245d4a/OpenToonzSetup.exe

**Comment by RodneyBaker** [comment]
Until such a time as it can be determined there is an actual bug involved in this issue let's close this report and explore the problem further via the Opentoonz Troubleshooting forum:

https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting
