### ISSUE TITLE
After grouping, the Tape Tool does not connect ungrouped vectors.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2937]
### Screenshot or Video Reference

![ezgif-6-8dd207006146](https://user-images.githubusercontent.com/25724133/70665883-33437900-1c76-11ea-80ed-97468e08bff6.gif)

### Steps to Reproduce

1. Draw three vector strokes in the same order as in the video.
2. Select and group the middle stroke (RMB> Group)
3. Using the Tape Tool, try connecting the first stroke to the third. For some reason this is not possible, although neither the first stroke nor the third is grouped.
### Expected Results

Vectors must connect as they are not grouped.
### Actual Results

Vectors do not connect
### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by melieconiek** [comment]
I have experienced this. The affected strokes won't properly close regions either and will cause problems with fills. They seem to behave as if they in a group.

**Comment by gab3d** [comment]
confirmed here

Windows 10
nightly from Nov 18

**Comment by RodneyBaker** [comment]
Interestingly, this error only seems to occur with three strokes.
If we try four, five... apparently any other number other than three strokes the Tape Tool will work.

This suggests an interim workaround to avoid the issue would be to create one additional vector stroke to allow Tape Tool connectivity.

**Comment by melieconiek** [comment]
@RodneyBaker this bug most certainly occurs when there are more than three strokes in a drawing--I can't use groups on clean linework at all because of it.

Please remove this misinformation from this bug report.

**Comment by RodneyBaker** [comment]
I'm reporting what I'm seeing.
I'll try to record a session and show the results.

Using a variety of the latest nightly releases here.

**Comment by gab3d** [comment]
(it happens to me with more than three strokes, using Nightly from mid November I think)

what I experience is as if the strokes drawn "before" the grouped one can connect between themselves, and the ones "after" the grouped one can also connect between themselves, but the snap won't work from a stroke in "one side" to one in the "other side".

**Comment by RodneyBaker** [comment]
You may have hit on something with the order of strokes drawn.
If I draw three strokes but not left to right... say left... right-most and then center... then group the center stroke... the outer strokes will tape together.

**Comment by manongjohn** [comment]
Comment hidden. A user is reporting it's still an issue
