### ISSUE TITLE
Batch Rendering fails

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#2940]
### Issue Summary

On macOS, batch rendering through the tasks window fails.
### Screenshot or Video Reference

<img width="1035" alt="tasks" src="https://user-images.githubusercontent.com/21159116/70870801-e3123280-1f65-11ea-87c2-661e84d57a43.png">

### Steps to Reproduce

1. At the top of the Tasks window, click on "Add Render"
2. Select a scene
3. Click on the start button or right-click on a task & select "start"
### Expected Results

The render to be successful.
### Actual Results

The render fails. If you look at the path in the screenshot, the path uses OpenToonz_1.3.app instead of OpenToonz.app. Since the app no longer uses the version number as part of the name, that is likely the cause of failure.
### System Information
* **OpenToonz Version**: latest nightly, most recent OTX
* **Operating System**: macOS 10.15.1
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
Unfortunately batch rendering through Tasks still fails, even with the app name corrected in the path. Either I'm missing a step or there's something else going on. 

Since there's a command line field, I decided to try batch rendering from Terminal - I'm not sure if it should work. First of all, tcomposer can't be found when using this path directly in Terminal: "./OpenToonz.app/Contents/MacOS/tcomposer". 

Using "Applications/OpenToonz.app/Contents/MacOS/tcomposer" will begin to work but runs into an error:
<img width="626" alt="Screen Shot 2019-12-15 at 11 46 56 PM" src="https://user-images.githubusercontent.com/21159116/70880317-854a0e80-1f96-11ea-847c-86e92406e1cb.png">

**Comment by artisteacher** [comment]
It seems like there can be issues using @rpath on macOS, depending on how it is set up.
[https://blog.krzyzanowskim.com/2018/12/05/rpath-what/](https://blog.krzyzanowskim.com/2018/12/05/rpath-what/)

From toonz/sources/toonzlib/CMakeLists.txt:
<img width="694" alt="Screen Shot 2019-12-16 at 8 46 36 PM" src="https://user-images.githubusercontent.com/21159116/70957810-4e7f0180-2045-11ea-9949-cafe0b9280d6.png">

**Comment by RodneyBaker** [comment]
I can't help but wonder if this somehow relates to MacOS security process where an application has to be flagged appropriately in order to run.  What I mean by that is how Opentoonz launches a command line instance of tcomposer.exe to run in the background and... might this run afoul of security practices?

**Comment by artisteacher** [comment]
It's always possible...

Whatever the cause, it would be helpful to get this running. I'm hoping batch rendering will be more stable than normal rendering on macOS. My students have started joking that the "OpenToonz closed unexpectedly" crash notification should read "OpenToonz closed expectedly".

**Comment by RodneyBaker** [comment]
We certainly need to get those direct rendering issues investigated.
Users shouldn't need to resort to batch rendering to work around primary rendering processes.

**Comment by artisteacher** [comment]
This fails on OTX and the Morevna release too. Since the Morevna release lists 1.2 instead of 1.3, I wouldn't expect it to work anyways.

**Comment by manongjohn** [comment]
> My students have started joking that the "OpenToonz closed unexpectedly" crash notification should read "OpenToonz closed expectedly".

Sorry to say, but that made me chuckle. 

Unfortunately it's difficult for me to reproduce some of these issues in my macOS VM enviroment and compiling in Xcode directly somehow masks some of the issues making it nearly impossible to debug the real cause. ☹

**Comment by artisteacher** [comment]
> Sorry to say, but that made me chuckle.

It made me laugh too.

> Unfortunately it's difficult for me to reproduce some of these issues in my macOS VM enviroment

I really appreciate the effort!

**Comment by artisteacher** [comment]
I just tried building with #3038. On a positive note, I did not get the warning about "@rpath/libtoonzlib.dylib" not loading when trying to render from command line. I did get a similar error:
`dyld: Library not loaded: @rpath/libtnzcore.dylib`
`Reason: image not found`

**Comment by artisteacher** [comment]
@damies13 - you did a lot of work to get the farm working on macOS. Have you had any luck with batch rendering without setting up a farm?

**Comment by damies13** [comment]
Hi Guys, sorry for the delay in responding, I just saw this message.

it's been quite a while since I looked at Opentoonz, between work (when I can get it) and my own project I haven't had the time, plus my daughter never ended up using it, she preferred a commercial product so my motivation was reduced.

If I remember correctly you need to do was run tfarmcontroller on at least one machine in the farm and tfarmserver on the other machines in the farm pointed at the tfarmcontroller and tcomposer gets launched by tfarmserver for each job being processed. So for a single machine you would need both tfarmcontroller and tfarmserver running if my memory serves correct.

I just downloaded the latest version (1.4) from https://opentoonz.github.io/e/ and installed it and I am getting:

```
$ ./tfarmcontroller -h
dyld: Library not loaded: @rpath/libtfarm.dylib
  Referenced from: /Applications/OpenToonz.app/Contents/MacOS/./tfarmcontroller
  Reason: image not found
Abort trap: 6

$ ./tfarmserver -h
dyld: Library not loaded: @rpath/libtfarm.dylib
  Referenced from: /Applications/OpenToonz.app/Contents/MacOS/./tfarmserver
  Reason: image not found
Abort trap: 6

$ ./tcomposer -h
dyld: Library not loaded: @rpath/libtoonzlib.dylib
  Referenced from: /Applications/OpenToonz.app/Contents/MacOS/./tcomposer
  Reason: image not found
Abort trap: 6

```

So clearly something is broken on MacOS at least on 11.1 (BigSir) anyway

Dave.

**Comment by artisteacher** [comment]
It is broken on Catalina and Mojave too. I've tried to get this working for Tahoma, but with the path issue fixed, tcomposer still crashes:
[https://github.com/tahoma2d/tahoma2d/issues/97](https://github.com/tahoma2d/tahoma2d/issues/97)

**Comment by damies13** [comment]
I hope this question is not out of line, and if it is I apologise but I guess it is worth asking: 

How important of a feature is the render farm to people, would some one or a couple of people be willing to [sponsor](https://github.com/sponsors/damies13) me to spend the time needed to make it work well and improve it?

To put this question in context, my current day job is performance testing (simulating 1000's of users logged into application servers) of enterprise applications, but I work on contracts, usually when a project ends my contract ends, and I move on to the next organisation and next project, but 2020 has been a difficult year for me like many other people, as there have not been many projects around it's been hard to get work, when I'm not working I put 100% effort into finding my next contract, so no effort in projects like this, when I have work I put time into open source projects in my spare time and work on what interests me at the time.

If someone or a few people can [sponsor](https://github.com/sponsors/damies13) me enough that I don't need to stress about getting work I can use the time I would have been working to work on this project. 

Firstly I would get the render farm working again and then work on improving it.

I have ideas that would enable both cross platform rendering (i.e. your render farm could be Linux servers and your desktops could be a mix of Windows and Mac) and external render farms, imagine being able to run up say 30 render servers on AWS or Google compute for a few hours when you need the extra render capacity and then just shut it down when you don't, so you'd only pay for the extra rendering capacity for the few hours you need it.

**Comment by RodneyBaker** [comment]
Dave,
Consider yourself sponsored.
Thanks for your effort in the past as well as the prospects of more in the future.

I will also recommend that you contact the folks at Morevna who are working on RenderChan support for Opentoonz.
I'm not sure to what extent the internal Opentoonz rendering process (esp. Renderfarm) and RenderChan can be made more compatible but it would be good to at least know what the ecosystem looks like going forward.

For my part I currently have limited use for a full renderfarm but I do often use Task Rendering via the Farm Room and my single computer.  This seems to me to be more then niche for most Opentoonz users whereas the fuller renderfarm would be of definite interest to studios and to users who are deep into production.  I can easily see where renderfarms could be useful for educational institutions as well.

My sponsorship won't get you far in your effort but perhaps others with interest in seeing Opentoonz develop will join in the effort.  This can also be a good test case for future sponsorships of other developers as well.

Aside:  I note your interest in screen capture and that is of interest to me as well... specifically from the standpoint of a user being able to document their use case and submit the resulting video to resolve a problem with Opentoonz.  Further to this I note that often what is already rendered on screen via playback is adequate for my needs and therefore screen recording fits well into the pipeline of rendering in that it can save users the requirement for more extensive final rendering whether to regular rendeing output, to task/batch rendering, to render farm via networks of computers as well as what you suggest with regard to online rendering services.  I would like to think that there is a need for the latter but thus far to date I have not seen evidence of that level of rendering requirement in the Opentoonz community.  We are still a growing community though! 

All this to suggest that I don't know the full scope of your interest in developing Opentoonz and am perfectly willing to increase my sponsorship to see the rough edges of rendering pipeline get smoothed out for Opentoonz users.

All this to say I like what you are suggesting and you have my support.

**Comment by RodneyBaker** [comment]
Also @damies13, if testing Opentoonz I highly recommend using the latest nightly.
While I don't think much has changed with regard to render farm since Jan 2020 there have been a ton of changes since then and those would be captured in the nightly releases. 

Link to Nightly Releases:
https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by artisteacher** [comment]
I was hoping that some of the recent updates would have an impact on Task rendering. It seems there is another missing library:
<img width="1243" alt="Screen Shot 2021-03-15 at 11 44 48 PM" src="https://user-images.githubusercontent.com/21159116/111252870-73677900-85e8-11eb-9302-77fd7779c71e.png">
