### ISSUE TITLE
Frame numbering when using Duplicate Drawing

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#2944]
### Issue Summary

I want to pay attention to how two related functions work: Duplicate Drawing and Create Blank Drawing in Autocreation mode: Use Xsheet As animation Sheet (watch the video) In this case, the Duplicate Drawing function does not take into account the current frame number, but creates a duplicate with the following sequence number, that is, after applying the duplication operation, you must always apply Autorenumber so that there is no confusion in the Level Strip.
### Screenshot or Video Reference

![ezgif-6-35c34744afa1](https://user-images.githubusercontent.com/25724133/70915635-dbfd2a00-2022-11ea-8281-aaa610133b53.gif)

### Expected Results

In my opinion, the Duplicate Drawing function should follow the frame numbering as well as Create Blank Drawing so that these two operations can be used harmoniously and logically.

### System Information
* **OpenToonz Version**: latest
* **Operating System**: WIndows 8.1

**Comment by artisteacher** [comment]
I agree!
