### ISSUE TITLE
Mini Level Strip for Cel Input Context Menu 

### ISSUE THREAD

**Issue by hayoko** [opentoonz/opentoonz#2948]
Actually, @gab3d came up with a better layout for this, [read his comment](https://github.com/opentoonz/opentoonz/issues/2948#issuecomment-566867505).

![image](https://user-images.githubusercontent.com/36535462/71328305-0eb88e00-250d-11ea-90ac-4a917da36cac.png)

My own suggestions to this would be...
- Hovering the number changes the thumbnail image on the fly.
- Single-click is all that is necessary to input the drawing into the cell.
- Clicking anywhere outside the area cancels and closes the widget.

---

**Original Request**

This is something you can find in Clip Studio Paint, if you right-click a timeline cell it brings up a context menu containing a list of all available drawings contained within that level.

In our (very small) studio we primarily use Clip Studio Paint, so I guess we are accustomed to working with the Clip Studio Paint timeline now, that when it's time to continue working in OpenToonz it's a bit unfamiliar.

**How would it function?** When you right-click the cell to open the menu the input box is in focus, so if you type a number and hit return it will input that number into the cell. Or you can select a drawing from the list and hit return.

![inputconcept](https://user-images.githubusercontent.com/36535462/71047979-81a0be00-2135-11ea-8742-e7c32bf308f6.png)

**Comment by gab3d** [comment]
The idea is not bad for quick inserting of level drawings in the xsheet/timeline, when there's no previous certainty of which number the desired drawing really has.

I'd make the UI for this feature as simple as it could be...
Starting by not having to access the full RMB menu in first place, to trigger it.
Perhaps just using a well thought out keyboard shortcut, then the [arrow keys/mouse wheel/LMB click and drag] for cycling through the existing frame numbers, then [Enter/LMB click/release LMB] respectively for accepting and auto close the UI.
(Also, if user moves the mouse cursor out of the UI area, it would auto close too).

a quick and dirty mockup of the UI I imagine, for such a feature:
![mokup](https://user-images.githubusercontent.com/18104091/71056773-3be5f480-2139-11ea-998f-92cd70ed29f1.png)

**Comment by Acaunt** [comment]
Very cool and useful feature in Flash. "Frame Picker"

![image](https://user-images.githubusercontent.com/58738349/71073623-cbb78d00-2191-11ea-92e0-2bd3784364d8.png)

https://www.youtube.com/watch?v=nNlIsln7Gmc


https://www.youtube.com/watch?v=ErSU7PqAi40


https://helpx.adobe.com/animate/using/symbol-instances.html

**Comment by Acaunt** [comment]
We in the studio use this tool to animate all parts of the body.

**Comment by beeheemooth** [comment]
Guys, I have a feeling that you are finally re-invent Level Strip. I also use CSP, and, in my opinion: this way of choosing a drawing there is very inconvenient.
This is the way Acaunt offers it better (I remember a plugin in Flash called Keyframe Kaddy) and looking at it, I think it most likely looks like Level Strip's ability to arrange drawings in several rows. However, if you do this, you will need to solve some problems specific to working with Level Strip, for example, how to put Onion Skin markers, how to select several frames, how to do inbetweens, e.t.c.

**Comment by Acaunt** [comment]
This feature is very convenient for sub-Xsheet. So we use this function for symbols.
@beeheemooth

**Comment by beeheemooth** [comment]
@Acaunt In OT, frames located on the Xsheet can already be considered symbols, for that they are not required to collapse.

**Comment by gab3d** [comment]
@beeheemooth 
well... speaking for my mockup, I'd say no.
Mainly because it'd be just a popup aid for knowing what number to insert in a cell, and just that.

I do see how the other UIs proposed are much more complex and not just a simple popup but whole panels that can remain opened until the user specifically closes them. 🤔

**Comment by hayoko** [comment]
@gab3d That's really good, much better than the CSP way, I imagine hovering over the number would change the thumbnail image and a single-click would input and close it, very fast.

![image](https://user-images.githubusercontent.com/36535462/71092829-ea248500-219f-11ea-8413-6fc26e085a51.png)

* I wouldn't want it to close when cursor exits its small box though, just for drawing screens sake, I know some older people who have the hand shakes, clicking anywhere outside to cancel would be perfect.

The Flash comments could be better suited for the level strip itself, or a new window with the functionality, I've seen a few people express that they want symbol/library support now, but since I don't use Flash I couldn't really comment.

**Comment by RodneyBaker** [comment]
Updates to the Level Editor would very likely makeit an equivalent to the Keyframe Caddy so recommend that be considered for development to that end.  It already has most of the necessary foundation upon which to implement that functionality.

I like the simplicity of @gab3d's mockup as a 'mini level strip' attached to Timeline/Xsheet.
Perhaps the top option of that numbering could trigger opening of the full Level Strip (and therefore the Keyframe Caddy capability once that is added).

**Comment by artisteacher** [comment]
I also really like @gab3d's version. I wonder if it could be linked to the current w/q shortcuts for frames sliding forwards or backwards.

**Comment by beeheemooth** [comment]
@gab3d you can look for the necessary drawing by scrolling them in the Skeleton Tool, is this method bad?

**Comment by artisteacher** [comment]
@beeheemooth the skeleton tool isn't especially helpful for that in macOS - the numbers are very, very small - I always forget they are there. We can also scroll through the drawings with shortcuts w/q. Sometimes it can be tricky to find the exact drawing you are looking for when cycling through, especially if a couple drawings are similar. Sometimes it is just time consuming if you have a large number of drawings. I can see this proposal being helpful when you've lost track of what you are looking for, or for more quickly switching to a frame that is not nearby.

**Comment by RodneyBaker** [comment]
Some of the code from the Skeleton Tool can likely be used for this new proposal.

**Comment by beeheemooth** [comment]
@artisteacher nothing prevents you from manually numbering frames, as they do in traditional animation, and scrolling through them at any speed. If you know the frame number exactly, you will find it in a couple of seconds. On Windows, the numbers are also small, but it seems to me that their size is sufficient not to interfere with the review, because sometimes you need to scroll through frames of fairly small details, for example, the phalanx of the fingers.
![ezgif-6-58d5320b872d](https://user-images.githubusercontent.com/25724133/71115660-1a3d4980-21db-11ea-9d7a-c60afc80b0da.gif)

**Comment by artisteacher** [comment]
@beeheemooth - your text looks about the same as the size of the header text - that's usable. On my screen, it's nowhere near that big - not easy to use.
<img width="108" alt="Screen Shot 2019-12-18 at 2 59 02 PM" src="https://user-images.githubusercontent.com/21159116/71118896-f8c26a80-21a6-11ea-8db7-ac00a55f52c9.png">

**Comment by DarrenTAnims** [comment]
My only issue with the selection of frames shown in the OP and from the skeleton tool (as shown above in Beehemooth's post) is that you can only see one image at a time, so you have to go through them slowly. The keyframe caddy style of selection is better as you can see all (or at least, lots) of frames, so you can pick the image much quicker.

**Comment by hayoko** [comment]
I got nothing against a frame picker, the level strip is already one, I think it just needs to be duplicated with a few tweaks. It's more useful for cut out animation though, since in traditional animation if the frame number is written on the page it's going to be too small to see and if the drawings are too close together they will look like duplicates, if the drawings are on 1's then it's going to be pointless, reading the drawing number (named by frame) as a list is going to be quicker, and it's how Disney taught it.

![image](https://user-images.githubusercontent.com/36535462/71321428-03d01000-24b1-11ea-8bb4-ae4fbf184716.png)

That's why in #2943 I think "strong renumbering" would be more orderly, that way it works like Harmony does with the auto name by frame number option. So it would look like this in OpenToonz...

![image](https://user-images.githubusercontent.com/36535462/71321474-adaf9c80-24b1-11ea-99f0-1b2923a883ff.png)
