### ISSUE TITLE
Minor bug - XSheet onion skin selection icon persists when the cursor has left the Xsheet.

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#295]
It is not a major problem but the selection marker persists on the final frame your cursor passes over when it leaves the XSheet.

![persistance](https://cloud.githubusercontent.com/assets/18170954/15243586/d13db520-18fc-11e6-8767-f2c6ff1fd594.png)

**Comment by psychoanima** [comment]
Yeah, confirmed. Not a big deal, but someone might find it annoying.
