### ISSUE TITLE
Crash and Lost the level.

### ISSUE THREAD

**Issue by kirin1019** [opentoonz/opentoonz#2952]
When I'm drawing,opentoonz crash with this and all of my level is lost.

![未命名](https://user-images.githubusercontent.com/58040958/71319536-96d17000-24da-11ea-851e-ca6f0f55e6ef.png)

This is not first time happened.
There is some way can save my level?

[A.zip](https://github.com/opentoonz/opentoonz/files/3992284/A.zip)

[E.zip](https://github.com/opentoonz/opentoonz/files/3992286/E.zip)

**Comment by RodneyBaker** [comment]
There doesn't appear to be much in the files to recover, especially the TLV file inside of E.zip which is only 2kb in size.  The A.tlv file is 38 kb so it might have some very basic data inside but...

If you are using current releases of Opentoonz you might have a backup or cache file that is recoverable.

**Comment by kirin1019** [comment]
Thank you !!!!
The .bak file is work!
I never think that is backup file🤣
Thank you so much!!!

**Comment by RodneyBaker** [comment]
It's great to hear that got you back on track.  :)
