### ISSUE TITLE
Add New Links in Help Menu

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2958]
I'm thinking about making a **What's New** section in the OT Manual, where all the Release Notes from each successive version were on display.
I also think it'd be great if the user could click on a **What's New** entry in the **Help** menu inside OT, to access directly to the correspondent section in the Manual to that version of OT.

I guess this would improve users' experience when upgrading to new versions, as well as would also help raising visibility of Release Notes, which currently are somewhat difficult to access once launch time has passed.

What do you guys think? 🤔

**Comment by RodneyBaker** [comment]
I think we need to move quickly to get any additional features into v1.4 (other than those being locked in now).

Hopefully you've been tracking the effort to include your other two requested links in the Help menu as well.

Perhaps this request can serve to promote all three.

**Comment by RodneyBaker** [comment]
For a 'What's New' link this might be the ideal final landing place:

https://github.com/opentoonz/opentoonz/releases

Keep in mind that it would very likely be more ideal to land in the Opentoonz Docs where the user would find a link to that location.  In this way changes could be made to links without resorting to updating Opentoonz code.  Instead, the link in the docs would be edited.

**Comment by gab3d** [comment]
@RodneyBaker 
yeah, the Manual landing page would be up in no time, if we decide to do it. 
That's more of a decision, than a technical implementation matter.

**Comment by gab3d** [comment]
> Keep in mind that it would very likely be more ideal to land in the Opentoonz Docs )as you suggest) where the user would find a link to that github release notes location. 

The other benefit of having this inside the Manual is that the Release Notes could include links to the correspondent manual page explaining each new feature, if pertinent.

Perhaps there could be a summary of the *main* new features there in the What's New section of the Manual, and a link to the full Github Release Notes page, for the rest of them. So to avoid duplication of work... 🤔

**Comment by gab3d** [comment]
Here's a tentative [What's New](https://opentoonz.readthedocs.io/en/latest/whats_new.html) page, up and running...

**Comment by RodneyBaker** [comment]
Looking good!

My primary concern is maintenance but... that's why we have a community!  :)

As new features will need to be documented anyway if the What's New section has links to documentation/sections for those new items...  it's all good.  Might even be a good way to flag documentation priorities for those that are keen to document new/enhanced features.

**Comment by RodneyBaker** [comment]
@gab3d 
You might want to comment (or not!) on @shun-iwasawa recent feedback on the Donation/Support link in Help menu.  Perhaps it might suffice to have a 'What's New' link to documentation where users could also find additional information on how to support Opentoonz etc. and cover the needs of the other two requested links?

Please see:  #2939

**Comment by gab3d** [comment]
> My primary concern is maintenance but... that's why we have a community! :)

No worries, I will maintain it.

> You might want to comment (...)

I just commented on it, but I also think that while the "What's New" is best placed as a Manual section, for flexibility reasons, the "Support OpenToonz" menu option would rather link to a page in the official site. 👍

**Comment by RodneyBaker** [comment]
Closing in light of #2948 moving forward.

Having the manual/online documentation have a 'What's New' Section/link at the very top of the landing page will not only allow users to connect to that information via Help Menu > Online Manual but will encourage them to visit the site frequently.

**Comment by gab3d** [comment]
Sorry @RodneyBaker , but #2948 isn't related to this one 🤔 

Besides that, I include here for reference screen shots of several programs that have both links to the "Manual..." and to "What's New..." (that usually is in that manual) in their Help menus.

The target here would be to "make easier", not to provide the "bare minimum needed". It is clear that an interested/versed user could find the What's New section in the Manual, but for that to happen he/she would have to know there is such a section and consciously try to find it.
The means of this kind of "obvious" helping is to:
- rise awareness, and to
- make easier to access

In the following images, it can be seen that Photoshop, Blender or Maya have both "Manual (Online Help)" and "What's New (Release Notes)" entries, as part of their helping system:
![photoshop](https://user-images.githubusercontent.com/18104091/71546501-290fc300-2976-11ea-93f5-8700a00ba474.png)
![blender1](https://user-images.githubusercontent.com/18104091/71546505-3167fe00-2976-11ea-8221-aa5f2459be13.png)
![blender2](https://user-images.githubusercontent.com/18104091/71546508-34fb8500-2976-11ea-95a0-fabd6726a9ff.png)
![maya](https://user-images.githubusercontent.com/18104091/71546510-388f0c00-2976-11ea-8f1e-98d371793640.png)



In that sense, a "Report a Bug..." entry in the Help menu would be also a good thing:
![maya_bug](https://user-images.githubusercontent.com/18104091/71546519-5e1c1580-2976-11ea-94b3-7dbdd053b63a.png)

**Comment by RodneyBaker** [comment]
Sorry.  Typo.
Please see:  #2939

**Comment by gab3d** [comment]
@RodneyBaker 
> Perhaps we should wait until after v1.4 release to add new Help menu links?
The full gamut of what you are requesting cannot be added in time for v1.4 release.

...the problem is, with a release cycle of 1 year, and the low level of complexity of doing this, I think it's a shame to have to wait a full year for giving users something so useful, yet so easy to implement, like these things.

Let's list them quickly, we're discussing about including in the **Help** menu some links to external URLs, mainly:
- **Online Manual...** (already done) [✔️] 
- **What's New...** (pointing to the What's New section of the same manual) [*trivial*]
- **Report a Bug...** (pointing to the GitHub Issues page of the OpenToonz project) [*trivial*]
- **Support OpenToonz...** (pointing to a page in the official website) [*depends on the page being created*]

So, of the three pending ones, only the last one hasn't got yet a proper landing page (Support OT), but even so, that does not technically preclude its completion on the OT side of things (it's just a matter to decide an appropriate landing URL name), then whenever the page with that name is ready, the option will be operational (...and that I'm sure this could happen in time for release, or in worst case scenario shortly after it, but never 1 full year after!) 🤔 

So I don't really see the point in procrastinating on these simple decisions... we should be able to nimbly deliver what is on our hands.

other one's opinions? 
Perhaps I'm misinterpreting the complexity of some of these?
Or someone think there are some unforeseen drawbacks in including them?

@shun-iwasawa @manongjohn @artisteacher @turtletooth

**Comment by manongjohn** [comment]
I think `What's New` should point to https://github.com/opentoonz/opentoonz/releases/latest.  This way they can also jump to hyperlinks for each of the new features to get more information

As for `Report a  Bug`, I'd like it to do something similar to Krita's Report a Bug link which opens a popup.

![image](https://user-images.githubusercontent.com/19245851/71550428-e95cd180-299d-11ea-9002-638c08347baf.png)

The popup should explain it's going to take you to the Issues page in github.  The Issues page should have a pinned post with guidelines for submitting issues.  

I started a draft a while ago but never posted it.  You can see it here: [guidelines - bug reporting.txt](https://github.com/opentoonz/opentoonz/files/4007558/guidelines.-.bug.reporting.txt)


I'd also like to suggest a `Community Forum` link which will take you to the official Google Community Forum
