### ISSUE TITLE
(Proposal) Move "Send to Back" to last position in menu

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2962]
The "Send to Back" option in the Arrange sub-menu should really be put last, to be more easily understandable by users. 

Order should be:
- Bring to Front
- Bring Forward
- Send Backward
- **Send to Back** 

Most design programs have it that way too.

This example is from Adobe Illustrator's manual:
![imagen](https://user-images.githubusercontent.com/18104091/71493727-e045f600-281f-11ea-9101-1fba1f4c1ffa.png)

**Comment by RodneyBaker** [comment]
This proposal just needs a yeah or nay so it is added to the 2020 UI scrub.

**Comment by gab3d** [comment]
yeah!  :))

**Comment by RodneyBaker** [comment]
As this proposal hasn't gained traction in two years will close as part of general housekeeping.
Let's reconsider the proposal as part of the UI scrub for 2022 development cycle.

**Comment by gab3d** [comment]
🤷🏻‍♂️
