### ISSUE TITLE
UI elements mis-scale to a huge size once a scene is entered

### ISSUE THREAD

**Issue by cyanne-git** [opentoonz/opentoonz#2965]
### Issue Summary
For one of my setups, OpenToonz has an issue with the UI that makes it impossible to use. Entering a scene turns the elements inside of the UI panes huge. There seems to be no way of making the UI usable again after this happens.

The issue occurs at any Windows scaling setting that I tried, including 150% and 100%. A clean re-install of the software has no effect.

### Screenshot Reference
<img width="1280" alt="graphicsissue_step1" src="https://user-images.githubusercontent.com/46541538/71557191-0371df00-2a86-11ea-9016-0beb27876608.png">▼ ▼ ▼
<img width="1281" alt="graphicsissue_step2" src="https://user-images.githubusercontent.com/46541538/71557192-066ccf80-2a86-11ea-9b78-17c0d81ebac7.png">

### Steps to Reproduce
**Reproduction A:**
1. Start OpenToonz — the UI looks normal
2. Enter a scene name in the OpenToonz Startup window
3. Press Create Scene
=> The contents of the various UI panes become huge.

**Reproduction B:**
1. Start OpenToonz — the UI looks normal
2. Close the OpenToonz Startup window
3. Select the Brush Tool
4. Draw something on the canvas
=> The contents of the various UI panes become huge.

### Expected Results
The UI stays the normal size.

### Actual Results
Parts of the UI scale to enormous size and are impossible to interact with properly.

### System Information
* **OpenToonz Version**: 1.3 stable, and latest nightly (Dec 29 2019 10:19:48)
* **Operating System**: Windows 10 Pro version 1909
* **CPU**: Intel Core i7-9700
* **Memory**: 32 GB
* **Graphics Card**: Intel UHD Graphics 630 (internal)
* **Graphics Driver**: 26.20.100.7463
* **Display resolution**: 3840x2160 (4K)

**Comment by manongjohn** [comment]
Based on your screenshots, this is likely the same problem as #2840.  I've also seen a few recent reports of this on other forums. 

As yet, we don't know what the exact cause is but it seem to point to something with Windows.  I wonder if some Windows or driver update is impacting OT negatively somehow.

**Comment by manongjohn** [comment]
Out of curiosity, since you are on a newer version of Win10, can you try the following:

1. Go to Windows Settings-> Graphics Settings 
2. Add the C:\Program Files\OpenToonz\OpenToonz.exe 
3. After it is added, click on `Options` button for it.
4. Select `High Performance`

This will force OT to use your GPU.  Not sure if it will help or not.

**Comment by cyanne-git** [comment]
Thanks for your response manongjohn.

It does seem like a similar problem to #2840. That issue report lists a GTX 970M as the graphics card, but their processor also has internal graphics so it's unsure which one is used for OpenToonz and produces the issue.

My computer is a small form factor build without dedicated graphics, so both the _Power saving_ and _High performance_ settings you suggested end up using the same internal UHD Graphics 630.

**Comment by manongjohn** [comment]
On some systems, OT doesn't typically use GPU effectively unless forced to by creating 3D profile settings in graphics cards or in Windows Graphics settings.  It's the only reason I suggested it.

**Comment by cyanne-git** [comment]
I see... Sadly it didn't fix it.

**Comment by manongjohn** [comment]
Thanks for trying.

**Comment by RodneyBaker** [comment]
Everything I see related to this error points to a driver issue.
I note that your driver isn't the latest in that series although I've read reports that users of Intel UHD Graphics 630 had to back down to the driver you are using to restore some necessary OpenGl support.

This makes me think you might have luck moving back a driver or two from where you are currently BUT... first... I'd check to see what newer drivers may be available.

**Comment by cyanne-git** [comment]
Hi Rodney,
>I note that your driver isn't the latest in that series

Intel Graphics Command Center says it's the latest version. I'll look into this.

 >We should have also asked if you have been using multiple monitors...

I have not, it is a single display setup.

**Comment by hayoko** [comment]
Sorry man, bugs like that suck, I've seen this before with Intel in other software based on Qt. I'd first try updating your driver if you can, if not, I haven't studied much Toonz code so I'm swinging in the dark here, but you can try adding some lines to your system (not user) environment variables ([how at superuser](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10)).

Restart the app each time you apply new variables.

Add new and as name set `QT_SCALE_FACTOR` and set the value to the same as the scale factor in your Windows settings for your monitor, if you've set it to '200%' then set the value to `2`, if you set it to '150%' then set it to `1.5`, you can also set any custom value you like (1, 1.25, 1.5, 1.75, 2), this will effect all Qt apps like VLC, etc.

Next try this boolean, `QT_AUTO_SCREEN_SCALE_FACTOR` and set it to value `0`, you can also try `1`.

Otherwise you can try `QT_HIGHDPI_DISABLE_2X_IMAGE_LOADING` and set it to a value of `1`, or `0` if that doesn't work.

If it helps, report back as the info might be useful for a patch.

**Comment by cyanne-git** [comment]
Good news:

Intel's graphics application indicated that 26.20.100.7463 was the latest version, but they indeed released a new driver earlier this month. I installed 26.20.100.7584 and the issue is hereby fixed.

Thanks everyone!

**Comment by RodneyBaker** [comment]
Outstanding news.
Thanks for the feedback as that is sure to assist others with similar issues they encounter.

**Comment by shun-iwasawa** [comment]
@cyanne-git 

> Intel's graphics application indicated that 26.20.100.7463 was the latest version, but they indeed released a new driver earlier this month. I installed 26.20.100.7584 and the issue is hereby fixed.

Thank you for the info. I have had the same problem with my Wacom MobileStudioPro13.
I couldn't catch the latest driver via Windows Update so I downloaded it from Intel's website and the problem get fixed.

**Comment by gab3d** [comment]
Shouldn't there be a **Troubleshooting** section in the Manual or the web site (what's best), where we can put some of these knowledge in? 🤔 
I'm sure it would be very useful specially to a lot of beginners (but not only).

**Comment by manongjohn** [comment]
A **Troubleshooting** section for issues beyond OT's control in the Manual seems appropriate to me.

**Comment by shun-iwasawa** [comment]
I'm also thinking of adding a notification for this just under the download button in the web site.

**Comment by Tsuenica** [comment]
> I've seen this before with Intel in other software based on Qt. I'd first try updating your driver if you can, if not, I haven't studied much Toonz code so I'm swinging in the dark here, but you can try adding some lines to your system (not user) environment variables ([how at superuser](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10)).
> 
> Restart the app each time you apply new variables.
> 
> Add new and as name set `QT_SCALE_FACTOR` and set the value to the same as the scale factor in your Windows settings for your monitor, if you've set it to '200%' then set the value to `2`, if you set it to '150%' then set it to `1.5`, you can also set any custom value you like (1, 1.25, 1.5, 1.75, 2), this will effect all Qt apps like VLC, etc.
> 
> Next try this boolean, `QT_AUTO_SCREEN_SCALE_FACTOR` and set it to value `0`, you can also try `1`.
> 
> Otherwise you can try `QT_HIGHDPI_DISABLE_2X_IMAGE_LOADING` and set it to a value of `1`, or `0` if that doesn't work.
> 
> If it helps, report back as the info might be useful for a patch.

Can this method same implied to Tahoma2D interface UI size as well?
