### ISSUE TITLE
(Proposal) Revise "Basics"room

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#2967]
Now that we have a thinner Level Strip panel, it seems to be a waste of space to put it with the Style Editor.

Below I post two images, the first one shows how it is currently when you start OT for the first time, the second one is a little revised version, where the Style Editor is moved below the Viewer. In that way some good space is gained for Xsheet columns (besides the UI looking a little more polished, IMO)...

What do you think? 

Current:
![OT1 4_first_start](https://user-images.githubusercontent.com/18104091/71559848-963c5a80-2a41-11ea-8938-9f6ce16ca75e.png)

Proposed:
![OT1 4_first_start (revised)](https://user-images.githubusercontent.com/18104091/71559852-a05e5900-2a41-11ea-9937-4b8b1f639488.png)

**Comment by DarrenTAnims** [comment]
I like the change.

**Comment by beeheemooth** [comment]
I agree, the Level Strip should be free.

**Comment by RodneyBaker** [comment]
@gab3d Question:  Is your mockup an image or is it a local update to the UI files?

**Comment by gab3d** [comment]
@RodneyBaker it is captured as it's shown from my local install of OT

**Comment by RodneyBaker** [comment]
This is a yea or nay decision but I also suspect it to be part of a larger review of room layouts in general.

One important measurement going forward will be to review the process by which we arrive at some standardized/optimized layout for each room, as well as allow for alternative for the inevitable times when layout decisions will not be unanimous.

The title for this particular proposal may be more appropriately focused on freeing up the level strip especially in light of recent changes to the Level Strip and Viewers which allow for conserving even more room.

As this report's title is '(Proposal) Revise "Basics" room, perhaps we can use this opportunity to set in place some criteria for determining what comprises the best possible layout... for the Basics Room... as well as identifying shortfalls (if any) going forward.

As an example, we might consider two primary areas of interest for each room:
- The Specific User(s) targeted for use of the room
- Anticipated and Actual Use of that room
- Maintenance of the room (to include information on how best to customize for alternative users/uses

Additionally, identifying a means to measure the satisfaction of users of the room would be useful.  This likely following the current trend as in this report where a feature changed which drives interest in updating the layout of the room.

**Comment by RodneyBaker** [comment]
As for the current proposed reorganization of the Basics room.
It seems appropriate to issue an open call for suggestions for updating/optimizing the Basics Room.
A combination of screenshots and shared files (preferably in zip format) will be appreciated.
In this way the proposed layouts can be properly categorized, reviewed and tested.

**Comment by gab3d** [comment]
One thing I'd like to point out regarding the Basics room (and OT UI in general), that I have come across recently, is that the UI really sucks in small screens, up to the point of being almost unusable.
I know 1920 x 1080 is somewhat of a standard screen format nowadays, but there are many notebooks on the market that still has lower resolutions. For example, the one I temporarily have right now (after my notebook was stolen a couple months ago) is just 1366x768, although being purchased new, in 2019.

So, this is what I see when I run OT for the first time:
![imagen](https://user-images.githubusercontent.com/18104091/79696379-bb541380-8252-11ea-9b23-575ca1bd5490.png)

So that made me think about what are the root, bare bone elements of the interface that should be prioritized? And that obviously we're not doing a very good job on approaching a certainly big amount of users that have this kind of computers and are willing to use OT.
How can we optimize each panel for taking the absolute minimum screen real estate, so to make our interface usable for such systems?

What I see there are elements with an unnecessary size (Palette style thumbnails, Level Strip width), elements that have a inappropriate small size to be useful (Color wheel, Style Editor width, Xsheet width), superfluous elements (do a typical novice user need to use the Studio Palette?), and some problems: once I've expanded the toolbar I couldn't find a way to contract it again, the Output Settings window isn't able to show all of its options when Other Settings are expanded (no way to scroll it):

![imagen](https://user-images.githubusercontent.com/18104091/79696744-f2c3bf80-8254-11ea-8b05-eb1e66c8536d.png)

All in all, I think we can do a lot better in this area if we put our efforts on it.

I've managed to relocate some panels to com to something like this, which would be more functional, I think, if we manage to modify some Style Editor limitations when in horizontal mode (i.e. the bottom should be narrower and be placed below the sliders section, and not span the entire panel width):
![imagen](https://user-images.githubusercontent.com/18104091/79696870-a331c380-8255-11ea-9d16-b6646cfdf9dc.png)

Also, the new ability to hide elements of the Visor will come in handy for lowres screens.

Another option could be to have a "Lowres" room, but anyways there are things to improve regarding low space usage of the UI, in general,

**Comment by gab3d** [comment]
other rooms like the Animation one, are sorely unusable too in this low res 🤔 

![imagen](https://user-images.githubusercontent.com/18104091/79697070-f0fafb80-8256-11ea-83e8-c1dfee090f7a.png)

**Comment by DarrenTAnims** [comment]
I've been asking for a redesign for these room for 2 years and I've barely got the energy left with it to go through this conversation again. We can talk all we like, but who actually makes this decision? No one ever seems to. And before someone says that we've all got our own ideas. Yes we have, but the current set of rooms ARE BAD. Any redesign will be better.

But let me try just one more time. The layout of the rooms will only affect new users, not current ones. And animation studios will have their own set of rooms for consistency, so it's not hard for them to keep and share their room layouts. So we should only be considering new users. So a basics room where you can load and save palettes is insane. What chance has a new user got of wanted that panel. Do new users use or understand the level strip? No. So why is it on there. It just adds confusion. The palette editor doesn't need RGB controls. No one uses them. Obviously, the colour wheel should be large enough to use.

The animation room has the schematic AND the function  editor. They are used in conjunction with each other, but not at the same time. They should be in different rooms, especially considering how much space these 2 panels need to take up to use properly.

These things take no thinking about. Yet they haven't changed in years. I'm amazed we managed to get a timeline room. The room layouts are the first thing people see. And they're the first thing that puts users off using OpenToonz. I'm sure we've all read comments from users that when they start OpenToonz, they don't know where to start. Yes, there's things to learn, but let's not make it harder than in needs to be.

For instance, being as the menus can be setup for each room, I don't think that there should be any other "Save" options in the menu apart from Save All. The number of times users are reporting saving issues, only to find out they've been hitting Save Scene, thinking, not unreasonably, that the whole scene will be saved.

I use my own set of layouts that I've transferred from one version to the next and I'll continue to do so for the foreseeable future, but it would be nice to get some traction on this for new users, but I won't hold my breath.

**Comment by KaseyFarron** [comment]
All good points raised! This is what my "Basics" room (Draw) looks like.

![Annotation 2020-04-20 164315](https://user-images.githubusercontent.com/55353161/79770988-0ee36180-8326-11ea-8ae1-23d4c0c1c7b1.png)

The only thing that bugs me is the palette toolbar is inline with the tabs, I wish it was an option so it could go on the bottom so it was more accessible.

I actually used the Ghibli room layout for most others, since the Default one didn't make any sense to me, they seem pretty random.

**Comment by turtletooth** [comment]
I agree fully with @DarrenTAnims The target audience for the room set should be new users.

I regularly check on Twitter to see what people are saying about OT.  Time and again, they have interface issues or complain about the learning curve.

Once people get more familiar with the program, they can start personalizing the rooms and opening up panels they didn't need as a beginner.

I am responsible for the current basics room.  I built it shortly after OT launched and before I had a strong understanding of how OT would be used.  I think @KaseyFarron room up there is pretty good, but could even do without the level strip.   Beginner's so often get confused about the level strip vs the timeline.  I would also add alpha to the Style Editor.

I also think that "Lock Room Panes" is worth considering as a default.  So many people mess up the interface and don't know what happened and get confused.

OT has so much power and potential, but the interface and complexity pushes many people away before they give it much of a chance.

**Comment by artisteacher** [comment]
I'd love to see a few new room sets optimized for different types of use. A simplified set for new users, perhaps a small screen set & so on. I like how Blender reworked their layouts for 2.8. Each new file, you choose the workspace when you create it - general, 2d animation, sculpting, video editing. If we did something similar, we could potentially choose a cel animation room set, stop motion room set or etc. Rooms would still be customizable & could be added.

**Comment by RodneyBaker** [comment]
Now would be a good time to discuss and lock down any plans for updating of the Basics room... and the larger set of rooms as well.   This proposal has expanded beyond the original proposal so a decision might be made on whether to maintain the scope as being focused on the Basics room alone or to expand it further.  My recommendation would be to keep this proposal's focus on the Basics Room and to open a new proposal on the larger scope of updating all the rooms... which this proposal would be a part of.

This is also an area where some thought might be given to the recommended use of other forks which have different rooms already.  For example: Tahoma has made considerable changes to the standard rooms found in Opentoonz in particular to add emphasis for users focused on stopmotion.

And of course an additional consideration should be that all users can customize the rooms but they may simple not know what to do that nor how to do it optimally.  This might fall more into the arena of training/education.


v1.5 is not far away.

Back to your @gab3d :)

**Comment by gab3d** [comment]
I'd definitely say yes to rethink the Basics room, as well as some of the others too.
Also to include a StopMotion room would be sensible, as we now have features specially pointed towards that field.
Anyway, I agree that perhaps that's a debate for another issue.

For the Basics room, these would be my suggestions:

- We should point to make the Style Editor as ubiquitous as possible, perhaps hiding one of the slider sets (either RGB or HSV) by default. I'd also limit the **Auto** and **Apply** buttons and the current style preview thumbnails, to only use the space beneath the color sliders, when Style Editor is in horizontal mode. That would allow for that panel to take much less vertical real estate than it currently allows to.

- Studio Palette panel a possible candidate to leave the Basics room, as it could hardly be seen as a "basic" feature of the program. Perhaps reserve its appeareance for the Palette or Drawing rooms?

- Palette Editor panel should use medium chips size by default, to save space.

- Level Editor should also be as thin as possible by default.

**Comment by gab3d** [comment]
@RodneyBaker 
Thanks for bringing this up again.
I think, a timeline based room as default is good, as most new users understand it better than the xsheet.
Having said that, I would've kept an xsheet based room (similar to Basics), because now there's no equivalent room that allows to use the xsheet.

Speaking of room names, "Drawing" is not the best name in my opinion.
I'd prefer to have two similar rooms (one with timeline and the other with xsheet) and be called similar also.
"Basics T" and "Basics X", or something along these lines. Because currently the "Drawing" room is not really a room specially suited to drawing, but mostly a "generic" one to do most kinds of basic stuff instead.

Just today I've read a post in the Spanish Google support forum by a user asking how she could get the Basics room back, after she had upgraded to 1.5. These questions resurface from time to time, in my experience.

**Comment by RodneyBaker** [comment]
@gab3d  As part of housecleaning I'm going to close this proposal as per our discussion there is currently no Basics room.
This is regrettable but...

Let's discuss the rooms in light of UI for 2022 Development which should include consideration for the content of rooms as well as desire not to change the UI without need so as not to confuse users (as well as cause documentation to be outdated).

It may be that we can provide users with options to see exactly what they want via extra download... ala "Download and run this to get your basics room back".  In other words, in similar fashion to the Preferences Additional Stylesheet we have some options available but haven't fully leveraged them as of yet.  One example would be that of the room options in Preferences which currently is limited to Default and Studio Ghibli.  Perhaps we might field a third called Basics specifically designed to assist new users.

At a minimum at least everyone can be on the same page moving forward even if all are not in complete agreement.

**Comment by gab3d** [comment]
Yesterday I was just recalling that this hadn't gone anywhere... yeah, it's a shame, just because it's a really simple thing to do.
Perhaps it's just because it got lost in the woods of issues 😄 

I really think we should provide a simple Xsheet-based room in tandem with the Timeline one (Drawing). 
Not rocket science either, just the usual Viewer/Xsheet/Level Strip/Palette/Style Editor combination would do.
I do think that something is better than none, so an imperfect room would still be better than not having it.

Something similar to the following. Then we will have all of 2022 to perfect it.
(We can still keep Drawing as the default room, so not to confuse users as you say).
![imagen](https://user-images.githubusercontent.com/18104091/154538905-37573139-5b50-428e-8787-760154ecd341.png)
*(bear with the fact that this computer doesn't have a 1920x1080 screen, so it all looks more cluttered than it would look in a FullHD screen, but nevertheless the idea can be seen)*

What do others think?
speak NOW! 😺

**Comment by RodneyBaker** [comment]
I live in the Animation room for which I just add the Style Editor and Palette (and often Level Strip).
Keep in mind that 'animation' to me means drawing, so they are one and the same.  ;)
