### ISSUE TITLE
Stage Schematic: Reordering nodes causes a crash if a camera is grouped

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#2978]
Video Example:
![OT Grouped Camera Crash](https://user-images.githubusercontent.com/42905003/71774096-64a32200-2f60-11ea-81da-08f929162b46.gif)

Repro steps:

1. Create a group-able node e.g. a level or a pegbar
2. Select the created node and the camera node and group them (the option to group does not appear on the camera node)
3. Click the Reorder Nodes button.
OT will crash.

The crash will only occur if the group is closed.

Edit: Whoops, messed up the title

**Comment by RodneyBaker** [comment]
This crash confirmed.
