### ISSUE TITLE
Can't see or add any windows in animation tab.

### ISSUE THREAD

**Issue by PantherTeaLord** [opentoonz/opentoonz#2979]
So pretty much all the windows are hidden and all i can see is the canvas. 
The weird thing is that i can still use all tools and select columns by right clicking on the screen and selecting them that way... So its like its all still there but i can actually see it. (I can also still draw and ect...)

Even stranger when i open "windows" and try to add them back - i CAN add them on screen, but they don't lock in place. The red line for where they can go doesn't even show.

This is only in the animation view and i have tried resetting my windows to default, closing opentoonz, resetting pc, searching it up for AGES but gawd dam the internet comes up with nothing about it ,-, 
I have even went into shortcut config and searched up a bunch of names of what a shortcut like that would be called but nothing still.

![OpentoonzWHYWINDOWS1](https://user-images.githubusercontent.com/59520755/71774551-0e86ac80-2f69-11ea-8aa0-0f47b73d302f.PNG)

![OpentoonzWHYWINDOWS2](https://user-images.githubusercontent.com/59520755/71774552-13e3f700-2f69-11ea-8b9f-9ad2a722f299.PNG)

Some images. 
(Also sorry if i did something wrong in this post, i just made a account here and am kinda new xD)

**Comment by WolfInABowl** [comment]
It seems you have maximized the canvas unintentionally.
You can hover over the canvas and press ` 
Alternatively you can double-click on the canvas' header bar

**Comment by PantherTeaLord** [comment]
Thank you so much! I was stuck on this for ages and just couldn't fix it ,-, 
Thank goodness this worked though. Thank you ! ^^
