### ISSUE TITLE
Keyframes interpolation cannot be reset in the XSheet

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#298]
sometimes the sliders between the keyframes disappear, when they do there is no way to reset the interpolation.

![interpolation](https://cloud.githubusercontent.com/assets/18170954/15256988/7a15b138-1944-11e6-9b1d-f1658382f8c7.png)

**Comment by Juls3000** [comment]
@BrundleThwaite: here @psychoanima explains in deep how works keyframes and handles visualizations in xsheets and Function Editor:  https://github.com/opentoonz/opentoonz/issues/234 As I see it, from this message are the key explanations : https://github.com/opentoonz/opentoonz/issues/234#issuecomment-216255207

**Comment by BrundleThwaite** [comment]
I know why it happens and it does not really worry me but this is from page 240 of the harlequin manual.

> To make the arrowheads available when they are not:
> Right-click the vertical line connecting two subsequent keys and choose
> Reset Interpolation from the menu that opens.

And that menu can not be brought up.

**Comment by blurymind** [comment]
For some reason this does not happen in Toonz harlequin, but does in Open
toonz. :)

Try it yourself

**Comment by psychoanima** [comment]
Yes, harlequin does have that option with right mouse button. It's not a bug, just one more hidden option :)

**Comment by Juls3000** [comment]
Perhaps Digital Video abandoned skeleton animation by plastic.

**Comment by blurymind** [comment]
Ok we have two bug/regressions from harlequin that are quite serious. Since the old issue post got really long and we came to some conclusions as to why it was happening, I decided to split the handles issue in the curves editor in another bug report that is clearer to the developer:
https://github.com/opentoonz/opentoonz/issues/300

In this one we need to figure out why the are disappearing in the x-sheet exactly.
They do not disappear in harlequin, so what is causing this to happen in opentoonz?

**Comment by blurymind** [comment]
@BrundleThwaite I figured it out - it might be related to global key option missing in the pose (edit) tool.
Without it , there is a high likelihood of these interpulations disappearing from both the x-sheet and the curves editor.

Global key was by default always enabled in toonz harlequin and is now a removed feature from open toonz.

**Comment by psychoanima** [comment]
Here's one Easter Egg for you :)

Go to Customize drop down menu and select Configure Shortcuts

scroll down until you find Reset Interpolation. Assign shortcut button for that command ('R' for example)

![reset interpolation](https://cloud.githubusercontent.com/assets/18187104/15262190/0bc7d90a-1961-11e6-8e5e-8154fd4d2cf0.PNG)


go now to x-sheet, point your cursor to vertical line that is connecting keyframes. Press your previously assigned button for Reset Interpolation. Have fun :)

**Comment by Juls3000** [comment]
[Certified Diplodocuses](http://www.tintinologist.org/guides/lists/curses.html)!!! Very good finding. You also have it with RMB:

![cats2](https://cloud.githubusercontent.com/assets/19145844/15266528/fed4a9ec-19a8-11e6-8e68-c35330edd051.jpg)

**Comment by Juls3000** [comment]
one more:
(1) If you set "Curve Shape" to "Frame Based"
(2) Handlers in in Xsheet keep visibles and synchronized

![cats](https://cloud.githubusercontent.com/assets/19145844/15266598/0aa38a66-19ab-11e6-994a-d79ee12c55df.jpg)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
