### ISSUE TITLE
Jagged Curves while drawing at smaller resolutions

### ISSUE THREAD

**Issue by hoshideveloper** [opentoonz/opentoonz#2980]
### Issue Summary
Curves are not as smooth when you're drawing for small shapes at a smaller resolution.

### Screenshot or Video Reference
![opentoonz 03 - jagged curves](https://user-images.githubusercontent.com/59495096/71781104-dd25d500-2f98-11ea-949e-cd788709b0e0.png)
Closeup of Curves drawn in a resolution of 370x320 pixels.

### Steps to Reproduce
Turn your resolution to a small resolution, such as 300x300 pixels. 
Drawing anything with elaborate details, regardless of Brush settings for Accuracy and Smoothness, will yield more jagged curves. Please note that even if you adjust the nodes, the curve of them has a sharp angle that yields a less than desirable effect.

### Expected Results
![opentoonz 04 - Smooth curves](https://user-images.githubusercontent.com/59495096/71781136-49a0d400-2f99-11ea-9800-9a7e49d8a21c.png)
Here is a picture of a curvy line drawn at 1080x1920 pixels.

Drawing at larger resolutions is much smoother so I expected a vector-based program to carry that feeling into smaller resolutions.

### Actual Results
Instead of getting a very smooth result, I always get jagged edges shown in the first screenshot. This makes working on icons and avatar animations very difficult.

### System Information
* **OpenToonz Version**: 1.3
* **Operating System**: Windows 10
* **CPU**: Intel(R) Core(TM) i7
* **Memory**: 8 GB

**Comment by RodneyBaker** [comment]
There are a number of reports similar to this but this report adds some additional insight into part of the problem.

Perhaps the first thing I note is that this issue concerns vectors.
Some reasonably similar issues have been addressed with strokes snapping to nearest pixel, being overly offset from center, etc. but those primarily focus on toonz raster/raster.

This report might also hint at why drawing small shapes, especially circles, rarely produces circles.
As this is vectors my interest immediately gravitates to the bias handles and how (in your image) they are not evenly weighted going into and out of their respective control points.

Might this relate to a rounding (i.e. loss of data) for the magnitudes traversing the points?

**Comment by hoshideveloper** [comment]
> There are a number of reports similar to this but this report adds some additional insight into part of the problem.
> Perhaps the first thing I note is that this issue concerns vectors.
> Some reasonably similar issues have been addressed with strokes snapping to nearest pixel, being overly offset from center, etc. but those primarily focus on toonz raster/raster.
> This report might also hint at why drawing small shapes, especially circles, rarely produces circles.
> As this is vectors my interest immediately gravitates to the bias handles and how (in your image) they are not evenly weighted going into and out of their respective control points.
> Might this relate to a rounding (i.e. loss of data) for the magnitudes traversing the points?

I had a feeling that issue might have been posted before but didn't see anything relating to the size of the resolution from a search. I'm not familiar with the loss of data problem but it sounds like it could be related. It might explain why sometimes one part of the Bezier curve is sharp compared to the other side. I think this is more so a problem for smaller objects because maybe the Bezier curves are intersecting and overlapping with each other too much in comparison with larger resolution linework which gives the nodes more space and influence apart. That is just a theory though, as I'm more of an artist/animator that doesn't have much expertise outside of that.

**Comment by RodneyBaker** [comment]
When I tested using a 300x300 pixel image at first I didn't have the problem.
After messing around with settings (primarily Accuracy and Smoothing) the problem appeared but not as noticeable as in your case.

It is probably not just one thing but several things.
If you are using the v1.3 from the website link you might want to try a nightly release as that installer from the website is a year old (from Jan 2019).  The nightly releases can be found [HERE](https://github.com/opentoonz/opentoonz_nightlies/releases).

**Comment by hoshideveloper** [comment]
> When I tested using a 300x300 pixel image at first I didn't have the problem.
> After messing around with settings (primarily Accuracy and Smoothing) the problem appeared but not as noticeable as in your case.
> It is probably not just one thing but several things.
> If you are using the v1.3 from the website link you might want to try a nightly release as that installer from the website is a year old (from Jan 2019).  The nightly releases can be found HERE.

Thank you. Sorry for my late reply, I had to replace my computer. I'm having trouble with these nightly releases and I get a "glut32.dll is missing" error for a lot of them. 

Another issue I'm having when I get it to work is that theres no backward compatibility for old files. Even if I want to use 1.4, I can't use my 1.3 file. That's probably a common issue I bet though.

**Comment by RodneyBaker** [comment]
We can definitely use files created in v1.4 in v1.3 (and vice versa)
although there are a few exceptions to that rule.
Perhaps the most notable exception is the Fill Tool's gap distance slider.
If a user adjusts the gap distance in releases after the file will not be
compatible.

Forward compatibility... moving from v1.3 to v1.4... there should be no
major issues so it would be good if you can open a new topic on that one
and provide more specific details.

It is odd that you are having the glut32.dll issue.
It does happen from time to time but I haven't seen that much since the
early days of Opentoonz.
That should be an easy fix.

**Comment by manongjohn** [comment]
Regarding the glut32.dll issue, for some reason, even though it is provided, OT doesn't detect it in the installed folder.

One way to fix that is to copy `C:\Program Files\OpenToonz\glut32.dll` to `C:\Windows\SysWOW64` folder.

**Comment by hoshideveloper** [comment]
> Regarding the glut32.dll issue, for some reason, even though it is provided, OT doesn't detect it in the installed folder.
> One way to fix that is to copy C:\Program Files\OpenToonz\glut32.dll to C:\Windows\SysWOW64 folder.

Oh thank you! I was wondering why it was acting up even though the file was already in the program folder. I will try this.

**Comment by hoshideveloper** [comment]
> We can definitely use files created in v1.4 in v1.3 (and vice versa)
> although there are a few exceptions to that rule.
> Perhaps the most notable exception is the Fill Tool's gap distance slider.
> If a user adjusts the gap distance in releases after the file will not be
> compatible.
> 
> Forward compatibility... moving from v1.3 to v1.4... there should be no
> major issues so it would be good if you can open a new topic on that one
> and provide more specific details.
> 
> It is odd that you are having the glut32.dll issue.
> It does happen from time to time but I haven't seen that much since the
> early days of Opentoonz.
> That should be an easy fix.
> …

I will try doing the .dll fix and see if that helps. If not, I will open a new thread, thank you so much for your assistance so far :)

**Comment by hoshideveloper** [comment]
> We can definitely use files created in v1.4 in v1.3 (and vice versa)
> although there are a few exceptions to that rule.
> Perhaps the most notable exception is the Fill Tool's gap distance slider.
> If a user adjusts the gap distance in releases after the file will not be
> compatible.
> 
> Forward compatibility... moving from v1.3 to v1.4... there should be no
> major issues so it would be good if you can open a new topic on that one
> and provide more specific details.
> 
> It is odd that you are having the glut32.dll issue.
> It does happen from time to time but I haven't seen that much since the
> early days of Opentoonz.
> That should be an easy fix.
> …

![hands](https://user-images.githubusercontent.com/59495096/73148328-681e5a80-4081-11ea-9c05-e4322f4a7038.png)

Alright, I managed to fix the glut32.dll issue with manongjohn's response. 

I tried drawing some really fast hands to test it out on a 300x300 page. I want to make very small details. For the most part, the edges are smooth, though still kind of adds weird pointy spots here and there once it gets smaller, Still, much better than before. I think I can work with this for now. 

Only problem left is that while I can open my 1.3 file and see all my columns and levels... no art shows up unfortunately so I will probably open up a new thread for that. This has happened for every version I upgrade to so I expected it to happen. I'll open a new thread.

**Comment by RodneyBaker** [comment]
Glad to hear of your success with the DLL issue.
That's a strange thing for sure and even stranger that some users have the issue while others do not.

(Assuming vector drawing here) 
Don't forget that if desiring to draw really small details an option is to draw regular size and then scale a selection down.  Check the option to maintain line thickness if that is desired.

**Comment by hoshideveloper** [comment]
> Glad to hear of your success with the DLL issue.
> That's a strange thing for sure and even stranger that some users have the issue while others do not.
> (Assuming vector drawing here)
> Don't forget that if desiring to draw really small details an option is to draw regular size and then scale a selection down.  Check the option to maintain line thickness if that is desired.

Oh I think I figured out what was wrong. My files for the levels were not backed up with the scene file. :( Oh well, I'll try to keep it all together and make a copy of the folder where it all is for future reference

**Comment by RodneyBaker** [comment]
@hoshideveloper  Can you re-summarize what issues (if any) you still have related to the original report related to drawing smooth vector lines?

We don't want to close the issue if it isn't resolved.

**Comment by hoshideveloper** [comment]
> @hoshideveloper  Can you re-summarize what issues (if any) you still have related to the original report related to drawing smooth vector lines?
> We don't want to close the issue if it isn't resolved.

No issues relating to the initial jagged edges at small resolution problem for now in the new version

**Comment by RodneyBaker** [comment]
Great news.
Closing.
