### ISSUE TITLE
Adding a keyframe to a selection with the ctrl key does not work when a frame on that column is selected.

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#299]
When you are selecting keys in the XSheet it does not select properly if you have selected a frame which is in the same column as the keyframe. ctrl toggles selection and shift adds all the keyframes from frame 1 to the keyframe you have selected.

When a frame outside of the column the keyframe is on is selected ctrl adds/removes selection and space selects a range.

crtl

![ctrl](https://cloud.githubusercontent.com/assets/18170954/15257752/1f6bf84c-1948-11e6-89e1-2b3533b55741.gif)

Shift

![shift](https://cloud.githubusercontent.com/assets/18170954/15257725/f867d9d2-1947-11e6-8ebe-5df4a3d5a824.gif)

**Comment by shun-iwasawa** [comment]
@BrundleThwaite 
Could you please check if this problem can be reproduced in the latest version? I couldn't find difference in behavior, regardless of selected cell before clicking the key icon.

**Comment by BrundleThwaite** [comment]
I still have the problem. I'm using the Windows edition

**Comment by artisteacher** [comment]
I’m not seeing this in OS X. @BrundleThwaite, is this still an issue?

**Comment by BrundleThwaite** [comment]
@artisteacher Sorry don't really know. The newer versions of OpenToonz have a severe Lag when drawing on my computer and are unusable for drawing. So unfortunately I can't really check.

**Comment by RodneyBaker** [comment]
> The newer versions of OpenToonz have a severe Lag when drawing on my computer and are unusable for drawing. So unfortunately I can't really check.

Ouch.  That sounds severe enough to elaborate on and I hope you will.  Unless you have a really old computer I can't imagine why you'd be unable to draw in OT on current releases.  Something definitely doesn't add up there and I hope you'll assist others in resolving that as there must be others experiencing similar issues.

**Comment by artisteacher** [comment]
@BrundleThwaite, have you tried a nightly build recently? There have been a few fixes for drawing lag & a lot of bug fixes overall in the past month or so.

**Comment by BrundleThwaite** [comment]
I checked again 2 days ago. I also updated the drivers at the same time to make sure.

The issue is logged here my specs are all listed in the thread: [#1592](https://github.com/opentoonz/opentoonz/issues/1592)

**Comment by manongjohn** [comment]
@BrundleThwaite I still wonder if its not using your GPU for some reason. Win10 can now detect GPU usage along with CPU usage. Can you verify you see spikes in GPU usage when you are drawing in OT? If not, the setting in your Radeon card might not be quite right.

**Comment by BrundleThwaite** [comment]
The graphics card is being used. I have checked all the basic settings none of them make any difference.

**Comment by RodneyBaker** [comment]
This report could use a status check.
Bringing forward the specs @BrundleThwaite linked to for easier reference:

OS: Microsoft Windows 10 Pro
Version: 10.0.16299 Build 16299.
Processor: AMD FX(tm)-8300 Eight-Core Processor, 3300 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM) 8,00 GB
Drive 1: 232.40 GB SSD
Drive 1: 4TB Seagate
Graphics card: Radeon(TM) RX 460 Graphics 2G
OpenToonz is running off the SSD.
Up to date on drivers.

Thus far the issue appears to be isolated to the specific system/environment.

**Comment by turtletooth** [comment]
This doesn't seem to be an issue anymore.
