### ISSUE TITLE
Camera Capture OSX: Onion Skin not working

### ISSUE THREAD

**Issue by piotrnikov** [opentoonz/opentoonz#2999]
## Issue Summary
Turning on Onion skin feature in camera capture doesn't show Onion Skin.

### Expected Results
Onion skin!

### Actual Results
Onion Skin briefly appears (I think) but disappears almost immediately .
Works fine on my Win 10 rig.

### System Information
* **OpenToonz Version**: 1.3 Build January 9 2020
* **Operating System**: MacOs 10.15.2
* **CPU**: 8-Core Intel Core i9
* **Memory**: 32 GB
* **Graphics Card**: AMD Radeon Pro 5500M
* **Graphics Tablet**: Intuos 4

**Comment by artisteacher** [comment]
I'm seeing this as well. Changing the opacity value seems to make a slight visual shift but you cannot see any sign of the prior frame.
