### ISSUE TITLE
Regression from harlequin: Edit tool - Global Key option is missing - causing problems with the interpolation handles

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#300]
Here is the curves editor in Toonz harlequin:
![handlevisibilityregression](https://cloud.githubusercontent.com/assets/6495061/15260924/632d311e-1951-11e6-9e09-be40617bd7e6.JPG)

Please note in the screenshot that all channels are toggled on, and the interpolation handles (ease in/out) are all visible!

And here it is in Toonz Harlequin:
![otnohandlesissue](https://cloud.githubusercontent.com/assets/6495061/15261011/dcc86d9a-1951-11e6-81aa-6b2104bd4781.JPG)
 
when all the channels are visible, the handles in the curves editor disappear. If you however expose only the channel with the keyframes, you get them back - in the curves editor. They are however missing in the x-sheet:
![handlesstillmissing](https://cloud.githubusercontent.com/assets/6495061/15261058/26a664a8-1952-11e6-953e-9de1b06a96c0.JPG)

Handles in the x-sheet never disappear in harlequin, and they are for some reason constantly vanishing in opentoonz. This might be related to: https://github.com/opentoonz/opentoonz/issues/298

**Comment by blurymind** [comment]
Ok I understand why this happens now - When you use the Edit tool in harlequin to pose a level, It creates a new keyframe on all channels. It uses that via 'Global Key' - this is an option that is missing in opentoonz:
![globalkey](https://cloud.githubusercontent.com/assets/6495061/15261492/c75255c2-1954-11e6-957a-9533723a43bb.JPG)

**Comment by blurymind** [comment]
@shun-iwasawa  please bring back 'global key' to the edit tool. It is convenient to cut-out animation workflow.
Global key was by default always enabled in toonz harlequin and is now a removed feature from open toonz. Without it the handles will constantly get lost.

I already filed another related bug report for the same tool:
#157 
Please revert changes to the tool, as it is causing all sorts of trouble in the keyframing department.

**Comment by blurymind** [comment]
Thank you @Banbury

**Comment by kogaki** [comment]
Thanks to @Banbury , this issue must have been fixed.

**Comment by blurymind** [comment]
thank you for merging it :)
