### ISSUE TITLE
(Feature Request) official AppImage support for Linux

### ISSUE THREAD

**Issue by Lounes-Tb** [opentoonz/opentoonz#3004]
We all already know about the .AppImage (the Linux apps format that just works and stuff) since there is already an unofficial version of opentoonz available as an AppImage file for Linux (https://github.com/morevnaproject/opentoonz/releases)
 * We know that it works as an AppImage.
 * Synfig and Pencil2D are already available as AppImages, they are easy to run on Linux that way.
So why not taking the last step and making an official opentoonz.AppImage?

thank you for making such a great animation software for free and for reading my request.

**Comment by RodneyBaker** [comment]
Thanks for the rquest @Lounes-Tb

**Comment by manongjohn** [comment]
It would be nice if an official Linux version was offered.

If the meantime, the OTX version does offer a portable AppImage for Linux. It is updated monthly (for now at least) with the latest and greatest OT has to offer + some stuff in the pipeline. You can get it at https://github.com/manongjohn/OTX/releases

**Comment by RodneyBaker** [comment]
There is now an automated linux build for each Pull Request via Github Actions.
This is for Ubuntu with one build with GCC and one build with clang.

Example:  https://github.com/opentoonz/opentoonz/actions/runs/435852330/workflow
