### ISSUE TITLE
'Adjust Current Level to This Palette' command crashes with Palette levels

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3007]
Here's a somewhat obscure reproducible crash

Video example:
![Palette Crash](https://user-images.githubusercontent.com/42905003/72129773-5f364500-336f-11ea-93ce-60c5189c66f3.gif)

Repro steps:
1. Load a palette into a column (click and drag it onto the XSheet/Timeline).
2. With the newly created palette level selected, right-click on a palette in the Studio Palette window and choose the 'Adjust Current Level to This Palette' command.
OT will then crash.

OT Ver: Jan 10th Nightly
OS: Windows 10

**Comment by RodneyBaker** [comment]
Confirm the crash.
