### ISSUE TITLE
render crash but not on OTX

### ISSUE THREAD

**Issue by bobbybutterfly** [opentoonz/opentoonz#3016]
Render crash on latest nightly build but renders perfect on latest OTX version

102 frames, 1920 HD tif, no fx,  columns are from loaded psd file on desktop
uninstalling and reinstalling OT had no effect

Surface pro 2017 i5 8gb

Edit:   same crash on OT 1.3 30 Jan 2019 build

Edit2: i reduced the size of the psd file from 4000 x 4000pixels to 2000 x 2000 and now it renders
          ( i am wondering, why that OTX build handles that bigger file without problems)

Edit3: importing instead of loading the 4000pixels psd file didnt change crashing of OT

Edit4: SOLVED! uninstalling OT and completely deleting the opentoonz stuff folder (saving my project files temporarily on the desktop), then reinstalling the program - it renders well now. Maybe i have overseen it, but there should be a hint for this workaround. Many crash scenarios could be solved this way!

**Comment by RodneyBaker** [comment]
RE:  Edit4: SOLVED! 
Yes, a clean install is a very good idea when troubleshooting a persistent problem.
I wouldn't call this a workaround so much as a Standard Operating Procedure (SOP).
This is similar to encounters with glitches in interfaces where users should quickly consider checking/updating their graphics drivers.
A clean install is especially important after major changes to an application such as we now see in the nightlies headed into v1.4.

A question:  In Edit 4 you say "Solved!" but does this mean the entire issue you reported is resolved?
If so then recommend closing.

**Comment by bobbybutterfly** [comment]
@RodneyBaker completely solved thanks!

**Comment by manongjohn** [comment]
I wonder what in the stuff folder would have caused that. Perhaps some preference setting might have contributing to this issue?

In theory, we should be able to upgrade over existing installation without problems, which was one reason we removed the version number from stuff folder so we wouldn't have to keep resetting up our preferences and settings.  Would have been helpful to have a before and after to see what could have caused it.

**Comment by bobbybutterfly** [comment]
@manongjohn  i deleted absolute everything so the fault could be anywhere.
What i noticed after the clean install was the new look of the menu bar with a new render dropdown menu, not longer a part of the edit menu.
