### ISSUE TITLE
Nightly build 13/5 OSX crash

### ISSUE THREAD

**Issue by Gulwer** [opentoonz/opentoonz#302]
Hi
The nightly build from 13/5 crashes when I choose the brush tool and try to paint. Here is the crash report. 

[Opentoonz_crash_15_5.docx](https://github.com/opentoonz/opentoonz/files/264900/Opentoonz_crash_15_5.docx)

edit: the latest nightly build16/5 just hangs at the splash screen.

**Comment by kogaki** [comment]
Thanks, I will check right now.

**Comment by Gulwer** [comment]
Hi
Thanks for the fix. Now the program opens but it still crashes

**Comment by kogaki** [comment]
Yes, and now I have created fix #317.

**Comment by Gulwer** [comment]
Hi again
The fix works fine, thanks Kogaki
