### ISSUE TITLE
Style Editor rearrangement bug

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3022]
GIF example:
![OT Style Editor Bug](https://user-images.githubusercontent.com/42905003/72406283-9c297f80-3753-11ea-86be-1995a8bed46e.gif)

Repro steps:

1. Create a new room
2. Create any window, (the example gif uses a Combo Viewer) and make it fill the whole space
3. Create a Style Editor window and try to place it above or below the Combo Viewer

The Style Editor window will not be placed correctly.

Edit: Upon further testing, it seems that step 2 is not necessary, all that is needed is to create a Style Editor window and attempt to make it fill the whole screen.
The only difference is that if you only have the Style Editor window, it is possible to drag it again and return it to a working state. However, from that point onward, you are unable to snap any other windows.

OT Ver: Jan 15th Nightly
OS: Windows 10

**Comment by shun-iwasawa** [comment]
Confirmed the problem and found that the Level Strip also has the same issue.
I tried removing lines for fixing widths of the panels (added in #2645 and #2814)  and the problem seems not to occur.

**Comment by artisteacher** [comment]
It would be great to have a way to avoid this issue without having the resizing problems that were resolved in #2645 and #2814.
