### ISSUE TITLE
cycle the availabe options issue

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3025]
### Issue Summary

cycle the availabe options not working anymore in the preferences. the assigned shortcuts open dropdown options instead of
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
I'm seeing this too.

**Comment by shun-iwasawa** [comment]
I think I found a probable cause of the problem. Thank you @openanim I'll fix it right away.
