### ISSUE TITLE
Stop Motion for all OS

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#3027]
### Issue Summary

Please enable the new stop motion controls #2635 for macOS and Linux too. This is too helpful of a feature to be limited to Windows only! 

Assuming this will not happen in time for the 1.4 release, it will be important for the release notes to specify that the Canon DSLR & stop motion support is currently a Windows only feature.

**Comment by turtletooth** [comment]
The Canon SDK doesn't have a linux option, but OSX should be doable.  I don't have a Mac anymore, so I can't test, but the SDK does have Mac  support.

**Comment by turtletooth** [comment]
@artisteacher I have a license to Dragonframe that I am no longer using. I would like to transfer my Dragonframe account to you. Would you have any interest in a Dragonframe license?

**Comment by artisteacher** [comment]
@turtletooth - That would be amazing! Thank you for thinking of me.

**Comment by turtletooth** [comment]
@artisteacher can you email me at jcbullock @ gmail so I can get you the details?

**Comment by turtletooth** [comment]
For anyone following here, i am doing a little digital decluttering and I have a license to Gamemaker Studio desktop and html modules that I would like to pass on to someone who would put it to use. If interested please let me know.

**Comment by artisteacher** [comment]
@turtletooth - How complicated should it be to get the Stop Motion feature to work on macOS? Is it just a matter of having a mac & the Canon SDK & the right build steps, or would there be additional coding involved? If it's the first, I might be able to figure it out with enough trial and error...

**Comment by turtletooth** [comment]
I'm going to close this since there is a pending PR. #3221
