### ISSUE TITLE
some display issues on the 3 levels with the level strip

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3028]
### Issue Summary

It seems there are some display issues on the 3 levels with the level strip and brush.
### Screenshot or Video Reference

![display issues level strip_brush](https://user-images.githubusercontent.com/29790512/72457802-ae450580-37c7-11ea-9dc9-c1c81f7aaf0f.gif)

### Steps to Reproduce

Create levels and work from level strip.
### System Information
* **OpenToonz Version**: Last NB build jan 16 2020 01.49:01
* **Operating System**: w10
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
Not seeing anything similar here.
The two things I would look at would be updating graphics drivers and manually clearing the Opentoonz cache.  The latter of which shouldn't really relate to the problem but it occurs to me to do that as the installers don't appear to do that automatically.

**Comment by openanim** [comment]
I updated my graphics card just before the last night. It's possibly related to that. I will downgrade to see if the update is the problem.

**Comment by openanim** [comment]
I confirm, the problem came from the intel update. I close the issue
