### ISSUE TITLE
Delete unused styles right-click item missing?

### ISSUE THREAD

**Issue by hayoko** [opentoonz/opentoonz#3035]
### Issue Summary
I couldn't find the Delete unused styles command in the right-click menu, I had to set it to a shortcut.

### Steps to Reproduce
Right-click in the palette, there's no option (for me at least).

### Expected Results
For it to be a right-click menu item in the palette.

### Additional Context
I could almost swear it used to be there, so it could be user error.

**Comment by shun-iwasawa** [comment]
@hayoko 
Thank you for pointing. It seems that I temporarily commented out the lines for `Delete unused styles` command when preparing for the first release of OpenToonz 4 years ago. And once @turtletooth reverted the command ( #628 ) but I commented it out again ( #817 ) ... I'm not sure why I did so.
Let me check if it will work by just reverting the lines.
