### ISSUE TITLE
The Camera Capture window moves to the background and does not return when the cursor moves to some panels.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3045]
### Screenshot or Video Reference

![ezgif-3-694924393b32](https://user-images.githubusercontent.com/25724133/72763664-7c7bd680-3bed-11ea-9b1e-702a0e893d62.gif)

### System Information
* **OpenToonz Version**: latest
* **Operating System**: Windows 8.1

**Comment by RodneyBaker** [comment]
I confirm the problem with the steps outlined and that this PR fixes the issue.
Thank you @shun-iwasawa for the fix.
