### ISSUE TITLE
(Discussion) What's New page in the Manual

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#3047]
I've done a first try of English [What's New](https://opentoonz.readthedocs.io/en/latest/whats_new.html) page, it summarizes more or less the same Highlights found in the Release Notes Github page, but I've taken some time to go through them and add several others that I found interesting for users to get the news about.

I'd like for others to take a look and tell if there's some other topics I should add, or change something perhaps? 🤔 

@shun-iwasawa @manongjohn @artisteacher @DarrenTAnims @RodneyBaker @turtletooth @blackwarthog @caryoscelus @konero @snapai @otakuto @jpturcotte @morevnaproject 

P.S.
One of the advantages of linking the **Help > What's New...** option to this page instead of the GitHub one is that we take more people right to the Manual, and they could easily continue exploring other topics after reading the News.
The other one being that for new/enhanced features that get their section in the Manual, we can easily link to that section. (Right now there is none, but in time we could keep adding them and linking from here.)

**Comment by DarrenTAnims** [comment]
This looks really useful. Thanks for doing this.

Are you planning to add any links to this page? So that you can click on them and be taken to the page in the manual where the feature is covered in more detail?

**Comment by gab3d** [comment]
> Are you planning to add any links to this page?

absolutely. that's the idea! 😸 
still, there currently isn't any pages featuring covering the new features.

**Comment by DarrenTAnims** [comment]
That'd be soooo useful.

**Comment by konero** [comment]
Agreed! Love your work on the manual. ❤️

**Comment by DarrenTAnims** [comment]
Just a thought ... Is it easy to edit the manual? Can we all propose or add new sections to it? if more *could* add details of new features, then more *might* do so. I'd be tempted to do so myself.

**Comment by gab3d** [comment]
It's rather easy...
It'd be great if more people contributed in adding the new features to the current manual.
I think there are sections for almost everything in there, so initially I'd say it's better to go adding the new features where they fit best, in the current structure.

Of course new sections could be also added too, if for some reason they are needed.

I think one interesting thing that you could contribute to, would be in making some short animated GIFs, showing some of the features (the ones that benefit most from a visual explanation). For example, the new vector guided drawing workflow, comes to my mind.

**Comment by DarrenTAnims** [comment]
And where are the files for the manual? And what is the process? Is that written down somewhere? I'm guessing github somewhere. I just remember a while back that we didn't all have the permissions to edit them. But yes, animated GIFs can be a big help. I intend to look over these new features over the coming days anyway. I might write up a few of them, if I can work out how to - with your help, possibly ;-)

**Comment by gab3d** [comment]
great!
I'll put you up to speed with this, it's really easy. 👍 
you can write to me privately if you wish.
gabcorreo at gmail

**Comment by gab3d** [comment]
@shun-iwasawa 
Could you please give Darren commit privileges in the manual repository?
He'll be helping to produce materials for it.
Thanks!

**Comment by shun-iwasawa** [comment]
@DarrenTAnims 
I just invited you to collaborators (= write access) of the documentation repository.
Please check https://github.com/opentoonz/opentoonz_docs/invitations and accept to join.

[Here](https://github.com/opentoonz/opentoonz_docs/blob/master/CONTRIBUTING.md) is a brief instruction for contribution. Thanks!

**Comment by morevnaproject** [comment]
@gab3d  Great idea!

> The other one being that for new/enhanced features that get their section in the Manual, we can easily link to that section. (Right now there is none, but in time we could keep adding them and linking from here.)

While not all features are described in manual, I suggest to place links to relevant issues/PRs for main features.

**Comment by RodneyBaker** [comment]
Closing as the 'What's New' page is live and looking good.
Thanks @gab3d !
