### ISSUE TITLE
[Feature Request] Split and Paint Shade Mask TLV Command

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#3049]
### What is this?
A command that splits a shade mask into separate styles (painted areas) and repaints them automatically based on what colors are on the level below, similar to functionality of a layer blending effect, except we can preload what those colors will be manually.

### How is it supposed to work?
Artwork should be painted flat on one level with no shaded areas, you paint the shaded areas on a separate level using single colors to represent everything, e.g. blue represents all shadow no matter what region (skin, clothes) it covers, and so on.

This method of working is already very popular, which is why I created this suggestion, as it's very fast to composite lighting effects this way, the artist pays no mind to adding shading keys to each individual region like you would with PaintMan so the painter can differentiate colors, this feature would make it even faster and cheaper to do.

![image](https://user-images.githubusercontent.com/19820721/72933124-085e4180-3d59-11ea-8db1-d932def27bc3.png)

### What should the command do?
1. Take a **base level¹**, a **shade mask²** and a **color model³**.
2. Split the **shade mask²** into separate styles by comparing it to the **base level¹**.
- 1. If blue in the **shade mask²** covers [2] different styles on the **base level¹** then split the **shade mask²** between those [2] styles, do this for as many styles that it covers.
- 2. The end result should be; if the **shade mask²** was [1] blue style to begin with, it is now [2] blue styles. Here's an example, blue **shade mask²** style covers **skinᵃ** and **hairᵇ** on the **base level¹**, the command splits the [1] blue style into [2] styles.
![blueStyles2](https://user-images.githubusercontent.com/19820721/73065368-4a8f9c00-3e9b-11ea-8323-d557fc7c258d.gif)
3. The command then repaints these areas by once again comparing with the **base level¹** and a **color model³** reference.
- 1. The color model can be scanned by detecting surrounding pixels and color picking each swatch detected in a chain, we can end the chain when the color that starts the chain is detected again.
![image](https://user-images.githubusercontent.com/19820721/73068031-19ff3080-3ea2-11ea-84a1-112622e46d47.png)
- 2. Each time specific pixel colors are detected it begins a new search for a style color and it should loop through until the search ends. If black or white is detected it can be ignored.
![image](https://user-images.githubusercontent.com/19820721/73068146-6480ad00-3ea2-11ea-9d3a-e247475ee8ef.png)
- 3. Now the command can understand that our crown position (base color) if detected in the **base level¹** below (as rgb) has shades connected to it.
- 4. The command repaints the newly split blue style in the **shade mask²** using this information.
4. Finally, the two levels are merged into one.

### Notes
**Has another program done this before?**
Yes, this can be done using After Effects or TVPaint though it takes some work.

**Comment by gab3d** [comment]
yesterday I saw a very good video about the technology used in Klaus.
although it shows so much more than just lights and shadows, it certainly shows some good things related to this topic.

I leave this link, starting at the moment it shows light and shadow, but the whole video is very interesting:
https://youtu.be/VnmQy0UMLtA?t=469

**Comment by hayoko** [comment]
+1

This would be nicer in OpenToonz as a command and not an FX, our replacement colors can be kept as a separate TLV that way. We should split the mask TLV large style areas into multiple style areas based on each color detected by comparing the two levels and generating the new style colors from our comparison color model table, merge mask TLV into base TLV to clean it up to allow TLV FX compositing and voila, but how to split one painted area into multiple areas like that?

I work with this color mapping method and we use color keep/replace and script replacements using After Effects on rasterized frames since you can do what @gab3d showed in that video by using clipping vector masks just to automatically track and generate tweens for lighting areas (I use Animate CC).

I'll see if there's anyone willing to bounty this, even if a little, I got no money to spare at the moment, but it would be an awesome way to combine hand-drawn art with vector lighting keys, and that way we get a little bit of the Klaus stuff.

**Comment by konero** [comment]
@hayoko That's a very interesting method! I amended my post to take it into account. I never studied computer imaging so it's difficult to get across. Thanks.

**Comment by artisteacher** [comment]
> I can't think of how to interface it so that it's quick to do, I think it would be a pain if in the panel the user has to pick matching colors one by one for each scene.

It could be helpful for each shadow/highlight color to be automatically generated based on the mid-tone fills. The styles could always be adjusted as necessary afterwards.

Ie. If style 3 below were chosen as a mid-tone color, styles 2 & 4 would be created automatically.
<img width="152" alt="Screen Shot 2020-01-23 at 8 46 46 AM" src="https://user-images.githubusercontent.com/21159116/72989776-ed251d80-3dbc-11ea-8570-599e86325cb2.png">

**Comment by konero** [comment]
Updated, I hope that's some better explanation.

**Comment by hayoko** [comment]
I tried, but I've never used OpenCV before, I manged to mask out blue from one image using a color from another image, here I did red+black.

![Annotation 2020-01-25 101639](https://user-images.githubusercontent.com/36535462/73119615-4a0b0a00-3f5c-11ea-87f3-779402390030.png) ![Annotation 2020-01-25 101932](https://user-images.githubusercontent.com/36535462/73119616-4bd4cd80-3f5c-11ea-9f4d-34cf735f8d62.png)

Next it could go green+black, etc. and I'd get two independent shapes out of one. But aside from playing around and finding snippets, it's out of my expertise. ☹️

**Comment by RodneyBaker** [comment]
I'm not sure why this feature request was closed.
Reopening (at least temporarily) until it can be processed through the v1.5 review.

@konero As this is/was your feature request we will appreciate any information you can provide concerning the original request and whether the feature is still desired and also if there is a current external process by which users can achieve the same or similar results.  Thanks!

**Comment by konero** [comment]
Closing as already implemented.
