### ISSUE TITLE
Unable to load/import folder with .tga files inside

### ISSUE THREAD

**Issue by lemonbako** [opentoonz/opentoonz#3051]
### Issue Summary
OpenToonz is unable to load/import a folder with _.tga_ files

### Screenshot or Video Reference
![tga_bug](https://user-images.githubusercontent.com/46865843/72849138-aa8a1500-3cd8-11ea-9f3a-c1e9dbbc07e1.gif)

### Steps to Reproduce
I use sample data provided from OpenToonz official website
If you load a folder by drag & drop operation or Load Folder command in _File_ menu with any_ _.tga_ files in it, OpenToonz will refuses to load/crashed

### Expected Results
OpenToonz should load all assets into the xsheets columns/timeline rows

### Actual Results
Drag & Drop operation: 
OpenToonz refuses to load assets when .tga files are inside the folder

Load Folder command:
OpenToonz crashed 

### System Information
* **OpenToonz Version**: OpenToonz 1.4rc
* **Operating System**: Windows 10 Build 19035
* **CPU**: AMD Ryzen™ 3 2200G
* **Memory**: 8 GB
* **Graphics Card**: (APU) Radeon™ Vega 8 Graphics

**Comment by manongjohn** [comment]
Seems the `Load Folder` process does not like loading TGA files if the filename sequence notation uses the _xxxx. notation (underline-dot).  If it is the .xxxx. notation (dot-dot), it loads fine.
