### ISSUE TITLE
FX spiral

### ISSUE THREAD

**Issue by gianlucagiacometti** [opentoonz/opentoonz#3055]
Any chance to have a logarithmic spiral as well?
The FX->Gradient->Spiral is an Archimedean spiral  `r=aß`; it would be useful to add also a Logarithmic spiral `r=ae^(kß)` which often appears in nature.
Thank you
Gianluca

**Comment by shun-iwasawa** [comment]
@gianlucagiacometti 
LIke this? 😉 

<img src="https://user-images.githubusercontent.com/17974955/73049249-4d9c8380-3ebf-11ea-872d-32fc975fbd5b.png" width=300>

**Comment by gianlucagiacometti** [comment]
Yes! That would be perfect, thank you!
