### ISSUE TITLE
Render threading issue

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3056]
Disclaimer: Multi-threading is far outside my realm of experience so I don't really understand what's going on under the hood.

Crashes & hangs when rendering have been mentioned by many other users over the past few years.
One of the main causes appears to be an underlying issue with OT's threading in regards to multi-threaded rendering.
The hangs seem to be a direct result of OT wrongly attempting to destroy a locked mutex, as can be seen with error message printed: 'QMutex: destroying locked mutex'
![image](https://user-images.githubusercontent.com/42905003/73019329-4c197f80-3e1b-11ea-87f8-27f590d9b248.png)

A quick way of triggering this hang is to have the Render Preview window open (by pressing Ctrl+R) and quickly making many changes in order to force the frames to be regenerated repeatedly. 
The length of time the frames take to calculate appears to increase the chance of the hang, i.e. a more complex scene is more likely to encounter this issue.

Other threading-related issues may manifest when performing the above steps:
The entire range of frames is rendered multiple times repeatedly even if they have already been rendered
![Render_Multiple](https://user-images.githubusercontent.com/42905003/73017799-4e2e0f00-3e18-11ea-8759-e7e3cf989966.gif)
In this gif, you can see that none of the frames are red after the first render, yet they are rendered two more times.
Closing and reopening the Render Preview window alleviates this particular issue.

**Comment by RodneyBaker** [comment]
I believe this may be  resolved, at least for processes using ffmpeg.
REF:  #4205

**Comment by RodneyBaker** [comment]
Closing but if this doesn't meet the intention please let us know @WolfInABowl
