### ISSUE TITLE
Can't change the DPI in the drawing preferences, grey and at 120

### ISSUE THREAD

**Issue by Lovewyrm** [opentoonz/opentoonz#3061]
I'm on commit: 7f56cb89d344dd63fde0225e56ea2e9649f4a444

The DPI settings are grayed out in the preferences under drawing (but show 120).

I see no DPI settings in the camera settings, or output settings or level settings, or english setter settings or any other of the various settings one could set to settingly change settings in a setting setting way...
Despite these things showing up in the online docs and on various newsgroup posts.

I combed through the git log and found nothing that jumped out at me immediately.
I'm on Slackware Linux 64 bit.

What am I missing here? << Cause I'm mighty confused by this... makes dealing with vectors strange.

**Comment by RodneyBaker** [comment]
As vectors are resolution independent and don't have any DPI... and as some raster image formats don't store DPI information... DPI will revert to the default DPI set in Preferences > Drawing for those cases.

The reason the DPI is grayed out in Preferences for you is likely that you have the default image/level type set to Vector.   Change that to raster or toonz raster and you'll see that no longer grayed out.

Camera DPI can be changed in several locations but primarily via menu; Xsheet > Camera Settings.

**Comment by Lovewyrm** [comment]
My default level is set to toonz raster and there are literally no DPI controls for me anywhere like that.
I've seen the screenshots in the docs and in the newsgroup, the fields are straight up missing from my dialogues.

https://imgur.com/a/suokZap
Note: The resolutions are different in this case but matching them makes no difference anyway.
Neither does unchecking "New Levels Default to the Current Camera Size" enable the DPI textbox in the preferences.

I can not change DPI (to my knowledge so far) through OT itself, only through my ini file via text editing.

Which doesn't even seem to make any difference in vector fidelity anyway, I just can't get smooth lines, it's always 'rasterized' looking even at high resolutions. I don't really like vectors anyway lol but the confusion from this behavior is still real.

Probably my fault for misunderstanding something but can't say this curious case of the missing setting is helping much...

**Comment by Lovewyrm** [comment]
Hmm, it turns out that actually rendering the cut makes the vector lines as smooth as the camera/output resolution allows. 
It's merely the preview that behaves wonky.

Example: Draw a small vector design in an isolated vector level (as in, drawing it not in the 'xsheet' view with everything composed together).
Then go to the xsheet view, the small vector design will look all pixelated in the preview etc because at this small scale the resolution simply cannot display more pixels than that.

Then, scaling this small design up with the animation tool, but the preview will still display it in a pixely way in the preview (and by preview I mean the eye in the viewer).

Actually rendering it out is working as intended.
Confusing but at least now I know.

**Comment by RodneyBaker** [comment]
Make sure you don't have 'Vizualize Vector as Raster' turned on in the menu; View > Visualize Vector as Raster

**Comment by RodneyBaker** [comment]
Closing as this may be more of a topic for the Opentoonz Troubleshooting forum than for a bug report.

https://groups.google.com/forum/#!forum/opentoonz_en

Discussion can continue here in the closed report as well as necessary.

**Comment by gab3d** [comment]
@Lovewyrm 
You have the Preferences > Interface > **Only Pixels** option on.
When you do so, no DPI data is used in OpenToonz, that's why it is not shown.

**Comment by Lovewyrm** [comment]
Ohhhh, I see, you are absolutely right, I did have that on and now the field IS editable.
Thanks.
