### ISSUE TITLE
Part of the Russian interface flies

### ISSUE THREAD

**Issue by jrhyme** [opentoonz/opentoonz#3062]
After deleting the stuff folder and installing the program, part of the translation flies, the beeheemooth has the same problem

![OpenToonz_CkJwwQjoFq](https://user-images.githubusercontent.com/49364531/73145449-50ad9480-40b6-11ea-9103-becc2a181987.png)

It was Accuracy - Точность, smooth - плавность e.t.c

### System Information
* **OpenToonz Version*1.4 (last nightless)*: 
* **Operating System *windows 10*:

**Comment by shun-iwasawa** [comment]
Thank you @jrhyme for the report. 
Oddly, it seems to have no problem in the translation file ( `tnztools.ts` ), but I once open it in Qt Linguist and click the problematic items, they unexpectedly change their state to `Unfinished` .

I'll try re-uploading them anyway.

**Comment by shun-iwasawa** [comment]
Ah! I finally found a probable cause and will fix right away.

**Comment by manongjohn** [comment]
As I provided the qm when I built the Russian translations, was there something I did incorrectly?

**Comment by shun-iwasawa** [comment]
@manongjohn No, actually it was totally my mistake when I separated the conventional brush tool class into ones for toonz raster and for toonz vector.
