### ISSUE TITLE
[Proposal] Preferences:  Move options to Saving category 

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#3068]
@shun-iwasawa @manongjohn 
I'll copy this proposal from #2543 here, to gain visibility...

Move backup saving preferences to the Saving category.
This reorganization would, both, unclutter the General section, and find a more logical place for these options too:

![imagen](https://user-images.githubusercontent.com/18104091/73176930-6ccc2880-40ec-11ea-91a3-68e35b00b2e7.png)

![imagen](https://user-images.githubusercontent.com/18104091/73176940-735aa000-40ec-11ea-815f-7ca5c01861f3.png)

**Comment by DarrenTAnims** [comment]
Looks like a great change to me.

**Comment by RodneyBaker** [comment]
Thanks @gab3d 
Adding this report as a reference in #2923.

**Comment by gab3d** [comment]
:muscle:
