### ISSUE TITLE
Curves FX crash

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3069]
gif example:
![Curves Crash](https://user-images.githubusercontent.com/42905003/73201672-7330c380-4131-11ea-9f0b-414cae290b1f.gif)

Repro steps:
1. Create a Curves node
2. Drag the top right point to the bottom left corner or the bottom left point to the top right corner

OT will crash

OT Ver: 1.4 [Jan 24 Nightly]

**Comment by RodneyBaker** [comment]
I confirm the crash here.
