### ISSUE TITLE
Join vector using tape tool may create buggy stroke

### ISSUE THREAD

**Issue by pojienie** [opentoonz/opentoonz#3072]
### Issue Summary
When using tape tool to join two strokes together, if those points are at the exact same position, it might create a buggy stroke which contains one too few points at one end. When trying to manipulate the missing point, opentoonz will crash.

### Screenshot or Video Reference
https://www.youtube.com/watch?v=snDS_qMRy-Q

### Steps to Reproduce
1. create a toonz vector level
2. draw a stroke using geometric tool with Arc shape and snap option checked
3. draw another stroke but with one end snapped to one end point of the first stroke
4. use tape tool with normal type, endpoint to endpoint mode, join option selected, and smooth NOT selected to connect the connecting end points (the two you snapped together in step 3)
5. use control point edit tool to manipulate the missing point

### Expected Results
creates a not buggy stroke. If possible, the resulting stroke should have only 1 point in the place where it connects.

### Actual Results
the result stroke will contain one too few points and when you try to manipulate it, opentoonz will crash.

### other info
If you try to move the connecting point first, the stroke will be fixed. (video: https://youtu.be/hcRo29Iyg4Y)
If the smooth option is checked in tape tool, this won't happen
If you join two lines, this won't happen.
If you draw line first then an arc, this will happen. If you draw arc first then a line, this won't happen.

log when the crash happens: opentoonz/toonz/sources/tnztools/controlpointselection.cpp:528: bool ControlPointEditorStroke::isSpeedInLinear(int) const: Assertion `index < (int)m_controlPoints.size()' failed

### System Information
* **OpenToonz Version**: latest nightly (1af1ae59bc6275dc28650f25d6a98bc66fe3b848)
* **Operating System**: Arch linux 5.4.11-arch1-1 with i3 as desktop environment
* **Graphics Tablet**: Mouse

**Comment by WolfInABowl** [comment]
Can confirm both the bugged stroke and the crash.

**Comment by beeheemooth** [comment]
I got such a crash using the mouse. There is no problem using the tablet.

mouse
![ezgif-3-e24941449bc5](https://user-images.githubusercontent.com/25724133/73284423-38945d00-41fd-11ea-8933-a685c28952b5.gif)

**Comment by gab3d** [comment]
I could not reproduce it (Windows 10, mouse or tablet, geforce)

**Comment by gab3d** [comment]
Aside from the bug, I don't really know why the Tape tool doesn't merge the two joined vertices, when they are closer than a given threshold distance, this would be saner and much more easy for editing at a later time. 🤔
