### ISSUE TITLE
ninja build broken

### ISSUE THREAD

**Issue by eszlari** [opentoonz/opentoonz#3085]
The ninja build worked in 1.3.0.
```
ninja: error: build.ninja:1488: multiple rules generate tnzcore/CMakeFiles/tnzcore.ts_lst_file [-w dupbuild=err]
```
https://flathub.org/builds/#/builders/48/builds/1691

(tested with cmake 3.13.4 & ninja 1.9.0)

**Comment by RodneyBaker** [comment]
This could use an assist from someone else that uses ninja to build Opentoonz.
@eszlari The official build has never used ninja but was considering the merits of adding it so if you have additional information related to ninja related issues it will be appreciated.

**Comment by eszlari** [comment]
Actually, the build with ninja fails because they changed a warning into an error between ninja v1.8 and v1.9: https://github.com/ninja-build/ninja/issues/931

Maybe you can take inspiration from this Krita commit to fix it:
https://github.com/KDE/krita/commit/e9b99ee5b75102a454dd728c81581dba92e19c4e

**Comment by shun-iwasawa** [comment]
You can now avoid errors by adding an option `-DWITH_TRANSLATION=OFF` to cmake command.

**Comment by eszlari** [comment]
But doesn't that mean, there are no translation when built with ninja?

**Comment by shun-iwasawa** [comment]
The translation projects which will be generated with `-DWITH_TRANSLATION=ON` are utility projects for updating `.ts` files based on the current source code.
You can still use the [update script](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/translations/update.sh) or manually call `lupdate` to do the same thing.

And if you do not update the translation you don't need them and OT works as-is.
