### ISSUE TITLE
Failed to load PSD layer if it has Japanese name

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#309]
When loading PSD file, if a layer name includes Japanese letter (such as "背景"), it fails to be loaded with error message "Layer ID not exists".

**Comment by kogaki** [comment]
Does it happen for all not `ascii` characters ?

**Comment by ullebulle** [comment]
This has happened to me too, several times. But in my case it has nothing to do with non ascII characters. OT can open psd files saved from photoshop but if the psd has been edited and saved in another graphical editor, I'll get the same "Layer ID not exist" - message when trying to open it in OT, maybe it has something to do with that?

**Comment by kogaki** [comment]
OK, we now fixed for `Japanese Photoshop` version of psd file. So this issue will closed.
But there remain another problem for other languages or other text-encodings.
