### ISSUE TITLE
Disable antialiasing on vector levels

### ISSUE THREAD

**Issue by mosujiba** [opentoonz/opentoonz#3101]
By default, the program smooths out vector lines when rendering them, but it provides no option to keep them pixelated.
In (Render->Output Settings), there is no setting to control antialiasing. 
In (Level->Export Level), there is a "No Antialias" option, but it seems to have no effect.

### System Information
* **OpenToonz Version**: 1.4
* **Operating System**: Windows 10

**Comment by WolfInABowl** [comment]
This is not currently possible in an automatic manner.

Though, through the use of FX nodes it is possible to get aliased results, though this approach becomes less practical the more colors there are. As such, I would recommend to only use this approach before painting your drawings.

To get an aliased result you can use these three nodes:

PaletteFilter: this allows you to separate colors based on their style index.
You will need to use this node for each of your colors.

Curves: this is used to crush the alpha channel to remove any translucent pixels.
Move the handles together, the further they are to the left, the thicker the line.
![image](https://user-images.githubusercontent.com/42905003/74458976-68d92e00-4e82-11ea-9227-2ea186299959.png)

Over: this is used to combine the separated and binarized colors.

**Comment by gab3d** [comment]
Perhaps this could be an option in the Scene Settings window, together with the Subsampling options (if it were something to be applied globally), or in the Level Settings window (if it were something to be applied on a level by level basis).

**Comment by Lovewyrm** [comment]
Yeah, this has thrown me for a loop when using vectors, too.
On one hand, it makes sense because OT ultimately produces raster output (unlike flash player which directly works with the vectors and 'renders' them on the fly).
On the other hand, vectors are still a mathematical construct and can therefore be rendered in (almost) any way, including aliased.

If the raster pen can do it, vectors should be able to do it, too.

**Comment by RodneyBaker** [comment]
It is strange that rendering out with Toonz raster levels can produce sharper/crisper lines than vector levels.

A workaround (of sorts) in some cases... without resorting to processing the files via FX in the Schematic is to convert the vector levels to TLV (toonz raster) just prior to final rendering.

![animeboyz](https://user-images.githubusercontent.com/2576432/75100374-f820c880-5589-11ea-88f5-b475394a8ef2.gif)

**Comment by RodneyBaker** [comment]
I'm not sure if this question ever got answered to your satisfaction @mosujiba
Inquiring minds want to know.

**Comment by mosujiba** [comment]
I still find it rather limiting that OpenToonz does not allow you to directly adjust vector aliasing. In fact, it does not even tell you what sampling algorithm is being used under the hood.

I noticed that, under (Preview Settings) and (Output Settings), there are many options to control 'Resample Balance' . Perhaps a similar menu could be implemented for vector sampling.
 
![sampling](https://user-images.githubusercontent.com/5388020/158310407-3ac3c4eb-17dc-4dbf-8f0b-dd7664a1954f.png)
