### ISSUE TITLE
Texture, PaletteFilter, and ColorBlending - crash when using a hyphen

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3111]
gif example:
![PaletteFilter crash](https://user-images.githubusercontent.com/42905003/75062500-d288b600-54da-11ea-9c1c-3b5b6a8e0664.gif)

Repro Steps;
1. Create a Texture or PaletteFilter node, 
2. Create a ToonzRaster or ToonzVector level and connect to the created node's Source input, this is needed so the node computes. Otherwise nothing will happen.
3. In the node's Indexes box, enter a hyphen
4. Attempt to render

OT will crash

I encountered this when accidentally pressing - instead of 0

Edit:
This does not seem to happen with the ArtContour or CalligraphicLine nodes

Interestingly, Texture and PaletteFilter crash no matter the type of level connected, but ColorBlending does not crash with zerary levels.

OS: Win 10
OT Ver: 1.4 Feb 20 Nightly

**Comment by RodneyBaker** [comment]
I still get a crash when using ONLY a hyphen.
Importantly, we can still use a hyphen that separates color style numbers.

![image](https://user-images.githubusercontent.com/2576432/155466211-fe952c15-77f9-4cdf-ba78-ad5d278a3c76.png)

I'm attaching a project file that sets up the scene for success as well as crash when removing the color style numbers.

Of note, final render shouldn't be needed to get the crash.  I observe the same when using Preview.

[crashwithonlyhyphen.zip](https://github.com/opentoonz/opentoonz/files/8129981/crashwithonlyhyphen.zip)


Workaround:   Don't enter a hyphen for the value of color styles.  :)
