### ISSUE TITLE
Some actions are rescalling all my controls except for viewer 

### ISSUE THREAD

**Issue by martynk666** [opentoonz/opentoonz#3113]
### Issue Summary
I saw this bug being reported here but ticket have been closed. I tried to upgrade my drivers and it didn't helped. I also check Windows scaling, multiple displays, changing resolution with no luck. It completely
[DxDiag.txt](https://github.com/opentoonz/opentoonz/files/4241617/DxDiag.txt)
 block me from doing anything in OpenToonz:((((

### Screenshot or Video Reference
![image](https://user-images.githubusercontent.com/48645450/75115442-e1987100-565e-11ea-820f-f8f9bf3bd36f.png)

### Steps to Reproduce
I have 100% repro when eg. creating new level in Animation tab

### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**: 
Intuos 5 Pro

**Comment by manongjohn** [comment]
This is a dupicate issue.

What graphics card do you have? There are 2 different fixes for this, but need to know what your graphics card is.

**Comment by RodneyBaker** [comment]
Can you provide the make/brand of your graphics card?

There is a known issue with Intel graphics where the latest driver installed doesn't adequately reflect the latest driver.

Driver utilities have been reporting that systems are updated with the latest driver but there is a newer driver available for download via the graphics card manufacturers website.  If you didn't get the driver directly from the website and updated through a software updater/utility you likely did not get the latest driver.

This is the message posted on the Opentoonz download page:

> For Windows users: There is a known issue that OpenToonz GUI irregulary scales when used on PC with some version of Intel Graphics Driver. Installing the latest driver (26.20.100.7584 and newer) will resolve the problem. If it is not yet listed in Windows Update, please try updating via Intel's website.

The intel link:  
https://www.intel.com/content/www/us/en/support/detect.html

**Comment by martynk666** [comment]
Thanks guys!!! It was intel drivers. I updated only drivers for Nvidia card. It looks like it's working correctly!

**Comment by manongjohn** [comment]
Fyi, the other way to fix this was to create a 3D profile in the NVIDIA Control Panel configured to use the High Performance GPU of the nvidia card.
