### ISSUE TITLE
I can't open scene

### ISSUE THREAD

**Issue by aiovn1989** [opentoonz/opentoonz#3118]
### Issue Summary
I could not open the scene (previously I opened them normally and after adding the png files it could not open, sorry my english is so bad, thanks everyone

**Comment by RodneyBaker** [comment]
The first thing I note is that you appear to be running on older v1.3 release of Opentoonz.
It would be good to update to a current v1.4 release.

**Comment by aiovn1989** [comment]
I installed version 1.4 but after the error I tried reinstalling version 1.3 and did not open
[OpenToonz stuff.zip](https://github.com/opentoonz/opentoonz/files/4265510/OpenToonz.stuff.zip) version 1.4

**Comment by artisteacher** [comment]
If you haven't already, try renaming the Stuff folder before installing 1.4.

**Comment by aiovn1989** [comment]
I reinstalled version 1.4 and copied the old stuff folder but still couldn't open

**Comment by manongjohn** [comment]
What was the error you are getting? OT opens fine, just not the scene?

**Comment by aiovn1989** [comment]
@manongjohn yes, opentoonz opens normally, only when loading the scene will the software hang.

**Comment by manongjohn** [comment]
Good news.  I found out it's something in your scene file.  Somehow it saved Horizontal/Vertical Guides with invalid values:
>>
    <hGuides>
      inf 
    </hGuides>
    <vGuides>
      77.8419 -20.1077 
    </vGuides>


Here is a corrected a.tnz file for you to replace your bad one with (removed the .txt extension)

[a.tnz.txt](https://github.com/opentoonz/opentoonz/files/4267575/a.tnz.txt)

**Comment by aiovn1989** [comment]
It works, thank you very much bro. I love you.
