### ISSUE TITLE
OSX nightly build 8105532 16/5 hangs on the splash screen

### ISSUE THREAD

**Issue by Gulwer** [opentoonz/opentoonz#312]
Hi
The latest build 8105532 16/5 stops at the splash.
<img width="639" alt="skarmavbild 2016-05-16 kl 17 57 18" src="https://cloud.githubusercontent.com/assets/18187452/15295335/4e0fba9a-1b90-11e6-9309-9e8be4dc5bec.png">

**Comment by agbarrows** [comment]
this is the error message:
![schermata 2016-05-17 alle 09 56 48](https://cloud.githubusercontent.com/assets/18673714/15315071/d0c3f552-1c15-11e6-9ee0-9524c5fd9cb4.png)

**Comment by kogaki** [comment]
We now found that builds after `2016-05-16 12:07:01 UTC ` not works and are debugging. Plz use builds before them from <https://github.com/opentoonz/opentoonz_nightlies/releases>. Thanks.

**Comment by Gulwer** [comment]
Hi again
The build from 13/5 crashes when you use the brush tool. see #302  
[Opentoonz_crash_15_5.docx](https://github.com/opentoonz/opentoonz/files/267876/Opentoonz_crash_15_5.docx)

**Comment by kogaki** [comment]
Now this has been fixed with #316. Thanks.

**Comment by Gulwer** [comment]
Thanks for your work kogaki
