### ISSUE TITLE
Auto Create New Drawing When a New Keyframe is Created

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3126]
It would be great if there was a setting to make it so when you create a new keyframe in the Xsheet or Timeline, the current drawing of the keyframed thing is automatically duplicated. This would make OpenToonz way more intuitive! I'm thinking this setting could be enabled by default for new projects, but maybe disabled by default for existing projects.

### System Information
* **OpenToonz Version**: 1.4.0
* **Operating System**: macOS Catalina
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by DarrenTAnims** [comment]
Can you leave a few more details? I'm not sure where this would be useful. I'm guessing that you mean adding a key by using the animation tool or pressing the key button to add a current key position for all items affected by the animation tool. Using those 2, I don't think I'd see the benefit of another frame being added, but I'm happy to learn a new workflow.

**Comment by MrBlockCat** [comment]
Oh, as it turns out I just severely misinterpreted what keyframes do in OpenToonz. Sorry! I'll close this issue
