### ISSUE TITLE
Some Command Bar Icons are Pixelated

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3128]
### Issue Summary
On the Command Bar, some icons appear pixelated on screen, with the exception of text-based ones like 1's, 2's, and 3's. There are some other exceptions I've noticed too, namely the three New Level buttons. I've attached an example.

### Screenshot or Video Reference
<img width="446" alt="Screen Shot 2020-03-03 at 12 08 13 PM" src="https://user-images.githubusercontent.com/37186692/75800504-aaede500-5d47-11ea-8375-1a335add35d6.png">

### Steps to Reproduce
Use a high resolution display (this becomes pretty noticeable to me because I'm using a high-resolution 2560 x 1600 display.)

### Expected Results
All icons show up at native resolution

### Actual Results
Some Command Bar icons show up pixelated

### System Information
* **OpenToonz Version**: 1.4.0
* **Operating System**: macOS Catalina
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by MrBlockCat** [comment]
This would also make #3123 look nicer!

**Comment by MrBlockCat** [comment]
https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/toonz/Resources This seems to hold most of OpenToonz's icons, including XSheet Toolbar ones. The ones that are still .png should probably be moved to .svg, that seems to be what's causing this problem. At some point I can help replace these, but that would probably take a while for me to do alone!

**Comment by MrBlockCat** [comment]
I noticed as I was going through a couple of these icons that we have both a rotate.png and a rotate.svg in that folder. Both look a lot like the Rotate tool's cursor, which is strange since the cursors are in their own folder, I think, and the Rotate tool's icon in the tool bar is different from those. What are either of those two used for? Can we simply delete at least rotate.png?

**Comment by MrBlockCat** [comment]
Also, I could make a PR with new icons as I make some of them, except I don’t know OpenToonz’s code very well! So I’ll just upload the SVGs I make to this issue and rename the file extension to PNG since GitHub doesn’t like SVGs for some reason, and then hopefully someone knows how to implement them haha

**Comment by artisteacher** [comment]
You can also upload a zipped file or folder. No need to use the wrong extension.

**Comment by MrBlockCat** [comment]
Good call! I'll do that then, once I have the time to make more

**Comment by MrBlockCat** [comment]
[SVG Icons.zip](https://github.com/opentoonz/opentoonz/files/4333715/SVG.Icons.zip)

I fixed the two lowest quality of the default XSheet Toolbar icons, repeat and collapse, here. I'll add more over time, though SVGs take a while to make!

Also worth noting is that I made it so the collapse icon's _click variant is white instead of a darker gray, so it matches with other _click variants. Is that good?

Out of curiosity what are the _click and _over variants used for, if anything? At least from my small amount of investigating in OpenToonz's XSheet Toolbar it looks to me like only the main variant is used, at least in the XSheet Toolbar.

**Comment by MrBlockCat** [comment]
The three XSheet Toolbar new level buttons all are SVG, but their _click and _over counterparts are PNG, and this is also the case for some other icons, which also leads me to believe they might be unused in the XSheet Toolbar.

**Comment by MrBlockCat** [comment]
[SVG Icons.zip](https://github.com/opentoonz/opentoonz/files/4340289/SVG.Icons.zip)

Here's a new version, with way more icons! This gets all the defaults, plus quite a few others, and the arrow that shows up when the XSheet Toolbar (or some other UI elements, like the normal tool bar) overflow. Here's some notes:

Colors:
Inside color: e1e1e1 (light gray)
Inside color for _click: ffffff (white)
Border: 000000 (black)

Icons changed:
1. repeat_icon.svg
2. repeat_icon_over.svg (should this be deleted?)
3. repeat_icon_click.svg (should this be deleted?)
4. collapse.svg
5. collapse_over.svg (should this be deleted?)
6. collapse_click.svg (made white from darker grey to match others) (should this be deleted?)
7. sub_enter.svg
8. sub_enter_over.svg (should this be deleted?)
9. sub_enter_click.svg (made white from darker grey to match others) (should this be deleted?)
10. sub_leave.svg
11. sub_leave_over.svg (should this be deleted?)
12. sub_leave_click.svg (made white from darker grey to match others) (should this be deleted?)
13. timestretch.svg (was svg, tweaked to match others, showed up blurry before so is this the wrong file?)
14. undo.svg (was svg, tweaked inside color to match others)
15. redo.svg (was svg, tweaked inside color to match others)
16. preferences.svg (was svg, tweaked colors to match others)
17. toolbar_arrow.svg

**Comment by MrBlockCat** [comment]
I believe the above folder is just about complete! There's one icon I'd like to change, but I can't find it in the files.
<img width="104" alt="Screen Shot 2020-03-16 at 8 33 35 PM" src="https://user-images.githubusercontent.com/37186692/76810706-69d4e680-67c5-11ea-8572-9525c419dd5d.png">

That one, with the tooltip "New Output", has a grey outline rather than black like the others do.

Besides that, though, all that should be needed for this now is for OpenToonz's code to be tweaked to call for the '.svg's instead of '.jpg's! Unfortunately, I'll have to leave that to someone else, as I don't know the code well enough...

**Comment by MrBlockCat** [comment]
I think I found the code where these are read by OpenToonz! I'll still definitely need someone to test this, since I don't have my own build environment (and'll probably wait until GitHub Actions is supported at this point), but I'll try and make a PR with the edited code and new SVGs.

**Comment by MrBlockCat** [comment]
I also found the New Output SVG icon file, it's in opentoonz/toonz/sources/toonzqt/Resources, rather than the opentoonz/toonz/sources/toonz/Resources that most other icons are in. Pretty strange how the icons are split across a few different locations, but that's a seperate thing I suppose. I'll tweak the New Output icon soon, I'm just waiting on a bug fix for my art program to let me do it.

**Comment by MrBlockCat** [comment]
Does anyone know where toolbar_arrow.png is currently referenced? I've looked and will keep looking all over the code but I'm having a very hard time finding it, and I'd like to replace it with toolbar_arrow.svg in this PR

**Comment by RodneyBaker** [comment]
This is the only place I see where toolbar_arrow.png is referenced:
https://github.com/opentoonz/opentoonz/search?q=toolbar_arrow.png&unscoped_q=toolbar_arrow.png

**Comment by MrBlockCat** [comment]
Awesome, thank you! I also didn't know that type of search existed to directly search all the code, I'd tried to figure out if that was possible before... This helps me in two different ways!
