### ISSUE TITLE
Tool Bar should be customizable

### ISSUE THREAD

**Issue by MsBlockCat** [opentoonz/opentoonz#3133]
This would make it so we can remove options we don't often use, or put ones we use a lot closer to the top. I think using code similar to how you can customize the XSheet would be ideal, though even a list of checkboxes to show/hide things like the Viewer tools have would be a good improvement!

**Comment by RodneyBaker** [comment]
Closing this as Custom Panels largely should fill this requirement.
@MsBlockCat Please let us know where that approach falls short.
