### ISSUE TITLE
Icon Size doesn't work

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3135]
### Issue Summary
Unless I'm misinterpreting what the setting does, it doesn't seem to matter what I make the icon size (In Preferences > Interface > Icon Size). That's even though I restart OpenToonz after changing the size. I tested this on macOS with OpenToonz 1.4 on a MacBook Pro display, as well as Windows 10 with OpenToonz 1.4 on a 768p display and OpenToonz 1.3 on a 1080p display. They all do it, so I doubt this is a platform or resolution issue.

### Screenshot or Video Reference
With 10x10 icons:
<img width="1552" alt="Screen Shot 2020-03-05 at 12 33 44 PM" src="https://user-images.githubusercontent.com/37186692/76008394-93e0fb80-5edd-11ea-995a-3fa745818e50.png">

With 400x400 icons:
<img width="1552" alt="Screen Shot 2020-03-05 at 12 42 16 PM" src="https://user-images.githubusercontent.com/37186692/76009162-c0e1de00-5ede-11ea-9194-641ee7a73ce4.png">

### Steps to Reproduce
Go to Preferences > Interface > Icon Size, change the Icon Size, and restart OpenToonz

### Expected Results
The icon size in the Tool Bar, Timeline, and elsewhere changes according to what the setting's set to

### Actual Results
The icon size displayed always stays the same

### System Information
* **OpenToonz Version**: Tested on 1.4.0 and 1.3.0
* **Operating System**: Tested on macOS and Windows
* **CPU**: dual core i3, quad core i5, and quad core Ryzen 5 tested
* **Memory**: 8 GB DDR4 and 16 GB DDR3 tested
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by manongjohn** [comment]
Icon size is for the icons in the Level Strip, not the xsheet/timeline icons.

**Comment by MrBlockCat** [comment]
Ah, I thought I might've misinterpreted it! Thank you, I'll close this issue. Maybe that checkbox should be renamed from "Icon Size" to "Level Strip Icon Size" for clarity though?
