### ISSUE TITLE
There should probably be a way to hide stuff related to the camera in the viewer

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3140]
To be perfectly honest, I don't fully understand how cameras work in OpenToonz yet, but my impression is that there's no way to hide the "Camera1" (or whatever you name the camera), the outline of where the camera sees, and the crosshair in the center of the camera's view (the purple stuff in the attached image).

<img width="763" alt="Screen Shot 2020-03-07 at 4 41 30 PM" src="https://user-images.githubusercontent.com/37186692/76152855-80c35c80-6092-11ea-8434-c06633920bbe.png">

In cases where a user doesn't need to work with the advanced camera stuff, it would be great if there was a way to hide those things in the viewer to declutter it a bit. I'm not sure what the best way to make that possible would be, maybe a setting, or maybe it could detect when there's only one camera and you've hidden the camera column in the Timeline/Xsheet (by right clicking a layer and choosing "Hide Camera Column"

**Comment by RodneyBaker** [comment]
Those can be turned off via the menu:   View > Camera Box.

![View Camera Box](https://user-images.githubusercontent.com/2576432/76155382-9d6a8f00-60a8-11ea-857b-1d93b5e69518.png)

Recommend closing.

**Comment by MrBlockCat** [comment]
Oh, thanks! Closing
