### ISSUE TITLE
assistant tool recurring click

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3143]
### Issue Summary

Since the assistants levels only work with the assistant tool, why not add a preference so that the assistant tool is activated as soon as you create or when you are on an assistant level, to avoid an additional recurring click. When we using several assistants levels for exemple.

### Expected Results

Assistant tool auto-activated on assistant level

**Comment by RodneyBaker** [comment]
The assistant tool hasn't been added to Opentoonz yet.
As such it's a bit premature to request modifications to it other than via the PR and or via forks/branches that have added it (ex:  OTX, Morevna)

**Comment by openanim** [comment]
Yes it was planned to close it. I just plan to create a bounty later. I preferred to write it now so as not to lose sight of it.
