### ISSUE TITLE
Crash when creating zerary node after cleaning up camera column cell

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#3153]
Repro Steps:

1. Select a cell in the camera column, or the camera column's header
2. Execute the `Scan & Cleanup -> Cleanup` command, nothing will appear to have happened
3. Attempt to create a new zerary node

OT will crash.

OS: Win 10
OT Ver: Mar 5 2020 Nightly

**Comment by RodneyBaker** [comment]
Sorry for the delay in confirmation.
I confirm the crash with the provided steps.
