### ISSUE TITLE
OpenToonz's title/tab bars should follow OpenToonz's theme

### ISSUE THREAD

**Issue by MsBlockCat** [opentoonz/opentoonz#3166]
### Issue Summary
This is a possibly weird one. On nightly and 1.4.0, OpenToonz always has light title bars (and tab bars, when you do View > Show Tab Bars), but when I build manually, it has either light or dark bars depending on the system theme.

### Screenshot or Video Reference
Nightly:
<img width="1439" alt="Screen Shot 2020-03-18 at 3 20 25 PM" src="https://user-images.githubusercontent.com/37186692/76998782-00231c80-692c-11ea-919e-87a681d3cec4.png">

Manually Built (from opentoonz/opentoonz)
<img width="1439" alt="Screen Shot 2020-03-18 at 3 21 06 PM" src="https://user-images.githubusercontent.com/37186692/76998839-192bcd80-692c-11ea-853e-09aabeb000ca.png">

### Steps to Reproduce
On a Mac, set the system theme to dark (System Preferences > General > Appearance: Dark)

### Expected Results
The title/tab bars should probably follow OpenToonz's theme

### Actual Results
The title/tab bars are always white on nightly/public builds, but on manual builds they follow the system theme

### System Information
* **OpenToonz Version**: 1.4.0, nightly, and manually built
* **Operating System**: macOS Catalina 10.5.3
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3

**Comment by manongjohn** [comment]
If I had to guess, this is likely because the nightlies are built on older macOS versions using older QT libraries than what you are building with.

Not necessarily sure an issue is needed for this.

**Comment by MrBlockCat** [comment]
That makes sense as to what causes the difference between the manual build and nightly, but would it be possible to make it so the OT themes modify the color of the title/tab bars for both nightly and manual builds? Ideally if it can be done I think they should probably follow OT's theme, not the system's anyway

**Comment by MrBlockCat** [comment]
As it turns out, this also happens on Windows! Specifically, the title bars are always white, at least as of 1.4.0, on Windows 10. I'd recommend removing the macOS tag, although I'm not sure how title bars react on Linux and I don't currently have a Linux OS so I can't vouch for what happens on there unfortunately.

**Comment by jeremybullock** [comment]
@artisteacher Does this happen on your builds?

**Comment by artisteacher** [comment]
@jeremybullock - Since I'm using the latest SDK (10.15) & QT 5.15.0, the title bar automatically updates to light or dark depending on what is set as the system theme. I can even change the system theme while Tahoma is open & the title bar updates automatically. On 10.13, the bar is always light, since there is no dark mode.

**Comment by artisteacher** [comment]
Dark theme macOS + dark theme Tahoma:
<img width="735" alt="Screen Shot 2020-09-29 at 10 55 41 PM" src="https://user-images.githubusercontent.com/21159116/94638265-9c4cb980-02a7-11eb-9430-1248646f90c5.png">


Dark theme macOS + light theme Tahoma:
<img width="733" alt="Screen Shot 2020-09-29 at 10 54 51 PM" src="https://user-images.githubusercontent.com/21159116/94638248-90f98e00-02a7-11eb-9bdf-7f8d9d62cd2d.png">


Light theme macOS + light theme Tahoma:
<img width="730" alt="Screen Shot 2020-09-29 at 10 56 31 PM" src="https://user-images.githubusercontent.com/21159116/94638193-73c4bf80-02a7-11eb-9c0e-45c775e43bdc.png">

Light theme macOS + dark theme Tahoma:
<img width="733" alt="Screen Shot 2020-09-29 at 10 56 11 PM" src="https://user-images.githubusercontent.com/21159116/94638389-d74eed00-02a7-11eb-8a0b-b2ff531a292a.png">

**Comment by jeremybullock** [comment]
Awesome.  I was just trying to see if this is still an issue.  Thanks.

**Comment by RodneyBaker** [comment]
Closing as a stale report.
@MsBlockCat please let us know if this is still an issue.
