### ISSUE TITLE
UI Scaling Issue

### ISSUE THREAD

**Issue by rkuhlf** [opentoonz/opentoonz#3167]
### UI Scaled Incorrectly and Doesn't Interact
![Screenshot](https://user-images.githubusercontent.com/29072641/77089947-809d5800-69d4-11ea-8506-c5be04909459.png)
As you can see, the UI is much larger than it should be. Additionally, it doesn't interact correctly, and whenever I click on the window, it doesn't register it. Attempting to change rooms causes the program to crash. This error only occurs in this specific scene.

I am unsure of the cause, if I remember correctly the graphics displayed like that right after opening the program. The UI still displays correctly if I make a new scene.

### System Information
**OpenToonz 1.4**
**Windows**

P.S.
Any advice on how to save the things that I had already drawn would be greatly appreciated.

**Comment by artisteacher** [comment]
This looks like a known issue - #2840, #2965, #3078, #3039, #3113...

Usually updating the Intel driver fixes this, though there are some other fixes listed in the issues. Use Save-All (ctl+S) to save your scene & levels.
