### ISSUE TITLE
Have you ever considered packaging Linux?

### ISSUE THREAD

**Issue by qianyigengwu** [opentoonz/opentoonz#3173]
Here, the snap store is very slow to access, so Linux doesn't have a good installation method for opentoonz.

**Comment by RodneyBaker** [comment]
Several have indicated that the Morevna and OTX releases are solid releases for Linux.
Have you tried those?

Opentoonz Experimental (OTX)
https://github.com/manongjohn/OTX/releases/tag/OTX-2020-03-04

Morevna Edition:
https://github.com/morevnaproject/opentoonz/releases

**Comment by RodneyBaker** [comment]
Closing as I believe the current answer is no, there is no official support for Linux distros.
With regard to plans to support Linux, if/when Github Actions are turned on an automated Linux build will be a likely result. 

@qianyigengwu can you provide any additional information on the Snap store you reference.
This is the first report of difficulties logged and others involved in Snap distribution will be interested.

**Comment by RodneyBaker** [comment]
As a follow up to this...
Github Actions is now being employed to build Opentoonz Ubuntu (in both GCC and cmake flavors).
This is new for v1.5 and therefore evolving...
