### ISSUE TITLE
不好意思我英文不是很好 (Graphics Glitches)

### ISSUE THREAD

**Issue by kanrena** [opentoonz/opentoonz#3175]
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**: 

the boxes of tools in this soft are not in their places
I can’t click the right bottom I want because of the dislocation
some of the interfaces are bigger than others and I cant move them
![2020324-133311](https://user-images.githubusercontent.com/62585977/77391653-40731680-6dd4-11ea-83b6-dbc2910448c4.jpg)

**Comment by manongjohn** [comment]
This has been brought up a number if times.

2 things you can do...

If you have an Intel Graphics display driver, you may need to find and download the latest version. Don't rely on Driver Update as it may not detect it. Need to go onto intel's driver download site and check the version of the driver you have against yours. Manually download and install the driver upgrade it if you are not at the latest.

If you have driver version 26.20.100.7463 or a version of this graphic driver, try downloading and installing version 26.20.100.7584. Here is the direct download link:

https://downloadmirror.intel.com/29274/a08/igfx_win10_100.7584.exe

If you have an NVIDIA graphics card, this may work better for you: Enter the NVIDIA Control Panel and create a 3D Profile for OpenToonz.exe and if given the option, set to use High Performance GPU. You are essentially forcing OT to use your GPU which should fix the issue.

**Comment by artisteacher** [comment]
@manongjohn @shun-iwasawa - maybe the notification on the website needs to be more prominent.

**Comment by RodneyBaker** [comment]
Closing as a duplicate BUT @kanrena please let us know if following @manongjohn 's suggestions work for you.  If not we will investigate.

Gambate kudasai!
