### ISSUE TITLE
Grey Double Arrow in Toolbar, Xsheet Toolbar, etc.

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3185]
### Issue Summary
With newer versions of Qt (that's likely the problem), the double arrow used when icons overflow from the Toolbar, Xsheet Toolbar, and likely some other things is a grey SVG. This is replacing the black PNG that's still used in nightly builds, as nightly is built with an outdated Qt. For more details please see #3161 , but this in essence causes a problem because on some OpenToonz themes (especially Dark) the new grey arrow blends in too well, making it hard to see! I believe the ideal solution is to customize the new grey arrow to make it black again.

### Screenshot or Video Reference
Nightly with all tools and Collapse toolbar arrow visible
<img width="44" alt="Screen Shot 2020-03-18 at 11 12 18 PM" src="https://user-images.githubusercontent.com/37186692/77027947-eb677880-696d-11ea-8087-3e830f7b6b27.png">
(It's not there)

Manual with all tools and Collapse toolbar arrow visible
<img width="46" alt="Screen Shot 2020-03-18 at 11 13 05 PM" src="https://user-images.githubusercontent.com/37186692/77027981-09cd7400-696e-11ea-8b6c-0ee8ea030cd9.png">
(It's not there)

Nightly with all tools but not Collapse toolbar arrow visible
<img width="42" alt="Screen Shot 2020-03-18 at 11 13 45 PM" src="https://user-images.githubusercontent.com/37186692/77028007-1eaa0780-696e-11ea-9956-31030750d68d.png">
(It's grey)

Manual with all tools but not Collapse toolbar arrow visible
<img width="43" alt="Screen Shot 2020-03-18 at 11 15 11 PM" src="https://user-images.githubusercontent.com/37186692/77028092-531dc380-696e-11ea-8fa2-97145ab34ac4.png">
(It's even lighter grey)

Nightly with not all tools visible and Collapse toolbar arrow not visible
<img width="42" alt="Screen Shot 2020-03-18 at 11 15 47 PM" src="https://user-images.githubusercontent.com/37186692/77028122-67fa5700-696e-11ea-8d94-bb5503628cb5.png">
(It's black)

Manual with not all tools visible and Collapse toolbar arrow not visible
<img width="47" alt="Screen Shot 2020-03-18 at 11 16 28 PM" src="https://user-images.githubusercontent.com/37186692/77028178-81030800-696e-11ea-9b5c-8693b28d4f43.png">
(It's grey)

### Steps to Reproduce
Build OpenToonz with Qt 5.14.1 (in my case, on macOS; I'm unsure how this affects other OSs, but right now on Windows it's recommended to build with an outdated Qt version in our build docs which may be how this hasn't been caught)

### Expected Results
The new SVG toolbar arrow should be black

### Actual Results
It's grey, making it often hard to see

### System Information
* **OpenToonz Version**: Manually built
* **Operating System**: macOS Catalina 10.15.4
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3
* **Graphics Card**: Intel Iris Plus Graphics 645

**Comment by MrBlockCat** [comment]
I think the ideal way to fix this is to set this arrow to be [opentoonz/toonz/sources/toonz/Resources/toolbar_arrow.svg](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/Resources/toolbar_arrow.svg) , as doing this would make it work the same way across Qt versions, along with both being HD and black, unlike the old and new default toolbar arrows which are black and pixely, and grey and HD, respectively.

**Comment by MrBlockCat** [comment]
@RodneyBaker I've added a $10 bounty for this! https://www.bountysource.com/issues/90834084-grey-double-arrow-in-toolbar-xsheet-toolbar-etc

**Comment by konero** [comment]
This was fixed in #3457, you can close this.
