### ISSUE TITLE
On Macs Resize Brush Tool Still Shows Ctrl+Alt

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3189]
### Issue Summary
On Windows, the option in Preferences > Tools that says "Use Ctrl+Alt to Resize Brush" makes sense, but on Macs this should show Cmd+Option (is there a shorter term for Option?) as that's what you press to resize the brush

### Screenshot or Video Reference
<img width="889" alt="Screen Shot 2020-03-28 at 11 07 20 PM" src="https://user-images.githubusercontent.com/37186692/77839229-e1e9c780-7148-11ea-96e3-6d09e9f48d6a.png">

### System Information
* **OpenToonz Version**: March 28th Nightly
* **Operating System**: macOS Catalina 10.15.4
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3

**Comment by artisteacher** [comment]
This is really the same thing as #3130. All shortcuts using control or alt on Windows use command or option on Mac. Qt automatically interprets the keys as the same thing. Unfortunately right now that only impacts the function, not the display of the shortcut.

It looks like [QKeySequence::NativeText](https://doc.qt.io/qt-5/qkeysequence.html#SequenceFormat-enum) might be needed?

**Comment by MrBlockCat** [comment]
Would it be best if I combined this issue with #3130 ? I agree it’s similar, although I don’t know how any of the underlying keyboard shortcuts code works so I personally couldn’t say definitively if QKeySequence::NativeText would also work for that, but if you believe it would I could combine them!

**Comment by RodneyBaker** [comment]
My first thought is that this is such as simple fix (in comparison to the larger set of issues) that it might be best kept and resolved apart from others.  You are the author/dev for both though so you are the best one to make that call.  If there are things you can fix and others you cannot I'd think that might be a good place to separate one from the other.

**Comment by MrBlockCat** [comment]
I'll leave it separate, as you make a good point there. I probably can't resolve even this smaller issue myself, as I've looked into the link and I'm pretty sure I don't know enough C++/Qt to be able to implement it

**Comment by RodneyBaker** [comment]
I'm not a good judge of this issue because I see the Command and Control keys as equivalent.
But I'm not operating from the POV of a Mac user who has no choice but to make that distinction.
I do think that I would still likely have the same outlook if I was a Mac user and the shoes were on the other feet.

I don't suppose we could print out stickers to go on the command key that have both Ctrl and Mac Command symbol on them?

Aside:  How does one type the Mac command key when writing about it with text?
Tentative answer (besides using other methods such as ascii):   Use copy/paste!   ⌘

**Comment by MrBlockCat** [comment]
What makes keyboard shortcuts particularly confusing for people who use Macs is that Macs do have a Control button, it just doesn't do the same things as Control on Windows, so when apps don't change that for macOS it looks like the Control key does stuff it doesn't.

And I would love to see those symbols for Mac buttons implemented rather than the text on Macs! macOS tends to do this, as does Adobe Animate. If we could do that:

Command (Control on Windows): ⌘
Option (Alt on Windows): ⌥
Control (doesn't exist on Windows, so probably irrelevant to OT): ⌃
Escape (Escape on Windows): ⎋

Displaying the symbols probably(?) isn't possible with QKeySequence::NativeText, however, so that seems more difficult. Having the text be accurate to Macs on Macs is still a substantial improvement. Either way, nice to be able to use for typing!

**Comment by RodneyBaker** [comment]
It is interesting to note that over the course of 30+ years this issue has never been resolved.
It use to bug me that in books the writers had to stop and take the time to explain "Use Control (Command key on the Mac) + C to copy, etc.

We are own own worst enemies.
