### ISSUE TITLE
Resize Brush with Ctrl + Alt Should Follow Direct Mouse Movements

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3190]
### Issue Summary
There might be some reason this is worse or wouldn't work, so please let me know if I'm in the wrong! But to me it seems like it would be better if, rather than tracking the direction the mouse is in relative to the brush pointer when it moves and resizing the inner/outer brush based on how far it is in that direction, it tracked the mouse relative to where the mouse was the frame before.

### Expected Results
I think it would be more intuitive and easier to use if the inside/outside brush sizes were figured out based on if the mouse is currently moving left or right and up or down!

### Actual Results
Right now, no matter the direction you move your mouse, as long as it stays in one corner of the brush pointer, the brush's inside and outside will increase/decrease the same way when the cursor moves.

### System Information
* **OpenToonz Version**: March 28th Nightly
* **Operating System**: macOS Catalina 10.15.4
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3

**Comment by RodneyBaker** [comment]
@MrBlockCat Not to dampen your enthusiasm but some suggestions might be more appropriate for the Opentoonz forum where they can be discussed at length and explored in depth.  The OT Forum might be a better venue for discussing the merits of pursing one idea or another.

**Comment by RodneyBaker** [comment]
Regarding part of your query...

> it seems like it would be better if, rather than tracking the direction the mouse is in relative to the brush pointer when it moves and resizing the inner/outer brush based on how far it is in that direction, it tracked the mouse relative to where the mouse was the frame before.

As I'm interpreting this, the assumption is that there is a frame before the current frame being drawn on.  I would think it the process would at least have to account for a single frame with no  previous or subsequent frames. If everything else was in place for this... probably not much more difficult to account for cases with one frame though.

A bit more difficult perhaps...
Assuming I'm not reading this wrong, a new mechanism for storing the mouse's final position when leaving any given frame would need to be developed.

I guess I'm struggling a little envisioning what the primary purpose would be for the proposed enhancement and what success might look like.

**Comment by MrBlockCat** [comment]
Point well taken about the Google forum: I could move this there if you'd like! Although, if this is something it's agreed should be done, I'll likely add a bounty to this issue sometime soon, and prior to that at the least look into if I could do it myself.

I just thought of a much easier way to explain what I think would be best:

When the mouse moves away from the brush pointer in the x direction, I think the outer brush should get bigger. (Right now the outer brush gets bigger when the mouse moves at all but is to the right of the brush pointer)

When the mouse moves towards the brush pointer in the x direction, I think the outer brush should get smaller. (Right now the outer brush gets smaller when the mouse moves at all but is to the left of the brush pointer)

When the mouse moves away from the brush pointer in the y direction, I think the inner brush should get bigger. (Right now the inner brush gets bigger when the mouse moves at all but is above the brush pointer)

And when the mouse moves towards the brush pointer in the y direction, I think the inner brush should get smaller. (Right now the inner brush gets smaller when the mouse moves at all but is below the brush pointer)

Looking at it that way, I think we could probably avoid making a new mouse pointer detection system and instead use something pretty similar to what we have now. I believe this would be more intuitive for new users, and allow for much finer control for all users!

**Comment by RodneyBaker** [comment]
Do you know of any specific software that currently demonstrates the results you detail?
It would be good to explore that in action.

**Comment by MrBlockCat** [comment]
Only now am I realizing that my second idea was in fact different, and wouldn't work with decreasing the size of the min or max brush relative to where it was. Sorry! I guess that's why it has to have it based on overall direction. I'll close this.

**Comment by RodneyBaker** [comment]
I'm a fan of discussion continuing in closed reports as that can get ideals vetted and move them toward the goal of implementation.  At the same time a closed report doesn't generate too much distraction so that developers can concentrate on higher priorities.

Others have mentioned Brush resizing before so it will be good to get those thoughts into the mix as well.

**Comment by MrBlockCat** [comment]
Awesome! In that case, what turned out to be my first idea, described hopefully better below, should allow for making the brush bigger or smaller:

When the mouse moves right, I think the outer brush should get bigger. (Right now the outer brush gets bigger when the mouse moves, no matter the direction of its movement, as long as the mouse remains to the right of the brush pointer)

When the mouse moves left, I think the outer brush should get smaller. (Right now the outer brush gets smaller when the mouse moves, no matter the direction of its movement, as long as the mouse remains to the left of the brush pointer)

When the mouse moves up, I think the inner brush should get bigger. (Right now the inner brush gets bigger when the mouse moves, no matter the direction of its movement, as long as the mouse remains above the brush pointer)

And when the mouse moves down, I think the inner brush should get smaller. (Right now the inner brush gets smaller when the mouse moves, no matter the direction of its movement, as long as the mouse remains below the brush pointer)

**Comment by MrBlockCat** [comment]
[toonz/sources/tnztools/toonzvectorbrushtool.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/toonzvectorbrushtool.cpp) lines 1284-1295 and [toonz/sources/tnztools/toonzrasterbrushtool.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/toonzrasterbrushtool.cpp) lines 1791-1802 seem to hold the relevant code.
