### ISSUE TITLE
Some New Xsheet Toolbar Icons are Invisible

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3191]
### Issue Summary
On manual builds, the new SVG icons I recently added with #3161 (Repeat, Collapse, Open Sub-xsheet, and Close Sub-xsheet) show up as expected. However, on the latest nightly build for both Windows and macOS, those icons are invisible unless you hover over them! This happens in the Xsheet Toolbar, the Command Bar, and even the menu bar options (the one with File, Edit, Scan & Cleanup, etc.) I have no idea what could cause this, and it's very strange to me that it only shows up on nightly builds. What makes it odder yet is that the versions of the icons for when you hover your cursor over it were modified by me in the same fashion as the main icons. And whatever may have caused this, sorry!

### Screenshot or Video Reference
Not hovering my cursor over anything in a nightly build
<img width="366" alt="Screen Shot 2020-03-29 at 12 07 58 AM" src="https://user-images.githubusercontent.com/37186692/77840127-a69fc680-7151-11ea-9461-3faafe82445f.png">

Hovering my cursor over Open Sub-xsheet button in a nightly build
<img width="363" alt="Screen Shot 2020-03-29 at 12 08 06 AM" src="https://user-images.githubusercontent.com/37186692/77840098-604a6780-7151-11ea-9934-9ad6a77ac616.png">

Not hovering my cursor over anything in a manual build
<img width="368" alt="Screen Shot 2020-03-30 at 5 01 31 PM" src="https://user-images.githubusercontent.com/37186692/77961618-1c1dab00-72a8-11ea-9a0f-a73c3e029657.png">

Hovering my cursor over Open Sub-xsheet button in a manual build
<img width="365" alt="Screen Shot 2020-03-30 at 5 02 17 PM" src="https://user-images.githubusercontent.com/37186692/77961696-3788b600-72a8-11ea-903d-81712869ae6e.png">

### Steps to Reproduce
Download the latest nightly build and look at the Repeat, Collapse, Open Sub-xsheet, and Close Sub-xsheet icons, then try hovering over them

### Expected Results
The new icons should show up as others do, and as they do on manual builds

### Actual Results
The new icons I made don't show up on screen, besides the _over variants

### System Information
* **OpenToonz Version**: Latest nightly
* **Operating System**: macOS and Windows (untested on Linux but probably there too)

**Comment by MrBlockCat** [comment]
Something interesting to note is that the nightly also seems to generally render SVGs less well than my manual build, which leads me to believe this issue could somehow be related to Qt being outdated in nightly, but it's very hard for me to say

**Comment by RodneyBaker** [comment]
If Qt is outdated in nightly it is also in all the official releases too so...
Whatever you can add to provide additional detail concerning Qt version being used that might help in keeping all the official/master side of Opentoonz as up to date as possible.  Especially if you run into any issue that directly relate to current Qt releases not working as we will know what to avoid when moving forward.

When you build Opentoonz what release of Qt are you building against?

**Comment by MrBlockCat** [comment]
When I manually build, I do it using Qt 5.14.1 and Boost 1.72.0 on macOS Catalina 10.15.4

**Comment by RodneyBaker** [comment]
While I understand why there might be some hesitation to move too quickly to Qt 5.14.1 it certainly would be good to know what specifically is problematic in moving forward.

Of note:  The VFX Platform(https://vfxplatform.com/) recommends standardization on Qt 5.12.x for the film and effects industry.

**Comment by RodneyBaker** [comment]
To ensure maximum compatibility its good to standardize on a common set of tools and specifications.
One question though would be how best to allow for the testing and private builds that pave the way forward such as you have done by moving into Qt 5.14.1 and Boost 1.72.0.

If following the specs more strictly... it could be years before we reach those higher releases as a standard.

**Comment by MrBlockCat** [comment]
I’ve updated my comment with Qt differences I’ve found in OpenToonz between 5.14.1 and whatever nightly is built with. I’ve been meaning to downgrade my Qt on my Mac to verify that the differences go away when I do, I hope to try that soon.

**Comment by MrBlockCat** [comment]
I still think there’s also a decent chance this particular issue isn’t caused by Qt, since other icons aren’t affected, but I’ll be able to find that out if I temporarily downgrade Qt and rebuild... Maybe there’s some kind of additional filter done for files when they’re built for nightly? I don’t know all of the differences between how nightly is built and how I build so it’s very hard to say which might cause this

**Comment by MrBlockCat** [comment]
@RodneyBaker I believe you also built OpenToonz with the new icons when they were in my branch still, right? Do you happen to recall what Qt version you used, or other differences between how you built and how nightly is built? It would help to get more data points on this

**Comment by RodneyBaker** [comment]
Sadly, I've mostly built using Qt 5.9, as that is what was specified to be used, although I do recall attempting 5.12 some time back.  This is where I largely shifted to focusing on the automated builds generated via Appveyor.  

If we look in the appveyor.yml there is this note:

# C:\Qt\5.9 is mapped to C:\Qt\5.9.n for backward compatibility

See also the references to Qt 5.9 in the file here:

https://github.com/opentoonz/opentoonz/blob/master/appveyor.yml

I must assume that by and large most of what I have build locally has been with Qt 5.9 with an attempt to press into 5.12.

There was a PR some time back that adjusted Travis so that versions didn't have to adhere so strictly to specific versions allowing for use of Qt 5.13.  @manongjohn submitted that update.

**Comment by MrBlockCat** [comment]
Interesting. If you used an older version of Qt than the nightly and I used a newer one, the missing icons problem most likely isn’t with Qt, so that’s good in some sense, but it also means I don’t know what it could be!

Regarding Qt, though, I agree it should be updated (to the extent of my rather minimal knowledge), as they’ve fixed some longstanding issues we’ve had and it seems like the issues with updating would be fairly small (as far as I’ve seen, just the new grey double arrow needs to be tweaked by us to be black again)

**Comment by MrBlockCat** [comment]
I probably used createQIconOnOff wrong in mainwindow.cpp in #3161 , although I don't fully understand why createQIconOnOffPNG was used before since those icons don't seem to have _on and _off after their names. I'll look into this more!

**Comment by jrhyme** [comment]
I confirm the bug...

**Comment by RodneyBaker** [comment]
Yes, as reported here:

https://groups.google.com/d/msg/opentoonz_en/KRv45VLsQkM/EkPD6s4yAwAJ

Hopefully we can track down the cause so we don't have to revert the earlier PR.

**Comment by MrBlockCat** [comment]
Yup, apologies for causing this bug! I found a likely solution with #3198 , though since this only occurs in nightly builds and not manual ones it's impossible for me to test and make sure it is fixed. There's some underlying weirdness about why it does currently work in manual but not nightly that I have yet to understand, but that new PR should, fingers crossed, go over that issue.

**Comment by MrBlockCat** [comment]
I just tested, and on my MacBook this is indeed fixed! There might be some kind of underlying issue, but at least it's been covered up again.
