### ISSUE TITLE
Opentoonz aborted because of nouveau assertion.

### ISSUE THREAD

**Issue by GabrielCambe** [opentoonz/opentoonz#3193]
### Issue Summary

Sometimes as soon as i maximize the window of the program, when  i move some windows like the palette or others i get this, sometimes when i use the fill tool. The program simply closes, on the command line the last line i get everytime is this:
OpenToonz: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.
Aborted (core dumped)

### Screenshot or Video Reference

Link:  https://youtu.be/3hQkwBbhiHo

### Steps to Reproduce

I am not sure if this is reproducible or a problem of the combination of Opentoonz and my hardware.

### System Information
* **OpenToonz Version**:  Compiled 1.4.0
* **Operating System**:  Ubuntu 19.10
* **CPU**:  Pentium(R) Dual-Core  CPU E5400  @ 2.70GHz
* **Memory**: 
I have two instances of:
Memory Device
	Array Handle: 0x0031
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 2048 MB
	Form Factor: DIMM
	Set: None
	Locator: DIMM A1
	Bank Locator: BANK0
	Type: DDR2
	Type Detail: Synchronous
	Speed: 800 MT/s
	Manufacturer: Manufacturer0
	Serial Number: SerNum0
	Asset Tag: AssetTagNum0
	Part Number: PartNum0

So 4096Mb in total.

* **Graphics Card**:  
  *-display                 
       description: VGA compatible controller
       product: GT216 [GeForce GT 220]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:28 memory:fd000000-fdffffff memory:e0000000-efffffff memory:de000000-dfffffff ioport:dc00(size=128) memory:c0000-dffff

* **Graphics Tablet**: None
* **Kernel Version**: Linux 5.3.0-42-generic.

**Comment by RodneyBaker** [comment]
Could possibly relate to #3147 which has not yet been merged.

**Comment by GabrielCambe** [comment]
More errors happened but the message now is segmentation fault, so i do not know if i make another issue or something like it. Here:
https://youtu.be/sk1zQHYCJCs

https://youtu.be/acMcQE0OYec

https://youtu.be/YjUJmO0orhs

https://youtu.be/OCj_2SxWIvY

The next sessions i tried just froze my computer and i had to restart it.

Ill check the other issue and then reply later, thanks.

**Comment by GabrielCambe** [comment]
> Could possibly relate to #3147 which has not yet been merged.
> (It hasn't yet been validated/tested)

i have compiled the dwango plugins on ubuntu eoan ermine but they're not showing up on opentoonz

**Comment by RodneyBaker** [comment]
It is likely this crash report is resolved.
@GabrielCambe Can you confirm?

Note:  The building of the dwango plugins is an issue that would be best separated from the crash report.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.

**Comment by GabrielCambe** [comment]
> It is likely this crash report is resolved. @GabrielCambe Can you confirm?
> 
> Note: The building of the dwango plugins is an issue that would be best separated from the crash report.

Holy moses i didnt see the notification... Sorry! I could not find the source of the crashes, they used to happen in debian and ubuntu, but after i updated to 1.5 they stopped happening, but i also changed to linux mint and widnows 10. My bet is that probably it had something to do with my graphics card being old.

(Sorry for the year gap in repsonding again...)

**Comment by RodneyBaker** [comment]
Thank you @GabrielCambe for closing the loop on this one.
Even more importantly... glad to hear you are having success!
