### ISSUE TITLE
there were problems loading the scene C:\...... some files maybe missing: this is error i am getting when opening my scene

### ISSUE THREAD

**Issue by lectura** [opentoonz/opentoonz#3197]
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

**Comment by RodneyBaker** [comment]
@lectura If you are having trouble posting to github you might want to post your issue to the Opentoonz Forum's troubleshooting area:

https://groups.google.com/forum/#!categories/opentoonz_en/troubleshooting
