### ISSUE TITLE
Pinch Tool Manual Influence Adjustment Unresponsive

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#320]
Although the manual adjustment (dragging square icon) for the Pinch Tool works when the view is zoomed in closely - (displaying the variably adjustable green influence curve) - it becomes almost impossible to obtain this behavior when the view is zoomed out moderately.

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
