### ISSUE TITLE
Motion Blur with Rotation, Scale, Shear, Etc.

### ISSUE THREAD

**Issue by opentoonzuser111** [opentoonz/opentoonz#3206]
Using the Motion Blur effects don't seem to do anything when keyframing anything other than position such as rotation, scale, shear, etc. When will these other types of motion be taken into account? The documentation says

> No result will be visible if the motion blur is applied to a column that always stands in the same position while the content is a level where the movement is drawn.

Is this why motion blur doesn't work with the other movements besides position? If so, can the Motion Blur effect be improved to account for the other keyframes?

**Comment by RodneyBaker** [comment]
We can set the option to Camera and use the cameras motion.
Hmmm... makes me want to do a few experiments.

This is probably a discussion better suited for the Opentoonz Forum until such a time as an actual feature request with specific targets to hit can be produced.

**Comment by opentoonzuser111** [comment]
> 
> 
> We can set the option to Camera and use the cameras motion.
> Hmmm... makes me want to do a few experiments.
> 
> This is probably a discussion better suited for the Opentoonz Forum until such a time as an actual feature request with specific targets to hit can be produced.

Changing the camera rotation, scale, shear, etc. doesn't seem to have an effect either with the Motion Blur effects.

**Comment by RodneyBaker** [comment]
Can you share a project file of what you are trying to add motion blur to?

**Comment by opentoonzuser111** [comment]
![test](https://user-images.githubusercontent.com/63019924/78200326-1f00d300-7443-11ea-89c3-3eec483ea678.gif)
This is the output of a rotating square with the rotation keyframed for Col1 and a default Motion Blur effect set between Col1 and XSheet. There is no motion blur. I'm assuming this is because of

> No result will be visible if the motion blur is applied to a column that always stands in the same position while the content is a level where the movement is drawn.

**Comment by shun-iwasawa** [comment]
Unfortunately neither the Motion Blur nor the Motion Blur Iwa fxs support movements other than position.

The Motion Blur is basically the same as the Directional Blur. The only difference is that the direction and the amount of blur is defined by the column movement. OTOH the Motion Blur Iwa will filter the image by using trajectory of the column.

Both fxs have a common point - they create some filter and apply it uniformly to whole pixels in the source image. It works based on an assumption that all pixels move the same speed and direction.

If the fxs need to take into account other movements like rotation and scale, the above method will not work since the movement of the pixels may vary according to the locations.

**Comment by RodneyBaker** [comment]
A random thought related to @shun-iwasawa 's feedback...

In some cases of rotation perhaps using a Spin Blur would be more ideal that Motion Blur?
Use of Direction Blur might be more appropriate in cases of Scale and Skew?

I was responding to someone else about something similar a year or so ago and we produced some pretty nice results.  Unfortunately, I cannot find that discussion.  I believe it was with @snapai perhaps via discord.

**Comment by opentoonzuser111** [comment]
> 
> 
> Unfortunately neither the Motion Blur nor the Motion Blur Iwa fxs support movements other than position.
> 
> The Motion Blur is basically the same as the Directional Blur. The only difference is that the direction and the amount of blur is defined by the column movement. OTOH the Motion Blur Iwa will filter the image by using trajectory of the column.
> 
> Both fxs have a common point - they create some filter and apply it uniformly to whole pixels in the source image. It works based on an assumption that all pixels move the same speed and direction.
> 
> If the fxs need to take into account other movements like rotation and scale, the above method will not work since the movement of the pixels may vary according to the locations.

Is there any chance Motion Blur will be able to take the other movements into account in the near future?

**Comment by opentoonzuser111** [comment]
> 
> 
> A random thought related to @shun-iwasawa 's feedback...
> 
> In some cases of rotation perhaps using a Spin Blur would be more ideal that Motion Blur?
> Use of Direction Blur might be more appropriate in cases of Scale and Skew?
> 
> I was responding to someone else about something similar a year or so ago and we produced some pretty nice results. Unfortunately, I cannot find that discussion. I believe it was with @snapai perhaps via discord.

I have thought about using a Spin Blur, but I was just wondering specifically about using the Motion Blur in a more universal way. I will wait until the Motion Blur effect takes the other movements into account.
