### ISSUE TITLE
OpenToonz_1.0.exe has stopped working (Windows 7)

### ISSUE THREAD

**Issue by Bigmacjoe** [opentoonz/opentoonz#321]
Hello, I have this problem: I downloaded the latest release (1.0.2) installed it and when I tried to run it I could see the green starting screen, then it crashed. the name of the problem is APPCRASH, it also says that the name of the module with errors is: MSVCR120.dll 

 I had the 1.0.1 version before, I uninstalled it and deleted the folders containing Toonz stuff. I don't have multiple monitors nor drives.

 My system is Windows enterprise 7 64 bits

 Thanks for your time.

**Comment by kogaki** [comment]
Does v1.0.1 still works fine in your environment ?

**Comment by Bigmacjoe** [comment]
neither of them work, thought the last release might solve the problem, but no such luck.

**Comment by kogaki** [comment]
You mean v1.0.1 had never worked? Or stop working after you tried v1.0.2?

And... <https://groups.google.com/forum/#!searchin/opentoonz_en/APPCRASH/opentoonz_en/1sDCtY04SlQ/ri82EVTcDwAJ> This topic might help you. 
We haven't find exact cause, but with some DLLs installed OpenToonz doesn't work.

**Comment by Bigmacjoe** [comment]
1.0.1 had never worked too. I've tried to remove dll, will try to update it now, thanks.
