### ISSUE TITLE
Importing a Lip Sync file doesn't start or end with the correct 'rest' drawing

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#3218]
This is a small issue and one that I can work around. However, it should be an easily fixed issue.

Importing a lip sync file using the menu item: Xsheet > Apply lip sync data to column, correctly uses the 10 drawings I've selected in the dialog, but if my lip sync info doesn't start on frame 1, it adds drawing #9 in those frames. It should add drawing #10, the rest frame. Likewise, at the end of the animation, it adds a single frame of drawing #9 or if you tick the box at the bottom of the dialog (Extend rest drawing to end marker), it extends drawing #9 to the end, when it should use drawing #10.

Here's the dialog showing that drawing 10 is the rest drawing:

![LipSyncModal](https://user-images.githubusercontent.com/28575907/78704525-e0b45980-7903-11ea-906c-7fc802ac38c3.png)

### System Information
I'm on Windows using version 1.4

**Comment by DarrenTAnims** [comment]
Just an update. I've just imported a different file and this time it correctly set drawing 10 at the beginning, but only added 1 drawing 10 at the end instead of extending it as the tickbox requested. Because of the different versions of Papagayo, I suspect the files exported from it might be creating different data files. For today's test I was using Papagayo 2.0 beta. Previously I was using either 1.2 or the Morevna version.

**Comment by turtletooth** [comment]
Hey @DarrenTAnims could you share a lip sync file that isn't working the right way?

**Comment by DarrenTAnims** [comment]
Hi.
So I believe the problem I had was because of the version of Papagayo I was using. After posting this report I downloaded V2.0 and used that and this worked apart from it didn't extend the rest frame 10 to the end.

I'll attach 3 files, 1 each from Version 1.1, from version 2.0 and from Morevna's NG. Note, I had to rename them .txt files to upload them here

Hope they help.
Darren

[TestDataFromNG.txt](https://github.com/opentoonz/opentoonz/files/4505483/TestDataFromNG.txt)
[TestDataFromV1.1.txt](https://github.com/opentoonz/opentoonz/files/4505484/TestDataFromV1.1.txt)
[TestDataFromV2.txt](https://github.com/opentoonz/opentoonz/files/4505485/TestDataFromV2.txt)
