### ISSUE TITLE
On macOS, OpenToonz Asks to Access Documents and Desktop

### ISSUE THREAD

**Issue by MrBlockCat** [opentoonz/opentoonz#3224]
### Issue Summary
When opening OpenToonz on a Mac (possibly only with macOS Catalina), it asks to have access to Documents and the Desktop. This also happens sometimes when adding files to the Desktop or Documents when OpenToonz is open.

### Screenshot or Video Reference
I would provide a screenshot, but my MacBook just temporarily broke! Here's the same notification for a different app, though (photo from How-To Geek):
![image](https://user-images.githubusercontent.com/37186692/78960588-890d1e00-7abc-11ea-9c6f-fa05287867f5.png)

### Steps to Reproduce
Open OpenToonz in macOS Catalina, or (less reliably) leave it open and add files to the desktop and documents folders

### Expected Results
No messages asking to access Desktop and Documents unless OpenToonz should be accessing those places

### Actual Results
OpenToonz tries to access the Desktop and Documents on opening, and sometimes when the contents of the folders change

### System Information
* **OpenToonz Version**: Nightly and manual builds
* **Operating System**: macOS Catalina 10.15.4
* **CPU**: Quad core i5
* **Memory**: 8 GB LPDDR3

**Comment by artisteacher** [comment]
This isn't specific to OpenToonz. Any newly installed apps on macOS as of Catalina have to be granted access to any directories they use. I don't think we can change change this behavior on the OpenToonz side. 

It's certainly annoying when building yourself or when testing out the nightly builds. Anyone that doesn't update OT regularly, probably won't be bothered.

**Comment by MrBlockCat** [comment]
If it happened once per version, that’d be fine... The thing is, this also happens more once it’s open and I add files in the desktop/documents folder! For instance, I’ve left OpenToonz open, taken a screenshot (it defaults to saving to the Desktop), and had OpenToonz ask me again if it can access the Desktop and Documents. I’m not sure why it has to repeat asking

**Comment by artisteacher** [comment]
You might want to check your privacy settings. In Preferences -> Security & Privacy -> Privacy -> Files and Folders, make sure the Desktop & Documents folders are checked.
<img width="408" alt="Screen Shot 2020-04-10 at 12 32 51 PM" src="https://user-images.githubusercontent.com/21159116/79006571-6d8b2d00-7b27-11ea-9a6f-8764169ede0a.png">

**Comment by MrBlockCat** [comment]
I’ll try that once my Mac is back up and running! It’s strange if that notification only gives OpenToonz permissions for a few minutes, rather than permanently (for that OT version), though

**Comment by RodneyBaker** [comment]
Closing as we are pretty sure this is a Mac issue as described by @artisteacher 
Will reopen if there is something specific to Opentoonz that triggers the process.
