### ISSUE TITLE
Window layout

### ISSUE THREAD

**Issue by Reese4817** [opentoonz/opentoonz#3229]
### Issue Summary

window menus are out of size and I am unable to move them. The widows will not allow me to resize them and seem to become frozen instantly when this occurs. 
### Steps to Reproduce

create a new room=> create personal room => set up windows to your liking=> then windows become extremely large off screen=> then freeze.

### Expected Results

I would like the windows to stay the size i set them too. 

### Actual Results

nothing=> after this occures only the viewer works.
### System Information 64 bit operating system x64 processor
* **OpenToonz Version**: 1.4
* **Operating System**: windows 10
* **CPU**: 2.10 2.30
* **Memory**: 4 gb
* **Graphics Card**:  
* **Graphics Tablet**:

**Comment by artisteacher** [comment]
This sounds like it might be related to #2840, #2965, #3078, #3039, #3113, and #3167. A lot of windows 10 users have had scaling issues that were resolved after updating drivers.

**Comment by RodneyBaker** [comment]
@Reese4817 
Closing this report as a duplicate but please see the links @artisteacher has provided.
There is also a notice and link via the main Opentoonz download page in small print at the bottom.
The link there goes to:  https://www.intel.com/content/www/us/en/support/detect.html
