### ISSUE TITLE
Opentoonz crash, fault module: toonzlib.dll

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#323]
Hi, I've been having some issues after working a while with OPT on Windows . After doing some drawings with a raster brush, moving, rotating the view, zooming in etc, the software suddenly crashes. So I started looking for  similar cases at the english user forum. When someone had a problem with a .dll they just delete it, but in my case, the fault module name is: toonzlib.dll which it seems to be a crucial file , so If I remove it OPT won't work. What should I do? 

Thanks in advance and for all the hard work you've been doing.

Details:

Problem Event Name: APPCRASH
Application Name: OpenToonz_1.0.exe
Application Version: 0.0.0.0
Application Timestamp: 572097a0
Fault Module Name: toonzlib.dll
Fault Module Version: 0.0.0.0
Fault Module Timestamp: 57209676
Exception Code: c0000005
Exception Offset: 000000000012ff53
OS Version: 6.3.9600.2.0.0.256.48
Locale ID: 1033
Additional Information 1: 5d31
Additional Information 2: 5d31d5920e4f1ca59debb85d57195124
Additional Information 3: b0bd
Additional Information 4: b0bda9ef073d9c97b12ea7116fed1bc5

**Comment by turtletooth** [comment]
Can you duplicate the issue?  What specifically seems to cause it?

**Comment by NestorAntonio** [comment]
The problem occurs after I draw a while with a raster brush, like ten minutes after.  I've tried so many times with different versions of OPT but the crash persist. Some people say that the raster level is a bit unnstable by the moment.  

These are the details that appeared on the screen after the crash, the issue seems to be on the file toonzlib.dll:

Problem Event Name: APPCRASH
Application Name: OpenToonz_1.0.exe
Application Version: 0.0.0.0
Application Timestamp: 572097a0
Fault Module Name: toonzlib.dll
Fault Module Version: 0.0.0.0
Fault Module Timestamp: 57209676
Exception Code: c0000005
Exception Offset: 000000000012ff53
OS Version: 6.3.9600.2.0.0.256.48
Locale ID: 1033
Additional Information 1: 5d31
Additional Information 2: 5d31d5920e4f1ca59debb85d57195124
Additional Information 3: b0bd
Additional Information 4: b0bda9ef073d9c97b12ea7116fed1bc5

Thanks in advance.

**Comment by turtletooth** [comment]
If you can give us steps to consistently duplicate this issue, we can reopen this and try and solve it.
