### ISSUE TITLE
Key shortcut to Zoom In does not work

### ISSUE THREAD

**Issue by ErwinBr** [opentoonz/opentoonz#3235]
### Issue Summary
No matter what key I map, Zoom In does not work. (Nor the default setting of +). Zoom in does work the alternative methods such as the scroll wheel or the button. Also interesting: Zoom Out (- key) does work without problems.

### Screenshot or Video Reference
N/A

### Steps to Reproduce
Press the key to zoom. Nothing happens.

### Expected Results
Zoom in.

### Actual Results
Nothing.

### System Information
* **OpenToonz Version**: 1.4 (Build Feb 2 2020)
* **Operating System**: Mac OS - Catalina 10.15.2
* **CPU**: 2x 2.8 GHz Quad-Core Intel Xeon
* **Memory**: 8GB 800MHz DDR2
* **Graphics Card**: Nvidia GeForce GTX 680 2GB
* **Graphics Tablet**: N/A

**Comment by artisteacher** [comment]
Do you have a laptop? This is a known issue - #1327. The default zoom in shortcut (+) is not possible on consolidated laptop keyboards, since there is no dedicated + key  (there's =/+, which doesn't function exactly the same). Zoom in should work if you change the shortcut to cmd+=, which is the system wide zoom in shortcut on a Mac laptop.

**Comment by ErwinBr** [comment]
> Do you have a laptop? This is a known issue - #1327. The default zoom in shortcut (+) is not possible on consolidated laptop keyboards, since there is no dedicated + key (there's =/+, which doesn't function exactly the same). Zoom in should work if you change the shortcut to cmd+=, which is the system wide zoom in shortcut on a Mac laptop.

I’m on a Mac Pro desktop and my connected usb keyboard does have a dedicated + sign. Also, it doesn’t work if I assign another key, for example z.

**Comment by artisteacher** [comment]
Interesting. I don't have any problem setting a shortcut with any of the macs I've had access to. You might want to try a clean install with one of the nightly builds & see if that makes any difference. I'd rename the stuff folder before reinstalling.

**Comment by ErwinBr** [comment]
As I started to get more serious issues, crashes that even rebooted my machine, I decided to reinstall and all my problems are gone. I can now assign any key to zoom. I'm guessing my installation was corrupt. Closing this ticket.
