### ISSUE TITLE
(Proposal) Stop Motion Room

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#3245]
The stop motion features in OT are pretty robust now.  Can we have a room for it to make it easy to discover and without some of the clutter that isn't needed?

![smroom](https://user-images.githubusercontent.com/4576381/79708355-704ef600-827c-11ea-9316-d26d88258b9c.PNG)

**Comment by gab3d** [comment]
I say yes!

**Comment by DarrenTAnims** [comment]
Of course we should. But this goes along with the whole rooms redesign.
