### ISSUE TITLE
UI Enchancement - ability to mark keyframes and breakdowns In the XSheet and Level Strip

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#325]
I would be useful to be able to mark which frames were the keyframes and breakdowns for both scanned and digital frame by frame animation. 

![key break](https://cloud.githubusercontent.com/assets/18170954/15361249/01b766b6-1d11-11e6-9317-686d1448268b.png)

**Comment by blurymind** [comment]
That is actually a pretty good idea. Both tvpaint and toonboom have that

**Comment by NestorAntonio** [comment]
Great idea BrundleThwaite!  would be good if besides marking the keyframes and breakdowns, you also could reproduce one of those.

**Comment by Rayek** [comment]
Agreed, that would be extremely helpful when doing traditional animation. I would love such an addition.

**Comment by BrundleThwaite** [comment]
A more elegant approach might just be as colours like this.

![keyfreameb](https://cloud.githubusercontent.com/assets/18170954/15385993/88e76eee-1da5-11e6-8414-f131d2230f79.png)

**Comment by blurymind** [comment]
interesting ideas. Anything to bring it closer to the traditional x-sheet will be appreciated by classic animators for sure :) 

They tend to scribble that information on the pencil test itself - inside the drawing area.

**Comment by blurymind** [comment]
perhaps we could use the memos system to do that by making an empty memo with one of the preferred colors at the frame. That way color coded memos can be used to mark breakdowns, etc - and we will also be able to attach information to frames, which was requested as well:
https://github.com/opentoonz/opentoonz/issues/368

**Comment by BrundleThwaite** [comment]
I have been using memos but they are time consuming and the do not work if you re-time the animation as they are not linked to the frames.

**Comment by 2dvision** [comment]
Transfer of [here](https://github.com/opentoonz/opentoonz/issues/367).

I tried to show in the image. For example, by clicking on (K) the sidebar cells border will be converted to the specified color. In traditional animation is very efficient.

Red K = Keyframe
Blue B = Breakdown
Green I = In-between

In-between color is the default cells border opentoonz.

![opentoonz-new-button-xsheet2](https://cloud.githubusercontent.com/assets/16509592/15636451/7a4c4432-2614-11e6-9abb-301a46e31e4f.jpg)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
