### ISSUE TITLE
What is this int used for in the TPL file?

### ISSUE THREAD

**Issue by KaseyFarron** [opentoonz/opentoonz#3250]
If you open a TPL file in a text editor, you'll see this block per style:

![image](https://user-images.githubusercontent.com/55353161/80061909-59cdc680-852a-11ea-8eec-60918958cf31.png)

What is the int '3' used for that I highlighted?

| autopaint | name | `???` | r | g | b | a |
| - | - | - | - | - | - | - |
| _1 | color_0 | `3` | 0-255 | 0-255 | 0-255 | 0-255 |

**Comment by shun-iwasawa** [comment]
It's a style's tagId indicating the type of the style.
TagID = 3 means `TSolidColorStyle` , which is basic solid color.

| TagID | Class                                     | Description              | Source               |
|-------|-------------------------------------------|--------------------------|----------------------|
| 2     | TCenterLineStrokeStyle                    |                          | tsimplecolorstyles.h |
| 3     | TSolidColorStyle                          |                          | tsimplecolorstyles.h |
| 4     | TTextureStyle                             |                          | imagestyles.h        |
| 99    | OutlineViewerStyle                        | OutlineViewer(OnlyDebug) | strokestyles.h       |
| 100   | Obsolete - TRasterImagePatternStrokeStyle |                          | tsimplecolorstyles.h |
| 102   | Obsolete - TFriezeStrokeStyle2            |                          | strokestyles.h       |
| 103   | TFurStrokeStyle                           | Herringbone              | strokestyles.h       |
| 104   | TChainStrokeStyle                         | Chain                    | strokestyles.h       |
| 105   | Obsolete - TChalkStrokeStyle2             |                          | strokestyles.h       |
| 106   | TSprayStrokeStyle                         | Circlets                 | strokestyles.h       |
| 107   | TGraphicPenStrokeStyle                    | Dashes                   | strokestyles.h       |
| 108   | TRopeStrokeStyle                          | Rope                     | strokestyles.h       |
| 109   | TCrystallizeStrokeStyle                   | Tulle                    | strokestyles.h       |
| 110   | Obsolete - TBlendStrokeStyle2             |                          | strokestyles.h       |
| 111   | TDottedLineStrokeStyle                    | Vanishing                | strokestyles.h       |
| 112   | Obsolete - TBraidStrokeStyle              |                          | strokestyles.h       |
| 113   | TSketchStrokeStyle                        | Fuzz                     | strokestyles.h       |
| 114   | TBubbleStrokeStyle                        | Bubbles                  | strokestyles.h       |
| 115   | Obsolete - TBiColorStrokeStyle            |                          | strokestyles.h       |
| 115   | TZigzagStrokeStyle                        |                          | zigzagstyles.h       |
| 116   | TImageBasedZigzagStrokeStyle              |                          | zigzagstyles.h       |
| 117   | TTissueStrokeStyle                        | Gauze                    | strokestyles.h       |
| 118   | Obsolete - TMultiLineStrokeStyle2         |                          | strokestyles.h       |
| 119   | Obsolete - TBiColorStrokeStyle            |                          | strokestyles.h       |
| 120   | TNormal2StrokeStyle                       | Bump                     | strokestyles.h       |
| 121   | Obsolete - TNormal2StrokeStyle            |                          | strokestyles.h       |
| 123   | TChalkStrokeStyle2                        | Chalk                    | strokestyles.h       |
| 125   | TBlendStrokeStyle2                        | Fade                     | strokestyles.h       |
| 126   | TTwirlStrokeStyle                         | Ribbon                   | strokestyles.h       |
| 127   | TSawToothStrokeStyle                      | Jagged                   | strokestyles.h       |
| 128   | Obsolete - TMultiLineStrokeStyle2         |                          | strokestyles.h       |
| 129   | TZigzagStrokeStyle                        | Zigzag                   | strokestyles.h       |
| 130   | TSinStrokeStyle                           | Wave                     | strokestyles.h       |
| 132   | TDualColorStrokeStyle2                    | Striped                  | strokestyles.h       |
| 133   | TFriezeStrokeStyle2                       | Curl                     | strokestyles.h       |
| 134   | TLongBlendStrokeStyle2                    | Watercolor               | strokestyles.h       |
| 135   | TBiColorStrokeStyle                       | Shade                    | strokestyles.h       |
| 136   | TBraidStrokeStyle                         | Plait                    | strokestyles.h       |
| 137   | Obsolete - TBubbleStrokeStyle             |                          | strokestyles.h       |
| 138   | TMultiLineStrokeStyle2                    | Gouache                  | strokestyles.h       |
| 141   | TMatrioskaStrokeStyle                     | Toothpaste               | strokestyles.h       |
| 1125  | MovingSolidColor                          | Offset                   | regionstyles.h       |
| 1127  | ShadowStyle                               | Hatched Shading          | regionstyles.h       |
| 1128  | TRubberFillStyle                          | Blob                     | regionstyles.h       |
| 1129  | TPointShadowFillStyle                     | Sponge Shading           | regionstyles.h       |
| 1130  | TDottedFillStyle                          | Polka Dots               | regionstyles.h       |
| 1131  | TCheckedFillStyle                         | Square                   | regionstyles.h       |
| 1132  | ArtisticSolidColor                        | Irregular                | regionstyles.h       |
| 1133  | Obsolete - TChalkFillStyle                |                          | regionstyles.h       |
| 1135  | ShadowStyle2                              | Plain Shadow             | regionstyles.h       |
| 1136  | TChessFillStyle                           | Chessboard               | regionstyles.h       |
| 1137  | TStripeFillStyle                          | Banded                   | regionstyles.h       |
| 1138  | TLinGradFillStyle                         | Linear Gradient          | regionstyles.h       |
| 1139  | TRadGradFillStyle                         | Radial Gradient          | regionstyles.h       |
| 1140  | TCircleStripeFillStyle                    | Concentric               | regionstyles.h       |
| 1141  | TMosaicFillStyle                          | Stained Glass            | regionstyles.h       |
| 1142  | TPatchFillStyle                           | Beehive                  | regionstyles.h       |
| 1143  | TChalkFillStyle                           | Chalk                    | regionstyles.h       |
| 1150  | TAirbrushRasterStyle                      | Airbrush                 | rasterstyles.h       |
| 1151  | TNoColorRasterStyle                       | Markup                   | rasterstyles.h       |
| 1160  | TBlendRasterStyle                         | Blend                    | rasterstyles.h       |
| 2000  | TRasterImagePatternStrokeStyle            |                          | tsimplecolorstyles.h |
| 2001  | TColorCleanupStyle                        |                          | cleanupcolorstyles.h |
| 2002  | TBlackCleanupStyle                        |                          | cleanupcolorstyles.h |
| 2800  | TVectorImagePatternStrokeStyle            |                          | tsimplecolorstyles.h |
| 3000  | TVectorBrushStyle                         |                          | tvectorbrushstyle.h  |
| 4001  | TMyPaintBrushStyle                        |                          | mypaintbrushstyle.h  |

**Comment by KaseyFarron** [comment]
Thank you!
