### ISSUE TITLE
Invalid value for Color Calibration path preference causes crash on startup

### ISSUE THREAD

**Issue by martinvanzijl** [opentoonz/opentoonz#3258]
**Describe the bug**
I entered an invalid value (added some spaces, I think) to the "Color Calibration 3DLUT file path" in the Preferences window, then closed OpenToonz. The next time I tried to start OpenToonz, it crashed with a segfault message during the splash screen.

I found this quite by accident while testing something else related to preferences.

**To Reproduce**

**WARNING: Please do not try this unless you know how to edit the preferences file manually!**

1. Choose _File --> Preferences_.
2. Go to the _Interface_ page.
3. Check the box for "Color Calibration using 3D Look-up Table".
4. Type an invalid value into the textbox (e.g. "Hello").
5. Close the window.
6. Close OpenToonz.
7. Try to restart OpenToonz. This crashes during the splash screen due to a segfault error.

The only way to fix this is to manually edit the settings file and remove the entry for "colorCalibrationLutPaths". Then restart OpenToonz and it runs correctly.

**Expected behavior**
Invalid value for the path should not cause a crash on startup.

**Screenshots**
1. Setting the preference:

![preference-bug-01](https://user-images.githubusercontent.com/24422213/80421892-4a3aed00-8931-11ea-8d9d-342e9d034128.png)

2. Crash upon closing and restarting:

![preference-bug-02](https://user-images.githubusercontent.com/24422213/80421918-56bf4580-8931-11ea-8808-b682c5435c98.png)

3. Have to delete line from preferences file:

![preference-bug-03](https://user-images.githubusercontent.com/24422213/80421932-5e7eea00-8931-11ea-90b6-17d989c205af.png)

Full video below (zipped OGV):

[preference-bug-demo.zip](https://github.com/opentoonz/opentoonz/files/4542165/preference-bug-demo.zip)

**Device Information:**
 - OS: Ubuntu 18.04 (64-bit)
 - OpenToonz Version: Git 90814c256edff7e11ced473770672520619c1014 (24 April 2020)
 - GPU: Intel® Sandybridge Mobile
 - GPU Driver Version: 3.0 Mesa 19.2.8 (?)

**Comment by martinvanzijl** [comment]
**Useful debugging info**

I debugged it in GDB, and the problem occurs here:

https://github.com/opentoonz/opentoonz/blob/90814c256edff7e11ced473770672520619c1014/toonz/sources/toonzlib/preferences.cpp#L661

It seems to go through the loop twice, and crashes on the second time it executes this statement.

**Comment by RodneyBaker** [comment]
I believe this might be resolved
Testing...
