### ISSUE TITLE
toggle bottom commands in top area 

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3260]
<img width="343" alt="Annotation 2020-04-29 000750" src="https://user-images.githubusercontent.com/29790512/80549805-7cdef700-89be-11ea-9b3d-0b64a3a89e95.png">
Is it possible to have an option similar to toggle Xsheet toolbar to hide / show the commands from the bottom since the introduction of the following #3233 PR. This is useful when you do not want to use shortcuts for flips in particular.

it's also more natural to use your hands up than down when working with a tablet on your knees for example.

**Comment by DarrenTAnims** [comment]
It would make sense for them to be at the top being as the other buttons at the top also affect the look of the viewer.

**Comment by RodneyBaker** [comment]
Closing this report as the originator has ghosted themselves.
There may be useful information contained in this report and that information should be transferred to a new report where appropriate.
