### ISSUE TITLE
Reversing the guidance direction creates double lines.

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3267]
**Describe the bug**

Not really sure it's related to that but when I try to create a tweening based on the following drawing with guided drawing feature (GDF), double lines are created when the onion skin is still active.

This seems also impacts the guidance in "conventional" mode after that.

**To Reproduce**

1.With GDF enabled , create 2 blank vector frames
2.Draw something in the second frame
3.Enable onion skin to follow the strokes
4.Draw something in the first frame with brush or geometry tools.
5.Modify the shape stroke with control point editor

**Expected behavior**
No double lines

**Screenshots**
![guided drawing double lines](https://user-images.githubusercontent.com/29790512/80813165-cc454300-8bc9-11ea-863c-7e92e6130d90.gif)

**Device Information:**
 - OS: [e.g. Windows 10]
 - OpenToonz Version: [e.g. Nightly (Apr 25 2020 10.16.40)]

**Comment by openanim** [comment]
It seems that the bug is related to the auto-inbetween function introduced in the new tweening features. At least when it is checked the bug appears and once deactivated, it almost seems to work. There remains, however, one additional stroke without correct correspondence.

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
