### ISSUE TITLE
Creating animation characters with real images

### ISSUE THREAD

**Issue by creationskh** [opentoonz/opentoonz#3269]
Hi,

I am trying to create an animation scene with characters that are real people. could our experienced Toonz members let me know a best approach to create this with the images that i have. (atleast just the face)

Thanks in advance :)

**Comment by RodneyBaker** [comment]
As you've already opened the same question in the Opentoonz forum will close this.
Those interested in providing feedback please see:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/opentoonz_en/fX0zpRMwkIQ/tqozCiHtAQAJ
