### ISSUE TITLE
Enhancement - Add DCI_2K and Add DCI_4K to camera resolution presets

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#327]
DCI_2K - 2048 - 1080 1:90:1
DCI_2K - 4086 - 2160 1:90:1

These formats should be added to the standard video presets. They are the standard for digital film cameras and DCI_2K is the minimum resolution for digital film in the admission requirements of the  Academy of Motion Picture Arts and Sciences.

http://www.oscars.org/sites/oscars/files/89aa_rule19_short_guidelines.pdf

**Comment by turtletooth** [comment]
I'll do it.
Give me a day or two.

**Comment by BrundleThwaite** [comment]
Thanks I appreciate it. Some day I will have to set up visual studio again and do these things myself. :)

**Comment by turtletooth** [comment]
Pull request submitted.

**Comment by kogaki** [comment]
Fixed by @turtletooth. Thanks.

**Comment by BrundleThwaite** [comment]
Thanks
