### ISSUE TITLE
Snap low works only on direct contact of the stroke

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3271]
**Is your feature request related to a problem? Please describe**

This request is related to certain problems encountered with the snap tool in general (brush tool, geometric tools, control point editor). This concerns the level of snap "low".

- Sometimes, the snap cannot really "snap" the other stroke although the snap is established.

- In the case of the brush and the geometric tools and although I am in low sensitivity, the snap is still much too high from my point of view.

- The beginning and especially the end of the strokes have an unwanted and uncontrolled trajectory.

- Which makes it difficult to use fluidly.

Even if you can temporarily deactivate it with the alt key in the case of the brush, the workflow is reduced.

Because it very often snap on the nearest lines even if there is a space between them. Which requires us to be constantly using alt or simply deactivating the snap.

**Describe the solution you'd like**

If possible, it would be great to have a 4th level of snap, failing to modify the current behavior of "snap low".

This new snap would only activate on direct contact with another line. Snap established at the last moment before touching the other stroke and not along the way as it is currently the case and which gives unexpected trajectories.

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
