### ISSUE TITLE
DLSR Canon 5D mark iii not recognized

### ISSUE THREAD

**Issue by benoitlemay** [opentoonz/opentoonz#3273]
Fresh install of OpenToonz, latest version (1.4 Build Fev 2020) My Canon DSLR are not recognized.. Do i need to install additionnal plugins/driver?..  Other app (AnimaShooter) are seeing the camera.. 
Thanks!

**Comment by turtletooth** [comment]
Can you try this build:
https://github.com/turtletooth/opentoonz/releases/tag/1.4b

**Comment by benoitlemay** [comment]
My bad.. i didn't see the Stop Motion Controller window!!.. ..

**Comment by turtletooth** [comment]
You may still want to try the build I posted above.  It has a much improved tool set for stop motion.

**Comment by evgenigit** [comment]
opentoonz. on mac os can't see canon 650d camera

**Comment by evgenigit** [comment]
I read your comment on the compilation that you posted above. downloaded it. I don’t know what to do with it

**Comment by benoitlemay** [comment]
Thanks Turtletooh!. now it's working fine, and i see the live preview image with onion skin..
