### ISSUE TITLE
Dropdown-menu of toolbar appears in different desktop

### ISSUE THREAD

**Issue by kogaki** [opentoonz/opentoonz#328]
![untitled35 0001](https://cloud.githubusercontent.com/assets/17926501/15380689/8b386096-1db3-11e6-9f13-1bcf5d73057f.png)
## How to reproduce
1. Start OpenToonz on Desktop 1
2. Move OpenToonz into Desktop 2
3. Click "show more" on toolbar
## Environment

OSX
nightly-May-19

**Comment by artisteacher** [comment]
I'm not seeing this in the RC with 10.11.6.

**Comment by RodneyBaker** [comment]
@kogaki Are you still experiencing this issue?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
Pending confirmation by @kogaki or other Mac user although note @artisteacher reported this likely resolved in June 2018.
