### ISSUE TITLE
Reset to default rooms

### ISSUE THREAD

**Issue by Tartarin8** [opentoonz/opentoonz#3281]
Windows/Workspace/Reset to default rooms doesn't seem to do anything. It does one thing, however: it corrupts the room list. After that, it becomes impossible to delete a room (critical error). Tested on lastest nightly too.

 - OS: Windows 8.1
 - OpenToonz Version: 1.4 Nightly 05-13-2020

**Comment by manongjohn** [comment]
When you Reset to Default Rooms, you need to close and restart OT to take effect.

**Comment by Tartarin8** [comment]
That's correct, thanks. I hadn't found the info anywhere.

**Comment by manongjohn** [comment]
If would be nice if a popup would warn users that is necessary to restart OT to complete the process and either `Continue` to reset and shut down automatically or `Cancel` to not do anything

**Comment by gab3d** [comment]
...I'd substitute the Cancel button for a Restart Later one, though.
