### ISSUE TITLE
Auto smooth arc tool 

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3282]
I wonder if the arc tool could have certain attributes of the tape tool in order to simulate a continuous curve tool.

In particular endpoint to endpoint, join strokes and smooth.

When joining 2 strokes with the tape tool with its attributes, a smooth curve is created.

If the arc tool could do this continuously with each addition of a new stroke to obtain an "auto smooth line" effect, we could maybe simulate a polyline curve tool, currently absent in OT.

Currently with the polyline tool we needs to create the curves manually. So similarly, perhaps a definable smooth value between two segments for the polyline tool could allow that.

Which would help with the lineart, the filling etc.

![auto smooth arc tool](https://user-images.githubusercontent.com/29790512/81850195-f26acb80-9557-11ea-8655-2c88a2396e5e.gif)

**Comment by pojienie** [comment]
Is this what you want? https://youtu.be/ekCwA1bbvP4

basically I add 1 shape in geometric tool: MultiArc. It allows you to immediately start another arc shape after one is completed. The start point of the new arc is the end point of the previous arc.

Currently there is a huge bug when you only enable "join vector" and not "smooth". But I want to know if this is how you want it to work first.

**Comment by openanim** [comment]
@pojienie Thank you so much, to tackle the implementation, that's exactly that !

Ideally, I wanted to do something like this. 

![Curve tool cacani](https://user-images.githubusercontent.com/29790512/85221826-584c3d80-b3b7-11ea-8eba-4ef9814544e4.gif)

Its more as a "polyline with curve" But I think your version fits perfectly with the tools present in OT and I am very grateful to you. Possible to be able to test it ?

**Comment by pojienie** [comment]
wow, how does the software you're using know how "curvy" the lines should be?

I have submitted PR #3360 and it should have apveyor image after awhile.

(btw the artwork is from Regular Show and not by me, I just used it as an example that this feature is useful for drawing her kind of hair)

**Comment by openanim** [comment]
Yes cacani has some good tools ... :) Thanks for this, exciting !

**Comment by beeheemooth** [comment]
This is a great feature, but it doesn't seem to work properly with Vector Guided Drawing in the case meant that the line created with the help of MultiArc be whole (Join Vector).
![ezgif-4-5119d2389ebb](https://user-images.githubusercontent.com/25724133/85232765-3f20ac80-b40a-11ea-9c17-83cdf7337402.gif)
I also caught a crash when canceling incomplete actions when the Join Vectors option is enabled
![ezgif-4-a2810b979277](https://user-images.githubusercontent.com/25724133/85233091-9de72580-b40c-11ea-8f34-b4dd46bc17ad.gif)

**Comment by pojienie** [comment]
Haven't tested Vector Guided Drawing yet as there were more problematic issues.

And I completely didn't think about using undo while using a tool... I'll add it to known bugs. Thanks!

**Comment by adamearle** [comment]
this is great but you know improving the workflow of keyframes is the one thing that holds OT back. Should i make Video about it?

**Comment by RodneyBaker** [comment]
@openanim Does the Multiarc option in #3360 fulfill this request?

**Comment by openanim** [comment]
@RodneyBaker yes of course !

**Comment by williebluebussell** [comment]
Hi Good Day, 

Are you also interested to collaborate on KRITA for the same tool... we need that curve tool badly our side... i hope you can for this plea of help im asking... 
They have the same files tools in CLIP STUDIO 
they use SUT... maybe you can decode from there also so the tool wont hang in opentoonz
heres the link to the video:
https://www.youtube.com/watch?v=RbGgaqrYvow
heres the link to the tools:
https://onedrive.live.com/?authkey=%21AJzirUUkdEX2VdI&id=ADEF7C332FA8981%21178064&cid=0ADEF7C332FA8981
its free open authorship so no copyright issues...
please let me know 👍 
im teaching poor students on scholarship for animation and they cant afford CLIP STUDIO or RETAS...
Please Kindly help... thanks
williebluebussell@yahoo.com
williebluebussell@facebook.com
Thanks so much guys and be safe from the virus including families...
