### ISSUE TITLE
Rasters levels with differents canvas size make the brush inactive

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3283]
**Describe the bug**

When working with different raster levels of different sizes, the brush only appears active on a portion of the canvas that represents the size of the smallest level.

Some situations:

1. When creating/ modifying different rasters levels of different sizes.

- either by the command "New raster level" in the size properties

- or by the command Level > Canvas size.

The brush is active only on a part of the canvas of the new size and remains inactive for the rest as long as we don't use another tool in the meantime so that the bug stops (example selection tool). But as soon as we change levels, the bug returns.

2. When importing / loading a raster level or external raster with a different size from that present.

**To Reproduce**

List steps to reproduce the behavior.

1.Create 2 rasters levels with differents size
2. Draw something on the levels
3. The brush is active only on part of the canvas

**Expected behavior**

Brush active on the whole canvas with brush tool.

**Device Information:**

 - Windows 10

**Comment by RodneyBaker** [comment]
Just to be sure...
You aren't using the column masking that @turtletooth has been working on are you?

**Comment by openanim** [comment]
@RodneyBaker no, I have always experienced this problem, even in older versions of OT.

**Comment by WolfInABowl** [comment]
I can reproduce this

OS: Win 10
OT Ver: May 12th Nightly

**Comment by RodneyBaker** [comment]
In my brief test of this, creating two raster levels of different resolution and then attempting to draw on the small one first and large one second, I get a crash.
