### ISSUE TITLE
Default Layout

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#329]
Is there any interest in creating a default layout for people just getting started with OpenToonz?  I teach animation in school and would love to use OpenToonz, but the default rooms are not the easiest for a beginner.

I was thinking something like this.  It has most of the components users would need to get started and play their animations back.

![default_layout](https://cloud.githubusercontent.com/assets/4576381/15381193/a444f6f4-1d3a-11e6-850b-540e86037a90.png)

**Comment by papio-pl** [comment]
Good point. Open source software should encourage new users to use it, play with it, discover it etc. I learned from youtube tutorials how to set layout like you did here. But when I opened Opentoonz for the first time i was compeletly lost.

**Comment by blurymind** [comment]
I already made this same point and even shared layouts I made - based on toonz harlequin:

https://github.com/opentoonz/opentoonz/issues/80
They were not included in opentoonz

I also found a bug with the level strip width  when you start OT - that has not been fixed either. :)

**Comment by turtletooth** [comment]
I'm going to try and submit a pull request tonight. The current setup is great for a paper workflow, but is so confusing to people getting started and trying paperless.

**Comment by turtletooth** [comment]
I'm going to post this in two places to get some feedback: What do you think of a toggle in preferences that will let you choose between the Studio Ghibli rooms and the standard rooms?  That way the folks who brought this amazing product open source don't lose the layouts they are used to, but the folks who are new to OT have a better chance of catching on.  I think the default rooms should be the standard rooms, but I want to hear from other folks.  I will start looking in the code for the best place to add it.

**Comment by blurymind** [comment]
@turtletooth Toonz harlequin used the same menus in all rooms. I sat down and created a setup that can revert the room menus from harlequin, while also adding the new toonz ghibli added features:
[room1_menubar.zip](https://github.com/opentoonz/opentoonz/files/294019/room1_menubar.zip)

To revert the default toonz harlequin menu layout, just use this menubar for all the rooms. You are of course free to further edit it and remove some of the entries on some of the rooms. That is something I am doing myself on further edits.
