### ISSUE TITLE
My paint brushes acting strangely on Toonz raster Level

### ISSUE THREAD

**Issue by NobleFrugal** [opentoonz/opentoonz#3295]
**Describe the bug**
When using the "My paint brushes" on a Toonz Raster layer, there is strange interaction between brush strokes on the same layer. Some strokes act as if they are on a layer above when attempting to draw over them. It affects each of the brushes differently. (I am aware that this issue is due to the limitations of the Toonz Raster layer itself, but I thought it would be worth a mention anyway).

**To Reproduce**
1. Draw a stroke using a Mypaint brush on a toonz raster layer.
2. Pick another brush out of the mypaint menu and draw across your first stroke.
3. lo' and behold

**Expected behavior**
Usually, the previous stroke will cover the new one. Or, when the new stroke crosses over the previous one, it appears only to strip the previous stroke of its antialiasing without covering it fully. I'd recommend checking out the videos I left in the screenshots section to get a full understanding of what this looks like.

**Screenshots**
Here is a perfect example provided by one of my supporters: https://www.dropbox.com/s/2afn513haltx2g7/2020-05-09%2018-30-49.mp4?dl=0

Extra examples: 
https://www.dropbox.com/s/sasxrc1lpwbagy3/2020-05-09%2018-25-36.mp4?dl=0
https://www.dropbox.com/s/cye53nauokb21sh/2020-05-09%2018-32-39.mp4?dl=0
https://www.dropbox.com/s/4qrevdafi3noiz1/example4.mp4?dl=0

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.4
 - GPU: Amd Radeon Rx 560
 - GPU Driver Version: 19.20

**Comment by RodneyBaker** [comment]
Sebastian,
Have you made your supporters aware that MyPaint brushes have not been fully added to Toonz Raster levels?

Additional information on what was implemented and what doesn't work can be found via the PR that added the feature (PR #2257).

In the case of each specific mypaint brush the user may need to examine whether the brush being used has any settings that disqualify use on toonz raster.  Examples include any erasing and blending.  The brushes need to be additive and work as lines and not areas.d 

It would be nice if we could find a way to identify/separate brushes that cannot work on toonz raster from those that can.  Perhaps this could be part of the broader goal to add management/organization capability for mypaint brushes.

**Comment by NobleFrugal** [comment]
My apologies, I could not find anything discussing the my paint brushes that was recent so I assumed that it was uncharted territory. I will inform them that they have not been fully implemented. Thanks for letting me know.
