### ISSUE TITLE
installing nighly AND stable versions simultaneously?

### ISSUE THREAD

**Issue by Tartarin8** [opentoonz/opentoonz#3297]
Is there a way to have a nightly version and a stable version simultaneously on a Windows (8.1) system? To be able to help the debugging while working on projects on a stable version at the same time?
By the way, in a general manner, are the nightly less or more stable than the 1.4 release? I mean, I know the release is usually more stable, but since the release is recent maybe the nightlies already have bugs corrected.

**Comment by manongjohn** [comment]
This is what I do to keep full installations sharing same `C:\OpenToonz stuff` folder:

1. Install the official verision
2. Backup a clean `C:\OpenToonz stuff` just in case
3. Rename `C:\Program Files\OpenToonz` -> `C:\Program Files\OpenToonz (official)`
4. Either create new shortcuts or change any existing shortcuts created to point to the new folder name
5. Install the nightly version.  
   Allow the stuff folder to be overwritten with new changes. Personal preferences should keep.
6. Rename `C:\Program Files\OpenToonz` -> `C:\Program Files\OpenToonz (nightly)`
7. Either create new shortcuts or change any existing shortcuts created to point to the new folder name

Caveat: The stuff folder may contain changes from the nightly that may cause an issue in the official. Usually that doesn't happen but it can depending on what was fixed/introduced.


Alternatively you can convert them to local portables (likely a safer choice)
1. Install the official verision
2. Rename `C:\Program Files\OpenToonz` -> `C:\Program Files\OpenToonz (official)`
3. Either create new shortcuts or change any existing shortcuts created to point to the new folder name
4 Move and rename  `C:\OpenToonz stuff` -> C:\Program Files\OpenToonz (official)\portablestuff`
5. Install the nightly version.  
6. Rename `C:\Program Files\OpenToonz` -> `C:\Program Files\OpenToonz (nightly)`
7. Either create new shortcuts or change any existing shortcuts created to point to the new folder name
4 Move and rename  `C:\OpenToonz stuff` -> C:\Program Files\OpenToonz (nightly)\portablestuff`

I would suggest in either case to configure in both OT's the same Project Root folder someplace outside the stuff folder, like My Documents, this way you can access projects from any version of OT you use, even OTX and Morevna editions.
