### ISSUE TITLE
Opentoonz Preview show only white 

### ISSUE THREAD

**Issue by IOriginI** [opentoonz/opentoonz#3302]
I don't know how I got this bug but when I tried to view a preview of my animation it would just show white and I've looked around for solutions and they haven't worked for me.
**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by manongjohn** [comment]
Open up the Fx Schematic window (OpenToonz menu Windows -> Schematic, then click bottom right button).

Make sure all nodes lead to the same active Output node (blue). If not, right click the node and make it active.

**Comment by IOriginI** [comment]
It hasn't worked I've sent an image down below to show you if I've done it right.
![Opentoonz Problem](https://user-images.githubusercontent.com/65740024/82614839-b0c5ca80-9bc0-11ea-9b85-44f426ce37a7.jpg)

**Comment by manongjohn** [comment]
That's the Stage Schematic. Click on the bottom right button on that window to switch it to the FX Schematic.

**Comment by IOriginI** [comment]
Thank you my problem is now solved.
