### ISSUE TITLE
Center a peg along a motion path

### ISSUE THREAD

**Issue by Al532** [opentoonz/opentoonz#3310]
Is there a way to easily recenter/offset a group of layers to be inline with a motion path? It seem there's no direct way to do this. With a unique layer, it's easy to select the drawing with the selection tool to offset it ; however, if this layer has several level images to display, or if that layer is linked to one or more layers (by schematic link, by a peg or by a sub x-sheet), it becomes trickier to move the layer group at the same time.
I found a workaround that consists of having a two peg chaining, with the motion path linked to the parent one. Doing this way, I can freely move (animate/position) the child peg (Peg1 in my exemple) to recenter the group along with the motion path. However this is not very elegant, and doing so we don't see the path at the same time. (Note that the child peg could also be a sub x-sheet, or a direct chaining between several layers, it would work the same.)

Is there a more elegant way to do this?

If not, I would suggest the center (animate tool/center) of the element linked to the motion path would always be aligned with the motion path itself, by default. At the moment, moving the center point doesn't do anything.

![motion path peg](https://user-images.githubusercontent.com/50932820/82956571-5c03c480-9fb1-11ea-8e41-efe2d3ae9f92.png)

**Comment by RodneyBaker** [comment]
Recommend reviewing this report in light of (pending) v1.5 review and closing as appropriate.

**Comment by RodneyBaker** [comment]
@Al532 I'm not sure if you ever got a satisfactory answer to your question here...

**Comment by artisteacher** [comment]
In Tahoma2D, you can move the center of a column to change the offset between a column and a motion path. It works just the same with a peg. Moving the center of the peg, moves all of the children.

Here's the offset of my 3 columns which are connected to the same peg:
<img width="408" alt="Screen Shot 2022-03-14 at 6 37 45 PM" src="https://user-images.githubusercontent.com/21159116/158272358-8aa87c0a-80e2-4d50-9e30-a494d8c9ec71.png">
If I move the center to the drawings:
<img width="348" alt="Screen Shot 2022-03-14 at 6 37 56 PM" src="https://user-images.githubusercontent.com/21159116/158272495-34168f57-493b-4b0d-851b-5c66354c55f2.png">
And then let go, the drawings all move together to the motion path:
<img width="182" alt="Screen Shot 2022-03-14 at 6 38 05 PM" src="https://user-images.githubusercontent.com/21159116/158272545-0af3f7a5-cf08-4666-b72b-b118616437aa.png">
I could also move the center to increase the offset and etc.

If this hasn't been ported over to OT yet, it should be. Personally I don't see any benefit to the original behavior...

**Comment by RodneyBaker** [comment]
A workaround for this appears to be collapsing the column (or columns) down into a subxsheet.
The subxsheet can then be adjusted further on/off anywhere along the motion path.

**Comment by RodneyBaker** [comment]
@Al532 I'm not sure if your question ever got answered.
Please let us know if you have additional questions.
