### ISSUE TITLE
error when using a cintiq

### ISSUE THREAD

**Issue by Melunis** [opentoonz/opentoonz#3312]
**Describe the bug**
stroke appears only after i release the pen, windows ink support enabled, using cintiq 13HD
bug disappears when: before opening Aplication i set screen settings to duplicate, then open the Aplication then change the settings to extend. 

**To Reproduce**
List steps to reproduce the behavior.
1.Set the screen to extend (i have 2 screens )
2. open openToonz
3.try drawing in any level raster or vector

**Expected behavior**
I expect it to draw simultaneously as i draw

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 2020-03-03
 - GPU: NVIDIA RTX 2070
 - GPU Driver Version: 445.87

**Comment by RodneyBaker** [comment]
Set the extended screen to the same resolution as the main screen/monitor and see if that helps.

**Comment by Melunis** [comment]
it works if i change the resolution to the same as my cintiq, but it is a waste to set my main 4k fancy monitor to 1080p, can someone help me figure it out so i can use my main screen at 4k resolution?

**Comment by manongjohn** [comment]
There is a known issue when using multiple monitors that drawing may be offset from where the pen. The only ways to work around this is to either set the resolutions on both monitors to be the same or duplicate the screen instead of extending.

**Comment by melieconiek** [comment]
This configuration seems to work for me. The offset is unnoticeable in any case. I still cannot use screen scaling, though. This is on a Cintiq Pro 24 (4k) paired with a 1080p secondary display.

![image](https://user-images.githubusercontent.com/42298081/83253956-e3049880-a17b-11ea-9ef6-66fb68cf384f.png)

**Comment by Melunis** [comment]
no i don experience any offset only "lag" - my stroke appears only when i release the pen, my cintiq is only 1080p, and my main monitor is 4k

**Comment by Melunis** [comment]
solved the issue by setting my cintiq as main display! thank you for your help
