### ISSUE TITLE
Browser navigation improvments 

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3314]
This request  is similar to the behavior that we could find in the windows explorer for browsing files:

1. Would it be possible to be able to navigate our files with the keyboard. I mean by pressing a letter you can browse the files that refer to the letter.

2. Is it possible to keep the blue color of the last selected file maintained when you return to the "browser" room after changing rooms.

3. When using the flipbooks preview in addition (right click> view) allow to use the arrows to scroll through the different content files

This would help to find what we want more quickly and to better visualize things as well.

**Comment by DarrenTAnims** [comment]
I'd agree that the OT browser should work like windows explorer. On top of the above:

- Double clicking to move into a folder, not a single click. The number of times I've double clicked and moved down 2 folders is just irritating. I'm sure it's a feature to save time, but it doesn't.
- Double clicking to open each file type. I know that has been done for scenes. Hopefully, it'll be done for the other files too.
- Backspace delete to move up a folder
- Cursor keys to move up and down the list.
- Tab to move from the folder list to the file list.

Or we could just use the standard browser and save time trying to reinvent the wheel. I'm sure this was revolutionary in its time, but you can just show a standard browser window so easily.

**Comment by beeheemooth** [comment]
Really! What could be a “browser” without a search engine? ^__^

**Comment by openanim** [comment]
I agree ,maybe single click or double click could be an option, it seems to me that there is already a similar option with cells in the preferences. A search bar would be great !

**Comment by turtletooth** [comment]
I got double clicking working for folders and viewing files.

**Comment by openanim** [comment]
On vector level :

In the browser, a sequence of numbers with 1 digit does not seem to work well with OT when the sequence changes to 2 digits for example:
1,2,3 ... 9 ... 10 or_1, _2, _3 ..._9 ..._10 (scenario 1)

but works in this way 01, 02, 03..09..10 or_01 ...._ 10 when all numbers are 2 digits. I mean, _10 PLI file will be after _09 file, (scenario 2).

I think OT in the 1st scenario should display the continuation as in the second in the browser. This is, I think, the expected behavior and basic file naming.

**Comment by Zenahr** [comment]
Could we have an option to have OT use the default file explorer instead?
