### ISSUE TITLE
Crash and corrupt file creation when converting file to unpainted TLV

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3320]
**Describe the bug**
Program crashes and corrupt file is created when converting a single image to a TLV with the right-click Convert command in the file browser

**To Reproduce**
1. Convert a single image (does not have a sequential numbering format in its name) to a TLV in the file browser in Unpainted TLV mode

2. Program crashes and a very small corrupt TLV file is created

**Expected behavior**
Image gets converted into a TLV 

**Screenshots**
![convert](https://user-images.githubusercontent.com/60277069/83369155-393a2d00-a370-11ea-8b56-1cbcfa2d89e8.png)

![sampleimage](https://user-images.githubusercontent.com/60277069/83369163-3ccdb400-a370-11ea-9d2d-ace9ae51a2a4.png)

**Device Information:**

    OpenToonz Version: OpenToonz 1.4 nightly (built May 31 2020 10:18:28)
    Operating System: Windows 10 Home 64-bit
    CPU: Intel Core i7-4710HQ
    Memory: 16 GB
    Graphics Card: Nvidia GeForce GTX 970M
    Graphics Tablet: XP-Pen Artist 22HD

**Comment by manongjohn** [comment]
Confirmed this crash. This was due to a change in #3099.  It worked correctly prior to this change.

**Comment by shun-iwasawa** [comment]
Thank you @RattusaurusRex and @manongjohn for reporting and investigating the problem. 
Sorry for the trouble, I'll look into it.
