### ISSUE TITLE
'Save Level As' - Level Replaced When Action is Canceled

### ISSUE THREAD

**Issue by melieconiek** [opentoonz/opentoonz#3329]
**Describe the bug**
Bug appears after executing the 'Save Level As...' command while 'Replace Toonz Level after SaveLevelAs command' in the options is enabled. If the user tries to save over an existing file and hits 'Cancel' when asked if they want to overwrite the file, the file will still be replaced on the Xsheet. The action is not able to be undone.

**To Reproduce**
1. Enable 'Replace Toonz Level after SaveLevelAs command' under the General tab in the settings dialog.
2. Create two new levels on the xsheet and save both (Level A, Level B.)
3. Place the xhseet cursor on the first level (Level A) and execute the 'Save Level As...' command.
4. Attempt to save over the second level (Level B.) When presented with a dialog box asking if you'd like to save over the existing file, hit 'Cancel.'

_The level will be replaced on the xsheet even though the action was canceled._

**Expected behavior**
Nothing. The action should be canceled.

**Device Information:**
 - OS: Windows
 - OpenToonz Version: Latest Nightly

**Comment by openanim** [comment]
There seems to be a issue with saving the levels.
I tried several times to save changes to a vector level, but after restarting OT the saves were not done. I used both command save level and save level as.
It seems random in my environment, I don't know how to reproduce it. I wonder if maybe it's a problem that could be related in some way to this one.
