### ISSUE TITLE
Windows called with  a large size

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3330]
There seems to be a problem when calling a window. Most are larger than before. For example, the style editor window takes up the whole width of my screen.

**To Reproduce**

1. call a window as style editor

**Expected behavior**
Normal size as previous versions

**Screenshots**
![issue_windows](https://user-images.githubusercontent.com/29790512/83932605-fcbd6580-a7a3-11ea-96ef-b2d620837f95.png)

**Comment by openanim** [comment]
It seems that is fixed.

**Comment by RodneyBaker** [comment]
Post mortem review:  It's not immediately clear what changed to fix this although there are several likely candidates.
