### ISSUE TITLE
Right-click on guide to delete also opens context menu

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#3331]
**Describe the bug**
Right-clicking on a guide handle in the viewer's ruler area both deletes a guide & opens the GUI context menu.

**Expected behavior**
In the ruler area, right-clicking on a guide handle should only delete the guide. Clicking in the ruler area but not on a guide should open the context menu.

**Device Information:**
 - OS: macOS 10.15.4
 - OpenToonz Version: Nightly - May 3rd 2020

**Comment by RodneyBaker** [comment]
Confirm on Windows as well.
I don't recall this happening in other recent releases so perhaps it's a fairly new change.
Will have to test some older release as that might clue us in to when it changed.
