### ISSUE TITLE
Control Point editor bug alt_click

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3332]
**Describe the bug**

The CPE tool is very weird lately. When you want to create a corner point, it advances the point by several millimeters. A second click continues to move it forward instead allow it to find its handles. It occasionally follows a crash.

**To Reproduce**
Itseems random but happens  fairly regularly

**Screenshots**

![CPE_issue](https://user-images.githubusercontent.com/29790512/84058354-695d7d80-a9b9-11ea-86d7-dd838b877f8f.gif)
**Device Information:**
 - OS: W10
 - OpenToonz Version:  Nightly jun 05 2020

**Comment by beeheemooth** [comment]
I confirm this.
