### ISSUE TITLE
Use "X" and "Y" instead of "E/W" and "N/S"

### ISSUE THREAD

**Issue by morevnaproject** [opentoonz/opentoonz#3337]
This is more intuitive for users.

![screenshot_002](https://user-images.githubusercontent.com/332868/84241890-4ef6e180-ab2a-11ea-89b9-c789cdefa844.png)

**Comment by DarrenTAnims** [comment]
I agree. For users working digitally, using X & Y is typically how you'd refer to those directions.

**Comment by beeheemooth** [comment]
Maybe it's better to change Z to Z / N - zenith and nadir? ^_________^

**Comment by MrBlockCat** [comment]
This would be awesome! I’d say definitely a step towards OpenToonz being more intuitive.
