### ISSUE TITLE
gui bug: level strip width  is wrong when you start open toonz

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#334]
Every time you open open toonz, if the starting room has a level strip - the level strip width will be set to a ridiculously wide value - not the one you had when you closed it last time.

To reproduce : 

1. Go to a room where the level strip is visible like this:
![levelstrip-1](https://cloud.githubusercontent.com/assets/6495061/15403384/a4466d52-1df0-11e6-9ca9-6fa6da5d0997.PNG)
2. quit open toonz
3. start open toonz again. When it loads at the same room, the level strip width will be doubled like this:
![levelstrip2](https://cloud.githubusercontent.com/assets/6495061/15403443/dd0f3196-1df0-11e6-93cc-3cda74c392db.PNG)
This is a slightly annoying bug - because it makes the user change the width.

I reported it at #80 as a comment, but I should have made a dedicated bug report for it - so as more developers notice it.

**Comment by Rayek** [comment]
Yes, confirmed. Every time I start OT, it bugs me, and I kept thinking "I ought to report this as a bug", but I kept forgetting. Thanks Blurymind.

**Comment by turtletooth** [comment]
Confirmed here too.

**Comment by kogaki** [comment]
Thanks to @Banbury , this issue has been fixed
