### ISSUE TITLE
Feature request - hit tab key to toggle only canvas mode

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#335]
This is something present in most drawing applications nowadays.
The idea is basically when you hit the tab key, all other windows dissappear and you only see the canvas.

so for example when you work on this and draw something:
![levelstrip-1](https://cloud.githubusercontent.com/assets/6495061/15403641/ebb21744-1df1-11e6-9224-17b06bed4127.PNG)

hitting tab makes the entire window show only the canvas or the window that your mouse hovered over when you hit the button:
![capture](https://cloud.githubusercontent.com/assets/6495061/15403701/3001b774-1df2-11e6-848a-e35b7884d9b3.PNG)

Hitting tab again brings you back to the normal view.

That way the artist has more screen estate to work on the illustration and distracting GUI disappears!
It's especially useful for people who know all the keyboard shortcuts.

**Comment by shun-iwasawa** [comment]
Double-clicking the title bar of the panel will enlarge it to entire window size.
(Double-clicking again will return to the normal view.)
Does it meet your demand, or you mean you would like to assign shortcut to such feature?

**Comment by Rayek** [comment]
It would indeed be handy if we could assign a shortcut to this function.

**Comment by blurymind** [comment]
A shortcut would be quicker and indeed nice to have. When using a stylus ,
double clicking doesnt feel natural

**Comment by blurymind** [comment]
Is it possible to assign one? If so, i will close this

**Comment by tofarley** [comment]
There is a shortcut setting for this. Under `Customize->Configure Shortcuts` in the `Visualization` section, `Show/Hide Full Screen`. The GUI doesn't accept tab as a shortcut (it tries to tab to another field) but you can set it to Ctrl+Tab or something similar.

**Comment by blurymind** [comment]
The problem is that it also full screens it. Full screen and show only
canvas should be two separate functions-like it is in most other software

**Comment by turtletooth** [comment]
Done.  Pull request 404

**Comment by blurymind** [comment]
Thank you :) 
Now we only need a full screen mode without pane maximizing

**Comment by turtletooth** [comment]
Demo:
https://youtu.be/80EF-2QG-gE

**Comment by blurymind** [comment]
Please merge this. Its so much more comfortable to use this way!

**Comment by turtletooth** [comment]
Merged #581
