### ISSUE TITLE
the erase is extremely slow

### ISSUE THREAD

**Issue by sozz7** [opentoonz/opentoonz#3350]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by turtletooth** [comment]
Need more detail please.

**Comment by sozz7** [comment]
draw a black line with the paint brush in a vector level
i have only 2 levels both vector, one with a simple line the other with about 40 frames of very basic rough animation
using wacom intuos by bluetooth
erase black line and very laggy

alienware 15 r3 15gb ram windows 10
