### ISSUE TITLE
Exploding Sub-x "bring relevant pegbars into the main x sheet" change to communicate effect on all parenting

### ISSUE THREAD

**Issue by phillycheese007** [opentoonz/opentoonz#3357]
when given the option to "bring relevant pegbars into the main x sheet"
a user might expect that if they have any peg-bars they will come into the main x sheet upon exploding.

-what this command actually does is ensure any parenting(peg-peg/peg-column/column-column)
stays intact.

if you do not check this option columns parented to each other will lose their parenting upon exploding.

Imo the dialog box needs to say this explicitly. 

I discovered this then exploding a head sub-xsheet with about 20 levels....for a second i thought i had forgotten to parent everything but i tried checking the first option(even though there is not one peg in my scene) and it kept parenting of columns intact

![hhhhh](https://user-images.githubusercontent.com/25863731/84888867-cc4fb400-b04c-11ea-9d18-ed93ab71bfcf.PNG)

**Comment by DarrenTAnims** [comment]
I agree. This is very misleading.

However, if I've got ANY parenting, I can't imagine a situation when I wouldn't want to bring these relationships into the main timeline. So personally, it's a dialog that, I suspect, 90% of the time, everyone wants to do the same thing, so why are we all being bothered with it? If you want to unparent your columns, do so before you explode your sub-xsheet.

So my suggestion is to remove the dialog and ALWAYS keep your columns parented.

**Comment by manongjohn** [comment]
Perhaps another option would be to have a checkbox to not prompt any more and remember choice for future use. This way people are aware of the option until they understand if they really need it or not.

Probably want to start a Preference option that consolidates these types of checkboxes into 1 spot so people can reset some or all of them if they need to.

**Comment by phillycheese007** [comment]
@DarrenTAnimsIi'm there with you.. I don't really need an un-parent function...though sometimes it does come in handy if you want to scrap a whole bunch of pegs at once....so i would not disable this.

@manongjohn this would make sense in the preferences...i have the feeling that most people use one or the other function the majority of time...so this would make sense

but the wording should definitely change imo
"bring parenting in main x sheet" is more accurate than the current bring relevant pegbars into the main x sheet"
