### ISSUE TITLE
Disable Bountysource

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#3358]
@shun-iwasawa In light of the new changes to bountysource's terms of service, I would like to recommend disabling bountysource.  Apparently if a project manager emails bountysource and asks them to disable posting bounties to their project and asks them to refund all bounties posted for a project to the original payers, bountysource will do so.

support@bountysource.com

**Comment by turtletooth** [comment]
The new terms of service sure sounds a lot like theft.

**Comment by manongjohn** [comment]
I agree with @turtletooth on the suggestion (and the comment *smirks*) .

Probably a good time to find other ways to fund developers other than bountysource. 

If we disable bountysource and people are refunded their money, the biggest issue is the Assistant Tool bounty. Perhaps something can be arranged privately to partially award the bounty as a show of good faith with the remainder upon successful merging. There were 14 backers for that bounty so not sure how that would work.

**Comment by shun-iwasawa** [comment]
@turtletooth
I think the first priority would be to prevent any existing bounties from being taken by Bountysource.
 
> Apparently if a project manager emails bountysource and asks them to disable posting bounties to their project and asks them to refund all bounties posted for a project to the original payers, bountysource will do so.

Is that true? According to the mail I received and the terms of use, I thought that the bounties are nonrefundable and only the backers can ask them to "redeploy" their bounties to another issue.

**Comment by shun-iwasawa** [comment]
It seems that the bounties for following 3 issues will be lost on July 1. (Correct me if i am wrong!)

### [(WIP) Krita-Like Assistant Tool For Opentoonz](https://www.bountysource.com/issues/47719781-wip-krita-like-assistant-tool-for-opentoonz)
Posted on 29 July 2017 by @Orphanlast
#### Backers
@Orphanlast @zarco1794 @Agnyy @openanim @jpturcotte @amotarzi @splatz
@sfepa @Toybulldog
[Backers I couldn't find the Github account]
trim  Ziggy7570  wolfram  Agnes955  richie  InTheSky


### ["Test tween command" and inbetween pop-up](https://www.bountysource.com/issues/48479745-test-tween-command-and-inbetween-pop-up)
Posted on 21 August 2017 by @openanim

#### Backer
@Orphanlast


### [(WIP) Command Bar missing icons.](https://www.bountysource.com/issues/60247847-wip-command-bar-missing-icons)
Posted on 29 June 2018 by @openanim

#### Backer
@openanim

**Comment by turtletooth** [comment]
I got an email today saying they had reverted  the new policy.  They went back to their old terms of service.  It looks like we don't need to worry about expiring bounties yet.  I don't really trust that they won't try something like this again though.

Regarding my message earlier, I had seen another repo owner who had asked bountysource to disable posting bounties on his repo and they responded that they would block new bounties and refund the existing ones.  I don't think we need to do that anymore, though.  And it may have been a one time thing for him.  It isn't posted as a public policy.

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for the update! Wow.
https://twitter.com/Bountysource/status/1273406549252177920
