### ISSUE TITLE
feature request - full screen mode that does not change the room layout 

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#336]
Full screen mode is something present in most drawing software nowadays.
What it does is when enabled, it full screens the application - so it uses the entire screen of the monitor. Any panels and window decorations that come with your operating system become invincible and no longer take screen estate.

This will in my opinion further improve the painting tools in open toonz. :)

**Comment by Rayek** [comment]
Full screen mode is already possible: right-mouse click in the view, and choose "Full Screen". I assigned the F12 shortcut.

Or double-click on the title bar of the view, and the other panels will be hidden. Double-click again to switch back.

**Comment by blurymind** [comment]
Ah awesome. Sorry i missed it. Closing

**Comment by blurymind** [comment]
Ok it does full screen, but it hides all the panels. This is now what I meant. When going full screen - i want the software to preserve it's interface, just use all the screen estate of the monitor

**Comment by turtletooth** [comment]
Demo: 
https://youtu.be/3ykJ-88BftI

**Comment by blurymind** [comment]
This is perfect. Much better than what we currently have! Looking forward to getting it in the nightly builds :)

**Comment by adamearle** [comment]
Yes Yes Yes is the hotkey by any chance the Tilda Key? Well done on
improving workflow on such a horrible interface IMO.

Personally I think why bring it up to the same standard as Harlequin when
Harlequin clearly needs a massive overhaul done its workflow. I get jumping
through the hoops and getting it one par.

But I am pretty sure if you asked the community what kind of timelines and
libraries they are wanting to deal with in terms of workflow; the  first
thing that spring to mind would not be Open Toonz  IMO

Maybe we can ask some questions to the world and hold a Kick starter and
get what we really want and some people can get paid.

Adam Earle

**Comment by blurymind** [comment]
Well we need to first establish a developer or a developer team with proven knowledge of the code base, a list of goals and more than anything else- the time and will to do it. For now we can clearly see a number of active contributors who improve the current features immensely, while also getting to know the code base. Its not clear if dwango's devs work on it full time. There is no roadmap either. The best course of action really is to file bug reports and suggestions, make tutorials and videos - so as to place the software in more people's workflow. Stabilize it, iron out the rough edges and get the low hanging fruits. I already posted a couple of bigger feature requests, but they are not enough for a kickstarter campaign

**Comment by blurymind** [comment]
We should be careful what to implement from the suggestions from internet. Not all the people making them know the software enough or have the experience of working on productions. Some of the suggestions might not fit it. Btw a good case study is Krita's kickstarter campaign. They made 30k last year and 40k this year. They however have a foundation, full time devs and a solid roadmap

**Comment by turtletooth** [comment]
The toggle panel hotkey is ~ and the fullscreen mode is Ctrl - ~.

I agree with @blurymind - my main goal is getting the basic ui more understandable and picking the low-hanging fruit.  I am a teacher and want to use this in my classroom but some UI pieces need to be tweaked before I can really implement it.  I would love to see a full roadmap developed and help out as I get more familiar with the code base.

**Comment by turtletooth** [comment]
Merged #581

**Comment by blurymind** [comment]
@shun-iwasawa @turtletooth  Thank you!! :)
