### ISSUE TITLE
can't find the precision tool

### ISSUE THREAD

**Issue by DKdexusMusic** [opentoonz/opentoonz#3362]
I can't find the precision tool now Hardness appears, and I need to use precision for my drawings

**Comment by RodneyBaker** [comment]
Not sure what a 'Precision Tool' is.
A few things to note:

The terms in the menu are different for various languages so perhaps by 'precision tool' you refer to the 'accuracy slider' in the toolbar?  Not sure.

Some options will not appear until we have created a level.
The reason for this is that different levels have different options.
For example, vector levels have Accuracy and Smooth while raster level have Hardness and Smooth.

If by 'precision' you mean 'accuracy', try creating a vector level to draw on and then activate the brush.

**Comment by RodneyBaker** [comment]
@DKdexusMusic Have you had any luck finding the tool you need?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@DKdexusMusic please let us know if that is not the case.
