### ISSUE TITLE
Opentoonz export with mac

### ISSUE THREAD

**Issue by Cosmicdrawer** [opentoonz/opentoonz#3366]
**Question**
Ask a question related to OpenToonz.
Hi everybody, please be patient, I'm a new Opentoonz user, I own an Apple computer and trying to export my animation as a video I cannot find any video format, I googled it and found some posts reporting the same issue but in 2017, do you confirm that I can't still export video format with Mac? they didn't release any patch in order to fix this?
Thanks

**Comment by artisteacher** [comment]
On macOS, you need to install FFmpeg to be able to render to mp4, gif & webm formats. Directions are [here in the manual](https://opentoonz.readthedocs.io/en/latest/using_ffmpeg_with_opentoonz.html#installing-ffmpeg-for-mac).

**Comment by Cosmicdrawer** [comment]
Thanks! I'm gonna try right now!

**Comment by RodneyBaker** [comment]
Closing.  @Cosmicdrawer please let us know if you have additional issues or concerns.
