### ISSUE TITLE
Level Strip Docking Bug

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3370]
**Describe the bug**
Level strip window gets stuck and screws up windows in a room when docking it into certain places.  Level strip stays stuck after exiting and re-opening the program. The only way to get rid of it is to reset to default rooms. 

**To Reproduce**
1. Move level strip to certain horizontal edges of windows to dock
2. Level strip gets stuck on screen, dark rectangle appears in top left of room, other strange window behavior

**Expected behavior**
Level strip docks into place

Turtletooth made a fix for this in Tahoma here: https://github.com/turtletooth/tahoma/commit/07ccb76de74f2c7f990d8993ac66b6198f3b8df6

**Screenshots**
![levelstripbug](https://user-images.githubusercontent.com/60277069/85958841-8bf60d00-b94d-11ea-88b8-a1cd5540eabf.gif)

**Device Information:**
OpenToonz Version: OpenToonz 1.4 nightly (built Jun 28 2020 10:18:00)
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: XP-Pen Artist 22HD

**Comment by turtletooth** [comment]
I actually put back the code I removed in that fix and modified it here:
https://github.com/turtletooth/tahoma/pull/59

**Comment by shun-iwasawa** [comment]
@turtletooth 
Can you please post a PR with the same fix to OT as well ?
