### ISSUE TITLE
Enable Style Editor & Level Palette for Empty Cells when Autocreation is Enabled

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#3376]
**Is your feature request related to a problem? Please describe**
When an empty cell in a column is active (unless it is the first empty cell after a level), both the style editor & the level palette are disabled and show nothing. If autocreation is enabled (the default), drawing in empty cells adds frames to a level in the column - or creates a level if one is not there already. It's annoying to have to draw in a frame first to be able to switch or create styles, especially if there's a level there already.

**Describe the solution you'd like**
If there is a vector, toonz raster, or raster level in the column, the style editor & level palette should be enabled for empty cells if autocreation is turned on. If there is not a level in the column and autocreation is on, I would argue that the style editor & the default palette for the level type should be visible.

**Comment by phillycheese007** [comment]
To add to this...it is distracting on playback if there are empty cells in a level... You get the palette and style editor flickering back and forth.

**Comment by artisteacher** [comment]
Has been implemented.
