### ISSUE TITLE
"Failed to save palette" warning appears even though palette is saved

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3377]
**Describe the bug**
After adjusting a Level Palette with a Studio Palette, using 'Save All' results in a warning message pop-up saying that it failed to save the Level Palette.  But, upon exiting and reopening OpenToonz, it is clear that the Level Palette was saved - all styles are still there.

Pressing the 'Save Palette' button will prevent the warning message from appearing, but it does not seem necessary in order to actually save the the Level Palette.

**To Reproduce**
1. Use 'Load into Current  Palette' or 'Adjust Current Level to this Palette' from the Studio Palette
2. 'Save All'
3. Warning message appears
4. Exit the program (warning message appears again)
5. Reopen the program (level palette is still there)

**Expected behavior**
If the Level Palette has been saved, no warning should appear saying that it has not been saved.

**Screenshots**
![fail](https://user-images.githubusercontent.com/60277069/86414651-6df41980-bc79-11ea-9630-c5b3cb801bb6.png)

**Device Information:**
OpenToonz Version: OpenToonz 1.4 nightly (built Jun 28 2020 10:18:00)
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: XP-Pen Artist 22HD

**Comment by RodneyBaker** [comment]
Seems related to #3378 (which has been merged) at least tangentially.
