### ISSUE TITLE
Xsheet enhancement: allow xsubsheets to be opened in additional Xsheet panel

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#341]
Currently the animator is allowed to open multiple Xsheet window instances. All these instances, however, display the same timeline.

When working with subsheets, it would be extremely handy if the animator would be able to open the subsheet in one Xsheet window, and keep the master scene open in the other Xsheet window.

This would allow for easier subsheet animation, and simultaneously the animator could keep track and edit the master Xsheet.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
