### ISSUE TITLE
I can't delete the "Opentoonz Stuff" 

### ISSUE THREAD

**Issue by BerryDecode** [opentoonz/opentoonz#3413]
I can't delete the file, it keep saying that i need admin permission

**Comment by artisteacher** [comment]
On macOS, since the stuff folder is in the Applications directory (and available to all users), admin privileges are needed to delete it. On my home computer, as the only user, I am automatically the admin so deleting is not an issue. At work, I had to get admin privileges from the tech team.

**Comment by RodneyBaker** [comment]
@BerryDecode   Any update?  Are you still having issues with permissions?
Closing.

Also:  Please be aware that the Opentoonz Forum is a good place to troubleshoot problems that aren't specifically bugs.  
Link:  https://groups.google.com/forum/#!forum/opentoonz_en/categories
