### ISSUE TITLE
Weird 'undo' glitch

### ISSUE THREAD

**Issue by Cherryfrin** [opentoonz/opentoonz#3415]
![Screen Shot 2020-07-20 at 11 43 17](https://user-images.githubusercontent.com/67905605/88466308-e76ed880-cec2-11ea-9cca-e175296835ee.png)
![Screen Shot 2020-07-25 at 22 02 07](https://user-images.githubusercontent.com/67905605/88466309-ea69c900-cec2-11ea-9a69-39bf1068c58c.png)
Recently I've been getting all sorts of glitches and this one is new.Now when you want to go back to fix a mistake you have one that is unfixable probably because opentoonz thinks this is the image you started with.I don't know what the cause is but this is probably linked with the previous problem i had with right clicking because most glitches I come across on this program is caused by right clicking.But anyway, this glitch is very annoying especially now that I made a 30 second animation and had to clean up because of that problem.I use a MacOS Sierra btw opentoonz 1.4 and use a mouse to draw.

**Comment by artisteacher** [comment]
I think you've just run into a change in the user preferences rather than a glitch. In the menu, try going to "OpenToonz -> Preferences -> Saving" and uncheck "Clear Undo History when Saving Levels".

**Comment by Cherryrin** [comment]
Thank you for this!I remember tampering with the preferences a bit so I will try this.

**Comment by Cherryrin** [comment]
> I think you've just run into a change in the user preferences rather than a glitch. In the menu, try going to "OpenToonz -> Preferences -> Saving" and uncheck "Clear Undo History when Saving Levels".
I'm not sure if they renamed "Clear Undo History"because I cannot find it on the preferences so is "Undo memory size" the same thing?

**Comment by Cherryrin** [comment]
![Screen Shot 2020-07-26 at 16 26 22](https://user-images.githubusercontent.com/67905605/88483001-d1adf180-cf5c-11ea-8659-c4b025701830.png)
I don't think I can find this option anywhere, did the creators rename it?

**Comment by artisteacher** [comment]
Sorry! I'm using a more recent nightly build - the preference must have been added after 1.4. Try doing a clean install of the [most recent nightly build](https://github.com/opentoonz/opentoonz/releases/tag/nightly). I recommend renaming the Stuff folder first as a backup. Then if you need to copy any projects or etc. over to the new Stuff folder, you can. You'll need to redo any changes to preferences but you should see the undo history option.

**Comment by Cherryrin** [comment]
Okay,will do thanks.

**Comment by RodneyBaker** [comment]
Any update here @Cherryfrin ?
Did running a clean installation resolve the problem?

**Comment by Cherryfrin** [comment]
Oh yes,I fixed this long time ago so I should probably close this issue.
