### ISSUE TITLE
Can someone please explain the difference between levels and layers?

### ISSUE THREAD

**Issue by Cherryrin** [opentoonz/opentoonz#3417]
I've been using opentoonz for about a month but I still have not fully understood the difference or what are actually levels.
I only ever use them if I want to insert a new frame without dragging the previous one behind its they are really useless to me to be honest.But I feel like one day I'll need them for my projects but since I don't name them at all I'll have to browse through like 50!I'll be very grateful if someone explained in detail.
Thanks.

**Comment by RattusaurusRex** [comment]
Levels contain your drawings.  Without levels, you would have no drawings, so they are not useless.  Layers/columns are where your level drawings are exposed as frames for animation.  The OpenToonz docs should have everything you want to know: https://opentoonz.readthedocs.io/en/latest/index.html

**Comment by gab3d** [comment]
Honestly, @Cherryrin this bug tracking system is not for this kind of questions.
For basic usage questions you have the Google Forum, you can access through the OpenToonz' Help menu.
Or you could consult the Online Manual, also accessible from the same place.

Thanks for your comprehension.

**Comment by RodneyBaker** [comment]
Will close this but feel free to keep the discussion going as needed.
Closed reports can still be posted to.

**Comment by Cherryrin** [comment]
Sorry for the cloggage guys!
