### ISSUE TITLE
My windows are stuck in place and the image of the buttons are too large compared to the actual button

### ISSUE THREAD

**Issue by Evantures** [opentoonz/opentoonz#3418]
**Describe the bug**
The layout of my windows got messed up and the image of them are now larger and disproportional to the actual buttons. Every time I try to find and resize the edges of a window the program closes. The first image shows the layout that occurred when the bug fist happened and how It currently is right now. The second image is how it looked like after the first few reopenings of OpenToonz and before I updated my driver

**To Reproduce**
1. Downloaded OpenToonz and opened it
2. Tried to resize and reorganize the windows
3. The layout bugged out and became stuck

**Expected behavior**
I wanted to move the windows around to my liking but this glitch happened. I tried deleting and redownloading OpenToonz as well as updating my driver but the problem persisted.

![20200728_153249](https://user-images.githubusercontent.com/68926579/88723780-15386500-d0ef-11ea-9b39-a30f392f2d4a.jpg)
![OpenToonzpic](https://user-images.githubusercontent.com/68926579/88723766-0c479380-d0ef-11ea-8f3a-8c9c271cfa4f.jpg)

**Device Information:**
 - OS: Windows
 - OpenToonz Version: 1.4
 - GPU: Intel(R) UHD Graphics
 - GPU Driver Version: 26.20.100.6911

**Comment by manongjohn** [comment]
Try downloading and installing version 26.20.100.7584? Here is the direct download link:

https://downloadmirror.intel.com/29274/a08/igfx_win10_100.7584.exe

**Comment by jeedha** [comment]
having the same issue and that download won't install.

**Comment by Evantures** [comment]
I tried downloading the driver you provided but it didn't let me. Heres the pop up
![image](https://user-images.githubusercontent.com/68926579/89092281-e54ec300-d375-11ea-8d18-f364f44cf6be.png)

**Comment by Evantures** [comment]
Ok i finally got it fixed it by getting some updates from the dell and intel site

**Comment by RodneyBaker** [comment]
Congratulations on the fix!
