### ISSUE TITLE
Abnormal color lines when rendering. Bug?

### ISSUE THREAD

**Issue by Juls3000** [opentoonz/opentoonz#342]
Not sure if there is some relation. I see abnormal color lines in rendering (just in one frame) with "Channel Width" set to 8 bit, 

![rep1](https://cloud.githubusercontent.com/assets/19145844/15438038/9604efd6-1eca-11e6-9424-64ec4cbbcc3b.jpg)

when I set it to 16 bit it seems that the color lines disappear

![rep2](https://cloud.githubusercontent.com/assets/19145844/15438040/9cc616ce-1eca-11e6-86e7-bc66148e18eb.jpg)

Using **OT Pre-Release 2016-05-20 08:09:25 UTC**
Please see attached my platform:
[NVIDIA System Information 05-20-2016 20-38-09.txt](https://github.com/opentoonz/opentoonz/files/275238/NVIDIA.System.Information.05-20-2016.20-38-09.txt)

**Comment by kogaki** [comment]
Thank you for your report. We will examine it.
For developers, related topic is here <https://groups.google.com/forum/#!msg/opentoonz_en/fwJFbXyRJ4U/hCpoLsoRAgAJ>.

**Comment by Juls3000** [comment]
Thank you ! :)

**Comment by artisteacher** [comment]
It’s been over 2 years, @Juls3000, is this still an issue? I’ve never run into it myself.
