### ISSUE TITLE
Animation now loads but now with no drawings at all

### ISSUE THREAD

**Issue by SmithyGCN** [opentoonz/opentoonz#3423]
**Describe the bug**
Okay, I finally got it to load the scene by updating the program. Now, when I load the scene however, the entire scene is blank. What happened?

**To Reproduce**
List steps to reproduce the behavior.
1.Just load the scene.
2.
3.

**Expected behavior**
I expect there to be the animation I was working on.

**Screenshots**
![image](https://user-images.githubusercontent.com/68975222/89073684-98042e80-d340-11ea-8f98-9b0e3fc7c141.png)

**Comment by RattusaurusRex** [comment]
Did you move any files?  Right-click on a frame, choose Level Settings, and check the path.  Are the drawings there, or are they somewhere else on your computer?

**Comment by SmithyGCN** [comment]
Okay, did that. Still nothing, though. I feel we're getting closer.

**Comment by RattusaurusRex** [comment]
You did what?  Are the drawings located in the path location or not?  Did you move any files or not?

**Comment by SmithyGCN** [comment]
I did. All of them.

**Comment by jrhyme** [comment]
Was the update from version 1.3 to 1.4?

**Comment by SmithyGCN** [comment]
Yeah. I have 1.4

**Comment by RattusaurusRex** [comment]
This might be related to #3361? One thing I have confirmed is that the levels/drawings are still intact.  He shared one of the level files with me and I was able to load it into my copy of Opentoonz just fine.

![miss](https://user-images.githubusercontent.com/60277069/89585385-9def8900-d7f2-11ea-8cd1-2dab0ff0b013.png)

**Comment by manongjohn** [comment]
@SmithyGCN  I'm still a little confused.  So after you saved the scene originally, did you move the level files, the scene file or the project directory or anything related to this animation? 

If you did **not** move anything and when you opened it, it was just blank, then can you zip up the project folder and share it with me, privately, so I can take a look to see what is happening?

You can contact me privately on discord, if we're on the same ones, on reddit or the google forum.

**Comment by SmithyGCN** [comment]
Sure. I just don't know your discord handle.

**Comment by RodneyBaker** [comment]
Closing  as likely resolved.
@SmithyGCN Please let us know if you are still experiencing problems.
