### ISSUE TITLE
Feature Request - context sensitive toolbar.

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#343]
If you are working a level all the tools are always available. It would be better if the tools that are not usable are not shown or are greyed out depending on the level that is selected.

![context](https://cloud.githubusercontent.com/assets/18170954/15441994/97e6e3e0-1ede-11e6-946c-8457e8b39b35.png)

**Comment by blurymind** [comment]
good idea! it will make the software more user friendly :)

**Comment by blurymind** [comment]
best approach would be to not show tools that are not available for that level. That will make the ones that are available easier to find/click on.

**Comment by BrundleThwaite** [comment]
I agree that Is what I would like as well.

**Comment by blurymind** [comment]
Also the mesh level does not allow the select tool, the brush tool and geometric tool

**Comment by blurymind** [comment]
Hiding the unavailable to the level tools like that would free screen estate for some of the tools that have too much functionality crammed into a single too.

The mesh tool (modes) for example can be split into 4 separate tools that you can select from the toolbox:
- edit mesh tool --> no need to rename
- paint rigid tool --> no need to rename
- build skeleton tool --> no need to rename
- animate tool --> could be renamed to "pose tool"

**Comment by BrundleThwaite** [comment]
That is a possibility (and would be faster to work with) but the problem then would be that it will not be consistent with other tools like the skeleton tool so when you get to that kind of change you would have to think a lot more carefully in order to keep the interface unified.

If it is applied consistently though it could be a very nice workflow improvement.

**Comment by CodyEakins** [comment]
I support this change on the condition that the tools were simply greyed out rather than completely disappearing -- it can mess w/ a person's UI customization pretty quickly and there muscle memory to "look" at an icon (because it's position would move around w/ respect to other icons disappearing).

**Comment by blurymind** [comment]
the muscle memory is a good point, but in this case some of these toolbox entries actually get buried behind an extra click - as they cant all fit vertically.
Hiding the unavailable ones will improve workflow by removing that extra click that is required:
![extraclick2](https://cloud.githubusercontent.com/assets/6495061/15720281/93016dcc-282b-11e6-9492-0755f6908262.PNG)
![extraclick](https://cloud.githubusercontent.com/assets/6495061/15720280/92ffeeac-282b-11e6-9bd1-9d7c1fa6ea9c.PNG)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
