### ISSUE TITLE
surface pen pressure sensitivity issue

### ISSUE THREAD

**Issue by Dkobs** [opentoonz/opentoonz#3432]
hello, 

I just got a new Surface Book 3 and surface pen for school, and I wanted to try using opentoonz for some animation. For whatever reason, however, the pressure sensitivity isn't exactly working for the surface pen. Instead of allowing me to go from my set minimum size to maximum size by pressing more or less hard, the brush stroke will almost instantly go to the set maximum size when I start a stroke. Does anyone know why this might be? Any help would be appreciated.

**Comment by manongjohn** [comment]
Try enabling in OT: Preferences -> Touch/Tablet Settings -> Enable Windows Ink Support.

**Comment by Dkobs** [comment]
> Try enabling in OT: Preferences -> Touch/Tablet Settings -> Enable Windows Ink Support.

Ha! Thank you so much! Works great now.

**Comment by crab-kap-wearer-stds** [comment]
> Try enabling in OT: Preferences -> Touch/Tablet Settings -> Enable Windows Ink Support.

i use a lenovo thinkpad which uses windows and then tried, but its not wotking
