### ISSUE TITLE
Audacity integration with Opentoonz issue

### ISSUE THREAD

**Issue by Snevetz74** [opentoonz/opentoonz#3436]
Importing an Audacity wav file into any Opentoonz (1.4 version) column(s) with existing animation causes the Audacity wav file to crash. More specifically, the Wav file sound is intermittent (the sound cuts in and out), and the Audacity wav file sound quality is only clear when paired next to an opentoonz column without any animation contained. An isolated Audacity wav file will work (without the subsequent animation columns).

**Comment by artisteacher** [comment]
Are you working with 32bit audio? 16bit is more reliable.

**Comment by RodneyBaker** [comment]
@Snevetz74 Can you supply a wav file that is crashing?

**Comment by Snevetz74** [comment]
I think it's figured out.  I changed it (Audacity)from 32 bit to 16 bit
prior to exporting. Also I enabled the noise reduction sample (in
audacity). Seems to be working  okay now.

**Comment by RodneyBaker** [comment]
Please let us know if you experience any similar issues.
Closing.
