### ISSUE TITLE
Worley noise effect

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#344]
This is one of the most useful procedural effects ever made.

https://en.wikipedia.org/wiki/Worley_noise

http://www.rhythmiccanvas.com/research/papers/worley.pdf

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
Reopening.

Curious to know how close some of the added effects, in particular the fractal noise fx comes to worley noise.

REF:  New Fx: Fractal Noise Iwa Fx #3422
