### ISSUE TITLE
Github crashing after I opened a scene

### ISSUE THREAD

**Issue by Cherryrin** [opentoonz/opentoonz#3443]
I imported a mp4 video not long ago and was about to add audio.When I opened the scene it loaded for a long time and then crashed.Now when I open opentoonz it crashes and leaves me with this,
![Screen Shot 2020-08-14 at 14 34 25](https://user-images.githubusercontent.com/67905605/90255092-b2a7ce80-de3b-11ea-842d-c6f79c73f64a.png)
I'll just delete the scene but if problems still continue I'll update

**Comment by manongjohn** [comment]
Not sure how long your mp4 is, but you may need to increase Preferences -> Import/Export -> Ffmpeg Timeout setting.

Also note that when loading mp4, it will first convert them into a PNG sequence in a temp cache area before loading. Make sure you aren't running out of space.

**Comment by Cherryrin** [comment]
oh alright.Thanks!
