### ISSUE TITLE
What are these blue lines around the viewer's upper edge?

### ISSUE THREAD

**Issue by Cherryrin** [opentoonz/opentoonz#3444]
These lines kind of bother me but look unharmful.I have no information about these and can't look in the manual because I don't know what they actually are!All I know is that they are probably linked with the camera.
![Screen Shot 2020-08-14 at 14 49 42](https://user-images.githubusercontent.com/67905605/90256540-cd7b4280-de3d-11ea-9e0d-813a9c69ada7.png)

**Comment by manongjohn** [comment]
Those are guides you can use. You should be able to right click on the blue part in the ruler to delete then or left click to move them. You can also remove them if you left click and drag away from viewer.

**Comment by Cherryrin** [comment]
Oh thanks!
