### ISSUE TITLE
Opentoonz crashed even the saved file got corrupted,and the tools are not working properly

### ISSUE THREAD

**Issue by arconor** [opentoonz/opentoonz#3448]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by arconor** [comment]
crashing
tools not working
automatically deletes saved file

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@arconor If you are still experiencing this issue with the latest nightly release please let us know.
