### ISSUE TITLE
crashed while importing png

### ISSUE THREAD

**Issue by arconor** [opentoonz/opentoonz#3449]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by turtletooth** [comment]
Can you share the png?

**Comment by RodneyBaker** [comment]
Closing as an incomplete report.
@arconor If you have any additional information to report please post it here and we will reopen the issue.
Thanks!
