### ISSUE TITLE
What does black mean in the Sheet timeline?

### ISSUE THREAD

**Issue by Cherryfrin** [opentoonz/opentoonz#3453]
I was just loading a scene and saw this appear in the audio layer.I clicked on it and opentoonz crashed, but when I checked in the browser,I didn't delete the audio file.
![Screen Shot 2020-08-20 at 16 43 25](https://user-images.githubusercontent.com/67905605/90794594-db7d0780-e304-11ea-986f-29d7149df569.png)

**Comment by manongjohn** [comment]
If you loaded an mp3 into OT but did not configure ffmpeg correctly, it shows up as a black column.

Basically you loaded some sort of audio file whose format isn't supported.

**Comment by Cherryfrin** [comment]
Oh yeah, another thing is that OT cannot save the mp3 when I deleted it and put the same one again so is that linked with FFmeg?

**Comment by RodneyBaker** [comment]
The MP3 format is only supported in Opentoonz via ffmpeg.

**Comment by Cherryfrin** [comment]
Oh okay I understand what's the problem,thanks!
