### ISSUE TITLE
I open my scene and the program crashes

### ISSUE THREAD

**Issue by tazcreations** [opentoonz/opentoonz#3456]
**Describe the bug**
When I go to open my last scene I was working on the day before. Opentoonz just crashes and shuts down.

**To Reproduce**
List steps to reproduce the behavior.
1. Load up opentoonz
2. Click on the last scene I was working on
3. Program stops and shuts down

**Expected behavior**
Scene loads and I can continue my animation.

**Screenshots**
![Error](https://user-images.githubusercontent.com/69707613/90955462-b7fcbd00-e4bc-11ea-9b64-9d02ded862c0.jpg)
As soon as I click on my scene the program just shuts down.

**Device Information:**
 - OS: Windows 10 Pro
 - OpenToonz Version: Version 1.4 - Nightly (2020-08-22)
 - GPU: Geforce GT 710
 - GPU Driver Version: 432.00

**Copy of my Scene**
[Playing in a box.zip](https://github.com/opentoonz/opentoonz/files/5112303/Playing.in.a.box.zip)

**Comment by b4zz4** [comment]
The same thing happens to me.
But I can't find <n link ...

[scene_crash.tnz.zip](https://github.com/opentoonz/opentoonz/files/5183875/scene_crash.tnz.zip)

**Comment by manongjohn** [comment]
@b4zz4 You have the other issue of `<>`...`</>`.  Search file for those and remove them.

**Comment by RodneyBaker** [comment]
@b4zz4 This should be fixed in the latest nightly release (with fix courtesy of @manongjohn (Thanks John!)

Nightly releases:
https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by b4zz4** [comment]
@RodneyBaker I compile it for gnu/linux and works fine

**Comment by b4zz4** [comment]
this scene was broken when saving in version 2020-09-27 08:27:28 UTC
[E11T1.tnz.txt](https://github.com/opentoonz/opentoonz/files/5302782/E11T1.tnz.txt)

:(
