### ISSUE TITLE
Bug: Character color on Memos turns white

### ISSUE THREAD

**Issue by Juls3000** [opentoonz/opentoonz#346]
I found "Memos" very useful , between other things, as a help to syncronize sound with animation.

Now it has a bug:

(03) Case of you delete the first character:

![cats00](https://cloud.githubusercontent.com/assets/19145844/15447913/50107df6-1f51-11e6-9fde-3c8849c87baf.jpg)

(04) The characters color turn white:

![cats01](https://cloud.githubusercontent.com/assets/19145844/15447921/64858682-1f51-11e6-82e1-7532eca955b3.jpg)

**Comment by BrundleThwaite** [comment]
I agree this is annoying and needs to be fixed.

There is a small workaround ( if you do not already know it :) ).
-open the style editor.
-then select the memo text and you should get arrow at the side:

![memo](https://cloud.githubusercontent.com/assets/18170954/15453383/249db378-2014-11e6-941a-2c350934e28c.png)

this will give you the text properties which will allow you to reapply the the colour with the style editor.

**Comment by Juls3000** [comment]
Thank you !

**Comment by shun-iwasawa** [comment]
Modification merged.

**Comment by Juls3000** [comment]
Great thank you !
