### ISSUE TITLE
How to "loop" a short sequence of frames?

### ISSUE THREAD

**Issue by JTheSpyder** [opentoonz/opentoonz#3463]
Hey,
so I'm trying to do a little animation with a helicopter thats flying in the air. Because the moving rotors are just like 13 frequently returning frames, I'd like to know if theres a function where I can group these few frames together in the xsheet without having to copy them down until like the 300th frame. Is there a way to do that or do I have to keep copying the frames until the whole scene is finished?

Thanks in advance!

**Comment by artisteacher** [comment]
You could select the cells you want to repeat, right-click on them, and then select "Edit Cell Numbers -> Repeat". In the Repeat dialog, you can either set the number of times you wan the selection to repeat or you can specify what frame number you want them to repeat up to. There's also a repeat button in the command bar.

Alternatively, you can copy the first cell in the sequence and paste it into the cell after the last frame for the sequence (you could also just type in the frame number). Select just the last two cells & then drag with the small handle to repeat the sequence for as long as needed.

**Comment by beeheemooth** [comment]
Aside. The kung fu method. ^_^

![ezgif-7-922b03cc9e78](https://user-images.githubusercontent.com/25724133/91631540-f1fd2000-e9e2-11ea-9ec6-f55336aa2f0e.gif)
