### ISSUE TITLE
Opentoonz doesn't open

### ISSUE THREAD

**Issue by ItsWidee** [opentoonz/opentoonz#3464]
I downloaded OpenToonz recently and every time I try to open it, the loading screen appear but after charging, no window.
I don't know what to do. My computer run on Windows 10 64 bits.

Hope y'all help !

**Comment by manongjohn** [comment]
Can you go to Windows Event Viewer and look for a Windows Application Error log that explains why OT is crashing? It might help determine what is going on.

**Comment by ItsWidee** [comment]
I have that 

> Nom de l’application défaillante OpenToonz.exe, version : 0.0.0.0, horodatage : 0x5e359c19
Nom du module défaillant : EDSDK.dll, version : 13.10.20.6400, horodatage : 0x5c4141df
Code d’exception : 0xc0000005
Décalage d’erreur : 0x0000000000046bbc
ID du processus défaillant : 0x7b48
Heure de début de l’application défaillante : 0x01d6806d2589416e
Chemin d’accès de l’application défaillante : D:\Program Files\OpenToonz\OpenToonz.exe
Chemin d’accès du module défaillant: D:\Program Files\OpenToonz\EDSDK.dll
ID de rapport : e8cc8491-998a-4e14-8b4d-a6d746ac29ab
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :

**Comment by ItsWidee** [comment]
@manongjohn

**Comment by manongjohn** [comment]
This was seen by another user on Reddit.  Here is what he said:

> Turned out EDSDK.dll was also a part of Canon EOS Utility and other associated Canon apps, and that they were also running in the background. I uninstalled them since I don't really have any use for them anyway and I figured this was the easiest way to solve it. This solved the EDSDK problem. I wonder if this could be of any use to the other user? Thanks for the help

Do you have some other Canon related apps installed?

**Comment by ItsWidee** [comment]
Oh yes I have one, it's also canon eos utility. Do I need to close it ?

**Comment by manongjohn** [comment]
Yes, try closing that and make sure it isn't running in the background and see if that helps.

**Comment by ItsWidee** [comment]
It worked ! Thanks !
