### ISSUE TITLE
Mutiple rooms automatically deleted

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3465]
![Screen Shot 2020-09-01 at 17 44 13](https://user-images.githubusercontent.com/67905605/91882560-0ce9c180-ec7b-11ea-9771-016c2e8e2a19.png)
I'm not sure how this happened as this happened recently,I made a room two months ago but that never interfered with any of the default ones.

**Comment by artisteacher** [comment]
I've never had rooms disappear, so I'm not sure what happened. There are 2 ways to remove rooms that I'm aware of:
1. Right-click on the room name from a different room & choose delete
2. Actually delete or move the room.ini files in the stuff folder 

If you want to get the original rooms back, you can always use the "Reset to Default Rooms" command. This would remove your new room, but you'd get the others back.
<img width="528" alt="Screen Shot 2020-09-03 at 7 15 26 PM" src="https://user-images.githubusercontent.com/21159116/92182543-ef9f2980-ee19-11ea-8530-dcaa6c9efeac.png">
It only takes effect after you restart OT.

**Comment by Cherryfrin** [comment]
@artisteacher Yeah I'm sure of that,but only the Browser and Farm rooms got deleted for some reason.

**Comment by manongjohn** [comment]
A user on reddit forum reported an issue of a custom room that they were using for over a month suddenly got deleted. Every time it is recreated, it gets deleted again. Likely related.

**Comment by Cherryfrin** [comment]
Yes although in the screenshot my custom room is still there,but its still related though.

**Comment by artisteacher** [comment]
@manongjohn does the reddit user get a crash on closing? Crashes on closing always prevent room changes from being saved - at least on macOS.

**Comment by manongjohn** [comment]
No crash mentioned. Just closes OT and room is gone when restarted. Was happening in Windows 10.
