### ISSUE TITLE
OpenToonz Nightly Linux AppImage

### ISSUE THREAD

**Issue by CigamPower** [opentoonz/opentoonz#3466]
I was wondering if a Linux AppImage could be made of OpenToonz nightly, or after commits. So that I can always work on the latest version that fixes various bugs. I am asking about this because I am currently using the OpenToonz eXperimental from here: https://github.com/manongjohn/OTX however that is done monthly. It would be nice to have an official version quicker than that. Thanks.

**Comment by RodneyBaker** [comment]
While not yet listed along with the nightlies this feature request is implemented via Github Actions where Linux Ubuntu artifacts are created for both GCC and clang.

To access, go to the top of Github > Actions
Opening that will display the operating systems on the left and build listing in the center.
Click on the appropriate operating system (in this case Linux) and then the PR of the desired build.
Just above will be a number (which should be 2 for Linux).
Click on the number as this is where the artifacts can be accessed.

There are likely other locations where these artifacts can be accessed but this location appears to be reliable.
