### ISSUE TITLE
v1.5 Planning and Report Review

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#3468]
**Current schedule (November):**
- [x] Report Review (ongoing)
- [x] Bug Hunt (Focus:  show stopping bugs and crashes)
- [x] UI Scrub (Focus:  major issues)
- [ ] Documentation
- [ ] Feature Roadmapping

This is an area to begin planning and to keep visibility open on status of various issues, bug reports, feature requests and other areas of interest moving forward to the release of Opentoonz v1.5 and beyond.

**Timeline / Schedule**
The release of v1.5 is anticipated for January 2021 timeframe with December 2020 being timeframe for feature freeze.

A review of activities since the release of v1.4 will be conducted to better capture the current efforts of the Opentoonz community.  

A survey of various resources available to include forks/branches and where appropriate other related and complementary software Opentoonz users utilize in their personal and/or studio productions will be conducted.

**Focus / Goal**
The focus of this early planning is to identify development tasks that should be included in v1.5 and to suggest reasonable timelines and paths forward for those tasks best suited for development in 2021 and beyond.

PRs added/merged thus far since v1.4 consist of 200+ features, enhancements, bug fixes and other general improvements:
https://github.com/opentoonz/opentoonz/pulls?q=is%3Apr+is%3Aclosed

**Comment by RodneyBaker** [comment]
Development currently assigned a monetary bounty:

https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3Abounty

**Comment by RodneyBaker** [comment]
Bugs and crxitical issues to include crash reports:

https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3Abug

**Comment by RodneyBaker** [comment]
Feature Requests:

https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22

Note that many other feature requests have been posted in other venues besides those currently in github.
A full review of all feature requests submitted will be conducted.

**Comment by RodneyBaker** [comment]
There are a number of known issues requiring review and documentation to provide best practices/workarounds until the issue can be more fully resolved:

Known Issues:
https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3A%22known+issue%22

**Comment by RodneyBaker** [comment]
Thanks to those who continue their efforts to document and translate Opentoonz:

Documentation:
https://opentoonz.readthedocs.io/en/latest/

Translation / Localization:

https://github.com/opentoonz/opentoonz/tree/master/stuff/config/loc

**Comment by RodneyBaker** [comment]
An area of general interest is promotion.

Opentoonz continues to gain interest from artists, animators.
Work is being produced regularly by individuals, students, studios and more.
Here we highlight best practices, workflow, features and the effort that has made Opentoonz what it is today even as we look forward to v1.5 and beyond.

**Comment by age3rcm** [comment]
is the feature, animating vector points, going to be in opentoonz 1.5 ?

**Comment by RodneyBaker** [comment]
> is the feature, animating vector points, going to be in opentoonz 1.5 ?

No.  There are no plans for adding animated vector points any time soon.
If you know of any developers interested in working on that many Opentoonz users would love to see that implemented.  :)

**Comment by RodneyBaker** [comment]
Here is a list of bugs being targeted... and many fixed... it Tahoma2d.
To the greatest extent possible we should try to channel those fixes upstream into Opentoonz v1.5.
'We' being the operative term here as there is currently limited interest in porting those fixes over.
For those interested, this is a great opportunity to squash some bugs while getting familiarized with the source code.

**Comment by RodneyBaker** [comment]
Of the  436 reports currently open there are a number of reports generated by highly active reporters.
I am currently reviewing those but would appreciate the authors giving them a look and where applicable add a note to indicate current status or any changes observed.  Your assistance will help in determining whether these issues can be addressed in time for v1.5 or moved to the 2021 development cycle.


@artisteacher:
https://github.com/opentoonz/opentoonz/issues/created_by/artisteacher

@beeheemooth:
https://github.com/opentoonz/opentoonz/issues/created_by/beeheemooth

@gab3d:
https://github.com/opentoonz/opentoonz/issues/created_by/gab3d

@morevnaproject:
https://github.com/opentoonz/opentoonz/issues/created_by/morevnaproject

@openanim:
https://github.com/opentoonz/opentoonz/issues/created_by/openanim

@shun-iwasawa: 
https://github.com/opentoonz/opentoonz/issues/created_by/shun-iwasawa

@WolfinABowl:
https://github.com/opentoonz/opentoonz/issues/created_by/WolfInABowl

In cases where the report is a feature request it will be helpful to know what process or application is currently being used in lieu of the feature being implemented in Opentoonz.


All combined these reports represent approximately half of those  currently open.

...and as always, thanks for your feedback!

**Comment by RodneyBaker** [comment]
A few 'planning' type updates...

**Funding**
It looks like use of bounty source for Opentoonz is winding down although there are still funds present which have not been awarded.  Currently testing githubs sponsorship feature to see how viable it might be for supporting individual deveolpers going forward.  A recommended step in 2021 might be to survey what resources are available as well as summarize current funding efforts specifically so that users and developers know what avenues for funding are open and closed.  A popular consensus is that there is currently not adequate funding for development.

**Bug Hunt**
The current Bug Hunt is closed with focus on show stopping bugs and immediate attention to correctly any bugs being introduced by new additions to v1.5.  There are a few high profile bugs/crashes that should receive focused attention after initial release of v1.5.  The most often encountered crashes appear to relate in some form or fashion to use of Plastic Tool.

**Feature Requests / Enhancement**
Feature requests continue to be reported regularly and there no lack of causes for developers to champion.
The focus here does appear to be narrowing into specific paths of productivity and user experience.
Concern for new user/student experience continues to be of high interest due to the complexity of Opentoonz and the often overwhelming scope of  animation production in general.  
Studio support for new features is largely off the radar and feedback from studios and their representatives is always appreciated. 

**Known Issues**
Most of the knowledge base of known issues is collected only via Opentoonz github.
Some effort to further refine these issues for purpose of planning and documented workarounds should be explored in 2021.

**Promotion**
Promotion is currently held in the hands of users of Opentoonz and specifically in the animation, artwork and related documentation shared in various communities.  These include personal blogs, Youtube, Reddit, Discord, Udemy, etc. 
As users get more experience with the tools and processes, the content created will further promote Opentoonz.

And that is roughly where we are as we leave v1.4 and 2020 and move forward into the release of v1.5
