### ISSUE TITLE
OpenToonz turn off itself when I use "no current level" to drawing.

### ISSUE THREAD

**Issue by learndrawingagain** [opentoonz/opentoonz#3471]
**Describe the bug**
crash

**To Reproduce**
List steps to reproduce the behavior.
It crashes this way: >>>>
1. New sence
2. Brush sth on the paper
3. select "No current level"
4. brush sth
5. Opentoonz turned off automatically

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: Windows 10 (Up to date)
 - OpenToonz Version: OpenToonz 1.4
 2rd Feb 2020
 - GPU: NVIDIA Geforce MX250 / Intel(R) UHD Graphics 620
 - GPU Driver Version: 451.67 / 26.20.100.7926

**Comment by jrhyme** [comment]
Use the latest versions. Perhaps your problem won't be there. https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by RodneyBaker** [comment]
This fix is not in Opentoonz nightly releases as of yet.
We still need to smooth out the path of commit flow from forks/branches.
As has been mentioned though the fix can be tested currently in the Tahoma fork.

REF commit:  https://github.com/turtletooth/tahoma/pull/149/commits/09a331b688675ca760977ad7a281fd6b305548e2

https://github.com/turtletooth/tahoma/pull/149/commits/09a331b688675ca760977ad7a281fd6b305548e2
