### ISSUE TITLE
Cannot correctly import indexed-colour PNGs

### ISSUE THREAD

**Issue by cjriches** [opentoonz/opentoonz#3474]
**Describe the bug**
If an indexed-colour PNG is imported, it does not display correctly. Problems include missing transparency, weird vertical black lines, lack of colour, and incorrect image size.

**To Reproduce**
List steps to reproduce the behavior.
1. Load any PNG that uses indexed colours, observe that it is wrong.
2. Convert the same PNG to RGB colours and import, observe that it works just fine.

**Expected behavior**
All PNG images should import correctly; there should be no difference between indexed-colour and RGB-colour images.

**Screenshots**
![image](https://user-images.githubusercontent.com/11373036/92718814-37faa200-f35a-11ea-80f6-c08114a33881.png)
The right hand fish has been converted from indexed-colour to RGB colour before loading.

PNGs in question:
Indexed
![indexed colour](https://user-images.githubusercontent.com/11373036/92718942-68424080-f35a-11ea-910e-9fc33b37cad5.png)

RGB
![rgb colour](https://user-images.githubusercontent.com/11373036/92718952-6aa49a80-f35a-11ea-9e3e-4efaff7c23c6.png)

Note how they are identical when viewed outside of OpenToonz.

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.4
 - GPU: NVIDIA GTX 970
 - GPU Driver Version: 26.21.14.3200

**Comment by RodneyBaker** [comment]
If you aren't using a current nigthly release you might not have a fix that addresses a related issue.

Ref:  https://github.com/opentoonz/opentoonz/issues/242

If the v1.4 of Opentoonz you are using is of January vintage (e.g. from the link on the Opentoonz website) then it will not contain this fix.  Nightly releases can be found here:  https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by RodneyBaker** [comment]
John Dancel added some more information to similar report in the Opentoonz Forum.
REF:  https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!category-topic/opentoonz_en/qUjHXxBLaXE

In particular, he mentions that some images may not be 8bit or 16bit PNG files and that could lead to problems.
The 8bit problem was fixed however so if the PNG is 8bit then an upgrade should fix the problem.
If other than 8 or 16bit then the workaround of converting the image will likely work.

@cjriches If you can share a copy of the actual image that is causing problems that will help assess the problem more fully.
Thanks!

**Comment by RodneyBaker** [comment]
When using both images posted above I get norm results.
No grayscale and no artifacting.

It is my guess that the release being used does not include the fix and that using a current release will resolve the problem.
@cjriches If you can confirm you have tested a current nightly release and still have the problem that will be appreciated.
Thanks!

**Comment by cjriches** [comment]
Ah, yes. The problem exists on 1.4, but the latest nightly works just fine. Both images loaded correctly.
![image](https://user-images.githubusercontent.com/11373036/94363919-8085bf80-00bd-11eb-83da-c3f03b6ff7af.png)

**Comment by RodneyBaker** [comment]
Outstanding news.
Thank you for the feedback and I hope the word gets out to the others that have had this problem.

Closing.
