### ISSUE TITLE
drawing like this is not possible

### ISSUE THREAD

**Issue by iceharryred** [opentoonz/opentoonz#3476]
**Describe the bug**
I do not know describe it it's when I try to put my pen onto the drawing tablet I have here and i start trying to draw as a like a delay I know it's like normal but there a delay for it the delay and when I try to do quick strokes it doesn't even register let me try to record it

**To Reproduce**
List steps to reproduce the behavior.
1.put pin on tablet
2.drag 
3.the line do not follow 
[2020-09-13 13-56-35.zip](https://github.com/opentoonz/opentoonz/files/5214961/2020-09-13.13-56-35.zip)

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment]
Can you provide information on what kind of pen and tablet you are using?
That will help is assessing the problem.

**Comment by YesMab** [comment]
I'm having the same issues man
or at least similar

**Comment by manongjohn** [comment]
2 things you should look at trying:

1. Enable Preferences -> Tablet/Touch Settings -> Enable Windows Ink Support.  This may help with pen not drawing
2. To help with drawing out of position, try one of these solutions that works for you since you have 2 monitors:
    - Make sure the resolution on both monitors is the same or as close as possible
    - Duplicate the main monitor to the tablet instead of extending it
    - Make your tablet the main monitor.

**Comment by YesMab** [comment]
Thank you I got everything working now. I went to my Huion driver and enabled mouse mode. Sorry for bothering you.

**Comment by manongjohn** [comment]
@YesMab Out of curiosity, does mouse mode allow for pen pressure sensitivity?

**Comment by RodneyBaker** [comment]
Closing as resolved but @YesMab if you can provide @manongjohn with additional information I'm sure he will appreciate it.
Thanks!
