### ISSUE TITLE
unable to find ffmpeg on Parrot

### ISSUE THREAD

**Issue by CharlesFreeman2016** [opentoonz/opentoonz#3482]
**Describe the bug**
insttalled ffmpeg  added file path to opentoonz
then i restarted opentoonz but when i try to render i still get the same error 

**Expected behavior**
render file  to mp4 

**Screenshots**
![Screenshot at 2020-09-16 13-09-15](https://user-images.githubusercontent.com/57152880/93335557-290e6680-f816-11ea-904d-2a8006bd8aac.png)

**Device Information:**
 - OS: Linux
 - OpenToonz Version: 1.4.0
 - GPU: NVIDIA RTX 2080
 - GPU Driver Version: [e.g. 440.00]

**Comment by manongjohn** [comment]
Not sure what Linux distro you are using. If you are using a snap version of OT, it won't detect it due to an issue with snap security.  

You either need to
1. Compile locally from source
2. Download and use OTX version which is a portable AppImage
3. Download and install the Morevna Edition version (either installed or portable AppImage)

**Comment by CharlesFreeman2016** [comment]
Thanks for the tip

**Comment by CharlesFreeman2016** [comment]
It didn't work
My distro is parrot 4.10

**Comment by RodneyBaker** [comment]
I'm not familiar with the linux parrot distro.
Perhaps someone can provide additional information on where current linux releases of Opentoonz can be found and leveraged for use on Parrot.

As there is no official support for linux (or parrot) by Opentoonz it will be important to contact those in the community who do support Opentoonz on various platforms as well as contacting the Parrot community who may have suggestions on how best to get Opentoonz running on their platform.

**Comment by RodneyBaker** [comment]
Feel free to continue the discussion here as others will be interested in the information also.
