### ISSUE TITLE
Crash when exploding sub-xsheet containing audio level.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3488]
**Describe the bug**
The explosion of a sub-xsheet containing an audio file is so powerful that it even destroys the program.

**To Reproduce**

1. Collapse audio level
2. Explode obtained sub-xsheet

![ezgif-3-256e99162eea](https://user-images.githubusercontent.com/25724133/93585495-90135300-f9af-11ea-8a66-c41a4ca8f9d4.gif)

**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: latest

**Comment by RodneyBaker** [comment]
I confirm the crash.
A workaround appears to be to not collapse a column that contains only an audio level.
If accidentally collapsing only an audio level, Undoing will restore without a crash but exploding a subxsheet with only an audio level consistently produces a crash.

**Comment by RodneyBaker** [comment]
Thanks to @jeremybullock for the fix over in Tahoma for this issue.

Developer note:
We are still investigating the best way to port fixes over from the forks.
Developers interested is assisting with porting bug fixes and features from Tahoma into Opentoonz please don't hesitate to let us know.  Recent bug fixes and features added to Tahoma will eventually work their way here but with your help they'll get here a lot quicker.   Thanks!
