### ISSUE TITLE
layout difficulties?

### ISSUE THREAD

**Issue by drylinens** [opentoonz/opentoonz#349]
This will sound silly but here it is...

 I just downloaded OpenToonz version 1.0.1. I opened it and started messing around. After turning on my onion skin preferences I somehow x'd out of the cleanup settings and the cleanup camera has now disappeared. I uninstalled it and and re-installed it and when it loaded up I got it the exact same way I had messed it up previously.
 Is there anyway to get the layout how it was on default once again?

**Comment by turtletooth** [comment]
If you are on a PC- If you delete the OpenToonz 1.0 Stuff folder from your C: drive and reinstall you should get the default layouts back.
