### ISSUE TITLE
freeze on playback control using 1 control image

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3491]
**Describe the bug**

The viewer freezes when adding a control image with particles. Even if you turn off the source image from the schematic. The playback features no longer respond, perhaps related to this #3489

**To Reproduce**
List steps to reproduce the behavior.

1. Add particles fx
2. Add  control image
3. Use playback control to play or loop with preview enabled

**Expected behavior**
No freezes as previous version

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment]
I am not able to reproduce this in current nightly release.
@openanim Can you confirm?

**Comment by openanim** [comment]
Yes indeed it looks like it's good ! Thanks.
