### ISSUE TITLE
Can you Import/Export/Use .FLA (Adobe Flash Animate) or .SWF (Shockwave Flash) files on OpenToonz?

### ISSUE THREAD

**Issue by Calvin242** [opentoonz/opentoonz#3494]
So recently, I installed OpenToonz on my Chromebook, via Linux Beta last week. And I was so very curious, if that software had the ability to use .FLA or .SWF files. So you see, I really want to use those assets that my friend gave me over on Social Media, but those files can only be done by Adobe Animate, and since my Chromebook doesn't have Adobe Animate, or a semi clone of it, I can't use those files. So can you teach me how to use them on Opentoonz, or just me a plugin so I can use it.

Cheers,
Calvin

BTW: Here's the file: https://drive.google.com/file/d/1D5NJ7w4gJq8J9YZGwxRH-Bk8uWAjWr1O/view

**Comment by DarrenTAnims** [comment]
No you can't. But if your friend can export to png images or a gif/mp4 video, you can import those.

**Comment by RodneyBaker** [comment]
Agree that converting from FLA to another format (or rendering out to appropriate format) is the best way to go for getting these resources into Opentoonz.

Closing but please continue the discussion here as others will be interested in the information also.

**Comment by openanim** [comment]
This and #3461 reminds me that Harlequin had the import and export functionality to swf. It may be a lead to explore as alternative bridge between somes softwares for vectors works, if the swf was brought back.

**Comment by RodneyBaker** [comment]
@openanim Can you confirm Harlequin had import for swf (or other similar formats)?
I know some earlier versions of Toonz could output to swf (as well as WIndows screensaver format) but I can't recall the import.

**Comment by jeremybullock** [comment]
All the swf code was ripped out.  It never made it into the OT source code.

**Comment by openanim** [comment]
@RodneyBaker, Yes, but it is transformed into a .pli file therefore, everything does not correspond correctly to the original (effects, gradients etc.). It depends on the model.

**Comment by Calvin242** [comment]
> No you can't. But if your friend can export to png images or a gif/mp4 video, you can import those.

As in this for example? (NOTE: I DON'T OWN THIS ASSET: https://www.deviantart.com/jnohai/art/Let-s-Go-Luna-Honey-Assets-856016372)

**Comment by RodneyBaker** [comment]
From what I can tell the SWF code was removed with PR 9 (although I suspect it was a very limited implementation from the outset.

@Calvin242 There are currently no appropriate formats for .FLA in Opentoonz other than those standard image formats (PNG, etc) that can be converted by other programs into .FLA, .FLV, .SWF etc.

ffmpeg does have some support for the .flv wrapper/format but it seems you require FVA and/or SWF.
