### ISSUE TITLE
Specks appear on canvas while drawing lines in ToonzRaster with tablet

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3496]
**Describe the bug**
While drawing on my tablet in ToonzRaster levels with the default brush, I often get little specks/dots near the ends of my lines.  If I press Undo, the specks do not go away.  Sometimes undoing a much earlier drawn line will also undo the nearby specks -- the specks seem to be attaching themselves to earlier drawn lines instead of the line just drawn.  The specks are not just a graphical error, as they will be rendered in the animation.  Using the mouse, MyPaint brushes, regular Raster levels, or Vector levels do not produce any specks.  My tablet drivers are up-to-date.

**To Reproduce**
1.  Draw lines with the default brush in ToonzRaster level
2.  Specks appear (usually near the end of lines) and cannot easily be undone

**Expected behavior**
No specks/dots

**Screenshots**
![specks2](https://user-images.githubusercontent.com/60277069/93844977-0637e400-fc54-11ea-8644-963f68152111.png)

Video of the specks being created:
[specks.zip](https://github.com/opentoonz/opentoonz/files/5259254/specks.zip)

**Device Information:**
OpenToonz Version: OpenToonz 1.4 nightly (built Sep 22 2020 10:20:04)
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: XP-Pen Artist 22HD

**Comment by artisteacher** [comment]
Possibly related, I had a student trying to erase on a Toonz raster level. Increasing the eraser to the largest size (filling most of the viewer) actually added more and more artifacts the more they tried to erase. Type: normal, Mode: lines.

macOS Catalina
Wacom Intuos CTL-490 tablet

**Comment by RattusaurusRex** [comment]
I've found that if I have the program ScreenToGif running at the same time while using OpenToonz, I do not get any specks.  I don't know what kind of interaction is happening between my tablet pen, OpenToonz, and ScreenToGif, but maybe this could help point to the problem?

**Comment by RattusaurusRex** [comment]
Closing since it doesn't happen on my new tablet and I don't have the old tablet anymore.
