### ISSUE TITLE
OT crash on zerary fx after canceled a copy paste command

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3505]
**Describe the bug**

 OT crash if you copy then paste immediately whitout deselect the node accidentally
for the 3 commands paste replace / insert/ add
With paste add OT crash immediately whitout using cancel command

**To Reproduce**
List steps to reproduce the behavior.
1.Add/insert a zerary node
2.Copy the node
3.Use paste command
4. Cancel

All versions

**Comment by WolfInABowl** [comment]
I believe this may be a duplicate of #3084

**Comment by openanim** [comment]
@WolfInABowl yes it's a duplicate. Sorry i didnt checked if that issue was already reported.
