### ISSUE TITLE
Pressure dont work

### ISSUE THREAD

**Issue by b4zz4** [opentoonz/opentoonz#3507]
**Describe the bug**
Pressure don't work. Similar result with mouse
The wacom (056a:033b) pressure does not work
this works fine in version 1.4

**Device Information:**
 - OS: [GNU/Linux]
 - OpenToonz Version: [Nightly (2020-09-27)]
 - GPU: [ NVIDIA K100]

**Screenshot**
![draw](https://user-images.githubusercontent.com/643833/94378171-adf25d80-00fd-11eb-9454-4e48ff1d9210.gif)

**Comment by RodneyBaker** [comment]
Hi @b4zz4 
There is no official nightly release for Linux so it is not entirely clear what release of Opentoonz you are currently using.
Perhaps you are building from source?

**Comment by RodneyBaker** [comment]
An added note related to loss of pressure while drawing.
I noticed a loss of pressure the other day that seemed to relate to scaling/zooming in on the canvas.
At some point Opentoonz lost pressure and it didn't want to come back.
Later pressure sensitivity came back but I'm not sure what I did for that to happen.

**Comment by RodneyBaker** [comment]
@b4zz4  Any update on the status of this.
A request for additional information went out last October.

**Comment by b4zz4** [comment]
It seems a problem of the QT with which I compiled the opentoonz
