### ISSUE TITLE
problem with stroke color on version 102

### ISSUE THREAD

**Issue by cuuulboy** [opentoonz/opentoonz#351]
whenever i draw line, color is always red even when i add a new style and change color.But in preview and sub cam preview color is right as in style editor see the url . [http://b0.eu.is.pp.ru/v/vinuol/7/48416107vKH.jpg](url)

**Comment by shun-iwasawa** [comment]
Please check if the options "Ink Check" or "Ink #1 Check" are activated.
(In InknPaint room, they are in the menu bar > Checks menu by default.)
These options makes lines with the current style (or with the style #1) to be displayed in red color in the viewer.

**Comment by cuuulboy** [comment]
thanks shun-iwasawa it worked ! now i can draw with the color i choose :) thanks a lot >:)
