### ISSUE TITLE
Increment editor (like DragonFrame tool)

### ISSUE THREAD

**Issue by quirinux-so** [opentoonz/opentoonz#3512]
Increment editor is a tool widely used by StopMotion animators and it is the main reason why they prefer DragonFrame over any other software, be it free or proprietary.

If they could incorporate it, I know a lot of people who would start using OpenToonz.

Reference: https://vimeo.com/353672737

GNU / Linux users, we also miss being able to use at least our webcam

Reference: https://github.com/opentoonz/opentoonz/issues/3333

**Comment by gab3d** [comment]
it seems to be a very useful tool, indeed. :+1: 

@jpturcotte

**Comment by quirinux-so** [comment]
That's right, Gabriel, and the animators use it a lot.

**Comment by quirinux-so** [comment]
https://github.com/tahoma2d/tahoma2d/pull/420
