### ISSUE TITLE
Convert in browser area close OT after conversion

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3515]
**Describe the bug**

It's not something that happens all the time. But at times when you do a conversion from the browser panel, OT will automatically close after the conversion. It's not systematic so it doesn't seem like a preference but rather a bug. This has happened on all levels but more frequently on the vector level. The processor seems to be affected for quite a long time by the operation on my cintiq companion.

**To Reproduce**
List steps to reproduce the behavior.
1.Go in browser room
2. right click > convert on a .pli file (see attached file)
3.confirm convert
[convert_issue.zip](https://github.com/opentoonz/opentoonz/files/5317581/convert_issue.zip)
**Expected behavior**

Do not close OT or warn that OT will close after the operation

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
