### ISSUE TITLE
Translator rights

### ISSUE THREAD

**Issue by comradekingu** [opentoonz/opentoonz#3519]
Add https://hosted.weblate.org/user/kingu/ for https://hosted.weblate.org/languages/nb_NO/opentoonz/ ?
also, delete https://hosted.weblate.org/languages/norwegian_BOKMAL/opentoonz/

**Comment by Savraska2** [comment]
@comradekingu Sorry, I am new in Weblate. Despite the changes made, I was unable to configure the correct language names. #3499 
You are added as admin and can change the settings if you want.

**Comment by comradekingu** [comment]
@Savraska2 Deleted norwegian_BOKMAL, and added the language consistency plugin, and the component autotranslation one.
This means all added languages are available in every component, and translations between components populate other components if the strings match 80%, (added as needing work).

Some of the langauges are (generated), but I'll find out why that is. Closing this one :)

**Comment by Savraska2** [comment]
Thank you very much. @comradekingu
