### ISSUE TITLE
Fix Magnet "Influence" Profile to Simulate a Bell Curve (It is Useless as it is Now)

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#353]
Whenever the Magnet Tool is used on any curve - it distorts this curve by flattening the peaks - instead of producing a smooth Bell Curve shape.  If the Magnet Tool is used multiple times on the same curve - it becomes impossible to produce a continuously smooth shape - rather, it produces a shape composed of many "peaks" and "valleys".

To see this behavior in action, simply create a closed Circle with the Geometry Tool and use the Magnet Tool on this Circle multiple times.  The result is almost always not a useful shape.

Left with a shape that is not a continuously flowing curve, one is forced to use the Iron Tool to smooth out the peaks and valleys of this curve.  This extra step should not be necessary.

To see a Magnet Tool that works as it should, please examine the action of the Magnet Tool now present in Anime Studio Pro 11 - observing that it distorts a shape - smoothing out the boundaries of "magnetic influence" as it goes.

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
