### ISSUE TITLE
crash on a scene with level no saved

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3531]
**Describe the bug**
on the vector level, if I save a scene forgetting to save a level, when I load the scene again and use a tool (the brush in example) OT will crash.

1.create a level
2.save the scene
3.load the scene
4.use the brush / geometry / type tool on the level
5.OT will crash

**Comment by RodneyBaker** [comment]
I don't quite get the same results (i.e. no crash in my tests) but #3541 does appear to address the issue.

**Comment by openanim** [comment]
I confirm the fix thank you !
