### ISSUE TITLE
Where is Scene -> Scene Settings?  (I swear I saw it before, but no I can't seem to find it!)

### ISSUE THREAD

**Issue by ladlon** [opentoonz/opentoonz#3533]
The manual mentions the frame rate of the scene can be set by going to Scene -> Scene Settings, yet I can't seem to find what they are referring to.  Was this a change in Tahoma2D (vs OT)?

I know you can do an alternate output by 'stretching' in the Output settings, but I'm interested in 'hard coding' the scene frame rate, after a project has been started.

I just can't seem to find that screen anywhere, for some reason!

**Comment by shun-iwasawa** [comment]
In the current version `Scene Settings` is in `Xsheet` menu (In `Default` rooms layout).

![scenesettings](https://user-images.githubusercontent.com/17974955/96203995-2b431c80-0f9e-11eb-8c17-7ba679c18423.png)

If not, you can try `Windows -> Workspace -> Reset to Default Rooms`  and restart OT to get back the default menubar.

**Comment by ladlon** [comment]
Yep, there it is!  Thanks for that!

**Comment by gab3d** [comment]
@ladlon 
thank you for pointing it out.
Manual should be checked for that and corrected.

**Comment by manongjohn** [comment]
FYI, Tahoma2D changed `Xsheet` to `Scene`. It's still Xsheet in OT.
