### ISSUE TITLE
OPENTOONZ CRASHING ON CERTAIN SCENE

### ISSUE THREAD

**Issue by GRACEanims729** [opentoonz/opentoonz#3535]
**Question**
Hi everyone! Please help me! I can't open my project on certain scene which i am currently working now. it started crashing last week and until now, opentoonz kept on crashing. 
![image](https://user-images.githubusercontent.com/72960710/96216777-fe5b1f00-0f35-11eb-8fb4-db411e33095e.png)e

but when i open another scene, it doesn't crash 
![image](https://user-images.githubusercontent.com/72960710/96217044-a96bd880-0f36-11eb-8d27-24dfa6871048.png)

**Comment by beeheemooth** [comment]
Frames with negative numbers !? How did you manage to do this?

Oh, these are not frames, but levels in one column! O-O

**Comment by GRACEanims729** [comment]
Oh I’m sorry. This is what I use for the cut out animation. I just used it
as a name so i don’t have a hard time inputing the alpahabets letter by
letter

**Comment by manongjohn** [comment]
Quite possible the scene is corrupted from the crash. We'd need to see the .tnz file to check

I would see if the backup file still works. There should be a .tnz.bak file for your scene. Rename the original `.tnz` just to keep it, then remove the `.bak` from the filename and open the scene again.

**Comment by beeheemooth** [comment]
You have to make a sequence of images (rename all files like this: "name_0001") and load it from the program browser. All files in this case will be displayed in the browser as one file (screenshot) and you can load it into the scene by dragging it.
![Screen_0072](https://user-images.githubusercontent.com/25724133/96250597-c4caf800-0fb7-11eb-8f92-31113e8031b7.jpg)

**Comment by GRACEanims729** [comment]
Thank you ManongJohn! I only see my file named newscene2.tnz there’s no
.bak.

And how can I send it to you? Thank you so much for helping me. I hope that
I can recover my project

**Comment by manongjohn** [comment]
Oh. Either you turned backups off or you are on a version where it was not enabled by default. 🙁

If you are ok with posting it here, please do. Might need to add a .txt to the end of the file. If not, we'll find another way.

**Comment by GRACEanims729** [comment]
@manongjohn, here's my work. it's not done yet please do understand.


![NEW SCENE 02 ](https://user-images.githubusercontent.com/72960710/96257297-f7043780-0f6e-11eb-8510-93ee4e522596.png)

**Comment by artisteacher** [comment]
@GRACEanims729 - Try zipping the file/folder before uploading.

**Comment by GRACEanims729** [comment]
[NEW SCENE 02_1.zip](https://github.com/opentoonz/opentoonz/files/5397081/NEW.SCENE.02_1.zip)

**Comment by RodneyBaker** [comment]
@GRACEanims729 It has been quite awhile since you posted your file here.
As it looks like your scene file is mostly intact and recoverable hopefully you did recover it.
If this is not the case please let us know.
