### ISSUE TITLE
Opentoonz crash during Render

### ISSUE THREAD

**Issue by Snevetz74** [opentoonz/opentoonz#3538]
Opentoonz crashes during rendering phase. Before rendering in 'output settings', I tried choosing both saving to 'Desktop' or in 'Documents -  neither works . When the render stops, Opentoonz says Runs out of continguous physical memory. I've included the screenshots below.
![Opentoonz1](https://user-images.githubusercontent.com/69117986/96365809-d53eb800-1108-11eb-93a9-5b5731b520f0.jpg)
![Opentoonz2](https://user-images.githubusercontent.com/69117986/96365820-e8ea1e80-1108-11eb-8dba-0c8610693a86.jpg)

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Snevetz74 Please let us know if you are still experiencing problems.
