### ISSUE TITLE
Adding clipping masks that don't require the FX schematic

### ISSUE THREAD

**Issue by ALPHABRINE** [opentoonz/opentoonz#3556]
It would be massively helpful if we could use clipping masks in real time in Opentoonz without uisng mates.. Mates would be very good for complex  effects, but clipping masks would be helpful in alot of situations, Like fast coloring shadows into scenes ans characters without going outside the lines, Simulating things like blinks easily, or objects moving inside other objects and disappearing into other objects with clipping masks. Kind of like the Photoshop and Tv paint masks.

**Comment by RodneyBaker** [comment]
While technically this report should be left open and the newer one closed...
Will close this as additinal information has been added to that report.

Please see #4329 for more information.
