### ISSUE TITLE
The fill bucket is NOT working.

### ISSUE THREAD

**Issue by Duckdcluckgoose** [opentoonz/opentoonz#3558]
When I click, it doesn't do anything. I click and click and click and click and click and click and make sure that the lines were closed and they were but still it WAS NOT WORKING.

I even went to view and did transparency check. I did.

I don't even know what happened.

I have a Mac and my opentoonz is 1.4
Pleas help.

**Comment by artisteacher** [comment]
Check and see what the tool options you are using are. 
- Type: rectangular, polyline or freehand need to be dragged/drawn around the shape to fill it
- Mode: lines won't fill an area
- Frame range on: have to click to fill in multiple frames

Sometimes it helps to increase the maximum gap value on vector layers. Also, you probably already have this, but make sure you are filling with a style that will be visible on the background.

**Comment by Duckdcluckgoose** [comment]
It was working just a few hours ago.

The mode is normal.

**Comment by artisteacher** [comment]
Another thing to check is the style itself. Trail or brush styles can't be used for a fill. Same with 1/2 of the generated styles. Also, check the opacity of the style.

If there's no issue with the style & you are working on a vector level, you could try the "Replace Vectors with Simplified Vectors" command. It's in the Level menu under Optimize. If a vector shape is being fussy, that command almost always makes the shape fillable.

If none of this helps, you might want to try restarting the computer. Sometimes a restart can resolve strange behaviors if everything was working fine earlier.

**Comment by RodneyBaker** [comment]
There are a number of other settings/features that can make it look like we aren't filling as well as some that will prevent filling.
Since you were checking fills before... make sure you don't have 'Inks Only' on in the view menu  (where we turn on Fill Check etc.)

**Comment by Duckdcluckgoose** [comment]
The Fill only is not on.

**Comment by Duckdcluckgoose** [comment]
Well, not fill only. Inks only. Sorry.

**Comment by DarrenTAnims** [comment]
Can you share a screenshot while you're on the fill tool please?

**Comment by Duckdcluckgoose** [comment]
ok

**Comment by Duckdcluckgoose** [comment]
Ok

**Comment by Duckdcluckgoose** [comment]
ok

**Comment by Duckdcluckgoose** [comment]
Im am still trying to do that...

**Comment by Duckdcluckgoose** [comment]
![Screen Shot 2020-10-23 at 1 22 54 PM](https://user-images.githubusercontent.com/73257686/97051448-10d7e880-1534-11eb-824c-778db26e82b2.png)

**Comment by DarrenTAnims** [comment]
Thanks for sharing that. I see you've ticked the onion skin option. This is why it's not appearing to fill. The onion skin option takes the colour from the drawing that's showing on the onion skin, to copy it through. Untick it and you'll be able to fill.

**Comment by Duckdcluckgoose** [comment]
Thanks! That helped me a lot! Thank you so much!
