### ISSUE TITLE
Range start and end fields with the Adjust Thickness command

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3560]
**Is your feature request related to a problem? Please describe**

![stroke taper cacani](https://user-images.githubusercontent.com/29790512/97061075-c8511700-1595-11eb-8be6-98229f2bac4d.png)

This feature request is similar to "stroke taper" that can be found in cacani.

The adjust thickness command would help stylize and nuances our strokes quickly if it allowed for variations on the start and end of strokes instead of being applied globally.

Some workarounds as applying a vector style or using the pump tool is often laborious and time consuming to have the variations you want. This request would help with this goal if we could get a range start and range end field for each stroke half.

**Describe the solution you'd like**

New range field that allow to set some percentage of the half range start and end stroke to create variations.

the way how it's described in cacani manual

Range (Start) Determines how much of the stroke is affected by the Start Width Taper option. Affects the 1st half of the stroke

Range (End) Determines how much of the stroke is affected by the End Width Taper option. Affects the 2nd half of the stroke.

https://www.youtube.com/watch?v=8aAJxB-2QS0

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
