### ISSUE TITLE
Undo with Adjust Thickness display issues 

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3561]
**Describe the bug**
the adjust thickness command seems to have display issues.

![display adjust thickness issue](https://user-images.githubusercontent.com/29790512/97062360-e2412880-159a-11eb-8792-0c8bcb02a5a3.gif)

After validating a thickness
undo and redo only apply when the cursor is on the canvas.

to reproduce:
(1)
1.create strokes
2.select levels or strokes
3.use adjust thickness command on start field for example
4.undo or redo via shortcuts
5.undo or redo does not apply if the cursor is elsewhere than on the canvas

(2)
 Does the end field sometimes seem random? The display rarely seems to work in the preview window.

(3)
It would be very interesting to get a range start and range end field for the line in order to be able to create line variations at the start and end of each line quickly. (e.g to this feature request #3560).

**Device Information:**
 - OS: [e.g. Windows 10]
 cintiq companion 2

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
