### ISSUE TITLE
Be able to modify settings keys's from vectors styles

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3565]
**Is your feature request related to a problem? Please describe**
The animation of the parameters are based on the timing linked to the xsheet but it would be very useful to be able to also have them in the function editor in order to use the curves to quickly modify the speed. Especially when you animate the parameters related to different vector styles.

**Describe the solution you'd like**
similar to this request #3404  be able to modify key of settings from vectors styles in function editor similarly to the other "fx" while we animate them

**Comment by artisteacher** [comment]
Related to #3404

**Comment by openanim** [comment]
@artisteacher is it possible to extend your request to global animating palettes topic to take into account the settings keys also since they work in same way ? And i can close it as duplicate.

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
