### ISSUE TITLE
OpenToonz Files Missing! Can I Recover all my work??? 

### ISSUE THREAD

**Issue by Lettuceshoes** [opentoonz/opentoonz#3566]
**Question**
Ask a question related to OpenToonz.
I spent a little while working on a commission animation, probably around 6 hours. Opentoonz was behaving weirdly, not letting me adjust position keyframes, so i saved and quit, to try to solve the problem. When I came back the entire project was broken. Now I cant work on it and i lost EVERYTHING. Im kinda freaking out here. Is there a way to recover anything? 

I attatched then TNZ file 
[Among Us Comission 1.zip](https://github.com/opentoonz/opentoonz/files/5434128/Among.Us.Comission.1.zip)

**Comment by manongjohn** [comment]
There is a bug with how keyframe data is written to the .tnz file.  I've fixed your file.

[Among Us Comission 1.tnz.txt](https://github.com/opentoonz/opentoonz/files/5434146/Among.Us.Comission.1.tnz.txt)

This bug has been fixed and is available in the [latest nightly version](https://github.com/opentoonz/opentoonz/releases/tag/nightly). I highly recommend you upgrade to it so you don't run into this again.

**Comment by Lettuceshoes** [comment]
> There is a bug with how keyframe data is written to the .tnz file. I've fixed your file.
> 
> [Among Us Comission 1.tnz.txt](https://github.com/opentoonz/opentoonz/files/5434146/Among.Us.Comission.1.tnz.txt)
> 
> This bug has been fixed and is available in the [latest nightly version](https://github.com/opentoonz/opentoonz/releases/tag/nightly). I highly recommend you upgrade to it so you don't run into this again.

Thank you so Much!!! The File is fixed and I updated opentoonz so it wont do it! Thank You!
