### ISSUE TITLE
Hey im trying to start animation and im using OpenToonz ive got this problem where when i put the pen on the screen and start drawing but the line doesn't show up on the screen until i take my pen off the screen then the line shows up its really hard to draw when i cant see where my line is ive tried looking stuff up on youtube and i cant find anything im not sure if its a bug or i pressed something and changed a setting with out knowing but all my other tools work so im so confused why the pen isn't if someone could help me id really appreciate it.

### ISSUE THREAD

**Issue by ShyGuy45** [opentoonz/opentoonz#3569]
**Question**
Ask a question related to OpenToonz.

**Comment by RodneyBaker** [comment]
Perhaps a slightly shorter title would be appropriate.

**Comment by ShyGuy45** [comment]
> Perhaps a slightly shorter title would be appropriate.

Whats the title sorry i dont know much about open toonz im a beginner is it a setting ???

**Comment by RodneyBaker** [comment]
Do you have a friend or family member who can help you?
The problem can be fixed but we need good information in order to help.

**Comment by ShyGuy45** [comment]
![photo](https://user-images.githubusercontent.com/73528307/97572677-8d5d4200-19e0-11eb-999f-ce404a356ac4.jpg)


This is what comes up on my screen and ive tried uninstalling reinstalling nothing changed and dont think my family would know much about this. When i use my mouse pad on my laptop to draw lines it works the line follows the pen fine but i dont use that because you cant get good lines using the mouse pad i dont have this problem on any of my other softwares i can draw fine on the rest of them its just this and its only the pen tool that doesn't work also thank you for your quick replies and help it means a lot @RodneyBaker.

**Comment by manongjohn** [comment]
Do you have multiple monitors?  If you zoom out, do you see your line outside the camera area?

Btw, the title Rodney is referring to is this issue you created. You put the issue in the title instead of the body.

**Comment by ShyGuy45** [comment]
Yes @manongjohn i have my laptop and my animation monitor and no ive had that problem before though and i see now sorry this is my first time using GitHub so i dont 100% know how it works.

**Comment by ShyGuy45** [comment]
Would it help for me to send a video of the problem @RodneyBaker @manongjohn ???

**Comment by manongjohn** [comment]
Since you have multiple monitors, make sure they are using the same resolution, since that can cause the drawings to be significantly offset to where you are drawing.

If matching resolution is not possible or desired, try duplicating the main screen to tablet instead of extending. Alternatively, try making your tablet screen the main monitor.
