### ISSUE TITLE
Broken lines and Rough drawings

### ISSUE THREAD

**Issue by jbtyst** [opentoonz/opentoonz#3573]
Hello,

_**Describe the bug**_
I am using Tahoma2D for traditional animation. So the first thing I do is do a quick sketch to have my rough animation. I create a Smart Raster Level to draw then I start to make circles and Tahoma2D break all my curves. Circles look more like hexagons or polygons than fluid circles. I have tested on other software and this problem is not present so it is not my cintiq or my stylus.

_**To Reproduce**_
List steps to reproduce the behavior.
1. Create a Smart raster level
2. Use the brush tool
3. Make a circle

_**Expected behavior**_
I would like the lines that I draw to remain faithful to the gesture. It is very annoying that the lines are broken and angular. If I draw gently the angles no longer appear but it is not logical and natural to draw this way when it comes to sketches and rough animation.

_**Screenshots**_
![2020-10-29 14_34_43-untitled6_  Mentoranim  _ Tahoma 1 0 1](https://user-images.githubusercontent.com/68372601/97580681-eaaebe80-19f3-11eb-926c-c31a606cc06d.png)

_**Device Information:**_
 - OS: Windows 10 64 bits
- RAM : 16 Go
 - Tahoma2D Version: Tahoma 1.0.1 Built : Sep 3 2020
 - GPU: AMD Ryzen 5 2400G with Radeon Vega Graphics 3,60 GHz
 - GPU Driver Version: I don't know.

_**Others informations**_

I work on a Cintiq 22HD with an other screen (Benq 21'')

Thank you.

**Comment by gelatinbomb** [comment]
I have the same problem with opentoonz 1.4. I tried using windows ink but i didn't got any results.
The problem is not so hard on opentoonz morevna and OTX so i don't know if they fix it or maybe some change in the code is affecting the behavior of the way opentoonz handles the stylus information. 

**Device Information:**

- OS: Windows 10 64 bits
- RAM : 8gb
- GPU: Intel HD 5500
- GPU Driver Version: 20.19.15.5107
- Tablet: XP-Pen Artist Pro 15.6

**Comment by gelatinbomb** [comment]
Ooooh i didn't noticed the year! xD I'm going to try with that nightly release.

**Comment by gelatinbomb** [comment]
It still happens but it doesn't feel that bad. Now this doesn't happen with krita as far know, i never have this issue there. I will see if i send a massage to xp-pen to see if they can give better support for opentoonz. Who knows maybe its something weird with the tablet.

**Comment by gelatinbomb** [comment]
Oh yeah i found this. Its the sdk of xp-pen. I don't know if this could be helpful but maybe it could be a hint to solve the problem at least on my tablet.

https://www.xp-pen.com/developer/index

**Comment by gelatinbomb** [comment]
![2021-03-31 17_22_31-Window](https://user-images.githubusercontent.com/31792239/113223931-81073a80-9247-11eb-85c5-eec55b8fd8ad.png)

Tested last nightly. Still happens. Here you have a comparison. Especially with doing fast curves is where it shows more.
