### ISSUE TITLE
Crashing When Saving

### ISSUE THREAD

**Issue by Coffeewind** [opentoonz/opentoonz#3574]
I have auto save on, and it seems that the program crashes whenever it saves if I have something selected with the selection tool.

**Comment by RodneyBaker** [comment]
This sounds like a problem fixed in current releases.
Recommend trying a current nightly release to ensure use of all the latest updates and fixes.

Nightly releases link:
https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
