### ISSUE TITLE
Keep distance for selected Plastic Tool vertices

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#358]
When you untick Keep Distance option, stretch ability is applied to all vertexes. It will be nice to have option to apply Keep distance only for selected vertices. This way you have better control of which part of the model you want to stretch (for example only arms, legs, etc.)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
Reopening temporarily for as a random selection for routine review.
I have verified the current operation still doesn't allow for the functionality identified in this request.

There are no currently known or published workarounds although users should be able to individually lock vertexes via Function Editor.  For instance, entering an expression in the Distance channel of "=0" should lock that channel in place.  This or something similar could be a mechanism for individually locking some vertexes (keeping their distance) while allowing other vertex distances to move freely.  

The mechanism for this might be that of Right Clicking on the Vertex and choosing a 'Lock Distance' option.  This could at least theoretically also be keyframeable in that frame could either have the token expression applied or not.

**Comment by RodneyBaker** [comment]
I confirm the individual vertex locking approach identified above does work and can be keyframed.
So a vertex length can be free to change in distance in one frame and be locked in place in another.
