### ISSUE TITLE
Weird Pen lag/delay

### ISSUE THREAD

**Issue by Puffb** [opentoonz/opentoonz#3587]
Whenever I draw using my pen in Opentoonz there's this terrible lag/delay that keeps causing straight lines before I can draw anything ![Screenshot (101)_LI](https://user-images.githubusercontent.com/74430827/99118106-e6260080-25c4-11eb-8b1d-55b9fc646faa.jpg) (so for example I draw a circle and there's a second of delay before the line appears and when it does it's a quick straight line while the rest I have control over) sometimes a line won't come out at all and it would just be a dot. I have looked at COUNTLESS forums and videos for help ranging, from turning off windows ink, changing the "view" to "visualize vector as raster", etc and etc. So far nothing has worked, even tested to see if this was a new problem for my tablet itself ( i have a  Huion H610 Pro V2 Graphic Drawing Tablet Android Supported Pen Tablet Tilt Function Battery-Free Stylus 8192 Pen Pressure with 8 Express Keys) so I went to the software I've had for a good while, Photoshop and my lines seem completely fine on that. ![Screenshot (102)](https://user-images.githubusercontent.com/74430827/99118163-0786ec80-25c5-11eb-8243-c2cac447e174.png)
 I even tested in blenders 2d animation software and again it worked fine, so it seems to be a problem within Opentoonz (or something) If anyone can help me, please do because this problem keeps me from drawing straight on Opentoonz

**Comment by konero** [comment]
Go to Wacom settings and turn off double click distance.

![image](https://user-images.githubusercontent.com/19820721/99130439-35415500-2608-11eb-9fa6-b05ad2bae4ad.png)

Type "flicks" in Windows search and open "Turn flicks on or off", disable press and hold.

![image](https://user-images.githubusercontent.com/19820721/99130531-7b96b400-2608-11eb-926e-1c20fe141612.png)

**Comment by Puffb** [comment]
It's still not working, unfortunately.
![Screenshot (109)_LI](https://user-images.githubusercontent.com/74430827/99139795-e5fc2400-2609-11eb-955e-c508031bb5f1.jpg)
![Screenshot (110)](https://user-images.githubusercontent.com/74430827/99139800-eb596e80-2609-11eb-8324-c9d41382b7e0.png)
![Screenshot (111)](https://user-images.githubusercontent.com/74430827/99139802-f01e2280-2609-11eb-9c01-6329a6258e57.png)
I clicked what you told me but I'm still getting this
![Screenshot (112)](https://user-images.githubusercontent.com/74430827/99139811-fca27b00-2609-11eb-990f-1b7aafbce153.png)
And like I said earlier, I can draw just fine in photoshop and blender even before I did this.

**Comment by konero** [comment]
Ah, I just noticed you wrote you use a Huion, my bad. In OpenToonz, you can try toggling this option: Preferences > Touch/Tablet Settings > Enable Windows Ink Support. In the Huion driver, make sure they match, so if you enable it in OpenToonz, enable it in Huion's driver, restart OpenToonz each time.

Otherwise I'm not sure, I only have Wacom stuff.

**Comment by Puffb** [comment]
THANK YOU! It FINALLY works now, I can draw smoothly! Thank you so much!
