### ISSUE TITLE
autorenumber failed after a copy paste in empty cell

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3589]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.create a level with 2 frames
2.copy some drawings from a frame
3.Paste insert in empty cell between the 2 frames

**Expected behavior**
Im expect that autorenumber works like that works usually with autocreation or the insert blank drawing

**Screenshots**
![autorenumber failed after copy paste lnes](https://user-images.githubusercontent.com/29790512/99192496-79049d80-2773-11eb-857c-1d70a8349aa1.gif)

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.
