### ISSUE TITLE
Load as Sub-XSheet crashes

### ISSUE THREAD

**Issue by hippiecool** [opentoonz/opentoonz#3590]
I am using: 
OTX Nov 2020 on Ubuntu 20.04
OT 1.4 latest on Win10

I'm reporting this as per @manongjohn for informing me that this might not be related to <n> keyframe issue #3501, rather an issue with my vector artwork. 

ISSUE: 
I've been experiencing Issues with Load as Sub-Xsheet with scenes that contain many numerous keyframes that indeed were copy/pasted from previous frame rows.  But also have 'common' vector art used across numerous characters.  But might not be related. 

Steps I do:

1. Create a new scene with lots of keyframes that were indeed copy/pasted throughout the scene.  
2. Save as dave1.tnz
3. Create new scene, called master.tnz then in Column1, Cell1, do Load as Sub-Xsheet dave1.tnz. 

RESULTS:
OT and OTX instantly crashes.
Win10 throws an Application Error 1000 pointing to AcLayers.DLL  

In general, it usually will work as expected with scenes who's keyframes were created manually, not copy/pasted. But @manongjohn suggested maybe its my vector artwork instead.  

I did checked all my vector levels by loading all just fine into a new scene.  I also did a 'Replace Level' and 'Remove Unused Levels' with the particular scene I cannot get to Load as Sub-XSheet but did not fix the issue. 

HERE IS HOW I CREATE AND USE VECTOR ART WITH ALL CHARACTERS
All characters are uniquely drawn and their .pli files are in a unique directory.  

+drawings\Dave\Body.pli
+drawings\Dave\Head.pli
+drawings\Dave\BicepL.pli
+drawings\Dave\ForearmL.pli
+drawings\Dave\BicepR.pli
+drawings\Dave\ForearmR.pli
+drawings\Dave\ThighL.pli
+drawings\Dave\ShinL.pli
+drawings\Dave\FootL
+drawings\Dave\ThighR.pli
+drawings\Dave\ShinR.pli
+drawings\Dave\FootR.pli

But all characters have common facial parts (Eyes, Brows, Lids, Mouth) which are in a directory called 'Common_Standard'.  

+drawings\Common_Standard\Eyes\Eyes_Blue.pli    (numerous files for different colors)
+drawings\Common_Standard\Brows\Brows_1.pli    (numerous files for various thickness)
+drawings\Common_Standard\Lids\Lids_1.pli          (numerous files for different colors)
+drawings\Common_Standard\Mouth\Mouth.pli

My reason for this is that it helps with "common" artwork changes that would apply to all characters. 

When I create (dave1.tnz), I Load Levels navigating to each "unique" body part and each "common" facial part (to rig the character).  

RIGGING
All 'unique' parts are 'child' to Body.pli as 'parent'
All 'common' facial parts are 'child' to Head.pli as 'parent' - which is 'child' to Body.pli as its 'parent'.  
So 'unique' parts will get the keyframes, not the 'common' facial part (eyes, brows, lids).   

From here, I can animate a character. 

CREATING A MASTER SCENE TO INCLUDE NUMEROUS CHARACTERS
(NOTE: I do not typically use the Sub-Xsheet to "animate" a character within a Master Scene using Open SubXSheet, Toggle Edit in Palce, Close Sub-XSheet.   I would rather create a unique scene.tnz for each character and Load as Sub-Xsheet into the Master scene.  

My reasoning for this is:
1. If a Master Scene.tnz file gets corrupt, I cannot restore the embedded Sub-XSheets within it. 
2. I re-use previously created scenes (dave1.tnz) as a baseline for a new scene (dave2.tnz or dave3.tnz) and can't successfully Save an embedded Sub-XSheet as a workable .tnz file.
3. If I want to make a change to dave1.tnz, that has been Loaded as SubXSheet into a Master Scene,  I would rather Open dave1.tnz, Save As dave2.tnz and make the changes.  Then completely delete dave1.tnz in the Master Scene and Load as Sub-XSheet dave2.tnz.  Again going to my point of keeping scenes individual in-case of corruption or need to re-use in the overall production workflow. 

SO DOES THIS METHODOLOGY CREATE THE PROBLEM WHEN I CREATE THE MASTER SCENE? 

1. I create dave1.tnz (1000 frames) and jennifer1.tnz (1000 frames) both with unique copy/pasted keyframes. 
2. I create a MasterScene.tnz
 - Load Level +drawings\Sets\Background.pli in Column 1
 - Load Sub-Xsheet dave1.tnz. in Column 2
 - Load Sub-XSheet jennifer1.tnz in Column 3
 - Load Level - dave.wav in Column 4
 - Load Level -jennifer.way in Column 5
 - Render

Crashes occur on Load as Sub-XSheets with .tnz files with numerous keyframes but not too many rows of frames (500).  Ubuntu would crash right away. Windows looks like its working, then crashes. 

But could the 'common' facial parts which are being brought in on each character be causing the issue?  
 
- I **do not** have the Preference: Loading: **Create sub-folder when Importing Sub-xsheet** enabled. I find it creates too many sub-folders which is massive redundancy in the +drawing folder to manage when creating numerous scenes or Episodes.  But even with this Preference enabled, I have experienced crashing on Load as Sub-Xsheet.  

Any input would help?   Is there a log.file I could check to search for a more specific root cause? 

I have attached the particular problem scene.txt below. 
[scene1.tnz.txt](https://github.com/opentoonz/opentoonz/files/5548458/scene1.tnz.txt)

Thank you.

**Comment by manongjohn** [comment]
As I could successfully open your scene directly as well as load in as a sub-xsheet, it's unclear what is causing the problem since I can't replicate the crash.  There might be something going on with other things in the project that is contributing to the issue.

If you are ok with it, can you send me the entire project?  Also let me know the scene to open and which scene to load as a sub-xsheet?  You can click on my avatar to get to my profile where my email is currently visible.

**Comment by hippiecool** [comment]
I wonder if it has to do with a path / sub-directory issue because if you can do these things without my stuff folder, that is the only missing piece from a structure point of view. 

I am wondering if when I initially created the characters, I messed something up.  For example, I created Danny.tnz using  the vector art in +drawings\Danny\  then Save As Laurie.tnz.  Close OT.   I copied and pasted the entire +drawings\Danny\ folder and named +drawings\Jennifer and all its files .pli inside.  Then opened Laurie.tnz and did a Replace Level on all unique parts pointing to the Jennifer folder.  It works as expected.  But I wonder if in the long-run it ruined my baseline Laurie.tnz files and so forth with each other character. 

The entire project is 750MB so maybe best to send you my stuff folder but only with the 3 scenes I am having issues with Load as Sub-XSheet into one Master Scene.  I will email you to take this offline. 

Thanks.

**Comment by hippiecool** [comment]
I am moving this issue to CLOSED.  I have found the root cause and I'm sharing to help anyone who experiences issues like this. 

ISSUE RECAP: For many months, Load as SubXSheet would crash OT and OTX for me.  I also only use Vector art for Levels.  Working with @manongjohn - he was not able to reproduce which made me look closer at my specific Preferences. 

The root cause seems to be when **Preferences: Loading: Column Icon** = At once. (which is default)
**Column Icon:** **must** be flagged as **On Demand**.  (this is specifically what made my Load as Subxsheet work everytime).

![Loading](https://user-images.githubusercontent.com/20970451/99542238-d3724980-297f-11eb-8c72-7fe4dad6e7ad.png)

I was also able to successfully Load as SubXSheet 10 scenes without issue.  I even went back and tried previous scenes I had trouble with before and it worked as expected.  

Not sure if this is OpenGL related or an OT Thumbnail issue using Vector Levels - but at least there is a workaround to get scenes to Load as Sub-Xsheet as expected. 

I hope this helps anyone having a similar issue.
