### ISSUE TITLE
PROBLEMA PARA ABRIR OPENTOONS

### ISSUE THREAD

**Issue by elpanchitodelp** [opentoonz/opentoonz#3594]
THE BUG: initially, the program didn´t open because i didn´t have installed something called "vulkan ddl1". the program itself told me that i could solve this problem by reinstalling the program, so i did it, but it dind´t work and the the same problem was there. so, i installed by myself this component called "vulkan ddl1", and i thought that the problem would be fixed, but when i tried to open it, a new problem apeared. the program said something like "ffmpeg.exe-the entry point is not found", and below of it, it says that the "entry point of the proces vkCreateDescriptorUpdateTemplate in the library of dynamic links.. (and it shows the route where, i think, some things of the program should be) wasn´t found". despite of this opentoons open, and i can use it, but if i try to work with a saved project, the frames that i´ve used are empty, but they appear like they have been covered, like in red color. i don´t know how to solve this, and i´m very worried about it.

Hola, el programa me esta fallando. en un principio porque no andaba el vulkan ddl1, y me el mismo programa me expecificaba que podia resolver este problema reinstalando el programa. hice eso mismo, pero cuando lo trato de abrir me aparece el mismo error, por lo tanto descargo el vulkan ddl1. pensé que asi podría resolver el problema, pero cuando voy a abrir el programa, nuevamente me salta un error que dice que no se encuentra el vkCreateDescriptorUpdateTemplate en la biblioteca de vinculos dinamicos. busque en internet a ver que signifcaba esto, pero no encuentro ninguna solucion. hay alguien que le haya sucedido lo mismo y lo haya solucionado?
aun asi el programa termina abriendo, pero cuando trato de abrir un proyecto guardado, me aparece en la linea de tiempo que los fotogramas fueron cubiertos, pero están en rojo porque no hay dibujos en ellos
![WhatsApp Image 2020-11-18 at 9 22 12 PM](https://user-images.githubusercontent.com/74688770/99617888-060f5700-29ff-11eb-90d1-4faf3c225488.jpeg)

**Comment by RodneyBaker** [comment]
I sounds to me like you need a different (or updated) release of ffmpeg for that particular part of the problem.
I would do that first and then check to see what other problems may still exist.

It also sounds like you have Vulcan enabled GPU which might need to be adjusted as there is nothing that would specifically support Vulcan via Opentoonz.   Perhaps the copy of ffmpeg you downloaded is expressly designed for use with Vulcan?  Not sure.

Please share your system/computer information as that will help others understand what hardware issues might relate to the problem.

**Comment by elpanchitodelp** [comment]
el ffmpeg lo tengo que descargar de alguna pagina en especial de internet?
no estoy seguro de como funciona mi GPU.
Esta es la información de mi computadora: 
![WhatsApp Image 2020-11-23 at 8 01 59 PM](https://user-images.githubusercontent.com/74688770/100025112-e5604c00-2dc6-11eb-9112-34bcdce34926.jpeg)

**Comment by gab3d** [comment]
@elpanchitodelp 
Creo que sería mejor que publicaras tu consulta en el Grupo de OpenToonz en español (lo accedés mismo desde el menú "Ayuda" de la interfaz de OpenToonz).
Este lugar es para reportar errores confirmados del programa (en inglés); no es un foro de ayuda.
Gracias por la comprensión!

**Comment by RodneyBaker** [comment]
Closing as likely reserved and/or abandoned by original reporter.
@elpanchitodelp Please let us know if you continue to experience problems.
