### ISSUE TITLE
Crashing for render/preview in MacOS BigSur

### ISSUE THREAD

**Issue by thvardhan** [opentoonz/opentoonz#3595]
**Describe the bug**
I have a simple scene with a simple cat mesh animation made with plastic tool. it works good in the editor but as soon as I press render/preview or any way to get the video file, opentoonz crashes.

**To Reproduce**
List steps to reproduce the behavior.
1. import an image
2. make mesh and rig using plastic tool
3. create a simple animation (works fine in editor)
4. click render->fast render as MP4 OR render->preview
5. crash.

**Expected behavior**
Video file should've been exported

**Screenshots**
![Nov-19-2020 21-33-47](https://user-images.githubusercontent.com/17314986/99691200-f6e7e200-2aae-11eb-904b-915478b10e47.gif)

**Error log**
https://pastebin.com/UJjS2qKi

**Device Information:**
 - OS: MacOS BigSur 11.0.1
 - OpenToonz Version: nightly build 2020-11-19
 - GPU: Intel Iris Plus Graphics 640 1536 MB
 - GPU Driver Version: Default that ships with OS

**Comment by RodneyBaker** [comment]
I'm curious if you get similar crashing if using the normal Output Settings and rendering to PNG sequence of images.
(Note here that I assume you get a crash when rendering to MP4 via Output Settings too but that would be good to validate too)

P,S.  Cute cat!

**Comment by thvardhan** [comment]
Hi, yeah I was successfully able to output to PNG sequence of images. but as soon as the rendering to PNG finishes, it opens "preview" mode which then crashes the program. I did get a sequence of images though that I can now combine using something else.

**Comment by RodneyBaker** [comment]
The PNG format will (I believe) use FFMPEG for processing if FFMPEG is detected as present.
If FFMPEG isn't detected Opentoonz will process PNGs directly.

As such it might not be the ideal image format to test for this.

Aside:  Part of the process Opentoonz uses to create an MP4 movie file is to first render out to temporary PNG sequence and then convert that PNG sequence to MP4 (erasing the temp PNGs upon successful creation of the MP4 file).  This is an additional reason why I generally wouldn't use PNG as a test format when trying to narrow down specific issues.

But... Glad to hear you got a sequence rendered out.  :)

**Comment by artisteacher** [comment]
I'm getting the same crash on Big Sur when rendering or previewing (cmd+r) a plastic animation. Not an issue on Tahoma2D.

**Comment by thvardhan** [comment]
I just ran the same with .tif output, seems to crash midway. if I use a simple keyframe based animation without any plastic animation then it works fine and I can even get a MP4.

**Comment by RodneyBaker** [comment]
Appears to be same issue as reported in #3576

**Comment by artisteacher** [comment]
I'm no longer getting a crash on Big Sur - when using the latest nightly build. I think the changes to the mac build environment resolved the problem.

**Comment by shun-iwasawa** [comment]
Great! Thank you @artisteacher for testing.
