### ISSUE TITLE
problem installing Nightly's build 

### ISSUE THREAD

**Issue by dumplekin** [opentoonz/opentoonz#360]
hey guys,
 I'm having the same problem with the clean up, because the program either crashes or the image disappear. I've seen people saying that nightly's build work, but unfortunately I can't install it for some reason, because something popped up and said installing this program could put my computer at risk and the only option Microsoft gave me was 'don't run' so I can't install it. I'm really in a stuck and I don't know what to do.

**Comment by tofarley** [comment]
Where it says "don't run" to the left there should be blue text above and to the left that says something like "More info". Clicking that should give you the option to run anyway.

**Comment by dumplekin** [comment]
thank you, Ill try thaat, but to make sure, the link to download it, was it this?
![what](https://cloud.githubusercontent.com/assets/19562205/15529108/90d1ccfe-2218-11e6-9e85-0289b2a22dab.png)

**Comment by turtletooth** [comment]
Yes.  That is what you want.

**Comment by dumplekin** [comment]
i installed
![what](https://cloud.githubusercontent.com/assets/19562205/15551457/1af43d0c-2284-11e6-83f5-c51474bdcdb8.png)
 it, but now im getting this every time i try to run it

**Comment by turtletooth** [comment]
This is the same as #364

**Comment by dumplekin** [comment]
oooh! Yes, sorry

**Comment by tofarley** [comment]
Googling that error, it would appear the most common cause is running a 32bit app on a 64bit system, or vice versa. If you are running the right app on the right architecture, I saw recommendations for reinstalling .NET framework and/or DirectX. I have not tested this, as I have not encountered this problem.

**Comment by dumplekin** [comment]
thank you, but i don't think i want to do that much changes just for one software

**Comment by kogaki** [comment]
This is duplicated issue.
