### ISSUE TITLE
(FFMPEG) Error al abrir el programa

### ISSUE THREAD

**Issue by elpanchitodelp** [opentoonz/opentoonz#3603]
Cuando intento abrir el programa me aparece el cartel que está abajo. cuando cierro este cartel, puedo usar el programa con normalidad, pero a la hora de abrir un proyecto guardado, todo lo que guardé ya no existe, por lo tanto se me hace imposible trabajar con el programa. No sé que hacer, necesito una solución, no soy bueno con la tecnología, quiero una respuesta con la solución y nada más. estoy desesperado, no quiero volver a usar el pencil2d.
tambien agrego las especificaciones de mi computadora.
![especificaciones de la compu](https://user-images.githubusercontent.com/74688770/100267271-f083bb00-2f31-11eb-8eaa-ea9c548cfbdc.jpeg)

![error programa](https://user-images.githubusercontent.com/74688770/100267241-e661bc80-2f31-11eb-9f8c-fd3557c30583.jpeg)

**Comment by RodneyBaker** [comment]
@elpanchitodelp could use some assistance with someone that can speak the same language.
Thanks in advance!

**Comment by RodneyBaker** [comment]
Closing as an apparent duplicate of #3594.
