### ISSUE TITLE
Dumb simple building with cmake

### ISSUE THREAD

**Issue by kalemas** [opentoonz/opentoonz#3605]
Hi all. I had a pleasure to setup cmake's ExternalProject feature in my own single project recently, so i thought that it would be great to have OpenToonz initial build as simple as `cmake . && cmake --build .`.

I want debug build to debug frequent crashes. I know i would make a PR so i just starting this topic to be in subject and maybe i will find time to prepare PR.

**Comment by RodneyBaker** [comment]
@kalemas Have you had any success with your effort to simplify cmake builds?
Curious minds want to know.

**Comment by RodneyBaker** [comment]
Will close as this is reaching its 4 year anniversary.
