### ISSUE TITLE
Display issues after created blank drawings on reframe  commands

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3610]
**Describe the bug**
There is a display an issue when we create blank drawings after used the reframes commands. No icon display is shown and inbetween command not displayed.

**To Reproduce**
List steps to reproduce the behavior.
1.select some frames and use reframe on or reframe with empty inbetweens command
2.transform the news frames as blank drawings

**Expected behavior**

**Screenshots**

![Reframe issues](https://user-images.githubusercontent.com/29790512/100514429-e998ba80-3174-11eb-81d8-3878335d784b.gif)
**Device Information:**
 - OS: [windows 10]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by beeheemooth** [comment]
#3208

**Comment by openanim** [comment]
Close as duplicate.
