### ISSUE TITLE
(Discussion) Jumping to the first frame after cutting a frame in the Level Strip

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3612]
**Describe the bug**
When you cut a frame from the Level Strip, it jumps to the first frame. If you have few frames it is not noticeable. But if you have a lot of them, then this is very inconvenient, since you constantly need to scroll to the very last frame.

**Expected behavior**
After cutting the frame (in Level Strip), it would be more logical for the jump to occur to the previous frame (if any).

**Screenshots**
![ezgif-7-8dc9363db2b7](https://user-images.githubusercontent.com/25724133/100735288-a4c18d80-33d9-11eb-885d-c24f612049c1.gif)

(I don't know which shortcut is more appropriate: "bug" or "feature request" for this issue. In my opinion, this is a bug.)

**Device Information:**
 - OS: [e.g. Windows] 8.1
 - OpenToonz Version: latest Nightly

**Comment by RodneyBaker** [comment]
It does seem logical that after the removal of a level strip frame the focus would shift to the previous frame rather than the first.
Tagging this as a feature request and changing the title to allow for some discussion on how best to proceed.

**Comment by beeheemooth** [comment]
Discussion? Does anyone need this kind of frame behavior in the Level Strip? Please describe a workflow where it would be helpful. I was hesitant about which label to specify (bug or feature) to fix this problem, but I definitely think it's a bug.

**Comment by artisteacher** [comment]
I don't see the benefit to the current behavior. I'd rather have the active frame switch to the previous or next frame instead of the first.

**Comment by shun-iwasawa** [comment]
For now [OT selects the first frame after cutting frames](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/filmstripselection.cpp#L243-L244) which causes scrolling of the Level Strip.
I agree that this behavior is not helpful. I'll look into this.
