### ISSUE TITLE
Program not opening anymore

### ISSUE THREAD

**Issue by JTheSpyder** [opentoonz/opentoonz#3615]
I have worked much with Opentoonz the past months and today suddenly it doesnt open anymore. After "Creating Main Window" just nothing happens...no error or anything. I've seen similar problems but they didnt really compare to mine. I tried reinstalling several times, but no matter where I install, it just doesnt open anymore

**Device Information:**
 - OS: Windows
 - OpenToonz Version: 1.4
 - GPU: Nvidia Geforce GTX 1060
 - GPU Driver Version: 27.21.14.5751

**Comment by RodneyBaker** [comment]
Is there any way your antivirus program might be terminating the launch of the program?
Several reports have been raised related to overly aggressive antivirus interfering with programs... especially if unsigned... and in the case of Opentoonz even preventing launch (in worst case) and causing significant delay in writing to disk in other cases.

**Comment by JTheSpyder** [comment]
> Is there any way your antivirus program might be terminating the launch of the program?
> Several reports have been raised related to overly aggressive antivirus interfering with programs... especially if unsigned... and in the case of Opentoonz even preventing launch (in worst case) and causing significant delay in writing to disk in other cases.

Yeah thats what I read in other Issues...I've tried changing the Firewall settings for it but it didnt work....I had Avast installed but never used it so I deinstalled it now...Can Windows defender be a problem? And why would my antivirus programm just now cause problems with OpenToonz, when everything still worked fine this morning?

**Comment by RodneyBaker** [comment]
Something obviously changed and an update of operating system or application (such as antivirus) is good to rule out.

Yes, Windows Defender can be overly aggressive too although in my experience not like Avast and other antivirus programs that tend to default to stricter protocols.

I don't know if Opentoonz does this but some programs don't load defaults if the application is run with the Shift key held down.   You might try this with Opentoonz so that any troublesome settings might be ignored.
Opentoonz doesn't load a project by default so it doesn't appear that a corrupted project file is causing the problem although... the startup popup does have to prep the list of recent projects to display to the user.

If you recall one of the the last things you were working on that might suggest something that got corrupted... such as adding a plugin...

If you are using the Opentoonz release linked from the Opentoonz website I will also recommend updating to the latest nightly release.  You don't mention which release you've been installing/reinstalling so at least that would give us that foundation to start from.   Here's the link to the nightlies:  https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by JTheSpyder** [comment]
Okay so I tried that thing with holding shift down...didnt work....I also didnt install any plugins that might have corrupted the program. I forgot to say that before I wrote this I tried opening the latest nightly release but got the same problem. I actually found some more avast elements via explorer search, most of them being in roaming and local which I couldnt uninstall but one file made me curious because it was called "avast!sandbox" and it really turned out to have a folder with something opentoonz related in it....I deleted those files but its still not working...at this point I just dont know what to do anymore....cant it be that some of the files, that are regularly installed to program files in c: or something are corrupted and I have to delete them??? If yes, how do I find these??? If nothing else works I guess i'll have to try downloading the 1.3 version because I've had this whole Issue half a year ago when I updated from 1.3 to 1.4....back then it somehow worked out randomly when I tried installing it again

**Comment by manongjohn** [comment]
I would try the following

1. After it fails to open, open the Windows Event Viewer and look under `Windows Logs` -> `Application` for an Error log with OpenToonz mentioned in it.  There is a small chance It might explain what is going on.

2. Try running OpenToonz as Administrator.  If that works, then look at the next option as a possible issue.

3. I would look at the security settings on the `OpenToonz stuff` folder (Properties -> Security tab).  Under the Group or user names, make sure you see your login/account in the list and it has full access to the folder.  If not, add the login and/or change permissions to full control.

**Comment by JTheSpyder** [comment]
> I would try the following
> 
> 1. After it fails to open, open the Windows Event Viewer and look under `Windows Logs` -> `Application` for an Error log with OpenToonz mentioned in it.  There is a small chance It might explain what is going on.
> 2. Try running OpenToonz as Administrator.  If that works, then look at the next option as a possible issue.
> 3. I would look at the security settings on the `OpenToonz stuff` folder (Properties -> Security tab).  Under the Group or user names, make sure you see your login/account in the list and it has full access to the folder.  If not, add the login and/or change permissions to full control.

I tried your first option and to my surprise it actually shows an application error followed by a windows error everytime I click  Opentoonz!! It showed an error in a module called "EDSDK.dll" I've linked a picture of the apllication error, but its in german. You might still be able to find something out with it!
![Fehler Opentoonz](https://user-images.githubusercontent.com/70415548/100936647-2dcbe800-34f2-11eb-8d9a-c03be6477a30.png)

**Comment by manongjohn** [comment]
Do you have any Canon software installed?    There is an issue opening OT when certain Canon product software is running in the background and using EDSDK.dll.  I'm guessing it's trying to load the EDSDK.dll twice or something and fails.

If you have some other Canon software running in the background as a service or something, shut it off and see if OT will open afterwards.

**Comment by JTheSpyder** [comment]
Oh my god!! I actually did! Just today I opened EOS Utility after a long time to import photos from my camera! It actually still ran in Task Manager and I deactivated it on Autostart. When I started OpenToonz it asked me for Firewall Access again, and opened! Thank you soo much! I could imagine that I had the same problem half a year ago

**Comment by manongjohn** [comment]
Glad we figured it out. I am going to close this as there is already an open issue for OT not opening when Canon EOS is running in the background.
