### ISSUE TITLE
Pegs and xSheet

### ISSUE THREAD

**Issue by papio-pl** [opentoonz/opentoonz#362]
Is there a way to view pegs in xSheet? It would be great to see both Peg-keyframes and Graphic-keyframes in one timeline. The only place where I find Peg-keyframes is "Function editor" which is pretty hard to control.

If the Pegs would be visible in timeline/xSheet it would be nice to have some kind of filter to for example fold all graphics columns and see only Pegs.

One more thing with Pegbars. To keep things more organized I would like to see different color of pivot center in comboviewer for Pegbar, and different for Graphic column. Sometimes you set keyframes for animation, and in the end you notice that you set keframes in wrong place;)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
