### ISSUE TITLE
My Opentoonz audio is only importing as one frame.

### ISSUE THREAD

**Issue by MaxGure** [opentoonz/opentoonz#3620]
![opentoonz glitch](https://user-images.githubusercontent.com/75632906/101380770-c6ec5d00-386a-11eb-8d28-989047ef55c3.png)

I tried to drag and drop my .wav file into the timeline and into the drawing interface, but it still just imported as a single frame even when I did Import or Load. I also tried to go to File > Import > Toonz Lipsync File (Toonz Lipsync file was the only option) and it did not work either. Any help?
Thanks!

**Comment by MaxGure** [comment]
I'm pretty sure I have version 1.4, that's what shows up when I go to Help > About Opentoonz

**Comment by MaxGure** [comment]
Actually, never mind, I fixed the issue. All I had to do was export the file from Audacity as a 16 bit wav file instead of 32 bit.

**Comment by artisteacher** [comment]
Yeah, 32bit audio files are not supported.
