### ISSUE TITLE
Saved scenes are empty

### ISSUE THREAD

**Issue by EmiEmoEmi** [opentoonz/opentoonz#3621]
**Describe the bug*
I've had some saved scenes ,but when I'm opening them ,frames numbers are red ,and frames don't have any content. Even If I saved the scene before. I was saving my project to not loose it if program crashes.

**To Reproduce**
Well.. It not happens every time when I'm doing these things ,but I'll write here what I've done.
1.I saved my project
2.I was working on it for a while.
3.I was searching to change color (in pltedit changing kolor makes whole drawing in the same color) So i saw "line processing" window ,and I tried to change it from greyscale to color. And then program crashed. I've opened program again and i pick my project to load.
When it loaded ,nothing was in there. All drawings have vanished.

**Expected behavior**
Frames should have some content.

**Screenshots**
![screen z toonza](https://user-images.githubusercontent.com/64745175/101487106-f92ab700-395d-11eb-8ff3-72ea73fdc7d8.png)

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment]
> OpenToonz Version: [e.g. Nightly (2020-01-10)]

I suspect you are not in fact using the nightly release from January 10 2020.
Before investigating much further... recommend downloading and installing the latest nightly release (releasesd a few days ago as of the time of this reply).

Here's the link:  https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by EmiEmoEmi** [comment]
I dowloaded this program *3 days* ago (from the offical site),so I think I already have the latest version. And I can't download it from your link ,bacause windows blocks it because : 
"Running this application may put your computer at risk."

**Comment by konero** [comment]
Are you using **Save Scene** command? If you use that, the level data won't save to disk (levels are individual files on disk). For that to happen, you need to use the **Save All** command, or **Levels > Save All Levels**.

> Running this application may put your computer at risk.

It's safe, just click **Run Anyway**.

**Comment by EmiEmoEmi** [comment]
OK thanks! As I understand ,there's no way to recover my projects?

**Comment by DarrenTAnims** [comment]
The program from the site is almost a year old. They've not updated that version since the start of 2020, so if you follow that link, you'll get the latest version of OpenToonz and it will be more stable, with 1 years worth of bug fixes in it.

If you've used Save Scene instead of Save All, then no. You've not saved your drawings. However, when you exited the program it will have prompted you to save unsaved changes. Do you remember if it asked you that?

**Comment by artisteacher** [comment]
If you did actually save the levels at some point, there could be backup files.  In Tahoma, levels are usually stored in the project's Drawings and Extras folders. If you look in those folders through File Explorer/Finder (or etc.), you can see any backup files. They will have .bak at the end of the name. If you rename the backup levels to remove .bak from the name, you can load them back in Tahoma.

**Comment by RodneyBaker** [comment]
Closing as part of regular housekeeping.
@EmiEmoEmi Please let us know if you experience additional issues.
