### ISSUE TITLE
"Savel level as" failed after a cleanup conversion

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3634]
**Describe the bug**
After a raster level cleanup if using save levels as command, levels turn to red and save fails. It seems that affect only the rasters levels made in OT, from outside OT that seems to work as expected.

**To Reproduce**
List steps to reproduce the behavior.
1.from a raster level made inside OT
2.use cleanup command
3.use save levels as

**Expected behavior**
No save failed

**Screenshots**

**Device Information:**
- w10
- OpenToonz Version: [nov 15 2020]

**Comment by shun-iwasawa** [comment]
@openanim 
I couldn't reproduce the problem with the current nightly build. Can you please check if it still occurs at your end?

**Comment by openanim** [comment]
@shun-iwasawa, i tried with one of the last NB and it looks like the problem is still there in my environment.
![Save level as_issue](https://user-images.githubusercontent.com/29790512/111846177-8ccd3580-8906-11eb-8574-8dea264b3846.gif)

**Comment by shun-iwasawa** [comment]
Thanks, now I could reproduce the problem.
It was needed to create the raster level via brush tool's auto creation, not via new level command.
