### ISSUE TITLE
Requested adjustments from Tahoma2D

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3637]
X-Sheet Level Parenting.
![image](https://user-images.githubusercontent.com/74626650/102279078-11637e80-3ee8-11eb-985b-2f2c5a276a02.png)

Displayed TimeLine Effects Icons.
![image](https://user-images.githubusercontent.com/74626650/102279142-2b04c600-3ee8-11eb-81bf-907fbc07783e.png)

Diamond Keys  to match the ui icons design.
![image](https://user-images.githubusercontent.com/74626650/102279270-57204700-3ee8-11eb-87e4-dfb1ddc4ac19.png)

All of these changes are all available and can be ported from Tahoma2D.?????
I believe these Adjustments would be  Great for OpenToonz 1.5

Links
https://github.com/tahoma2d/tahoma2d/pull/68
https://github.com/tahoma2d/tahoma2d/pull/275
https://github.com/tahoma2d/tahoma2d/pull/288
https://github.com/tahoma2d/tahoma2d/pull/130
https://github.com/tahoma2d/tahoma2d/

**Comment by JPUser1** [comment]
I think these are nice Adjustments and only need someone to port it.

**Comment by JPUser1** [comment]
@shun-iwasawa Please consider some of these Adjustments for OpenToonz 1.5

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information contained in this report and where appropriate that information should be transferred to a new report.

Note that portions of this request may have been implemented.
