### ISSUE TITLE
I have no idea what to do right now...

### ISSUE THREAD

**Issue by jackspediceyfan** [opentoonz/opentoonz#3639]
So what happened was I was just using OpenToonz and everything just broke. I have no canvas, no color creator, no nothing. Please help me.

**Comment by gab3d** [comment]
@jackspediceyfan 
Please be aware that this is not a user forum, but a bug reporting site.
So, if you think what is happening to you is a bug, please give as much data as possible about the system you're on, and directions on how to reproduce your problem.

On the other hand, you can also post your message in the Community Forum you can access via the Help menu of OpenToonz; so perhaps there other users that had gone through the same as you can give useful hints on how to resolve your situation.

Thanks!

**Comment by RodneyBaker** [comment]
@
