### ISSUE TITLE
Bug - Nightly build 57d083b and onwards all crash at startup (Windows)

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#364]
I get this when starting all the nightly builds from  57d083b onwards.

![crash](https://cloud.githubusercontent.com/assets/18170954/15542990/53f114cc-2293-11e6-9e79-7037eb9cc622.png)

I am running windows 10.

**Comment by Rayek** [comment]
Confirmed. Windows 7 64bit Pro. I tried re-installing OpenTOonz, but still the same error.

**Comment by psychoanima** [comment]
Go to **C:\Program Files\OpenToonz 1.0\srv\** and locate t32bitsrv.exe Delete that file and start OpenToonz. It should work until someone fix it in code.

**Comment by BrundleThwaite** [comment]
@psychoanima - Thanks. but please remember to tell everyone that this will disable .mov as a rendering option. A lot of people get stressed by not having it.

It does not bother me as I only render out as frames. I also think that .mov should die as a format (along with .mp3 and .jpg). Although not liking .mov is more involved with the politics of the format and its lack of development than the others which are obsolete and poor formats for artists to be using.

Either way it is best for the devs to have me say which version the bug started with.

personally I would not mind to seeing .mov dumped and Matroska added instead but that would be a more technical request than I want to log at the moment.

**Comment by psychoanima** [comment]
@BrundleThwaite quicktime for windows users is dead anyway. 

> Apple has confirmed it will no longer issue updates or patch security holes for the PC version of its multimedia software, meaning those who continue to use the software do so at their own risk .

**Comment by BrundleThwaite** [comment]
The .mov format has not been properly updated for years on any format. It actualy makes .avi seem modern which is a joke. A lot of applications took 5 or six years longer than they should have to become 64Bit because of quicktime integration.

It is also the main reason Final Cut was never turned into a 64Bit application (Final Cut Pro X does not count because it is a new application).

I'll stop here I could go on about this for ages, as I said there is a lot of politics about .mov which would all have been considered unacceptable ( for a format that was supposed to be the industry standard ) if it had been developed by someone other than Apple.

As I have said I would like to see open formats like Matroska promoted instead (Although it is also possible for them to stagnate).

**Comment by dumplekin** [comment]
does your clean up crash when using the build? Mine does unfortunately

**Comment by BrundleThwaite** [comment]
Sorry I can't check properly. firstly my scanner does not work with OpenToonz and secondly I am really only working digitally at the moment. I have played around with the cleanup settings and they are not crashing but I am not really using them in context

**Comment by kogaki** [comment]
#390 has fixed this issue. Thank you for your report

**Comment by BrundleThwaite** [comment]
Awesome, Thanks for all the hard work.
