### ISSUE TITLE
Randomly Deleted/Altered Frames

### ISSUE THREAD

**Issue by JPJammin** [opentoonz/opentoonz#3649]
**Describe the bug**
 As I work, when I periodically play back my animation, sometimes are missing. Unbeknown to me, frames had seemingly been deleted, and don't appear in my X-sheet anymore. In the thumbnails, the missing frame has turned red and says "no icon". This keeps happening periodically, and at one time, frames that were separate becomes merged with one image over the other. I've just been dealing with it.

**To Reproduce**
I have no idea how to reproduce it. I've just been working and frames disappear. Admittedly, I'm new to Opentoonz. I've been saving my scenes to a folder on my computer, and opening new scenes [rather than projects] anytime I want to start a new animation. I don't know if that creates any issues.

**Screenshots**
<img width="409" alt="Screen Shot 2020-12-21 at 10 46 37 AM" src="https://user-images.githubusercontent.com/76447467/102808624-93dbba80-438e-11eb-9bce-c36ec61bb057.png">
<img width="1134" alt="Screen Shot 2020-12-21 at 10 47 08 AM" src="https://user-images.githubusercontent.com/76447467/102808626-950ce780-438e-11eb-91c4-c0042be139c5.png">

**Device Information:**
 - OS: Mac OS High Sierra
 - OpenToonz Version: 1.4

**Comment by artisteacher** [comment]
The undo history can sometimes be a little wonky. Is it possible that you undid a couple steps, and didn't realize that you undid creating a drawing?

**Comment by JPJammin** [comment]
Thank you for the reply. I don't think that would make sense in this case. In the above example, the frame deleted was a key I had made hours ago. I had been inbetweening for quite some time by the time it deleted and played the animation back multiple times with the frame there.

**Comment by RodneyBaker** [comment]
@JPJammin Keep in mind that a 'project' with Opentoonz is a directory structure so moving things out of a directory/folder can lead to loss of a referenced file.  That could be the cause of missing frame although that shouldn't necessarily relate to any undo action short of undoing to the point where a reference points to a different location.

In other words, think of projects as directories on your harddrive and that will help in maintaining a solid workflow.
Files can be located outside of those directories but in those cases the chance of a broken link to a resource increases.

This project element of Opentoonz is one of the harder things to get use to when working with Opentoonz but ultimately works out to be a great timesaver and project management workflow.

**Comment by DarrenTAnims** [comment]
The undo issues are time independant. Once it goes wrong, when you press undo, it seems it can undo any step made during that session. Once you realised the undo has gone wrong. I'd suggest to save and restart immediately.

**Comment by JPJammin** [comment]
Thank you all so much for the replies! It sounds like my best bet right now is to keep things in the directory and restart if things are behaving strangely. I'm still very new to the program, so It's all taking some getting used to. Please don't hesitate if anyone else has any other tips or advice!

**Comment by RodneyBaker** [comment]
I'm tagging this as a bug although it isn't clear exactly what the bug is at this time.

**Comment by RodneyBaker** [comment]
@JPJammin Closing this as part of routine housekeeping.
Hopefully you haven't ran into this problem again but if you have please let us know.
