### ISSUE TITLE
So I installed the nightly's build but now im getting error when trying to run it

### ISSUE THREAD

**Issue by dumplekin** [opentoonz/opentoonz#365]
![what](https://cloud.githubusercontent.com/assets/19562205/15551491/3e484d48-2284-11e6-82fb-72e81da3039f.png)

**Comment by turtletooth** [comment]
This is the same as #364- can they be merged?

**Comment by dumplekin** [comment]
merge?

**Comment by dumplekin** [comment]
oooh! Yes, sorry

**Comment by psychoanima** [comment]
Go to **C:\Program Files\OpenToonz 1.0\srv\**  and locate t32bitsrv.exe Delete that file and start OpenToonz. It should work until someone fix that in code.

**Comment by dumplekin** [comment]
Oh okay, thank you it, works now, but man, after solving one problem there's another, so it still crash when I try to clean it up :/

**Comment by kogaki** [comment]
This is duplicated issue.
