### ISSUE TITLE
Cannot open menubar settings template file. Re-installing Toonz will sorve the problem

### ISSUE THREAD

**Issue by cpcbegin** [opentoonz/opentoonz#3656]
**Describe the bug**
I compile opentoonz in Ubuntu 20.04 follow all your instructions but I run the software I get this error 7 times before start the sofware:
`Cannot open menubar settings template file. Re-installing Toonz will sorve the problem`

**To Reproduce**
List steps to reproduce the behavior.
1. Compile the software in Ubuntu Mate 20.04 following all your instructions
2. Change to /opt/opentoonz/bin path
3. Run ./opentoonz

**Expected behavior**

**Screenshots**
![bug_open_toonz](https://user-images.githubusercontent.com/10259216/103112483-fa462e80-4655-11eb-9589-6c019e6dc3b4.png)

**Device Information:**
 - OS: Ubuntu Mate 20.04
 - OpenToonz Version: 1.4 (Build Dec 25 2020 00:58.17)
 - GPU: NVIDIA Corporation GF119 [GeForce GT 610] (rev a1)
 - GPU Driver Version: 390.138

**Comment by wellingjin** [comment]
I have the same problem，mac OS

**Comment by cbrherms** [comment]
Have just had a report of this myself on Windows.
Windows 10 22H2, Opentoonz version 1.7.1

**Comment by RodneyBaker** [comment]
You are building your own release of Opentoonz?

**Comment by cbrherms** [comment]
Nay, was latest prebuilt installer from releases page.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@cpcbegin Please let us know if you are still experiencing problems.
