### ISSUE TITLE
Same view between Xsheet and Level strip

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3658]
**Is your feature request related to a problem? Please describe**

Request for an option in the preferences so that the levels from the Xsheet and the Level strip share the same view.

Personally, I really like to use the level strip to isolate part of a drawing to zooming in/out according my needs.

But, one aspect that I find very frustrating is to always reorient the views between Xsheet and level strip. after that.

The same optional view would be really great  without rectify the canvas view each time for every frame.

**Describe the solution you'd like**
A preference option to share same view between Xsheet and level strip on the viewer window.

**Comment by RodneyBaker** [comment]
Closing as the originator of the report has ghosted themselves.
As a feature request it may be appropriate to transfer this report to Opentoonz-docs for appropriate consideration.
