### ISSUE TITLE
Crash when deleting a node from Stage Schematic.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3659]
**To Reproduce**
1. Create a new level.
2. In Stage Schematic, select the column node and delete it.
3. Crash
**Screenshots**
![ezgif-7-f35303f6d87c](https://user-images.githubusercontent.com/25724133/103149836-0e814d00-4776-11eb-85eb-b1763ed1431f.gif)

**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: latest Nightly

**Comment by RodneyBaker** [comment]
Crash on confirmed on Windows 10.

**Comment by beeheemooth** [comment]
Hmm, by the way, this crash is absent in Tahoma.

**Comment by shun-iwasawa** [comment]
@beeheemooth 
Yes, because the crash had been related to the feature not (yet) included in Tahoma2D.
Since the feature (#3375) is experimental, it is disabled by default in the preferences.
I forgot to include necessary checks of the option in some functions and caused the crash.
