### ISSUE TITLE
Text editor do not support right to left languages

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#366]
In the picture you can see that the Persian (Farsi) sentence,
(اسرار ازل را نه تو دانی و نه من)
is written left to right and broken.

![Opentoonz right to left languages](http://s6.picofile.com/file/8252995768/Opentoonz_RTL.jpg)

**Comment by walkerka** [comment]
It needs to integrate Harfbuzz or ICU text shaping library. Not an easy task.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
