### ISSUE TITLE
Having separate preference for Multitouch Gesture option (requesting simultaneous gesture of pan,zoom and rotation)  

### ISSUE THREAD

**Issue by mercuriousreign** [opentoonz/opentoonz#3661]
Hello, 
Is it possible to have a separate option so that the multitouch gesture is able to do action of rotation+zoom+pan simultaneously rather than doing things one at a time?

I understand that looking through past commits of https://github.com/opentoonz/opentoonz/pull/1437
it was decided to have multi gesture do their action one at a time to prevent leaf like movement.

However for me I would vastly prefer if it is in the other way similar to the apps like Krita, Leonardo and Concepts.

I would be immensely grateful if two separate option is there, if this is impossible then that is fine too.

Sorry for the trouble.

Thanks.

**Comment by texorama** [comment]
YES! This is very much how e.g. almost all apps on the iPad work these days, for drawing, viewing photos, animating... Very intuitive, you just use two fingers and then do whatever transformation you want with them, pan, zoom, rotate.

**Comment by RodneyBaker** [comment]
I'm curious how what is suggested here isn't working as desired when touch is turned on in preferences:

![image](https://user-images.githubusercontent.com/2576432/154864883-2ba76479-2f32-4951-a5a9-8b24e23f0222.png)

I ask because... I can currently pan, zoom/scale and rotate with two fingers simultaneously now on my touch monitor.

**Comment by mercuriousreign** [comment]
Hi, 
Sorry that I was not clear in my writing. As you have said, Opentoonz does have touch gesture controls, but it is sort of different from other apps, its hard to describe it in detail without comparison. 

Using Krita as comparison, I think that drawing software allows you to zoom, pan, rotate simultaneously while Opentoonz only allows one gesture at a time.

I have attached video showing both of their touch gesture (Krita 5.0.1 & Opentoonz 1.5.0), I don’t know if things are different now in new released or in the night build. This thread was originally made in December 2020.

Krita : [https://imgur.com/a/j3HP1nn](url)
Opentoonz : [https://imgur.com/HTix8OZ](url)

 At the end of the day, what Opentoonz have is alright as well. As I understand. It seems Opentoonz userbase does not prefer the touch gesture in Krita because it gives them hand cramps. I wanted both of the style of gesture to co exist in my original post.

You guys can close this issue.

**Comment by artisteacher** [comment]
I don't think it was ever about hand cramps - it's that at the start touch gestures were too unreliable.  It was way too easy to accidentally trigger the wrong gesture. If all you want is to zoom, it's super annoying to have panning or rotation triggered instead of or in addition to zooming. There's certainly still room for improvement though.

**Comment by RodneyBaker** [comment]
> There's certainly still room for improvement though.

Always!

Touch is one of those things... hardware things... that development always considers especially as technology advances and hardware improves.

Something that would be good to do in the 2022 development cycle is survey what options are available to not only add more simultanuity but also improve other aspects of touch integration too.

Will close but... by all means please revisit and add additional commentary as desired.
The ideas of users is what helps chart the future of the software.
