### ISSUE TITLE
Why are my imported images blurry?

### ISSUE THREAD

**Issue by Yogi861** [opentoonz/opentoonz#3667]
When I import an image it is always some-what blurry. I tried increasing the DPI and I tried rendering but it didn't help. Does anyone know how I can fix this?

The imported files are PNG. 

Thank you to anyone who answers!

**Comment by RodneyBaker** [comment]
Can you share a sample PNG image that you are using and perhaps a screen grab of what the blurred image looks like?

**Comment by Yogi861** [comment]
This is one of the images

![Mark IV Male 300 DPI](https://user-images.githubusercontent.com/67271571/103461863-1585fd80-4d2a-11eb-8705-491fc1895669.png)


And this is how it looks blurry upon import

![Blurry Import](https://user-images.githubusercontent.com/67271571/103461885-41a17e80-4d2a-11eb-8c85-b8704f7761d9.png)

**Comment by RodneyBaker** [comment]
Aha!  What you have there is antialiasing; where an attempt to make the image look 'smoother' is applied by averaging pixels.
This is one reason why you might want to go with vector images rather than raster.
We can try to troubleshoot the issue more but I converted your raster image into a vector image so you could see what difference that makes.

Note that I had to put it in a zip file because Github doesn't accept the .PLI format as an attachment.

[tankship.zip](https://github.com/opentoonz/opentoonz/files/5760627/tankship.zip)

**Comment by Yogi861** [comment]
I am unable to open PLI files. How were you able to convert it? When I tried converting it through opentoonz it completely messed up the details on the tank.

**Comment by RodneyBaker** [comment]
Pli files are the vector image format for Opentoonz.
Either use the menus/browser to open the file or drag/drop it into Opentoonz.

Converting is something of an art that takes a little time to master.
The first suggestion I would make would be to change the setting from centerline to outline...

**Comment by Yogi861** [comment]
Is there a way to import an image as a vector to avoid this problem? Maybe I can export the original ai. file (I drew it on adobe illustrator) as a different file than I did (PNG)?

**Comment by RodneyBaker** [comment]
Unfortunately, Opentoonz won't recognize the .AI format but...
You could export as SVG and... if all the options are set optimally... possibly achieve a reasonable conversion to PLI inside of Opentoonz.  The problem there is that there are a few problems with that process of SVG conversion that need to be fixed for it to work optimally.

If you can share the .AI exported from illustrator I can give it a look and make suggestions.

To convert an SVG you can either drag/drop the SVG into Opentoonz... which will initiate the conversion to .PLI or... use Opentoonz's browser dialogue to Right Click and convert from SVG to PLI (This latter option allowing you to at least see what options are available (i.e. not many).

SVG is really the only vector option we have at the moment for importing vector images from other programs.

**Comment by artisteacher** [comment]
Does the image look blurry when the Viewer is at 100%? The image you shared looks expected for something that is zoomed in a lot.

**Comment by Yogi861** [comment]
Well seems github doesn't support ai. files I tried exporting as SVG and it just gave me a weird black shape in the shape of the outline and another in the outline of the details

**Comment by Yogi861** [comment]
> Does the image look blurry when the Viewer is at 100%? The image you shared looks expected for something that is zoomed in a lot.

Yes it  was zoomed in a lot but when I zoom in on the original file it doesn't have this issue

**Comment by DarrenTAnims** [comment]
What you're seeing there is anti-aliasing and for some reason, this is added when you import the image. I don't know why. And I don't know how to get rid of it. Most of the time you don't notice it. And as Yogi has said, when showing at 100%, which is the size that most of your audience will see your animation at, it will look fine. (Note, a large portion may also see it smaller, but none will zoom in). So unless someone knows how to import an image without OpenToonz adding this anti-aliasing, I wouldn't worry about it.

**Comment by RodneyBaker** [comment]
Closing this as a question asked and answered.
Please feel free to continue the discussion as necessary though here in this report.
