### ISSUE TITLE
Custom rooms not saving

### ISSUE THREAD

**Issue by krookxd** [opentoonz/opentoonz#3668]
One day I opened opentoonz to finish an animation I was previously working on. I noticed that the custom room I was using was gone and when I tried to open the animation and got a warning message that said some files may be missing , I clicked ok and as I thought the whole animation was missing. Left my computer alone for some days and when I came back I remade my custom room and closed the application but when Reopened the room would be gone again. I have tried it several times since then and my custom room still does not save.

**Screenshots of the warning**
![2021-01-04](https://user-images.githubusercontent.com/76963246/103561784-6879c500-4e90-11eb-899f-908a860008f5.png)

![2021-01-04 (1)](https://user-images.githubusercontent.com/76963246/103561829-82b3a300-4e90-11eb-8cf4-f6bf201e472a.png)

My Device Information:
 - OS: Windows 10
 - OpenToonz Version: 1.4
 - GPU: Intel(R) UHD Graphics 605

**Comment by RodneyBaker** [comment]
The release you are using is the likely cause of the problem (of which there appears to be two).
Can you confirm the problem still exists using the latest nightly release?
That should contain the fixes required.

Link to latest nightly release:  https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_fea3b63487f2f339b3cbcfa90776a59ec7d392c3

Aside:  The (pending) v1.5 release should be very similar to the latest nightly release.
Expect to see that in February.

**Comment by RodneyBaker** [comment]
@krookxd Where you able to discover how to save your custom rooms?

**Comment by krookxd** [comment]
sorry for the late reply i was ale to fix the problem thank you for the help
