### ISSUE TITLE
Crashing when clicking on the X-Sheet.

### ISSUE THREAD

**Issue by amadlover** [opentoonz/opentoonz#3669]
**Describe the bug**

Attached Stuff folder [OpenToonz stuff.zip](https://github.com/opentoonz/opentoonz/files/5776624/OpenToonz.stuff.zip)

**To Reproduce**
List steps to reproduce the behavior.
1. Please find the project in the sandbox folder in the attached zip
2. Load the Scene Sc01.
3. Add a few drawings to the Ball Column. (4th Column)
4. Click on a random cell.

**Expected behavior**
Update the view to the contents of the cell that is clicked

**Screenshots**

**Device Information:**
 - OS: Windows 10 Home
 - OpenToonz Version: Nightly - Version 1.4, Built Jan 6 2021
 - GPU: NVIDIA RTX 960
 - GPU Driver Version: 451.67

This behaviour was immediate when using the version 1.4 exe from the website ( e.g. draw one frame and then Ctrl-Z would crash the program). 

In the nightly build, it lets me draw a few frames before crashing.

Let me know if you need more info.

Thank you,
Nihal Kenkre.

**Comment by RodneyBaker** [comment]
Hi Nihal,
I attempted to replicate your problem but have not been able to as of yet.
In the latter part of your report you mention using Undo so I am attempting to find a problem with that as well.

Not that this helps much but I wanted you to know someone was looking at the issue.

**Comment by amadlover** [comment]
Hello Rodney.

Thank you for your response. 

My initial suspect was the GPU - driver combo too.

It just felt like the application tried to refresh but the GPU could not draw it correctly.

Cheers. 

Closing this now.

Nihal Kenkre.

**Comment by amadlover** [comment]
Is there a log file that is generated?
