### ISSUE TITLE
Option in Windows installer to create portable archival copy of release and project content

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#3670]
@shun-iwasawa This is based on a few discussions I've had over the past year but just now was reminded of...

Because every Opentoonz release can be made portable with relative ease...

and...

Because many users are not aware of the option...

and...

Because the process of making Opentoonz portable is subject to not work due to typos, etc. in the process...

It would be ideal if during the installation an option to create a portable copy of Opentoonz was presented.
This option would not need to negate the standard installation but rather would simply make a copy of the installed Opentoonz program files and the Opentoonz stuff directory at a location the user specified.  Of course it would rename the stuff directory appropriately as well in the process so that Opentoonz would recognize it and operate as portable.

There are a few potential 'gotchas' in the process of making Opentoonz portable if the user has previously installed Opentoonz but this might actually be a means to turn that into a useful feature set; namely, to allow for archiving project files located in the current stuff directory along with the Opentoonz program used in its production.

Proposed steps to create the portable (archival) copy of Opentoonz during installation:

1) Install the new Opentoonz release into default locations
2) Upon successful installation copy the contents of C:\Program Files\Opentoonz and C:\Opentoonz stuff into a directory of the users choice (with the default being on the current Desktop... or My Documents... with default name of 'Opentoonz portable').
2a) During copying of Opentoonz stuff directory (which might include many files created from previous releases) the directory would be renamed as 'portablestuff' and the contents copied into that location.
3) I looked to see if Inno Setup allowed for additonal options such as compressing directories into .zip files and if I recall correctly it can but not without using extensions.  This would be optimal for archiving and would also help in resolving issues with sharing project files (for troubleshooting and collaboration).

Other considerations this initial request does not address relate to how portables also work on Mac and Linux platforms.
As Innosetup is WIndows only that would likely need to be addressed in a separate PR.

All this... likely best saved for development beyond the initial release of v1.5 but it seems a good time to get these thoughts onto the development radar.

 Also relates to #669

**Comment by shun-iwasawa** [comment]
Thank you for the suggestion, it's nice idea 👍

**Comment by RodneyBaker** [comment]
Closing this request as #3995 covers most of the same territory.
The primary distinction being the emphasis on archiving the entire production assets and program together in addition to having an option to automate the process of creating a portable copy of Opentoonz.
