### ISSUE TITLE
v1.5 Previews

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#3675]
This is a space to post screenshots (and links) to highlights heading for Opentoonz v1.5 (and forks!).
Please feel free to share your discoveries and experience.

Github now allows uploading of MP4 attachments for those so inclined.

**Comment by RodneyBaker** [comment]
One of the themes for v1.5 is Customization.
Opentoonz has always been highly customizable but now there is a feature to bring this to users that don't care to dive too deeply into the files themselves.  Many changes to the user interface can be done via the Preferences Style Sheet (Additional Style Sheet).

![image](https://user-images.githubusercontent.com/2576432/104115832-2827a600-52d9-11eb-8b35-6276e474c3b1.png)

**Comment by RodneyBaker** [comment]
The Segment Erase Tool is a welcome new addition to v1.5:


https://user-images.githubusercontent.com/2576432/104116481-9753c900-52de-11eb-9c99-5dd4e0fda5e2.mp4

**Comment by RodneyBaker** [comment]
A breaking change for v1.5 is Glare FX.
Scene using Glare FX cannot be opened in older versions of Opentoonz.

https://user-images.githubusercontent.com/17974955/100841437-a1ea9980-34ba-11eb-803f-83ba17b1a536.png

For more information see:  #3614

**Comment by RodneyBaker** [comment]
**Bloom FX Iwa plugin** 

![image](https://user-images.githubusercontent.com/2576432/104116773-54472500-52e1-11eb-9634-3f94ca4405d9.png)


For more information see:  #3584

**Comment by RodneyBaker** [comment]
There are a number of additions and enhancements for Expressions.
Here is one:

**Random Periododic Expressions**

![image](https://user-images.githubusercontent.com/2576432/104116923-945ad780-52e2-11eb-9998-6bd90ffab2fc.png)


![image](https://user-images.githubusercontent.com/2576432/104116909-6aa1b080-52e2-11eb-871e-c0731fcbabc3.png)

For more information see #3411

**Comment by RodneyBaker** [comment]
Fractal Noise Iwa FX

Being introduced to v1.5 is a set of fractal noise effects (8 basic types... here is a sampling).

![Fractal Noise 1](https://user-images.githubusercontent.com/2576432/104117259-7b9ff100-52e5-11eb-8fad-c65960395139.gif)
![Fractal Noise 2](https://user-images.githubusercontent.com/2576432/104117260-7d69b480-52e5-11eb-9eeb-54b19e6ca649.gif)





For more information see:  ##3422

**Comment by RodneyBaker** [comment]
Github Actions (CI builds for Windows, Mac and Linux)

For users (and testers!) that like to be out on the cutting edge the Opentoonz github repo now builds Windows, Mac and Linux artifacts (portable releases).  Linux has builds for Ubuntu with both GCC and Clang.

![image](https://user-images.githubusercontent.com/2576432/104117377-83ac6080-52e6-11eb-92d7-feb10950ed39.png)

**Comment by RodneyBaker** [comment]
(Optional) Horizontal Level Strip Orientation

![image](https://user-images.githubusercontent.com/2576432/104117714-1bab4980-52e9-11eb-801f-095b1979bfa9.png)

Set your Level Strip to be vertical, horizontal... or both!

**Comment by beeheemooth** [comment]
camera1.ew? shouldn't it be camera1.x?

**Comment by RodneyBaker** [comment]
> camera1.ew? shouldn't it be camera1.x?

Depends on the context but yes, in most places that notation has been changed from 'east/west' to 'x'.
For backwards compatibility Opentoonz should still be able to accept the old terms for such uses as in expressions.

If there is a specific area of interest that is particularly problematic a report should be filed to have it get the issue addressed.

**Comment by RodneyBaker** [comment]
This is a good time to mention another small enhancement for Expressions in Opentoonz.

(Expression) Selectable Parameter Name Label

![image](https://user-images.githubusercontent.com/2576432/104134685-e8040a00-5350-11eb-8416-d329dca51ff3.png)

This ability to copy the expression element from the label field is especially useful when working with complex expressions.
For example, when working with Plastic Tool vertexes the name can be quite long.

![image](https://user-images.githubusercontent.com/2576432/104134902-22ba7200-5352-11eb-8557-e1e8072a8e84.png)


For more information please see PR #3537.

There is also the capability of dragging the objects name from the Stage Listing into the expression field.
Care must be taken so as not to lose the focus of the selection in this process however which makes copying the Label Name a useful alternative.

**Comment by age3rcm** [comment]
> In addition to a completely updated user interface with new icons, themes and styling... one of the themes for v1.5 is Customization.

but can we make our own cursors for tools? i have some ideas of my own

**Comment by RodneyBaker** [comment]
> can we make our own cursors for tools? i have some ideas of my own

As far as I know adjusting cursors will require a local build as they are not exposed to LESS/QSS and therefore cannot be adjusted in the Themes or via the new Preferences Additional Styles System.

Perhaps one of the UI experts can weigh in on what options are available.

As for cursor ideas... by all means start a new report and share what is on your mind.

**Comment by RodneyBaker** [comment]
*Production Board* 
![image](https://user-images.githubusercontent.com/2576432/105161668-3e9ee000-5ad7-11eb-9eae-f5692f152b9c.png)


Here is a feature that isn't yet added to Opentoonz so the jury is still out on whether it will be in the initial v1.5 release.

https://youtu.be/UjU7BgKYq58

Dimitri posted more information on basic usage as well as the road forward for the feature [HERE](https://github.com/opentoonz/opentoonz/pull/3665).

**Comment by age3rcm** [comment]
> > can we make our own cursors for tools? i have some ideas of my own
> 
> As far as I know adjusting cursors will require a local build 

i would be happy if i can simply swap some png files like i did with toonboom

**Comment by beeheemooth** [comment]
The Auto close option for the Brush Tool is very useful. Are there any plans to add this feature from Tahoma?

**Comment by RodneyBaker** [comment]
> Are there any plans to add this feature from Tahoma?

Short answer:  yes, of course.

Longer answer:  No one has publicly committed to porting any specific feature from Tahoma2D code into Opentoonz as of yet.  It will happen though.

**Comment by RodneyBaker** [comment]
Closing in order to tidy up open reports.
Additional previews of the v1.5 release can still be posted here or... preferrably... in Opentoonz documentation.

**Comment by RodneyBaker** [comment]
New set of MyPaint brushes:

![image](https://user-images.githubusercontent.com/2576432/111492944-216b4400-870b-11eb-9c4e-2075cc4f45ce.png)

Thank you @andeon!
