### ISSUE TITLE
[Feature request] Add action note column in xsheet

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#368]
There is option in [tvpaint](http://www.tvpaint.com/) & [toon boom harmony 12](https://www.toonboom.com/) and very useful. 
### What is The Action Notes?

This part is dedicated to the Action Notes.
The aim of this feature is to allow the user to add some comments / remarks / ideas / suggestions / notes over the animation on which he is working.
This Action Notes part is only a help for the animator, they are played over the project window at the same time than the animation is played in the software.
Of course, they won't be added in the final animation on render.
(This text is copy from tvpaint)

![opentoonz action note in xsheet](http://s6.picofile.com/file/8252995784/Opentoonz_The_Action_Notes.jpg)

**Comment by Juls3000** [comment]
I think Memos is similar to this : https://groups.google.com/forum/#!searchin/opentoonz_en/memo/opentoonz_en/ERrO0CaFPbw/RTn3vu9aAgAJ

**Comment by 2dvision** [comment]
@Juls3000 But Memos is very difficult. If you want lipsync your animation, action note is very easy way for this. 

Look at this xsheet action note:

![lipsync xsheet](http://www.bitterfilms.com/lilyjimnotes1.jpg)

**Comment by Juls3000** [comment]
You mean Memos as tooltips connected (associated) to frame number, and/or to frames of individual columns?, that could be interesting.

![cats](https://cloud.githubusercontent.com/assets/19145844/15572119/f0429a48-233e-11e6-9d8a-1f334380eaef.jpg)

**Comment by Juls3000** [comment]
The above could work together with one dedicated, non horizontally scrolleable, column which admits some combinations of text, and tooltips for more extense explanations.

![cats](https://cloud.githubusercontent.com/assets/19145844/15572676/5154a0b2-2342-11e6-85f0-40bc6c3da590.jpg)

**Comment by blurymind** [comment]
yes the suggestion by @Juls3000  is pretty good as it also resolves this request:
https://github.com/opentoonz/opentoonz/issues/325

**Comment by 2dvision** [comment]
I think if possible drawing directly with brush in Action Notes is easier for animators. For you understand what I mean, look at [The Timeline Notes](http://www.tvpaint.com/doc/tvp11/index.php?id=lesson-sound-management-notes) in tvpaint 11 and [Annotation Column](http://docs.toonboom.com/help/harmony-12/premium/Content/_CORE/_Workflow/011_Timing/012_H2_Adding_an_Annotation_Col.html) in toonboom harmony 12.

If impossible do that, @Juls3000 idea looks good. Action Notes must be Separate column. Maybe animator want direction scene in one Action Notes Column and planning lipsync in other. If columns are flexible, it is very useful.

I think @Juls3000 idea looks good. I add Dialog Notes too, look at this:

![Action Notes Column opentoonz](http://s6.picofile.com/file/8253133200/Opentoonz_Xsheet_Action_Notes.jpg)

**Comment by AyameLee** [comment]
I think people misunderstand, I wouldn't use either solution mentioned here, maybe for doing cut-out animation but certainly not for traditional, there would be too often a disconnect from drawing and typing on a keyboard.

If what you want is to simulate the TVP or Toon Boom method then it must be like a whiteboard, a column that you can draw directly onto, erase and clear-all, this would probably be very difficult to do though.

![animation3](https://cloud.githubusercontent.com/assets/18118611/15600711/9d6604f4-23e3-11e6-8bd0-7b8624115bb6.gif)

**Comment by Juls3000** [comment]
I think that transition from paper to the computer gives us a key advantage that better we not lose, gives us the flexibility to quick and easily duplicate, copy, paste, insert and move frames, to keep this advantage, the information has to be associated with frames. IMO just a drawing in one column, will petrify it. If problem is to use the keyboard, I think it is better to think in digital solutions :

![cats](https://cloud.githubusercontent.com/assets/19145844/15601987/f22bd6ee-23f2-11e6-95d5-cf621f032ec8.jpg)

**Comment by Juls3000** [comment]
> I think if possible drawing directly with brush in Action Notes is easier for animators. For you understand what I mean, look at [The Timeline Notes](http://www.tvpaint.com/doc/tvp11/index.php?id=lesson-sound-management-notes) in tvpaint 11 and [Annotation Column](http://docs.toonboom.com/help/harmony-12/premium/Content/_CORE/_Workflow/011_Timing/012_H2_Adding_an_Annotation_Col.html) in toonboom harmony 12.

Perhaps it will be worthy to study those examples, if possible bring more material (video tutorias, etc)

**Comment by AyameLee** [comment]
I gave you a digital solution, that's how TVP does it and how I'd do it on paper, you need to understand all the notes need to be readable all at once but I can't really explain it anymore than that without going into animation fundamentals.

I have some courses by Disney animators that I obviously can't show you, but I think it was Aaron Blaise who showed how to transcribe phonetics from a sound file using the TVP notes panel.

Even Niels Krogh Mortensen had this in his development/ideas stages for his animation software Animation Paper.

![cap](https://cloud.githubusercontent.com/assets/18118611/15604502/be8d3db8-23f8-11e6-981b-9d854061af35.PNG)

**Comment by Juls3000** [comment]
IMO questión is to integrate the best of paper animation with best of digital technology. 

The optimal solution will not come, neither from paper point of view, neither from digital technology point of view. Optimal solution will be in a new spot haf way of those two fieds.

To achieve this, people of each field has to make the effort of understand, to some extent, the world of people of the other field. 

This is the reason why I am asking here for as much documentation as possible about how other software is finding the integration above mentioned.

I think taht, it will be good to avoid the risk of to pretend to move to digital, the 100% of paper animation ways. This would be to be using the past as rest chair, not as springboard.

**Comment by Juls3000** [comment]
> Niels Krogh Mortensen had this in his development/ideas stages for his animation software Animation Paper.

I think that OT is a software developed in both, step-by-step and in interpolated animation, and this polivalent focus should be the phylosophy to approach this issue. Thinking on it, just from one of the two scopes, IMO will be a wrong approach

**Comment by 2dvision** [comment]
Look at this video tutorial. Tvpant by Aaron Blaise and Toon Boom by Bloop Animation.


[Animation -  TVPaint Animation, a quick start guide](https://www.youtube.com/watch?v=t_B8lB3Gf_w) (3:00)
[Animation - TVPaint 11 QuickStart Overview](https://www.youtube.com/watch?v=u4CPPXx4LaI) (14:00)
[Frame-by-frame Animation with Toon Boom](https://www.youtube.com/watch?v=KvimRY6Z4pY) (7:00)

**Comment by Juls3000** [comment]
I like TVPaint Timeline Notes, not sure if slice and move, could be enough to edit it; select, cut and paste also could be useful.  Drawings on the column could be complemented with tooltips when more espace will be needed.

![cats](https://cloud.githubusercontent.com/assets/19145844/15614868/733126e8-243b-11e6-9333-bb7037aba36e.jpg)

**Comment by 2dvision** [comment]
I like @AyameLee idea, because it's simple and easy for traditional animators. I add 3 color too.

![xsheet-opentoonz---action-note](https://cloud.githubusercontent.com/assets/16509592/15636471/1adc865a-2615-11e6-97b1-02b2bbb22ca2.jpg)

**Comment by Juls3000** [comment]
Anyway this "Note Column" should be hideable, not everyone will use it

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
