### ISSUE TITLE
Similar Shape Interpolation:  Working Correctly?

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#3683]
This could be user error but...
I noted some time back there might be an issue with Similar Shape interpolation but failed to follow up on it.

Before I dig any further, can someone confirm Similar Shape interpolation is working for them?
If working what release is it confirmed to work on?

**In particular take note when entering the simular shape expression into the text field and how it doesn't seem to want to accept the full text being typed in.**  For me it seems to fail at the point of typing in any dot/period, as in "col1.x".  It also rejects the older "col1.ew" formatting.

Thanks in advance.

For those not familiar with that form of interpolation, Similar Shape interpolation is quite useful.
Please refer to the documentation for more information:

https://opentoonz.readthedocs.io/en/latest/editing_curves_and_numerical_columns.html#using-interpolations-based-on-similar-shapes

**Comment by shun-iwasawa** [comment]
I made the Similar Shape interpolation when developing Toonz Ghibli Edition.
I briefly tested it and it seems to work properly in the current version.
![similarshape](https://user-images.githubusercontent.com/17974955/104672330-ed7f9c80-5722-11eb-8630-d412889429b4.gif)

Can you please let me know in detail - is there any condition when the text is not accepted?

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa for the quick follow up.

I see now this is largely user error on my part.
Your screen capture has reminded me that I've done this before.

Where I am going wrong is in forgetting to use the curve editor and selecting a channel segment and instead am simply selecting the column header of the Function Editor spreadsheet, similarly to use of other interpolation options, and then attempting to enter the source column.channel ID into the Reference Curve text field.

![image](https://user-images.githubusercontent.com/2576432/104689799-d14f1180-56c8-11eb-887e-b04329549329.png)

This results in the contents of the text field only getting to the end of the column name before the text field resists the entry of the period/dot and channel.  I must assume that is because the focus is still on the whole column and not the channel beneath.

I will plan to close this as the feature is indeed working as you have so ably demonstrated.
We should definitely examine how users discover this feature as the typical method of initiating interpolations via Function Editor via selecting the column header can leading a user to the impression that Similar Shape interpolation doesn't work.
Perhaps there might be a way to trigger an error message if Similar Shape is invoked while not having the focus on a channel segment?

At any rate, I would not call addressing this a high priority.

Thanks again for setting me straight.

**Comment by RodneyBaker** [comment]
Closing this as Similar Shape interpolation appears to be working, just not optimally.
I will reopen this report or create a new report if/when I can more directly describe the problem(s) I have previously encountered.
