### ISSUE TITLE
(Proposal) Cosmetic change to external Opentoonz v1.5 release 

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#3685]
In order to make it easily clear to users at a quick glance that they have an updated release of Opentoonz perhaps we could adjust either the splash screen and desktop icon (or both).

I'm attaching an example of a slightly modified SVG splash screen.
The intent is not to make any bold change but just a subtle one that users will immediately recognize as an update.

The attached SVG has embedded text which is something I'm not sure the engine that is presenting the splash screen can actually parse through and display.  I include it here primarily because editable text in the splash screen SVG would be a good way to customize the text for special purposes... or temporarily hide with the color same color as the splash background if unneeded.  I include it as an example of what potentially we might target in the future... to programmatically populate the splash screen with appropriate information.

Note here that I do not suggest the release version or other information that will change in the future be presented in the splash screen as that would make for more work than reasonably necessary.  The exception of course would be if that information could be automated in similar way as the Xsheet Print function that populates HTML with user information.  

The primary change I was thinking of for v1.5 release is just to add a border but the experiment ended up going a little farther than that.

Here is what my experiment currently looks like:
![image](https://user-images.githubusercontent.com/2576432/104570061-1450ac80-5617-11eb-8418-4a2612cf7c97.png)

From memory I don't think the splash screen can contain editable text.
In the attached SVG however the content, color and placement of the SVG text can easily be edited and then converted to non-editable text formatted SVG.

Attached please find a zip file with the SVG as well as a text file where the .svg extension has been renamed as .txt.

Again, the purpose of this cosmetic change would be to let users know at a glance they have launched an updated release of Opentoonz.  This perhaps more important as this is the v1.5 release (half way to v2.0!) and the splash has not changed since 2016.

[splash_example.txt](https://github.com/opentoonz/opentoonz/files/5813467/splash_example.txt)
[splash_example.zip](https://github.com/opentoonz/opentoonz/files/5813468/splash_example.zip)

**Comment by gab3d** [comment]
I like the idea of a slight variation from release to release.

**Comment by amotarzi** [comment]
I don't think the splashscreen should change...

**Comment by RodneyBaker** [comment]
> I don't think the splashscreen should change...

I have many reasons why I don't think it should change also.
Any particular reason why you prefer it not to change @amotarzi?

**Comment by RodneyBaker** [comment]
For reference, here is the current splash as it appears when launching Opentoonz.
Note that in this captured instance the text doesn't include indication that a portable is launching because the splash I recorded is from Opentoonz installed to harddrive.
When Opentoonz is portable that information appears in the text stream.

![OTSplash_current](https://user-images.githubusercontent.com/2576432/104830748-4ba5a000-5847-11eb-8abd-08342e77d2db.gif)

To meet the basic intent of this proposal all that might be needed is to add a border around the splash image.
This would immediately signal to the user... even if only subsconsciously... the release of Opentoonz has changed.

Other data could added to the current text stream but this may not optimal for a number of reasons.  
For instance release info could be added to the text stream.
Ideally the splash screen appears for the shortest time possible... so the user can use the program immediately.
The current text can flash by so quickly as to be hard to read (generally a good thing!).
As such adding addition output would not address the intent of this proposal which is to provide a simple, concise and clear signal of change.  This isn't to say that having some form of debug mode where additional information was piped into the current text stream might not sure additional needs outside the scope of this proposal.

**Comment by RodneyBaker** [comment]
Closing as a change best suited for future discussion and exploration.
Hopefully something that can be discussed in Github Discussions if that can be brought online.
