### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by ScooB20** [opentoonz/opentoonz#3687]
**Describe the bug**
The picture appears to be out of the white lined box

**To Reproduce**
List steps to reproduce the behavior.
1.I got a new computer with the new graphics card
2.i downloaded my files from my old laptop
3.I looked at them in opentoonz
4.and they were all out of the white box

**Expected behavior**
the picture binning in the right spot

**Screenshots**
![image](https://user-images.githubusercontent.com/77516352/104833522-2bc5aa80-584e-11eb-8cb3-269b74df41f8.png)

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 3070]
 - GPU Driver Version: [e.g. idk at the moment I will check]

**Comment by RodneyBaker** [comment]
To post a screenshot via Windows:
1) Have Opentoonz showing the screen/information you want to share.
2) Locate the Print Screen key on your keyboard and press it (this will copy your current screen into the WIndows Clipboard (or in latest releases of WIndows might open a clipboard program to allow you to draw a rectangle around what you want to capture)
(It should be the key up top/right next to the backspace and delete keys labeled 'prt scn'.
3) Place your cursor in a post here and use Control + V to paste the captured image from the clipboard into the post.
(Other means of copy pasting exist in many programs as well such as Right Clicking and selecting either copy or paste)
4) Submit your post

**Comment by ScooB20** [comment]
i posted the screenshot

**Comment by shun-iwasawa** [comment]
It seems to be due to the long-time bug with working on the multi monitor environment with different device-pixel ratio.
Are you connecting two monitors, one is with normal dpi and the other is with high dpi?

**Comment by ScooB20** [comment]
yes

**Comment by shun-iwasawa** [comment]
Sorry for the trouble but you need to set the same device-pixel ratio between monitors when you use more than one monitor.
Please try the following:
1. (On Windows 10) Go to Start Menu -> Settings -> System -> Display and choose the monitor.
2. Scroll down to the Scale and layout option and select a percentage from the dropdown menu.
3. Set the same percentage value for both monitors.
4. Launch OpenToonz.
