### ISSUE TITLE
FFMPEG not found by OpenToonz on Ubuntu

### ISSUE THREAD

**Issue by VinceFINET** [opentoonz/opentoonz#3688]
**Describe the bug**
FFMPEG not found by OpenToonz on Ubuntu

**To Reproduce**
List steps to reproduce the behavior.
1. Install OpenToonz on a Ubuntu from apt-get
2. Install ffmpeg on the same Ubuntu from apt-get (command "which ffmpeg" output "/usr/bin/ffmpeg")
3. Launch OT, try to render as MP4 you get a dialog box saying the program did not found ffmpeg
4. Go to preference, and set "/usr/bin/ffmpeg" and restart OT
5. Same error as step 3
6. Go to preference, and set "/usr/bin/" and restart OT
7. Same error as step 3
8. Go to preference, and set "/usr/bin" and restart OT
9. Same error as step 3 

**Expected behavior**
OT should find ffmpeg

**Device Information:**
 - OS: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - OpenToonz: 1.4 built May 29 2020 11:56:49

**Comment by VinceFINET** [comment]
Hi again,

I got the package from here: https://snapcraft.io/opentoonz
I have created an issue in their own Issue Tracker at: https://github.com/snapcrafters/opentoonz/issues/9
I will update you.

Meanwhile can you tell me if there is an option to set the log of the app into DEBUG to better understand what's happening?

**Comment by VinceFINET** [comment]
Yes i see the modification. I did update the snap.

```
$ snap refresh 
opentoonz 1.4.0 par Snapcrafters mis à jour

```

And MIRACLE it's working now!!!
Thank you so much for your work!

**Comment by VinceFINET** [comment]
So in conclusion:

- The new version of the snapcraft opentoonz has a fix about this, thanks to @popey
- Remember to update the snap if already installed with `snap refresh opentoonz`
- And set the path of FFmpeg in preferences to `/snap/opentoonz/current/usr/bin`

**Comment by RodneyBaker** [comment]
Thank you @VinceFINET for pressing forward with this.
I know quite a few people who will be happy to hear the news.
