### ISSUE TITLE
Two glitches when merging Global Palettes with the current palette.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3689]
**Glitch 1:**
1. Create new level (any type)
2. Drag a palette from the Global Palettes into the current palette (or use the Merge to Current Palette command) so that the palette will automatically create a new page.
3. Draw something using the styles of this palette.
4. Save All and restart the scene.
5. The palette you added (and the page) will be lost and the drawing will be red.
6. If you load the same palette again, the styles color will return to its place. 

![ezgif-7-064a54b7042f](https://user-images.githubusercontent.com/25724133/105074489-18eee800-5a91-11eb-8797-52a8aaa67192.gif)

**Glitch 2:**
1. In the Level Strip, select the frame and clear it (by pressing Delete).
2. Together with the drawing, the loaded palette (which is located on another page) will disappear.
3. If you have several frames drawn and you delete one, the loaded palette will not disappear, however, after restarting the scene, the drawings will be red.

![ezgif-7-121b2189307f](https://user-images.githubusercontent.com/25724133/105076615-f0b4b880-5a93-11eb-8328-5a8c5ecf5055.gif)

The palette disappears the moment you move from the Level Strip to the Xsheet. If at the same time you have selected any style of the disappeared palette, then the Brush Tool will draw red strokes.

**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: latest Nightly

**Comment by KaseyFarron** [comment]
Following your steps I can recreate the problem (glitch 1). I noticed there is no asterisk when you merge palette on the palette panel, so I guess it's being skipped on save? If you press the save icon in the palette window and overwrite the level palette it seems to work OK.

**Comment by beeheemooth** [comment]
But doesn't the "Save All" command save changes to the palette? Then it should be renamed as "Save Almost All". ^_^
