### ISSUE TITLE
Missing Icons in Command Bar

### ISSUE THREAD

**Issue by Agnyy** [opentoonz/opentoonz#3699]
Hello everyone!. I noticed that the commandBar does not have all the icons for the tools. 
Maybe the problem is only in my version of the program? Or were these icons never rendered? If they just haven't been drawn then I can sketch some of them.
I am interested in the icons from the tools section.
![image](https://user-images.githubusercontent.com/25137502/105728649-72499200-5f3d-11eb-8462-37dc681e6bfd.png)
And there are not enough icons for.
Animate Tool - All
Animate Tool - Center
Animate Tool - Next Mode
Animate Tool - Position
Animate Tool - Rotation
Animate Tool - Scale
Animate Tool - Shear
Although almost all the icons for the "Animate Tool" tools are already in the program itself.
![image](https://user-images.githubusercontent.com/25137502/105729157-fac83280-5f3d-11eb-9c44-c08c8db85933.png)
There are also no icons for.
Eraser tool - Freehand
Eraser tool - Next Type
Eraser tool - Normal
Eraser tool - Polyline
Eraser tool - Rectangular
Eraser tool - Segment
Fill tool - Areas
Fill tool - Freehand
Fill tool - Lines
Fill tool - Lines & Areas
Fill tool - Next mode
Fill tool - Next Type
Fill tool - Normal
Fill tool - Polyline
Fill tool - Rectangular
Geometric Tool - Arc
Geometric Tool - Circle
Geometric Tool - Elipse
Geometric Tool - Line
Geometric Tool - MultiArc
Geometric Tool - Next Shape
Geometric Tool - Polygon
Geometric Tool - Polyline
Geometric Tool - Rectangle
And 34 more items. Tired of listing. I can draw a few icons for the ones I often use myself if it makes sense. I want to hear your opinion.

**Comment by Agnyy** [comment]
![image](https://user-images.githubusercontent.com/25137502/105730909-e422db00-5f3f-11eb-82eb-b34f4504d5c7.png)
Are these icons used in the commandBar? @konero

**Comment by artisteacher** [comment]
It looks like those are all commands that switch the tool and set a specific mode/type at the same time.

Those icons are used:
<img width="260" alt="Screen Shot 2021-01-25 at 1 04 19 PM" src="https://user-images.githubusercontent.com/21159116/105746875-fedc5c00-5f0d-11eb-8744-67d20a4a2876.png">
But they are used just to change the mode/type - not changing the tool too.

I guess there should be additional icons that combine the tool and mode/type icons - where one overlaps the other.

**Comment by konero** [comment]
When I did the redesign I only prioritized the top menu and all the front facing UI, I made sure to do the front UI first as I was expecting to experience creative burn-out when I numbered how many there were to do, and I did eventually (I managed 500+) so I decided to call it. The command icons I submitted were actually requests by people I work with or on Discord at the time, many requested the Modes icons for Fill/Paint Brush tools but nobody seemed to use the tool switch version.

I probably won't do anymore for awhile, as the ones I was creating during the last quarter of work were not the best, the autofill empty cell command icon for example is a bit chunky, and my designs were becoming rushed.

I'd be happy to see other command icons designed (or redesigned) and submitted by others. It's not difficult to do, but you should have a working build so you can test them before submitting (just follow the build guide, I think @DoctorRyan made some actually quite useful how-to build OpenToonz videos). I list in some detail how the icons work, and I made a post about design choices in the PR, but I'll list some steps here for anyone wanting to try it out.

The icon should be made 20x20px and exported as an SVG, but first try to design it for 16x16 in a 20x20 canvas, use the extra pixels if nessesary. I included some template files you can find in the icons directory so feel free to use those. The emblems file contains the small bin, etc. emblems you see on some icons.

https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/toonz/icons/templates

To use emblems, I made this explainer, you basically just need to cut out a 1px outline from the main icon shape:

![image](https://user-images.githubusercontent.com/19820721/105793450-0d179000-5f81-11eb-9bdf-ff195f66346e.png)

You should use just black (`#000000`) as that is the color OpenToonz uses to recolor it automatically for themeing. Any other color will not be recolored. You should also turn on the pixel grid and enable snapping. This is important, as each pixel in the grid represents one pixel on the screen. If your shape covers only half a pixel, it means you'll get dithering and the icon will look blurry.

Open up mainwindow.cpp and go to about line 1657, you'll find the commands there.

https://github.com/opentoonz/opentoonz/blob/c4c3932decd853309202d576fde49386b9967ca9/toonz/sources/toonz/mainwindow.cpp#L1657

To give a command an icon, use the setIcon function. If the command looks like this...

`menuAct = createMenuFileAction(MI_LoadScene, tr("&Load Scene..."), "Ctrl+L");`

You can set an icon by writing this line undereneath:

`menuAct->setIcon(createQIcon("load_scene"));`

Where it says "load_scene" is the filename of the SVG minus the file extension, the createQIcon function will handle the extension so don't worry about that. The path is handled by another built-in function automatically, so you only need to type the filename.

Then you need to add the icon file to the [icons/dark/actions/20](https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/toonz/icons/dark/actions/20) directory, then open the Qt resource file [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/toonz.qrc) and add the icon path, beginning with the **_icons_** directory, like so:

`<file>icons/dark/actions/20/your_icon_file.svg</file>`

Build, test, and that's it.
