### ISSUE TITLE
Type Tool don't work in OSX

### ISSUE THREAD

**Issue by kogaki** [opentoonz/opentoonz#370]
I can't type any characters with `Type Tool`. `Font` in tool option bar also don't work. There might be something wrong in loading fonts.

![2016-05-26 15 45 34](https://cloud.githubusercontent.com/assets/17926501/15565923/fe4581a4-2358-11e6-9e73-3a9d75aa3418.png)

**Comment by kogaki** [comment]
OK, this is because `type tool` is programmed as 32bit feature. In windows we bundled 32bit while we don't in OSX.

**Comment by artisteacher** [comment]
Is there going to be any resolution for this issue? I'm having my high school students use OpenToonz and we are using Macs. It would be better to remove the font tool from the menu if the functionality will not be added.

**Comment by artisteacher** [comment]
Still an issue in 1.1.2. It would be really great to be ale to use text at some point.

**Comment by artisteacher** [comment]
While the type tool can be selected, it is still unusable in OS X. The drop downs next to font and size do not open. Nothing happens when clicking & etc. @kogaki seemed to think that #463 would help...
