### ISSUE TITLE
Can someone confirm OpenToonz compatibility on M1 MacBook?

### ISSUE THREAD

**Issue by Resotakuchira** [opentoonz/opentoonz#3704]
Did anyone manage to use OpenToonz on a new Mac with M1 chip?

**Comment by artisteacher** [comment]
Have you had trouble?

**Comment by Resotakuchira** [comment]
No, I'm planning to buy an M1 MacBook Pro, but I'm afraid of OpenToonz not working on it, as even though I've contacted several tech people all I got was 'that's beyond my knowledge'.

**Comment by artisteacher** [comment]
It sounds like apps designed for older macs should run on the new machines using [Rosetta 2](https://www.theverge.com/21304182/apple-arm-mac-rosetta-2-emulation-app-converter-explainer) which is an emulator that's part of Big Sur. 

So theoretically it should work, but confirmation from someone with the M1 chip would be great.

**Comment by notthatnathan** [comment]
On an M1 MacBook Air, it worked fine for a bit but now crashes on open. The logs seem to point at Rosetta.

**Comment by RodneyBaker** [comment]
I've seen multiple confirmations of users running Opentoonz with M1 MacBook.
It would be good to get that word from someone actually using it successfully though to close this report out.

**Comment by artisteacher** [comment]
I haven't had any new or unexpected problems running OT. Though I am having trouble getting a working build environment for OT/T2D .

**Comment by RodneyBaker** [comment]
Thanks @artisteacher!
Will be interested to know more about the build environment aspect of the equation.
