### ISSUE TITLE
Allow User to Modify Time for Temporary Tool Switch Shortcut Keys

### ISSUE THREAD

**Issue by KaseyFarron** [opentoonz/opentoonz#3706]
**Is your feature request related to a problem? Please describe**
This is about the temporary tool switch when you hold the shortcut key and then let go after a certain time to automatically switch back to the previous tool.

When I pan using hand, or rotate the canvas using shortcut keys, very often the tool switches to those tools by accident. I think the time range set for this is too long for navigating tools and makes a cumbersome workflow.

**Describe the solution you'd like**
I would like to see a new option added to Preferences that lets the user choose the time.

**Comment by juniormolina** [comment]
that would be great... it happened to me too, and I'm certainly used to CSP time too...

**Comment by konero** [comment]
I second this, it's currently a pain to navigate using the temp shortcut keys, I always end up switching to the wrong tool, most likely my muscle memory is tuned to other software like everyone else has mentioned. I don't know what the current length is, probably one second? But it feels too long to be registered as a temp press.

I didn't have much time but I tried looking to see where this is set but I couldn't find anything. If anyone could add this option it would be greatly appreciated.
