### ISSUE TITLE
Vektor Bezier drawing tool ?

### ISSUE THREAD

**Issue by GJG** [opentoonz/opentoonz#3707]
Hi
I am new user of Open Toonz and I realy love it exept I cant find the Besier drawing vector tool.  The vector point creator tool that is in all major vector programmes.  Is it in deveopment?

Thanks

**Comment by RodneyBaker** [comment]
Hi GJG,
We need to find you some video tutorials...

The Brush Tool works with both raster and vector.
What makes the difference is the level type that is created to draw on.

If you go into Preferences on the Drawing tab you'll find a place where you can change the default from toonz raster to toonz vector.   This may help you in the short term until you are more familiar with the tools and options.

Of course you can simply create a vector level at any time even if the default in Preferences is set to toonz raster or raster.  There are multiple ways to create a level and multiple ways to create vector levels.

Once you have a vector level the various tools can be used with vector drawings such as the Control Point Editor Tool... and that is where user will edit via bezier curves.  The Eraser also has useful modes such as segment erase... and there is a whole lot more.

Closing this but please feel free to continue the discussion.
You may want to join one of the Opentoonz communities where other users will be glad to help you learn the ins and outs of Opentoonz in real time.

**Comment by artisteacher** [comment]
Do you mean like a pen tool? If you have a vector level created, try using the Geometric Tool set to "Polyline" it behaves can be used nearly like a pen tool, though you can't hold down on opt/alt to make cusp points. You can use the Control Point Editor to make adjustments after as needed.

**Comment by GJG** [comment]
> Do you mean like a pen tool? If you have a vector level created, try using the Geometric Tool set to "Polyline" it can be used nearly like a pen tool, though you can't hold down on opt/alt to make cusp points. You can use the Control Point Editor to make adjustments after as needed.

This is what I was looking for, not so obvious for a beginner  ;) thanks

**Comment by GJG** [comment]
> Do you mean like a pen tool? If you have a vector level created, try using the Geometric Tool set to "Polyline" it can be used nearly like a pen tool, though you can't hold down on opt/alt to make cusp points. You can use the Control Point Editor to make adjustments after as needed.

This is what I was looking for, not so obvious for a beginner ;) thanks

**Comment by artisteacher** [comment]
Yeah, I'd love to see it separated out as a Pen tool so it is more obvious - #3246 but no one has been interested so far.

**Comment by chrisatbest** [comment]
This discussion was 4 years ago. I have just started using this program, but the lack of the Vector Bézier drawing tool makes drawing in vectors very difficult!

I was very surprised it was not there when I first started using this program, so go back to Inkscape.

**Comment by RodneyBaker** [comment]
It's hard to go wrong with Inkscape when needing vector drawing tools.

**Comment by gab3d** [comment]
@chrisatbest 
I'd like a Pen Tool to exist too, mainly for UX reasons. 
But honestly, the functionality of the current Geometric Tool in Poly Line mode is almost identical to a regular Pen Tool in other programs.
You can:
- Create linear or smooth vertices.
- Create one side smooth, the other linear.
- Snap to angle steps, while drawing.
- Delete already placed points without exiting the tool.

And other common post drawing editing operations are usually served well by the Control Point Editor Tool.

Perhaps the ability to tweak already placed point without exiting the tool would be good, though.

**Comment by chrisatbest** [comment]
@gab3d 
Thank you for telling me where's to find a similar tool, you're right, it is basically the same. 

I'm so pleased.
