### ISSUE TITLE
Crashing when opening a scene. Please HELP.

### ISSUE THREAD

**Issue by Duckdcluckgoose** [opentoonz/opentoonz#3709]
**Describe the bug**
Hi, I was working on a project, and I decided to use the plastic tool. I then applied the mesh fine, it worked, But I did not like the way it looked. So I deleted the Plastic and mesh layer, and saved, and exit. But then, Whenever I try to open that project, It crashes opentoonz. So I cannot get into the project. And I need that project ASAP.
**To Reproduce**
List steps to reproduce the behavior.
1.Apply Plastic and mesh covering and Rig it all up.
2.Save. Exit.
3.Try and get back into the project.

**Expected behavior**
Whenever you use the plastic tool and delete the layer, I expected for it to just go back to what it was before, not crash it again and again.

**Screenshots**
https://user-images.githubusercontent.com/73257686/106827134-21bced80-663d-11eb-8c4f-182c12a88d64.png

**Device Information:**
 - OS: [Mac]
 - OpenToonz Version: [1.4]
 - GPU: [Intel HD Graphics 6000 1536 MB]
 - GPU Driver Version: [NA]

**Comment by artisteacher** [comment]
Do other scenes in the same project always crash too? Please share the crash report (you can find it in the Console app and copy/paste it into a .txt file).

**Comment by Duckdcluckgoose** [comment]
No, other scenes do not crash.

**Comment by Duckdcluckgoose** [comment]
Other scenes do not crash, just the ones that I deleted the plastic tool. Where do you find the crash log?

**Comment by artisteacher** [comment]
<img width="359" alt="Screen Shot 2021-02-05 at 1 11 51 PM" src="https://user-images.githubusercontent.com/21159116/107072389-0c1e0400-67b4-11eb-9235-c2c35ed4f718.png">

<img width="697" alt="Screen Shot 2021-02-05 at 1 10 34 PM" src="https://user-images.githubusercontent.com/21159116/107072549-3b347580-67b4-11eb-89e4-17d4fdf2e336.png">

**Comment by Duckdcluckgoose** [comment]
What specific File in the console am I supposed to click?

**Comment by Duckdcluckgoose** [comment]
I think this is correct.
![Screen Shot 2021-02-08 at 10 36 03 AM](https://user-images.githubusercontent.com/73257686/107265932-b470da00-69f9-11eb-8058-f3e01d21ad72.png)

**Comment by manongjohn** [comment]
It's an issue in your scene file when you deleted the mesh. A pegbar entry has parent information for the mesh you deleted and its crashing when it tries to find something that is not there.

If you can share your scene file with me I can fix the file for you. If you cannot share it publically, but willing to share privately, we can arrange something.

**Comment by Duckdcluckgoose** [comment]
How can I do that?

**Comment by Duckdcluckgoose** [comment]
> It's an issue in your scene file when you deleted the mesh. A pegbar entry has parent information for the mesh you deleted and its crashing when it tries to find something that is not there.
> 
> If you can share your scene file with me I can fix the file for you. If you cannot share it publically, but willing to share privately, we can arrange something.

How can I share the file?
