### ISSUE TITLE
(Proposal) Branding and Visual update! :: [concept] [FluentDesign]

### ISSUE THREAD

**Issue by juniormolina** [opentoonz/opentoonz#3710]
# Visual update

We all loved the redesign of the interface, it was an incredible job, but I think OT can continue to improve visually, with this in mind I proposed to make a concept of a visual layout of the interface so that it is clearer.

**A short presentation**, I am an artist, illustrator and animator, graduated as a graphic designer, I have followed OT since it was released as opensource software and now I feel that under my knowledge I could contribute to its development.

In my opinion, if OT becomes more and more a standard in animation competing with other software, this will allow the development and exploration of industry and open code.

If we make OT visually competitive software, we will attract more animators, recognition, attracting more people to the project could also add more developers and OT would continue to grow together.

The whole concept will go into Fluent Design, for developers, below I will leave some links about the code that may be useful.

### Branding Redesign

Starting with the image, the OpenTtoonz logo would adapt to be a more modern, minimalist and aesthetic design.

The colors will also be updated to a more vivid scheme, which allows creating better contrasts and showing OpenToonz as a software in constant growth.

![logo](https://user-images.githubusercontent.com/40076112/105998800-00776280-607b-11eb-98b5-52c211bc1613.jpg)

<br><br>
You can see an animated video of the logo redesign... Click in the image:
<br><br>

[![Watch the video](https://i.ytimg.com/vi/z_YG0NuNraY/maxresdefault.jpg)](https://www.youtube.com/watch?v=z_YG0NuNraY&feature=youtu.be)

Without forgetting that we are building animation software, presenting these changes with animations will make my explanation easier, so throughout the text you will see some animations in order to show how the objects and colors interact...

### Recomendation: To see the Gifs in better quality, click "ViewFullSize"

<br><br>
<p align="center">
<img src="https://user-images.githubusercontent.com/40076112/106024627-f747bf00-6095-11eb-8688-a1497b5997c1.gif" width="150" style="text-align:center" />
</p>
<br><br>

It is important that Darktheme becomes the main OpenToonz theme by default, more than a matter of aesthetics, DarkTheme reduces fatigue and eyestrain after hours of work.

This will be able to unify all the branding while the colors will contrast faster and in the work environment it will reduce distractions _(It's something that editing software has been studying for several years).

![Darktheme](https://user-images.githubusercontent.com/40076112/106067399-97203f80-60cc-11eb-8de9-8e481cebc043.jpg)

### Talking about the Fluent Design

The principal keywords for the redesign will be "Clean, Modern and Fresh", an interface that allows a faster learning curve, easily understand what each option does. If we talk about fluent design, we talk about materials, intuition and user experience.

So, when we talk about materials, in fluent design the most common is acrylic, which allows, apart from a stylized aesthetic finish, to see the background through the open window with a certain degree of blur, at the end is a link to the open code about it that Windows has developed, I am not sure if this code can be implemented with OT but it gives a visual idea to the objective of wanting to implement acrylics in OpenToonz.

Here you can see how the concept of acrylic affects when OT starts on our desktop, the wallpapers change quickly to better appreciate the effect.

<br><br>
[![Watch the video](https://i.giphy.com/media/BNMZktEXz5As26ule4/giphy.webp)](https://i.giphy.com/media/BNMZktEXz5As26ule4/source.gif)
[ViewFullSize](https://i.giphy.com/media/BNMZktEXz5As26ule4/source.gif)
<br><br>

From there, the concept of the OT start screen was born, in which we can easily create a new scene with visual recommendations to facilitate creation...

![FirstScreenA](https://user-images.githubusercontent.com/40076112/106052799-08092c80-60b8-11eb-901f-da4ed7e15867.png)
![FirstScreenB](https://user-images.githubusercontent.com/40076112/106052300-6a156200-60b7-11eb-9919-22fbe99b7872.png)

Here an animation of how the elements interact in the concept...

<br><br>
[![Watch the video](https://media.giphy.com/media/ifwaeEjeaileloNtzd/giphy-downsized-large.gif)](https://i.giphy.com/media/ifwaeEjeaileloNtzd/source.gif)
[ViewFullSize](https://i.giphy.com/media/ifwaeEjeaileloNtzd/source.gif)

<br><br>
You may wonder what that icon is next to "Show this at startup", well it is the icon to activate and deactivate the Acrylics of the fluent design. We can also find it at the top of the menu, just after "Help". More examples of acrylics will be shown below.
<br><br>

![physics](https://user-images.githubusercontent.com/40076112/106067372-8ec80480-60cc-11eb-8fc4-9e68aceaba0b.jpg)

<br><br>
If you desactivate the option "Show this at startup" you will be able to see this options when you initialice OT...
<br><br>

![FirstScreenC](https://user-images.githubusercontent.com/40076112/106053176-7d74fd00-60b8-11eb-9b4a-6abf3b1bc986.png)
![FirstScreenD](https://user-images.githubusercontent.com/40076112/106053184-806fed80-60b8-11eb-8615-a0fc6c75cb4c.png)

It is a similar to the start window, we will have the "Recent scenes" with the Gif previews with 2 important diferences, on the left side we will have links to important OT articles, about the versions, about the development or about the new features, this is important, in this way we can connect more and more animators or interested parties to participate here in the community, testing new versions, finding bugs or joining the program as developers ...

On the right side there will be two buttons, "create scene" will open the Start window while the "open scene" will perform the function of the "Open another scene" button in the start window as well.

Talking about the "Recent Scenes" section, the idea is that when you save a scene, it will generate a gif of reduced size (300x200 max) of the first seconds, to serve as a preview when choosing which scene to open.

Here an animation of "Recent Scenes"

<br><br>
[![Watch the video](https://i.giphy.com/media/JD8x60abSmwMjWVjfY/giphy.webp)](https://i.giphy.com/media/JD8x60abSmwMjWVjfY/source.gif)
[ViewFullSize](https://i.giphy.com/media/JD8x60abSmwMjWVjfY/source.gif)
<br><br>

### Windows and information

Continuing with the idea of making OpenToonz a visually attractive, clear and bold software, I've redesigned some windows and better diagrammed their information to make it clearer...

In the following images the new design will be compared with the current design based on the current OpenToonz Darktheme. You can always click on the image to open it and see it in full size with better quality.

![Starting](https://user-images.githubusercontent.com/40076112/106055547-85826c00-60bb-11eb-860f-6089b0c94cff.jpg)
![Starting-concept](https://user-images.githubusercontent.com/40076112/106055562-87e4c600-60bb-11eb-996e-57fb381584b8.jpg)

![FirstWindow2](https://user-images.githubusercontent.com/40076112/106065504-67bc0380-60c9-11eb-9c93-52427fd33f59.png)

<br><br>
Each one of the types of levels would have a color, it will be easy to identify and remember, notice how green is the focus of the whole theme, while the K frames have higher contrast.

When we open the window to create a new level, we can quickly choose the type according to the color, while the other information is better organized and clear.
<br><br>

![Typesof2](https://user-images.githubusercontent.com/40076112/106065476-5f63c880-60c9-11eb-8b17-f8e42b6980de.jpg)
![Levels](https://user-images.githubusercontent.com/40076112/106065680-a2be3700-60c9-11eb-9ee1-9a42cca4295a.jpg)
![NewLevel](https://user-images.githubusercontent.com/40076112/107101423-494eba00-67e5-11eb-92ea-25feaa91f646.jpg)
![NewandOldLevel](https://user-images.githubusercontent.com/40076112/107101427-4eac0480-67e5-11eb-8d27-57f2035016f4.jpg)

<br><br>
The concept of acrylics would apply to any window that overlaps within OenToonz, blurring whatever is behind ... to name a few: Render/Output settigns, Render/Preview, Xsheet/Settings, Level/Settings, Scan&CleanUp/CameraCapture, File/Preferences... and others more...

<br><br>

![AcrylicsOn](https://user-images.githubusercontent.com/40076112/107101409-3a680780-67e5-11eb-873e-6703ddeeb771.jpg)

<br><br>
more examples of the green color as an emphasis of the theme, present in the tools, editable texts, buttons and more...
<br><br>

![Folders2](https://user-images.githubusercontent.com/40076112/106065468-5d9a0500-60c9-11eb-9739-bb238815127c.jpg)
![Green2](https://user-images.githubusercontent.com/40076112/106065470-5e329b80-60c9-11eb-8ccb-2749c3f923be.jpg)
![Playbar2](https://user-images.githubusercontent.com/40076112/106065471-5ecb3200-60c9-11eb-8b6f-656dba63de7f.jpg)
![PrevBar2](https://user-images.githubusercontent.com/40076112/106065472-5ecb3200-60c9-11eb-9231-6e0ce48b9c45.jpg)
![tools2](https://user-images.githubusercontent.com/40076112/107092696-09caa280-67d2-11eb-89be-0a8b09edba02.jpg)
![tool-settings](https://user-images.githubusercontent.com/40076112/106066857-81f6e100-60cb-11eb-9e62-40eea3012b6b.jpg)
![ToolSettinganimation-2](https://user-images.githubusercontent.com/40076112/106075514-c1c5c480-60db-11eb-923a-27981b9bc353.gif)

### For developers

While researching about Fluent Design, I found this page from Microsoft, where they talk and expose about the code and how to implement it ... I hope it can be useful.

[FluentDesign OpenSource](https://www.microsoft.com/design/fluent/#/)

[Acrylics](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic)

If the concept of acrylics is too complicated, we could improve the organization and structure of the windows and other parts of the concept exposed...

### What's next?

I deeply believe that if we all help from where we know best, we can make OpenToonz grow more and more, that is why I leave open the possibility that we implement this concept to all OpenToonz branding in general, I mean the web page (it seems that has not been updated in a long time), to the installer, the manual and other instances in design.

I hope you like the concept,
-JM

**Comment by age3rcm** [comment]
have you thought about the cursors for the tools?
they do feel very archaic, like something from a windows 95 program
i had once wondered if i could make different cursors for myself to work with it on my machine
but after seeing your propositions, i bet you could get good ideas for the cursors too!

**Comment by age3rcm** [comment]
i feel that the color for the logo is too bright, considering you propose the use of a dark theme and all
the transparent loading screen would leech more resources from the operating system? i recall something like this happening with windows vista back at the day, and opentoonz ofeers support to many Operational systems, and i bet these are not always used with a powerful machine, (imagining some third world countries running on 10 year old cheap computers :c   )

**Comment by juniormolina** [comment]
First of all, I'm glad that you write your comments, I hope you liked the concept...

> have you thought about the cursors for the tools?
> they do feel very archaic, like something from a windows 95 program
> i had once wondered if i could make different cursors for myself to work with it on my machine
> but after seeing your propositions, i bet you could get good ideas for the cursors too!

Do you mean the icons? recently @konero  updated most of the icons, in my opinion from the graphic design, the current icons (latest version) are incredible, if we compare them with another open source project, Blender in this case, their icons recently in the latest version were also redesigned based on new UI standards in design, and I think the ones made by @konero  fall into that line of standards, so I think it is not necessary for now to redesign all the icons again.

You can see some of the work he did briefly from here and keep exploring: https://github.com/opentoonz/opentoonz/issues/3699#issuecomment-767259557



> i feel that the color for the logo is too bright, considering you propose the use of a dark theme and all
> the transparent loading screen would leech more resources from the operating system? i recall something like this happening with windows vista back at the day, and opentoonz ofeers support to many Operational systems, and i bet these are not always used with a powerful machine, (imagining some third world countries running on 10 year old cheap computers :c )

Yes, the greens are a little brighter in the concept, contrasted with the dark mode this will help to quickly identify the tools without attacking our eyes too much as a pure white, if you notice, the tools and texts are currently quite bright, in the concept I use a gray to replace this and homogenize the dark theme, so that all the attention goes to green, to the tools that you have active.

You're correct, the idea of acrylics would work perfectly on a computer that can run Windows 10 (since the proposal in terms of code is also based on the code released by Windows to achieve these effects with the best performance possible, since win10 does this by default), of course if we are talking about performance, whoever feels that the acrylic mode is lowering its performance, could deactivate it at any time.

Now, with your question, it occurs to me that we could write code to recognize in the OpenToonz installation what operating system you have, this would enable or disable acrylics from the beginning and avoid any conflict with older computers.

In your personal opinion, what would you like to see applied from concept to future OpenToonz updates? What did you think of the idea of restructuring the organization of the windows, as well as the colors of the columns and when you create a new one?

**Comment by FerrLui** [comment]
I think your concept is amazing, really like it)).

пн, 15 февр. 2021 г., 08:06 Junior Molina <notifications@github.com>:

**Comment by artisteacher** [comment]
I love the idea of seeing the scene thumbnails instead of just the scene/project name.

> Yes, the greens are a little brighter in the concept, contrasted with the dark mode this will help to quickly identify the tools without attacking our eyes too much as a pure white, if you notice, the tools and texts are currently quite bright, in the concept I use a gray to replace this and homogenize the dark theme, so that all the attention goes to green, to the tools that you have active.

I'm concerned that the lack of contrast in certain areas would make OT harder to navigate on some screens. It would be especially challenging for those with some level of color blindness, whom rely more on contrast.

**Comment by age3rcm** [comment]
![image](https://user-images.githubusercontent.com/36406840/108019373-dcaf9880-6ff8-11eb-8daf-fe80a698d230.png)
this is the cursor for the pump tool
would you have any design idea to upgrade the cursor?
i am thinking about how they use the colors for street signs like the one for speed limit, that is red black and white
the cursors being made using these 3 colors would be easier to track and not lose when you work on a big screen or more than one monitor
![ellipse](https://user-images.githubusercontent.com/36406840/108019558-416af300-6ff9-11eb-9d65-c788f47e1185.png)
this one cursor i made myself to use at another program (toonboom)

**Comment by age3rcm** [comment]
![image](https://user-images.githubusercontent.com/36406840/108019742-a3c3f380-6ff9-11eb-87ef-f309b07727f7.png)
as for the color change, this is what i meant
i picked the color from the original icon and applied in the design you suggested

**Comment by RodneyBaker** [comment]
@juniormolina There has been enough interest in customization of Opentoonz UI elements that it seems clear there will be additional branding and visual customization in the future.

I am curious if any experts out there have good working knowledge that might take the current level of customization to the next level making custom 'skins'... or skin collections... a possibility for Opentoonz and its forks.  In this way those interested in updating/branding could present their skins to the community and developers as well as users could then leverage that to optimize the look and feel... and the experience... to meet their corporate and individual needs.  The master branch then would focus on one look and feel as a default skin which would be reviewed for periodic updates.  The primary benefit being that where the default skin does not meet the end users needs they could access available skins or customize their own to meet that need.   There might even be a secondary market for customized skins and Opentoonz brandings.

**Comment by RodneyBaker** [comment]
We are coming up on a year since this topic was opened.
While no major UI changes are getting into v1.6 the 2022 Development cycle can surely discuss the potential and the possibiities.

For now will close those as a proposal that has been set aside for the moment.
Let's revisit this for v1.7 and beyond.

**Comment by RodneyBaker** [comment]
Reopening as part of the current UI Scrub
