### ISSUE TITLE
Opentoonz  1.4 Warning. Failed to load 3dlut file  everytime i open the software.

### ISSUE THREAD

**Issue by mkprabh5642** [opentoonz/opentoonz#3711]
**Describe the bug**

**To Reproduce**
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by RodneyBaker** [comment]
Check your preferences to make sure that the 3dlut option hasn't been turned on accidentally and is looking for a .3dl look up table file.  Here's where you can find it in Preferences:

![image](https://user-images.githubusercontent.com/2576432/107115199-88562d00-6830-11eb-993a-f4cc32da085a.png)

**Comment by RodneyBaker** [comment]
@mkprabh5642 Were you able to discover anything else?

**Comment by mkprabh5642** [comment]
Hello Rodney.


Yes it did work. Thank you. I love opentoonz.

Thank you for your help.
Have a great day!
