### ISSUE TITLE
Some files may be missing (and solution)

### ISSUE THREAD

**Issue by WanderStudios** [opentoonz/opentoonz#3715]
When I load a saved scene it shows the message "Some files may be missing" and the scene opened is empty.
Older backups are also corrupted except for one that loads fine.
I compared the two files into a text editor and I found the corrupt line. I copied and pasted the correct syntax and it works.

![opentoonz_bug](https://user-images.githubusercontent.com/61146444/108090368-d2ce7980-707a-11eb-9e4c-5eaa23be251f.jpg)

**Comment by konero** [comment]
I think this might have been fixed already in the nightly build with https://github.com/opentoonz/opentoonz/pull/3501.

Someone will need to confirm it.

**Comment by RodneyBaker** [comment]
Yes, that was the fix @manongjohn submitted.
Highly recommended especially when troubleshooting to test using the latest nightly release.

Thanks @WanderStudios for the confirmation of the problem.
Hopefully you can also confirm the fix via recent nightlies.

**Comment by RodneyBaker** [comment]
Closing as being addressed via previous PR with fix available in the nightly releases.
@WanderStudios Please let us know if you continue to have related issues with the nightlies and/or v1.5 when it is released.
Thanks!
