### ISSUE TITLE
Smoothing option missing

### ISSUE THREAD

**Issue by Flairieve** [opentoonz/opentoonz#3716]
**Describe the bug**
Brushes other than the default brush (Without brush) are missing the smoothing option.

**To Reproduce**
1. Choose the without brush and it show a smoothing option.
2. Choose any other custom brush and it won't show a smoothing option.

**Expected behavior**
I except all the brushes to have the same smoothing option as what the default brush has in the editor.

**Screenshots**
Without brush selected:
![OpenToonz_0151EICTnQ](https://user-images.githubusercontent.com/16618467/108163889-9c0d5900-70a4-11eb-914b-8ff0990880cd.png)

With any other brush selected:
![OpenToonz_gRdyNYsYJN](https://user-images.githubusercontent.com/16618467/108163728-52247300-70a4-11eb-98af-74784cd66730.png)

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.4
 - GPU: NVIDIA GTX 750 Ti
 - GPU Driver Version: 456.71

**Comment by artisteacher** [comment]
The default brush isn't a MyPaint brush, so it has different options. This isn't a bug. Notice there are no max/min brush values either...

The MyPaint brushes have a large number of settings in the settings tab. You can probably find a setting that behaves similarly to the default brush's smoothing - perhaps try "Slow Position Tracking". 

The difference here is that each MyPaint brush style can have custom values for the each setting. So if I change the slow position tracking value to 5 for one style, I can set it to something different for another. This is a lot more flexible, but can require more setup.

**Comment by RodneyBaker** [comment]
Closing but please feel free to continue discussing the workflow of various brushes here.
Hang in there @Flairieve, in time it will all make sense.  :)
