### ISSUE TITLE
White boxes appear around brush when drawing

### ISSUE THREAD

**Issue by Flairieve** [opentoonz/opentoonz#3722]
**Describe the bug**
White boxes appear around where you draw when your drawing in a new blank frame.

**To Reproduce**
1. Select a blank frame on the level sheet.
2. Use any brush.
3. Use a drawing tablet to draw on the screen.
4. Hold down the pen and draw, white boxes start to appear around the brush.
5. Once you release the pen, the white background of the canvas appears.

**Expected behavior**
The expected behavior is for the canvas to turn white immediately when drawing.

**Screenshots**
https://user-images.githubusercontent.com/16618467/108616881-78108700-73c6-11eb-8e36-f872baca6dfb.mp4

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: v1.4
 - GPU: NVIDIA GTX 750 Ti
 - GPU Driver Version: 456.71

**Comment by RodneyBaker** [comment]
Apologies for the delayed response but I didn't want to steer you in the wrong direction.

You might look a bit closer at your current graphics card driver.
While it appears your driver might be the latest (or at least current) perhaps it is not the best for your case).
This could be one of those rare cases where you have to dial back a driver version to an earlier release.
Not sure but well work investigating...

**Comment by shun-iwasawa** [comment]
Confirmed the problem when drawing on Raster Level. Other level types seems to have no problem.
