### ISSUE TITLE
Cannot open scene

### ISSUE THREAD

**Issue by cameronsteele** [opentoonz/opentoonz#3727]
Greetings,

I was cutting a bunch of frames inside a sub xsheet. It crashed and I couldn't get back in. Now when I open the project, I receive the message:

"There were problems loading the scene [filepath]. Some files may be missing."

It then opens momentarily, all of my levels appear red, and it crashes.

I tried a .bak file from 5 minutes prior, but it also crashes. I presume this means there's something wrong with one of my levels?

The .tnz file appears to have a lot of information, but I wouldn't know where to begin debugging.

[Here is the project zip](https://drive.google.com/file/d/1mCPZpfPeoALoywkZIKz1VgTiaSmo5BBV/view?usp=sharing)

Any help would be greatly appreciated.

Thank you.

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.4
 - GPU: GTX1080

**Comment by RodneyBaker** [comment]
You have a keyframe corruption in your scene file which fortunately is fairly easy to recover from.
I'll upload a repaired copy  of your project.

If you want to know more about the problem we can get into that but I figure the most important thing is to recover your files and to be able to press on with work.

The keyframe bug that you encountered was fixed almost a year ago so I will recommend using a nightly release until such a time as the next version (v1.5) which will also contain the fix.  The nightly release also has many other bug fixes, features and enhancements... pretty close to what v1.5 will be.

[CAMMY Quick Sketch.zip](https://github.com/opentoonz/opentoonz/files/6020082/CAMMY.Quick.Sketch.zip)

Please note that the repaired file is named the same as the broken file so some care should be taken in keeping them separate.

**Comment by RodneyBaker** [comment]
Should you be interested here is the link to the latest nightly releases:

https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by cameronsteele** [comment]
Thank you very greatly for repairing my project. I apologize for reporting an old bug. I will move over to nightly releases and perhaps in the future come up with a real contribution to this wonderful software.

**Comment by RodneyBaker** [comment]
@cameronsteele I hadn't taken the time to actually view your animation as I had my troubleshooting hat on.
I just went in and played your animation.

Nice.  Love the gag!  :)

**Comment by cameronsteele** [comment]
@RodneyBaker You're exceedingly kind. That means a lot!
