### ISSUE TITLE
Bug in Full screen mode

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz#3734]
**Tools are invisible in full screen mode (im using single monitor)**
They are working, But They are invisible

**To Reproduce**
List steps to reproduce the behavior.
1. Install the last nightly version
2.Go to      Windows ->Toggle Main Windows Full screen mode
3.Try to save the file (for example)

**Screenshots**
The problem is that when i was trying  to rec my screen with OBS in video it is  working and visible. But in real its invisible. So when i rec it i dont see the tools , but in rendered video they are visible .I create 2 videos. 
1: i rec my screen with OBS- https://youtu.be/RqkFEdc9pns   (When i rec this i dont see tools, only aftrer rendering video they are shown)
2 I rec my screen with my phone _https://youtu.be/dVU0u_AkDEs  (There u can see that they are invisible in full mode)

**Device Information:**
 - OS: Windows 7
 - OpenToonz Version: [nightly build 2021-02-26]
 

 Sorry for my  english )

**Comment by konero** [comment]
I can confirm there seems to be a problem, my experience is a little different.

- Entering full screen and opening menus, the screen flashes black for a second
- Drawing on the canvas; when opening a menu after drawing, the canvas switches to displaying what was previously on the canvas before entering full screen mode, once the menu action is no longer active, the canvas goes back to the drawing made while in full screen, also affects thumbnail in Xsheet, etc

**Comment by artisteacher** [comment]
I'm not seeing a problem in macOS - but we use a native menu, not the one that's created for Windows.

**Comment by shun-iwasawa** [comment]
In the current nightly I confirmed the issue that when entering the full screen mode and try to save scene (via shortcut key) OT becomes uncontrollable as the full screen viewer stays on top of the modal dialog. I'll fix it.
