### ISSUE TITLE
Corrupted scene

### ISSUE THREAD

**Issue by slimeus21** [opentoonz/opentoonz#3735]
Hey, I don't know if this has already been said but when I try to open a certain scene there's an error message saying "There were problems loading the scene [scene name] Some files may be missing." I looked around my opentoonz stuff folder trying to find something which may be corrupted and I noticed that in my scene icons folder, the windows photo viewer wouldn't open the image for it even though it was a png like the others.
I was working on the scene just yesterday, but stayed up late working on it until 3am. I saved all before closing the program and turned off my computer after it closed, does this sound like something that can be fixed based on the information I gave?
**Device Information:**
 - OS: Windows
 - OpenToonz Version: OpenToonz V1.4
 - GPU: NVIDIA GeForce GT 635M
 - GPU Driver Version: 23.21.13.9135

**Comment by RodneyBaker** [comment]
This is likely the oft reported problem with keyframe corruption from the release from Jan 2020.
This was resolved in the nightly releases since May timeframe and will be in the 2021 v1.5 release (pending).

This would not explain why your PNG won't open but perhaps you have more than one problem going on at the same time.

If you can share the scene file at least we can check for the keyframe corruption issue and resolve that part of the problem.

**Comment by slimeus21** [comment]
Sorry about the file name lol i was messing around and named it after a song lyric

I also found that my frames from the project were saved into my OpenToonz stuff > sandbox > outputs folder as TIFs and those all opened properly if that means anything.

[lets goooo you know its baby nigga.zip](https://github.com/opentoonz/opentoonz/files/6062442/lets.goooo.you.know.its.baby.nigga.zip)

**Comment by RodneyBaker** [comment]
Unfortunately, your scene file corruption is not the keyframe issue.
It doesn't look like it can be recovered.
If you open the file in a text editor you'll see why.  Nothing but NULL entries:
![image](https://user-images.githubusercontent.com/2576432/109516020-591c8f80-7a6d-11eb-9e56-89fcaee8b37b.png)

You can still likely recover some of your project but if it was me I'd cut my losses and start a new scene... import the levels/images that still work... and press on

Sorry to be the bearer of bad news.

You might look to see if you have a scene file with a .bak extension as that would be a backup created at the time of the last save of the scene.  Perhaps that will not have the corruption.  Removing the .bak extension will be enough for Opentoonz to recognize the .tnz extension and open the scene file.

**Comment by slimeus21** [comment]
Well that sucks, but I'm glad that you could inform me more about the situation.

I tried using the .bak file earlier but I may have done it wrong, if I remove the .bak from the backup file and delete the old one will Opentoonz open the backup or is there something else I should do?

**Comment by RodneyBaker** [comment]
Yes, you will want to either rename or remove the old scene or else you'll get a conflict saying there is already a file by that name in the directory.   The .tnz file should open as normal although I suspect it is likely corrupt as well...
Still worth a shot at it working though.

**Comment by RodneyBaker** [comment]
I will also recommend you upgrade to a recent nightly release as using the one from more than a year ago (linked via the Opentoonz website) will still have known issues.  The latest nightly release can be found here:

https://github.com/opentoonz/opentoonz_nightlies/releases

The v1.5 release should be out sometime in March and that will largely be the same as the most recent nightly release.

**Comment by slimeus21** [comment]
Okay, thanks for the feedback!
