### ISSUE TITLE
Feature Request: H.264 export

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#374]
With Apple no longer supporting Quicktime on Windows, the secure thing is to uninstall Quicktime from our systems.  That leaves no H.264 export option in OpenToonz.  The two most obvious solutions are X.264 and Windows Media Foundation.

X.264 is not really an option, however, since it is GPL software and would clash with OpenToonz license.  It seems like the only other option is to use Windows Media Foundation for export.  If there is another open source solution, I would prefer that, but I don't know of one.

I realize that many folks just export as an image sequence and load into a compositor.  I am an animation teacher and need a simple solution for my kids to export.  

I don't mind building this myself if someone can show me where to hook into the output stream in OpenToonz.  I am new to Qt and still figuring things out.

**Comment by kogaki** [comment]
Yes, this is critical issue. And not just for Windows. For now, module for exporting video is compiled for 32bit architecture. This is because it depends on legacy libraries. Best solution is remove dependency on Quicktime and use current alternatives for cross platform (not Windows Only). I think libavcodec (https://www.ffmpeg.org/libavcodec.html) can be a candidate. Anyway, it takes a time to implement such a big feature...

**Comment by kogaki** [comment]
FYI: Quicktime is called from <https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/image/mov/tiio_movW.cpp> in Windows. We can dispose of `Quicktime` with replace that source entirely.

**Comment by turtletooth** [comment]
The problem with ffmpeg/libav is that they are GPL which would force all of OpenToonz to be GPL.
I haven't yet found a solution that is both non-GPL and not platform dependent.  The only option I can think of right now is to build platform specific options in.  Quicktime is safe on Macs, but is a security issue in PCs.  Windows Media Foundation is the only non-GPL option I can find for Windows.

@kogaki while we are talking about exporting, could you point me in the direction of where to look to fix AVI and tif exports using black as the transparent color?

**Comment by turtletooth** [comment]
libav is LGPL unless you need  H.264 export for which they use X.264 which is GPL.  It's frustrating, I know.  I've been looking for a solution for a while now.

**Comment by kogaki** [comment]
I see. It is hard to use x264 with OpenToonz. IMO, we should start from exporting AVI or MOV without QuickTime that can be done with libav. But it is OK to add H.264 feature just for windows.

**Comment by walkerka** [comment]
There's a BSD licensed H.264 codec from cisco. I haven't try it but it supports all the major platforms.
https://github.com/cisco/openh264

You can also use shell script (through QProcess) to call ffmpeg command line tool to convert formats. In this way your program can export all the formats ffmpeg supports and doesn't need to be GPLed (because they're two processes). But users have to download ffmpeg by themselves and put it into PATH or program folder.

**Comment by turtletooth** [comment]
There are a few options to consider here.  OpenH264 is compatible with the license and works with ffmpeg/libav.  It only supports baseline profile for h264 which might be satisfactory since most users needing high end export will probably use an image sequence anyway.

If you want to make sure that main and high profiles are supported, it looks like the only options there are platform specific.  Quicktime on Mac and Windows Media Foundation on PC.  The downside here is multiple platforms to support but you might get better results.

If you decide on a direction, I can start looking at how to pull it into OT.  This is a big priority for me, so I am glad to help.

**Comment by kogaki** [comment]
@turtletooth 
I agree to you. Exporting mp4 is not for professional use and optional feature, so OpenH264 can fill the needs. To clear our stance, I think  render for mp4 can be separated command as `instant preview render`.

**Comment by turtletooth** [comment]
So I finally got ffmpeg compiled with openh264.  I am new to all this, so it took me a while to figure it out.  

It is definitely going to be worth it.  I exported a 2 second avi from OpenToonz - 482MB.  I converted it to mp4 in ffmpeg - 103KB.  Thats KB!  I need to play with the quality and bitrate, so that will probably go up a bit, but this will be awesome when I get it fully working.

**Comment by turtletooth** [comment]
merged #624
