### ISSUE TITLE
Improve File Browser to refresh the current folder items automatically

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#375]
For now, changes of the items (i.e. create/rename/delete of files) in the current folder are not reflected automatically to an item viewer panel of the file browser. You need to exit and re-enter the current folder in order to refresh the items, which is quite troublesome.

**Comment by CodyEakins** [comment]
I'd almost rather have it so that OpenToonz utilizes an OS's native file explorer rather than relying on its current alternative... That way, people are used to it, and keyboard shortcuts & customization are available.

**Comment by shun-iwasawa** [comment]
I understand that the users are familiar with OS's native file browser, but the File Browser panel has some advantages specialized for this software such as;
- uniting the sequential raster image files and display as one level,
- collecting the link to project folders under each project, etc.  
So, IMO, it would be better to keep using it and enhance the consistency with OS's native ones.

**Comment by shun-iwasawa** [comment]
merged
