### ISSUE TITLE
text and buttons get way too big on tablet screen??

### ISSUE THREAD

**Issue by CatLady808** [opentoonz/opentoonz#3756]
on my main laptop screen, the text and buttons are too small and they frustrate me. but then when i move the window to my tablet screen, they are WAY too big to get any work done? i can't find a setting that's doing this it was fine the first time but the second time i opened the app it just started doing this.

**Comment by RodneyBaker** [comment]
There are two somewhat related things that play into this kind of display problem.
The first is graphics drivers which in a known issue especially with intel graphics.
There is even a link on the Opentoonz website that outlines that issue and provides a link for updating the drivers.

The second concerns multiple monitors of which there has been some progress recently but not all setups have been addressed as of yet.  The workaround however is generally to start by setting the tablet as the primary screen and seeing if that won't resolve the issue.  If not, the most likely option is to have the tablet and the monitor mirror/duplicate each other.

As always when troubleshooting an issue it is going to be wise to test with a recent nightly release.
This is especially the case when a fix has been submitted that relates to the problem... such as a recent fix related to multiple monitors.

So, I suppose I will recommend first updating to a recent nightly release.
If for some reason of production this is not considered a viable option for the current production cycle I would make plans to update as soon as that cycle ends.  Then if the update doesn't resolve the problem explore thoroughly the workarounds such making the tablet the primary screen and mirroring the screen on both monitors.

Link to nightly releases:  https://github.com/opentoonz/opentoonz_nightlies/releases

There was a fix for multiple monitors in full screen about a week ago.
As nightly releases are cumulative that fix will be included in the latest release as well.

**Comment by RodneyBaker** [comment]
Closing as a duplicate likely resolved via graphics card driver update.
@CatLady808 Please advise if this is not the case and we will continue the investigation.
