### ISSUE TITLE
Mac Opentoonz crash importing png

### ISSUE THREAD

**Issue by Azusapink** [opentoonz/opentoonz#377]
Whenever I go to the browser tab to import a png to column Opentoonz crashes. 

is there a fix or work around?

**Comment by Rayek** [comment]
Is that PNG an indexed 8bit file? OT does not import indexed PNG files. You must convert those to full 24bit with/without transparency before import.

**Comment by Azusapink** [comment]
i've been trying to figure out how to convert an image to a full 24bit png all day. Any tips?

**Comment by Rayek** [comment]
Ah, not sure - I work on WIndows, and use Photoline for my image editing nowadays since leaving Adobe's Digital Serfdom. It should work in Affinity, though. Would you mind attaching a sample PNG file to your next message, so I can test it on Windows? This would be helpful in determining whether it is a Mac issue or not.

**Comment by Azusapink** [comment]
ok here you go. thank you for the help
![ottest4](https://cloud.githubusercontent.com/assets/5882245/15661425/ea1ea4b0-26ac-11e6-8a43-c8c2926d9224.png)
![24-bit check](https://cloud.githubusercontent.com/assets/5882245/15661427/ecab4f80-26ac-11e6-8ce8-8ed4b0338e08.png)

**Comment by Rayek** [comment]
Imports fine in the latest Windows build.

**Comment by kogaki** [comment]
Hmm. In my OSX, I can import the file.

![2016-05-31 12 26 25](https://cloud.githubusercontent.com/assets/17926501/15662380/ecb8b32c-272a-11e6-98ea-9cb8fdb005a4.png)

**Comment by Azusapink** [comment]
Are you importing through the browser tab? can you edit the image or does it say the frame is uneditable?

do you have the nightly Build version or the Stable release?

**Comment by Rayek** [comment]
I imported the file via the browser tab, as well as dragging and loading a level.Works without a hitch.

**Comment by kogaki** [comment]
I'm using latest nightly (nightly_5df182a8627826c7920001c6db934a3de6e5b65a).
Both drag and drop and browser works.
Of course, it's editable.

If you can provide error message and stacktrace, we might clarify the problem.

**Comment by Azusapink** [comment]
Im using nightly build 1.0.2 Built May 29th. I don't get a message at all OT just closes when i either drag in the image or go through the browser tab.

I am also using El Capitan for my mac
![screen shot 2016-05-31 at 9 27 41 pm](https://cloud.githubusercontent.com/assets/5882245/15696518/c0bca444-2776-11e6-920f-1687c29544ca.png)

**Comment by kogaki** [comment]
Could you try
1) other format (.psd, .tga, etc...)
2) other releases (1.0.1)

**Comment by Azusapink** [comment]
i tried the other formats and got the follow
1.) PSD I get " this image is no editable" I searched ever where to try and see if i could get it to edit, but couldn't find anything.
![screen shot 2016-06-01 at 10 47 49 pm](https://cloud.githubusercontent.com/assets/5882245/15733403/4ba45712-284b-11e6-8243-f4509615e447.png)
2.) TFF when i use paint brush or eraser you can see any changes being made but you can tell that the tools are activated
3.) TGA works so far!!! can edit and paint, but can't use bucket fill.
