### ISSUE TITLE
Menu items icons are merged with text in the viewport menu on linux

### ISSUE THREAD

**Issue by Hexadec-0x** [opentoonz/opentoonz#3777]
**Describe the bug**
Menu items icons are merged with text in the viewport menu.

**To Reproduce**
List steps to reproduce the behavior.
1. Be on Linux (Tested only on linux at the moment)
2. Download the following nightly: https://github.com/opentoonz/opentoonz/actions/runs/661502020
3. Click on the menu under the viewport (check the screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/70974028/111526397-fb6f8f00-875e-11eb-8117-c38592fd3e7b.png)

**Device Information:**
 - OS: Linux Mint 20.1
 - OpenToonz Version: Nightly (2021-03-17) https://github.com/opentoonz/opentoonz/actions/runs/661502020
 - GPU: NVIDIA GTX 1070
 - GPU Driver Version: 460.39

**Comment by RodneyBaker** [comment]
I believe this has been reported and possibly has a posted solution but regardless, thanks for the validation @Hexadec-0x

**Comment by konero** [comment]
I'll look into it.

**Comment by konero** [comment]
I had a quick look, it looks like the Qt 5.12 bug, is it possible the GitHub Actions builds are not using 5.15 but 5.12 instead?

Perhaps something like this can help: https://github.com/jurplel/install-qt-action

If someone can test building on Qt 5.15.2+ it would help confirm it.

**Comment by shun-iwasawa** [comment]
I introduced a default style sheet to fix the problem, but applied only for Qt 5.9.x .
https://github.com/opentoonz/opentoonz/commit/668c9b00ce231067015eec32b8263834b977107d

The Linux artifacts seems to be using Qt 5.12.8 so I'll expand the condition for applying it.
