### ISSUE TITLE
I accidently messed up my room and I want to get the default room settings back. How can I do that? I have already tried the button in windows that says reset default room settings but it didnt work. Please help!

### ISSUE THREAD

**Issue by EnderTobias** [opentoonz/opentoonz#3793]
**Question**
Ask a question related to OpenToonz.

**Comment by artisteacher** [comment]
Try restarting OT.

**Comment by EnderTobias** [comment]
All you have to do for that is to close it right? Cause ive done that
plenty of times.

**Comment by artisteacher** [comment]
Try closing any floating, undocked windows. Then reset again, close and restart OT.

**Comment by EnderTobias** [comment]
How do you restart it?

**Comment by manongjohn** [comment]
1. Go to `Preferences -> Interface`
2. Change `Rooms` to `StudioGhibli`, then change it back to `Default`.
3. Click on `Windows -> Workspace -> Reset to Default Rooms`
4. Close and reopen OpenToonz

**Comment by RodneyBaker** [comment]
Closing but please feel free to continue the troubleshooting discussion here in this report.
@EnderTobias Let us know if you continue to experience problems resetting the default rooms.
