### ISSUE TITLE
Using V1.5: Can the toolbar expander be expanded by default

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#3804]
I thought that there was a fix to have all of the toolbar buttons shown by default. I see lots of comments/confusion from users who can't find a tool, simply because they have to click the expander. The expander button looks like just another button, so it's not obvious that you can expand it. It would save a lot of support time if all of the tools were shown from a fresh install.

Is there any chance that this could this be changed before 1.5 is released?

**Comment by DarrenTAnims** [comment]
Is this a possibility before release @shun-iwasawa ?
I'd hope that it should just be changing a room or preference file.

**Comment by artisteacher** [comment]
It would be really helpful for new users.

**Comment by gab3d** [comment]
I support it too.
Not a big deal, but it'd be nice.
