### ISSUE TITLE
Arc & multiarc weird behavior with pen

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3813]
**Describe the bug**
It seems there is issues with pen using theses tools

**To Reproduce**
List steps to reproduce the behavior.
1.create a level
2.use arc

 or multi arc on canvas

with mouse thats seems works normal

**Screenshots**
![arc   multi arc issues](https://user-images.githubusercontent.com/29790512/112236842-abeb0080-8c41-11eb-87fe-b1b06804d909.gif)

W10 cintiq companion 2 OT 1.5 RC

**Comment by shun-iwasawa** [comment]
Fixed by #3823
