### ISSUE TITLE
Crash on Recording Audio

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3819]
**Describe the bug**
OpenToonz crashes after clicking the record button on the Record Audio window. Seems similar to #3762 except I'm on Windows 10.

https://user-images.githubusercontent.com/60277069/112393070-afb96a00-8cb7-11eb-925d-ede3fb866072.mp4

**Device Information**
OpenToonz Version: OpenToonz V1.5 Release Candidate
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: Wacom Cintiq Pro 24

**Comment by shun-iwasawa** [comment]
Thank you @RattusaurusRex for reporting.
I could reproduce the crash. It seems to be the same problem as #3762 . I'll apply the same fix.
