### ISSUE TITLE
Record Audio - Linux

### ISSUE THREAD

**Issue by andeon** [opentoonz/opentoonz#3827]
It is present in older versions, maybe for fix the problem need to link libs or set paths.

Whoever is testing it, remember to turn on or unmute the microphone.

> Testing the Build https://github.com/opentoonz/opentoonz/actions/runs/689530194, I receive this:
> 
> QLayout: Attempting to add QLayout "" to AudioRecordingPopup "", which already has a layout
> QMediaRecorder::FormatError : Not compatible codecs and container format.
> QMediaRecorder::FormatError : Not compatible codecs and container format.
> Could not create a media muxer element: ""
> QMediaRecorder::FormatError : Failed to build media capture pipeline.
> 
> 
> But it also doesn't work in previous versions. Here the screenrecord:
> 
> 
> https://user-images.githubusercontent.com/11843239/112724689-576eac00-8ef3-11eb-8ef1-c816bc9ef1d8.mp4
> 
> 
> 
> I recorded how Morevna Build behaves:
> 
> https://user-images.githubusercontent.com/11843239/112724758-9c92de00-8ef3-11eb-8ba7-856a9b0a7e88.mp4

_Originally posted by @andeon in https://github.com/opentoonz/opentoonz/issues/3825#issuecomment-808747697_

**Describe the bug**

The Record Audio not work , apparently not find the function or call the lib.

**To Reproduce**

1. Try record the audio, [Windows > Record Audio]

**Device Information:**
 - OS: Linux 64 bits (KDE Neon)
 - OpenToonz Version: Opentoonz 1.5RC, Opentoonz 1.4
 - GPU: Nvidia Geoforce 940MX
 - GPU Driver Version: 450.102.04

**Comment by RodneyBaker** [comment]
Thank you @andeon for the follow up and feedback.
Much appreciated!

**Comment by justburner** [comment]
Can you please test #4164 artifact?
It may solve this issue since it doesn't use QAudioRecorder anymore. *(QAudioRecorder Inherit QMediaRecorder)*

**Comment by andeon** [comment]
This PR fixes the issue.

PS: I installed gstreamer1.0-plugins-bad together with gstreamer1.0-plugins-good to make it work properly in my distro.

If you use Debian-based distributions:
```
sudo apt update
sudo apt install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad 
```

**Comment by justburner** [comment]
Thanks a lot for testing the PR, appreciated :)
