### ISSUE TITLE
Bug with Elipse tool when drag in a new level

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#3829]
https://user-images.githubusercontent.com/74098734/112737332-b3681d80-8f51-11eb-94bb-dbeb56f01397.mp4

When you drag to draw an Elipse and create a new level, the shape don't go from your mouse like the second shape in the video.

**Comment by andeon** [comment]
Probably related to the same issue: https://github.com/opentoonz/opentoonz/issues/3820

See that the linked PR fix works for you.

**Comment by shun-iwasawa** [comment]
Please try once the nightly build is updated including #3828

**Comment by F-Burning** [comment]
It works perfectly

Thank you so much :D

**Comment by RodneyBaker** [comment]
Closing.  Reported as fixed by #3828.
