### ISSUE TITLE
Menu icons color issue in macOS light and dark modes

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#3837]
**Describe the bug**
Icons are too light for the native menu on macOS Mojave. I haven't had a chance to check out other versions of macOS yet.

**Screenshots**
<img width="212" alt="Screen Shot 2021-03-30 at 12 12 46 PM" src="https://user-images.githubusercontent.com/21159116/113021694-d7924d00-9151-11eb-9238-9d09d2776963.png"><img width="289" alt="Screen Shot 2021-03-30 at 12 12 22 PM" src="https://user-images.githubusercontent.com/21159116/113021709-da8d3d80-9151-11eb-93d1-97715940c6fb.png">

**Device Information:**
 - OS: [macOS Mojave]
 - OpenToonz Version: [Nightly (2021-03-30)]

**Comment by konero** [comment]
I think this might be why I disabled them before, a number of things to consider:
- **[USER]** Switch to dark mode on macOS if these are important
- **[USER]** Switch to light theme in OT with dark icons
- **[DEV]** Disable these showing in menus for macOS only as quickfix (maybe a pref option)

I know it's not ideal, as for an actual solution I think maybe one way would be to separate the main menu and command bar so they create unique icons each if they don't already, create a way to detect macOS dark mode, then where the main menu is created and calls `createQIcon()` pass a QColor as an argument into the `recolorPixmap()` calls, and pick black or white depending if macOS has dark mode active.

That's above my skill level though! Not even sure if detecting macOS dark mode is possible or not. 😟

**Comment by artisteacher** [comment]
You are right that this is a light/dark mode issue. The white menu icons are too light in light mode. The black icons aren't ideal in dark mode.
![Screen Shot 2021-03-30 at 2 11 43 PM](https://user-images.githubusercontent.com/21159116/113036187-f7317180-9161-11eb-8e40-778a8ecb9104.png)

I don't have strong feelings about the icons being visible or not in the menu for macOS. They are a little busy, yet helpful. 

I do feel strongly that the user shouldn't have to change the system theme to give the menu icons better contrast. Users also shouldn't have to experiment with theme/icon combinations to find one that displays properly for the light or dark mode.

**Comment by artisteacher** [comment]
Now that the icons are optional in the menu, this is no longer an issue.
