### ISSUE TITLE
Bug: AVI settings on Windows 10 crashes OT.

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#384]
On Windows 10, when I choose AVI as output format and click settings, OT crashes.  This does not happen on Windows 7.

**Comment by turtletooth** [comment]
#653 is the fix.  Looks like it isn't necessarily a Windows 10 thing, but a lvcod64.dll thing.  Logitech dll

**Comment by RodneyBaker** [comment]
REF also:  https://github.com/opentoonz/opentoonz/issues/46
