### ISSUE TITLE
Brush tool lost antialiasing when you draw below (Bug?)

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#3847]
https://user-images.githubusercontent.com/74098734/113440807-070cb800-93e5-11eb-90bc-8893ea33e2e4.mp4

To reproduce:

-Create a Toonz raster level
-Create a second color
-Take the brush tool without pencil mode
-Choose Under all
-Draw with the second color

**Comment by RattusaurusRex** [comment]
What behavior were you expecting?  ToonzRaster levels don't have the ability to blend colors. Leaving the anti-aliased pixels in place doesn't exactly look great either: 
![image](https://user-images.githubusercontent.com/60277069/113452382-b41d0b80-93b8-11eb-93b0-a81cd50f4fb2.png)

**Comment by F-Burning** [comment]
Hmm, I see, didn't know it!

I thought that the lines were literally positioned behind at "different levels" and they didn't touch each other.
