### ISSUE TITLE
Can't find new nightly builds?

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#386]
Hello guys, I just want to check if everything is ok cuz it passed too many day since we saw latest nightly build (latest commit was 5 days ago). Are you gonna stop with this tradition of posting nightly builds or?

**Comment by kogaki** [comment]
We stop deploying new changes because we have serious bugs ( #364 ) in nightly builds. It will be soon resolved and new nightlies will be appear. Please be patient. Thanks.
