### ISSUE TITLE
(Proposal) Use system libtiff rather than included libtiff

### ISSUE THREAD

**Issue by jointri** [opentoonz/opentoonz#3864]
As of december of last year, libtiff 4.2.0 is the latest version. Is that good enough to no longer need to use the included libtiff? It would make libtiff 4.2.0 as another dependency, but being able to use the system libtiff would be great.

**Comment by jointri** [comment]
I have an update. I managed to compile OpenToonz with the libtiff directory deleted and used the system libtiff on arch linux. I had an undefined reference error when linking, but the binary was still created. I can fix the undefined reference error later, but it seems it's possible to compile using just the system libtiff. @RodneyBaker what do you think?
![arch linux](https://user-images.githubusercontent.com/81046576/113639041-4dad1d00-9646-11eb-98ea-533816d4f5fb.png)
[one.txt](https://github.com/opentoonz/opentoonz/files/6261090/one.txt)
[two.txt](https://github.com/opentoonz/opentoonz/files/6261091/two.txt)

**Comment by manongjohn** [comment]
Per @shun-iwasawa in https://github.com/opentoonz/opentoonz/pull/2499#issuecomment-466259830 when they were trying to get homebrew libtiff to brew for macOS builds, Opentoonz uses a custom libtiff.

Latest versions of libtiff should probably be reviewed to see if the customization is still needed.

**Comment by shun-iwasawa** [comment]
Comparing `one.txt` and the original `tiio_tif.cpp` , it seems that you just removed the line for reading 16bpc TIFF.
Regarding TIFF I/O I think we need to take another way to migrate versions keeping availability of 16bpc.

Regarding `two.txt` ( which is originally `tiio_tzp.cpp` ), it is for I/O of TZP files. TZP had been a special format used in Digital Video's TOONZ 4.x . Since TOONZ 4.6 is a 20-year-old software and not all users may need the compatibility with it (we do need it, though) , I think including TZP I/O feature can be optional in the future.

**Comment by jointri** [comment]
> Comparing `one.txt` and the original `tiio_tif.cpp` , it seems that you just removed the line for reading 16bpc TIFF.
> Regarding TIFF I/O I think we need to take another way to migrate versions keeping availability of 16bpc.
> 
> Regarding `two.txt` ( which is originally `tiio_tzp.cpp` ), it is for I/O of TZP files. TZP had been a special format used in Digital Video's TOONZ 4.x . Since TOONZ 4.x is a 20-year-old software and not all users may need the compatibility with it (we do need it, though) , I think including TZP I/O feature can be optional in the future.

If you or anyone else wants to test what I did, just do the following (I tested this again on arch linux):
1. Delete the included libtiff directory
2. tell cmake to find libtiff installed in the system location such as `cmake ../sources -DTIFF_INCLUDE_DIR=/usr/include -DTIFF_LIB=/usr/lib`
3. you WILL get a few errors, however, these errors most definitely can be fixed because I either modified them as the compiler suggested or outright deleted them. Just need to fix a few errors, I'll post a few errors later when I get the chance because I'm on a different computer right now.

**Comment by jointri** [comment]
I'll just leave here where I started getting the errors. The included text file has the first two errors and then what happened after I renamed two functions. I guess we could chip this away one little bit at a time, if anyone has a different idea how to tackle being able to use system libtiff, that would be great to know.
[ERROR.txt](https://github.com/opentoonz/opentoonz/files/6265398/ERROR.txt)

**Comment by jointri** [comment]
@shun-iwasawa How difficult or how much work would it be to get OpenToonz to use the system libtiff rather than the included one?

**Comment by shun-iwasawa** [comment]
I've checked the difference between official libtiff 4.0.3 and our customized one (the customization had been done by Digital Video) . The major changes done in the customized libtiff was adding capability to handle 16 bit per channel (64bit-RGBA / 48bit-RGB) TIFF format without compression to 8 bit-per-channel.

If the latest libtiff natively supports such formats or there is another way to handle 16 bit per channel images without compression, I think the migration to system libtiff would be feasible. I don't have enough information to achieve it yet.

**Comment by jointri** [comment]
Just a heads up @shun-iwasawa that the december release of libtiff has been replaced with a new version from last month.
https://www.asmail.be/msg0055059467.html
https://libtiff.gitlab.io/libtiff/v4.3.0.html
Could you look into that release if the replacement for libtiff is ready yet?

**Comment by RodneyBaker** [comment]
Closing this as part of general housekeeping.
We need to revisit this periodically until such a time as the underlying issues are resolved.
