### ISSUE TITLE
Right-click with stylus acts as left-click

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3869]
**Describe the bug**
When pressing the right-click button on my pen, a circle appears on my cursor and starts acting like left-click, even though I am not even touching the screen with the pen tip.  It makes the program much more difficult to use because it can cause the brush to start drawing, the playhead to move, the selection of cells to change, etc.  None of the tablet settings in the Preferences changed this behavior.  Turning off Windows Ink in Wacom Tablet Properties got rid of this behavior, but disabled pressure sensitivity in the program.

**To Reproduce**
1. Right-click with stylus to left-click
2. Hold right-click with stylus to draw

**Expected behavior**
Opentoonz 1.5 RC 2 lists "Custom Qt with Wintab support" as one of its features, so I expected it to act like this build (which worked great): https://github.com/opentoonz/opentoonz/pull/3823 

**Screenshots**
In this video, I only press right-click on my stylus.  I don't even touch the pen tip to my screen at all.
https://user-images.githubusercontent.com/60277069/113779233-40de0700-96e2-11eb-95c5-96df47fa042d.mp4

**Device Information:**
OpenToonz Version: OpenToonz V1.5 Release Candidate 2
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: Wacom Cintiq Pro 24

**Comment by shun-iwasawa** [comment]
Confirmed the problem. Thank you for reporting!

**Comment by openanim** [comment]
But where is the link for opentoonz V1.5 R.C Candidate 2 ?
Is this the latest night version ?

**Comment by shun-iwasawa** [comment]
I confirmed that the Qt libraries included in RC2 package are not proper.
I'll fix it tonight. Again, thank you @RattusaurusRex for reporting the issue and so sorry for the trouble!

**Comment by shun-iwasawa** [comment]
@RattusaurusRex I've updated the v1.5rc2 release package. Could you please try it?

@openanim Here it is : https://github.com/opentoonz/opentoonz/releases/tag/v1.5.0rc2

**Comment by RattusaurusRex** [comment]
@shun-iwasawa Seems to be working great now! Thank you.
