### ISSUE TITLE
Project Files got Deleted when Uninstalled

### ISSUE THREAD

**Issue by merlin2v** [opentoonz/opentoonz#3872]
**Is your feature request related to a problem? Please describe**
I just decided to install the latest version so I installed the newest version and uninstalled the other versions. Now all my files are gone and well... I didn't think the uninstaller would delete

**Describe the solution you'd like**
Please ask in the uninstaller before removing the files with work from my computer. I just lost all my work and all the work I have ever done so I am honestly still in a bit of a shock as a try to see if there is any slight chance I can recover what I lost. 

I am not sure what else to say.

**Comment by RodneyBaker** [comment]
The installer shouldn't remove your project files so they should still be there.
Perhaps you set the stuff directory to be some other location than the default either before or during this install?

If you manually deleted the Opentoonz stuff directory then the files would be in your recycle bin (Windows).

Look a little bit closer and you should be able to find your files.

**Comment by shun-iwasawa** [comment]
As @RodneyBaker pointed, 
OT's uninstaller is not made to remove your works.
The software binaries ( in `C:\Program Files\OpenToonz` by default ) will be deleted, but the stuff folder ( `C:\OpenToonz stuff` by default ) should be kept unchanged because there may contain user's own work and personal settings.

**Comment by merlin2v** [comment]
Thankyou I panicked when I saw the project folders empty. Sorry for the bother and thankyou for your help.

**Comment by RodneyBaker** [comment]
All good @merlin2v!  Glad you were able to find your files.  :)
