### ISSUE TITLE
Korean translation files...

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#3874]
@kimpd shared this Korean xls file via discord.
I'm not sure why it's in this format but want to at least bring it to others attention as they might be able to assist.
I think @manongjohn worked with him last year and might have been the middle man for translating.

cc:  @Savraska2 @gab3d @beeheemooth @shun-iwasawa 

[v1.4_Korean_Translations_modify_new_1.xlsx](https://github.com/opentoonz/opentoonz/files/6276695/v1.4_Korean_Translations_modify_new_1.xlsx)

**Comment by shun-iwasawa** [comment]
Hmm, the file seems to contain only 6 English terms without translations.

**Comment by RodneyBaker** [comment]
I apologize.  Something was apparently lost in translation.  ;)
I just mentioned to @kimpd that I would pass the file on and didn't even consider the contents.

I will ask some questions and see if we can make progress in adding the actual Korean language translation.

**Comment by RodneyBaker** [comment]
Closing this as I believe he has made contact via a different github report.
