### ISSUE TITLE
Importing Audio in Opentoonz not working 

### ISSUE THREAD

**Issue by ChampagneJuliam** [opentoonz/opentoonz#3876]
**Describe the bug**
When importing audio ( tested only WAV files) it only fills one frame of the timeline and there is no audio played 
2. When you import another audio into the same level where the first was imported then the level turns into a sound level(although the audio is not properly imported as it only fills one frame see pics below for clear explanation) 
3. When added also in recent versions (candidate 2) It doesn't even allow me to delete the level strip frame (although I can delete the whole level)
4. The sound level frames also are not able to being expanded either 

*The WAV file used for testing vary from 8MB to 21MB 

**To Reproduce**
List steps to reproduce the behavior.
1. Pick a WAV sound file and drag it into Opentoonz Timeline 
2. You can either choose  "Import" or "Load" options to import the audio file
3. repeat step 1 and 2 in the same level to turn the level into an audio level.

**Screenshots**
1.First WAV file imported in col 2 

![1_imported_Wav_file](https://user-images.githubusercontent.com/47542031/114034099-cb0aa480-9875-11eb-85c8-e955d475fd9f.png)
2. Same Wav file imported into col2 for second time ( now the UI turned into sound level)

![2_second_wav_file_imported](https://user-images.githubusercontent.com/47542031/114034127-d1008580-9875-11eb-8646-4c28852dd633.png)

**Device Information:**
 - OS: Windows 10 
 - OpenToonz Version: nightly build 2021-04-08 (tried also on Release Candidate 2 )
 - GPU:NVIDIA RTX 2080 

( Yes I've uninstalled all previous versions of Opentoonz before doing this + manually deleted all Opentoonz related folders)

**Comment by RodneyBaker** [comment]
I recall having something like that happen when I was using a WAV file that was not of the proper type.
You might adjust the WAV file to see if that is true in your case as well.

**Comment by artisteacher** [comment]
That's the common behavior if the audio file is 32bit. Only 8bit and 16bit audio files are currently supported. It should probably refuse to load and give an error message stating that only 8bit and 16bit audio is supported.

**Comment by artisteacher** [comment]
Though enough people try to use 32bit files, that it would be better to support them too.

**Comment by RodneyBaker** [comment]
I suspect OT an use the 32bit WAV as well via the undocumented FFMPEG import trick.
That's where we temporarily change the extension of the .WAV to say MP3 so that OT will open and process it with FFMPEG.
FFMPEG should then see it as the 32bit WAV and process it as it doesn't care about file extensions but instead reads the internal data to ID the file.

Would have to test this theory of course.

If OT cannot support then it would be ideal to have unsupported audio files be flagged as unsupported.
If the FFMPEG trick works I'd love to see a feature added that allows a user to 'Try to Import' the file which would then perform the task of opening and processing the file via FFMPEG.  OT can open many 'unsupported' files in the manner.

**Comment by ChampagneJuliam** [comment]
Hey,

thanks for the quick replies, tried to import WAV files recorded from my phone and it seems to work (those were at 44.1kHz sample rate)
So like you guys said it was the bit depth (as the examples used were 32bit at 44100 sample rate)
*artisteacher thanks saw the info  in the documentation*


> If OT cannot support then it would be ideal to have unsupported audio files be flagged as unsupported.
> If the FFMPEG trick works I'd love to see a feature added that allows a user to 'Try to Import' the file which would then perform the task of opening and processing the file via FFMPEG. OT can open many 'unsupported' files in the manner.

> Though enough people try to use 32bit files, that it would be better to support them too.

If it's doable to add the 32 bit support out of the box in the software that would be great :) ( as I've noticed with low sound track it imports them even if 32bit but it sound like  full volume glitchy noises)

**Comment by RodneyBaker** [comment]
Excellent news.  Will close this report as there should be others related to the issue still open.
