### ISSUE TITLE
Canvas size always expand from center (Bug?)

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#3879]
When I try to expand a canvas, always do from center

https://user-images.githubusercontent.com/74098734/114171896-d967c780-992c-11eb-95ad-b2d300307cc6.mp4

**Comment by shun-iwasawa** [comment]
I think it works properly. You can see the green region sticks at the bottom edge, which means that the image expands to only the upper direction.

Even if the image size is changed, the column position (= where the image's **center** is placed) is left unchanged.
It is why the image appears to be expanded to the both directions.

**Comment by gab3d** [comment]
@F-Burning 
if you select a drawing from de Level Strip and change the canvas from there, you will see it's working properly.

the effect you're seeing onscreen is derived from the fact that the column/layer that shows the drawing in the Xsheet/Timeline takes the center of the image as its pivot point, and as the height of the level has increased by 920 pixels, the new center will be shifted by half that amount (i.e. 460 pixels).

the same happens in most other animation software as well.

**Comment by F-Burning** [comment]
Oh, that was clarifier :smile: 

Thank you both for solving my question :+1:
