### ISSUE TITLE
Smoothing stops working with stylus

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#3894]
When drawing with a stylus, smoothing only seems to work on the first stroke.  Each following stroke has little to no smoothing applied.  Smoothing may get applied to the first stroke of each new drawing/frame.  Turning Windows Ink on or off doesn't seem to have any effect on this behavior.  Smoothing with mouse seems normal.

**To Reproduce**
1. Turn smooth up to max
2. Draw multiple strokes with tablet pen

**Expected behavior**
Smoothing should be applied at the set level to every stroke.

**Screenshots**

https://user-images.githubusercontent.com/60277069/114323347-9ac34000-9ad9-11eb-8144-0efc6072837a.mp4

**Device Information:**
OpenToonz Version: OpenToonz V1.5
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: Wacom Cintiq Pro 24

**Comment by shun-iwasawa** [comment]
It seems that the smoothing works the same between the first stroke and subsequent strokes on my end.
However, it looks "weaker" than when using stylus when compared to mouse.

I think it may be a side effect of #3841 .
I gained tablet response so OT captures tablet movement more frequent.
Which means that the stroke quickly drawn with stylus will be like the one drawn slowly in the previous versions.

**Comment by RattusaurusRex** [comment]
I think this issue also relates to #3893.  I notice that when smoothing is on but doesn't seem to be applied, the brush also lags and stutters.  The higher the smooth setting, the sooner it starts to stutter.

In this video, only the second stroke seems to have smoothing applied to it.  It is the only stroke that doesn't stutter.  Stroke 3 has the same smooth setting as stroke 2, but it doesn't act like it has smoothing applied to it and it ends up stuttering. 

https://user-images.githubusercontent.com/60277069/114342240-5dc67000-9b10-11eb-95a6-0a8d051efec8.mp4

**Comment by shun-iwasawa** [comment]
I could reproduce the lag. Thanks!
