### ISSUE TITLE
Implicit Holds

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#3901]
When you expose a frame, another one automatically appears below:

https://user-images.githubusercontent.com/74098734/114712170-b1f76d00-9d27-11eb-8347-494f50f0b594.mp4

Isn't it better to keep the exposure until the next frame as in the following example?

https://user-images.githubusercontent.com/74098734/114712392-f256eb00-9d27-11eb-8e49-4af84d50e615.mp4

This above is the free Toei animation exposure sheet, by the way!

**Comment by WolfInABowl** [comment]
I don't know if there is an official name for this behavior, but I like to refer to it as **explicit** vs **implicit** holds.

Explicit holds require you to mark a series of cells with the same drawing, any empty cells represent no drawing.

Implicit holds only require you to mark the first cell a drawing appears on, any empty cells are treated as holds.
If you don't want a drawing, you need to manually specify that.

Personally, I prefer the implicit approach seen in Clip Studio Paint and Toei Animation Digital Exposure Sheet as it removes the need to select several cells to make sure all are adjusted to a new drawing index.

**Comment by F-Burning** [comment]
Me too @WolfInABowl 

You can navigate through an exposed sheet only pressing enter :p


https://user-images.githubusercontent.com/74098734/114726627-78c5f980-9d35-11eb-8de6-a461dfe5e689.mp4

**Comment by gab3d** [comment]
I find the proposed change more intuitive than the current behavior.

Also, OT could differentiate between the main Enter key and the numpad Enter key, in the following way:
- Main Enter: accept input and end numeric input.
- Numpad Enter: accept input and go to next frame to continue typing there.

**Comment by F-Burning** [comment]
> Encuentro el cambio propuesto más intuitivo que el comportamiento actual.
> 
> Además, OT podría diferenciar entre la tecla Enter principal y la tecla Enter del teclado numérico, de la siguiente manera:
> 
> * Entrada principal: acepta la entrada y finaliza la entrada numérica.
> * Teclado numérico Enter: acepte la entrada y vaya al siguiente cuadro para continuar escribiendo allí.


Very good idea, it would be great 😄 👍

**Comment by gab3d** [comment]
@F-Burning ...por un momento pensé que había escrito en español y casi me viene algo! 😸

**Comment by artisteacher** [comment]
> Main Enter: accept input and end numeric input.
Numpad Enter: accept input and go to next frame to continue typing there.

This doesn't work out so well when your laptop doesn't have a numberpad.

**Comment by gab3d** [comment]
Good point, perhaps it could be reversed by default ...buuuut, I think if you do have a numpad it's way more practical what I originally proposed.

Another solution could be to use **Enter** (either one) for continue entering data and **Shift + Enter** to finalize entering data.

**Comment by F-Burning** [comment]
@gab3d Ya decía yo que Gabriel muy anglosajón no era 😆 

@artisteacher I think there is not problem, because you could change it in shortcuts 👍

**Comment by artisteacher** [comment]
I strongly believe default shortcuts should work with most keyboards. It goes the other way too - numberpad shortcuts can always be set manually by people who actually have numberpads.

**Comment by gab3d** [comment]
@artisteacher what do you think of Enter and Shift + Enter? 🤔

**Comment by artisteacher** [comment]
I'd be all for that.

**Comment by F-Burning** [comment]
The big question here is...is this going to get anywhere? 

As there is currently not much feedback with developers, there is that feeling of uncertainty.

**Comment by gab3d** [comment]
@F-Burning 
well, that we cannot know right now.
all we can do is try and trigger interest on some good-willing developer to take it on his/her shoulders to do it.
if that doesn't finally happen, then at least we've done our job of raising the point to a visible status.
but, many things have been improved in this way, so don't despair... 💪

**Comment by shun-iwasawa** [comment]
One of the differences between OT and Toei Animation Digital Exposure Sheet would be that OT does not need to define the frame length of a scene. I think the "implicit" holds need the scene length or the software cannot specify the end of the last hold cells.

BTW If you would like to alter all cells only inside of the current hold cells, `Similar Drawing Substitution Forward / Backward` would be  worth trying.

**Comment by gab3d** [comment]
@shun-iwasawa 
Perhaps the last exposed frame of a Column could be handled as an exception. But for all of the other frames of a Column the proposal seems practical...

**Comment by F-Burning** [comment]
Totally @gab3d ! :smile_cat: 

Sorry if my message sounds desperate, the last thing I want is to pressure anyone :smiling_face_with_three_hearts:  I commented on it because of the little activity that I have noticed the little time that I have been here, and so I was wondering if this would get anywhere, because I have noticed few interactions with developers in general for the amount of users, but I do not mean this as a criticism, but as an appreciation.

In any case, I share what you say!


@shun-iwasawa 

Couldn't it work both ways?

By extending the exposure manually, it would do so explicitly, and when editing within it, implicitly

Thanks for your attention!

> Perhaps the last exposed frame of a Column could be handled as an exception. But for all of the other frames of a Column the proposal seems practical...

That's an option too!

**Comment by RodneyBaker** [comment]
Follow up to this...
An implementation of Implicit holds can be see in Tahama2D.
It's an option via Preferences.

REF:  https://github.com/tahoma2d/tahoma2d/pull/847

**Comment by F-Burning** [comment]
Great!

Thank you Rodney!

**Comment by RodneyBaker** [comment]
This report should be reviewed in light of recent addition to Opentoonz related to Implicit holds and how it differs from the implementation in Tahoma2D.  Both approaches offer advantages and may very well be best when combined.
