### ISSUE TITLE
Lag / slow editing with selection tool

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#3902]
**Describe the bug**
It seems that some selections with the selection tool make OT lag on the raster levels. This seems to happen a lot when selecting the entire drawing. 

**To Reproduce**
List steps to reproduce the behavior.
1.create a  raster / toonz raster level
2. select the entire drawing
3.try to edit with selection tool

**Screenshots**
![slow editing with some selections](https://user-images.githubusercontent.com/29790512/114780302-7edcca00-9d77-11eb-9de0-1d21d79e3f04.gif)

W 10 Cintiq companion 2 1.5 official

**Comment by shun-iwasawa** [comment]
The lag seems to appear from the previous versions.
When enabling `No Antialiasing` option seems to make the operation faster, thanks to the resampling changes from bilinear to nearest-neighbor.

So, one possibility of enhancement would be using nearest-neighbor resampling while dragging.

**Comment by openanim** [comment]
What seems strange to me is that I often use the selection tool for this type of operation, I did not feel such a slowdown on version 1.4. I wonder if there is a possible link with the next build?

<img width="889" alt="issue_selection" src="https://user-images.githubusercontent.com/29790512/115208248-a4156380-a0fc-11eb-8486-d27d1e30e2fe.PNG">

I tried to test when my environment has this lag, and it seems to be from this build. 


https://user-images.githubusercontent.com/29790512/115208619-0c644500-a0fd-11eb-84ee-ff58427bd15f.mp4


The build just before it doesn't have the problem and the builds that follow seem to have inherited it.

https://user-images.githubusercontent.com/29790512/115208575-01111980-a0fd-11eb-8788-88100674f289.mp4

**Comment by JPUser1** [comment]
it only happens when you use a stylus.
it wont happen if using a mouse.

**Comment by RattusaurusRex** [comment]
A couple things I noticed while testing with stylus:
1. The lag depends on the size of the selection box -- it can be completely empty with no drawing.
2. If you turn ON 'Use Qt's Native Windows Ink Support' in the Preferences and turn OFF Windows Ink in your tablet drivers, the lag goes away.  Not practical for using the program, of course.
![image](https://user-images.githubusercontent.com/60277069/115339931-a0182e80-a15a-11eb-8c5c-3b0a3f01f816.png)
![image](https://user-images.githubusercontent.com/60277069/115339948-a8706980-a15a-11eb-8a8a-ad9376e48f15.png)

https://user-images.githubusercontent.com/60277069/115341395-65fc5c00-a15d-11eb-9e29-f02e13e2124e.mp4


Device Information:
OpenToonz Version: OpenToonz nightly build 2021-04-19 15:50:43 UTC
Operating System: Windows 10 Home 64-bit
CPU: Intel Core i7-4710HQ
Memory: 16 GB
Graphics Card: Nvidia GeForce GTX 970M
Graphics Tablet: Wacom Cintiq Pro 24
