### ISSUE TITLE
Rooms not loading right

### ISSUE THREAD

**Issue by TropicalCritter** [opentoonz/opentoonz#3908]
I recently updated to v1.5.  When I first updated to this version not that long ago, everything booted up as normal and ran good.  A friend of mine asked if I had any problems with exporting videos and I said no.  I went to launch OpenToonz to see if I could figure out how to help and only a few rooms loaded in.  There could be more problems but this is the only one I am aware of.  I have not used the program since I've updated it and my graphics driver is up to date (lest it says it is).  I uninstalled and reinstalled a few times, even going back to v1.4 but the problem was still there.  The laptop I use is really... not good, but it worked perfectly fine before.  I have included screenshots and the 3rd one is what it looked like before this happened.  Any help is appreciated.

![Screenshot 1](https://user-images.githubusercontent.com/82770236/115152396-e1b3b700-a03e-11eb-8e89-6308c8fb4c36.png)
![Screenshot 2](https://user-images.githubusercontent.com/82770236/115152406-e4aea780-a03e-11eb-88b1-1b0f9d29eee5.png)
![Screenshot 3](https://user-images.githubusercontent.com/82770236/115152475-3a834f80-a03f-11eb-9a56-15746a354584.png)

**Comment by RodneyBaker** [comment]
You'll want to use the option Windows > Workspace > Reset to Default Rooms 
The installer is trying to preserve any previously set rooms and will likely not get the new rooms of v1.5 without the reset.

![image](https://user-images.githubusercontent.com/2576432/115158526-2c8bf980-a054-11eb-9390-b6a954edbf16.png)

One of your images suggests you had some customized rooms so you'll likely need to do some additional work to get those back if that is desired.  The reset info above is just to get the new default rooms from v1.5.

**Comment by TropicalCritter** [comment]
> You'll want to use the option Windows > Workspace > Reset to Default Rooms
> The installer is trying to preserve any previously set rooms and will likely not get the new rooms of v1.5 without the reset.
> 
> ![image](https://user-images.githubusercontent.com/2576432/115158526-2c8bf980-a054-11eb-9390-b6a954edbf16.png)
> 
> One of your images suggests you had some customized rooms so you'll likely need to do some additional work to get those back if that is desired. The reset info above is just to get the new default rooms from v1.5.

I did as you said but it still looks exactly the same.

**Comment by TropicalCritter** [comment]
> You'll want to use the option Windows > Workspace > Reset to Default Rooms
> The installer is trying to preserve any previously set rooms and will likely not get the new rooms of v1.5 without the reset.
> 
> ![image](https://user-images.githubusercontent.com/2576432/115158526-2c8bf980-a054-11eb-9390-b6a954edbf16.png)
> 
> One of your images suggests you had some customized rooms so you'll likely need to do some additional work to get those back if that is desired. The reset info above is just to get the new default rooms from v1.5.

I did as you said but it still looks exactly the same.

> > You'll want to use the option Windows > Workspace > Reset to Default Rooms
> > The installer is trying to preserve any previously set rooms and will likely not get the new rooms of v1.5 without the reset.
> > ![image](https://user-images.githubusercontent.com/2576432/115158526-2c8bf980-a054-11eb-9390-b6a954edbf16.png)
> > One of your images suggests you had some customized rooms so you'll likely need to do some additional work to get those back if that is desired. The reset info above is just to get the new default rooms from v1.5.
> 
> I did as you said but it still looks exactly the same.

Ah I'm sorry I believe it did work.  I relaunched the program and now everything appears to be working!  Thank you so much and sorry about that.

**Comment by RodneyBaker** [comment]
Yes, I forgot to emphasize restarting the program!
Glad to hear the rooms are now working for you.
