### ISSUE TITLE
feature request- creating a new level with no name should automatically give the level an automatic name instead of failing to create the level

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#391]
This is something I notice that I am not the only one do. Staring opentoonz I create a new level, but forget to give it a name. Opentoonz fails to create the level, it closes the create level window and an annoying pop up tells me that I should name it. I have to start over.
If you look at people using OT at youtube - you will notice that they do the same thing when in hurry.

Here is a proposition. Instead of failing with a prompt, why not create the level and automatically name it to 'untitled_x' or 'Col_3' or whatever the column it was made on is. If the automatic name already exists, opentoonz could append and extra number to it's name automatically "Col_3_1".

![newlevelcreate](https://cloud.githubusercontent.com/assets/6495061/15742130/02c84872-28b5-11e6-8094-491846f3dd3a.PNG)

This is similar to how a basic file manager works, or even chrome web browser when you save a file to a directory that already has the file with the same name.

**Comment by blurymind** [comment]
Opentoonz actually already has the ability to automatically name a level when no name is specified. If you scribble on an empty level in the xsheet, open toonz gives it a letter for the name.

What I am proposing here is to make opentoonz do the same thing when you create a new level without giving it a name in the "new level" window.

**Comment by turtletooth** [comment]
I'll look into it. This has bugged me too.

**Comment by blurymind** [comment]
@turtletooth You have made some really nice changes to the software lately. Thank you for these. I hope they all get merged!

**Comment by turtletooth** [comment]
@blurymind Thanks!  What do you think about my onion skin default color change?  I can't decide if I like it?  Most animation programs use red and green for default onion skins and it helps me, but I don't know about everyone else.

**Comment by blurymind** [comment]
I dont oppose the change. I think it is better than blue, as some animators (me included) use blue pencil for my sketching pass

**Comment by turtletooth** [comment]
I'll work on this tonight

**Comment by turtletooth** [comment]
https://github.com/opentoonz/opentoonz/pull/437

Demo:
https://youtu.be/MWFawEhj58A

**Comment by blurymind** [comment]
This is fantastic! I hope it gets merged. You solved not just the issue here, but also a bunch of other issues that it has.
