### ISSUE TITLE
Reset to Default Rooms Command: Inform User

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#3911]
**Is your feature request related to a problem? Please describe**
Seems some users don't realize you need to restart the program for the command to take effect.

Command: `Windows > Workspace > Reset to Default Rooms`

**Describe the solution you'd like**
Have a popup message displayed after clicking telling the user the action will take effect next time OpenToonz is launched.

**Comment by DarrenTAnims** [comment]
Ideally you wouldn't have to restart. If you do then the popup would be a great idea. But as an alternative, is there any way that you  can reset your rooms and NOT have to restart?

**Comment by RodneyBaker** [comment]
I agree that not having to restart Opentoonz would be ideal.

I note that in Tahoma2D, which I also had a similar issue upon loading a new release and the menus not appearing correctly, resetting the default rooms... did not require a manual restart.  I'm not sure what it's doing there... perhaps it is saving everything, restarting and reloading the same project and files automatically?
