### ISSUE TITLE
"Toggle Maximize panel" bug

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#3912]
**Describe the bug**

You can't change tools, colors, etc, with "Toggle Maximize panel" activated.

**To Reproduce**

1. Go to Windows menu.
2. Select "Toggle Maximize panel"
3. Try to change tools or colors with shortcuts.

**Expected behavior**

Work normally.

**Device Information:**

 - OS: Windows 10
 - OpenToonz Version Nightly 2021-04-19 
 - GPU: NVIDIA GeForce GT 730

**Comment by RodneyBaker** [comment]
Interestingly, some shortcut keys appear to work while others do not.
I just started poking keys randomly.
Why some work and others do not I have no idea.

**Comment by F-Burning** [comment]
> Update: It appears to be a loss of window/panel focus issue. If the palette window is selected and has proper focus I can change colors while 'toggle maximize panel' is on (and off).

Curious 👀

**Comment by shun-iwasawa** [comment]
I've tested and confirmed that switching tools or styles via shortcut works OK on the maximized Viewer.
OTOH toggling tool options via shortcut does not work if there is no visible tool options bar.
