### ISSUE TITLE
Show all tools by default

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#392]
One default that bothers me in open toonz is the toolbar. When you first open OT, the toolbar always hides half of the items by default:
![extraclick](https://cloud.githubusercontent.com/assets/6495061/15740598/68df6ad0-28ad-11e6-8c1e-60d04f6273e1.PNG)
Can you change it so it doesnt hide them when you start the software.
This forces the user to always have to make an extra click to get to half the tools on every restart of the software. It is a bad default to have imo

**Comment by skitaoka** [comment]
This feature is merged by https://github.com/opentoonz/opentoonz/pull/460.
