### ISSUE TITLE
Keyboard Shortcuts: Shifted number shortcuts inaccessible.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#3926]
While testing issue #3923 I tried to create temporary shortcuts for interpolations and found out that while trying to create shifted number shortcuts (i.e. Shift+1, Ctrl+Shift+2, etc.) the editor showed them as: Shift+! and Ctrl+Shift+@

So, when trying to use those shortcuts they do not work, presumably because you can't double shift a key (i.e. Shift+Shift+1, Ctrl+Shift+Shift+2, etc.)

**Comment by F-Burning** [comment]
I have problems with some keys too, like  **>**  For example **shift** **+** **>** doesn't work.
