### ISSUE TITLE
Missing room

### ISSUE THREAD

**Issue by Danyko03** [opentoonz/opentoonz#3936]
**Describe the bug**
I just Installed Opentoonz and, theres just 8 rooms, I saw some videos and the missing one is Basics, I've never used this, but as I saw that room is important, I wanted to test Opentoonz using that room but what a surprise, that room just disappeared 

**To Reproduce**
List steps to reproduce the behavior.
1.I opened the app
2.I created a scene
3.There is no Basics room

**Expected behavior**
I expected a basics room to test the opentoonz

**Screenshots**
No, I uninstalled Opentoonz

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: 
 - GPU: AMD radeon r5
 - GPU Driver Version: idk

**Comment by gab3d** [comment]
v1.5 doesn't have Basics room anymore, previous versions did.
The default room now is Drawing.

**Comment by Danyko03** [comment]
Yes
