### ISSUE TITLE
Rendering crash the app

### ISSUE THREAD

**Issue by Danyko03** [opentoonz/opentoonz#3937]
**Describe the bug**
I've finished something, so, I tried to save it, first I tried to see the preview, the app crashed, then, I tried to render in every format, jpg, avi, png, etc. The app crashed
My pc is not the problem, the animation is not the problem, everything is actually okay except for the app, also, when I try to use external media, the app also crash lol, I just can save it as the default tnz format, and that is useless for any other app, I spended like 6 hours trying to fix and I just can't

**To Reproduce**
List steps to reproduce the behavior.
1. I made some animated stuff
2. I tried to see preview
3. App crashed
4. I tried to save using every aviable format
5. App crashed again

**Expected behavior**
Render correctly to keep my animation in a useful format

**Screenshots**
I cant take screenshots of the app closing lmao

**Device Information:**
 - OS: [e.g. Windows] 
 - OpenToonz Version: 1.5 (Today is may 3th of 2021, idk about the current version) 
 - GPU: Radeon r5
 - GPU Driver Version: yes

**Comment by artisteacher** [comment]
You might want to try rendering from the Tasks window to see if that works any better.

When you try to render, does it crash immediately? Or does it crash after some number of frames? Does this happen in every scene/project, or just one?

I've found that more processing heavy scenes might crash more often when rendering/previewing - depending on the computer specs. Using the plastic tool, skeleton tool, sub-scenes, FX, and/or a sketchy vector style can all be more processing heavy.

I usually render to an image format when that is a problem. When there's a crash, I'll see how many frames rendered. Then I'll change the start frame in Output Settings and render again. After I make it through the whole scene, I load the sequence in a new scene and render to video.

**Comment by Danyko03** [comment]
> You might want to try rendering from the Tasks window to see if that works any better.
> 
> When you try to render, does it crash immediately? Or does it crash after some number of frames? Does this happen in every scene/project, or just one?
> 
> I've found that more processing heavy scenes might crash more often when rendering/previewing - depending on the computer specs. Using the plastic tool, skeleton tool, sub-scenes, FX, and/or a sketchy vector style can all be more processing heavy.
> 
> I usually render to an image format when that is a problem. When there's a crash, I'll see how many frames rendered. Then I'll change the start frame in Output Settings and render again. After I make it through the whole scene, I load the sequence in a new scene and render to video.

**Comment by Danyko03** [comment]
> > You might want to try rendering from the Tasks window to see if that works any better.
> > When you try to render, does it crash immediately? Or does it crash after some number of frames? Does this happen in every scene/project, or just one?
> > I've found that more processing heavy scenes might crash more often when rendering/previewing - depending on the computer specs. Using the plastic tool, skeleton tool, sub-scenes, FX, and/or a sketchy vector style can all be more processing heavy.
> > I usually render to an image format when that is a problem. When there's a crash, I'll see how many frames rendered. Then I'll change the start frame in Output Settings and render again. After I make it through the whole scene, I load the sequence in a new scene and render to video.

Well, it crash after some frames, rendering or trying to watch the preview is the same, I tried in several projects and every of them crashed, yeah, 2 of them are 100% plastic tool, but the other ones are frame by frame, and all of them are 400 x 400 and 192 x 192, also, it's just the character walking in a 30 frames or less animation, with no background, so, is not soooo heavy

**Comment by gab3d** [comment]
@Danyko03 
OpenToonz tends to crash on systems with low RAM specs, if that's your case I'd suggest increasing RAM.

Ideally the program shouldn't crash due to that, but instead warn the user and stop rendering if it can't process the scene. 
But for some reason developers haven't been able to figure out how to do that yet.

**Comment by artisteacher** [comment]
Frame by frame could be processing heavy if you are using vector levels with a large number of control points. Sometimes people try to use vectors for a sketchy style or paint in areas with the brush to fill instead of using the fill tool. This ends up creating excessive numbers of control points which result in processing problems. If you are doing frame by frame with raster, that shouldn't be processing heavy, unless the images are especially large.

**Comment by RodneyBaker** [comment]
@Danyko03 If you are still experiencing rendering problems please let us know.
This discussion can be dusted off and your problem addressed.

If you are still having problems you may want to:

1) Join an Opentoonz discord where you can chat about the problem in real time
2) Share the contents of a project file

**Comment by RodneyBaker** [comment]
Will close as likely resolved and/or abandoned.

There is a pending fix for Tahoma2D that may address issues with Plastic too and rendering.
That might relate to this issue as well.
REF:  https://github.com/tahoma2d/tahoma2d/pull/1179
