### ISSUE TITLE
Creating a new scene with a shortcut will crash the program when you are in the Level Strip of a Raster Level. 

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#3940]
**To Reproduce**
List steps to reproduce the behavior.
1. Create a new scene and a new raster layer.
2. Enter the Level Strip of the raster level.
3. Close the scene (more precisely, create a new scene) using the shortcut (I have Ctrl + W).
4. After closing the dialog box, the program crashes.

The steps described do not always lead to a crash, for me it happens with a probability of 50%.

![ezgif-2-42db33881f40](https://user-images.githubusercontent.com/25724133/117340537-ad971d80-aea9-11eb-889b-73e2c33c10a4.gif)

This glitch is missing in Tahoma2D. 

**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: latest Nightly

**Comment by RodneyBaker** [comment]
I confirm the crash if/when I save the old scene prior to creating the new scene with the shortcut key.
That seems to be a step missing from your instructions; i.e. what option to you choose when OT requests input from the user to save or discard the current scene files).
