### ISSUE TITLE
The eraser stopped working

### ISSUE THREAD

**Issue by candez23** [opentoonz/opentoonz#3952]
The eraser stopped working
Hello everybody
Today I wanted to share a question or error that is happening to me and if someone has a solution I hope they can share it with me.

When I was making an animation and I made a drawing mistake and tried to erase it, the eraser stops working out of nowhere and I can only do it with "Supr", if someone has a similar problem or knows a possible solution, I hope they will share it with me, Thank you

**Comment by RattusaurusRex** [comment]
Check the settings on the tool options bar and see if you have the right mode enabled (Lines, Areas, or Lines & Areas) and that you don't have any extra settings enabled (like Selective or Frame Range).

**Comment by DarrenTAnims** [comment]
If you're still not sure, @candez23, share a screenshot while you've got the eraser selected. Screenshots always help solve these kinds of problems.
