### ISSUE TITLE
How do i use drawing tab on opentoonz and long press without it opening the right click menu?

### ISSUE THREAD

**Issue by squidddd** [opentoonz/opentoonz#3953]
I want to draw but when i draw like a small circle the right click menu opens and when i exit it keeps drawing even if my pen isnt on the tab, and also for some reason, you cant undo the drawing that was born from getting out of the right click menu.

**Comment by RattusaurusRex** [comment]
Turning off Windows Ink in my driver settings gets rid of that issue for me.

**Comment by shun-iwasawa** [comment]
If you meant that the issue is an unwanted right-click action by pressing-and-holding the pen, you can disable it : 
https://www.isunshare.com/windows-10/disable-or-enable-press-and-hold-for-right-clicking-in-win-10.html

**Comment by RodneyBaker** [comment]
Based on @squidddd 's thumbs up will consider this question answered.
