### ISSUE TITLE
When i use a vector level, i cant use the brush

### ISSUE THREAD

**Issue by Pirobit** [opentoonz/opentoonz#3954]
https://user-images.githubusercontent.com/78168482/119041766-0627e980-b985-11eb-8fe9-c296e017146d.mp4

this is what happens
help

**Comment by RodneyBaker** [comment]
Check the Range setting in the toobar options.
In your current mode OT is expecting you to move to another frame and draw a second line which then fills in all the inbetween images between any existing frames.

This is evident by the X at the origin of the stroke and the color red which indicates it is the first of two strokes.
