### ISSUE TITLE
Direct shortcuts for selection tool's modes

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#3962]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**
That will be a time saver to have shortcuts to switch between the differents modes of the selection tool, whitout open the dropdown menu.

**Comment by pojienie** [comment]
IIRC this is already done? Or am I misunderstanding something?

![a](https://user-images.githubusercontent.com/60221547/120321488-f2ca3600-c315-11eb-815a-9eae75af38aa.png)

**Comment by openanim** [comment]
Those ^^

![selection tool's modes](https://user-images.githubusercontent.com/29790512/120328268-f399a280-c2ea-11eb-8455-c9af382fc374.gif)

**Comment by pojienie** [comment]
Ah, gotcha. Sorry I misunderstood ^^;

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themself.
Note that there may still be useful information in this report and where appropriate that information should be transferred to a new report.
