### ISSUE TITLE
Help! OpenToonz never gets past the "creating main window" part of the loading screen- crashes

### ISSUE THREAD

**Issue by MrHec417** [opentoonz/opentoonz#3963]
![image](https://user-images.githubusercontent.com/85009896/120228496-1c665d00-c243-11eb-8258-4913d34edb03.png)
So OpenToonz crashes whenever i open it and i have tried reinstalling it but it never works, same with Tahoma2D or Morevna edition - note it is installed in d drive as c drive is full

Event Viewer Report:
Log Name:      Application
Source:        Windows Error Reporting
Date:          31/05/2021 19:04:49
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      -------
Description:
Fault bucket 1848884501612174080, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: OpenToonz.exe
P2: 0.0.0.0
P3: 6071a1fd
P4: ucrtbase.dll
P5: 10.0.19041.789
P6: 2bd748bf
P7: 000000000007286e
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBB32.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBD95.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBDD4.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBDD4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBE33.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OpenToonz.exe_6a851483245977317beafca668380f83d51cae3_ed821c1e_a6ef7208-f073-4fd4-a20a-13bcd276ed7b

Analysis symbol: 
Rechecking for solution: 0
Report Id: 56c186d0-6ce1-4a9c-9ff5-ed4f52f70fac
Report Status: 268435456
Hashed bucket: ec28fd293e4bf8caa9a88ea88d519b00
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-31T18:04:49.0377793Z" />
    <EventRecordID>40171</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>--------</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1848884501612174080</Data>
    <Data>5</Data>
    <Data>BEX64</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>OpenToonz.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>6071a1fd</Data>
    <Data>ucrtbase.dll</Data>
    <Data>10.0.19041.789</Data>
    <Data>2bd748bf</Data>
    <Data>000000000007286e</Data>
    <Data>c0000409</Data>
    <Data>0000000000000007</Data>
    <Data>
    </Data>

**Comment by RodneyBaker** [comment]
@MrHec417 After freeing up space on your C Drive did you get your installations to work?

**Comment by RodneyBaker** [comment]
Closing this as likely resolved and/or abandoned.
Also, a similar report is still opened as #4135.
