### ISSUE TITLE
How to import all images at once in one column?

### ISSUE THREAD

**Issue by girderi** [opentoonz/opentoonz#3964]
How to import all png images at once in one column? in older versions this was possible(saw youtube tutorials 2-4 years ago). opentoonz 1.5 adds each picture to new column.(  I tryed change different "loading" settings but not helpful.

**Comment by RodneyBaker** [comment]
@girderi If you didn't discover that you can use Opentoonz renaming option to automatically rename/resequence a number of images so they will be recognized as a sequence and placed in the same column... that is a good option to use.   That can be found via the Browser and a Right Click > Rename (selecting only the first of the images in the sequence... Opentoonz is smart enough to know in most cases what images belong to that sequence.
