### ISSUE TITLE
I like Blender's 2D great ability to edit strokes but I don't like great complexity of filling. Can I export finished contours from Blendner 2D and use them for further work in OpenToonz? 

### ISSUE THREAD

**Issue by girderi** [opentoonz/opentoonz#3965]
I tried export blender 2D strokes to PNG without anti-aliasing then converted to tlv files(with opentoonz browser).  I have access to outlines as Toonz raster images. I can use  fill frame range but I do not know how to automate the drawing of penumbra. if I could transfer vector layers from Blender to OpenToonz then I would have previously created contours for penumbra.  Can I import vector layers from blender 2D to Opentoonz?

**Comment by openanim** [comment]
You can try to export as svg from blender to opentoonz but you should probably expect some imperfections.
