### ISSUE TITLE
renderings lost after auto save

### ISSUE THREAD

**Issue by gearki1** [opentoonz/opentoonz#3966]
**Describe the bug**
Program in use for 5 days, auto save activated, all renderings dropped and lost following auto save 

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.5
 - Gaomon Tablet

**Comment by gearki1** [comment]
NM, uninstalled/reinstalled and updated graphics driver...renderings unrecoverable.

**Comment by artisteacher** [comment]
You should double-check the project folder for backups of the levels. If you look in File Explorer, the drawings or extras folder might have levels with .bak at the end of the name. If your uninstall deleted the stuff folder and your project was in the stuff folder, there's probably not a way to recover anything unless you run regular system backups.

**Comment by gearki1** [comment]
Thank you for that, I made a rookie error and didn’t establish multiple layers (or change the save fx- so when the auto save glitched I lost that whole level. My bad. Luckily I was only 8 seconds in so I recreated it (multiple levels) and designated save folders. Easier the 2nd time ;)
