### ISSUE TITLE
Is it possible to animate vectors using the timeline only instead of the level sheet?

### ISSUE THREAD

**Issue by Nukiloco** [opentoonz/opentoonz#3970]
**Question**
I been trying to figure out if its possible to animate points on a vector line by using the timeline. Right now it seems like the only approach to animating vectors is to make another frame on the level sheet, then animate it at the end position. After that then you have to insert blank frames and set how you want to animate the frames. What's worse is then you have to manually input all of those frames back into the timeline just for it to animate. Even though this approach does what I want, its very tedious having to animate like this. I was wondering if its possible to animate vector points using the timeline instead so the animated vectors would depend on the function editor.

**Comment by RodneyBaker** [comment]
Unless you want to add a plastic mesh animating Control Points isn't possible.
In this way we can animate the vector lines (along with the control points) via the Function Editor.
Perhaps you can provide some additional detail on what you are trying to accomplish.

Some time back there was some development effort to achieve what you are suggesting but it didn't get past the initial exploration stage.   See #1878 for more information (and links to code etc. for those interested in development).

**Comment by RodneyBaker** [comment]
If you consider 'animating' more akin to the old traditional animation approach then we can go frame by frame via timeline/xsheet and manipulate copies of the vector lines via the Selection Tool.  Then when played back the images appear to animate.  I'm sure you are hoping for automation however.

**Comment by DarrenTAnims** [comment]
I think the original question is asking about using the auto-inbetween option directly in the timeline without using the Level Strip. I think it'd be really useful to be able to do so, but also, you can't currently do it there. You described the process perfectly @Flairieve

**Comment by RodneyBaker** [comment]
Yes, there currently is no option to autoinbetween via the timeline/xsheet.
There are basically two processes that might be changed that would allow that:

1) Autoinbetweening would need to be able to ignore frame in a level
Currently autoinbetweening can only be done on consecutive/continuous/adjacent frames in a level.
There would need to be some way for the process to exclude frames not exposed in the timeline/xsheet.

2) There is no shortcut key assignment for autoinbetweening.  
Either a shortcut process would need to be added or a new UI element to allow the user to launch the process of autoinbetweening via the timeline/xsheet (or other appropriate location where allowed)

**Comment by artisteacher** [comment]
Doesn't vector guided drawing have an automatic mode though?

**Comment by manongjohn** [comment]
You can auto-tween 2 ways using the timeline. 

In both scenarios it requires that you have a number of blank frames, numbered in order, in the timeline as you would in the Level Strip.

If you have auto-renumber turned on, then select a bunch of empty cells in 1 level and use `Create Blank Drawing` to fill them with blank frames.

Then to auto-tween...
- Method 1: Using Vector Brush `Range` option.
    - Change the Range value to the interpolation you wish to use.
    - Click on first cell and draw a stroke
    - Click on last cell and draw a stroke
    - Repeat for each stroke you are tweening.

- Method 2: Vector Guided Drawing Panel
  - Draw what you want in the first cell
  - Draw what should be in the last cell
  - Select a blank cell inbetween
  - Enable Onion Skin and set Onion Skin markers on 1st and last cell
  - Open Vector Guided Drawing Panel
  - Set to furthest away and choose interpolation type.
  - Use the option to tween stroke to stroke where you select the stroke in the 1st cell then select  the corresponding stroke in the 2nd cell.

In either case, the stroke(s) will tween across the frames between the 1st and last. You can see it happen if you put onion skin markers on each frame or even keep the frames visible in the Level Strip.

Hope that helps.

**Comment by RodneyBaker** [comment]
Thanks @manongjohn for that reminder.  It is easy to forget some of the tools and processes we have available at our disposal.   Thanks also @artisteacher for the reminder of Guided Drawing... so very useful as well!

**Comment by Flairieve** [comment]
The issue I was reporting is more around what @DarrenTAnims was saying though also being allowed to use the Function Editor to control the vector points. There is a few programs that can already animate vector paths automatically without having to manually set blank frames either in the Timeline or Level Sheet.

**Comment by DarrenTAnims** [comment]
It'd only be a short step to introduce a system where you draw your 2 frames on the timeline and then ask OT to interpolate and add a set number of inbetween frames direct to the timeline. But there's not many developers working on OT at the moment, so we'll just have to continue with the current system for now. But thanks for raising this issue. Hopefully a developer will see this and be inspired to build this.

**Comment by manongjohn** [comment]
Actually, it sounds like you want what we called curve automation, where individual points on a stroke can be animated without having to draw new frames. Unfortunately dev was started for it but ultimately abandoned.

**Comment by RodneyBaker** [comment]
Closing this as a question that is at least partially answered.
Feel free to continue discussion here or open a new report as necessary.
