### ISSUE TITLE
The color styles aren't changing

### ISSUE THREAD

**Issue by Stickman06** [opentoonz/opentoonz#3976]
The color styles are remaining the same color no matter how many times I try to change it.

1. If I try to change the color wheel on the color wheel, it doesn't change
2. 
It's supposed to be the color I want it to be

![image](https://user-images.githubusercontent.com/85585597/121567992-093a5680-c9d4-11eb-8cea-d0e41dfd4f3d.png)

**Device Information:**
 - OS: Windows 10
 - OpenToonz 1.5
 - GPU: Not known
 - GPU: Not known

**Comment by DarrenTAnims** [comment]
It looks like you've turned off auto-changing. If you click the button labelled Auto, in your screenshot, that should change the colour on the palette entry as you change it. Without auto turned on, you have to press the Apply button to apply your chosen colour.
