### ISSUE TITLE
Plastic Tool Problem 

### ISSUE THREAD

**Issue by tomDreams** [opentoonz/opentoonz#3983]
Hi why the plastic tool is pixelating me vector mesh like hell 
![image](https://user-images.githubusercontent.com/85890154/121917110-7257fc00-cd3d-11eb-942c-3c599b51902d.png)

**Comment by shun-iwasawa** [comment]
The plastic tool displays deformed image using [limited sized (1024x1024 pixels in maximum) texture](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonzlib/textureutils.cpp#L180-L184) when you animate it in the camera stand mode for performance reasons.
When you render the image, it will be with good resolution.

**Comment by tomDreams** [comment]
thank you so so much !


‫בתאריך יום ג׳, 15 ביוני 2021 ב-3:19 מאת ‪shun-iwasawa‬‏ <‪
***@***.***‬‏>:‬
