### ISSUE TITLE
OpenToonz can't run 

### ISSUE THREAD

**Issue by nukeCrayon** [opentoonz/opentoonz#3985]
**Describe the bug**
I can't run OpenToonz on terminal 

**To Reproduce**
List steps to reproduce the behavior.
1. install thru software manager
2. run in terminal by typing flatpak run io.github.OpenToonz
3. you can see the result

**Expected behavior**

**Screenshots**
`flatpak run io.github.OpenToonz
Gtk-Message: 18:29:17.382: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
`
**Device Information:**
 - OS: linux mint 20.1
 - OpenToonz Version: 1.5.0
 - GPU: AMD Radeon RX 570
 - GPU Driver Version: Radeon™ Software for Linux® 20.20

**Comment by fayizms** [comment]
I have a similiar problem, except that i dont run it from the Command Line. It gives me a popup saying OpenToonz.exe has stopped working

Steps to reproduce:
1. Install OpenToonz v.15 for Windows from this link(not nightly)[Download Page](https://opentoonz.github.io/e/download/opentoonz.html)
2. Run the installer
3. Once it's finished installing, Run it
4. The loading screen appears for a few seconds, and suddenly shows the popup with a close option

**Comment by nukeCrayon** [comment]
same here when I just run it by clicking the icon. I just run it in the command line to know what could be the error.

**Comment by shun-iwasawa** [comment]
@fayizms 
Your issue seems to be due to remaining dll from the previous version which is unnecessary and causes crash on OT 1.5. Either of the followings will fix the problem: 
- Uninstall the software completely (i.e. making sure that `C:/Program Files/OpenToonz` is cleared) and install OT 1.5 again.
- Or, as a quick fix, just remove `C:/Program Files/OpenToonz/bearer/qnativewifibearer.dll` .

@nukeCrayon 
According to the messages, your problem seems to be different from the one @fayizms reported.
I'm sorry I don't have Linux environment to investigate further.

**Comment by nukeCrayon** [comment]
I'll try also to uninstall the software completely here in Linux. Because I already made it run OpenToonz at first then I restore.

**Comment by fayizms** [comment]
I didn't knew about the dll issue. That would've been an easier fix. Anyway, I installed a different version(don't remember which, i'll say after looking it up) and it works like a charm
