### ISSUE TITLE
Drawing

### ISSUE THREAD

**Issue by TeeniToonz** [opentoonz/opentoonz#3992]
**Describe the bug**
I opened Opentoonz and I looked in the top right to look for the drawing tab and for some reason it wasn't there and I can not figure out a way to get it back. So as of now I cant change the color and use some other options that I would be able to use with it. So basically I can start my animation, but I really want to use Opentoonz because it looks really good and there is nothing really like it. So please tell me a way to fix this. It only shows cleanup, pltedit, inknpaint, xsheet, batches, and browser.

**To Reproduce**
List steps to reproduce the behavior.
1. Make a scene
2. then close out of  Opentoonz
3. and go back in and you wont have the drawing option at least for me only cleanup 
**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. AMD Ryzen 3 3350U]
 - GPU Driver Version: [e.g. idk]

**Comment by RodneyBaker** [comment]
@TeeniToonz   We can reset/recover the default rooms via the menu:

![image](https://user-images.githubusercontent.com/2576432/123419581-ff8e2280-d57f-11eb-9f4d-6019b4e40222.png)


Make sure to quit/restart Opentoonz for the change to take effect.

If for some reason you still don't get the v1.5 default rooms (which are different than those of v1.4) then there are some additional things you can do to ensure clean settings are placed into your stuff directory.  BUT... let's try the reset first before we wander any deeper.

Note that if you go to the Windows menu you can open the various panels to include the Palette window, Style Editor, etc.  In short, you can make your own custom rooms with anything you need inside.

**Comment by DarrenTAnims** [comment]
You won't get the Drawing room as that's a default room in Version 1.4 and earlier and I assume you're using V1.5. But what you're looking at isn't the standard set of rooms. For some reason you've change your room list to the Studio Ghibli rooms. You can change back to the default set by opening up your preferences (File > Preferences) then in the Interface tab, change the Rooms drop down to Default, then restart OpenToonz.

**Comment by TeeniToonz** [comment]
> You won't get the Drawing room as that's a default room in Version 1.4 and earlier and I assume you're using V1.5. But what you're looking at isn't the standard set of rooms. For some reason you've change your room list to the Studio Ghibli rooms. You can change back to the default set by opening up your preferences (File > Preferences) then in the Interface tab, change the Rooms drop down to Default, then restart OpenToonz.

Thanks!

**Comment by TeeniToonz** [comment]
> @TeeniToonz We can reset/recover the default rooms via the menu:
> 
> ![image](https://user-images.githubusercontent.com/2576432/123419581-ff8e2280-d57f-11eb-9f4d-6019b4e40222.png)
> 
> Make sure to quit/restart Opentoonz for the change to take effect.
> 
> If for some reason you still don't get the v1.5 default rooms (which are different than those of v1.4) then there are some additional things you can do to ensure clean settings are placed into your stuff directory. BUT... let's try the reset first before we wander any deeper.
> 
> Note that if you go to the Windows menu you can open the various panels to include the Palette window, Style Editor, etc. In short, you can make your own custom rooms with anything you need inside.

It worked thank you!
