### ISSUE TITLE
Probleme Toonz

### ISSUE THREAD

**Issue by Enith30** [opentoonz/opentoonz#3998]
Lorsque je sélectionne la pompe (et d'autre), cette erreur s'affiche : L'outil actuel ne peut pas être utilisé sur in niveau toonz
Pouvez vous m'aider ?

**Comment by RodneyBaker** [comment]
@Enith30 
The pump tool can only be used with Vectors.
Therefore, it can only be used with Vector levels and not raster or toonz raster bitmap levels.
Create a vector level and then draw with vector levels and you'll be able to use the Pump Tool and other tools designed for use with vector levels.

Cheers!

**Comment by RodneyBaker** [comment]
Will close this as likely resolved but...
Please let us know if you are still having problems @Enith30
