### ISSUE TITLE
plastic tool  crash *linux

### ISSUE THREAD

**Issue by BLANO** [opentoonz/opentoonz#3999]
![Schermata 2021-07-05 12:53:55](https://user-images.githubusercontent.com/42709459/124460811-1eff2980-dd90-11eb-86f7-a50e11ca81f6.png)
**Describe the bug**

my opentoonz crashes when i render a project using plastic tool

**To Reproduce**
List steps to reproduce the behavior.
1. create a new project
2. create a toonz raster level
3. create a mesh using plastic tool and animate it
4. try to render -crash-

**Expected behavior**
i expect to render a scene

**Screenshots**

**Device Information:**
 - OS: linux ubuntu 20.04
 - OpenToonz Version: 1.5
 - GPU: nvidia 
 - GPU Driver Version: 450

**Comment by josepablo-espinoza** [comment]
I think I have a similar problem (QT Bad drawable) when applying a mesh to an external resource (images). The only way I've solved it is by rendering by chunks via the task window or the tconverter cli utility, try different chunk sizes (multiple of 8s seems to produce better results), example of the tconverter utility:

`tcomposer "<path to tnz file>" -o "<path to output dir>/<filename>" -range <int frame to begin, starts at 1> <int frame to end> -step 1 -shrink 1 -multimedia 0 -nthreads all -maxtilesize none`

**Comment by RodneyBaker** [comment]
I cannot confirm this but assume linux users can (and as @josepablo-espinoza has).
Adding crash and workaround labels.

**Comment by RodneyBaker** [comment]
@manongjohn has been posted a likely fix for this crash to Tahoma2d.
This relates to updated SuperLu.
Please see: https://github.com/tahoma2d/tahoma2d/issues/1036

**Comment by RodneyBaker** [comment]
This may be resolved in latest nightlies but status thus far is unconfirmed.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@BLANO please let us know if you are still experiencing this issue.
Also if you can supply a project file to test with we will be most grateful.
Current releases now have the File > Export Scene dialogue to facilitate zipping up a scene and sharing.
This need not be a project in projection, just any project that reliable can reproduce the problem.
