### ISSUE TITLE
Compilation notes for OSX

### ISSUE THREAD

**Issue by justinclift** [opentoonz/opentoonz#40]
For anyone else trying to compile on OSX, please note the OSX compiling instructions (so far) are missing a few lines (eg libusb dependency).

Some initial commits here to add further bits, which might help others:

https://github.com/justinclift/opentoonz/commits/addqt5

**Comment by Emasoft** [comment]
Thank you for improving the OSX instructions! Can you also make a shell script to do all that?

**Comment by justinclift** [comment]
At first thought, that should be doable. :smile:

One way to find out for sure though... :wink:

**Comment by scribblemaniac** [comment]
I'm having some difficulties getting it to compile on my mac, but when I figure it out I will try to make a brew formula for opentoonz which will make it very easy to build on mac. A shell script and some documentation would still be useful for developers though.

**Comment by justinclift** [comment]
@scribblemaniac Do the adjustments here help with your OSX compiling?

&nbsp; &nbsp; https://github.com/justinclift/opentoonz/commit/b7cf4cdc1ae8b966f3783c6617635e2b73a1a264

With the Homebrew formula, that's a good thought.  It might need to wait until some of the dependency problems are fixed (eg the customised tiff 4.0.3 code), but then again... probably better to get it ready sooner rather than later. :smile:

I was going to put some time into it... but I'm kind of tired and not really feeling into it atm.  :innocent:  If you get the Homebrew formula happening instead, that would be great. :grin:

**Comment by scribblemaniac** [comment]
@justinclift Actually, I was already using your branch! Thank you very much as that probably saved me quite a bit of trouble. Unfortunately the problems I am currently having are related to libtiff, probably just conflicts with the system-installed 4.0.6 version which I need for building other programs.

**Comment by justinclift** [comment]
Ahhh, yeah.  It definitely requires the bundled tiff-4.0.3.  If you can somehow force it to detect that, you should be fine. :smile:

**Comment by justinclift** [comment]
The tiff detection bits are here, though you've probably already found them and started trying things out:

* https://github.com/opentoonz/opentoonz/blob/master/toonz/cmake/FindTIFF.cmake
* https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/CMakeLists.txt#L144-L145

You might be able to do something super simple like just hard code the path value into the CMakeLists.txt file.  Not sure though, as I'm not very clueful with CMake atm.

**Comment by Emasoft** [comment]
OpenToonz has been just added to homebrew-cask. 
To install on OS X:
`brew cask install opentoonz`

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by justinclift** [comment]
@Emasoft As a curiosity thing, it's possible to see the download stats:

&nbsp; &nbsp; https://api.github.com/repos/opentoonz/opentoonz/releases/2887466

Look for the "download_count" lines in the JSON, one per each of the release assets (eg one for the .pkg, one for the .exe).

**Comment by mich181189** [comment]
@justinclift I think the tiff issue may be that while it's finding the correct tiff headers, it isn't using them because I don't think TIFF_INCLUDE_DIR is properly being added to the include path. I'm testing a fix now

**Comment by aars** [comment]
Any updates on this documentation? I'm trying to compile on osx but finally run into:
```
clang: warning: -Wl,-install_name,@rpath/libimage.dylib: 'linker' input unused
[ 52%] Linking CXX shared library libimage.dylib
Undefined symbols for architecture x86_64:
  "_lzma_code", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.o)
      _LZMAPostEncode in libtiff.a(tif_lzma.o)
      _LZMAEncode in libtiff.a(tif_lzma.o)
  "_lzma_end", referenced from:
      _LZMASetupDecode in libtiff.a(tif_lzma.o)
      _LZMASetupEncode in libtiff.a(tif_lzma.o)
      _LZMACleanup in libtiff.a(tif_lzma.o)
  "_lzma_lzma_preset", referenced from:
      _TIFFInitLZMA in libtiff.a(tif_lzma.o)
      _LZMAVSetField in libtiff.a(tif_lzma.o)
  "_lzma_memusage", referenced from:
      _LZMADecode in libtiff.a(tif_lzma.o)
  "_lzma_stream_decoder", referenced from:
      _LZMAPreDecode in libtiff.a(tif_lzma.o)
      _LZMADecode in libtiff.a(tif_lzma.o)
  "_lzma_stream_encoder", referenced from:
      _LZMAVSetField in libtiff.a(tif_lzma.o)
      _LZMAPreEncode in libtiff.a(tif_lzma.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [image/libimage.dylib] Error 1
make[1]: *** [image/CMakeFiles/image.dir/all] Error 2
make: *** [all] Error 2
```

Which might be the same `TIFF_LIB` problem.

**Comment by justinclift** [comment]
Hmmm, that looks like it's not finding the lzma library, even though it would probably have found the lzma include files.  You might need to look where lzma is installed, and figure out what part of things is referring to it in the build files.

Btw, I'm not putting time into OpenToonz any more, so won't be any further help debugging this.  Sorry. 😦

**Comment by jboyle** [comment]
@aars - Not sure if you were ever able to solve this problem, but I ran into the same issue and solved it by running `sudo make install` after building the tiff library.

**Comment by justinclift** [comment]
@jboyle Ahhh that's probably interesting for people trying to do this and hitting the problem.

From memory, OpenToonz uses their own version of the tiff library, and by default has things set up to use the bundled version without installation.

But... if the detection pieces aren't finding it, they'd probably look in the "standard" system directories instead.  `sudo make install` probably puts them in there too, so it works out ok. :smile:
