### ISSUE TITLE
(FFMPEG) Export an animation on MacOS

### ISSUE THREAD

**Issue by EPICFACE99LOL** [opentoonz/opentoonz#4005]
(I’m a beginner to both GitHub and Opentoonz)
    I made my first animation that has 158 frames and 24FPS and I can’t export it at all. I downloaded the FFMPEG as required to export it(because OT can’t bundle with ffpmeg). I have a MacOS Big Sur(MacBook Air). Please help, I’ve been at this for _hours_ and I don’t know what else to do.

**Comment by RodneyBaker** [comment]
I must assume by use of the term 'export' and the use of ffmpeg you wish to 'render' your animation.
Rendering requires use of the various rendering options found in the Render menu.
Of these options rendering through Output Settings will give us the most options.

Perhaps you are doing this already and the render is simply failing?

If not perhaps you can detail what process you are attempting to use to export.

**Comment by EPICFACE99LOL** [comment]
I tried rendering..still wouldn't export.
So I've completed a tutorial on downloading FFmpeg and going back to the program to try again. It keeps saying, "FFmpeg not found, please get the location in the Preferences and restart."

**Comment by RodneyBaker** [comment]
A Mac user will need to confirm the address but I believe preferences should point to the directory of ffmpeg as opposed to the directory/bin for PCs.  Linux has a similar difference in paths I believe.

**Comment by EPICFACE99LOL** [comment]
It's like the FFMPEG thing doesn't exist though. The program won't 
 Let me click the export button.

**Comment by RodneyBaker** [comment]
I am very confused by your use of the term 'export'.
Where exactly is this Export button?

**Comment by EPICFACE99LOL** [comment]
![image](https://user-images.githubusercontent.com/87244298/125178197-629ecc80-e1b0-11eb-957d-b84f222104f1.jpeg)

**Comment by EPICFACE99LOL** [comment]
I gave it a location

**Comment by RodneyBaker** [comment]
The FFMPEG path needs to point to the directory where you unzipped the FFMPEG files.
Currently it is pointing to where Opentoonz resides.

**Comment by EPICFACE99LOL** [comment]
![image](https://user-images.githubusercontent.com/87244298/125178260-11dba380-e1b1-11eb-97e9-e6bbb29ce54c.jpeg)
These aren't unzipped yet right?

**Comment by RodneyBaker** [comment]
No.  Nothing looks unzipped there.
Unzip the ffmpeg download and that should provide a directory to point to in the Preferences.

**Comment by EPICFACE99LOL** [comment]
Which one to unzip..?

**Comment by RodneyBaker** [comment]
Good question.
Which one is the ffmpeg you want to use?

**Comment by EPICFACE99LOL** [comment]
The one that says FFMPEG.zip....
how do I unzip?

**Comment by RodneyBaker** [comment]
I unzip by right clicking on the file and choosing an unzip option but I'm not sure what will work for you on a Mac.

**Comment by EPICFACE99LOL** [comment]
I don't have an unzip option.

**Comment by RodneyBaker** [comment]
You may need to wait until a Mac user sees this topic.
Or... visit one of the Opentoonz discords and ask for assistance there.

Or...
Download the Tahoma2D fork of Opentoonz which comes with FFMPEG ready to run.

**Comment by EPICFACE99LOL** [comment]
Yeahh I'll try those...thanks for trying to help, I appreciate it :)

**Comment by artisteacher** [comment]
Double-click on the file to unzip.

**Comment by gab3d** [comment]
@EPICFACE99LOL 
I don't intend to sound rude, but please understand this is not a user support forum.
This is a place for reporting bugs. 
People here are being kind in answering your questions, but in the future please resort to Google Forums, Facebook Groups or any other user support platform, for similar issues.
Only after an issue is being refered to as a possible bug, by other experienced users, it should be the right time to post an issue here.

Thanks!!
