### ISSUE TITLE
Transferring an Animation from one program to another

### ISSUE THREAD

**Issue by EPICFACE99LOL** [opentoonz/opentoonz#4006]
Because I can't export an animation on Opentoonz, is there a way I can transfer that one animation to another program(Tacoma2D) to export it there instead?

**Comment by RodneyBaker** [comment]
Files created in Opentoonz can be opened in Tahoma2d.

**Comment by EPICFACE99LOL** [comment]
Oo, so I opened the file from Opentoonz to Tacoma and it worked! The Problem though is that it doesn't show any of the drawn frames. What should I do from here?


(Also I'm going to try to change the topic thing because I just saw that this isn't a user supported forum page)

**Comment by RodneyBaker** [comment]
@EPICFACE99LOL 
Perhaps we should look into your real issue which is why you cannot export/render from Opentoonz.
This generally is a trivial process so we just need to look at that and... on to the next problem.

**Comment by EPICFACE99LOL** [comment]
Ah :^
FFMPEG is confusing :|)
I think that's why...? I'm not really a tech-savvy person...

![image](https://user-images.githubusercontent.com/87244298/126073536-90f25eb5-c13a-43bb-b024-82e46ef83aec.jpeg)this is what happened after I transferred the animation..

**Comment by RodneyBaker** [comment]
Closing as part of regular housekeeping.
@EPICFACE99LOL If you are still experiencing issue you need help troubleshooting I'll recommend joining one of the Opentoonz discord/chat sessions.   There are lots of people willing and able to help you though any rough spots.
