### ISSUE TITLE
Render sound bug

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4007]
OpenToonz 1.5
==========

Hi,

I made an animation of a character with his mouth talking. I incorporated the sound into it. At rendering, the character speaks. I can play the scene in opentoonz: he talks. But when I read the created file on my hard drive, the video has no sound!
On the other hand, when I convert the ".AVI" into ".MP4" with the MediaCoder software, the sound reappears.

I think this is a bug in OpenToonz ...

===
http://xmas.free.fr/SPH_DA2021.mp4

**Comment by RodneyBaker** [comment]
I haven't dug into this deeply yet but initial investigation is producing a crash when I click on the Options button for AVI rendering.

**Comment by RodneyBaker** [comment]
This report should be reviewed in light of recent fixes and additions to audio.

**Comment by RodneyBaker** [comment]
The crash I was experiencing while troubleshooting this report was solved by renaming (i.e. removing) a logitec driver.
For more information please see report https://github.com/opentoonz/opentoonz/issues/46

**Comment by RodneyBaker** [comment]
Will close as possibly resolved and/or abandoned.
Recent fixes to audio may also relate to this issue.
@SPH404 Please let us know if you are still experiencing audio problems.
