### ISSUE TITLE
opentoonz crashes when i import any kind of file 

### ISSUE THREAD

**Issue by iikesleep** [opentoonz/opentoonz#4009]
i tried it with the older versions as well . i had uninstalled it because i wanted to try out live2d first but when re installed it it crashed when i tried to import files

**Comment by RodneyBaker** [comment]
The fact that you are recieving a crash suggests you might not have a solid installation.
Perhaps you can uninstall the program and then reinstall... preferably using a recent nightly release that contains various bug fixes not included in the original v1.5 release.

The most recent nightly release, from 2 days ago, can be found here:  https://github.com/opentoonz/opentoonz_nightlies/releases

As for the files themselves...
Can share a copy of a file you are trying to import and/or provide more information on what type of file you are attempting to open in Opentoonz?

There are some file formats that can be opened easily in Opentoonz while others need assistance from programs such as FFMPEG.  For instance; gif, mp4 and webm are formats that requier FFMPEG to be downloaded and connected to Opentoonz via a path in Preferences.

**Comment by RodneyBaker** [comment]
It will also help to know what platform you are on; Windows, Mac or Linux.

**Comment by artisteacher** [comment]
Before reinstalling, it's always a good idea to rename the stuff folder first.

**Comment by iikesleep** [comment]
> The fact that you are recieving a crash suggests you might not have a solid installation.
> Perhaps you can uninstall the program and then reinstall... preferably using a recent nightly release that contains various bug fixes not included in the original v1.5 release.
> 
> The most recent nightly release, from 2 days ago, can be found here: https://github.com/opentoonz/opentoonz_nightlies/releases
> 
> As for the files themselves...
> Can share a copy of a file you are trying to import and/or provide more information on what type of file you are attempting to open in Opentoonz?
> 
> There are some file formats that can be opened easily in Opentoonz while others need assistance from programs such as FFMPEG. For instance; gif, mp4 and webm are formats that requier FFMPEG to be downloaded and connected to Opentoonz via a path in Preferences.

i ve tried the nightly builds too . here is a file i tried to open in opentoonz : 
![pastelpastelpastelpastelpastelpastelpastel](https://user-images.githubusercontent.com/81380674/125662363-9cd62aa0-a4cf-46ab-aa0d-17dbf0571e75.png)
 i wanted to try using the plastic tool to make it flowy and stuff but opentoonz just crashed

**Comment by RodneyBaker** [comment]
I'm not having any issues with the image... although for best animation in cut out approach with or without the plastic tool I would recommend separating parts of the character so that elements can be moved/animated separately from each other.

It appears we need to focus on your system and installation of Opentoonz.
Please provide information on your operating system etc.

Aside:  The only issue I intially had with your posted image was that I had somehow turned the option in Preferences on that tells Opentoonz to ignore the alpha channel/transparency of images/levels in Column 1 and so I intially thought there was something wrong with your image.   That wasn't the case... it was that option in Preferences and I was seeing the image as if it had no transparency.

**Comment by iikesleep** [comment]
> I'm not having any issues with the image... although for best animation in cut out approach with or without the plastic tool I would recommend separating parts of the character so that elements can be moved/animated separately from each other.
> 
> It appears we need to focus on your system and installation of Opentoonz.
> Please provide information on your operating system etc.
> 
> Aside: The only issue I intially had with your posted image was that I had somehow turned the option in Preferences on that tells Opentoonz to ignore the alpha channel/transparency of images/levels in Column 1 and so I intially thought there was something wrong with your image. That wasn't the case... it was that option in Preferences and I was seeing the image as if it had no transparency.

i use windows ten, 64 bit version . 3.00 ghz prcessor and 4gb ram.
i had uninstalled opentoonz when i wanted to use live2d but when i re installed it  the crash would happen

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
