### ISSUE TITLE
OSX Crash in libpng16.16.dylib when saving scene or exporting levels

### ISSUE THREAD

**Issue by arteficio** [opentoonz/opentoonz#401]
Hi.
on OpenToonz 1.02 MacOSX 10.11,5 i get an immediate crash when trying to save a scene or exporting a level in png.

Scene save crash is triggered by makeSceneIcon()
Level export crash happens only when exporting is in png format.

So it must definitely be an issue with png writing.

I attach a couple of snippets from the OSX crash reporter. Please let me know if you need the full crash reports.

This is from the report when saving a scene - looks like the createSceneIcon triggers the problem.
`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libpng16.16.dylib               0x00000001107f69ac 0x1107f5000 + 6572
1   libpng16.16.dylib               0x000000011080eb5e png_create_write_struct_2 + 19
2   libpng16.16.dylib               0x000000011080eb45 png_create_write_struct + 27
3   libimage.dylib                  0x000000010e44b093 PngWriter::open(__sFILE*, TImageInfo const&) + 163
4   libtnzcore.dylib                0x000000010d2e7e98 TImageWriter::save(TSmartPointerT<TImage> const&) + 5000
5   libtnzcore.dylib                0x000000010d2e8fd8 TImageWriter::save(TFilePath const&, TSmartPointerT<TRaster>) + 104
6   libtoonzlib.dylib               0x000000010dd47bf4 (anonymous namespace)::makeSceneIcon(ToonzScene*) + 324
7   libtoonzlib.dylib               0x000000010dd42a3c ToonzScene::save(TFilePath const&, TXsheet*) + 780
8                                   0x000000010c53132b IoCmd::saveScene(TFilePath const&, int) + 3419
9                                   0x000000010c3c8a97 SaveSceneAsPopup::execute() + 471
10                                  0x000000010c3c48a7 FileBrowserPopup::onOkPressed() + 4103
11                                  0x000000010c72aa4b 0x10c11a000 + 6359627
`

This is when exporting a level in png. Same crash in libpng.

`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libpng16.16.dylib               0x000000010b27b9ac 0x10b27a000 + 6572
1   libpng16.16.dylib               0x000000010b293b5e png_create_write_struct_2 + 19
2   libpng16.16.dylib               0x000000010b293b45 png_create_write_struct + 27
3   libimage.dylib                  0x0000000108ec9093 PngWriter::open(__sFILE*, TImageInfo const&) + 163
4   libtnzcore.dylib                0x0000000107d68e98 TImageWriter::save(TSmartPointerT<TImage> const&) + 5000
5                                   0x000000010711eb2a 0x106b9e000 + 5770026
6                                   0x000000010711db1b IoCmd::exportLevel(TFilePath const&, TXshSimpleLevel*, IoCmd::ExportLevelOptions, IoCmd::OverwriteCallbacks*, IoCmd::ProgressCallbacks*) + 1835
7                                   0x0000000106cb0986 ExportLevelPopup::execute() + 3174
8                                   0x0000000106e488a7 FileBrowserPopup::onOkPressed() + 4103
`

**Comment by jpturcotte** [comment]
Is this still an issue? cc @artisteacher & @shun-iwasawa

**Comment by artisteacher** [comment]
I'm not getting a crash on export nor saving the scene with MacOS 10.14. I haven't tried exporting a level in 10.13.6 nor in 10.11.6, but both saved scenes without issue. I would assume this is resolved & can be closed unless @arteficio is still experiencing this in OT 1.2.1.

**Comment by RodneyBaker** [comment]
Closing this three year old report as likely resolved and abandoned by original reporter.
@arteficio If you are still experiencing this problem please let us know and we will investigate.
