### ISSUE TITLE
Keys unpacking

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4013]
http://xmas.free.fr/opentoonz_error_key.bmp

Hi
I have an anime that starts at line 1 and has a magnification key on box 1.
When I try to move the anime back by inserting empty boxes, the key does not move with the block.
How to do ?

Big thanks

**Comment by DarrenTAnims** [comment]
I think you're saying that you're moving the exposure of the drawings. If so, then you're right. Moving drawings doesn't affect the keys. To move them all together you can hold the Ctrl key before you highlight the drawings and drag them all together. Or move the keys separately. Just click on a key to highlight it, then click and drag it to the new position.

**Comment by SPH404** [comment]
Big thank you to you and your comment ! =)

Check out my example that I linked in my first post (the screenshot). Even when pressing CTRL, the key does not move with the drawings ...
Is this an error or is it planned by OT, I don't know but it seems abnormal to me ...

**Comment by artisteacher** [comment]
It works, though you have to select and drag in a very specific way. It's not particularly intuitive.

Hold down on ctrl (cmd on macOS) when making the selection. Then release both ctrl and the mouse. Keys should be blue to show they are part of the selection.
<img width="513" alt="Screen Shot 2021-07-17 at 8 23 46 PM" src="https://user-images.githubusercontent.com/21159116/126052109-496cff41-a155-4ec4-87ca-245ff8a1e0e6.png">

Then use the dragbar (no ctrl) to drag everything  to the new location.
<img width="512" alt="Screen Shot 2021-07-17 at 8 25 16 PM" src="https://user-images.githubusercontent.com/21159116/126052126-bb23a3f5-ba73-4a53-b3f7-9df00953007c.png">

My example shows the timeline, though it works the same in the Xsheet.

**Comment by SPH404** [comment]
On PC (win10), my keys look like real keys (you, you must have a MAC or an old version of OT because your keys are in diamonds).
Are we talking about the same thing?

**Comment by DarrenTAnims** [comment]
If you can see real key images on your timeline, then you're using version 1.4 or earlier. You should update when possible to get the newer features and bug fixes.
(I'm on Win10 too)

**Comment by RodneyBaker** [comment]
Here's a link to the latest nightly release which is highly recommended:

https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by DarrenTAnims** [comment]
Keys aren't shown in V1.5, so you must've tried installing a previous version once. If you uninstall and remove your OpenToonz Stuff folder, then install the nightly release that Rodney shared above, you'll have the very latest version.

**Comment by artisteacher** [comment]
I do use a mac, but the display and moving of keys should be the same on all OS. The only difference is the modifier key. 

If you run a clean install, you can also just rename the stuff folder before running the new install - in case you need any of the files later.

**Comment by SPH404** [comment]
Does this mean that OT 1.5 will no longer be improved?
Why is Rodney working on a side project?

It's sad news I think ... 😥

**Comment by DarrenTAnims** [comment]
Who said anything about OT not being improved?
What side project?
Have you tried re-installing the nightly build?

**Comment by SPH404** [comment]
the night version is an OT beta version?
I haven't installed it yet because you told me about it very recently ...

Thank you all

**Comment by RodneyBaker** [comment]
Rodney... err... my....  only side project these days seems to be drawing.
I need to be doing more of that.  :)

The nightly releases are what is heading for v1.6.
You could call it a beta... or alpha... or gamma... or epsilon... but... that wouldn't quite be accurate.  (definitely not an omega though!) ;)

A new nightly build is generated each time a new bugfix or feature is added to the program.
Usually this means the nightlies are slightly more stable than the annual release.**
The release of v1.5 back earlier this year had some issues that the nightlies address... such as slow drawing.
As such updating to a recent nightly release is highly recommended.

**The one time this is generally not the case is just prior to the annual release where development is hot and heavy.  As such there is an increased chance during that timeframe that something will slip through the cracks and introduce instability.  Just prior to the annual release (usually January of each year) it would generally be wise to avoid using the nightly releases unless specifically assisting with the release or haviing another compelling production need to use the nightly.  There are also automated builds created via Github for Windows, Mac and Linux that are similar to the nightly releases but those are in my estimation best used for testing.

**Comment by SPH404** [comment]
Are you the one who codes and updates OT?
Congratulations !!!!
I DID NOT KNOW !!!
Well done.

I suppose it is on this forum that we should list the bugs of OT?

Thank you 😃

**Comment by RodneyBaker** [comment]
> it is on this forum that we should list the bugs of OT?

One of the reasons the discord servers and other forums are recommended is to discuss and validate potential bugs.
In this way general workflow, troubleshooting and learning curve elements can be avoided here on github itself so that developers an concentrate on bug fixes and development.

But... having said that...
It is better to report something that turns out not to be a bug than to neglect reporting.
A problem cannot be addressed if/when no one knows about it.  :)

**Comment by SPH404** [comment]
Ok, thxxx
