### ISSUE TITLE
Some files were missing problem in opentoonz 

### ISSUE THREAD

**Issue by shamm321** [opentoonz/opentoonz#4016]
I have an scene in opentoonz but now it does not open and show some files were missing. I am very tensed because I have made that project with lots of effort and passion. So please please help me for getting out of these mesh. Pleaseeee

**Comment by RodneyBaker** [comment]
If you were using keyframes you likely have a corrupt keyframe problem in your scene file.

If you are able to share the .tnz scene file here as an attachment we might be able to find the problem.

If you prefer to investigate the problem on your own, you can open the .tnz file in a text editor (such as notepad++) and look for the bad keyframe entry.   Do a search for the word 'nan' as that is something recently observed in another users keyframe related problem.  Replacing the two instances of 'nan' with zeros recently repaired a similar problem.

**Comment by artisteacher** [comment]
You should take a look at the drawings and extras folder for your project (unless your images are saved elsewhere). Do the levels display there? If they are missing, you might still find backups of those files (named with .bak). Removing the .bak extension will allow the backups to load in OT. Backups don't display in the OT browser, though they do display in your system browser  ie. Finder or Explorer.

**Comment by shamm321** [comment]
What should I do now please tell ????

**Comment by RodneyBaker** [comment]
If you can upload the .tnz scene file we can take a look at it.
You may have to rename the extension from .tnz to .txt or zip it up as github likely won't recognize the .tnz extension as a valid attachment.

Getting a good look at the scene file will help eliminate some of the variables and... might even resolve the problem.f

If you cannot share the file the besty approach might be to reconstruct the scene using the images located in the drawings and extras directories.

**Comment by shamm321** [comment]
[animation.txt](https://github.com/opentoonz/opentoonz/files/6885357/animation.txt)

**Comment by RodneyBaker** [comment]
That file (animation.txt) is full of nothing but NULL entries.
If you open it in a text editor you will see that.
This unfortunately means that file is completely corrupted and cannot be used.

Perhaps there is another file in the scenes directory?  (such as one with the .bak  extension as @artisteacher suggested)

**Comment by RodneyBaker** [comment]
@shamm321 
You have neglected to provide information about your operating system and the version of Opentoonz you are using.
We really need you to provide that information.

WIndows?  Mac?  Linux?
Opentoonz 5.1?  

Also, if you know how to record your screen, sharing images or a video of what your are seeing will help tremendously in helping to recover your project.

**Comment by shamm321** [comment]
can u please say why this issue occurs???

And how to **prevent** it????

**Comment by RodneyBaker** [comment]
> can u please say why this issue occurs???
> 
> And how to prevent it????

The primary cause of the problem is that you are using an older version of Opentoonz that has a very serious problem.
Updating to a current release is the best thing I can suggest to prevent issues like this occuring.

Here is a link to the nightly releases:  https://github.com/opentoonz/opentoonz_nightlies/releases

Please let us know when you've installed the nightly and provide your operating system information so we can better prepare to assist you in the future..

**Comment by shamm321** [comment]
But I have got this issue in opentoonz 1.5. And I think thats only the new version then I thought that it can be solved by going back to older version but it did not so can u say another solution to prevent these issue.

**Comment by shamm321** [comment]
Can nighty version**prevent** these issue please tell
