### ISSUE TITLE
Crash when attempting to open AVI rendering option

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4017]
**Describe the bug**
Crash when attempting to render to AVI where the Options button is selected
Discovered while troubleshooting #4007 

**To Reproduce**
1.  Create some frames to render
2.  Open Output Settings dialog and set output to AVI format
3.  Click on the Options button to right of location where AVI format is set
Stall and crash

AVI appears to be the only problematic format.
Other output formats do not appear to have this problem.

**Expected behavior**
Options for AVI format should be presented and Opentoonz should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/2576432/126065498-76a0c1fa-43ca-4a40-87b7-e6c55a7f6ad9.png)

**Device Information:**
 - OS:  Windows
 - OpenToonz Version: Lastest nightly build

**Comment by beeheemooth** [comment]
Ooops! No crash.

![ezgif-2-801e639dec50](https://user-images.githubusercontent.com/25724133/126066128-781e98bd-09ba-493b-ad3f-c218fc76f500.gif)


However, Rodney did not deceive us, there really was such a crash before, but I forgot to write a report about it. And then this crash stopped appearing for a strange reason, and I thought that the problem was solved in some PR.

**Comment by RodneyBaker** [comment]
Thanks @beeheemooth for the feedback.
I suspect it might relate to a conflicting codec especially as I was troubleshooting a codec related issue when this problem was first observed.  I don't usually render to the AVI format so am not sure when the problem would have started.

**Comment by beeheemooth** [comment]
Hmm, if that's really the case, then we need to determine which codecs are causing the program to crash and which ones are preferable to use.

**Comment by RodneyBaker** [comment]
@justburner mentioned this during a recent discussion that seems related to this report:  #653

**Comment by RodneyBaker** [comment]
Crash log from selecting AVI > Options

[AVI Options crash.txt](https://github.com/opentoonz/opentoonz/files/9315120/AVI.Options.crash.txt)

My interpretation:  Indicators point to faulty codecs installed on local systems.

**Comment by artisteacher** [comment]
This is probably Windows specific. There's no AVI rendering from the macOS release - not sure about Linux.

**Comment by RodneyBaker** [comment]
Renaming the a DLL file rsolved this (and other) issues so it will be well worth looking into.
For more information please see:  #46

**Comment by RodneyBaker** [comment]
Closing as resolved but I'll wager users run into this problem regularly.
