### ISSUE TITLE
Geometric tool doesn't work on Toonz Raster and Raster Layer

### ISSUE THREAD

**Issue by jitterogue** [opentoonz/opentoonz#4022]
**Describe the bug**
Geometric tool won't work on toonz raster layer and raster layer.  When I double click or click away to finish the shape, it doesn't do anything.

**To Reproduce**
List steps to reproduce the behavior.
1. Choose geometric tool
2. Choose line/circle/rectangle or polyline
3. Draw the shape
4. Stop clicking on left mouse button or double click to finish drawing

**Expected behavior**
Doesn't produce anything

![SS Bug OPT](https://user-images.githubusercontent.com/88011575/127080863-21c76125-7613-48b6-bc34-23bd13ae3372.png)

**Device Information:**
 - OS: Windows
 - OpenToonz Version: Nightly (2021-07-26)]
 - GPU: Intel(R) HD Graphics 4600
 - GPU Driver Version: 10.18.10.4358

ps sorry for any mistakes, this is my first time on this platform.

**Comment by shun-iwasawa** [comment]
This seems to be because you are selecting the MyPaint style.
MyPaint style is currently available only with the brush tool. Set the style to plain color will work.

It would be better if MyPaint styles are available in the geometric tool as well, though..

**Comment by jitterogue** [comment]
Oh, that actually works!!! Yeah, a bit of a  bummer it can only be used with the default, but it's good for now. thanks!!
