### ISSUE TITLE
geometric tool problem on Chrome OS

### ISSUE THREAD

**Issue by GrishGautam** [opentoonz/opentoonz#4024]
I don't know please help me.

https://user-images.githubusercontent.com/85336666/127143048-fc205181-cbec-4ebd-98ca-2ef1c3cf5c3c.mp4

**Comment by shun-iwasawa** [comment]
It looks very strange.
In which operating system are you running the software?

**Comment by GrishGautam** [comment]
Am running this on chrome os. Installed through flatpak

**Comment by GrishGautam** [comment]
Can you please help me reinstall it again in proper way in chrome os.

**Comment by RodneyBaker** [comment]
Opentoonz is not supported on Chrome OS so you may wish to contact the folks that created the flatpack and see if they have any suggestions.

**Comment by GrishGautam** [comment]
I guess i will have to wait till google guys remove beta from chrome Linux support.
