### ISSUE TITLE
dull colors

### ISSUE THREAD

**Issue by SPH404** [opentoonz/opentoonz#4026]
Hello,
When I render an animation, the colors are not rendered exactly. They are dull.
Do you have an explanation ?

Big thanks

**Comment by DarrenTAnims** [comment]
Do you have any screenshots to show the difference?

**Comment by SPH404** [comment]
Yes : 

http://xmas.free.fr/fade01.bmp

**Comment by artisteacher** [comment]
In case this is a translucency issue, I would try setting the camera background color's alpha channel to 255 (fully opaque). You can do so in the Scene Settings window.

**Comment by SPH404** [comment]
Salvation,

I couldn't find anywhere where you can adjust the camera. And I can't find a tutorial on it.
Could you enlighten me?

**Comment by artisteacher** [comment]
<img width="300" alt="Screen Shot 2021-08-18 at 10 54 29 PM" src="https://user-images.githubusercontent.com/21159116/130000275-45c71c1a-6e67-4c3e-a7f7-12959993935e.png">

**Comment by shun-iwasawa** [comment]
@SPH404 
Does the problem occur with any player software? It looks like a long-standing “QuickTime Gamma Shift” problem.

**Comment by RodneyBaker** [comment]
Closing this as a question that is at least partially answered and/or abandoned.
Feel free to continue discussion here or open a new report as necessary.
