### ISSUE TITLE
Raster Brushes (Github Action Windows artifact)

### ISSUE THREAD

**Issue by andeon** [opentoonz/opentoonz#4027]
**Describe the bug**
The Raster Brushes aren't  working properly in the builds of Github Action for Windows (artifact) don't keep the chosen colors and has weird glitch in the strokes. 

Now I'm afraid to make test reports for non-existent bugs or not detecting them on new Pull requests. Since Raster Brushes works fine on nightly release, so maybe the run script to generate the artifact be out of date?

P.S. I'm not sure if there's anything else that doesn't work correctly in artifact. 

**To Reproduce**
List steps to reproduce the behavior.
1. Download a Windows Build  artifact
2. Create a level Raster or Toonz Raster
3. Use the raster brushes (more visible on textured brushes)

**Device Information:**
 - OS: [Windows]
 - OpenToonz Version: [Last Artifact]
 - GPU: [940MX]
 - GPU Driver Version: [430.63]

**Comment by andeon** [comment]
![Raster brushes](https://user-images.githubusercontent.com/11843239/129269006-4e741510-7853-4a35-8b67-75aec9ce5f52.jpg)

Now, I suspect that Mypaint lib or related is outdated.

**Comment by andeon** [comment]
@RodneyBaker  Do you know about appveyor config? Does it copy pre-artifact windows files or run another workflow action?  There the MyPaint settings and brushes work correctly without any glitches.

To test this, I downloaded the artifact "toonz\x64\OpenToonz.zip" in appveyor "Configuration: Release > Artifacts", but I believe the structure is to create the installer because the folders after extract:

toonz\x64\OpenToonz.zip
> Opentoonz
> OpenToonz Stuff

I extracted and rename OpenToonz Stuff to portablestuff and put it inside the extracted Opentoonz folder.

> - Opentoonz
>   - portablestuff

Bingo, it will work as portable and all worked right like nightly build.

So if we could check what appveyor does differently from others workflows could fix all.

**Comment by RodneyBaker** [comment]
While we might be able to figure out what is different/lacking in the github action build environment I believe @shun-iwasawa is the only one that can tweak that environment and get it running correctly.

I'll give it a look to see if anything stands out as different.
In my earlier check it seemed the mypaint library needed to be updated but... not sure.

**Comment by andeon** [comment]
Forgot to say the linux version also has the same issue as the windows artifact, not sure about the mac artifact, I gonna change the title to include this.

If you check the folder the appveyor artifact has so much more libs than windows artifact, but I think may be when the compilation happens, maybe for lack of paths or updated library as you predict. But it doesn't seem hard to fix.

**Comment by andeon** [comment]
I'd some tests and tried to follow the whole process, everyone can change it. But this is not the solution, is need to create steps to follow when there are big changes in libs, distro, etc. We need to fix what's missing in each environment so that everyone follows and is on the same page.

For example if we look at How to build locally it says QT 5.9, mypaint 1.3 things not working properly with 1.6.0 on linux https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_linux.md

Scripts is easier to maintain as we only need to change it when necessary. I did a test creating an opentoonz artifact with 1.4.0 mypaintlib using the script https://github.com/andeon/opentoonz/blob/fix_actions_linux/ci-scripts/linux/ot-buildlibmypaint.sh , https://github.com/andeon/opentoonz/blob/fix_actions_linux/.github/workflows/workflow_linux.yml

On Linux we still don't need to immediately switch to another distro if using the Stephan Binner PPA https://launchpad.net/~beineri it maintains PPAs for almost every version of Qt.

**Comment by andeon** [comment]
fixed after https://github.com/opentoonz/opentoonz/pull/5549
