### ISSUE TITLE
downloading .deb file of opentoonz.

### ISSUE THREAD

**Issue by GrishGautam** [opentoonz/opentoonz#4028]
**Question**
can you please guide me how to download .deb file of opentoonz. I love opentoonz and chromebook. In chromebook I can draw with pen bet in this laptop I need graphics tablet so please help me. Chromebook supports .deb file please.......help me............
sudo echo "deb http://www.deb-multimedia.org stable main" | tee -a /etc/apt/sources.list
tee: /etc/apt/sources.list: Permission denied
deb http://www.deb-multimedia.org stable main
this is what i get can you help me?

**Comment by RodneyBaker** [comment]
There is currently no known source for Opentoonz or any of it's forks in the .deb format.
But perhaps this is the most likely source:

https://pkgs.org/download/opentoonz

**Comment by GrishGautam** [comment]
Ah.....thank you RodneyBaker..........I edited my comment can you please help????????

**Comment by RodneyBaker** [comment]
Sorry, I don't speak Linux.
Perhaps someone that does will see your query and have some advice.

**Comment by GrishGautam** [comment]
grishgautam17@penguin:~$ wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
--2021-08-01 20:14:09--  http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
Resolving www.deb-multimedia.org (www.deb-multimedia.org)... 2001:41d0:1:c3c4::1, 91.121.146.196
Connecting to www.deb-multimedia.org (www.deb-multimedia.org)|2001:41d0:1:c3c4::1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10658 (10K) [application/vnd.debian.binary-package]
Saving to: ‘deb-multimedia-keyring_2016.8.1_all.deb.2’

deb-multimedia-keyring_2016.8.1_all.d 100%[======================================================================>]  10.41K  --.-KB/s    in 0s      

2021-08-01 20:14:14 (77.8 MB/s) - ‘deb-multimedia-keyring_2016.8.1_all.deb.2’ saved [10658/10658]

grishgautam17@penguin:~$ 
grishgautam17@penguin:~$ sudo dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
Selecting previously unselected package deb-multimedia-keyring.
(Reading database ... 62344 files and directories currently installed.)
Preparing to unpack deb-multimedia-keyring_2016.8.1_all.deb ...
Unpacking deb-multimedia-keyring (2016.8.1) ...
Setting up deb-multimedia-keyring (2016.8.1) ...
grishgautam17@penguin:~$ 
grishgautam17@penguin:~$ sudo echo "deb http://www.deb-multimedia.org stable main" | tee -a /etc/apt/sources.list
tee: /etc/apt/sources.list: Permission denied
deb http://www.deb-multimedia.org stable main
grishgautam17@penguin:~$ 
here are codes I typed in terminal......Thanks in advance for anyone who helps me fix this.
