### ISSUE TITLE
opentoonz installation error in linux following everything from readthedocs.

### ISSUE THREAD

**Issue by GrishGautam** [opentoonz/opentoonz#4029]
**Question**
Debian GNU/Linux
wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb
sudo dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
sudo echo "deb http://www.deb-multimedia.org stable main" | tee -a /etc/apt/sources.list Builds for testing and sid also avalaible.
sudo apt update && apt install opentoonz opentoonz-data
For updating enter sudo apt update && apt upgrade.

I did this and opentoonz is not updating. It says opentoonz version 1.3 there are 2 opentoonz 1 is v1.3 another is not opening.

update:
from snap I installed opentoonz again. then while opening it in terminal it says this:
grishgautam17@penguin:~$ opentoonz
libdc1394 error: Failed to initialize libdc1394
No protocol specified
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.

**Comment by GrishGautam** [comment]
there are 2 opentoonz installed. one doesnot opens whereas another says it is version 1.3

**Comment by Savraska2** [comment]
Unofficial Deb Multimedia repository contains 1.3 version OpenToonz for current stable Debian 10 (buster). You can update your system into testing or wait new stable release Debian 11 (bullseye) which is will avalaible (possibly) 14th September. Debian 11 fully support OpenToonz 1.5.

**Comment by GrishGautam** [comment]
I guess I will wait and i am not running Linux Debian it is Linux built in support for Chromebook. Anyway so I will have to wait for 16 days more. OR any suggestion for installing it on Chromebook it is only device I have that has screen touch support.

**Comment by GrishGautam** [comment]
grishgautam17@penguin:~$ sudo echo "deb http://www.deb-multimedia.org stable main" | tee -a /etc/apt/sources.list
tee: /etc/apt/sources.list: Permission denied
deb http://www.deb-multimedia.org stable main
grishgautam17@penguin:~$ sudo -i
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
root@penguin:~# sudo echo "deb http://www.deb-multimedia.org stable main" | tee -a /etc/apt/sources.list
deb http://www.deb-multimedia.org stable main
root@penguin:~# sudo apt update && apt install opentoonz opentoonz-data

Ign:1 https://storage.googleapis.com/cros-packages/92 buster InRelease          
Hit:2 https://deb.debian.org/debian bullseye InRelease                          
Hit:3 https://storage.googleapis.com/cros-packages/92 buster Release
Get:5 http://www.deb-multimedia.org stable InRelease [15.8 kB]
Get:6 http://www.deb-multimedia.org stable/main amd64 Packages [122 kB]
Get:7 http://www.deb-multimedia.org stable/main Translation-en [54.2 kB]
Fetched 192 kB in 22s (8,655 B/s)         
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 opentoonz : Depends: libjson-c3 (>= 0.10) but it is not installable
             Depends: libmypaint-1.3-0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
