### ISSUE TITLE
saving is broken and random closing

### ISSUE THREAD

**Issue by SimonCrys** [opentoonz/opentoonz#4031]
**Describe the bug**
no matter what i do my work just wont save, every time i do and opentoonz closes by itself the save is flawed and the drawings i did are not to be seen but the fames are visible. 
every time i click out of opentoonz it closes itself on its own.
**To Reproduce**
List steps to reproduce the behavior.
1.click crome
2.opentoonz closes
3.

**Expected behavior**
I expect my work to be saved and the window not to close when i'm not on it or randomly
**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]

**Comment by DarrenTAnims** [comment]
Hi. This is a confusing report. If you can delete parts of the template that you're not using, that'll help the report to read better. Also, if you can edit your original post, rather than adding more, that'll make it easier for everyone to read.
What did you press to save your project?
Your steps to reproduce are, Click Chrome, then OpenToonz closes ??? What's Chrome got to do with anything. If you can list the steps that you got through to cause the issue, that'd help. Is it only when you load a specific project or when you start a new project, what do you do before and as OpenToonz closes?

**Comment by shames-moon** [comment]
> أهلا. هذا تقرير محير. إذا كان بإمكانك حذف أجزاء من النموذج لا تستخدمها ، فسيساعد ذلك في قراءة التقرير بشكل أفضل. أيضًا ، إذا كان بإمكانك تعديل مشاركتك الأصلية ، بدلاً من إضافة المزيد ، فسيؤدي ذلك إلى تسهيل قراءتها على الجميع.
> ماذا ضغطت لحفظ مشروعك؟
> خطوات إعادة الإنتاج هي النقر على Chrome ثم إغلاق OpenToonz ؟؟؟ ما علاقة Chrome بأي شيء. إذا كان بإمكانك سرد الخطوات التي مررت بها لإحداث المشكلة ، فسيساعدك ذلك. هل هو فقط عند تحميل مشروع معين أو عند بدء مشروع جديد ، ماذا تفعل من قبل وعندما يغلق OpenToonz؟
**mister Darren T sir
I think I have the same problem
When I open Google Chrome and Opentoonz together
I can't switch between programs
Because Opentoonz will automatically close
not only this
I can't open software besides Opentoonz even the image viewer**

**Comment by shames-moon** [comment]
> أهلا. هذا تقرير محير. إذا كان بإمكانك حذف أجزاء من النموذج لا تستخدمها ، فسيساعد ذلك في قراءة التقرير بشكل أفضل. أيضًا ، إذا كان بإمكانك تعديل مشاركتك الأصلية ، بدلاً من إضافة المزيد ، فسيؤدي ذلك إلى سهولة قراءتها على الجميع.
> ماذا ضغطت لحفظ مشروعك؟
> خطوات إعادة الإنتاج هي النقر على Chrome ثم إغلاق OpenToonz ؟؟؟ ما علاقة Chrome بأي شيء. الأمر الذي يمكن أن تحدثه بشأن حدوث بعض الإجراءات. هل هذا فقط عند تحميل مشروع معين أو عند بدء مشروع جديد ، ماذا تفعل من قبل عندما يغلق OpenToonz؟

**Comment by shames-moon** [comment]
mister Darren T sir
I think I have the same problem
When I open Google Chrome and Opentoonz together
I can't switch between programs
Because Opentoonz will automatically close
not only this
I can't open software besides Opentoonz even the image viewer

**Comment by shames-moon** [comment]
mister Darren T sir
I think I have the same problem
When I open Google Chrome and Opentoonz together
I can't switch between programs
Because Opentoonz will automatically close
not only this
I can't open software besides Opentoonz even the image viewer

**Comment by DarrenTAnims** [comment]
Using Chrome and saving are 2 different issues. These need separating into separate reports.
The Chrome one I've had kind of similar issues with before. From time to time, switching from OpenToonz to another program and back makes OT crash, but getting into the habit of saving often, especially when switching programs is helpful for this.
So I was asking more about the saving issue, asking for details of what happens, then maybe we can make suggestions.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@SimonCrys Please feel free to add additional information as you see fit.
