### ISSUE TITLE
OpenToonz Opens, then Closes

### ISSUE THREAD

**Issue by David-Beigoma** [opentoonz/opentoonz#4041]
https://user-images.githubusercontent.com/89023528/129585658-6104714c-a9cf-41dc-8659-d6f4c53c7c41.mp4

Hi there, I wanted to start on a new animation project on OpenToonz, but the program keeps opening and closing. I tried running the program in Administrator Mode, but, it wasn't responding. Below is a video of what keeps happening to me when I launch it. 

Computer Specs:

Computer: Dell XPS 8940(2019)
OS: Windows 10 Home(Build 2004)
GPU: AMD Radeon FirePro W2100 2GB DDR3
CPU: Intel Core i5 
Disk Drives: 5
Architecture: 64 Bit Operating System(x64 based processor)
Memory: 8 GB Installed

**Comment by GeneralFlipHax** [comment]
Can you send me the logs from the Event Viewer? Maybe I can figure it out...

**Comment by David-Beigoma** [comment]
There are logs. They both say:
================================================================
Faulting application name: OpenToonz.exe, version: 0.0.0.0, time stamp: 0x6071a1fd
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x0000000000000000
Faulting process id: 0x3ce4
Faulting application start time: 0x01d792b78e500bac
Faulting application path: C:\Program Files\OpenToonz\OpenToonz.exe
Faulting module path: unknown
Report Id: 5a623c24-d701-4e16-9dba-ff75396ca022
Faulting package full name: ?
Faulting package-relative application ID: ?
=================================================================
Information:
Fault bucket 1216516299856549892, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: OpenToonz.exe
P2: 0.0.0.0
P3: 6071a1fd
P4: StackHash_ac46
P5: 0.0.0.0
P6: 00000000
P7: PCH_43_FROM_ntdll+0x000000000009D974
P8: c0000005
P9: 0000000000000008
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER559.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5D8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5F2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER602.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OpenToonz.exe_37c39577c163e83f5ad43325860b349c2a9b27a_ed821c1e_091e90f5-886a-45d4-9fff-af7396e51110

Analysis symbol: 
Rechecking for solution: 0
Report Id: e91f11a9-32f6-4646-82c6-9ce306b782f0
Report Status: 268435456
Hashed bucket: b002b9a3652cc5da00e1ef211c6c1804
Cab Guid: 0

**Comment by GeneralFlipHax** [comment]
Ahhh ok. I'm thinking it's a corrupted system file. Did you try deleting one of the system32 files? Or even reinstalling the program?

**Comment by David-Beigoma** [comment]
I reinstalled the program, but the program keeps crashing... What's the second method?

**Comment by GeneralFlipHax** [comment]
Well, to delete the svf.dll file... It works for me?

**Comment by GeneralFlipHax** [comment]
System32 files are important, but not all of them are important, you can delete system32 files, and it won't even do a thing to the computer... Just trust me okay? ;)

**Comment by David-Beigoma** [comment]
So I can delete several system32 files without harming the computer? Dang, not even I knew that, Imma try and delete the lvcod64.dll file... Also, can it be with the graphics drivers?

**Comment by GeneralFlipHax** [comment]
Maybe, OpenToonz will run slowly on AMD and Intel graphics cards, but Nvidia works best with OpenToonz. The reason why is becasue Nvidia has more processing power than Intel or AMD.

**Comment by David-Beigoma** [comment]
Update: It didn't work... Tried getting an NVIDIA graphics card, but, it didn't work...

**Comment by GeneralFlipHax** [comment]
Maybe your whole computer is corrupted. Maybe you need to delete all your files and do a clean install on your computer. It will make OpenToonz work, or even run better...

**Comment by David-Beigoma** [comment]
But I don't want to reinstall an operating system or get an Adobe CC Plan, and my project is due in 5 days! Please help!

**Comment by GeneralFlipHax** [comment]
Sorry, but there's no other way anymore. Sorry dude, Open source software can make life more harder because of bugs and all that.  Adobe is more trustworthy and I highly recommend it. Sorry dude, but I think you're on your own. I didn't use this software in the first place, it's going to make your computer even worse. Byeeeee!

**Comment by manongjohn** [comment]
@David-Beigoma 

One thing to check is the permissions on the `C:\OpenToonz stuff` folder which is a more common reason for what you are experiencing.  Right click on it and go to the Security tab. Look in the top box for your login and see if it is there.  If not, add it and make sure you give yourself Full access. 

If you have anti-virus software running, try temporarily disabling it in case it is shutting down/quarantining stuff OpenToonz is trying to use/launch in the background.  If that is the reason, you may need to add an exception for OpenToonz.

**Comment by David-Beigoma** [comment]
@manongjohn Tried turning off my antivirus software, but the problem persists. Tried giving myself full access to the computer, but the program keeps crashing, maybe the fact that my dad recently tampered with my user privileges with programs(kinda the reason why Discord can't open) :/
![2021_08_17_12_34_21_Windows_C_](https://user-images.githubusercontent.com/89023528/129774992-6ab027ec-d914-4e2d-864e-c41fc4363e2f.png)

**Comment by GeneralFlipHax** [comment]
@David-Beigoma JUST USE ADOBE ANIMATE DUMMY! IT'S NOT MY PROBLEM THAT YOUR DAD BLOCKED YOUR USER ACCESS, OR YOU DON'T HAVE MONEY! IT'S THE ONLY WAY IF YOU WANT THAT SCHOOL PROJECT TO BE DONE EARLY! I DON'T CARE IF YOU DON'T HAVE ANY MONEY, JUST GET A GODDANG JOB! IT'S THAT EASY!!!!!!!!!

**Comment by David-Beigoma** [comment]
Dude- just chill...

**Comment by RodneyBaker** [comment]
@GeneralFlipHax It is very rare when we have to step in and moderate here in Opentoonz github.  
Please moderate yourself so others won't have to.
Thanks.

**Comment by manongjohn** [comment]
Wish we could kick trolls out....

@David-Beigoma  Ignore anything that idiot says since he's obviously here just to cause trouble.  Sorry you have to experience that.

Your permissions appears to be correct.  Your account appears to have full access to that folder.  Another thing to try is to go to the `General` tab on the stuff folder and uncheck `Read Only` and 'Apply' and make sure it applies to that folder and subfolders.

You might also want to try and uninstall and reinstall OT again, just in case.  If you do that, I would rename the current stuff folder to move it out of the way so you can do a fresh install.  Temporarily disable anti-virus when installing in case it's doing something in case it is somehow messing up the install.

**Comment by RodneyBaker** [comment]
In addition to what @manongjohn said I will recommend installing the latest nightly release (as opposed to the original v1.5 release).  There have been several bug fixes and updates since that initial release that might make the difference for you.

NIghtly releases can be found here:

https://github.com/opentoonz/opentoonz_nightlies/releases

To re-emphasize what @manongjohn said before... it is recommended that you uninstall (i.e. use the included uninstaller that comes with Opentoonz) prior to reinstalling   and  rename your stuff directory located at C:\Opentoonz stuff so that you get all new config files installed.

**Comment by David-Beigoma** [comment]
I tried reinstalling the program in Administrator Mode, but the problem persists. I also tried installing the nightly build, but the program wasn't responding, I might try using Krita for the time-being. Let me try finding an answer on YouTube to see if it helps...
![Keeps Not Responding](https://user-images.githubusercontent.com/89023528/129808822-2e16d499-f6d8-4bf8-96a1-7bb71a16b3df.png)

**Comment by David-Beigoma** [comment]
UPDATE: I ran a troubleshooter, and it says that OpenToonz is Incompatible with your system. I have all the maximum system requirements, but what am I missing?
![image](https://user-images.githubusercontent.com/89023528/129819025-aacfa45a-5441-4515-a9fe-b2fdd3e5680b.png)

**Comment by manongjohn** [comment]
Ah. Copy C:\Program Files\OpenToonz\glut32.dll to C:\Windows\SysWOW64

**Comment by David-Beigoma** [comment]
Hmmm... Tried that, but still, didn't work...

**Comment by shun-iwasawa** [comment]
@David-Beigoma
Please try renaming a folder `C:\Program Files\OpenToonz\srv` to some another name like `srv_tmp` . Then launch the software.

According to the error message there seems to be a problem with `t32bitsrv.exe` which is contained in the `srv` folder.
`t32bitsrv.exe` is only for reading/writing QuickTime Mov format and you can just remove it if you don't need it.

**Comment by David-Beigoma** [comment]
Hmmm..... I don't have the error anymore, but it still shows that white screen, then closes. Here's a screenshot of what the window has shown 2 seconds before it closed...
![image](https://user-images.githubusercontent.com/89023528/129904415-8816392c-2127-49d0-b026-911d33d2da5c.png)

**Comment by David-Beigoma** [comment]
UPDATE: I found a different error in the Event Viewer, and for some reason, it's an AppCrash...
<HTML><HEAD>
<SCRIPT>
  
    function Toggle(node)
    {
      if (!window.fullyLoaded) return;

      // Expand the branch?
      if (node.nextSibling.style.display == 'none')
      {
        // Change the sign from "+" to "-".
        var tBodyNode = node.childNodes[0];
        var trNode = tBodyNode.childNodes[0];
        var tdNode = trNode.childNodes[0];
        var bNode = tdNode.childNodes[0];
        var textNode = bNode.childNodes[0];
        if (textNode.nodeType == 3 /* Node.TEXT_NODE */) {
          var s = textNode.data;
          if (s.length > 0 && s.charAt(0) == '+') {
            textNode.data = '-' + s.substring(1, s.length);
          }
        }

        // show the branch
        node.nextSibling.style.display = '';
      }
      else // Collapse the branch
      {
        // Change the sign from "-" to "+".
        var tBodyNode = node.childNodes[0];
        var trNode = tBodyNode.childNodes[0];
        var tdNode = trNode.childNodes[0];
        var bNode = tdNode.childNodes[0];
        var textNode = bNode.childNodes[0];
        if (textNode.nodeType == 3 /* Node.TEXT_NODE */) {
          var s = textNode.data;
          if (s.length > 0 && s.charAt(0) == '-') {
            textNode.data = '+' + s.substring(1, s.length);
          }
        }

        // hide the branch
        node.nextSibling.style.display = 'none';
      }
    }

    // Toggle "System" element by default so that it's default status is to hide its children
    function ToggleSystemElement()
    {
      var body = document.getElementById("body");
      var anchor = body.getElementsByTagName("table")[0];
      Toggle(anchor);
    }

    // If binary data is present in event XML, show it in friendly form.
    function ProcessBinaryData(binaryString, binaryDataCaption, wordsFormatString, bytesFormatString, normalFont, fixedWidthFont)
    {
      var bodyNode = document.getElementById("body");

      // Add a <hr> at the end of the HTML body.
      bodyNode.appendChild(document.createElement("hr"));      

      // This paragraph (p element) is the "Binary data:" literal string.
      var p = document.createElement("p");
      p.style.fontFamily = normalFont;
      var b = document.createElement("b");
      b.appendChild(document.createTextNode(binaryDataCaption));
      p.appendChild(b);
      p.appendChild(document.createElement("br"));
      bodyNode.appendChild(p);

      //
      // Show binary data in Words format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(wordsFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      var i = 0;
      var j = 0;
      var s, tempS;
      var translatedString;
      var charCode;
      var byte1, byte2;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte; 4 characters for a word.
      while (i < binaryString.length) {

        s = (i / 2).toString(16);    // To hex representation.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // DWords representation is simply a rearrangement of the original binaryString
        // For example, from:
        // 
        // 0000000002005600000000000f000540
        //
        // (which is 00 00 00 00 02 00 56 00 00 00 00 00 0f 00 05 40).
        //
        // to:
        //
        // 0000: 00000000 00560002 00000000 4005000f
        // 8 words per line, 4 DWords per line.
        for (j = 0; j < 4; j++) {
          s += binaryString.substring(i + 6, i + 8);
          s += binaryString.substring(i + 4, i + 6);
          s += binaryString.substring(i + 2, i + 4);
          s += binaryString.substring(i, i + 2) + " ";
          i += 8;
        }

        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);

      //
      // Show binary data in bytes format.
      //
      p = document.createElement("p");
      p.style.fontFamily = normalFont;
      p.appendChild(document.createTextNode(bytesFormatString));
      bodyNode.appendChild(p);

      // Must use fixed-width font for binary data.
      p = document.createElement("p");
      p.style.fontFamily = fixedWidthFont;
    
      i = 0;
      j = 0;

      // Each character in binaryString is a hex (16-based) representation of
      // 4 binary bits. So it takes 2 characters in binaryString to form a
      // complete byte.
      while (i < binaryString.length) {
        translatedString = "";
        // 2 characters in binaryString to form a byte
        s = (i / 2).toString(16);   // to hex representation.

        // Prefix with '0' until its length is 4.
        while (s.length < 4) {
          s = "0" + s;
        }
        s += ": ";

        // Show 8 bytes per line
        for (j = 0; j < 8; j++) {
          tempS = binaryString.substring(i, i + 2); // 2 for 1 byte
          i += 2;
          s += tempS + " ";

          // Treat tempS as hex integer
          charCode = parseInt(tempS, 16);
          if (charCode < 32) {
            translatedString += ".";
          } else {
            translatedString += String.fromCharCode(charCode);
          }
        }

        while (s.length < 32) {
          s += " ";
        }
        s += translatedString;
        
        p.appendChild(document.createTextNode(s));
        p.appendChild(document.createElement("br"));
      }

      bodyNode.appendChild(p);
    }
  
  </SCRIPT>
</HEAD>
<BODY id=body onload=window.fullyLoaded=true;ToggleSystemElement();>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR><TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">1404470532218248006</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">4</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">APPCRASH</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Not 
available</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">OpenToonz.exe</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0.0.0.0</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">6071a1fd</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">StackHash_8f51</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0.0.0.0</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">00000000</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">c000041d</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">PCH_84_FROM_unknown+0x0000000000000000</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top"></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top"></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE1F6.tmp.mdmp 
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE274.tmp.WERInternalMetadata.xml 
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE285.tmp.xml 
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE285.tmp.csv 
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE2A5.tmp.txt</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OpenToonz.exe_ae3de9527659f6d1157831bee11324423e6e8df_ed821c1e_68bbb261-f1d2-4e84-a435-74fa2c608f84</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top"></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">185b9320-17d8-4390-9571-27e8fc0fd2c4</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">268435456</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2bddba436a234284037dae82025f5b46</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></DIV></BODY></HTML>

**Comment by David-Beigoma** [comment]
UPDATE: I went on my friends' computer(which has a working state of OpenToonz) and transferred the ProgramFiles > OpenToonz folder, and my C: > OpenToonz stuff folder to my computer , but the program had the same crash, so it's something that has to do with my computer...

**Comment by David-Beigoma** [comment]
OH MY GOD!!!!!!!!!!!! IT WORKED!!!!!!!!!! I JUST ACCDINTALLY CLICKED ON AN INSTALLATION OF MY DRIVER IN MY DOWNLOADS FOLDER (WHICH I DIDN'T NOTICED) AND THE DAY AFTER, I OPENED OPENTOONZ! IT WAS A CORRUPTED GRAPHICS MODULE! HOPE THIS WILL HELP ANYONE IN THE FUTURE! TYSM FOR THE PEOPLE WHO HELPED ME THROUGH THIS PROCESS OF TRIAL AND ERROR!

**Comment by vehosah** [comment]
> @David-Beigoma JUST USE ADOBE ANIMATE DUMMY! IT'S NOT MY PROBLEM THAT YOUR DAD BLOCKED YOUR USER ACCESS, OR YOU DON'T HAVE MONEY! IT'S THE ONLY WAY IF YOU WANT THAT SCHOOL PROJECT TO BE DONE EARLY! I DON'T CARE IF YOU DON'T HAVE ANY MONEY, JUST GET A GODDANG JOB! IT'S THAT EASY!!!!!!!!!

Dude chill the fuck out

**Comment by David-Beigoma** [comment]
So y'all we're wondering about the guy who started bugging me on the issue, turns out, he was an old classmate who somehow got my GitHub user (I believe he got it from my Discord Bio) and started "joking" with me by posting all these comments. He even did the same thing on Discord servers too, little did I know, he was using alt accounts. So, in September, I confronted him by DM and took him two days (25-26) to fully apologize to me. In the end, we all good and learned his lesson, but still, he still feels bad on what he did to me, as a so-called harmless "joke."  Can't believe people still do these until today...

**Comment by vehosah** [comment]
> So y'all we're wondering about the guy who started bugging me on the issue, turns out, he was an old classmate who somehow got my GitHub user (I believe he got it from my Discord Bio) and started "joking" with me by posting all these comments. He even did the same thing on Discord servers too, little did I know, he was using alt accounts. So, in September, I confronted him by DM and took him two days (25-26) to fully apologize to me. In the end, we all good and learned his lesson, but still, he still feels bad on what he did to me, as a so-called harmless "joke." Can't believe people still do these until today...

Don't worry, this guy doesn't deserve your attention

**Comment by David-Beigoma** [comment]
Lol, it also happens when ur part of the bois. Once they do these types of stuff when they get used to you, there's no going back XD

**Comment by GeneralFlipHax** [comment]
Yo... you still active after all these months? I've never heard from you ever since...

**Comment by GeneralFlipHax** [comment]
I've finally switched to OpenToonz like you said, and overall, it was a great alternative! I've had some issues, but I'll figure it out, or ask in the forums.
