### ISSUE TITLE
Please add method to user manual to install opentoonz(i installed it) and t runs perfectly. It is sugesstion to add in user manual.

### ISSUE THREAD

**Issue by GrishGautam** [opentoonz/opentoonz#4045]
**Is your feature request related to a problem? Please describe**
I wanted opentoonz in my chromebook but it was not easy. I did some steps and I will share them here.
**Describe the solution you'd like**
in chromebook firstly enable linux 
then 
in chrome://flags disable Crostini GPU Support
you will have to restart.

then
sudo apt install flatpak

then 
sudo apt install opentoonz
with this opentoonz will be installed without any bugs in program

Thanks........ as always.....

**Comment by RodneyBaker** [comment]
@GrishGautam There is a separate github repo for the manual/online documentation.
That can be found here:

https://github.com/opentoonz/opentoonz.github.io

**Comment by RodneyBaker** [comment]
Closing this as it relates to Opentoonz documentatio and not the program itself.
