### ISSUE TITLE
i accidentally deleted some of the windows such as the window that you need to change colour

### ISSUE THREAD

**Issue by cyanideinfection** [opentoonz/opentoonz#405]
i was trying to move it and accidentally closed it and i cant get it back! i tried reinstalling but even that wont work help me pls

**Comment by cyanideinfection** [comment]
i have now found a way to get the windows but the palette window wont open

**Comment by turtletooth** [comment]
What version of OT are you using? What room(tab) did you delete stuff from?  

You can create a new room(tab) at the top by right clicking on a room such as cleanup and choosing new room.  With that new room selected you now have an option in Windows->reset to default rooms.  The next time you open OT, it should reset.

If that does not work:
You can reset the rooms by going to your OpenToonz stuff folder going to profiles/layouts and going into the OpenToonz.yourUserName folder and deleting currentroom.txt, layouts.txt and all room#.ini files.  This will repopulate the rooms with the default rooms from the profiles/layouts/OpenToonz folder.  A change will soon be released that makes resetting rooms from inside
