### ISSUE TITLE
onion skin doesn't work on rigged character

### ISSUE THREAD

**Issue by matitanimata** [opentoonz/opentoonz#4056]
the onion  skin doesn't work on a rigged character. 

1. build a rigged character
2. animate the character
3. activate onion skin to adjust character poisition

the onion skin doesn't work, the levels become just slightly transparent, making the animation process very difficult (for istance, in a a walk we need to check the previous feet position to avoid the character slipping on the ground).

![Schermata 2021-09-09 alle 09 02 46](https://user-images.githubusercontent.com/20012515/132642094-4d0d41bd-a939-40f4-8817-1f28c2bc95c7.png)

if the onion skin is applied to the subscene in which the character is, the onion skin works properly (but of course we can't animate it)
![Schermata 2021-09-09 alle 09 02 09](https://user-images.githubusercontent.com/20012515/132642084-b1f0e509-21b3-4f6d-9a89-c69a61346d88.png)

opening the same scene in Tahoma the onion skin works always properly.
![Schermata 2021-09-09 alle 09 50 47](https://user-images.githubusercontent.com/20012515/132645800-0a0d6613-a720-4287-b36c-8b9e9bc1c598.png)

**Device Information:**
 - OS: mac os mojave
 - OpenToonz Version: OT 1.5 build Aug 24 2021

**Comment by beeheemooth** [comment]
The problem that you described is most likely related to the different display of Onion Skin in different Numbering Systems (#3632). I don't understand why Onion Skin's behavior should depend on this preference option. If the user uses Numbering System: Animation Sheet then he cannot see Onion Skin in exposure frames, for this he needs to enable Numbering System: Incremental. Nonsense!

**Comment by matitanimata** [comment]
@beeheemooth thank you! I would not have understood it in a million years, I was going crazy. That's really nonsense, I agree!
