### ISSUE TITLE
Disallow the mouse wheel adjusting drop downs until they have focus

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#4060]
**Describe the bug**
While scrolling down the output settings with a mouse wheel, it's really easy for the mouse pointer to accidentally be over a dropdown and while scrolling the drop down value changes.

**Expected behavior**
Until you select on a dropdown, the mouse wheel shouldn't change the value.

**User problems**
Users are often accidentally changing dropdowns in their output settings and not getting the output they expect. In particular, the Multiple Rendering option is often changed and users don't get the output they expect. And they don't know that they've changed something. And CAN'T know how to fix it because it's not something that they've actually changed.

**Device Information:**
 - OS: Windows
 - OpenToonz 1.5

**Comment by RodneyBaker** [comment]
I believe this problem was addressed.
Closing.
