### ISSUE TITLE
Opentoonz drawing issue

### ISSUE THREAD

**Issue by LeinadSW45** [opentoonz/opentoonz#4062]
Something VERY weird is happening with stroke when I draw I tried resetting the program multiple times, I even tried reinstalling the program but Its STILL doing it What should I do?
![untitled53_  sandbox  _ OpenToonz 1 5 9_12_2021 3_02_04 PM](https://user-images.githubusercontent.com/70663390/132999648-70e45fa4-5c54-46b5-b7c8-2cb476d0f6f7.png)

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@LeinadSW45 Please let us know if you are still experiencing problems.
