### ISSUE TITLE
levels disappear from view despite being present on timeline

### ISSUE THREAD

**Issue by conformitycontrol** [opentoonz/opentoonz#4070]
When I opened my project, both F and G levels disappeared. Attached is a screenshot. Anybody know what to do? I'm very new to this.

![Capture](https://user-images.githubusercontent.com/91038087/133949223-158e24df-025a-48d1-9fc5-f9abd1dc9a99.PNG)

**Comment by DarrenTAnims** [comment]
I can't tell which of your levels are F & G, but I can see that you're not showing any levels in your viewer. You've turned off the columns in the column header. To the left of each column (Col1, Col2, etc), there are 4 boxes. The far left box is to include that column in your render. The one next to it is to show that column in the viewer. Click them to show them all.

**Comment by conformitycontrol** [comment]
> 
> 
> I can't tell which of your levels are F & G, but I can see that you're not showing any levels in your viewer. You've turned off the columns in the column header. To the left of each column (Col1, Col2, etc), there are 4 boxes. The far left box is to include that column in your render. The one next to it is to show that column in the viewer. Click them to show them all.

Hi Darren,

I click on the far left boxes and it doesn't seem to do anything. There used to be icons where those boxes were, but when I reloaded the file they've disappeared. Any suggestions?

**Comment by artisteacher** [comment]
Something definitely looks wrong. If you restart the computer, are the visibility icons still missing? Is it that way in every scene/project?

**Comment by conformitycontrol** [comment]
> 
> 
> Something definitely looks wrong. If you restart the computer, are the visibility icons still missing? Is it that way in every scene/project?

Yea its stuck like this. I don't know what to do

**Comment by RodneyBaker** [comment]
When I see UI elements not appear that seems to be an indication of a faulty installation.  As such I'll recommend installing the latest nightly release over the top of your current installation.

The latest nightly was posted three days ago and can be found here:

https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by gab3d** [comment]
A clean installation might always take potential problems out of the equation too.
