### ISSUE TITLE
A way to slide a cell over its neighbouring hold cells, while moving it.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#4078]
@shun-iwasawa @RodneyBaker 

While animating frame by frame digitally in OT, an usual procedure is to first draw key frames and then start drawing inbetweens in the intermediate space between the already drawn key frames.
As currently the default method of creation in the Xsheet automatically places "holding cells" inbetween exposed cells, it gets pretty uncomfortable when you need to move one of those newly drawn inbetweens to expose it a little early/late in the Xsheet to adjust timing.

An elegant solution to this problem could be to have a "Slide" function, that allowed to automatically adjust nearby "holding cells", while moving the first cell in which a drawing is exposed.

Example:
11**2**222333  (slide 1 frame to the left)
111**2**22333  (original)
1111**2**2333  (slide 1 frame to the right)

Activation of this new mode could simply be by holding some modifier keys (Ctrl + Shift) prior to dragging a cell.

What do you think about it?

**Comment by RodneyBaker** [comment]
Hi @gab3d 
You bring several thoughts to mind.
Firstly, you raise a good point about the process being harder than it needs to be.
Additionally, I note:
- We almost have what you propose
-- When we turn off the option to auto stretch frames we basically get what you propose with one very important shortfall... the empty frames do not display the previous 'key' frame exposed. Aside:  If there was an option to display the last exposed frame during scrubbing for all empty cells that might equate to the same process you outline
- While I follow your specific use case I am certain it will fall short of an expectation by users not to just 'slide' one cell but rather a selection of cells.  This in my estimation would be the full feature you suggest here.  If one cell is selected that cell would slide and the 'empties' would fill with exposures of the last cell occupied.   If multiple cell were selected and slid... that selection would slide and any empties would likewise fill with auto-stretched exposures.
- There are some special cases which would need to be accounted for but we'll imagine they are can be satisfied.

What I would encourage you to do... and perhaps you've already done this... is play with the option that allows us to currently slide a selection (either one or more cells) into empty cells and -through- previously exposed cells (with auto-stretch off).  It would be good to know in what way this falls short of your expectations.   I do note that our selection moves through any cells with exposures an it would be nice if there was a way to have our selected cells push that exposure to a new location.  Perhaps there already is and I'm not aware of it.

Now is an excellent time to review this area of workflow so thanks for bring up the subject.

**Comment by gab3d** [comment]
@RodneyBaker thanks for your thoughts on this one.

Yes, I considered what's pointed out in your first suggestion (turning off **Enable Auto-stretch Frame** option), the problem with that is exactly what you found out: currently there's no way to show "fake hold drawings" while previewing the animation, so it's really very difficult to see what your doing. Of course there could be a Preview Using Fake Holds mode to see those ghost holds while working, and then turn it off when you don't need them anymore.

Still, the potential shortcomings and issues of such a method, coupled with what I asses as a more complex implementation task is what made me discard it, and propose the other workflow instead.
(*shortcomings*: most probably it'd be a "global" preview mode, so it'd fake holds for all scene layers while active. A little messy I guess. 
*issues*: user forgets to turn it off, or turn it on accidentally (novices) and start seeing (and reporting) all sorts of apparently unexplainable behavior).

Regarding the use case of having several cells selected, well, yes. I think if a user has several cells selected, the function should still work by taking into account all first exposed drawings in the selection and slide them accordingly. Perhaps even on multiple columns.
Having said that, I guess most users would be "more than happy" if a simpler "one selected cell" version of the function is implemented, just because it'd represent a great step forward in timing refinement tasks. So I'd go with it anyway.

**Comment by shun-iwasawa** [comment]
It seems to be related to #4052 . I think I understand your demand.

How about an idea as follows ?:
- Currently dragging&dropping the cells cannot move the selection to occupied cells. 
- A new feature will relief such restriction.
- Dragging a selscted cells will "replace" the selection and the existing cells.
- It will not be a simple replacement, especially for holding frames.
- Holding frames will not have it's frame number, but only have status of "holding frame" on replacement. So the actual frame number can be changed according to the upper numbered cell after dragging & dropping.

I'll prepare images to illustrate the idesa.

**Comment by shun-iwasawa** [comment]
<img src="https://user-images.githubusercontent.com/17974955/135188043-06729fd9-5247-4e7a-9ab6-845c977a5a0e.png" width=500>
<img src="https://user-images.githubusercontent.com/17974955/135188044-c445d4ad-b574-47a1-a7f4-d0505dfe9553.png" width=750>

**Comment by gab3d** [comment]
@shun-iwasawa firstly, thanks for listening! 

yeah... it looks like it's doing it. :+1: 

![imagen](https://user-images.githubusercontent.com/18104091/135188538-1865391b-867e-40ae-bc1a-516e4d25fa6d.png)
in this case, what happens if you then drag the cell on frame 2 downwards? (i.e. to frame 4)

**Comment by shun-iwasawa** [comment]
> in this case, what happens if you then drag the cell on frame 2 downwards? (i.e. to frame 4)

The existing frames 3 and 4 will be move upward (to frame 2 and 3) replacing the dragged cell.
As they are holding cells, both of them will become drawing # 1 after dragging, according to the firstly-found numbered upper cell (which will be at frame 1).

**Comment by gab3d** [comment]
![imagen](https://user-images.githubusercontent.com/18104091/135189439-526d296c-17ae-4cf7-a1e4-f8f0577e04b1.png)
so, end result will be like this?

I'd most surely be one happy guy with that! :smile_cat:

**Comment by gab3d** [comment]
niiice!! :heart:

**Comment by RodneyBaker** [comment]
This is something that I can use immediately for retiming of a rough draft.
Definitey a big thumbs up from me.

**Comment by gab3d** [comment]
@shun-iwasawa 
any chances to have this feature included in the next release? 
it'd really be quite useful...
thx!
