### ISSUE TITLE
Window will not close no matter what! Delete room, still there. Have to full reinstall, reinstall will not work. Main V1.5

### ISSUE THREAD

**Issue by 5ZkPth2fnywt** [opentoonz/opentoonz#4088]
https://github.com/opentoonz/opentoonz/releases/tag/v1.5.0

**Describe the bug**
The window is not closable. Tried everything. Look at the screenshot for better detail.
When you are delete the room which was hard to do because the window is still there.
Restarting won't work or reinstall

**To Reproduce**
List steps to reproduce the behavior.
1. Main window on the side.
2. New room.
3. Create style editor

**Expected behavior**
It happen sometimes.

**Screenshots**
https://i.imgur.com/mLRvneg.jpeg

**Device Information:**
 - Windows 10
 - OpenToonz Version: 1.5
 - GPU: e.g. NVIDIA GeForce GT 1050
 - GPU Driver Version: e.g. 471

**Comment by 5ZkPth2fnywt** [comment]
To fix it, to my knowledge is deleting the program files and the OpenToonz stuff.

**Comment by RodneyBaker** [comment]
Try at least temporarily mirroring your monitors so that both show the same screen.

**Comment by RodneyBaker** [comment]
Closing as it sounds like you have resolved this @5ZkPth2fnywt 
Please let us know if that is not the case.
