### ISSUE TITLE
Massive improvements to drawing performance. Drawing gets slow after drawing many frames. May be an option to use gpu aswell.

### ISSUE THREAD

**Issue by ALPHABRINE** [opentoonz/opentoonz#4090]

**Comment by RodneyBaker** [comment]
Closing this as a duplicate but improvements to drawing performance and all performance is always an ongoing effort.
Use of GPU and more.  @ALPHABRINE If you have specific details to include video of areas that are particularly problematic recommend opening a report that focuses on those areas. 

(REF:  Renderman's move into 'XPU' which attempts to leverage and optimize rendering with both CPU and GPU)
