### ISSUE TITLE
M1 optimization

### ISSUE THREAD

**Issue by Zapdaps** [opentoonz/opentoonz#4097]
I recently bought an m1 Mac mini, but every time I try to use opentoonz or tahoma it crashes before opening.

**Comment by RodneyBaker** [comment]
@Zapdaps Do you have any updates to this report?

Others that use M1... can you report your experience?
Let's not leave crash reports hanging.

**Comment by Zapdaps** [comment]
sorry, i thought i closed this issue. It was bc i didn’t move the download into the applications folder 😅

**Comment by RodneyBaker** [comment]
Thanks for closing the loop on this one.  Much appreciated @Zapdaps!
