### ISSUE TITLE
OpenToonz CLR Error; White Screen of Death then Closes

### ISSUE THREAD

**Issue by David-Beigoma** [opentoonz/opentoonz#4110]
Hi, it's me again with another OpenToonz error...

So I was editing something until everything turned black on my screen. I got a No Signal on my computer monitor. Then when it popped up, a debugging error came up and some kind of memory error. I then realized when I can't open OpenToonz anymore! It's the same white screen along with a new error that came up. this is the second time OpenToonz keeps acting up. It's some kind of CLR error, but the most important thing is OpenToonz itself. Any solutions?
![rrrrr](https://user-images.githubusercontent.com/89023528/137820998-4c596628-35d5-46db-bbcc-4b2986ae789c.png)
![fgfgfg](https://user-images.githubusercontent.com/89023528/137821001-eeac0348-a31b-418d-a01a-f2ecf40184f3.png)

Thanks!

**Comment by RodneyBaker** [comment]
Thanks for closing the loop on this one @David-Beigoma 
Will close.
