### ISSUE TITLE
Huion HS64:  Opentoonz closes randomly

### ISSUE THREAD

**Issue by Roosterington** [opentoonz/opentoonz#4115]
**Describe the bug**
The program closes at random times without a crash report.

**To Reproduce**
1. Have the Huion HS64 Graphics tablet connected to your device and use it.
2. Have OpenToonz open for some time.
3. Eventually it will close itself.

**Expected behavior**
Opentoon closes by itself.

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: 1.5
 - GPU: Nvidia GeForce MX 110
 - GPU Driver Version: Intel i3-7020U

Update 2: I think I have located the issue partially — the program seems to be closing down when I'm using my Huion HS64 tablet, still, at random times but most commonly when I tab out. I don't know if this is a compatibility issue or something. This problem doesn't seem to appear when the tablet is completely disconnected and I'm using a mouse instead.

I've updated the reproduction instructions.

**Comment by RodneyBaker** [comment]
I don't think this relates to your issue but it has a little similarity so will post this info...

I have noted that my stylus has some sensitivity issue that has it click or double click when I don't want it to.
This has let to Opentoonz strangely minimizing to the taskbar and I always think Opentoonz has crashed when it does this.
I go to the taskbar, open the program again and everything is there as I left it.  

As I say, I'm sure this isn't what is happening with you and the program is actually crashing but please do check to make sure the program is not just minimizing and looking like it crashes.

**Comment by RodneyBaker** [comment]
Updating the title of this report to include Huion as that seems to relative to the problem.

**Comment by RodneyBaker** [comment]
Closing this as @Roosterington has stated in #4130 that:

> Deleting the driver fixes the problem

Will keep that report open as it has some additional concerns with regard to Windows Ink etc.
