### ISSUE TITLE
regression bug: FX - outline node doesnt work

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#412]
Trying to replicate this functionality:
https://youtu.be/-jjeh1USIlY?t=4m54s

For some reason not getting any result. Whatever values I try nothing happens:
![outlinenode](https://cloud.githubusercontent.com/assets/6495061/15822848/05412cc0-2bf0-11e6-9ef4-a7aa7a4072bb.PNG)

**Comment by Juls3000** [comment]
me too, I not able to get it working

**Comment by shun-iwasawa** [comment]
This bug is already fixed by @skitaoka in the PR https://github.com/opentoonz/opentoonz/pull/297.
The modification is already merged yesterday so please check the current nightly build. Thanks!

**Comment by Juls3000** [comment]
![cats](https://cloud.githubusercontent.com/assets/19145844/15887825/9f2f7092-2d64-11e6-9fcf-ab5a45839221.jpg)

**Comment by blurymind** [comment]
Thank you. Closing this now!
