### ISSUE TITLE
Opentoonz not loading, hanging on "Initializing Toonz Environment ..." (SOLVED)

### ISSUE THREAD

**Issue by MikeTysonsPidgeon** [opentoonz/opentoonz#4127]
I recently moved over to a new rig and unfortunately, Opentoonz doesn't seem to want to work on it. I've tried uninstalling and reinstalling multiple times while making sure the "opentoonz stuff" folder is clear every time. I've also downloaded Tahoma2d and tested that out and it does seem to work, so at the very least I can move my stuff over to Tahoma if I can't get Opentoonz working, but I would prefer sticking with Opentoonz for the most part.

**Comment by MikeTysonsPidgeon** [comment]
Unfortunately, I've tried to install it multiple times to no avail. And I always make sure the toonz folder is empty (but backed up) and the program still doesn't open. As for specs:

Processor: AMD Ryzen Threadripper 3960X 24-Core Processor    3.80 GHz
GPU: NVIDIA GeForce RTX 2060
RAM: 32.0 GB

I think those are the only specs that would be relevant?

**Comment by RodneyBaker** [comment]
And you are attempting to load the latest nightly release?

Link to latest nightly release:  https://github.com/opentoonz/opentoonz_nightlies/releases

**Comment by MikeTysonsPidgeon** [comment]
I was wondering if my antivirus was causing it, but unfortunately that doesn't seem to be it either. I uninstalled my antivirus and reset my computer, but Opentoonz still won't load. Tahoma2d is still working fine.

Is there anywhere to try downloading the OLDER versions of Opentoonz, like 1.4 to test them out?

**Comment by RodneyBaker** [comment]
Yes, all the older release are available on the releases page.

Releases link:  https://github.com/opentoonz/opentoonz/releases

21 releases to date if we include the latest nightly.

**Comment by MikeTysonsPidgeon** [comment]
I've tried 1.3 and 1.4 on this computer, as well as the stable version of 1.5 and the most recent nightly build. All of them are reacting the same. I'm starting to lose hope that I'll figure out why it's not working.

**Comment by konero** [comment]
@MikeTysonsPidgeon Maybe you can try making the install a portable install?

1. Install OT like normal
2. Go to `C:\Program FIles\OpenToonz` and drag everything inside to a new location (like `C:\OpenToonz Portable`)
3. Drag the `C:\OpenToonz stuff` folder into the newly created folder and rename the stuff folder `portablestuff`

**Comment by MikeTysonsPidgeon** [comment]
That didn't seem to work either unfortunately.

**Comment by konero** [comment]
@MikeTysonsPidgeon Damn, OK.

Try this then:
1. Go to where you installed OpenToonz
2. Open the `/srv` folder
3. Rename `t32bitsrv.exe` to `t32bitsrv.exe.bak`
4. Try launch OpenToonz

**Comment by MikeTysonsPidgeon** [comment]
well, hot damn. that fixed it instantly.

Thanks a lot. I'll have to keep this in mind if I run into problems when 1.6 comes out.

**Comment by RodneyBaker** [comment]
Leaving this report open for the present to make it easier for others with similar issue to find.
