### ISSUE TITLE
Crash on Startup after Splash Screen

### ISSUE THREAD

**Issue by hawkerm** [opentoonz/opentoonz#4135]
**Describe the bug**
After seeing the splash screen and the "creating main window" message the splash screen disappears and nothing happens. The app has crashed, I see the events in Event Viewer.

I tried uninstalling and re-installing. This is my first time trying to use the program so I don't have an older version. I uninstalled 1.5 and tried the nightly build, but received the same issue.

Is there a log file OpenToonz dumps somewhere I can provide?

**To Reproduce**
List steps to reproduce the behavior.
1. Download and Install
2. Run
3. Crashes after Splash Screen

**Expected behavior**
Program to Run

**Screenshots**
![image](https://user-images.githubusercontent.com/8959496/140598107-3e2adba8-e83f-409f-87ee-28d1e66c0a71.png)

**Device Information:**
 - OS: Windows 10 20H2 (19042.1288)
 - OpenToonz Version: 1.5 and [e.g. Nightly (2021-04-11)]
 - GPU: Intel HD Graphics 630 + Radeon RX Vega M GL
 - GPU Driver Version: 23.20.16.4973 + 23.20.792.1280

**Comment by hawkerm** [comment]
Tried 1.5 on my other machine and had the same exact problem. It's also running Windows 10 20H2 (19042.1288), but it has a NVIDIA GeForce GTX 1080 GPU version 27.21.14.5671.

**Comment by hawkerm** [comment]
Looks like the same issue reported here actually: #3963

**Comment by RodneyBaker** [comment]
There was a similar problem reported some time back where (I believe it was @shun-iwasawa) it was suggested to add a specific WIndows related file... presumably because it was missing.  I did a quick search for that report but didn't find it.

**Comment by konero** [comment]
If it happens on two machines, then what do those machines have in common? What anti-virus software do you use? Have you used any registry "cleaners"?

**Comment by DarrenTAnims** [comment]
Try turning off your anti-virus software before you install and before you first run, just in case that's preventing something from being written to disk.

**Comment by hawkerm** [comment]
This is just a standard Windows 10 box, no special software or anti-virus, just Microsoft Defender.

Is there not any log written by the program to disk somewhere to indicate why it's crashing?

**Comment by RodneyBaker** [comment]
There have been a number of similar reports to this.
Some were fixed by updating drivers while others removed files.

Here for instance is a report related to drivers:  #4041

I'm still looking for the report related to removing a file from the stuff directory...

**Comment by RodneyBaker** [comment]
@hawkerm The latest nightly releases have a crash reporter included that might help in determining what exactly is causeing your problem.  Recommend you try that.

**Comment by RodneyBaker** [comment]
Similar issue with Logitec driver:  #46
Renaming/removal of DLL resolves the crashing.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@hawkerm Please feel free to add additional information as you find necesary.
