### ISSUE TITLE
i cannot see what i am drawing

### ISSUE THREAD

**Issue by namele1189** [opentoonz/opentoonz#4144]
**Describe the bug**

**To [Reproduce**]
List steps to reproduce the behavior.
1.
2.
3.

**Expected behavior**

**Screenshots**

**Device Information:**
 - OS: [e.g. Windows]
 - OpenToonz Version: [e.g. Nightly (2020-01-10)]
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by DarrenTAnims** [comment]
You've logged this 4 times. Once is enough. But you haven't provided any of the suggested information or any information of your own. So unless you add some, expect these 4 reports to be deleted.
