### ISSUE TITLE
Brush Tool bug.

### ISSUE THREAD

**Issue by KorenaJu** [opentoonz/opentoonz#4150]
So sometimes when i use OpenToonz my brush tool is like really buggy and i can see every pixel and cant do anything.
and i tried everything but didnt find anything to fix this bug.
so here is my question does anyone know what this is?
if yes please tell me the answer i really really need hel
![Desktop Screenshot 2021 11 14 - 22 26 05 48](https://user-images.githubusercontent.com/94323057/141699220-edcc0fad-650a-41f2-b62d-839523380a35.png)
p

**Comment by RodneyBaker** [comment]
I looks to me like you are drawing at a very low resolution.
The two options I can think of immediately would be:
1) Use vector levels as they are resolution independent
2) Increase the resolution of your image/level at the time it is created

As a test try a resolution such as 4000px by 3000px and then adjust accordingly to the desired resolution for your specific project.
Keep in mind here that we can mix resolutions and even have raster, toonz raster and vector images/levels all appearing in the frame at the same time.  Just expose each in a different column so they layer over each other.

If you can share the resolution of the image/level you are currently drawing in that will help assess the problem.

**Comment by RodneyBaker** [comment]
Closing this as a question that is at least partially answered.
Feel free to continue discussion here or open a new report as necessary.
