### ISSUE TITLE
The passthrough nodes have been empty and unrenamable for me for some while, what could be the cause?

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4151]
OT version I'm running is 43165553f762ec2b881e8b6e7e4494894e8d2b30

I tried running OT with a clean 'stuff' directory and everything. 
Is it a bug? Or am I missing some style related things somewhere.
OS is Linux.

**Comment by KaseyFarron** [comment]
It was redesigned in https://github.com/opentoonz/opentoonz/pull/4036.

I like the redesign, but I do wish we could still rename the node! 🙏

**Comment by Bracket-H** [comment]
Thanks~
I'll look into the Tahoma code and pull it over for myself until this is hopefully fixed in the base.

**Comment by RodneyBaker** [comment]
As a follow up, this issue should be resolved by #4176.
