### ISSUE TITLE
Options for extra space for drawing around (toonz raster) levels, like in clip studio paint. 

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4152]
Split up into the desired level dimension, like 1920x1080.
And one to four additional extra space values, increasing the final, overall level dimensions.

Example with a single extra space value:
Level width: 1920 px
Level height: 1080 px
Extra Space: 200 px

Final level size, 2120x1280

More fields for entry would simply scale and position the level to reflect the values chosen.

The upside of splitting this into intended size and extra space size is that its, well, split. If one wanted 200pixels of extra drawing space outside of the camera, every time, then no matter which dimensions of the level, one would get that, without having to do extra maths :P
And if the extra values are in the options, then it would set it once, use forever would work too.
Perhaps with a checkbox to use them.

**Comment by oliver-dreamwalker** [comment]
@Bracket-H, You know you can change the raster level resolution, right?

![image](https://user-images.githubusercontent.com/66680990/142015907-19287955-8737-4544-8ae5-9a952d8eb70b.png)

**Comment by Bracket-H** [comment]
Well, yeah that works, of course. Guess if it doesn't get implement I'll just stay with that, but, you know?
New Levels Default to the camera size + extra space would give extra space no matter the camera, etc...but yeah this slipped my mind.
Thanks.

**Comment by DarrenTAnims** [comment]
You set the size of your level when you create it,. so you can create each one at whatever size suits you.
If you want them all to be a different size, you can set the default for this dialog, from the Preferences > Drawing section. Then you won't need to type it every time.
If you prefer you can set this all up in pixel sizes instead of mm, which I personally find much easier and makes much more sense while working digitally. Preferences > Interface section.

**Comment by oliver-dreamwalker** [comment]
@Bracket-H , you can also play around with DPI, same resolution levels with different sizes, same level size different resolution.

**Comment by Bracket-H** [comment]
Yeah. I'll close this for now since this technically fulfills my need. I explained why I'd like additional options but, again, the option to set defaults slipped my mind, etc. No need to sit on an open issue for this now. Thanks for reminding me.
