### ISSUE TITLE
Macro FX added from Browser FX causes crash. 

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#4162]
I am getting stable crash when loading MacroFX from FX Browser. However, if I load the same MacroFX from the context menu, then it loads without problems. 

**To Reproduce**
List steps to reproduce the behavior.
1. Create a MacroFX from several effect nodes (mine is "Matte Visible In", "Palette Filter", "Over") and save it as a preset.

2. Load the saved MacroFX into the FX Schematic window from the context menu. It will load successfully.

3. Load the saved MacroFX into the FX Schematic window from the FX Browser. A crash will occur.

**Screenshots**

![ezgif-2-1e14111f1cf3](https://user-images.githubusercontent.com/25724133/143724144-c594824c-f516-4be0-85ff-1971b1ff0b76.gif)

The same crash occurs in Tahoma2D. In the video you can see the Tahoma interface, I accidentally deleted a similar video recorded in OT (it's a pity, the eye was prettier there). 

**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: latest Nightly

**Comment by RattusaurusRex** [comment]
From what I've tested, the crash will occur if the MacroFX contains one of the blue Layer_Blending effect nodes.  The purple Layer_Blending nodes do not cause a crash.

![image](https://user-images.githubusercontent.com/60277069/143726907-bbe2242e-3d67-4955-95c5-ffc128a6d4df.png)
