### ISSUE TITLE
drawing tab takes up whole screen.

### ISSUE THREAD

**Issue by LandoDahMando** [opentoonz/opentoonz#4165]
HI so I have an Asus Zenbook Pro duo laptop and I was on opentoonz and was trying to move the drawing tab but it expanded and now it covers both monitors and I cant exit out of it. Left click doesn't work, i cant reach the borders to move it, esc doesn't work, only the drawing page is accessible. Ive even tried to delete and reinstall but the page still covers the whole screen and I cant do anythign about it. Anyone have a fix for this? I've been working on an animation for a while and I do not want to restart.

**Comment by artisteacher** [comment]
Were you changing the room order or reorganizing one of the rooms? In case you maximized a panel, try pressing the ` key, while hovering over it.

**Comment by LandoDahMando** [comment]
> Were you changing the room order or reorganizing one of the rooms? In case you maximized a panel, try pressing the ` key, while hovering over it.

Thanks for the reply but it doesnt seem to be working.

**Comment by LandoDahMando** [comment]
> 

I also forgot to mention that it does this for all projects and when i open opentoonz so i cant do anything

**Comment by artisteacher** [comment]
Are the icons extra large by chance? There's a weird display issue that happens with some graphics drivers. If that's the issue, updating to the most current driver should help.

**Comment by Bracket-H** [comment]
Mmm, if you have an us keyboard, try the ` key, it's under escape.
Maybe you hit it by accident and it expanded the whole thing...tripped me up before...

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@LandoDahMando please let us know if you are still having issue with the drawing tab.
