### ISSUE TITLE
Why is my UI shrunk down???

### ISSUE THREAD

**Issue by IAmTheBlade** [opentoonz/opentoonz#4177]
I just downloaded OT on my new PC, the  issue is that the UI is smaller than normal size. my display resolution is at the recommended level. Please let me know weather this is a bug or fixable (if so, how to )....
![Screenshot (1)](https://user-images.githubusercontent.com/95624424/144844319-a669d0be-f081-4fdb-9c71-f67a249ef476.png)

**Comment by RattusaurusRex** [comment]
It looks normal to me.  Before this, maybe you had the bug with the graphics driver that gave you an enlarged UI?

**Comment by IAmTheBlade** [comment]
> I agree that the scale looks pretty normal, but I don't use Windows, so I can't say for sure. I have found that high resolution screens can make a difference in how parts of the UI display #1216. I think on Windows you can disable specific apps opening in high resolution? It might be worth trying out.

Thanks I had to override the high dpi settings
