### ISSUE TITLE
Timeline/X-Sheet marker overplay extending Bug.

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4180]
When you create a Level on the X-Sheet or Timeline in expand the frames of the Level then delete the last few frames and press Play 
the playback will play beyond the new playback marker to where the last marker was set.

![Bug Report](https://user-images.githubusercontent.com/74626650/145231332-f3d0cfbf-a6d8-4ab7-928e-f3fe521a557b.gif)

**Comment by Bracket-H** [comment]
Can confirm this for me too. 
I"m on 43165553f762ec2b881e8b6e7e4494894e8d2b30

**Comment by RodneyBaker** [comment]
Closing as possibly resolved but definitely abandoned by ghost.
