### ISSUE TITLE
Opentoonz automatically exits when I render

### ISSUE THREAD

**Issue by King25-Cybernet** [opentoonz/opentoonz#4188]
Opentoonz automatically exits when I render

**Comment by artisteacher** [comment]
Does it always crash straight away, or can you get part way before the crash? Is this a problem with every scene/project, or just the current one?

It is often best to render to an image sequence first and then bring the sequence back into OT to render to video. That way, if you crash part way, you can start again where the sequence left off. Sometimes rendering with the Tasks panel can also give you a better result.

**Comment by RodneyBaker** [comment]
@King25-Cybernet  Are you still experiencing this issue?
If so there have been a number of bug fixes that may help resolve the problem available in the latest nightly release.

LINK:  https://github.com/opentoonz/opentoonz_nightlies/releases

If the problem still persists even with the latest nightly release we will likely need more information such as more specifics on what you are attempting to render.  Knowing more about your specific computer system will help as well.

**Comment by RodneyBaker** [comment]
Closing as abandoned and/or likely resolved.
