### ISSUE TITLE
Opentoonz crashed and even if I saved the projekt it didn´t save it

### ISSUE THREAD

**Issue by Tedobi** [opentoonz/opentoonz#4189]
Why?

I spend several hours on my work and then Opentoonz crashed and it didn´t save every 15 minutes even when I turned it on. I am so angry and I will never use opentoonz again

**Comment by RodneyBaker** [comment]
Closing as a user who never will use Opentoonz again isn't likely to seek feedback.
Sorry to hear of your troubles @Tedobi
