### ISSUE TITLE
Support for OCA format

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz#4201]
"[OCA [Open Cel Animation]](https://rainboxlab.org/tools/oca/) is an open format to ease the exchange of traditional/frame-by-frame/cel animation between different applications". It is licensed under GPL v3.

It can been considered akin to XDTS in that it allows for the exporting and importing of timing data and is intended for cel animation pipelines. Unlike XDTS however, it packs in a lot more data such as relative image paths, and per-frame opacity and position. It also includes per-layer info such as blending mode, position, and opacity, as well as much more.

With regards to the `blendingMode` property, this could be used to instantiate a corresponding Blending FX node, recreating the intended look without the need for user action.

OCA is supported by several applications; it has an exporter for Krita as well as importers for Blender and After Effects.
[I have created a small application that can convert OCA to XDTA and vice versa](https://wolfinabowl.itch.io/oca-to-xdts-converter). This allows you to import animations created in Krita, improving the pipeline for those using Krita in place of Clip Studio Paint. 

Native OCA support would allow for transferring much more information, as my tool is limited to the data that XDTS can support.

**Comment by JPUser1** [comment]
@shun-iwasawa would we be on legal grounds to develop a 3rd Party .OCA plugin? I have been in contact with the author of .OCA and he is happy we want to use his format we are only now awaiting your approval?

**Comment by shun-iwasawa** [comment]
@JPUser1 
In my opinion, developing OCA I/O feature and releasing it as part of OT source is OK, as long as you only refer to the JSON spec of .OCA files and do not use any part of the source from OCA software which is licensed under GPL.

**Comment by JPUser1** [comment]
Sorry I was under the influence MJ wanted to do it but he kind of backed out so I personally do not have the skill set to do this  but if anyone wants to help the Krita users would be very Happy for this workflow.

**Comment by RodneyBaker** [comment]
Closing as @justburner has added initial OCA support.

For more information please see #4483
