### ISSUE TITLE
Bug with  Mesh tool (Something wrong with vertexes)

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz#4204]
I am creating a puppet, then want to add some skeleton in 1 mesh layer, But when im animating 1 skeleton, then the second is changing too.

**To Reproduce**
List steps to reproduce the behavior.
1.create some skeletons in 1 mesh layer
2.change 1 of skeletons
3.check if other sceletons are changed

**Expected behavior**
Itr must change only on skeleton im working on.
**Screenshots**
Here is video --> https://youtu.be/Ovqlz7qlRWs

**Device Information:**
 - OS: Windows 7
 - OpenToonz Version: Last Nightly (Some thing with Tahoma2D, I try it too)

**Comment by beeheemooth** [comment]
@FerrLui I answered you in the comments to your video.

**Comment by FerrLui** [comment]
@beeheemooth  Thanks
