### ISSUE TITLE
Type Tool causes crash if you hit the space key

### ISSUE THREAD

**Issue by the-mantis-shrimp** [opentoonz/opentoonz#4221]
Updated to nightly, same issue.

**Describe the bug**
Identical behavior to the following issue, but on windows: 
https://github.com/opentoonz/opentoonz/issues/3604

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: [e.g. Nightly (2022-14-1)]
 - GPU: NVIDIA 3060
 - GPU Driver Version: current

**Comment by shun-iwasawa** [comment]
Unfortunately I couldn't reproduce the crash so far. Does anyone can try this?

**Comment by RodneyBaker** [comment]
I cannot reproduce this either.

@the-mantis-shrimp Please do double check to make sure you are using the latest nightly release.
You mention you are using the nightly from Jan 14 so it looks like you have that side handled.

The assumption is that using the space key at any time with the Type key will cause the crash but if there is a specific time or instance when it happens that will be useful to know.  For example if it fails using some fonts but not others.

**Comment by the-mantis-shrimp** [comment]
Thank you for your responses. After updating to today's nightly build the error is gone.

**Comment by RodneyBaker** [comment]
Great news.  Glad it worked for you!

**Comment by the-mantis-shrimp** [comment]
Unfortunately, it was not the solution. I repeated the steps that enabled me to use it without crashing and I got a crash with a fresh install, no custom user settings. If it's helpful, here's the output from the Win10 event viewer:

Faulting application name: OpenToonz.exe, version: 0.0.0.0, time stamp: 0x61e8b71f
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409

The version looks weird to me, I'll poke around and see why I'm getting 0.0.0.0

**Comment by the-mantis-shrimp** [comment]
I discovered that it only crashes if any connected display is scaled over 125% in Window Display Settings. So for now I have a work around.
