### ISSUE TITLE
Black background on Export

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#423]
When avi, jpg, bmp and tga files are exported, transparent backgrounds are rendered as black.  
I think white makes much more sense. and would probably be the expected behavior for most users.
Is there a way to change this?

Sidenote: do you know why Photoshop only sees the png files as transparent.  I realize that some formats like jpg don't support transparency, but shouldn't tif files have transparency?

**Comment by psychoanima** [comment]
Most video formats can't hold alpha. Same for image formats. However .tiff and .tga do have alpha channels, but for this formats/standards in Photoshop you have to approach differently from png's. Open rendered OpenToonz image (tiff or tga) in Photoshop. Open channels tab and there you will see Alpha 1 channel. Visibility is turned off and it should stay that way.

![alpha in opentoonz](https://cloud.githubusercontent.com/assets/18187104/15919789/b69ce2b8-2e14-11e6-829b-3b09605bccd1.JPG)


 If you want to see transparency "live" like for png files, ctrl+mouse click that alpha1 channel to make selection in the viewport. Then go to Layer drop-down menu, choose Layer mask -> Reveal selection.
![untitled](https://cloud.githubusercontent.com/assets/18187104/15919807/fa96823a-2e14-11e6-9a4e-b1a6e942a916.jpg)

It's just how Photoshop works, compositing software like After Effect or Blackmagic Fusion have no problem showing immediate alpha transparency for this formats

But here's one cool trick you can do in OpenToonz: after you setup your render format from Output Settings click Render button. In Flipbook window there is an option to check if there is alpha for selected format. Only thing you have to do is to press Alpha Channel button and voilà! :)

![trick](https://cloud.githubusercontent.com/assets/18187104/15919900/eaf7eda4-2e15-11e6-8a96-33d398773b22.jpg)

**Comment by konero** [comment]
> and would probably be the expected behavior for most users

Not at all. This is the expected behavior for all those file types you listed. Take anything else as an example like DigiCel FlipBook, Toon Boom Harmony and TVPaint and they all behave in the exact same way.

**Comment by turtletooth** [comment]
@psychoanima
Thank you for the incredibly detailed answer.  I learned a few things.

@konero I realize that other programs may do it that way, but I don't think that is the most user friendly- especially for beginners.  (I am a teacher and that is where my bias comes in).  In OT, if a user is previewing their xsheet without a background layer, the bg is white.  Most users (at least those without much experience in the other programs you mentioned) would expect their render to look the same.

I think the  formats that have transparency should stay the same, but for the formats that don't I think the export should match the xsheet preview.

**Comment by konero** [comment]
Apologies, because you mentioned TGA I assumed your complaint was about alpha.

I see now, filetypes without alpha should show a white background. :+1:

**Comment by turtletooth** [comment]
Fixed on #438
