### ISSUE TITLE
Make select tool animatable

### ISSUE THREAD

**Issue by sjsheelan** [opentoonz/opentoonz#4230]
Give Animation options  to selection tool, point editor and make other tools animatable

**Comment by RodneyBaker** [comment]
@sjsheelan Your feature request needs additional information.
Will close your request for now but please add specific details.
Thanks!

**Comment by beeheemooth** [comment]
Imo, it would make more sense to give the Animate Tool the option to deform and edit points, since such an animation (if it is meant to be customizable) will be in the form of a key animation.
