### ISSUE TITLE
Help. Why the screen of my opentoonz looks white and black?

### ISSUE THREAD

**Issue by Avkto** [opentoonz/opentoonz#4238]
**What happened?** 
I opened the software normally, and then it showed up like this. But it was normal a few hours ago, the color gray by default.

![image](https://user-images.githubusercontent.com/98876664/152123878-b958aec1-4f69-4655-9e5d-cace4dba3271.png)

![image](https://user-images.githubusercontent.com/98876664/152124714-d72da10f-efdf-48ed-b76e-d29ed38d77fd.png)

**I tried to..**
i tried to restart the computer but that didn't work.
Also, I tried to change the "interface theme" in "preferences" but nothing.

It´s a problem cause, I can´t see the tools and the interface properly. 

**Question**
-Why is this happening?
-How can I solve it? 

**Information:** 
Windows 10
Opentoonz 1.5 

I'II thank you so much.

**Comment by RodneyBaker** [comment]
The last time I saw black in the UI like that it was an indication that the stuff directory hadn't gotten fully updated from an installation. 

If you have recently installed Opentoonz I'll recommend renaming your stuff directory (to something like "Opentoonz stuff old" or "Opentoonz stuff 20220205" (i.e. today's date) and then reinstall using the latest nightly release ([LINK](https://github.com/opentoonz/opentoonz_nightlies/releases)).  

The fresh install will make sure you don't have any older UI files hanging around while installing the latest nightly release will ensure you have the latest and greatest in features and bug fixes.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Avkto please let us know if you are still experiencing problems.
