### ISSUE TITLE
Feature modification: Ability to move pinned center keys on Xsheet row area

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#424]
Since awesome @shun-iwasawa made pinned center keys available on xsheet (https://github.com/opentoonz/opentoonz/pull/369), it would be great if someone can now extend this feature with ability to manipulate Pinned center keyframes by click&drag, just like with the regular keys on Xsheet. 

Removing selected Pinned center keys from xsheet can also be great (instead of having only global pinned center reset), but I don't know how complex that might be, so it can be another feature request.

**Comment by turtletooth** [comment]
Duplicate of #498
