### ISSUE TITLE
Copy the keyframes to a new scene in Opentoonz 

### ISSUE THREAD

**Issue by Avkto** [opentoonz/opentoonz#4240]
So, if I made an animation in one level and I want to move it to a new scene, **what could I do?**

Like in the image, I selected an animation with keyframes, and I need to move it to a new scene in another window.

![image](https://user-images.githubusercontent.com/98876664/152279521-b55f1e76-0865-4b28-b86a-c8924ecb37d3.png)

![image](https://user-images.githubusercontent.com/98876664/152279592-176df43f-3ad5-4d8a-bc91-366b942a4bee.png)

**I tried to..**
-I already tried to export a level. But when I load it in the new scene, only the level comes to me without the animation already done.
Also if I try to paste the frames with the keyframes I get that it can't, just like in the following image.

![image](https://user-images.githubusercontent.com/98876664/152279883-ec8b0a47-1674-4360-acfe-05fbecc0fb98.png)

It says "unable to paste data: there is nothing to paste."

**Question**
**Is there a way to copy an animation already done in a level (with its keyframes and cells), into a new scene?**
This in order not to repeat a certain animation again.
Or. **I have to make the animation from the start in the new scene?**

**Comment by RodneyBaker** [comment]
I think we should be able to copy/paste keyframe data to other scenes as long as the scene is a subxsheet (subscene in Tahoma)  opened at the same time.  Will have to verify that.

If the scenes are open in different instances of the program (or say... one scene open in Opentoonz and the other in Tahoma2D or other fork/version)... perhaps the best way to transfer key values is via Curve export.

For those unaware, in the Function Editor if we Right Click on the stage listing of a channel there is an option to Save or to Load a .curve file.  That curve file constains the data values of that specific channel.  

Here's an example where I saved out a curve as temp.curve from Opentoonz and opened it on a similar channel in Tahoma2D:

![image](https://user-images.githubusercontent.com/2576432/152281386-ab9e5158-ebc2-4351-aef2-37adb3328328.png)

This should work for moving expressions across scenes as well.

Aside:  The other option (Export Data) appears to only have an output option BUT that data can be brought back into Opentoonz via the File Interpolation option... where we can set other interpolations.

That's not copy and paste but perhaps that is a reasonable workaround.

**Comment by Avkto** [comment]
> 

THANK YOU SO MUCH! Without your comment I would not have been able to reposition the animation. thanks again! :-D 💯

**Comment by RodneyBaker** [comment]
@Avkto   Will close this report but please feel free to continue the discussion as you see fit.
We are alwasys learning new and useful things and the questions people ask help us all tremendously.
