### ISSUE TITLE
Relative (percentage) based values for room panel layouts

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4245]
I purely request this because, for some reason, resizing OT panels that are attached to the main viewer/drawing area is really really darn slow and very, very laggy (keeps resizing even when I am done pushing the edge around) when done so with the stylus, not with the mouse.

And since it's probably quite a bit more difficult to track such an issue down, I'd like to request percentage based values for room panel layouts, because at the moment, when I open OT on my smaller monitor, it messes up the layout for the bigger cintiq, making the drawing area etc small and all the panels that don't need to be bigger (like palette/styles) bigger...

Which means I have to resize them on the cintiq, but that's super laggy (again, for some reason) since I don't have a mouse at my work spot and putting one there would be awkward... but maybe ,despite my personal/niche wish here, saving layouts as relative percentages are the way to go anyway?

That way if a panel is 50% of the width of the screenspace, it will be 50% on both big and small resolution screens.

So I'm putting this out there as a quasi 'poll' too. If noone agrees with me in some time, and you don't consider this worthwhile then that'll be fine...but maybe, again, this could be a good change overall.

P.S.: I hacked this into OT myself for the time being (with an extra option type to not overwrite the absolute rect dimesions) and I am already liking it, heh.

**Comment by artisteacher** [comment]
I agree that going back and forth between different screen sizes can be annoying.

**Comment by Bracket-H** [comment]
It's so much nicer this way, but I won't dare make a pull request with my solution...
Which involves:
checking the (virtual/multi monitor setup) screen of the splash window on startup.
Taking those dimensions.
Resizing the room panels based on those dimensions and the percentage (0.0 - 1.0) value with the new floatGeo ini attribute
And if those don't exist, it will use a similar way to generate them upon closing OT.

So, closing OT generates the float values on exit based on OTs then used screen/virtual screenspace
and upon starting, uses the screen it starts on (due to the splash window) to generate the pixel based dimensions from the float ones stored previously.

Works well enough but ...that's so ugly...

**Comment by Bracket-H** [comment]
It's been over ten days and the repository is visited by a few people at least, only one has answered here so I'm closing the issue for now...it's not like its gone with that, and the devs still have insight into it. No need to sit around the frontpage tho.

**Comment by RodneyBaker** [comment]
Thanks @Bracket-H   It's a good idea and I hope someone will be able to take on the task.
As a community (of user/developers) it's our job to continuously review these reports... even the closed ones... and mine them for all they are worth.  

I like to say 'good ideas always return' so I'm confident we'll see this one return. :)
