### ISSUE TITLE
Fail to save PNG and TPL palette on latest nightlies

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4246]
On latest nightlies (last two) I'm getting an error where TLV levels seem to be getting confused with raster levels.  This relates to palette saving and that is the error that message that pops up.  This generally leads to a crash later if continuing to work with the scene.

I'll upload some screenshots but am having some issue replicating the problem without crashing.

Of note:  The error message states that a PNG image cannot be saved and yet I'm not using any PNG image... leaving the default option as TIF for the standard raster level.  

I am using the option 'Use White as Transparency' in the Level Settings.
This to show through the TLV level underneath that has key'd color.
Added:  This doesn't appear to related to the specific TLV saving issue.

This seems mostly unrelated but a few days ago a fix was posted to Tahoma2D relating to palette saving.
REF:  [Fix palette saving issues](https://github.com/tahoma2d/tahoma2d/pull/895#)
#895

Update:
I was able to salvage a test project by specifically saving the levels as .tlv levels whereas it was apparently trying to reference them as PNG.

**Comment by RodneyBaker** [comment]
It appears to me that TLV levels are trying to remap as PNG levels, perhaps in the process of creating the palette file upon save.
If specifically saving the level as TLV I can then press on using (and saving) the TLV level as normal).

**Comment by shun-iwasawa** [comment]
Thank you for the report! I will check it right away.

**Comment by shun-iwasawa** [comment]
Obviously it was my careless mistake in #4241 . Sorry for the trouble.
