### ISSUE TITLE
Crash when draging on xsheet empty cell

### ISSUE THREAD

**Issue by walkerka** [opentoonz/opentoonz#425]
When I was trying to add a new drawing on xsheet, OT crashed. I attempted to clicking on an empty cell but it looks that triggered a drag. It happened twice only.

The code is pulled from git 3 days ago. I was using vs2013 on win7 x64 to debug. Here's the log.

----------------------------------------------------------------------
Assertion failed!

Program: ...de\opentoonz\toonz\build32\Debug\OpenToonz_1.0.exe
File: D:\code\opentoonz\toonz\sources\toonz\xsheetdragtool.cpp
Line: 693

Expression: r1 == row - 1

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)Assertion failed!

Program: ...de\opentoonz\toonz\build32\Debug\OpenToonz_1.0.exe
File: D:\code\opentoonz\toonz\sources\toonz\xsheetdragtool.cpp
Line: 369

Expression: rowCount > 0 && colCount > 0

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

**Comment by shun-iwasawa** [comment]
I could reproduce the bug. Thank you for the report!

**Comment by shun-iwasawa** [comment]
merged in v1.0.3
