### ISSUE TITLE
Brush Tool Bug

### ISSUE THREAD

**Issue by FunkyZomb** [opentoonz/opentoonz#4254]
Undo a line from a brush tool won't erase the while line

List steps to reproduce the behavior.
1. Draw a line
2. Ctrl+Z

The line would erase but there will be a bit left from where it started, which require another undo.

https://imgur.com/a/MuKgqO0

**Device Information:**
 - OS: Windows 10
 - OpenToonz Version: Nightly (2022-02-10)
 - GPU: NVIDIA GeForce GTX 1660 Ti
 - GPU Driver Version: 511.65

**Comment by FunkyZomb** [comment]
Found the solution, My driver has a "Window Ink" button inside and when unticked the problem above is gone.

**Comment by RodneyBaker** [comment]
Will close with thanks for posting the follow up!
Always good to know what resolves a problem.
