### ISSUE TITLE
Shortcuts Discussion

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#426]
I love shortcuts.  I would love to see more default shortcuts set in OT.

The ones that stand out to me are:
I think that Ctrl S should save all.  Right now just saving the scene with Ctrl S is a great way to lose work because so many people are used to Ctrl S and thinking they are safe.

I would like default shortcuts for:
Play/Pause
Increase Step (Extend Hold)
Decrease Step (Decrease Hold)
Brush Size- I realize that Alt also works, but a shortcut like [ ] in Photoshop is nice too.
Maybe a toggle through the modes on the Edit Tool
Onion Skin Toggle
Show Zero Thick Lines toggle
Drawing substitution

What are your thoughts?
I don't mind building them in if there seems to be a general agreement.

**Comment by blurymind** [comment]
I agree on the brush size. The brushes in OT seem to be resized in a similar fashion to what blender has with the F key (texture mode). I need to think about the shortcuts for a while. This is a really good topic to bring out,as OT currently doesnt have a complete keymap!

**Comment by konero** [comment]
OpenToonz current shortcut list appear to be from the stone age, it is illogical beyond belief and takes in no account for left-handed use, a default shortcut set list should in the most part have its core functions accessible to both. We got to test OpenToonz in a real pipeline and quite literally everybody changed the following shortcuts straight away:

Previous Frame (**Shift+S**) to (**,**)
Next Frame (**Shift+A**) to (**.**)
Prev Drawing (**Shift+Z**) to (Right-Handed: **F** | Left-Handed: **H**)
Next Drawing (**Shift+X**) to (Right-Handed: **G** | Left-Handed: **J**)
First Frame to (**<**)
Last Frame to (**>**)
Save All to (**Shift+S**)

How on earth is a left-handed user supposed to use Shift+Z/X for arguably the most useful two shortcuts?

I agree with @blurymind about a shortcut set list. :+1: 

I would still argue making the Toon Boom Harmony layout the default, it's more logical in most aspects and professional OpenToonz users will likely couple it with Toon Boom Storyboard Pro; but at least if the option is there it reduces the frustration greatly.

> **Shortcut Sets**
> Toon Boom Harmony (right-handed)
> Toon Boom Harmony (left-handed)
> OpenToonz (right-handed)
> OpenToonz (left-handed)
> Custom 1
> Custom 2
