### ISSUE TITLE
Polar coordinates in opentoonz?

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4262]
Hi! I was wondering if opentoonz has an effect like polar coordinates of after effects.

**Comment by artisteacher** [comment]
What does the polar coordinates effect do?

**Comment by F-Burning** [comment]
It creates a distortion like this on vertical or horizontal lines (sorry I don't know how to explain this, but maybe @shun-iwasawa knows this fx)

![Screenshot_1](https://user-images.githubusercontent.com/74098734/154945057-e16bcd8b-ef7f-4c64-b2ec-b80bc633942f.jpg)

**Comment by F-Burning** [comment]
Finally I found this option.

In the Fractal Noise Fx, you have to check the Conical transform.

![01](https://user-images.githubusercontent.com/74098734/155730759-b35e4ca8-50e1-4e04-944f-be45db53ec9c.jpg)

I close this thread now that the question is resolved.
