### ISSUE TITLE
Interface - wasted horizontal screen estate in input boxes, inconsistent width

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#427]
One problem that is very obvious in open toonz current interface design is the Tool option bar window!

It's about the number input boxes!
It is actually two problems, as stated in the title of this issue.

1. Horizontal Space is completely wasted - space that can be used to wider sliders and more interface elements:
![wastedspace](https://cloud.githubusercontent.com/assets/6495061/15943529/6678cf32-2e81-11e6-8db7-70dc363fb2b0.PNG)
Even when you can enter up to three digits in these boxes, they are often twice or even three times wider than they need to be!

2. Horizontal space is not consistent. Some input boxes are wider than others, much wider - even when they have the same number of possible digits. Take 'accuracy' as an example- three digits that can not go over 100. Still much wider than maximum width for some odd reason.

Horizontal space is precious. The inconsistency and inefficient use of space makes for a less tidy and professional interface design that is harder to read.

**Comment by blurymind** [comment]
This is actually a regression from toonz harlequin again. It's one of the things that makes Opentoonz appear clunkier and less organized.

look how the width is consistent here, and it is not so badly wasted:
![betterlayoutspaceuse](https://cloud.githubusercontent.com/assets/6495061/15943725/4fca6a2e-2e82-11e6-9a9a-09e65cb01ecb.PNG)
They left some space, but very carefully decided it based on design- to make it breathe more. In open toonz its just insanely random and too much some times.

**Comment by shun-iwasawa** [comment]
fixed
