### ISSUE TITLE
Export Xsheet to PDF, some quirks.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#4270]
- Memo text is printed only in one line and gets cut off if longer than page width (even though there is plenty of space in that part of the page.
- when also printing Export Date and Time and Scene Path, they show overlapped to the Memo text.
(couldn't test "Print Level Names on the Bottom" option output because it was always greyed out)

![imagen](https://user-images.githubusercontent.com/18104091/155062223-d443fcd3-088b-4c8e-b3d3-54413cc400cc.png)

![imagen](https://user-images.githubusercontent.com/18104091/155063646-22edcc36-ab4b-4aea-a76e-5fb63b77df1f.png)

[Edit]:
...of course we can insert explicit line-feeds ourselves to go to a new line:
![imagen](https://user-images.githubusercontent.com/18104091/155068174-86c1f07b-e099-440c-9f86-c95bad3bed8e.png)

**Comment by shun-iwasawa** [comment]
`Print Level Names on the Bottom` becomes active when the cells are occupied more than a half of a page, i.e. when the scene length is longer than 36 frames.

**Comment by gab3d** [comment]
Another one:
**TOT / th** order for "A3, 6 sec." and "B4, 3 sec." sheet templates.
**th / TOT** order for "B4, 6 sec." sheet template.

is that intended?

**Comment by shun-iwasawa** [comment]
>is that intended?

Yes. I made the templates with different properties so that users can easily know it is modifiable when creating their own template.
As the fraction form, **th / TOT** would be natural for me. But in Japanese animation industry, many studios are familiar with **TOT / th** format for historical reasons.

>Also, is there supposed to be an "A3, 3 sec." sheet template?

Sorry, but the A3-3sec template is not included for now.

**Comment by gab3d** [comment]
@shun-iwasawa 
Great, just asking so to better know the feature.
Thanks!

**Comment by RodneyBaker** [comment]
@gab3d  Closing question as answered but please feel free to reopen as necessary
