### ISSUE TITLE
Parent from Xsheet, hangs when there's only 1 column in the scene

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#4273]
![imagen](https://user-images.githubusercontent.com/18104091/155183917-07b560d9-1d09-4dc3-b85b-986ef321a915.png)

the image is pretty much self explanatory.

1. create New Scene.
2. draw something in the Viewer.
3. in the Xsheet, click on the "Table" word in the column header. menu opens showing two entries: "Table" and "Col 2" (which is empty).
4. select "Col 2".
Crash.

**Comment by gab3d** [comment]
otherwise, I'm so glad we can use this option again! ❤️

**Comment by gab3d** [comment]
By the way, the word "Table" remains untranslated there. 🤔

**Comment by justburner** [comment]
Could reproduce this... also found out other bugs.

For example it fetch the list from the active selected object, not the column you pressed on, so you can indirectly modify parent of pegs and even the camera this way.

**Comment by justburner** [comment]
Was able to fix this issue but wasn't able to fix all the other bugs i've found along the way today, i'll push a PR as soon i have more free time to work on it.
