### ISSUE TITLE
Interface feature request - context sensitive Style editor

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#428]
This is a feature that would make open toonz brush tool much less confusing to new users. It is similar to this one:
https://github.com/opentoonz/opentoonz/issues/343

@turtletooth might like it :)

Basically the style editor shows different tabs. Some do something only for the brush tool when used on a vector level, but nothing when used on a raster level. Other apply for both type of levels.
![hidenonapplicable](https://cloud.githubusercontent.com/assets/6495061/15944461/975ae4d8-2e85-11e6-908f-3dde149cbdf7.PNG)

My suggestion is to make it context sensitive. Show only tabs that have use for the current active level/brush tool mode. If a tab has no use and no effect on the brush in the current mode (vector or raster) simply do not show it!

**Comment by blurymind** [comment]
Another note - 'Auto Apply' should be switched ON by default. This would take away an extra step between cause and effect for anyone first using the software. It used to be on by default in toonz harlequin and that made it more userfriendly to new users. I dont know why they made it OFF in OT.

**Comment by turtletooth** [comment]
I totally agree on both points.  I have been bothered by having options that aren't valid for the current layer style and also think that auto apply should be on by default.  99% of the time, if a user is changing a color, they actually wan't it applied.

**Comment by blurymind** [comment]
Another thing to note:
'Special', 'Custom' and 'Vector' brushes should all be in one tab i think.
I filed another bug report on that to keep discussion organised: 
https://github.com/opentoonz/opentoonz/issues/429

**Comment by turtletooth** [comment]
@blurymind I was thinking about this when I was digging around with linked styles.  What would you do about palettes pulled in from the studio section?  If they have patterns or vector brushes but are pulled in to a raster type layer, the only option would be to delete them if they can't access the tabs to change the change the style.  I agree that having options visible on a layer type that doesn't support the feature isn't very user friendly, but I'm not sure the best approach for the rare case I mentioned.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by turtletooth** [comment]
Done in #1397

**Comment by blurymind** [comment]
@turtletooth while the changes are great, they dont seem to include making
it context sensitive. But they are changes in the right direction and
definitely declutter the interface!

By context sensitive I mean this:
Depending on what type of level the brush tool is operating on - show only
brush tabs that are relevant to the level type that is active.
Dont show the 'raster' brushes tab when the user is using the brush tool on
a vector level. Dont show the vector brushes tab when the user is working
on a raster level.

This is so that the user doesnt select any brushes that will not work at
all on the level type he is on.

I posted another request to also make the toolbox context sensitive - so it
doesnt show tools that dobt work on the active level's type

**Comment by blurymind** [comment]
related
https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/Zjif6kO98EQ
