### ISSUE TITLE
about"Import&Create Mesh"-Window-OT1.5.0

### ISSUE THREAD

**Issue by JoinChamp** [opentoonz/opentoonz#4288]
about"Import&Create Mesh"-Window-OT1.5.0

I import simple png,
Use"Edit"or"Selection Tool"to change my image,image disappears.
Use"Animate Tool\Position&Scale"to change my image is OK.

Then I use"Plastic Tool"to create Mesh,But the mesh not stick on the image,appeared in the center of the screen!!!

sorry my English is not good,thanks for answer.

**Comment by RodneyBaker** [comment]
If you have screenshots or video that will help tremendously.

You may also wish to join an Opentoonz discord (chat) where you can get answer to your questions (and possibly in your native language) in real time.

Opentoonz discord (invitation):  https://discord.gg/tywCGWeyEC

**Comment by JoinChamp** [comment]
@RodneyBaker 
Thank you very much for your reply.
I have found the answer :
After importing the image，must be made first [ Canvas   Size  ]，get a sufficient area .
Use[  Selection Tool  ] to change image.

Question can be closed , but I can't execute .

Thank you very much.
