### ISSUE TITLE
Interface feature request: Style editor - Unify vector brushes under one tab

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#429]
This is a followup to #428 (context sensitive style editor)
It's one of the things that make the Style editor confusing.

Special', 'Custom' and 'Vector' brushes should all be under one tab i think.
They are all the same functionality spread between three category tabs.So clicking an item in one category tab cancels the effect created by clicking an item from another category tab (override effect - red). This is confusing to the end user in this case, because these tabs are mixed with other additive to the style functionality tabs (additive effect - yellow). 
![categoryfunctabsmess](https://cloud.githubusercontent.com/assets/6495061/15949647/003c1452-2ea1-11e6-9aa7-763e70d44155.PNG)

@shun-iwasawa It is bad design to mix functionality tabs with category tabs.  A suggestion I can make - is to unify the three tabs into one 'Vector brushes' and have them inside collections which can be selected from a drop down list like this:
![unifyvectorbrushes](https://cloud.githubusercontent.com/assets/6495061/15948691/1ad8d3ec-2e9a-11e6-9e64-51d3a5b01622.png)

**Comment by artisteacher** [comment]
I really like the brush sets/collections idea. Particularly once the mypaint brushes #417 are added in, the style editor is going to be very full. Having fewer tabs but also a way to still keep different brush types separate, would be really helpful and save space.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
