### ISSUE TITLE
Reopening as feature requests are no longer verbotten.

### ISSUE THREAD

**Issue by Emasoft** [opentoonz/opentoonz#4290]
Reopening as feature requests are no longer verbotten.

@Emasoft There is a lot of interest in the SVG format and it will be good to examine the way forward relative to use of SVG in Opentoonz moving forward.

_Originally posted by @RodneyBaker in https://github.com/opentoonz/opentoonz/issues/183#issuecomment-1052340069_

**Comment by RodneyBaker** [comment]
@Emasoft   Let's not spam the reports with link to other reports.
Perhaps champion the request for Github Discussions.  ;)

**Comment by Emasoft** [comment]
@RodneyBaker You should PIN that feature request. We need more coders working on this.

**Comment by RodneyBaker** [comment]
It's a bit of a conflict of interest to pin my own requests but I hear you.
