### ISSUE TITLE
Translating Documentation into English

### ISSUE THREAD

**Issue by odysseywestra** [opentoonz/opentoonz#43]
Splitting off from #34 

>  Will there be a translation (english) made available - for the documentation, if there already isnt one? If not, how can we get started on localizing it to different languages?

I know @blurymind mentions in that issue thread that openToonz UI is mostly translated into English. However, it would greatly benefit the Open Source community if the Documentation like the Markdown files are also translated into English as well.

**Comment by mospina** [comment]
Are the strings available (or they will be available) for translation? I'm thinking Zanata or some other Translation Management System. I'm interested in helping with Spanish.

**Comment by justinclift** [comment]
@mospina Yep, they seem to be here: https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/translations

**Comment by odysseywestra** [comment]
@keizo042 Also mentions in #53 that parts of the code documentation is in Italian.

**Comment by justinclift** [comment]
@mospina These might be helpful, if you're still interested. https://github.com/opentoonz/opentoonz/pull/78 https://github.com/opentoonz/opentoonz/issues/76 :)

**Comment by deruji** [comment]
I'd be interested in helping with translating the documentation into English and German

**Comment by mmuman** [comment]
The how_to_build*.md files would make use of English as well although at least the shell commands don't need translation :)

**Comment by scribblemaniac** [comment]
@mmuman These files have already been translated, and are waiting to be merged in #68.

**Comment by odysseywestra** [comment]
Now that the front facing Documentation is translated, all that left for translating is the Code documentation. @keizo042 Do you still want to translate the Italian Code Documentation to English?

**Comment by AmEv7Fam** [comment]
While we're at it....

I've poked through most of the documentation. Most of it seems to just be plaintext with a few images.

Do we still want to have the PDFs? Or perhaps use something like readthedocs? If we go the readthedocs method, it should allow for multiple languages, and submitting a language/translation would just be a pull request away. It looks like it even allows downloading the page(s).

**Comment by odysseywestra** [comment]
@AmEv7FAM Ahh thanks for pointing those out. Actually those may be more suited for the Wiki pages. Maybe we could translate and move them there? That way it would be easier to find, plus it's translator friendly. Or we can keep them where they are and convert them to Markdown.

**Comment by justinclift** [comment]
@odysseywestra That'll need someone to create the Wiki first.  You ok to get that done? :smile:

**Comment by AmEv7Fam** [comment]
Good idea, the two of you. I think the wiki will make documentation a bit easier for translators.

Open the wiki, and we can easily convert the PDFs into Markdown.

**Comment by mmuman** [comment]
We can always convert the wiki syntax back to MD then PDF with things like Pandoc btw.

@scribblemaniac yeah I noticed, thanks ;-) and the Linux howto I did was in english already :D

**Comment by mospina** [comment]
@mmuman sorry, where is thelinux howto?

**Comment by mmuman** [comment]
@mospina with the rest of the linux branch: https://github.com/opentoonz/opentoonz/pull/51

**Comment by odysseywestra** [comment]
Okay I've open the wiki up so we can translate and move them there. After we are finish with the transfer, someone should make a pull request with purging them from the Repository. Please keep it organized.

**Comment by AmEv7Fam** [comment]
Started to copy the Japanese PDFs into my fork.

I'll give you a chime when I've got them all copied over.

(Unfortunately, GitHub doesn't allow pull requests on wikis alone yet; the good news is, you can grab it and push it to your repository, the bad news is, it needs to be done semi-manually.

**Comment by odysseywestra** [comment]
That's fine let me know when you are ready and I'll get them on the wiki.

**Comment by Chayemor** [comment]
I offer to translate both to Spanish and English.

**Comment by automated-reckoning** [comment]
I've been digging into the raster/vector data structures in the hopes of improving OT's copy/paste functions. Unfortunately most of the comments at this level are still in Italian. I'm doing my best with google, but I'm afraid some of the comments don't make much sense after machine translation.

**Comment by RodneyBaker** [comment]
I believe most of the known areas of interest have been translated into english.
That is a significant achievement so.. congratulations and thank you to all involved in the effort.

Recommend closing this and opening new issues for specific translation needs.

There are too many resources to list here but here is primary one:

http://opentoonz.readthedocs.io/en/latest/#

**Comment by RodneyBaker** [comment]
Recommend closing this issue and opening documentation issues at:

https://github.com/opentoonz/opentoonz_docs
