### ISSUE TITLE
Are there any plans for Opentoonz and Tahoma?

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4300]
I mean bringing cool Tahoma features to Opentoonz at some point, and if it is the idea, is there a date that the rest of the mortals can know?

Sometimes I wonder why Opentoonz and Tahoma don't join forces due to the little collaboration that usually exists with both programs individually. I think they would make a good team.

**Comment by RodneyBaker** [comment]
Sure.  Some of the features of Tahoma are tagged with a label of 'roadmap' as that label is often used to suggest there is code available for porting over to Opentoonz.

As with most development efforts those ports mostly need a champion... or champions... folks to actually do the work of porting.
It is important to note that the underlying source code isn't exactly the same so porting isn't just a matter of copy/pasting the code from one program to the other.

As to why OT and T2D don't 'join forces' more often the forces involved are mostly two people (Shun and John) who rightly so are focused on the respective programs they maintain.  Others join in the effort when and where they can.  As such there is a limit of 'forces' to draw from. 

As you did ask if there was a 'plan'... nothing particularly set in stone.
A wise person once posted on the internet that a schedule is 'only about confindence' is something getting done.
Does a general 'roadmap' meet your criteria as a plan?
If it does then I'll refer you to things currently tagged with 'roadmap', some of which consist of features from Tahoma:

https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3Aroadmap

There is a lot that can be done to leverage the forces behind OT and T2D (and other Opentoonz forks) and to grow the Opentoonz community.  Or to put it another way... "If wishes were fishes... we'd need a really big net!".  :)

For those with an affinity for C++ and github we hope you'll join the effort.

**Comment by RodneyBaker** [comment]
We would be remiss if we didn't mention that some folks have been executing their plans for Opentoonz and Tahoma.
Let's make sure we appreciate and recognize their effort.

**Comment by F-Burning** [comment]
Thanks for the reply, It's clear for me.

I am totally grateful for the selfless efforts of the developers, without them, especially Shun, this wonderful program would not be in our hands!

**Comment by RodneyBaker** [comment]
Will close this report.  Thanks for the question.
You aren't the only one wondering about the relationship of OT and T2D... and other forks as well.
