### ISSUE TITLE
Old shift and trace is not better?

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4306]
I was seeing this video...

https://www.youtube.com/watch?v=N3RsBr932NU

... and I find this more direct and less cumbersome to work with. It even seems that there is no limit of drawings that you can move like now, that it is reduced to the previous one and to the later one, and with how versatile the timeline is I don't understand why this feature is so limited.

**Comment by RodneyBaker** [comment]
I don't use Shift and Trace a lot so I might be missing something in the details here...

Current Shift and Trace isn't limited to only one previous and one latter image.
The frames presented is adjustable/controlled by onionskin markers.

In the video Simon mostly uses the Level Strip onionskin markers but either that or timeline/xsheet markers can be utilized depending on preferred workflow.

At any rate, I followed the same process as in Simon's video and didn't observe any shortfalls.
Can you provide more detail about what is currently lacking in Shift and Trace?

**Comment by F-Burning** [comment]
Hi @RodneyBaker 

The main difference I see is that Simon can move the drawings directly from the canvas, while currently it works with a menu

![02](https://user-images.githubusercontent.com/74098734/157552524-b272e130-cca3-4440-bb88-153c223037fa.jpg)


I don't really feel like this is a big deal, but this methodology limits you to only being able to move two drawings (previous and next), and with how versatile onionskin is, I'm wondering why limit the number of drawings to edit, when it would be very useful to be able to move the ones you wanted

![03](https://user-images.githubusercontent.com/74098734/157552706-89a46944-11ec-40c1-9009-85a6c46e72f6.jpg)


> Aside: Thanks for getting me to actually use Shift and Trace.


Thank you too for being interestedthe interest, the truth is that it is a very useful function!

**Comment by gab3d** [comment]
@F-Burning 
Well, you are under the wrong impression, really...
1. Shift and Trace have always worked with two reference drawings, as it is intended to help in making an intermediate drawing (between these two), by letting the user move/rotate/scale those reference drawings and then "trace" over them to create the new intermediate. Honestly, I don't envision how being able to see and transform more (far away) drawings could help the purpose of the tool.
2. You can currently click on the lines of a reference drawing to select it. The "Previous/Following Drawing" options in the toolbar, were placed there to help in selecting, because there wasn't always easy to select from the Viewer image itself.

**Comment by F-Burning** [comment]
Thank you, my mistake there, I didn't know that! 

> 1. Honestly, I don't envision how being able to see and transform more (far away) drawings could help the purpose of the tool.

Ok, for example, imagine you're at frame 14 and you want to trace a drawing between 1 and 7 on that frame, you just can't because only one previous drawing can be used for tracing! You can create an empty frame between these two and then move it to that frame, but I think it's a bit cumbersome being able to use the specific tool for it.  In addition, you cannot edit each drawing independently, since the change you make will affect all the drawings, and you will have to always reset the options, losing the configuration of the drawing that you already have if you wanted to keep it.

**Comment by gab3d** [comment]
Sorry, I understood what you want (trace in cell 14 an intermediate drawing of the drawings in cells 1 and 7), what I ask myself (but can't answer myself) is why isn't there in cells sourrounding the 14 cell, drawings that are more appropriate as reference for that new intermediate drawing? 🤔

I'm assuming a traditional 2D production workflow, where firstly primary keyframes are drawn, then intermediate frames are produced to lead action lines, etc. And finally, all the rest of inbetweens are made to complete the animation.

**Comment by F-Burning** [comment]
Ni yo entiendo el ejemplo que he puesto @gab3d 😅🤣 Pero a lo que voy es a que, ya que el programa no tiene mesa de luz como clip studio paint por ejemplo, que puedes cargar cualquier dibujo cuantas veces quieras y trazarlo, que menos que aprovechar esta característica para que no tenga límites, independientemente de que tenga o no sentido, porque en algún momento te puede hacer falta, quien sabe, y sinceramente, creo que es mejor que sobre a que falte.

Lo siento por escribir en español, pero es que se me da muy mal expresarme en inglés.

**Comment by gab3d** [comment]
jajaja ok, entiendo, no hay drama. :smile_cat: 

ok, so @F-Burning is basically asking for something along the lines of Clips Studio's "Light Table" function, where you can freely choose any frame to be displayed and transformed, to then trace over it.

Example of that can be seen in the following video:
https://youtu.be/w9c4yxrn4S4?t=77

**Comment by F-Burning** [comment]
that is, thank you😋

**Comment by RodneyBaker** [comment]
Will close as I believe the original question is somewhat answered.
Some users like the old... some like the new.

If there are still shortfalls perhaps either a new report can be open requesting a change or the title and report here can be modified.
