### ISSUE TITLE
Make RGB Picker Pick Screen option sticky

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4313]
I know this is a minor detail, but I think it would be nice to be able to use the style picker tool to pick colors from the flipbook, so you don't have to load color models into the color models option, or images into the canvas.

![Screenshot_1](https://user-images.githubusercontent.com/74098734/157890994-3f90d0ce-af5a-41a7-891d-09c8e5154454.jpg)

EDIT:

This request has been resolved by @RodneyBaker, but another one has come up in the second reply to the thread, so the title has been edited.

**Comment by RodneyBaker** [comment]
In what way does the RGB Picker not accomplish this for you?

![image](https://user-images.githubusercontent.com/2576432/157924767-2730189d-82d3-4f89-a499-68d7940fc1f2.png)

With the Pick Screen option we can select any color (or average color of an area) anywhere on the screen to include the Flipbook.

**Comment by F-Burning** [comment]
Oh, thank you bro, I didn't notice that!

One thing I would like is for this option to stay enabled instead of turning itself off

![3](https://user-images.githubusercontent.com/74098734/157930744-72a7f4f9-d276-4f56-8296-587677a57f42.jpg)

**Comment by RodneyBaker** [comment]
I've taken the liberty of updating the title of this report.
Please feel free to adjust it further as you see necessary.

I suppose in the interim before your requested option can be added a workaround might be to assign a shortcut key to Pick Screen.

**Comment by F-Burning** [comment]
I also used the P hahaha

Thanks once again Rodney, I'll edit the first post so it's not confusing ; )
