### ISSUE TITLE
Can the room layout be quickly tidied before the release of 1.6?

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#4319]
I've just installed the 1.6RC and I hoped the room layouts would have changed. They're still the same as 1.5 (as far as I can see). I've not got a big issue with the content of the rooms (it's always a bone of contention, so I don't want to open that box again), but some of the panels in these rooms are oversized. If we're going to keep the content, could we set them to a better default size before the final release? I know some of these comments will be small changes, but it won't affect the release (no code changes), but will help new users.
My resolution is 1920x1080. I've included screenshots of the initial layout of each room that I think could be tidied and my suggestion:

**Drawing room:**

- The timeline could be slightly shorter. It only needs enough initial space to show the camera column and 2 or 3 other columns.
- The palette and style editor column could be narrower
 
Current:
![image](https://user-images.githubusercontent.com/28575907/158060274-6d9b3179-c2f2-440a-8c1f-ff42c20e7ca9.png)
To change to:
![image](https://user-images.githubusercontent.com/28575907/158060423-c2ab84a2-7bcc-4e8c-bfdf-e7611272cab5.png)

**Palette Room**

- The style editor column could be much narrower

Current:
![image](https://user-images.githubusercontent.com/28575907/158060381-60616cb7-68e7-470c-b379-7997422ac3c6.png)
To change to:
![image](https://user-images.githubusercontent.com/28575907/158060513-f36e2904-409b-4ef5-85b3-43459490a3ba.png)

**Ink n Paint**

- The level strip is far too wide. The width will never be used because it's restricted to the thumbnail size.

Current:
![image](https://user-images.githubusercontent.com/28575907/158060545-74cbb40e-225b-4d63-9a4f-3aa9f3e94bc4.png)
To change to:
![image](https://user-images.githubusercontent.com/28575907/158060571-b095ecfd-b873-42f5-8cbd-0e5562e0f7a9.png)

**Animation room**

- The level strip is too wide

Current:
![image](https://user-images.githubusercontent.com/28575907/158060579-a64b41ac-4652-49a6-a1f4-8f4e269d155d.png)
To change to:
![image](https://user-images.githubusercontent.com/28575907/158060602-0c4d0731-548b-4992-b0d4-18c57d80e22f.png)

Everything else is set to a fair size.

Thanks for the consideration in advance.

**Comment by RodneyBaker** [comment]
@DarrenTAnims As always thanks for the suggestions.
It is not clear who would do this quick tidying up prior to v1.6 release.

Regarding the Level Strip width... this is an issue dating back to 2016 and even has an entry in the online documentation identifying the problem (which suggests changing the size of the icon/thumbnail via Preferences).  It is not clear to me why that particular issue wasn't resolved in the various updates to the Level Strip but I must assume it's a fairly pesky problem which I read as being unlikely to be addressed prior to v1.6 release.

**Comment by artisteacher** [comment]
Jeremy fixed some panel size/resizing behaviors in T2D pretty early on. I'm not sure if those changes made it back to OT.

**Comment by DarrenTAnims** [comment]
I'm happy to submit these small adjustments to the layout, if they'd get into the final release.

**Comment by artisteacher** [comment]
Related to this, the OT program window only takes up part of the screen when it launches for the first time. On smaller screens, a good deal of the interface isn't really usable like this. It really should open maximized instead.

**Comment by DarrenTAnims** [comment]
Absolutely @artisteacher. And is this kind of small startup issues that can be fixed really easily, but also put off a lot of new users. I hope we can fix this for this release. @shun-iwasawa - Is there any chance we can start the program as maximised? Any to maybe fix the initial layout? I don't mean that the panels on screen need to change (although some should), but the initial size of them should be set to the ideal size for use.

**Comment by gab3d** [comment]
agreed...

**Comment by manongjohn** [comment]
Just thought I would share this in case someone was working on the room layouts...

If you want OT to start maximized for new installations, when you are done setting up the default room layouts, make sure you close with OT maximized.

When you create the PR for the default room layout files changes, also replace the `stuff\profiles\layouts\settings\mainwindow.ini` with your `stuff\profiles\layouts\settiings.xxxx\mainwindow.ini` as that will control how/where the main window starts.

**Comment by konero** [comment]
It would be nice if the panel sizes were indeed fixed, it's possible there was something wrong with my environment when I set them up the last time they were updated, so if they work well on another environment it will be good to push an update.

Note: I made them to work on the minimum spec size of 1280 x 1024 rather than 1920 x 1080, not sure if that is still important.
