### ISSUE TITLE
Scene Cast folders can't drag and drop or delete

### ISSUE THREAD

**Issue by adamearle** [opentoonz/opentoonz#4328]
**Describe the bug**
Scene cast folder can't drag and drop folders after creating a new folder. The folder can't be deleted from within the window either.
This is a simple problem that becomes very time-consuming when setting up character libraries for cutout animation.

Thanks @shun-iwasawa 

**To Reproduce**
List steps to reproduce the behavior.
1. open scene cast window.
![image](https://user-images.githubusercontent.com/16330340/158278862-a277fac0-b2ba-4ee5-8f47-5ad6031de207.png)
2. Create 2 new folders by clicking on the new folder icon twice.
![image](https://user-images.githubusercontent.com/16330340/158279016-74ec45c0-1857-4450-be9a-dfd69f3e2663.png)
3. One folder should be placed inside the other.
4. Attempt to drag and drop folder.
5. Attempt to delete the folder.

**Expected behavior**
The folder should be able to drag and drop and be deleted.
It would be good if there was a right-click menu that allowed you to open in explorer.

**Screenshots**

**Device Information:**
Computer specs:
Screen - Huion (on a $100 computer arm )
            - Viano TV

Operating System - 64 bit Windows 10 Pro
                              - Version 4
                              - Pen Touch Support

Processor - Intel Core i7-8700k CPU @3.70GHz 3.70GHz
Ram - 32 GB
Graphics card - NVIDIA GeForce GTX 1070
                       - NVIDIA GeForce GTX 960

- OpenToonz Version:
![image](https://user-images.githubusercontent.com/16330340/158278297-5a9a2d81-96eb-4830-b0d7-86904f0809bb.png)

**Comment by artisteacher** [comment]
Delete works for me, though not cut (ctrl+x | cmd+x). I often use cut instead of delete in OT since standard mac keyboards don't have the same delete key - ours is the equivalent of backspace. There is a modifier key to make delete work, but this is literally the only program I need to do that with so I almost always forget, get annoyed, and then switch to cut. All that to say, it would be helpful if cut worked here too, if the standard delete for macs isn't going to be corrected. 

Drag and drop to reorganize is expected. 

Adding an Open in Explorer (or Finder) command in the context menu is a great idea.

**Comment by shun-iwasawa** [comment]
I tried the steps from 1 to 3 but could not reproduce the problem. In my Win10 environment the second folder was created under the first one.

I confired that currently drag and drop of the folder is not available. (step 4)

I could delete the folder with no problem. (step 5)

>It would be good if there was a right-click menu that allowed you to open in explorer.

You can right-click the cast item and select `Show Folder Contents` to open the containing folder in explorer.

**Comment by adamearle** [comment]
> older should be ab

hi ya & thanks for checking that for me. I have no right-click option at all. Do you have any ideas on the next steps.

**Comment by adamearle** [comment]
Well this is a start for fixing this problem

![image](https://user-images.githubusercontent.com/16330340/203572503-da1d22aa-1f6d-4ec2-8b77-95d760241ac5.png)

**Comment by adamearle** [comment]
Just worked out you can't duplicate in the scene cast as well like you can in the browser

**Comment by RodneyBaker** [comment]
The Recent Scenes listing (as is the Recent Levels listing) are just a listing of files recently used.
It's purpose is to list files... recently used... as in a history.
It's not clear to me how this relates to moving folders around and deleting them.

**Comment by adamearle** [comment]
The issue has been close because UX design is not consistent with the rest of OpenToonz. The delete key removes a folder. Right lcik menu you be added here.
