### ISSUE TITLE
Feature Request: Autopaint for Lines Palette Icon

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#433]
_We discovered there is actually a menu item for this in the Configure Shortcut panel, oddly it's named **Autofill on Current Palette Color** which toggles **Autopaint for Lines**, good news. I previously requested a shortcut for this function, no need now._

I'm requesting an icon, other visual reference or some other widget to give users clarity on whether or not Autopaint for Lines is activated on which color.

Right now, unless we keep the Style Editor panel open in the Settings tab and having selected the color we'll have no indication whether the mode is on or off.

Here is a great presentation of how it works in Retas:

![tvp_ex](https://cloud.githubusercontent.com/assets/19820721/16252468/5e26d320-3826-11e6-9c7d-b7c36bf179ef.gif)

It works the same way in TVPaint since 11.0.3.

Here is a mock up, we could place an asterisk or something else over the color, change the border color, place a tick mark on it, anything will do.

![tz_auto3](https://cloud.githubusercontent.com/assets/19820721/15972087/55197594-2f34-11e6-9998-dc7ecb2dca57.PNG)

**Comment by turtletooth** [comment]
I will look into it soon.  Right now I am working on H264 export.

**Comment by shun-iwasawa** [comment]
@turtletooth 
If you do not start working on this issue yet, is it OK if I tackle it ?
Actually this UI feature seems to be regression from Toonz Harlequin.

**Comment by turtletooth** [comment]
Yeah- I am out of town until tomorrow, so I can't get to it tonight and I want to finish the unsaved on exit dialog and get going on h264.  So I can't get to it too soon anyway.  Thanks for working on it.

**Comment by turtletooth** [comment]
@shun-iwasawa BTW - would you mind looking at my most recent comments on the pixels pull?  I think I am close but need to change the default camera dpi to 53.3333 for all types so scenes don't get messed up switching between the two.

**Comment by shun-iwasawa** [comment]
OK. I'll be out of the office from tomorrow as well so I'll check it out next week.
