### ISSUE TITLE
Level Strip Icons Disappearing

### ISSUE THREAD

**Issue by abstractfragment** [opentoonz/opentoonz#435]
I'm having a problem with my level strip icons disappearing. They will disappear from the level strip window and then the frame I had them exposed into the xsheet will go blank too riddling my animation with holes. I don't know what's causing this or how to fix it.
![broken level strip](https://cloud.githubusercontent.com/assets/19860818/15972074/590fdb54-2f0a-11e6-877f-9a4467022302.png)

**Comment by turtletooth** [comment]
We need some reproducible steps to be able to take any action on this.

**Comment by MarkGnarz** [comment]
Hello,  I've just run into this issue as well.  All of my Toonz Raster levels are doing this.

  I had been animating a number of walk cycles using the Toonz Raster Level as my default.  This past weekend I started some doing some cut out animation and switched the default level to Toonz Vector Level. Today I went back to work on a walk cycle and discovered all of my previous work disappeared.  

  I started on another walk cycle this morning ( on Toonz Raster Level)everything was fine and I was saving manually.  When I came back from a break and clicked on the screen, the last  drawing I worked on disappeared.  Restarted Open Toonz and loaded the scene only to see all the work from this morning has disappeared, the level strip drawings all showing no Icon and tinged red.


The work done on the Toonz Vector level is fine.  
![opentoonz_lost_work](https://cloud.githubusercontent.com/assets/27441201/25017665/a2a9a832-2052-11e7-96aa-e62c940bbdf9.jpg)

![Uploading OpenToonz_Lost_work.jpg…]()
@turtletooth

**Comment by MarkGnarz** [comment]
Ok, I completely removed OpenToonz and re-installed it.  And all my saved Toonz Raster levels are back to normal.

I think this might have been caused by changing my default level in Preferences from Toonz Raster to Toonz Vector and back again
