### ISSUE TITLE
Crash on Right Click in Xsheet (MacOS)

### ISSUE THREAD

**Issue by lindsayM12** [opentoonz/opentoonz#436]
Just downloaded the program and still getting a feel for it. Didn't see this particular issue posted yet. Let me know if I should move it!

Right clicking anywhere in the X-sheet after a delay will crash the program. I'm on Max OS running OS X El Capitan Version 10.11.3 and I'm also using a magic mouse, and I think the connection to the bluetooth is the issue:

Application Specific Information:
Assertion failed: (getDragTool() == 0), function mousePressEvent, file /Users/keisuke_ogaki/.jenkins/jobs/opentoonz/workspace/toonz/sources/toonz/xshcolumnviewer.cpp, line 1454.

I'll try to get my hands on a wired mouse and see if the problem persists.

**Comment by artisteacher** [comment]
Is this still an issue? I'm not having any problems with 10.11.6 or 10.12.4.

**Comment by turtletooth** [comment]
@lindsayM12 if this is still an issue, I can reopen it.
