### ISSUE TITLE
Undo and Redo Button

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4372]
There was an issue posted about this before, but it wasn't a feature request, and got closed in 2017.

I still consider it a useful addition, it's a very common operation, more so than pastes and the like.
I'd be fine with it being in the menu as dedicated entries, too. Perhaps after help. 
Aka: 
File|Edit|Scan & Cleanup|Level|XSheet|Cells|Play|Render|View|Windows|Help|Undo|Redo

(Which would place it further to the right ...and I'm right handed :P, saving not only one click to open the edit menu, but also cutting travel across the tablet down some...)
Or even Help|Redo|Undo, which kind of messes up the logical flow of backwards and forwards, but would put the most used command at the edge, for less precise clicking

**Comment by RodneyBaker** [comment]
You do know you can customize the menus for each room in Opentoonz right?

As such you can place Undo anywhere you like.
Currently it is located in File|Edit  but it can be placed as many locations as desired.

Here I've added a new UNDO room where every menu categorie's first option is... Undo:

![image](https://user-images.githubusercontent.com/2576432/160275345-e9e8edf7-2416-4f31-9671-4ea402f72fd9.png)

The same can be done for other options as well such as Redo:
![image](https://user-images.githubusercontent.com/2576432/160275397-5497c2e1-db62-4d39-91c9-6b8d089c54a4.png)



Note:  The menu cannot be customized in Tahoma2D in the same way as it has been modified.  Users of T2D will have to press for other options.

**Comment by Bracket-H** [comment]
I did not know that. Thanks. Closing this then ^^;

**Comment by Bracket-H** [comment]
Err, I'm gonna leave this closed, but...I don't get an option for changing the menu >.>
I'm (still) on 3165553f762ec2b881e8b6e7e4494894e8d2b30
Linux...
Did something change on that front?

**Comment by RodneyBaker** [comment]
Should be available to all users as far as I know.
You don't have the Right Click option on the room tabs?

![image](https://user-images.githubusercontent.com/2576432/160276530-28b469a7-1d2b-4851-95a4-4cf76628d380.png)

**Comment by Bracket-H** [comment]
I don't. Lol. The functionality is in a preprocessor check in the code. I'm amused...
I commented that check out and it seems to work... lol.

**Comment by Bracket-H** [comment]
It seems that the changes don't get loaded upon restart, despite being written to the menubar.xml config file correctly.
In fact, customizing menu bar again, shows the entries in the correct order and clicking okay in the menu customization window will restore the customized layout.

But it won't load this custom layout upon start of opentoonz.

**Comment by Bracket-H** [comment]
In menubar.cpp, at line 250, there is another check for Windows/Cygwin, along with a comment a bit further down:
````
void StackedMenuBar::loadAndAddMenubar(const TFilePath &fp) {
#if defined(_WIN32) || defined(_CYGWIN_)
  QMenuBar *menuBar = loadMenuBar(fp);
  if (menuBar)
    addWidget(menuBar);
  else
    addWidget(createFullMenuBar());
#else
  /* OSX では stacked menu が動いていないのでとりあえず full のみ作成する */
  addWidget(createFullMenuBar());
#endif
}

Stacked menu is not working on OSX, so create a normal one. 

Must be an OSX issue then ^^;
````

**Comment by konero** [comment]
Undo and redo are by default included on the Command Bar (Windows > Command Bar), you could utilize this in some way. It's also customizable (right-click anywhere on it, it's the same as editing the menu bar).
