### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [opentoonz/opentoonz#4387]
toonz/sources/stdfx/igs_density.cpp line 123

else if ((std::numeric_limits<unsigned short>::digits == bits) &&
             (std::numeric_limits<unsigned short>::digits == ref_bits)) {
    change_template_(reinterpret_cast<unsigned short *>(image_array), height,
                     width, channels,
                     reinterpret_cast<const unsigned short *>(ref), ref_mode,
                     density);
  } else if ((std::numeric_limits<unsigned short>::digits == bits) &&   // <- identical
             (std::numeric_limits<unsigned short>::digits == ref_bits)) {
    change_template_(image_array, height, width, channels,
                     reinterpret_cast<const unsigned short *>(ref), ref_mode,
                     density);
  } else {
    throw std::domain_error("Bad bits,Not uchar/ushort");
  }

**Comment by flurick** [comment]
Was removed in pr https://github.com/opentoonz/opentoonz/pull/4700
