### ISSUE TITLE
StyleEditor does not refresh in OT1.0.2 on OSX 10.11.5

### ISSUE THREAD

**Issue by Dragularos** [opentoonz/opentoonz#439]
Hi there,
1) Go to the StyleEditor and choose a color on the left field of colors. 
2) Toggle the "Wheel" window off and on again
3) Try to choose another color on the left colorfield (the new color will be chosen but it will not refresh the colorfield.)
4) Switch to (for example) the Texture window and back to the plain window.
5) The left colorfield should have updated correctly.

As you can see in the pictures i have added.

![bildschirmfoto 2016-06-13 um 02 45 31](https://cloud.githubusercontent.com/assets/19895943/15994984/a6f538a0-3112-11e6-9ede-0ca3bf332e39.png)
![bildschirmfoto 2016-06-13 um 02 46 10](https://cloud.githubusercontent.com/assets/19895943/15994983/a6f499e0-3112-11e6-82c7-eabd66f2c731.png)

... as you can see on the second picture, i have chosen a dark black color but the colorfiled hasn't changed at all.

Thanx for your good work!

Phil

**Comment by Dragularos** [comment]
The problem seems to be solved in OT 1.0.3.

**Comment by artisteacher** [comment]
@turtletooth - this is working in the current release. Should be ok to close.
