### ISSUE TITLE
Missing a "&" in menu item "Scan & Cleanup"

### ISSUE THREAD

**Issue by jcome** [opentoonz/opentoonz#440]
<img width="563" alt="screen shot 2016-06-13 at 10 34 41 am" src="https://cloud.githubusercontent.com/assets/417336/15996215/c306b894-3157-11e6-87fe-3f4505edb4ed.png">
the menu in the new UI layout is missing a "&" as shown in the screenshot.

**Comment by jcome** [comment]
it is strange, I have remove the app and the stuff folder complete, and reinstalled the nightly build. The menu item is correct for the first time, but it will missing "&" after that ( close the app and open it again).

it happens on Windows only, there is no issue on OSX.

**Comment by jcome** [comment]
it seems work by adding another "&: character in the line:

[https://github.com/opentoonz/opentoonz/blob/master/stuff/profiles/layouts/rooms/Default/menubar_template.xml#L76](url) 

`  <menu title="Scan &amp; &amp; Cleanup">`

**Comment by jcome** [comment]
besides Default rooms layout, StudioGhibli  layout has the issue too.

https://github.com/opentoonz/opentoonz/blob/master/stuff/profiles/layouts/rooms/StudioGhibli/menubar_template.xml#L76

**Comment by adamearle** [comment]
Maybe "Scan + Clean up"?


*Adam Earle*
*Phone:* 0431799431
*Google Hangout: * MrAdamEarle@Gmail.com
*Email:* MrAdamEarle@Gmail.com

**Comment by skitaoka** [comment]
This was fixed by https://github.com/opentoonz/opentoonz/pull/441.
