### ISSUE TITLE
all my frames have turned red, and all of the images on them are gone.

### ISSUE THREAD

**Issue by Arc32** [opentoonz/opentoonz#4403]
### Ask a question related to OpenToonz

i am really confused. all of my frames are now red, the images on them are gone, and the drawing square things are really big (i think there called pixels). i really worked hard on this one, and i would really like help please.

**Comment by DarrenTAnims** [comment]
This might help: https://youtu.be/-OlP2rtbS-E

**Comment by Arc32** [comment]
sorry, i tried updating it and it will no longer open... thanks for the help though!
