### ISSUE TITLE
Level editor box colour sometimes fails to show

### ISSUE THREAD

**Issue by KaseyFarron** [opentoonz/opentoonz#4405]
### Description

When I click a drawing in level strip I expected to see a white background (Level Editor Box Colour in Preferences), but instead it shows as transparent. **_Usually_** it shows as white, but for some reason it sometimes shows transparent and the only way to fix it is to restart OpenToonz.

### Steps to Reproduce

Sorry, but I don't know what reproduces it! I do know that saving, closing and starting the program again fixes it for awhile.

### Expected Behavior

The level editor box colour background should display what's set in preferences.

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/55353161/164872709-c239dd5c-3795-4d2e-982c-e710ddb7865c.png)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

built Mar 22 2022

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by DarrenTAnims** [comment]
I can't see what's happening here. A full screenshot of the whole program might help. But it sounds like you've clicked on the drawing in the level strip, which shows a different background colour (to show it's a different view). If that's the case, just click back onto the drawing that's exposed on the timeline and you'll get back to the normal view.

**Comment by KaseyFarron** [comment]
> I can't see what's happening here. A full screenshot of the whole program might help. But it sounds like you've clicked on the drawing in the level strip, which shows a different background colour (to show it's a different view). If that's the case, just click back onto the drawing that's exposed on the timeline and you'll get back to the normal view.

Hi @DarrenTAnims, I updated my post a bit with more clear description. Basically when I click a drawing in level strip the background is usually white (or whatever is set for Level Editor Box Colour in preferences) but sometimes it shows as transparent, the only way to get it to show up as white again is to restart OpenToonz. 😕

**Comment by shun-iwasawa** [comment]
Please check the following:
- Is the current level type either Toonz Raster or Raster? The BG color does not appears when selecting a Vector level.
- Is the current tool is enabled on the current level type? Selecting some non-available tool will hide the BG color.

**Comment by KaseyFarron** [comment]
> * Is the current level type either Toonz Raster or Raster? The BG color does not appears when selecting a Vector level.
> * Is the current tool is enabled on the current level type? Selecting some non-available tool will hide the BG color.

Toonz Raster, I didn't know that some tools didn't display the BG colour, that could possibly have been the problem! Thank you! I'll close this for now and reopen if I encounter the problem again. 🙏
