### ISSUE TITLE
Cannot run last master/nightly branch builds Appimage for linux

### ISSUE THREAD

**Issue by le-dragon-dev** [opentoonz/opentoonz#4406]
### Description

Hello, I'm trying the last two Appimage (Linux) from the master and nightly branch and I've got the following error:
`/home/dragondev/OpenToonz/.mount_OpenToxBweID/usr/bin/OpenToonz: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2`

I try each time with the GCC and Clang builds:
- [https://github.com/opentoonz/opentoonz/actions/runs/2206033732](https://github.com/opentoonz/opentoonz/actions/runs/2206033732)
- [https://github.com/opentoonz/opentoonz/actions/runs/2205991136](https://github.com/opentoonz/opentoonz/actions/runs/2205991136)
- [https://github.com/opentoonz/opentoonz/actions/runs/2199456451](https://github.com/opentoonz/opentoonz/actions/runs/2199456451)

I did not try the previous builds.

### Steps to Reproduce

1. Linux system (Ubuntu 21.10 for me)
2. Download one of the package of the last linux build on the master/nightly branch
3. Unzip and run the appimage with a terminal
4. Error `symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2`

### Expected Behavior

Start the software

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

April 22 

### Operating System

Linux

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by andeon** [comment]
What  does `ldd /lib/x86_64-linux-gnu/libpango-1.0.so.0` show you?

Maybe something is broken and you need to update the system. Either is a problem of lack or deprecated lib, that's hard to know.

**Comment by johnblommers** [comment]
I see the exact same error message preventing Opentoonz from running. This on PopOS 22.04. This system is as up to date as it gets.

```bash
ldd /lib/x86_64-linux-gnu/libpango-1.0.so.0
	linux-vdso.so.1 (0x00007fff7c595000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5888fd8000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f5888e9e000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f5888e3e000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f5888c66000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f5888c4a000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007f5888c3d000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f5888b6e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5888946000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5889160000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f58888d0000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f58888c3000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f58888bc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f58888a0000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f588885a000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f588882e000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f5888825000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f588875d000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f5888736000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f58886fd000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f5888666000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f588862b000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f588861d000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f58885fa000)
```

Perhaps a compatible Pango library should be bundled in with the AppImage to avoid this kind of dependency hell.

**Comment by andeon** [comment]
> 
> Perhaps a compatible Pango library should be bundled in with the AppImage to avoid this kind of dependency hell.
> 
Not sure if it a good practice for AppImage https://docs.appimage.org/reference/best-practices.html need check this. @manongjohn  Do you have experience with this, what do you recommend for now?

But recently a I see a discussion about https://github.com/AppImage/AppImageKit/issues/1193

**Comment by manongjohn** [comment]
Please keep mind that there is no official support for the Linux versions of OT. The Snap/Flatpak versions are maintained by someone in the community. Whether they are watching this repo or not is unknown. Should report Snap/Flatpak OT versions issue in the snap/flatpak communities or somehow contact the maintainer of those versions directly.

Sadly as far as Linux versions go, there are many flavors of linux, each with their own nuisances/library support, making universal support for them quite difficult.

As far as this issue goes, AppImages should try to include libraries it compiled with to avoid problems like this.  In lieu of that, usually I would get the right versions on my system, but that may impact other things especially if you are downgrading or may need to do some additional stuff to keep both versions (if possible) and making sure the apps use the appropriate ones.

**Comment by johnblommers** [comment]
Last year I created an AppImage from the Ted richtext word processor. In testing I ran it on a bunch of VMs of different Linux distros. This uncovered as many of the missing dependencies as I could find and bundled them into the AppImage.

But tomorrow a distro could come by that doesn't bundle a dependency and break my Ted AppImage. Therefore the safest strategy is to bundle everything into it.

**Comment by johnblommers** [comment]
Indeed I got OpenToonz running on my system by using Flatpak to install it. Apparently it bundles in the necessary library version.

> Sadly as far as Linux versions go, there are many flavors of linux, each with their own nuisances/library support, making universal support for them quite difficult.

The Linux community derives great strength from the diversity of the ecosystem. Yes packaging standards themselves are many in number and I am amazed at the amount of packages some projects build in response.

I hoist a glass of Romulan Ale to any project like OpenToonz that also provides Windows, macOS and Linux versions.  I think that's amazing and wonderful.

**Comment by andeon** [comment]
I think there is a problem with the workflow linux.xml because somethings are deprecated, so need someone fix it for appimages version work correctly.

I don't recommend it, but if you really want to run it in the state it's in now:

`env LD_LIBRARY_PATH=/lib/x86_64-linux-gnu ./OpenToonz.AppImage `

I recommend using the Flatpak or Snap version, but remember you need to use different settings to set things like ffmpeg.

for snap: `/snap/opentoonz/current/usr/bin`
for flatpack:  `/app/bin/`

Another alternative is use tahoma2d
