### ISSUE TITLE
cannot save (OpenToonz 1.6)

### ISSUE THREAD

**Issue by kkuzie** [opentoonz/opentoonz#4417]
### Description

when saving (or auto-saving) getting following error message:

C:\OpenToonz stuff\sandbox\scenes\ghost.tnz.tmp
:Search permission is denied by a component of the path prefix, or write permission on the file named by path is denied, or times is NULL, and write access denied

have tried saving with new name, changing file name, closed OpenToonz and reopened, and restarting computer. When did this yesterday, closed OpenToonz then when reopened it worked. Today, nope.

I saw there was this problem in version 1.4 (i could not discern the solution from the report).

### Steps to Reproduce

1. create new scene (or open saved scene)
2. File > save scene (or save scene as) 
3. get warning

does for auto save as well. 

### Expected Behavior

Expect file to save.

### Screenshots, Video & Crash Logs

![opentoonz saving error](https://user-images.githubusercontent.com/46034255/165329381-4244eddb-abdf-4d14-9346-96fed9ceade8.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by DarrenTAnims** [comment]
It sounds like your OpenToonz Stuff folder doesn't have the correct write permissions. Try this:

Open Windows Explorer and go to the C:\OpenToonz stuff folder
Right-click OpenToonz stuff folder and select Properties
Click on the Security tab
Look in the Group or user names box for your username.
If you do not see it, click on the Edit button
Click on the Add button
Enter your username in the bottom box and click on Check Names.
After it finds/verifies your username, click 'OK'
Click on your newly added username in the top box
In the bottom box, check Full control under the Allow column
Click OK until you close the Properties dialogbox.
Try restarting OT normally.

And you might want to add the Stuff folder as an exception in your anti-virus software. That could be getting in the way of saving to disk.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
