### ISSUE TITLE
frame disappear sometime!!!!

### ISSUE THREAD

**Issue by HeartPounD** [opentoonz/opentoonz#4435]
### Description

I have no idea that some of you guys have seen this bug but it has happened to my twice now. Sometime, if I undo my drawing that glitch happen and my some of my drawing disappear and I have to do it again. Now, the second time happened. That's very annoying and It got me angry. 

There is about another bug that I would like to ask you guys. When the auto save happened while I was selecting my drawing with selection tool, it deselected it. And sometime, it make glitch.

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Other

**Comment by RodneyBaker** [comment]
@HeartPounD We really need more information to address your issue.
Please consider opening a new request and sharing some screen grabs or video that displays the problem.

Another useful approach is to join on of the Opentoonz discords where other users can assist with troubleshooting.
There you can chat and even share your screen live.
