### ISSUE TITLE
OpenToonz(1.6) stops responding 

### ISSUE THREAD

**Issue by plurplesz** [opentoonz/opentoonz#4436]
### Description

Whenever I import, make, or load a scene it continuously loads the blue circle cursor and won't let me exit the application or click anything. And even when I start a new project or scene it does the same thing. 
![Opentoonz wont work](https://user-images.githubusercontent.com/104744947/166176792-a5fde89a-6b40-4756-96a2-faa208730904.jpg)
#OpenToonz stops responding 

### Steps to Reproduce

1. 
2. 

### Expected Behavior

I would expect it to load my scene without continuously loading.

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
When a user is prompted with an option to 'Change Project' that is an indication that the files are not in a common recognized location.

There are several ways around this to include adding the location in Preferences but...
What I tend to do is select 'Change Project' and then with that open use the Browser room to open the .tnz project (via Right Click > Export Scene and save the project to an accepted location.

You may have some other things going on here but getting all of your projects into recognized locations would be a good start.
Some will suggest not using the Sandbox to store projects but users can almost be guaranteed that a scene will open when scenes are saved in the Sandbox.  Until such a time as users get comfortable using Opentoonz I recommend using the Sandbox.

**Comment by DarrenTAnims** [comment]
This dialog is showing because you've selected "New" as the current project (in the dropdown at the top left of the previous dialog. And as the popup says, the scene that you want to load is part of the Sandbox project. Just choose, Change Project.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
