### ISSUE TITLE
Improvements AOTz brush pack

### ISSUE THREAD

**Issue by andeon** [opentoonz/opentoonz#4437]
I'm working on improving and small fixes to the brushes in the pack. I'd like to know if you need specific brushes. The majority of brushes in the package focus on fast paint to create backgrounds and conceptual art.

https://user-images.githubusercontent.com/11843239/166332194-6ea242e6-5a08-4fe1-84f3-f96fc30e94de.mp4

Important:

- Many Mypaint brushes are only designed to be used in standard sizes. They don’t scale to large sizes consistently.

- Many Mypaint brushes are designed to only be used with a graphics tablet or device with pen pressure. AOTz brushes try to keep optimized to work with both.

- Mypaint brushes are designed to work primarily on the Opentoonz "Raster Level", and some brushes only work correctly there.

I thought of putting the "raster level" icon to flag this instead of using the red border. What do you think? Is this enough for the user to know which level to use?

![new](https://user-images.githubusercontent.com/11843239/166332850-ee7dbbaa-5cd7-472f-b632-22e8817bf64f.png)
_*the FX in many brushes means it's an effect that often needs a background color to work or to create with less effort, I'm not sure people know this too._

![random AOTz brushes](https://user-images.githubusercontent.com/11843239/166396485-7de0945a-c092-499f-9c38-7e0f3750db94.png)

**Comment by artisteacher** [comment]
I like the idea of adding the raster icon to make the level type clear. Severa existing brushes would benefit from that.

**Comment by DarrenTAnims** [comment]
Ideally, the brushes that don't fully work with Toonz Raster levels won't be shown, or they'd be in a different list. Maybe, in advance of the Tahoma feature coming to OpenToonz, of the grouping of brushes, the raster-only brushes could be put into a separate folder, then they'd be shown separately to the other brushes. The folder name is shown as the group title.

**Comment by andeon** [comment]
> Ideally, the brushes that don't fully work with Toonz Raster levels won't be shown, or they'd be in a different list. Maybe, in advance of the Tahoma feature coming to OpenToonz, of the grouping of brushes, the raster-only brushes could be put into a separate folder, then they'd be shown separately to the other brushes. The folder name is shown as the group title.

Toonz Raster is good for "Cel Paint", so technically using MyPaint brushes to create painterly wouldn't be a good option initially, as it doesn't work well; many people give up on the program when they try to paint because they don't understand the concept of level type. But it's possible with another approach.

https://user-images.githubusercontent.com/11843239/166554477-a8948603-538a-4c6c-9eb9-2e3eae98f28e.mp4

Creating more levels to "blend the colors" is more steps than just using the raster layer, but it has the advantage of fully controlling the colors. It's good to props design or some foreground layouts.

**Comment by andeon** [comment]
> Hm, my raster brush strokes don't update like that when I change colors. Is it a new feature? Or is it a feature of this AOTz 

The palette styles are dynamically updated to drawn lines and filled areas by using indexes only on "Vector Level" and "Toonz Raster Level". For the "Raster Level" the palette styles are used to draw and no link exists between the styles and the already drawn lines. This palette is named as Raster Drawing Palette.

**Comment by Bracket-H** [comment]
> > Hm, my raster brush strokes don't update like that when I change colors. Is it a new feature? Or is it a feature of this AOTz
> 
> The palette styles are dynamically updated to drawn lines and filled areas by using indexes only on "Vector Level" and "Toonz Raster Level". For the "Raster Level" the palette styles are used to draw and no link exists between the styles and the already drawn lines. This palette is named as Raster Drawing Palette.
> 
> When you try to explain about it it gets confused because it has a similar name, I suppose for new users there is much more confusion and doubts.

Yes ^^; I was merely confused because I did not expect fancy brushes to work on Toonz Raster levels, I thought you could only draw with the simple round 'standard' brush.
That said, the name similiarity had me confused for longer than needed, can't think of a better alternative though since both Toonz Raster and Raster ARE Raster formats.
The only thing I can think of is "bitmap" level, bitmaps are rasters as well.
But whenever I hear or read bitmap specifically, knowing how crappy that format is (at least tradionally, MSPaint etc), I don't expect anything fancy.

Nothing fancy like 'updateable live wired color styles' for sure.
So maybe Bitmap Level could work, but that is a very very very weak suggestion that relies on assumptions/presuppositions.

**Comment by andeon** [comment]
Rebranding all the icons in the images, I created new brush to simulate a dirtier sketch. New brushes to create quick concept art, when I finally push the package I'll detail it better.

https://user-images.githubusercontent.com/11843239/169639570-2c8d257a-7a14-4a2d-9f54-911b088b5c5d.mp4

I'm putting the "raster level" icon, how recommendation to use this level and the red border to flag for user that brush not gonna work on "Toonz  Raster Level"

**Comment by RodneyBaker** [comment]
Apologies for the delayed response.
I'm a fan of your brushes and use them quite often.

I hesitate to suggest this butto add the thought for general consideration...
It might be appropriate to drop the OT icon to better allow for adoption of the brushes by other programs that use mypaint brushes.  Unless there is a specific reason why these brushes should be identified for use specifically with Opentoonz.  If the goal is to promote OT with the brush set... mission accomplished! :)

I personally like the OT icon (looks spiffy!) but am not sure it is necessary.
I also get the sense the OT icon might be a reason Tahoma2D would hesitate to add the brushes as that might lead to some confusion.

Having said this I suppose that same thing could be said for the 'raster level' icon and red border but I understand there is a distinct and direct purpose for that addition.  The icons will of course have to be updated in that far flung future when they work on toonz raster levels.  (No I don't think that will be any time soon!)  

All this for what little it is worth.
Thanks for putting the effort into adding and updating the AOTz brush pack.
Good stuff!

**Comment by andeon** [comment]
I really appreciate any comments to improve this. I built the brushes for OpenToonz many don't works in the same way even in mypaint. I put this icon (label) to make it clear that it was optimized for Opentoonz. 

I really not like to put these graphics flags. But I thought about the people using the brush "Why has theses icons in some brushes?", So maybe start to understand why some brushes not working or search to "What is the difference between Toonz Raster Level and Raster Level?". But I not sure If I need worry since we have documentation explained about this https://opentoonz.readthedocs.io/en/latest/managing_palettes_and_styles.html 

Someone suggested to me a light blue instead of red, since thats the color of "Raster level" at Xsheet and Timeline. 

![new_brush](https://user-images.githubusercontent.com/11843239/169662410-ce03d1a2-050f-4b26-b52c-e2b28790fc1e.png)

**Comment by andeon** [comment]
I'm updating the repository for now [AOTz](https://github.com/andeon/aotz) to test just Choose the **Download ZIP** option from the **Code** pull-down menu; the release will be v5 soon!

I see that Shun-iwasawa is updated the environment, so I'm not sure if it's safe to push it yet.
