### ISSUE TITLE
FFMPEG not found by OpenToonz 1.5 in Ubuntu

### ISSUE THREAD

**Issue by Nelo390** [opentoonz/opentoonz#4438]
**Describe the bug**
FFMPEG not found by OpenToonz on Ubuntu (Mint)

**To Reproduce**
List steps to reproduce the behavior.

    1. Install OpenToonz on Unbuntu through the integrated Software Manager
    2. Install ffmpeg on from apt-get (command "which ffmpeg" output "/usr/bin/ffmpeg")
    3.  Launch OT, try to render as MP4 you get a dialog box saying the program did not find ffmpeg
    4. Go to preference, and set "/usr/bin/ffmpeg" and restart OT
    5. Same error as step 3
    6. Go to preference, and set "/usr/bin/" and restart OT
    7. Same error as step 3
    8. Go to preference, and set "/usr/bin" and restart OT
    9. Same error as step 3

**Expected behavior**
OT should find ffmpeg

**Device Information:**
  Operating System: Linux Mint 20.3
            Kernel: Linux 5.4.0-109-generic
      Architecture: x86-64

OpenToonz build 1.5.0
https://community.linuxmint.com/software/view/io.github.OpenToonz

**Comment by Nelo390** [comment]
First time speaking in github, hope i didn't screw anything up.

**Comment by andeon** [comment]
Please type this command in terminal `whereis ffmpeg` and paste the result here.

Maybe the path to your distro could be:

`/usr/local/bin/ffmpeg `

**Comment by Nelo390** [comment]
**nelo@nelo-22022:~**$ whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz

**Comment by andeon** [comment]
Sorry, but now I'm wondering if this is a snap or flatpak version?

If it a Snap try this put this `snap/opentoonz/current/usr/bin`

**Comment by Nelo390** [comment]
Sorry for the late reply- I tried it and it did not work. If it helps the default save path for files is set to (/home/nelo/.config/OpenToonz/stuff/sandbox/scenes) on installation.

**Comment by andeon** [comment]
We need to know what kind of package you have installed:

> 1. Install OpenToonz on Unbuntu through the integrated Software Manager

That doesn't say much.

**Comment by Nelo390** [comment]
I put in a link to the site at the very bottom, that's all i know about it.
"

OpenToonz build 1.5.0
https://community.linuxmint.com/software/view/io.github.OpenToonz "

**Comment by andeon** [comment]
What does `whereis OpenToonz`  show you?

**Comment by manongjohn** [comment]
Snap version of OT used to have the same issue. It was discovered that ffmpeg was failing to run because a library was missing. OT would fail to launch ffmpeg but not report any specific problem so it just looked like it couldnt find it.

Try running ffmpeg manually and verify it actually runs on your machine.

**Comment by Nelo390** [comment]
@andeon Third one worked:
 Name         Description     Application ID         Version   Branch   Remotes
OpenToonz    2D animation    io.github.OpenToonz    1.5.0     stable   flathub

and @manongjohn I don't really know how to run ffmpeg honestly, When i attempt to open it it looks for an associated program to run it with, "unknown file type". I installed it with the docs instructions for debian, https://opentoonz.readthedocs.io/en/latest/using_ffmpeg_with_opentoonz.html ,which is just running apt install ffmpeg in terminal.

**Comment by andeon** [comment]
Ok, it's a flatpak, so set this path and restart OT:

`/app/bin/`

This is a permission "issue", applications that are run with Flatpak or Snap have extremely limited access, as @manongjohn said but I believe they have fixed, the problem is that the path are different for each.  Some times you need to use commands to update applications and runtimes for fresh fixes.

**Comment by Nelo390** [comment]
It's alive!!!!! Thanks so much for your help andeon, i appreciate it.

**Comment by francogrex** [comment]
> **Describe the bug** FFMPEG not found by OpenToonz on Ubuntu (Mint)
> 
> **To Reproduce** List steps to reproduce the behavior.
> 
> ```
> 1. Install OpenToonz on Unbuntu through the integrated Software Manager
> 2. Install ffmpeg on from apt-get (command "which ffmpeg" output "/usr/bin/ffmpeg")
> 3.  Launch OT, try to render as MP4 you get a dialog box saying the program did not find ffmpeg
> 4. Go to preference, and set "/usr/bin/ffmpeg" and restart OT
> 5. Same error as step 3
> 6. Go to preference, and set "/usr/bin/" and restart OT
> 7. Same error as step 3
> 8. Go to preference, and set "/usr/bin" and restart OT
> 9. Same error as step 3
> ```
> 
> **Expected behavior** OT should find ffmpeg
> 
> **Device Information:** Operating System: Linux Mint 20.3 Kernel: Linux 5.4.0-109-generic Architecture: x86-64
> 
> OpenToonz build 1.5.0 https://community.linuxmint.com/software/view/io.github.OpenToonz

I have this same problem and this is a BUG in opentoonz n linux, it isn't able to find ffmpeg while ffmpeg is present and perfectly usable

**Comment by RodneyBaker** [comment]
Linux mint has some peculiarities that other flavors of Linux do not.
You may find sufficient recipes for success on some of the Linux mint support sites.
They will often suggest downloading the ffmpeg build specifically set up for Linux mint from the Linux mint repo.

Here's an old link that might get you started.  I saw a few other similar topics but they all pretty much suggest the same or similar solutions.  REF:  https://forums.linuxmint.com/viewtopic.php?t=316413
