### ISSUE TITLE
Platform won't open TNZ file

### ISSUE THREAD

**Issue by noodleofdanger** [opentoonz/opentoonz#4441]
### Ask a question related to OpenToonz

I'm having a problem opening the TNZ files. They are the files that OpenToonz originally saved my animation as but when I go to load the file on OpenToonz again, it says the file is invalid. 
![Screenshot 2022-05-07 233632](https://user-images.githubusercontent.com/105140736/167282012-ec928883-4caa-4fb9-9f30-23469d2d4e5a.jpg)
I've saved the animation as other files but none of them saved the actual animation. The TNZ files seem to be the only file that saved it but I can't open it. I'm not sure what I should do. Am I doing something wrong or is this a bug?

**Comment by DarrenTAnims** [comment]
I notice that there's a space before the dot. Try editing that in explorer and removing that last space.
Also, by loading it from the "Today" folder, I can't see which project it belongs to, which could be an issue, but try removing the space first to see if that works.

**Comment by gab3d** [comment]
@DarrenTAnims 
It'd be good if OpenToonz checked for things like that (trailing spaces) in the file name, before saving the file.

**Comment by RodneyBaker** [comment]
@noodleofdanger Did renaming the scene files help with your problem?
If not perhaps you can share your scene file to assist with the troubleshooting.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@noodleofdanger please let us know if you are still experiencing problems with scene files.
