### ISSUE TITLE
Opentoonz not opening v1.6

### ISSUE THREAD

**Issue by fakedGrid** [opentoonz/opentoonz#4444]
This is my first time downloading Opentoonz but it doesn't open
it opens the screen saying creating main window and then closes without an error message

I tried opening Opentoonz multiple times and  once it opened but when I tried again it didn't open
and I don't think there is an issue with my pc 

I also checked if my antivirus was interfering with it but it was not

I checked windows event viewer for any errors and I found this:

Faulting application name: OpenToonz.exe, version: 0.0.0.0, time stamp: 0x624a4a4e
Faulting module name: DbgHelp.dll_unloaded, version: 10.0.18362.1, time stamp: 0xf8112e59
Exception code: 0xc0000005
Fault offset: 0x000000000003b796
Faulting process id: 0x1624
Faulting application start time: 0x01d865fd02f6a25e
Faulting application path: C:\Program Files\OpenToonz\OpenToonz.exe
Faulting module path: DbgHelp.dll
Report Id: 0caac94e-3e72-4c5d-a4a3-1a559a43b1d5

hope you all help
And I would be able to start animating soon .

**Comment by RodneyBaker** [comment]
@fakedGrid  It seems that you either didn't get a proper download to install with or... perhaps simply got a bad installation**.
I'll recommend joining one of the Opentoonz discords where others can assist with troubleshooting in real time.

** By your report it reads this was your first time installing.  I would normally suggest performating a clean install but if it was the first time then you already should have accomplished that.

**Comment by RodneyBaker** [comment]
All indications point to  the problem of Opentoonz not opening... that is to say not getting past the 'setting up environment' notice with splash screen... relates to antivirus settings.

In the case I ran into I created an exception in the management section of virus protection and this allowed the program to run.

@fakedGrid Please let us know if you've been able to successfully launch Opentoonz.  Thanks!

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@fakedGrid please let us know if you are still experiencing issue opening Opentoonz.

**Comment by fakedGrid** [comment]
thanks, it works now.
