### ISSUE TITLE
File got corrupted and cant open bak file

### ISSUE THREAD

**Issue by Eferadne** [opentoonz/opentoonz#4448]
### Ask a question related to OpenToonz

I am stressed out. I was editing the audio of my animatic when my computer started acting up. I saved the file then turned my laptop off. When I turned it on and went back to Opentoonz, it says some files are missing. Whats worse is, unlike people who say they see red dots, I'm not getting anything to show. It actually doesn't even open the file. I have the bak file but have a hard time trying to convert it to a tnz file. I don't know what to do. This is my first time making some animation and I hate I wasted so much time for it to disappear

**Comment by artisteacher** [comment]
Have you tried renaming the the scene file to remove .bak from the name?

**Comment by Eferadne** [comment]
> Have you tried renaming the the scene file to remove .bak from the name?

Like right clicking and renaming? Cause that's what i did and its still doesn't change the bak file.  Unless I'm supposed to change it to something particular

**Comment by artisteacher** [comment]
You might need to restore backups of the levels too. Look in the drawings or extras folders for the project.

**Comment by RodneyBaker** [comment]
@Eferadne Iexpect you've long moved past the problem you experienced reported here but if not... please share your project file as we we should be able to tell whether there is anything that can be recovered from the file.  If the files should not be shared publically we can do that privately.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
