### ISSUE TITLE
Plastic tool does not create mesh correctly on vector layers.

### ISSUE THREAD

**Issue by Gilraiser** [opentoonz/opentoonz#4450]
### Description

In the two types of image levels that Open Toonz has, the Plastic Tool correctly creates the mesh and then creates the bones that are going to move it. It happens differently in the vector level of Open Toonz, where only a mesh is created in the form of a rectangle.

It was tried with the elements of the drawing grouped and also without grouping.

I hope the information is useful for everyone. Many thanks.

### Steps to Reproduce

1. Create a vector level in Open Toonz
2. Draw something suitable to put bones on
3. Select the Plastic Tool
4. Click Create Mesh

### Expected Behavior

An approximation to the silhouette of the drawing that was created at the vector level should be created.

### Screenshots, Video & Crash Logs

**Drawing made in vector level**

![vector-OT](https://user-images.githubusercontent.com/45057390/169197173-52c5cc6c-b29b-4bc2-9d9a-a2f5a2f76007.png)

**Drawing made at raster image level**

![raster-OT](https://user-images.githubusercontent.com/45057390/169197178-abaa5fb3-d160-4d44-82fe-a58f677c2fb1.png)

### OpenToonz Version

1.6

### OpenToonz Version Information

Built May 4 2022 12:15:42

### Operating System

Linux

### GPU

AMD

**Comment by RodneyBaker** [comment]
This is a known issue on Mac although I'm not sure it has ever been confirmed on Linux.

See reports:  #3978 and #406 although there are a few others

**Comment by Gilraiser** [comment]
Thanks a lot 
@RodneyBaker, it worked adding a subxsheet.

**Comment by RodneyBaker** [comment]
Outstanding.  I didn't actually know if that would work.

We'll keep this report open and perhaps find a way to combine all the similar reports into one (if/where appropriate).

**Comment by Bracket-H** [comment]
I'm on Slackware Linux (64 bit)  and on commit 43165553f762ec2b881e8b6e7e4494894e8d2b30 and the create a mesh button covers the vector shape accurately.

![Screenshot_20220522_234346](https://user-images.githubusercontent.com/93729441/169717174-fffd98b1-d515-46ca-b5b3-8d11a62a1ab7.png)

**Comment by andeon** [comment]
@Gilraiser Can you create a new project and create a simple ellipse with the geometric tool and use the plastic tool? With this image it isn't possible to see what happens in the selected cell, so the best way to test the workflow is to simplify and check what happens step by step.

I'm using 1.6.0 and it works on Linux, trying to figure out if it could be some kind a video card issue. Yeap need to check if the video driver is open source, proprietary or generic, this could explain some issues. Another thing is checking if a Hybrid graphics that involve an integrated & discrete GPU.

**Comment by flurick** [comment]
Seems fixed :)
