### ISSUE TITLE
Undo History Bug

### ISSUE THREAD

**Issue by infernosblade** [opentoonz/opentoonz#4453]
Using the "column adjustment" tool to move/resize a column etc would bug out the undo history. Pressing undo will undo your action before the column adjustment. Any action made afterwards will no longer register onto the undo history.

**Comment by infernosblade** [comment]
I happened consistently with a particular scene file I had. But a new scene doesnt have the problem.

**Comment by infernosblade** [comment]
i was using the tool in a subscene on one of the column. It seems thats the reason it bugged. It happened to some other subscenes later. The column simply had some raster drawings. I switched over to tahoma2d and things worked fine over there.

**Comment by RodneyBaker** [comment]
Will close as likely resolved but...
@infernosblade Please let us know if you are still experiencing problems.
