### ISSUE TITLE
'alpha rendering' in Bloom lwa FX doesn't seem to work.

### ISSUE THREAD

**Issue by JiniousChoi** [opentoonz/opentoonz#4459]
### Description

As the title gives away, I can't remove the transparent black rectangle, no matter how.
I made sure that the image's background is fully transparent.

### Steps to Reproduce

1. Import a random picture for the background.
2. Now, create a toonz raster level and draw a simple ghost figure with while color. (Don't touch the background so it's transparent)
4. Add bloom-lwa fx to the ghost column in Fx schematic.
5. Open the Bloom lwa Fx property and check on the 'alpha rendering'.
6. And it doesn't work.

### Expected Behavior

I expect the ghost is blooming without any surrounding blackish transparent rectangle.

### Screenshots, Video & Crash Logs

![bugreport](https://user-images.githubusercontent.com/3206725/170610660-4d935d7b-007d-46b0-985e-ff22875ca576.png)
![ghost](https://user-images.githubusercontent.com/3206725/170610664-b9c6a7b1-0b54-460f-9f83-cab39e1ef058.png)

### OpenToonz Version

1.6

### OpenToonz Version Information

OpenToonz 1.6 (built May 4 2022 12:15:42)

### Operating System

Linux

### GPU

Other

### Graphics Tablet

Ugee

**Comment by JiniousChoi** [comment]
FYI, I use arch linux, and installed it with pacman.

**Comment by FerrLui** [comment]
Its because of transparency  fx. Turn transparency off and it will work.
Dont know why its working that way, but...

пт, 27 мая 2022 г., 05:40 Jin Choi ***@***.***>:

**Comment by shun-iwasawa** [comment]
Bloom Iwa Fx had been revised in #3867 and the parameter `Alpha Rendering` is deprecated and is replaced by `Alpha Mode` now.

It seems that the updates either or both of the software / the settings file may not be included in your version.
Can you try [the latest artifacts](https://github.com/opentoonz/opentoonz/actions/runs/2388251322) from the Github Actions and see if the same problem occurs?

**Comment by JiniousChoi** [comment]
@FerrLui I deactivated and checked if the transparency fx had any influence before registering this issue. No luck.
Just now, I deleted the fx and rechecked if it makes any difference. No luck, still.

**Comment by JiniousChoi** [comment]
@shun-iwasawa I'll see what I can and get back to you.

**Comment by JiniousChoi** [comment]
@shun-iwasawa I tried to run the appimage from both artifacts in the link, but I have an issue.

```
$ ./OpenToonz.AppImage 
/tmp/.mount_OpenToeZ9A3j/usr/bin/OpenToonz: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_memdup2
```

I upgraded and my system with 'pacman -Syu' command and then rebooted it, but it is the same.
Any suggestion?

**Comment by shun-iwasawa** [comment]
Sorry I don't have any Linux environment to test with, but according to [this](https://bbs.archlinux.org/viewtopic.php?id=264759) and [this](https://bbs.archlinux32.org/viewtopic.php?id=3066), the error may be resolved by updating glib2.

**Comment by JiniousChoi** [comment]
@shun-iwasawa
Thanks for the posts. I read them.
I have my glib2 updated just now and it doesn't resolve the problem.

And as far as I know, if there is any system-dependant libraries the executable must rely upon, the appimage itself need to contain them so that it fulfills the desired purpose of 'AppImage' - being runnable independently from the underlying OS.

It doesn't seem right downgrading libraries on my system to run an `appimage` file.

Would you check out if the current appimages need any improvement?

**Comment by JiniousChoi** [comment]
@andeon 
```
$ env LD_LIBRARY_PATH=/lib/x86_64-linux-gnu ./OpenToonz.AppImage
/tmp/.mount_OpenTo2GEdQ5/usr/bin/OpenToonz: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: g_memdup2
```
I won't fix it for me.

**Comment by JiniousChoi** [comment]
FYI, at first, I tried to use flatpak version to keep my machine tidy.
But it had a serious bug that I couldn't deal with.
Therefore I am here now with this version of build from Arch User Repository.
And the serious bug is `Opentoonz can't recognize my ffmpeg path, /usr/bin`
It just happened a week ago, in case it helps you any how.

**Comment by andeon** [comment]
For flatpak the path to recognize ffmpeg is 

`/app/bin/`

Ref: https://github.com/opentoonz/opentoonz/issues/4438

Now that you said Arch I think the path from `LD_LIBRARY_PATH` is different for that I know it works to Debian-Based , maybe /usr/lib could worked.

**Comment by JiniousChoi** [comment]
@andeon 
Thanks, '/app/bin/' works in my flatpak version.
Now I can test if I can reproduce my 'alpha rendering' issue on ver 1.5 as well.

@shun-iwasawa 
As you know, I had this alpha rendering issue with `OpenToonz 1.6 (built May 4 2022 12:15:42)` from AUR(Arch User Repository).

For a test, I installed `OpenToonz 1.5 (built Ap 16 2022 14:57:10)` from flatpak.
And here I don't have any alpha rendering issue.

Do you reckon, maybe, some unintended changes were made in the codebase when updating to 1.6?


![bugreport2](https://user-images.githubusercontent.com/3206725/170804420-e220c5dd-7afe-410c-9be1-170d84115760.png)

**Comment by andeon** [comment]
@JiniousChoi  Commit done at [21 Apr 2021] the AUR(Arch User Repository) links correctly the Source code (tar.gz), so I thought about the $HOME/.config/OpenToonz

Can you try to remove this (or backup the .config/OpenToonz first) and reinstall the AUR version and check if the window changes as shun-iwasawa pointed out.

**Comment by JiniousChoi** [comment]
@andeon 
You were right. It was configuration issue.
Thanks. Now it works.
BTW, should I purge my .config/Opentoonz folder whenever I upgrade this program?

**Comment by andeon** [comment]
Discussion about it https://github.com/opentoonz/opentoonz/issues/3903, but it not cover macOS and Linux. The simple answer is yes, but back it up first because preferences, projects or sandbox with scenes, images etc can be stored inside the folder better avoid storing things in there. 

Please close this issue as it has been resolved.
