### ISSUE TITLE
Reframe with "frame handle" change position bottom level/frame

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#446]
For reframe bottom frame to up, you can hold "Ctrl" and drag frame handle to up without change position top level.

![refream-handel-1](https://cloud.githubusercontent.com/assets/16509592/16042514/567a5fba-3250-11e6-9d15-7d5841cb15b5.gif)

But it dont work for top frame and change position bottom level/frame.

![refream-handel-2](https://cloud.githubusercontent.com/assets/16509592/16042518/5ee138d6-3250-11e6-8007-2f8ec74a7dfc.gif)

I think if somebody fix that, it is useful. maybe like this:

![refream-handel-3](https://cloud.githubusercontent.com/assets/16509592/16042522/64854674-3250-11e6-8527-619d8792aff3.gif)

**Comment by blurymind** [comment]
Ooh thats a good point. We still need to preserve the functionality to push the next frames down- when the handle reaches them

**Comment by AyameLee** [comment]
> We still need to preserve the functionality to push the next frames down- when the handle reaches them

**Absolutely.**

**Comment by shun-iwasawa** [comment]
As @2dvision pointed, I implemented the "invert" level extender tab not to insert cells but to overwrite cells in order to avoid disappearing of the previous cells into negative frames by insertion.

What do you think how the level extender tab should behave when you drag UP?
In the third figure of @2dvision 's comment, it seems that empty cells appear when you drag up the  tab. But I think this tab is also useful to shrink frames with pulling up the following cells.

**Comment by animking** [comment]
I think both function required. Filling the gap and extending or shrinking. Maybe with two different key press :)

**Comment by 2dvision** [comment]
TVPaint have "Frame Handle" too. with these you can reframe freely, bottom handle change position other frame but top handle dont that.

![refream-handle-5](https://cloud.githubusercontent.com/assets/16509592/16172422/e6ac080e-359d-11e6-8ee1-8639e7917a1c.gif)


Toon boom harmony and Adobe flash have "F5" shortcut for fill gap between two frame. In Toon boom called "Extended Exposure" and i dont know whats name in flash. 

![refream-handle-4](https://cloud.githubusercontent.com/assets/16509592/16153674/954911be-34bc-11e6-9f81-aca4d7cf640c.gif)

**Comment by blurymind** [comment]
tvpaint's approach is the best one imo :)

**Comment by konero** [comment]
DigiCel FlipBook does it even better, click the frame and type a number on the keyboard, it automatically selects the next frame so you can expose all the frames really fast. In this example, timed to 3-4-8.

![fb_ex](https://cloud.githubusercontent.com/assets/19820721/16180784/4b806d3a-3687-11e6-8c08-6124b0d4c8f6.gif)

Unsure if others can do that, haven't really checked.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
