### ISSUE TITLE
contacting OpenToonz. why when I want to open the file I need, I get an error on the photo attached below???

### ISSUE THREAD

**Issue by LockDown228** [opentoonz/opentoonz#4462]
### Description

I get an error when starting certain projects. presumably this is due to the use of the Plastic tool

### Steps to Reproduce

1. I opened the project
2. started drawing
3. I opened a tab with an error report
when last time it popped up for me, I couldn't even save the project and start all over again because the error report didn't let me save the project

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/106834712/171922795-08b17d3b-b86f-4e32-a1b3-7b9811f21ac1.png)

### OpenToonz Version

1.5

### OpenToonz Version Information

June 03 2022

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Other

**Comment by RodneyBaker** [comment]
@LockDown228 This report lacks vital information needed to reproduce or diagnose the issue.
If you are still experiencing the issue with opening files please let us know.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@LockDown228 please let us know if you are still experiencing problems.
