### ISSUE TITLE
Option for an Xsheet selection to follow the playhead

### ISSUE THREAD

**Issue by deathchimera** [opentoonz/opentoonz#4463]
### Is your feature request related to a problem? Please describe

I try to minimize what needs to be done with a mouse when using shortcuts, and as such, I bind keys to move the playhead to the next and previous frame. When performing actions that need the current frame selected, the point of the shortcuts is kinda negated.

### Describe the solution you'd like

Ideally, there would be four minimum shortcut events, two for moving the playhead while keeping a singular selection wherever the playhead goes, and two more for moving the playhead and making a selection between the inital position and the current position. I feel like this could make shortcuts more useful then they are currently, as manipulation of the xsheet while animating is key.

Another related problem I find often is that there is no shortcut to switch between columns on the xsheet. I imagine implementation would follow the same format.

**Comment by RodneyBaker** [comment]
Thanks for the report.

> Another related problem I find often is that there is no shortcut to switch between columns on the xsheet. I imagine implementation would follow the same format.

Can you provide a little more detail here.
When I read this my mind immediately thinks of the left and right arrow keys being the shortcut to move between columns on the xsheet.  I have to assume that does not fit into what you'd like to see in your solution.

Thanks!

**Comment by GoodbyeGhost** [comment]
Essentially I'm looking for flexibility and maybe some extensibility sprinkled in. It's more for convenience sake then anything, but being able to change the bindings for the arrow keys seems like it could put some pains to rest. Admittedly I kinda forgot about the arrow keys after changing key bindings, but if my solution is adopted, I don't see why column movement could be opened for rebinding alongside it. 

Shortcuts feel like they would see more action if selections could be made easily on the Xsheet, so I want to explore that with this proposal.
