### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#447]
I made a portable version (doesn't need to be installed) of OT for some folks in the Google Group who are teachers and need the ability to set projects on a user by user basis.  Is there any interest in making this part of the releases?  I don't want to create a project that distracts from OT or confuses the users about which version to use, but portable apps sometimes have their advantages.

**Comment by Rayek** [comment]
I think this would be a boon to many users, not only for teaching environments. The capability to run OT off any portable device is very handy in general.

And it would be nice if you would add those great improvements of yours in the portable version - but I understand it would start to be confusing. Perhaps I will start building my own version. ;-)

**Comment by blurymind** [comment]
I agree - a portable version is also good when you need to test nightly
builds. It makes it easier to compare versions of software and find
regressions.
