### ISSUE TITLE
Auto exposition in exposure sheet

### ISSUE THREAD

**Issue by boarderfrance** [opentoonz/opentoonz#4470]
### Ask a question related to OpenToonz

When I import a level of numbered drawings, they do not automatically expose. For example: draw.0001 - draw.0005 - draw.0010, do not fall in front of their number in the exposure sheet. You have to expose them manually. It seems to me that other versions of Toonz did this. Thanks in advance for your help.

![image](https://user-images.githubusercontent.com/31380825/175768773-158a01c5-41bd-4087-995a-310297c1b57b.png)

**Comment by beeheemooth** [comment]
When you load a level into Xsheet, you only load a set of numbered drawings with no exposure. The exposure information is stored in the scene file (tnz). This exposure can be different and does not always depend on the frame numbering. For example, if you use the same frame in different places in one or more columns. In your case, you're using the Numbering System "Xsheet as Animation Sheet" (which I also prefer), so you can use the "Autoexpose" command to position level drawings by Xsheet cell numbers.

**Comment by boarderfrance** [comment]
Many thanks beeheemooth ! It works, it was so simple !
