### ISSUE TITLE
Hide multiple columns/nodes

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#4472]
### Is your feature request related to a problem? Please describe

Having to click on a lot of tiny icons for the nodes are time consuming and sometimes stressfull

### Describe the solution you'd like

select all the columns or nodes and click one button to hide them all from camera view or stage view

**Comment by age3rcm** [comment]
yes, its there
sorry
![image](https://user-images.githubusercontent.com/36406840/176342998-19edd75a-908a-407a-96d2-23735dc0f8e6.png)

**Comment by RodneyBaker** [comment]
Will close as I believe this satisfies the requirement.
