### ISSUE TITLE
undo option not working

### ISSUE THREAD

**Issue by WoolyTheWool** [opentoonz/opentoonz#4473]
### Description

im animating something, and the undo button just isn't working correctly. it undoes an action i did a while ago instead of undoing the last action. 

### Expected Behavior

the undo button should undo the last action

### OpenToonz Version

1.6

### Operating System

macOS

### GPU

Intel

**Comment by RodneyBaker** [comment]
There are a number of Undo issue reports open.
In light of lack of detail for this report, will close for now pending additional information that will suggest a different aspect of Undo problems beyond those reports.

At some point in the future the entire Undo process does need to be scrubbed with a goal to update and improve the system and make it more reliable, predictable and user friendly.
