### ISSUE TITLE
The program does not allow me to export .mov elements

### ISSUE THREAD

**Issue by Small7u7** [opentoonz/opentoonz#4478]
### Description

I just installed the program with all the corresponding components and it does not allow me to export elements of the .mov type but for some reason conventional .mp4 videos do, although it does not allow me to play them

### Steps to Reproduce

1. 
2. 

### Expected Behavior

I would like to be able to export .mov files to animate on them

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by DarrenTAnims** [comment]
To render to MOV you have to have quicktime or a related library. It's not, and can't be, fully built into OpenToonz. Most users I've spoken with prefer MP4 anyway. I assume you've installed ffmpeg, to be able to render to MP4. If it's not rendering properly, try a different version of ffmpeg.

**Comment by RodneyBaker** [comment]
As @DarrenTAnims suggests:

LInk:  https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_win.md#creating-the-files-for-the-srv-folder

You may want to join one of the Opentoonz discords to get realtime assistance in setting up Opentoonz for use with MOV files.
