### ISSUE TITLE
Copy paste mesh on level editor crash

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#4479]
### Description

if you cut the mesh on level editor and paste it the program crashes

### Steps to Reproduce

https://user-images.githubusercontent.com/36406840/178165540-bd8cd629-05a8-41eb-9684-727957534604.mp4

last commands are simply cut=>paste with ctrl x and then ctrl v

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/36406840/178165575-2e0dcd7b-c6ad-4234-bb13-5481e0c54b6c.mp4

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

**Comment by RodneyBaker** [comment]
I had some success using Duplicate but confirm the crash with copy/paste.

**Comment by RodneyBaker** [comment]
Crash log:

[mesh cut paste crash.txt](https://github.com/opentoonz/opentoonz/files/9314711/mesh.cut.paste.crash.txt)

**Comment by justburner** [comment]
Just pressing paste (Ctrl +V) after clicking on the Mesh cell inside Level Strip is enough to reproduce it.

Gotta admit I'm using this one to quickly test the Crash Handler... so if i'm the one doing the fix then it has to wait until that one gets merged first 😅

**Comment by justburner** [comment]
Ops... completely forgot this report... well, better be late than never.
