### ISSUE TITLE
OpenToonz v1.6 Crashing on startup

### ISSUE THREAD

**Issue by ApollyonDraws** [opentoonz/opentoonz#4480]
Upon initially downloading OpenToonz everything worked just fine. I am able to customize my windows, import and export, etc. but when I close OpenToonz and open it back up it after a while i am met with an error saying "OpenToonz is not Responding". If I uninstall, then reinstall it doesn't necessarily fix the issue. The only way I've been able to fix this issue is by deleting the file that is named "OpenToonz.[user's name]" which makes it work and fixes the issue but deleting this file deletes the user's customizations and returns OpenToonz back to it's default settings. Thus, rendering me unable to do anything with my preferences unless I want OpenToonz to crash on startup. 

This has been happening for months now and I have pretty much given up using OpenToonz.  If anyone else has been able to fix this another way I'd love to hear suggestions, I love to animate using Opentoonz but unless this gets fixed, I may have to find an alternative.

**Comment by RodneyBaker** [comment]
If you haven't installed using the latest nightly release I'll recommend giving that a try:

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_4359d4d6d078da494ac900ced61c66e273dbdf94/OpenToonzSetup.exe

I assume use of Windows here.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
