### ISSUE TITLE
Why i can't see my animation in render view?

### ISSUE THREAD

**Issue by Punitron** [opentoonz/opentoonz#4481]
### Ask a question related to OpenToonz

https://user-images.githubusercontent.com/109227745/179272823-2cd678d3-7a95-4f33-a93b-bdb7d2b6cbfa.mp4

**Comment by andeon** [comment]
Apparently your XSheet node doesn't connected to the active output.

Check the Animation or Schematic tab, then the FX Schematic section and connect it. If necessary, click the FX/Stage (schematic) toggle button on the bottom bar of the Schematic panel until the title bar displays FX Schematic.

looks like it:

![image](https://user-images.githubusercontent.com/11843239/179327245-6ddf54a9-ca30-46c0-a432-79405dff834c.png)

About Schematic: https://opentoonz.readthedocs.io/en/latest/interface_overview.html?highlight=Schematic#schematic-1

**Comment by RodneyBaker** [comment]
@Punitron 
Closing this report as this problem appears to be resolved.
Please let us know if that is not the case.
