### ISSUE TITLE
Rename Text Color Bug

### ISSUE THREAD

**Issue by AyameLee** [opentoonz/opentoonz#449]
Not really a bug, but the text in the rename field is unreadable because it is blue.

![tz_rename_bug](https://cloud.githubusercontent.com/assets/18118611/16085385/cee924ea-3313-11e6-8d0b-8864df0f4347.PNG)

Version 1.0.3 Stable

**Comment by skitaoka** [comment]
This bug is fixed by https://github.com/opentoonz/opentoonz/pull/458.
