### ISSUE TITLE
Audio immediately crashes on windows 10

### ISSUE THREAD

**Issue by Animatical** [opentoonz/opentoonz#4490]
### Description

I've noticed that on both the release version and the nightly version, adding audio to the timeline and scrubbing/playing it will crash the program without any error message. The audio is the correct bit rate and is WAV.

### Steps to Reproduce

1. Drag audio onto the timeline
2. Scrub or play the audio in any way
3. Crash

### Expected Behavior

It's supposed to be able to scrub and play the audio without crashing.

### Screenshots, Video & Crash Logs

I found this in the windows event viewer:
Faulting application name: OpenToonz.exe, version: 0.0.0.0, time stamp: 0x62e2a79b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1741, time stamp: 0xe9b4a91b
Exception code: 0xe06d7363
Fault offset: 0x0000000000034fd9
Faulting process id: 0x4fd8
Faulting application start time: 0x01d8a2c882d9b829
Faulting application path: C:\Users\LB157370\Downloads\OpenToonz\OpenToonz.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8ff4f6ca-87db-4075-828f-fd002a921d8f
Faulting package full name: 
Faulting package-relative application ID: 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
I was recently reading a post where hardware was reportedly related to audip scrubbing problems.
Perhaps this might even have been a post by you (on discord) @Animatical ?

One thing that makes this hard to diagnose is that others can't seem to reproduce the problem.
If you haven't joined an Opentoonz discord I'll recommend that in order to recieve real time feedback and ultimately resolve the problem.

If you do discover the source of the problem please let us know as others will surely appreciate it if it also addresses their problems.

**Comment by Animatical** [comment]
Yeah I was on the discord with this probem too, but it didn't really get anywhere in the end. It **MAY** be a driver issue, but I haven't been able to prove that. The only "fix" I seem to be able to find is to disable all audio outputs in the settings, but then obviously I can't hear anything. I don't know how to give any more info than I already have, so I guess here's a video showing the problem

https://user-images.githubusercontent.com/64507221/181809500-9761a7e3-92fd-4439-b714-cc76e29a81cf.mp4

**Comment by RodneyBaker** [comment]
Can you share an audio file that doesn't work for you?
(It is my understanding that no audio files will work for you but at least we can rule that out)

Short of that it would be good know as much as we can about the audio being used... even filename.

**Comment by Animatical** [comment]
sent audio in discord since github doesn't accept WAVs

**Comment by Animatical** [comment]
Update for any spectators: when he tested it, it worked fine for him. We tried different things like running the installer as admin and making a portable version of OT but none have worked so far. Will continue to test around

**Comment by Animatical** [comment]
It seems to work when I try it on a different computer, (as expected) but I can't keep borrowing other people's computers lol

**Comment by Animatical** [comment]
Opentoonz log, day 2..
My supplies are enough to last a couple more weeks but I don't know how much longer I can go without being able to play audio... I came across a native american village but nobody there knew how to fix the problem either, however they did crown me as their new chief. After doing some digging, some of the village people discovered that the MOV can still be exported and play audio as long as it isn't through the mini player that appears in OpenToonz

**Comment by Animatical** [comment]
Opentoonz log, day 3.
I died... BUT THEN I LIVED, only to find out that it still doesn't play audio

**Comment by Animatical** [comment]
GOOD NEWS: The problem has been fixed.
BAD NEWS: I don't know what the fix was.
It was one of two things: either the computer restore to Feb 2022, or the /sfc SCANNOW I did in CMD. I was reading that the SCANNOW was a fix to the kernelbase.dll bug, so it's more likely that. However don't close this just yet since I'm re-updating my drivers, and it may bug out again in that time. Once I'm certain that everything is fixed, I'll close it
thanks all :)

**Comment by Animatical** [comment]
Issue seems to be solved for me, I've re-installed all missing programs and drivers and it seems to still work!
If anyone else ever has this issue, open CMD as an admin and type "sfc /scannow" then restart your computer. If that doesn't work, then (if you can) restore your computer to an earlier date like 6 months prior for example.

Thanks for all the help, glad I can use opentoonz again :D

**Comment by Animatical** [comment]
It came back, the only thing that changed is I updated drivers. I already tested the main display drivers, so one of these is messing with opentoonz:
- Java runtime environment 32 bit
- Intel Management Engine Interface
Does Opentoonz happen to use java? if so that would explain it

**Comment by Animatical** [comment]
I tried replacing all of them but it doesn't seem to work, strange-

**Comment by Animatical** [comment]
Bump

**Comment by Animatical** [comment]
Update for github viewers of this issue: We think it may have been a registry cleaner that wiped some "unused" registries that were important for opentoonz, so I restored my computer to an earlier date to see if not using any registry cleaners solves the issue.

**Comment by RodneyBaker** [comment]
@Animatical It almost reads as your problem is resolved.
Can you confirm?

**Comment by Animatical** [comment]
Yup, I was giving it time before I declare it closed but I think a month is good enough.

In conclusion to future people having this issue, don't use registry cleaners like CCleaner or Razer game boost cleaner
