### ISSUE TITLE
Frame bar Disappearance + Unsafe video file

### ISSUE THREAD

**Issue by Guestforfun** [opentoonz/opentoonz#4492]
### Description

So opentoonz so far has been great and all but first i wanted to make a test and figure out how to get a youtube free file and after a long time of trying i came to the solution to screen record but i wanted to lower the bars on the bottoms and side which resulted into me accidentally deleting the bar showing the frames at the bottom, i tried reinstalling but it just wouldn't work.

### Steps to Reproduce

1. Make youtube friendly files?
2. Make a invisible frame button

### Expected Behavior

I expected there to be a warning or some sort of when you accidentally delete a bar,

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/110273543/181871769-9b17bc92-f465-416a-a0c0-c2545ff7364f.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

**Comment by RodneyBaker** [comment]
@Guestforfun Recommend joining a Opentoonz discord where you can work out your process and get tailored instructions on resetting your user interface.

**Comment by DarrenTAnims** [comment]
Resetting the layout from the Windows menu should restore all of your panels.
Re-installing doesn't affect the layout as the layout is stored in files in your C:\OpenToonz Stuff folder. So to fully reset, you'd have to delete or rename that folder before installing, to get a clean install.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Guestforfun please let us know if you are experiencing any  additional problems.
