### ISSUE TITLE
Ease in/Ease Out not working. Why is it happening and what's the fix?

### ISSUE THREAD

**Issue by H-Helio** [opentoonz/opentoonz#4493]
### Ask a question related to OpenToonz

I have selected ease in/ease out for the animate tool in order to get smooth camera movement, but it's still linear. I can't change this in the function editor either, as it is greyed out. What is causing this? How can I fix this?

**Comment by H-Helio** [comment]
correction, I meant that it's still constant.

**Comment by RodneyBaker** [comment]
If you go into Preferences, on the Animation tab...
What is that option set at?

![image](https://user-images.githubusercontent.com/2576432/182245305-1d410614-aeea-4bc9-a277-8ee5fa186d66.png)

**Comment by RodneyBaker** [comment]
@H-Helio Are you still troubleshooting your issue with Ease in/out?

**Comment by RodneyBaker** [comment]
Closing but please feel free to ask additiona questions as needed @H-Helio 
Ease in/out works but if you are having problems with it then that certainly is an indicator that it can work better.
