### ISSUE TITLE
Bug: crashing after creating a new level in OS X (v. 1.0.3)

### ISSUE THREAD

**Issue by Dragularos** [opentoonz/opentoonz#450]
When you create a new level without having a folder called "drawings" in your destination folder, OT 1.0.3 tries to create a folder called "drawings" (after asking to do so) but than the prog crashes. 

This bug was present in version 1.0.2 too

Maybe you can look into it.

Thanx, Phil

**Comment by artisteacher** [comment]
I'm not experiencing a crash with 10.12.4 and the recent nightly builds.

**Comment by turtletooth** [comment]
@Dragularos If this is still an issue, we can reopen it.
