### ISSUE TITLE
Can we consider replacing libtiff with a rust library called image-tiff?

### ISSUE THREAD

**Issue by jointri** [opentoonz/opentoonz#4505]
### Is your feature request related to a problem? Please describe

Libtiff needs to be replaced. In the scenario where it's too much work to upgrade it or backport patches, can we use this rust library instead for tiff encoding and decoding? It's licensed under the MIT license, perfect for opentoonz.

https://github.com/image-rs/image-tiff

### Describe the solution you'd like

I would like to see libtiff be replaced with something else and I am proposing using image-tiff as a replacement that's licensed under the MIT license.

**Comment by RodneyBaker** [comment]
There might be more success convincing a developer to create a fork of Opentoonz that uses (and demonstrates) the various benefits of image-rs libraries that are all in rust.  REF:  https://github.com/image-rs

What success might look like could begin as a subset of Opentoonz that focuses not on drawing but on file handling, image viewing. and conversion.  Once successful the main Opentoonz code could then update to that code base.

You don't mention any specific reasons why a move to image-tiff would be more advantageous than some other change but your previous requests related to TIFF libraries do cover some of that territory.  For those that aren't as familiar it might be good to eliminate guesswork.  REF:  #4193 #3968

**Comment by jointri** [comment]
@RodneyBaker There will be sometime soon an update for Tahoma2D updating libtiff from 4.0.3 to 4.2.0. This issue is no longer necessary since updating the library now and again is going to happen. Whatever changes T2D makes can be ported to OpenToonz.

**Comment by RodneyBaker** [comment]
I have been following you and John's progress via the Tahoma2D discord and appreciate all the effort going into modernizing libtiff.  Once we get to that stage the only concern seems to be one of validation and porting. :)
