### ISSUE TITLE
Cannot create a new scene.

### ISSUE THREAD

**Issue by CoreyWarren** [opentoonz/opentoonz#4509]
### Description

This is my fourth scene in the default 'sandbox' project. At no point did I intend to create a new folder, as the folder I wanted already existed. However, that did not stop OpenToonz from giving me problems. I've quit out of the program and started it again, but to no avail.

### Steps to Reproduce

1. Attempt to create a new scene in some pre-existing subfolder within the sandbox project directory. (using the '...' button in the 'OpenToonz Startup' prompt at startup.
2. Select that folder with the 'Choose' button in the 'Choose Folder' prompt.
3. Name could anything here, does not seem to affect upcoming results. Camera Size is '...', Frame Rate is '24', canvas is 16" by 9", or 1920px by 1080px. 'Save In' field reads '+scenes'. Same results as when 'Save In' field reads '+scenes\example'.
4. Press 'Create Scene.'
5. You will get the prompt saying "The chosen folder path does not exist. Do you want to create it?"
6. Click the 'Create' button.
7. Last prompt is an "OpenToonz 1.6 - Warning' prompt. Reads 'Failed to create the folder." 
8. Press "OK" and accept fate.
9. This bug occurs ad infinitum.
![opentoonz bug folder](https://user-images.githubusercontent.com/46623610/186025955-f171309d-eb5c-43af-993a-0bcd88b21fc6.png)

### Expected Behavior

1st of all, there was no folder to create. So the 'create folder?' prompt should not have even shown up.
2nd of all, despite all of that, the attempt to simply create a scene within a pre-existing folder failed.

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

**Comment by CoreyWarren** [comment]
One thing of note as well:
I am still, fortunately, able to start a new scene, as OpenToonz 1.6 also seems to have created a scene for me upon startup, which I can actually edit, and subsequently save in my intended destination folder. It saves without incident. This is the workaround I will use until I can start a new scene in its intended destination folder via the startup prompt.

In essence, this problem may be local to just the startup prompt, and not a global file-saving system bug. Fingers crossed?

**Comment by DarrenTAnims** [comment]
I wouldn't try to create a scene in a subfolder of the Scenes folder. I'd expect that to go wrong. OpenToonz expects scenes to be in the scenes folder for the project. The folder structure is quite strict.

**Comment by RodneyBaker** [comment]
Closing as likey resolved and/or abandoned.
@CoreyWarren Please let us know if you are still having problems creating new scenes.
