### ISSUE TITLE
Ancient: Drawing substitution

### ISSUE THREAD

**Issue by Marandal-l** [opentoonz/opentoonz#4513]
### Description

In Opentoonz 1.1, Drawing substitution
worked far below the exposed Cell's. (no longer possible with newer versions)

used the feature to make my 3rd, 4th & 5th cartoons on YT.
Was too lazy to make a bug report on Github untill now.(4 years later)

### Screenshots, Video & Crash Logs

![unknown](https://user-images.githubusercontent.com/35547019/186600591-a31fdcd6-40eb-48ca-a3dc-7492af6dcf46.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

Mouse

**Comment by RodneyBaker** [comment]
Thanks for the report.

Some other users mentioned this some time ago and at that time I was curious about it as that seemed 1) Useful 2) Potentially problematic with some workflows.

Given you say the process worked in v1.1, I wonder if the loss of functionality wasn't introduced with #410.

**Comment by Marandal-l** [comment]
i re-downloaded the github OT 1.0 to 1.2.1 and couldn't reproduce it.

If memory serves(and i can be mis-remembering); The function dissapeared after installing 1.3

immediately after installing 1.3, i reverted to older versions and the strange function no longer worked.
Wonder if i was using a bug to my advantage.

**Comment by gab3d** [comment]
Sorry, I don't fully understand what is that is not working just from looking at the screenshot.
Is it using the Q and W shortcuts to expose drawings past the end of a level?

How would that work if there is more than one level in a layer/column?

**Comment by Bracket-H** [comment]
I also don't really understand this, and from first glance this seems like something I would think would be a bug, if it happened to me.

But then again, I already find the substitution to be iffy to deal with to begin with. (I'd like it to substitute the entire held duration but I think that needs a hotkey by default...which is ok to remap but I think changing the entire hold should be the default instead ...bt that's just my opinion)

**Comment by gab3d** [comment]
@Bracket-H 
both options have default shortcuts assigned,
what you want is done with [Alt + Q / W]

**Comment by Marandal-l** [comment]
>  Is it using the Q and W shortcuts to expose drawings past the end of a level?
That's how it worked yes.

**Comment by RodneyBaker** [comment]
@Marandal-l  In reinstalling Opentoonz v1.1 I am unable to get the results you suggest use to be the norm for drawing substitution.  Any additional information you can provide will be useful if we wish to revert to a feature that is no longer available.

**Comment by RodneyBaker** [comment]
Closing pending additional information to allow a path forward.
