### ISSUE TITLE
Focus on Current doesn't work in FX Schematic

### ISSUE THREAD

**Issue by Marandal-l** [opentoonz/opentoonz#4514]
### Description

Focus on Current doesn't work in FX Schematic.

This feature works in Version 1.3 and lower
(another bug i was too lazy to report on github for 2 years)

### Steps to Reproduce

1.Select Column in timeline
2.Select Focus on Current

### Expected Behavior

Should Focus on Current

### Screenshots, Video & Crash Logs

![Untitled](https://user-images.githubusercontent.com/35547019/186603628-8020ffda-9e86-47fe-9d3f-864eb4272123.png)

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

Works in 1.3 and lower

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

Mouse

**Comment by RodneyBaker** [comment]
I'll have to go back to v1.3 and before to test what might be different but in my initial testing of selecting both cell and column (in Xsheet) as well as node (in Schematic) the focus does shift the selection to the center of the Schematic window.

The one thing that doesn't work as I would expect would be selecting multiple columns or nodes and have the focus go to the middle of the selection  I don't think that worked in earlier releases either however.

Perhaps someone else can reproduce the problem on their system.

**Comment by Marandal-l** [comment]
`focus does shift the selection to the center of the Schematic `
The Stage Schematic Yes: Focuses on Current.
The FX Schematic where Special Effects are added; Doesn't.

Hope this helps!

**Comment by RodneyBaker** [comment]
This now appears to work (for me) in both stage and FX schematics.
Perhaps it may have been fixed as a side effect by #4567?  Not sure. 
@Marandal-l, can you confirm?
