### ISSUE TITLE
Save level fails with selection tool (via command bar)

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4517]
### Description

Saving a level via the "save level" command from the command bar fails with the selection tool. Sometimes i have a crash. It seems working normaly with brush instead of selection tool.

### Steps to Reproduce

1. Create a vector level  with a drawing
2. Clone it (cells -->clone cells) and delete part of it
3. Save both levels (command bar)
4. Use selection tool and copy a stroke from the original
5. Paste the stroke to the clone
6. Save level (command bar)
7. restart OT
8. Save fails whitout warning

### Expected Behavior

No fail

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/29790512/187011374-6950a576-6d5a-4f3e-88fb-cdd9ca131cac.mp4

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Last build 25 08 2022

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themselves.
Note that there may be useful information contained in this report and where appropriate that information should be captured in a new report.
