### ISSUE TITLE
Stop Motion/Camera Capture.

### ISSUE THREAD

**Issue by Tragustauro** [opentoonz/opentoonz#4520]
### Ask a question related to OpenToonz

Hello.

I have a question in regards to the 

1: StopMotion function(Ability)
and
2: Camera Capture function (Ability)

Is see there is two different "places" to "shoot" stopmotion/Lintestdrawings(Paper)

In:
Stop Motion my dslr camera is detected.
In: Camera Capture my dslr camera is not detected!?? Why is that?

Once working with down shooting a amount of paper drawings I seem not to have the ability to render "Levels" (a few levels) out. 
But only one  selected level.
And how come OT is detecting my dslr cam in Stop Motion and not in Camera Capture mode? 
Is there any place online with an extensive knowledge base on this issue?  

Any feedback is appreciated. :)
T.

**Comment by RodneyBaker** [comment]
The stop motion feature is a later addition that specifically was being tailored for stop motion.
The Camera Capture feature is used primarily as a line test tool.

There are some crossovers in features but the Stop mo feature was specifically added to take avantage of Canon DSLR SDK which isn't a part of the Camera Capture feature.

The most extensive information on each of these is likely to be found in the PRs where the features (and updates) were added.

**Comment by Tragustauro** [comment]
Hello.
Aha. I see....

My question is now this.

Why does that make sense? To have two different "tools" almost doing the same thing?

Sorry for my ignorance but would´nt it be Cool to have just one place where to work from in regards to Pencil linetesting 
or Stopmotion work . I mean open one "workspace" and select what one is needed?

"The Camera Capture feature is used primarily as a line test tool." But it does not support with dslr cams?

Thou I found Tahoma 2D quiet unstable I will have a go at it. 
I have used it for a while now with a webcam but I wanted to go with my dslr cam for better resolution. 

One more question: 

Is it, as is, possible to capture a linetest (paper) in "stop motion function" and render out more than one layer? without exposing the paper drawings in 50%opacity to see the underlying drawing?

Or is this only in "Camera Capture mode"? (with no dslr ability) 

I did not have the change to explore this base on my unawareness of the Camera Capture function mode.

Thanks 4 all ur work. It is much appreciated.

T.

**Comment by RodneyBaker** [comment]
It's somewhat the nature of open source development for things to not always make sense... although there is sense there if we know where to look for it.

A little (abreviated) background:
The developer of the additional stop motion feature* had a specific goal in mind but later left entirely.
That development tends to get updates by the developer that took over the Tahoma2D fork.
The original camera capture then is updated by the same person who supports it for use by studios etc.

I'm not quite sure what you mean by 'render out more than one layer'.

If you want to update the stop motion feature set you probably should query John (@manongjohn) of Tahoma2D as he's likely most familiar with that code.  

If wanting to update the camera capture feature @shun-iwasawa is the likely one to consider that feature request.

*Jeremy is responsible for much of Opentoonz development over the past years so nothing but praise for his efforts from me here.  He is certainly missed.

**Comment by Tragustauro** [comment]
Hello.

It makes sense once you know the background of the software. Thank you.

I'm not quite sure what you mean by 'render out more than one layer'.:..


Well... in stop motion all elements are right there to "Shoot". But in traditional 2d linetest you need to "shoot" each frame (Paper) and drawing. So ie:

Layer 1: = Background drawing
Layer2: = Animated character

and so forth...

Before exporting MoV/Mp4 this, usually you  look at the timing and placement and so forth.

In doing this in "Stopmotion" mode. I lover the opacity on the "Character" level to approx 45-50% so that makes the background appear. Now I can see if everything (Both layers) line up correct.

Now I want to render out/Exporting this linetest as a mov or a mp4. 

I then, only get one of the layers showing in the exported mov/mp4 file.( Iguess the selcted layer)

 Is it not possible to merge layers in the final output, in "stopmotion" mode?
And is this only possible in camera capture mode? Am I not aware of any "clickselect or unclickselect" button?

I did have contact with @manongjohn in regards to camera crash in Tahoma 2d. And He seems to have fixed this issue. Personally I fell Tahoma  2d is more unstable than OT.

I wanted to replace my webcam to my dslr to "shoot" my linetest for a clearer and nicer image. And I found out (A little late) about the cameracapture mode. 

But I realize it is not supporting dslr cam. Thats why I got confused.  

So at this moment it is either stopmotion mode with out the possiblity to merge layers or it is web cam in Cameracapture mode ..

Personally I appreciate all the works being done on T2 and OT.

Thanks again for all your works. 
T.


 I am running Win7 pro (Still)

**Comment by RodneyBaker** [comment]
When you say you lower the opacity of the character layer... I assume you mean the column's opacity here.

There is an option that is required to be turned on in order to get the column tint and opacity to appear in final rendering.  Somewhat unfortunately this option is per scene and off by default so it often needs to be turned on manually to take advantage of column tint/transparency.  Perhaps some day we can get it added into the Render dialogue but I tend to agree that it probably best off by default to allow for image transparency (for compositing etc.).

To turn the option on go to Xsheet > Scene Settings and look for the option at the bottom:

![image](https://user-images.githubusercontent.com/2576432/187092912-c68438b9-6941-43a0-9f4e-080a587bcf40.png)

**Comment by Tragustauro** [comment]
Hello RodneyBaker.
Thanks alot.
Yes I agree with you. Simplicity does it. :)


Oldschool 2danimation use to function like this.

Lowest "level" in connection to the downshoot camera is:

BG level.
Level01
Level02 
Level03
and so forth.....

So... You "shoot" a frame/Picture of your BG level and "on top" of that level you usually shoot /Take a picture of your "character level" or what ever you have planned out...

The "character level" usually consist of a character drawn with line art and then colored in.
The whole area around the character usually is transparent so you see the BG Level thru.

The only way I seem to replicate this (in Stopmotion mode) is by lowering the opacity on the desired level/Drawing, so I can see if the "character" is placed in the right spot after drawing it.(It usually is, unless you draw with out paying attention).

By the way it is mindboggeling to me why in one menu dslr is working fine and in another it is not!!??
 But I guess it comes out of the way OT is programmed. Opensoftware.....

So after viewing your "linetest" and accepting what you see you want to export this to put it into your animatic to see if there is an acceptable flow in your film/Movie. 

This is where the "issue" occurs. I do not seem to be able or know how to export this linetest as I see it in the "preview" in OT.
And it is also kind of a bummer not to be able to turn on or off a layer in preview mode in stead of lowering the opacity on the layer above.. 

I attached a "drawing of what I mean. I hope it makes sense.

I apologize if I have not been aware of functions that actually do what I look for. But as you mentioned yourself some things are not in the open and you have to look for it to know.

Thanks again.
[T.](![pic001](https://user-images.githubusercontent.com/97757066/187444236-e166bdc7-33f4-4d45-a3c2-f71c2fd520ca.jpg))

**Comment by RodneyBaker** [comment]
There is an option in Output Settings called Mutiple Rendering (way down at the bottom) that allows to render out each column separately for later compositing.

Also in latest nightly releases there is an option File > Export > Export to OCA that will render the columns out separately as well.

**Comment by Tragustauro** [comment]
Hey Ok I see. 

Thanx.

So if I wanted the opposite of your suggestion. 

Like Rendering out "Not" separatly? But All colums mixed?

If I have 3 colums and I want to render out these all visible in one video?
T.

**Comment by RodneyBaker** [comment]
Just render normally as that will compost everything in each of the frames.

**Comment by Tragustauro** [comment]
hmm ok i try.

thanx
T.
