### ISSUE TITLE
Download Opentoonz manual

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#4524]
### Is your feature request related to a problem? Please describe

![image](https://user-images.githubusercontent.com/36406840/188278432-aceb7f5c-051d-4dbf-95bb-60a15ad70332.png)
it seems that kdenlive opensource project manual can be downloaded, why not opentoonz?

### Describe the solution you'd like

download the docs! some people might not have internet on work pc

**Comment by konero** [comment]
If you scroll to the bottom you can click the `v: latest` drop down and find downloadable versions, is this what you mean?

![image](https://user-images.githubusercontent.com/19820721/188283001-8f712100-b00e-45fe-b459-e941c27f5625.png)

https://readthedocs.org/projects/opentoonz/downloads/

**Comment by age3rcm** [comment]
ugh, a little hidden to say myself
tried downloading the page via browser before, but i did not work
