### ISSUE TITLE
Pen On 2 monitors issue

### ISSUE THREAD

**Issue by BATTUK-EGROEG** [opentoonz/opentoonz#4528]
### Description

So the pen and tablet I use work great on any other software but for opentoonz it causes the pen to act on my other monitor (instead of on the drawing tablet) as far as I can tell there are no fixes. (on clip studio paint this was fixed by simply switching to wintab in preferences if that helps) my tablet is a bosto

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Other

**Comment by RodneyBaker** [comment]
Hi @BATTUK-EGROEG 
There are a number of things users do to work around issues tith multiple monitors.
For example:

- Making the problematic monitor be the main monitor
- Duplicating monitors vs extending the monitors accross screeens
- Other things that don't immediately come to mind although... typical things like updating drivers, turning on (or off!) Windows Ink (on Windows), adjusting resolution to make sure both monitors resolutions match, etc.

As you appear to be on Windows you might start by making sure Windows Ink is off both in Windows and in Opentoonz preferences.

**Comment by BATTUK-EGROEG** [comment]
Thanks
