### ISSUE TITLE
How to change DPI

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz#4529]
### Ask a question related to OpenToonz

Hello, i want to know if trhere is way to change dpi in OpenToonz, Now it is 120 but i want something like 300.

+  I cant change DPI for camera too(((

**Comment by RodneyBaker** [comment]
Look on the Drawing tab in Preferences for the main DPI setting.

Right Click on a level and select Level Settings to view the level's DPI (the same thing is there when creating a new level)

Under the menu Xsheet > Camera Settings you can set the DPI for the camera.

**Comment by FerrLui** [comment]
@RodneyBaker 
 Not working 

 I cant change the dpi ((

 Here is a video https://youtu.be/SzIKnVLJFfE

**Comment by FerrLui** [comment]
![Снимок](https://user-images.githubusercontent.com/42417604/189538723-1529b321-afaa-4222-8e87-4c21fe28aac7.PNG)
 Version of my Opentoonz

**Comment by RodneyBaker** [comment]
I'll guess you have your settings in Preferences set to disallow changing of DPI:

![image](https://user-images.githubusercontent.com/2576432/189547826-00b37cdd-02be-46eb-a49b-15c7670f4d91.png)

Use a setting other than pixels as the unit.

**Comment by RodneyBaker** [comment]
@FerrLui Have you been able to change DPI yet?

As a side note... some image formats do not store DPI settings so that is good to keep in mind.
REF:  #1935

**Comment by FerrLui** [comment]
@RodneyBaker  Ah, yes. Thank you very much. Simply change pixels to mm and it works.
 Thank you🤩🤩
