### ISSUE TITLE
[request] Please make mousewheel (when hovering over the timeline/xsheet) zoom in/out the x-sheet timeline

### ISSUE THREAD

**Issue by bencresty** [opentoonz/opentoonz#4539]
### Describe the solution you'd like

Please see title. It's very tedius to need to zoom in and out with the small slider on the bottom of the timeline/xsheet window.
In many timeline software there's therefor a faster way to zoom in/out the timeline, like mousewheel, when hovering over the timeline/x-sheet panel.
That would be a lot less time consuming and way nicer to work with IMO!

**Comment by openanim** [comment]
Maybe 2 workarounds :

1. ctrl+mousewheel anywhere on timeline / xsheet (in xsheet mode the zoom stops on the path if we dont hovering the slider, unfortunately)

2. If you have a wacom pen and tablet you can for example assign the command "déplacer/zoomer" (probably pan/zoom in english) to a button on your pen. This is very fast to zoom in/out or pan in the applications. You need to click+drag on timeline.


![pan zoom](https://user-images.githubusercontent.com/29790512/190939919-55769b82-6c61-4e41-858e-baad05febb12.gif)


<img width="770" alt="pan zoom" src="https://user-images.githubusercontent.com/29790512/190939827-e23a8114-8cf8-456c-a666-2c7306131632.png">

**Comment by bencresty** [comment]
> Maybe 2 workarounds :

Thanks a lot for your response! Those methods are great! Closing this!
