### ISSUE TITLE
OpenToonz Crashes Immediately on Start Up (Mac) - Help?

### ISSUE THREAD

**Issue by EdenRye** [opentoonz/opentoonz#4555]
### Ask a question related to OpenToonz

Hello! I recently downloaded OpenToonz and every time I try to open it, it says that it crashed unexpectedly. I have the necessary software requirements for it to download and run efficiently; and I already tried uninstalling/reinstalling and restarting my whole computer. I've only seen resources on how to fix in on Windows but I can't seem to find any resources pertaining to Mac if it runs into this issue - any suggestions???

**Comment by artisteacher** [comment]
Are you trying to open an existing scene, or does it crash immediately on open?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@EdenRye If you are still experiencing problems please let us know.
