### ISSUE TITLE
New layer resolution setting dropdown menu

### ISSUE THREAD

**Issue by HatWearingMann** [opentoonz/opentoonz#4558]
### Is your feature request related to a problem? Please describe

When changing the camera settings, the "new layer" menu doesn't default to the new canvas resolution.

![obraz](https://user-images.githubusercontent.com/79970290/194774567-8f78440d-be9a-44f2-8add-a6d10b004e6c.png)

### Describe the solution you'd like

I'd like to have a resolution dropdown menu in the "new layer" window, in a similar manner to how the "camera settings" does, so I don't have to type it in manually each time I add a layer.

![obraz](https://user-images.githubusercontent.com/79970290/194774569-f0c2912d-b279-4277-908a-deb0f5ae047b.png)

**Comment by DarrenTAnims** [comment]
If you want your new levels to default to the camera resolution, tick the option in the Preferences dialog, on the Drawing tab.

**Comment by HatWearingMann** [comment]
Oh, sorry then, thanks!
