### ISSUE TITLE
opentoonz nightly crash

### ISSUE THREAD

**Issue by age3rcm** [opentoonz/opentoonz#4564]
### Description

i try to click and edit vector points with "auto-select drawing" enabled and when i click a point in another level its a Insta-crash everytime
[MLP-FIM_Mare V7_2.zip](https://github.com/opentoonz/opentoonz/files/9802960/MLP-FIM_Mare.V7_2.zip)

### Steps to Reproduce

1. open scene
2. click to edit control points of vectors
3crash
[crash.zip](https://github.com/opentoonz/opentoonz/files/9802972/crash.zip)

### Screenshots, Video & Crash Logs

[crash.zip](https://github.com/opentoonz/opentoonz/files/9802974/crash.zip)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Built 16/10/2022

### Operating System

Windows

### GPU

NVIDIA

**Comment by RodneyBaker** [comment]
At a guess I'll say this might relate to codecs installed on your system.
That is just from a quick glance at the crash report however so... not sure.

The crash report states "OpenToonz 1.6  (Build Aug 22 2022)" so I'm not sure what is going on there as I see from your post you are using the nightly from yesterday.

**Comment by RodneyBaker** [comment]
As I cannot reproduce the crash...

@age3rcm Can you confirm the same result using the latest nightly release?

@ OthersWillingToTest Can you confirm a crash?

**Comment by age3rcm** [comment]
it stopped crashing!
but maybe it got sightly harder to select a drawing from another column...

what was it that produced crashes?
