### ISSUE TITLE
"Draw under" for Geometric tool option

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz#4571]
### Is your feature request related to a problem? Please describe

 Hello, We often use geometric tool (in toonz smart layer), but it is not very comfortable tool, because its not have draw order us brush tool. 

### Describe the solution you'd like

 Please, can you add "Draw under " function for geometric tool, if its possible.
 And, thank you guys for making Opentoonz such a good and amazing programm for us, love you.

**Comment by konero** [comment]
Already requested here #3693.

**Comment by RodneyBaker** [comment]
Agreed.   Will close this as a duplicate request.
@FerrLui please feel free to add details that will further differentiate this request from that of #3693 either here or in that request.
