### ISSUE TITLE
OpenToonz it closes suddenly

### ISSUE THREAD

**Issue by CarlosBarrazaE** [opentoonz/opentoonz#4580]
### Description

It closes many times, I don't know if it's my computer or how to compile it, but running in terminal I found these:

I think it happened when drawing (it is the most common of all):
OpenToonz: /var/tmp/portage/media-gfx/opentoonz-1.6.0/work/opentoonz-1.6.0/toonz/sources/toonz/xshcolumnviewer.cpp:2326: virtual void XsheetGUI::ColumnArea::mousePressEvent(QMouseEvent*): La declaración `getDragTool() == 0' no se cumple.
Abortado

On undo:
OpenToonz: /var/tmp/portage/media-gfx/opentoonz-1.6.0/work/opentoonz-1.6.0/toonz/sources/tnztools/toolutils.cpp:1004: virtual void ToolUtils::UndoModifyListStroke::undo() const: La declaración `reg' no se cumple.
Abortado

I don't remember what I was doing
OpenToonz: /var/tmp/portage/media-gfx/opentoonz-1.6.0/work/opentoonz-1.6.0/toonz/sources/tnztools/toolutils.cpp:1095: virtual void ToolUtils::UndoPencil::undo() const: La declaración `reg' no se cumple.
Abortado

### Steps to Reproduce

I have tried to reproduce it without success, it happens when it occurs to it.

### Expected Behavior

Not to close

### OpenToonz Version

1.6

### OpenToonz Version Information

1.6.0 built by me

### Operating System

Gentoo Linux

### GPU

NVIDIA

**Comment by RodneyBaker** [comment]
Hi @CarlosBarrazaE 
Sorry to hear you are experiencing problems.

You didn't mention what flavor of Linux you are using although I see you are building your own release.
If Ubuntu compatible you might try one of the Linux github action builds found here (at the very bottom):

https://github.com/opentoonz/opentoonz/actions/runs/3340364966#artifacts

What I'm suggesting is to isolate the problem a little more to determine if your local build is more problematic than other options.  That might then help discover the issue with your personal build.

**Comment by CarlosBarrazaE** [comment]
I discovered a problem with the RAM memory, it is possible that it is not an opentoonz problem, sorry. is it possible to disable asserts?

**Comment by justburner** [comment]
Avoid using "Debug" target for production, it should only be used for debugging the program.
The best way to disable asserts is to not use "Debug" target.

**Comment by flurick** [comment]
Could be closed.
