### ISSUE TITLE
Probablems installing on Mac

### ISSUE THREAD

**Issue by 5v34734** [opentoonz/opentoonz#4582]
### Ask a question related to OpenToonz

After I update the operating system in my Mac, Open Toonz completely crashes. Downloading and trying to unpack a new pkg file doesn't help; the computer just considers the file as corrupt. What am I doing now?

**Comment by artisteacher** [comment]
Make sure you right-click to open the pkg - the second time you'll get an option to open anyways or something to that effect.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@5v34734 If you are still having problems installing Opentoonz please let us know.
