### ISSUE TITLE
Crash loading column icons for sub-xsheet with pegbars  in 1.0.3

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#459]
The tool crashes when I try to Load scene and there is an Xsheet pane in the room.   I'm trying to load a scene I was working on in 1.0.2 and it consistently crashes.  Attached as a .txt file

It does not happen when there is no Xsheet pane in the room, like the "Drawing" room, but when I try to open the Xsheet window after successfully loading the scene, it crashes.

Not sure what in the scene is causing it, so it's hard for me to help pinpoint what might be causing it.  I tried to create new scenes, save and load with similar items to what I was trying to load but can't reproduce the crash.

If you need additional information or need me to try something, please let me know.

[LJ_walk.tnz.txt](https://github.com/opentoonz/opentoonz/files/319459/LJ_walk.tnz.txt)

**Comment by shun-iwasawa** [comment]
I could open your scene like this and couldn't reproduce the crash..
<img src = "https://cloud.githubusercontent.com/assets/17974955/16138799/2c5631c2-347c-11e6-9b94-1c78f5a02f98.png" width=350>

The major difference between your environment and mine would be existence of the level files.
Could you please try the following:
1. Set Preferences>Loading>Column Icon to "On Demand" and try to load the same scene. If it opens, then icon data of some level may be corrupted. 
2. Try to load each level in your scene by "Load Level" one by one in order to find corrupted item.

**Comment by manongjohn** [comment]
I changed the preferences as mentioned and it opened.  When I attempted to load the icons on each column (Alt - Click column), the one that causes it to crash is Col 6.

If I Open sub-xsheet or even explode the sub-xsheet on Col 6, I can load the icons for each of the levels.

The only real difference between Col 6 sub-xsheet and the other sub-xsheets is it has 2 mesh layers in it.

**Comment by manongjohn** [comment]
I was able to duplicate this issue with a brand new scene.  It has to do with sub-xsheets, mesh and including pegbars.

1) Create a new scene
2) Add a level with a simple image to animate over a few frames
3) Use the Plastic tool to create the mesh for that image
4) Build the skeleton
5) Animate it over the few frames
6) Select the 2 columns and "Collapse"
7) Select "Include relevant pegbars in the sub-xsheets as well" and click Apply
8) Alt-Click the column to load the icon on the newly collapsed column and it crashes.

Oddly, for step #7, in this scenario, if I didn't include pegbars, it still crashes for me.  In my original scene, if I opened Col 6 without including the pegbars and then recollapsed and manually loaded the icon, it didn't crash.  Only when I tried including pegbars did it crash.

If you need any additional information or want me to try anything, please let me know.  I can include the new .tnz and .pli files if you can't reproduce it.

NOTE: I am using the Windows version.

**Comment by manongjohn** [comment]
Confirmed fix. Closing.
