### ISSUE TITLE
Bring back Tab key with palette window and styles

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4597]
### Description

Related to this problem opentoonz/opentoonz_docs#132 . It seems that since version 1.5. it is no longer possible to reach the styles beyond 9 thanks to the tab key ,from the palette window.

### Steps to Reproduce

From palette window try tab, to reach 2 digits styles

### Expected Behavior

Palette window can be focused with tab key to navigate with the styles.

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by shun-iwasawa** [comment]
Pressing tab key for switching the style shortcut scope is available only in Viewer / Combo Viewer.

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themselves and...
See @shun-iwasawa's comment above.
Any remaining shortfalls should be transferred to a new report where appropriate.
