### ISSUE TITLE
Opentoonz levels corrupted, showing "no icon" on entire column

### ISSUE THREAD

**Issue by thegrayoutlaw** [opentoonz/opentoonz#4603]
### Description

Ive been working on a project for a while, saving frequently, making copies of the scene repeatedly. While saving, Opentoonz crashed and now almost everything on my animation column is gone. The frames are still there but nothing shows up and on the levels strip it says "no icon". I thought, "no problem, ill go onto a different save file" but on every copy I have of the scene, the animation column has the exact same problem. I have no idea what to do.
![Screenshot (556)](https://user-images.githubusercontent.com/118583160/202856985-d6341f5a-2407-4884-97a5-5409af0d5a56.png)

### Steps to Reproduce

1. Save file
2. crash opentoonz in process

### Expected Behavior

to be able to access a past save file and not have the problem be there

### Screenshots, Video & Crash Logs

![Screenshot (556)](https://user-images.githubusercontent.com/118583160/202857036-09827cc1-ec7c-4d63-8123-6a7eca8b02ae.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Other

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
@shun-iwasawa The attached TLV file appears to be corrupt although according to Opentoonz it does appear to contain 211 frames at 10MB+ in size.

Attached is the TLV level and palette file.

[badtlv.zip](https://github.com/opentoonz/opentoonz/files/10048145/badtlv.zip)

**Comment by RodneyBaker** [comment]
I do wish we had a better way to organize these sorts of report as there is very little actionable information to work with and yet the report does capture a moment in time where Opentoonz files became corrupted.

For the moment will close as a known issue.
The known issue being:

During saving if something interupts the saving process files may become corrupted.  That something can be a power outage but can also be any interruption to the process.

If encountered and the progam still has the potential of completing the saving of files, recommend leaving the program open to allow the process to finish.  

There is a very odd chance that starting up a second iteration of Opentoonz will free the process and allow the file to save.  If a second instance of installed Opentoonz will not launch a portable version of Opentoonz may be launched.
