### ISSUE TITLE
Crash flipbook with png 

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#4619]
### Description

While using flipbook with png and define and use loading box command's OT will crash will. No issue with jepg format.

### Steps to Reproduce

1. view a PNG with flipbook
2. define loading box on the image
3. use loading box command
4. OT crash

### Expected Behavior

No crash

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/29790512/204278974-8d2cf08d-4e9b-4995-8efd-533ff309bc86.mp4

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

**Comment by RodneyBaker** [comment]
I'm not even able to use the Loading Box in the Flipbook so I'm not quite sure what is going on here.

**Comment by RodneyBaker** [comment]
Perhaps this issue has been resolved by other recent updates to flipbook and viewers?
@openanim Can you confirm you are still experiencing this problem with the recent v1.7 release candidate?

**Comment by RodneyBaker** [comment]
Nope.  I get a crash with PNG images that I don't get with JPGs.
