### ISSUE TITLE
Stylet issue with define sub camera

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#4621]
### Description

I have some problems with my stylus when I use "define sub camera" it is impossible to manually modify the box or move it. No problem with the mouse. This seems to be visible in several versions.

### Steps to Reproduce

1. use a wacom stylet  to define sub camera and edit it

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/29790512/204361273-f184a0a7-2c96-43f6-b641-a5c279d8a69c.mp4

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Other

### Graphics Tablet

Wacom

**Comment by flurick** [comment]
After some headache debugging this, the tablet changes into a mouse event for some #2282 reason. https://github.com/opentoonz/opentoonz/blob/99ba6d106480718d055ebcb577c316b8abcfde8e/toonz/sources/toonz/sceneviewerevents.cpp#L300
