### ISSUE TITLE
Flipbook target area

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4622]
### Is your feature request related to a problem? Please describe

This is a feature available in Harlequin (so chances are somewhere in the OT code). You can target an area to quickly zoom in on it. It is easy to examine an area in this way.

### Describe the solution you'd like

Similar than exemple below from Toonz premium

https://user-images.githubusercontent.com/29790512/204374172-3585a2f8-cf59-41d7-8990-0aa5a6c8b464.mp4

**Comment by beeheemooth** [comment]
Such a thing would be useful in the Viewer as well, as it is more accurate! The Zoom Tool is terrible, it almost always requires an extra pan with Hand!

**Comment by openanim** [comment]
Yes, same feeling i think that will be even more useful on the viewer and will help  a lot for edit things in the fly.

**Comment by RodneyBaker** [comment]
Closing as as the original reporter has ghosted themselves.
As a feature request this report may contain useful information and where appropriate that information should be transferred into another report.
