### ISSUE TITLE
When ever I use plastic tool it always crashes my project

### ISSUE THREAD

**Issue by Akskr73** [opentoonz/opentoonz#4625]
Hii.
Please fix this problem.
I am using opentoonz 1.6 and whenever I uses plastic tool to animate and want to render it always crashes.

It says memory could not be loaded.
Clock ok to terminate the program.

Please fix this problem.

**Comment by RodneyBaker** [comment]
Sorry to hear you are having problems @Akskr73 
Please provide additional information as there is no way to diagnose and resolve your problem without it.

**Comment by Akskr73** [comment]
Every time I am using plastic tool this is happening 

![IMG_20221202_130813](https://user-images.githubusercontent.com/101984414/205240636-9d35297f-e4bb-4b05-8426-7144b9302b03.jpg)

What to do it does not able to render and i am not getting the result

**Comment by Akskr73** [comment]
What should I do

**Comment by GiorgioAKrenkel** [comment]
I think is related to bitmap (raster) images. Could make it work with vectors (svg) files.

**Comment by RodneyBaker** [comment]
@Akskr73 If there is any way you can supply a project file (scene) that demostrates the specific problem you are experiencing that will go a long way toward resolving the issue.

Ideally use the File > Export Scene dialogue to export the scene and all of its contents into a directory.
Then zip up that directory and share the zip file.
This functionality is in older versions of Opentoonz as well just buried a little deeper.
Right Click on a Scene file in Browser room or other appropriate location and select Export Scene.

This need not be a production scene.
Any scene that demonstrates the issue will suffice.

**Comment by RodneyBaker** [comment]
@Akskr73 You might also look into Task rendering in Opentoonz as that approach has helped many users render projects/scenes that were otherwise problematic.

**Comment by RodneyBaker** [comment]
In addition to information above will recommend joining one of the Opentoonz discords where additional assistance can be shared concerning optimal ways to use Plastic Tool as well as work with some of its known problems.
