### ISSUE TITLE
Open toonz automatically stopped working

### ISSUE THREAD

**Issue by Akskr73** [opentoonz/opentoonz#4636]
### Description

I am working on an animation an it's automatic stopped working and closed down. And when I am reponeing it won't reopen it crashes down..
..

It feds me up 

What to do if we have huge problems in opentoonz software.

Should we use other softwares.

If it's not working i am using other software and never use it in my life 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by Ensaru** [comment]
A possible workaround would be to close the startup menu and open your project manually from the OpenToonz' taskbar using File> Load Scene. 

I encountered a somewhat similar issue today and that helped.

**Comment by flurick** [comment]
Trying to recreate this crash-on-launch state, 
not sure if its the same as what @Akskr73 got but I suspect there's something not handled when loading toolbars. 

And also triggering the mainwindow to show via a debugger avoided my crash (time related?), and seemed to have been worked around by re-installing the "stuff" folder.

**Comment by RodneyBaker** [comment]
Closing as not enough information to begin to troubleshoot the problem.
@Akskr73 Very sorry to hear of your problems.  You may find more direct assistance in one of the Opentoonz discords (chat rooms). Reddit, Google Groups or other online areas dedicted to assisting Opentoonz users.  If you can supply additional information... perhaps a video/screen grab of what you are experienceing that will help tremendously.  Thanks!
