### ISSUE TITLE
Colours are shifting their values when switching styles

### ISSUE THREAD

**Issue by KaseyFarron** [opentoonz/opentoonz#4651]
### Description

When changing the values of a colour style in the style editor for HSV, after switching to another style and back again the digit has decreased by 1 or 2.

If I entered a lower number, then it would decrease by 2. If I entered a higher number it would decrease by 1.

### Steps to Reproduce

1. Make two styles
2. Edit one of the HSV fields
3. Switch to another style
4. Switch back to the style that was modified
5. Notice the value has changed

### Expected Behavior

For the values to remain when switching styles.

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/55353161/207823330-4f0aa443-e5f4-4d77-ae2b-71bdf2002c12.mp4

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Latest

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by flurick** [comment]
Oh yes, at a first glance there's quit a bit of rounding and what not in the HSV data 
https://github.com/opentoonz/opentoonz/blob/195d1c166cc986cfaccac669fb41d6720bcaea55/toonz/sources/toonz/separatecolorspopup.cpp#L148
