### ISSUE TITLE
Random Auto-filling

### ISSUE THREAD

**Issue by Abhainn35** [opentoonz/opentoonz#4654]
### Description

I'm having a problem with the fill tool. Each time I connect a line(an enclosed space) on a vector layer, it fills the entire space with the lineart color. I can move the original line art aside and the filled ink will disappear, but it returns when I attach the lines. It doesn't happen on all the frames, only the last (currently at 10). I've played around with the settings and nothing seems to work.

### Steps to Reproduce

1. I'm not sure what button caused it for sure, but I'll try my best:
2. Start with a vector layer
3. Draw an enclosed space
4. (Possible) Erase part of the enclosed line

### Expected Behavior

I expected when I connect the lines (head and neck in this example) it doesn't fill in.

### Screenshots, Video & Crash Logs

![Screenshot_20221216_082623](https://user-images.githubusercontent.com/119885849/208120424-409f6f03-0387-4716-b63c-f533a84b72c9.png)
(Separated)

![Screenshot_20221216_082640](https://user-images.githubusercontent.com/119885849/208120432-ac9a88b1-6afb-452b-a17a-2d2d907b5b47.png)
(Glitch)

![Screenshot_20221216_083217](https://user-images.githubusercontent.com/119885849/208120847-f8c17f3f-5daa-4947-ad88-eb830f7a3a30.png)
(Previous frame)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by konero** [comment]
Did you use the Fill Tool at all? Try this:
1. Select the Fill Tool
2. Set the type to `Rectangular`
3. Set the mode to `Areas`
4. Select `color_0` in the palette window
5. Drag a selection over the entire drawing

**Comment by Abhainn35** [comment]
@konero 
It took a few tries to stay, but it worked! Thank you!
