### ISSUE TITLE
create Mesh not coming on the object

### ISSUE THREAD

**Issue by TestTime3000** [opentoonz/opentoonz#4658]
### Ask a question related to OpenToonz

when i create mesh ....its not coming on the selected object 
its coming up...or far 
![image](https://user-images.githubusercontent.com/75811532/208208166-2e1267b6-bbda-4e74-a42c-32c66ed58efc.png)

**Comment by artisteacher** [comment]
It might be because you have a keyframe on the drawing column. Generally speaking, you should put all keyframes on the mesh column instead.

**Comment by TestTime3000** [comment]
can you explain it my bro..in a video here .....becuse i am also new here ....and didn't find The solution in youtube

**Comment by TestTime3000** [comment]
> can you explain it my bro..in a video here .....becuse i am also new here ....and didn't find The solution in youtube
