### ISSUE TITLE
Missing Mode for Selection Tool

### ISSUE THREAD

**Issue by quah1234** [opentoonz/opentoonz#4660]
### Description

My selection tool have no mode to set and cannot automatic select the item I click.
Please fix it as fast as you can.

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/121085723/208609336-50137038-ec2d-44d0-b860-7474b41e99f6.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by shun-iwasawa** [comment]
Selection tool has different functions (and tool options) depending on the current level type. The image in your post seems to be when a raster level is selected. Selecting vector level will display the Mode combo box.

**Comment by RodneyBaker** [comment]
Closing as likely resolved.
@quah1234 Please let us know if that is not the case.

For real time troubleshooting of differences in level types (and much more) you may be interested in joining one of the Opentoonz communities on discord.   Others online places to assist in near real time include Google Groups, Reddit, Facebookand more.
