### ISSUE TITLE
Crash When Using Type Tool

### ISSUE THREAD

**Issue by ablechow29** [opentoonz/opentoonz#4666]
### Description

When I create a new layer and click on the text tool, as soon as I try to type something, OpenToonz crashes. 
Perhaps something was wrong with my installation. 

```
OpenToonz 1.6  (Build Nov 23 2022)

Report Date: 2022-12-21 01:11:03
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: Arch Linux
OS Kernel: 6.0.7-arch1-1
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1080/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 520.56.06

Crash File: /home/able/.local/share/OpenToonz/OpenToonz/crash/Crash-20221221-011103.log

Application Dir: /opt/opentoonz/bin
Stuff Dir: /home/able/.config/OpenToonz/stuff

Project Name: 2022_Christmas_Card
Scene Name: Christmas_Card_2022_V1
Project Path: /home/able/.config/OpenToonz/stuff/projects/2022_Christmas_Card/2022_Christmas_Card_otprj.xml
Scene Path: /home/able/.config/OpenToonz/stuff/projects/2022_Christmas_Card/scenes/Christmas_Card_2022_V1.tnz

==== Backtrace ====
  1> /usr/lib/libc.so.6(+0x8864c) [0x7f9ed8ca164c]
  2> /usr/lib/libc.so.6(gsignal+0x18) [0x7f9ed8c51958]
  3> /usr/lib/libc.so.6(abort+0xd7) [0x7f9ed8c3b53d]
  4> /usr/lib/libstdc++.so.6(+0x99833) [0x7f9ede899833]
  5> /usr/lib/libstdc++.so.6(+0xa5cfc) [0x7f9ede8a5cfc]
  6> /usr/lib/libstdc++.so.6(+0xa5d69) [0x7f9ede8a5d69]
  7> /usr/lib/libstdc++.so.6(+0xa5fcd) [0x7f9ede8a5fcd]
  8> /opt/opentoonz/bin/../lib/opentoonz/libtnzcore.so(+0xae23f) [0x7f9edaeae23f]
  9> /opt/opentoonz/bin/../lib/opentoonz/libtnzcore.so(_ZNK5TFont8drawCharER9TRasterPTI10TPixelCM32ER7TPointTIiEiww+0x7d) [0x7f9edb1438bd]
 10> /opt/opentoonz/bin/../lib/opentoonz/libtnztools.so(_ZN8TypeTool11replaceTextENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEii+0x7ef) [0x7f9ede22903f]
 11> /opt/opentoonz/bin/../lib/opentoonz/libtnztools.so(_ZN8TypeTool7keyDownEP9QKeyEvent+0x28b) [0x7f9ede22971b]
 12> /opt/opentoonz/bin/../bin/OpenToonz(_ZN11SceneViewer13keyPressEventEP9QKeyEvent+0x262) [0x55c28484a182]
 13> /usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x9b1) [0x7f9edd3af5d1]
 14> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7f9edd378b1c]
 15> /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0xe68) [0x7f9edd37ddf8]
 16> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7f9edc68cf98]
 17> /usr/lib/libQt5Widgets.so.5(+0x1cf18b) [0x7f9edd3cf18b]
 18> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7f9edd378b1c]
 19> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7f9edc68cf98]
 20> /usr/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE+0xf0) [0x7f9edcb3fb80]
 21> /usr/lib/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xb5) [0x7f9edcb28995]
 22> /usr/lib/libQt5XcbQpa.so.5(+0x64710) [0x7f9ec452f710]
 23> /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x19b) [0x7f9ed746d87b]
 24> /usr/lib/libglib-2.0.so.0(+0xac279) [0x7f9ed74c4279]
 25> /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x7f9ed746c132]
 26> /usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x6c) [0x7f9edc6d7c4c]
 27> /usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x12c) [0x7f9edc68573c]
 28> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x99) [0x7f9edc690269]
 29> /opt/opentoonz/bin/../bin/OpenToonz(main+0x2b10) [0x55c2846b90f0]
 30> /usr/lib/libc.so.6(+0x23290) [0x7f9ed8c3c290]
 31> /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f9ed8c3c34a]
 32> /opt/opentoonz/bin/../bin/OpenToonz(_start+0x25) [0x55c2846d1cc5]
==== End ====

```

### Steps to Reproduce

1. Create a new layer
2. Select the text tool
3. type on the keyboard

### Expected Behavior

Error message shows up and OpenToonz closes

### Screenshots, Video & Crash Logs

OpenToonz 1.6  (Build Nov 23 2022)

Report Date: 2022-12-21 01:11:03
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: Arch Linux
OS Kernel: 6.0.7-arch1-1
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1080/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 520.56.06

Crash File: /home/able/.local/share/OpenToonz/OpenToonz/crash/Crash-20221221-011103.log

Application Dir: /opt/opentoonz/bin
Stuff Dir: /home/able/.config/OpenToonz/stuff

Project Name: 2022_Christmas_Card
Scene Name: Christmas_Card_2022_V1
Project Path: /home/able/.config/OpenToonz/stuff/projects/2022_Christmas_Card/2022_Christmas_Card_otprj.xml
Scene Path: /home/able/.config/OpenToonz/stuff/projects/2022_Christmas_Card/scenes/Christmas_Card_2022_V1.tnz

==== Backtrace ====
  1> /usr/lib/libc.so.6(+0x8864c) [0x7f9ed8ca164c]
  2> /usr/lib/libc.so.6(gsignal+0x18) [0x7f9ed8c51958]
  3> /usr/lib/libc.so.6(abort+0xd7) [0x7f9ed8c3b53d]
  4> /usr/lib/libstdc++.so.6(+0x99833) [0x7f9ede899833]
  5> /usr/lib/libstdc++.so.6(+0xa5cfc) [0x7f9ede8a5cfc]
  6> /usr/lib/libstdc++.so.6(+0xa5d69) [0x7f9ede8a5d69]
  7> /usr/lib/libstdc++.so.6(+0xa5fcd) [0x7f9ede8a5fcd]
  8> /opt/opentoonz/bin/../lib/opentoonz/libtnzcore.so(+0xae23f) [0x7f9edaeae23f]
  9> /opt/opentoonz/bin/../lib/opentoonz/libtnzcore.so(_ZNK5TFont8drawCharER9TRasterPTI10TPixelCM32ER7TPointTIiEiww+0x7d) [0x7f9edb1438bd]
 10> /opt/opentoonz/bin/../lib/opentoonz/libtnztools.so(_ZN8TypeTool11replaceTextENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEii+0x7ef) [0x7f9ede22903f]
 11> /opt/opentoonz/bin/../lib/opentoonz/libtnztools.so(_ZN8TypeTool7keyDownEP9QKeyEvent+0x28b) [0x7f9ede22971b]
 12> /opt/opentoonz/bin/../bin/OpenToonz(_ZN11SceneViewer13keyPressEventEP9QKeyEvent+0x262) [0x55c28484a182]
 13> /usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x9b1) [0x7f9edd3af5d1]
 14> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7f9edd378b1c]
 15> /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0xe68) [0x7f9edd37ddf8]
 16> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7f9edc68cf98]
 17> /usr/lib/libQt5Widgets.so.5(+0x1cf18b) [0x7f9edd3cf18b]
 18> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c) [0x7f9edd378b1c]
 19> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7f9edc68cf98]
 20> /usr/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE+0xf0) [0x7f9edcb3fb80]
 21> /usr/lib/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xb5) [0x7f9edcb28995]
 22> /usr/lib/libQt5XcbQpa.so.5(+0x64710) [0x7f9ec452f710]
 23> /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x19b) [0x7f9ed746d87b]
 24> /usr/lib/libglib-2.0.so.0(+0xac279) [0x7f9ed74c4279]
 25> /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x7f9ed746c132]
 26> /usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x6c) [0x7f9edc6d7c4c]
 27> /usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x12c) [0x7f9edc68573c]
 28> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x99) [0x7f9edc690269]
 29> /opt/opentoonz/bin/../bin/OpenToonz(main+0x2b10) [0x55c2846b90f0]
 30> /usr/lib/libc.so.6(+0x23290) [0x7f9ed8c3c290]
 31> /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f9ed8c3c34a]
 32> /opt/opentoonz/bin/../bin/OpenToonz(_start+0x25) [0x55c2846d1cc5]
==== End ====

### OpenToonz Version

1.6

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
What drawing level type are you creating?
How are you creating it? (by clicking a button above the timeline, from the menu or just drawing something?)
Does it matter what you type? Is it the first keystroke that makes it crash?

**Comment by ablechow29** [comment]
> What drawing level type are you creating? How are you creating it? (by clicking a button above the timeline, from the menu or just drawing something?) Does it matter what you type? Is it the first keystroke that makes it crash?

Sorry about the delayed response, I just got back to Opentoonz and encountered the same problem. This is on a new install of Arch. 

When I try to use the text tool in a new vector level (created from the button above the timeline, while on the drawing pane), it only types out blank. 
In the Animate pane, When I try to create a new level by clicking on a new column on the timeline, it crashes as soon as I start typing. 

```
OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-06-19 19:25:53
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: Arch Linux
OS Kernel: 6.3.8-arch1-1
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1080/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 535.54.03

Crash File: /home/able/.local/share/OpenToonz/OpenToonz/crash/Crash-20230619-192553.log

Application Dir: /usr/bin
Stuff Dir: /home/able/.config/OpenToonz/stuff

Project Name: BONANZA_Dragon_Boat_2023
Scene Name: DragonBoat_2023
Project Path: /home/able/.config/OpenToonz/stuff/projects/BONANZA_Dragon_Boat_2023/BONANZA_Dragon_Boat_2023_otprj.xml
Scene Path: /home/able/.config/OpenToonz/stuff/projects/BONANZA_Dragon_Boat_2023/scenes/DragonBoat_2023.tnz

==== Backtrace ====
  1> /usr/lib/libc.so.6(+0x39ab0) [0x7fa13424fab0]
  2> /usr/lib/libc.so.6(+0x8926c) [0x7fa13429f26c]
  3> /usr/lib/libc.so.6(gsignal+0x18) [0x7fa13424fa08]
  4> /usr/lib/libc.so.6(abort+0xd7) [0x7fa134238538]
  5> /usr/lib/libstdc++.so.6(+0x9ca6f) [0x7fa13aa9ca6f]
  6> /usr/lib/libstdc++.so.6(+0xb011c) [0x7fa13aab011c]
  7> /usr/lib/libstdc++.so.6(+0xb0189) [0x7fa13aab0189]
  8> /usr/lib/libstdc++.so.6(+0xb03ed) [0x7fa13aab03ed]
  9> /usr/bin/../lib/opentoonz/libtnzcore.so(+0x83e86) [0x7fa137683e86]
 10> /usr/bin/../lib/opentoonz/libtnzcore.so(_ZNK5TFont8drawCharER9TRasterPTI10TPixelCM32ER7TPointTIiEiww+0x7d) [0x7fa13788ddfd]
 11> /usr/bin/../lib/opentoonz/libtnztools.so(_ZN8TypeTool11replaceTextENSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEii+0x63e) [0x7fa13a3d835e]
 12> /usr/bin/../lib/opentoonz/libtnztools.so(_ZN8TypeTool7keyDownEP9QKeyEvent+0x272) [0x7fa13a3db932]
 13> /usr/bin/../bin/OpenToonz(_ZN11SceneViewer13keyPressEventEP9QKeyEvent+0x2d6) [0x5630431ecfd6]
 14> /usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x55d) [0x7fa1397aee6d]
 15> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8f) [0x7fa13977893f]
 16> /usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0xc68) [0x7fa13977d958]
 17> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7fa138a9b778]
 18> /usr/lib/libQt5Widgets.so.5(+0x1cec5b) [0x7fa1397cec5b]
 19> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8f) [0x7fa13977893f]
 20> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7fa138a9b778]
 21> /usr/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE+0xf0) [0x7fa138f455a0]
 22> /usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so(+0xd995) [0x7fa1207f7995]
 23> /usr/lib/libQt5Core.so.5(+0x2d06a7) [0x7fa138ad06a7]
 24> /usr/lib/libQt5DBus.so.5(_ZN23QDBusPendingCallWatcher8finishedEPS_+0x44) [0x7fa1207b7ad4]
 25> /usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0x234) [0x7fa138ac31e4]
 26> /usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8f) [0x7fa13977893f]
 27> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x128) [0x7fa138a9b778]
 28> /usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x19b) [0x7fa138aa06db]
 29> /usr/lib/libQt5Core.so.5(+0x2e6748) [0x7fa138ae6748]
 30> /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x141) [0x7fa133710981]
 31> /usr/lib/libglib-2.0.so.0(+0xb7b39) [0x7fa13376db39]
 32> /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x32) [0x7fa13370e032]
 33> /usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x6c) [0x7fa138aea5cc]
 34> /usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x134) [0x7fa138a9a484]
 35> /usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x93) [0x7fa138a9b923]
 36> /usr/bin/../bin/OpenToonz(main+0x29dc) [0x5630430a104c]
 37> /usr/lib/libc.so.6(+0x23850) [0x7fa134239850]
 38> /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fa13423990a]
 39> /usr/bin/../bin/OpenToonz(_start+0x25) [0x5630430b3f35]
==== End ====
```

**Comment by ablechow29** [comment]
Text tool now works normally without issue after installing all-repository-fonts and making sure the available font is selected. 
Still not sure why uninstalled or unavailable fonts are displayed in the drop down but that's a separate issue.
