### ISSUE TITLE
The Fill Tool

### ISSUE THREAD

**Issue by reinier03** [opentoonz/opentoonz#4673]
### Description

When i try to use THE FILL TOOL, opentoonz is break down, is very disgusting :l 
i started to use krita, another option to animate but i really want opentoonz, 

¡please fix it!

### Steps to Reproduce

1. Open Opentoonz
2. Try to use the Fill Tool XD

### Expected Behavior

Only that, being able to fill in normal

### Screenshots, Video & Crash Logs

i don't have, just taste it

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@reinier03 There is insufficient information in your report to begin to troubleshoot your problem.
Perhaps you will find one of the Opentoonz chat/discords to your liking:  https://discord.gg/UQxvYBKW5U

**Comment by gab3d** [comment]
@reinier03 
Sorry man, that's no useful way of getting help.
You have to give specific details about what is not working for you and what you expect to happen instead. Also platform and program version you're using.

Obviously the Fill tool does fill fillable areas. Maybe you encountered a bug, maybe you're not setting up things correctly, but if you don't circumscribe your problem to something measurable by objective means, there's very little anybody would be able to do to help you.
