### ISSUE TITLE
Import image sequences with unevenly incremental indices/unique frames

### ISSUE THREAD

**Issue by khoidauminh** [opentoonz/opentoonz#4674]
### Is your feature request related to a problem? Please describe

I have an image sequence of animation that contains only unique frames and I want to import them to Opentoonz.
![image](https://user-images.githubusercontent.com/81458575/209464540-bbce1028-aceb-4fc5-8d3d-c01da3e0734b.png)

With defaults settings during import, Opentoonz will expose the sequence into the Xsheet as if it's a regular sequence (placing frames in an successive order).
![image](https://user-images.githubusercontent.com/81458575/209464551-25e59381-d522-4251-a9d4-f62d4cf68a39.png)

*Note that the frame numbers in the Levels are correct.*

I've tried changing the import settings and found out with Inc set to 1, the sequence is exposed appropriately to the Xsheet, but leaving the empty inbetweens as red frames, which I have to manually select, remove and fill back in using Fill in the empty cells.
![image](https://user-images.githubusercontent.com/81458575/209464563-e2bd0c08-09d8-421f-b05b-12dc1934cd72.png)
 

### Describe the solution you'd like

I have 2 solutions:
1. Include an option to delete all red frames found in selection or the entire track.
2. Have Opentoonz automatically detect and expose the level into the Xsheet appropriately according to the indices in the filename number or the Level's frame number.

I hope this will be resolved. Thank you!

**Comment by RodneyBaker** [comment]
There is a way to do this but I did think Opentoonz did it by default for broken image sequences.
Perhaps it was my imagination.

I need to refresh my memory but try this with a simple (broken) sequence:

Place your broken sequence in location easy to access.
Using Opentoonz browser Right Click  > Convert and convert to TLV format
Load this TLV sequence into Opentoonz and select it
Use Cells > Autoexpose to get it to stretch the frame exposures to fill the inbetween frames.

Okay... you don't want to convert to TLV.  
Rename will do this same thing with raster images.
Opentoonz > Browser > Right Click > Rename
Put in an appropriate name (don't add any numbers as OT will do this).
Cells > Autoexpose
Frames should align into proper exposures

And... this should work for your image sequence as well if it is properly named.
What might mess with this process is the image type if it has to pass through ffmpeg etc.

While not the immediate goal of automatically recognizing exposures this should get exposures to appear with one or two clicks (depending on if using a shortcut key for autoexposure).

Disclaimer:  There may be a way to get Opentoonz to autoexpose automatically but I can't find it.

**Comment by khoidauminh** [comment]
Works like a charm! I won't mind a few more clicks
Thank you very much!
