### ISSUE TITLE
saving level crashes opentoonz

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#468]
![crashdata](https://cloud.githubusercontent.com/assets/6495061/16168541/13bd1b90-3502-11e6-97a3-03cde33ffcdf.PNG)

here is the output data:
[Temp.zip](https://github.com/opentoonz/opentoonz/files/321533/Temp.zip)

**Comment by blurymind** [comment]
this happened on 1.0,
I dont know why. The bug is hard to reproduce - but it lost the drawing too. 

I will try to do some drawing on the newest later - see if I can get it to crash again - by saving right at the end.

**Comment by turtletooth** [comment]
Nice drawing though.

**Comment by blurymind** [comment]
ah thanks :) 
this crash is the worst a software can do because it loses your work

**Comment by blurymind** [comment]
btw I noticed that the eraser tool in bitmap mode does not have pressure sensitivity for opacity (min and max opacity for the slider) that kinda sucks when you do sketching

**Comment by turtletooth** [comment]
@blurymind That would be a cool eraser setting.

BTW- do you have Harlequin?  I am working on pixels as a measurement and want to know what harlequin does.  What happens to the level dpi and camera dpi if you choose pixels?  Does it default to new settings for new projects and levels?  Do the dpis of tifs and psds get ignored on import or are they still able to recognize dpi?

Right now it makes sense that if pixels is chosen, dpi should be ignored and all items should reflect their actual resolution.  

Do you think that if pixels is chosen as a measurement it should be that everywhere or is there benefit to being able to choose pixels for the camera but still keeping the other units in mm or whatever?

**Comment by blurymind** [comment]
I think opentoonz should use pixels as a default metric system. It is insane that given that the final output is digital, opentoonz doesnt even have the option in the preferences.

here it is in inches:
![dpi1](https://cloud.githubusercontent.com/assets/6495061/16180346/70343bd2-367a-11e6-9229-ad7cd856230c.PNG)

Basically if you change it, the input boxes for size are in a pixel metric system

![dpi2](https://cloud.githubusercontent.com/assets/6495061/16180347/775681ae-367a-11e6-819d-81cd996e174d.PNG)

To me personally this is more intuitive. In other software the switch between pixels and inches is found everywhere in the interface where there is input bux for size. A good example of this of course is all of adobe's products. Just take a look at photoshop and illustrator, flash or final cut pro:
![ai-16-9](https://cloud.githubusercontent.com/assets/6495061/16180358/d5556d1a-367a-11e6-92e2-1033bfb5eed1.jpg)

if you create content for printing then inches and centimeters makes more sense. If you are creating for a specific target digital video resolution then i have no idea why inches is the default and pixels have been removed.  

So thank you for working on bringing this back! :) Another very useful feature

**Comment by blurymind** [comment]
I filed a feature request on the eraser tool here:
https://github.com/opentoonz/opentoonz/issues/481

perhaps @walkerka might be interested? :)

**Comment by walkerka** [comment]
@blurymind I don't quite like brush like eraser. 
Fixed sized eraser is fast to use but hard to control the range, especially when you zoom in/out.
Pressure controlled eraser is flexible but users have to press strongly when clearing large areas.

Freehand closed region based "eraser" is fast and accurate. Does OT have such thing?
In TVP you can use "Filled Stroke" tool and "Erase" composition mode to achieve this.

**Comment by blurymind** [comment]
@walkerka  eraser could be better for cleaning up bitmap inking work if the pressure could control the size of the eraser.

The freehand close eraser would be awesome to have in opentoonz. I dont think that it has it. it is indeed very very nice in tvpaint and makes life easier.
Existing code of that eraser mode can be found in krita btw.

**Comment by blurymind** [comment]
for freehand eraser - in raster levels, you can use the selection tool to lasso select pixels and then hit delete. So we kind of have it- even if it takes that extra step.

This of course doesnt work the same way on vector layers where selection happens on a strokes basis.

**Comment by walkerka** [comment]
@blurymind I checked the code and found it. It's under the tool option bar. Select "Freehand" in "Type" option. It's much better than the "Normal" one IMO.

**Comment by blurymind** [comment]
Here is another crash report:
[Temp.zip](https://github.com/opentoonz/opentoonz/files/326812/Temp.zip)

Latest version (nightly)
this time it crashed while drawing on a raster level.
can these help stabilize the software?

**Comment by turtletooth** [comment]
@blurymind I'm going to close this for now.  If you have specific steps we can use for recreating, we can reopen.
