### ISSUE TITLE
a red circle is staying after a stroke 

### ISSUE THREAD

**Issue by noelcurray** [opentoonz/opentoonz#4686]
### Description

While testing the app, I tried some strokes on the canvas and some weird red circle artifacts is showing on the strokes and stays for a couple of seconds. 

### Steps to Reproduce

1. Open Opentoonz
2. Draw some lines using the brush tools
3. The issue then shows.

### Expected Behavior

I expect that the red circle will not show at anytime you draw.

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/83384364/210166934-36ad2dcc-933a-4982-a0b2-1ce3cdaa6ac8.mp4

### OpenToonz Version

1.6

### Operating System

Arch Linux

### GPU

AMD

### Graphics Tablet

Wacom Cintiq 16

**Comment by RodneyBaker** [comment]
Hi @nukeCrayon   Thanks for the report.
I've (temporarily) removed the bug label until we can confirm more about the problem.
I've tagged with troubleshooting until we collect more information.

Thanks for the video.
I note you are on Linux and if you can provide more information on that it will be helpful.

Hopefully other Linux users will join in here soon but in the meantime I will suggest checking graphics card settings to make sure you are in high graphics mode.
 
Happy New Year!

**Comment by RodneyBaker** [comment]
I see in your other report that you also have access to a Windows system.
Do you get this same red circle on that system?

**Comment by nukeCrayon** [comment]
> I see in your other report that you also have access to a Windows system. Do you get this same red circle on that system?

Hi. I don't have an access to a windows system. I only have Arch Linux here.

**Comment by RodneyBaker** [comment]
> > I see in your other report that you also have access to a Windows system. Do you get this same red circle on that system?
> 
> Hi. I don't have an access to a windows system. I only have Arch Linux here.

Thanks for the clarification.  I was going by the information you posted so you may want to update that in your other report.

**Comment by nukeCrayon** [comment]
> > > I see in your other report that you also have access to a Windows system. Do you get this same red circle on that system?
> > 
> > 
> > Hi. I don't have an access to a windows system. I only have Arch Linux here.
> 
> ![image](https://user-images.githubusercontent.com/2576432/210167406-2bf031f6-2fa8-4e81-8467-ede5562da316.png)
> 
> Thanks for the clarification. I was going by the information you posted so you may want to update that in your other report.

Thank you sir. Its been updated now.

**Comment by nukeCrayon** [comment]
> I also have this problem, have had it for years.
> 
> I just turned the cursor outline off in the preferences, I don't miss it.
> 
> I think the reason for this bug is that opentoonz doesn't know when the pen is lifted from the drawing surface, and thus keeps on drawing the circle there.

thank you for this. I follow this and the annoying cursor is gone. the issue is not solved but this can do for now.

**Comment by nukeCrayon** [comment]
just an update here. it seems that the red circle that staying has been minimized after the update of opentoonz to 1.7 and maybe after some update with arch linux and KDE plasma desktop. but its not removed entirely. its just bearable.  
[https://drive.google.com/file/d/1c771rF9K6qCOZc_o1pgLJ40U_Y49wg0S/view?usp=sharing](url)
