### ISSUE TITLE
brush become offset when you change workspace 

### ISSUE THREAD

**Issue by nukeCrayon** [opentoonz/opentoonz#4687]
### Description

the brush tip draws on a different place when you change workspace.

### Steps to Reproduce

1. open Opentoonz
2. create a test scene
3. in the drawing workspace, make some mark/sketch
4. change workspace from "drawing" to "cleanup" 
5. try to draw again
6. the issue shows.

### Expected Behavior

I expect that the calibration is still the same whenever you change workspace.

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/83384364/210167267-61a3c330-d3bd-4743-ae42-ddb80481b5cb.mp4

### OpenToonz Version

1.6

### Operating System

Arch Linux

### GPU

AMD

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Thanks for the report @nukeCrayon  
I think this has to do with rooms retaining their states (window placement, zooming) but we need to investigate this further.

**Comment by nukeCrayon** [comment]
just an update.

somehow the issue is also gone after the opentoonz 1.7 update.

thank you guys.
