### ISSUE TITLE
Resizing cursor stays when the mouse pointer passover

### ISSUE THREAD

**Issue by noelcurray** [opentoonz/opentoonz#4688]
### Description

the cursor doesn't change to original state if your mouse moves over to a panel. 

### Steps to Reproduce

1. Open Opentoonz
2.  Create a project
3. Try to move your mouse over a panel like color pallete
4. then move your mouse cursor to the canvas
5. the issue shows

### Expected Behavior

I expect that the mouse cursor changes according to the task that it should be doing. Like if you want to adjust the size of the panel, it will show the resizing cursor and change back to the original mouse cursor when you are not trying to adjust the panel. 

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/83384364/210168456-6951d7b4-8e3b-44b4-a0fb-67f39def8d0c.mp4

### OpenToonz Version

1.6

### Operating System

Arch Linux

### GPU

AMD

### Graphics Tablet

Wacom Cintiq 16

**Comment by flurick** [comment]
Looks like the canvas Viewer doesn't get focused by pen events

**Comment by flurick** [comment]
Could [possibly just be this]( 
https://github.com/opentoonz/opentoonz/compare/master...flurick:opentoonz:linux-restore-cursor) (similar to some other tablet input issues)

**Comment by nukeCrayon** [comment]
I also notice that this just happen on vertical side. I test to adjust the horizontal panel and the issue doesn't show. 

one of my workaround is hit the shortcut key <S> and <B> and the cursor go back to original arrow.

**Comment by andeon** [comment]
I belive it's an issue with Linux event mouseMove or tabletMove refresh. Unfortunately, this bug is very annoying, to avoid this I try to use a detached window like a toolbar or locator.

https://github.com/opentoonz/opentoonz/issues/2569

**Comment by nukeCrayon** [comment]
> I belive it's an issue with Linux event mouseMove or tabletMove refresh. Unfortunately, this bug is very annoying, to avoid this I try to use a detached window like a toolbar or locator.
> 
> #2569

it's been 4 years and we still have the same issue.

**Comment by noelcurray** [comment]
this is fixed now. thank you.
