### ISSUE TITLE
Changing Unit/Camera Unit is Broken

### ISSUE THREAD

**Issue by KaseyFarron** [opentoonz/opentoonz#4691]
### Description

I can't change unit or camera unit properly, it will auto select pixels, auto become disabled, won't let me uncheck all images use same dpi option, etc.

### Steps to Reproduce

1. Try change unit or camera unit to pixel, then back to cm or mm, or a mix of both, or try disabling dpi option

### Expected Behavior

Let me choose what unit I want without fuss.

### Screenshots, Video & Crash Logs

![pixels](https://user-images.githubusercontent.com/55353161/210357286-0a61123c-8b58-4413-9d10-1c86ff07ff15.gif)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Latest

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by flurick** [comment]
I can reproduce, fussy indeed. 
Could there be a reason for "Unit" needing to be set to something other than pixel mode for the "Pixels Only" checkbox to be changed?
