### ISSUE TITLE
OpenToonz 1.6 does not start : qt5Core.dll issue

### ISSUE THREAD

**Issue by dino213dz** [opentoonz/opentoonz#4692]
### Description

OpenToonz craches before main windows is loaded

We see the green start window then it craches

I've got windows 11 and an integrated intel GPU

After checking the event viewer, I saw that the issue comes from qt5core.dll

The older version works well (2020 version)
the freshly installed 1.6 version never worked, never started

### Steps to Reproduce

1. run application ...we see the loading green windows appears
2. then the green windows craches at step : "Creating Main Window"
![greenWindow](https://user-images.githubusercontent.com/34544107/210588097-68722fd9-5de5-417c-8e40-c212942f2b49.png)

### Screenshots, Video & Crash Logs

Event Viewer > Application  :

Nom du journal :Application
Source :       Application Error
Date :         04/01/2023 16:16:48
ID de l’événement :1000
Catégorie de la tâche :Événements d’arrêts inattendus d’applications
Niveau :       Erreur
Mots clés :    
Utilisateur :  VORTEX\BadMotherF
Ordinateur :   VORTEX
Description :
Nom de l’application défaillante OpenToonz.exe, version : 0.0.0.0, horodatage : 0x624a4a4e
Nom du module défaillant : Qt5Core.dll, version : 5.15.2.0, horodatage : 0x605c8071
Code d’exception : 0xc0000005
Décalage d’erreur : 0x00000000000275f0
ID du processus défaillant : 0x0x5DBC
Heure de début de l’application défaillante : 0x0x1D9204F8F4CE752
Chemin d’accès de l’application défaillante : C:\Program Files\OpenToonz\OpenToonz.exe
Chemin d’accès du module défaillant: C:\Program Files\OpenToonz\Qt5Core.dll
ID de rapport : 8c52c18a-ce69-4763-980f-8749fa136fb8
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-04T15:16:48.0413722Z" />
    <EventRecordID>52796</EventRecordID>
    <Correlation />
    <Execution ProcessID="25904" ThreadID="3648" />
    <Channel>Application</Channel>
    <Computer>VORTEX</Computer>
    <Security UserID="S-1-5-21-2703282463-3850770778-2260736793-1001" />
  </System>
  <EventData>
    <Data Name="AppName">OpenToonz.exe</Data>
    <Data Name="AppVersion">0.0.0.0</Data>
    <Data Name="AppTimeStamp">624a4a4e</Data>
    <Data Name="ModuleName">Qt5Core.dll</Data>
    <Data Name="ModuleVersion">5.15.2.0</Data>
    <Data Name="ModuleTimeStamp">605c8071</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">00000000000275f0</Data>
    <Data Name="ProcessId">0x5dbc</Data>
    <Data Name="ProcessCreationTime">0x1d9204f8f4ce752</Data>
    <Data Name="AppPath">C:\Program Files\OpenToonz\OpenToonz.exe</Data>
    <Data Name="ModulePath">C:\Program Files\OpenToonz\Qt5Core.dll</Data>
    <Data Name="IntegratorReportId">8c52c18a-ce69-4763-980f-8749fa136fb8</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by dino213dz** [comment]
I found the solution.

The old files remains in c:\Programs\OpenToonz

I uninstalled OpenToonz.
Then I deleted all files manually 
then restarted the computer.
and finally I installed OpenToonz again

It Works.

Issue occurs when we install the last version on an old one.
Is it systematic? I dont know :/

**Comment by RodneyBaker** [comment]
@dino213dz  I modified the title of your report to help others find it in hopes of helping them resolve installation issues.
