### ISSUE TITLE
Load custom textures on Calligraphic lines

### ISSUE THREAD

**Issue by F-Burning** [opentoonz/opentoonz#4695]
I think would be interesting use custom textures on the Calligraphic lines Fx as occurs in Vectors lines with vector textures.

![Screenshot_1](https://user-images.githubusercontent.com/74098734/210801417-3b7e81e8-ed85-42c6-9f0d-561bf22222fd.jpg)

**Comment by RodneyBaker** [comment]
We probably need more information here as we can currently use custom textures with Calligraphic Line FX.

![image](https://user-images.githubusercontent.com/2576432/210812362-c055a9ee-933d-4a01-8002-685361871870.png)

**Comment by F-Burning** [comment]
But those textures are in the own line, right? because I mean add texture to a line without texture, only as a Fx.

**Comment by F-Burning** [comment]
The main objective is to obtain a non-destructive work, since when drawing the texture manually, there is no going back to try another style unless you do all the work again, while with an Fx you can simulate it. If during the process you decide to change the artistic style or keep the line clean, you can do it with this procedure without any problem. It is a fast and efficient way to work, which also saves a lot of effort if you are part of a small team or are a single person. You can also reuse that material for other projects with another artistic style and apply it to it.

I always put the Japanese industry as an example because it uses these techniques a lot, but it is worth it because they are really efficient.

![image](https://user-images.githubusercontent.com/74098734/210824886-ebbcf0cc-6669-47b3-9170-88c77e2b632e.png)

Yes, I would like a Fx to add custom textures, or simple more parameters to achieve different result.

Thank you for the link, I will test that Fx  :)
