### ISSUE TITLE
Spanish UI translation conflicts?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#470]
Hi, 
Several weeks ago I've completed the Spanish translation for the UI, but when doing the Pull Request it said it had conflicts.  ( #382 )
Honestly I don't know what to do now (if I really have to do anything), but the thing is that the translation is not available in nightly builds.

Could anybody lend a hand on this?

Thanks in advance!

**Comment by walkerka** [comment]
You need sync with upstream branch and resolve conflicts. There should be some files changed and got submitted after you forked. You have to merge these changes before commiting.

[http://stackoverflow.com/questions/14199286/what-is-the-correct-way-to-merge-upstream-without-losing-changes](http://stackoverflow.com/questions/14199286/what-is-the-correct-way-to-merge-upstream-without-losing-changes)
[http://stackoverflow.com/questions/10773518/merge-conflicts-updating-from-upstream](http://stackoverflow.com/questions/10773518/merge-conflicts-updating-from-upstream)

**Comment by gab3d** [comment]
@walkerka 
I think I was finally able to merge my changes back (not before some time spending on studying).
Thanks for you help!! :)

**Comment by walkerka** [comment]
You're welcome.
