### ISSUE TITLE
FFmpeg import issue 

### ISSUE THREAD

**Issue by Lord-of-Griddlecakes** [opentoonz/opentoonz#4701]
### Ask a question related to OpenToonz

When adding an image sequence via "Load Folder" or simply drag & drop, the images do not load sequentially into one column, they all separate into individual columns. Trying to import an mp4 file or GIF through the same methods, simply does load in (the program recognizes the files, and prompts me to load/import the files). 

I would like to know why it is doing this, I know that FFmpeg is linked in preferences, so I'm at a loss as to why it is doing this. 

Any advice would be appreciated, I have minimal coding experience and I'm trying to learn more :3

**Comment by RodneyBaker** [comment]
Hi @Lord-of-Griddlecakes 

An image sequence loading into separate columns is a general indication that:

1)  FFMPEG is not installed correctly (Note however that if ffmpeg is not installed correctly images likely will not get to the stage of loading)
2) The filename is not properly indicated to allow recognition of a sequence of images.  (As such Opentoonz treats each image in the sequence as a separate image).

The ideal filenaming for a sequence in Opentoonz is:  filename DOT four digit number DOT three character image format extension  (ex:  frame.0001.png)

Note that if we select an image from a sequence that isn't properly named in the Browser Room (or other similar location) and Right Click > Rename we can add a filename ** and Opentoonz will automatically rename the frames as a proper image sequence recognized by Opentoonz.

** When using Rename do not add the numbering as that will be supplied.

One way to see the optimal filename and sequencing form for files is to render out a sequence of images using Output Settings.  Examinging that output will demonstrate that the 'filename.0001.ext' format is what Opentoonz prefers.

If you can share more information on what filenaming and image formats you are working with that will help to better understand the problem.

**Comment by RodneyBaker** [comment]
Great to hear and glad it worked out.
Will close this report.

Keep on animating!
