### ISSUE TITLE
Crash while Animating

### ISSUE THREAD

**Issue by eren0002** [opentoonz/opentoonz#4703]
### Description

Opentoonz sent me a crashed report while I was animating a scene in my computer, they mentioned that the reason was EXCEPTION_ACCESS_VIOLATION and I have to report about this issue on GitHub 

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![Screenshot (49)](https://user-images.githubusercontent.com/122435989/211757013-afca079b-c42b-40cb-9759-9b2c2b2bf190.png)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

OpenToonz 1.6 (Build Dec 16 2022)

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Thanks for the report @eren0002 
Sorry to hear you are crashing.

We'll need additional information here to be able to address your issue.
Hopefully you are able to reload your scene and keep working.

**Comment by RodneyBaker** [comment]
@eren0002 
I am closing this report as not containing enough information to move forward with.
We do however want you to be able to resolve any and all issues you are having.

As such I'll recommend joining one of the Opentoonz discords (or other social platforms where Opentoonz has reprensentation of users) as that is the most likely way to troubleshoot problem; in the case of discord chat... live and with immediate feedback as necessary.
