### ISSUE TITLE
Record Audio doesn't see my mic

### ISSUE THREAD

**Issue by Galina49** [opentoonz/opentoonz#4708]
### Description

Record Audio doesn't see my microphone, it gives me one option "Default". And it doesn't record audio at all. Operation system Ubuntu 

### Steps to Reproduce

1. Create project
2. Click Windows -> Record audio

### Expected Behavior

Click on the red button and see the line moves, and then at the end see how it appears in a column

### OpenToonz Version

1.5

### OpenToonz Version Information

26.08.2022

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by andeon** [comment]
Try installing both the "good" and "bad" gstreamer plugins and see if that fixes the issue.

https://github.com/opentoonz/opentoonz/issues/3827
