### ISSUE TITLE
Bug/Error in the color tool

### ISSUE THREAD

**Issue by Davsito** [opentoonz/opentoonz#4711]
### Description

[ENG]
I am a regular OpenToonz animator and for a couple of months I have been seeing an error in the color tool.
When I try to give color to a scene, regardless of what tool it is with (paint bucket, brush, etc.) It always appears black, even if I put a pure white or a saturated color, I don't know if it's a configuration problem or this doing something wrong, however, this did not happen to me before.
If anyone knows what can cause this problem, I would appreciate it if you could share that information with me.
Thank you very much in advance!
[ESP]
Soy un animador habitual de OpenToonz y hace un par de meses vengo viendo un error en la herramienta de color.
Cuando intento darle color a una escena, sin importar con que herramienta sea (cubo de pintura, pincel, etc.) Siempre me aparece de color negro, aunque ponga un blanco puro o un color saturado, no se si sea problema de configuración o este haciendo algo mal, sin embargo, esto antes no me pasaba.
Si alguien sabe que puede provocar este problema, agradecería que compartieran esa información conmigo.
¡muchas gracias por adelantado!

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/122960529/213099008-5cca2ae9-b544-46ad-b0cc-6e9286031dff.png)

### OpenToonz Version

1.5

### OpenToonz Version Information

built Apr 10 2021 22:02:43

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by konero** [comment]
Open the view menu and see if you have **Fill Check** or **Transparency Check** enabled. If so, turn them off.

**Comment by RodneyBaker** [comment]
Hopefully the problem is what @konero mentions.

I note that you are using a very old version of Opentoonz and as such I will recommend updating to the latest nightly release to test and confirm your error... not to mention to update the software and move past many bugs and to gain features.

If you are building yourself that should be noted in your report.
I note that current windows github action builds have this same problem with all colors being black and this likely relates to build libraries.

**Comment by Davsito** [comment]
[ENG]
TYSM!!!
I really did not know that I had this option enabled and they saved the project I was doing, I was seriously thinking about uninstalling and reinstalling the app, thank you very much!
And by the way, as @RodneyBaker aker said I'm going to update my version, I forgot to do it.
again, thank you both!
[ESP]
TYSM!!!
La verdad no sabia que tenia habilitada esta opcion y ustedes me salvaron el proyecto que estaba haciendo, estuve pensando seriamente en desinstalar y reinstalar la app, muchas gracias!
Y por cierto, como dijo @RodneyBaker er voy a actualizar mi versión, se me olvidó hacerlo.
de nuevo, gracias a los dos!

![image](https://user-images.githubusercontent.com/122960529/213612542-58c97e0d-5eb6-4c22-9285-97537d9d07e0.png)

**Comment by RodneyBaker** [comment]
Glad to hear you got it worked out.
Keep on animating!
