### ISSUE TITLE
User Interface (UI) Scrub

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4713]
With the release of v1.7 only a few months away now is an ideal time to scrub through reports related to Opentoonz UI and to determine what will be in the next release and what needs to go back to the drawing board in hopes of getting into a later release.

Here is a listing of all reports tagged with 'UI':
https://github.com/opentoonz/opentoonz/issues?q=is%3Aopen+is%3Aissue+label%3AUI

Interface changes are often contentious so understand that changes to current room sets, themes and customization will be more difficult than changes to newly created ones that are optional for user to choose from.

Please join in the discussion.  :)

**Comment by DarrenTAnims** [comment]
The issue I wanted to raise isn't directly a UI issue, but it causes UI issues over and over. I've added a Feature request for it:
https://github.com/opentoonz/opentoonz/issues/4717
Change the install option to ALWAYS overwrite user menus (and add an option for updating rooms)

**Comment by RodneyBaker** [comment]
Because bugs should be a priority...

[Link to listing of all open reports tagged with both BUG and UI](https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+label%3AUI+label%3Abug+)

**Comment by RodneyBaker** [comment]
Collecting some reports that (more or less) generically request updates to the user interface.
These requests are often recurring and where possible the community should endeavor to find a means of customization and branding to assist in facilitating the requests.

Beyond customization, the look development of each release should be considered and carefully weighed in light of current usage versus changes to improve user workflow and experience.

|| Area of Interest  | Reporting   | Description|Notes  |
|-----:| :----------------:|:----------------| :---------------------------------|:-------------------|
[⚫ | Program Icon  | #4722 | OT icon is outdated? |General Interest and personal learning|

**Comment by RodneyBaker** [comment]
There is a need to scrub the 'Known Issues' to determine status and whether there is a clear path forward.
Additionally, determine how best to deal with these issues given many may never be resolved.

REF:  [Reports tagged with Known Issue](https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+is%3Aopen+label%3A%22known+issue%22)

**Comment by RodneyBaker** [comment]
Closing as largely complete for v1.7 release cycle.
