### ISSUE TITLE
Icon update request

### ISSUE THREAD

**Issue by Chris-Aitan** [opentoonz/opentoonz#4722]
### Is your feature request related to a problem? Please describe

I love Opentoonz but the icon seems a bit **outdated**...

### Describe the solution you'd like

I created a possible new icon here
If you like it please contact me on my Instagram, [https://www.instagram.com/chris.aitan/](url). I would love to contribute more in designing as it will help me learn and i use opentoonz a lot!
![OpenToonz icon](https://user-images.githubusercontent.com/123502198/214395121-af738104-a24e-4baf-82d3-2b7b47f5878e.png)

**Comment by RodneyBaker** [comment]
You might wish to review some of the earlier requests that mirror your own.
For example:

- [ ] #3710

**Comment by RodneyBaker** [comment]
@Chris-Aitan Closing this report but keep an eye out for the next UI scrub (probably in the Oct/Nov timeframe but also ongoing even now).

Feel free to continue the discussion on updating of icons here or in othe related reports.
