### ISSUE TITLE
Can't drag to play animation in latest version of nightly build..

### ISSUE THREAD

**Issue by gngugnniokl** [opentoonz/opentoonz#4729]
### Ask a question related to OpenToonz

In older versions of opentoonz there used to be a bar to play animations
![image](https://user-images.githubusercontent.com/75842539/214940406-1addf7f0-7f14-4739-8a3e-a89bf84ddbc3.png)

But there isn't anymore
![image](https://user-images.githubusercontent.com/75842539/214940204-e0a08e05-739c-42a2-818f-b03aa1e5419b.png)
Why has this feature been removed? If it hasn't how can I re-enable it?

**Comment by RodneyBaker** [comment]
I had that disappear on me as well.
That can be turned on via Right Click on the Viewer and checking the box to turn on/off the Frame Slider
`Right Click > GUI Show / Hide > Frame Slider`


![image](https://user-images.githubusercontent.com/2576432/214944177-47f5d618-30e4-4263-a35e-7a40faa37e09.png)

**Comment by RodneyBaker** [comment]
This is an issue that likely needs to be addressed as it is a frequently asked question of late.
It isn't clear exactly where (e.g. in which nightly update) the Frame Slider option was turned off.

**Comment by RodneyBaker** [comment]
Tagging as bug as this appears to be a change that likely needs to be reverted.

**Comment by RodneyBaker** [comment]
@gngugnniokl The latest nightly release should restore the Frame Slider's default to being on.
It may require a clean install.

Apologies for the incovenience and thanks for the report that helped identify the problem.
