### ISSUE TITLE
Download OpenToonz 1.0.3, crashes on startup 

### ISSUE THREAD

**Issue by ShamelessMagic** [opentoonz/opentoonz#473]
Been having trouble opening up OpenToonz with the latest version, especially when the program was lagging for me earlier and I had to reinstall. This message keeps popping up: 
https://gyazo.com/861b1553c5b0341f141cc498caeebcd3 
- Checked my graphics and monitor drivers, everything seems to be up-to-date. 
- Tried opening the program with and without my dual monitor (my drawing tablet), nothing. 
- Reinstalled several times, nope. 
- The lvcod64.dll was not found in any of the folders. All the folders are in the default locations.
- As far as I know, the version on the Download page reads 1.0.3 but the downloaded file's properties read 1.0.1

**Comment by turtletooth** [comment]
Is this still an issue?  Do you have any Blackmagic Design software or Camtasia installed?  Have you tried the portable version?

**Comment by ShamelessMagic** [comment]
I still have the issue where OpenToonz crashes upon opening the software. I do not have Blackmagic Design or Camstasia installed. I am unsure about how to use the portable version, although I much prefer to work on my laptop and monitor. Recently I tried installing OpenToonz again and received the same outcome. 

--Alyssa W 

    On Monday, January 30, 2017 11:37 PM, Jeremy Bullock <notifications@github.com> wrote:
 

 Is this still an issue? Do you have any Blackmagic Design software or Camtasia installed? Have you tried the portable version?—

**Comment by turtletooth** [comment]
Can you try this version:  https://github.com/turtletooth/OpenToonzPortable/releases
It is a version that still works on a laptop or desktop but doesn't require installing.

**Comment by ShamelessMagic** [comment]
I downloaded the Portable but it stops working and doesn't open the program at all. 

--Alyssa W 

    On Tuesday, January 31, 2017 12:12 PM, Jeremy Bullock <notifications@github.com> wrote:
 

 Can you try this version: https://github.com/turtletooth/OpenToonzPortable/releases
It is a version that still works on a laptop or desktop but doesn't require installing.—

**Comment by turtletooth** [comment]
What version of Windows are you running?  Is it 64 bit?

**Comment by ShamelessMagic** [comment]
It is a Windows 7, 64 bit. 
--Alyssa W  

    On Wednesday, February 1, 2017 12:57 PM, Jeremy Bullock <notifications@github.com> wrote:
 

 What version of Windows are you running? Is it 64 bit?—

**Comment by turtletooth** [comment]
If this is still an issue, do you have Service Pack 1 installed?

**Comment by humming9** [comment]
I recommand you to show opentoonz installation tutorial. Here is web site address  https://youtu.be/_5MAdh8y0fs

**Comment by RodneyBaker** [comment]
@ShamelessMagic can you provide an update on this.
Your issue should be resolved via a current release.

**Comment by RodneyBaker** [comment]
Recommend closing as the fix to this issue is to update to a more current release of OpenToonz especially as the report has not been updated by @ShamelessMagic in two years.   If someone still using v1.0.3 can confirm the problem recommend the issue remain open with workaround of updating noted.

**Comment by RodneyBaker** [comment]
No response or similar recurrence of issue since Nov 2017 even after attempts in May and July of 2018 to determine status from original poster of issue @ShamelessMagic .

Recommend closing.
