### ISSUE TITLE
Brush tool option [Draw Order] for Toonz Vector level

### ISSUE THREAD

**Issue by jcome** [opentoonz/opentoonz#4732]
### Describe the solution you'd like

In Toonz Raster level, the brush tool has "Draw Order" option  (Over All, Under All and Palette Order), can we expect to have it available in Toonz Vector level as well?

**Comment by RodneyBaker** [comment]
You may find some answers to your question in this issue (as well as those it links to):  #3549

The short answer being: Yes, but...

**Comment by jcome** [comment]
@RodneyBaker thanks for the info. let me close this duplicated one.
