### ISSUE TITLE
Not changing colour to what I want

### ISSUE THREAD

**Issue by rookiecartoonguy** [opentoonz/opentoonz#4734]
### Description

Hi all, I have just started learning how to make a cartoon. I have had many problems, but I am not losing hope yet.

I have made green for the grass, blue for the sky, a yellow sun, and white clouds. Now when i freehand draw a brown horse, it auto fills it to white. And I have the brown colour clicked? Iam even freehand drawing in the brown colour but it ends up white?

![image](https://user-images.githubusercontent.com/124423897/216753207-a37b3887-7b19-4baf-9c29-12a01d01bf91.png)

Infact now its showing a tiny bit of white and not filling it?

![image](https://user-images.githubusercontent.com/124423897/216753241-ccf20514-3993-4225-9bb5-4b7d30f51a76.png)

Now i have filled the space with a brown colour and it turns white?

![image](https://user-images.githubusercontent.com/124423897/216753263-e8e96ea7-e1c8-4c3e-ba70-f811ca07f634.png)

If anyone can help me out here it would be amazing!

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hi @rookiecartoonguy 
There may be multiple things going on here that prevent getting what you want but the immediate thing I see is that your brown color is entirely transparent.  

If you look at the Alpha Channel (matte) value you'll see it is set to a value of 0 (zero).
Any color that is fully transparent will therefore be transparent and allow us to see all the way through to the background... which we might assume here to be... white.

![image](https://user-images.githubusercontent.com/2576432/216756895-a15cd447-67a4-4195-9eb7-e2ffbe9e5a83.png)

Try cranking that value up to 255 (fully opaque) and see what result you get.

**Comment by RodneyBaker** [comment]
Closing as an issue that should be easily resolved with a little troubleshooting.
@rookiecartoonguy Please let us know if this is not the case and we need to look more deeply into the problem.

Recommend also joining one of the Opentoonz venues where others will troubleshoot issues such as these in real time.
There are several Opentoonz discords, reddit, facebook etc.

**Comment by rookiecartoonguy** [comment]
thanks so much for your help! I have made great progress today making a
cartoon! I am nearly finished all the scenes, just need to add the mouth
movements and see how i get on!
