### ISSUE TITLE
crashing while rendering

### ISSUE THREAD

**Issue by Savidh** [opentoonz/opentoonz#4740]
### Ask a question related to OpenToonz

![important](https://user-images.githubusercontent.com/98796983/217130315-975b7f1e-bbe0-4ce6-998f-90334aa66f87.PNG)

**Comment by RodneyBaker** [comment]
@Savidh There is not enough information in this report to diagnose the problem.
I'll recommend joining the Opentoonz discord (or other Opentoonz online venue) where you can troubleshoot your project.

This is the link to one of the discords:  https://discord.gg/UQxvYBKW5U
(Disclaimer:  I am a moderator in the one I am linking)

**Comment by RodneyBaker** [comment]
Closing at this report doesn't include actionable information and there are other reports open related to rendering crashes.
@Savidh Thank you for your report and if you have any additional information to share please do let us know.
