### ISSUE TITLE
drawing tools are not working

### ISSUE THREAD

**Issue by Anesberg** [opentoonz/opentoonz#4741]
### Description

whean i draw something i cannot repair to make it smooth, so when i need some tools for example control point editor, it is not function. im using windows laptop with 8gb Ram anyway.

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![Screenshot_20230207_045215](https://user-images.githubusercontent.com/124664906/217188832-fd34625a-deae-49c9-97b6-3789b32d3a79.png)

control point editor tools, pinch tool and many more is not working

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The Control Point Editor only works with vector levels.
The error message states that you are using a toonz raster level.

Therea are three basic kinds of image level; raster, toonz raster and vector.
All three can be used in the same frame (placing them in different columns of the xsheet... or rows in the timeline).
Each has unique qualities which allow for use of different tools.

**Comment by RodneyBaker** [comment]
Note that in Preferences we can set the tools to only be active if the level we have selected is of the proper type.
Tools then will only appear active/enabled if we are on the correct level.

![image](https://user-images.githubusercontent.com/2576432/217248914-7dec7598-2647-4132-b7b8-37c91cdb5099.png)

**Comment by Anesberg** [comment]
but i need that tools... so how i can use that tools

**Comment by Anesberg** [comment]
allright thank

> The Control Point Editor only works with vector levels. The error message states that you are using a toonz raster level.
> 
> Therea are three basic kinds of image level; raster, toonz raster and vector. All three can be used in the same frame (placing them in different columns of the xsheet... or rows in the timeline). Each has unique qualities which allow for use of different tools.



Thank you for your help. i found it
