### ISSUE TITLE
save the character and can be used again for another scene

### ISSUE THREAD

**Issue by Anesberg** [opentoonz/opentoonz#4744]
### Ask a question related to OpenToonz

how do I save a character that has been created in opentoonz and can be used again for scene by scene in making a cartoon movie?

**Comment by RodneyBaker** [comment]
@Anesberg The character will be in a 'level'.
A level is either a sequence of image files or a single file that contains all those images (in the case of toonz raster and toonz vector levels).

Use that level in any scene you wish to use that character in.

**Comment by RodneyBaker** [comment]
Transferring this to Opentoonz docs.
