### ISSUE TITLE
Why can't I load pictures as 16/9 backgrounds?

### ISSUE THREAD

**Issue by Dineeeyd** [opentoonz/opentoonz#4745]
### Ask a question related to OpenToonz

When I start dragging and dropping the 16/9 backgrounds onto the scene and for some reason nothing works, the program just asks "export, load or cancel". But when I drag and drop images as 16/8, 1/1, etc. everything works and the pictures drag and drop and work. What is the problem?

Also, is it possible to use an 8K quality scene? Just wondering since I have 8K quality backgrounds.

Thanks in advance :)

**Comment by RodneyBaker** [comment]
@Dineeeyd 
Are you sure that doesn't read "Import, Load, Cancel' as the options?
This is normal when opening any image as Opentoonz wants to know if you want to Import (that is to say... make a copy of the current image and place it in the Opentoonz stuff directory) or to Load (this is to say... reference the image at it's original location.

If you can share more information... perhaps a screenshot of what you are seeing... that will be greatly appreciated.

**Comment by Dineeeyd** [comment]
> @RodneyBaker

a little wrongly formulated question. i wanted to say that when this window "export, load or cancel" appears i press any button nothing happens and the scene remains empty and how and why this happens i do not know here below is a screenshot may you understand. :)

![Снимок экрана (898)](https://user-images.githubusercontent.com/125077296/218295962-020fe1f1-4895-4905-a105-54b2a4c7b298.jpg)

**Comment by RodneyBaker** [comment]
The only  thing that comes immediately to mind is the name of the image.
Opentoonz prefers a specific naming convention and special characters are usually to be avoided.
I see two potential problems with your image's name; special characters and... numbering.
While Opentoonz will load images with these in some cases its best to avoid them while troubleshooting issues.
Then when things are working well... explore what filenaming and numbering you can also use.

Not required but... the recommended format:  imagename.0001.png

If you ever forget... render out a sequence of images with Opentoonz and it will render into that filenaming convention.

Try a simple filename and see if that works.

**Comment by RodneyBaker** [comment]
@Dineeeyd Have you had any success loading your images yet?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Dineeeyd please let us know if you are still experiencing difficulties.
