### ISSUE TITLE
Various issues.

### ISSUE THREAD

**Issue by coffseducation** [opentoonz/opentoonz#4746]
### Description

1. Lag: Activating nodes can take 5-20 seconds to respond.
2. Eraser: Not working. Cannot erase textures.
3.  Freeze. Constant freezing and crashing.
4.  Fill: Overspills randomly outside of bounded area.
5.  SVG: Cannot import svg from Inkscape. SVG's are either all black or if filled then imported with separate locked parts of different sizes.

I understand this is mostly unhelpful without a more comprehensive bug report. Please advise on how to provide more detail.

Operating System: Kubuntu 22.10
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.6
Kernel Version: 5.19.0-31-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: Dell Inc.
Product Name: Precision 5520

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Thanks for the report @coffseducation 
I've no doubt there are some bugs in what you are beginning to describe but I've untagged this report as bug as there isn't any actionable bug to squash (as of yet).

What we can do is delve more deeply into the troubleshooting process and use that to report bugs that can then be addressed.

This will perhaps be especially helpful as there is no official support for Linux and the community has to rise to the challenge of smoothing out the rough spots.

In reading your list I note many familiar areas of interest but don't know specifically whether those are currently captured in other reports.  Some likely are but might not specifically address the issues you are observing.

I've taged this report as troubleshooting as we need to gather additional information.
One way we can do this is to work through the various issues in other venues such as Opentoonz discord etc.
There bugs can be confirmed and suggestions can be made for honing in on specific bugs.

That exploration can continue here as well although it may take longer as not everyone is willing or able to post to github to provide the feedback necessary to build detailed reports.

**Comment by RodneyBaker** [comment]
Here are my thoughts after an initial look at your listing:

1.  Node Lag  (Not sure if this is mostly Linux releated as there are many variables here)
2.  Eraser (Depending on what level type and brushes you are using this might be a limitation of the level type you are currently using.  Trying a different level type might resolve the issue)
3. Freezing/Crashing (Need more specific information to be able to provide feedback)
4. Fill Overspill (A number of things come to mind here and some specific information such as screen recording will help tremendously in seeing what you are experiencing)
5. SVG has a number of issue which have open reports... Linux might have additional issues as well.  The issue with GIMP SVGs sounds familiar and that should be resolveable by examining the settings used exporting the SVG from GIMP)

**Comment by RodneyBaker** [comment]
Here's all the current open reports that are deemed to specifically relate to Linux:

https://github.com/opentoonz/opentoonz/issues?q=label%3Aos-linux+

Some of those might not relate to your specific version (Kubuntu 22.10).

It would be good to know more about the specific build on Linux you are using.

**Comment by artisteacher** [comment]
For the eraser, it might be worth checking if it's set to erase lines, areas, or both.

**Comment by RodneyBaker** [comment]
Concerning SVGs there are two types of SVG that Inkscape exports; one that attempts to be as conformant to SVG v1.1 and the other a custom SVG designed for use with Inkscape and (I believe) targeted to be compatable with SVG v2.0.

Of these two the Inscape version likely will not be compatible with Opentoonz although I have a vague memory of it still opening in Opentoonz when I tried.   The standard SVG format should open although we need to document current shortfalls.

**Comment by RodneyBaker** [comment]
I'm curious if some of the improvements to SVG import resolve issues identified here.
@coffseducation Any updates you can share?

**Comment by RodneyBaker** [comment]
Not sure of the status of these various issues so will close.
@coffseducation Please feel free to add additional information and/or open new reports as you deem necessary.

I'm tempted to move this report to Opentoonz-Docs as some of the issues do have workflows that can and should be documented.
