### ISSUE TITLE
Image does not import or load correctly.

### ISSUE THREAD

**Issue by prandygame** [opentoonz/opentoonz#4759]
### Description

I have a problem when importing an 8000x1080 image, it is cropped, even though I change the size of the level, what I want to achieve is that the image moves while the character walks forward, I would also like to know how to do that the image moves from one point to another I tried it with a keyframe at the beginning and then another at the end and I moved the image to the final position and nothing happened.

### Steps to Reproduce

1. Create an image tier, select a frame, drag the image onto the canvas, load it, and then resize the tier to make it look custom.

### Expected Behavior

That the image does not look cropped.

### Screenshots, Video & Crash Logs

The image is pushed and cropped.
![image](https://user-images.githubusercontent.com/60197201/222486574-6923b70c-2727-45ad-8ba9-a3ac0996a8d2.png)

This is the image I upload.
![image](https://user-images.githubusercontent.com/60197201/222487120-0102a8d4-4e46-419a-b072-15b296f149c9.png)

Mysteriously after uploading the image Opentoonz damages the original file and crops it, it's like it pushes it.
![image](https://user-images.githubusercontent.com/60197201/222486834-a337f34f-84b0-47c5-94fe-3fd7dcc62894.png)

### OpenToonz Version

1.5

### OpenToonz Version Information

10 April 2021

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by DarrenTAnims** [comment]
I can't see what the problem with your image could be. The image doesn't appear to be cropped as such, but that it's shown docked into the camera view, but you've, ironically, cropped the screenshot, so I can't see the timeline. I'm guessing you either:
- Created a level and tried to import your image to it
- or you used the selection tool to move the image.
But without a video showing how you imported the image, I'm just guessing.

Finally, moving your background is a matter of using the animate tool, as you suggestions. Place a key at the start frame. Go to the last frame and move your column with the animate tool and it'll add another key. Then if your default interpolation is any but constant, you'll see movement.

**Comment by prandygame** [comment]
@DarrenTAnims Well, I fixed it, the problem is that I was trying to animate the image by moving the image from left to right with keyframes, but I moved it with the selection tool, when moving it it was cropped and then I found out that I had to move it with the animate tool, which was silly of me, however, it's funny how the image gets damaged or cropped out of the level's size range when you drag it outside of it, and not as if it were a mask, Curiously, the cutting effect is also done in the image outside of opentoonz, I don't know if it's normal for that to happen, but I'll let you know just in case.

**Comment by artisteacher** [comment]
That's a normal feature of raster levels in every program I've used. Any part of a selection moved off the canvas always gets removed. If you loaded the image rather than importing, the changes you saved will apply to the image in the original location. To prevent that, import instead.

**Comment by DarrenTAnims** [comment]
@prandygame
"the problem is that I was trying to animate the image by moving the image from left to right with keyframes,". If you're using the selection tool, you're not using any keyframes. Keyframes are only added when you animate with the Animate too. I wish you'd said you was using the selection tool in your original post.
But yes, as artisteacher says, using the selection tool to move an image that has already got its size set (set when importing) is perfectly normal. The raster canvas isn't infinite, so there is a border.

**Comment by RodneyBaker** [comment]
Will close as a troubleshooting issue but please feel free to continue discussion and exploration here.
