### ISSUE TITLE
﻿Change checkbox option to button in Tool Option Bar

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#476]
I think with this doing, Tool Option Bar display clear.

![checkbox-to-button](https://cloud.githubusercontent.com/assets/16509592/16186718/531cdf10-36e1-11e6-9722-baea0c9b4ad7.jpg)

**Comment by blurymind** [comment]
that is a good idea, might save some horizontal space and also add more clarity.

**Comment by 2dvision** [comment]
Oops :)
Maybe change color button to OT green helpful.

![checkbox-to-button2](https://cloud.githubusercontent.com/assets/16509592/16202049/5be76f64-3729-11e6-86e2-5d961a7eaca1.jpg)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
