### ISSUE TITLE
Red Frames and Missing Animation. Yet the File is not missing, and "Save All Constantly"

### ISSUE THREAD

**Issue by gidicent** [opentoonz/opentoonz#4767]
I tried to follow directions from Darren T's Video on red frames on the 3rd reason why and seem to not get any result.

I didn't add any images.

I didn't get a file from someone else. this is my original artwork.

I don't find the file to be in a different directory.

I constantly do save all and do many new vectors. 

![Screenshot (4)](https://user-images.githubusercontent.com/121685838/224039911-208d2d01-96a4-445c-a3b6-55677dfa6084.png)
Here's my Red Frames which should go up to 40 but only reached 21 Frames.

![Screenshot (5)](https://user-images.githubusercontent.com/121685838/224040745-daa8e686-2e4f-45a7-b42c-6dffd00e0f0f.png)
I've right clicked to check if the file exist, and it does.

![Screenshot (8)](https://user-images.githubusercontent.com/121685838/224041325-0992c873-97ce-416f-8cf3-1f150dc641b4.png)
I went to put in 15 backup files

![Screenshot (6)](https://user-images.githubusercontent.com/121685838/224041860-22d114c0-1c37-4e5a-83be-0ec00f8d58bc.png)
I renamed the backup file and erased bak. I renamed the original file to put in my initials. 

I then went to "Open Recent Scene FIles" and I haven't found any changes. 

I hope this is just super simple and maybe I'm missing something. 

Also missing a drawing in some frames and I don't know how.
![Screenshot (10)](https://user-images.githubusercontent.com/121685838/224044837-fda308b5-1267-4070-a5ad-db88724f9ef8.png)
This is frame 21 which the old man is present

![Screenshot (11)](https://user-images.githubusercontent.com/121685838/224044986-b1ebc0ef-f6d9-4f19-8663-3579694e1d98.png)
Then he is missed on frame 22 and so on. He's on the same pose throughout the rest of the frames. Again I hope this is an easy fix. 

Would super appreciate it if someone could help.

**Comment by DarrenTAnims** [comment]
Thanks for the clear report, with images. They really help. I can see that your level file is on disk. And because some of your drawings are showing their numbers in white, they show that the level file is loading. Having just "some" numbers in red just signifies to me that those drawings were created, the scene file was saved, but the levels weren't. Either you didn't hit save all or the program crashed part way through. So unless a backup file has those drawings, they're lost. Sorry.

**Comment by gidicent** [comment]
Thank you!

**Comment by gidicent** [comment]
Just last question. I tried to re due it by making a new vector to start off on the beginning red frame and onward. I then Saved All, exit, and went back and it's still having red frames. 
Likewise with the old man. I just copied and pasted him and put him in the frames he was missing. Saved All, exit, and went back and it's still missing. 

How can I be able to get them back by just drawing them again?

**Comment by DarrenTAnims** [comment]
Have you check if the files are actually on disk?
If not, it could be your virus checker stopping them being saved.

**Comment by RodneyBaker** [comment]
Keep in mind that the cells in the xsheet/timeline are just exposures.
They point to a file on the harddrive.
So... we need to remove any bad exposures in order to place new/good ones.
This specifically if the exposures are pointing to a source that is no longer there.

**Comment by gidicent** [comment]
Thank you guys!
