### ISSUE TITLE
﻿Change brush size with Alt+RightClick

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#477]
OT can change brush size with hold Alt and move mouse pointer. But when use shortcut with Alt key, Maybe you change brush size mistake. Adobe photoshop use Alt+RightClick for that.

Maybe need new function for change Min/Max size separately. (move horizontal and vertical mouse pointer)

![brush size](https://cloud.githubusercontent.com/assets/16509592/16186844/1cd9fa04-36e2-11e6-9dee-e0018104a066.gif)

**Comment by animking** [comment]
yes, this is a good idea :)

**Comment by blurymind** [comment]
It should be configurable. It used to be ctrl and it was extremely
annoying. People thought it was a bug. Every time you ctrl+z a brush stroke
you made, it would accidentally change the size of your brush. I wouldn't
use a modifier key for this. Using alt will interfere with something for
sure

**Comment by nittolo** [comment]
Under the Tool Modifiers tab of the Configure Shortcuts window, there's listed shortcuts to change the min and max brush size. However, they don't really seem to do anything. Do these actually work for anyone?

**Comment by blurymind** [comment]
the ones in the modifier tab seem to be incremental increase/decrease. The one proposed here is based on cursor position - while a button is held.
As said before- toonz already has this functionality in harlequin- it is set to use the ctrl key. That is a terrible design choice, because almost always after making a wrong stroke and ctrl+z it - the software resizes the size of your brush to some ridiculous amount. It was is a problem still in harlequin i think. I am glad opentoonz removed it.

But I agree on the sentiment that having the option to give it a specific modifier key (like a letter on the keyboard, anything but ctrl,shift or alt) would be better than completely removing it.

As for incremental resize of brush values- that is well caught bug. it does not work.

**Comment by konero** [comment]
in Corel Painter and Clip Studio Paint they use **Ctrl+Alt**+_Click&Drag_ to resize the brush, always worked well for me.

![csp_ca](https://cloud.githubusercontent.com/assets/19820721/16198220/0a02efd8-36fd-11e6-8664-961ac31397ca.PNG)

**Comment by blurymind** [comment]
That sounds like a good default as it wont interfere with undo, redo and
viewport navigation

**Comment by blurymind** [comment]
But it should be configurable for sure

**Comment by adamearle** [comment]
Krita handles this workflow really well. Much better than photoshop in my
opinion

Adam Earle

**Comment by turtletooth** [comment]
I was looking at this code yesterday.  It doesn't look like it would be too hard to implement.  I am out and won't be able to touch it for a bit, but it shouldn't be too hard.

**Comment by inkapnea** [comment]
I agree with @adamearle, Krita does it really well:
Shift+LeftClick & Drag (to the right for increase, to the left to decrease).

I don't see the need to use multiple modifier keys or the right mouse button.
Shift+LeftClick & Drag is really simple but difficult to trigger by accident, try it.

The modification to individually change the Min/Max radius could be added to OpenToonz , as @2dvision suggested, with:
Left/Right Drag - Max size decrease/increase
Down/Up Drag - Min size decrease/increase

It shouldn't take too much to train your muscle memory to use this, and it stays very close to another piece of great FLOSS software. Consider the overlapping user base, too.

**Comment by turtletooth** [comment]
I made a  PR for this issue on #685.  Right now it uses Ctrl + Alt as the trigger keys to be consistent with Painter and Clip Studio Paint.  Mouse up/down changes max value, mouse left/right changes min value.  I like Krita, but the way the brush tool is configured right now, clicking whether or not there is a modifier key actually paints.  
@blurymind this isn't configurable yet, but Ctrl + Alt are easy to reach on both mac and windows keyboards, so it should still be usable.

**Comment by df-0** [comment]
Hey, it's great having a brush-size shortcut that works like this - but perhaps should also work consistently for the eraser? 'U' & 'I' work for the eraser but not CTRL+ALT
