### ISSUE TITLE
Audio in Fast Render to MP4 Extremely Boosted

### ISSUE THREAD

**Issue by deathchimera** [opentoonz/opentoonz#4779]
### Description

Resulting files from Fast Render to MP4 have their audio maxed out, probably even more than what's allowed normally. This is on linux, though it's surprising I haven't heard anyone else address it, considering how long it's been like this in the nightlies.

### Steps to Reproduce

Fast render to MP4 with an audio level on linux.

### Expected Behavior

The volume to be set at the percent chosen on the level.

### Screenshots, Video & Crash Logs

(SERIOUS VOLUME WARNING)

https://user-images.githubusercontent.com/77942602/224632787-73a3a28f-2b1c-41a7-b642-21376d669fc2.mp4

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Latest, built Mar 13 2023

### Operating System

Linux

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Interesting.

I don't use  the Fast Render to MP4 feature often and when I have I have rarely done so with audio included.
As such I was fully expecting to run into the same issue.
But, in my tests I don't see anything amiss with audio using that means of output.

I'll tag as a Linux issue until we find out more about the problem.
There are several things you can do to assist in the problem solving.
For instance if you can Export an example scene that has the problem that will make sure we are seeing the exact thing you are.  If you have access to another computer I'd also suggest test on that to rule out something localized to your current system.  

I do at this point suspect this might be Linux related but hopefully we can get other on PC, Linux and Mac to confirm.

I think I'll try to incorporate use of Fast render to MP4 for my weekly drawing sessions with my niece.
Here a result adding audio to yesterday's session that exported fine (but on WIndows):

https://user-images.githubusercontent.com/2576432/224706806-31adbfd5-bf74-4906-af21-2c99e9bb5dd3.mp4

**Comment by deathchimera** [comment]
This scene only has the audio used in the example given, though it still distorts on Fast Render. Getting others to test would seem necessary.

[OT_AudioIssue.zip](https://github.com/opentoonz/opentoonz/files/10960957/OT_AudioIssue.zip)

**Comment by RodneyBaker** [comment]
Thanks for the sample file.
Yes, that renders fine for me via Fast Render to MP4.

I'm beginning to suspect this might be a Linux only problem but...
There are some other things you can check before we can conclude it is something in the source code itself.
For instance, you might download the latest FFMPEG... which by the way they just released v6.0 and I think the installers can still be a little hard to find.  I grabbed the releases from the FFMPEG github site as they weren't yet built via the regular FFMPEG download site.  They might be there now however.

**Comment by deathchimera** [comment]
Installed the latest FFMPEG, still has the same problem. Double checked the other dependencies as well, everything is up to date.

**Comment by deathchimera** [comment]
[Scene File (AudioRecordTest2.zip)](https://github.com/opentoonz/opentoonz/files/11008338/AudioRecordTest2.zip)

My system is running pipewire-pulse, and I'm not enough of an audio guy to know if it is partial to the cause of this issue. Sounds like something important to note though. 
My Fast Render audio. Same issue, it appears. 

================= AUDIO WARNING, AGAIN. ======================

https://user-images.githubusercontent.com/77942602/226102208-2724c5fe-b2cc-4449-9c43-771202534fee.mp4

**Comment by RodneyBaker** [comment]
We do need more Linux testers and developers for sure.

Thanks for looking into this.
We want to get a fix in by v1.7 release.

**Comment by RodneyBaker** [comment]
Just to clarify...

The extreme boost doesn't occur with when rendering out via Output Settings?

**Comment by justburner** [comment]
Strange this report show up 1 year after the patch, have people not been using OT on Linux for an entire year!?

Please try "Export Soundtrack" under "Export"... in preference with WAV extension, the resulting audio output is purely from OT.

**Comment by manongjohn** [comment]
Just to clarify, T2D did have 32bit support originally but I incorporated a number of changes made in @justburner's PR to somewhat synchronize the code.  I didn't necessarily take everything though and made modifications, where necessary for T2D's implementation.

Reviewing the changes I incorporated, I'm not entirely sure where the problem might be in OT.  T2D might have additional changes for 32bit support from its original implementation that is keeping it from having this problem.

**Comment by justburner** [comment]
The fact that "Export Soundtrack" is normal it means something strange is happening in the bridge between OT and FFmpeg on Linux only.

Anyway i don't recall messing with anything in regard to the bridging on that specific patch but that was 1 year ago so I'm not entirely sure... all this situation is very bizarre.

**Comment by manongjohn** [comment]
FYI...comparing T2D's changes and OT's changes, I found the issue by removing the difference in T2D and verifying it caused the same problem.  Missing a bunch of `break;` statements in one of the OT changes that was made.  I saw this while porting but ignored it.

I can't build/verify OT in linux at the moment so I'll submit a PR to fix it and will need to test the artifacts to verify.

**Comment by justburner** [comment]
> FYI...comparing T2D's changes and OT's changes, I found the issue by removing the difference in T2D and verifying it caused the same problem. Missing a bunch of `break;` statements in one of the OT changes that was made. I saw this while porting but ignored it.
> 
> I can't build/verify OT in linux at the moment so I'll submit a PR to fix it and will need to test the artifacts to verify.

Thanks into investigating the issue deeply!

**Comment by deathchimera** [comment]
Alright, it seems the Fast Render audio is dealt with, unfortunately the viewer / xsheet audio is silent, at least on my end. Bass boosted audio seems to have made a return in projects / scenes made before this commit. Recording audio often leads to Opentoonz freezing up after pressing record, and needing it's process to be manually killed, and I'm not sure changing devices entirely helps.

Running Opentoonz through a terminal, whenever I press play on the timeline, "error 2" spits out whenever the timeline is playing. Initially pressing play on the timeline spits out 11 instances of the error 'QAudioOutput(pulseaudio): pa_stream_write, error = Invalid argument", which appears to be consistent even if a new scene is created with new audio.

I'm *fairly certain* that the bass boosted xsheet audio is only played on scenes with audio made before this update, though I'll have to test a bit more to make sure this isn't the only instance the issue arises.

[Bass Boost Examples' Scene File (AudioFixIssue_OldScene.zip)](https://github.com/opentoonz/opentoonz/files/11011243/AudioFixIssue_OldScene.zip)

============================== EXTRA EXTRA SERIOUS AUDIO WARNING =============================

https://user-images.githubusercontent.com/77942602/226182606-b13f8d4a-f533-4266-b1be-c1a010158218.mov

**Comment by manongjohn** [comment]
It seems the problem is the audio file is 32-bit float  @ 48000 (per Audacity) however OT is reading it as 16-bit fixed  @ 44100.

**Comment by justburner** [comment]
The good old audio shenanigans on Linux.

> ~~It seems the problem is the audio file is 32-bit float @ 48000 (per Audacity) however OT is reading it as 16-bit fixed @ 44100.~~

Don't be confused with Audacity mixing format, the app always use 32-bits float for that regardless of the input format.

You can verify the format on OT itself by right-clicking the audio file and click "Info..."

**Comment by justburner** [comment]
> Especially since I initially found out (but then decided not to post because of story developments in this manner) that setting the format to float samples manually fixed column playback, but then messed up rendering.
`qFormat.setSampleType(QAudioFormat::Float)`

I  was hoping that MJ patch fixed that issue since the lack of breaks caused fall-through into the last case, that is, the Float format.
Are you all testing with up to date code after the MJ patch merge?

Sadly I can't help since i don't have access to a Linux system. (the only linux PC i had died several years ago)

**Comment by manongjohn** [comment]
Just realized that about Audacity...not much of a sound guy. lol

Just wanted to make sure it wasn't reading the file in wrong...and now realizing it's also an MP3 file and not a WAV file so it's being converted by ffmpeg first. 

I noticed in Windows, when the MP3 is loaded, it goes out to Frame 614, but on Linux, it only goes to Frame 460.  Makes me wonder if something about the ffmpeg conversion of the mp3 isn't right on Linux.

FYI, T2D on linux does have a similar issue with the scene, though the sound isn't boosted.
