### ISSUE TITLE
whole program became laggy on huion tablet display.

### ISSUE THREAD

**Issue by Milkmoo** [opentoonz/opentoonz#4781]
### Description

Opentoonz used to work fine on my tablet display, but out of nowhere became too unbearably laggy as a whole like the interface and using the pencil tool. Doesn't matter what display type i use on my tablet, its always the same. Opentoonz works fine on my laptop display with a mouse.

i have reinstalled huion driver three time the correct way, also cleared opentoonz cash, and have reinstalled it itself too mutiple times, same result. i got opentoonz from the pop!_shop.

other programs like krita works smoothly, and i keep my operating system, nvidia drivers and tablet driver up to date.

I use Lenovo Legion 5 15 (if needed spec info just ask) with debian Pop!_OS 22.04 LTS
My tablet is Huion kamvas pro 16 (2021)

red lines are with mouse(laptop display), blue lines are tablet+pen (tablet display)
![image](https://user-images.githubusercontent.com/112820974/224764474-a44a2049-b350-4b36-a0a4-1e4772005cef.png)

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### OpenToonz Version Information

1.6.0 Mar 25 2022

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
This may not cover the Linux side of the equation but here are other open reports related to Huion tablets:

https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+is%3Aopen+huion

**Comment by Milkmoo** [comment]
> This may not cover the Linux side of the equation but here are other open reports related to Huion tablets:
> 
> https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+is%3Aopen+huion


hello! I want to apologize as the problem is NOT with Opentoonz, but something to do with graphics! with further examinations, there seem to be a pattern of lag with all chromium based programs like google chrome and discord, I'm not sure if opentoons one of them but it worked, the solution; 
My default graphic settings was on "NVIDIA Graphics", switch to "Hybrid Graphics", and switch back to "NVIDIA Graphics". 

it's on more detail on here;
https://github.com/pop-os/pop/issues/2417
https://github.com/pop-os/nvidia-graphics-drivers/issues/61

**Comment by RodneyBaker** [comment]
Very interesting @Milkmoo   
Thanks for sharing your findings and closing the loop on this.
