### ISSUE TITLE
never on drawing only on cleanup

### ISSUE THREAD

**Issue by PandazSznx** [opentoonz/opentoonz#4782]
### Description

When I Start my drawing I noticed ats always on cleanup and never on drawing. Also, When going on drawing ot shows a color pie and not the animation that's supposed to be there. IS there a way you can fix it 

### Steps to Reproduce

1. I always Start on cleanup and not on drawing 
2. When on drawing it shows a color pie. ☹ 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by PandazSznx** [comment]
VERY HELPFUL

**Comment by RodneyBaker** [comment]
Will close this as not enough information to troubleshoot.
Please feel free to continue the discussion however.

@PandazSznx 
@gab3d makes a great point about troubleshooting and there are quite a number of different places where these kinds of issues can be addressed.  When posting it can help tremendously to provide screenshots*.

Please feel free to continue the discussion here however as well.




*On Windows there is the Print Screen key that can easily capture the current window.
