### ISSUE TITLE
Brush Error and Crash

### ISSUE THREAD

**Issue by JPJammin** [opentoonz/opentoonz#4784]
### Description

After leaving the program open and idle for at least an hour, when trying to make strokes with the brush tool (set to black), it was erasing the lines I had previously drawn in my frame. After a few seconds of this happening, Opentoonz crashed. During the few seconds while the error was happening, I was able to undo the "stokes" the brush tool made. So, it was erasing something accidentally and undoing that mistake. I was able to make new "strokes" after the undo, but it was still acting as an eraser. Other than the idling, I do not know what could have caused the issue.

### Steps to Reproduce

1.  Create frames and animate normally, using the brush tool to draw.
2. Leave Opentoonz open and idle for at least 2 hours. I think it remained open with my brush tool selected the whole time.
3. Attempt to create new lines and/or draw over the already-existing lines in the currently-selected frame with the brush tool.

### Expected Behavior

What I expected was to be able to draw with the brush tool. What happened was that it seemed to be erasing my likes.

### Screenshots, Video & Crash Logs

OpenToonz 1.6  (Build Mar 14 2023)

Report Date: 2023-03-15 22:21:13
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 20.6.0
CPU Threads: 12

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon Pro 560X OpenGL Engine
GPU Version: 2.1 ATI-4.6.20

Crash File: /Users/jhaneenjones/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20230315-222113.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: Animation Sketches
Scene Name: Color Line Processing Test
Project Path: /Applications/OpenToonz/OpenToonz_stuff/projects/Animation Sketches/Animation Sketches_otprj.xml
Scene Path: /Applications/OpenToonz/OpenToonz_stuff/projects/Animation Sketches/scenes/Color Line Processing Test.tnz

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   OpenToonz                           0x000000010e899ebb _ZN20CleanupPaletteViewer7setModeEb + 27
  3> 5   OpenToonz                           0x000000010e8f64bf _ZN19CleanupSettingsPane16updateVisibilityEv + 479
  4> 6   OpenToonz                           0x000000010e8f6141 _ZN19CleanupSettingsPane9updateGuiEP17CleanupParametersS1_ + 625
  5> 7   OpenToonz                           0x000000010e8f5acc _ZN19CleanupSettingsPane9showEventEP10QShowEvent + 332
  6> 8   QtWidgets                           0x0000000111a3ad69 _ZN7QWidget5eventEP6QEvent + 1161
  7> 9   QtWidgets                           0x0000000111ae2a8b _ZN6QFrame5eventEP6QEvent + 43
  8> 10  QtWidgets                           0x0000000111a0152d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
  9> 11  QtWidgets                           0x0000000111a028f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 10> 12  QtCore                              0x0000000112e657f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 11> 13  QtWidgets                           0x0000000111a39aed _ZN14QWidgetPrivate11show_helperEv + 413
 12> 14  QtWidgets                           0x0000000111a3a724 _ZN14QWidgetPrivate10setVisibleEb + 804
 13> 15  QtWidgets                           0x0000000111a39d34 _ZN14QWidgetPrivate12showChildrenEb + 340
 14> 16  QtWidgets                           0x0000000111a39998 _ZN14QWidgetPrivate11show_helperEv + 72
 15> 17  QtWidgets                           0x0000000111a39d3b _ZN14QWidgetPrivate12showChildrenEb + 347
 16> 18  QtWidgets                           0x0000000111a39998 _ZN14QWidgetPrivate11show_helperEv + 72
 17> 19  QtWidgets                           0x0000000111a3a724 _ZN14QWidgetPrivate10setVisibleEb + 804
 18> 20  QtWidgets                           0x0000000111a23f95 _ZN14QStackedLayout15setCurrentIndexEi + 421
 19> 21  QtCore                              0x0000000112e97bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 20> 22  QtWidgets                           0x0000000111bb2ef6 _ZN7QTabBar15setCurrentIndexEi + 406
 21> 23  OpenToonz                           0x000000010e511eb8 _ZN13RoomTabWidget15mousePressEventEP11QMouseEvent + 232
 22> 24  QtWidgets                           0x0000000111a3aa82 _ZN7QWidget5eventEP6QEvent + 418
 23> 25  QtWidgets                           0x0000000111bb54e2 _ZN7QTabBar5eventEP6QEvent + 130
 24> 26  QtWidgets                           0x0000000111a0152d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 25> 27  QtWidgets                           0x0000000111a04424 _ZN12QApplication6notifyEP7QObjectP6QEvent + 7428
 26> 28  QtCore                              0x0000000112e657f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 27> 29  QtWidgets                           0x0000000111a01e57 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 903
 28> 30  QtWidgets                           0x0000000111a59b07 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 10951
 29> 31  QtWidgets                           0x0000000111a5823e _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4606
 30> 32  QtWidgets                           0x0000000111a0152d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 31> 33  QtWidgets                           0x0000000111a028f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 32> 34  QtCore                              0x0000000112e657f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 33> 35  QtGui                               0x0000000111fdd811 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 3489
 34> 36  QtGui                               0x0000000111fe1d19 _ZN22QGuiApplicationPrivate18processTabletEventEPN29QWindowSystemInterfacePrivate11TabletEventE + 1689
 35> 37  QtGui                               0x0000000111fc27eb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 219
 36> 38  libqcocoa.dylib                     0x000000014e804a58 qt_plugin_instance + 199592
 37> 39  CoreFoundation                      0x00007fff2042794c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 38> 40  CoreFoundation                      0x00007fff204278b4 __CFRunLoopDoSource0 + 180
 39> 41  CoreFoundation                      0x00007fff20427634 __CFRunLoopDoSources0 + 242
 40> 42  CoreFoundation                      0x00007fff2042605c __CFRunLoopRun + 893
 41> 43  CoreFoundation                      0x00007fff2042561c CFRunLoopRunSpecific + 563
 42> 44  HIToolbox                           0x00007fff2866ba83 RunCurrentEventLoopInMode + 292
 43> 45  HIToolbox                           0x00007fff2866b6b6 ReceiveNextEventCommon + 284
 44> 46  HIToolbox                           0x00007fff2866b583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
 45> 47  AppKit                              0x00007fff22c2d172 _DPSNextEvent + 864
 46>  47> sh: addr2line: command not found
 48> 50  libqcocoa.dylib                     0x000000014e80386c qt_plugin_instance + 195004
 49> 51  QtCore                              0x0000000112e6197f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 50> 52  QtCore                              0x0000000112e65d82 _ZN16QCoreApplication4execEv + 130
 51> 53  OpenToonz                           0x000000010e4db617 main + 16487
 52> 54  libdyld.dylib                       0x00007fff20349f3d start + 1
==== End ====

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

built Mar 14 2023

### Operating System

macOS

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by JPJammin** [comment]
I apologize for the inconvenience. I do not know if that was the issue, but
it was just my best guess.
The frame I had been working on was not saved, but I do still have the
file, and I was saving before I left the program idle. Everything that I
had done since my previous save still seems intact.
No, I never use the autosave feature. It was not enabled.
I did not know Undo was known to be unstable. That does seem like a pretty
important issue, at least to me. Much of my time is spent redrawing and Cmd
Z-ing the same lines. Are there any alternatives to Undo, if it is not
stable? Or, is there some type of Undo limit I should try to stay below?
Are there plans to make it more stable in the future?
Save/ Restart has generally been my go-to. Thank you for confirming.
Clear Undo Cache when Saving is enabled. Undo Memory Size is also 100 MB
Thank you for taking the time to look into it and respond! I am sorry this
is probably not the most helpful log. Upon the crash, I just saw the
buttons and instructions leading to report the issue, and so, I did.

**Comment by RodneyBaker** [comment]
> Are there any alternatives to Undo, if it is not
> stable? Or, is there some type of Undo limit I should try to stay below?
> Are there plans to make it more stable in the future?

We plan to make Opentoonz perfect (or as humanly close to perfect as possible) so yes... we'll get Undo working great one of these days.  :)

Alternatives to Undo...
The primary alternative is to Save incrementally... that is the ultimate Undo.
I am familiar with using Undo not so much as a means to restore a file but as an additional tool to move back and forth between say... strokes we've drawn etc.  As a matter of fact the new feature that allows us to create custom panels/windows with buttons also has a slider capability and as such we can assign Undo to one side of the slider and Redo to the other and slider our way into and out of the strokes of our drawing... timetravel to to point where we laid down the line that we want to keep and the commence drawing again.  Fun stuff.

Having said that however, Undo is simply not robust enough to be reliable at this point and there are several reasons for this, most of which are captured here in github reports, so I won't itemize here in this report.  We'll get there but we aren't there yet.

There are a number of things we can do to increase stability in Opentoonz.
For instance, give File > Clear Cache Folder a try every once in awhile to clear out the cobwebs of old project data still stored in Opentoonz.

No need to aplogize, we always appreciate reports as they help us gain a better view on the issues we need to work on and Undo/History (file integrity) is one of those very important issues.

The best time to use Undo, especially as an extension of tools (and not to just correct errors) is when Opentoonz itself is the most stable.  Opentoonz is generally most stable immediately after it has loaded a project where it is not competing with resources from itself (unnecessary cached data for instance) and other programs.  If you are doing something other than drawing, such as animating via xsheet, working with effects, etc. Opentoonz can lose track of where it is and Undo can get confused.  As such, after a long period of standing Idle it can be good to either relaunch the program or at least reload the scene we are working on.  This after saving of course.**

I'll end with a feature I hope we might add in the future; an option to relaunch Opentoonz with the current scene as there are changes we can make to Opentoonz that don't get fully seated until Opentoonz is restarted.  If we make enough of those changes they accumulate and there is no current process that would suggest to the user... you know... you probably should save and restart the program.  ;)

And... finally... why in this world would you allow Opentoonz to sit idle for hours when you should be drawing?
Get back to work!  :)

**Comment by RodneyBaker** [comment]
@JPJammin Closing this as a general matter of housekeeping but...
Please let us know if you are still experiencing the problem.
