### ISSUE TITLE
i cant save

### ISSUE THREAD

**Issue by Charlie676** [opentoonz/opentoonz#4788]
### Description

I save my animation, but when i left the app and come back, i didn't have the drawings anymore, just the frames and before 10 different palettes appear in a blue tone with numbers from 1 to 10 and other random ones and i only used one palette.

### Steps to Reproduce

1. 
2. 

### Expected Behavior

When I save the animations, the drawings do not appear, only the frames.

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Will close as a general troubleshooting issue and one without enough information to diagnose the issue.
Please feel free to continue the discussion here.

@Charlie676 If you can share screenshots, project files or other information about your project that will help in providing feedback toward resolution of your problem.
