### ISSUE TITLE
New Custom Column Color breaks Preview/Render Transparency

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4791]
### Description

@shun-iwasawa 
Since the addition of #4756 adjusting the Opaqueness slider no longer works with Preview and final rendering without also adding a color tint.  If a color is selected the opaqueness/transparency will kick in and work.

### Steps to Reproduce

1.  Draw with several colors on a toonz raster level (results should be the same on other levels as wel) 
2.  Adjust the column opaqueness slider (without Preview on) and note that transparency works
3.   Make sure the option to render column transparency and tinting is turned on in Scene Settings so that preview and rendering should be effected by the columns transparency (and color tinting).
4. Turn Preview on and note that column transparency no longer works (Final rendering should also not produce desired result)
5.  Select any color tinting from the dropdown and note that now the transparency will work.

**Comment by flurick** [comment]
https://github.com/opentoonz/opentoonz/blob/f6f00a0a43c2c1ef85c2989e36380f0fd511f465/toonz/sources/toonzlib/scenefx.cpp#L979
