### ISSUE TITLE
bug: brush size increase/decrease min/max commands do not work

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#480]
To reproduce the bug:
1. Open 'configure keyboard shortcuts'
2. Under tool modifiers, set shortcuts to brush size- decrease max,brush size- increase max, brush size- decrease min,brush size- increase min
3. try to use the shortcuts

expected behavior: incremental change of brush size
current behavior: nothing happens.

**Comment by blurymind** [comment]
@shun-iwasawa  thank you !

**Comment by turtletooth** [comment]
This bug still exists for raster levels.  #685 will fix it.
