### ISSUE TITLE
Implement a user 'stuff' directory tree to separate user files from OT files. Rename 'Stuff' directory to something better. 

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4804]
### Is your feature request related to a problem? Please describe

I just grepped (a tool that searches for patterns in files) for "stuff" to see if I can't hack in a userlibrary, and because 'stuff' is an awful name (too common/generic for a programming thing), grep returned many locations in the sources where 'stuff' is written.

It immediately put a damper on my motivation to sift through it, a more unique name, would possibly narrow it down, facilitating contributions by people who don't know the jungle of the source code by heart.

But when push comes to shove, that's not really a dealbreaker (would be nice, though)

### Describe the solution you'd like

However, a properly separated user 'stuff' at a different location, that never gets overwritten by OT updates, but instead overwrites OT things by getting loaded in separately would be suuuuch a quality of life improvement.

Even more ideal would be that the user settings are 'changes only', so for user menus, it has a reference to the original menu, but with hints about modification.

So, that if one has not messed with menus themselves, only added things to them (I have undo and redo as clickable buttons for the stylus)
Then only those buttons would be added to the user menu changes.

But that's just a cherry on the top desire.

The separation of OT stuff and user stuff is, to me, the most valuable change of this set of proposals.

**Comment by RodneyBaker** [comment]
Will close primarily as a matter of housekeeping.
There are certainly relevant elements withhin this request however.

As for the part 2 of the request...
During installation we can name the stuff directory anything we want and also place it in different locations.
The most typical rename might be 'portablestuff' which Opentoonz automatically will recognize as a mean to use any copy of Opentoonz as a portable application.

It would be good to further organize the stuff directory and we should consider proposals moving forward.
Another way forward would be to target specific areas of the stuff directory incrementally which would eventually lead to the same desired outcome of a well managed stuff directory.

My own personal desire related to some of this (well, at least one of them) is to separate the DLL files all into a DLL directory.
This to help facilitate upgrades/updates especially targeting files that never change.  An update that only updates necessary files would likely be under 10MB in size.  The OpenCV.dll file is over 50MB all by itself and rarely changes.  Yet with each download we get those same exact files again... and again... and again...

Opentoonz downloads currently weigh in at about 100MB.
Tahoma2D's downloads around 300MB.. due largely to third party support files.
By streamlining both program and user files we can get that number down significantly.
There are a number of ways to do this but we want to be smart in how we get it done.
Opentoonz is pretty lean and fast now and we want to see that not only maintained but further optimized.

I actually like the name 'stuff' as it is 'stuff' for opentoonz.
I have a repo called 'extrastuff' where I hope to collect lots of extras for users to add to their 'stuff'.
This as a separate download independent of Opentoonz itself.

**Comment by RodneyBaker** [comment]
This report should be reopened in the form of another request.
Perhaps in the v1.8 development cycle we can refine our collective approach to areas of development; the stuff directory contents, installation and user preferences being one of points of interest.
