### ISSUE TITLE
feature request: eraser tool - min and max brush size/opacity (where applicable) based on pressure sensitivity

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#481]
The eraser tool for raster levels supports opacity and size change, but that can not be based on pressure sensitivity like the brush tool.
The same applies for the size of the eraser tool on vector levels.

Please add min/max sliders to the eraser tool, so we can have a pressure sensitive eraser tool. It will make sketch cleanup much easier.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
