### ISSUE TITLE
Unspecified Crash

### ISSUE THREAD

**Issue by TestTime3000** [opentoonz/opentoonz#4817]
### Description

i copy the clipboard !! and past it here to show it to you guys

OpenToonz 1.6  (Build Dec 16 2022)

Report Date: 2023-04-09 04:39:01
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 528.24

Crash File: C:\Users\machi\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230409-043901.log
Mini Dump File: C:\Users\machi\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230409-043901.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: untitled14
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\Users\machi\AppData\Local\OpenToonz\OpenToonz\cache\temp\untitled14\untitled14.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_d1bd230cd08e7436\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\System32\fwpuclnt.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffc0a408b4c] <ntdll.dll>
  2> RtlRaiseException [0x7ffc0a3e12c6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffc0a430f4e] <ntdll.dll>
  4> QObject::isWidgetType [0x7ffbdbf89a74] <Qt5Core.dll>
  5> QWidgetPrivate::showChildren [0x7ffbdcc19f9d] <Qt5Widgets.dll>
  6> QWidgetPrivate::show_helper [0x7ffbdcc1a2a4] <Qt5Widgets.dll>
  7> QWidgetPrivate::setVisible [0x7ffbdcc187b8] <Qt5Widgets.dll>
  8> QWidget::setVisible [0x7ffbdcc1855e] <Qt5Widgets.dll>
  9> QWidgetPrivate::showChildren [0x7ffbdcc1a0da] <Qt5Widgets.dll>
 10> QWidgetPrivate::show_helper [0x7ffbdcc1a2a4] <Qt5Widgets.dll>
 11> QWidgetPrivate::setVisible [0x7ffbdcc187b8] <Qt5Widgets.dll>
 12> QWidget::setVisible [0x7ffbdcc1855e] <Qt5Widgets.dll>
 13> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7648039f2] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff764c19a67] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff764c19042] <OpenToonz.exe>
 16> BaseThreadInitThunk [0x7ffc093e7614] <KERNEL32.DLL>
 17> RtlUserThreadStart [0x7ffc0a3e26a1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![image](https://user-images.githubusercontent.com/75811532/230750194-15ce3a6e-af7f-4966-bb0c-1a56cd5212b8.png)

![Screenshot 2023-04-09 045349](https://user-images.githubusercontent.com/75811532/230750206-49ea5951-0ad5-4a9f-a91d-5d2600c154db.png)

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by TestTime3000** [comment]
and by the way ...you cant add a ( A i ) JPG pictures  to opentoonz  xsheet

**Comment by RodneyBaker** [comment]
JPG images apparently have problems these days but as of yet no one has opened a report on that.

**Comment by TestTime3000** [comment]
i hope you guys fix this problem ....becuse i cant open opentoonz its crash

**Comment by RodneyBaker** [comment]
Perhaps the problem is fixed already in a recent nightly release?
It's hard to say without knowing if you have tried a more recent release and still have the issue.

It looks to me like you might have just got a bad installer.
Do you have access to a second computer that you can test running Opentoonz on?

The reports you have shared are a bit too generic to be able to dig much deeper so at this point we are in need of additional  information.

**Comment by TestTime3000** [comment]
thanks ....i clear the cach  and i download the one you send me ......i was using the nightly before .....i am traying the one you send me now in the first link from get hub not the direct ....and if there is difference please tell me about it .....i will try the first one if there was any problems i will tell you about it ....with a lot thanks

**Comment by RodneyBaker** [comment]
Just to clarify, both links go to the same place.  The second link just goes all the way (directly) to the Windows executable file you have to locate manually if you use the first link.

**Comment by RodneyBaker** [comment]
@TestTime3000 Are you still having the problem?

**Comment by RodneyBaker** [comment]
Will close as likely resolved and/or abandoned.

This crash smells like one I had temporarily after an update.
I believe I resolved it by copying the ntdll.dll file from windows system directory into Opentoonz program directory.
After a later (nightly) install I no longer had the problem.
