### ISSUE TITLE
feature request: (view) command to toggle horizontal flip of canvas viewport

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#482]
Very often when drawing, the artist's eyes get used to the image and they stop noticing mistakes in it. 
A common approach to look for problems in a drawing with fresh eyes is flipping the canvas horizontally. It is a 'View' command found in most drawing software like photoshop - including tvpaint and toonboom.

![13422425_1645300485795736_874756708222360569_o](https://cloud.githubusercontent.com/assets/6495061/16194636/6f1fe2c8-36ed-11e6-8839-742fd4296c24.jpg)

The command does not do anything to the actual image, just to the display of the viewport.
It can be done as a command under the view menu, a command that can be binded to a keyboard shortcut.

**Comment by Rayek** [comment]
There are some workarounds, but YES a simple flip view command should be implemented.

Workarounds:
1) copy the current camera in the schematic view. You may want to rename it "Flip View"
2) select that camera, and switch to the EDIT tool.
3) switch to SCALE mode, and set the H value (horizontal) to -100%.

To check your work by flipping it you have several options now:

A) activate that second camera (either going into the schematic view, or left top dropdown menu in the EDIT tool properties), and click on the small camera icon at the top right of a view. By clicking on that icon, and switching back to table view (the first one of the three icons) you can now flip the screen easily.

Or:

B) keep the view in camera mode, and activate either the normal or flip camera.

Or:

C) open a second combo viewer, and activate the flip camera. Then in your main view work in table view, and in the second view turn on camera view. You now have two views, the original one, and a flipped version. Even when animating you can check your work against a flipped version. You could even create a dedicated room for this - side by side view :-)

To flip just one object, select the level, and use the level EDIT tool in scale mode, and again apply a negative 100% scale H value.

**Comment by adamearle** [comment]
There is probably a flip and a flop effect. Make sure you check the nodes

Adam Earle

**Comment by blurymind** [comment]
thank you for the workarounds guys. The feature request is for something quick  that is out of the box and can be bind to a keyboard shortcut.

We do this flip back and forth often, so making it easy to get to would be nice.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
