### ISSUE TITLE
The delete context menu option for Deleting an Output doesn't work

### ISSUE THREAD

**Issue by DarrenTAnims** [opentoonz/opentoonz#4822]
### Description

You can right click on an output on the FX Schematic to show a menu. It only has 1 item, Delete. But clicking it does nothing! You can select the node and press the delete key on your keyboard, but the command doesn't work.

### Steps to Reproduce

1. Open a scene
2. Open the FX schematic
3. Press the New Output button to create a new output (or press Alt+O or right click on the schematic and add one from there)
4. Right click on the new output and choose Delete from the context menu.
5. Nothing changes!

However - If you create a number of outputs, then try to delete them from their context menu. Notice nothing happens.
But if you then right click on another output and choose to Activate it, the outputs that you tried to delete now disappear!!
So it seems that the node might ACTUALLY be deleted and it's just a redraw issue.

### Expected Behavior

After choosing the delete option the node should disappear immediately.

### Screenshots, Video & Crash Logs

![ScreenRecording](https://user-images.githubusercontent.com/28575907/230960958-167f9326-a1d2-4408-9714-4bfc7f00b807.gif)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

built Apr 9 2023 10.03:23

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
> You can select the node and press the delete key on your keyboard, but the command doesn't work.

This works for me but of course not on the last/original output as that is required.
It's not clear why this isn't working for you.

I'm tagging with 'workaround' but if the delete key doesn't work then it obviously isn't much of a workaround.

**Comment by DarrenTAnims** [comment]
I've just tried this in a nightly build and it works great for a single Output. But if you highlight more than one and try to delete them with the context menu, that doesn't work. Do you have time to take a look at that too @shun-iwasawa ?
