### ISSUE TITLE
bug: Zooming out when approaching pen to tablet (Wacom) OSX #148

### ISSUE THREAD

**Issue by gasparzilla** [opentoonz/opentoonz#483]
I'm requesting to reopen #148 because apparently the issue has not been fixed, there is two more user experiencing the same problem in the old thread since it closed.

im currently using a bamboo CTL-470/K on a mac mini with el Capitan 10.11.5.

**Comment by michaeltchapman** [comment]
I just tested nightly build with a Cintiq 12HD on 10.11.6, and it doesn't seem to exhibit this behaviour (I do see it in Krita 3.0 though)

**Comment by artisteacher** [comment]
My students use the same tablets with 10.11.6. They've had problems with random scribbling #756  and the menus becoming greyed out within a few minutes but no one has reported a zooming out issue.

**Comment by turtletooth** [comment]
I think #1304 should fix this.
