### ISSUE TITLE
"create mesh" button in plastic tool didn't appear

### ISSUE THREAD

**Issue by nabbrodie** [opentoonz/opentoonz#4835]
### Ask a question related to OpenToonz

Hello, my student is having a problem that when he clicked "x" or plastic tool button, the "create mesh" button didn't appear. Please help me to solve this problem thank you!

**Comment by RodneyBaker** [comment]
Your student might not have the cell selected that they wish to have a plastic mesh created with.
Not sure though.

We probably need more information... perhaps a screenshot of what is being seen?


Aside:  Taking screenshots is a most excellent thing to teach students early on.
On Windows they can use the Print Screen key and paste that screenshot directly back into Opentoonz (if they want to do such a thing). I'm sure there is an equivalent on Mac and Linux as well.

*Copy/Pasting from the clipboard is something that available only recent releases of Opentoonz.

**Comment by RodneyBaker** [comment]
Will close as lacking any actionable information to assist with the problem.
@nabbrodie please feel free to continue the troubleshooting here although I suspect it might be more advantageous to join others in the various venues where real time assistance can be had via chat (discord for instance).
