### ISSUE TITLE
Levels not saving

### ISSUE THREAD

**Issue by RonjaFair** [opentoonz/opentoonz#4841]
### Description

Opentoonz isn't saving any changes I make to the paper. When I click save all it says "failed to save the following resources: C.tlv and C.tpl"

### Steps to Reproduce

1. 
2. 

### Expected Behavior

I expected it to actually save what I drew, but it failed to do so

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Try Saving your levels individually via Level > Save Level   or  Level > Save Level As.
It appears you have a conflict with levels saved with those particular names.

Once you have your renamed levels in place then perform the Save All again.

**Comment by RodneyBaker** [comment]
Levels normally do save so perhaps the best thing we can recommend at this stage is to join a venue such as one of the Opentoonz discords where others can assist in real time and help walk through the process to make sure all your levels are saving.

There are a number of things that might be causing your issue but until we have additional information there is very little we can do to assist.
