### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ngohtig** [opentoonz/opentoonz#4845]
### Description

OpenToonz 1.7 RC  (Build Mar 14 2023)

Report Date: 2023-04-22 14:33:03
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 16

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.4032

Crash File: C:\Users\Choi Hong\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230422-143303.log
Mini Dump File: C:\Users\Choi Hong\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230422-143303.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: iLoveYou
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\iLoveYou.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.436_none_fb2b38f27923daed\COMCTL32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\bcrypt.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6ee8e9575de3dde2\igc64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6ee8e9575de3dde2\igd12dxva64.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\Windows.ApplicationModel.dll
C:\Windows\system32\propsys.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\Windows\SYSTEM32\windows.staterepositoryclient.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6ee8e9575de3dde2\igxelpicd64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6ee8e9575de3dde2\igdml64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6ee8e9575de3dde2\igdgmm64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\System32\winrnr.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\nlansp_c.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\Ninput.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.1465_none_271271ab738361f1\comctl32.DLL
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\policymanager.dll
C:\Windows\SYSTEM32\msvcp110_win.dll
C:\Windows\SYSTEM32\ntmarta.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffa547a7a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffa5474e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffa547d2cee] <ntdll.dll>
  4> QDesktopWidget::workAreaResized [0x7ff9e87b0a22] <Qt5Widgets.dll>
  5> QDesktopWidget::workAreaResized [0x7ff9e87ae96e] <Qt5Widgets.dll>
  6> QApplicationPrivate::notify_helper [0x7ff9e87655c0] <Qt5Widgets.dll>
  7> QApplication::notify [0x7ff9e8764643] <Qt5Widgets.dll>
  8> QCoreApplication::notifyInternal2 [0x7ff9e2e6318a] <Qt5Core.dll>
  9> QGuiApplicationPrivate::processMouseEvent [0x7ff9e3de47c3] <Qt5Gui.dll>
 10> QWindowSystemInterface::sendWindowSystemEvents [0x7ff9e3dcf030] <Qt5Gui.dll>
 11> QEventDispatcherWin32::processEvents [0x7ff9e2eabcfa] <Qt5Core.dll>
 12> qt_plugin_query_metadata [0x7ff9e91828d9] <qwindows.dll>
 13> QEventLoop::exec [0x7ff9e2e5f64c] <Qt5Core.dll>
 14> QCoreApplication::exec [0x7ff9e2e62164] <Qt5Core.dll>
 15> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6fc385219] <OpenToonz.exe>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fc7ae6a7] <OpenToonz.exe>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fc7adc82] <OpenToonz.exe>
 18> BaseThreadInitThunk [0x7ffa53c9269d] <KERNEL32.DLL>
 19> RtlUserThreadStart [0x7ffa5478a9f8] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.6

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
Without any details of what you did, this report is likely to just be closed.
Also, for future reference, title your bug report with the issue. If everyone did this, the list of bugs would all just say, bug. And that isn't helpful.

**Comment by RodneyBaker** [comment]
@ngohtig I hope you'll take the opportunity to join one of the Opentoonz online venues where problems like this one get worked through in real time.  Here's a link to one of the Opentoonz discords:  https://discord.gg/UQxvYBKW5U
