### ISSUE TITLE
Sound Not Update Correctly on OT1.7RC

### ISSUE THREAD

**Issue by PapayaLimon** [opentoonz/opentoonz#4846]
### Description

When you cut audio frames it still reproduces the audio as it was at the beginning although in the timeline noiselines have been updated.

### Steps to Reproduce

1. Cut audio from the timeline
2. 

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

1.7RC

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Just for informational purposes, I'm curious what release of ffmpeg you are using.

**Comment by PapayaLimon** [comment]
Good question. How do I check that on Windows?

**Comment by PapayaLimon** [comment]
Ok, I installed the latest release (version: 2023-04-19-git-c17e33c058), and still get the same issue.

**Comment by shun-iwasawa** [comment]
I think I could reproduce the problem and will investigate it. Thank you @PapayaLimon !
