### ISSUE TITLE
Feature request: Autodetect new release/nightly build versions

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#485]
Would be nice when launching OpenToonz if it went out to GitHub and detected if a new release version was available and give options to download now or later with further download option to install now or later.

Might be nice for those brave enough if options were also available to detect nightly builds, allowing the user to download and install whichever ones they want, if they want.

NOTE: I do see a "Version Control" preference setting.  Not 100% sure what this is.  Is this for OpenToonz versioning or something else?  If I try to enable it I get a Critical error with message "The version control configuration file is empty or wrongly defined. Please refer to user guide for details".

**Comment by jcome** [comment]
> I do see a "Version Control" preference setting. 
> Not 100% sure what this is. Is this for OpenToonz versioning or something else?
it is animation content (files) versioning control system, like the git to manage source code.

**Comment by kogaki** [comment]
Now `OpenToonz` has ability to check it's versions. For example, if you launch 1.0.2, you will see an alert saying "plz upgrade to 1.0.3".

Github branch and Nightly Builds are not stable and sometimes have serious regression. So it's not good idea to announce that releases for *users* (not developers).

**Comment by manongjohn** [comment]
It was in 1.0.2? Either the popup alert didn't work or the message was not obvious, because I never saw it anywhere. Only reason i knew about the 1.0.3 release was because i saw the post on user forum.

**Comment by kogaki** [comment]
Hmm. It's actually there.

**Comment by manongjohn** [comment]
I definitely did not see that. I use the Windows version.

**Comment by kogaki** [comment]
@manongjohn Thank you for helping us debugging. As you reported, it doesn't work in OpenToonz v1.0.2 for windows. But now it has already been fixed in v1.0.3 ( #290 ). So you will be informed automatically when v1.0.4 will appear.

**Comment by manongjohn** [comment]
Thanks.  I will keep an eye out for it.
