### ISSUE TITLE
bug: onion skinning should be disabled during playback

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#486]
With the latest version of opentoonz (today's nightly) When you hit the play button onion skinning is still active.

It should switch off automatically during playback and switch back on when playback is stopped.

**Comment by turtletooth** [comment]
I think it has always done this, but I agree that it is not super useful during playback.  I can think of a few times when it has been nice to see.  There is a quick toggle in keyboard shortcuts but it isn't set by default.

**Comment by blurymind** [comment]
perhaps this could be a setting in the preferences (onion skin tab) window?
"Disable during playback"

I dont like having an extra step every time i start and stop playback and would like to have it disabled during 99% of the time when the animation is running. Having it on is distracting.

**Comment by turtletooth** [comment]
I agree with you that it should be generally disabled during playback.  If it is an option I think it should be disabled by default during playback.

**Comment by blurymind** [comment]
i agree - "disable during playback" should be ticked on default!

**Comment by turtletooth** [comment]
#708 should take care of this.

**Comment by blurymind** [comment]
AWESOME! :o
