### ISSUE TITLE
"Visualize Vector As Raster" mode Undo BUG

### ISSUE THREAD

**Issue by optical-core** [opentoonz/opentoonz#4869]
### Description

https://user-images.githubusercontent.com/39340555/236097954-92c945d2-feba-4239-a0dd-4cada5bc21dc.mp4

Under "Visualize Vector As Raster" mode，Edit line Undo will appear bug.

### Steps to Reproduce

1. Draw a vector line on vector level.
2. Use the selection tool and edit the lines.
3. Undo.

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/39340555/236097954-92c945d2-feba-4239-a0dd-4cada5bc21dc.mp4

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

1.7RC May 1 2023

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by beeheemooth** [comment]
#1818

**Comment by shun-iwasawa** [comment]
fixed with #4870

**Comment by optical-core** [comment]
@shun-iwasawa Thank you
