### ISSUE TITLE
feature request- drag and drop a sequence of drawings onto x-sheet from level strip

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#487]
Currently we can drag and drop a single image from the level strip onto the x-sheet.
If we select a sequence of (multiple) images and drop them onto the x-sheet, only the last selected one gets dropped.

It will be much more useful if we could drag and drop the sequence of selected images onto the xsheet and then be able to readjust their timing. 

try it out:
1. select multiple images on the level strip window
2. drag and drop them onto xsheet

expected behavior: They all get dropped- in the correct level strip order
current behavior: Only one of them gets dropped

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
I'll note that a near workaround that accomplishes the same thing as this request specifies is to Right Click and select 'Expose in xsheet'.  Once exposed then the cells can be moved wherever necessary.

**Comment by RodneyBaker** [comment]
This may be a good example of why the Google Groups forum is the best place to vet most Feature Requests.  In looking into this request I find that not only is the feature working but it's working in even better ways than originally considered.

Note that it is unclear to me whether this feature has always been there or if some developer implmented it and the addition was never published publicly.  The important thing is that it works.

The related exploration/discussion can be followed here:  https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/dRzymJqsxt8

I imagine that at some point topics such as these (in the forum) will move from 'Feature Request' to 'Tips and Tricks'.

**Comment by tGuMedia** [comment]
@RodneyBaker the drag and drop also works if the images are sequentially named like this: levelname.0001.tiff, levelname.0002.tiff, levelname.0003.tiff, etc.

**Comment by RodneyBaker** [comment]
@tGuMedia 
We may not be talking about quite the same thing but please feel free to add your observations to the forum discussion ([Link](https://groups.google.com/forum/#!category-topic/opentoonz_en/feature-requests/dRzymJqsxt8))**.  I must assume drawings created in the level strip all have the .pli extension and therefore cannot have extensions such as .tiff etc.

**Please, the more discussion in the forum the better!  :)
