### ISSUE TITLE
Export to OCA Couldn't Create Folder

### ISSUE THREAD

**Issue by deathchimera** [opentoonz/opentoonz#4871]
### Description

Trying to export to OCA results in a message in the terminal saying "Couldn't create folder" and leaves a forever loading progress bar. It also creates a .oca file with nothing inside of it at the designated location. Not sure how long it's been an issue, but I don't think it's new to the 1.7 RC.

### Steps to Reproduce

1. Load scene
2. Export to OCA

### Expected Behavior

Expected a .oca folder to appear containing all the necessary files and such.

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/77942602/236674949-9c445817-01f1-4ac6-8fa1-fc3174c62428.mov

(Couldn't create folder message)
[OT.log](https://github.com/opentoonz/opentoonz/files/11414863/OT.log)

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

1.7 RC

### Operating System

Linux

### GPU

Intel

### Graphics Tablet

None

**Comment by JParks123** [comment]
It works fine on Windows maybe this is a Linux build problem.

**Comment by RodneyBaker** [comment]
According to your screenshot the folder is already there but Opentoonz is asking if you want to overwrite.
![image](https://user-images.githubusercontent.com/2576432/236706745-8a7cb65b-3981-4106-8417-86f55f9b68d9.png)

Can you clarify as it looks like it must have worked at least once before?

**Comment by deathchimera** [comment]
Exporting to OCA does result in OT creating a .oca file, it's just that there is nothing inside of the file itself, and no matter how long I wait, nothing comes of it either. Choosing a new name creates another file with nothing inside of it, and the same problems as listed.

**Comment by justburner** [comment]
*sigh* Qt bugs strike again...
Anyway I've forgot to close the progress dialog after detecting an error so I'll probably have to fix both.

Thanks Bracket-H for testing on Linux and discovering the problem.
