### ISSUE TITLE
Import / Load Dialogue not working on 1.7 update

### ISSUE THREAD

**Issue by Tallowick** [opentoonz/opentoonz#4877]
### Description

Since updating to 1.7, when dragging an image into Opentoonz the dialogue that appears asking whether to load or import the level does not work. Clicking the "Import", "Load" and "Cancel" buttons does not do anything, only the "x" button in the corner works to exit the dialogue.
![image](https://github.com/opentoonz/opentoonz/assets/129105712/b82d83f5-0aea-478f-8557-6912f3f2298c)

Running Windows 10. 
Have tried reinstalling the update, restarting Opentoonz, trying different images on different hard drives, no difference

### Steps to Reproduce

1. Drag a png image into OpenToonz that isn't part of the current project
2. Wait for the dialogue box to appear

### Expected Behavior

Nothing happens when clicking the "import", "load" or "cancel" buttons.

### OpenToonz Version

1.7

### OpenToonz Version Information

built May 9 2023 11:12:45

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Thanks for the report @Tallowick 
I believe I am seeing the same problem as you.

**Comment by shun-iwasawa** [comment]
FIxed & replaced the v1.7 installer. I'll release the urgent patch version (v1.7.1) for it. So sorry for the trouble!

**Comment by Tallowick** [comment]
Awesome! Thanks for all the hard work
