### ISSUE TITLE
feature request - reorder drawings in the level strip* by drag and drop

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#488]
Currently it is not possible to reorder drawings in the level strip by drag and drop. The user has to cut and paste to insert.
I find this to be somewhat un-intuitive.

A possible reason for this not being enabled in opentoonz is the currently unexpected result that drawing reordering in the level strip causes to the cells in the x-sheet:
https://github.com/opentoonz/opentoonz/issues/471
I suggested a solution to that at the link above.

In any case instead of discouraging the user from doing that, I think it would be much better if it's made easier to reorder them and fixing the above issue if that causes confusion.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
