### ISSUE TITLE
Crash when holding Ctrl+Z while drawing.

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#4887]
### Description

I discovered this crash while testing #4885, but the crash can be reproduced in earlier versions.
In Tahoma 2D, such a crash is not observed.

### Steps to Reproduce

1. Create a new vector level.
2. Start drawing a line (keep the stylus on the canvas)
3. While drawing, press and hold Ctrl+Z
4. At the end of the cancellation of all operations, the program will crash.

(btw, cool crash window! I haven't tested OT in a while)

### Screenshots, Video & Crash Logs

![ezgif-2-990963defa](https://github.com/opentoonz/opentoonz/assets/25724133/42dd713e-2f5f-4be9-8b5a-1ee401283169)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
I can't reproduce the crash.
Perhaps I'm missing an important step however.

**Comment by RodneyBaker** [comment]
@beeheemooth @Bracket-H Can you confirm that #5187 actually fixed your problem?
I can't produce the crash but I couldn't last year either so it'll be good to get a confirmation either way.

**Comment by RodneyBaker** [comment]
Will work with that then.  Thanks
@beeheemooth Please let us know if you still have thie problem and we'll reopen.
