### ISSUE TITLE
OpenToonz 1.7.1 crashes upon opening.

### ISSUE THREAD

**Issue by CCToonz** [opentoonz/opentoonz#4888]
### Ask a question related to OpenToonz

 OpenToonz 1.7.1 crashes upon opening. It is the same problem as on earlier versions of OT. I've have an iMac of from 2020. What's the problem? What can I do to get the OP up and running?

**Comment by RodneyBaker** [comment]
If you haven't check other recent repports will want to read up on those as those have solved the problem for some users.

As for what the problem might be... hard to say as your report doesn't include much to go on.
Hopefully the solutions outlined in other reports will resolve your issue as well.

**Comment by FlashlightET** [comment]
same here but on windows

**Comment by CCToonz** [comment]
Thanks for the reply.
But I'm totally confused. I'm not very well versed in programming, but I'm
guessing that OT is conflicting with my iMac's operating system. My OS is
called Ventura 13.3.1.

I am sending with this email the latest crash report from OT, which always
comes up when I try to start the program. Can it help you find the problem?
And maybe give me tips on how to remedy the problem.

---------

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-05-13 17:38:43
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 22.4.0
CPU Threads: 16

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon Pro 5500 XT OpenGL Engine
GPU Version: 2.1 ATI-4.10.12

Crash File: /Users/sverkerottosson/Library/Application
Support/OpenToonz/OpenToonz/crash/Crash-20230513-173843.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: sandbox
Scene Name: untitled395
Project Path:
/Applications/OpenToonz/OpenToonz_stuff/sandbox/sandbox_otprj.xml
Scene Path:
/Users/sverkerottosson/Library/Caches/OpenToonz/OpenToonz/temp/untitled395/untitled395.tnz

==== Backtrace ====
  1> 3   QtCore                              0x00000001096e0d98
_ZN7QObject16staticMetaObjectE + 0
  2> 4   QtWidgets                           0x00000001079ec998
_ZN14QWidgetPrivate11show_helperEv + 72
  3> 5   QtWidgets                           0x00000001079ed724
_ZN14QWidgetPrivate10setVisibleEb + 804
  4> 6   QtWidgets                           0x00000001079ecd34
_ZN14QWidgetPrivate12showChildrenEb + 340
  5> 7   QtWidgets                           0x00000001079ec998
_ZN14QWidgetPrivate11show_helperEv + 72
  6> 8   QtWidgets                           0x00000001079ed724
_ZN14QWidgetPrivate10setVisibleEb + 804
  7> 9   OpenToonz                           0x0000000103970894 main + 15092
  8> 10  dyld                                0x00007ff8037d641f start + 1903
==== End ====

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@CCToonz If you are still experiencing the problem you reported I will recommend joining one of the Opentoonz discords where others can assist.
