### ISSUE TITLE
Toonz Raster Level Brush Tools "shift"key drawing line size change

### ISSUE THREAD

**Issue by optical-core** [opentoonz/opentoonz#4889]
### Is your feature request related to a problem? Please describe

![line](https://github.com/opentoonz/opentoonz/assets/39340555/4af4de9e-37bb-4738-90a3-c0242d3d70e6)
When "Pressure" mode is not enabled, "Shift" key draws a straight line, and the size of both ends of the line changes.

### Describe the solution you'd like

When the brush draws a straight line without activating "Pressure" mode, the size remains the same.

**Comment by RattusaurusRex** [comment]
Can confirm.  A size 2 straight vertical line starts out at 2 pixels wide, but ends at 4 pixels wide:

<img width="469" alt="Screenshot 2023-05-11 220843" src="https://github.com/opentoonz/opentoonz/assets/60277069/9df12275-4e91-4031-b56e-25506529b5bb">

<img width="552" alt="Screenshot 2023-05-11 220957" src="https://github.com/opentoonz/opentoonz/assets/60277069/9b51d584-9740-49b2-99c6-2ae0b4a0acc3">
