### ISSUE TITLE
feature request- xsheet- box selecting cells should also select the memo notes

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#489]
We tend to attach notes to the xsheet based on the cells. 
- Every time we move keyframes/cells, the notes we placed above/next to those cells stay. (1)
- Every time we reorder a level - the memo notes stay, they dont get moved with the level (2)

It would make more sense if they move with the cells while we move the cells.

For situation (1,2) - a memo note could store a variable every time it is moved or created - that variable stores the cell the memo note's center overlapped with when the mouse button was released (drag and drop event).It could also store the offset from it.
If a cell is moved or pushed down - the memo note would then move as well- move with it.

If a memo note is dropped onto an empty cell, it stays null and it doesn't move until dragged by the user.
Im not sure if that can be done that way - but its an idea.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
