### ISSUE TITLE
Crashes on multiple instances of use at ver. 1.7.1

### ISSUE THREAD

**Issue by Jotafrost** [opentoonz/opentoonz#4891]
### Description

i've updated Today and faced multiple crashes during use in different situations. The first one crashed just as the program oppened, after that during a few hours of use it crashed mostly while using the skeleton toon on a raster level. i've been using them on animations linking many subsheets, witch may have triggered some issue.  Two other crashes happened while creating meshes on plastic tool. the last one simply happened when i finished a drawing and pressed the button to close the program.   I'm unsure how to reproduce the crashes, and i'm a fairly new user, but the last crash was the only one to pop up a window with informations while all the previous ones just closed the program without anything else happening, so i'm posting the log here in case it help identifying issues.

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-05-12 21:58:51
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19044
CPU Threads: 8

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1650/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 531.61

Crash File: C:\Users\frost\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230512-215851.log
Mini Dump File: C:\Users\frost\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230512-215851.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Studies
Scene Name: 
Project Path: C:\OpenToonz stuff\projects\Studies\Studies_otprj.xml
Scene Path: 

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\WINTRUST.DLL
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_89cdd9f6f9724565\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.DLL
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
C:\WINDOWS\SYSTEM32\msvcp110_win.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffb3d3c8b4c] <ntdll.dll>
  2> RtlRaiseException [0x7ffb3d3a12c6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb3d3f0f0e] <ntdll.dll>
  4> TSmartPointerT<TData>::TSmartPointerT<TData> [0x7ffad2472c29] <tnzcore.dll>
  5> TImageException::getRawMessage [0x7ffad24741b5] <tnzcore.dll>
  6> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b71025fb] <OpenToonz.exe>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b710512e] <OpenToonz.exe>
  8> QObject::qt_static_metacall [0x7ffad31b20d7] <Qt5Core.dll>
  9> TXshLevelHandle::xshLevelSwitched [0x7ffad2c24b31] <toonzlib.dll>
 10> TXshLevelHandle::setLevel [0x7ffad2be6d4e] <toonzlib.dll>
 11> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7b706022c] <OpenToonz.exe>
 12> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7b705ff40] <OpenToonz.exe>
 13> QObject::qt_static_metacall [0x7ffad31b20d7] <Qt5Core.dll>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b7228bc6] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7b7018cb1] <OpenToonz.exe>
 16> QWidget::event [0x7ffae1aa8529] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ffae1a855c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffae1a84643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffad319318a] <Qt5Core.dll>
 20> QWidgetPrivate::close_helper [0x7ffae1aa5017] <Qt5Widgets.dll>
 21> QDesktopWidget::workAreaResized [0x7ffae1ace6ed] <Qt5Widgets.dll>
 22> QApplicationPrivate::notify_helper [0x7ffae1a855c0] <Qt5Widgets.dll>
 23> QApplication::notify [0x7ffae1a84643] <Qt5Widgets.dll>
 24> QCoreApplication::notifyInternal2 [0x7ffad319318a] <Qt5Core.dll>
 25> QGuiApplicationPrivate::processCloseEvent [0x7ffad35d337d] <Qt5Gui.dll>
 26> QWindowSystemInterface::sendWindowSystemEvents [0x7ffad35bf030] <Qt5Gui.dll>
 27> QEventDispatcherWin32::processEvents [0x7ffad31dbcfa] <Qt5Core.dll>
 28> qt_plugin_query_metadata [0x7ffad54128d9] <qwindows.dll>
 29> QEventLoop::exec [0x7ffad318f64c] <Qt5Core.dll>
 30> QCoreApplication::exec [0x7ffad3192164] <Qt5Core.dll>
 31> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7b7015219] <OpenToonz.exe>
 32> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b743eab7] <OpenToonz.exe>
 33> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b743e092] <OpenToonz.exe>
 34> BaseThreadInitThunk [0x7ffb3b857614] <KERNEL32.DLL>
 35> RtlUserThreadStart [0x7ffb3d3a26a1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
This appears to be a codec problem but... not sure.

**Comment by RodneyBaker** [comment]
@Jotafrost It has been awhile since you issued your report.
I must assume that you've reinstalled and had better success since that timeframe.
If you have any additional information you can share that will be appreciated.

**Comment by RodneyBaker** [comment]
Will close as likely resolved and/or abandoned but thanks for the report @Jotafrost 
As others scrub through similar reports perhaps patterns can be discovered that will improve stability over all.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Jotafrost If you are still experiencing the issue you report and can share additional information we'll try to assist.
