### ISSUE TITLE
OpenToonz Crashed at launch

### ISSUE THREAD

**Issue by cpiatkowski** [opentoonz/opentoonz#4892]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-05-15 12:26:17
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 6

Crash File: C:\Users\Chris Piatkowski\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230515-122617.log
Mini Dump File: C:\Users\Chris Piatkowski\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230515-122617.dmp

==== Modules ====
H:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
A:\Antivirus\aswhook.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
H:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
H:\Program Files\OpenToonz\glut64.dll
H:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
H:\Program Files\OpenToonz\Qt5Xml.dll
H:\Program Files\OpenToonz\Qt5SerialPort.dll
H:\Program Files\OpenToonz\colorfx.dll
H:\Program Files\OpenToonz\image.dll
H:\Program Files\OpenToonz\tnztools.dll
H:\Program Files\OpenToonz\tnzstdfx.dll
H:\Program Files\OpenToonz\tfarm.dll
H:\Program Files\OpenToonz\Qt5Widgets.dll
H:\Program Files\OpenToonz\Qt5Gui.dll
H:\Program Files\OpenToonz\Qt5Core.dll
H:\Program Files\OpenToonz\sound.dll
H:\Program Files\OpenToonz\toonzqt.dll
H:\Program Files\OpenToonz\toonzlib.dll
H:\Program Files\OpenToonz\opencv_world451.dll
H:\Program Files\OpenToonz\Qt5Script.dll
H:\Program Files\OpenToonz\tnzext.dll
H:\Program Files\OpenToonz\Qt5OpenGL.dll
H:\Program Files\OpenToonz\tnzbase.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
H:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
H:\Program Files\OpenToonz\MSVCP140.dll
H:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
H:\Program Files\OpenToonz\MSVCP140_1.dll
H:\Program Files\OpenToonz\VCRUNTIME140_1.dll
H:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
H:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
H:\Program Files\OpenToonz\glew32.dll
H:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
H:\Program Files\OpenToonz\libmypaint-1-4-0.dll
H:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
H:\Program Files\OpenToonz\libjson-c-2.dll
H:\Program Files\OpenToonz\libintl-8.dll
H:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
H:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
H:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
H:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\WINTRUST.DLL
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_e34a87a86b660c23\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff8fa4c7a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff8fa46e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff8fa4f2cee] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ff81799413e] <MSVFW32.dll>
  6> ICOpen [0x7ff817993da4] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff88d786212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff88d784478] <image.dll>
  9> initImageIo [0x7ff88d727ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73ca50dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73ca52d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73ce7eab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73ce7e092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff8f8c226ad] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff8fa4aa9f8] <ntdll.dll>
==== End ====

### Steps to Reproduce

1.  Launch
2. 

### Expected Behavior

Crashes

### OpenToonz Version

1.7

### OpenToonz Version Information

v.1.7.1

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Another issue with the logitec webcam driver.
I note that users of Adobe products have started to report the issue over there as well stating (after the issue was 'resolved' for a few years) that the problem was back.

**Comment by cpiatkowski** [comment]
Thanks 👍

**Comment by RodneyBaker** [comment]
Another possibility for crashing in similiar fashion has been reported as being from bad video codecs.
If you have recently downloaded a codec pack that would be well worth investigating.

**Comment by RodneyBaker** [comment]
For others referencing this issue...

C:\WINDOWS\SYSTEM32\lvcod64.dll apparently is an old and problematic logitec driver.
Removal (or renaming) of that file should resolve the problem.
