### ISSUE TITLE
OpenToonz crash

### ISSUE THREAD

**Issue by Feliximon** [opentoonz/opentoonz#4893]
### Description

I have no idea why but OP keeps crashing. The App generates this  message every time. I hope it will help the devs in some way:

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-05-15 16:31:02
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 16

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics
GPU Version: 4.6.0 - Build 31.0.101.3413

Crash File: C:\Users\Mondaley\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230515-163102.log
Mini Dump File: C:\Users\Mondaley\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230515-163102.dmp

Application Dir: C:/OP/OpenToonz/OpenToonz
Stuff Dir: C:\OP\OpenToonz stuff

Project Name: sandbox
Scene Name: Animașie
Project Path: C:\OP\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OP\OpenToonz stuff\sandbox\scenes\Animașie.tnz

==== Modules ====
C:\OP\OpenToonz\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\OP\OpenToonz\OpenToonz\Qt5Xml.dll
C:\OP\OpenToonz\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\OP\OpenToonz\OpenToonz\glut64.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\OP\OpenToonz\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\OP\OpenToonz\OpenToonz\colorfx.dll
C:\OP\OpenToonz\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\OP\OpenToonz\OpenToonz\image.dll
C:\OP\OpenToonz\OpenToonz\tnztools.dll
C:\WINDOWS\System32\WS2_32.dll
C:\OP\OpenToonz\OpenToonz\tnzstdfx.dll
C:\OP\OpenToonz\OpenToonz\tfarm.dll
C:\OP\OpenToonz\OpenToonz\Qt5Gui.dll
C:\OP\OpenToonz\OpenToonz\sound.dll
C:\OP\OpenToonz\OpenToonz\toonzqt.dll
C:\OP\OpenToonz\OpenToonz\Qt5Widgets.dll
C:\OP\OpenToonz\OpenToonz\Qt5Core.dll
C:\OP\OpenToonz\OpenToonz\toonzlib.dll
C:\OP\OpenToonz\OpenToonz\tnzext.dll
C:\OP\OpenToonz\OpenToonz\Qt5Script.dll
C:\OP\OpenToonz\OpenToonz\Qt5OpenGL.dll
C:\OP\OpenToonz\OpenToonz\opencv_world451.dll
C:\OP\OpenToonz\OpenToonz\tnzbase.dll
C:\OP\OpenToonz\OpenToonz\Qt5Multimedia.dll
C:\OP\OpenToonz\OpenToonz\Qt5Network.dll
C:\OP\OpenToonz\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\OP\OpenToonz\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\OP\OpenToonz\OpenToonz\MSVCP140_1.dll
C:\OP\OpenToonz\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\OP\OpenToonz\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\OP\OpenToonz\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\OP\OpenToonz\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\OP\OpenToonz\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\OP\OpenToonz\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\OP\OpenToonz\OpenToonz\libintl-8.dll
C:\OP\OpenToonz\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\OP\OpenToonz\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\OP\OpenToonz\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\OP\OpenToonz\OpenToonz\styles\qwindowsvistastyle.dll
C:\OP\OpenToonz\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igxelpicd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igdml64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igdgmm64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qgif.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qicns.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qico.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qjpeg.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qsvg.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qtga.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qtiff.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qwbmp.dll
C:\OP\OpenToonz\OpenToonz\imageformats\qwebp.dll
C:\OP\OpenToonz\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\OP\OpenToonz\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffb26da7a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffb26d4e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb26dd2cee] <ntdll.dll>
  4> TStroke::getMaxThickness [0x7ffaa592e4e3] <tnzcore.dll>
  5> TRegion::addEdge [0x7ffaa59228c3] <tnzcore.dll>
  6> computeRegionFeature [0x7ffaa591b5a2] <tnzcore.dll>
  7> TVectorImage::moveStrokes [0x7ffaa5948cb4] <tnzcore.dll>
  8> TVectorImage::notifyChangedStrokes [0x7ffaa5948f82] <tnzcore.dll>
  9> ToolOptions::showEvent [0x7ffadd950177] <tnztools.dll>
 10> ToolOptions::showEvent [0x7ffadd94dcd5] <tnztools.dll>
 11> PinchTool::getToolType [0x7ffadd86da65] <tnztools.dll>
 12> PinchTool::getToolType [0x7ffadd86d17a] <tnztools.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e38b4fd] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e38a5f8] <OpenToonz.exe>
 15> QWidget::event [0x7ffac97c8066] <Qt5Widgets.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e38942b] <OpenToonz.exe>
 17> QApplicationPrivate::notify_helper [0x7ffac97a55c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffac97a34e0] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffac69a318a] <Qt5Core.dll>
 20> QApplicationPrivate::sendMouseEvent [0x7ffac97a67c5] <Qt5Widgets.dll>
 21> QDesktopWidget::workAreaResized [0x7ffac97f09d2] <Qt5Widgets.dll>
 22> QDesktopWidget::workAreaResized [0x7ffac97ee96e] <Qt5Widgets.dll>
 23> QApplicationPrivate::notify_helper [0x7ffac97a55c0] <Qt5Widgets.dll>
 24> QApplication::notify [0x7ffac97a4643] <Qt5Widgets.dll>
 25> QCoreApplication::notifyInternal2 [0x7ffac69a318a] <Qt5Core.dll>
 26> QGuiApplicationPrivate::processMouseEvent [0x7ffac6de47c3] <Qt5Gui.dll>
 27> QWindowSystemInterface::sendWindowSystemEvents [0x7ffac6dcf030] <Qt5Gui.dll>
 28> QEventDispatcherWin32::processEvents [0x7ffac69ebcfa] <Qt5Core.dll>
 29> qt_plugin_query_metadata [0x7ffacb1028d9] <qwindows.dll>
 30> QEventLoop::exec [0x7ffac699f64c] <Qt5Core.dll>
 31> QCoreApplication::exec [0x7ffac69a2164] <Qt5Core.dll>
 32> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73e2a5219] <OpenToonz.exe>
 33> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e6ceab7] <OpenToonz.exe>
 34> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e6ce092] <OpenToonz.exe>
 35> BaseThreadInitThunk [0x7ffb260f26ad] <KERNEL32.DLL>
 36> RtlUserThreadStart [0x7ffb26d8a9f8] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
You haven't said what you was doing at the time of the crash. The more information you can share, the easier it will be to find and fix any problems.

**Comment by Feliximon** [comment]
> You haven't said what you was doing at the time of the crash. The more information you can share, the easier it will be to find and fix any problems.

The only thing i remember is that I was using the Control Point Editor Tool with the snap mode turned on. I did a lot of experimenting to find the cause but without any success. I'm sorry for this little information. This problem should be closed because of its ambiguity. I thought the generated message would be enough.
