### ISSUE TITLE
Ot 1.7.1 render issues - render doesn't start at all from task room

### ISSUE THREAD

**Issue by matitanimata** [opentoonz/opentoonz#4897]
### Description

as in previous versions also in 1.7 it is very tiring to render scenes that contain assets that use the plastic tool. To generate a movie of about 180 frames I had to render 6 clips of 30 frames each. Normally the solution is to generate a sequence of images by launching the render from the task room, but in this version the render from the task room doesn't start at all, both in scenes that use plastic and in scenes that don't use it.

### Steps to Reproduce

1. create a scene, set the output settings and save
2. from the browser room select the scene, right click "add as render task"
3. in the task room start the render

### Expected Behavior

 the render icons will get immediately red.

### Screenshots, Video & Crash Logs

![Schermata 2023-05-16 alle 19 24 50](https://github.com/opentoonz/opentoonz/assets/20012515/72f37294-a71d-430b-aa51-c7a89b4720db)
![Schermata 2023-05-16 alle 19 24 57](https://github.com/opentoonz/opentoonz/assets/20012515/722805aa-047a-4ece-976f-e89e825d2e65)

### OpenToonz Version

1.7

### Operating System

macOS

### GPU

AMD

### Graphics Tablet

None

**Comment by RattusaurusRex** [comment]
Is there no scene or settings that work for you?  Or are there specific kinds of scenes/settings that won't render?  Task rendering works for me on Windows: 
![image](https://github.com/opentoonz/opentoonz/assets/60277069/da0b19ec-881f-40c4-af9b-9c388734939d)

**Comment by matitanimata** [comment]
I've tried with several scenes and settings, it doesn't work. I haven't tried on windows yet.

**Comment by artisteacher** [comment]
I'm seeing the same thing on macOS - on T2D as well in recent nightly builds.

**Comment by artisteacher** [comment]
On the T2D end, this is where it broke:
https://github.com/tahoma2d/tahoma2d/pull/1139

**Comment by artisteacher** [comment]
It looks like this started with #4727 on the OT side.

**Comment by RodneyBaker** [comment]
Tagging with 'os-mac' although likely an issue on Linux as well.
As with @RattusaurusRex I'm not seeing the task rendering problem on Windows.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/38b3dc7d-4f16-49b7-859a-2bd88224c393)

Here I am rendering to PNG sequence however.
Haven't tried rendering to MP4 yet.
