### ISSUE TITLE
how do i get big pixels without loosing quality

### ISSUE THREAD

**Issue by home-gihub** [opentoonz/opentoonz#4899]
### Ask a question related to OpenToonz

I've been wanting a flipnote style animation in OpenToonz i know i just need to make the pixels bigger but when i change the dpi it results in a blurry export, i want the effect of having big pixels but on having blur maybe not changing the resolution at all.  CS gost animation is doing this.

**Comment by home-gihub** [comment]
i don't want to mess with the resolution

**Comment by home-gihub** [comment]
ok this is what im talking about

zoomed out:
![nozoom](https://github.com/opentoonz/opentoonz/assets/124263428/1c4ed3f3-2edf-4d10-8586-9c60f6ba56fe)
(looks not pixelated)

**Comment by home-gihub** [comment]
> For the brush, check the pencil tickbox, that will make it pixelated.
> 
> As for the resolution, you don't have to change the resolution, only the resample balance.

already did that

**Comment by home-gihub** [comment]
I don't know where to find all of theses setting but I would like a aspect ratio of 16:9

**Comment by home-gihub** [comment]
btw i have a 3440x1440 display it might just be my screen

**Comment by andeon** [comment]
Try using Raster Level instead of Toonz Raster Level


https://github.com/opentoonz/opentoonz/assets/11843239/8e2bcde6-2686-488b-a2b2-d0dbe9a8af06


Choose in Style Editor "Raster guide" 1 pixel brush, avoid using eraser, set another "1 pixel brush" to white or bg color to avoid transparency.

**Comment by home-gihub** [comment]
> Try using Raster Level instead of Toonz Raster Level
> 
>  untitled.mp4 
> Choose in Style Editor "Raster tab" the 1pixel brush, avoid using eraser, set another "1pixel brush" to white or bg color to avoid transparency.

![still](https://github.com/opentoonz/opentoonz/assets/124263428/0db02d9f-2e2d-4fd7-b86d-2a0b3ed76c8e)

its still blurry

**Comment by home-gihub** [comment]
i  close this now

**Comment by elixsmax** [comment]
@Bracket-H Hi, do u have discord, I'd love to ask u some questions about this

**Comment by elixsmax** [comment]
> Try using Raster Level instead of Toonz Raster Level
> 
>  untitled.mp4 
> Choose in Style Editor "Raster tab" the 1pixel brush, avoid using eraser, set another "1pixel brush" to white or bg color to avoid transparency.

im using the raster level and the 1pixel brush but my lines look anti-aliased. 
![Screenshot 2024-08-09 095523](https://github.com/user-attachments/assets/ccf76af6-f8ad-48c4-8c4f-a32530a705be)

**Comment by elixsmax** [comment]
> Is that level 'animated' using the 'animation tool'? In other words, is it moved even a tiny bit? Cause the animation tool and raster art don't mix very well due to the animation tool producing fractional position and size data, and raster being discrete whole numbers. On a 1080 x 1920 grid, there are only 1080x1920 pixels, not more, not less, there are no half pixels, or quarter pixels, or 0.0000000001 pixels.
> 
> But that's what the animation tool produces.

im new to OT but i dont think it's moved at all i didnt touch the animate tool. i am using the flipnote template zip you included above. when using the black brush with pencil box clicked it works fine, i just found. but at this point im just wondering how @andeon was able to get it to work using 1pixel above in this thread. all good about not having discord. im just glad u replied here :P i read the entire thread and really tried to understand what you were saying about resolutions and not moving the columns or using the animate tool. 
![image](https://github.com/user-attachments/assets/ea5b8c9e-4eeb-42a8-9bd4-e8515af60f84)

**Comment by elixsmax** [comment]
![image](https://github.com/user-attachments/assets/4fa72f34-91c3-4f2d-8820-b4678c5c9c3f)
i made a brand new raster level to test it with the 1pixel brush and the issue persists

**Comment by andeon** [comment]
@elixsmax It's a problem with the size of the brush radius. For now, after creating the "raster level", set the brush to "1pixel" and in the settings change the size from -0.58 to 0 so the grayed-out pixel disappears.

I forgot to send a pull request with the brush fix when this issue appeared on my screen I'll do it soon

**Comment by elixsmax** [comment]
> @elixsmax It's a problem with the size of the brush radius. For now, after creating the "raster level", set the brush to "1pixel" and in the settings change the size from -0.58 to 0 so the grayed-out pixel disappears.
> 
> I forgot to send a pull request with the brush fix when this issue appeared on my screen I'll do that soon because I need to review some others that are having some kind of issue.

Thank you so much!
