### ISSUE TITLE
Transparent Window Mode Missing

### ISSUE THREAD

**Issue by isthatshaz** [opentoonz/opentoonz#4901]
### Ask a question related to OpenToonz

Yesterday I was able to make my opentoonz window see through by going to the windows tab but that option is no longer there. Has it been relocated or removed?
Thanks

**Comment by DarrenTAnims** [comment]
It sounds like yes it has. What did you do in the meantime? Have you upgraded or changed your settings?
But the option to make your OpenToonz window transparent is in the latest version of OpenToonz, V1.7.1.

**Comment by isthatshaz** [comment]
Nope I didnt change anything, it was at the bottom before but now its just gone for me
![image_2023-05-17_172417924](https://github.com/opentoonz/opentoonz/assets/133872583/a6a16f85-1607-4441-8556-29bf24fa40f7)

**Comment by isthatshaz** [comment]
That worked! Thank you
