### ISSUE TITLE
I was working on a short anime film in open toonz and during animation and my some frames got crashed. Please help me with this , I am in great trouble right now.

### ISSUE THREAD

**Issue by Ethynhunt** [opentoonz/opentoonz#4908]
### Ask a question related to OpenToonz

I was working on a short anime film in open toonz and during animation and my some frames got crashed. Please help me with this , I am in great trouble right now.

**Comment by RodneyBaker** [comment]
@Ethynhunt You haven't provided any information about the trouble you are experiencing so there is really nothing to work with in troubleshooting your issue.   There are some common things you can do when troubleshooting and perhaps you can discuss those with other Opentoonz users via discord (chat).

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
