### ISSUE TITLE
unspecified crash

### ISSUE THREAD

**Issue by Ethynhunt** [opentoonz/opentoonz#4909]
crash details are attached with the report [https://1drv.ms/f/s!AmfBZwXOGjk5igyOHgeG0ex50ABw?e=zMwttz](url)

**Comment by RodneyBaker** [comment]
@Ethynhunt Your link goes to:  https://github.com/opentoonz/opentoonz/issues/url
As such there is nothing to see.
Most crash reports won't provide the information needed anyway so perhaps it is just as well.

I will again suggest a better way to resolve your issues is likely going to be to join an Opentoonz discord.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U


You may also wish to review other crash reports as they may contain solutions that resolved other users' issues.
Link to closed/resolved crash reports:  https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+label%3Acrash+is%3Aclosed

**Comment by RodneyBaker** [comment]
One of the first things to do when this error appears is... restart the computer.
Many other possible solutions can apply thereafter.

REF:  https://www.lifewire.com/how-to-fix-ntdll-dll-errors-2624474
