### ISSUE TITLE
Pasting a Raster drawing selection into a blank cell stops actions from being entered into History (UNDO Bug)

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#4910]
### Description

Pasting a Raster selection into a blank cell isn't recorded into the scene's History.  Actions taken afterwards are also no longer recorded.  Undo and Redo after this do not work properly.

This bug only seems to affect Raster levels.  Pasting into a blank cell is properly recorded in History with ToonzRaster and Vector levels.

I believe this is the same bug that is described in https://github.com/opentoonz/opentoonz/issues/4907 and https://github.com/opentoonz/opentoonz/issues/4905.

### Steps to Reproduce

1. Draw something on a Raster level
2. Use the Selection Tool to select part of the drawing
3. Press Copy
4. Select an empty cell on the X-Sheet
5. Press Paste (this action is not entered into History)
6. Perform other actions, such as drawing more strokes (these actions are also not entered into History)
7. Press Undo (a much earlier recorded action instead of the previous action is undone)

### Expected Behavior

Pasting a Raster selection and all actions following should be recorded into History so that Undo can function properly.

### Screenshots, Video & Crash Logs

https://github.com/opentoonz/opentoonz/assets/60277069/59159ae2-6916-48a9-98bf-4df5453e3a83

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

nightly build 2023-05-21

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Sure does @Bracket-H 
Just open the History window and watch... err... history unfold.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/83ee7d7a-7b15-4460-bd6a-08ceb4a06ed2)


Thanks @RattusaurusRex for delving into this issue.

**Comment by konero** [comment]
He's on latest nightly if you read his report...

I confirm the bug and it's very reproducible, I followed his steps exactly. Since no more actions are recorded into history, when you want to undo something you're essentially undoing something that happened awhile ago instead.

Possibly caused by: https://github.com/opentoonz/opentoonz/pull/4786, https://github.com/opentoonz/opentoonz/pull/4777, https://github.com/opentoonz/opentoonz/pull/4681.

**Comment by konero** [comment]
> In either case, here's a demo from me, just now. https://files.catbox.moe/el98zz.mp4

You're using Toonz Raster (green level), test with Raster (blue level).

**Comment by RodneyBaker** [comment]
I saw in the report that it was mentioned that @RattusaurusRex was using the latest nightly but... that's the problem... on my end I'm not having the issue with regular raster levels with the latest nightly.
The specific step I get to that isn't the same as reported is step No 5:

> Press Paste (this action is not entered into History)

The paste is entered into History for me (using standard raster levels).

**Comment by callybug** [comment]
https://files.catbox.moe/axbx3o.mkv Here's a demo from me (apologies for missing cursor). Undoing a cut/paste results in an overlap.
https://files.catbox.moe/vnh0px.mkv This isn't the best example, but I've had problems where I've cut/pasted a selection between layers onto existing drawings, and then parts of the drawing go missing. Sometimes it's like in the video, most times though it's been like a square hole is cut out of the drawing, tearing into History with no way to restore what was lost.
(OpenToonz 1.7, built from source, running in Mint XFCE)
