### ISSUE TITLE
ocurrio un crash

### ISSUE THREAD

**Issue by Alexismatias19** [opentoonz/opentoonz#4912]
### Description

quiero instalar opentoonz y no me deja porque ocurrio un crash

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![image](https://github.com/opentoonz/opentoonz/assets/134350474/d30586df-1214-427d-b5b5-79a2e0aac700)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Will close as not having enough information to investigate the problem further.
@Alexismatias19 I'll recommend joining one of the Opentoonz discords where other users can help in troubleshooting the problem.

Invitation link to Opentoonz discord:  https://discord.gg/UQxvYBKW5U
