### ISSUE TITLE
(Discussion) Stuff Directory / Library Resources

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4913]
Opentoonz users and developers,
This is a place to discuss thoughts on the stuff directory's contents and what needs to be considered going forward;
This discussion also relates to other aspects of the stuff directory that aren't the focus here such as user profiles and files required to operate Opentoonz.  That broader scope needs to be discussed in depth as well but here we want to consider resources stored in the Opentoonz Library such as brushes, textures, etc.  An additional topic of interest might be the help files stored in docs directory.

From what I can tell, the two main categories of interest are:

Content and Distribution

This core interest here is to consider what the default (and specifically required) content for the Library is.
As an example, Custom Panels has a directory in the LIbrary that containts two example custom panel files.
This is to allow the user to see the potential behind the Custom Panels feature and have something to modify while learning how to create new custom panels.  There could be a whole lot more example files included... but where to draw the line?

Similary, we have a good variety of MyPaint brushes but there could be hundreds more as there are many available that are not included as part of the Opentoonz distribution.

The same can be said for other resources as well although many of those resources may require more work than just adding additional files; example:  Shader files can be added to the Libary but they need to specifically be added into Opentoonz by editing a number of files dedicated for that purpose.

At present we aren't having any issue with the number of resources or their file size.
The reason for this discussion however is to begin to see a future where that could potentially be a problem.

Your thoughts?

**Comment by deathchimera** [comment]
@Bracket-H I don't think your opinions on the topic are that unpopular. I believe new features like OCA export and the new Copy / Clipboard functionality being introduced to OT are big steps in the right direction for the program. Trying to strengthen the bridge between other art software and OT seems like the best way to go. It might take a while for newcomers like myself to understand this "Asset Creation" workflow that OT works best with, but if features continue to be introduced and refined facilitating this bridge, then the tools already included in OT will shine even brighter.

The clipboard functionality has already helped me achieve my goal of replicating that Flipnote style I was looking for when I had initially opened that Issue. Before, it had been cumbersome to streamline exporting the frames I wanted from Krita and to use them in OT, but now it's as simple as a copy and paste, occasionally exporting new frames from OT to paint over. I think that OCA would easily streamline this process further, as it already distinguishes what program the OCA file is coming from.

For the question of resource management, I do like how Krita implements importing optional brush packs. I'm not sure where to draw the line with what resources are brought into OT as default though.

**Comment by konero** [comment]
> Before, it had been cumbersome to streamline exporting the frames I wanted from Krita and to use them in OT, but now **it's as simple as a copy and paste**, occasionally **exporting new frames from OT to paint over**. I think that OCA would easily streamline this process further, as it already distinguishes what program the OCA file is coming from.

Why not just open the images in Krita directly? OpenToonz will update them if you use the Reload option.

Load the images into Krita using `File > Import Animation frames`, do your paint over then go to File > Export Animation frames and save them in the same location with the same name, so if the original drawings were called `A_000X.png` put in the `Base name` field `A_` then export, back in OpenToonz right-click the Level palette and click `Reload`.

If you want to modify again, just go back to Krita, do some painting, export the frames again, then use Reload again.

I worked this way on a scene with 187 drawings using Krita's mesh warp, copy-pasting each drawing back and forth would be a huge time waste.

**Comment by deathchimera** [comment]
@konero True, I did this once for a timed project last year, but I think I experienced some pains with how OT exports the frames since I just needed keyframes and it would export the interpolated frames for camera movements or something. That's all blurry to me now though. I was new to the program at the time and it left a bad impression on me somehow for my own odd reasons. I'll play with that though, need more experience in that area I suppose.

**Comment by konero** [comment]
> [..] I think I experienced some pains with how OT exports the frames since I just needed keyframes and it would export the interpolated frames for camera movements or something.

You don't need to export from OpenToonz if you're working on a raster level (blue level), they're already saved to disk as PNG files in the project folder as only unique frames, so you can just import these into Krita directly.

**Comment by andeon** [comment]
@konero would be nice if we had something like that.

[Cells] 
     [Open with]
               [GIMP]
               [Krita]
               [Photoshop]
               [Manage apps] (Option to set path or remove the external programs)

Implementing it would be very simple, but it could help a lot for a clean workflow.

About the Library, I like to have minimal resources to work with, but that cover the maximum possibilities and follow standards to look like they are integrated into the program.

**Comment by RattusaurusRex** [comment]
I like that other programs have an interface that shows you what additional content is available for download that you can add only if you want to.  If you want to download additional resources for Opentoonz, you have to go looking for it, download it, and move the files to the right place.  

As for the drawing experience in Opentoonz, I think a better Viewer and less drawing lag is what would improve that, not more brushes.

**Comment by andeon** [comment]
Something that doesn't fit for me in Opentoonz is the trail and some vector brush in the vectors tab. I was working on a proposal to remove most of it and add something that would go well with anime and other animation styles. 

I think these stuff comes from TAB KIDS https://youtu.be/CPGQvsCsJYE?t=221 so maybe that's why it looks like that.

**Comment by RodneyBaker** [comment]
Will close for now but if anyone has thoughts relate to stuff/library contents please feel free to add it here.
Thanks for any and all feedback.
