### ISSUE TITLE
Opentoonz crashed

### ISSUE THREAD

**Issue by rockyhandso** [opentoonz/opentoonz#4918]
### Description

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Vega 3 Graphics
GPU Version: 4.6.14761 Compatibility Profile Context 21.30.26 30.0.13026.3

Crash File: C:\Users\Admin\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230528-222534.log
Mini Dump File: C:\Users\Admin\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230528-222534.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: eat on table
Scene Name: coffee time
Project Path: C:\OpenToonz stuff\projects\eat on table\eat on table_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\eat on table\scenes\coffee time.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0372791.inf_amd64_621505ff768b464e\B372529\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0372791.inf_amd64_621505ff768b464e\B372529\atio6axx.dll
C:\Windows\SYSTEM32\dxva2.dll
C:\Windows\System32\DriverStore\FileRepository\u0372791.inf_amd64_621505ff768b464e\B372529\atig6txx.dll
C:\Windows\SYSTEM32\atiadlxx.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\pdh.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\drprov.dll
C:\Windows\System32\WINSTA.dll
C:\Windows\System32\ntlanman.dll
C:\Windows\System32\davclnt.dll
C:\Windows\System32\DAVHLPR.dll
C:\Windows\System32\wkscli.dll
C:\Windows\SYSTEM32\cscapi.dll
C:\Windows\SYSTEM32\browcli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffbb0248b4c] <ntdll.dll>
  2> RtlRaiseException [0x7ffbb02212c6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffbb0270f0e] <ntdll.dll>
  4> PinchTool::getToolType [0x7ffb791e3a57] <tnztools.dll>
  5> PinchTool::getToolType [0x7ffb791e4f10] <tnztools.dll>
  6> PinchTool::getToolType [0x7ffb791e98fc] <tnztools.dll>
  7> PinchTool::getToolType [0x7ffb791e8cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff644efbec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff644efa7ee] <OpenToonz.exe>
 10> QWidget::event [0x7ffb78358092] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff644ef942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ffb783355c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ffb783334e0] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ffb77f2318a] <Qt5Core.dll>
 15> QApplicationPrivate::sendMouseEvent [0x7ffb783367c5] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ffb783809d2] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ffb7837e96e] <Qt5Widgets.dll>
 18> QApplicationPrivate::notify_helper [0x7ffb783355c0] <Qt5Widgets.dll>
 19> QApplication::notify [0x7ffb78334643] <Qt5Widgets.dll>
 20> QCoreApplication::notifyInternal2 [0x7ffb77f2318a] <Qt5Core.dll>
 21> QGuiApplicationPrivate::processMouseEvent [0x7ffb788a47c3] <Qt5Gui.dll>
 22> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb7888f030] <Qt5Gui.dll>
 23> QEventDispatcherWin32::processEvents [0x7ffb77f6bcfa] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ffb730028d9] <qwindows.dll>
 25> QEventLoop::exec [0x7ffb77f1f64c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x7ffb77f22164] <Qt5Core.dll>
 27> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff644e15219] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff64523eab7] <OpenToonz.exe>
 29> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff64523e092] <OpenToonz.exe>
 30> BaseThreadInitThunk [0x7ffbafc77614] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7ffbb02226a1] <ntdll.dll>

### Steps to Reproduce

1. 
2. 

### Expected Behavior

 EXCEPTION_ACCESS_VIOLATION

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Will close as lacking actionable information to troubleshoot.
@rockyhandso If you can provide additional information that will be helpful but... your crash report does appear to be the same as a few others recently reported so you may want to look at those as that might give you an idea of how best to proceed.

Closed crash reports:
https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+label%3Acrash+is%3Aclosed

Open crash reports:
https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+label%3Acrash+is%3Aopen
