### ISSUE TITLE
﻿Change position and insert frame between two frame in xsheet directly

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#492]
You can not change position frame between two frame directly unless:
1. Move frame to other column
2. Empty space between two frame
3. Move back frame in empty space

And you can not insert frame from level strip to between two frame in xsheet directly too.

![change-position-frame1](https://cloud.githubusercontent.com/assets/16509592/16258924/4d3b3318-3875-11e6-94c6-4d4ca2f2e8f1.gif)

![change-position-frame2](https://cloud.githubusercontent.com/assets/16509592/16258931/5804921c-3875-11e6-8a44-65d98ee0d495.gif)

**Comment by 2dvision** [comment]
Maybe be useful behaves like this:

![change-position-frame3](https://cloud.githubusercontent.com/assets/16509592/16292694/1c55b764-3929-11e6-9e2f-dcb6381559af.gif)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
