### ISSUE TITLE
se cierra el programa cuando exporta a video 

### ISSUE THREAD

**Issue by leoflute** [opentoonz/opentoonz#4926]
### Description

cuando renderiza o exporta  a video se cierrra 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by gab3d** [comment]
Hola,
Esta plataforma es para escribir en inglés.
Soy el traductor a español del programa, pero no está bien visto escribir en otros idiomas acá, para eso están los foros como el que hay en Google y al cual podés acceder desde el menú Ayuda de OpenToonz.

Es posible que tu problema se deba a que se te esté agotando la RAM mientras estás procesando el video.
Lo que se recomienda en general en esos casos es no procesar a un archivo de video, sino a una secuencia de imágenes. De esa forma cuando el programa se cuelgue, sólo perderás la imagen correspondiente al fotograma que se estaba procesando en ese momento. Luego podés volver a cargar el programa y continuar el procesamiento de allí en adelante.

Saludos y si querés la seguimos en español en el foro de Google, o sino acá mismo pero en inglés, sí?
