### ISSUE TITLE
Window See Through Mode not working in Opentoonz 1.7.1 

### ISSUE THREAD

**Issue by AMoczar** [opentoonz/opentoonz#4929]
### Description

I have a Debian Bullseye 5.10 KDE system and I just compiled Opentoonz 1.7.1 to use the new window see through mode, but it has no effect on the opacity of the OpenToonz window. I also tested the nightly build 2023-06-02 11:54:30, but same issue.

Note: I removed qt5-default from the dependency list because it seems to be unavailable for my system. OpenToonz successfully compiled with no errors regardless, so I don't know if that is an issue.

### Steps to Reproduce

1. Go to Window->Toggle Main Window's See Through Mode.
2. The pop-up window appears with a slider to adjust the transparency level.

### Expected Behavior

My window remains completely visible while adjusting the slider and toggling the Quick Toggle button.

### OpenToonz Version

1.7

### OpenToonz Version Information

built 2 june 2023

### Operating System

Linux

### GPU

AMD

### Graphics Tablet

None

**Comment by flurick** [comment]
Could it be a wm/compositor setting or does other transparent programs look ok for example window shadows etc?

**Comment by AMoczar** [comment]
Hey @flurick and @Bracket-H  that worked! My compositor was using OpenGL 2.0, so I switched it to OpenGL 3.1 and that fixed the issue. I have read of KDE theme effects failing do to using older OpenGL back-ends.


Thanks a lot for your help! The window see-through feature now works as advertised.
