### ISSUE TITLE
Ability to add color to palette directly

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#493]
Currently if select one color in palette and click "New Style", OT duplicate selected color, Then you can change that color in "Style Editor".

if possible when user choose color in "Style Editor", if There was not that color in palette, By clicking "New Style" that color add to palette directly.

I think this is useful and fast for create new color in palette.

**Comment by inkapnea** [comment]
Somewhere I saw a Style Editor mockup depicting the “New” button next to “Apply” but I can't find it right now.
Another sleek solution for adding new colors to he palette. Hope to see it implemented.
So this could be a duplicate request.

**Comment by 2dvision** [comment]
@inkapnea Maybe you saw this mockup.

![new-style-button](https://cloud.githubusercontent.com/assets/16509592/16485249/21b93212-3ed3-11e6-8a9c-3bfc1334f8c8.jpg)

**Comment by inkapnea** [comment]
I kindly repeat the request to add the "New Style" button if feasible. Thank you very much, OpenToonz is shaping really great month after month!

**Comment by artisteacher** [comment]
It's a nice idea, though I think it would only be possible with "auto-apply" turned off.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
