### ISSUE TITLE
SoapBubble Iwa effect not working

### ISSUE THREAD

**Issue by RattusaurusRex** [opentoonz/opentoonz#4939]
### Description

SoapBubble Iwa only seems to be rendering black shapes instead of the soap bubble effect.  It works properly in 1.6 until this nightly: [2023-01-15 02:30:24 UTC](https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_0252f0e81a5b5b2c7d02452b5bf77c499522abfe)

### Steps to Reproduce

1. Set up a SoapBubble Iwa effect like the example here: https://www.youtube.com/watch?v=VUN5-CkGJwI
2. Preview or Render (shape is just black)

### Screenshots, Video & Crash Logs

SoapBubble Iwa in 1.6:
![image](https://github.com/opentoonz/opentoonz/assets/60277069/daba3c1f-142f-49b0-a369-595f9bb0674b)

SoapBubble Iwa in 1.7.1:
![image](https://github.com/opentoonz/opentoonz/assets/60277069/66a25048-908b-4db2-a59f-ee1d022da7e8)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

nightly build 2023-05-21

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by JParks123** [comment]
This problem also effects the Dwango Plugins specifically the Light Incident node is now not working correctly. 😭

**Comment by RodneyBaker** [comment]
@JParks123 Glare FX is working for me.
Try changing the render option and see if that doesn't change things.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/85f9c043-d933-44f7-a7d1-277b6db00541)

**Comment by RattusaurusRex** [comment]
Glare Iwa is definitely much dimmer in 1.7.  Comparison between the two on default settings:

1.6: 
![image](https://github.com/opentoonz/opentoonz/assets/60277069/1f796011-a1cd-43fb-95e9-f0dcd4572266)

1.7: 
![image](https://github.com/opentoonz/opentoonz/assets/60277069/df97a7e9-2710-42c5-b975-1f5e82af3097)

**Comment by shun-iwasawa** [comment]
@RattusaurusRex 
> Glare Iwa is definitely much dimmer in 1.7. Comparison between the two on default settings

In v1.6, the conversion of light intensity to RGB was missing in the results; this has been corrected in v1.7 and the correct results are now produced.
In v1.7 the simillar results as in v1.6 can be obtained by adjusting Gamma to 0.455 (=1/2.2) using GammaFx or LevelMasterInoFx.

@Bracket-H 
> To me, there is more than dimness, that's some pretty awful banding like degradation. Like the values, or even the alpha channel, are messed up.

This seems to be an unintended issue. Could you please post the details in another Issue?
