### ISSUE TITLE
Open toonz crash

### ISSUE THREAD

**Issue by Conner206** [opentoonz/opentoonz#4941]
### Description

My screen keeps lagging

### Steps to Reproduce

I figure out away to stop the screen lag

### Expected Behavior

I drag my mouse across the timeline and the screen starts to freeze.

### OpenToonz Version

1.7

### OpenToonz Version Information

June 2033

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
@Conner206 I've added a link to the Opentoonz discord in one of your other reports.
That will be a much better way to troubleshoot problems as you are learning Opentoonz.
