### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by AK000026** [opentoonz/opentoonz#4943]
### Ask a question related to OpenToonz

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-06-10 17:19:41
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 531.79

Crash File: C:\Users\anshk\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230610-171941.log
Mini Dump File: C:\Users\anshk\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230610-171941.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: walk cycle stick figure
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\walk cycle stick figure.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\bcrypt.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_269da44064f4461c\igc64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_269da44064f4461c\igd12dxva64.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\Windows.ApplicationModel.dll
C:\Windows\system32\propsys.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\NetworkExplorer.dll
C:\Windows\system32\mssprxy.dll
C:\Windows\System32\DriverStore\FileRepository\nvami.inf_amd64_b05947f9052e5fd2\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\wldp.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\system32\nvspcap64.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\SYSTEM32\nvapi64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_269da44064f4461c\igd10um64xe.DLL
C:\Windows\SYSTEM32\ncrypt.dll
C:\Windows\SYSTEM32\NTASN1.dll
C:\Windows\SYSTEM32\dcomp.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\System32\winrnr.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\nlansp_c.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\System32\DriverStore\FileRepository\nvami.inf_amd64_b05947f9052e5fd2\nvldumdx.dll
C:\Windows\System32\DriverStore\FileRepository\nvami.inf_amd64_b05947f9052e5fd2\nvwgf2umx.dll
C:\Windows\System32\DriverStore\FileRepository\nvami.inf_amd64_b05947f9052e5fd2\Display.NvContainer\MessageBus.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_269da44064f4461c\igd10iumd64.dll
C:\Windows\SYSTEM32\ControlLib.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_269da44064f4461c\IntelControlLib.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_269da44064f4461c\igdgmm64.dll
C:\Windows\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffca04a7a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffca044e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffca04d2cee] <ntdll.dll>
  4> ImageBuilder::setImageInfo [0x7ffc3a69801a] <toonzlib.dll>
  5> ToolUtils::updateSaveBox [0x7ffc4e8a46ac] <tnztools.dll>
  6> ToolUtils::updateSaveBox [0x7ffc4e8a4794] <tnztools.dll>
  7> RasterSelection::makeFloating [0x7ffc4e999c47] <tnztools.dll>
  8> RasterSelection::setFrameId [0x7ffc4e92d96c] <tnztools.dll>
  9> RasterSelection::operator= [0x7ffc4e929d31] <tnztools.dll>
 10> RasterSelection::setTransformationCount [0x7ffc4e92e327] <tnztools.dll>
 11> RasterSelection::setTransformationCount [0x7ffc4e9378c5] <tnztools.dll>
 12> RasterSelection::isPastedSelection [0x7ffc4e92be06] <tnztools.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7cc7eb4fd] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7cc7ea5f8] <OpenToonz.exe>
 15> QWidget::event [0x7ffc3b058066] <Qt5Widgets.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7cc7e942b] <OpenToonz.exe>
 17> QApplicationPrivate::notify_helper [0x7ffc3b0355c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffc3b0334e0] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffbf2ce318a] <Qt5Core.dll>
 20> QApplicationPrivate::sendMouseEvent [0x7ffc3b0367c5] <Qt5Widgets.dll>
 21> QDesktopWidget::workAreaResized [0x7ffc3b0809d2] <Qt5Widgets.dll>
 22> QDesktopWidget::workAreaResized [0x7ffc3b07e96e] <Qt5Widgets.dll>
 23> QApplicationPrivate::notify_helper [0x7ffc3b0355c0] <Qt5Widgets.dll>
 24> QApplication::notify [0x7ffc3b034643] <Qt5Widgets.dll>
 25> QCoreApplication::notifyInternal2 [0x7ffbf2ce318a] <Qt5Core.dll>
 26> QGuiApplicationPrivate::processMouseEvent [0x7ffc138247c3] <Qt5Gui.dll>
 27> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc1380f030] <Qt5Gui.dll>
 28> QEventDispatcherWin32::processEvents [0x7ffbf2d2bcfa] <Qt5Core.dll>
 29> qt_plugin_query_metadata [0x7ffc48b828d9] <qwindows.dll>
 30> QEventLoop::exec [0x7ffbf2cdf64c] <Qt5Core.dll>
 31> QCoreApplication::exec [0x7ffbf2ce2164] <Qt5Core.dll>
 32> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7cc705219] <OpenToonz.exe>
 33> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7ccb2eab7] <OpenToonz.exe>
 34> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7ccb2e092] <OpenToonz.exe>
 35> BaseThreadInitThunk [0x7ffc9e5226ad] <KERNEL32.DLL>
 36> RtlUserThreadStart [0x7ffca048a9f8] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
Closing as an incomplete report.
Please consider joining one of the Opentoonz discords (chat) where others can assist you in troubleshooting.

Invite link:  https://discord.gg/UQxvYBKW5U
