### ISSUE TITLE
Timeline Crash

### ISSUE THREAD

**Issue by Conner206** [opentoonz/opentoonz#4944]
### Ask a question related to OpenToonz

I'm having trouble running opentoonz when I use the timeline . How do I stop opentoonz from crashing

**Comment by RodneyBaker** [comment]
@Conner206 You should join one of the Opentoonz discords (chat) where others can help you troubleshoot your issues.
Here's a link/invite:

https://discord.gg/UQxvYBKW5U

**Comment by RodneyBaker** [comment]
Closing as an incomplete report that has no actionable information.
