### ISSUE TITLE
List View for Studio Palettes (green icon with s at the bottom) seems to be broken (black bars) ?

### ISSUE THREAD

**Issue by Bracket-H** [opentoonz/opentoonz#4949]
### Description

List view for studio palettes (or palettes that have references to other colors? More testing needed) is broken.
It only shows the first entry and the rest is messed up black stuff.
![image](https://github.com/opentoonz/opentoonz/assets/93729441/7adda797-0788-46c1-ab16-2ac4f485ef30)

Palettes which aren't 'studio palettes' are unaffected
![image](https://github.com/opentoonz/opentoonz/assets/93729441/6e75113f-2923-46d3-9497-4035e0ccf76b)

The only way to see other colors is to scroll them into the first place
![image](https://github.com/opentoonz/opentoonz/assets/93729441/20d86b06-9780-4f7f-a00f-247a4758762a)
scrolling down so that another color 'scrolls up' into the first position:
![image](https://github.com/opentoonz/opentoonz/assets/93729441/f19467e6-1463-4cc5-9d5d-aaae495ac41d)

I have noticed that since my last Linux update, that I have had trouble with GTK apps...their windows needing a resize to show up correctly.
But OT is a Qt application...so I'm only adding this detail for completeness sake.

### Steps to Reproduce

1. Choose a studio palette from the palette window 
or
1.Right click a non studio palette and choose "Convert To Studio Palette and Overwrite"
2.Receive broken palette display 

The colors themselves are not messed with, it's just the display.

### Expected Behavior

OT making me a coffee and a sandwich...
Just kidding (partly) 
For the colors to be displayed correctly.

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

68c066af8d9b87aa18837312a31aaca23d48f0a

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by konero** [comment]
I can reproduce but only on Ubuntu, it works fine on Windows.
