### ISSUE TITLE
Selection Tool Bug

### ISSUE THREAD

**Issue by indfibneiubdf** [opentoonz/opentoonz#4954]
### Description

Whenever I try to use the selection tool, it doesn't seem to be doing anything that it needs to. I can't stretch or squish the image, nor can I delete it.

### Steps to Reproduce

 
Unknown

### Expected Behavior

I should be able to be to select the image and move it around, or morph it into any way you want it to as can seen here: https://www.youtube.com/watch?v=drXtrLPJ2uw The time stamp is (4:18)

### Screenshots, Video & Crash Logs

https://github.com/opentoonz/opentoonz/assets/111816819/5ad71b81-30c1-4999-8654-8dd32a77bce6

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by RodneyBaker** [comment]
It looks to me like you need to select the cell (green:  toonz raster level) in the timeline before you select the area of the drawing.
At that point it should select that area and not whatever blank area it is currently selecting.

**Comment by shun-iwasawa** [comment]
Please turn off the `Modify Savebox` checkbox in the tool options bar.
When that checkbox is ON, the Selection tool has a different role. (i.e. Specifying the savebox for the Toonz raster level that will serve as the boundary of the Fill tool)

**Comment by indfibneiubdf** [comment]
That seemed to do the trick, thanks
