### ISSUE TITLE
Sluggish response after addition of Assistants Tool

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#4957]
This is just an initial report to let others know of issues appearing after the incorporation of the Krita-like Assistants Tool.
It's not entirely clear what is causing the problem nor why the problem is appearing now but not in original testing.

Hopefully the problem will be resolved speedily and we won't need to revert the Assistants Tool PR.

I did want to let others know the problem has an associated bug report opened.

### Steps to Reproduce

To test just install any of the latest nightly releases after the inclusion of Assistants Tool from #4852 

If the problem is present on your system it will be very obvious.

**Comment by konero** [comment]
Can you give more detail?

**Comment by RodneyBaker** [comment]
I'm currently on the road so can't provide additional detail.
I did want to get the word out though to be on the look for issues.
If you are using a nightly and NOT experiencing any issues then... very interesting.

**Comment by konero** [comment]
> Are you having no issues with currently nightly while or after using the Assistants Tool @konero?

I didn't test nightly (I built myself) but I am having a few issues, I outlined them in #4852.

**Comment by RattusaurusRex** [comment]
Drawing with stylus on ToonzRaster level: 

https://github.com/opentoonz/opentoonz/assets/60277069/7a4c3665-f34a-4e2b-b9aa-9df8271e0593

**Comment by RodneyBaker** [comment]
An update here...

After noticing my entire system was being laggy, I decided to restart my system (again as I had done before with no change) but this time I decided to download the latest Wacom driver for my tablet and...

After a restart... no lag.
I'm currently playing with the Assistants to see when/if the lag starts afresh.

**Comment by RodneyBaker** [comment]
Keeping this open for now to collect troubleshooting information for users that have issues so we can work through them.

**Comment by andeon** [comment]
It increases usage memory very fast over time, I don't know why this leak, maybe it registers and calculates constantly, so it needs to be better optimized.

Wouldn't a [SQLite](https://www.sqlite.org) database work well with this concept?

**Comment by RodneyBaker** [comment]
Will close this as #4963 resolves the issue with Assistant Tool slowness.  (Thank you @shun-iwasawa!)
For other issues likely related to addition of Assistants Tool please see:  #4968

**Comment by blackwarthog** [comment]
Sorry for the late answer. I worked on implementation of assistants for other tools (toonz brush and toonz raster brush), and did not visit github for a while. I'm trying to reduce my presence on github since MS bought it. Now i've enabled email notifications to be in touch.

Is this problem already solved completely or it is still there?
