### ISSUE TITLE
Dialogs action buttons not working properly 

### ISSUE THREAD

**Issue by andeon** [opentoonz/opentoonz#4962]
### Description

Dialog with buttons "Save All", "Save Scene Only", "Discard Changes" , "Cancel"  etc. not working

I'm testing with appimage, I think only linux users are affected by this, not sure about MacOS.

I believe the problem was introduction after this fix patch: https://github.com/opentoonz/opentoonz/pull/4872

Edit:
Weird I decided to test the opentoonz flatpak 1.7.1 and not found this problem.

### Steps to Reproduce

1. Try closing opentoonz without saving by menu or keyboard shortcuts after create some level.

### Screenshots, Video & Crash Logs

[dialogbug.webm](https://github.com/opentoonz/opentoonz/assets/11843239/68d17065-7d0b-436f-8d8a-fc71aa65a9b1)

### OpenToonz Version

1.7

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by andeon** [comment]
I need to investigate more, but the last appimage that worked without this issue was this https://github.com/opentoonz/opentoonz/actions/runs/4859247003

Perhaps something self builted is slightly different from what is generated by the actions.

**Comment by andeon** [comment]
@Bracket-H Could you tell me which version of Qt are you using to build?

**Comment by andeon** [comment]
I tried building appimage with the most up-to-date qt, qt-5.15.4-focal and it didn't work. ref: https://github.com/andeon/opentoonz/actions/runs/5352120940

So I rolled back the fix patch: #4872 and it's back to working as I thought. ref: https://github.com/andeon/opentoonz/actions/runs/5371114137

Now I just can't understand why this fix works on traditional build and Flatpak and not AppImage maybe something missing or deprecated in the appimage script.

**Comment by morevnaproject** [comment]
The problem is related to use of `idClicked()` signal.
This signal is available starting from QT  5.15 - https://doc.qt.io/qt-5/qbuttongroup.html#idClicked

The AppImage was built with older version of QT, this is why problem appears.

The issue is also mentioned here - https://github.com/opentoonz/opentoonz/issues/5508#issuecomment-2198465778

**Comment by morevnaproject** [comment]
...so in this commit you probably should revert only places when `idClicked()` signal is used - https://github.com/andeon/opentoonz/commit/d7612d2880dd31649d70b6198c05133d998d9d1d

Possibly, we can use `buttonClicked()` signal instead of `idClicked()`?

**Comment by andeon** [comment]
Apparently buttonClicked is obsoleted at 5.15  https://doc-snapshots.qt.io/qt5-5.15/qbuttongroup-obsolete.html#buttonClicked-1

Therefore, it is necessary to check and update the ci-scripts/linux/ to work with new packages version and .github/workflows/workflow_linux.yml to use new ones too for build the appimage.  Need found the correct QT maybe v5.15.2 not sure which one is used in Windows e MacOs.

**Comment by morevnaproject** [comment]
As an alternative, is it possible to add conditional code, which checks QT version?
In this case it will keep compatibility with older QT versions and OT will support wider range of environments.

**Comment by andeon** [comment]
Closing this issue, appImage now works after set Qt 5.15 for build Opentoonz.
