### ISSUE TITLE
Level strip scroll bar/pane moves past window frame

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#497]
When the level strip is docked on the right and the pane is shifted too far right, the vertical scroll bar (and even the level strip pane) moves past the window frame.  This did not happen in 1.0.2 (Windows).  It used to keep the vertical scroll bar and stop when the icons hit the scroll bar.

![level strip issue after](https://cloud.githubusercontent.com/assets/19245851/16272994/db8aa1ce-386d-11e6-9b5d-c1f14183cdfb.JPG)

**Comment by blurymind** [comment]
ah well spotted! I can confirm. This is an annoying bug
