### ISSUE TITLE
unspecified crash

### ISSUE THREAD

**Issue by friedkidd** [opentoonz/opentoonz#4970]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-06-21 22:00:40
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 8

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.4369

Crash File: C:\Users\mkfar\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230621-220040.log
Mini Dump File: C:\Users\mkfar\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230621-220040.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Lab8
Scene Name: The Clever Crow
Project Path: C:\OpenToonz stuff\projects\Lab8\Lab8_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Lab8\scenes\The Clever Crow.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\ole32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\x64\AudioDevProps2.dll
C:\Program Files\Huawei\PCManager\plugins\PerfWndMonModule.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2ec86af404806919\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2ec86af404806919\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2ec86af404806919\igdgmm64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2ec86af404806919\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\x64\ProductInfo.dll
C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\x64\ASM.Plugin.AudioDevProps2.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.1635_none_270f70857386168e\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\WINDOWS\SYSTEM32\TextShaping.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffca7307a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffca72ae232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffca7332cee] <ntdll.dll>
  4> TFunctorInvoker::qt_static_metacall [0x7ffc25e1bd62] <tnzcore.dll>
  5> TFunctorInvoker::qt_static_metacall [0x7ffc25e1ec99] <tnzcore.dll>
  6> TFunctorInvoker::qt_static_metacall [0x7ffc25e18d4e] <tnzcore.dll>
  7> TFunctorInvoker::qt_static_metacall [0x7ffc25e18eee] <tnzcore.dll>
  8> Tiio::JpgReader::open [0x7ffc25df45ed] <tnzcore.dll>
  9> TImageReader::open [0x7ffc25cfdb8f] <tnzcore.dll>
 10> TImageReaderP::TImageReaderP [0x7ffc25cfb00b] <tnzcore.dll>
 11> TLevelReader::getFrameReader [0x7ffc25d00627] <tnzcore.dll>
 12> TLevelReader::getImageInfo [0x7ffc25d007e7] <tnzcore.dll>
 13> TXshSimpleLevel::load [0x7ffc260cfea1] <toonzlib.dll>
 14> ToonzScene::loadLevel [0x7ffc2608221d] <toonzlib.dll>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60dabe81c] <OpenToonz.exe>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60dabfe40] <OpenToonz.exe>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60dac1280] <OpenToonz.exe>
 18> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60d998d4c] <OpenToonz.exe>
 19> QWidget::event [0x7ffc2a6d85d3] <Qt5Widgets.dll>
 20> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60d99942b] <OpenToonz.exe>
 21> QApplicationPrivate::notify_helper [0x7ffc2a6b55c0] <Qt5Widgets.dll>
 22> QApplication::notify [0x7ffc2a6b41f1] <Qt5Widgets.dll>
 23> QCoreApplication::notifyInternal2 [0x7ffc2a2a318a] <Qt5Core.dll>
 24> QDesktopWidget::workAreaResized [0x7ffc2a6ff721] <Qt5Widgets.dll>
 25> QDesktopWidget::workAreaResized [0x7ffc2a6fead8] <Qt5Widgets.dll>
 26> QApplicationPrivate::notify_helper [0x7ffc2a6b55c0] <Qt5Widgets.dll>
 27> QApplication::notify [0x7ffc2a6b4643] <Qt5Widgets.dll>
 28> QCoreApplication::notifyInternal2 [0x7ffc2a2a318a] <Qt5Core.dll>
 29> QGuiApplicationPrivate::processDrop [0x7ffc3b6d3820] <Qt5Gui.dll>
 30> QWindowSystemInterface::handleDrop [0x7ffc3b6bc950] <Qt5Gui.dll>
 31> 
 32> DoDragDrop [0x7ffca705529b] <ole32.dll>
 33> NdrNsSendReceive [0x7ffca52073f3] <RPCRT4.dll>
 34> NdrClientCall3 [0x7ffca527451a] <RPCRT4.dll>
 35> NdrStubCall3 [0x7ffca51e4d23] <RPCRT4.dll>
 36> CStdStubBuffer_Invoke [0x7ffca6ba5daf] <combase.dll>
 37> WindowsGetStringRawBuffer [0x7ffca6b7dfad] <combase.dll>
 38> WindowsGetStringRawBuffer [0x7ffca6b7dd38] <combase.dll>
 39> Ordinal67 [0x7ffca6ba9191] <combase.dll>
 40> DllGetClassObject [0x7ffca6b80dd7] <combase.dll>
 41> CoWaitForMultipleHandles [0x7ffca6b29c69] <combase.dll>
 42> DllGetClassObject [0x7ffca6b86859] <combase.dll>
 43> Ordinal87 [0x7ffca6b4a608] <combase.dll>
 44> Ordinal87 [0x7ffca6b4aed9] <combase.dll>
 45> DispatchMessageW [0x7ffca57e8231] <USER32.dll>
 46> DispatchMessageW [0x7ffca57e7cf1] <USER32.dll>
 47> QEventDispatcherWin32::processEvents [0x7ffc2a2ec22c] <Qt5Core.dll>
 48> qt_plugin_query_metadata [0x7ffc25b028d9] <qwindows.dll>
 49> QEventLoop::exec [0x7ffc2a29f64c] <Qt5Core.dll>
 50> QCoreApplication::exec [0x7ffc2a2a2164] <Qt5Core.dll>
 51> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff60d8b5219] <OpenToonz.exe>
 52> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60dcdeab7] <OpenToonz.exe>
 53> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff60dcde092] <OpenToonz.exe>
 54> BaseThreadInitThunk [0x7ffca5f326ad] <KERNEL32.DLL>
 55> RtlUserThreadStart [0x7ffca72ea9f8] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
What was you doing at the time?
You've added no steps for reproduction. Without any hint at the problem, nothing can be done about this report.
