### ISSUE TITLE
Logitech webcam driver issue

### ISSUE THREAD

**Issue by kiurachan** [opentoonz/opentoonz#4971]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-06-21 19:42:52
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 1607
OS Kernel: 10.0.14393
CPU Threads: 4

Crash File: C:\Users\Professional\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230621-194252.log
Mini Dump File: C:\Users\Professional\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230621-194252.dmp

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\windows.storage.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\System32\powrprof.dll
C:\Windows\System32\advapi32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\shlwapi.dll
C:\Windows\System32\kernel.appcore.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\profapi.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\msvcp_win.dll
D:\OpenToonz\Qt5Xml.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
D:\OpenToonz\glut64.dll
D:\OpenToonz\Qt5SerialPort.dll
D:\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
D:\OpenToonz\colorfx.dll
C:\Windows\System32\WS2_32.dll
D:\OpenToonz\image.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\tnzcore.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\MSASN1.dll
D:\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
D:\OpenToonz\VCRUNTIME140.dll
D:\OpenToonz\VCRUNTIME140_1.dll
D:\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\DDRAW.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.14393.2457_none_a13eaee9d8fd5c07\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
D:\OpenToonz\libmypaint-1-4-0.dll
D:\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
D:\OpenToonz\Qt5Svg.dll
D:\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\bcrypt.dll
C:\Windows\SYSTEM32\DCIMAN32.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libjson-c-2.dll
D:\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\SYSTEM32\RTWorkQ.DLL
D:\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\atig6pxx.dll
C:\Windows\SYSTEM32\atio6axx.dll
C:\Windows\SYSTEM32\atiadlxx.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\atig6txx.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlInitializeCriticalSection [0x7fff02ab5e90] <ntdll.dll>
  2> RtlImageNtHeaderEx [0x7fff02a8fa1b] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff02af96fa] <ntdll.dll>
  4> DriverProc [0x7f8411c9] <lvcod64.dll>
  5> ICSendMessage [0x7ffeecd728fc] <MSVFW32.dll>
  6> ICOpen [0x7ffeecd72a98] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffed2f56212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffed2f54478] <image.dll>
  9> initImageIo [0x7ffed2ef7ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6568f0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6568f2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff656d1eab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff656d1e092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7fff027b84d4] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7fff02abe851] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### OpenToonz Version Information

Build Mar 14 2023

### Operating System

Windows

### GPU

Other

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The following logitec webcam driver is causing a conflict:

C:\Windows\SYSTEM32\lvcod64.dll

If you remove or rename that file the problem should go away.
Some users report they are still able to use their legacy webcam even without that driver but we won't know until you provide feedback if this works for you as well.

**Comment by RodneyBaker** [comment]
Closing as likely resolved.
@kiurachan Please let us know if you are still having problems.
