### ISSUE TITLE
Prevent column changes when using column header attributes.

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4978]
### Is your feature request related to a problem? Please describe

Prevent column changes when using column header attributes.

I'm tempted to see this as a bug, even though I'm tagging it as a feature request, because all the software works in opposite way, and Harlequin originally did too. I think this request has already been made, but I can't find it. I suggest modify the current behavior , the way how OT select the colums in the header attributes.

When you draw on a column/level, you may have to hide/edit the elements of other columns if necessary. But in OT this will also cause you to change columns, which is not the expected behavior. This causes you to lose focus on what you were doing and generates an extra click to return.

Column attributes such as, camera stand visibility, preview visibility, lock toggle, additional column settings, should not cause you to change columns. And let the top and bottom of the column do it.

![Use header columns features](https://github.com/opentoonz/opentoonz/assets/29790512/c1db4a69-d7df-4b2a-9315-b3f64931d394)

### Describe the solution you'd like

Having the expected behavior is what you find in any software. Tahoma2D has changed this behavior too

**Comment by RodneyBaker** [comment]
Closing this as the original reporter has ghosted themselves.
I might be mistaken but I believe this request has been implemented to some degree and as such it will be good to validate that and to transfer any remaining shortfalls into a new report.
