### ISSUE TITLE
Animate frame range

### ISSUE THREAD

**Issue by openanim** [opentoonz/opentoonz#4980]
### Is your feature request related to a problem? Please describe

Ot has powerful coloring modes, but whether it's frame range or onion skin, both tend to fail when there a a big variation in the animation and frame range require repeated coloring process on different ranges to control and color an animation with a lot of variation.

In the same vein as this request based on strokes matching #3562 and #3563, I suggest another idea with a new "track fill"  mode to solve, for example, a coloring process with large zone spaces in an animation with fill tool(but could work with others tools).

In an approach based on zone tracking, as can be done with OT's Hook and tracker tools, this could help to better predict the result without repeating small ranges step by step until the coloring is complete when variations are significant.

![frame range_guide_1](https://github.com/opentoonz/opentoonz/assets/29790512/0ece83bc-ed9c-4ff5-b310-93b5e047f136)

### Describe the solution you'd like

Maybe something like this: 

- ctrl + click defines the first range, the entry point (open range)

- you can then edit all markers in flight, as you can with the tracker and hook tools

- a 2nd ctl click closes the range, the exit point (to apply the range)

Or/and
If we can make this new fill mode use hooks as a reference to fill hooked/tracked areas. And if we can link a style to the hook in question so as to fill a zone with a color using a function like "fill on tracked zone".

![frame range_guide_2](https://github.com/opentoonz/opentoonz/assets/29790512/6ea511c0-c4ea-473d-9ec4-fe1b3b1436dd)

**Comment by JParks123** [comment]
here's an idea? why not try freehand fill mode on frame range with Paint Bucket tool just use your onion skin to see how wide to make your first and last selections.

**Comment by beeheemooth** [comment]
In the first video, the fill failed due to the fact that the Fill Tool in Frame Range mode has only linear interpolation, and the strokes were created using Ease In / Out. The overlap of these two interpolations does not match and the fill cursor does not match the enclosed area in some places. (#3280) Here it is better to apply the Fill Tool (Frame Range) in Freehand/Rectangular/Polyline mode, then you will be able to control the fill more accurately. Although in a specific case, you can simply use the Onion Skin mode (I mean the special mode in the Fill Tool settings). If the indexing of enclosed areas has not been broken, then you can fill all three areas with the appropriate color styles with one click.

**Comment by openanim** [comment]
@JParks123 

Yes, although the example I've given isn't very representative of the problem I wanted to solve, so I've tried to simplify it. The problem is that I have to predict positions when the animation varies greatly in frame range and the marker doesn't follow my animation.

@beeheemooth

I'd forgotten about this but #3280 describes exactly my problem, if shift click worked at the chosen location it would be perfect for following the animation regardless of the offset and would be a great improvement. The fill tool could also benefit from other types of interpolation like brush and eraser although I still don't understand why have linear interpolation instead of free positioning by clicking on the right place as this will mean using the same interpolation to have a  chance to match

**Comment by beeheemooth** [comment]
@openanim Issue #3280 is marked as a "bug", but you have a "feature request". I would really like the Fill Tool and Eraser Tool (in Toonz Raster) to also have all interpolation (EaseIn/Out) methods as it's really important for a complete workflow.
