### ISSUE TITLE
Frequent and unpredictable freeze on windows 11.

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#4984]
### Description

This is hard to debug or retrace my steps, but every 5 or maybe 10 minutes on windows clicking on a brush be it a raster brush or a texture brush causes the brush not to switch, but to instead freeze and be unresponsible. The screen turns white and I'm forced to terminate the process manually. I don't know why or how it does this, but on my linux machine this is yet to happen.

### Steps to Reproduce

I really cannot figure out a way to re-create the freezing.

### Expected Behavior

Not freeze up.

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
The only thing that comes immediately to mind is to double check the settings of WIndows Defender (and Windows 11 itself) to make sure it isn't being overly protective and preventing files from being saved/updated.

If you have Autosave turned on in Preferences try turning it off to see if that relates to the freeze.

**Comment by RodneyBaker** [comment]
Closing as the originator of the report has ghosted their github account, signaling the report is likely resolved and abandoned.
