### ISSUE TITLE
Audio crash

### ISSUE THREAD

**Issue by 5CP123** [opentoonz/opentoonz#4985]
### Description

For some reason when i add a audio in opentoonz (yes its a WAV file) it crashes and send me to this page! does somebody knows what is this bug?

### Steps to Reproduce

1. i open my file on downloads.
2. i add it to the animation program
3. put the option "keep existing file"
4. then appears a crash message!!

### Expected Behavior

It was supposed to play and show the audio.

### Screenshots, Video & Crash Logs

![2023-07-01 (1)](https://github.com/opentoonz/opentoonz/assets/138270872/82f1ed65-795d-4909-8cb9-916c1b75c904)
![2023-07-01 (2)](https://github.com/opentoonz/opentoonz/assets/138270872/234fe3b1-c18d-4d91-997c-d31cebacac44)
![2023-07-01 (3)](https://github.com/opentoonz/opentoonz/assets/138270872/e86dfe1b-80cc-47fc-8f8d-97ed5bbc523d)

### OpenToonz Version

1.7

### OpenToonz Version Information

2022 or 2023 around may i guess

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as an incomplete report without enough actionable information to troubleshoot.
In addition to reviewing other similar reports already closed I'll recommend joining one of the Opentoonz discords where others will be able to assist in troubleshooting the issue.

Opentoonz discord invite: https://discord.gg/UQxvYBKW5U
