### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Jaywallden** [opentoonz/opentoonz#4986]
### Description

it won't let me use the app without saying its crashed and telling me to write a report issue but won't tell me about what

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hi @Jaywallden 
Sorry to hear you are having problems running Opentoonz.
I will recommend joining one of the Opentoonz discords (chat) where others will be happy to help troubleshoot and get you up and running.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
