### ISSUE TITLE
Opentoonz Crash 

### ISSUE THREAD

**Issue by JuanJ1as** [opentoonz/opentoonz#4995]
### Description

When I open the app. I get greeted with a crash report for no reason. Please help

Sincerely,

Juan.

P.S, It still opens afterwards when you click on the X's two times but I am afraid it will sabatoge my projects in the middle of them.

### Screenshots, Video & Crash Logs

![1223](https://github.com/opentoonz/opentoonz/assets/138722069/0b770d23-f9d1-43de-8068-ecde35b8af51)

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-07-05 13:10:48
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

Crash File: C:\Users\Juan Silva\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230705-131048.log
Mini Dump File: C:\Users\Juan Silva\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230705-131048.dmp

==== Modules ====
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\Program Files\AVG\Antivirus\aswhook.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\combase.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\ADVAPI32.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\glut64.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SHLWAPI.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5SerialPort.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\image.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\tnztools.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\tnzstdfx.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\tfarm.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Widgets.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Gui.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Core.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\toonzqt.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\sound.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Script.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\toonzlib.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\tnzext.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\opencv_world451.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\tnzbase.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5OpenGL.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\tnzcore.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Multimedia.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\VCRUNTIME140.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\MSVCP140.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\libmypaint-1-4-0.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\libintl-8.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\styles\qwindowsvistastyle.dll
F:\Wants\Work\Opentoonz (Main)\OpenToonz\Opentoonz (Main)\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_5b6e4554b945d508\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff9578c8b9c] <ntdll.dll>
  2> RtlRaiseException [0x7ff9578a1316] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff9578f0f8e] <ntdll.dll>
  4> DriverProc [0x7f8411c9] <lvcod64.dll>
  5> ICSendMessage [0x7ff948fa2b9c] <MSVFW32.dll>
  6> ICOpen [0x7ff948fa2d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff91df06212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff91df04478] <image.dll>
  9> initImageIo [0x7ff91dea7ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff777580dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff777582d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7779aeab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7779ae092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff9564d7614] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff9578a26f1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by Ashley-Butcher** [comment]
Same stack trace for me. Windows 10, Wacom tablet (doesn't matter if connected or not). NVidia RTX 3090 GPU. OpenToonz 1.7.1 x64 built May 10 2023 11:07:51.

This was the first time I have installed OpenToonz, so this is a totally fresh install. After closing the crash dialogue it eventually opens.

**Comment by Ashley-Butcher** [comment]
After digging through the issues here on GitHub, I found #4971 in which @RodneyBaker mentioned the an old Logitech webcam driver causing an issue.

The specific file is `C:\Windows\System32\lvcod64.dll` and sure enough I had it there in the folder. I have a Logitech camera, but this file is more than 10 years old, so likely stale. I renamed it from `lvcod64.dll` to `lvcod64.dll.OLD` and the camera still works, and OpenToonz opens just fine now.

@JuanJ1as maybe this is also a work-around for you.

Thanks to @RodneyBaker 😊

**Comment by JuanJ1as** [comment]
Thank you. It was fixed. :)
