### ISSUE TITLE
Column Crash

### ISSUE THREAD

**Issue by Zukuio** [opentoonz/opentoonz#4996]
### Description

I made a new project in hopes of getting some practice in, I tried to make a new column but I couldn't find the usual keys along the timeline like they were on my first project, so I went into edit and into insert columns. That's when OpenToonz crashed. Beforehand I even quit and reopened the program but the keys I needed wouldn't appear.

### Steps to Reproduce

1. can't find button to make new column 
2. Go into edit 
3. insert columns
4. crash

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-07-06 13:43:33
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 22.5.0
CPU Threads: 8

GPU Vendor: Apple
GPU Model: Apple M1
GPU Version: 2.1 Metal - 83.1

Crash File: /Users/taemiaarcher1/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20230706-134333.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: sandbox
Scene Name: tester 2
Project Path: /Applications/OpenToonz/OpenToonz_stuff/sandbox/sandbox_otprj.xml
Scene Path: /Applications/OpenToonz/OpenToonz_stuff/sandbox/scenes/tester 2.tnz

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   QtCore                              0x0000000117818bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
  3> 5   QtWidgets                           0x0000000114d421a6 _ZN7QAction8activateENS_11ActionEventE + 310
  4> 6   QtCore                              0x0000000117810b5d _ZN7QObject5eventEP6QEvent + 957
  5> 7   QtWidgets                           0x0000000114d4b52d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
  6> 8   QtWidgets                           0x0000000114d4c8f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
  7> 9   QtCore                              0x00000001177e67f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
  8> 10  QtCore                              0x00000001177e7923 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData + 691
  9> 11  libqcocoa.dylib                     0x000000012532d352 qt_plugin_instance + 197794
 10> 12  libqcocoa.dylib                     0x000000012532da58 qt_plugin_instance + 199592
 11> 13  CoreFoundation                      0x00007ff80e79e906 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 12> 14  CoreFoundation                      0x00007ff80e79e8a9 __CFRunLoopDoSource0 + 157
 13> 15  CoreFoundation                      0x00007ff80e79e686 __CFRunLoopDoSources0 + 217
 14> 16  CoreFoundation                      0x00007ff80e79d30a __CFRunLoopRun + 916
 15> 17  CoreFoundation                      0x00007ff80e79c91c CFRunLoopRunSpecific + 560
 16> 18  HIToolbox                           0x00007ff8186e0dad RunCurrentEventLoopInMode + 292
 17> 19  HIToolbox                           0x00007ff8186e09f4 ReceiveNextEventCommon + 199
 18> 20  HIToolbox                           0x00007ff8186e0918 _BlockUntilNextEventMatchingListInModeWithFilter + 64
 19> 21  AppKit                              0x00007ff8117905d0 _DPSNextEvent + 858
 20>  21> sh: addr2line: command not found
 22> 24  libqcocoa.dylib                     0x000000012532c86c qt_plugin_instance + 195004
 23> 25  QtCore                              0x00000001177e297f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 24> 26  QtCore                              0x00000001177e6d82 _ZN16QCoreApplication4execEv + 130
 25> 27  OpenToonz                           0x0000000104c2fe07 main + 16487
 26> 28  dyld                                0x00000002059e041f start + 1903
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

May 10 2023

### Operating System

macOS

### GPU

Other

### Graphics Tablet

XP-Pen

**Comment by RattusaurusRex** [comment]
If you're looking for the toolbar with the buttons to create a New Level on the Timeline, right-click on a layer header -> Toggle Xsheet Toolbar.  

I don't get a crash when using Edit -> Insert Columns on Windows 10.

**Comment by Zukuio** [comment]
> If you're looking for the toolbar with the buttons to create a New Level on the Timeline, right-click on a layer header -> Toggle Xsheet Toolbar.
> 
> I don't get a crash when using Edit -> Insert Columns on Windows 10.

This is what im looking for: (first image is mine, second is what im missing.)
![Screenshot 2023-07-16 at 10 29 23 am](https://github.com/opentoonz/opentoonz/assets/138746432/99605d1b-a4ce-470c-939c-01a177e6e518)
![Screenshot 2023-07-16 at 10 30 46 am](https://github.com/opentoonz/opentoonz/assets/138746432/c81b3c7d-438b-45e4-bb02-9780c4bfb407)

**Comment by Zukuio** [comment]
> If you're looking for the toolbar with the buttons to create a New Level on the Timeline, right-click on a layer header -> Toggle Xsheet Toolbar.
> 
> I don't get a crash when using Edit -> Insert Columns on Windows 10.

Found it! thank you!
