### ISSUE TITLE
when drawing on a frame/cell step , the frame/cell step is replaced by a new frame

### ISSUE THREAD

**Issue by whotookalexoop** [opentoonz/opentoonz#4999]
### Description

in opentoonz 1.7.1, on windows 10 , 7 columns/levels (one of them being the camera), the video should be self-explaining enough, don't worry about the censored parts. 

### Steps to Reproduce

1. draw on frame
2. make mesh of the frame using plastic tool
3.select part of before-mentioned frame
4.make another level with frame 
5.use animate tool on the level mentioned in the previous step
6.draw on the step of the frame/cell 
7.the frame/cell step dissapears

### Expected Behavior

and the frame/cell step is replaced with another standalone frame

### Screenshots, Video & Crash Logs

https://github.com/opentoonz/opentoonz/assets/138816554/f57c2ded-170c-4936-8f68-85105d86fa98

### OpenToonz Version

1.7

### OpenToonz Version Information

2023-07-05 11:17:35 UTC nightly

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

None

**Comment by shun-iwasawa** [comment]
Check if the option  `Preferences > Drawing > Enable Autocreation > Enable Creation in Hold Cells` is ON.
The option will insert a blank frame when you draw on a hold cell.

**Comment by RodneyBaker** [comment]
Thanks for posting this @whotookalexoop 
I needed the reminder that we could turn that option off and draw anywhere in any of that same frame's exposure to effect the original frame/drawing.  We can easily do that with the eraser but cannot with brush if the option @shun-iwasawa mentions isn't turned off.

So good to have this as an option.  :)
