### ISSUE TITLE
Problem copying values from the Style Editor context menu

### ISSUE THREAD

**Issue by beeheemooth** [opentoonz/opentoonz#5002]
### Description

The HEX code in the input window for a color cannot be copied from the context menu, because when the context menu is called, the focus of the selection is lost.

Calling the context menu with the system button "Menu" also leads to loss of focus.

### Steps to Reproduce

1. Highlight the code in the input window
2. Call the context menu with a right click
3. Code highlighting will disappear, copying is impossible

### Expected Behavior

Copying from the context menu in my case is the only way to copy, since I use a macro for Ctrl + C, which at the same time introduces extraneous characters into the field.

### Screenshots, Video & Crash Logs

![ezgif-1-7abb783bc5](https://github.com/opentoonz/opentoonz/assets/25724133/f9d32b55-6c9c-43cd-8da3-a7b3d1df78ad)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
I can replicate the problem.
As you've stated a workaround is to use Control + C to copy the values.
It is unfortunate that you can't use that standard shortcut.
Perhaps you can share your Autohotkey script and we can find a way to allow both your customized use and the standard copy/paste.

The bug itself appears to be (as you suggest) a loss of focus (or failure to release focus).
The problem exists in Tahoma2D as well.

**Comment by RodneyBaker** [comment]
Closed by #5185
