### ISSUE TITLE
Opentoonz Crash Reason: EXCEPTION_INT_DIVIDE_BY_ZERO

### ISSUE THREAD

**Issue by ElEmiiiiiii** [opentoonz/opentoonz#5003]
### Description

This, oh well:

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-07-08 17:15:37
Crash Reason: EXCEPTION_INT_DIVIDE_BY_ZERO

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 16

Crash File: C:\Users\MSI\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230708-171537.log
Mini Dump File: C:\Users\MSI\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230708-171537.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: haha
Scene Name: Extroverted sensing
Project Path: C:\OpenToonz stuff\projects\haha\haha_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\haha\scenes\Extroverted sensing.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\ole32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_357acc06f2c40efb\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_357acc06f2c40efb\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_357acc06f2c40efb\igdgmm64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_357acc06f2c40efb\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffaba268b9c] <ntdll.dll>
  2> RtlRaiseException [0x7ffaba241316] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffaba290f8e] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff618637fba] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61863ac28] <OpenToonz.exe>
  6> QWidget::event [0x7ffa07af84d1] <Qt5Widgets.dll>
  7> QApplicationPrivate::notify_helper [0x7ffa07ad55c0] <Qt5Widgets.dll>
  8> QApplication::notify [0x7ffa07ad4643] <Qt5Widgets.dll>
  9> QCoreApplication::notifyInternal2 [0x7ffa0704318a] <Qt5Core.dll>
 10> QWidgetPrivate::drawWidget [0x7ffa07af7aeb] <Qt5Widgets.dll>
 11> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 12> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 13> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 14> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 15> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 16> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 17> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 18> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 19> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 20> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 21> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 22> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 23> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 24> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 25> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 26> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 27> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afd985] <Qt5Widgets.dll>
 28> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 29> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 30> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 31> QWidgetPrivate::paintSiblingsRecursive [0x7ffa07afda57] <Qt5Widgets.dll>
 32> QWidgetPrivate::drawWidget [0x7ffa07af7c44] <Qt5Widgets.dll>
 33> QWidgetPrivate::moveRect [0x7ffa07ae0406] <Qt5Widgets.dll>
 34> QWidget::event [0x7ffa07af890f] <Qt5Widgets.dll>
 35> QApplicationPrivate::notify_helper [0x7ffa07ad55c0] <Qt5Widgets.dll>
 36> QApplication::notify [0x7ffa07ad4643] <Qt5Widgets.dll>
 37> QCoreApplication::notifyInternal2 [0x7ffa0704318a] <Qt5Core.dll>
 38> QCoreApplicationPrivate::sendPostedEvents [0x7ffa07044f25] <Qt5Core.dll>
 39> qt_plugin_query_metadata [0x7ffa05ce28ff] <qwindows.dll>
 40> QEventDispatcherWin32::processEvents [0x7ffa0708bcfa] <Qt5Core.dll>
 41> qt_plugin_query_metadata [0x7ffa05ce28d9] <qwindows.dll>
 42> StyleEditor::onStyleSwitched [0x7ffa06beb80b] <toonzqt.dll>
 43> QObject::qt_static_metacall [0x7ffa070620d7] <Qt5Core.dll>
 44> TPaletteHandle::setPalette [0x7ffa069e663b] <toonzlib.dll>
 45> PaletteController::editLevelPalette [0x7ffa06a06630] <toonzlib.dll>
 46> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff6185afb70] <OpenToonz.exe>
 47> QObject::qt_static_metacall [0x7ffa070620d7] <Qt5Core.dll>
 48> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61871e16b] <OpenToonz.exe>
 49> QObject::qt_static_metacall [0x7ffa070620d7] <Qt5Core.dll>
 50> QAbstractButton::clicked [0x7ffa07b9fa97] <Qt5Widgets.dll>
 51> QAbstractButton::click [0x7ffa07b9f9b8] <Qt5Widgets.dll>
 52> QAbstractButton::mouseReleaseEvent [0x7ffa07ba06bd] <Qt5Widgets.dll>
 53> QWidget::event [0x7ffa07af8092] <Qt5Widgets.dll>
 54> QApplicationPrivate::notify_helper [0x7ffa07ad55c0] <Qt5Widgets.dll>
 55> QApplication::notify [0x7ffa07ad34e0] <Qt5Widgets.dll>
 56> QCoreApplication::notifyInternal2 [0x7ffa0704318a] <Qt5Core.dll>
 57> QApplicationPrivate::sendMouseEvent [0x7ffa07ad67c5] <Qt5Widgets.dll>
 58> QDesktopWidget::workAreaResized [0x7ffa07b209d2] <Qt5Widgets.dll>
 59> QDesktopWidget::workAreaResized [0x7ffa07b1e96e] <Qt5Widgets.dll>
 60> QApplicationPrivate::notify_helper [0x7ffa07ad55c0] <Qt5Widgets.dll>
 61> QApplication::notify [0x7ffa07ad4643] <Qt5Widgets.dll>
 62> QCoreApplication::notifyInternal2 [0x7ffa0704318a] <Qt5Core.dll>
 63> QGuiApplicationPrivate::processMouseEvent [0x7ffa074847c3] <Qt5Gui.dll>
 64> QWindowSystemInterface::sendWindowSystemEvents [0x7ffa0746f030] <Qt5Gui.dll>
 65> QEventDispatcherWin32::processEvents [0x7ffa0708bcfa] <Qt5Core.dll>
 66> qt_plugin_query_metadata [0x7ffa05ce28d9] <qwindows.dll>
 67> QEventLoop::exec [0x7ffa0703f64c] <Qt5Core.dll>
 68> QCoreApplication::exec [0x7ffa07042164] <Qt5Core.dll>
 69> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff618565219] <OpenToonz.exe>
 70> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61898eab7] <OpenToonz.exe>
 71> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61898e092] <OpenToonz.exe>
 72> BaseThreadInitThunk [0x7ffab8687614] <KERNEL32.DLL>
 73> RtlUserThreadStart [0x7ffaba2426f1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
What was you doing when the crash happened?

**Comment by RodneyBaker** [comment]
Closing as an incomplete report without enough actionable information to troubleshoot here.
In addition to reviewing other similar reports related to crashing (those already closed), I'll recommend joining one of the Opentoonz discords where others will be able to assist in troubleshooting the issue.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
