### ISSUE TITLE
HELP MY FRAME SHOW UP BUT MY DRAWINGS DON'T!!?

### ISSUE THREAD

**Issue by LinxyHonest** [opentoonz/opentoonz#5005]
### Description

Excuse me, but I need help! I just finished up drawing some frames and wanted to save the animation, as I saved, the program crashed! And when I reopened it the frames were there but now there all red! I can see there there on the bar, but the drawings don't show up!!? WHAT DO I DOO??????

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The red is an indication that your frame exposures are missing.
If you right click on one of those cells and choose Level Settings you'll see where Opentoonz thinks those should be.

In that directory (likely C:\Opentoonz stuff\sandbox\drawings) you may have some files with .bak extensions.
Those are backups of the drawings.  And in many cases they can be restored to near current condition by removing the .bak extension leaving a file like 'image.tlv" etc.

As you don't supply much information more information and it can be hard to do the back and forth of troubleshooting via github I'll recommend joining one of the Opentoonz discords where others can assist you in determining if the files can be restored.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U

The red is often an indication that files have been moved from their original location (i.e. thy present a broken link to where files once were) but... in your case you state that you were saving and that led to loss of the files.  Hopefully this didn't corrupt the files.  If it did then restoring the files from the backups could at least save you a lot of work recreating the files.

**Comment by LinxyHonest** [comment]
Thank you very much for the help! I have now tried, but the images are
perminantly lost. After the crash as I was saving the images coudn't be
saved propaly yet I guess, and no backups were made... I checked them and
they were empty! I will yet have to start from the begining, but luckely it
was only the sketches of the rough animation I was doing.

**Comment by RodneyBaker** [comment]
Sorry to hear of the loss of files @LinxyHonest.  That is always a frustrating experience.
We are always looking for ways to prevent such losses and... in cases where that occurs... to recover files.

WIll close this report but please feel free to add any information you feel is appropriate or open a new report as needed.
