### ISSUE TITLE
Opentoonz crash upon opening specific file

### ISSUE THREAD

**Issue by torntobits** [opentoonz/opentoonz#5007]
For some reason I cannot find the issue template on the app, so I will try my best to explain.
I've noticed this issue be brought up with lvcod64.dll, but this file does not appear on my crash report. 
All I need to do to receive this crash message is to open 1 particular project.
Most of my projects share 1 .png layer that I modify based on the project I am actively working on. I'm not sure if it has anything to do with this.

The project opens normally if I open a different project, then load in the "affected" project

Crash log for reference:

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-07-09 15:24:53
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 512.78

Crash File: C:\Users\alice\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230709-152453.log
Mini Dump File: C:\Users\alice\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230709-152453.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Commissions
Scene Name: FiveEyedCaprine_New
Project Path: C:\OpenToonz stuff\projects\Commissions\Commissions_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Commissions\scenes\FiveEyedCaprine_New.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\WINTRUST.DLL
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_4c9ded46d0fbe1f8\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\SYSTEM32\nvapi64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_4c9ded46d0fbe1f8\nvldumdx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_4c9ded46d0fbe1f8\nvwgf2umx.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd1aea8b9c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd1ae81316] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd1aed0f8e] <ntdll.dll>
  4> StyleEditorGUI::ColorSlider::setColor [0x7ffce66ae237] <toonzqt.dll>
  5> StyleEditor::setStyle [0x7ffce66af1aa] <toonzqt.dll>
  6> StyleEditor::onStyleSwitched [0x7ffce66ab8fe] <toonzqt.dll>
  7> QObject::qt_static_metacall [0x7ffcce8220d7] <Qt5Core.dll>
  8> TPaletteHandle::setPalette [0x7ffcdf46663b] <toonzlib.dll>
  9> PaletteController::editLevelPalette [0x7ffcdf486630] <toonzlib.dll>
 10> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff72494fb70] <OpenToonz.exe>
 11> QObject::qt_static_metacall [0x7ffcce8220d7] <Qt5Core.dll>
 12> TSceneHandle::setScene [0x7ffcdf466916] <toonzlib.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff724b12c28] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff724abe317] <OpenToonz.exe>
 15> QObject::qt_static_metacall [0x7ffcce8220d7] <Qt5Core.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff724ca78c0] <OpenToonz.exe>
 17> QObject::qt_static_metacall [0x7ffcce8220d7] <Qt5Core.dll>
 18> QListWidget::qt_static_metacall [0x7ffcd209aa1b] <Qt5Widgets.dll>
 19> QObject::qt_static_metacall [0x7ffcce8220d7] <Qt5Core.dll>
 20> QAbstractItemView::mouseReleaseEvent [0x7ffcd2062a0f] <Qt5Widgets.dll>
 21> QListView::mouseReleaseEvent [0x7ffcd209346f] <Qt5Widgets.dll>
 22> QWidget::event [0x7ffcd1e68092] <Qt5Widgets.dll>
 23> QFrame::event [0x7ffcd1f09d10] <Qt5Widgets.dll>
 24> QAbstractItemView::viewportEvent [0x7ffcd2068ae8] <Qt5Widgets.dll>
 25> QCoreApplicationPrivate::sendThroughObjectEventFilters [0x7ffcce80523a] <Qt5Core.dll>
 26> QApplicationPrivate::notify_helper [0x7ffcd1e455ac] <Qt5Widgets.dll>
 27> QApplication::notify [0x7ffcd1e434e0] <Qt5Widgets.dll>
 28> QCoreApplication::notifyInternal2 [0x7ffcce80318a] <Qt5Core.dll>
 29> QApplicationPrivate::sendMouseEvent [0x7ffcd1e467c5] <Qt5Widgets.dll>
 30> QDesktopWidget::workAreaResized [0x7ffcd1e909d2] <Qt5Widgets.dll>
 31> QDesktopWidget::workAreaResized [0x7ffcd1e8e96e] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ffcd1e455c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ffcd1e44643] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ffcce80318a] <Qt5Core.dll>
 35> QGuiApplicationPrivate::processMouseEvent [0x7ffccc4647c3] <Qt5Gui.dll>
 36> QWindowSystemInterface::sendWindowSystemEvents [0x7ffccc44f030] <Qt5Gui.dll>
 37> QEventDispatcherWin32::processEvents [0x7ffcce84bcfa] <Qt5Core.dll>
 38> qt_plugin_query_metadata [0x7ffcd72c28d9] <qwindows.dll>
 39> QEventLoop::exec [0x7ffcce7ff64c] <Qt5Core.dll>
 40> QCoreApplication::exec [0x7ffcce802164] <Qt5Core.dll>
 41> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff724905219] <OpenToonz.exe>
 42> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff724d2eab7] <OpenToonz.exe>
 43> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff724d2e092] <OpenToonz.exe>
 44> BaseThreadInitThunk [0x7ffd1a207614] <KERNEL32.DLL>
 45> RtlUserThreadStart [0x7ffd1ae826f1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
@torntobits Thanks for the report.
As you mention something most reports do not... crashing only upon opening of a specific file... that can help tremendously in diagnosing the problem.

Can you share the project files?  If not can you share part of the project (such as the scene file... or another project that also replicates the problem?

In current releases (since v1.7) the export Scene dialog is easier to get to than before.
It can now be accessed via the menu with File > Export Scene 
Look to the bottom of the dialogue where a location and name for the project can be entered.
Once exported that directory can be zipped up and shared.

Barring that you might be able to removed specific parts of the project and have the project open.
This assuming there is no major corruption of the scene file.
If corrupted hopefully it can be restored from one of the .bak backup files Opentoonz creates in the stuff directory.

And... for additional feedback in real-er time you might consider joining one of the Opentoonz discords.

**Comment by Camlegofan** [comment]
I'm having the same issue (mostly). It's not too consistent, sometimes the file will actually open properly, but then after closing it and reopening it it crashes again. Once that happens some of my other files will have the same problem (even though they didn't before), but some still work fine

**Comment by RodneyBaker** [comment]
@torntobits If you are still having this issue with a specific file it will be good to know more about that specific file.
Can you share a copy of that file and/or provide additional information about it?

**Comment by RodneyBaker** [comment]
The name of the level/image file might be problematic but otherwise we are lacking important information that will help resolve this issue.

@torntobits I will recommend joining one of the Opentoonz discords as that is an excellent place to resolve such issues.

@Camlegofan Thank you for you additional information.
If you are still experiencing your problem you may want to open a new report.
