### ISSUE TITLE
[English Typos] File Access Warning and Shortcut

### ISSUE THREAD

**Issue by AyameLee** [opentoonz/opentoonz#501]
If write access is denied to the user and you try to save a level you will get a warning, it has a typo.

![t2](https://cloud.githubusercontent.com/assets/18118611/16290865/c9177bd0-38f8-11e6-9085-59d814bbc644.PNG)

"**can't fopen.**"

How about...

"**Can't open file. Access may be denied or someone else may be saving the same file. Please wait and try again.**"

Users working in environments with rigorous working group policies may be left scratching their head if the project manager has revoked write access for any reason and they get presented with this prompt. The small specification about access may be denied could give some guidance to their issue.

Also our old friend "sensibility" is back under **Shortcut Settings > Tool Modifiers > Pressure _sensibility_**.

Change to:

**Pressure Sensitivity**.

**Comment by turtletooth** [comment]
Done.

**Comment by turtletooth** [comment]
Fixed on #474

**Comment by turtletooth** [comment]
@AyameLee What do you think of the dialog boxes in the newest update to #474 ?  Are they clear?  Anything seem strange?

**Comment by konero** [comment]
This should probably have its own PR since it is a bug report and the bundle PR #474 is a new feature.

_* I just ran into the file access typo._

**Comment by turtletooth** [comment]
Moved fixes to #531
