### ISSUE TITLE
Suddenly crash

### ISSUE THREAD

**Issue by hozhengzhe** [opentoonz/opentoonz#5013]
### Description

Since i had download opentoonz at this laptop, crash keep happening when i making animations, i cant found any solution for this.

### Steps to Reproduce

1. just normal drawing animation, nothing special
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Jun 16 2023)

Report Date: 2023-07-12 19:23:29
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 516.59

Crash File: C:\Users\zhezh\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230712-192329.log
Mini Dump File: C:\Users\zhezh\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230712-192329.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: School Promotional 
Scene Name: genga
Project Path: C:\OpenToonz stuff\projects\School Promotional \School Promotional _otprj.xml
Scene Path: C:\OpenToonz stuff\projects\School Promotional \scenes\genga.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\WINTRUST.DLL
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmig.inf_amd64_450cb17918816837\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\SYSTEM32\nvapi64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmig.inf_amd64_450cb17918816837\nvldumdx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmig.inf_amd64_450cb17918816837\nvwgf2umx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0388886.inf_amd64_28a1b79ad1509517\B385477\aticfx64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0388886.inf_amd64_28a1b79ad1509517\B385477\atiuxp64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0388886.inf_amd64_28a1b79ad1509517\B385477\atidxx64.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\amdihk64.dll
C:\Windows\System32\threadpoolwinrt.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.1635_none_270f70857386168e\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
C:\WINDOWS\SYSTEM32\msvcp110_win.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\SYSTEM32\TextShaping.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffa47927a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffa478ce232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffa47952cee] <ntdll.dll>
  4> TSmartPointerT<TData>::TSmartPointerT<TData> [0x7ff9f5912e79] <tnzcore.dll>
  5> TImageException::getRawMessage [0x7ff9f5914445] <tnzcore.dll>
  6> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7d71f547b] <OpenToonz.exe>
  7> QObject::qt_static_metacall [0x7ff9f4c020d7] <Qt5Core.dll>
  8> TTool::notifyImageChanged [0x7ff9f9ff8f4b] <tnztools.dll>
  9> StrokeSelection::toggle [0x7ff9fa140346] <tnztools.dll>
 10> StrokeSelection::toggle [0x7ff9fa143430] <tnztools.dll>
 11> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7d71eed37] <OpenToonz.exe>
 12> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7d71ef1b9] <OpenToonz.exe>
 13> QWidget::event [0x7ff9f7d980f7] <Qt5Widgets.dll>
 14> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7d71ec1db] <OpenToonz.exe>
 15> QApplicationPrivate::notify_helper [0x7ff9f7d755c0] <Qt5Widgets.dll>
 16> QApplication::notify [0x7ff9f7d73e73] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x7ff9f4be318a] <Qt5Core.dll>
 18> QDesktopWidget::workAreaResized [0x7ff9f7dc1284] <Qt5Widgets.dll>
 19> QDesktopWidget::workAreaResized [0x7ff9f7dbeb59] <Qt5Widgets.dll>
 20> QApplicationPrivate::notify_helper [0x7ff9f7d755c0] <Qt5Widgets.dll>
 21> QApplication::notify [0x7ff9f7d74643] <Qt5Widgets.dll>
 22> QCoreApplication::notifyInternal2 [0x7ff9f4be318a] <Qt5Core.dll>
 23> QGuiApplicationPrivate::processTabletEvent [0x7ff9f5ca56b7] <Qt5Gui.dll>
 24> QWindowSystemInterface::sendWindowSystemEvents [0x7ff9f5c8f030] <Qt5Gui.dll>
 25> QEventDispatcherWin32::processEvents [0x7ff9f4c2bcfa] <Qt5Core.dll>
 26> qt_plugin_query_metadata [0x7ff9f96628d9] <qwindows.dll>
 27> QEventLoop::exec [0x7ff9f4bdf64c] <Qt5Core.dll>
 28> QCoreApplication::exec [0x7ff9f4be2164] <Qt5Core.dll>
 29> TSmartPointerConstT<TXshSoundLevel>::~TSmartPointerConstT<TXshSoundLevel> [0x7ff7d7106259] <OpenToonz.exe>
 30> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7d7535377] <OpenToonz.exe>
 31> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7d7534952] <OpenToonz.exe>
 32> BaseThreadInitThunk [0x7ffa46a426ad] <KERNEL32.DLL>
 33> RtlUserThreadStart [0x7ffa4790a9f8] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

Build Jun 16 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Closing as an incomplete report without enough actionable information to troubleshoot here.
In addition to reviewing other similar reports related to crashing (those already closed), I'll recommend joining one of the Opentoonz discords where others will be able to assist in troubleshooting the issue.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
