### ISSUE TITLE
tools not working properly like control tool and eraser tool and lagging issue also

### ISSUE THREAD

**Issue by mrakhilsahu** [opentoonz/opentoonz#5014]
### Description

tools not working properly like control tool and eraser tool and lagging issue also

### Steps to Reproduce

1. 
2. 

### Expected Behavior

to working properly my eraser and control tool 

### OpenToonz Version

1.7

### OpenToonz Version Information

may 10 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by RodneyBaker** [comment]
Closing as an incomplete report that contains no actionable information.
@mrakhilsahu Back to you.
