### ISSUE TITLE
error while loading shared libraries: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by overtube** [opentoonz/opentoonz#5015]
### Description

Falling at **runtime** step

### Steps to Reproduce

1. install that software with `pacman` (also try `nightly` version , that cannot help too) 
2. launch from `*.desktop`
3. get that error (also from `terminal` too)
**~$ opentoonz**
`/usr/bin/../bin/OpenToonz:` error while loading shared `libraries: libopencv_videoio.so.408:` cannot open shared `object file:` No such file or directory

### OpenToonz Version

1.7

### OpenToonz Version Information

~$ pacman -Q opentoonz opentoonz 1.7.1-2

### Operating System

Linux

### GPU

AMD

### Graphics Tablet

None

**Comment by andeon** [comment]
Apparently some path is missing, try running

`sudo ldconfig -v`

Perhaps just running the previous command it works, otherwise I think you'll need to set LD_LIBRARY_PATH to link the shared library.
