### ISSUE TITLE
opentoonz crashed unexpectedly 

### ISSUE THREAD

**Issue by mrakhilsahu** [opentoonz/opentoonz#5017]
### Description

when i start opentoonz after some time it show crashed unexpectedly 

### Steps to Reproduce

1. just normal drawing animation 
2. 

### Expected Behavior

not crashed in future and run smoothly

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-07-15 15:49:57
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 12

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Graphics
GPU Version: 4.6.0 Compatibility Profile Context 22.20.28.220830

Crash File: C:\Users\Lenovo\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230715-154957.log
Mini Dump File: C:\Users\Lenovo\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230715-154957.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: f
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\f.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\x64\AudioDevProps2.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0383722.inf_amd64_5cbaacf42cbd3812\B383240\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0383722.inf_amd64_5cbaacf42cbd3812\B383240\atio6axx.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\SYSTEM32\BCrypt.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\x64\ProductInfo.dll
C:\ProgramData\A-Volute\A-Volute.Nahimic\Modules\Scheduled\x64\ASM.Plugin.AudioDevProps2.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\sxs.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fff7dca7a9a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fff7dc4e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff7dcd2dee] <ntdll.dll>
  4> TStroke::getMaxThickness [0x7fff22b6e4e3] <tnzcore.dll>
  5> TRegion::addEdge [0x7fff22b628c3] <tnzcore.dll>
  6> computeRegionFeature [0x7fff22b5b5a2] <tnzcore.dll>
  7> TVectorImage::moveStrokes [0x7fff22b88cb4] <tnzcore.dll>
  8> TVectorImage::notifyChangedStrokes [0x7fff22b88f82] <tnzcore.dll>
  9> ToolOptions::showEvent [0x7fff267606f0] <tnztools.dll>
 10> ToolOptions::showEvent [0x7fff2675e1aa] <tnztools.dll>
 11> PinchTool::getToolType [0x7fff2667d22f] <tnztools.dll>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff67876b4bd] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff67876c4eb] <OpenToonz.exe>
 14> QWidget::event [0x7fff240c80f7] <Qt5Widgets.dll>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff67876942b] <OpenToonz.exe>
 16> QApplicationPrivate::notify_helper [0x7fff240a55c0] <Qt5Widgets.dll>
 17> QApplication::notify [0x7fff240a3e73] <Qt5Widgets.dll>
 18> QCoreApplication::notifyInternal2 [0x7fff2361318a] <Qt5Core.dll>
 19> QDesktopWidget::workAreaResized [0x7fff240f1284] <Qt5Widgets.dll>
 20> QDesktopWidget::workAreaResized [0x7fff240eeb59] <Qt5Widgets.dll>
 21> QApplicationPrivate::notify_helper [0x7fff240a55c0] <Qt5Widgets.dll>
 22> QApplication::notify [0x7fff240a4643] <Qt5Widgets.dll>
 23> QCoreApplication::notifyInternal2 [0x7fff2361318a] <Qt5Core.dll>
 24> QGuiApplicationPrivate::processTabletEvent [0x7fff23a556b7] <Qt5Gui.dll>
 25> QWindowSystemInterface::sendWindowSystemEvents [0x7fff23a3f030] <Qt5Gui.dll>
 26> QEventDispatcherWin32::processEvents [0x7fff2365bcfa] <Qt5Core.dll>
 27> qt_plugin_query_metadata [0x7fff247728d9] <qwindows.dll>
 28> QEventLoop::exec [0x7fff2360f64c] <Qt5Core.dll>
 29> QCoreApplication::exec [0x7fff23612164] <Qt5Core.dll>
 30> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff678685219] <OpenToonz.exe>
 31> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff678aaeab7] <OpenToonz.exe>
 32> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff678aae092] <OpenToonz.exe>
 33> BaseThreadInitThunk [0x7fff7cc426ad] <KERNEL32.DLL>
 34> RtlUserThreadStart [0x7fff7dc8aa68] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

build mar 14 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by DarrenTAnims** [comment]
Without any specific repeatable steps, there's nothing that can be done with this report.
If you have a repeatable case of a problem, please share full details so it can be looked into.

**Comment by RodneyBaker** [comment]
Will close this report as not having enough actionable information to address the problem.
@mrakhilsahu If you have additional information describing the problem we'd be interested in reviewing that.
