### ISSUE TITLE
K-Lite Codec Pack related crash after updating to v1.7

### ISSUE THREAD

**Issue by Oreo-00** [opentoonz/opentoonz#5025]
### Description

OT was working perfectly on V1.6 But it Crashed while opening and after updating to V1.7

### Steps to Reproduce

1. 
2. 

### Expected Behavior

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-07-30 03:24:58
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

Crash File: C:\Users\muhamed\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230730-032458.log
Mini Dump File: C:\Users\muhamed\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230730-032458.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\SYSTEM32\ig75icd64.dll
C:\WINDOWS\SYSTEM32\igdusc64.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\ff_vfw.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll
C:\Program Files (x86)\K-Lite Codec Pack\Filters\ffdshow64\ffdshow.ax
C:\WINDOWS\SYSTEM32\DINPUT.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\inputhost.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffe89268b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ffe892412d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe89290ebe] <ntdll.dll>
  4> DriverProc [0x7ffe4be452e3] <ff_vfw.dll>
  5> ICSendMessage [0x7ffe5f9d2b9c] <MSVFW32.dll>
  6> TSmartPointerT<TXshColumn>::operator> [0x7ffe397d7498] <image.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffe397d4bb6] <image.dll>
  8> initImageIo [0x7ffe39777ace] <image.dll>
  9> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff749ee0dae] <OpenToonz.exe>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff749ee2d41] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff74a30eab7] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff74a30e092] <OpenToonz.exe>
 13> BaseThreadInitThunk [0x7ffe882b7614] <KERNEL32.DLL>
 14> RtlUserThreadStart [0x7ffe892426b1] <ntdll.dll>
==== End ====

### Screenshots, Video & Crash Logs

I have renamed the t32bitsrv.exe also I don't have any of Logitech
![SharedScreenshot](https://github.com/opentoonz/opentoonz/assets/140925896/0568ac00-c089-4885-ba4c-e9bbd6d16016)
![SharedScreenshot2](https://github.com/opentoonz/opentoonz/assets/140925896/0bc9fe23-1e92-477c-a400-d9038a1c39c4)
 drivers

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hi @Oreo-00 
I will suggest looking into the K-Lite codec pack that is installed on your system as that is a likely culprit for incompatibility.

Your crash report refers to that K-Lite Codec Pack.

Interestingly, you also have an error with the oft encountered logitec webcam driver which for many users requires them to remove (or to rename/move) that driver but... in your case a process is looking for that .dll file and NOT finding it.   In your case it appears to be Windows (and perhaps the specific codec loaded via the K-Lite Codec pack... very possibly one related to AVI video format that is being troublesome.  

You might first try to reinstall the codec pack and then hone in on the specific codecs that might be troublesome.

Note the location that WIndows expects the logitec webcam driver to be in:  

![image](https://github.com/opentoonz/opentoonz/assets/2576432/c15ea61c-7f2c-4aab-84ea-3cb5c58f01d9)


You might not have that webcam but some program/process is looking for that driver.

**Comment by Oreo-00** [comment]
Hello Rodney,
thank you for your response. I have noticed that my K-Lite version was 10.5.5 Standard installed in 2014.
Do you have any suggestions about which version to install and be compatible with OT?
Thanks in advance

**Comment by RodneyBaker** [comment]
No, Sorry.  When I personally experienced issues with K-Lite codecs I uninstalled them and didn't investigate any further.
Once uninstalled everything went back to working as expected and at the time that's what I needed.

Any information you discover will be appreciated.

I suppose given that the install is from 2014 I'll recommend installing the latest release of K-Lite codecs just to see if that remedies the problem so... that'd be my suggestion.

**Comment by Oreo-00** [comment]
@RodneyBaker 
after reinstalling the latest K-Lite mega package everything working perfectly.
Thank you so much for your help 
![SharedScreenshot](https://github.com/opentoonz/opentoonz/assets/140925896/74b59add-8962-491e-b06f-672b0966128f)
