### ISSUE TITLE
Tool option bar settings available in setting tab or like dockable responsive panel 

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#5035]
### Is your feature request related to a problem? Please describe

My request mainly concerns the settings of the native opentoonz brush tool, although it could be extended to the entire OT toolbar.

I think that in addition to offering the alternative of a more conventional layout, it will speed up a lot of workflows to have the tool options in a panel that can be collapsed to the side and used in full screen mode. 

Possible solutions:

**1 . The tool options bar becomes responsive and can also be arranged as a dockable panel**

 as is possible with the powerful new custom panels.

<img width="1280" alt="setting OT_3" src="https://github.com/opentoonz/opentoonz/assets/29790512/a7eb2d0a-3947-4e55-9538-4e9fd3a62d9f">

![side panel settings](https://github.com/opentoonz/opentoonz/assets/29790512/8d667d00-5e78-4df9-924b-2aa723fb6f4e)

or

**2. Make avaivalable also the tool option bar settings info to the "settings" area of the style editor panel**

which is currently empty for the toolbar's tools.

Similar to mypaint vectors and textures brush settings

![settings_brushes_request](https://github.com/opentoonz/opentoonz/assets/29790512/7ea588ec-a1b8-49fe-9d82-8878a91411f2)

### Describe the solution you'd like

explained above

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themselves.
As this report does contain a feature request it likely contains information useful for advancing Opentoonz features which should be captured in another appropriate report.
