### ISSUE TITLE
crashes when clicking on a layer on the timeline

### ISSUE THREAD

**Issue by GleeReer** [opentoonz/opentoonz#5037]
### Description

Crashes when clicking on a layer on the timeline with any mouse button.
The problem appeared in version 1.5. I downloaded and installed version 1.7.1 from the flatpack, moved the project to it, but there is the same trouble.

In version 1.5, the message "segmentation error" appeared in the terminal. Version 1.7.1 gives a report:

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Jun 12 2023)

Report Date: 2023-08-06 14:52:11
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: KDE Flatpak runtime
OS Kernel: 6.1.38-un-def-alt1
CPU Threads: 24

GPU Vendor: AMD
GPU Model: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.49, 6.1.38-un-def-alt1)
GPU Version: 4.6 (Compatibility Profile) Mesa 23.1.4 (git-8b0202e4b4)

Crash File: /home/oleg/.var/app/io.github.OpenToonz/data/OpenToonz/OpenToonz/crash/Crash-20230806-145211.log

Application Dir: /app/bin
Stuff Dir: /home/oleg/.config/OpenToonz/stuff

Project Name: fishermen
Scene Name: fishermen1
Project Path: /home/oleg/.config/OpenToonz/stuff/projects/fishermen/fishermen_otprj.xml
Scene Path: /home/oleg/.config/OpenToonz/stuff/projects/fishermen/scenes/fishermen1.tnz

==== Backtrace ====
  1> sh: строка 1: addr2line: команда не найдена
  2> sh: строка 1: addr2line: команда не найдена
  3> sh: строка 1: addr2line: команда не найдена
  4> sh: строка 1: addr2line: команда не найдена
  5> sh: строка 1: addr2line: команда не найдена
  6> sh: строка 1: addr2line: команда не найдена
  7> sh: строка 1: addr2line: команда не найдена
  8> sh: строка 1: addr2line: команда не найдена
  9> sh: строка 1: addr2line: команда не найдена
 10> sh: строка 1: addr2line: команда не найдена
 11> sh: строка 1: addr2line: команда не найдена
 12> sh: строка 1: addr2line: команда не найдена
 13> sh: строка 1: addr2line: команда не найдена
 14> sh: строка 1: addr2line: команда не найдена
 15> sh: строка 1: addr2line: команда не найдена
 16> sh: строка 1: addr2line: команда не найдена
 17> sh: строка 1: addr2line: команда не найдена
 18> sh: строка 1: addr2line: команда не найдена
 19> sh: строка 1: addr2line: команда не найдена
 20> sh: строка 1: addr2line: команда не найдена
 21> sh: строка 1: addr2line: команда не найдена
 22> sh: строка 1: addr2line: команда не найдена
 23> sh: строка 1: addr2line: команда не найдена
 24> sh: строка 1: addr2line: команда не найдена
 25> sh: строка 1: addr2line: команда не найдена
 26> sh: строка 1: addr2line: команда не найдена
 27> sh: строка 1: addr2line: команда не найдена
 28> sh: строка 1: addr2line: команда не найдена
 29> sh: строка 1: addr2line: команда не найдена
 30> sh: строка 1: addr2line: команда не найдена
 31> sh: строка 1: addr2line: команда не найдена
 32> sh: строка 1: addr2line: команда не найдена
 33> sh: строка 1: addr2line: команда не найдена
 34> sh: строка 1: addr2line: команда не найдена
 35> sh: строка 1: addr2line: команда не найдена
 36> sh: строка 1: addr2line: команда не найдена
 37> sh: строка 1: addr2line: команда не найдена
 38> sh: строка 1: addr2line: команда не найдена
 39> sh: строка 1: addr2line: команда не найдена
 40> sh: строка 1: addr2line: команда не найдена
 41> sh: строка 1: addr2line: команда не найдена
 42> sh: строка 1: addr2line: команда не найдена
 43> sh: строка 1: addr2line: команда не найдена
 44> sh: строка 1: addr2line: команда не найдена
 45> sh: строка 1: addr2line: команда не найдена
 46> sh: строка 1: addr2line: команда не найдена
 47> sh: строка 1: addr2line: команда не найдена
 48> sh: строка 1: addr2line: команда не найдена
 49> sh: строка 1: addr2line: команда не найдена
 50> sh: строка 1: addr2line: команда не найдена
 51> sh: строка 1: addr2line: команда не найдена
 52> sh: строка 1: addr2line: команда не найдена
 53> sh: строка 1: addr2line: команда не найдена
 54> sh: строка 1: addr2line: команда не найдена
 55> sh: строка 1: addr2line: команда не найдена
 56> sh: строка 1: addr2line: команда не найдена
 57> sh: строка 1: addr2line: команда не найдена
==== End ====

### OpenToonz Version

1.7

### Operating System

Linux

### GPU

AMD

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Closing as an incomplete report without enough actionable information to troubleshoot here.
In addition to reviewing other similar reports related to crashing (those already closed), I'll recommend joining one of the Opentoonz discords where others will be able to assist in troubleshooting the issue.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
