### ISSUE TITLE
OpenToonz crashed unexpectedly

### ISSUE THREAD

**Issue by Ruthemium** [opentoonz/opentoonz#5045]
### Description

I was making a less than a minute long animation and it was working fine a few hours ago, but it keeps crashing now when I tried to open it again
![image](https://github.com/opentoonz/opentoonz/assets/142157566/c469a03c-ebdf-4a6c-bde9-973033c02faa)

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Will close this report as not having adequate information to troubleshoot the problem.
@Ruthemium If you have any additional information to share that will be appreciated.
