### ISSUE TITLE
意外崩溃 (Unexpected Crash)

### ISSUE THREAD

**Issue by giiiitt** [opentoonz/opentoonz#5054]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-08-21 11:15:40
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 21H1
OS Kernel: 10.0.19045
CPU Threads: 16

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Graphics
GPU Version: 4.6.0 Compatibility Profile Context 23.4.3.230420

Crash File: C:\Users\同学\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230821-111540.log
Mini Dump File: C:\Users\同学\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230821-111540.dmp

Application Dir: D:/Appexe/OpenToonz
Stuff Dir: D:\Appexe\OpenToonz stuff

Project Name: camera01
Scene Name: untitled8
Project Path: D:\skeleton\ep01\camera01\camera01_otprj.xml
Scene Path: C:\Users\同学\AppData\Local\OpenToonz\OpenToonz\cache\temp\untitled8\untitled8.tnz

==== Modules ====
D:\Appexe\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
D:\Appexe\OpenToonz\Qt5Xml.dll
D:\Appexe\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\ole32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
D:\Appexe\OpenToonz\glut64.dll
D:\Appexe\OpenToonz\Qt5SerialPort.dll
D:\Appexe\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
D:\Appexe\OpenToonz\colorfx.dll
C:\Windows\System32\bcrypt.dll
D:\Appexe\OpenToonz\image.dll
D:\Appexe\OpenToonz\tnztools.dll
D:\Appexe\OpenToonz\tnzstdfx.dll
D:\Appexe\OpenToonz\tfarm.dll
D:\Appexe\OpenToonz\Qt5Widgets.dll
D:\Appexe\OpenToonz\Qt5Gui.dll
D:\Appexe\OpenToonz\Qt5Core.dll
D:\Appexe\OpenToonz\sound.dll
D:\Appexe\OpenToonz\toonzqt.dll
D:\Appexe\OpenToonz\opencv_world451.dll
D:\Appexe\OpenToonz\toonzlib.dll
D:\Appexe\OpenToonz\Qt5Script.dll
D:\Appexe\OpenToonz\tnzext.dll
D:\Appexe\OpenToonz\tnzbase.dll
D:\Appexe\OpenToonz\tnzcore.dll
D:\Appexe\OpenToonz\Qt5Multimedia.dll
D:\Appexe\OpenToonz\Qt5OpenGL.dll
D:\Appexe\OpenToonz\Qt5Network.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
D:\Appexe\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
D:\Appexe\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\MF.dll
D:\Appexe\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
D:\Appexe\OpenToonz\libmypaint-1-4-0.dll
D:\Appexe\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
D:\Appexe\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
D:\Appexe\OpenToonz\Qt5Svg.dll
D:\Appexe\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
D:\Appexe\OpenToonz\libintl-8.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\Appexe\OpenToonz\libjson-c-2.dll
D:\Appexe\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
D:\Appexe\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
D:\Appexe\OpenToonz\styles\qwindowsvistastyle.dll
D:\Appexe\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0391252.inf_amd64_b298c070ddf486e2\B391109\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0391252.inf_amd64_b298c070ddf486e2\B391109\atio6axx.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
D:\Appexe\OpenToonz\imageformats\qgif.dll
D:\Appexe\OpenToonz\imageformats\qicns.dll
D:\Appexe\OpenToonz\imageformats\qico.dll
D:\Appexe\OpenToonz\imageformats\qjpeg.dll
D:\Appexe\OpenToonz\imageformats\qsvg.dll
D:\Appexe\OpenToonz\imageformats\qtga.dll
D:\Appexe\OpenToonz\imageformats\qtiff.dll
D:\Appexe\OpenToonz\imageformats\qwbmp.dll
D:\Appexe\OpenToonz\imageformats\qwebp.dll
D:\Appexe\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
D:\Appexe\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Program Files (x86)\Sangfor\SSL\ClientComponent2\SangforNspX64.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffb4e648b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ffb4e6212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb4e670eee] <ntdll.dll>
  4> QObject::isWidgetType [0x7ffb06439a74] <Qt5Core.dll>
  5> QWidgetPrivate::showChildren [0x7ffb076e9f9d] <Qt5Widgets.dll>
  6> QWidgetPrivate::show_helper [0x7ffb076ea2a4] <Qt5Widgets.dll>
  7> QWidgetPrivate::setVisible [0x7ffb076e87b8] <Qt5Widgets.dll>
  8> QWidget::setVisible [0x7ffb076e855e] <Qt5Widgets.dll>
  9> QWidgetPrivate::showChildren [0x7ffb076ea0da] <Qt5Widgets.dll>
 10> QWidgetPrivate::show_helper [0x7ffb076ea2a4] <Qt5Widgets.dll>
 11> QWidgetPrivate::setVisible [0x7ffb076e87b8] <Qt5Widgets.dll>
 12> QWidget::setVisible [0x7ffb076e855e] <Qt5Widgets.dll>
 13> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff77c204ce2] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77c62eab7] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77c62e092] <OpenToonz.exe>
 16> BaseThreadInitThunk [0x7ffb4ce87614] <KERNEL32.DLL>
 17> RtlUserThreadStart [0x7ffb4e6226b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
I will recommend that while troubleshooting install Opentoonz with the defaults.
This will at least reduce the chances of problems arising due to use of other locations/drives (i.e. D:\Appexe\OpenToonz stuff)

**Comment by giiiitt** [comment]
I will take your advice.
sorry for that incomplete bug report, I'm not a programmer and I can't clearly get those columns' meaning, so I just copy all it shows to the report. I know it must be bothering to read materials mixed together, so I didn't expect a reply, but you did.
Anyway, thanks!




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月22日 17:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [opentoonz/opentoonz] 意外崩溃 (Unexpected Crash) (Issue #5054) |

I will recommend that while troubleshooting install Opentoonz with the defaults.
This will at least reduce the chances of problems arising due to use of other locations/drives (i.e. D:\Appexe\OpenToonz stuff)

**Comment by RodneyBaker** [comment]
@giiiitt There are some users that might be able to help you in your native language in the Opentoonz discord.

Closing as an incomplete report without enough actionable information to troubleshoot here.
In addition to reviewing other similar reports related to crashing (those already closed), I'll recommend joining one of the Opentoonz discords where others will be able to assist in troubleshooting the issue.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
