### ISSUE TITLE
OpenToonz crashed unexpectedly

### ISSUE THREAD

**Issue by Kuuurtiiizz** [opentoonz/opentoonz#5057]
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-08-22 00:04:30
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 12

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.4032

Crash File: C:\Users\Kurt Brent\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230822-000430.log
Mini Dump File: C:\Users\Kurt Brent\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230822-000430.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Bouncing Ball
Scene Name: bowling
Project Path: C:\OpenToonz stuff\projects\Bouncing Ball\Bouncing Ball_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Bouncing Ball\scenes\bowling.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\System32\USER32.dll
C:\windows\System32\win32u.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\gdi32full.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\msvcrt.dll
C:\windows\System32\ucrtbase.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\sechost.dll
C:\windows\System32\SHELL32.dll
C:\windows\System32\COMDLG32.dll
C:\windows\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\windows\System32\ole32.dll
C:\windows\System32\combase.dll
C:\windows\System32\OLEAUT32.dll
C:\windows\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\windows\SYSTEM32\GLU32.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\windows\SYSTEM32\WINMM.dll
C:\windows\SYSTEM32\MFPlat.DLL
C:\windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\windows\SYSTEM32\VERSION.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\windows\SYSTEM32\USERENV.dll
C:\windows\SYSTEM32\d3d11.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\windows\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\windows\SYSTEM32\DNSAPI.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\windows\SYSTEM32\cfgmgr32.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\windows\SYSTEM32\NETUTILS.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\windows\SYSTEM32\dxcore.dll
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\SYSTEM32\profapi.dll
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\SYSTEM32\bcrypt.dll
C:\windows\SYSTEM32\DEVOBJ.dll
C:\windows\System32\WINTRUST.dll
C:\windows\SYSTEM32\MSASN1.dll
C:\windows\SYSTEM32\directxdatabasehelper.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igc64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igd12dxva64.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\SYSTEM32\CoreMessaging.dll
C:\windows\SYSTEM32\CoreUIComponents.dll
C:\windows\system32\Oleacc.dll
C:\windows\system32\UIAutomationCore.dll
C:\windows\System32\clbcatq.dll
C:\windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igxelpicd64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igdml64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igdgmm64.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\twinapi.appcore.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\windows\SYSTEM32\dhcpcsvc6.DLL
C:\windows\SYSTEM32\dhcpcsvc.DLL
C:\windows\System32\netprofm.dll
C:\windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\windows\SYSTEM32\MMDevAPI.DLL
C:\windows\SYSTEM32\wdmaud.drv
C:\windows\SYSTEM32\ksuser.dll
C:\windows\SYSTEM32\AVRT.dll
C:\windows\SYSTEM32\AUDIOSES.DLL
C:\windows\SYSTEM32\msacm32.drv
C:\windows\SYSTEM32\midimap.dll
C:\windows\SYSTEM32\resourcepolicyclient.dll
C:\windows\system32\Ninput.dll
C:\windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\windows\system32\napinsp.dll
C:\windows\system32\pnrpnsp.dll
C:\windows\System32\winrnr.dll
C:\windows\system32\wshbth.dll
C:\windows\system32\nlansp_c.dll
C:\windows\System32\fwpuclnt.dll
C:\windows\SYSTEM32\PROPSYS.dll
C:\windows\SYSTEM32\LINKINFO.dll
C:\Windows\System32\Windows.System.Launcher.dll
C:\Windows\System32\msvcp110_win.dll
C:\windows\SYSTEM32\windows.staterepositorycore.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\windows\system32\wintab32.dll
C:\windows\SYSTEM32\WINSTA.dll
C:\windows\system32\winhttp.dll
C:\windows\SYSTEM32\SspiCli.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2070_none_2713e6537381f706\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffe13f67a9a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffe13f0e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe13f92dee] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6aa6cd07b] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6aa4f61e3] <OpenToonz.exe>
  6> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6aa4dd75d] <OpenToonz.exe>
  7> QWidget::event [0x7ffda274807c] <Qt5Widgets.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6aa4db13b] <OpenToonz.exe>
  9> QApplicationPrivate::notify_helper [0x7ffda27255c0] <Qt5Widgets.dll>
 10> QApplication::notify [0x7ffda27234e0] <Qt5Widgets.dll>
 11> QCoreApplication::notifyInternal2 [0x7ffda1c9318a] <Qt5Core.dll>
 12> QApplicationPrivate::sendMouseEvent [0x7ffda27267c5] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffda27709d2] <Qt5Widgets.dll>
 14> QDesktopWidget::workAreaResized [0x7ffda276e96e] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x7ffda27255c0] <Qt5Widgets.dll>
 16> QApplication::notify [0x7ffda2724643] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x7ffda1c9318a] <Qt5Core.dll>
 18> QGuiApplicationPrivate::processMouseEvent [0x7ffda20d47c3] <Qt5Gui.dll>
 19> QWindowSystemInterface::sendWindowSystemEvents [0x7ffda20bf030] <Qt5Gui.dll>
 20> QEventDispatcherWin32::processEvents [0x7ffda1cdbcfa] <Qt5Core.dll>
 21> qt_plugin_query_metadata [0x7ffd9d1e28d9] <qwindows.dll>
 22> QEventLoop::exec [0x7ffda1c8f64c] <Qt5Core.dll>
 23> QCoreApplication::exec [0x7ffda1c92164] <Qt5Core.dll>
 24> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6aa435219] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6aa85eab7] <OpenToonz.exe>
 26> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6aa85e092] <OpenToonz.exe>
 27> BaseThreadInitThunk [0x7ffe138026ad] <KERNEL32.DLL>
 28> RtlUserThreadStart [0x7ffe13f4aa68] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
Closing as an incomplete report without enough actionable information to troubleshoot.
In addition to reviewing other similar reports already closed I'll recommend joining one of the Opentoonz discords where others will be able to assist in troubleshooting the issue.

Opentoonz discord invite:  https://discord.gg/UQxvYBKW5U
