### ISSUE TITLE
opentoonz not opening

### ISSUE THREAD

**Issue by petITA1185** [opentoonz/opentoonz#5058]
### Description

i try to open opentoonz and it crashes. i made a new folder and choosed to put the files in there, then i launch the app and it crashes. (windows 10)

### Steps to Reproduce

i dont know if this will work, but ill type in there what i did:

0. windows 10, install opentoonz 1.7
1. create a new folder
2. launch opentoonz setup
3. choose italian language
4. put the files in the new folder
5. wait for the app to install
6. open it
7. have that annoying crash log

### Expected Behavior

i expected it to normally open

### Screenshots, Video & Crash Logs

crash log: OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-08-21 19:40:16
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 16

Crash File: C:\Users\Nathaniel Rossi\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230821-194016.log
Mini Dump File: C:\Users\Nathaniel Rossi\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230821-194016.dmp

==== Modules ====
C:\Progetti\OpenTazze\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\Program Files\Avast Software\Avast\aswhook.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Progetti\OpenTazze\glut64.dll
C:\Progetti\OpenTazze\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Progetti\OpenTazze\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Progetti\OpenTazze\Qt5Xml.dll
C:\Progetti\OpenTazze\Qt5SerialPort.dll
C:\Progetti\OpenTazze\colorfx.dll
C:\Progetti\OpenTazze\image.dll
C:\Progetti\OpenTazze\tnztools.dll
C:\Progetti\OpenTazze\tnzstdfx.dll
C:\Progetti\OpenTazze\tfarm.dll
C:\Progetti\OpenTazze\Qt5Widgets.dll
C:\Progetti\OpenTazze\Qt5Core.dll
C:\Progetti\OpenTazze\Qt5Gui.dll
C:\Progetti\OpenTazze\toonzqt.dll
C:\Progetti\OpenTazze\sound.dll
C:\Progetti\OpenTazze\toonzlib.dll
C:\Progetti\OpenTazze\opencv_world451.dll
C:\Progetti\OpenTazze\tnzext.dll
C:\Progetti\OpenTazze\Qt5Script.dll
C:\Progetti\OpenTazze\Qt5OpenGL.dll
C:\Progetti\OpenTazze\tnzbase.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Progetti\OpenTazze\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Progetti\OpenTazze\tnzcore.dll
C:\Progetti\OpenTazze\VCRUNTIME140.dll
C:\Progetti\OpenTazze\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Progetti\OpenTazze\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Progetti\OpenTazze\MSVCP140_1.dll
C:\Progetti\OpenTazze\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Progetti\OpenTazze\glew32.dll
C:\Progetti\OpenTazze\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Progetti\OpenTazze\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\Progetti\OpenTazze\Qt5Svg.dll
C:\Progetti\OpenTazze\libintl-8.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Progetti\OpenTazze\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\Progetti\OpenTazze\libiconv-2.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Progetti\OpenTazze\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Progetti\OpenTazze\styles\qwindowsvistastyle.dll
C:\Progetti\OpenTazze\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffe503e8b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ffe503c12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe50410ebe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ffe353f2b9c] <MSVFW32.dll>
  6> ICOpen [0x7ffe353f2d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffdf9de6212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffdf9de4478] <image.dll>
  9> initImageIo [0x7ffdf9d87ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7b7910dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7b7912d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b7d3eab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b7d3e092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ffe4ec27614] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ffe503c26b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by petITA1185** [comment]
i just wanna make animations on my pc because on my tablet i got flipaclip and it has watermark :((

**Comment by RodneyBaker** [comment]
The good news...

Look into the file here: C:\WINDOWS\SYSTEM32\lvcod64.dll
If you remove. move or rename that logitech webcam driver the problem should go away.

REF: https://github.com/opentoonz/opentoonz/issues/4971 (and others)

**Comment by RodneyBaker** [comment]
Closing as a known issue/duplicate report.
@petITA1185 Feel free to discuss this more as needed here or...
Consider joining one of the Opentoonz discords where other users (same ones that would answer here) will be glad to help you troubleshoot.
