### ISSUE TITLE
Crash Reason: (SIGSEGV) Segmentation Fault

### ISSUE THREAD

**Issue by imshibaji** [opentoonz/opentoonz#5060]
### Description

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-08-22 14:42:32
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 22.5.0
CPU Threads: 10

GPU Vendor: Apple
GPU Model: Apple M1 Pro
GPU Version: 2.1 Metal - 83.1

Crash File: /Users/shibaji/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20230822-144232.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: sandbox
Scene Name: test2
Project Path: /Applications/OpenToonz/OpenToonz_stuff/sandbox/sandbox_otprj.xml
Scene Path: /Applications/OpenToonz/OpenToonz_stuff/sandbox/scenes/test2.tnz

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   libtnztools.dylib                   0x000000010eb0fde7 _ZN13GeometricTool9addStrokeEv + 855
  3> 5   libtnztools.dylib                   0x000000010eb1a29e _ZN13LinePrimitive12leftButtonUpERK7TPointTIdERK11TMouseEvent + 606
  4> 6   libtnztools.dylib                   0x000000010eb10da4 _ZN13GeometricTool12leftButtonUpERK7TPointTIdERK11TMouseEvent + 36
  5> 7   OpenToonz                           0x00000001022222b6 _ZN11SceneViewer9onReleaseERK11TMouseEvent + 678
  6> 8   OpenToonz                           0x00000001022233d1 _ZN11SceneViewer17mouseReleaseEventEP11QMouseEvent + 225
  7> 9   QtWidgets                           0x0000000112227a97 _ZN7QWidget5eventEP6QEvent + 439
  8> 10  QtWidgets                           0x00000001121ee52d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
  9> 11  QtWidgets                           0x00000001121f1424 _ZN12QApplication6notifyEP7QObjectP6QEvent + 7428
 10> 12  QtCore                              0x0000000114c897f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 11> 13  QtWidgets                           0x00000001121eee57 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 903
 12> 14  QtWidgets                           0x0000000112246b07 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 10951
 13> 15  QtWidgets                           0x000000011224523e _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4606
 14> 16  QtWidgets                           0x00000001121ee52d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 15> 17  QtWidgets                           0x00000001121ef8f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 16> 18  QtCore                              0x0000000114c897f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 17> 19  QtGui                               0x00000001135df811 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 3489
 18> 20  QtGui                               0x00000001135c47eb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 219
 19> 21  libqcocoa.dylib                     0x000000012278fa58 qt_plugin_instance + 199592
 20> 22  CoreFoundation                      0x00007ff81010a906 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 21> 23  CoreFoundation                      0x00007ff81010a8a9 __CFRunLoopDoSource0 + 157
 22> 24  CoreFoundation                      0x00007ff81010a686 __CFRunLoopDoSources0 + 217
 23> 25  CoreFoundation                      0x00007ff81010930a __CFRunLoopRun + 916
 24> 26  CoreFoundation                      0x00007ff81010891c CFRunLoopRunSpecific + 560
 25> 27  HIToolbox                           0x00007ff81a04cdad RunCurrentEventLoopInMode + 292
 26> 28  HIToolbox                           0x00007ff81a04c9f4 ReceiveNextEventCommon + 199
 27> 29  HIToolbox                           0x00007ff81a04c918 _BlockUntilNextEventMatchingListInModeWithFilter + 64
 28> 30  AppKit                              0x00007ff8130fc5d0 _DPSNextEvent + 858
 29>  30> sh: addr2line: command not found
 31> 33  libqcocoa.dylib                     0x000000012278e86c qt_plugin_instance + 195004
 32> 34  QtCore                              0x0000000114c8597f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 33> 35  QtCore                              0x0000000114c89d82 _ZN16QCoreApplication4execEv + 130
 34> 36  OpenToonz                           0x00000001020d2e07 main + 16487
 35> 37  dyld                                0x0000000202d0641f start + 1903
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

macOS

### GPU

Other

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Not quite sure what 'this' is but yes, there have been many fixes for similar problems.
Please give the latest nightly release a try and see if that doesn't help.
