### ISSUE TITLE
macOS Action Builds crash on open

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#5067]
### Description

It is impossible to test current PRs on macOS, since the action builds crash on open. due to missing libraries.

### Steps to Reproduce

1. Download the mac action build of the most recent open PRs
2. Drag the app out of the DMG to Downloads or etc.
3. Open app & close unknown developer security dialog
4. Right-click on app to open (which overrides unknown developer security)
5.  The app icon bounces in the dock for a short time & then crash...

### Screenshots, Video & Crash Logs

[ot-action-crash.txt](https://github.com/opentoonz/opentoonz/files/12446794/ot-action-crash.txt)

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

Current action builds from the most recent PRs

### Operating System

macOS

### GPU

Other

### Graphics Tablet

None

**Comment by artisteacher** [comment]
Still crashing...

**Comment by RodneyBaker** [comment]
I'd like to think that the github action builds might now be working.... however...

Now the nightly builds for MacOS are not propogating to the list.
I'll guess this will require an update from @shun-iwasawa

**Comment by artisteacher** [comment]
It's been a while since I tested, but they are opening now.
