### ISSUE TITLE
opentoonz crash repeatedly

### ISSUE THREAD

**Issue by Kawaiisakura** [opentoonz/opentoonz#5073]
OpenToonz 1.7  (Build Mar 14 2023)

Report Date: 2023-09-01 00:56:07
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce 940MX/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.99

Crash File: C:\Users\HP\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230901-005607.log
Mini Dump File: C:\Users\HP\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230901-005607.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: artist stands near the painting
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\artist stands near the painting.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmi.inf_amd64_6a14e722301177c2\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\SYSTEM32\nvapi64.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\dcomp.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmi.inf_amd64_6a14e722301177c2\nvldumdx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmi.inf_amd64_6a14e722301177c2\nvwgf2umx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvhmi.inf_amd64_6a14e722301177c2\Display.NvContainer\MessageBus.dll
C:\WINDOWS\System32\DriverStore\FileRepository\ki126176.inf_amd64_694219dc1ebc939c\igd10iumd64.dll
C:\WINDOWS\SYSTEM32\ncrypt.dll
C:\WINDOWS\SYSTEM32\NTASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\ki126176.inf_amd64_694219dc1ebc939c\igc64.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffb4a928b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ffb4a9012d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb4a950eee] <ntdll.dll>
  4> PegbarCenterField::tr [0x7ffafa161aa5] <tnztools.dll>
  5> ToolHandle::setTool [0x7ffafa0d9656] <tnztools.dll>
  6> ToolHandle::onImageChanged [0x7ffafa0d94c4] <tnztools.dll>
  7> QObject::qt_static_metacall [0x7ffadb0620d7] <Qt5Core.dll>
  8> TXshLevelHandle::xshLevelSwitched [0x7ffada8c4b31] <toonzlib.dll>
  9> TXshLevelHandle::setLevel [0x7ffada886d4e] <toonzlib.dll>
 10> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7f098022c] <OpenToonz.exe>
 11> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7f097f5ee] <OpenToonz.exe>
 12> QObject::qt_static_metacall [0x7ffadb0620d7] <Qt5Core.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7f09ff58f] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7f09f61a2] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7f09dd75d] <OpenToonz.exe>
 16> QWidget::event [0x7ffae009807c] <Qt5Widgets.dll>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7f09db13b] <OpenToonz.exe>
 18> QApplicationPrivate::notify_helper [0x7ffae00755c0] <Qt5Widgets.dll>
 19> QApplication::notify [0x7ffae00734e0] <Qt5Widgets.dll>
 20> QCoreApplication::notifyInternal2 [0x7ffadb04318a] <Qt5Core.dll>
 21> QApplicationPrivate::sendMouseEvent [0x7ffae00767c5] <Qt5Widgets.dll>
 22> QDesktopWidget::workAreaResized [0x7ffae00c09d2] <Qt5Widgets.dll>
 23> QDesktopWidget::workAreaResized [0x7ffae00be96e] <Qt5Widgets.dll>
 24> QApplicationPrivate::notify_helper [0x7ffae00755c0] <Qt5Widgets.dll>
 25> QApplication::notify [0x7ffae0074643] <Qt5Widgets.dll>
 26> QCoreApplication::notifyInternal2 [0x7ffadb04318a] <Qt5Core.dll>
 27> QGuiApplicationPrivate::processMouseEvent [0x7ffadb4847c3] <Qt5Gui.dll>
 28> QWindowSystemInterface::sendWindowSystemEvents [0x7ffadb46f030] <Qt5Gui.dll>
 29> QEventDispatcherWin32::processEvents [0x7ffadb08bcfa] <Qt5Core.dll>
 30> qt_plugin_query_metadata [0x7ffae83028d9] <qwindows.dll>
 31> QEventLoop::exec [0x7ffadb03f64c] <Qt5Core.dll>
 32> QCoreApplication::exec [0x7ffadb042164] <Qt5Core.dll>
 33> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7f0935219] <OpenToonz.exe>
 34> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7f0d5eab7] <OpenToonz.exe>
 35> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7f0d5e092] <OpenToonz.exe>
 36> BaseThreadInitThunk [0x7ffb49dc7614] <KERNEL32.DLL>
 37> RtlUserThreadStart [0x7ffb4a9026b1] <ntdll.dll>
==== End ====

**Comment by jpcwebb** [comment]
Same issue, on startup - fresh install:
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-09-10 14:27:06
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19044
CPU Threads: 8


Crash File: C:\Users\Jason\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230910-142706.log
Mini Dump File: C:\Users\Jason\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230910-142706.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\Program Files\AVAST Software\Avast\aswhook.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\Program Files (x86)\Dexpot\hooxpot64.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d3828c822366e497\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff89d3c8b9c] <ntdll.dll>
  2> RtlRaiseException [0x7ff89d3a1316] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff89d3f0f8e] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7fffdc7a2b9c] <MSVFW32.dll>
  6> ICOpen [0x7fffdc7a2d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7fffd77b6212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7fffd77b4478] <image.dll>
  9> initImageIo [0x7fffd7757ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff656c10dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff656c12d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65703eab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65703e092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff89c867614] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff89d3a26f1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
@jpcwebb Yours is a different/known issue related to C:\WINDOWS\SYSTEM32\lvcod64.dll
Please see that file in listed in your crash report and...

REF:  https://github.com/opentoonz/opentoonz/issues/4971#issuecomment-1601253941
(and other similar reports)

This isn't to suggest there might not be simularities but at least your issue is well reported with known ways to resolve the issue.

**Comment by jpcwebb** [comment]
Thanks, that fixed it.

**Comment by RodneyBaker** [comment]
Closing as the original report lacks sufficient information to address the problem.
@Kawaiisakura If you are still experiencing the problem please feel free to add additional information to this report.
