### ISSUE TITLE
Exception Violation Crash

### ISSUE THREAD

**Issue by bettybyrne** [opentoonz/opentoonz#5074]
### Ask a question related to OpenToonz

For some reason I cannot figure out, Opentoonz will crash after I draw one of a series of pictures.  No explanation other than a popup Exception Violation.  When I try to eliminate the cell that has caused the crash, Opentoonz crashes before I can do so.  The entire scene, therefore, is lost.  Is there anything that can be done?  
I have windows 10
here is the information from the popup:

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-08-31 16:31:16
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 12

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GT 1030/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.19

Crash File: C:\Users\walke\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230831-163116.log
Mini Dump File: C:\Users\walke\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230831-163116.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: CHARLESTON DANCERS
Scene Name: FORESHORTEN PRACTICE_1
Project Path: C:\OpenToonz stuff\projects\CHARLESTON DANCERS\CHARLESTON DANCERS_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\CHARLESTON DANCERS\scenes\FORESHORTEN PRACTICE_1.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ole32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvdd.inf_amd64_67b1df330bec74ef\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
C:\WINDOWS\SYSTEM32\msvcp110_win.dll
C:\WINDOWS\system32\IconCodecService.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
C:\Windows\System32\Windows.StateRepositoryPS.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\Windows\System32\iertutil.dll
C:\WINDOWS\system32\mssprxy.dll
C:\WINDOWS\System32\coml2.dll
C:\WINDOWS\system32\Ninput.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7fff14a88b5c] <ntdll.dll>
  2> RtlRaiseException [0x7fff14a612d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff14ab0eee] <ntdll.dll>
  4> TStroke::getMaxThickness [0x7ffece1de4e3] <tnzcore.dll>
  5> TRegion::addEdge [0x7ffece1d28c3] <tnzcore.dll>
  6> computeRegionFeature [0x7ffece1cb5a2] <tnzcore.dll>
  7> TVectorImage::replaceStroke [0x7ffece1d1e8b] <tnzcore.dll>
  8> initImageIo [0x7ffeddab8adc] <image.dll>
  9> initImageIo [0x7ffeddab8df5] <image.dll>
 10> IKSkeleton::setPurpose [0x7ffed190576d] <toonzlib.dll>
 11> ImageManager::getImage [0x7ffed1907066] <toonzlib.dll>
 12> TXshSimpleLevel::renumber [0x7ffed1a4459f] <toonzlib.dll>
 13> ToolUtils::renumberForInsertFId [0x7ffedb173316] <tnztools.dll>
 14> TTool::touchImage [0x7ffedb167e71] <tnztools.dll>
 15> StrokeSelection::toggle [0x7ffedb2b2355] <tnztools.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff71c0fbb21] <OpenToonz.exe>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff71c0fc3d4] <OpenToonz.exe>
 18> QWidget::event [0x7ffecb6a80f7] <Qt5Widgets.dll>
 19> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff71c0f942b] <OpenToonz.exe>
 20> QApplicationPrivate::notify_helper [0x7ffecb6855c0] <Qt5Widgets.dll>
 21> QApplication::notify [0x7ffecb683e73] <Qt5Widgets.dll>
 22> QCoreApplication::notifyInternal2 [0x7ffecabf318a] <Qt5Core.dll>
 23> QDesktopWidget::workAreaResized [0x7ffecb6d1284] <Qt5Widgets.dll>
 24> QDesktopWidget::workAreaResized [0x7ffecb6ceb59] <Qt5Widgets.dll>
 25> QApplicationPrivate::notify_helper [0x7ffecb6855c0] <Qt5Widgets.dll>
 26> QApplication::notify [0x7ffecb684643] <Qt5Widgets.dll>
 27> QCoreApplication::notifyInternal2 [0x7ffecabf318a] <Qt5Core.dll>
 28> QGuiApplicationPrivate::processTabletEvent [0x7ffecb0356b7] <Qt5Gui.dll>
 29> QWindowSystemInterface::sendWindowSystemEvents [0x7ffecb01f030] <Qt5Gui.dll>
 30> QEventDispatcherWin32::processEvents [0x7ffecac3bcfa] <Qt5Core.dll>
 31> qt_plugin_query_metadata [0x7ffec69328d9] <qwindows.dll>
 32> QEventLoop::exec [0x7ffecabef64c] <Qt5Core.dll>
 33> QCoreApplication::exec [0x7ffecabf2164] <Qt5Core.dll>
 34> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff71c015219] <OpenToonz.exe>
 35> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff71c43eab7] <OpenToonz.exe>
 36> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff71c43e092] <OpenToonz.exe>
 37> BaseThreadInitThunk [0x7fff130d7614] <KERNEL32.DLL>
 38> RtlUserThreadStart [0x7fff14a626b1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information to diagnose the problem.
@bettybyrne As you discover additional information related to this problem please feel free to share it here.
