### ISSUE TITLE
Rooms revert to Ghibli room set

### ISSUE THREAD

**Issue by amatoranimator** [opentoonz/opentoonz#5075]
### Description

Hello! Im amateur in animation i have bug! I don't have a mode ,,animation,, I do not know what to do I uninstalled and installed OpenToonza nothing worked
I only have cleanup modes pitedit inknpaint xsheet

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
That is the Ghibli room that you are seeing which is the fallback set of rooms in the program.
It can also be selected via Preferences:

![image](https://github.com/opentoonz/opentoonz/assets/2576432/b7e067b8-3a0d-4433-a1d0-7cc7c9a834e4)

The fact that you are seeing this unintentionally suggests you didn't get a good installation or something reset (or removed) the setting that tells Opentoonz to use the Default room set.

Before reinstalling you might try resetting your rooms:
![image](https://github.com/opentoonz/opentoonz/assets/2576432/98d780da-a4d2-4c19-8c57-1cf8b319ba0b)

Once clicked, restart OT and see if that resolves the problem

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
