### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by ryanflux** [opentoonz/opentoonz#5078]
### Description

repeated crash with said title

code:
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-09-03 08:03:51
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 16

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Graphics
GPU Version: 4.6.0 Compatibility Profile Context 22.20.24.02.220906

Crash File: C:\Users\flexy\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230903-080351.log
Mini Dump File: C:\Users\flexy\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230903-080351.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: tests
Scene Name: noodles
Project Path: C:\OpenToonz stuff\projects\tests\tests_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\tests\scenes\noodles.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0383113.inf_amd64_9242eb4af0e982f6\B383140\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0383113.inf_amd64_9242eb4af0e982f6\B383140\atio6axx.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\SYSTEM32\BCrypt.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffc651e7a9a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffc6518e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffc65212dee] <ntdll.dll>
  4> PinchTool::getToolType [0x7ffc21c94466] <tnztools.dll>
  5> PinchTool::getToolType [0x7ffc21c94808] <tnztools.dll>
  6> PinchTool::getToolType [0x7ffc21c98e07] <tnztools.dll>
  7> PinchTool::getToolType [0x7ffc21c98cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7694cbec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7694cc349] <OpenToonz.exe>
 10> QWidget::event [0x7ffc02e380f7] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7694c942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ffc02e155c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ffc02e13e73] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ffbe624318a] <Qt5Core.dll>
 15> QDesktopWidget::workAreaResized [0x7ffc02e61284] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ffc02e5eb59] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ffc02e155c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffc02e14643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffbe624318a] <Qt5Core.dll>
 20> QGuiApplicationPrivate::processTabletEvent [0x7ffbe4ee56b7] <Qt5Gui.dll>
 21> QWindowSystemInterface::sendWindowSystemEvents [0x7ffbe4ecf030] <Qt5Gui.dll>
 22> QEventDispatcherWin32::processEvents [0x7ffbe628bcfa] <Qt5Core.dll>
 23> qt_plugin_query_metadata [0x7ffc008628d9] <qwindows.dll>
 24> QEventLoop::exec [0x7ffbe623f64c] <Qt5Core.dll>
 25> QCoreApplication::exec [0x7ffbe6242164] <Qt5Core.dll>
 26> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7693e5219] <OpenToonz.exe>
 27> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76980eab7] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76980e092] <OpenToonz.exe>
 29> BaseThreadInitThunk [0x7ffc6493257d] <KERNEL32.DLL>
 30> RtlUserThreadStart [0x7ffc651caa68] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. run program for approx ten minutes
2.  crash ensues

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Following the steps described:

> run program for approx ten minutes
> crash ensues

Doesn't lead to a crash on this end.
We'll need more information to be able to take any action on this report.

On the positive side I'm pretty sure I've seen similar reports as yours so perhaps we'll get some feedback that will eventually lead a resolution.

**Comment by ryanflux** [comment]
Thanks for the update. Yea it's kind of difficult to pin point exactly when
it happens when I'm in the middle of drawing but it's good to know it looks
like a familiar error, thanks again for the quick response

**Comment by RodneyBaker** [comment]
Will close as more of a one time occurance.
@ryanflux Please let us know if you discover new information that can help in reproducing the problem.
