### ISSUE TITLE
assert changes value

### ISSUE THREAD

**Issue by maddin200** [opentoonz/opentoonz#5080]
### Description

/toonz/sources/tnztools/hookselection.cpp line 124

code:
assert(level = m_level); // <-- should be == 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Line 125 appears to have a typo/error/redundancy as well
