### ISSUE TITLE
OpenToonz crashed unexpectedly

### ISSUE THREAD

**Issue by malvibrada** [opentoonz/opentoonz#5084]
### Description

Yesterday I exported the project into another file and also added the ffmpeg file into the OpenToonz things folder. Today it crashes when I try to draw in the drawing tab.

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-09-04 10:11:33
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 16

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.23

Crash File: C:\Users\denib\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230904-101133.log
Mini Dump File: C:\Users\denib\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230904-101133.dmp

Application Dir: B:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Cabezas de Chorlito
Scene Name: EXT NIDO DIA 5
Project Path: C:\OpenToonz stuff\projects\Cabezas de Chorlito\Cabezas de Chorlito_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Cabezas de Chorlito\scenes\EXT NIDO DIA 5.tnz

==== Modules ====
B:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
B:\Program Files\OpenToonz\Qt5PrintSupport.dll
B:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\combase.dll
B:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\SHLWAPI.dll
B:\Program Files\OpenToonz\Qt5SerialPort.dll
B:\Program Files\OpenToonz\EDSDK.dll
B:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
B:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\cfgmgr32.dll
B:\Program Files\OpenToonz\tnztools.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
B:\Program Files\OpenToonz\tnzstdfx.dll
B:\Program Files\OpenToonz\tfarm.dll
B:\Program Files\OpenToonz\Qt5Widgets.dll
B:\Program Files\OpenToonz\Qt5Gui.dll
B:\Program Files\OpenToonz\Qt5Core.dll
B:\Program Files\OpenToonz\toonzqt.dll
B:\Program Files\OpenToonz\sound.dll
B:\Program Files\OpenToonz\toonzlib.dll
B:\Program Files\OpenToonz\Qt5Script.dll
B:\Program Files\OpenToonz\opencv_world451.dll
B:\Program Files\OpenToonz\tnzext.dll
B:\Program Files\OpenToonz\tnzbase.dll
B:\Program Files\OpenToonz\tnzcore.dll
B:\Program Files\OpenToonz\Qt5OpenGL.dll
B:\Program Files\OpenToonz\Qt5Multimedia.dll
B:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
B:\Program Files\OpenToonz\MSVCP140.dll
B:\Program Files\OpenToonz\MSVCP140_1.dll
B:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
B:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
B:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
B:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
B:\Program Files\OpenToonz\Qt5Svg.dll
B:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
B:\Program Files\OpenToonz\libintl-8.dll
B:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
B:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
B:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
B:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
B:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
B:\Program Files\OpenToonz\imageformats\qgif.dll
B:\Program Files\OpenToonz\imageformats\qicns.dll
B:\Program Files\OpenToonz\imageformats\qico.dll
B:\Program Files\OpenToonz\imageformats\qjpeg.dll
B:\Program Files\OpenToonz\imageformats\qsvg.dll
B:\Program Files\OpenToonz\imageformats\qtga.dll
B:\Program Files\OpenToonz\imageformats\qtiff.dll
B:\Program Files\OpenToonz\imageformats\qwbmp.dll
B:\Program Files\OpenToonz\imageformats\qwebp.dll
B:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
B:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff82b568b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ff82b5412d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff82b590eee] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6273861c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff62736d75d] <OpenToonz.exe>
  6> QWidget::event [0x7fffe79b807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff62736b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7fffe79955c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7fffe79934e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7fffe66e318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7fffe79967c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7fffe79e09d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7fffe79de96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7fffe79955c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7fffe7994643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7fffe66e318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7fffe6b247c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7fffe6b0f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7fffe672bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7fffe1ab28d9] <qwindows.dll>
 21> QEventLoop::exec [0x7fffe66df64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7fffe66e2164] <Qt5Core.dll>
 23> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6272c5219] <OpenToonz.exe>
 24> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6276eeab7] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6276ee092] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7ff82ab77614] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7ff82b5426b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
The location of some of your files on a B: drive (ex:  B:\Program Files\OpenToonz\OpenToonz.exe) while other files are on C: drive is highly suspect.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@malvibrada If you have additional information you can share that will help in assisting you.
