### ISSUE TITLE
Rendered in white only

### ISSUE THREAD

**Issue by Jate-1** [opentoonz/opentoonz#5088]
### Ask a question related to OpenToonz

After checking all the settings, it seems that there are no issues, but only white color is present during rendering, We have tried different systems, but none of them work. Please help me check where the problem is, and the project files have been packaged as attachments

[LY_YP_SC005_DH_大苪 V1.9.zip](https://github.com/opentoonz/opentoonz/files/12539812/LY_YP_SC005_DH_.V1.9.zip)

**Comment by RodneyBaker** [comment]
I think...

You may have two outputs in your FX Schematic.
Right Click and Activate the one that the nodes are flowing into and that should resolve your problem.

**Comment by Jate-1** [comment]
> 

According to your method, the problem has been solved! Thank you for every answer that has gradually given us a better understanding of this software.
