### ISSUE TITLE
Can not open OpenToonz

### ISSUE THREAD

**Issue by colorful-ink** [opentoonz/opentoonz#5097]
### Description

After the start window shows that "Creating main window ..." for a while, the start window closed and nothing happened.

### Steps to Reproduce

1. Click the OpenToonz.exe
2. 

### Screenshots, Video & Crash Logs

windows event viewer shows that the  error module is ucrtbase.dll
![image](https://github.com/opentoonz/opentoonz/assets/77783501/85b1e4a1-46eb-4366-a179-e26257b1f281)

detailed information：
[-](https://github.com/opentoonz/opentoonz/issues/new?assignees=&labels=&projects=&template=bug_report.yml#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/opentoonz/opentoonz/issues/new?assignees=&labels=&projects=&template=bug_report.yml#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-09-15T05:04:05.4943266Z" /> 
  <EventRecordID>14141</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-CJ4OG4N</Computer> 
  <Security /> 
  </System>
[-](https://github.com/opentoonz/opentoonz/issues/new?assignees=&labels=&projects=&template=bug_report.yml#) <EventData>
  <Data>OpenToonz.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>645afc80</Data> 
  <Data>ucrtbase.dll</Data> 
  <Data>10.0.19041.789</Data> 
  <Data>2bd748bf</Data> 
  <Data>c0000409</Data> 
  <Data>000000000007286e</Data> 
  <Data>24e0</Data> 
  <Data>01d9e79200d0dbdd</Data> 
  <Data>F:\OpenToonz\OpenToonz\OpenToonz.exe</Data> 
  <Data>C:\WINDOWS\System32\ucrtbase.dll</Data> 
  <Data>b8724f4e-9a98-451f-b04a-b7ce9b8eb55b</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Closing as a report that lacks actionable information to work with.
@colorful-ink  I'll recommend joining one of the Opentoonz discords or other venues where others can help you troubeshoot the problem.
