### ISSUE TITLE
Issue with crashing upon launch

### ISSUE THREAD

**Issue by bepperdev** [opentoonz/opentoonz#5103]
### Description

No matter if I test on the nightly build or the regular download, OpenToonz crashes upon selecting and opening an existing scene. The second I select a column it brings up the crash window.

### Steps to Reproduce

1. Launch OpenToonz
2. Open existing project
3. Select column and/or frame

### Expected Behavior

To select a frame to draw on

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Sep 10 2023)

Report Date: 2023-09-19 08:37:56
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 20

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.4502

Crash File: C:\Users\scout\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230919-083756.log
Mini Dump File: C:\Users\scout\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20230919-083756.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Bloo and Elo
Scene Name: bloo dance
Project Path: C:\OpenToonz stuff\projects\Bloo and Elo\Bloo and Elo_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Bloo and Elo\scenes\bloo dance.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\msvcrt.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\bcrypt.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3fd734cf72127ac9\igxelpicd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3fd734cf72127ac9\igdml64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3fd734cf72127ac9\igdgmm64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3fd734cf72127ac9\igc64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\System32\winrnr.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\nlansp_c.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\Ninput.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2215_none_270d72677387dfc3\comctl32.DLL
C:\Windows\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fffdc2a7a9a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fffdc24e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fffdc2d2dee] <ntdll.dll>
  4> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff634b78be9] <OpenToonz.exe>
  5> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff634b5fa7e] <OpenToonz.exe>
  6> QWidget::event [0x7fff5f7a807c] <Qt5Widgets.dll>
  7> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff634b5d43b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7fff5f7855c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7fff5f7834e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7fff5e45318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7fff5f7867c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7fff5f7d09d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7fff5f7ce96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7fff5f7855c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7fff5f784643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7fff5e45318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7fff5e8947c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7fff5e87f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7fff5e49bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7fff65c228d9] <qwindows.dll>
 21> QEventLoop::exec [0x7fff5e44f64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7fff5e452164] <Qt5Core.dll>
 23> TSmartPointerConstT<TXshSoundLevel>::~TSmartPointerConstT<TXshSoundLevel> [0x7ff634ab60f0] <OpenToonz.exe>
 24> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff634ee5c17] <OpenToonz.exe>
 25> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff634ee51f2] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7fffdb42257d] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7fffdc28aa68] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

Sep 10 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by konero** [comment]
Might be a Windows issue, open a CMD prompt as administrator and type `sfc /scannow`, if it finds and fixes any problems restart your PC and run it again, keep doing it until it can fix nothing else. If it finds a problem but can't fix anything, you'll need to use DISM to repair the Windows image.

**Comment by RodneyBaker** [comment]
I like where @konero is going with this one.
While there isn't a lot of informaton to go on here... it reads as a potential issue with graphics card/drivers to me.

**Comment by bepperdev** [comment]
Hey followed Konero's advice and it worked like a charm! There was some sort of corrupt file in my computer somewhere. Fixed it and now OpenToonz is running perfectly again!! Thank you all so much!
