### ISSUE TITLE
can't load old projects

### ISSUE THREAD

**Issue by vishalgore2105** [opentoonz/opentoonz#5104]
### Ask a question related to OpenToonz

when ever I open the old projects this crash happens and i have to close the program or new project 
![Screenshot (11)](https://github.com/opentoonz/opentoonz/assets/145565067/5804e0e0-5270-4947-a1f9-846c5b49b5ba)

**Comment by RodneyBaker** [comment]
Can you share the contents of an old project to test this with?
There are a number of things that could be at issue but we'll need more information to hazard more than a guess.

**Comment by RodneyBaker** [comment]
When you are able try to do the same thing but not in a custom room.
Ideally on a new install that is using default rooms without any changes.
See if that makes any difference.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@vishalgore2105 Please let us know if you are still experiencing problems.
