### ISSUE TITLE
OpenToonz crash when opening. Error message: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by jchibs** [opentoonz/opentoonz#5105]
### Description

Cannot open OpenToonz application. When opening it always show error message "EXCEPTION_ACCESS_VIOLATION"

Tried uninstalling and reinstalling OpenToonz both regular and nightly installer but nothing worked. I also tried other work around in compatibility mode and "sfc /scannow now" in command prompt but still nothing happened. 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@jchibs Closing as not enough actionable information in the report to work with but...

Check out report #5107 and other similar reports as that might relate to your case as well. 


Please feel free to add any and all information you can that will assist in helping to resolve  the problem.
