### ISSUE TITLE
Adjust the Oopacity of the Level, but it does not display after rendering

### ISSUE THREAD

**Issue by chainmask** [opentoonz/opentoonz#5106]
### Ask a question related to OpenToonz

I changed the Opacity by 20% on the Raster Level, but after rendering, the Raster Level did not change its own transparency.

Is this a bug or is it my operation error?

![Y2FP2%1L~WG12 %V_TZ3W79](https://github.com/opentoonz/opentoonz/assets/145781803/909f036d-7d8a-4e1c-a12b-17a874e7c740)
![image](https://github.com/opentoonz/opentoonz/assets/145781803/35852e6e-ae59-46f1-8815-3315ef8f8f67)

**Comment by konero** [comment]
Go to menu `Xsheet` > `Scene Settings` then check `Enable column color filter and transparency for rendering`.

**Comment by chainmask** [comment]
Thank you! It's working properly！
