### ISSUE TITLE
Move to gtkmm3 or gtkmm4? (The C++ bindings for GTK)

### ISSUE THREAD

**Issue by ghost** [opentoonz/opentoonz#5112]
### Is your feature request related to a problem? Please describe

The licensing (very expensive licensing) changes to Qt6 has put a road block for the future of OpenToonz and Tahoma2D.

### Describe the solution you'd like

Sooner or later the elephant in the room needs to be addressed, Qt company changed their licensing model with a hefty price tag to it making it completely unfeasible for development on Qt past version 5. Because the transition from Qt5 to Qt6 would be almost a rewrite, why not just transition to gtkmm? These are the C++ bindings to GTK and have no strings attached. No licensing model of any kind. Under LGPL just like Qt (partially) is. I thought I just make a general issue opened to talk about what OpenToonz should do for the future.

https://gtkmm.org/en/index.html

**Comment by RodneyBaker** [comment]
Closing as the original reporter has ghosted themselves.
There may be useful information contained in this report and where that exists it should be transferred into a new report and/or into Opentoonz documenation (as appropriate).
