### ISSUE TITLE
Crash with Opentoonz (MacBook)

### ISSUE THREAD

**Issue by SilentLullaby** [opentoonz/opentoonz#5113]
### Description

The app says it crashed unexpectely.

### Steps to Reproduce

OpenToonz 1.7.1  (Build Sep 28 2023)

Report Date: 2023-09-28 11:21:44
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 21.6.0
CPU Threads: 4

GPU Vendor: Intel Inc.
GPU Model: Intel(R) HD Graphics 6000
GPU Version: 2.1 INTEL-18.8.6

Crash File: /Users/esmeraldasolano/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20230928-112144.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: Come Back
Scene Name: Ehhhajsa
Project Path: /Applications/OpenToonz/OpenToonz_stuff/projects/Come Back/Come Back_otprj.xml
Scene Path: /Applications/OpenToonz/OpenToonz_stuff/projects/Come Back/scenes/Ehhhajsa.tnz

==== Backtrace ====
  1> 3   ???                                 0x00007ff7b1d10df8 0x0 + 140701816917496
  2> 4   OpenToonz                           0x000000010e31a2e8 _ZN9XsheetGUI8CellArea15mousePressEventEP11QMouseEvent + 3480
  3> 5   QtWidgets                           0x00000001123a0a82 _ZN7QWidget5eventEP6QEvent + 418
  4> 6   OpenToonz                           0x000000010e31fdd7 _ZN9XsheetGUI8CellArea5eventEP6QEvent + 327
  5> 7   QtWidgets                           0x000000011236752d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
  6> 8   QtWidgets                           0x000000011236a424 _ZN12QApplication6notifyEP7QObjectP6QEvent + 7428
  7> 9   QtCore                              0x0000000113d267f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
  8> 10  QtWidgets                           0x0000000112367e57 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 903
  9> 11  QtWidgets                           0x00000001123bfb07 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 10951
 10> 12  QtWidgets                           0x00000001123be23e _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4606
 11> 13  QtWidgets                           0x000000011236752d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 12> 14  QtWidgets                           0x00000001123688f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 13> 15  QtCore                              0x0000000113d267f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 14> 16  QtGui                               0x0000000112f47811 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 3489
 15> 17  QtGui                               0x0000000112f46fbb _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 1355
 16> 18  QtGui                               0x0000000112f2c7eb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 219
 17> 19  libqcocoa.dylib                     0x000000011aff2a58 qt_plugin_instance + 199592
 18> 20  CoreFoundation                      0x00007ff81d19715b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 19> 21  CoreFoundation                      0x00007ff81d1970c3 __CFRunLoopDoSource0 + 180
 20> 22  CoreFoundation                      0x00007ff81d196e3d __CFRunLoopDoSources0 + 242
 21> 23  CoreFoundation                      0x00007ff81d195858 __CFRunLoopRun + 892
 22> 24  CoreFoundation                      0x00007ff81d194e1c CFRunLoopRunSpecific + 562
 23> 25  HIToolbox                           0x00007ff825e425e6 RunCurrentEventLoopInMode + 292
 24> 26  HIToolbox                           0x00007ff825e42213 ReceiveNextEventCommon + 283
 25> 27  HIToolbox                           0x00007ff825e420e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
 26> 28  AppKit                              0x00007ff81fbcff6d _DPSNextEvent + 927
 27>  28> sh: addr2line: command not found
 29> 31  libqcocoa.dylib                     0x000000011aff186c qt_plugin_instance + 195004
 30> 32  QtCore                              0x0000000113d2297f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 31> 33  QtCore                              0x0000000113d26d82 _ZN16QCoreApplication4execEv + 130
 32> 34  OpenToonz                           0x000000010e2207c1 main + 15553
 33> 35  dyld                                0x000000011af0652e start + 462
==== End ====

### Expected Behavior

To stop showing up but it kept coming back. Because I took on an update of the verison.

### Screenshots, Video & Crash Logs

![Image 9-28-23 at 11 39 AM](https://github.com/opentoonz/opentoonz/assets/139931207/c734d09f-6c62-4c4e-93a4-30cba6080c3f)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Sep 28 2023)

### Operating System

macOS

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by SilentLullaby** [comment]
I don't know what gpu is. Don't look below it.

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information in the report to move forward.
@SilentLullaby Recommend joining one of the Opentoonz discords where others can help you troubleshoot your current issue.
