### ISSUE TITLE
crash windows11

### ISSUE THREAD

**Issue by yunnnnnnnnnnu87** [opentoonz/opentoonz#5115]
### Description

crash whenever opened

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as an incomplete report with no actionable information to assist in identifying and resolving the problem.

@yunnnnnnnnnnu87 You may wish to review some of the other closed crash reports as those have helped other Opentoonz users resolve their crashes.
