### ISSUE TITLE
Autosave some times saves during playback - which causes temporary freeze

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#512]
If you enable save every X minutes feature from preferences, sometimes it gets triggered during playback (while the animation is playing).
That causes a momentary freeze that some users might misinterpret as a crash.
It would be nice if autosave waits for playback to be stopped before being triggered.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
