### ISSUE TITLE
vector tape tool crash

### ISSUE THREAD

**Issue by 000pee** [opentoonz/opentoonz#5124]
### Description

OpenToonz 1.7.1  (Build Jun 16 2023)

Report Date: 2023-10-07 18:53:41
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 4060/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 537.42

Crash File: C:\Users\p\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231007-185341.log
Mini Dump File: C:\Users\p\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231007-185341.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: ref
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\ref.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\msiltcfg.dll
C:\WINDOWS\SYSTEM32\msi.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsi.inf_amd64_b81967d035927122\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\WINDOWS\SYSTEM32\TextShaping.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffa54468b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffa544412d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffa54490d2e] <ntdll.dll>
  4> TScale::TScale [0x7ff9eb630e06] <tnzcore.dll>
  5> TVectorImage::addStrokeToGroup [0x7ff9eb6958fb] <tnzcore.dll>
  6> ToolOptions::showEvent [0x7ff9f19f4858] <tnztools.dll>
  7> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff62d96e38d] <OpenToonz.exe>
  8> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff62d96d488] <OpenToonz.exe>
  9> QWidget::event [0x7ff9f0fe8066] <Qt5Widgets.dll>
 10> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff62d96c1fb] <OpenToonz.exe>
 11> QApplicationPrivate::notify_helper [0x7ff9f0fc55c0] <Qt5Widgets.dll>
 12> QApplication::notify [0x7ff9f0fc34e0] <Qt5Widgets.dll>
 13> QCoreApplication::notifyInternal2 [0x7ff9ed74318a] <Qt5Core.dll>
 14> QApplicationPrivate::sendMouseEvent [0x7ff9f0fc67c5] <Qt5Widgets.dll>
 15> QDesktopWidget::workAreaResized [0x7ff9f10109d2] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ff9f100e96e] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ff9f0fc55c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ff9f0fc4643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ff9ed74318a] <Qt5Core.dll>
 20> QGuiApplicationPrivate::processMouseEvent [0x7ff9eab047c3] <Qt5Gui.dll>
 21> QWindowSystemInterface::sendWindowSystemEvents [0x7ff9eaaef030] <Qt5Gui.dll>
 22> QEventDispatcherWin32::processEvents [0x7ff9ed78bcfa] <Qt5Core.dll>
 23> qt_plugin_query_metadata [0x7ff9eb3728d9] <qwindows.dll>
 24> QEventLoop::exec [0x7ff9ed73f64c] <Qt5Core.dll>
 25> QCoreApplication::exec [0x7ff9ed742164] <Qt5Core.dll>
 26> TSmartPointerConstT<TXshSoundLevel>::~TSmartPointerConstT<TXshSoundLevel> [0x7ff62d8860f0] <OpenToonz.exe>
 27> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff62dcb5b17] <OpenToonz.exe>
 28> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff62dcb50f2] <OpenToonz.exe>
 29> BaseThreadInitThunk [0x7ffa53a77344] <KERNEL32.DLL>
 30> RtlUserThreadStart [0x7ffa544426b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by DarrenTAnims** [comment]
Can you give us a clue what you was doing? 
What settings you had?
What levels you was working on?
Does it happen again after restarting or was this a one-off incident?

Without some detail, there's little that can be looked into.

**Comment by 000pee** [comment]
i try to use tape tool line to dot (endpoint to endpoint,join vector)
setting 1920/1080 pixel
vector level
after restarting everything fine (except non save data)

**Comment by 000pee** [comment]
> Can you give us a clue what you was doing? What settings you had? What levels you was working on? Does it happen again after restarting or was this a one-off incident?
> 
> Without some detail, there's little that can be looked into.

i try to use tape tool line to dot (endpoint to endpoint,join vector)
setting 1920/1080 pixel
vector level
after restarting everything fine (except non save data)

**Comment by DarrenTAnims** [comment]
It sounds like it's just a one-off issue, which will happen from time to time with all tools, so it's unlikely something that can be fixed. If you have repeating steps for a problem, please do share them.

**Comment by RodneyBaker** [comment]
Will close as a one time occurance.
@000pee Please let us know if the problem occurs again.
