### ISSUE TITLE
Drawing tablet not working

### ISSUE THREAD

**Issue by AYU3413** [opentoonz/opentoonz#5127]
### Description

the drawing tablet is not working 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Closing as a report that lacks any information that can assist in addressing the problem.
@AYU3413 I will recommend you join one of the Opentoonz discords (chat rooms) where other users can assist you in troubleshooting your tablet problems.

Here's an invite:  https://discord.gg/Y6FvQkpg76
