### ISSUE TITLE
Some drawings in my "A.tlv" file are corrupted.

### ISSUE THREAD

**Issue by theEpicjosh** [opentoonz/opentoonz#5129]
### Description

This never happened before. I go to load my scene one day and I see that some drawings in my A level were missing. Upon trying to reload them, I get an error message and OpenToonz crashes.
I even tried to load the A.tlv file independently from the current scene, into a new file, and the same issue still persists.

### Steps to Reproduce

1. I load my project.
2. I see some corrupted drawings to the side marked "no image".
3. I right-click on the imageless drawing and click "Reload".
4. I get this crash report.

### Expected Behavior

I was already supposed to have my drawings present in the file like I always had them.
However, I don't think I did anything prior that made them as corrupt

### Screenshots, Video & Crash Logs

LOG:

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-10-13 14:23:56
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 32

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3080/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.99

Crash File: C:\Users\Josh\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231013-142356.log
Mini Dump File: C:\Users\Josh\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231013-142356.dmp

Application Dir: D:/OpenToonz
Stuff Dir: D:\OpenToonz\portablestuff

Project Name: CrosswordSt-YourGodsMind
Scene Name: CrosswordSt-YourGodsMind
Project Path: D:\OpenToonz\portablestuff\projects\CrosswordSt-YourGodsMind\CrosswordSt-YourGodsMind_otprj.xml
Scene Path: D:\OpenToonz\portablestuff\projects\CrosswordSt-YourGodsMind\scenes\CrosswordSt-YourGodsMind.tnz

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
D:\OpenToonz\Qt5Xml.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\OpenToonz\glut64.dll
C:\WINDOWS\System32\shcore.dll
D:\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
D:\OpenToonz\colorfx.dll
D:\OpenToonz\image.dll
C:\WINDOWS\System32\WS2_32.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\tnzcore.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
D:\OpenToonz\MSVCP140.dll
D:\OpenToonz\MSVCP140_1.dll
D:\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
D:\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\OpenToonz\libmypaint-1-4-0.dll
D:\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
D:\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
D:\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
D:\OpenToonz\CONCRT140.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
D:\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\bcrypt.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_4cd868923cf17286\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
D:\OpenToonz\imageformats\qgif.dll
D:\OpenToonz\imageformats\qicns.dll
D:\OpenToonz\imageformats\qico.dll
D:\OpenToonz\imageformats\qjpeg.dll
D:\OpenToonz\imageformats\qsvg.dll
D:\OpenToonz\imageformats\qtga.dll
D:\OpenToonz\imageformats\qtiff.dll
D:\OpenToonz\imageformats\qwbmp.dll
D:\OpenToonz\imageformats\qwebp.dll
D:\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\SYSTEM32\TextShaping.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff91e467aaa] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff91e40e232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff91e4932fe] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e53b3cb] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e53ddf2] <OpenToonz.exe>
  6> QObject::qt_static_metacall [0x7ff81c1320d7] <Qt5Core.dll>
  7> QAction::activate [0x7ff81d115eff] <Qt5Widgets.dll>
  8> QMenu::actionGeometry [0x7ff81d26c308] <Qt5Widgets.dll>
  9> QMenu::actionGeometry [0x7ff81d26c0e3] <Qt5Widgets.dll>
 10> QMenu::mouseReleaseEvent [0x7ff81d2718a1] <Qt5Widgets.dll>
 11> QWidget::event [0x7ff81d148092] <Qt5Widgets.dll>
 12> QMenu::event [0x7ff81d26d8a7] <Qt5Widgets.dll>
 13> QApplicationPrivate::notify_helper [0x7ff81d1255c0] <Qt5Widgets.dll>
 14> QApplication::notify [0x7ff81d1234e0] <Qt5Widgets.dll>
 15> QCoreApplication::notifyInternal2 [0x7ff81c11318a] <Qt5Core.dll>
 16> QApplicationPrivate::sendMouseEvent [0x7ff81d1267c5] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ff81d170383] <Qt5Widgets.dll>
 18> QDesktopWidget::workAreaResized [0x7ff81d16e96e] <Qt5Widgets.dll>
 19> QApplicationPrivate::notify_helper [0x7ff81d1255c0] <Qt5Widgets.dll>
 20> QApplication::notify [0x7ff81d124643] <Qt5Widgets.dll>
 21> QCoreApplication::notifyInternal2 [0x7ff81c11318a] <Qt5Core.dll>
 22> QGuiApplicationPrivate::processMouseEvent [0x7ff81cad47c3] <Qt5Gui.dll>
 23> QWindowSystemInterface::sendWindowSystemEvents [0x7ff81cabf030] <Qt5Gui.dll>
 24> QEventDispatcherWin32::processEvents [0x7ff81c15bcfa] <Qt5Core.dll>
 25> qt_plugin_query_metadata [0x7ff81b9c28d9] <qwindows.dll>
 26> QEventLoop::exec [0x7ff81c10f64c] <Qt5Core.dll>
 27> QMenu::exec [0x7ff81d26ddd8] <Qt5Widgets.dll>
 28> QMenu::exec [0x7ff81d26db7b] <Qt5Widgets.dll>
 29> TSmartPointerT<TXshChildLevel>::~TSmartPointerT<TXshChildLevel> [0x7ff73e3a1e4e] <OpenToonz.exe>
 30> QWidget::event [0x7ff81d1485bd] <Qt5Widgets.dll>
 31> QFrame::event [0x7ff81d1e9d10] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ff81d1255c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ff81d123cf3] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ff81c11318a] <Qt5Core.dll>
 35> QDesktopWidget::workAreaResized [0x7ff81d170abb] <Qt5Widgets.dll>
 36> QDesktopWidget::workAreaResized [0x7ff81d16e96e] <Qt5Widgets.dll>
 37> QApplicationPrivate::notify_helper [0x7ff81d1255c0] <Qt5Widgets.dll>
 38> QApplication::notify [0x7ff81d124643] <Qt5Widgets.dll>
 39> QCoreApplication::notifyInternal2 [0x7ff81c11318a] <Qt5Core.dll>
 40> QGuiApplicationPrivate::processMouseEvent [0x7ff81cad47c3] <Qt5Gui.dll>
 41> QWindowSystemInterface::sendWindowSystemEvents [0x7ff81cabf030] <Qt5Gui.dll>
 42> QEventDispatcherWin32::processEvents [0x7ff81c15bcfa] <Qt5Core.dll>
 43> qt_plugin_query_metadata [0x7ff81b9c28d9] <qwindows.dll>
 44> QEventLoop::exec [0x7ff81c10f64c] <Qt5Core.dll>
 45> QCoreApplication::exec [0x7ff81c112164] <Qt5Core.dll>
 46> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73e325219] <OpenToonz.exe>
 47> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e74eab7] <OpenToonz.exe>
 48> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73e74e092] <OpenToonz.exe>
 49> BaseThreadInitThunk [0x7ff91c48257d] <KERNEL32.DLL>
 50> RtlUserThreadStart [0x7ff91e44aa78] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1 (May 10 2023 11:07:51)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by RodneyBaker** [comment]
Will close as a likely one off problem encountered.
We should recognize that users till too often run into situations where file can either go missing or become corrupted.
It isn't clear how to safeguard again removal or corruption of files but this shouldn't stop us from reviewing the process and finding more secure ways to operate and in case of lost data... to speedily and fully recover.
