### ISSUE TITLE
open toonz crashing

### ISSUE THREAD

**Issue by sa-NJAI** [opentoonz/opentoonz#5132]
### Description

crashing

### Steps to Reproduce

solve crashing problem

### Screenshots, Video & Crash Logs

![Screenshot (8)](https://github.com/opentoonz/opentoonz/assets/148141500/5be97e30-ba27-48dd-867e-071b45958251)

### OpenToonz Version

1.7

### OpenToonz Version Information

open toonz 1.7.1

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by sa-NJAI** [comment]
![Screenshot (8)](https://github.com/opentoonz/opentoonz/assets/148141500/556b52a4-4b66-423d-b00c-b72f6a382b54)

**Comment by DarrenTAnims** [comment]
"Steps to Reproduce
solve crashing problem"

This is asking what steps we can take to reproduce your problem.
Without any steps or any details of what you was doing or your computer specs, there's nothing that can be done.

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information in the report to move forward.
@sa-NJAI Recommend joining one of the Opentoonz discords where others will assist in troubleshooting the issue you are experiencing.
