### ISSUE TITLE
OpenToonz crashes on start (Logitec webcam driver)

### ISSUE THREAD

**Issue by NotAgentAJ** [opentoonz/opentoonz#5137]
### Description

open toonz crashes as soon as i start it. i have updated my drivers and tried running it as administrator.

### Steps to Reproduce

1. double click on open toonz
2. crash report pops up

### Expected Behavior

i expected open toonz to open

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-10-20 11:50:28
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

Crash File: C:\Users\Andrew\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231020-115028.log
Mini Dump File: C:\Users\Andrew\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231020-115028.dmp

==== Modules ====
E:\OpenToonz\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
E:\OpenToonz\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
E:\OpenToonz\OpenToonz\Qt5Xml.dll
E:\OpenToonz\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
E:\OpenToonz\OpenToonz\glut64.dll
E:\OpenToonz\OpenToonz\colorfx.dll
E:\OpenToonz\OpenToonz\image.dll
E:\OpenToonz\OpenToonz\EDSDK.dll
E:\OpenToonz\OpenToonz\tnztools.dll
C:\WINDOWS\System32\WS2_32.dll
E:\OpenToonz\OpenToonz\tfarm.dll
E:\OpenToonz\OpenToonz\tnzstdfx.dll
E:\OpenToonz\OpenToonz\toonzqt.dll
E:\OpenToonz\OpenToonz\sound.dll
E:\OpenToonz\OpenToonz\Qt5Core.dll
E:\OpenToonz\OpenToonz\Qt5Widgets.dll
E:\OpenToonz\OpenToonz\opencv_world451.dll
E:\OpenToonz\OpenToonz\toonzlib.dll
E:\OpenToonz\OpenToonz\tnzext.dll
E:\OpenToonz\OpenToonz\Qt5Script.dll
E:\OpenToonz\OpenToonz\Qt5OpenGL.dll
E:\OpenToonz\OpenToonz\tnzbase.dll
E:\OpenToonz\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
E:\OpenToonz\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
E:\OpenToonz\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
E:\OpenToonz\OpenToonz\MSVCP140.dll
E:\OpenToonz\OpenToonz\VCRUNTIME140.dll
E:\OpenToonz\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
E:\OpenToonz\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
E:\OpenToonz\OpenToonz\libmypaint-1-4-0.dll
E:\OpenToonz\OpenToonz\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
E:\OpenToonz\OpenToonz\Qt5Svg.dll
E:\OpenToonz\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
E:\OpenToonz\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
E:\OpenToonz\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
E:\OpenToonz\OpenToonz\libintl-8.dll
E:\OpenToonz\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
E:\OpenToonz\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
E:\OpenToonz\OpenToonz\styles\qwindowsvistastyle.dll
E:\OpenToonz\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_4eef80c06561d01a\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\gpapi.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_4eef80c06561d01a\nvgpucomp64.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffb19b08b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffb19ae12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb19b30ebe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ffb0b522b9c] <MSVFW32.dll>
  6> ICOpen [0x7ffb0b522d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffb0d786212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffb0d784478] <image.dll>
  9> initImageIo [0x7ffb0d727ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff789450dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff789452d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78987eab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78987e092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ffb18e87344] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ffb19ae26b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
The good news is that this is a known issue related to outdated logitech webcam driver located at:  C:\WINDOWS\SYSTEM32\lvcod64.dll

You can see that listed in your crash report.

Renaming or removing that file will resolve the problem.

**Comment by NotAgentAJ** [comment]
well that's weird, but it worked, thanks.
