### ISSUE TITLE
Flatpak does not save preferences

### ISSUE THREAD

**Issue by jzkmath** [opentoonz/opentoonz#5138]
### Description

When I set the output directory for ffmpeg from `/usr/bin` to `/app/bin` and then restart the program, the preferences revert back to `/usr/bin`

### Steps to Reproduce

1. install flatpak version of opentoonz onto system
2. open preferences
3. change ffmpeg output path in Import/Export from `/usr/bin` to `/app/bin`
4. restart opentoonz
5. check ffmpeg path

### Expected Behavior

ffmpeg path stays at `/app/bin` after program restart

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1 built Jun 12 2023

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by jzkmath** [comment]
it should be noted that because of this, it is essentially impossible for me to import or export any video files from Opentoonz.

**Comment by andeon** [comment]
Apparently, every new opening of the program is rewriting the "preferences.ini" file in your home folder .config/OpenToonz/stuff/profiles/layouts/settings.YourNameUser

Have some issues about this in https://github.com/flathub/io.github.OpenToonz

I think add a small patch to change the path should solve this issue or something similar made in Snap https://github.com/snapcrafters/opentoonz

**Comment by andeon** [comment]
Since this PR https://github.com/flathub/io.github.OpenToonz/pull/26 has been merged, this fixes the issue for Flatpak users.

Then we can close this one.
