### ISSUE TITLE
Crash with specific scene + TLV files cannot be saved

### ISSUE THREAD

**Issue by AkutaZehy** [opentoonz/opentoonz#5144]
### Description

OpenToonz crashes every time now when opening a certain scene, the scene is created yesterday around 2023/10/24 0:00 ~ 1:00 and the computer is only closed once after saving the scene maually. The project could be normally exported at that time.

Another weird thing is that I have checked the files in project\extras but I didn't find the expected files in this scene like the other scene. The other scene saved all paintings in that path. The paintings in this scene are saved in project\drawings and unproblematic, the placement of the frame grid has not been saved here, so I need some time to restore my animation.

I have to added that I have checked the similar problem https://github.com/opentoonz/opentoonz/issues/5107 or https://github.com/opentoonz/opentoonz/issues/4883, however there's no such file called "lvcod64.dll" or "lvcode64.dll" in my computer after global scanning.

Then I updated my application from 1.7.1  (Build Mar 14 2023) to 1.7.1  (Build Oct  4 2023), however that does no help to the bug. The latest crash report has been pasted onto the corresponding form. Due to personal issues, the project files are temporarily not included here. If the entire content provided is not sufficient to determine where the problem lies, the necessary file information will be attached.

### Steps to Reproduce

1.
2.

### Expected Behavior

Just normally open a scene.

The scene nearby in this project could be opened normally.

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Oct  4 2023)

Report Date: 2023-10-24 11:17:42
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 16

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Graphics
GPU Version: 4.6.0 Compatibility Profile Context 23.9.2.230827

Crash File: C:\Users\31374\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231024-111742.log
Mini Dump File: C:\Users\31374\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231024-111742.dmp

Application Dir: D:/Program Files/OpenToonz
Stuff Dir: D:\Workfile\Tools\OpenToonz Stuff

Project Name: Spring Loneliness
Scene Name: 
Project Path: D:\Workfile\Tools\OpenToonz Stuff\projects\Spring Loneliness\Spring Loneliness_otprj.xml
Scene Path: 

==== Modules ====
D:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\Program Files\OpenToonz\Qt5SerialPort.dll
D:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\Program Files\OpenToonz\glut64.dll
D:\Program Files\OpenToonz\Qt5Xml.dll
D:\Program Files\OpenToonz\colorfx.dll
D:\Program Files\OpenToonz\image.dll
D:\Program Files\OpenToonz\tnztools.dll
D:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
D:\Program Files\OpenToonz\tfarm.dll
D:\Program Files\OpenToonz\tnzstdfx.dll
D:\Program Files\OpenToonz\toonzqt.dll
D:\Program Files\OpenToonz\sound.dll
D:\Program Files\OpenToonz\Qt5Core.dll
D:\Program Files\OpenToonz\Qt5Widgets.dll
D:\Program Files\OpenToonz\opencv_world451.dll
D:\Program Files\OpenToonz\Qt5Script.dll
D:\Program Files\OpenToonz\toonzlib.dll
D:\Program Files\OpenToonz\tnzext.dll
D:\Program Files\OpenToonz\tnzbase.dll
D:\Program Files\OpenToonz\Qt5OpenGL.dll
D:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
D:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
D:\Program Files\OpenToonz\VCRUNTIME140.dll
D:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
D:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\Program Files\OpenToonz\MSVCP140_1.dll
D:\Program Files\OpenToonz\libmypaint-1-4-0.dll
D:\Program Files\OpenToonz\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
D:\Program Files\OpenToonz\Qt5Svg.dll
D:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
D:\Program Files\OpenToonz\libjson-c-2.dll
D:\Program Files\OpenToonz\libintl-8.dll
D:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
D:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
D:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\system32\SogouTSF.ime
C:\WINDOWS\system32\MSIMG32.dll
C:\WINDOWS\system32\SogouPY.ime
C:\WINDOWS\SYSTEM32\OLEACC.dll
C:\WINDOWS\SYSTEM32\WINHTTP.dll
D:\Program Files\SogouInput\13.7.0.7991\Resource.dll
D:\Program Files\SogouInput\Components\PicFace\1.1.0.2129\PicFace64.dll
C:\WINDOWS\System32\PSAPI.DLL
C:\WINDOWS\SYSTEM32\TextShaping.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\msiltcfg.dll
C:\WINDOWS\SYSTEM32\msi.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0396094.inf_amd64_a90ea54eeab05481\B395672\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0396094.inf_amd64_a90ea54eeab05481\B395672\atio6axx.dll
C:\WINDOWS\SYSTEM32\amdihk64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\SYSTEM32\dcomp.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\d3d12.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0396094.inf_amd64_a90ea54eeab05481\B395672\amdxc64.dll
C:\WINDOWS\system32\D3D12Core.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0396094.inf_amd64_a90ea54eeab05481\B395672\amdenc64.dll
C:\WINDOWS\SYSTEM32\D3DSCache.dll
C:\WINDOWS\system32\dwrite.dll
D:\Program Files\OpenToonz\imageformats\qgif.dll
D:\Program Files\OpenToonz\imageformats\qicns.dll
D:\Program Files\OpenToonz\imageformats\qico.dll
D:\Program Files\OpenToonz\imageformats\qjpeg.dll
D:\Program Files\OpenToonz\imageformats\qsvg.dll
D:\Program Files\OpenToonz\imageformats\qtga.dll
D:\Program Files\OpenToonz\imageformats\qtiff.dll
D:\Program Files\OpenToonz\imageformats\qwbmp.dll
D:\Program Files\OpenToonz\imageformats\qwebp.dll
D:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffca98a8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffca98812d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffca98d0ebe] <ntdll.dll>
  4> QString::toInt [0x7ffc63aba493] <Qt5Core.dll>
  5> initImageIo [0x7ffc6bfbfdbb] <image.dll>
  6> initImageIo [0x7ffc6bfbf504] <image.dll>
  7> initImageIo [0x7ffc6bfc152b] <image.dll>
  8> 
  9> TLevelReaderP::TLevelReaderP [0x7ffc62bc5a25] <tnzcore.dll>
 10> TXshSimpleLevel::load [0x7ffc63501b15] <toonzlib.dll>
 11> ToonzScene::loadResources [0x7ffc634b38db] <toonzlib.dll>
 12> ToonzScene::load [0x7ffc634b2abb] <toonzlib.dll>
 13> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff700197de1] <OpenToonz.exe>
 14> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff700142b67] <OpenToonz.exe>
 15> QObject::qt_static_metacall [0x7ffc63be20d7] <Qt5Core.dll>
 16> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff70032e8d0] <OpenToonz.exe>
 17> QObject::qt_static_metacall [0x7ffc63be20d7] <Qt5Core.dll>
 18> QListWidget::qt_static_metacall [0x7ffc64f8aa1b] <Qt5Widgets.dll>
 19> QObject::qt_static_metacall [0x7ffc63be20d7] <Qt5Core.dll>
 20> QAbstractItemView::mouseReleaseEvent [0x7ffc64f52a0f] <Qt5Widgets.dll>
 21> QListView::mouseReleaseEvent [0x7ffc64f8346f] <Qt5Widgets.dll>
 22> QWidget::event [0x7ffc64d58092] <Qt5Widgets.dll>
 23> QFrame::event [0x7ffc64df9d10] <Qt5Widgets.dll>
 24> QAbstractItemView::viewportEvent [0x7ffc64f58ae8] <Qt5Widgets.dll>
 25> QCoreApplicationPrivate::sendThroughObjectEventFilters [0x7ffc63bc523a] <Qt5Core.dll>
 26> QApplicationPrivate::notify_helper [0x7ffc64d355ac] <Qt5Widgets.dll>
 27> QApplication::notify [0x7ffc64d334e0] <Qt5Widgets.dll>
 28> QCoreApplication::notifyInternal2 [0x7ffc63bc318a] <Qt5Core.dll>
 29> QApplicationPrivate::sendMouseEvent [0x7ffc64d367c5] <Qt5Widgets.dll>
 30> QDesktopWidget::workAreaResized [0x7ffc64d809d2] <Qt5Widgets.dll>
 31> QDesktopWidget::workAreaResized [0x7ffc64d7e96e] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ffc64d355c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ffc64d34643] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ffc63bc318a] <Qt5Core.dll>
 35> QGuiApplicationPrivate::processMouseEvent [0x7ffc623f47c3] <Qt5Gui.dll>
 36> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc623df030] <Qt5Gui.dll>
 37> QEventDispatcherWin32::processEvents [0x7ffc63c0bcfa] <Qt5Core.dll>
 38> qt_plugin_query_metadata [0x7ffc622a28d9] <qwindows.dll>
 39> QEventLoop::exec [0x7ffc63bbf64c] <Qt5Core.dll>
 40> QCoreApplication::exec [0x7ffc63bc2164] <Qt5Core.dll>
 41> TSmartPointerConstT<TXshSoundLevel>::~TSmartPointerConstT<TXshSoundLevel> [0x7ff6fff85dc0] <OpenToonz.exe>
 42> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7003b58d7] <OpenToonz.exe>
 43> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7003b4eb2] <OpenToonz.exe>
 44> BaseThreadInitThunk [0x7ffca8f47344] <KERNEL32.DLL>
 45> RtlUserThreadStart [0x7ffca98826b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RattusaurusRex** [comment]
Regular Raster levels (PNG, TIF) are normally stored in the extras folder.  ToonzRaster and Vector levels (TLV, PLI) are normally stored in the drawings folder.  Do you maybe have a corrupt vector level causing the crash?  Try loading the levels from your crashing scene into a brand new scene (Level -> Load Level).

**Comment by RodneyBaker** [comment]
The only thing that seems odd to me in your crash report is the location of applications and stuff directory which is showing as being on a drive D: instead of the standard drive C.  This would not generally be an issue but your other system files are being reported as being on drive C:.

As such I'll suggest at least testing with Opentoonz installed in it's default location on C: drive.
If that works then it will provide a good foundation to branch out on and run Opentoonz from other drives.
But I would first test the defaults and resolve any issues there.

**Comment by AkutaZehy** [comment]
> Regular Raster levels (PNG, TIF) are normally stored in the extras folder. ToonzRaster and Vector levels (TLV, PLI) are normally stored in the drawings folder. Do you maybe have a corrupt vector level causing the crash? Try loading the levels from your crashing scene into a brand new scene (Level -> Load Level).

Thank you for your proposal.

I have noticed the "level" issue. In the subsequent "reconstruction" work, I used the TIF format to replace the previously used TLV  to save the painting file, effectively avoiding crashes and file loss currently.

Load-level was tried at the same time. It caused a similar crash even in brand new scene, highly likely that the files were already corrupted when saving before.

**Comment by AkutaZehy** [comment]
@RodneyBaker 

Thank you for your proposal.

The situation is much more **WEIRD** than I imagined, so I temporarily change the title to "Crash with specific scene + TLV files cannot be saved". Or I need to start a new issue maybe?

I have checked is:open issues and fould that my problem is  similar to #5129.

Before this scene crashed I have successfully exported it to MP4 files, so I created a new scene in the same project, importing the MP4 file and added a new OpenToonz track (saving as TLV) to finish the unfinished part. To avoid unexpected loss, I tried to save after drawing a few frames then I found all drawn frames were lost at once with the frames marked "no image'. It seems that this situation cannot be stably reproduced at present, and there may be unclear reasons for unexpected quitting with no crash report during the use of the software **FREQUENTLY**.

As mentioned, this problem was temporarily solved when I started to save paintings with TIF format in a new project, no more file loss and there are few unexpected quitting, which seems to be a significant improvement in software stability.

However, I did not consider the installation path problem as you mentioned, which may be one of the most likely reasons for software instability. I will try again later and report the results below.

![image](https://github.com/opentoonz/opentoonz/assets/42381419/9f9d0b39-536c-4ab0-9b41-402146d48e27)

The screenshot is about the TLV file loss when saving and it is in Chinese, all the frames went "no image".

**Comment by AkutaZehy** [comment]
Okay bruh, I think we may need to mark this issue as "closed".

This is astonishing that after uninstalling the software completely and reinstall it in the default path, I can normally open the previous "seemed-corrupted" scene. The stability of the software has not been tested yet, but it should have also been improved I think.

That is to say, crashes and software instability in specific scenes are likely caused by "not being installed in the default path", which may require additional checks and testing :)

At present, the software will be used in the default path. If new problems arise, a new issue will be opened for feedback.

**Comment by RodneyBaker** [comment]
Thanks for the feedback @AkutaZehy 
Very good to know.
That is also something we'll want to investigate because the software should be able to be installed in other locations as well.

Something else to keep in mind for the future is the fact that EVERY copy of Opentoonz can be turned into a portable version that doesn't need to be installed so... if you want to run Opentoonz from D: drive that can be done as well.  Apparently, in your case there is a conflict with the install however.  The steps to create a portable are quite easy but initially seem difficult.  If interested in this just let us know and we can elaborate further.  The short of it is:  Create a new directory where you want the portable and then copy the program files into that directory.  Then copy the stuff directory over into that same directory BUT rename "Opentoonz stuff" to "portablestuff".  Done.  You now have a portable copy of Opentoonz that can be moved to any (reasonable) location and run.
