### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by tokiyomangigang** [opentoonz/opentoonz#5145]
### Description

dear sir i was using opentoonz and making a animation but suddenly a massege came in the middle of my animation and it's telling me that files are crashed . Because of this i can't able to continue my animation work and if i am trying to close it so it's deleting my animation work as well so, i have huge request to you please solve this bugs or problem which is not letting me to finish my work .
![Screenshot (376)](https://github.com/opentoonz/opentoonz/assets/148845387/7ae9e7b5-9f03-4450-88fb-150632951965)

### Steps to Reproduce

1. 
2. 

### Expected Behavior

i don't want this problem again 

### Screenshots, Video & Crash Logs

![Screenshot (376)](https://github.com/opentoonz/opentoonz/assets/148845387/d6c4fecc-d432-4142-907e-d51eb4eed801)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as:
1) Report lacks sufficient information to move forward
2) Likely a one time occurance

@tokiyomangigang While you are certainly welcome to post additional information here I will recommend you join one of the Opentoonz discords where others can assist in troubleshooting the issue you are experiencing.
