### ISSUE TITLE
Open Toonz crashed

### ISSUE THREAD

**Issue by tvortsa** [opentoonz/opentoonz#5150]
### Description

Just start Open Toonz and after few cliks - crush!

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-10-28 20:16:53
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 12

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics
GPU Version: 4.6.0 - Build 27.20.100.9365

Crash File: C:\Users\Gigabyte\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231028-201653.log
Mini Dump File: C:\Users\Gigabyte\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231028-201653.dmp

Application Dir: E:/Program Files/OpenToonz
Stuff Dir: D:\OpenToonz stuff

Project Name: synergy_1
Scene Name: ball
Project Path: D:\OpenToonz stuff\projects\synergy_1\synergy_1_otprj.xml
Scene Path: D:\OpenToonz stuff\projects\synergy_1\scenes\ball.tnz

==== Modules ====
E:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
E:\Program Files\OpenToonz\Qt5Xml.dll
E:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\combase.dll
E:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\ole32.dll
E:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\OLEAUT32.dll
E:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\cfgmgr32.dll
E:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\bcrypt.dll
E:\Program Files\OpenToonz\tnztools.dll
E:\Program Files\OpenToonz\image.dll
E:\Program Files\OpenToonz\tnzstdfx.dll
E:\Program Files\OpenToonz\tfarm.dll
E:\Program Files\OpenToonz\Qt5Gui.dll
E:\Program Files\OpenToonz\toonzqt.dll
E:\Program Files\OpenToonz\sound.dll
E:\Program Files\OpenToonz\Qt5Widgets.dll
E:\Program Files\OpenToonz\Qt5Core.dll
E:\Program Files\OpenToonz\Qt5Script.dll
E:\Program Files\OpenToonz\tnzext.dll
E:\Program Files\OpenToonz\toonzlib.dll
E:\Program Files\OpenToonz\opencv_world451.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
E:\Program Files\OpenToonz\tnzbase.dll
E:\Program Files\OpenToonz\tnzcore.dll
E:\Program Files\OpenToonz\Qt5OpenGL.dll
E:\Program Files\OpenToonz\Qt5Multimedia.dll
E:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
E:\Program Files\OpenToonz\MSVCP140_1.dll
E:\Program Files\OpenToonz\MSVCP140.dll
E:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
E:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\VERSION.dll
E:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
E:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
E:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
E:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
E:\Program Files\OpenToonz\libintl-8.dll
E:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
E:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
E:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
E:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
E:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\msiltcfg.dll
C:\Windows\SYSTEM32\msi.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_23a1c1315f01c788\ig9icd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_23a1c1315f01c788\igdml64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_23a1c1315f01c788\igdgmm64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_23a1c1315f01c788\igc64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
E:\Program Files\OpenToonz\imageformats\qgif.dll
E:\Program Files\OpenToonz\imageformats\qicns.dll
E:\Program Files\OpenToonz\imageformats\qico.dll
E:\Program Files\OpenToonz\imageformats\qjpeg.dll
E:\Program Files\OpenToonz\imageformats\qsvg.dll
E:\Program Files\OpenToonz\imageformats\qtga.dll
E:\Program Files\OpenToonz\imageformats\qtiff.dll
E:\Program Files\OpenToonz\imageformats\qwbmp.dll
E:\Program Files\OpenToonz\imageformats\qwebp.dll
E:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
E:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\Ninput.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3570_none_60bb2a3971f3e41a\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffb13248b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffb132212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb13270ebe] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6206b61c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff62069d75d] <OpenToonz.exe>
  6> QWidget::event [0x7ffab1e6807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff62069b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ffab1e455c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffab1e434e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffab1a3318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ffab1e467c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ffab1e909d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffab1e8e96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffab1e455c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffab1e44643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffab1a3318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ffab09547c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ffab093f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ffab1a7bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ffab11628d9] <qwindows.dll>
 21> QEventLoop::exec [0x7ffab1a2f64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7ffab1a32164] <Qt5Core.dll>
 23> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6205f5219] <OpenToonz.exe>
 24> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff620a1eab7] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff620a1e092] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7ffb12e17344] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7ffb132226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information in the report to move forward.
@tvortsa Recommend joining one of the Opentoonz discords where others can help you troubleshoot the issue you are experiencing.
