### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by eremitad** [opentoonz/opentoonz#5157]
### Description

The program crashed and I can't open my scenes anymore

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-11-03 19:14:18
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 22.4.0
CPU Threads: 8

GPU Vendor: Apple
GPU Model: Apple M1 Pro
GPU Version: 2.1 Metal - 83.1

Crash File: /Users/sarapelagalli/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20231103-191418.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: peter 1
Scene Name: 
Project Path: /Applications/OpenToonz/OpenToonz_stuff/projects/peter 1/peter 1_otprj.xml
Scene Path: 

==== Backtrace ====
  1> 3   ???                                 0x000000010e69a000 0x0 + 4536770560
  2> 4   libtnzcore.dylib                    0x000000010a923d48 _ZN6TLevel8setFrameERK8TFrameIdRK14TSmartPointerTI6TImageE + 72
  3> 5   libimage.dylib                      0x000000010b27704e _ZN15TLevelReaderPli8loadInfoEv + 286
  4> 6   libtoonzlib.dylib                   0x000000010b7e0ca4 _ZN15TXshSimpleLevel4loadEv + 1540
  5> 7   libtoonzlib.dylib                   0x000000010b77b907 _ZN10ToonzScene13loadResourcesEb + 615
  6> 8   libtoonzlib.dylib                   0x000000010b77b562 _ZN10ToonzScene4loadERK9TFilePathb + 34
  7> 9   OpenToonz                           0x000000010049641a _ZN5IoCmd9loadSceneERK9TFilePathbb + 4106
  8> 10  OpenToonz                           0x0000000100425903 _ZN12StartupPopup22onExistingSceneClickedEi + 307
  9> 11  QtCore                              0x0000000112d65bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 10> 12  OpenToonz                           0x00000001006dd83b _ZN17StartupScenesList11itemClickedEi + 59
 11> 13  QtCore                              0x0000000112d65bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 12> 14  QtWidgets                           0x0000000110551d05 _ZN11QListWidget5eventEP6QEvent + 2165
 13> 15  QtCore                              0x0000000112d65bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 14> 16  QtWidgets                           0x0000000110504ecf _ZN17QAbstractItemView17mouseReleaseEventEP11QMouseEvent + 847
 15> 17  QtWidgets                           0x000000011053b49a _ZN9QListView17mouseReleaseEventEP11QMouseEvent + 26
 16> 18  QtWidgets                           0x00000001102d1a97 _ZN7QWidget5eventEP6QEvent + 439
 17> 19  QtWidgets                           0x0000000110379a8b _ZN6QFrame5eventEP6QEvent + 43
 18> 20  QtWidgets                           0x0000000110503ba9 _ZN17QAbstractItemView13viewportEventEP6QEvent + 1417
 19> 21  QtCore                              0x0000000112d33a99 _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent + 217
 20> 22  QtWidgets                           0x0000000110298518 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 248
 21> 23  QtWidgets                           0x000000011029b424 _ZN12QApplication6notifyEP7QObjectP6QEvent + 7428
 22> 24  QtCore                              0x0000000112d337f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 23> 25  QtWidgets                           0x0000000110298e57 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 903
 24> 26  QtWidgets                           0x00000001102f0b07 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 10951
 25> 27  QtWidgets                           0x00000001102ef23e _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4606
 26> 28  QtWidgets                           0x000000011029852d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 27> 29  QtWidgets                           0x00000001102998f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 28> 30  QtCore                              0x0000000112d337f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 29> 31  QtGui                               0x0000000111689811 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 3489
 30> 32  QtGui                               0x000000011166e7eb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 219
 31> 33  libqcocoa.dylib                     0x000000012089ca58 qt_plugin_instance + 199592
 32> 34  CoreFoundation                      0x00007ff810412a36 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 33> 35  CoreFoundation                      0x00007ff8104129d9 __CFRunLoopDoSource0 + 157
 34> 36  CoreFoundation                      0x00007ff8104127b6 __CFRunLoopDoSources0 + 217
 35> 37  CoreFoundation                      0x00007ff81041143a __CFRunLoopRun + 916
 36> 38  CoreFoundation                      0x00007ff810410a4c CFRunLoopRunSpecific + 560
 37> 39  HIToolbox                           0x00007ff81a342fcd RunCurrentEventLoopInMode + 292
 38> 40  HIToolbox                           0x00007ff81a342c14 ReceiveNextEventCommon + 199
 39> 41  HIToolbox                           0x00007ff81a342b38 _BlockUntilNextEventMatchingListInModeWithFilter + 64
 40> 42  AppKit                              0x00007ff8134027a0 _DPSNextEvent + 858
 41>  42> sh: addr2line: command not found
 43> sh: addr2line: command not found
 44> sh: addr2line: command not found
 45> 47  AppKit                              0x00007ff81369cd53 _NSTryRunModal + 100
 46> sh: addr2line: command not found
 47> 49  libqcocoa.dylib                     0x000000012089b06a qt_plugin_instance + 192954
 48> 50  QtCore                              0x0000000112d2f97f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 49> 51  QtCore                              0x0000000112d33d82 _ZN16QCoreApplication4execEv + 130
 50> 52  OpenToonz                           0x000000010018ee07 main + 16487
 51> 53  dyld                                0x0000000200cf641f start + 1903
==== End ====

### OpenToonz Version

1.7

### Operating System

macOS

### GPU

Other

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information in the report to move forward.
@eremitad I will recommend you join an Opentoonz discord where others can help you troubleshoot your current issue.
