### ISSUE TITLE
Incomplete Report

### ISSUE THREAD

**Issue by BALEVS1989** [opentoonz/opentoonz#5160]
### Ask a question related to OpenToonz

open toonz 1.7.1 crash when wifi on my computer

**Comment by BALEVS1989** [comment]
open toonz 1.7.1 crash when wifi on my computer

**Comment by RodneyBaker** [comment]
Will likely close this as not having enough actionable information to move forward.
The addition of the word 'wifi' does suggest a way forward however.

@BALEVS1989 I will recommend you join one of the Opentoonz discords where others can help you troubleshoot the issue you are experiencing.

**Comment by RodneyBaker** [comment]
Closing as not having sufficient information in the report to properly assess the problem.
