### ISSUE TITLE
Incomplete Report

### ISSUE THREAD

**Issue by madavilar** [opentoonz/opentoonz#5161]
### Description

OpenToonz crashes when starting up 

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-05 21:02:58
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 16

Crash File: C:\Users\Maria Angela\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231105-210258.log
Mini Dump File: C:\Users\Maria Angela\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231105-210258.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\msvcp_win.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\shcore.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\Windows\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1c83a5d7cffd7bff\nvoglv64.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\hapcodec.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffab1a68b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffab1a412d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffab1a90ebe] <ntdll.dll>
  4> IsBadWritePtr [0x7ffab0525c09] <KERNEL32.DLL>
  5> DriverProc [0x22c90b767c9] <hapcodec.dll>
  6> DriverProc [0x22c90b76036] <hapcodec.dll>
  7> DriverProc [0x22c90b75eeb] <hapcodec.dll>
  8> DrvGetModuleHandle [0x7ffaa0484941] <winmmbase.dll>
  9> CloseDriver [0x7ffaa04834d8] <winmmbase.dll>
 10> ICClose [0x7ffa96293023] <MSVFW32.dll>
 11> TSmartPointerT<TXshColumn>::operator> [0x7ffa8a4f746e] <image.dll>
 12> TSmartPointerT<TXshColumn>::operator> [0x7ffa8a4f4de0] <image.dll>
 13> initImageIo [0x7ffa8a497ace] <image.dll>
 14> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff798c80dae] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff798c82d41] <OpenToonz.exe>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7990aeab7] <OpenToonz.exe>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7990ae092] <OpenToonz.exe>
 18> BaseThreadInitThunk [0x7ffab04d7344] <KERNEL32.DLL>
 19> RtlUserThreadStart [0x7ffab1a426b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hmmm... perhaps another codec issue...

**Comment by RodneyBaker** [comment]
Closing as not having sufficient information in the report to properly assess the problem.
