### ISSUE TITLE
Exception access violation crash error 👇 screenshot added 

### ISSUE THREAD

**Issue by zombade** [opentoonz/opentoonz#5166]
![Uploading IMG_20231107_154931748.jpg…]()

**Comment by zombade** [comment]
Oh thanks you please suggested me any solution regarding to this error

**Comment by RodneyBaker** [comment]
Right now we have no idea what you were doing at the time you crashed so there isn't much we can do except perhaps suggest reinstalling Opentoonz.  

You should consider joining one of the Opentoonz discords (chat rooms) where others can help troubleshoot.
There are even others there that speak many different languages.

Here's an invitation if you are interested:  https://discord.gg/EkDrDzPqz2

**Comment by zombade** [comment]
Thanks for the tip!
