### ISSUE TITLE
possible codec issue on Mac

### ISSUE THREAD

**Issue by Cris80001** [opentoonz/opentoonz#5167]
### Description

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-11-10 14:31:04
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 23.1.0
CPU Threads: 8

Crash File: /Users/crisLibrary/Application Support/OpenToonz/OpenToonz/crash/Crash-20231110-143104.log

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   libsystem_c.dylib                   0x00007ff800a73a49 abort + 126
  3> 5   libc++abi.dylib                     0x00007ff800b0dc72 abort_message + 241
  4> 6   libc++abi.dylib                     0x00007ff800affe1a _ZL28demangling_terminate_handlerv + 266
  5> 7   libobjc.A.dylib                     0x00007ff8007a0673 _ZL15_objc_terminatev + 104
  6> 8   libc++abi.dylib                     0x00007ff800b0d0cb _ZSt11__terminatePFvvE + 6
  7> 9   libc++abi.dylib                     0x00007ff800b0fa97 __cxa_get_exception_ptr + 0
  8> 10  libc++abi.dylib                     0x00007ff800b0fa5e _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
  9> 11  libtnzcore.dylib                    0x000000010cb6def2 _ZN7TSystem5mkDirERK9TFilePath + 1266
 10> 12  libtnzcore.dylib                    0x000000010cb612be _ZN11TImageCache10setRootDirERK9TFilePath + 270
 11> 13  OpenToonz                           0x000000010208bb8c main + 7660
 12> 14  dyld                                0x0000000202ae03a6 start + 1942
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

macOS

### GPU

Other

### Graphics Tablet

Other

**Comment by RodneyBaker** [comment]
Sorry to hear of the problem @Cris80001
Please provide additional information and we'll be glad to look into the issue.

**Comment by RodneyBaker** [comment]
Will close as likely resolved and/or abandoned.
@Cris80001 Please let us know if you are still experiencing this problem.
