### ISSUE TITLE
Another Logitech webcam driver crash

### ISSUE THREAD

**Issue by RD64TAlpha** [opentoonz/opentoonz#5169]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-12 18:44:01
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

Crash File: C:\Users\John De Cunha\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231112-184401.log
Mini Dump File: C:\Users\John De Cunha\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231112-184401.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\SYSTEM32\apphelp.dll
C:\windows\System32\USER32.dll
C:\windows\System32\win32u.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\gdi32full.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\ucrtbase.dll
C:\windows\System32\SHELL32.dll
C:\windows\System32\ole32.dll
C:\windows\System32\RPCRT4.dll
C:\windows\System32\combase.dll
C:\windows\System32\OLEAUT32.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\msvcrt.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\sechost.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\windows\System32\SETUPAPI.dll
C:\windows\System32\cfgmgr32.dll
C:\windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\windows\System32\COMDLG32.dll
C:\windows\System32\shcore.dll
C:\windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\windows\SYSTEM32\MPR.dll
C:\windows\SYSTEM32\GLU32.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\windows\System32\CRYPT32.dll
C:\windows\SYSTEM32\MFPlat.DLL
C:\windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
C:\windows\SYSTEM32\WINMM.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\windows\SYSTEM32\VERSION.dll
C:\windows\SYSTEM32\USERENV.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\windows\SYSTEM32\DNSAPI.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\windows\SYSTEM32\d3d11.dll
C:\windows\SYSTEM32\dxgi.dll
C:\windows\SYSTEM32\winmmbase.dll
C:\windows\SYSTEM32\NETUTILS.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\SYSTEM32\ksuser.dll
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\Wldp.dll
C:\windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\System32\CoreMessaging.dll
C:\windows\System32\CoreUIComponents.dll
C:\windows\SYSTEM32\ntmarta.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\system32\Oleacc.dll
C:\windows\system32\UIAutomationCore.dll
C:\windows\SYSTEM32\PROPSYS.dll
C:\windows\System32\clbcatq.dll
C:\windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_518f2921ba495409\ig9icd64.dll
C:\windows\SYSTEM32\dxcore.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_518f2921ba495409\igc64.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\dcomp.dll
C:\windows\system32\twinapi.appcore.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_518f2921ba495409\igdgmm64.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff8bb988b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8bb9612d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff8bb9b0ebe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ff88da22b9c] <MSVFW32.dll>
  6> ICOpen [0x7ff88da22d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff884376212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff884374478] <image.dll>
  9> initImageIo [0x7ff884317ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73f890dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73f892d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73fcbeab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff73fcbe092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff8b9d17344] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff8bb9626b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The good news...

A known problem with obsolete Logitech webcam driver located at C:\WINDOWS\SYSTEM32\lvcod64.dll is apparently at fault.
Rename or remove that file and Opentoonz should no longer have that problem.

REF: https://github.com/opentoonz/opentoonz/issues/5137 (and other similar reports)

**Comment by RD64TAlpha** [comment]
thanks

**Comment by RodneyBaker** [comment]
Closing as likely resolved by attending to the problematic Logitech webcam driver (lvcod64.dll).

**Comment by RodneyBaker** [comment]
Temporarily reopening so that other users with same problem can run across the fix.
