### ISSUE TITLE
Import and export backup setting

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#517]
If you want import your setting to other computer (or fresh OS), You should backup your setting manually. For example, for backup shortcut you need go to **OpenToonz 1.0 stuff/profiles/layouts/settings.[USER]** and save **shortcuts.ini** to your backup folder.

If posible export setting (Preferences, Shortcuts, Brush presets, etc) and import that to other computer, It will be usefull.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
