### ISSUE TITLE
what can i do?/que puedo hacer?

### ISSUE THREAD

**Issue by Aryyysss** [opentoonz/opentoonz#5170]
### Ask a question related to OpenToonz

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-12 16:18:43
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 2

Crash File: C:\Users\aryah\AppData\Local\OpenToonz\crash\Crash-20231112-161843.log
Mini Dump File: C:\Users\aryah\AppData\Local\OpenToonz\crash\Crash-20231112-161843.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0387389.inf_amd64_995be970e30b8c79\B385477\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0387389.inf_amd64_995be970e30b8c79\B385477\atio6axx.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\SYSTEM32\BCrypt.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffc21847aaa] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffc217ee232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffc2187348e] <ntdll.dll>
  4> IcdPresentBuffers [0x7ffb912b1cc2] <atio6axx.dll>
  5> IcdPresentBuffers [0x7ffb912b1b07] <atio6axx.dll>
  6> IcdPresentBuffers [0x7ffb912b1775] <atio6axx.dll>
  7> DrvSetCallbackProcs [0x7ffb912ab884] <atio6axx.dll>
  8> DrvSetCallbackProcs [0x7ffbf988c18c] <atig6pxx.dll>
  9> wglSwapMultipleBuffers [0x7ffbb7d83047] <OPENGL32.dll>
 10> wglSwapMultipleBuffers [0x7ffbb7d81b1f] <OPENGL32.dll>
 11> wglUseFontBitmapsW [0x7ffbb7d854e4] <OPENGL32.dll>
 12> wglGetPixelFormat [0x7ffbb7da163a] <OPENGL32.dll>
 13> wglDescribePixelFormat [0x7ffbb7da13d9] <OPENGL32.dll>
 14> wglChoosePixelFormat [0x7ffbb7da1053] <OPENGL32.dll>
 15> ChoosePixelFormat [0x7ffc1f464113] <gdi32full.dll>
 16> 
 17> 
 18> 
 19> 
 20> 
 21> 
 22> DispatchMessageW [0x7ffc20788241] <USER32.dll>
 23> DispatchMessageW [0x7ffc20787efc] <USER32.dll>
 24> CallNextHookEx [0x7ffc2079522c] <USER32.dll>
 25> KiUserCallbackDispatcher [0x7ffc21873434] <ntdll.dll>
 26> NtUserCreateWindowEx [0x7ffc1f132294] <win32u.dll>
 27> CreateWindowExW [0x7ffc2077f6e0] <USER32.dll>
 28> CreateWindowExW [0x7ffc2077f3fc] <USER32.dll>
 29> CreateWindowExW [0x7ffc2077f242] <USER32.dll>
 30> 
 31> 
 32> 
 33> QWindowPrivate::create [0x7ffb5e6cb08d] <Qt5Gui.dll>
 34> QOffscreenSurface::create [0x7ffb5e6d136d] <Qt5Gui.dll>
 35> ShaderInterface::getDeclaration [0x7ffb81a12590] <tnzstdfx.dll>
 36> TFunctorInvoker::qt_static_metacall [0x7ffb5a1383e2] <tnzcore.dll>
 37> QObject::event [0x7ffb5e2a9991] <Qt5Core.dll>
 38> QApplicationPrivate::notify_helper [0x7ffb778355c0] <Qt5Widgets.dll>
 39> QApplication::notify [0x7ffb77834643] <Qt5Widgets.dll>
 40> QCoreApplication::notifyInternal2 [0x7ffb5e28318a] <Qt5Core.dll>
 41> QCoreApplicationPrivate::sendPostedEvents [0x7ffb5e284f25] <Qt5Core.dll>
 42> qt_plugin_query_metadata [0x7ffb818728ff] <qwindows.dll>
 43> QEventDispatcherWin32::processEvents [0x7ffb5e2cbcfa] <Qt5Core.dll>
 44> qt_plugin_query_metadata [0x7ffb818728d9] <qwindows.dll>
 45> QWidgetPrivate::show_helper [0x7ffb7786a4ae] <Qt5Widgets.dll>
 46> QWidgetPrivate::setVisible [0x7ffb778687b8] <Qt5Widgets.dll>
 47> QWidget::setVisible [0x7ffb7786855e] <Qt5Widgets.dll>
 48> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff775c22b71] <OpenToonz.exe>
 49> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77604eab7] <OpenToonz.exe>
 50> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77604e092] <OpenToonz.exe>
 51> BaseThreadInitThunk [0x7ffc20ea257d] <KERNEL32.DLL>
 52> RtlUserThreadStart [0x7ffc2182aa78] <ntdll.dll>
==== End ====

**Comment by DarrenTAnims** [comment]
What was you doing when the crash happened.
Can you give some details about your system? What have you done after installing? What's your computer setup?
Anything would help.

**Comment by RodneyBaker** [comment]
A (very) wild guess here...
Double/triple check your graphics card's driver to make sure it is up to date.
If up to date and there is still a problem... consider backing down one update to see if that remedies the problem.

Other than that due to lack of information contained in this report we can't offer much assistance.

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information to troubleshoot the problem.
@Aryyysss Please feel free to continue troubleshooting here in this report.
