### ISSUE TITLE
Report Date: 2023-11-16 18:35:32 Crash Reason: (SIGSEGV) Segmentation Fault

### ISSUE THREAD

**Issue by ArtEmpireIndustry** [opentoonz/opentoonz#5172]
OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2023-11-16 18:35:32
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 22.5.0
CPU Threads: 12

GPU Vendor: Apple
GPU Model: Apple M2 Max
GPU Version: 2.1 Metal - 83.1

Crash File: /Users/camdenbarbour/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20231116-183532.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: MDtD Act 1 30 fpm Duffle Bag Rev 1
Scene Name: Meet Your Duffle Bag 1
Project Path: /Applications/OpenToonz/OpenToonz_stuff/projects/MDtD Act 1 30 fpm Duffle Bag Rev 1/MDtD Act 1 30 fpm Duffle Bag Rev 1_otprj.xml
Scene Path: /Applications/OpenToonz/OpenToonz_stuff/projects/MDtD Act 1 30 fpm Duffle Bag Rev 1/scenes/Meet Your Duffle Bag 1.tnz

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   OpenToonz                           0x000000010511d2f1 _ZN9XsheetGUI8CellArea15mousePressEventEP11QMouseEvent + 3457
  3> 5   QtWidgets                           0x0000000115178a82 _ZN7QWidget5eventEP6QEvent + 418
  4> 6   OpenToonz                           0x0000000105122d87 _ZN9XsheetGUI8CellArea5eventEP6QEvent + 327
  5> 7   QtWidgets                           0x000000011513f52d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
  6> 8   QtWidgets                           0x0000000115142424 _ZN12QApplication6notifyEP7QObjectP6QEvent + 7428
  7> 9   QtCore                              0x0000000117bda7f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
  8> 10  QtWidgets                           0x000000011513fe57 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 903
  9> 11  QtWidgets                           0x0000000115197b07 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 10951
 10> 12  QtWidgets                           0x000000011519623e _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4606
 11> 13  QtWidgets                           0x000000011513f52d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 12> 14  QtWidgets                           0x00000001151408f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 13> 15  QtCore                              0x0000000117bda7f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 14> 16  QtGui                               0x0000000116530811 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 3489
 15> 17  QtGui                               0x00000001165157eb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 219
 16> 18  libqcocoa.dylib                     0x00000001256e0a58 qt_plugin_instance + 199592
 17> 19  CoreFoundation                      0x00007ff80668a906 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 18> 20  CoreFoundation                      0x00007ff80668a8a9 __CFRunLoopDoSource0 + 157
 19> 21  CoreFoundation                      0x00007ff80668a686 __CFRunLoopDoSources0 + 217
 20> 22  CoreFoundation                      0x00007ff80668930a __CFRunLoopRun + 916
 21> 23  CoreFoundation                      0x00007ff80668891c CFRunLoopRunSpecific + 560
 22> 24  HIToolbox                           0x00007ff8105ccdad RunCurrentEventLoopInMode + 292
 23> 25  HIToolbox                           0x00007ff8105cc9f4 ReceiveNextEventCommon + 199
 24> 26  HIToolbox                           0x00007ff8105cc918 _BlockUntilNextEventMatchingListInModeWithFilter + 64
 25> 27  AppKit                              0x00007ff80967c5d0 _DPSNextEvent + 858
 26>  27> sh: addr2line: command not found
 28> 30  libqcocoa.dylib                     0x00000001256df86c qt_plugin_instance + 195004
 29> 31  QtCore                              0x0000000117bd697f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 30> 32  QtCore                              0x0000000117bdad82 _ZN16QCoreApplication4execEv + 130
 31> 33  OpenToonz                           0x0000000105023e07 main + 16487
 32> 34  dyld                                0x0000000205d3041f start + 1903
==== End ====

**Comment by RodneyBaker** [comment]
Closing as lacking any information that can be used in helping to diagnose the problem.
