### ISSUE TITLE
idk how to fix

### ISSUE THREAD

**Issue by TENb00** [opentoonz/opentoonz#5174]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-17 22:46:22
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon R7 200 Series
GPU Version: 4.6.14830 Compatibility Profile Context 22.6.1 27.20.20913.2000

Crash File: C:\Users\user\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231117-224622.log
Mini Dump File: C:\Users\user\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231117-224622.dmp

Application Dir: D:/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: kabbb
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\kabbb.tnz

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
D:\OpenToonz\Qt5Xml.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
D:\OpenToonz\glut64.dll
C:\Windows\System32\SHLWAPI.dll
D:\OpenToonz\Qt5SerialPort.dll
D:\OpenToonz\EDSDK.dll
D:\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\bcrypt.dll
D:\OpenToonz\image.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\tnzcore.dll
D:\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
D:\OpenToonz\MSVCP140_1.dll
D:\OpenToonz\MSVCP140.dll
D:\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
D:\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\d3d11.dll
D:\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\dxgi.dll
D:\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
D:\OpenToonz\Qt5Svg.dll
D:\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libjson-c-2.dll
D:\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
D:\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\dwrite.dll
D:\OpenToonz\imageformats\qgif.dll
D:\OpenToonz\imageformats\qicns.dll
D:\OpenToonz\imageformats\qico.dll
D:\OpenToonz\imageformats\qjpeg.dll
D:\OpenToonz\imageformats\qsvg.dll
D:\OpenToonz\imageformats\qtga.dll
D:\OpenToonz\imageformats\qtiff.dll
D:\OpenToonz\imageformats\qwbmp.dll
D:\OpenToonz\imageformats\qwebp.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0382934.inf_amd64_cbf07db13ec1507d\B381983\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0382934.inf_amd64_cbf07db13ec1507d\B381983\atio6axx.dll
C:\Windows\SYSTEM32\dxva2.dll
C:\Windows\System32\DriverStore\FileRepository\u0382934.inf_amd64_cbf07db13ec1507d\B381983\atig6txx.dll
C:\Windows\SYSTEM32\atiadlxx.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\pdh.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
D:\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
D:\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\SYSTEM32\TextShaping.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\policymanager.dll
C:\Windows\SYSTEM32\msvcp110_win.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7fff16368b4c] <ntdll.dll>
  2> RtlRaiseException [0x7fff163412c6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff16390f0e] <ntdll.dll>
  4> QObject::qt_static_metacall [0x7ffec6471b2e] <Qt5Core.dll>
  5> TThread::Runnable::terminated [0x7ffec6147bc4] <tnzcore.dll>
  6> loadShaderInterfaces [0x7ffed0cd2d8f] <tnzstdfx.dll>
  7> TRenderer::nextRenderId [0x7ffefc7f2ee3] <tnzbase.dll>
  8> TThread::Runnable::qt_static_metacall [0x7ffec61478fa] <tnzcore.dll>
  9> QObject::event [0x7ffec6479991] <Qt5Core.dll>
 10> QApplicationPrivate::notify_helper [0x7ffed01e55c0] <Qt5Widgets.dll>
 11> QApplication::notify [0x7ffed01e4643] <Qt5Widgets.dll>
 12> QCoreApplication::notifyInternal2 [0x7ffec645318a] <Qt5Core.dll>
 13> QCoreApplicationPrivate::sendPostedEvents [0x7ffec6454f25] <Qt5Core.dll>
 14> qt_plugin_query_metadata [0x7ffef25328ff] <qwindows.dll>
 15> QEventDispatcherWin32::processEvents [0x7ffec649bcfa] <Qt5Core.dll>
 16> qt_plugin_query_metadata [0x7ffef25328d9] <qwindows.dll>
 17> QEventLoop::exec [0x7ffec644f64c] <Qt5Core.dll>
 18> QCoreApplication::exec [0x7ffec6452164] <Qt5Core.dll>
 19> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff77ce15219] <OpenToonz.exe>
 20> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77d23eab7] <OpenToonz.exe>
 21> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77d23e092] <OpenToonz.exe>
 22> BaseThreadInitThunk [0x7fff152c7614] <KERNEL32.DLL>
 23> RtlUserThreadStart [0x7fff163426a1] <ntdll.dll>
==== End ====
idk how to fix pls help

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as lacking any informaton that can be used to troubleshoot the problem.
