### ISSUE TITLE
uhhh crash thingy

### ISSUE THREAD

**Issue by alxer2** [opentoonz/opentoonz#5175]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-17 18:29:18
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

Crash File: C:\Users\shunya\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231117-182918.log
Mini Dump File: C:\Users\shunya\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231117-182918.dmp

### Steps to Reproduce

1. 
2. 

### Expected Behavior

open it up i guess

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-17 18:29:18
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

Crash File: C:\Users\shunya\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231117-182918.log
Mini Dump File: C:\Users\shunya\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231117-182918.dmp

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as lacking any information that can assist in determining the problem being experienced.
