### ISSUE TITLE
Camera Glitch on my Animatic

### ISSUE THREAD

**Issue by PolyStoryGuy** [opentoonz/opentoonz#5176]
### Description

OpenToonz 1.7.1  (Build Nov  3 2023)

Report Date: 2023-11-17 22:20:16
Crash Reason: (SIGSEGV) Segmentation Fault

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 21.6.0
CPU Threads: 4

GPU Vendor: Intel Inc.
GPU Model: Intel(R) Iris(TM) Graphics 6100
GPU Version: 2.1 INTEL-18.8.6

Crash File: /Users/User/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20231117-222016.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: Between The Pages
Scene Name: Sc_2_1_3
Project Path: /Applications/OpenToonz/OpenToonz_stuff/projects/Between The Pages/Between The Pages_otprj.xml
Scene Path: /Applications/OpenToonz/OpenToonz_stuff/projects/Between The Pages/scenes/Sc_2_1_3.tnz

==== Backtrace ====
  1> 3   ???                                 0x0000000000000000 0x0 + 0
  2> 4   libtoonzqt.dylib                    0x000000011120756a _ZN11StyleEditor8setStyleEP11TColorStyle + 202
  3> 5   libtoonzqt.dylib                    0x0000000111206718 _ZN11StyleEditor15onStyleSwitchedEv + 184
  4> 6   QtCore                              0x0000000114a97bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
  5> 7   libtoonzlib.dylib                   0x0000000110b1df20 _ZN14TPaletteHandle10setPaletteEP8TPalettei + 96
  6> 8   libtoonzlib.dylib                   0x0000000110b46ae2 _ZN17PaletteController17setCurrentPaletteEP14TPaletteHandle + 98
  7> 9   libtoonzlib.dylib                   0x0000000110b46b52 _ZN17PaletteController16editLevelPaletteEv + 18
  8> 10  OpenToonz                           0x000000010efc4a8d _ZN4TApp15onSceneSwitchedEv + 93
  9> 11  QtCore                              0x0000000114a97bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 10> 12  libtoonzlib.dylib                   0x0000000110b1e6fe _ZN12TSceneHandle8setSceneEP10ToonzScene + 46
 11> 13  OpenToonz                           0x000000010f2671f7 _ZN5IoCmd9loadSceneERK9TFilePathbb + 4887
 12> 14  OpenToonz                           0x000000010f1f4da3 _ZN12StartupPopup22onExistingSceneClickedEi + 307
 13> 15  QtCore                              0x0000000114a97bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 14> 16  OpenToonz                           0x000000010f4b1d0b _ZN17StartupScenesList11itemClickedEi + 59
 15> 17  QtCore                              0x0000000114a97bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 16> 18  QtWidgets                           0x000000011335fd05 _ZN11QListWidget5eventEP6QEvent + 2165
 17> 19  QtCore                              0x0000000114a97bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 18> 20  QtWidgets                           0x0000000113312ecf _ZN17QAbstractItemView17mouseReleaseEventEP11QMouseEvent + 847
 19> 21  QtWidgets                           0x000000011334949a _ZN9QListView17mouseReleaseEventEP11QMouseEvent + 26
 20> 22  QtWidgets                           0x00000001130dfa97 _ZN7QWidget5eventEP6QEvent + 439
 21> 23  QtWidgets                           0x0000000113187a8b _ZN6QFrame5eventEP6QEvent + 43
 22> 24  QtWidgets                           0x0000000113311ba9 _ZN17QAbstractItemView13viewportEventEP6QEvent + 1417
 23> 25  QtCore                              0x0000000114a65a99 _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent + 217
 24> 26  QtWidgets                           0x00000001130a6518 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 248
 25> 27  QtWidgets                           0x00000001130a9424 _ZN12QApplication6notifyEP7QObjectP6QEvent + 7428
 26> 28  QtCore                              0x0000000114a657f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 27> 29  QtWidgets                           0x00000001130a6e57 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb + 903
 28> 30  QtWidgets                           0x00000001130feb07 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 10951
 29> 31  QtWidgets                           0x00000001130fd23e _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4606
 30> 32  QtWidgets                           0x00000001130a652d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 31> 33  QtWidgets                           0x00000001130a78f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 32> 34  QtCore                              0x0000000114a657f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 33> 35  QtGui                               0x0000000113c86811 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 3489
 34> 36  QtGui                               0x0000000113c6b7eb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 219
 35> 37  libqcocoa.dylib                     0x0000000119f5ba58 qt_plugin_instance + 199592
 36> 38  CoreFoundation                      0x00007ff8048440ab __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 37> 39  CoreFoundation                      0x00007ff804844013 __CFRunLoopDoSource0 + 180
 38> 40  CoreFoundation                      0x00007ff804843d8d __CFRunLoopDoSources0 + 242
 39> 41  CoreFoundation                      0x00007ff8048427a8 __CFRunLoopRun + 892
 40> 42  CoreFoundation                      0x00007ff804841d6c CFRunLoopRunSpecific + 562
 41> 43  HIToolbox                           0x00007ff80d4ef5e6 RunCurrentEventLoopInMode + 292
 42> 44  HIToolbox                           0x00007ff80d4ef213 ReceiveNextEventCommon + 283
 43> 45  HIToolbox                           0x00007ff80d4ef0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
 44> 46  AppKit                              0x00007ff80727cf6d _DPSNextEvent + 927
 45>  46> sh: addr2line: command not found
 47> sh: addr2line: command not found
 48> sh: addr2line: command not found
 49> 51  AppKit                              0x00007ff80752c77e _NSTryRunModal + 100
 50> sh: addr2line: command not found
 51> 53  libqcocoa.dylib                     0x0000000119f5a06a qt_plugin_instance + 192954
 52> 54  QtCore                              0x0000000114a6197f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 53> 55  QtCore                              0x0000000114a65d82 _ZN16QCoreApplication4execEv + 130
 54> 56  OpenToonz                           0x000000010ef57d61 main + 15553
 55> 57  dyld                                0x000000011bb8352e start + 462
==== End ====

Dear OpenToonz Crew,

Why did my OpenToonz camera glitch on me when I open all of a sudden? At that time, I wanted to analyze my length of timing of my story sketches. Please fix my camera right away.

Polyvios Christoforos
Polyspictures1991@gmail.com

### Steps to Reproduce

1. Get to the Scene_2_1_3 for the animation camera.
2. Reset the camera.

### Expected Behavior

In this particular issue, I was trying to get my camera back to normal.

See?

![Screen Shot 2023-11-17 at 10 26 13 PM](https://github.com/opentoonz/opentoonz/assets/74742318/59ce2380-d421-4de1-a6ae-5dfb0c53ba96)

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Nov 3 2023

### Operating System

macOS

### GPU

Intel

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Do you mean the Field Guide/Grid overlay on top of your image?
Over to the right there is an icon/option to turn that on/off.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@PolyStoryGuy Please let us know if you are still experiencing this problem.
