### ISSUE TITLE
Changed crash reporting for shortcut keys

### ISSUE THREAD

**Issue by Crysta0w0** [opentoonz/opentoonz#5177]
### Description

OpenToonz 1.7.1  (Build Oct  4 2023)

Report Date: 2023-11-18 15:48:31
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19043
CPU Threads: 12

GPU Vendor: ATI Technologies Inc.
GPU Model: Radeon RX 580 Series
GPU Version: 4.6.0 Compatibility Profile Context 22.10.2.221017

Crash File: C:\Users\73666\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231118-154831.log
Mini Dump File: C:\Users\73666\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231118-154831.dmp

Application Dir: E:/opentoonz
Stuff Dir: D:\opentoonz

Project Name: aa_ep01_001
Scene Name: gif_20231118
Project Path: D:\Animate\AAA\aa_ep01_001\aa_ep01_001_otprj.xml
Scene Path: D:\Animate\AAA\aa_ep01_001\scenes\gif_20231118.tnz

==== Modules ====
E:\opentoonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
E:\opentoonz\Qt5Xml.dll
E:\opentoonz\Qt5PrintSupport.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\COMDLG32.dll
E:\opentoonz\glut64.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\shcore.dll
E:\opentoonz\Qt5SerialPort.dll
C:\Windows\System32\SHLWAPI.dll
E:\opentoonz\EDSDK.dll
E:\opentoonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\bcrypt.dll
E:\opentoonz\image.dll
E:\opentoonz\tfarm.dll
E:\opentoonz\tnzstdfx.dll
E:\opentoonz\tnztools.dll
E:\opentoonz\toonzqt.dll
E:\opentoonz\Qt5Widgets.dll
E:\opentoonz\Qt5Core.dll
E:\opentoonz\Qt5Gui.dll
E:\opentoonz\sound.dll
E:\opentoonz\Qt5Script.dll
E:\opentoonz\tnzext.dll
E:\opentoonz\toonzlib.dll
E:\opentoonz\tnzbase.dll
E:\opentoonz\opencv_world451.dll
E:\opentoonz\Qt5OpenGL.dll
E:\opentoonz\tnzcore.dll
E:\opentoonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
E:\opentoonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
E:\opentoonz\MSVCP140_1.dll
E:\opentoonz\MSVCP140.dll
E:\opentoonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
E:\opentoonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.844_none_423537bff6b9828c\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
E:\opentoonz\glew32.dll
E:\opentoonz\libmypaint-1-4-0.dll
E:\opentoonz\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
E:\opentoonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\MSACM32.dll
E:\opentoonz\libintl-8.dll
E:\opentoonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
E:\opentoonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
E:\opentoonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
E:\opentoonz\styles\qwindowsvistastyle.dll
E:\opentoonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\system32\SogouTSF.ime
C:\Windows\system32\MSIMG32.dll
C:\Windows\system32\SogouPY.ime
C:\Windows\SYSTEM32\OLEACC.dll
C:\Windows\SYSTEM32\WINHTTP.dll
D:\Ӧ������\SogouInput\Components\PicFace\1.1.0.2129\PicFace64.dll
C:\Windows\System32\PSAPI.DLL
D:\Ӧ������\SogouInput\13.10.0.8469\Resource.dll
C:\Windows\SYSTEM32\TextShaping.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0384626.inf_amd64_709232910597852f\B384589\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0384626.inf_amd64_709232910597852f\B384589\atio6axx.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
E:\opentoonz\imageformats\qgif.dll
E:\opentoonz\imageformats\qicns.dll
E:\opentoonz\imageformats\qico.dll
E:\opentoonz\imageformats\qjpeg.dll
E:\opentoonz\imageformats\qsvg.dll
E:\opentoonz\imageformats\qtga.dll
E:\opentoonz\imageformats\qtiff.dll
E:\opentoonz\imageformats\qwbmp.dll
E:\opentoonz\imageformats\qwebp.dll
E:\opentoonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
E:\opentoonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\system32\Ninput.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_ca00b6081b84eb1d\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd41388a4c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd41361276] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd413b0bae] <ntdll.dll>
  4> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff727048b69] <OpenToonz.exe>
  5> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff72702f93e] <OpenToonz.exe>
  6> QWidget::event [0x7ffd1465807c] <Qt5Widgets.dll>
  7> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff72702d2fb] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ffd146355c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffd146334e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffcfedb318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ffd146367c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ffd146809d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffd1467e96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffd146355c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffd14634643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffcfedb318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ffd13fe47c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ffd13fcf030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ffcfedfbcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ffcf96d28d9] <qwindows.dll>
 21> QEventLoop::exec [0x7ffcfedaf64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7ffcfedb2164] <Qt5Core.dll>
 23> TSmartPointerConstT<TXshSoundLevel>::~TSmartPointerConstT<TXshSoundLevel> [0x7ff726f85dc0] <OpenToonz.exe>
 24> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7273b58d7] <OpenToonz.exe>
 25> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7273b4eb2] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7ffd3f877034] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7ffd41362651] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as lacking any information that can be used to diagnose the problem.
