### ISSUE TITLE
cierre repentino

### ISSUE THREAD

**Issue by nataliabguih** [opentoonz/opentoonz#5179]
### Description

El programa se cierra solo y al momento de abrir de nuevo el programa, sale una ventana que informa sobre el cierre forzado de open toonz , no me permite seguir trabajando
. 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Realmente necesitamos más información para poder determinar la mejor manera de investigar. Por ahora, todo lo que podemos hacer es sugerirle que consulte otros informes de errores (cerrados) donde puede encontrar información relacionada con el problema que está experimentando.

Hay algunos problemas conocidos que ocurren con frecuencia durante el inicio y la mayoría de ellos pueden abordarse fácilmente con la información adecuada.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@nataliabguih Please let us know if you are still experiencing problems.
