### ISSUE TITLE
brush strokes becomes red even if have selected the black color

### ISSUE THREAD

**Issue by Rajkumar0swain** [opentoonz/opentoonz#5180]
### Description

brush strokes become red even if have selected the black colour. and also there is some glitch in undo after copying anything well I'm attaching the video of red stroke problem, right now I don't have the video of undo problem, but I will attach that soon
[2023-11-15 21-28-49.zip](https://github.com/opentoonz/opentoonz/files/13402632/2023-11-15.21-28-49.zip)

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### OpenToonz Version Information

latest 1.7.1

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Make sure you don't have one of the Checks turned on in the menu:

![image](https://github.com/opentoonz/opentoonz/assets/2576432/678b1a14-0385-4371-9f9b-3d1672ef5091)

**Comment by Rajkumar0swain** [comment]
it was just fixed but I don't know how and I did nothing; I just opened the obs to record and I have not turned any checks on
[2023-11-19 17-47-15.zip](https://github.com/opentoonz/opentoonz/files/13403123/2023-11-19.17-47-15.zip)

**Comment by Rajkumar0swain** [comment]
it happens sometimes when a new frame is created

**Comment by RodneyBaker** [comment]
Glad to hear the problem fixed itself.

There are a number of reasons why lines can inadvertantly be red.
The Checks are one (specifically Ink Check) but also any time we draw with a color style that is later removed this can happen as there is no color to reference so a red line appears until such a time as that color style position is filled again.  Other reasons for red lines exist but those perhaps are the most frequently encountered.

Another time lines can be red is when using Onion skin but that doesn't appear to be related to your case.
If using mypaint brushes in github action automated builds there has been an issue with some features not working fully.
In that case the only fix for now would be to use a different installer/build that references the required code.

Generally speaking, red is used as a color for error.
