### ISSUE TITLE
undo glitch after copying

### ISSUE THREAD

**Issue by Rajkumar0swain** [opentoonz/opentoonz#5183]
### Description

undo glitch after copying

https://github.com/opentoonz/opentoonz/assets/124340073/28ce873e-02a6-49a3-b1b4-ac1f99c856fe

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
Duplicate of #5182
