### ISSUE TITLE
 brush tool options - some inconsistent naming in raster levels - input boxes still some times too wide 

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#519]
toonz vector and raster levels - brush tool has it as "pressure:"
Ordinary raster level - its called "Pressure sensitivity:"

Also you have "Opacity:min: --- max:----"
Where as everywhere else it is "Opacity min" without the ":" 

@shun-iwasawa 
The input boxes still have inconsistent width in raster level brush tool options.
Also the input boxes everywhere are way too wide still- that space can be used for the sliders - it would be better for tablet users.

**Comment by blurymind** [comment]
here I am marking in yellow all the wasted space:
![wasted space](https://cloud.githubusercontent.com/assets/6495061/16321536/4fbe890c-3995-11e6-9381-7b83850f9caa.PNG)

**Comment by blurymind** [comment]
To be honest that floating point number some times even exceeds the size of the input box - it jumps up and down in digits as you move the slider. The truth is that nobody will care about such precision. 4-5 digits should be enough. And if you want to be precise, you can always manually enter a number in that box and read it in its entirety by copying it and pasting it elsewhere.

Having it so wide just for the off chance that someone will care to always see the 9 in 56.76589 is just crazy

**Comment by shun-iwasawa** [comment]
This issue seems to be duplicated of the issue #427 .
I already modified the tool option layout in the PR #443 and it is not merged yet.
Please note that the decimals displayed in the field are also optimized in #443 .

**Comment by blurymind** [comment]
Ah sorry. I thought it got merged. I am adding more observations. Thank you for the fixes

**Comment by turtletooth** [comment]
I fixed the inconsistencies you mentioned in #685

**Comment by blurymind** [comment]
Thank you! :)
