### ISSUE TITLE
Possible Driver/Codec Incompatibility

### ISSUE THREAD

**Issue by melancholy-kitchen** [opentoonz/opentoonz#5192]
### Description

Crashing on startup even after restarting computer — can't find logitech either

### Steps to Reproduce

1. Try to open app.
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-24 02:44:25
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 8

Crash File: C:\Users\6carb\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231124-024425.log
Mini Dump File: C:\Users\6carb\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231124-024425.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\System32\USER32.dll
C:\windows\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\msvcrt.dll
C:\windows\System32\gdi32full.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\sechost.dll
C:\windows\System32\ucrtbase.dll
C:\windows\System32\RPCRT4.dll
C:\windows\System32\SHELL32.dll
C:\windows\System32\combase.dll
C:\windows\System32\COMDLG32.dll
C:\windows\System32\ole32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\windows\System32\OLEAUT32.dll
C:\windows\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\windows\SYSTEM32\MPR.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\windows\SYSTEM32\GLU32.dll
C:\windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\windows\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\windows\SYSTEM32\MF.dll
C:\windows\SYSTEM32\WINMM.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\windows\SYSTEM32\VERSION.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\windows\SYSTEM32\USERENV.dll
C:\windows\SYSTEM32\dxgi.dll
C:\windows\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\windows\SYSTEM32\DNSAPI.dll
C:\windows\SYSTEM32\cfgmgr32.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\windows\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\windows\SYSTEM32\NETUTILS.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\SYSTEM32\profapi.dll
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\SYSTEM32\directxdatabasehelper.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\SYSTEM32\CoreMessaging.dll
C:\windows\SYSTEM32\CoreUIComponents.dll
C:\windows\system32\Oleacc.dll
C:\windows\system32\UIAutomationCore.dll
C:\windows\System32\clbcatq.dll
C:\windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igxelpicd64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igdml64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igdgmm64.dll
C:\windows\SYSTEM32\DEVOBJ.dll
C:\windows\System32\WINTRUST.dll
C:\windows\SYSTEM32\MSASN1.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_6e6a7f579616ad0a\igc64.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\twinapi.appcore.dll
C:\windows\system32\ApplicationTargetedFeatureDatabase.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\WINMMBASE.dll
C:\windows\SYSTEM32\hapcodec.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff9df3e7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff9df38e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff9df41340e] <ntdll.dll>
  4> IsBadWritePtr [0x7ff9dde77889] <KERNEL32.DLL>
  5> DriverProc [0x20bedfd67c9] <hapcodec.dll>
  6> DriverProc [0x20bedfd6036] <hapcodec.dll>
  7> DriverProc [0x20bedfd5eeb] <hapcodec.dll>
  8> DrvGetModuleHandle [0x7ff9b65b4976] <WINMMBASE.dll>
  9> CloseDriver [0x7ff9b65b3568] <WINMMBASE.dll>
 10> ICClose [0x7ff9bada2bf3] <MSVFW32.dll>
 11> TSmartPointerT<TXshColumn>::operator> [0x7ff9b9f9746e] <image.dll>
 12> TSmartPointerT<TXshColumn>::operator> [0x7ff9b9f94de0] <image.dll>
 13> initImageIo [0x7ff9b9f37ace] <image.dll>
 14> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff70f290dae] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff70f292d41] <OpenToonz.exe>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff70f6beab7] <OpenToonz.exe>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff70f6be092] <OpenToonz.exe>
 18> BaseThreadInitThunk [0x7ff9dde6257d] <KERNEL32.DLL>
 19> RtlUserThreadStart [0x7ff9df3caa58] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
You might investigate programs on your system that encode... audio(?)... using the HAP codec.
That appears to be highly prevalent in your crash report.

This can be associated with a missing or corrupt Avcodec.dll (driver).
You might first check your Recyle Bin to see if that file is present but not fully removed yet.
If still in the Recyle Bin you could restore it.

If not you may need to reinstall some drivers on your system.

**Comment by RodneyBaker** [comment]
No response from original reporter so will close as likely resolved and/or abandoned.
@melancholy-kitchen Please let us know if you are still experiencing problems.
