### ISSUE TITLE
Crash after 10 minutes of use

### ISSUE THREAD

**Issue by beginnerani12** [opentoonz/opentoonz#5193]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-27 01:41:09
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 16

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3070/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 546.01

Crash File: C:\Users\oggai\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231127-014109.log
Mini Dump File: C:\Users\oggai\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231127-014109.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: untitled23
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\Users\oggai\AppData\Local\OpenToonz\OpenToonz\cache\temp\untitled23\untitled23.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\shcore.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\wintrust.dll
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\msiltcfg.dll
C:\Windows\SYSTEM32\msi.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_677da8a9230cea15\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\gpapi.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_677da8a9230cea15\nvgpucomp64.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\nvspcap64.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffb10ca8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffb10c812d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffb10cd0ebe] <ntdll.dll>
  4> QObject::isWidgetType [0x7ffaa7149a74] <Qt5Core.dll>
  5> QWidgetPrivate::showChildren [0x7ffaac0e9f9d] <Qt5Widgets.dll>
  6> QWidgetPrivate::show_helper [0x7ffaac0ea2a4] <Qt5Widgets.dll>
  7> QWidgetPrivate::setVisible [0x7ffaac0e87b8] <Qt5Widgets.dll>
  8> QWidget::setVisible [0x7ffaac0e855e] <Qt5Widgets.dll>
  9> QWidgetPrivate::showChildren [0x7ffaac0ea0da] <Qt5Widgets.dll>
 10> QWidgetPrivate::show_helper [0x7ffaac0ea2a4] <Qt5Widgets.dll>
 11> QWidgetPrivate::setVisible [0x7ffaac0e87b8] <Qt5Widgets.dll>
 12> QWidget::setVisible [0x7ffaac0e855e] <Qt5Widgets.dll>
 13> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6fc0f4ce2] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fc51eab7] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6fc51e092] <OpenToonz.exe>
 16> BaseThreadInitThunk [0x7ffb102c7344] <KERNEL32.DLL>
 17> RtlUserThreadStart [0x7ffb10c826b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. when i try to open OpenTonnz
2. After use of 10 min or more

### Expected Behavior

to open

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by RodneyBaker** [comment]
Recommend uninstalling and then installing the latest nightly release to make sure the problem remains.

Nightly Releases:  https://github.com/opentoonz/opentoonz_nightlies/releases

Direct link to latest Windows nightly release:  

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_b7470844aec8f730d1e4bc5a841d86bd53ddee6c/OpenToonzSetup.exe

We don't have much information to go on.
It isn't clear from your report what you are doing during that 10 minutes of use.
Making sure you are using the latest release however at least will rule out some things.

**Comment by RodneyBaker** [comment]
@beginnerani12 We really need to know more about how you are using Opentoonz as that will lead to a better understanding of the problem you are experiencing.  For instance, are you using a particular level type (vector?) and in what ways are you saving your projects?  Doesn't clearing the cache via File > Clear Cache Folder help?

Any and all information you can provide will be better than just taking wild guesses so we eagerly await your response.

**Comment by RodneyBaker** [comment]
By chance do you have autosave turned on while experiencing this crashing problem?

**Comment by RodneyBaker** [comment]
Closing as lacking sufficient information required to troubleshoot.
