### ISSUE TITLE
Crash with Logitech webcam driver at C:\WINDOWS\SYSTEM32\lvcod64.dll

### ISSUE THREAD

**Issue by TJPPlanet** [opentoonz/opentoonz#5196]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-29 03:01:27
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 1903
OS Kernel: 10.0.18362
CPU Threads: 4

Crash File: C:\Users\reivax\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231129-030127.log
Mini Dump File: C:\Users\reivax\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231129-030127.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\System32\windows.storage.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\advapi32.dll
C:\WINDOWS\System32\profapi.dll
C:\WINDOWS\System32\powrprof.dll
C:\WINDOWS\System32\UMPDC.dll
C:\WINDOWS\System32\shlwapi.dll
C:\WINDOWS\System32\kernel.appcore.dll
C:\WINDOWS\System32\cryptsp.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\System32\MSASN1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.836_none_2a2600ea466b531c\COMCTL32.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\ig8icd64.dll
C:\WINDOWS\SYSTEM32\igdusc64.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\RMCLIENT.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlIsGenericTableEmpty [0x7ff9a2db85b6] <ntdll.dll>
  2> RtlRaiseException [0x7ff9a2daa056] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff9a2ddfe3e] <ntdll.dll>
  4> DriverProc [0x7f8411c9] <lvcod64.dll>
  5> ICSendMessage [0x7ff9746e292c] <MSVFW32.dll>
  6> ICOpen [0x7ff9746e2ac4] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff96dbb6212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff96dbb4478] <image.dll>
  9> initImageIo [0x7ff96db57ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7a57d0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7a57d2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a5bfeab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a5bfe092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff9a1e77bd4] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff9a2dace51] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 
Using Windows 10 OpenToonz simply wont opne?

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
More good news!

The Logitech webcam driver located at C:\WINDOWS\SYSTEM32\lvcod64.dll is the likely cause of this problem.
Renaming or deleting/removing the file should restore things to order.

REF:  #5194 (and others)

**Comment by RodneyBaker** [comment]
At least the good news is that your crash report should no longer have the lvcod64.dll listed in the report.  :)
(Note:  If it does then look for that file in other locations)

**Comment by TJPPlanet** [comment]
Hello Rodney,

The ivcod64.dll error is a serious bug issue that needs to be fixed.  You
cannot use a program if you CANNOT open it.  I will no longer be using
opentoonz switching to Blender.  I removed the dll files as instructed that
did not fix it.

Regards

Hector

**Comment by RodneyBaker** [comment]
Sorry to hear that Hector.
If you ever find yourself making the attempt again perhaps you can join us on discord where it will be easier to troubleshoot the problem.  There are just too many variables involved and not enough information in your report to make any reasonable guess as to what the problem might be.

We wish you much success to you in your endeavors.
