### ISSUE TITLE
Crash on Custom Built Windows System

### ISSUE THREAD

**Issue by whhatislove** [opentoonz/opentoonz#5197]
### Description

Opentoonz crashed after startup
i have no logitech camera by the way or anything else

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-30 00:24:49
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19042
CPU Threads: 8

Crash File: C:\Users\whatislove\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231130-002449.log
Mini Dump File: C:\Users\whatislove\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231130-002449.dmp

==== Modules ====
E:\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\System32\USER32.dll
E:\OpenToonz\Qt5Xml.dll
E:\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\win32u.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\COMDLG32.dll
E:\OpenToonz\glut64.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\shcore.dll
E:\OpenToonz\Qt5SerialPort.dll
E:\OpenToonz\EDSDK.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\OLEAUT32.dll
E:\OpenToonz\colorfx.dll
C:\Windows\System32\bcrypt.dll
E:\OpenToonz\image.dll
E:\OpenToonz\tnztools.dll
E:\OpenToonz\tnzstdfx.dll
E:\OpenToonz\tfarm.dll
E:\OpenToonz\Qt5Widgets.dll
E:\OpenToonz\Qt5Gui.dll
E:\OpenToonz\Qt5Core.dll
E:\OpenToonz\toonzqt.dll
E:\OpenToonz\sound.dll
E:\OpenToonz\toonzlib.dll
E:\OpenToonz\Qt5Script.dll
E:\OpenToonz\tnzext.dll
E:\OpenToonz\opencv_world451.dll
E:\OpenToonz\tnzbase.dll
E:\OpenToonz\tnzcore.dll
E:\OpenToonz\Qt5OpenGL.dll
E:\OpenToonz\Qt5Multimedia.dll
E:\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
E:\OpenToonz\MSVCP140.dll
E:\OpenToonz\MSVCP140_1.dll
E:\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
E:\OpenToonz\VCRUNTIME140_1.dll
E:\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
E:\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
E:\OpenToonz\Qt5Svg.dll
E:\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
E:\OpenToonz\libintl-8.dll
E:\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
E:\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
E:\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
E:\OpenToonz\styles\qwindowsvistastyle.dll
E:\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0397406.inf_amd64_327265d4e3c6acee\B397164\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0397406.inf_amd64_327265d4e3c6acee\B397164\atio6axx.dll
C:\Windows\SYSTEM32\amdihk64.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SysWOW64\tsccvid64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd471083dc] <ntdll.dll>
  2> RtlRaiseException [0x7ffd470db406] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd4712fe3e] <ntdll.dll>
  4> DriverProc [0x7f845def] <tsccvid64.dll>
  5> DriverProc [0x7f8416e6] <tsccvid64.dll>
  6> ICSendMessage [0x7ffce1202b9c] <MSVFW32.dll>
  7> ICClose [0x7ffce120300e] <MSVFW32.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ffce2b0746e] <image.dll>
  9> TSmartPointerT<TXshColumn>::operator> [0x7ffce2b04de0] <image.dll>
 10> initImageIo [0x7ffce2aa7ace] <image.dll>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7112c0dae] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7112c2d41] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7116eeab7] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7116ee092] <OpenToonz.exe>
 15> BaseThreadInitThunk [0x7ffd46bd7034] <KERNEL32.DLL>
 16> RtlUserThreadStart [0x7ffd470dd0d1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Please see #5196 and other reports related to logitech webcam driver.
In short, the file at C:\WINDOWS\SYSTEM32\lvcod64.dll is the source of your trouble.
Rename or remove that file and the problem should be resolved.

**Comment by whhatislove** [comment]
> Please see #5196 and other reports related to logitech webcam driver. In short, the file at C:\WINDOWS\SYSTEM32\lvcod64.dll is the source of your trouble. Rename or remove that file and the problem should be resolved.

I havent logitech driver on my pc

**Comment by RodneyBaker** [comment]
My appologies.  That was meant for another report.
The only advice I can give is to update to the latest nightly release.
Ideally, prior to installation you should first use the uninstaller in the Opentoonz program directory to remove the old installation but... you can always try installing over the top of your old install first to see if that works.

Other than that... not enough information is contained in your report to suggest much else.

**Comment by whhatislove** [comment]
I noticed that if i try to ignore error 2 times, then program starts
May be its unstable, but it works
And i also installed nghtly release, it doesnt work

**Comment by whhatislove** [comment]
> My appologies. That was meant for another report. The only advice I can give is to update to the latest nightly release. Ideally, prior to installation you should first use the uninstaller in the Opentoonz program directory to remove the old installation but... you can always try installing over the top of your old install first to see if that works.
> 
> Other than that... not enough information is contained in your report to suggest much else.

there is the video https://drive.google.com/file/d/1CRXwFUVIBCGqaQOh_WPnk96Bk3tTBvw7/view?usp=sharing

**Comment by whhatislove** [comment]
> My appologies. That was meant for another report. The only advice I can give is to update to the latest nightly release. Ideally, prior to installation you should first use the uninstaller in the Opentoonz program directory to remove the old installation but... you can always try installing over the top of your old install first to see if that works.
> 
> Other than that... not enough information is contained in your report to suggest much else.

there it is https://drive.google.com/file/d/1cqRqoWpXi7cPbG6BOLS8Ju3yL4kJnITZ/view?usp=sharing

**Comment by RodneyBaker** [comment]
Windows comes with its own antivirus program (Windows Defender).

**Comment by whhatislove** [comment]
Its custom build without defender and other things

пт, 1 дек. 2023 г., 02:03 Rodney ***@***.***>:

**Comment by RodneyBaker** [comment]
Oh, a custom windows build... that's good information to know.
That makes me lean even farther toward the problem being a missing driver.

**Comment by RodneyBaker** [comment]
The only thing I can recommend here is to install Opentoonz using the default settings.
The installation onto E:Drive should work but for troubleshooting please install on the C:drive.

**Comment by RodneyBaker** [comment]
Without knowing more about your custom Windows build there isn't a lot we can do at this point.
Do you have access to a standard Windows setup you can test against to make sure that is working as desired?

**Comment by RodneyBaker** [comment]
Closing as need more information to move forward and troubleshoot.
@whhatislove Please feel free to continue discussion here or start a new report as you see fit.
