### ISSUE TITLE
Crash when installed on D:drive

### ISSUE THREAD

**Issue by tarik010275** [opentoonz/opentoonz#5198]
### Ask a question related to OpenToonz

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-11-29 16:01:33
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 2

GPU Vendor: Intel
GPU Model: Intel(R) G41 Express Chipset
GPU Version: 2.1.0 - Build 8.15.10.2302

Crash File: C:\Users\PC\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231129-160133.log
Mini Dump File: C:\Users\PC\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231129-160133.dmp

Application Dir: D:/OpenToonz
Stuff Dir: D:\

Project Name: sandbox
Scene Name: untitled
Project Path: D:\sandbox\sandbox_otprj.xml
Scene Path: C:\Users\PC\AppData\Local\OpenToonz\OpenToonz\cache\temp\untitled\untitled.tnz

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\Program Files\Avast Software\Avast\aswhook.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\OpenToonz\Qt5Xml.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
D:\OpenToonz\glut64.dll
D:\OpenToonz\Qt5SerialPort.dll
D:\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
D:\OpenToonz\colorfx.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\OpenToonz\image.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\Qt5OpenGL.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
D:\OpenToonz\VCRUNTIME140.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
D:\OpenToonz\VCRUNTIME140_1.dll
D:\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
D:\OpenToonz\glew32.dll
D:\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
D:\OpenToonz\CONCRT140.dll
D:\OpenToonz\libmypaint-1-4-0.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libiconv-2.dll
D:\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\SYSTEM32\ig4icd64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
D:\OpenToonz\imageformats\qgif.dll
D:\OpenToonz\imageformats\qicns.dll
D:\OpenToonz\imageformats\qico.dll
D:\OpenToonz\imageformats\qjpeg.dll
D:\OpenToonz\imageformats\qsvg.dll
D:\OpenToonz\imageformats\qtga.dll
D:\OpenToonz\imageformats\qtiff.dll
D:\OpenToonz\imageformats\qwbmp.dll
D:\OpenToonz\imageformats\qwebp.dll
D:\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\igd10umd64.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd1a4e8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd1a4c12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd1a510ebe] <ntdll.dll>
  4> ShCompile [0x17c14a4e6af] <ig4icd64.dll>
  5> ShCompile [0x17c14a4fd69] <ig4icd64.dll>
  6> ShCompile [0x17c1499d95c] <ig4icd64.dll>
  7> ShCompile [0x17c1499dd18] <ig4icd64.dll>
  8> 
  9> QOpenGLWidget::qt_metacast [0x7ffcd7c54c19] <Qt5Widgets.dll>
 10> QOpenGLWidget::resizeEvent [0x7ffcd7c55019] <Qt5Widgets.dll>
 11> QWidget::event [0x7ffcd7c28508] <Qt5Widgets.dll>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a936942b] <OpenToonz.exe>
 13> QApplicationPrivate::notify_helper [0x7ffcd7c055c0] <Qt5Widgets.dll>
 14> QApplication::notify [0x7ffcd7c04643] <Qt5Widgets.dll>
 15> QCoreApplication::notifyInternal2 [0x7ffcd41e318a] <Qt5Core.dll>
 16> QWidgetPrivate::setGeometry_sys [0x7ffcd7c35193] <Qt5Widgets.dll>
 17> QWidget::setGeometry [0x7ffcd7c34a14] <Qt5Widgets.dll>
 18> QWidgetItem::setGeometry [0x7ffcd7c1eaa0] <Qt5Widgets.dll>
 19> QBoxLayout::setGeometry [0x7ffcd7c13e16] <Qt5Widgets.dll>
 20> QLayoutPrivate::doResize [0x7ffcd7c1aaad] <Qt5Widgets.dll>
 21> QApplicationPrivate::notify_helper [0x7ffcd7c055a0] <Qt5Widgets.dll>
 22> QApplication::notify [0x7ffcd7c04643] <Qt5Widgets.dll>
 23> QCoreApplication::notifyInternal2 [0x7ffcd41e318a] <Qt5Core.dll>
 24> QWidgetPrivate::setGeometry_sys [0x7ffcd7c35193] <Qt5Widgets.dll>
 25> QWidget::setGeometry [0x7ffcd7c34a14] <Qt5Widgets.dll>
 26> QWidgetItem::setGeometry [0x7ffcd7c1eaa0] <Qt5Widgets.dll>
 27> QGridLayout::count [0x7ffcd7c15fb5] <Qt5Widgets.dll>
 28> QGridLayout::setGeometry [0x7ffcd7c17460] <Qt5Widgets.dll>
 29> QBoxLayout::setGeometry [0x7ffcd7c13e16] <Qt5Widgets.dll>
 30> QLayoutPrivate::doResize [0x7ffcd7c1aaad] <Qt5Widgets.dll>
 31> QApplicationPrivate::notify_helper [0x7ffcd7c055a0] <Qt5Widgets.dll>
 32> QApplication::notify [0x7ffcd7c04643] <Qt5Widgets.dll>
 33> QCoreApplication::notifyInternal2 [0x7ffcd41e318a] <Qt5Core.dll>
 34> QWidgetPrivate::setGeometry_sys [0x7ffcd7c35193] <Qt5Widgets.dll>
 35> QWidget::setGeometry [0x7ffcd7c34a14] <Qt5Widgets.dll>
 36> QWidgetItem::setGeometry [0x7ffcd7c1eaa0] <Qt5Widgets.dll>
 37> QBoxLayout::setGeometry [0x7ffcd7c13e16] <Qt5Widgets.dll>
 38> QLayoutPrivate::doResize [0x7ffcd7c1aaad] <Qt5Widgets.dll>
 39> QApplicationPrivate::notify_helper [0x7ffcd7c055a0] <Qt5Widgets.dll>
 40> QApplication::notify [0x7ffcd7c04643] <Qt5Widgets.dll>
 41> QCoreApplication::notifyInternal2 [0x7ffcd41e318a] <Qt5Core.dll>
 42> QWidgetPrivate::setGeometry_sys [0x7ffcd7c35193] <Qt5Widgets.dll>
 43> QWidget::setGeometry [0x7ffcd7c34a14] <Qt5Widgets.dll>
 44> DockLayout::applyGeometry [0x7ffcd7240977] <toonzqt.dll>
 45> DockWidget::mouseDoubleClickEvent [0x7ffcd72489d7] <toonzqt.dll>
 46> QWidget::event [0x7ffcd7c28066] <Qt5Widgets.dll>
 47> QApplicationPrivate::notify_helper [0x7ffcd7c055c0] <Qt5Widgets.dll>
 48> QApplication::notify [0x7ffcd7c034e0] <Qt5Widgets.dll>
 49> QCoreApplication::notifyInternal2 [0x7ffcd41e318a] <Qt5Core.dll>
 50> QApplicationPrivate::sendMouseEvent [0x7ffcd7c067c5] <Qt5Widgets.dll>
 51> QDesktopWidget::workAreaResized [0x7ffcd7c509d2] <Qt5Widgets.dll>
 52> QDesktopWidget::workAreaResized [0x7ffcd7c4e96e] <Qt5Widgets.dll>
 53> QApplicationPrivate::notify_helper [0x7ffcd7c055c0] <Qt5Widgets.dll>
 54> QApplication::notify [0x7ffcd7c04643] <Qt5Widgets.dll>
 55> QCoreApplication::notifyInternal2 [0x7ffcd41e318a] <Qt5Core.dll>
 56> QGuiApplicationPrivate::processMouseEvent [0x7ffcd75b47c3] <Qt5Gui.dll>
 57> QWindowSystemInterface::sendWindowSystemEvents [0x7ffcd759f030] <Qt5Gui.dll>
 58> QEventDispatcherWin32::processEvents [0x7ffcd422bcfa] <Qt5Core.dll>
 59> qt_plugin_query_metadata [0x7ffcdf2d28d9] <qwindows.dll>
 60> QEventLoop::exec [0x7ffcd41df64c] <Qt5Core.dll>
 61> QCoreApplication::exec [0x7ffcd41e2164] <Qt5Core.dll>
 62> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7a9285219] <OpenToonz.exe>
 63> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a96aeab7] <OpenToonz.exe>
 64> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a96ae092] <OpenToonz.exe>
 65> BaseThreadInitThunk [0x7ffd19ed7344] <KERNEL32.DLL>
 66> RtlUserThreadStart [0x7ffd1a4c26b1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
@tarik010275 
Were you able to have success installing with default settings?

In the interim while we await an update on this report... here are some generic thoughts on the report that might assist others experiencing similar problems:

> Crash Details:
> Crash Reason: EXCEPTION_ACCESS_VIOLATION
> Application and Stuff Directory: D:/OpenToonz, D:\
> Project and Scene: sandbox project, untitled scene
> Crash and Mini Dump Files: Provided paths for log and dump files

> Modules Loaded:
> A list of DLLs and other modules loaded, including system libraries and OpenToonz-specific modules like Qt5Widgets.dll, toonzqt.dll, etc.

> Backtrace Analysis:
> The backtrace points to a series of calls involving Qt5Widgets (related to the UI), OpenGL (graphics rendering), and OpenToonz's own modules.
> Notably, there are calls to QOpenGLWidget, QWidget, and DockWidget from the Qt framework, suggesting the crash might be related to UI rendering or interaction.
> The crash involves ig4icd64.dll, which is part of the Intel graphics driver. This could indicate a graphics driver issue, especially considering the older GPU model.

> Potential Areas of Investigation:
> Graphics Driver Compatibility: The Intel G41 chipset is relatively old. Compatibility with newer software versions and OpenGL requirements should be checked.
> OpenGL Issues: Since OpenGL calls are involved, there might be issues related to graphics rendering.
> UI Components: The involvement of Qt widgets suggests the crash could be related to specific UI interactions or rendering issues.
> Memory Access Violation: The EXCEPTION_ACCESS_VIOLATION error indicates an illegal memory access, which could be due to a bug in the application or an incompatibility with the system environment.
> Recommendations:
> Update Graphics Driver: Ensure the graphics driver is up to date, or test with a more recent GPU if possible.
> Test on Different Hardware: Run the same version of OpenToonz on different hardware to see if the issue is reproducible.

s.
