### ISSUE TITLE
Crash Reason: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by akashsingh39970** [opentoonz/opentoonz#5199]
### Description

Crash Reason: EXCEPTION_ACCESS_VIOLATION

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![image](https://github.com/opentoonz/opentoonz/assets/104356287/39a4f9d7-dc2f-4d0d-9852-d2f2bfc075f9)
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-12-01 22:04:43
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 4000
GPU Version: 4.0.0 - Build 10.18.10.4358

Crash File: C:\Users\HP\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231201-220443.log
Mini Dump File: C:\Users\HP\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231201-220443.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: jujutsu spoof
Scene Name: sukanasc1
Project Path: C:\OpenToonz stuff\projects\jujutsu spoof\jujutsu spoof_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\jujutsu spoof\scenes\sukanasc1.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\SYSTEM32\ig7icd64.dll
C:\WINDOWS\SYSTEM32\igdusc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\igd10iumd64.dll
C:\WINDOWS\SYSTEM32\ncrypt.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\NTASN1.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3570_none_60bb2a3971f3e41a\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffdae648b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffdae6212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffdae670ebe] <ntdll.dll>
  4> PinchTool::getToolType [0x7ffd68823a57] <tnztools.dll>
  5> PinchTool::getToolType [0x7ffd68824f10] <tnztools.dll>
  6> PinchTool::getToolType [0x7ffd68828e07] <tnztools.dll>
  7> PinchTool::getToolType [0x7ffd68828cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7683ebec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7683ea7ee] <OpenToonz.exe>
 10> QWidget::event [0x7ffd61088092] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7683e942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ffd610655c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ffd610634e0] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ffd5e41318a] <Qt5Core.dll>
 15> QApplicationPrivate::sendMouseEvent [0x7ffd610667c5] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ffd610b09d2] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ffd610ae96e] <Qt5Widgets.dll>
 18> QApplicationPrivate::notify_helper [0x7ffd610655c0] <Qt5Widgets.dll>
 19> QApplication::notify [0x7ffd61064643] <Qt5Widgets.dll>
 20> QCoreApplication::notifyInternal2 [0x7ffd5e41318a] <Qt5Core.dll>
 21> QGuiApplicationPrivate::processMouseEvent [0x7ffd5e8547c3] <Qt5Gui.dll>
 22> QWindowSystemInterface::sendWindowSystemEvents [0x7ffd5e83f030] <Qt5Gui.dll>
 23> QEventDispatcherWin32::processEvents [0x7ffd5e45bcfa] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ffd648a28d9] <qwindows.dll>
 25> QEventLoop::exec [0x7ffd5e40f64c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x7ffd5e412164] <Qt5Core.dll>
 27> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff768305219] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76872eab7] <OpenToonz.exe>
 29> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76872e092] <OpenToonz.exe>
 30> BaseThreadInitThunk [0x7ffdadd37344] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7ffdae6226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

v1.7.1

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Will plan to close this as a report that lacks sufficient information to investigate further.
@akashsingh39970 If you can provide additional information that will be greatly appreciated.
