### ISSUE TITLE
bug regression (harlequin)- toggle link to studio palette is missing, there is no way to link a style to the studio palette

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#520]
It looks like every level in opentoonz has its own palette. It cant be instanced.

The only way I found to share a color palette between levels is to use the studio palette window to set my colors, then load my palette manually to every level that I want to use it.

Edit: I seem to have found a regression bug again.

Toonz harlequin allows you to link a style to the studio palette. This command has been removed in opentoonz.

**Comment by blurymind** [comment]
@shun-iwasawa  "Do you want to update all linked styles in current scene"
Does not seem to do anything in today's nightly build.

I am assuming that this is the feature that i am looking for

**Comment by blurymind** [comment]
Ok I actually found that there is a regression from toonz harlequin!
In harlequin you can right click on a style on the level palette and "toggle link to studio palette"

It gets a tiny link indicator in the white box like this:
![regressionpalette](https://cloud.githubusercontent.com/assets/6495061/16323884/604f7b8a-39a6-11e6-9dfe-6aebff4f1879.PNG)

When link is enabled every time you change the studio palette color and save the studio palette, opentoonz updates it on every level where the style is linked!

This feature seems to have been removed from opentoonz. In the right click menu there is only an option to "remove links" which actually is the equivalent of "remove refference to studio palette" command in toonz harlequin.

When you save the studio palette, it asks you if you want to update it on the levels, but saying yes to that does absolutely nothing as none of them are actually linked.

@shun-iwasawa this is on the latest nightly build

**Comment by blurymind** [comment]
"Get color from studio palette" also does absolutely nothing.
@shun-iwasawa 
The functionality to link/update a level palette style to a studio palette style is completely broken/missing.

In toonz harlequin all you need to share a style between levels is have them all linked to studio palette. Then in order to update a color on two levels, all you need is to change it in the studio palette and save the palette. In a single click it updates everywhere.
OT can not seem to be able to do that.

**Comment by turtletooth** [comment]
> "Get color from studio palette" also does absolutely nothing.

I was just playing with it.  It works if the studio palette has been saved after updating.  It is still a bunch of steps, but it does work.

**Comment by blurymind** [comment]
@turtletooth it doesnt work for me on the latest nightly. Btw the feature i am asking for here is the linking capability that has been lost. When you toggle it on in harlequin, saving the studio palette is the only thing that you need to do in order to update the color on all the levels that use it! With the get color from studio palette command you need to select each individual level with the color and apply the command. If you have 100 levels that means that a color change takes 4 steps per level= 400 clicks. Compare this to two clicks with the linking capability

**Comment by blurymind** [comment]
Not having color linking is a huge blow to productivity as it multiplies the time needed to change a color globally by the number of levels that color exists in.

It may not be a big deal for classical animation workflow, but for cut out stuff with many levels that is a huge problem.
The linking capability solved it by allowing you to keep colors in the levels palettes linked to colors in the studio palette. A global update to a color on all levels with that feature is then trivial.

**Comment by Rayek** [comment]
I agree with Blurymind - the linking of colours should be fixed.

**Comment by konero** [comment]
> **It may not be a big deal for classical animation workflow**

It's a big deal, it needs to be fixed.

Cheers. :+1:

**Comment by blurymind** [comment]
@turtletooth @shun-iwasawa The command seems to still be available in the source code:
https://github.com/opentoonz/opentoonz/search?utf8=%E2%9C%93&q=toggle+link+to+studio
But why did Dwango disable it?

**Comment by turtletooth** [comment]
How's this for a start?
https://youtu.be/_MqfWTXgI-4
I'm not done, but linking works now.

**Comment by turtletooth** [comment]
Is that folder in your picture just the save button?

**Comment by blurymind** [comment]
@turtletooth  You are a star! Yes indeed - it is the save button. Saving the studio palette triggers all the linked level styles to update.

**Comment by turtletooth** [comment]
PR #628

**Comment by turtletooth** [comment]
@blurymind Would you mind giving your opinion on the wording discussion in the PR?

**Comment by blurymind** [comment]
I did. Bug still there. @turtletooth thank you for giving it a try anyways :)

**Comment by blurymind** [comment]
@shun-iwasawa  why did ghibli introduce this regression in the first place?
Do you think it needs to be refactored or redesigned?

**Comment by shun-iwasawa** [comment]
@blurymind 
In Studio Ghibli, coloring characters was done in quite complex way as follows:
In pre-production process, basic colors were designed for major parts of each character. Such color charts were saved in the studio palette and linked & copied to each level palette of each scene.
However, we did not use the basic color as-is. Every colors were adjusted from the basic color in order to fit the scene's background. After adjusting all colors of the level, link to the studio palette was removed and the final color was fixed.

For such occasions, the studio palette was used as "starting point" of color designing and could not be the final color in our studio. Automatic link feature had a risk to overwrite the final color of each level, so we decided to hide this feature and use update command manually if we need to do so.

Anyway, I understood that this feature is demanded. I'll try to revert it.

**Comment by blurymind** [comment]
@shun-iwasawa Thank you for taking the time to explain.
It's always a pleasure to get a glimpse at the pipeline that studio Ghibli uses.
Apart of being very interesting, it is also educational. :)

I am very glad that OT is being so actively developed and look forward to every next update.
You, @turtletooth , @ideasman42  and the rest of the devs here have improved it tremendously since the first release!
