### ISSUE TITLE
drawing and animation option not showing in the front page

### ISSUE THREAD

**Issue by vikas-vish** [opentoonz/opentoonz#5210]
### Ask a question related to OpenToonz

I've downloaded Opentoonz but my drawings and animation option aren't being displayed on the scene.
![problem](https://github.com/opentoonz/opentoonz/assets/153287425/41340532-14ea-43d5-b4e8-2e4220e2ff83)

**Comment by RodneyBaker** [comment]
What you are seeing is the Studio Ghibli room setup as opposed to the default room set normally shown.
It isn't clear why this is the case for you but double check your Preferences to make sure it isn't set to Studio Ghibli rooms.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/40d83e33-f1c0-4e8e-9a0c-2d7c656695a3)

**Comment by vikas-vish** [comment]
It is showing Default

**Comment by vikas-vish** [comment]
it is set on default.

**Comment by RodneyBaker** [comment]
> it is set on default.

Then I'll recommend renaming your stuff directory and reinstalling Opentoonz as you appear to have a corrupted install.
Renaming the stuff directory ensures that all settings will be set to the defaults at installation.
In this way you can still easily find any old projects/scenes in the renamed stuff directory.

**Comment by vikas-vish** [comment]
Problem solved. Thank you so much To help me🙂

**Comment by vikas-vish** [comment]
sir, I am return facing same problem. i do same process but nothing is happen
plz help me as soon as possible

**Comment by RodneyBaker** [comment]
@vikas-vish  The same recommendation for you.
- Rename C:\Opentoonz stuff to something like C:\Opentoon stuff (old) or C;\Opentoonz stuff (20240216)
- Go to C:\Program Files\Opentoonz and look for the uninstall.exe file and run tht unintaller
- Now download and run the latest nightly release of Opentoonz
( For windows that will be this program:  https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_b9a43f42714ee033300d027c889551fd4125d41c/OpenToonzSetup.exe )
