### ISSUE TITLE
my computer short circuited and now i cant open scenes from my project

### ISSUE THREAD

**Issue by jwjssif** [opentoonz/opentoonz#5216]
### Ask a question related to OpenToonz

i had opentoonz open when it happened. ive tried re-installing the program, doesnt work. what can i do?

it goes not responding when i try to open any scene from any project

**Comment by jwjssif** [comment]
> If your computer indeed hard crashed due to some overarching force (like electric current) then you might need to not only reinstall but also to delete your "stuff" folder.
> 
> I think by default, on Windows, it's at C:\ Opentoonz \ Stuff
> 
> I think moving or renaming the stuff folder works, too. That said, I haven't used Windows in ages so maybe someone else can give you better suggestions.

yeah i got help on reddit and the solution was to save the Project folder, then delete the Stuff folder and reinstall and then re-import the Project folder. This made me only lose one scene

**Comment by RodneyBaker** [comment]
Thanks for the follow up @jwjssif 
Much appreciated.

(Sorry to hear that you lost even that one scene though!)

Will close this report but please open a new report for any additional issues you encounter.
And...  happy animating!
