### ISSUE TITLE
Fill tool lines dissapear

### ISSUE THREAD

**Issue by randomuser189** [opentoonz/opentoonz#5220]
### Description

Note: English isnt my first language so my grammatic is not the best. Hopefully you can still understand what im trying to explain.
So basically in my animation there are moving obstacles, I used the fill tool to fill them in then moved them frame by frame (by duplicating the frame) left by -2000 with the select tool. everthing was going well till I saved my project and opened it back up.
half of my frames werent filled in (I even rendered my project before i closed it and all seemed to be fine) . So I simply used the fill tool and filled all of the frames again. I saved and opened the project again and it still wasnt filled in. I did the same thin g again, but this time added a ramdom block at the end. the frames didnt fill in again but the block stayed filled. I then copy and pasted the object on different layer and nothing changed. Can someone help me?

### Screenshots, Video & Crash Logs

https://github.com/opentoonz/opentoonz/assets/147276032/0180e9f8-8177-488c-9b22-bc9dd3bdbee5

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by Mondaley** [comment]
Why didn't you use the animation tool? Making everything by hand takes a lot of time

Also, the vector layer is glitchy due to the Primary Vertex https://github.com/opentoonz/opentoonz_docs/issues/162. Every vector glitch is related to it and your case makes no exception.

**Comment by randomuser189** [comment]
> Why didn't you use the animation tool? Making everything by hand takes a lot of time
> 
> Also, the vector layer is glitchy due to the Primary Vertex [opentoonz/opentoonz_docs#162](https://github.com/opentoonz/opentoonz_docs/issues/162). Every vector glitch is related to it and your case makes no exception.

thank you so much for answering, I moved it frame by frame just incase i needed to move any objects.
https://github.com/opentoonz/opentoonz_docs/issues/162  this doc helped me solve the problem.
thank you once again
