### ISSUE TITLE
red frames (broken level)

### ISSUE THREAD

**Issue by randomuser189** [opentoonz/opentoonz#5223]
### Description

one of my level/coloums turned red (vector layer). I already tried using .bak file but it didnt work for me.

### Screenshots, Video & Crash Logs

![Screenshot 2023-12-17 212953](https://github.com/opentoonz/opentoonz/assets/147276032/aca06a91-49c7-49ae-80d7-c553f6773f4f)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Perhaps you can share the PLI vector level and some of it can be recovered?

You may want to do this via discord... a direct message... if you cannot share the file publicly for any reason.

We can troubleshoot but the back and forth will take more time via github than working through it via chat.
Having said that, if you can share the file(s) here we'll certainly take a look at them.

**Comment by RodneyBaker** [comment]
Can you share the backup of that file... or is that the backup?

The PLI vector file in question is corrupt and I'm not able to recover anything using standard methods.
If the other file is larger than 576kb that would be a good sign.

**Comment by randomuser189** [comment]
[CI_ottmp1.zip](https://github.com/opentoonz/opentoonz/files/13705057/CI_ottmp1.zip)
Sure, here it is

**Comment by RodneyBaker** [comment]
Unfortunately, that file appears to be corrupt also.

**Comment by randomuser189** [comment]
do you know how i can possibly get the corrupted files back?

**Comment by randomuser189** [comment]
damn......
Thank you so much for your help though!

**Comment by RodneyBaker** [comment]
Closing with hope for the future.  :)
Keep on animating @randomuser189!
