### ISSUE TITLE
Crashed Render 

### ISSUE THREAD

**Issue by Catrina-Brando** [opentoonz/opentoonz#5224]
### Description

Every time I try to render my animation it always stop at 1% and then it will load a few second and automatically exit the software by itself. It would help if you fixed this matter because it's so frustrating, especially for someone like me who has a deadline. Also, every time I'm going to draw something on my canvas there's always this sign that keeps on popping in telling me that my software crashed. 

### Steps to Reproduce

1.  
2. 

### Expected Behavior

I want it to  be fix

### Screenshots, Video & Crash Logs

![Screenshot (125)](https://github.com/opentoonz/opentoonz/assets/154100107/5c5b1426-56f5-480d-99d5-ad86834e1e78)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as a duplicate of #5225
