### ISSUE TITLE
How to remove the crashed 

### ISSUE THREAD

**Issue by Catrina-Brando** [opentoonz/opentoonz#5225]
### Ask a question related to OpenToonz

I'm having trouble rendering my animation since it always exits itself every time I'm trying to render my animation. and I keep on receiving this pop-up notification that my software has crashed and then again it will exit on its own. 
![Screenshot (125)](https://github.com/opentoonz/opentoonz/assets/154100107/388ddd16-40a6-4803-a602-7c0ff30256b3)

**Comment by RodneyBaker** [comment]
It isn't entirely clear how you are rendering.
Are you using Output Settings > Render
or are you using Fast Render to MP4?
Something else?

Perhaps try initially rendering to a PNG sequence or even single frame to make sure you can actually render frames sucessfully.

Knowing more about your process and scene will help tremendously in better understanding the problem.
