### ISSUE TITLE
Problems with import mp4 files

### ISSUE THREAD

**Issue by CT543** [opentoonz/opentoonz#5232]
### Ask a question related to OpenToonz

So i have this problem with mp4 files, they import in my scene as a single image. I already downloaded Ffmpeg, and linked it in OT, still every mp4 file loads like this.  In "load level" OT sees all mp4 (and webm) files as 1 frame too. Also this 1 frame isn't even seenable, when loaded
![Screenshot_13](https://github.com/opentoonz/opentoonz/assets/154539649/99332e64-9dc1-4061-a014-8ddc08d22ce7)

**Comment by RodneyBaker** [comment]
How are you naming these files?

If they are only numbers in your filenames or if the filename contains any special characters... try removing those.
If only numbers then OT likely thinks the file is one part of a sequence and therefore wouldn't see/list others.

Also, as a good check to see if FFMPEG is indeed set up correctly try rendering out to one of the FFMPEG supported formats such as GIF, MP4 etc. as that should confirm that.  If you have issues rendering image/sequences out then I'd investigate your FFMPEG setup/connection in Opentoonz.  If not familiar with rendering, that is via Output Settings.

The fact that OT only sees one frame suggests to me that FFMPEG is not set up correctly although MP4 files listed should not show any number for frames.

**Comment by CT543** [comment]
I tried rendering mp4, and it turned out ok. But renaming files didn't do the trick

**Comment by RodneyBaker** [comment]
If you re-import the successfully rendered files what happens?

**Comment by manongjohn** [comment]
Make sure `ffprobe` is installed also

**Comment by CT543** [comment]
> If you re-import the successfully rendered files what happens?
The same thing - it imports as 1 frame without any picture or sound

**Comment by RodneyBaker** [comment]
Please post a screeshot of your ffmpeg bin directory.
It should look somthing like this:

![image](https://github.com/opentoonz/opentoonz/assets/2576432/6f6c0bf6-515b-43f5-af6e-e15b2e0a01ef)

**Comment by CT543** [comment]
This is some screenshots of ffmpeg and mp4 files 
![Screenshot_14](https://github.com/opentoonz/opentoonz/assets/154539649/bb3bdb14-a2f6-4e2c-9998-224607d80dce)
![Screenshot_17](https://github.com/opentoonz/opentoonz/assets/154539649/7fb8cab6-909f-4d3a-837a-1c27f0e7bb9a)

![Screenshot_15](https://github.com/opentoonz/opentoonz/assets/154539649/981a103a-10d6-4151-964e-8624d2f3dd55)
![Screenshot_16](https://github.com/opentoonz/opentoonz/assets/154539649/85b4a926-9cbf-40fa-9c10-db8f5fb4d49a)

I followed this tutorial, while downloading ffmpeg
https://www.youtube.com/watch?v=y8OyTVpH3dI

**Comment by RodneyBaker** [comment]
You've only got one of the three files you should have in the ffmpeg/bin directory.
You are missing ffplay.exer and ffprobe.exe
