### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Nedugames** [opentoonz/opentoonz#5233]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-12-26 22:33:01
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 3000
GPU Version: 3.1.0 - Build 9.17.10.4459

Crash File: C:\Users\Ajiero\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231226-223301.log
Mini Dump File: C:\Users\Ajiero\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231226-223301.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\Users\Ajiero\Desktop\Resource Gallery\OpenToonz stuff

Project Name: Mr Ajiero (Animations)
Scene Name: Turn around
Project Path: C:\Users\Ajiero\Desktop\Resource Gallery\OpenToonz stuff\projects\Cast\scenes\Mr Ajiero (Animations)\Mr Ajiero (Animations)_otprj.xml
Scene Path: C:\Users\Ajiero\Desktop\Resource Gallery\OpenToonz stuff\projects\Cast\scenes\Mr Ajiero (Animations)\scenes\Turn around.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\SYSTEM32\ig4icd64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\igd10umd64.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\SYSTEM32\urlmon.dll
C:\WINDOWS\SYSTEM32\iertutil.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\msiltcfg.dll
C:\WINDOWS\SYSTEM32\msi.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\ActXPrxy.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd251e8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd251c12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd25210ebe] <ntdll.dll>
  4> StyleEditorGUI::ColorSlider::setColor [0x7ffcb1c2e237] <toonzqt.dll>
  5> StyleEditor::setStyle [0x7ffcb1c2f1aa] <toonzqt.dll>
  6> StyleEditor::onStyleSwitched [0x7ffcb1c2b8fe] <toonzqt.dll>
  7> StyleEditor::showEvent [0x7ffcb1c2f54a] <toonzqt.dll>
  8> QWidget::event [0x7ffcb2b3862b] <Qt5Widgets.dll>
  9> QApplicationPrivate::notify_helper [0x7ffcb2b155c0] <Qt5Widgets.dll>
 10> QApplication::notify [0x7ffcb2b14643] <Qt5Widgets.dll>
 11> QCoreApplication::notifyInternal2 [0x7ffcb208318a] <Qt5Core.dll>
 12> QWidgetPrivate::showChildren [0x7ffcb2b4a02b] <Qt5Widgets.dll>
 13> QWidgetPrivate::showChildren [0x7ffcb2b4a012] <Qt5Widgets.dll>
 14> QWidgetPrivate::showChildren [0x7ffcb2b4a012] <Qt5Widgets.dll>
 15> QWidgetPrivate::showChildren [0x7ffcb2b4a012] <Qt5Widgets.dll>
 16> QWidget::event [0x7ffcb2b386b9] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ffcb2b155c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffcb2b14643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffcb208318a] <Qt5Core.dll>
 20> QDesktopWidget::workAreaResized [0x7ffcb2b61823] <Qt5Widgets.dll>
 21> QDesktopWidget::workAreaResized [0x7ffcb2b5eb04] <Qt5Widgets.dll>
 22> QApplicationPrivate::notify_helper [0x7ffcb2b155c0] <Qt5Widgets.dll>
 23> QApplication::notify [0x7ffcb2b14643] <Qt5Widgets.dll>
 24> QCoreApplication::notifyInternal2 [0x7ffcb208318a] <Qt5Core.dll>
 25> QGuiApplicationPrivate::processWindowStateChangedEvent [0x7ffcb24c76c2] <Qt5Gui.dll>
 26> QWindowSystemInterface::sendWindowSystemEvents [0x7ffcb24af030] <Qt5Gui.dll>
 27> QWindowSystemInterface::flushWindowSystemEvents [0x7ffcb24ab92b] <Qt5Gui.dll>
 28> 
 29> 
 30> 
 31> CallWindowProcW [0x7ffd2350e858] <USER32.dll>
 32> CallWindowProcW [0x7ffd2350e4ee] <USER32.dll>
 33> glPushClientAttrib [0x7ffd0788f0f0] <OPENGL32.dll>
 34> CallWindowProcW [0x7ffd2350e858] <USER32.dll>
 35> DispatchMessageW [0x7ffd2350e3dc] <USER32.dll>
 36> SendMessageTimeoutW [0x7ffd23520c93] <USER32.dll>
 37> KiUserCallbackDispatcher [0x7ffd25210e64] <ntdll.dll>
 38> NtUserDispatchMessage [0x7ffd228f1704] <win32u.dll>
 39> DispatchMessageW [0x7ffd2350e2ea] <USER32.dll>
 40> QEventDispatcherWin32::processEvents [0x7ffcb20cc22c] <Qt5Core.dll>
 41> qt_plugin_query_metadata [0x7ffcaca928d9] <qwindows.dll>
 42> QEventLoop::exec [0x7ffcb207f64c] <Qt5Core.dll>
 43> QCoreApplication::exec [0x7ffcb2082164] <Qt5Core.dll>
 44> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff756655219] <OpenToonz.exe>
 45> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff756a7eab7] <OpenToonz.exe>
 46> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff756a7e092] <OpenToonz.exe>
 47> BaseThreadInitThunk [0x7ffd23ce7344] <KERNEL32.DLL>
 48> RtlUserThreadStart [0x7ffd251c26b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2023-12-26 22:33:01
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 3000
GPU Version: 3.1.0 - Build 9.17.10.4459

Crash File: C:\Users\Ajiero\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231226-223301.log
Mini Dump File: C:\Users\Ajiero\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231226-223301.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\Users\Ajiero\Desktop\Resource Gallery\OpenToonz stuff

Project Name: Mr Ajiero (Animations)
Scene Name: Turn around
Project Path: C:\Users\Ajiero\Desktop\Resource Gallery\OpenToonz stuff\projects\Cast\scenes\Mr Ajiero (Animations)\Mr Ajiero (Animations)_otprj.xml
Scene Path: C:\Users\Ajiero\Desktop\Resource Gallery\OpenToonz stuff\projects\Cast\scenes\Mr Ajiero (Animations)\scenes\Turn around.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\SYSTEM32\ig4icd64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\igd10umd64.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\SYSTEM32\urlmon.dll
C:\WINDOWS\SYSTEM32\iertutil.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\msiltcfg.dll
C:\WINDOWS\SYSTEM32\msi.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\ActXPrxy.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd251e8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd251c12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd25210ebe] <ntdll.dll>
  4> StyleEditorGUI::ColorSlider::setColor [0x7ffcb1c2e237] <toonzqt.dll>
  5> StyleEditor::setStyle [0x7ffcb1c2f1aa] <toonzqt.dll>
  6> StyleEditor::onStyleSwitched [0x7ffcb1c2b8fe] <toonzqt.dll>
  7> StyleEditor::showEvent [0x7ffcb1c2f54a] <toonzqt.dll>
  8> QWidget::event [0x7ffcb2b3862b] <Qt5Widgets.dll>
  9> QApplicationPrivate::notify_helper [0x7ffcb2b155c0] <Qt5Widgets.dll>
 10> QApplication::notify [0x7ffcb2b14643] <Qt5Widgets.dll>
 11> QCoreApplication::notifyInternal2 [0x7ffcb208318a] <Qt5Core.dll>
 12> QWidgetPrivate::showChildren [0x7ffcb2b4a02b] <Qt5Widgets.dll>
 13> QWidgetPrivate::showChildren [0x7ffcb2b4a012] <Qt5Widgets.dll>
 14> QWidgetPrivate::showChildren [0x7ffcb2b4a012] <Qt5Widgets.dll>
 15> QWidgetPrivate::showChildren [0x7ffcb2b4a012] <Qt5Widgets.dll>
 16> QWidget::event [0x7ffcb2b386b9] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ffcb2b155c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffcb2b14643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffcb208318a] <Qt5Core.dll>
 20> QDesktopWidget::workAreaResized [0x7ffcb2b61823] <Qt5Widgets.dll>
 21> QDesktopWidget::workAreaResized [0x7ffcb2b5eb04] <Qt5Widgets.dll>
 22> QApplicationPrivate::notify_helper [0x7ffcb2b155c0] <Qt5Widgets.dll>
 23> QApplication::notify [0x7ffcb2b14643] <Qt5Widgets.dll>
 24> QCoreApplication::notifyInternal2 [0x7ffcb208318a] <Qt5Core.dll>
 25> QGuiApplicationPrivate::processWindowStateChangedEvent [0x7ffcb24c76c2] <Qt5Gui.dll>
 26> QWindowSystemInterface::sendWindowSystemEvents [0x7ffcb24af030] <Qt5Gui.dll>
 27> QWindowSystemInterface::flushWindowSystemEvents [0x7ffcb24ab92b] <Qt5Gui.dll>
 28> 
 29> 
 30> 
 31> CallWindowProcW [0x7ffd2350e858] <USER32.dll>
 32> CallWindowProcW [0x7ffd2350e4ee] <USER32.dll>
 33> glPushClientAttrib [0x7ffd0788f0f0] <OPENGL32.dll>
 34> CallWindowProcW [0x7ffd2350e858] <USER32.dll>
 35> DispatchMessageW [0x7ffd2350e3dc] <USER32.dll>
 36> SendMessageTimeoutW [0x7ffd23520c93] <USER32.dll>
 37> KiUserCallbackDispatcher [0x7ffd25210e64] <ntdll.dll>
 38> NtUserDispatchMessage [0x7ffd228f1704] <win32u.dll>
 39> DispatchMessageW [0x7ffd2350e2ea] <USER32.dll>
 40> QEventDispatcherWin32::processEvents [0x7ffcb20cc22c] <Qt5Core.dll>
 41> qt_plugin_query_metadata [0x7ffcaca928d9] <qwindows.dll>
 42> QEventLoop::exec [0x7ffcb207f64c] <Qt5Core.dll>
 43> QCoreApplication::exec [0x7ffcb2082164] <Qt5Core.dll>
 44> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff756655219] <OpenToonz.exe>
 45> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff756a7eab7] <OpenToonz.exe>
 46> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff756a7e092] <OpenToonz.exe>
 47> BaseThreadInitThunk [0x7ffd23ce7344] <KERNEL32.DLL>
 48> RtlUserThreadStart [0x7ffd251c26b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by Mondaley** [comment]
At this rate, those ambiguous reports won't end...

For an accurate report, please be sure to provide specific details. For instance, in what circumstances did this crash happen? How to reproduce it? What was the last thing you did before the app stopped responding? Pictures. Videos. And so on...
