### ISSUE TITLE
1.7.1 Crashes on New Scene or Opening Empty Scene

### ISSUE THREAD

**Issue by Boshgoria** [opentoonz/opentoonz#5237]
### Description

Creating a new scene and opening the empty one results in an unexpected crash occurring (EXCEPTION_INIT_DIVIDE_BY_ZERO). This happens both while the FFmpeg directory is added in preferences or taken away. This issue persists for me on the latest nightly build (2023-12-10), after completely uninstalling/reinstalling, and restarting my computer.

### Steps to Reproduce

1. Create a new scene (Optional)
2. Open the new or empty scene

### Expected Behavior

Create a new scene with no issues

### Screenshots, Video & Crash Logs

[user directory modified to avoid posting my real name]
--------------------------------------------------------------

OpenToonz 1.7.1  (Build Dec  9 2023)

Report Date: 2023-12-28 22:56:45
Crash Reason: EXCEPTION_INT_DIVIDE_BY_ZERO

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 16

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics
GPU Version: 4.6.0 - Build 31.0.101.4502

Crash File: C:\Users\[User Directory]\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231228-225645.log
Mini Dump File: C:\Users\[User Directory]\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20231228-225645.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\Users\[User Directory]\Desktop\OpenToonz stuff

Project Name: Storytime
Scene Name: perspective2
Project Path: C:\Users\[User Directory]\Desktop\OpenToonz stuff\projects\Storytime\Storytime_otprj.xml
Scene Path: C:\Users\[User Directory]\Desktop\OpenToonz stuff\projects\Storytime\scenes\perspective2.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\windows\System32\win32u.dll
C:\windows\System32\COMDLG32.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\ucrtbase.dll
C:\windows\System32\combase.dll
C:\windows\System32\RPCRT4.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\shcore.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\gdi32full.dll
C:\windows\System32\SHLWAPI.dll
C:\windows\System32\msvcrt.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\SHELL32.dll
C:\windows\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\windows\System32\ole32.dll
C:\windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\windows\SYSTEM32\MPR.dll
C:\windows\SYSTEM32\GLU32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\windows\System32\CRYPT32.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\windows\SYSTEM32\MFPlat.DLL
C:\windows\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\windows\SYSTEM32\MF.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\windows\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\windows\SYSTEM32\dxgi.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\windows\SYSTEM32\d3d11.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\windows\SYSTEM32\USERENV.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\windows\SYSTEM32\DNSAPI.dll
C:\windows\SYSTEM32\cfgmgr32.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\windows\SYSTEM32\dxcore.dll
C:\windows\SYSTEM32\NETUTILS.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\SYSTEM32\profapi.dll
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\SYSTEM32\bcrypt.dll
C:\windows\SYSTEM32\DEVOBJ.dll
C:\windows\System32\WINTRUST.dll
C:\windows\SYSTEM32\MSASN1.dll
C:\windows\SYSTEM32\directxdatabasehelper.dll
C:\windows\system32\WRusr.dll
C:\windows\System32\PSAPI.DLL
C:\windows\SYSTEM32\MSIMG32.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\SYSTEM32\CoreMessaging.dll
C:\windows\SYSTEM32\CoreUIComponents.dll
C:\windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0fdf6ce291234272\igxelpicd64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0fdf6ce291234272\igdml64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0fdf6ce291234272\igdgmm64.dll
C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_0fdf6ce291234272\igc64.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\twinapi.appcore.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\windows\SYSTEM32\dhcpcsvc6.DLL
C:\windows\SYSTEM32\dhcpcsvc.DLL
C:\windows\System32\netprofm.dll
C:\windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\windows\SYSTEM32\MMDevAPI.DLL
C:\windows\SYSTEM32\wdmaud.drv
C:\windows\SYSTEM32\AVRT.dll
C:\windows\SYSTEM32\ksuser.dll
C:\windows\SYSTEM32\AUDIOSES.DLL
C:\windows\SYSTEM32\msacm32.drv
C:\windows\SYSTEM32\midimap.dll
C:\windows\SYSTEM32\PROPSYS.dll
C:\windows\SYSTEM32\LINKINFO.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\windows\system32\napinsp.dll
C:\windows\system32\pnrpnsp.dll
C:\windows\System32\winrnr.dll
C:\windows\system32\wshbth.dll
C:\windows\system32\nlansp_c.dll
C:\windows\System32\fwpuclnt.dll
C:\windows\system32\UIAutomationCore.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\windows\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff8bcae7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff8bca8e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff8bcb1340e] <ntdll.dll>
  4> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7653ea9aa] <OpenToonz.exe>
  5> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7653ed618] <OpenToonz.exe>
  6> QWidget::event [0x7ff865e484d1] <Qt5Widgets.dll>
  7> QApplicationPrivate::notify_helper [0x7ff865e255c0] <Qt5Widgets.dll>
  8> QApplication::notify [0x7ff865e24643] <Qt5Widgets.dll>
  9> QCoreApplication::notifyInternal2 [0x7ff862a3318a] <Qt5Core.dll>
 10> QWidgetPrivate::drawWidget [0x7ff865e47aeb] <Qt5Widgets.dll>
 11> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 12> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 13> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 14> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 15> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 16> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 17> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 18> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 19> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 20> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 21> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 22> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 23> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 24> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 25> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 26> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 27> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 28> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4d985] <Qt5Widgets.dll>
 29> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 30> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 31> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 32> QWidgetPrivate::paintSiblingsRecursive [0x7ff865e4da57] <Qt5Widgets.dll>
 33> QWidgetPrivate::drawWidget [0x7ff865e47c44] <Qt5Widgets.dll>
 34> QWidgetPrivate::moveRect [0x7ff865e30406] <Qt5Widgets.dll>
 35> QWidget::event [0x7ff865e4890f] <Qt5Widgets.dll>
 36> QApplicationPrivate::notify_helper [0x7ff865e255c0] <Qt5Widgets.dll>
 37> QApplication::notify [0x7ff865e24643] <Qt5Widgets.dll>
 38> QCoreApplication::notifyInternal2 [0x7ff862a3318a] <Qt5Core.dll>
 39> QCoreApplicationPrivate::sendPostedEvents [0x7ff862a34f25] <Qt5Core.dll>
 40> qt_plugin_query_metadata [0x7ff866c828ff] <qwindows.dll>
 41> QEventDispatcherWin32::processEvents [0x7ff862a7bcfa] <Qt5Core.dll>
 42> qt_plugin_query_metadata [0x7ff866c828d9] <qwindows.dll>
 43> StyleEditor::onStyleSwitched [0x7ff84022eb0b] <toonzqt.dll>
 44> QObject::qt_static_metacall [0x7ff862a520d7] <Qt5Core.dll>
 45> TPaletteHandle::setPalette [0x7ff84001854b] <toonzlib.dll>
 46> PaletteController::editLevelPalette [0x7ff840038510] <toonzlib.dll>
 47> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff765361680] <OpenToonz.exe>
 48> QObject::qt_static_metacall [0x7ff862a520d7] <Qt5Core.dll>
 49> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7654d29cb] <OpenToonz.exe>
 50> QObject::qt_static_metacall [0x7ff862a520d7] <Qt5Core.dll>
 51> QAbstractButton::clicked [0x7ff865eefa97] <Qt5Widgets.dll>
 52> QAbstractButton::click [0x7ff865eef9b8] <Qt5Widgets.dll>
 53> QAbstractButton::mouseReleaseEvent [0x7ff865ef06bd] <Qt5Widgets.dll>
 54> QWidget::event [0x7ff865e48092] <Qt5Widgets.dll>
 55> QApplicationPrivate::notify_helper [0x7ff865e255c0] <Qt5Widgets.dll>
 56> QApplication::notify [0x7ff865e234e0] <Qt5Widgets.dll>
 57> QCoreApplication::notifyInternal2 [0x7ff862a3318a] <Qt5Core.dll>
 58> QApplicationPrivate::sendMouseEvent [0x7ff865e267c5] <Qt5Widgets.dll>
 59> QDesktopWidget::workAreaResized [0x7ff865e709d2] <Qt5Widgets.dll>
 60> QDesktopWidget::workAreaResized [0x7ff865e6e96e] <Qt5Widgets.dll>
 61> QApplicationPrivate::notify_helper [0x7ff865e255c0] <Qt5Widgets.dll>
 62> QApplication::notify [0x7ff865e24643] <Qt5Widgets.dll>
 63> QCoreApplication::notifyInternal2 [0x7ff862a3318a] <Qt5Core.dll>
 64> QGuiApplicationPrivate::processMouseEvent [0x7ff857dd47c3] <Qt5Gui.dll>
 65> QWindowSystemInterface::sendWindowSystemEvents [0x7ff857dbf030] <Qt5Gui.dll>
 66> QEventDispatcherWin32::processEvents [0x7ff862a7bcfa] <Qt5Core.dll>
 67> qt_plugin_query_metadata [0x7ff866c828d9] <qwindows.dll>
 68> QEventLoop::exec [0x7ff862a2f64c] <Qt5Core.dll>
 69> QCoreApplication::exec [0x7ff862a32164] <Qt5Core.dll>
 70> TSmartPointerConstT<TXshSoundLevel>::~TSmartPointerConstT<TXshSoundLevel> [0x7ff765315dc0] <OpenToonz.exe>
 71> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff7657458e7] <OpenToonz.exe>
 72> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff765744ec2] <OpenToonz.exe>
 73> BaseThreadInitThunk [0x7ff8bbba257d] <KERNEL32.DLL>
 74> RtlUserThreadStart [0x7ff8bcacaa58] <ntdll.dll>
==== End ====

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

built December 10th, 2023

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@Boshgoria In trying your steps I don't have any problems... and no crash.
As such there are a few things that need to be further clarified in your report.

Something I find interesting:
Not long ago I recall trying to save an 'empty' scene and Opentoonz would open a warning "There is nothing to save".
Something appears to have changed because I can now easily save a truly empty scene that has no levels.
But again, I ahve no issues with saving or loading an empy/new scene.

Any information you can share with us will help in better understanding the problem you are experiencing... to include information on your specific operating system, input devices (tablet?) etc.

The only thing that comes to mind is that you might have an overly agressive antivirus program (even if it is only Windows Defender) that is shutting down the program at that early stage.  Adjusting the settings of that antivirus program would allow Opentoonz to properly open, process and save scenes.

Perhaps someone else has thoughts on the problem they will share...

**Comment by RodneyBaker** [comment]
I note that your stuff directory appears to be on your desktop. 
At least for troubleshooting/testing purposes you should run Opentoonz with both the program and stuff directory in default locations.  That would be C:\Opentoonz stuff for Windows.

**Comment by Boshgoria** [comment]
Much thanks, RodneyBaker.

It seems OpenToonz was possibly having trouble with either a lack of available memory (it would crash similarly when working on regular projects while I had other programs running as well) or from the Opentoonz stuff being on my Desktop. I reinstalled Opentoonz a fourth time, but this time leaving each directory in their default spot (clearing the old directories since they didn't completely uninstall last time), and it's working fine now.

I also seemed to have an invalid FFmpeg path in my preferences. I had a bad path that led to a file on my desktop that I no longer had there, so when I tried to browse to modify it, the program would crash every time. I had to manually add the new one in.

If it was a directory problem, it seems fixed now, as I've defaulted the location according to what you said yesterday, and the program can create new scenes and open empty scenes just fine. If it's a memory problem, it seems to have fixed itself with the reinstall since I can run memory-intensive programs alongside OpenToonz after defaulting the directories.

However, I'll still include my system information in case it helps to identify this problem down the road and possibly contribute to fixing it. \/ \/ \/

     I am using Windows 11 (version 23H2, build 22631.2861), and I typically use my dedicated graphics for games (NVIDIA RTX 3050ti), but OpenToonz seems to be registering my OS as Windows 10 in the crash log (or maybe that's what the app was designed for?), and it's using my integrated graphics card (Intel UHD) by default instead of my dedicated one. The only input devices I was using during this issue was my mouse (Logitech G305) and my keyboard (integrated with my laptop).
     I already added an exception in my antivirus for OpenToonz before posting the issue, and it didn't do anything to help. I also ran the setup and executable as administrator which didn't help either.

**Comment by RodneyBaker** [comment]
Thanks for the follow up.  
It's always nice when we can close the loop on these kinds of things.

The fact that you cannot change the frame view option in Timeline (and I assume xsheet) is odd and perhaps that relates to a bad scene file.  I note that all of your color swatches/styles in the palette are blue indicating something got lost in transit.  

Some systems struggle with multiple monistors especially if/when they are set at different resolutions.
You might test to see if that is your case (if using muliple monitors).

**Comment by Boshgoria** [comment]
@RodneyBaker, I appreciate the quick response.

I do have a second monitor. Upon disabling it and restarting OpenToonz, as well as deleting my empty test scenes and starting a new one, I haven't been able to replicate the Frame View issue. If the problem pops up again, I'll open a new issue, but I can't gather any more information since it isn't happening again.

Thanks so much for the help!

**Comment by RodneyBaker** [comment]
Thanks again for the follow up.
I recently purchased two identical monitors just to make sure I don't have these kinds of issue especially when extending the screen across monitors.

Users that have reported the problem have stated that mirroring their monitors can resolve the issue (rather than extending the screen across monitors).  

Will close this report but please feel free to open a new report for any issues you encounter.
