### ISSUE TITLE
Autosave problem

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5243]
### Is your feature request related to a problem? Please describe

OpenToonz sometimes crashes, and people sometimes forget to save, so you can enable autosave. But there is a problem here, every time the program is autosaved, a window appears that saves, it interrupts some processes.

### Describe the solution you'd like

Please make autosaving occurs in the background, is invisible, and does not affect what we do in OpenToonz.

**Comment by RodneyBaker** [comment]
Not a direct addressing of this report but... if using Autosave you'll want to consider updating to the latest nightly release which has a related bugfix. 

Autosave should be largely working in the background so I'm not entirely following the problem reported here.
There are known problems with Autosave and all improvemetns to that process are certainly welcome.

**Comment by unoffending** [comment]
Thank you for answer!

**Comment by RodneyBaker** [comment]
Will close this report as a general report related to Autosave.
Some issues with Autosave have been addressed since this report was generated.
As such it would be good to review this... preferrably when the nightly release are stable.
