### ISSUE TITLE
missing free

### ISSUE THREAD

**Issue by maddin200** [opentoonz/opentoonz#5247]
### Description

toon/sources/common/twain/twain_conversion.c line 49
Code:

 if (!min_str) return;  // <-- missing free(maj_str);

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Thanks @maddin200 
Are you suggesting that scanning will work with this line restored?
My understanding is that much more of the TWAIN scanning code is missing than only that line.

I'll include this link to TWAIN Working Group's github as we've been talking about how best to get basic cross platform scanning working in Opentoonz of late.  Link:  https://github.com/twain/twain-samples

**Comment by maddin200** [comment]
already mentioned in  memory leak #5089
