### ISSUE TITLE
Colour change of background

### ISSUE THREAD

**Issue by starriderchef** [opentoonz/opentoonz#5248]
### Description

The background is filled with no gaps and heck without even using the fill tool 

### Steps to Reproduce

I do not know how it was produced the vague occurrence is that i was switching from one frame to another in ink-paint tab as i clicked on the first frame the background (empty/white) changed to a palleted shade which i had no intention of happening 
 
i refreshed it by going to drawing>re-clicking/selecting that frame and coming down to the working frame>going back to inkpaint now it infects the whole animation X3

### Screenshots, Video & Crash Logs

I do not have one

### OpenToonz Version

Other (Specify below)

### OpenToonz Version Information

May 10 2023 1.7.1

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Other

**Comment by DarrenTAnims** [comment]
Can you share a screenshot. I'm not really sure what you're seeing (it's always best to share a screenshot to describe something visual)

**Comment by RodneyBaker** [comment]
Closing as a report lacking sufficient information to troubleshoot the problem.
@starriderchef If you are still experiencing problems please let us know.
Another alternative would be to join one of the Opentoonz discords where others can assist in troubleshooting in real time.
