### ISSUE TITLE
OpenToonz crashed unexpectedly 

### ISSUE THREAD

**Issue by SodnomB** [opentoonz/opentoonz#5262]
### Description

Crash Reason: EXCEPTION_ACCESS_VIOLATION

### Steps to Reproduce

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 620
GPU Version: 4.6.0 - Build 31.0.101.2111

Crash File: C:\Users\HP\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240111-172310.log
Mini Dump File: C:\Users\HP\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240111-172310.dmp

Application Dir: D:/OpenToonz
Stuff Dir: D:\Opentoolz

Project Name: Hello1
Scene Name: Trial1
Project Path: D:\Opentoolz\projects\Hello1\Hello1_otprj.xml
Scene Path: D:\Opentoolz\projects\Hello1\scenes\Trial1.tnz

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\OpenToonz\Qt5Xml.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\bcrypt.dll
D:\OpenToonz\glut64.dll
D:\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\cfgmgr32.dll
D:\OpenToonz\EDSDK.dll
D:\OpenToonz\colorfx.dll
C:\WINDOWS\System32\WS2_32.dll
D:\OpenToonz\image.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
D:\OpenToonz\MSVCP140.dll
D:\OpenToonz\VCRUNTIME140.dll
D:\OpenToonz\VCRUNTIME140_1.dll
D:\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\OpenToonz\Qt5Network.dll
D:\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\System32\CRYPT32.dll
D:\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
D:\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
D:\OpenToonz\CONCRT140.dll
D:\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
D:\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
D:\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\ig9icd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igdml64.dll
C:\WINDOWS\system32\atig6txx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igdgmm64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_51f685305808e3a5\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
D:\OpenToonz\imageformats\qgif.dll
D:\OpenToonz\imageformats\qicns.dll
D:\OpenToonz\imageformats\qico.dll
D:\OpenToonz\imageformats\qjpeg.dll
D:\OpenToonz\imageformats\qsvg.dll
D:\OpenToonz\imageformats\qtga.dll
D:\OpenToonz\imageformats\qtiff.dll
D:\OpenToonz\imageformats\qwbmp.dll
D:\OpenToonz\imageformats\qwebp.dll
D:\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\NLAapi.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\WINDOWS\SYSTEM32\TextShaping.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll
C:\Windows\System32\Windows.StateRepositoryPS.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
C:\WINDOWS\SYSTEM32\msvcp110_win.dll
C:\WINDOWS\SYSTEM32\PhotoMetadataHandler.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffbbda08b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffbbd9e12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffbbda30ebe] <ntdll.dll>
  4> TVectorImageP::TVectorImageP [0x7ffb76c2e75b] <tnzcore.dll>
  5> TImageCache::compressAndMalloc [0x7ffb76c33a3d] <tnzcore.dll>
  6> TImageCache::dump [0x7ffb76c35184] <tnzcore.dll>
  7> TImageCache::get [0x7ffb76c35261] <tnzcore.dll>
  8> IconGenerator::generateVectorFileIcon [0x7ffb7724738c] <toonzqt.dll>
  9> IconGenerator::getIcon [0x7ffb77247f7f] <toonzqt.dll>
 10> TSmartPointerT<TXshChildLevel>::~TSmartPointerT<TXshChildLevel> [0x7ff6140621e1] <OpenToonz.exe>
 11> TSmartPointerT<TXshChildLevel>::~TSmartPointerT<TXshChildLevel> [0x7ff6140662d9] <OpenToonz.exe>
 12> QWidget::event [0x7ffb781b84d1] <Qt5Widgets.dll>
 13> QFrame::event [0x7ffb78259d10] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffb781955c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffb78194643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffb7770318a] <Qt5Core.dll>
 17> QWidgetPrivate::drawWidget [0x7ffb781b7aeb] <Qt5Widgets.dll>
 18> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 19> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 20> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 21> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 22> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 23> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 24> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 25> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 26> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 27> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 28> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 29> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 30> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 31> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 32> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 33> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 34> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 35> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 36> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 37> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 38> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 39> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bd985] <Qt5Widgets.dll>
 40> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 41> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 42> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 43> QWidgetPrivate::paintSiblingsRecursive [0x7ffb781bda57] <Qt5Widgets.dll>
 44> QWidgetPrivate::drawWidget [0x7ffb781b7c44] <Qt5Widgets.dll>
 45> QWidgetPrivate::moveRect [0x7ffb781a0406] <Qt5Widgets.dll>
 46> QWidget::event [0x7ffb781b890f] <Qt5Widgets.dll>
 47> QApplicationPrivate::notify_helper [0x7ffb781955c0] <Qt5Widgets.dll>
 48> QApplication::notify [0x7ffb78194643] <Qt5Widgets.dll>
 49> QCoreApplication::notifyInternal2 [0x7ffb7770318a] <Qt5Core.dll>
 50> QCoreApplicationPrivate::sendPostedEvents [0x7ffb77704f25] <Qt5Core.dll>
 51> qt_plugin_query_metadata [0x7ffb79a128ff] <qwindows.dll>
 52> QEventDispatcherWin32::processEvents [0x7ffb7774bcfa] <Qt5Core.dll>
 53> qt_plugin_query_metadata [0x7ffb79a128d9] <qwindows.dll>
 54> QEventLoop::exec [0x7ffb776ff64c] <Qt5Core.dll>
 55> QCoreApplication::exec [0x7ffb77702164] <Qt5Core.dll>
 56> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff613fe5219] <OpenToonz.exe>
 57> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61440eab7] <OpenToonz.exe>
 58> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61440e092] <OpenToonz.exe>
 59> BaseThreadInitThunk [0x7ffbbbbd7344] <KERNEL32.DLL>
 60> RtlUserThreadStart [0x7ffbbd9e26b1] <ntdll.dll>
==== End ====

### Expected Behavior

I wanted to mesh my png picture

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Please install Opentoonz on your C:Drive for troubleshooting purposes.
Once you get it up and running to your liking then expand out to other drives.

As for the crash... the only thing that stands out to me is that perhaps you have a codec pack installed that includes an incompatible codec.
