### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by iTheMarcus** [opentoonz/opentoonz#5266]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-01-13 14:49:27
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 5500
GPU Version: 4.4.0 - Build 20.19.15.5171

Crash File: C:\Users\EXO\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240113-144927.log
Mini Dump File: C:\Users\EXO\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240113-144927.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: SILENCE
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\SILENCE.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\SHELL32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\RPCRT4.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\MF.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\SYSTEM32\ig8icd64.dll
C:\Windows\SYSTEM32\igdusc64.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Windows\system32\Ninput.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\comctl32.DLL
C:\Windows\SYSTEM32\igd10iumd64.dll
C:\Windows\SYSTEM32\ncrypt.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\SYSTEM32\NTASN1.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffd24648b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffd246212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd24670ebe] <ntdll.dll>
  4> StyleEditorGUI::ColorSlider::setColor [0x7ffcef52e237] <toonzqt.dll>
  5> StyleEditor::setStyle [0x7ffcef52f1aa] <toonzqt.dll>
  6> StyleEditor::onStyleSwitched [0x7ffcef52b8fe] <toonzqt.dll>
  7> QObject::qt_static_metacall [0x7ffcd96020d7] <Qt5Core.dll>
  8> TPaletteHandle::setPalette [0x7ffceee2663b] <toonzlib.dll>
  9> PaletteController::editLevelPalette [0x7ffceee46630] <toonzlib.dll>
 10> QObject::qt_static_metacall [0x7ffcd96020d7] <Qt5Core.dll>
 11> TPaletteHandle::setPalette [0x7ffceee2663b] <toonzlib.dll>
 12> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7eb45fe1c] <OpenToonz.exe>
 13> QObject::qt_static_metacall [0x7ffcd96020d7] <Qt5Core.dll>
 14> TXshLevelHandle::xshLevelSwitched [0x7ffceee64b31] <toonzlib.dll>
 15> TXshLevelHandle::setLevel [0x7ffceee26d4e] <toonzlib.dll>
 16> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7eb46022c] <OpenToonz.exe>
 17> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7eb45f672] <OpenToonz.exe>
 18> QObject::qt_static_metacall [0x7ffcd96020d7] <Qt5Core.dll>
 19> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7eb504712] <OpenToonz.exe>
 20> FlipConsole::doButtonPressed [0x7ffcef4a2e24] <toonzqt.dll>
 21> FlipConsole::onButtonPressed [0x7ffcef4a4629] <toonzqt.dll>
 22> FlipConsole::onButtonPressed [0x7ffcef4a4700] <toonzqt.dll>
 23> FlipConsole::qt_static_metacall [0x7ffcef5f3a04] <toonzqt.dll>
 24> QObject::qt_static_metacall [0x7ffcd96020d7] <Qt5Core.dll>
 25> QToolButton::qt_static_metacall [0x7ffceceb5be4] <Qt5Widgets.dll>
 26> QObject::qt_static_metacall [0x7ffcd96020d7] <Qt5Core.dll>
 27> QAction::activate [0x7ffcecd05eff] <Qt5Widgets.dll>
 28> QAbstractButton::click [0x7ffcecddf94d] <Qt5Widgets.dll>
 29> QAbstractButton::mouseReleaseEvent [0x7ffcecde06bd] <Qt5Widgets.dll>
 30> QToolButton::mouseReleaseEvent [0x7ffceceb6b2f] <Qt5Widgets.dll>
 31> QWidget::event [0x7ffcecd38092] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ffcecd155c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ffcecd134e0] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ffcd95e318a] <Qt5Core.dll>
 35> QApplicationPrivate::sendMouseEvent [0x7ffcecd167c5] <Qt5Widgets.dll>
 36> QDesktopWidget::workAreaResized [0x7ffcecd609d2] <Qt5Widgets.dll>
 37> QDesktopWidget::workAreaResized [0x7ffcecd5e96e] <Qt5Widgets.dll>
 38> QApplicationPrivate::notify_helper [0x7ffcecd155c0] <Qt5Widgets.dll>
 39> QApplication::notify [0x7ffcecd14643] <Qt5Widgets.dll>
 40> QCoreApplication::notifyInternal2 [0x7ffcd95e318a] <Qt5Core.dll>
 41> QGuiApplicationPrivate::processMouseEvent [0x7ffcdcec47c3] <Qt5Gui.dll>
 42> QWindowSystemInterface::sendWindowSystemEvents [0x7ffcdceaf030] <Qt5Gui.dll>
 43> QEventDispatcherWin32::processEvents [0x7ffcd962bcfa] <Qt5Core.dll>
 44> qt_plugin_query_metadata [0x7ffcd8b328d9] <qwindows.dll>
 45> QEventLoop::exec [0x7ffcd95df64c] <Qt5Core.dll>
 46> QCoreApplication::exec [0x7ffcd95e2164] <Qt5Core.dll>
 47> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7eb415219] <OpenToonz.exe>
 48> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7eb83eab7] <OpenToonz.exe>
 49> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7eb83e092] <OpenToonz.exe>
 50> BaseThreadInitThunk [0x7ffd236d7344] <KERNEL32.DLL>
 51> RtlUserThreadStart [0x7ffd246226b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
Without filling out the bug form (Steps to Reproduce, Expected Behavior, etc), there's nothing that can be done with this.
