### ISSUE TITLE
Opentoonz crashed unexpectedly

### ISSUE THREAD

**Issue by kiidavid** [opentoonz/opentoonz#5267]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-01-15 13:09:38
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 8

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.5081

Crash File: C:\Users\david\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240115-130938.log
Mini Dump File: C:\Users\david\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240115-130938.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: 0000
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\0000.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\Windows.ApplicationModel.dll
C:\WINDOWS\system32\propsys.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\WINDOWS\system32\mssprxy.dll
C:\Windows\System32\Windows.StateRepositoryPS.dll
C:\WINDOWS\SYSTEM32\windows.staterepositoryclient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_30b27fc8a96c0745\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_30b27fc8a96c0745\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_30b27fc8a96c0745\igdgmm64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_30b27fc8a96c0745\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2506_none_270c5ae97388e100\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffd2d5c7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffd2d56e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffd2d5f340e] <ntdll.dll>
  4> StyleEditorGUI::ColorSlider::setColor [0x7ffc97a9e237] <toonzqt.dll>
  5> StyleEditor::setStyle [0x7ffc97a9f1aa] <toonzqt.dll>
  6> StyleEditor::onStyleSwitched [0x7ffc97a9b8fe] <toonzqt.dll>
  7> QObject::qt_static_metacall [0x7ffc8e8120d7] <Qt5Core.dll>
  8> TPaletteHandle::setPalette [0x7ffc8e4d663b] <toonzlib.dll>
  9> PaletteController::editLevelPalette [0x7ffc8e4f6630] <toonzlib.dll>
 10> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7aa7ffb70] <OpenToonz.exe>
 11> QObject::qt_static_metacall [0x7ffc8e8120d7] <Qt5Core.dll>
 12> TSceneHandle::setScene [0x7ffc8e4d6916] <toonzlib.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7aa9c2c28] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7aa96e317] <OpenToonz.exe>
 15> QObject::qt_static_metacall [0x7ffc8e8120d7] <Qt5Core.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7aab578c0] <OpenToonz.exe>
 17> QObject::qt_static_metacall [0x7ffc8e8120d7] <Qt5Core.dll>
 18> QListWidget::qt_static_metacall [0x7ffc97f8aa1b] <Qt5Widgets.dll>
 19> QObject::qt_static_metacall [0x7ffc8e8120d7] <Qt5Core.dll>
 20> QAbstractItemView::mouseReleaseEvent [0x7ffc97f52a0f] <Qt5Widgets.dll>
 21> QListView::mouseReleaseEvent [0x7ffc97f8346f] <Qt5Widgets.dll>
 22> QWidget::event [0x7ffc97d58092] <Qt5Widgets.dll>
 23> QFrame::event [0x7ffc97df9d10] <Qt5Widgets.dll>
 24> QAbstractItemView::viewportEvent [0x7ffc97f58ae8] <Qt5Widgets.dll>
 25> QCoreApplicationPrivate::sendThroughObjectEventFilters [0x7ffc8e7f523a] <Qt5Core.dll>
 26> QApplicationPrivate::notify_helper [0x7ffc97d355ac] <Qt5Widgets.dll>
 27> QApplication::notify [0x7ffc97d334e0] <Qt5Widgets.dll>
 28> QCoreApplication::notifyInternal2 [0x7ffc8e7f318a] <Qt5Core.dll>
 29> QApplicationPrivate::sendMouseEvent [0x7ffc97d367c5] <Qt5Widgets.dll>
 30> QDesktopWidget::workAreaResized [0x7ffc97d809d2] <Qt5Widgets.dll>
 31> QDesktopWidget::workAreaResized [0x7ffc97d7e96e] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ffc97d355c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ffc97d34643] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ffc8e7f318a] <Qt5Core.dll>
 35> QGuiApplicationPrivate::processMouseEvent [0x7ffc8ec347c3] <Qt5Gui.dll>
 36> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc8ec1f030] <Qt5Gui.dll>
 37> QEventDispatcherWin32::processEvents [0x7ffc8e83bcfa] <Qt5Core.dll>
 38> qt_plugin_query_metadata [0x7ffc8dd928d9] <qwindows.dll>
 39> QEventLoop::exec [0x7ffc8e7ef64c] <Qt5Core.dll>
 40> QCoreApplication::exec [0x7ffc8e7f2164] <Qt5Core.dll>
 41> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7aa7b5219] <OpenToonz.exe>
 42> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7aabdeab7] <OpenToonz.exe>
 43> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7aabde092] <OpenToonz.exe>
 44> BaseThreadInitThunk [0x7ffd2c37257d] <KERNEL32.DLL>
 45> RtlUserThreadStart [0x7ffd2d5aaa58] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### Expected Behavior

I couldn't notice any pattern between the crashes, even after it crashed for the first time, it happened again a few seconds after I tried to open the app again

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Huion

**Comment by 11jer** [comment]
me too...


OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-01-28 17:31:12
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 8

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 30.0.101.2079

Crash File: C:\Users\oc969\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240128-173112.log
Mini Dump File: C:\Users\oc969\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240128-173112.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: 나기사 카오루
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\나기사 카오루.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_57ce179e0ee5edd3\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_57ce179e0ee5edd3\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_57ce179e0ee5edd3\igdgmm64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_57ce179e0ee5edd3\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\WINDOWS\SYSTEM32\windows.staterepositoryclient.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\SYSTEM32\urlmon.dll
C:\WINDOWS\SYSTEM32\iertutil.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\Windows\System32\cldapi.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.2506_none_270c5ae97388e100\comctl32.DLL
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
C:\WINDOWS\SYSTEM32\msvcp110_win.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffbedb27a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffbedace242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffbedb5340e] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7681b61c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76819d75d] <OpenToonz.exe>
  6> QWidget::event [0x7ffb3636807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76819b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ffb363455c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffb363434e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffb34c3318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ffb363467c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ffb363909d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffb3638e96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffb363455c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffb36344643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffb34c3318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ffb350747c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb3505f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ffb34c7bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ffb608028d9] <qwindows.dll>
 21> QEventLoop::exec [0x7ffb34c2f64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7ffb34c32164] <Qt5Core.dll>
 23> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7680f5219] <OpenToonz.exe>
 24> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76851eab7] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76851e092] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7ffbec8e257d] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7ffbedb0aa58] <ntdll.dll>
==== End ====
