### ISSUE TITLE
Colour remains black of brush if change also

### ISSUE THREAD

**Issue by Rishav123Ku** [opentoonz/opentoonz#5270]
### Description

whenever i change the colour of brush and start to colour than also the colour remains black Initiall it was working welll but now its not working

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![Screenshot 2024-01-17 152113](https://github.com/opentoonz/opentoonz/assets/131454319/83829d72-df5f-4a89-911c-873f33adf86a)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Double check to make sure you don't have one of the specialized views on that will produce only black linework from your colored images.  Look for those in your menu:

![image](https://github.com/opentoonz/opentoonz/assets/2576432/b406c184-d3b9-4f0f-8ae2-fe3d5ef1fd24)

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Rishav123Ku Please let us know if you are still experiencing problems.
