### ISSUE TITLE
Pen Pressure not working properly

### ISSUE THREAD

**Issue by SLaMotte1** [opentoonz/opentoonz#5276]
### Description

I just downloaded the software today and I'm experiencing this weird issue with the pen pressure. Whether I activate the "enable windows ink" support or not the issue remains. The software starts off recognizing the pen pressure then it shoots to the max brush setting. There is no gradual build up of the pen raster nor vector brushes. Any reason why this is happening?

I have tried disabling windows ink in my wacom software and OT and I've enable windows ink in both software and the issue still exists.

I own a Wacom Intuos graphics tablet.
 
![Screenshot 2024-01-28 110346](https://github.com/opentoonz/opentoonz/assets/98706363/669e723c-c0b7-427f-b04b-e76300d9dae1)
![Screenshot 2024-01-28 110346](https://github.com/opentoonz/opentoonz/assets/98706363/4daa35e1-e121-4216-9f76-8883358b08ac)

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
You generally will want to DISABLE Windows Ink in Opentoonz, in your tablet's setting and in the operating system.
This for best use with Opentoonz at least.

You do have the sliders for pen width at the maximum low and high settings.
Try bring that maxiumum down considerably as (from my understanding) the rise is indeed exponential the higher that is set.

**Comment by SLaMotte1** [comment]
I've tried different varieties of sizes and it's the same result. I'm not sure what to do.

**Comment by SLaMotte1** [comment]
> I've tried different varieties of sizes and it's the same result. I'm not sure what to do.

**Comment by DarrenTAnims** [comment]
I had this until I adjusted the pressure settings curve in my tablet software. That fixed it for me.

**Comment by SLaMotte1** [comment]
> Does this happen in other programs, too?

Nope only Open Toonz

**Comment by SLaMotte1** [comment]
> I had this until I adjusted the pressure settings curve in my tablet software. That fixed it for me.

Ok I'll give that a try.

**Comment by SLaMotte1** [comment]
> I had this until I adjusted the pressure settings curve in my tablet software. That fixed it for me.

This still didn't work either sadly

**Comment by SLaMotte1** [comment]
SO I tried Tahoma2D and i'm having the same problem, could it be an issue with MyPaints brush

**Comment by SLaMotte1** [comment]
I reinstalled my Wacom drivers again to see if it would fix the issue and it did, the pen pressure is working now! Thanks for the suggestions everyone.
