### ISSUE TITLE
OpenToonz did something strange

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5278]
### Description

It is not clear why the drawing changed, grew larger and shifted in the other direction, I wanted to correct it, but soon an error occurred.

### Steps to Reproduce

If OpenToonz has changed the picture itself, this may mean that it may ruin some of the pictures, since when the picture is enlarged, it loses its quality.
I think we just need to make sure that OpenToonz can't change the frames by itself.

### Expected Behavior

I wish OpenToonz didn't crash so unexpectedly.

### Screenshots, Video & Crash Logs

![2024-01-29_21-37-56](https://github.com/opentoonz/opentoonz/assets/109032978/78dd52a4-484b-4d67-aac4-27cd15d4cf47)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Will close this report and leave this reference to other reports by same author still open.
REF:  https://github.com/opentoonz/opentoonz/issues/created_by/unoffending
