### ISSUE TITLE
OpenToonz unexpectedly crashed

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5279]
### Description

It is possible that this is because there are a lot of frames in the project. 

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![2024-01-29_22-23-57](https://github.com/opentoonz/opentoonz/assets/109032978/33762b11-c394-4e52-984b-47ae8288f0cb)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by unoffending** [comment]
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-01-29 22:23:48
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240129-222348.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240129-222348.dmp

Application Dir: F:/Program Files/OpenToonz
Stuff Dir: F:\OpenToonz stuff

Project Name: Один шаг
Scene Name: Один шаг 2
Project Path: F:\OpenToonz stuff\projects\Один шаг\Один шаг_otprj.xml
Scene Path: F:\OpenToonz stuff\projects\Один шаг\scenes\Один шаг 2.tnz

==== Modules ====
F:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
F:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
F:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\SHLWAPI.dll
F:\Program Files\OpenToonz\glut64.dll
F:\Program Files\OpenToonz\Qt5SerialPort.dll
F:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
F:\Program Files\OpenToonz\colorfx.dll
F:\Program Files\OpenToonz\image.dll
F:\Program Files\OpenToonz\tnztools.dll
F:\Program Files\OpenToonz\tnzstdfx.dll
F:\Program Files\OpenToonz\tfarm.dll
F:\Program Files\OpenToonz\Qt5Widgets.dll
F:\Program Files\OpenToonz\Qt5Gui.dll
F:\Program Files\OpenToonz\Qt5Core.dll
F:\Program Files\OpenToonz\toonzqt.dll
F:\Program Files\OpenToonz\sound.dll
F:\Program Files\OpenToonz\toonzlib.dll
F:\Program Files\OpenToonz\opencv_world451.dll
F:\Program Files\OpenToonz\Qt5Script.dll
F:\Program Files\OpenToonz\tnzext.dll
F:\Program Files\OpenToonz\tnzbase.dll
F:\Program Files\OpenToonz\tnzcore.dll
F:\Program Files\OpenToonz\Qt5OpenGL.dll
F:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
F:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
F:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
F:\Program Files\OpenToonz\VCRUNTIME140.dll
F:\Program Files\OpenToonz\VCRUNTIME140_1.dll
F:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
F:\Program Files\OpenToonz\libmypaint-1-4-0.dll
F:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
F:\Program Files\OpenToonz\Qt5Svg.dll
F:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
F:\Program Files\OpenToonz\libintl-8.dll
F:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
F:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
F:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
F:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
F:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
F:\Program Files\OpenToonz\imageformats\qgif.dll
F:\Program Files\OpenToonz\imageformats\qicns.dll
F:\Program Files\OpenToonz\imageformats\qico.dll
F:\Program Files\OpenToonz\imageformats\qjpeg.dll
F:\Program Files\OpenToonz\imageformats\qsvg.dll
F:\Program Files\OpenToonz\imageformats\qtga.dll
F:\Program Files\OpenToonz\imageformats\qtiff.dll
F:\Program Files\OpenToonz\imageformats\qwbmp.dll
F:\Program Files\OpenToonz\imageformats\qwebp.dll
F:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
F:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffec4aa8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffec4a812d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffec4ad0ebe] <ntdll.dll>
  4> PegbarCenterField::tr [0x7ffe67c68007] <tnztools.dll>
  5> RasterSelection::setFrameId [0x7ffe67c6d9a2] <tnztools.dll>
  6> RasterSelection::operator= [0x7ffe67c69d31] <tnztools.dll>
  7> RasterSelection::setTransformationCount [0x7ffe67c6e327] <tnztools.dll>
  8> RasterSelection::setTransformationCount [0x7ffe67c778c5] <tnztools.dll>
  9> RasterSelection::isPastedSelection [0x7ffe67c6be06] <tnztools.dll>
 10> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e877b4fd] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e877a5f8] <OpenToonz.exe>
 12> QWidget::event [0x7ffe54298066] <Qt5Widgets.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e877942b] <OpenToonz.exe>
 14> QApplicationPrivate::notify_helper [0x7ffe542755c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffe542734e0] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffe5232318a] <Qt5Core.dll>
 17> QApplicationPrivate::sendMouseEvent [0x7ffe542767c5] <Qt5Widgets.dll>
 18> QDesktopWidget::workAreaResized [0x7ffe542c09d2] <Qt5Widgets.dll>
 19> QDesktopWidget::workAreaResized [0x7ffe542be96e] <Qt5Widgets.dll>
 20> QApplicationPrivate::notify_helper [0x7ffe542755c0] <Qt5Widgets.dll>
 21> QApplication::notify [0x7ffe54274643] <Qt5Widgets.dll>
 22> QCoreApplication::notifyInternal2 [0x7ffe5232318a] <Qt5Core.dll>
 23> QGuiApplicationPrivate::processMouseEvent [0x7ffe53c247c3] <Qt5Gui.dll>
 24> QWindowSystemInterface::sendWindowSystemEvents [0x7ffe53c0f030] <Qt5Gui.dll>
 25> QEventDispatcherWin32::processEvents [0x7ffe5236bcfa] <Qt5Core.dll>
 26> qt_plugin_query_metadata [0x7ffe666928d9] <qwindows.dll>
 27> QEventLoop::exec [0x7ffe5231f64c] <Qt5Core.dll>
 28> QCoreApplication::exec [0x7ffe52322164] <Qt5Core.dll>
 29> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7e8695219] <OpenToonz.exe>
 30> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e8abeab7] <OpenToonz.exe>
 31> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e8abe092] <OpenToonz.exe>
 32> BaseThreadInitThunk [0x7ffec38c7344] <KERNEL32.DLL>
 33> RtlUserThreadStart [0x7ffec4a826b1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
Will assume we've moved on from this issue and...

Close this report in favor of other reports still opened by @unoffending.
