### ISSUE TITLE
export to webM video format

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#528]
Look into webm:
https://www.webmproject.org/

This codec is supported by all web browsers now - to view the animation people dont need to download and install anything.
Google developed webm precisely in order to solve the issue of codec patents - it affected them directly because youtube used to have a lot of videos with the patent infringing codecs.
Webm has an incredibly good quality, small size, it is widely supported and has no royalty fees.
It is the video format of the web. All youtube videos switched to it, 4chan, tumblr and the majority of image sharing websites use it - all web browsers support it on pc or mobile. It just works everywhere.

I advice everyone to support its use - that way the h.264 codec will become obsolete and its royalty fees will plummet.

Apart of gif and webm, it is worth looking into an exporter for spritesheets and json animation file- it will aid game developers greatly.
https://github.com/opentoonz/opentoonz/issues/173

**Comment by blurymind** [comment]
@turtletooth 
https://www.webmproject.org/tools/

> FFmpeg
> FFmpeg ships with libvpx support that can be configured at compile time. See the WebM wiki pages for compilation tips and ffmpeg arguments pertaining to libvpx.
> 
> A WebM user maintains a public spreadsheet (last seen 20140915) that attempts to map vpxenc arguments to ffmpeg arguments.

**Comment by turtletooth** [comment]
@blurymind I included webm in the version of ffmpeg I built for OT.  I plan on adding it alongside h.264.

**Comment by blurymind** [comment]
@turtletooth Thank you for the work on ffmpeg and for submitting a PR for webM export:
#624

**Comment by turtletooth** [comment]
merged #624
