### ISSUE TITLE
opentoonz has closed unexpectedly

### ISSUE THREAD

**Issue by MultimonWolfBear** [opentoonz/opentoonz#5285]
### Description

opentoonz has closed unexpectedly
a sale appears

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

GAOMON

**Comment by DarrenTAnims** [comment]
Please fill out the form when posting a bug report. With no information, there's nothing that can be done and this post will just be closed.
