### ISSUE TITLE
i have a crashed unexpected notice. 

### ISSUE THREAD

**Issue by IXMAIX** [opentoonz/opentoonz#5289]
### Description

when I draw frame by frame it shows a notification about a crash, it has happened twice when I draw.

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![Screenshot (349)](https://github.com/opentoonz/opentoonz/assets/158265440/7c1f29a3-07da-41a4-bcb2-d928096a3fad)

### OpenToonz Version

1.7

### OpenToonz Version Information

build January 20, 2024

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
There isn't much we can do here without additional information.
Perhaps a recommendation would be to join one of the Opentoonz discords where the community of Opentoonz users will assist in troubleshooting every problem you encounter.   Most who will answer questions here are there answering questions as well.

Here is a link for the main Opentoonz discord (although there are certainly other venues and even discords dedicated to Opentoonz and its forks):  https://discord.gg/hvVj44K4ee
