### ISSUE TITLE
Logitech driver crash at startup

### ISSUE THREAD

**Issue by GallAN21** [opentoonz/opentoonz#5290]
### Description

it immediately crashed

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Jan 28 2024)

Report Date: 2024-02-05 19:39:09
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 24

Crash File: C:\Users\galla\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240205-193909.log
Mini Dump File: C:\Users\galla\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240205-193909.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\SYSTEM32\apphelp.dll
C:\windows\System32\USER32.dll
C:\windows\System32\win32u.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\gdi32full.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\ucrtbase.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\windows\System32\SHELL32.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\ole32.dll
C:\windows\System32\msvcrt.dll
C:\windows\System32\RPCRT4.dll
C:\windows\System32\combase.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\OLEAUT32.dll
C:\windows\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\windows\System32\bcrypt.dll
C:\windows\System32\COMDLG32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\windows\System32\shcore.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\windows\System32\SHLWAPI.dll
C:\windows\System32\SETUPAPI.dll
C:\windows\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\windows\SYSTEM32\GLU32.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\windows\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\windows\SYSTEM32\WINMM.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\windows\SYSTEM32\VERSION.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\windows\SYSTEM32\d3d11.dll
C:\windows\SYSTEM32\dxgi.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\windows\SYSTEM32\USERENV.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\windows\SYSTEM32\DNSAPI.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\windows\SYSTEM32\winmmbase.dll
C:\windows\SYSTEM32\NETUTILS.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\ksuser.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\Wldp.dll
C:\windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\SYSTEM32\msasn1.dll
C:\windows\SYSTEM32\cryptnet.dll
C:\windows\System32\wintrust.dll
C:\windows\System32\imagehlp.dll
C:\windows\SYSTEM32\CRYPTSP.dll
C:\windows\system32\rsaenh.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\System32\CoreUIComponents.dll
C:\windows\System32\CoreMessaging.dll
C:\windows\SYSTEM32\ntmarta.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\system32\Oleacc.dll
C:\windows\system32\UIAutomationCore.dll
C:\windows\SYSTEM32\PROPSYS.dll
C:\windows\System32\clbcatq.dll
C:\windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_7e5fd280efaa5445\nvoglv64.dll
C:\windows\SYSTEM32\drvstore.dll
C:\windows\SYSTEM32\devobj.dll
C:\windows\SYSTEM32\dxcore.dll
C:\windows\system32\nvspcap64.dll
C:\windows\SYSTEM32\WINSTA.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\dcomp.dll
C:\windows\system32\twinapi.appcore.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff9526e8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff9526c12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff952710ebe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ff92d312b9c] <MSVFW32.dll>
  6> ICOpen [0x7ff92d312d64] <MSVFW32.dll>
  7> TSmartHolderT<TXshSimpleLevel>::set [0x7ff8f112a172] <image.dll>
  8> TSmartHolderT<TXshSimpleLevel>::set [0x7ff8f11282e8] <image.dll>
  9> initImageIo [0x7ff8f10c7bd4] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff71e461f2e] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff71e463e61] <OpenToonz.exe>
 12> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff71e897ff7] <OpenToonz.exe>
 13> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff71e8975d2] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff951de7344] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff9526c26b1] <ntdll.dll>
==== End ====
![image_2024-02-05_194428899](https://github.com/opentoonz/opentoonz/assets/159059405/6fcc9ee2-4ca9-4dac-9b2b-d9496408f921)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
@GallAN21 
Good news!

The file/driver C:\windows\SYSTEM32\lvcod64.dll is to source of your problem.
That driver is a Logitec webcam driver no longer supported by Logitec and one that has proven troublesome in many applications.

Remove or rename that file and Opentoonz should start.

**Comment by GallAN21** [comment]
@RodneyBaker 
I've been searching in "C:\Windows\System32" but I cant find lvcod64.dll
(I just copy pasted that from your report)

**Comment by GallAN21** [comment]
@RodneyBaker  Thanks
I managed to get it working thank you very much
