### ISSUE TITLE
My new columns option disappeared

### ISSUE THREAD

**Issue by Bianca1950** [opentoonz/opentoonz#5294]
### Description

I was in the middle of my project, in which I only used vector columns, but suddenly, the columns option disappeared, I couldn't create more vector layers, I don't know what happened, I think it's a bug, please help me

### Steps to Reproduce

1. restore my columns options
2. my columns option disappeared

### Expected Behavior

I was in the middle of my project, in which I only used vector columns, but suddenly, the columns option disappeared, I couldn't create more vector layers, I don't know what happened, I think it's a bug, please help me

### OpenToonz Version

1.7

### OpenToonz Version Information

1.17

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
Not quite sure what you mean by 'columns option' so perhaps you can share a screenshot or two.

To get most temporary problems to subside we can usually just restart Opentoonz.

**Comment by DarrenTAnims** [comment]
Be sure to select on a column header before right clicking, if you're after the insert column (or similar) options. Sometimes it looks like you've selected a column header when you've really only selected cells in the column. There are different menus shown, depending on what is selected.
