### ISSUE TITLE
OpenToonz意外崩溃

### ISSUE THREAD

**Issue by YiyuHuaiAi** [opentoonz/opentoonz#5298]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-02-12 21:52:59
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 8

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3060/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 546.29

Crash File: C:\Users\A\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240212-215259.log
Mini Dump File: C:\Users\A\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240212-215259.dmp

Application Dir: D:/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: A1,1C3
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\A1,1C3.tnz

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
D:\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\COMDLG32.dll
D:\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\shcore.dll
D:\OpenToonz\glut64.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
D:\OpenToonz\image.dll
D:\OpenToonz\colorfx.dll
D:\OpenToonz\tnztools.dll
C:\WINDOWS\System32\WS2_32.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
D:\OpenToonz\tnzcore.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
D:\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
D:\OpenToonz\VCRUNTIME140.dll
D:\OpenToonz\VCRUNTIME140_1.dll
D:\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
D:\OpenToonz\libmypaint-1-4-0.dll
D:\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
D:\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
D:\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
D:\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
D:\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\system32\SogouTSF.ime
C:\WINDOWS\system32\MSIMG32.dll
C:\WINDOWS\system32\SogouPY.ime
C:\WINDOWS\SYSTEM32\WINHTTP.dll
C:\WINDOWS\SYSTEM32\OLEACC.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\Program Files (x86)\SogouInput\14.1.0.8858\Resource.dll
C:\Program Files (x86)\SogouInput\Components\PicFace\1.1.0.2129\PicFace64.dll
C:\WINDOWS\System32\PSAPI.DLL
C:\WINDOWS\SYSTEM32\TextShaping.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmdig.inf_amd64_664a91c68a5bfa21\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\gpapi.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvmdig.inf_amd64_664a91c68a5bfa21\nvgpucomp64.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
D:\OpenToonz\imageformats\qgif.dll
D:\OpenToonz\imageformats\qicns.dll
D:\OpenToonz\imageformats\qico.dll
D:\OpenToonz\imageformats\qjpeg.dll
D:\OpenToonz\imageformats\qsvg.dll
D:\OpenToonz\imageformats\qtga.dll
D:\OpenToonz\imageformats\qtiff.dll
D:\OpenToonz\imageformats\qwbmp.dll
D:\OpenToonz\imageformats\qwebp.dll
D:\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\Windows\System32\appresolver.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fffffae7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fffffa8e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fffffb1340e] <ntdll.dll>
  4> TSmartPointerT<TXshChildLevel>::~TSmartPointerT<TXshChildLevel> [0x7ff786f1173e] <OpenToonz.exe>
  5> TSmartPointerT<TXshChildLevel>::~TSmartPointerT<TXshChildLevel> [0x7ff786f0cc8a] <OpenToonz.exe>
  6> TSmartPointerT<TXshChildLevel>::~TSmartPointerT<TXshChildLevel> [0x7ff786f16e79] <OpenToonz.exe>
  7> QObject::qt_static_metacall [0x7fff893920d7] <Qt5Core.dll>
  8> QAction::activate [0x7fff89df5eff] <Qt5Widgets.dll>
  9> QMenu::actionGeometry [0x7fff89f4c308] <Qt5Widgets.dll>
 10> QMenu::actionGeometry [0x7fff89f4c0e3] <Qt5Widgets.dll>
 11> QMenu::mouseReleaseEvent [0x7fff89f518a1] <Qt5Widgets.dll>
 12> QWidget::event [0x7fff89e28092] <Qt5Widgets.dll>
 13> QMenu::event [0x7fff89f4d8a7] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7fff89e055c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7fff89e034e0] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7fff8937318a] <Qt5Core.dll>
 17> QApplicationPrivate::sendMouseEvent [0x7fff89e067c5] <Qt5Widgets.dll>
 18> QDesktopWidget::workAreaResized [0x7fff89e50383] <Qt5Widgets.dll>
 19> QDesktopWidget::workAreaResized [0x7fff89e4e96e] <Qt5Widgets.dll>
 20> QApplicationPrivate::notify_helper [0x7fff89e055c0] <Qt5Widgets.dll>
 21> QApplication::notify [0x7fff89e04643] <Qt5Widgets.dll>
 22> QCoreApplication::notifyInternal2 [0x7fff8937318a] <Qt5Core.dll>
 23> QGuiApplicationPrivate::processMouseEvent [0x7fff897b47c3] <Qt5Gui.dll>
 24> QWindowSystemInterface::sendWindowSystemEvents [0x7fff8979f030] <Qt5Gui.dll>
 25> QEventDispatcherWin32::processEvents [0x7fff893bbcfa] <Qt5Core.dll>
 26> qt_plugin_query_metadata [0x7fff889128d9] <qwindows.dll>
 27> QEventLoop::exec [0x7fff8936f64c] <Qt5Core.dll>
 28> QMenu::exec [0x7fff89f4ddd8] <Qt5Widgets.dll>
 29> QMenu::exec [0x7fff89f4db7b] <Qt5Widgets.dll>
 30> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78710cbb0] <OpenToonz.exe>
 31> QWidget::event [0x7fff89e285bd] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7fff89e055c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7fff89e03cf3] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7fff8937318a] <Qt5Core.dll>
 35> QDesktopWidget::workAreaResized [0x7fff89e50abb] <Qt5Widgets.dll>
 36> QDesktopWidget::workAreaResized [0x7fff89e4e96e] <Qt5Widgets.dll>
 37> QApplicationPrivate::notify_helper [0x7fff89e055c0] <Qt5Widgets.dll>
 38> QApplication::notify [0x7fff89e04643] <Qt5Widgets.dll>
 39> QCoreApplication::notifyInternal2 [0x7fff8937318a] <Qt5Core.dll>
 40> QGuiApplicationPrivate::processMouseEvent [0x7fff897b47c3] <Qt5Gui.dll>
 41> QWindowSystemInterface::sendWindowSystemEvents [0x7fff8979f030] <Qt5Gui.dll>
 42> QEventDispatcherWin32::processEvents [0x7fff893bbcfa] <Qt5Core.dll>
 43> qt_plugin_query_metadata [0x7fff889128d9] <qwindows.dll>
 44> QEventLoop::exec [0x7fff8936f64c] <Qt5Core.dll>
 45> QCoreApplication::exec [0x7fff89372164] <Qt5Core.dll>
 46> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff786ea5219] <OpenToonz.exe>
 47> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7872ceab7] <OpenToonz.exe>
 48> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7872ce092] <OpenToonz.exe>
 49> BaseThreadInitThunk [0x7ffffe34257d] <KERNEL32.DLL>
 50> RtlUserThreadStart [0x7fffffacaa58] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Ugee

**Comment by RodneyBaker** [comment]
Closing as a report with insufficient information to troubleshoot the problem.
@YiyuHuaiAi Please feel free to continue troubleshooting here or please open a new report detailing the problem.
