### ISSUE TITLE
opentoonz's naming convension, Italian or English

### ISSUE THREAD

**Issue by keizo042** [opentoonz/opentoonz#53]
now, I read opentoonz's code in order to  contribute you.
In reading toonz/sources/tnztools/autfilltlv.cpp,I found code named in Italian.
I want to translate into English.
What does opentoonz's dev think about it?

**Comment by odysseywestra** [comment]
I would just go ahead, fork it and just translate it. And when you are done create a pull request. The translation still be fixed in that stage if there are any errors.

**Comment by odysseywestra** [comment]
@keizo042 do you want me to assign this issue to you?

**Comment by keizo042** [comment]
@odysseywestra I think that all devate about translation had better move to #43 .  I close this issue
