### ISSUE TITLE
usability feature request: file>level export- no alpha, black background - bad default setting - change matte to be 0 by default

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#530]
When you export a level as PNG, opentoonz does not keep the alpha channel of the level. Instead what you get is a BLACK background.

When you open the image in krita - you see there is no alpha channel.

I tried with TGA,TIF and BMP- same black background.

I tried all options - I cant seem to export a level with an alpha channel from opentoonz?
Is this possible to do, is it a missing feature or a bug?

**Comment by blurymind** [comment]
@turtletooth when I open in krita - there is no information in the alpha channel:
![noalphaexported](https://cloud.githubusercontent.com/assets/6495061/16364560/3a6a8c00-3be2-11e6-99c6-9df2cf8eed2e.PNG)

would it be possible to get OT to also export the alpha- Export images with alpha that need no further editing in any other software in order to enable their alpha channel.

This is required for exporting animation as a sprite.

**Comment by turtletooth** [comment]
Does this happen for renders also or just level export?

**Comment by blurymind** [comment]
@turtletooth confirmed to be a problem only when you export levels. rendering a tif exports with alpha, exporting a level as a tif loses the alpha and has a black background

**Comment by blurymind** [comment]
@turtletooth I found it - this is actually not a bug, but rather a bad default setting:
 
![capture](https://cloud.githubusercontent.com/assets/6495061/16365249/8e275dae-3bf2-11e6-8a54-c96de89299db.PNG)

So my suggestion would be to make the matte value 0 instead of 255 by default.
All other animation software out there exports with alpha by default.Why would anyone want to have a black background instead of alpha?

**Comment by turtletooth** [comment]
I would also think that formats that don't support transparency should keep the matte seeing but change the default background to white.

**Comment by blurymind** [comment]
Yes i agree. That is another issue related to this.

**Comment by inkapnea** [comment]
It looks that changing the default general export settings to R:255, G:255, B:255, M:0
should do the trick for all the export formats.

**Comment by turtletooth** [comment]
Submitted #621

**Comment by blurymind** [comment]
nice! Thank you :D
