### ISSUE TITLE
Help Painting Board has dissapeared

### ISSUE THREAD

**Issue by linx2855** [opentoonz/opentoonz#5305]
### Ask a question related to OpenToonz

The board to draw has dissapeared in the animation section of Open Toonz
![Captura de pantalla 2024-02-17 115555](https://github.com/opentoonz/opentoonz/assets/158617363/91699985-b1d3-4404-81c0-b4b94874fde6)

**Comment by DarrenTAnims** [comment]
You've closed it.
Either bring it back by choosing it from the Windows menu (Viewer), then dock it.
Or reset your room layout from the Windows > Workspace menu.

**Comment by RodneyBaker** [comment]
Closing as likely resolved.

**Comment by linx2855** [comment]
thankss
