### ISSUE TITLE
Crashed Unexpextedly

### ISSUE THREAD

**Issue by SarvinR** [opentoonz/opentoonz#5306]
### Description

Crashes occur frequently on my computer. I couldn't use it properly.

### Steps to Reproduce

1. Open the software
2. Play a song in spotify in brave browser
3. Start drawing a small ball animation
4. draw it under 2 seconds and press right key for new frame
5. repeat this proccess.
6. when reaching a large number like 35 or 40 frames it crashes.

### Expected Behavior

I think it overflows my 6gb ram, at background brave is playing song which uses some memory.

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-02-17 17:06:30
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 3000
GPU Version: 3.1.0 - Build 9.17.10.4459

Crash File: C:\Users\Home\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240217-170630.log
Mini Dump File: C:\Users\Home\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240217-170630.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: BallBounce
Scene Name: ball flying
Project Path: C:\OpenToonz stuff\projects\BallBounce\BallBounce_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\BallBounce\scenes\ball flying.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\SYSTEM32\ig4icd64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\igd10umd64.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\Ninput.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff8484a8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8484812d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff8484d0ebe] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a65a61c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a658d75d] <OpenToonz.exe>
  6> QWidget::event [0x7ffffd79807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a658b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ffffd7755c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffffd7734e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffffcce318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ffffd7767c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ffffd7c09d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffffd7be96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffffd7755c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffffd774643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffffcce318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ffffd1247c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ffffd10f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ffffcd2bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ffff83f28d9] <qwindows.dll>
 21> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7a652efa8] <OpenToonz.exe>
 22> QCoreApplicationPrivate::sendThroughApplicationEventFilters [0x7ffffcce5112] <Qt5Core.dll>
 23> QApplicationPrivate::notify_helper [0x7ffffd775502] <Qt5Widgets.dll>
 24> QApplication::notify [0x7ffffd774643] <Qt5Widgets.dll>
 25> QCoreApplication::notifyInternal2 [0x7ffffcce318a] <Qt5Core.dll>
 26> QGuiApplicationPrivate::processTabletLeaveProximityEvent [0x7ffffd12589d] <Qt5Gui.dll>
 27> QWindowSystemInterface::sendWindowSystemEvents [0x7ffffd10f030] <Qt5Gui.dll>
 28> QEventDispatcherWin32::processEvents [0x7ffffcd2bcfa] <Qt5Core.dll>
 29> qt_plugin_query_metadata [0x7ffff83f28d9] <qwindows.dll>
 30> QEventLoop::exec [0x7ffffccdf64c] <Qt5Core.dll>
 31> QCoreApplication::exec [0x7ffffcce2164] <Qt5Core.dll>
 32> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7a64e5219] <OpenToonz.exe>
 33> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a690eab7] <OpenToonz.exe>
 34> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7a690e092] <OpenToonz.exe>
 35> BaseThreadInitThunk [0x7ff847047344] <KERNEL32.DLL>
 36> RtlUserThreadStart [0x7ff8484826b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Huion

**Comment by DarrenTAnims** [comment]
6gb is very low for OpenToonz.
If you can increase it, then that will help. Until the, close down as many programs as you can while working in OpenToonz and remember to save regularly.

**Comment by Anthonykabuimwangi** [comment]
my laptop has 16gb ram yet it crashes unexpectedly

**Comment by RodneyBaker** [comment]
@Anthonykabuimwangi Please open a separate report with whatever information you can supply.
Crashes are unfortunately but there is always a reason and if we can discover the reason we can get it addressed.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@SarvinR There are some things that can help on systems with 6GB of RAM.
I'll recommend joining one of the Opentoonz venues such as discord where others can help troubleshoot.
