### ISSUE TITLE
Opentoonz Saving crashs

### ISSUE THREAD

**Issue by jjjjjuss** [opentoonz/opentoonz#5308]
### Description

Opentoonz is crashing everytime i am trying to save using "save all"
Every help will be highly appreciated :)

### Steps to Reproduce

1. Opening Scene within random Project (could be from sandbox as from another project)
2. Modifying a vector drawing by deleting 2 lines on a calc
3. Click on "Save All"

### Expected Behavior

Loading between 0 and 3 seconds and crashing 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-02-21 21:58:42
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 8

Crash File: C:\Users\jusub\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240221-215842.log
Mini Dump File: C:\Users\jusub\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240221-215842.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: Mindvisit1 16
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\Mindvisit1 16.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\ole32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\WINTRUST.DLL
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_18524371942b1cc3\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\SYSTEM32\nvapi64.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\dcomp.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_18524371942b1cc3\nvldumdx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvdmi.inf_amd64_18524371942b1cc3\nvwgf2umx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_4de65d949492707a\igd10iumd64.dll
C:\WINDOWS\SYSTEM32\ncrypt.dll
C:\WINDOWS\SYSTEM32\NTASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_4de65d949492707a\igdgmm64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_4de65d949492707a\igc64.dll
C:\WINDOWS\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffcf9ce7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffcf9c8e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffcf9d1340e] <ntdll.dll>
  4> getClosingPoints [0x7ffc96c6e277] <tnzcore.dll>
  5> initImageIo [0x7ffcb98e9f73] <image.dll>
  6> LevelUpdater::addFramesTo [0x7ffc9ba040e2] <toonzlib.dll>
  7> LevelUpdater::update [0x7ffc9ba05c32] <toonzlib.dll>
  8> TXshSimpleLevel::saveSimpleLevel [0x7ffc9bb39701] <toonzlib.dll>
  9> TXshSimpleLevel::save [0x7ffc9bb3661f] <toonzlib.dll>
 10> SceneLevel::save [0x7ffc9ba5beb6] <toonzlib.dll>
 11> SceneResources::save [0x7ffc9ba5d24d] <toonzlib.dll>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e4156a1b] <OpenToonz.exe>
 13> QObject::qt_static_metacall [0x7ffc971120d7] <Qt5Core.dll>
 14> QAction::activate [0x7ffc9a645eff] <Qt5Widgets.dll>
 15> QMenu::actionGeometry [0x7ffc9a79c308] <Qt5Widgets.dll>
 16> QMenu::actionGeometry [0x7ffc9a79c0e3] <Qt5Widgets.dll>
 17> QMenu::mouseReleaseEvent [0x7ffc9a7a18a1] <Qt5Widgets.dll>
 18> QWidget::event [0x7ffc9a678092] <Qt5Widgets.dll>
 19> QMenu::event [0x7ffc9a79d8a7] <Qt5Widgets.dll>
 20> QApplicationPrivate::notify_helper [0x7ffc9a6555c0] <Qt5Widgets.dll>
 21> QApplication::notify [0x7ffc9a6534e0] <Qt5Widgets.dll>
 22> QCoreApplication::notifyInternal2 [0x7ffc970f318a] <Qt5Core.dll>
 23> QApplicationPrivate::sendMouseEvent [0x7ffc9a6567c5] <Qt5Widgets.dll>
 24> QDesktopWidget::workAreaResized [0x7ffc9a6a0383] <Qt5Widgets.dll>
 25> QDesktopWidget::workAreaResized [0x7ffc9a69e96e] <Qt5Widgets.dll>
 26> QApplicationPrivate::notify_helper [0x7ffc9a6555c0] <Qt5Widgets.dll>
 27> QApplication::notify [0x7ffc9a654643] <Qt5Widgets.dll>
 28> QCoreApplication::notifyInternal2 [0x7ffc970f318a] <Qt5Core.dll>
 29> QGuiApplicationPrivate::processMouseEvent [0x7ffc98d647c3] <Qt5Gui.dll>
 30> QWindowSystemInterface::sendWindowSystemEvents [0x7ffc98d4f030] <Qt5Gui.dll>
 31> QEventDispatcherWin32::processEvents [0x7ffc9713bcfa] <Qt5Core.dll>
 32> qt_plugin_query_metadata [0x7ffcb06328d9] <qwindows.dll>
 33> QEventLoop::exec [0x7ffc970ef64c] <Qt5Core.dll>
 34> QCoreApplication::exec [0x7ffc970f2164] <Qt5Core.dll>
 35> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7e3f45219] <OpenToonz.exe>
 36> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e436eab7] <OpenToonz.exe>
 37> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7e436e092] <OpenToonz.exe>
 38> BaseThreadInitThunk [0x7ffcf7f5257d] <KERNEL32.DLL>
 39> RtlUserThreadStart [0x7ffcf9ccaa58] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
You might have a corrupt vector level (PLI file) in the directory you are saving to.
In cases of corrupt vector files Opentoonz can crash just accessing the directory that contains the corrupted file.

This was fixed in Tahoma2D but the fix hasn't been ported here to Opentoonz yet.

Before doing too much though you might temporarily remove files from where you are saving... or attempt to save to another location to check for this corrupt file problem.

If not using the latest nightly release I'll recommend using that as opposed to v1.7.1.
The latest nightly will have about a years worth of enhancements and... bug fixes.

**Comment by storymind86** [comment]
Hi Rodney,

I think I am having a similar problem. Opentoonz crashes when it opens up a particular PLI file that exists within its corresponding project. Specifically, after the PLI file has uploaded all of its preview images to the level strip in Opentoonz, it almost immediately crashes. I believe that I have identified the small number of problematic levels within the PLI file, as displayed by the level strip. How can I permanently delete them from the PLI file before Opentoonz crashes?

**Comment by RodneyBaker** [comment]
Hi @storymind86,
I once had success retrieving the good frames out of someone's PLI vector level by using the import dialogues options to limit which frames get imported. I have not been successful since doing that the first time however.

Basically, down at the bottom of the Load Level dialogue, find the option to load sub level frames and enter the frames you feel confident you can recover.  For instance, if the file got corrupted it is somewhat likely that it happened near the end of the sequence so start with the early frames and leave the latter frames out.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/20b34199-22c6-49f0-a908-ed428f84df47)

If you do get the frames to load in this way quickly Save Level As under a new name before Opentoonz has a chance to know that anything else is wrong.

You could share the PLI file here and we can give it a look also.

**Comment by jjjjjuss** [comment]
Hello @RodneyBaker ,
Thank you for your comment!
I tried to load frame by frame the last Level done , the one being suspected to be the corrupted one, I didn't manage to find anything unfortunately. Is loading frame by frame the only way of checking for corrupted file ? I have 44 levels and 2049 frames..
Now I tried to modify  another level vector drawing to see if it crash and it doesn't but it takes really long (around 1min), could be the size of the project too heavy ? it's currently 158 Ko, levels (.pli files from what i understood) are going from 50454 Ko to 1 Ko. With the .bak files the total drawing folder weights 1Go.

**Comment by RodneyBaker** [comment]
I does read like you are running out of system resources.

There are a number of ways to check for corrupted files.
If the Openotoonz Browser can see the files then an icon will display with broken image.
Corrupt files may also be 0kb in size (although that isn't always the case.

If levels are loadng fine then you probably don't have a corrupt level.

In step 2 you say, "Modifying a vector drawing by deleting 2 lines on a calc".
I'm not quite sure what a 'calc' is but you should be able to draw and modify vector drawings/levels without this error.

What I personally might do if I couldn't find the problem would be to rename my stuff directory and then reinstall the latest nigtly release.  Then, I'd add those scenes back into the new stuff directory as needed.  Other scenes can still be accessed via that old struff directory but they won't be clogging up the new stuff directory.

**Comment by jjjjjuss** [comment]
Thank you for the feedback again!
I didn't find any broken images, and levels are loading fine. 

 Sorry for the lack of vocabulary , by "calc" i was meaning a frame, i am able to modify vector drawings/levels without error, the issues comes when i try to save the last changes done.
It seems to not crash if I "save scene" after each frame modification and before "saving all"

I have already tried uploading the night batch following different steps, and now following yours it still doesn't make any difference unfortunately.

**Comment by RodneyBaker** [comment]
Closing as reported problem resolved as expressed by @jjjjjuss
