### ISSUE TITLE
OpenToonz crashed

### ISSUE THREAD

**Issue by Bayramoworld** [opentoonz/opentoonz#5309]
### Description

![image](https://github.com/opentoonz/opentoonz/assets/160960142/250e65c5-bb06-4ffc-aeef-4b3729907c2f)
OpenToonz crashed

### Steps to Reproduce

1. 
2. 

### Expected Behavior

i don't know. It crashed

### Screenshots, Video & Crash Logs

![image](https://github.com/opentoonz/opentoonz/assets/160960142/881da47e-e5a7-42e4-9dde-e4739e02f150)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@Bayramoworld
Closing this report as there isn't sufficient information to diagnose the problem.
If you join one of the Opentoonz discords there are others who can help troubleshoot to include those that can converse in languages other than English.
