### ISSUE TITLE
Does not cancel the action

### ISSUE THREAD

**Issue by PortCraft3** [opentoonz/opentoonz#5316]
### Description

When trying to cancel an action, it says that there are no cancellation operations. IT IS IMPOSSIBLE TO CANCEL! What to do?

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hi @PortCraft3.
Sorry to hear you are having problems.

What is it that you are trying to cancel?
Screen shots or screen recordings will help considerably to understand the issue you are dealing with in this case.
