### ISSUE TITLE
: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Gallardo355** [opentoonz/opentoonz#5323]
### Description

As soon as i click a layer the app crashes

### Steps to Reproduce

1. 3 layers open
2.  click the last one and it crashes 

### Expected Behavior

open the 3rd layer

### Screenshots, Video & Crash Logs

![image_2024-03-06_230830929](https://github.com/opentoonz/opentoonz/assets/162544367/8ce8ead1-2e44-43ae-b2a2-b1a3c17ccaba)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Can you export this scene and share that here?
Following the steps you outline doesn't result in any problem here.
Perhaps your third vector level is corrupted?

**Comment by Gallardo355** [comment]
I restarted it a couple of times and deleted the scene and remade it and
it’s fine maybe it was corrupt thank you!
