### ISSUE TITLE
OpenToonz crashed unexpectedly

### ISSUE THREAD

**Issue by Misha-mample** [opentoonz/opentoonz#5326]
### Description

**OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-03-09 10:56:09
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4**

Crash File: C:\Users\*\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240309-105609.log
Mini Dump File: C:\Users\*\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240309-105609.dmp

==== Modules ====
D:\��������\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
D:\��������\OpenToonz\Qt5Xml.dll
D:\��������\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\GDI32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\ole32.dll
D:\��������\OpenToonz\glut64.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\OLEAUT32.dll
D:\��������\OpenToonz\Qt5SerialPort.dll
D:\��������\OpenToonz\EDSDK.dll
D:\��������\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\cfgmgr32.dll
D:\��������\OpenToonz\image.dll
D:\��������\OpenToonz\tnztools.dll
D:\��������\OpenToonz\tnzstdfx.dll
D:\��������\OpenToonz\tfarm.dll
D:\��������\OpenToonz\Qt5Widgets.dll
D:\��������\OpenToonz\sound.dll
D:\��������\OpenToonz\Qt5Core.dll
D:\��������\OpenToonz\toonzqt.dll
D:\��������\OpenToonz\Qt5Gui.dll
D:\��������\OpenToonz\toonzlib.dll
D:\��������\OpenToonz\Qt5Script.dll
D:\��������\OpenToonz\tnzext.dll
D:\��������\OpenToonz\opencv_world451.dll
D:\��������\OpenToonz\tnzbase.dll
D:\��������\OpenToonz\Qt5OpenGL.dll
D:\��������\OpenToonz\tnzcore.dll
D:\��������\OpenToonz\Qt5Multimedia.dll
D:\��������\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MFPlat.DLL
D:\��������\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MF.dll
D:\��������\OpenToonz\VCRUNTIME140.dll
D:\��������\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
D:\��������\OpenToonz\glew32.dll
D:\��������\OpenToonz\libmypaint-1-4-0.dll
D:\��������\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\NETAPI32.dll
D:\��������\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
D:\��������\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
D:\��������\OpenToonz\libintl-8.dll
D:\��������\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\��������\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
D:\��������\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
D:\��������\OpenToonz\styles\qwindowsvistastyle.dll
D:\��������\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f9db1c3e7dadaaa7\ig11icd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f9db1c3e7dadaaa7\igdml64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f9db1c3e7dadaaa7\igdgmm64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f9db1c3e7dadaaa7\igc64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\ff_vfw.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\COMCTL32.dll
C:\Program Files\SAM CoDeC Pack\Filters\FFDShow\ffdshow.ax
C:\Windows\SYSTEM32\DINPUT.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\inputhost.dll
C:\Windows\SYSTEM32\PROPSYS.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffdd0dc8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffdd0da12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffdd0df0ebe] <ntdll.dll>
  4> DriverProc [0x7ffda52332c3] <ff_vfw.dll>
  5> ICSendMessage [0x7ffda5252b9c] <MSVFW32.dll>
  6> TSmartPointerT<TXshColumn>::operator> [0x7ffdbad37498] <image.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ffdbad34bb6] <image.dll>
  8> initImageIo [0x7ffdbacd7ace] <image.dll>
  9> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76c690dae] <OpenToonz.exe>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76c692d41] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76cabeab7] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76cabe092] <OpenToonz.exe>
 13> BaseThreadInitThunk [0x7ffdcfdf7344] <KERNEL32.DLL>
 14> RtlUserThreadStart [0x7ffdd0da26b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Your crash report suggests some non standard installation.
Recommend reinstalling using defaults to include hard drive location and no use of non standard alphanumeric characters.
