### ISSUE TITLE
Glitch rendering with plastic tool

### ISSUE THREAD

**Issue by CharlieBouyaka** [opentoonz/opentoonz#533]
1)_ I import png file into opentoonz
2)_ i am using plastic tool to animate this image
![02](https://cloud.githubusercontent.com/assets/20173928/16394406/53cc99da-3cb5-11e6-9266-af9acc5669b9.png)

3)_ when i am rendering i have an animation of glitchs.
![03](https://cloud.githubusercontent.com/assets/20173928/16394418/66c56756-3cb5-11e6-82aa-54e7d678cb45.png)
![04](https://cloud.githubusercontent.com/assets/20173928/16394422/68f3f876-3cb5-11e6-83e1-3dffc264b271.png)

on mac OS X 10.10.5.

Thank you all !

(sorry i don't speak english very well)

**Comment by artisteacher** [comment]
I’m not sure about 10.10.5, but this is fixed for 10.12.4 and 10.13.2 with the latest nightly build.

**Comment by artisteacher** [comment]
This is resolved, recommend closing.
