### ISSUE TITLE
No preferences window with french interface of opentoonz 1.0.3

### ISSUE THREAD

**Issue by CharlieBouyaka** [opentoonz/opentoonz#534]
Hello,

With the french interface of opentoonz 1.0.3, I can't open the preferences window.
![capture d ecran 2016-06-27 a 22 34 25](https://cloud.githubusercontent.com/assets/20173928/16395339/9be89d50-3cb9-11e6-86e2-87f8802a12ad.png)
when i click many times on "preferences".
![capture d ecran 2016-06-27 a 22 36 35](https://cloud.githubusercontent.com/assets/20173928/16395400/ed13583c-3cb9-11e6-86ac-6b06368729ac.png)

The only way to have the preference window is to restart opentoonz and click on "preferences". during the start-up of opentoonz.
![capture d ecran 2016-06-27 a 22 47 31](https://cloud.githubusercontent.com/assets/20173928/16395437/2eeb1bb4-3cba-11e6-8ee2-be60ef692637.png)

On mac OS X 10.10.5

Thank you all

(sorry i don't speak english very well).

**Comment by turtletooth** [comment]
I don't know if this is still an issue.  But just tested on Windows with no issue.

**Comment by artisteacher** [comment]
This is ongoing (and related to #1874) but is an easy fix. The preferences item is actually loading the tool option bar. There’s a second, functional preferences item under “File”.

In OS X, standard menu items (quit, about, and preferences) are identified with certain keywords and automatically moved into the application menu.  When there are multiple menu items with the same/related  keywords, the last item seems to take on the targeted role. For quit, the keywords are quit and exit. For about, the keyword is about, and for preferences: config, settings, options, setup, or preferences. To prevent incorrect role assignment, either the keywords should be avoided for other menu items or “no role” should be assigned.

So the tool options bar item definitely needs to be assigned “no role”, just like the exit group and configure shortcut items. It might also be a good preventative measure to also set “no role” to every menu item that has settings in the name in case they cause a related translation issue in the future.
