### ISSUE TITLE
The undo feature is limited to the current frame only

### ISSUE THREAD

**Issue by MYToonz** [opentoonz/opentoonz#5343]
### Is your feature request related to a problem? Please describe

Hello guys, I hope the honorable developers add an undo feature in the new releases so that the undo is limited only to the current frame that is being used.
It stops at the last operation performed on the frame

### Describe the solution you'd like

I liked this idea in the FlipaClip application, as it is very effective and reduces the errors that occur in the undo process
The work process speeds up

In my opinion, it is possible to add this feature by activating it by setting an option for it in the main interface or setting it as preferences
Thank you

**Comment by DarrenTAnims** [comment]
There is an option in the Preferences (under the File menu), in the Saving section, called "Clear undo history when saving levels". If that is ticked, any time you click Save All, the under history is cleared. So all you need to do is to save before drawing in each frame and then the undo will only work for the actions performed on that frame.
