### ISSUE TITLE
stick figure help

### ISSUE THREAD

**Issue by home-gihub** [opentoonz/opentoonz#5347]
### Ask a question related to OpenToonz

I made a stick figure and made a rig for it using the plastoc tool, the problem is that the arms and leggs become sort of webbed. Little bits of thestick figure will strech ount in the middle of the arm and I don't want that to happen!

**Comment by RodneyBaker** [comment]
Please share some screen grabs/screen shots of what you are seeing as that will help us understand what you are experiencing.

Perhaps even better yet, you might join one of the Opentoonz discords where others can help you more directly troubleshoot problems.  Link invitation:  https://discord.gg/4tMNN9cCsD

**Comment by home-gihub** [comment]
It broke, I can't see my stick figure even thought in the xsheet I set it to show.

**Comment by RodneyBaker** [comment]
As this is more of a troubleshooting issue recommend interacting with members of the Opentoonz community who can assist in troubleshooting.  There are many places to consider but one is the Opentoonz discord.  Invitation link:  https://discord.gg/GZHTutyygF
