### ISSUE TITLE
Issue with pen pressure sensitivity

### ISSUE THREAD

**Issue by Edahel** [opentoonz/opentoonz#5350]
### Ask a question related to OpenToonz

Heya,

I haven't been able to find anyone with my issue so here we go. 

I'm using OpenToonz on my Surface Pro 8 and I have issues regarding the sensitivity of pen pressure. Pen pressure DOES work, but it works poorly: I have to press really hard on my screen for it to thicken my line. I usually draw on Clip Studio Paint and it works fine, so the problem must come from OpenToonz itself. It really cringes me to have to press so hard to get any result, and it's really no comfortable and really prevents me from drawing normally. I'm brand new to this program so I don't know if there's any way to fix this/change the pressure sensitivity. 

I find it very weird that I'm the only one with this issue and I feel like I'm just not seeing something very obivous.

Thanks in advance for any help !

**Comment by RodneyBaker** [comment]
Hi @Edahel 
There likely is a way to adjust the pressure sensitivity of your setup.
We'll have to explore more deeply your general usage and what your current settings are however.

One initial thing to look into would be your Preference settings.
For instance, are you using Windows Ink?  If so then, turn off the option for that.
Not sure you are actually using Windows however so... hard to suggest anything specific.

Also, your pen/tablet can have individualized settings for different programs... if it's any of the current tablets/pens... but we don't know anything about that as you haven't shared any of that information as of yet.

I'll guess that being new it could be that you just need to increase the Min/Max slider settings... if using toonz raster levels.
The Max setting is expontential so it will get thick almost too quickly.   If using regular raster levels then you likely will want to experiment with different mypaint brushes that have additional thickness and pressure settings.

Welcome to the Opentoonz community!

**Comment by Edahel** [comment]
I'm really embarrassed because after a lot of fumbling around I ended up finding what I was looking for ^^'

Changing min and max size of the brush didn't work for my issue, but I found under settings "Pressure gain", which was what I needed since it enabled me to increase how sensitive the brush was to pressure.

Thank you for answering and sorry that I ended up finding the solution mysef! I should've searched longer before asking
