### ISSUE TITLE
Optimize "Cutter Tool" for overlap line

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#536]
Toon boom have "cutter tool" too, by using this you can erase tail overlap line. Its very helpful for inking.

![optimize cutter tool](https://cloud.githubusercontent.com/assets/16509592/16408712/40457cd6-3d2f-11e6-9296-aa0f5691edbe.gif)

**Comment by blurymind** [comment]
We have this feature- its called "remove vector overflow". Select a line and right click on it - then "remove vector overflow".

It is limited however, as it works only on closed shapes and it can't distinguish the part of the line you want to erase - I already filed a feature request on this here  #287

**Comment by 2dvision** [comment]
This issue is duplicate.
