### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by DarkRonyOfficial** [opentoonz/opentoonz#5363]
### Description

i click a layer then its crash 

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-03-28 10:36:22
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 12

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Graphics
GPU Version: 4.6.0 Compatibility Profile Context 22.20.02.07.220824

Crash File: C:\Users\ronal\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240328-103622.log
Mini Dump File: C:\Users\ronal\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240328-103622.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Sonic and the Rise of Begus
Scene Name: Sonic Nightmare
Project Path: C:\OpenToonz stuff\projects\Sonic and the Rise of Begus\Sonic and the Rise of Begus_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Sonic and the Rise of Begus\scenes\Sonic Nightmare.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\windows\SYSTEM32\ntdll.dll
C:\windows\System32\KERNEL32.DLL
C:\windows\System32\KERNELBASE.dll
C:\windows\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\windows\System32\win32u.dll
C:\windows\System32\GDI32.dll
C:\windows\System32\gdi32full.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\windows\System32\msvcp_win.dll
C:\windows\System32\ucrtbase.dll
C:\windows\System32\SHELL32.dll
C:\windows\System32\ole32.dll
C:\windows\System32\combase.dll
C:\windows\System32\RPCRT4.dll
C:\windows\System32\COMDLG32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\windows\System32\OLEAUT32.dll
C:\windows\System32\shcore.dll
C:\windows\System32\SHLWAPI.dll
C:\windows\System32\msvcrt.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\windows\SYSTEM32\OPENGL32.dll
C:\windows\System32\ADVAPI32.dll
C:\windows\System32\sechost.dll
C:\windows\System32\SETUPAPI.dll
C:\windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\windows\SYSTEM32\GLU32.dll
C:\windows\SYSTEM32\MPR.dll
C:\windows\System32\CRYPT32.dll
C:\windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\windows\SYSTEM32\WINSPOOL.DRV
C:\windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\windows\SYSTEM32\MFPlat.DLL
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\windows\SYSTEM32\WINMM.dll
C:\windows\SYSTEM32\VERSION.dll
C:\windows\SYSTEM32\AVIFIL32.dll
C:\windows\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\windows\SYSTEM32\d3d11.dll
C:\windows\SYSTEM32\dxgi.dll
C:\windows\SYSTEM32\UxTheme.dll
C:\windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\windows\SYSTEM32\USERENV.dll
C:\windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\windows\SYSTEM32\IPHLPAPI.DLL
C:\windows\SYSTEM32\DNSAPI.dll
C:\windows\SYSTEM32\cfgmgr32.dll
C:\windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\windows\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\windows\SYSTEM32\dbgcore.DLL
C:\windows\SYSTEM32\NETUTILS.DLL
C:\windows\SYSTEM32\MFCORE.DLL
C:\windows\SYSTEM32\SRVCLI.DLL
C:\windows\SYSTEM32\CRYPTBASE.DLL
C:\windows\System32\IMM32.DLL
C:\windows\System32\NSI.dll
C:\windows\SYSTEM32\kernel.appcore.dll
C:\windows\System32\bcryptPrimitives.dll
C:\windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\windows\SYSTEM32\WTSAPI32.dll
C:\windows\SYSTEM32\windows.storage.dll
C:\windows\SYSTEM32\wintypes.dll
C:\windows\SYSTEM32\profapi.dll
C:\windows\SYSTEM32\powrprof.dll
C:\windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\windows\system32\d3d9.dll
C:\windows\SYSTEM32\directxdatabasehelper.dll
C:\windows\System32\MSCTF.dll
C:\windows\SYSTEM32\textinputframework.dll
C:\windows\SYSTEM32\CoreMessaging.dll
C:\windows\SYSTEM32\CoreUIComponents.dll
C:\windows\system32\Oleacc.dll
C:\windows\system32\UIAutomationCore.dll
C:\windows\System32\clbcatq.dll
C:\windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\windows\System32\DriverStore\FileRepository\u0382799.inf_amd64_a513539812d0ae28\B382816\atig6pxx.dll
C:\windows\System32\DriverStore\FileRepository\u0382799.inf_amd64_a513539812d0ae28\B382816\atio6axx.dll
C:\windows\SYSTEM32\DEVOBJ.dll
C:\windows\System32\WINTRUST.dll
C:\windows\SYSTEM32\MSASN1.dll
C:\windows\system32\dataexchange.dll
C:\windows\system32\twinapi.appcore.dll
C:\windows\system32\ApplicationTargetedFeatureDatabase.dll
C:\windows\system32\dwrite.dll
C:\windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\windows\SYSTEM32\dhcpcsvc6.DLL
C:\windows\SYSTEM32\dhcpcsvc.DLL
C:\windows\System32\netprofm.dll
C:\windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\windows\SYSTEM32\MMDevAPI.DLL
C:\windows\SYSTEM32\wdmaud.drv
C:\windows\SYSTEM32\AVRT.dll
C:\windows\SYSTEM32\ksuser.dll
C:\windows\SYSTEM32\AUDIOSES.DLL
C:\windows\SYSTEM32\msacm32.drv
C:\windows\SYSTEM32\midimap.dll
C:\windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\windows\system32\napinsp.dll
C:\windows\system32\pnrpnsp.dll
C:\windows\System32\winrnr.dll
C:\windows\system32\wshbth.dll
C:\windows\system32\nlansp_c.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\windows\System32\fwpuclnt.dll
C:\windows\SYSTEM32\PROPSYS.dll
C:\windows\SYSTEM32\LINKINFO.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\windows\system32\winhttp.dll
C:\windows\SYSTEM32\SspiCli.dll
C:\windows\system32\Ninput.dll
C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3235_none_270f74e173860f98\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fff2b5a7a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fff2b54e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff2b5d340e] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6e3d961c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6e3d7d75d] <OpenToonz.exe>
  6> QWidget::event [0x7ffec4d1807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6e3d7b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ffec4cf55c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffec4cf34e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffec3f2318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ffec4cf67c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ffec4d409d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ffec4d3e96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ffec4cf55c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ffec4cf4643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ffec3f2318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ffec46a47c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ffec468f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ffec3f6bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ffec31628d9] <qwindows.dll>
 21> QEventLoop::exec [0x7ffec3f1f64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7ffec3f22164] <Qt5Core.dll>
 23> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6e3cd5219] <OpenToonz.exe>
 24> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6e40feab7] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6e40fe092] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7fff2a1b257d] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7fff2b58aa58] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as a report lacking sufficient information to troubleshoot the problem.
@DarkRonyOfficial Please share any additional information you can to help others address issues you are experiencing.
