### ISSUE TITLE
Is Tahoma2D more stable than OpenToonz?

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5368]
### Ask a question related to OpenToonz

Tahoma2D crashes less than OpenToonz? Is Tahoma2D better to use for large projects?

**Comment by RodneyBaker** [comment]
If it crashes less for you it likely will be better for you.
For some Opentoonz crashes more... for others... Tahoma2D crashes more.
One of these days we might figure out why.  ;)

**Comment by unoffending** [comment]
Thank you!
