### ISSUE TITLE
problema con insertar una imagen

### ISSUE THREAD

**Issue by ferintia** [opentoonz/opentoonz#5369]
### Description

el problema es que cuando voy a insertar una imagen no me deja dice que no hay miniatura y me manda aqui por un error. Ademas no se puede abrir correctamente el programa por que me aparece la ventana que traslada aqui.
ademas cada vez que ignoro la advertencia se cierra y cuando vuelvo a abrirlo reaparece y no deja que continue.

### Steps to Reproduce

1. cuando traslado una imagen del portapapeles a una capa o columna me aparece que no hay miniatura
2. y despues sale el anuncio que me dirije aqui para solucionar el problema

### Expected Behavior

obtener la imagen en la capa y calcarla con el pincel

### Screenshots, Video & Crash Logs

![Imagen de WhatsApp 2024-03-30 a las 08 36 03_48a51f5b](https://github.com/opentoonz/opentoonz/assets/165452249/f7a1fcd2-3023-4f5c-baaf-15af91ac04a1)

### OpenToonz Version

1.7

### OpenToonz Version Information

mayo 10 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by gab3d** [comment]
Hola, qué tal?
(Este sitio es en inglés como bien se advierte en la captura que enviaste; de todas maneras te contesto en español, pero todos los desarrolladores se comunican en inglés, puesto que es un equipo internacional).

Acabo de probar a hacer una captura de pantalla y pegarla en una celda vacía de la planilla y me lo hizo sin problema. en mi caso estoy en Windows 11, pero no creo que eso haga la diferencia. mi versión de OT es la 1.7.1 igual que la tuya.

Cuando intentaste pegar la imagen en la planilla/línea de tiempo ¿te apareció este mensaje?
![imagen](https://github.com/opentoonz/opentoonz/assets/18104091/a314b6b2-0a8f-48c5-8595-bad7fa6599a3)

La imagen pegada se guardará en la carpeta "extras" de tu proyecto activo.
Cuando hacés la captura se crea una imagen vacía en dicha carpeta, con el nombre correspondiente, pero no será hasta que guardes el nivel manualmente o hasta que uses el comando "Guardar todo", que la imagen será efectivamente almacenada en el disco.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@ferintia Please let us know if you are still experiencing problems.
