### ISSUE TITLE
Export multiple (selected) levels !

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#538]
Currently OT can only export one level. It would be nice to be able to export all selected levels - especially for cutout style animation workflow. It will save a lot of time.

When exporting multiple selected levels - automatically name the frame files to the level names.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by DrimLun** [comment]
sad...
