### ISSUE TITLE
OpenToonz crashed

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5380]
### Description

I experimented with pegbar and motion paths, clicked "edit in place", tried to draw something, and then it crashed.

### Steps to Reproduce

I think this is because I was doing various tasks one at a time and OpenToonz couldn't hold up.

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-03 21:59:35
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240403-215935.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240403-215935.dmp

Application Dir: F:/Program Files/OpenToonz
Stuff Dir: F:\OpenToonz stuff

Project Name: sandbox
Scene Name: training2
Project Path: F:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: F:\OpenToonz stuff\sandbox\scenes\training2.tnz

==== Modules ====
F:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
F:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\win32u.dll
F:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\SHLWAPI.dll
F:\Program Files\OpenToonz\glut64.dll
F:\Program Files\OpenToonz\Qt5SerialPort.dll
F:\Program Files\OpenToonz\EDSDK.dll
F:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\cfgmgr32.dll
F:\Program Files\OpenToonz\image.dll
F:\Program Files\OpenToonz\tnztools.dll
F:\Program Files\OpenToonz\tnzstdfx.dll
F:\Program Files\OpenToonz\tfarm.dll
F:\Program Files\OpenToonz\Qt5Widgets.dll
F:\Program Files\OpenToonz\Qt5Gui.dll
F:\Program Files\OpenToonz\Qt5Core.dll
F:\Program Files\OpenToonz\toonzqt.dll
F:\Program Files\OpenToonz\sound.dll
F:\Program Files\OpenToonz\toonzlib.dll
F:\Program Files\OpenToonz\Qt5Script.dll
F:\Program Files\OpenToonz\opencv_world451.dll
F:\Program Files\OpenToonz\tnzext.dll
F:\Program Files\OpenToonz\tnzbase.dll
F:\Program Files\OpenToonz\tnzcore.dll
F:\Program Files\OpenToonz\Qt5OpenGL.dll
F:\Program Files\OpenToonz\Qt5Multimedia.dll
F:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
F:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
F:\Program Files\OpenToonz\VCRUNTIME140.dll
F:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
F:\Program Files\OpenToonz\glew32.dll
F:\Program Files\OpenToonz\libmypaint-1-4-0.dll
F:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
F:\Program Files\OpenToonz\Qt5Svg.dll
F:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
F:\Program Files\OpenToonz\libintl-8.dll
F:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
F:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
F:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
F:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
F:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
F:\Program Files\OpenToonz\imageformats\qgif.dll
F:\Program Files\OpenToonz\imageformats\qicns.dll
F:\Program Files\OpenToonz\imageformats\qico.dll
F:\Program Files\OpenToonz\imageformats\qjpeg.dll
F:\Program Files\OpenToonz\imageformats\qsvg.dll
F:\Program Files\OpenToonz\imageformats\qtga.dll
F:\Program Files\OpenToonz\imageformats\qtiff.dll
F:\Program Files\OpenToonz\imageformats\qwbmp.dll
F:\Program Files\OpenToonz\imageformats\qwebp.dll
F:\OpenToonz stuff\plugins\DWANGO_BlurChromaticAberration.plugin
F:\Program Files\OpenToonz\VCOMP140.DLL
F:\OpenToonz stuff\plugins\DWANGO_BlurConvolution.plugin
F:\OpenToonz stuff\plugins\DWANGO_BlurCurlNoise.plugin
F:\OpenToonz stuff\plugins\DWANGO_BlurMaskedC.plugin
F:\OpenToonz stuff\plugins\DWANGO_BlurMaskedD.plugin
F:\OpenToonz stuff\plugins\DWANGO_BlurMaskedR.plugin
F:\OpenToonz stuff\plugins\DWANGO_CoherentNoise.plugin
F:\OpenToonz stuff\plugins\DWANGO_ComposeAdd.plugin
F:\OpenToonz stuff\plugins\DWANGO_ComposeMul.plugin
F:\OpenToonz stuff\plugins\DWANGO_ComposeOptical.plugin
F:\OpenToonz stuff\plugins\DWANGO_Drip.plugin
F:\OpenToonz stuff\plugins\DWANGO_ImageQuilting.plugin
F:\OpenToonz stuff\plugins\DWANGO_Kaleidoscope.plugin
F:\OpenToonz stuff\plugins\DWANGO_LightBloom.plugin
F:\OpenToonz stuff\plugins\DWANGO_LightGlare.plugin
F:\OpenToonz stuff\plugins\DWANGO_LightIncident.plugin
F:\OpenToonz stuff\plugins\DWANGO_Paraffin.plugin
F:\OpenToonz stuff\plugins\DWANGO_PencilHatching.plugin
F:\OpenToonz stuff\plugins\DWANGO_Tiling.plugin
F:\OpenToonz stuff\plugins\DWANGO_WaveGlass.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_BlurChannels.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_Diffusion.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_LumaThreshold.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_LumaThresholdTwo.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_OneChannel.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_Selector.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_SeparateChannels.plugin
F:\OpenToonz stuff\plugins\WolfInABowl_Slide.plugin
F:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
F:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\policymanager.dll
C:\Windows\SYSTEM32\msvcp110_win.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffcea648b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffcea6212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffcea670ebe] <ntdll.dll>
  4> TRaster::clear [0x7ffcabc52aa9] <tnzcore.dll>
  5> StrokeSelection::toggle [0x7ffcbbcd9fd6] <tnztools.dll>
  6> StrokeSelection::toggle [0x7ffcbbcd419d] <tnztools.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d7dfbc6c] <OpenToonz.exe>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d7dfa6cc] <OpenToonz.exe>
  9> QWidget::event [0x7ffcb70e807c] <Qt5Widgets.dll>
 10> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d7df942b] <OpenToonz.exe>
 11> QApplicationPrivate::notify_helper [0x7ffcb70c55c0] <Qt5Widgets.dll>
 12> QApplication::notify [0x7ffcb70c34e0] <Qt5Widgets.dll>
 13> QCoreApplication::notifyInternal2 [0x7ffcac11318a] <Qt5Core.dll>
 14> QApplicationPrivate::sendMouseEvent [0x7ffcb70c67c5] <Qt5Widgets.dll>
 15> QDesktopWidget::workAreaResized [0x7ffcb71109d2] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ffcb710e96e] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ffcb70c55c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ffcb70c4643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ffcac11318a] <Qt5Core.dll>
 20> QGuiApplicationPrivate::processMouseEvent [0x7ffcadbf47c3] <Qt5Gui.dll>
 21> QWindowSystemInterface::sendWindowSystemEvents [0x7ffcadbdf030] <Qt5Gui.dll>
 22> QEventDispatcherWin32::processEvents [0x7ffcac15bcfa] <Qt5Core.dll>
 23> qt_plugin_query_metadata [0x7ffcb4bc28d9] <qwindows.dll>
 24> QEventLoop::exec [0x7ffcac10f64c] <Qt5Core.dll>
 25> QCoreApplication::exec [0x7ffcac112164] <Qt5Core.dll>
 26> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6d7d15219] <OpenToonz.exe>
 27> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d813eab7] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d813e092] <OpenToonz.exe>
 29> BaseThreadInitThunk [0x7ffcea0d7344] <KERNEL32.DLL>
 30> RtlUserThreadStart [0x7ffcea6226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
While it shouldn't be a problem...
I'll recommend installing Opentoonz on your C:Drive rather than another drive... at least until you get to the point of stable operation.

When installing just accept the defaults and see if that helps.

The only other thing in your crash report that stands out to me is a mention of codecs and possibly bad DLL (C:\Windows\SYSTEM32\AVRT.dll (?).  

If you've ran a system cleaner recently it might have cleaned more than you wanted.


You could try:

> To run a system file check (SFC) 
> 
> Go to start>Type CMD
> 
> Right click and run as Administrator (called an elevated command prompt)
> 
> If you want to verify and repair the OS type sfc /scannow (note the space between sfc and "/")
> 
> If you just want to check (verify only) the OS type sfc /verifyonly (no changes will be made using verify only)

**Comment by unoffending** [comment]
Thank you very much!

**Comment by RodneyBaker** [comment]
I thought I added another post here to also suggest this might be a one-time crash due to the specific combination of things you did just prior to the problem.  If that is indeed the case then the recommendation would be to restart your computer and Oepntoonz and just press forward.

**Comment by unoffending** [comment]
> I thought I added another post here but don't see it. This might be a one-time crash due to the specific combination of things you did just prior to the problem. If that is indeed the case then the recommendation would be to restart your computer and Oepntoonz and just press forward.

I checked in cmd and indeed some files were damaged, but luckily they are now restored

**Comment by RodneyBaker** [comment]
Closing as (mostly) a temporary problem where files are reported as restored.
