### ISSUE TITLE
EXCEPTION ACCESS VIOLATION

### ISSUE THREAD

**Issue by allanootheanimator** [opentoonz/opentoonz#5388]
### Description

I have no understanding as to what the above bug as indicated on the title means and id like further clarification

### Steps to Reproduce

1. 
2. 
Maybe using a lot of toggles

### Expected Behavior

I end up losing a lot if my work

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@allanootheanimator We'd all like additional information about the problem you are experiencing.
Any information you can share will help.

Short of that I'll recommend joining one of the Opentoonz venues such as Opentoonz discord where others can help you troubleshoot problems in real time.

OT Discord invite:  https://discord.gg/TdYmzAvEDw
