### ISSUE TITLE
export level and render - autocrop alpha of frames option

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#539]
it would be nice if the export level window had a radio box to enable automatic cropping of empty canvas area where there are no pixels.

For example if you want to export a "hand" body part level - instead of exporting the hand image and all the empty space around it (where the other body parts on on other levels are), automatically crop the exported frames.

This is required for optimization purposes when you export to a games engine and you might want to pack your images into a spritesheet.

This option would be valuable to have also in the render settings of opentoonz.

**Comment by blurymind** [comment]
Not sure if opentoonz has a built in way- but I found out that it is possible to crop a collection of images by using imagemagick's mogrify command:

`mogrify -trim +repage -alpha Background *.png `

Imagemagick is really good at procedurally editing images. :)

**Comment by turtletooth** [comment]
For the spritesheet export that I build last night, I figured out a trim that doesn't need imagemagick at all.    I'll be submitting the PR soon.

**Comment by blurymind** [comment]
nice! Thank you :D

**Comment by turtletooth** [comment]
#748 - Submitted.
