### ISSUE TITLE
IwaWarper question 

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5392]
### Ask a question related to OpenToonz

Sorry, this is more of an IwaWarper question, but I have a question.
Why are red lines needed? In the program they are signed as “show from”, but their functionality is still unclear for me. 
Also, is there any detailed manual for this program?

**Comment by DarrenTAnims** [comment]
The manual is online, linked from the Help menu. Just press F1

**Comment by unoffending** [comment]
Thank you!

**Comment by unoffending** [comment]
> The manual is online, linked from the Help menu. Just press F1

But where's help menu in IwaWraper? I can't find it...

**Comment by DarrenTAnims** [comment]
Sorry. My misunderstanding. I replied before I read it properly.
I'm not sure there is a manual for it.

**Comment by unoffending** [comment]
> Sorry. My misunderstanding. I replied before I read it properly. I'm not sure there is a manual for it.

Btw, thank you for your lessons on YouTube! It was very helpful for me!

**Comment by RodneyBaker** [comment]
The red lines are your source area.  The blue lines are the target where the source area will be projected.

**Comment by unoffending** [comment]
> The red lines are your source area. The blue lines are the target where the source area will be projected. In this way both the source area and the target area can be modified/animated separately.

Thank you very much!
