### ISSUE TITLE
How to solve the problem that the application cannot start normally (0xc000007b)

### ISSUE THREAD

**Issue by Oshio22** [opentoonz/opentoonz#5393]
### Description

At first, I couldn't find glut32.dll and couldn't execute the code. I reinstalled the software and still had the same error.
![Image_1712902130233](https://github.com/opentoonz/opentoonz/assets/166789811/b7186efc-3ca0-49d6-83fc-4069fc999a28)

Then I downloaded glut32.dll according to the method on the Internet and put it under 
Windows/sysWOW64, but I encountered a new problem. The application could not start normally (0x000007b)
![Image_1712902124918](https://github.com/opentoonz/opentoonz/assets/166789811/440eeb06-57b6-4adb-aecf-fa694a720d6b)

Why does this happen? Has anyone encountered a similar problem? How can I solve it?

### Steps to Reproduce

1. At first, I couldn't find glut32.dll and couldn't execute the code. I reinstalled the software and still had the same error.
2. 
Then I downloaded glut32.dll according to the method on the Internet and put it under 
Windows/sysWOW64, but I encountered a new problem. The application could not start normally (0x000007b)ｌ−０

### Screenshots, Video & Crash Logs

![Image_1712902130233](https://github.com/opentoonz/opentoonz/assets/166789811/1bfbef2b-0d55-4f1c-9c02-0cfc1d667dba)
![Image_1712902124918](https://github.com/opentoonz/opentoonz/assets/166789811/3b2d60a2-244a-422e-aea6-2bc311732b1d)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
This is a known problem with current nightly releases.
We'll get the current nightly build issues fixed, it will just take a little time.
In the mean time, move back a nighly release or two and you shouldn't have the problem.

**Comment by Oshio22** [comment]
> This is a known problem with current nightly releases.
> We'll get the current nightly build issues fixed, it will just take a little time.
> In the mean time, move back a nighly release or two and you shouldn't have the problem.
> 
Thanks, the problem has been solved
