### ISSUE TITLE
it freezed

### ISSUE THREAD

**Issue by Navi45Bomber** [opentoonz/opentoonz#5399]
### Description

my opentoonz freeze

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as an incomplete report.
@Navi45Bomber Please feel free to continue detailing the problem here as that will help others troubleshoot the issue.
