### ISSUE TITLE
Idk why but I clicked on second column my opentoonz crash. this is not the first time 

### ISSUE THREAD

**Issue by Navi45Bomber** [opentoonz/opentoonz#5400]
### Description

Idk why but I clicked on second column my opentoonz crash. this is not the first. it crash I need to get my animation for my class

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@Navi45Bomber I will recommend joining one of the Opentoonz disocrds where others can assist in real time and help you get the most out of your experience with Opentoonz.  It will likely be very frustrating to troubleshoot this way.

Here's a invitation link:  https://discord.gg/2PqeeyA7yz

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@Navi45Bomber please let us know if you are still experiencing problems.
