### ISSUE TITLE
why is my opentoonz crash

### ISSUE THREAD

**Issue by Navi45Bomber** [opentoonz/opentoonz#5401]
### Description

why why

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
We couldn't possibly guess.
You've not told us anything about your system (the form prompts for these details). You've just left them blank. And you haven't said what you was doing or any details about your scene or installation.
This report will likely just be deleted.
Try to share as many of these details next time please.
