### ISSUE TITLE
bug report (probably after experimenting with auto input cell number)

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5403]
### Description

I experimented with auto input cell number, deleted one of the layers and OpenToonz crashed.

### Steps to Reproduce

1. create at least 2 layers
2. experiment with auto input cell number
3. deleted one of the layers
Although it is likely that this cannot be repeated

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-15 18:57:45
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240415-185745.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240415-185745.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Testing
Scene Name: textfortesting
Project Path: C:\OpenToonz stuff\projects\Testing\Testing_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Testing\scenes\textfortesting.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\OpenToonz stuff\plugins\DWANGO_BlurChromaticAberration.plugin
C:\Program Files\OpenToonz\VCOMP140.DLL
C:\OpenToonz stuff\plugins\DWANGO_BlurConvolution.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurCurlNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedC.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedD.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedR.plugin
C:\OpenToonz stuff\plugins\DWANGO_CoherentNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeAdd.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeMul.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeOptical.plugin
C:\OpenToonz stuff\plugins\DWANGO_Drip.plugin
C:\OpenToonz stuff\plugins\DWANGO_ImageQuilting.plugin
C:\OpenToonz stuff\plugins\DWANGO_Kaleidoscope.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightBloom.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightGlare.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightIncident.plugin
C:\OpenToonz stuff\plugins\DWANGO_Paraffin.plugin
C:\OpenToonz stuff\plugins\DWANGO_PencilHatching.plugin
C:\OpenToonz stuff\plugins\DWANGO_Tiling.plugin
C:\OpenToonz stuff\plugins\DWANGO_WaveGlass.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_BlurChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Diffusion.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThreshold.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThresholdTwo.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_OneChannel.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Selector.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_SeparateChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Slide.plugin
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ffe90228b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ffe902012d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffe90250ebe] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff739c043f0] <OpenToonz.exe>
  5> QObject::qt_static_metacall [0x7ffe549420d7] <Qt5Core.dll>
  6> QAction::activate [0x7ffe55695eff] <Qt5Widgets.dll>
  7> QAction::event [0x7ffe55696ebb] <Qt5Widgets.dll>
  8> QApplicationPrivate::notify_helper [0x7ffe556a55c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ffe556a4643] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ffe5492318a] <Qt5Core.dll>
 11> QShortcutMap::dispatchEvent [0x7ffe54d896b2] <Qt5Gui.dll>
 12> QShortcutMap::tryShortcut [0x7ffe54d8bb9a] <Qt5Gui.dll>
 13> QWindowSystemInterface::handleShortcutEvent [0x7ffe54d4daef] <Qt5Gui.dll>
 14> QGuiApplicationPrivate::processKeyEvent [0x7ffe54d63e7d] <Qt5Gui.dll>
 15> QWindowSystemInterface::sendWindowSystemEvents [0x7ffe54d4f030] <Qt5Gui.dll>
 16> QEventDispatcherWin32::processEvents [0x7ffe5496bcfa] <Qt5Core.dll>
 17> qt_plugin_query_metadata [0x7ffe53a228d9] <qwindows.dll>
 18> QEventLoop::exec [0x7ffe5491f64c] <Qt5Core.dll>
 19> QCoreApplication::exec [0x7ffe54922164] <Qt5Core.dll>
 20> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff739a15219] <OpenToonz.exe>
 21> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff739e3eab7] <OpenToonz.exe>
 22> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff739e3e092] <OpenToonz.exe>
 23> BaseThreadInitThunk [0x7ffe8f9c7344] <KERNEL32.DLL>
 24> RtlUserThreadStart [0x7ffe902026b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
It sounds like you ran across some combination of processes not meant for use with the tools.
I suspect the use of Undo might also factor in but there is really no way to know at this point.

Crashes are bad.
Bugs that lead to crashes need to get addressed.
But this might be one of those cases where as the patient said to the doctor, "Doctor, it hurts when I do this!", his response was... "Well, don't do that again.  And... that'll be $50." ;)

Will plan on closing this asa a one off occurance although it might be a good place to post more of your exploration experiences.

**Comment by unoffending** [comment]
> It sounds like you ran across some combination of processes not meant for use with the tools. I suspect the use of Undo might also factor in but there is really no way to know at this point.
> 
> Crashes are bad. Bugs that lead to crashes need to get addressed. But this might be one of those cases where as the patient said to the doctor, "Doctor, it hurts when I do this!", his response was... "Well, don't do that again. And... that'll be $50." ;)
> 
> Will plan on closing this as a a one off occurance although this report might be a good place to post more of your exploration experiences.

Yes, most likely, I just did something myself that shouldn’t have been done... But... I was just trying to understand what auto input cell number is...

**Comment by RodneyBaker** [comment]
You should consider joining one of the Opentoonz discords where Opentoonz users regularly explore features, ask questions and troubleshoot problems.

**Comment by unoffending** [comment]
> You should consider joining one of the Opentoonz discords where Opentoonz users regularly explore features, ask questions and troubleshoot problems.

I think yes, you are right...
So I guess the discussion is closed?

**Comment by RodneyBaker** [comment]
As it is your report that is primarily up to you.
You can of course still comment in closed reports.
