### ISSUE TITLE
my opentoonz crash what do I do? 

### ISSUE THREAD

**Issue by Navi45Bomber** [opentoonz/opentoonz#5409]
### Description

my opentoonz crash what do I do? Idk I click it then it crash

### Steps to Reproduce

1. 
2. 
b

### Expected Behavior

b

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@Navi45Bomber The first thing to do is share more information about what you are doing at the time of the crash.
With the information you have provided there isn't much we can do.

Short of that we might suggest reinstalling as a first step.
