### ISSUE TITLE
Provide Pinning of "Plastic Tool" Vertices - Making Believable Character Movement Easier

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#541]
In conjunction with providing for the independent movement of the Plastic Tool "root" vertex - random Plastic Tool vertex pinning would make convincing character movement (relative to any stationary object) a much simpler, less convoluted task - than that which exists in OpenToonz at the present time.

Greg Smith

**Comment by psychoanima** [comment]
Similar thing I requested a month ago. My proposal was ability to change root (plastic) bone that is acting as a pin.

https://github.com/opentoonz/opentoonz/issues/359

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
