### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by senoprhobbynerd** [opentoonz/opentoonz#5413]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-20 19:14:06
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 16

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 536.19

Crash File: C:\Users\tomsv\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240420-191406.log
Mini Dump File: C:\Users\tomsv\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240420-191406.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Ex4CreatingProjects(tom)
Scene Name: untitled13
Project Path: C:\OpenToonz stuff\projects\Ex4CreatingProjects(tom)\Ex4CreatingProjects(tom)_otprj.xml
Scene Path: C:\Users\tomsv\AppData\Local\OpenToonz\OpenToonz\cache\temp\untitled13\untitled13.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvdd.inf_amd64_67b1df330bec74ef\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff92a487a7a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff92a42e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff92a4b33fe] <ntdll.dll>
  4> QObject::isWidgetType [0x7ff8a6f99a74] <Qt5Core.dll>
  5> QWidgetPrivate::showChildren [0x7ff8a7c29f9d] <Qt5Widgets.dll>
  6> QWidgetPrivate::show_helper [0x7ff8a7c2a2a4] <Qt5Widgets.dll>
  7> QWidgetPrivate::setVisible [0x7ff8a7c287b8] <Qt5Widgets.dll>
  8> QWidget::setVisible [0x7ff8a7c2855e] <Qt5Widgets.dll>
  9> QWidgetPrivate::showChildren [0x7ff8a7c2a0da] <Qt5Widgets.dll>
 10> QWidgetPrivate::show_helper [0x7ff8a7c2a2a4] <Qt5Widgets.dll>
 11> QWidgetPrivate::setVisible [0x7ff8a7c287b8] <Qt5Widgets.dll>
 12> QWidget::setVisible [0x7ff8a7c2855e] <Qt5Widgets.dll>
 13> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff70e344ce2] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff70e76eab7] <OpenToonz.exe>
 15> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff70e76e092] <OpenToonz.exe>
 16> BaseThreadInitThunk [0x7ff928eb257d] <KERNEL32.DLL>
 17> RtlUserThreadStart [0x7ff92a46aa48] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@senoprhobbynerd No one can really assist without more information.
Will plan to close this report but please feel free to add any information you can to point others in the right direction.

You may want to join one of the Opentoonz discords where others can help trouble shoot the problem.
Invitation link:  https://discord.gg/RKqNryyQ9E

**Comment by syrsly** [comment]
I reproduced this exact error trying to run OpenToonz after a successful fresh install 3 times in a row. First 2 attempts were the 'stable' release and then 1 attempt with the nightly build.

My backtrace was a little different from OP's log. It was consistent between both builds, though, which makes me think this is a common error a lot of users are probably getting and then giving up using OpenToonz rather than reporting it.

==== Backtrace ====
  1> RtlDeleteAce [0x7fffd74a8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7fffd74812d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fffd74d0ebe] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7fff8cdd2b9c] <MSVFW32.dll>
  6> ICOpen [0x7fff8cdd2d64] <MSVFW32.dll>
  7> TSmartHolderT<TXshSimpleLevel>::set [0x7fff5f1ea912] <image.dll>
  8> TSmartHolderT<TXshSimpleLevel>::set [0x7fff5f1e8a88] <image.dll>
  9> initImageIo [0x7fff5f187bd4] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6de8d1f6e] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6de8d3ea1] <OpenToonz.exe>
 12> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6ded0b147] <OpenToonz.exe>
 13> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6ded0a722] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7fffd5f47344] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7fffd74826b1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
@syrsly If you are attempting to use the latest nightlies there is a known problem that is breaking Windows builds.
If the program will not even run... you are most likely running into this problem

Workaround until that issue is addressed is to move back a few nightly releases... say to February 4th I believe... and use that nightly.

Many apologies if that is indeed the problem.

**Comment by RodneyBaker** [comment]
@syrsly You problem is likely a DIFFERENT known problem.]
Specifically one related to the Logitech webcam driver that is incompatible with Opentoonz (and other applications.
If that file (lvcod64.dll) is removed or renamed  the problem should go away.

This can be seen in your report as:  "DriverProc [0x7f8411a9] <lvcod64.dll>"

More information can be found in #5367 (and other similar reports)

**Comment by RodneyBaker** [comment]
Closing as likely resolved.
Please let us know if that is not the case.
