### ISSUE TITLE
Introduce Vector "Spline Curves" (defined by Knot positions)

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#542]
When animating, the least friendly kind of curve to have to manipulate is a Bezier Curve.  One must constantly be adjusting the control point handles - and can easily "grab" one of those handles instead of the control point, itself.  This leads to many more mouse clicks, wasted time and incompatibility problems with tools such as the "Magnet Tool" - (using a sphere of influence on both Bezier control points and handle points makes for chaotic control problems) - and the "Pinch Tool".  

(Both of the above mentioned tools are pretty much useless as of today).

Spline curves which pass directly through their control points (not B Splines) - make for very direct construction of shapes - as well as for very straightforward manipulation of these points "after the fact".

Please consider introducing this kind of spline curve and their corresponding shape creation and manipulation in a future release.

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
