### ISSUE TITLE
When I was drawing, it crashed (again)

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5423]
### Description

I'm thinking maybe there's something wrong with me?...
But before that, for some reason the line began to be drawn in red...
### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs
![раскадровка3](https://github.com/opentoonz/opentoonz/assets/109032978/91f4a9e8-495f-4e91-b046-bdef94b4f2f8)

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-24 17:34:28
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240424-173428.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240424-173428.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Новая Жизнь 3 серия
Scene Name: scene1
Project Path: C:\OpenToonz stuff\projects\Новая Жизнь 3 серия\Новая Жизнь 3 серия_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Новая Жизнь 3 серия\scenes\scene1.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\SHELL32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\msvcrt.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\shcore.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\sechost.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\OpenToonz stuff\plugins\DWANGO_BlurChromaticAberration.plugin
C:\Program Files\OpenToonz\VCOMP140.DLL
C:\OpenToonz stuff\plugins\DWANGO_BlurConvolution.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurCurlNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedC.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedD.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedR.plugin
C:\OpenToonz stuff\plugins\DWANGO_CoherentNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeAdd.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeMul.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeOptical.plugin
C:\OpenToonz stuff\plugins\DWANGO_Drip.plugin
C:\OpenToonz stuff\plugins\DWANGO_ImageQuilting.plugin
C:\OpenToonz stuff\plugins\DWANGO_Kaleidoscope.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightBloom.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightGlare.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightIncident.plugin
C:\OpenToonz stuff\plugins\DWANGO_Paraffin.plugin
C:\OpenToonz stuff\plugins\DWANGO_PencilHatching.plugin
C:\OpenToonz stuff\plugins\DWANGO_Tiling.plugin
C:\OpenToonz stuff\plugins\DWANGO_WaveGlass.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_BlurChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Diffusion.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThreshold.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThresholdTwo.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_OneChannel.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Selector.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_SeparateChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Slide.plugin
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff823148b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8231212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff823170ebe] <ntdll.dll>
  4> TPalette::getStyle [0x7fffc50d2b9d] <tnzcore.dll>
  5> PinchTool::getToolType [0x7fffe46a730f] <tnztools.dll>
  6> PinchTool::getToolType [0x7fffe46a656e] <tnztools.dll>
  7> ToolHandle::setTool [0x7fffe46696fb] <tnztools.dll>
  8> StrokeSelection::selectNone [0x7fffe46672d5] <tnztools.dll>
  9> QObject::qt_static_metacall [0x7fffc71520d7] <Qt5Core.dll>
 10> QAction::activate [0x7fffd5ce5eff] <Qt5Widgets.dll>
 11> QAction::event [0x7fffd5ce6ebb] <Qt5Widgets.dll>
 12> QApplicationPrivate::notify_helper [0x7fffd5cf55c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7fffd5cf4643] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7fffc713318a] <Qt5Core.dll>
 15> QShortcutMap::dispatchEvent [0x7fffd56c96b2] <Qt5Gui.dll>
 16> QShortcutMap::tryShortcut [0x7fffd56cbb9a] <Qt5Gui.dll>
 17> QWindowSystemInterface::handleShortcutEvent [0x7fffd568daef] <Qt5Gui.dll>
 18> QGuiApplicationPrivate::processKeyEvent [0x7fffd56a3e7d] <Qt5Gui.dll>
 19> QWindowSystemInterface::sendWindowSystemEvents [0x7fffd568f030] <Qt5Gui.dll>
 20> QEventDispatcherWin32::processEvents [0x7fffc717bcfa] <Qt5Core.dll>
 21> qt_plugin_query_metadata [0x7fffc4a228d9] <qwindows.dll>
 22> QEventLoop::exec [0x7fffc712f64c] <Qt5Core.dll>
 23> QCoreApplication::exec [0x7fffc7132164] <Qt5Core.dll>
 24> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff61ce95219] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61d2beab7] <OpenToonz.exe>
 26> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff61d2be092] <OpenToonz.exe>
 27> BaseThreadInitThunk [0x7ff821907344] <KERNEL32.DLL>
 28> RtlUserThreadStart [0x7ff8231226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by konero** [comment]
Open CMD prompt as administrator and run this command:

`sfc /scannow`

If it finds and corrects any files, restart the PC and run it again, repeat until it says nothing else is corrupted.

**Comment by unoffending** [comment]
> Open CMD prompt as administrator and run this command:
> 
> `sfc /scannow`
> 
> If it finds and corrects any files, restart the PC and run it again, repeat until it says nothing else is corrupted.

Windows Resource Protection did not detect any integrity violations

**Comment by RodneyBaker** [comment]
Will close this report and leave this reference to other reports by same author still open.
REF:  https://github.com/opentoonz/opentoonz/issues/created_by/unoffending
