### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by bobthug** [opentoonz/opentoonz#5430]
### Ask a question related to OpenToonz

why opentoonz crashed on my pc

**Comment by bobthug** [comment]
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-26 17:38:11
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) HD Graphics 620
GPU Version: 4.6.0 - Build 27.20.100.9664

Crash File: C:\Users\DELL\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240426-173811.log
Mini Dump File: C:\Users\DELL\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240426-173811.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: wild dream
Scene Name: freaky
Project Path: C:\OpenToonz stuff\projects\wild dream\wild dream_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\wild dream\scenes\freaky.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\SHELL32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\COMDLG32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\shcore.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Program Files\NETGATE\Spy Emergency\webspam.dll
C:\Windows\SYSTEM32\msimg32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_c34fd594e40bf436\ig9icd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_c34fd594e40bf436\igdml64.dll
C:\Windows\system32\atig6txx.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_c34fd594e40bf436\igdgmm64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_c34fd594e40bf436\igc64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\Ninput.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\policymanager.dll
C:\Windows\SYSTEM32\msvcp110_win.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\drprov.dll
C:\Windows\System32\WINSTA.dll
C:\Windows\System32\ntlanman.dll
C:\Windows\System32\davclnt.dll
C:\Windows\System32\DAVHLPR.dll
C:\Windows\System32\wkscli.dll
C:\Windows\SYSTEM32\cscapi.dll
C:\Windows\SYSTEM32\browcli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7fff45e08b1c] <ntdll.dll>
  2> RtlRaiseException [0x7fff45de12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fff45e30ebe] <ntdll.dll>
  4> PinchTool::getToolType [0x7ffef2e04466] <tnztools.dll>
  5> PinchTool::getToolType [0x7ffef2e04808] <tnztools.dll>
  6> PinchTool::getToolType [0x7ffef2e08e07] <tnztools.dll>
  7> PinchTool::getToolType [0x7ffef2e08cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff648d4bec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff648d4a7ee] <OpenToonz.exe>
 10> QWidget::event [0x7ffef2628092] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff648d4942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ffef26055c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ffef26034e0] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ffee165318a] <Qt5Core.dll>
 15> QApplicationPrivate::sendMouseEvent [0x7ffef26067c5] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ffef26509d2] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ffef264e96e] <Qt5Widgets.dll>
 18> QApplicationPrivate::notify_helper [0x7ffef26055c0] <Qt5Widgets.dll>
 19> QApplication::notify [0x7ffef2604643] <Qt5Widgets.dll>
 20> QCoreApplication::notifyInternal2 [0x7ffee165318a] <Qt5Core.dll>
 21> QGuiApplicationPrivate::processMouseEvent [0x7ffee1a947c3] <Qt5Gui.dll>
 22> QWindowSystemInterface::sendWindowSystemEvents [0x7ffee1a7f030] <Qt5Gui.dll>
 23> QEventDispatcherWin32::processEvents [0x7ffee169bcfa] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ffef21a28d9] <qwindows.dll>
 25> QEventLoop::exec [0x7ffee164f64c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x7ffee1652164] <Qt5Core.dll>
 27> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff648c65219] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff64908eab7] <OpenToonz.exe>
 29> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff64908e092] <OpenToonz.exe>
 30> BaseThreadInitThunk [0x7fff45837344] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7fff45de26b1] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
I'm going to guess you have either a conflict with codecs or... even more likely some antivirus or security program with over zealous settings.   For the fun of it I had ChatGPT look at your crash report and it suggested the following:

```Here are some steps you can take to troubleshoot and potentially resolve this issue:

Update Graphics Drivers: Since the crash may be related to graphical operations (as indicated by the involvement of modules like Qt5Widgets.dll and tnztools.dll which are related to the graphical interface and tools of OpenToonz), updating the graphics drivers for the Intel HD Graphics 620 could help. Ensure that the drivers are up-to-date by visiting the Intel website or using a driver management tool.
Check for Software Updates: Ensure that OpenToonz is updated to the latest version. Although the crash log shows version 1.7.1, it's good to check if any patches or newer versions have been released since then.
Reinstall OpenToonz: Sometimes, reinstalling the software can resolve underlying issues by replacing any corrupt files and resetting configurations.
Run as Administrator: Try running OpenToonz as an administrator, which can sometimes resolve access issues related to file system or registry permissions.
Disable Conflicting Software: The log shows that NETGATE Spy Emergency (via webspam.dll) is loaded, which could potentially interfere with OpenToonz. Consider temporarily disabling this or other similar security software to see if that resolves the crash.
Analyze Crash and Mini Dump Files: The detailed crash log and mini dump file (C:\Users\DELL\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240426-173811.dmp) could provide more insights. You can use tools like WinDbg or Visual Studio to open and analyze these files to get more specific information about what caused the access violation.
Check System Resources: Make sure your system isn’t running out of resources. Sometimes, insufficient memory or CPU resources can cause applications to crash unexpectedly.
Check the Specific Project and Scene: The crash may be specific to the project or scene you are working on (Project Name: wild dream, Scene Name: freaky). Try opening a different project or scene to see if the issue persists. This can help determine if the problem is with specific content within your project.```

Some of those suggestions I would have made so it's not all random garbage.
Definitely worth considering.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@bobthug Please let us know if you are still experiencing problems.
