### ISSUE TITLE
It crashed when I copied, resized, canceled

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5432]
### Description

I've noticed that OpenToonz crashes for me specifically when I copy, paste, resize, undo, and repeat.
I was trying to make the picture I uploaded look fuller as there were white spaces on the sides and it was square.
What I was trying to do is similar to the stamp tool from Photoshop..

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![ежик и мышка](https://github.com/opentoonz/opentoonz/assets/109032978/7f78eb7b-3874-4668-a184-7e7a9b955a03)

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-27 17:12:00
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240427-171200.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240427-171200.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Learning
Scene Name: Ежик и Мышка
Project Path: C:\OpenToonz stuff\projects\Learning\Learning_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Learning\scenes\Ежик и Мышка.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\OpenToonz stuff\plugins\DWANGO_BlurChromaticAberration.plugin
C:\Program Files\OpenToonz\VCOMP140.DLL
C:\OpenToonz stuff\plugins\DWANGO_BlurConvolution.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurCurlNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedC.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedD.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedR.plugin
C:\OpenToonz stuff\plugins\DWANGO_CoherentNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeAdd.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeMul.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeOptical.plugin
C:\OpenToonz stuff\plugins\DWANGO_Drip.plugin
C:\OpenToonz stuff\plugins\DWANGO_ImageQuilting.plugin
C:\OpenToonz stuff\plugins\DWANGO_Kaleidoscope.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightBloom.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightGlare.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightIncident.plugin
C:\OpenToonz stuff\plugins\DWANGO_Paraffin.plugin
C:\OpenToonz stuff\plugins\DWANGO_PencilHatching.plugin
C:\OpenToonz stuff\plugins\DWANGO_Tiling.plugin
C:\OpenToonz stuff\plugins\DWANGO_WaveGlass.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_BlurChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Diffusion.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThreshold.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThresholdTwo.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_OneChannel.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Selector.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_SeparateChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Slide.plugin
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.3636_none_60b6a03d71f818d5\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff823148b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8231212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff823170ebe] <ntdll.dll>
  4> TPalette::getStyle [0x7fffe6972b9d] <tnzcore.dll>
  5> RasterSelection::setTransformationCount [0x7fffe93e006b] <tnztools.dll>
  6> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69d75bc6c] <OpenToonz.exe>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69d75a6cc] <OpenToonz.exe>
  8> QWidget::event [0x7fffe72e807c] <Qt5Widgets.dll>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69d75942b] <OpenToonz.exe>
 10> QApplicationPrivate::notify_helper [0x7fffe72c55c0] <Qt5Widgets.dll>
 11> QApplication::notify [0x7fffe72c34e0] <Qt5Widgets.dll>
 12> QCoreApplication::notifyInternal2 [0x7fffe7f7318a] <Qt5Core.dll>
 13> QApplicationPrivate::sendMouseEvent [0x7fffe72c67c5] <Qt5Widgets.dll>
 14> QDesktopWidget::workAreaResized [0x7fffe73109d2] <Qt5Widgets.dll>
 15> QDesktopWidget::workAreaResized [0x7fffe730e96e] <Qt5Widgets.dll>
 16> QApplicationPrivate::notify_helper [0x7fffe72c55c0] <Qt5Widgets.dll>
 17> QApplication::notify [0x7fffe72c4643] <Qt5Widgets.dll>
 18> QCoreApplication::notifyInternal2 [0x7fffe7f7318a] <Qt5Core.dll>
 19> QGuiApplicationPrivate::processMouseEvent [0x7fffe60647c3] <Qt5Gui.dll>
 20> QWindowSystemInterface::sendWindowSystemEvents [0x7fffe604f030] <Qt5Gui.dll>
 21> QEventDispatcherWin32::processEvents [0x7fffe7fbbcfa] <Qt5Core.dll>
 22> qt_plugin_query_metadata [0x7fffe6f328d9] <qwindows.dll>
 23> QEventLoop::exec [0x7fffe7f6f64c] <Qt5Core.dll>
 24> QCoreApplication::exec [0x7fffe7f72164] <Qt5Core.dll>
 25> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff69d675219] <OpenToonz.exe>
 26> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69da9eab7] <OpenToonz.exe>
 27> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69da9e092] <OpenToonz.exe>
 28> BaseThreadInitThunk [0x7ff821907344] <KERNEL32.DLL>
 29> RtlUserThreadStart [0x7ff8231226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
If you can share one of the project files that is causing crashes for you it would be good to test that to see if it works on other systems.

Alternatively, if you have access to other computers it would be good to validate if you get that same instability as you do on other computers as you do on the one you are currently using.

**Comment by unoffending** [comment]
> If you can share one of the project files that is causing crashes for you it would be good to test that to see if it works on other systems.
> 
> Alternatively, if you have access to other computers it would be good to validate if you get that same instability as you do on other computers as you do on the one you are currently using.

I think you're right.
The same file can work completely differently on different computers, which means that the problem is not with OpenToonz, but with a specific PC.
But I would also note that failures occur most likely in the process of editing these projects. I would say when copying, pasting, resizing, undoing, etc.
And of course I will share the project where I had a lot of failures.
By the way, I use a different method of committing versions than OpenToonz offers, it happens using git and TortoiseGit. So don't be surprised if you see a hidden .git folder there. It is needed specifically to save project versions (but I’m sure you already know all this, but I just want to show that I also understand what I’m dealing with).
Personally, it seems to me that the crashes are not due to the version control system, since I did not create the repository in that project, which caused crashes no less.
I will send a link to a Yandex disk in which I will attach a project whose scenes often crashed. I would say that “Ежик и Мышка” and “untitled” were crashed especially often.
I will attach a link to Yandex disk. Just click the "Download All" button in the top right corner. This will be a zip file.
https://disk.yandex.ru/d/6gxVgvHtXb33EQ

**Comment by RodneyBaker** [comment]
That you @unoffending 
That helps so much to experience similar setup as you are.

The initial loading and playing of all scenes in your download works without issue.
Not that I have not attempted to edit anything at this time... just check to make sure everything works and is present in the files.

Aside:  I love that you are using git/TortoiseGit for your projects.
Most excellent.

I will plan to look deeper into your scene files tonight to see if anything stands out as being potentially problematic.

P.S.  Love the exercises.
More excellence.

**Comment by RodneyBaker** [comment]
I stand slightly corrected from my last post in that I do find your  “Ежик и Мышка” scene missing one level file.
Column 1 refers to a JPG file:  C:\Users\Alex\Downloads\Ежик и Мышка.jpg
Not sure how important that might be... just noting it isn't like the other levels encountered that are in the +extras directory like the other raster levels.  Obviously, since it is pointing to a JPG image on your harddrive that won't appear on my side.

At a guess I'd say that is a rough or layout reference image and therefore not as intrinsic to the project as the other files.

**Comment by unoffending** [comment]
> Thank you @unoffending That helps so much to experience similar setup as you are.
> 
> The initial loading and playing of all scenes in your download works without issue. Not that I have not attempted to edit anything at this time... just check to make sure everything works and is present in the files.
> 
> Aside: I love that you are using git/TortoiseGit for your projects. Most excellent.
> 
> I will plan to look deeper into your scene files tonight to see if anything stands out as being potentially problematic.
> 
> P.S. Love the exercises. More excellence.

You're welcome, @RodneyBaker! 
I would say that I also have no problems when viewing a project; crashes usually occur when editing for me.
"Aside: I love that you are using git/TortoiseGit for your projects.
Most excellent." - I'd say it's just easier for me than what OpenToonz offers, but thanks!
"P.S. Love the exercises.
More excellence." - I have re-read this phrase several times, and I understand it differently... What do you mean? Are you suggesting that I love exercise, and want there to be more excellence? Or do you mean that you love exercises and they give more excellence? Or do you mean that you liked my exercises but they need more excellence?
In any case, thank you, @RodneyBaker!

**Comment by unoffending** [comment]
> I stand slightly corrected from my last post in that I do find your “Ежик и Мышка” scene missing one level file. Column 1 refers to a JPG file: C:\Users\Alex\Downloads\Ежик и Мышка.jpg Not sure how important that might be... just noting it isn't like the other levels encountered that are in the +extras directory like the other raster levels. Obviously, since it is pointing to a JPG image on your harddrive that won't appear on my side.
> 
> At a guess I'd say that is a rough or layout reference image and therefore not as intrinsic to the project as the other files.
> 
> Added: Someone reported issues with JPG files some time ago. Related to the current problem? Unknown. Update: The only JPG related report I found related to multiple monitors where JPG images were displaying offset. Doesn't appear related to your instability problems.

Wow! But if it has something to do with the picture, I think it's because I used "download" rather than "import"... But I don't know about that.

**Comment by RodneyBaker** [comment]
I find your excercises to be very nice... excellent even.
They remind me of animation exercises of the past that were very effective for students (mostly in 3D but of course the same exercises usually apply for 2D)

In other words, if you aren't a teacher/instructor... you should be moving in that direction.  :)

**Comment by unoffending** [comment]
> I find your excercises to be very nice... excellent even. They remind me of animation exercises of the past that were very effective for students (mostly in 3D but of course the same exercises usually apply for 2D)
> 
> In other words, if you aren't a teacher/instructor... you should be moving in that direction. :)

Thanks a lot! This is very inspiring to develop!

**Comment by RodneyBaker** [comment]
Haven't been able to crash anything yet via copy/pasting and I've been trying to crash Opentoonz... like a madman.
Your scene is more robust and stable than most of mine!

I am wondering if your release you have installed might be an issue.
Your report says:  v1.7
I hope it is at least v1.7.1 but... ideally it would be one of the nightlies from at least January of this year.
Disclaimer:  I would not use current nightly releases as the builds have been failing... even to the point where you won't be able to download them at all.

BUT... v1.7... no good.
v1.7.1 better and essential as it contains a hotfix to v1.7
Even better in my estimation... a fairly recent nightly as that should contain fixes from the past year (as well as some new features)

I find myself very curious about what your system might be versus what I am using.
That can make a big difference and it might be something as simple as a different graphics card driver although I'm sure there are other major differences.  Drivers are the bane of existence in the graphics computing world and if they aren't working right ... problems.

I have not experimented a lot with your scenes and Undoing... as I'm not a big user of Undo.
I will play with Undo a lot more though and see what happens.

Your scenes don't consist of things that often trouble users.
For instance, you aren't using a lot of Plastic Meshes and such.
Your use of vector levels is... well... I don't see any vector levels.  So that's not likely a problem.
Many users, especially on lower end systems, have problems with vector drawing.

If you are in the middle of important projects I don't recommend updating Opentoonz right now...
BUT...
We really need to get you installed with a more recent release.

That and perhaps examine what Antivirus programs could (theoretically) be intercepting operations.
Some users have learned that even Windows Defender can be a bit too zealous about safeguarding file updates/creation.
Particularly for an unsigned program such as Opentoonz.

Antivirus settings do not appear to be your current problem but that's generally easier to rule out than deeper problems.

**Comment by RodneyBaker** [comment]
More random 'suggestions'... most of which really need to be used with nightly releases to be of benefit.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/3601da51-2802-4b1d-839f-4dd35b55a644)

Notes:  
Autosave:  I usually have autosave turned off in Preferences because it is 'evil' but since some fixes where added to nightly releases have it turned on and have just forgotten about it.  Don't have it save more often than every 15 minutes though.  Combine autosave with routine manual saving via 'Save All'.  Setting less than 15 minutes is asking for critical processes to be interupted.  If using old versions of Opentoonz... turn off autosave and 'Save All' manually after any major/significant change.

Undo:  Not all processes have robust or correct Undo capability.
Recommend clearing Undo History frequently.  An option in Preferences allows for Undo History to be saved after the saving of Levels. (Without this I believe Undo history is cleared upon saving of the Scene.  

Don't rely on Undo as a happy tool to move back/forward through history as not all events are recorded.
Consider opening the History window and watching what gets stored (and removed or added back in) in Undo History if Undo is a good friend and Undo/Redo is used often.  As with autosave, undo is very useful... if/when used correctly.

At the first sign of glitches with Undo... Save All and Reload the Scene (via Recent Scenes menu to grab it quickly)

**Comment by unoffending** [comment]
> More random 'suggestions'... most of which really need to be used with nightly releases to be of benefit.
> 
> ![image](https://private-user-images.githubusercontent.com/2576432/326325071-3601da51-2802-4b1d-839f-4dd35b55a644.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjM3MzIsIm5iZiI6MTcxNDM2MzQzMiwicGF0aCI6Ii8yNTc2NDMyLzMyNjMyNTA3MS0zNjAxZGE1MS0yODAyLTRiMWQtODM5Zi00ZGQzNWI1NWE2NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDQwMzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVlZDhkNThmNzViYTIyNzRmOTdkNzE1Mzk1MjMzY2I4ZWE3N2U2MzYwYjAzYzgwMTFmMGZlZmQ0MTM1OWQ5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x2hS6FvPixy179ediYxRN8JAb0u-WLPtEwmNeJ2kvLY)
> 
> Notes: Autosave: I usually have autosave turned off in Preferences because it is 'evil' but since some fixes where added to nightly releases have it turned on and have just forgotten about it. Don't have it save more often than every 15 minutes though. Combine autosave with routine manual saving via 'Save All'. Setting less than 15 minutes is asking for critical processes to be interupted. If using old versions of Opentoonz... turn off autosave and 'Save All' manually after any major/significant change.
> 
> Undo: Not all processes have robust or correct Undo capability. Recommend clearing Undo History frequently. An option in Preferences allows for Undo History to be saved after the saving of Levels. (Without this I believe Undo history is cleared upon saving of the Scene.
> 
> Don't rely on Undo as a happy tool to move back/forward through history as not all events are recorded. Consider opening the History window and watching what gets stored (and removed or added back in) in Undo History if Undo is a good friend and Undo/Redo is used often. As with autosave, undo is very useful... if/when used correctly.
> 
> At the first sign of glitches with Undo... Save All and Reload the Scene (via Recent Scenes menu to grab it quickly)
> 
> Disclaimer: None of the above are laws; just random suggestions that might be of use... or not.

Thank you very much!!
So do you recommend downloading the nightly version?
By the way, in fact, the OpenToonz version is 1.7.1. I'll attach the screenshot.
![версия opentoonz](https://github.com/opentoonz/opentoonz/assets/109032978/e7c47ae1-80fb-4b58-8106-685717b189f1)

**Comment by unoffending** [comment]
Thank you very much for the life hacks, because these are all the subtle points that should be taken into account when working with OpenToonz. I especially liked the idea of ​​using history instead of cancellation.
About the drivers... It's possible that some of the drivers might be outdated, so I should try to check them all.
"If you are in the middle of important projects I don't recommend updating Opentoonz right now..." - but even if there are important projects, I can use the version saving system, so critical points can be saved!
And yet... Do you really recommend installing the nightly version?

**Comment by unoffending** [comment]
UPD: I checked the drivers, everything seems to be ok!

**Comment by RodneyBaker** [comment]
> Do you really recommend installing the nightly version?

Definitely.

Try this nightly and see if it works good for you:
https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_1dafb775ab3c458c056c263d3fbbe5107f943500/OpenToonzSetup.exe

If it doesn't meet your expectations... uninstall and reinstall an earlier release.

With very few exceptions I personally update to nightlies often... although I do test them constantly so there is that reason.

**Comment by RodneyBaker** [comment]
No, It isn't the last one (see below).
You don't have to install that version.
Just need to install a nightly that is recent... but... not of April vintage... because... building issues are causing problems with those releases and we do not want to give you more problems.  We want... less problems.  :)

You could... randomly pick a number and match that to a date/release but...
You could also just try that nightly and see how it works for you.

The nightly link on the website will take you to the latest nighly release.
You can try that and if it doesn't work... uninstall.
I'm just trying to get you a more recent release than the one that is being very mean and nasty to you currently.  :)

**Comment by unoffending** [comment]
> > Do you really recommend installing the nightly version?
> 
> Definitely.
> 
> Try this nightly and see if it works good for you: https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_1dafb775ab3c458c056c263d3fbbe5107f943500/OpenToonzSetup.exe
> 
> If it doesn't meet your expectations... uninstall and reinstall an earlier release.
> 
> With very few exceptions I personally update to nightlies often... although I do test them constantly so there is that reason.



> No, It isn't the last one (see below). You don't have to install that version. Just need to install a nightly that is recent... but... not of April vintage... because... building issues are causing problems with those releases and we do not want to give you more problems. We want... less problems. :)
> 
> You could... randomly pick a number and match that to a date/release but... You could also just try that nightly and see how it works for you.
> 
> The nightly link on the website will take you to the latest nighly release. You can try that and if it doesn't work... uninstall. I'm just trying to get you a more recent release than the one that is being very mean and nasty to you currently. :)

Thank you! 
But this nightly version doesn't start for me, so i'll try different nightly version!

**Comment by RodneyBaker** [comment]
If I download the nightly via the website link it doesn't work so... I can't recommend that one.

**Comment by unoffending** [comment]
> If I download the nightly via the website link it doesn't work so... I can't recommend that one.

But i think, i should try it

**Comment by unoffending** [comment]
> If I download the nightly via the website link it doesn't work so... I can't recommend that one.
> 
> EDIT: Actually, if you delete or rename one file in the latest Nighty release it should run. I'll add info here.

Wow! Thank you

**Comment by unoffending** [comment]
> If I download the nightly via the website link it doesn't work so... I can't recommend that one.
> 
> EDIT: Actually, if you delete or rename one file in the latest Nighty release it should run.
> 
> ![image](https://private-user-images.githubusercontent.com/2576432/326333727-4a38cf13-e155-4f34-9fd1-58c9a032a998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjc3MDYsIm5iZiI6MTcxNDM2NzQwNiwicGF0aCI6Ii8yNTc2NDMyLzMyNjMzMzcyNy00YTM4Y2YxMy1lMTU1LTRmMzQtOWZkMS01OGM5YTAzMmE5OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDUxMDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM5NzFhODA3MmNiNTJmMDdkNDQ1MjZkMzU1NzEzNjg1ZTY4MzhkOGM3ODRlYjRkZGM1NGJhOWFkZWNmNDE1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mkLJG7_-Yd44SbA_iS-dXJL-ijspwDOnjnkck3AYDVc)
> 
> Rename or delete the file 't32bitsrv.exe' from C:\Program Files\Opentoonz\srv\ directory. This file is now obsolete and only used for the .MOV Quicktime format which now is provided by FFMPEG. It was removed long ago but a glitch in the build process has brought it back.

Thanks again!!

**Comment by unoffending** [comment]
Wow! It launched!

**Comment by unoffending** [comment]
Wow!! I really really like the way the brush paints in vector!!

**Comment by unoffending** [comment]
The nightдн version is really better!

**Comment by RodneyBaker** [comment]
Will close this report and look for other issues reported by @unoffending to resolve any other remaining issues.
