### ISSUE TITLE
Crashed after rendering and doing nothing

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5433]
### Description

I rendered my project, everything was fine at first. But after some time, OpenToonz crashed. I did not touch my project, did not perform any OpenToonz actions.
P.S. For some reason OpenToonz has been crashing for me more often lately...

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-04-27 18:25:33
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240427-182533.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240427-182533.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Learning
Scene Name: Ежик и Мышка
Project Path: C:\OpenToonz stuff\projects\Learning\Learning_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\Learning\scenes\Ежик и Мышка.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\OpenToonz stuff\plugins\DWANGO_BlurChromaticAberration.plugin
C:\Program Files\OpenToonz\VCOMP140.DLL
C:\OpenToonz stuff\plugins\DWANGO_BlurConvolution.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurCurlNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedC.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedD.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedR.plugin
C:\OpenToonz stuff\plugins\DWANGO_CoherentNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeAdd.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeMul.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeOptical.plugin
C:\OpenToonz stuff\plugins\DWANGO_Drip.plugin
C:\OpenToonz stuff\plugins\DWANGO_ImageQuilting.plugin
C:\OpenToonz stuff\plugins\DWANGO_Kaleidoscope.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightBloom.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightGlare.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightIncident.plugin
C:\OpenToonz stuff\plugins\DWANGO_Paraffin.plugin
C:\OpenToonz stuff\plugins\DWANGO_PencilHatching.plugin
C:\OpenToonz stuff\plugins\DWANGO_Tiling.plugin
C:\OpenToonz stuff\plugins\DWANGO_WaveGlass.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_BlurChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Diffusion.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThreshold.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThresholdTwo.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_OneChannel.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Selector.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_SeparateChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Slide.plugin
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff823148b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8231212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff823170ebe] <ntdll.dll>
  4> StyleEditorGUI::ColorSlider::setColor [0x7fffe86ae237] <toonzqt.dll>
  5> StyleEditor::setStyle [0x7fffe86af1aa] <toonzqt.dll>
  6> StyleEditor::onStyleSwitched [0x7fffe86ab8fe] <toonzqt.dll>
  7> StyleEditor::showEvent [0x7fffe86af54a] <toonzqt.dll>
  8> QWidget::event [0x7fffe8d9862b] <Qt5Widgets.dll>
  9> QApplicationPrivate::notify_helper [0x7fffe8d755c0] <Qt5Widgets.dll>
 10> QApplication::notify [0x7fffe8d74643] <Qt5Widgets.dll>
 11> QCoreApplication::notifyInternal2 [0x7fffe73f318a] <Qt5Core.dll>
 12> QWidgetPrivate::showChildren [0x7fffe8daa02b] <Qt5Widgets.dll>
 13> QWidgetPrivate::showChildren [0x7fffe8daa012] <Qt5Widgets.dll>
 14> QWidgetPrivate::showChildren [0x7fffe8daa012] <Qt5Widgets.dll>
 15> QWidgetPrivate::showChildren [0x7fffe8daa012] <Qt5Widgets.dll>
 16> QWidget::event [0x7fffe8d986b9] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7fffe8d755c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7fffe8d74643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7fffe73f318a] <Qt5Core.dll>
 20> QDesktopWidget::workAreaResized [0x7fffe8dc1823] <Qt5Widgets.dll>
 21> QDesktopWidget::workAreaResized [0x7fffe8dbeb04] <Qt5Widgets.dll>
 22> QApplicationPrivate::notify_helper [0x7fffe8d755c0] <Qt5Widgets.dll>
 23> QApplication::notify [0x7fffe8d74643] <Qt5Widgets.dll>
 24> QCoreApplication::notifyInternal2 [0x7fffe73f318a] <Qt5Core.dll>
 25> QGuiApplicationPrivate::processWindowStateChangedEvent [0x7fffe7d376c2] <Qt5Gui.dll>
 26> QWindowSystemInterface::sendWindowSystemEvents [0x7fffe7d1f030] <Qt5Gui.dll>
 27> QWindowSystemInterface::flushWindowSystemEvents [0x7fffe7d1b92b] <Qt5Gui.dll>
 28> 
 29> 
 30> 
 31> CallWindowProcW [0x7ff8219bef75] <USER32.dll>
 32> CallWindowProcW [0x7ff8219be9ee] <USER32.dll>
 33> glPushClientAttrib [0x7ff81768f0f0] <OPENGL32.dll>
 34> CallWindowProcW [0x7ff8219bef75] <USER32.dll>
 35> DispatchMessageW [0x7ff8219be8dc] <USER32.dll>
 36> SendMessageTimeoutW [0x7ff8219d16d3] <USER32.dll>
 37> KiUserCallbackDispatcher [0x7ff823170e64] <ntdll.dll>
 38> NtUserDispatchMessage [0x7ff821031704] <win32u.dll>
 39> DispatchMessageW [0x7ff8219be7c6] <USER32.dll>
 40> QEventDispatcherWin32::processEvents [0x7fffe743c22c] <Qt5Core.dll>
 41> qt_plugin_query_metadata [0x7fffe6f328d9] <qwindows.dll>
 42> QEventLoop::exec [0x7fffe73ef64c] <Qt5Core.dll>
 43> QCoreApplication::exec [0x7fffe73f2164] <Qt5Core.dll>
 44> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff69d675219] <OpenToonz.exe>
 45> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69da9eab7] <OpenToonz.exe>
 46> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff69da9e092] <OpenToonz.exe>
 47> BaseThreadInitThunk [0x7ff821907344] <KERNEL32.DLL>
 48> RtlUserThreadStart [0x7ff8231226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Aare you using Autosave?

**Comment by unoffending** [comment]
> Aare you using Autosave?

Yes, sure. This is an important feature for me. I have autosave enabled every... 1 minute! Perhaps too often, and some processes are interrupted when autosaving, but it is still necessary.

**Comment by RodneyBaker** [comment]
Autosave every 1 minute?  
I believe if you look that up in a dictionary that is the defintion of insanity.  ;)

**Comment by unoffending** [comment]
> Autosave every 1 minute? I believe if you look that up in a dictionary that is the defintion of insanity. ;)

Hahahahahahahahahahaha

**Comment by RodneyBaker** [comment]
Will close pending additional information.
@unoffending If you have any additional information related to this report that will be most welcome.

**Comment by unoffending** [comment]
> Will close pending additional information. @unoffending If you have any additional information related to this report that will be most welcome.

Unfortunately, I do not have and most likely never will have any information regarding this report... It was quite a long time ago...
