### ISSUE TITLE
What was OpenToonz intended to serve?

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5434]
### Ask a question related to OpenToonz

Of course, they draw projects for Hayao Miyazaki in it, but as you know, the program can be unstable.
Overall, why was this program made free, and what is it ultimately intended for?

**Comment by RodneyBaker** [comment]
Most of that is captured on the Opentoonz website:

https://opentoonz.github.io/e/index.html

**Comment by unoffending** [comment]
> Most of that is captured on the Opentoonz website:
> 
> https://opentoonz.github.io/e/index.html

Okay, thank you

**Comment by RodneyBaker** [comment]
We can discuss this more in depth of course and ultimately what Opentoonz is intended to serve depends on us and how we develop the software further.  It's a fun discussion although perhaps one best suited for other venues.

There are a number of online videos and write ups that go into more detail about Toonz, the Studio Ghibli Edition of Toonz... and the move to open source.

Long story short... we've just scratched the surface and the best is yet to come.  :)

**Comment by unoffending** [comment]
> We can discuss this more in depth of course and ultimately what Opentoonz is intended to serve depends on us and how we develop the software further. It's a fun discussion although perhaps one best suited for other venues.
> 
> There are a number of online videos and write ups that go into more detail about Toonz, the Studio Ghibli Edition of Toonz... and the move to open source.
> 
> Long story short... we've just scratched the surface and the best is yet to come. :)

Sounds inspiring!
