### ISSUE TITLE
opentoonz crashed when opening

### ISSUE THREAD

**Issue by eunanimi** [opentoonz/opentoonz#5435]
### Description

Crash Reason: EXCEPTION_ACCESS_VIOLATION

### Steps to Reproduce

1.  opened opentoonz
2. opentoonz crashed and shut down

### Expected Behavior

opentoonz crashed when opening

### Screenshots, Video & Crash Logs

![스크린샷 2024-04-28 112938](https://github.com/opentoonz/opentoonz/assets/146204467/b2f995b0-15d4-4165-8ee2-f9f7af430e90)

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

**Comment by RodneyBaker** [comment]
@eunanimi There is no information in this report that can be used to decipher the issue you are experiencing but you have taken an important step in the right direction.  We know that there is a problem. though.

Any and all information you can share will help.

**Comment by eunanimi** [comment]
I think I forgot to add in the additional info that was provided on the popup window when OT crashed. I will make sure to add that in in my next posting. And fortunately, when I doubled clicked slowly on the Opentoonz desktop shortcut icon it opened as usual. Thank you.
