### ISSUE TITLE
Crash when drawing at vector level

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5438]
### Description

I like how the brush paints at the vector level in nightly build! So, I started drawing and OpenToonz crashed!

### Steps to Reproduce

1. Download nightly build
2. Draw on vector level 

### Screenshots, Video & Crash Logs

![баг ночной версии](https://github.com/opentoonz/opentoonz/assets/109032978/ab9b3aad-32b7-488d-8428-47e6b43d2d15)

OpenToonz 1.7.1  (Build Mar  3 2024)

Report Date: 2024-04-29 10:29:19
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 650 Ti BOOST/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 472.98

Crash File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240429-102919.log
Mini Dump File: C:\Users\Alex\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240429-102919.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: test1
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\test1.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\sechost.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\cfgmgr32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3636_none_7931fb75243f97c8\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
c:\Windows\System32\tumldr.dll
c:\Windows\System32\tumintx.dll
C:\Windows\SYSTEM32\cryptsp.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.DLL
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_72959b4e763ac8f5\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\OpenToonz stuff\plugins\DWANGO_BlurChromaticAberration.plugin
C:\Program Files\OpenToonz\VCOMP140.DLL
C:\OpenToonz stuff\plugins\DWANGO_BlurConvolution.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurCurlNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedC.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedD.plugin
C:\OpenToonz stuff\plugins\DWANGO_BlurMaskedR.plugin
C:\OpenToonz stuff\plugins\DWANGO_CoherentNoise.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeAdd.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeMul.plugin
C:\OpenToonz stuff\plugins\DWANGO_ComposeOptical.plugin
C:\OpenToonz stuff\plugins\DWANGO_Drip.plugin
C:\OpenToonz stuff\plugins\DWANGO_ImageQuilting.plugin
C:\OpenToonz stuff\plugins\DWANGO_Kaleidoscope.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightBloom.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightGlare.plugin
C:\OpenToonz stuff\plugins\DWANGO_LightIncident.plugin
C:\OpenToonz stuff\plugins\DWANGO_Paraffin.plugin
C:\OpenToonz stuff\plugins\DWANGO_PencilHatching.plugin
C:\OpenToonz stuff\plugins\DWANGO_Tiling.plugin
C:\OpenToonz stuff\plugins\DWANGO_WaveGlass.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_BlurChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Diffusion.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThreshold.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_LumaThresholdTwo.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_OneChannel.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Selector.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_SeparateChannels.plugin
C:\OpenToonz stuff\plugins\WolfInABowl_Slide.plugin
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\System32\StructuredQuery.dll
C:\Windows\SYSTEM32\edputil.dll
C:\Windows\System32\appresolver.dll
C:\Windows\System32\Bcp47Langs.dll
C:\Windows\System32\SLC.dll
C:\Windows\System32\sppc.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff823148b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff8231212d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff823170ebe] <ntdll.dll>
  4> TStroke::getMaxThickness [0x7fffb71d3673] <tnzcore.dll>
  5> TRegion::addEdge [0x7fffb71c9113] <tnzcore.dll>
  6> computeRegionFeature [0x7fffb71c1df2] <tnzcore.dll>
  7> TVectorImage::deleteStroke [0x7fffb71e7584] <tnzcore.dll>
  8> ToolUtils::TRasterUndo::undo [0x7fffc8de448b] <tnztools.dll>
  9> TUndoManager::tr [0x7fffb716f56e] <tnzcore.dll>
 10> TUndoManager::undo [0x7fffb716f603] <tnzcore.dll>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73a97bdd6] <OpenToonz.exe>
 12> QObject::qt_static_metacall [0x7fffc2c020d7] <Qt5Core.dll>
 13> QAction::activate [0x7fffc4665eff] <Qt5Widgets.dll>
 14> QAction::event [0x7fffc4666ebb] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x7fffc46755c0] <Qt5Widgets.dll>
 16> QApplication::notify [0x7fffc4674643] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x7fffc2be318a] <Qt5Core.dll>
 18> QShortcutMap::dispatchEvent [0x7fffc40496b2] <Qt5Gui.dll>
 19> QShortcutMap::tryShortcut [0x7fffc404bb9a] <Qt5Gui.dll>
 20> QWindowSystemInterface::handleShortcutEvent [0x7fffc400daef] <Qt5Gui.dll>
 21> QGuiApplicationPrivate::processKeyEvent [0x7fffc4023e7d] <Qt5Gui.dll>
 22> QWindowSystemInterface::sendWindowSystemEvents [0x7fffc400f030] <Qt5Gui.dll>
 23> QEventDispatcherWin32::processEvents [0x7fffc2c2bcfa] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7fffc34d28d9] <qwindows.dll>
 25> QEventLoop::exec [0x7fffc2bdf64c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x7fffc2be2164] <Qt5Core.dll>
 27> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff73a966300] <OpenToonz.exe>
 28> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff73ad9b147] <OpenToonz.exe>
 29> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff73ad9a722] <OpenToonz.exe>
 30> BaseThreadInitThunk [0x7ff821907344] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7ff8231226b1] <ntdll.dll>
==== End ====

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

latest version

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
I think we can safely just run one report for your crashes @unoffending 
No need to spam github with every problem when we are trying to get you stable.

**Comment by unoffending** [comment]
> I think we can safely just run one report for your crashes @unoffending No need to spam github with every problem when we are trying to get you stable.
> 
> Recommend closing.

Ok, sorry
