### ISSUE TITLE
OpenToonz Crashed when I selected a Raster Brush

### ISSUE THREAD

**Issue by buckycore** [opentoonz/opentoonz#5439]
### Description

I'm not very experienced with Opentoonz. I selected a raster brush from the menu, then opentoonz crashed. It then told me to report this bug. That's all I can give you.

### Steps to Reproduce

1. I clicked the Raster Tab on the right (using the Default Drawing Room)
2. I clicked on the first brush (which was the green pencil) 
3. And then it crashed

### Expected Behavior

I would assume to just be able to select a brush like any other art program

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build May 10 2023)

### Operating System

macOS

### GPU

Other

### Graphics Tablet

XP-Pen

**Comment by RodneyBaker** [comment]
Sorry to hear you are experiencing problems.
I will recommend just pressing on as you'll like move past the problem.
I do note that you are using a Mac which might have had some earlier reports of similar issues.
Other Mac users may be able to assist in helping you through the problem.

If you can restart and press on then hopefully its just a one off problem.

cc: @artisteacher

**Comment by buckycore** [comment]
I actually figured out the problem, and solved with by just downloading the nightly build. I didn’t realize how old the stable build was, and looked through some version history stuff to see that many little issues had been rectified this mont. I also had all my Open_toonz stuff on an external hard drive, but I’m going to have all the main resources in the default location and only change the path for the project folder. This recent build also seems a lot faster!

**Comment by RodneyBaker** [comment]
Outstanding.  Thanks for following up with information on how you resolved the problem.
It's amazing how many problems get solved by using the nightly builds.
Default locations... yes... highly recommended also!

**Comment by buckycore** [comment]
Yeah, I’m literally in baby steps with this application. I had prior experience using Application formally known as Adobe Flash, but even in its more recent versions as Adobe Animate still just feels as cheap and clunky as it always did. It’s the least inspiring drawing environment ever. Even though I knew all the metephors with the Rooms and purposes of the x-sheet with my previous studies as a traditional animator, that stuff was never used with Animate/Flash, expecially the type of cheap Web animations. However, after years of just slowly picking at Opentoonz, I’m starting to get comfortable with it. It’s so much more graceful with copying and pasting cells, and the brush selections are so beautiful. Drawing in this reminds me of drawing in Autodesk’s Sketchbook Pro, which is my default drawing app before I ink things in Clip studio.
