### ISSUE TITLE
Crash: Unable to open a project file

### ISSUE THREAD

**Issue by ForestEco** [opentoonz/opentoonz#5442]
### Description

I keep getting this crash error, would like to save 2-3 hours of work.

### Steps to Reproduce

1. Just open the project location
2. Select scene

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-05-01 23:17:23
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 16

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 546.33

Crash File: C:\Users\jsafr\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240501-231723.log
Mini Dump File: C:\Users\jsafr\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240501-231723.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: Player
Scene Name: 
Project Path: E:\UNREAL ENGINE\2D Content\Woodshire_Platformer_OpenToonz\Player_Theo - Draft2\Player_otprj.xml
Scene Path: 

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2506_none_b43bab19638c9595\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_99c8019dbacde1b2\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\gpapi.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_99c8019dbacde1b2\nvgpucomp64.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\SYSTEM32\nvapi64.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igd10um64xe.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\SYSTEM32\dcomp.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_BlurChromaticAberration.plugin
C:\WINDOWS\SYSTEM32\VCOMP120.DLL
C:\WINDOWS\SYSTEM32\MSVCP120.dll
C:\WINDOWS\SYSTEM32\MSVCR120.dll
E:\OpenToonz\opencv\build\x64\vc12\bin\opencv_world310.dll
C:\WINDOWS\SYSTEM32\AVICAP32.dll
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_BlurConvolution.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_BlurCurlNoise.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_BlurMaskedC.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_BlurMaskedD.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_BlurMaskedR.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_CoherentNoise.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_ComposeAdd.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_ComposeMul.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_ComposeOptical.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_Drip.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_ImageQuilting.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_Kaleidoscope.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_LightBloom.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_LightGlare.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_LightIncident.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_Paraffin.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_PencilHatching.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_Tiling.plugin
C:\OpenToonz stuff\plugins\dwango_opentoonz_plugins_win\plugins\DWANGO_WaveGlass.plugin
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_99c8019dbacde1b2\nvldumdx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_99c8019dbacde1b2\nvwgf2umx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nvami.inf_amd64_99c8019dbacde1b2\Display.NvContainer\MessageBus.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igd10iumd64.dll
C:\WINDOWS\SYSTEM32\ControlLib.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\IntelControlLib.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igdgmm64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a4e86d7e8f40267a\igc64.dll
C:\WINDOWS\SYSTEM32\edputil.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffa13887a7a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffa1382e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffa138b33fe] <ntdll.dll>
  4> QByteArray::QByteArray [0x7ff993ef1ba6] <Qt5Core.dll>
  5> TLevel::setFrame [0x7ff993048fab] <tnzcore.dll>
  6> initImageIo [0x7ff9fe4a8ffb] <image.dll>
  7> TXshSimpleLevel::load [0x7ff9d5cafe56] <toonzlib.dll>
  8> ToonzScene::loadResources [0x7ff9d5c6281b] <toonzlib.dll>
  9> ToonzScene::load [0x7ff9d5c619fb] <toonzlib.dll>
 10> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65abd2951] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65ab7e317] <OpenToonz.exe>
 12> QObject::qt_static_metacall [0x7ff9940e20d7] <Qt5Core.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65ad678c0] <OpenToonz.exe>
 14> QObject::qt_static_metacall [0x7ff9940e20d7] <Qt5Core.dll>
 15> QListWidget::qt_static_metacall [0x7ff993c1aa1b] <Qt5Widgets.dll>
 16> QObject::qt_static_metacall [0x7ff9940e20d7] <Qt5Core.dll>
 17> QAbstractItemView::mouseReleaseEvent [0x7ff993be2a0f] <Qt5Widgets.dll>
 18> QListView::mouseReleaseEvent [0x7ff993c1346f] <Qt5Widgets.dll>
 19> QWidget::event [0x7ff9939e8092] <Qt5Widgets.dll>
 20> QFrame::event [0x7ff993a89d10] <Qt5Widgets.dll>
 21> QAbstractItemView::viewportEvent [0x7ff993be8ae8] <Qt5Widgets.dll>
 22> QCoreApplicationPrivate::sendThroughObjectEventFilters [0x7ff9940c523a] <Qt5Core.dll>
 23> QApplicationPrivate::notify_helper [0x7ff9939c55ac] <Qt5Widgets.dll>
 24> QApplication::notify [0x7ff9939c34e0] <Qt5Widgets.dll>
 25> QCoreApplication::notifyInternal2 [0x7ff9940c318a] <Qt5Core.dll>
 26> QApplicationPrivate::sendMouseEvent [0x7ff9939c67c5] <Qt5Widgets.dll>
 27> QDesktopWidget::workAreaResized [0x7ff993a109d2] <Qt5Widgets.dll>
 28> QDesktopWidget::workAreaResized [0x7ff993a0e96e] <Qt5Widgets.dll>
 29> QApplicationPrivate::notify_helper [0x7ff9939c55c0] <Qt5Widgets.dll>
 30> QApplication::notify [0x7ff9939c4643] <Qt5Widgets.dll>
 31> QCoreApplication::notifyInternal2 [0x7ff9940c318a] <Qt5Core.dll>
 32> QGuiApplicationPrivate::processMouseEvent [0x7ff9933747c3] <Qt5Gui.dll>
 33> QWindowSystemInterface::sendWindowSystemEvents [0x7ff99335f030] <Qt5Gui.dll>
 34> QEventDispatcherWin32::processEvents [0x7ff99410bcfa] <Qt5Core.dll>
 35> qt_plugin_query_metadata [0x7ff9d5a228d9] <qwindows.dll>
 36> QEventLoop::exec [0x7ff9940bf64c] <Qt5Core.dll>
 37> QCoreApplication::exec [0x7ff9940c2164] <Qt5Core.dll>
 38> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff65a9c5219] <OpenToonz.exe>
 39> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65adeeab7] <OpenToonz.exe>
 40> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff65adee092] <OpenToonz.exe>
 41> BaseThreadInitThunk [0x7ffa127b257d] <KERNEL32.DLL>
 42> RtlUserThreadStart [0x7ffa1386aa48] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
@ForestEco If you can share the project (or stuff directory) that will help.
If I try to open your project from here... that doesn't work for me either. 

As we need more information and interaction...
I'll recommend joining the Opentoonz discord where others can assist in troubleshooting.

Opentoonz discord invite:  https://discord.gg/x9ejBCDKCK

We can of course continue here but at a much slower pace.

**Comment by ForestEco** [comment]
@RodneyBaker I found a work around, I made a new project and placed the drawing files in that scene, but it took a few extra hours rigging everything once more.

I also reinstalled OT because adding DarrenT's rooms from his course ended up causing it to crash, so it seems to crash when using someone else's setup. I had noticed crashing when blending other derivative work like Tahoma, etc. But it's very stable when I use just OT.

**Comment by RodneyBaker** [comment]
Thanks for the follow up @ForestEco 
While sorry to hear of the extra work you had to do I'm glad to hear you are back to where you need to be.

Issues of custom rooms and moving files back and forth from OT to T2D remain a challenge but I'm hopeful that will all be smoothed out in time.  When in doubt perhaps the best way to share files back and forth between programs is to render the frames out into an image sequence and use those.  In this way we take everything as far as we can in one program before moving on to the other.

Keep on keeping on! :)
