### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by magodvr** [opentoonz/opentoonz#5448]
### Description

OpenToonz 1.7.1  (Build Jan 28 2024)

Report Date: 2024-05-07 16:22:38
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 8

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics 620
GPU Version: 4.6.0 - Build 26.20.100.7372

Crash File: C:\Users\partn\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240507-162238.log
Mini Dump File: C:\Users\partn\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240507-162238.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: SR
Scene Name: mirror
Project Path: D:\OT Projects\SR\SR_otprj.xml
Scene Path: D:\OT Projects\SR\scenes\mirror.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\ole32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9c1ab568b4fa57de\ig9icd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9c1ab568b4fa57de\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9c1ab568b4fa57de\igdgmm64.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\Windows\System32\Windows.System.Launcher.dll
C:\Windows\System32\msvcp110_win.dll
C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\Windows\System32\Windows.FileExplorer.Common.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\system32\NetworkExplorer.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3527_none_270e469b73872a76\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffddfe67a7a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffddfe0e242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffddfe939ee] <ntdll.dll>
  4> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6fc5e731a] <OpenToonz.exe>
  5> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6fc5876a9] <OpenToonz.exe>
  6> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6fc58526a] <OpenToonz.exe>
  7> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6fc4974ca] <OpenToonz.exe>
  8> QObject::qt_static_metacall [0x7ffd52a320d7] <Qt5Core.dll>
  9> QAction::activate [0x7ffd56f85eff] <Qt5Widgets.dll>
 10> QMenu::actionGeometry [0x7ffd570dc308] <Qt5Widgets.dll>
 11> QMenu::actionGeometry [0x7ffd570dc0e3] <Qt5Widgets.dll>
 12> QMenu::mouseReleaseEvent [0x7ffd570e18a1] <Qt5Widgets.dll>
 13> QWidget::event [0x7ffd56fb8092] <Qt5Widgets.dll>
 14> QMenu::event [0x7ffd570dd8a7] <Qt5Widgets.dll>
 15> QApplicationPrivate::notify_helper [0x7ffd56f955c0] <Qt5Widgets.dll>
 16> QApplication::notify [0x7ffd56f934e0] <Qt5Widgets.dll>
 17> QCoreApplication::notifyInternal2 [0x7ffd52a1318a] <Qt5Core.dll>
 18> QApplicationPrivate::sendMouseEvent [0x7ffd56f967c5] <Qt5Widgets.dll>
 19> QDesktopWidget::workAreaResized [0x7ffd56fe0383] <Qt5Widgets.dll>
 20> QDesktopWidget::workAreaResized [0x7ffd56fde96e] <Qt5Widgets.dll>
 21> QApplicationPrivate::notify_helper [0x7ffd56f955c0] <Qt5Widgets.dll>
 22> QApplication::notify [0x7ffd56f94643] <Qt5Widgets.dll>
 23> QCoreApplication::notifyInternal2 [0x7ffd52a1318a] <Qt5Core.dll>
 24> QGuiApplicationPrivate::processMouseEvent [0x7ffd52e547c3] <Qt5Gui.dll>
 25> QWindowSystemInterface::sendWindowSystemEvents [0x7ffd52e3f030] <Qt5Gui.dll>
 26> QEventDispatcherWin32::processEvents [0x7ffd52a5bcfa] <Qt5Core.dll>
 27> qt_plugin_query_metadata [0x7ffd6a8f28d9] <qwindows.dll>
 28> QEventLoop::exec [0x7ffd52a0f64c] <Qt5Core.dll>
 29> QMenu::exec [0x7ffd570dddd8] <Qt5Widgets.dll>
 30> QMenu::exec [0x7ffd570ddb7b] <Qt5Widgets.dll>
 31> TSmartPointerConstT<TXshPaletteLevel>::~TSmartPointerConstT<TXshPaletteLevel> [0x7ff6fc403dee] <OpenToonz.exe>
 32> QWidget::event [0x7ffd56fb85bd] <Qt5Widgets.dll>
 33> QFrame::event [0x7ffd57059d10] <Qt5Widgets.dll>
 34> QApplicationPrivate::notify_helper [0x7ffd56f955c0] <Qt5Widgets.dll>
 35> QApplication::notify [0x7ffd56f93cf3] <Qt5Widgets.dll>
 36> QCoreApplication::notifyInternal2 [0x7ffd52a1318a] <Qt5Core.dll>
 37> QDesktopWidget::workAreaResized [0x7ffd56fe0abb] <Qt5Widgets.dll>
 38> QDesktopWidget::workAreaResized [0x7ffd56fde96e] <Qt5Widgets.dll>
 39> QApplicationPrivate::notify_helper [0x7ffd56f955c0] <Qt5Widgets.dll>
 40> QApplication::notify [0x7ffd56f94643] <Qt5Widgets.dll>
 41> QCoreApplication::notifyInternal2 [0x7ffd52a1318a] <Qt5Core.dll>
 42> QGuiApplicationPrivate::processMouseEvent [0x7ffd52e547c3] <Qt5Gui.dll>
 43> QWindowSystemInterface::sendWindowSystemEvents [0x7ffd52e3f030] <Qt5Gui.dll>
 44> QEventDispatcherWin32::processEvents [0x7ffd52a5bcfa] <Qt5Core.dll>
 45> qt_plugin_query_metadata [0x7ffd6a8f28d9] <qwindows.dll>
 46> QEventLoop::exec [0x7ffd52a0f64c] <Qt5Core.dll>
 47> QCoreApplication::exec [0x7ffd52a12164] <Qt5Core.dll>
 48> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6fc3862c0] <OpenToonz.exe>
 49> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6fc7b7ff7] <OpenToonz.exe>
 50> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff6fc7b75d2] <OpenToonz.exe>
 51> BaseThreadInitThunk [0x7ffdde84257d] <KERNEL32.DLL>
 52> RtlUserThreadStart [0x7ffddfe4aa48] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
All those "No response" fields and no repeating steps means this report will likely be deleted.

**Comment by RodneyBaker** [comment]
Well, not deleted but closed.
@magodvr Any and all information you can provide will help us assist you.

**Comment by magodvr** [comment]
Ok. Thank you.
