### ISSUE TITLE
How to reset all the settings?

### ISSUE THREAD

**Issue by anhle111** [opentoonz/opentoonz#5456]
### Ask a question related to OpenToonz

How to reset all the setting?

**Comment by RodneyBaker** [comment]
I'm assuming you've moved your windows around and would like those to return.

Try:

![image](https://github.com/opentoonz/opentoonz/assets/2576432/02efc860-55e6-4e9b-b81c-1717d1d87fa7)

**Comment by anhle111** [comment]
but I accidentally deleted them all while I was learning how to use OpenToonz
![OpenToonz 1 6 5_14_2024 12_38_14 PM](https://github.com/opentoonz/opentoonz/assets/169647825/15c51b4d-fae8-44c0-9eb1-6b03947060c5)

**Comment by RodneyBaker** [comment]
They aren't deleted... just covered up.
See your other report for the means to restore the layout:  #5458

**Comment by RodneyBaker** [comment]
Will close as likely resolved.
@anhle111 Please let us know if that is not the case.
