### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by VIKRAMJAISWAR** [opentoonz/opentoonz#5462]
### Is your feature request related to a problem? Please describe

OpenToonz 1.7  (Build Mar 14 2023)

Report Date: 2024-05-19 21:41:10
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22621
CPU Threads: 4

Crash File: C:\Users\Vikram\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240519-214110.log
Mini Dump File: C:\Users\Vikram\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240519-214110.dmp

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\msvcrt.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\ole32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0373004.inf_amd64_1504ed339c86207a\B371320\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0373004.inf_amd64_1504ed339c86207a\B371320\atio6axx.dll
C:\Windows\SYSTEM32\dxva2.dll
C:\Windows\System32\DriverStore\FileRepository\u0373004.inf_amd64_1504ed339c86207a\B371320\atig6txx.dll
C:\Windows\SYSTEM32\atiadlxx.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\pdh.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Windows\SYSTEM32\ff_vfw.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.608_none_a9444ca7c10bb01d\COMCTL32.dll
C:\Windows\system32\ffdshow.ax
C:\Windows\system32\DINPUT.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\inputhost.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff9b9107a2a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff9b90ae232] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff9b9132cee] <ntdll.dll>
  4> DriverProc [0x7ff92d4452e3] <ff_vfw.dll>
  5> ICSendMessage [0x7ff98a40413e] <MSVFW32.dll>
  6> TSmartPointerT<TXshColumn>::operator> [0x7ff933227498] <image.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff933224bb6] <image.dll>
  8> initImageIo [0x7ff9331c7ace] <image.dll>
  9> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff650ba0dae] <OpenToonz.exe>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff650ba2d41] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff650fceab7] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff650fce092] <OpenToonz.exe>
 13> BaseThreadInitThunk [0x7ff9b72126bd] <KERNEL32.DLL>
 14> RtlUserThreadStart [0x7ff9b90ea9f8] <ntdll.dll>
==== End ====

### Describe the solution you'd like

Installation problem

**Comment by RodneyBaker** [comment]
RE:  DriverProc [0x7ff92d4452e3] <ff_vfw.dll>
Etc.

I'm going to guess you have the K-Lite Codec pack installed on your system and that is causing problems.

See if that isn't installed to a location such as:  C:\Program Files\K-Lite Codec Pack\ffdshow

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@VIKRAMJAISWAR Please let us know if your problem persists.
