### ISSUE TITLE
Sctipts

### ISSUE THREAD

**Issue by TA-ANIM8** [opentoonz/opentoonz#5468]
### Ask a question related to OpenToonz

Uh, I'm Having a lot of problems with opentoonz and I'm wondering whether it's because my script isn't the same as others, so i wanted to ask where I can get or where I can find a script that suits the workflow of someone who creates Cut-out Rigs

**Comment by RodneyBaker** [comment]
Can you share more information on your script?
Most scripting in Opentoonz doesn't work but at least knowing what script you are using... or the workflow... that will help.

I'm not aware of any scripting that aides with cutout rigging.

**Comment by RodneyBaker** [comment]
Will recommend joining one of the Opentoonz discords where information about scripting, rigging and much much more are routinely answered.
