### ISSUE TITLE
Will you release 1.8 today?

### ISSUE THREAD

**Issue by unoffending** [opentoonz/opentoonz#5480]
### Ask a question related to OpenToonz

I just read on discord that the estimated release date is June 1st... I'll just be gone soon, so I thought maybe I'll have time to update OpenToonz for one person.
I'm not rushing you! I just wanted to know if version 1.8 will be available today...

**Comment by RodneyBaker** [comment]
Perhaps thie following is where you read about the estimated release date of 1 June?  
Link:  https://github.com/opentoonz/opentoonz/issues/5206

Note the update to a later estimated and still quite tentative date.

**Comment by unoffending** [comment]
> Thanks for the insterest. No, version 1.8 will not be released today.
> 
> Perhaps thie following is where the post you read on discord is sourced from which once estimated the release date asf 1 June? Link: #5206
> 
> Note the update to a later estimated and still quite tentative date.

Thanks for answer!
![когда выйдет](https://github.com/opentoonz/opentoonz/assets/109032978/98533344-295a-4c0e-820c-4c4acd8fe79f)
