### ISSUE TITLE
OpenToonz Immediately Crashes upon brand-new fresh install

### ISSUE THREAD

**Issue by SaturaniumYT** [opentoonz/opentoonz#5482]
### Description

I am compiling this message on my other linux desktop, but I had just gotten the app today and it crashed immediately upon opening it after i made a brand-new fresh install of the app. I do not have the crash report on hand on my linux desktop. This happened on my Windows 10 Laptop.
Laptop Model: Dell Latitude 7389 (2017)
CPU: Intel Core i7 vPro 7th gen
OS: Windows 10 Pro
GPU: Unknown Type of Intel GPU

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
There isn't enough information in your report to diagnose the problem but odds are that you have one of the two most frequently occurring problems.  If so then renaming a file or directory will likely get you operating.

Look through the recent reports, perhaps especially the closed reports and you will see those reports.
One of those is the Logitech webcam driver issue and the other relates to support for MOV format.

**Comment by RodneyBaker** [comment]
Closing as a report that lacks actionable information to address the problem ALTHOUGH the report reads exactly as many other reports that relate to known problems that can be addressed by renaming a file or directory.

REF:  #5351 and #5551
