### ISSUE TITLE
OpenToonz crashes after adding the following expression: "col1.angle"

### ISSUE THREAD

**Issue by DaProfessor** [opentoonz/opentoonz#5488]
### Description

I setup a scene where I wanted to control one object by another's behavior. I used the expression, "col1.angle", to do so. When I attempted to re-save the scene, OpenToonz crashed.

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build May 10 2023)

Report Date: 2024-06-07 15:19:22
Crash Reason: (SIGABRT) Usually caused by an abort() or assert()

Build ABI: x86_64-little_endian-lp64
Operating System: macOS 10.16
OS Kernel: 23.5.0
CPU Threads: 8

Crash File: /Users/williamjoel/Library/Application Support/OpenToonz/OpenToonz/crash/Crash-20240607-151922.log

Application Dir: /Applications/OpenToonz.app/Contents/MacOS
Stuff Dir: /Applications/OpenToonz/OpenToonz_stuff

Project Name: Stop Motion Analysis
Scene Name: basicWalkCycle
Project Path: /Users/williamjoel/Box Sync/Animation/Stop Motion Analysis/Stop Motion Analysis_otprj.xml
Scene Path: /Users/williamjoel/Box Sync/Animation/Stop Motion Analysis/scenes/basicWalkCycle.tnz

==== Backtrace ====
  1> 3   ???                                 0x0000600001ce0ec5 0x0 + 105553146547909
  2> 4   libsystem_c.dylib                   0x00007ff80822ca79 abort + 126
  3> 5   AppleIntelKBLGraphicsGLDriver       0x00007ffa207105fb _ZN4llvm22report_bad_alloc_errorEPKcb + 91
  4> 6   AppleIntelKBLGraphicsGLDriver       0x00007ffa2071060b _ZL25out_of_memory_new_handlerv + 11
  5> 7   libc++abi.dylib                     0x00007ff8082c135b _Znwm + 43
  6> 8   libtnzcore.dylib                    0x00000001051de850 _ZN12_GLOBAL__N_16escapeENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 304
  7> 9   libtnzcore.dylib                    0x00000001051de633 _ZN8TOStreamlsENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 371
  8> 10  libtnzbase.dylib                    0x0000000104d30a4d _ZNK15TDoubleKeyframe8saveDataER8TOStream + 4365
  9> 11  libtnzbase.dylib                    0x0000000104d38fab _ZN12TDoubleParam8saveDataER8TOStream + 395
 10> 12  libtnzcore.dylib                    0x00000001051df6e5 _ZN8TOStreamlsER8TPersist + 21
 11> 13  libtoonzlib.dylib                   0x00000001058381a3 _ZN12TStageObject8saveDataER8TOStream + 3539
 12> 14  libtoonzlib.dylib                   0x0000000105843bd4 _ZN16TStageObjectTree8saveDataER8TOStreamiP7TXsheet + 2260
 13> 15  libtoonzlib.dylib                   0x000000010585639b _ZN7TXsheet8saveDataER8TOStream + 843
 14> 16  libtnzcore.dylib                    0x00000001051df6e5 _ZN8TOStreamlsER8TPersist + 21
 15> 17  libtoonzlib.dylib                   0x0000000105809f24 _ZN10ToonzScene4saveERK9TFilePathP7TXsheet + 4260
 16> 18  OpenToonz                           0x0000000103cc01ff _ZN5IoCmd9saveSceneERK9TFilePathi + 2527
 17> 19  OpenToonz                           0x0000000103cbecff _ZN5IoCmd9saveSceneEi + 175
 18> 20  OpenToonz                           0x0000000103cbeb84 _ZN5IoCmd7saveAllEi + 20
 19> 21  QtCore                              0x00000001097a1bac _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3868
 20> 22  QtWidgets                           0x0000000107da71a6 _ZN7QAction8activateENS_11ActionEventE + 310
 21> 23  QtCore                              0x0000000109799b5d _ZN7QObject5eventEP6QEvent + 957
 22> 24  QtWidgets                           0x0000000107db052d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
 23> 25  QtWidgets                           0x0000000107db18f2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 466
 24> 26  QtCore                              0x000000010976f7f4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
 25> 27  QtCore                              0x0000000109770923 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData + 691
 26> 28  libqcocoa.dylib                     0x0000000104674352 qt_plugin_instance + 197794
 27> 29  libqcocoa.dylib                     0x0000000104674a58 qt_plugin_instance + 199592
 28> 30  CoreFoundation                      0x00007ff8083e4087 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 29> 31  CoreFoundation                      0x00007ff8083e4029 __CFRunLoopDoSource0 + 157
 30> 32  CoreFoundation                      0x00007ff8083e3df4 __CFRunLoopDoSources0 + 215
 31> 33  CoreFoundation                      0x00007ff8083e2a71 __CFRunLoopRun + 919
 32> 34  CoreFoundation                      0x00007ff8083e2112 CFRunLoopRunSpecific + 557
 33> 35  HIToolbox                           0x00007ff812dfba09 RunCurrentEventLoopInMode + 292
 34> 36  HIToolbox                           0x00007ff812dfb816 ReceiveNextEventCommon + 665
 35> 37  HIToolbox                           0x00007ff812dfb561 _BlockUntilNextEventMatchingListInModeWithFilter + 66
 36> 38  AppKit                              0x00007ff80ba52c61 _DPSNextEvent + 880
 37>  38> sh: addr2line: command not found
 39> 41  libqcocoa.dylib                     0x000000010467386c qt_plugin_instance + 195004
 40> 42  QtCore                              0x000000010976b97f _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
 41> 43  QtCore                              0x000000010976fd82 _ZN16QCoreApplication4execEv + 130
 42> 44  OpenToonz                           0x00000001039bee07 main + 16487
 43> 45  dyld                                0x00007ff807f7b366 start + 1942
==== End ====

### OpenToonz Version

1.7

### Operating System

macOS

### GPU

Other

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Opentoonz shouldn't crash when invalid expressions are used but apparently that is what you are encountering here.
Try "col2.rot" for rotation and you should be able to get basically the same thing as what you likely are after with the use of 'angle'.

In my experience incorrect entries usually just sit there and stare at us doing nothing.
It's very curious why in your case it leads to a crash.

There is an 'angle' that can be used but that is with Plastic vertexes.

![image](https://github.com/opentoonz/opentoonz/assets/2576432/6709a21c-47a3-49af-9993-e1b625c01148)

In this image we can see what channels are available to us in normal columns (in this case a mesh column but those have the same channels as regular columns.  In plastic meshes we have a more limited number of channels... one of which is 'angle'.

There are of course other expressions we can use.
If you ever want to know what expressions are legitimate start typing the 'word' into the expression field and whenyou type the first letter Opentoonz will list all of the available options for that lette BESIDES the channels names.

We can also copy/paste things we've selected and drag and drop which can help with those really long expressions referring to channels.

At any rate, try a legitimate expression and see if that works.

**Comment by RodneyBaker** [comment]
Since we are here...

There is an option in Preferences designed to automatically update expressions when we move columns as that can break connections and even lead to circular (self referencing) expressions.  That can lead to lock ups, crashes and expressions that just don't work.  If using expressions a lot you'll like want to have that option turned on:

![image](https://github.com/opentoonz/opentoonz/assets/2576432/9b5910a0-a7b1-4abf-9169-77bde6e82909)

**Comment by RodneyBaker** [comment]
Interestingly, I do appear to get values using 'col1.angle'... and no crashing.
Very interesting.

**Comment by RodneyBaker** [comment]
Try using the 'col1.angle' expression again but with the option in Preferences on.
After settnig up, Save All and then reopen the scene (use Recent scenes to quickly find it).

See if that still crashes for you.

It's possible it could be a one off crash or related to the content you are using so if still crashing use some generic scene with simple levels.

**Comment by DaProfessor** [comment]
Thanks! I got it work by using "rot" instead of "angle".
________________________________
