### ISSUE TITLE
opentooz

### ISSUE THREAD

**Issue by Andy4593** [opentoonz/opentoonz#5492]
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-06-12 11:45:49
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 4

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Vega 3 Graphics
GPU Version: 4.6.0 Compatibility Profile Context 22.20.44.221025

Crash File: C:\Users\Rohan\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240612-114549.log
Mini Dump File: C:\Users\Rohan\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240612-114549.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: icc t20 india
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\icc t20 india.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\GDI32.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0386004.inf_amd64_1e67c8d8a52858e9\B385477\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0386004.inf_amd64_1e67c8d8a52858e9\B385477\atio6axx.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\system32\Ninput.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\urlmon.dll
C:\WINDOWS\SYSTEM32\iertutil.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffbf6727a7a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffbf66ce242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffbf6753b1e] <ntdll.dll>
  4> TSmartPointerT<TData>::TSmartPointerT<TData> [0x7ffb9edb2c48] <tnzcore.dll>
  5> TPalette::getPaletteName [0x7ffb9ede82d5] <tnzcore.dll>
  6> StyleEditor::onStyleSwitched [0x7ffb9f65b90f] <toonzqt.dll>
  7> QObject::qt_static_metacall [0x7ffb9fad20d7] <Qt5Core.dll>
  8> TPaletteHandle::setPalette [0x7ffb9f27663b] <toonzlib.dll>
  9> PaletteController::editLevelPalette [0x7ffb9f296630] <toonzlib.dll>
 10> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff76f6ffb70] <OpenToonz.exe>
 11> QObject::qt_static_metacall [0x7ffb9fad20d7] <Qt5Core.dll>
 12> TSceneHandle::setScene [0x7ffb9f276916] <toonzlib.dll>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76f8c2c28] <OpenToonz.exe>
 14> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76f86e317] <OpenToonz.exe>
 15> QObject::qt_static_metacall [0x7ffb9fad20d7] <Qt5Core.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76fa578c0] <OpenToonz.exe>
 17> QObject::qt_static_metacall [0x7ffb9fad20d7] <Qt5Core.dll>
 18> QListWidget::qt_static_metacall [0x7ffba079aa1b] <Qt5Widgets.dll>
 19> QObject::qt_static_metacall [0x7ffb9fad20d7] <Qt5Core.dll>
 20> QAbstractItemView::mouseReleaseEvent [0x7ffba0762a0f] <Qt5Widgets.dll>
 21> QListView::mouseReleaseEvent [0x7ffba079346f] <Qt5Widgets.dll>
 22> QWidget::event [0x7ffba0568092] <Qt5Widgets.dll>
 23> QFrame::event [0x7ffba0609d10] <Qt5Widgets.dll>
 24> QAbstractItemView::viewportEvent [0x7ffba0768ae8] <Qt5Widgets.dll>
 25> QCoreApplicationPrivate::sendThroughObjectEventFilters [0x7ffb9fab523a] <Qt5Core.dll>
 26> QApplicationPrivate::notify_helper [0x7ffba05455ac] <Qt5Widgets.dll>
 27> QApplication::notify [0x7ffba05434e0] <Qt5Widgets.dll>
 28> QCoreApplication::notifyInternal2 [0x7ffb9fab318a] <Qt5Core.dll>
 29> QApplicationPrivate::sendMouseEvent [0x7ffba05467c5] <Qt5Widgets.dll>
 30> QDesktopWidget::workAreaResized [0x7ffba05909d2] <Qt5Widgets.dll>
 31> QDesktopWidget::workAreaResized [0x7ffba058e96e] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ffba05455c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ffba0544643] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ffb9fab318a] <Qt5Core.dll>
 35> QGuiApplicationPrivate::processMouseEvent [0x7ffb9fef47c3] <Qt5Gui.dll>
 36> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb9fedf030] <Qt5Gui.dll>
 37> QEventDispatcherWin32::processEvents [0x7ffb9fafbcfa] <Qt5Core.dll>
 38> qt_plugin_query_metadata [0x7ffb9e5428d9] <qwindows.dll>
 39> QEventLoop::exec [0x7ffb9faaf64c] <Qt5Core.dll>
 40> QCoreApplication::exec [0x7ffb9fab2164] <Qt5Core.dll>
 41> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff76f6b5219] <OpenToonz.exe>
 42> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76fadeab7] <OpenToonz.exe>
 43> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff76fade092] <OpenToonz.exe>
 44> BaseThreadInitThunk [0x7ffbf518257d] <KERNEL32.DLL>
 45> RtlUserThreadStart [0x7ffbf670aa48] <ntdll.dll>
==== End ====
I

**Comment by RodneyBaker** [comment]
Please see:  #5504
