### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Feverush** [opentoonz/opentoonz#5493]
### Description

Opentoonz will become unresponsive suddenly. You can be doing anything and it will give up and there will be no choice but to close the program.

### Steps to Reproduce

1. Just animate for more than an hour
2. 

### Expected Behavior

I wanted to be able toanimate in peace

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as not enough information to proceed with troubleshooting found in report.
@Feverush Any additional informatoin you can share about the problem will be appreciated.
This assuming you are still expereincing the reported issue.
