### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Eizywon** [opentoonz/opentoonz#5497]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-06-16 14:22:14
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Vega 6 Graphics
GPU Version: 4.6.13587 Compatibility Profile Context 19.40.42 26.20.14042.2

Crash File: C:\Users\Zoe\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240616-142214.log
Mini Dump File: C:\Users\Zoe\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240616-142214.dmp

Application Dir: D:/ZOEE/APLICACIONES/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: TIKTOK
Scene Name: foto 1
Project Path: C:\OpenToonz stuff\projects\TIKTOK\TIKTOK_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\TIKTOK\scenes\foto 1.tnz

==== Modules ====
D:\ZOEE\APLICACIONES\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Xml.dll
C:\Windows\System32\USER32.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\COMDLG32.dll
D:\ZOEE\APLICACIONES\OpenToonz\glut64.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\sechost.dll
D:\ZOEE\APLICACIONES\OpenToonz\EDSDK.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\bcrypt.dll
D:\ZOEE\APLICACIONES\OpenToonz\colorfx.dll
C:\Windows\System32\WS2_32.dll
D:\ZOEE\APLICACIONES\OpenToonz\image.dll
D:\ZOEE\APLICACIONES\OpenToonz\tfarm.dll
D:\ZOEE\APLICACIONES\OpenToonz\tnzstdfx.dll
D:\ZOEE\APLICACIONES\OpenToonz\tnztools.dll
D:\ZOEE\APLICACIONES\OpenToonz\toonzqt.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Widgets.dll
D:\ZOEE\APLICACIONES\OpenToonz\sound.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Core.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Gui.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Script.dll
D:\ZOEE\APLICACIONES\OpenToonz\tnzext.dll
D:\ZOEE\APLICACIONES\OpenToonz\toonzlib.dll
D:\ZOEE\APLICACIONES\OpenToonz\opencv_world451.dll
D:\ZOEE\APLICACIONES\OpenToonz\tnzcore.dll
D:\ZOEE\APLICACIONES\OpenToonz\tnzbase.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5OpenGL.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Multimedia.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
D:\ZOEE\APLICACIONES\OpenToonz\MSVCP140.dll
D:\ZOEE\APLICACIONES\OpenToonz\MSVCP140_1.dll
C:\Windows\System32\CRYPT32.dll
D:\ZOEE\APLICACIONES\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
D:\ZOEE\APLICACIONES\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.4355_none_792ecafd2442822f\COMCTL32.dll
C:\Windows\SYSTEM32\VERSION.dll
D:\ZOEE\APLICACIONES\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
D:\ZOEE\APLICACIONES\OpenToonz\libmypaint-1-4-0.dll
D:\ZOEE\APLICACIONES\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
D:\ZOEE\APLICACIONES\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\MSACM32.dll
D:\ZOEE\APLICACIONES\OpenToonz\libintl-8.dll
D:\ZOEE\APLICACIONES\OpenToonz\libjson-c-2.dll
D:\ZOEE\APLICACIONES\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
D:\ZOEE\APLICACIONES\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
D:\ZOEE\APLICACIONES\OpenToonz\styles\qwindowsvistastyle.dll
D:\ZOEE\APLICACIONES\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\u0353355.inf_amd64_756e38ab2b21614c\B353443\atig6pxx.dll
C:\Windows\System32\DriverStore\FileRepository\u0353355.inf_amd64_756e38ab2b21614c\B353443\atio6axx.dll
C:\Windows\SYSTEM32\dxva2.dll
C:\Windows\System32\DriverStore\FileRepository\u0353355.inf_amd64_756e38ab2b21614c\B353443\atig6txx.dll
C:\Windows\SYSTEM32\atiadlxx.dll
C:\Windows\System32\PSAPI.DLL
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qgif.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qicns.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qico.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qjpeg.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qsvg.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qtga.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qtiff.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qwbmp.dll
D:\ZOEE\APLICACIONES\OpenToonz\imageformats\qwebp.dll
D:\ZOEE\APLICACIONES\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
D:\ZOEE\APLICACIONES\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\wintab32.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\system32\Ninput.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.4355_none_60b8b9eb71f62e16\comctl32.DLL
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff9093e8b1c] <ntdll.dll>
  2> RtlRaiseException [0x7ff9093c12d6] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff909410f8e] <ntdll.dll>
  4> TStroke::getMaxThickness [0x7ff8b993e4e3] <tnzcore.dll>
  5> TRegion::addEdge [0x7ff8b99328c3] <tnzcore.dll>
  6> computeRegionFeature [0x7ff8b992b5a2] <tnzcore.dll>
  7> TVectorImage::replaceStroke [0x7ff8b9931e8b] <tnzcore.dll>
  8> initImageIo [0x7ff8cf518adc] <image.dll>
  9> initImageIo [0x7ff8cf518df5] <image.dll>
 10> IKSkeleton::setPurpose [0x7ff8b9c2576d] <toonzlib.dll>
 11> ImageManager::getImage [0x7ff8b9c27066] <toonzlib.dll>
 12> Stage::Player::image [0x7ff8b9caedf3] <toonzlib.dll>
 13> Stage::RasterPainter::onImage [0x7ff8b9cb234e] <toonzlib.dll>
 14> Stage::visit [0x7ff8b9cab0cb] <toonzlib.dll>
 15> Stage::visit [0x7ff8b9caa980] <toonzlib.dll>
 16> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78ea5fe8a] <OpenToonz.exe>
 17> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78ea5dda4] <OpenToonz.exe>
 18> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78ea64535] <OpenToonz.exe>
 19> QOpenGLWidget::redirected [0x7ff8bab84e2e] <Qt5Widgets.dll>
 20> QWidget::event [0x7ff8bab584d1] <Qt5Widgets.dll>
 21> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78ea6942b] <OpenToonz.exe>
 22> QApplicationPrivate::notify_helper [0x7ff8bab355c0] <Qt5Widgets.dll>
 23> QApplication::notify [0x7ff8bab34643] <Qt5Widgets.dll>
 24> QCoreApplication::notifyInternal2 [0x7ff8ba0a318a] <Qt5Core.dll>
 25> QWidgetPrivate::drawWidget [0x7ff8bab57aeb] <Qt5Widgets.dll>
 26> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5da57] <Qt5Widgets.dll>
 27> QWidgetPrivate::drawWidget [0x7ff8bab57c44] <Qt5Widgets.dll>
 28> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5da57] <Qt5Widgets.dll>
 29> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5d985] <Qt5Widgets.dll>
 30> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5d985] <Qt5Widgets.dll>
 31> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5d985] <Qt5Widgets.dll>
 32> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5d985] <Qt5Widgets.dll>
 33> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5d985] <Qt5Widgets.dll>
 34> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5d985] <Qt5Widgets.dll>
 35> QWidgetPrivate::drawWidget [0x7ff8bab57c44] <Qt5Widgets.dll>
 36> QWidgetPrivate::paintSiblingsRecursive [0x7ff8bab5da57] <Qt5Widgets.dll>
 37> QWidgetPrivate::drawWidget [0x7ff8bab57c44] <Qt5Widgets.dll>
 38> QWidgetPrivate::moveRect [0x7ff8bab40406] <Qt5Widgets.dll>
 39> QWidget::event [0x7ff8bab5890f] <Qt5Widgets.dll>
 40> QApplicationPrivate::notify_helper [0x7ff8bab355c0] <Qt5Widgets.dll>
 41> QApplication::notify [0x7ff8bab34643] <Qt5Widgets.dll>
 42> QCoreApplication::notifyInternal2 [0x7ff8ba0a318a] <Qt5Core.dll>
 43> QCoreApplicationPrivate::sendPostedEvents [0x7ff8ba0a4f25] <Qt5Core.dll>
 44> qt_plugin_query_metadata [0x7ff8b97928ff] <qwindows.dll>
 45> QEventDispatcherWin32::processEvents [0x7ff8ba0ebcfa] <Qt5Core.dll>
 46> qt_plugin_query_metadata [0x7ff8b97928d9] <qwindows.dll>
 47> QEventLoop::exec [0x7ff8ba09f64c] <Qt5Core.dll>
 48> QCoreApplication::exec [0x7ff8ba0a2164] <Qt5Core.dll>
 49> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff78e985219] <OpenToonz.exe>
 50> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78edaeab7] <OpenToonz.exe>
 51> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff78edae092] <OpenToonz.exe>
 52> BaseThreadInitThunk [0x7ff908fb7344] <KERNEL32.DLL>
 53> RtlUserThreadStart [0x7ff9093c26b1] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Hi @Eizywon 
There are three things that immediately come to mind that I personally would do/check if i was experiencing the same problems.
The last two might be remedied by the first (or just confirm other solutions aren't needed).

Update to the latest nightly... with the knowledge that there is a special consideration to make the current nightly releases work.  Namely that of renaming or replacing a file in the SRV directory (or the directory itself) as there is a bad file currently being installed in the latest nightlies.  See other reports or ask for more details if you aren't sure on that.  The important thing being that by installing the latest nightly you likely will resolve your current problem.

The second potential solution presents itself in your report as a Wintab issue.
This can likely be resolved via the update but on some systems this could be a driver issue or simply turning off Windows Ink in both Opentoonz and the operating system.

The third solution is likely the easiest and should generally be done for troubleshooting.
You have some files installed/stored on D:\ drive and until other issues are resolved please use the default locations of C:\ drive.
After all is resolved then try the other drive and you'll likely not have any issues and if you do... you'll then know exactly what to change to fix that problem.

That's really all I can see from your report.  
Other solutions may apply but I'd start there.

**Comment by RodneyBaker** [comment]
Closing as likely resolved although certainly not confirmed as such.
@Eizywon Please let us know of any problems you are still experiencing.

For troubleshooting purposes it may be advantageous to join one of the Opentoonz discords where troubleshooting can be accomplished in real time.
