### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by raymond-infinitecode** [opentoonz/opentoonz#5499]
### Description

Virus / Malicious issue found in the windows installer
![image](https://github.com/opentoonz/opentoonz/assets/4714784/4f9a92f9-ccf3-4e90-94ab-fc112a201b4f)

### Steps to Reproduce

1. Download latest opentoon, scan via http://www.virustotal.com
2. 

### Expected Behavior

No virus/malicious code

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by konero** [comment]
Two of the worst AV's, ignore.
