### ISSUE TITLE
Does not work on Windows XP

### ISSUE THREAD

**Issue by dsp2003** [opentoonz/opentoonz#55]
I presume, the compilation target has been set to 64-bit Windows NT 6.x series (i.e. Vista/7/8.1/10).

Is it possible to also release 32-bit version for NT 5.x (i.e. 2000, XP, 2003, ReactOS)? I'm aware of its "memory limitations" of 3 Gb for application addressing, but it really should be enough for any simple animation.

**Comment by odysseywestra** [comment]
Yeah, assumption is correct is since Microsoft dropped support for Windows XP a couple years ago. So there is really no point. Since this is made for production use, it should stay focused on 64-bit builds, but hey, someone may fork it and compile it for 32-bit.

**Comment by dsp2003** [comment]
If people are still using it regardless of what Microsoft thinks or wants, there is a point.

**Comment by EIREXE** [comment]
XP is not for production use, mainly because it does not receive updates anymore, and no one will support it, your only choice is to switch to a more modern operating system.

**Comment by mmuman** [comment]
While XP is officially end-of-lifed (except in some places like banks (and they get charged a lot)), ReactOS is a FLOSS clone of Windows (what GNU/Linux is to Unix) and currently targets the XP API AFAIK, it would be nice to have it supported.

**Comment by odysseywestra** [comment]
Closing since initial support is for Windows 7 and up and that Windows XP is no longer supported by Microsoft.
