### ISSUE TITLE
open toonz crashed

### ISSUE THREAD

**Issue by yasa2024** [opentoonz/opentoonz#5502]
### Description

Exception_Access_Violation

### Steps to Reproduce

1. I don't know the box show up 
2. the open toonz won't work
3. 
4. 

### Expected Behavior

![open oonz crashed](https://github.com/opentoonz/opentoonz/assets/173592321/c5080117-6e69-4297-b1fd-d672c9166e95)

### Screenshots, Video & Crash Logs

![image](https://github.com/opentoonz/opentoonz/assets/173592321/cbec9c86-22d1-431a-865b-16221013746b)

### OpenToonz Version

1.7

### OpenToonz Version Information

build mar 14 2023

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Ugee

**Comment by RodneyBaker** [comment]
There isn't sufficient information to troubleshoot the issue.
You might consider joining one of the Opentoonz discords where other routinely help Opentoonz users troubleshoot problems they encounter.

Short of that perhaps you can update to the latest nightly releasse (that will fix many problems) and do various things such as clearing the cache via File > Clear Cache Folder.  Also, double check drivers for your Ugee tablet and restart your computer from time to time to clear out the cobwebs.
