### ISSUE TITLE
 Bug Issue

### ISSUE THREAD

**Issue by Andy4593** [opentoonz/opentoonz#5504]
bug report
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-06-26 17:17:23
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 4

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Vega 3 Graphics
GPU Version: 4.6.0 Compatibility Profile Context 22.20.44.221025

Crash File: C:\Users\Rohan\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240626-171723.log
Mini Dump File: C:\Users\Rohan\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240626-171723.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: 23
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\23.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\ole32.dll
C:\Program Files\OpenToonz\glut64.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0386004.inf_amd64_1e67c8d8a52858e9\B385477\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0386004.inf_amd64_1e67c8d8a52858e9\B385477\atio6axx.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\SYSTEM32\Wacom_Tablet.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff896467f5a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff89640e642] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff89649403e] <ntdll.dll>
  4> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff635b261c9] <OpenToonz.exe>
  5> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff635b0d75d] <OpenToonz.exe>
  6> QWidget::event [0x7ff86f15807c] <Qt5Widgets.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff635b0b13b] <OpenToonz.exe>
  8> QApplicationPrivate::notify_helper [0x7ff86f1355c0] <Qt5Widgets.dll>
  9> QApplication::notify [0x7ff86f1334e0] <Qt5Widgets.dll>
 10> QCoreApplication::notifyInternal2 [0x7ff84460318a] <Qt5Core.dll>
 11> QApplicationPrivate::sendMouseEvent [0x7ff86f1367c5] <Qt5Widgets.dll>
 12> QDesktopWidget::workAreaResized [0x7ff86f1809d2] <Qt5Widgets.dll>
 13> QDesktopWidget::workAreaResized [0x7ff86f17e96e] <Qt5Widgets.dll>
 14> QApplicationPrivate::notify_helper [0x7ff86f1355c0] <Qt5Widgets.dll>
 15> QApplication::notify [0x7ff86f134643] <Qt5Widgets.dll>
 16> QCoreApplication::notifyInternal2 [0x7ff84460318a] <Qt5Core.dll>
 17> QGuiApplicationPrivate::processMouseEvent [0x7ff845c447c3] <Qt5Gui.dll>
 18> QWindowSystemInterface::sendWindowSystemEvents [0x7ff845c2f030] <Qt5Gui.dll>
 19> QEventDispatcherWin32::processEvents [0x7ff84464bcfa] <Qt5Core.dll>
 20> qt_plugin_query_metadata [0x7ff8468f28d9] <qwindows.dll>
 21> QEventLoop::exec [0x7ff8445ff64c] <Qt5Core.dll>
 22> QCoreApplication::exec [0x7ff844602164] <Qt5Core.dll>
 23> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff635a65219] <OpenToonz.exe>
 24> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff635e8eab7] <OpenToonz.exe>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff635e8e092] <OpenToonz.exe>
 26> BaseThreadInitThunk [0x7ff89524257d] <KERNEL32.DLL>
 27> RtlUserThreadStart [0x7ff89644af28] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
You don't supply any information on what is happening at time of crashing so will have to guess.

```You likely have the problem with t32bitsrv.exe
Current nighly builds have a bad file and that still needs to be addressed.
In the meantime you can safely rename the "srv" directory or the "t32bitsrv.exe" file inside that directory.
That is only used for legacy .MOV format which is now handled by FFMPEG.
There are other ways to resolve that as well but that is perhaps the quickest.

If you don't have a "srv" directory in C:\Program Files\Opentoonz... we are looking at a different problem.```

REF:  Other reports of similar nature.

**Comment by RodneyBaker** [comment]
I'm tagging this with 'known' issue but more information is needed to actually know that.
The first step to resolve the problem not quite specified in this report is to test with the latest nightly release.
From there we can move forward.

The 'known problem' at this point is lack of information in reporting.
@Andy4593 Anything and everything you can provide regarding this issue will be appreciated.

**Comment by RodneyBaker** [comment]
Closing for lack of actionable information to troubleshoot the problem.
@Andy4593  Any additional information you can share will be appreciated.

Here's a general analysis of the crash report:  ```Key Points from the Crash Report
Crash Reason: The crash occurred due to an EXCEPTION_ACCESS_VIOLATION, indicating an illegal memory access attempt.

Backtrace Analysis:

The backtrace shows the sequence of function calls that led to the crash, starting with the RtlGetLengthWithoutLastFullDosOrNtPathElement function in ntdll.dll.
The critical part of the stack trace seems to involve the destruction of TSmartPointerT objects in OpenToonz.exe, indicating a potential issue with object management or memory cleanup in the code.
The functions QWidget::event, QApplication::notify, and QCoreApplication::notifyInternal2 suggest that the crash might be related to event handling within the GUI framework.
Modules Loaded:

The report lists numerous modules, including Qt libraries (Qt5Widgets.dll, Qt5Core.dll, etc.), OpenGL, and OpenToonz-specific DLLs (toonzqt.dll, tnzlib.dll). The crash within the main OpenToonz executable (OpenToonz.exe) might be due to a problem in the application logic or resource management.
System Configuration:

The system is running on Windows 10 with an AMD Radeon(TM) Vega 3 Graphics GPU, which suggests compatibility with OpenGL 4.6.0.
Ensure the system meets the minimum hardware requirements for OpenToonz and that the GPU drivers are updated.
Possible Causes and Solutions
Software Bugs:

Cause: The crash might be due to bugs in the application code, especially related to memory management or GUI event handling.
Solution: Check for any available patches or updates for OpenToonz, as these might address known issues.
Graphics Driver Issues:

Cause: Outdated or incompatible graphics drivers can cause crashes, especially when the application involves complex graphics operations.
Solution: Ensure your graphics drivers are up-to-date. If the issue persists after an update, consider rolling back to a previous stable driver version.
Corrupted Project or Scene Files:

Cause: The specific project or scene file might be corrupted, causing the application to access invalid memory.
Solution: Test with a different project or scene to see if the crash is specific to a file. If so, try recreating the project or restoring it from a backup.
Resource Management:

Cause: Improper handling of resources such as smart pointers can lead to access violations.
Solution: Monitor the application for memory leaks or resource mismanagement. This might require profiling tools to analyze memory usage patterns.
Event Handling Issues:

Cause: The crash may be due to unexpected states or events in the GUI.
Solution: Try simplifying the operations leading to the crash and observe if specific actions trigger the problem. This can help in pinpointing the exact scenario causing the error.
Conclusion
The crash is likely related to memory management or GUI event handling issues within OpenToonz. Updating software and drivers, checking project file integrity, and monitoring resource usage are practical steps to mitigate the issue. If the problem persists, consider reaching out to the OpenToonz community for further insights or bug reporting.```
