### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by deleonfire** [opentoonz/opentoonz#5521]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-07-04 12:57:54
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 8

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.4502

Crash File: C:\Users\RickDeleon\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240704-125754.log
Mini Dump File: C:\Users\RickDeleon\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240704-125754.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: practice
Scene Name: characters outlines
Project Path: C:\OpenToonz stuff\projects\practice\practice_otprj.xml
Scene Path: C:\OpenToonz stuff\projects\practice\scenes\characters outlines.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\Program Files\OpenToonz\image.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3bfeb619bad09712\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3bfeb619bad09712\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3bfeb619bad09712\igdgmm64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_3bfeb619bad09712\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\ApplicationTargetedFeatureDatabase.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3672_none_2713b9d173822955\comctl32.dll
C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
C:\WINDOWS\SYSTEM32\TextShaping.dll
C:\Windows\System32\thumbcache.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\edputil.dll
C:\WINDOWS\SYSTEM32\windows.fileexplorer.common.dll
C:\WINDOWS\SYSTEM32\cldapi.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\windows.staterepositoryclient.dll
C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\policymanager.dll
C:\WINDOWS\SYSTEM32\msvcp110_win.dll
C:\WINDOWS\system32\Ninput.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffa5f4c7f5a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffa5f46e642] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffa5f4f403e] <ntdll.dll>
  4> ToolOptions::showEvent [0x7ffa01fadbb5] <tnztools.dll>
  5> PinchTool::getToolType [0x7ffa01ecbf15] <tnztools.dll>
  6> PinchTool::getToolType [0x7ffa01ecb3ea] <tnztools.dll>
  7> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff755cbee76] <OpenToonz.exe>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff755cc454f] <OpenToonz.exe>
  9> QOpenGLWidget::redirected [0x7ff9ffa64e2e] <Qt5Widgets.dll>
 10> QWidget::event [0x7ff9ffa384d1] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff755cc942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ff9ffa155c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ff9ffa14643] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ff9fe46318a] <Qt5Core.dll>
 15> QWidgetPrivate::drawWidget [0x7ff9ffa37aeb] <Qt5Widgets.dll>
 16> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3da57] <Qt5Widgets.dll>
 17> QWidgetPrivate::drawWidget [0x7ff9ffa37c44] <Qt5Widgets.dll>
 18> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3da57] <Qt5Widgets.dll>
 19> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3d985] <Qt5Widgets.dll>
 20> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3d985] <Qt5Widgets.dll>
 21> QWidgetPrivate::drawWidget [0x7ff9ffa37c44] <Qt5Widgets.dll>
 22> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3da57] <Qt5Widgets.dll>
 23> QWidgetPrivate::drawWidget [0x7ff9ffa37c44] <Qt5Widgets.dll>
 24> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3da57] <Qt5Widgets.dll>
 25> QWidgetPrivate::drawWidget [0x7ff9ffa37c44] <Qt5Widgets.dll>
 26> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3da57] <Qt5Widgets.dll>
 27> QWidgetPrivate::drawWidget [0x7ff9ffa37c44] <Qt5Widgets.dll>
 28> QWidgetPrivate::paintSiblingsRecursive [0x7ff9ffa3da57] <Qt5Widgets.dll>
 29> QWidgetPrivate::drawWidget [0x7ff9ffa37c44] <Qt5Widgets.dll>
 30> QWidgetPrivate::moveRect [0x7ff9ffa20406] <Qt5Widgets.dll>
 31> QWidget::event [0x7ff9ffa3890f] <Qt5Widgets.dll>
 32> QApplicationPrivate::notify_helper [0x7ff9ffa155c0] <Qt5Widgets.dll>
 33> QApplication::notify [0x7ff9ffa14643] <Qt5Widgets.dll>
 34> QCoreApplication::notifyInternal2 [0x7ff9fe46318a] <Qt5Core.dll>
 35> QCoreApplicationPrivate::sendPostedEvents [0x7ff9fe464f25] <Qt5Core.dll>
 36> qt_plugin_query_metadata [0x7ffa012028ff] <qwindows.dll>
 37> QEventDispatcherWin32::processEvents [0x7ff9fe4abcfa] <Qt5Core.dll>
 38> qt_plugin_query_metadata [0x7ffa012028d9] <qwindows.dll>
 39> QEventLoop::exec [0x7ff9fe45f64c] <Qt5Core.dll>
 40> QCoreApplication::exec [0x7ff9fe462164] <Qt5Core.dll>
 41> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff755be5219] <OpenToonz.exe>
 42> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff75600eab7] <OpenToonz.exe>
 43> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff75600e092] <OpenToonz.exe>
 44> BaseThreadInitThunk [0x7ffa5e7e257d] <KERNEL32.DLL>
 45> RtlUserThreadStart [0x7ffa5f4aaf28] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. Restarted 
2. reinstalled issue continues

### Expected Behavior

scene opens 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
General recommendation given the information in your report is to install the latest nightly release allowing for an issue that will likely prevent it from running initially until a file is renamed/removed.  The nightly release will likely resolve many common problems.

Please see #5351 for more information regarding the required fix for latest nightly releases.
