### ISSUE TITLE
Crushed

### ISSUE THREAD

**Issue by aryabath10** [opentoonz/opentoonz#5522]
### Description

Automatic closed after few hour spent.

### Steps to Reproduce

1. 
2. 

### Expected Behavior

Automatic closed after few hour spent.

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-07-09 11:20:51
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22635
CPU Threads: 12

GPU Vendor: ATI Technologies Inc.
GPU Model: AMD Radeon(TM) Graphics
GPU Version: 4.6.0 Compatibility Profile Context 22.20.27.09.230330

Crash File: C:\Users\rd616\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240709-112051.log
Mini Dump File: C:\Users\rd616\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240709-112051.dmp

Application Dir: D:/Opentoonz/opentoonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: Shivaji
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\Shivaji.tnz

==== Modules ====
D:\Opentoonz\opentoonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\Opentoonz\opentoonz\Qt5Xml.dll
D:\Opentoonz\opentoonz\Qt5SerialPort.dll
D:\Opentoonz\opentoonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\Opentoonz\opentoonz\glut64.dll
D:\Opentoonz\opentoonz\image.dll
D:\Opentoonz\opentoonz\colorfx.dll
D:\Opentoonz\opentoonz\EDSDK.dll
D:\Opentoonz\opentoonz\tnzstdfx.dll
C:\WINDOWS\System32\WS2_32.dll
D:\Opentoonz\opentoonz\tnztools.dll
D:\Opentoonz\opentoonz\tfarm.dll
D:\Opentoonz\opentoonz\Qt5Widgets.dll
D:\Opentoonz\opentoonz\Qt5Core.dll
D:\Opentoonz\opentoonz\sound.dll
D:\Opentoonz\opentoonz\toonzqt.dll
D:\Opentoonz\opentoonz\Qt5Script.dll
D:\Opentoonz\opentoonz\toonzlib.dll
D:\Opentoonz\opentoonz\tnzext.dll
D:\Opentoonz\opentoonz\opencv_world451.dll
D:\Opentoonz\opentoonz\tnzbase.dll
D:\Opentoonz\opentoonz\Qt5OpenGL.dll
D:\Opentoonz\opentoonz\tnzcore.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\Opentoonz\opentoonz\Qt5Multimedia.dll
D:\Opentoonz\opentoonz\Qt5Gui.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
D:\Opentoonz\opentoonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
D:\Opentoonz\opentoonz\VCRUNTIME140_1.dll
D:\Opentoonz\opentoonz\MSVCP140.dll
D:\Opentoonz\opentoonz\VCRUNTIME140.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.2706_none_b43dabad638ac843\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
D:\Opentoonz\opentoonz\MSVCP140_1.dll
D:\Opentoonz\opentoonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
D:\Opentoonz\opentoonz\glew32.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\Opentoonz\opentoonz\Qt5Svg.dll
D:\Opentoonz\opentoonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
D:\Opentoonz\opentoonz\libjson-c-2.dll
D:\Opentoonz\opentoonz\libintl-8.dll
D:\Opentoonz\opentoonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
D:\Opentoonz\opentoonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\Opentoonz\opentoonz\styles\qwindowsvistastyle.dll
D:\Opentoonz\opentoonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0390451.inf_amd64_39377efdd62734d1\B390182\atig6pxx.dll
C:\WINDOWS\System32\DriverStore\FileRepository\u0390451.inf_amd64_39377efdd62734d1\B390182\atio6axx.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
D:\Opentoonz\opentoonz\imageformats\qgif.dll
D:\Opentoonz\opentoonz\imageformats\qicns.dll
D:\Opentoonz\opentoonz\imageformats\qico.dll
D:\Opentoonz\opentoonz\imageformats\qjpeg.dll
D:\Opentoonz\opentoonz\imageformats\qsvg.dll
D:\Opentoonz\opentoonz\imageformats\qtga.dll
D:\Opentoonz\opentoonz\imageformats\qtiff.dll
D:\Opentoonz\opentoonz\imageformats\qwbmp.dll
D:\Opentoonz\opentoonz\imageformats\qwebp.dll
D:\Opentoonz\opentoonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\Opentoonz\opentoonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\Windows\System32\appresolver.dll
C:\WINDOWS\system32\wintab32.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\sxs.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ff8dd747a8a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ff8dd6ee242] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff8dd77340e] <ntdll.dll>
  4> PinchTool::getToolType [0x7ff876f24466] <tnztools.dll>
  5> PinchTool::getToolType [0x7ff876f24808] <tnztools.dll>
  6> PinchTool::getToolType [0x7ff876f28e07] <tnztools.dll>
  7> PinchTool::getToolType [0x7ff876f28cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6b44abec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6b44ac349] <OpenToonz.exe>
 10> QWidget::event [0x7ff8769b80f7] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6b44a942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ff8769955c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ff876993e73] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ff87658318a] <Qt5Core.dll>
 15> QDesktopWidget::workAreaResized [0x7ff8769e1284] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ff8769deb59] <Qt5Widgets.dll>
 17> QApplicationPrivate::notify_helper [0x7ff8769955c0] <Qt5Widgets.dll>
 18> QApplication::notify [0x7ff876994643] <Qt5Widgets.dll>
 19> QCoreApplication::notifyInternal2 [0x7ff87658318a] <Qt5Core.dll>
 20> QGuiApplicationPrivate::processTabletEvent [0x7ff8714656b7] <Qt5Gui.dll>
 21> QWindowSystemInterface::sendWindowSystemEvents [0x7ff87144f030] <Qt5Gui.dll>
 22> QEventDispatcherWin32::processEvents [0x7ff8765cbcfa] <Qt5Core.dll>
 23> qt_plugin_query_metadata [0x7ff8710128d9] <qwindows.dll>
 24> QEventLoop::exec [0x7ff87657f64c] <Qt5Core.dll>
 25> QCoreApplication::exec [0x7ff876582164] <Qt5Core.dll>
 26> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6b43c5219] <OpenToonz.exe>
 27> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6b47eeab7] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6b47ee092] <OpenToonz.exe>
 29> BaseThreadInitThunk [0x7ff8dcb1257d] <KERNEL32.DLL>
 30> RtlUserThreadStart [0x7ff8dd72aa58] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

OpenToonz 1.7.1  (Build Mar 14 2023)

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by aryabath10** [comment]
Thank You For Free Tools. And You're Company helped lot of people Career.

**Comment by RodneyBaker** [comment]
Not sure what is going on from the crash report.
Here are some general/generic thoughts:

General Recommendations:
For developers/bug hunters:

PinchTool Functionality:

The repeated calls to PinchTool::getToolType suggest that the crash may be related to this tool's operation. Reviewing the code for PinchTool could help identify memory access violations or improper handling of pointers.

Memory Access Violation:

Ensure that the PinchTool and other related tools are handling memory correctly. Look for any null pointer dereferences or out-of-bounds accesses.
Qt and OpenGL Integration:

Since the crash involves Qt5Widgets.dll and OPENGL32.dll, it may be worthwhile to check how OpenGL contexts are managed within the Qt application. Ensuring that OpenGL resources are correctly initialized and freed might resolve the issue.
Update Graphics Drivers:

For the user:
Ensure that the AMD Radeon graphics drivers are up to date, as outdated drivers can sometimes lead to crashes.
Check for Recent Changes:

If this crash started occurring after recent updates or changes to the project, review those changes to identify potential issues.

If not using the latest nightly release consider updating to the nightly release as it will include the latest bug fixes.

**Comment by RodneyBaker** [comment]
Actually, when troubleshooting, things like this should catch our attention:

D:\Opentoonz\opentoonz\OpenToonz.exe

Recommend installing to default locations while troubleshooting.
Later, when Opentoonz is working the location of program files and stuff directory can be modified.
