### ISSUE TITLE
opeantoonz crash's just after opening the project file

### ISSUE THREAD

**Issue by ammairakhan** [opentoonz/opentoonz#5526]
### Description

i have made a animations which took me 11 columns i imported a new image on 12th column on a vector level as soon as i imported it crashed, i tried restarting it then as soon as i opened a file it crashed 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing for lack of any actionable information to troubleshoot the problem.
@ammairakhan Any additional information you can share will be appreciated.
