### ISSUE TITLE
opentoonz not working 

### ISSUE THREAD

**Issue by skyasss** [opentoonz/opentoonz#5527]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-07-12 22:19:17
Crash Reason: EXCEPTION_ACCESS_VIOLATION

**Comment by RodneyBaker** [comment]
No choice but to close this for lack of information.
@skyasss I'll recommend joining the Opentoonz discord where other can help you troubleshoot issues with Opentoonz in real time.  

Opentoonz discord invite link:  https://discord.gg/QhWJJsQPMf
