### ISSUE TITLE
crashed after opening (Logitech webcam Driver)

### ISSUE THREAD

**Issue by G23M08** [opentoonz/opentoonz#5531]
### Description

just opend open toons fo rthe 1st time and it crashed

### Steps to Reproduce

1. open open toons
2. crash

### Expected Behavior

open toons open normaly

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-07-14 19:22:18
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 4

Crash File: C:\Users\Usuario\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240714-192218.log
Mini Dump File: C:\Users\Usuario\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240714-192218.dmp

==== Modules ====
E:\Users\algec\Downloads\ot\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\System32\USER32.dll
E:\Users\algec\Downloads\ot\Qt5Xml.dll
C:\Windows\System32\win32u.dll
E:\Users\algec\Downloads\ot\Qt5PrintSupport.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\RPCRT4.dll
E:\Users\algec\Downloads\ot\glut64.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\OLEAUT32.dll
E:\Users\algec\Downloads\ot\Qt5SerialPort.dll
E:\Users\algec\Downloads\ot\colorfx.dll
E:\Users\algec\Downloads\ot\image.dll
C:\Windows\System32\SETUPAPI.dll
E:\Users\algec\Downloads\ot\tnztools.dll
E:\Users\algec\Downloads\ot\tnzstdfx.dll
C:\Windows\System32\cfgmgr32.dll
E:\Users\algec\Downloads\ot\tfarm.dll
E:\Users\algec\Downloads\ot\Qt5Widgets.dll
C:\Windows\System32\WS2_32.dll
E:\Users\algec\Downloads\ot\toonzqt.dll
E:\Users\algec\Downloads\ot\Qt5Core.dll
E:\Users\algec\Downloads\ot\Qt5Gui.dll
E:\Users\algec\Downloads\ot\sound.dll
E:\Users\algec\Downloads\ot\EDSDK.dll
E:\Users\algec\Downloads\ot\Qt5Script.dll
E:\Users\algec\Downloads\ot\toonzlib.dll
E:\Users\algec\Downloads\ot\tnzext.dll
E:\Users\algec\Downloads\ot\tnzbase.dll
E:\Users\algec\Downloads\ot\tnzcore.dll
E:\Users\algec\Downloads\ot\Qt5OpenGL.dll
E:\Users\algec\Downloads\ot\Qt5Multimedia.dll
E:\Users\algec\Downloads\ot\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
E:\Users\algec\Downloads\ot\opencv_world451.dll
E:\Users\algec\Downloads\ot\MSVCP140_1.dll
E:\Users\algec\Downloads\ot\MSVCP140.dll
E:\Users\algec\Downloads\ot\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
E:\Users\algec\Downloads\ot\VCRUNTIME140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.4355_none_792ecafd2442822f\COMCTL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
E:\Users\algec\Downloads\ot\libmypaint-1-4-0.dll
E:\Users\algec\Downloads\ot\glew32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
E:\Users\algec\Downloads\ot\Qt5Svg.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
E:\Users\algec\Downloads\ot\CONCRT140.dll
C:\Windows\SYSTEM32\MSACM32.dll
E:\Users\algec\Downloads\ot\libintl-8.dll
E:\Users\algec\Downloads\ot\libjson-c-2.dll
C:\Windows\SYSTEM32\winmmbase.dll
E:\Users\algec\Downloads\ot\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
E:\Users\algec\Downloads\ot\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
E:\Users\algec\Downloads\ot\styles\qwindowsvistastyle.dll
E:\Users\algec\Downloads\ot\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\SYSTEM32\ig7icd64.dll
C:\Windows\SYSTEM32\igdusc64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff862649b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ff862622376] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff86267143e] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ff837dc2b9c] <MSVFW32.dll>
  6> ICOpen [0x7ff837dc2d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff832996212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff832994478] <image.dll>
  9> initImageIo [0x7ff832937ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6d45a0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6d45a2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d49ceab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6d49ce092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff861d97374] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff86261cc91] <ntdll.dll>
==== End ====

### OpenToonz Version

1.7

### OpenToonz Version Information

Build Mar 14 2023

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The good news...

You have a known issue with a Logitech webcam driver.
That can be seen in your crash report as being located at:  C:\Windows\SYSTEM32\lvcod64.dll

Rname or remove that file and Opentoonz should run fine.
Please see #5512 (and many other reports)
