### ISSUE TITLE
it keeps closing when i go in browser it closes

### ISSUE THREAD

**Issue by skyasss** [opentoonz/opentoonz#5532]
### Description

when i open and click on browser 
and click on one of my files and i scroll down it close i dont even have time to take a screen shot before it closes it down and one of my drawings dose the same thing its 77kb

### Steps to Reproduce

1. tried deleting it 
2. resting my pc

### Expected Behavior

i want it to loud so i can draw and work 

### Screenshots, Video & Crash Logs

how to put screenshots ?

### OpenToonz Version

1.7

### OpenToonz Version Informa
1.7,1

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Going to need a bit more information here @skyasss

**Comment by skyasss** [comment]
is that better?

**Comment by RodneyBaker** [comment]
> is that better?

A little but not really enough to help you much.

(see below note about clearing the cache)

I think what I will suggest is to start fresh.
Restart your computer and Opentoonz and start drawing again.
Save after a little while.
Perhaps close and reopen Opentoonz again from time to time.  Making sure to use SAVE ALL when you do close down.

BEFORE YOU RESTART OPENTOONZ...
Under the menu, use  File > Clear Cache Folder to clear the currently cached files.
This is important to do befor restarting
