### ISSUE TITLE
its closes

### ISSUE THREAD

**Issue by skyasss** [opentoonz/opentoonz#5533]
### Description

when i open opentoonz and click on browser and scroll down and up it closes it 
![Screenshot 2024-07-15 174349](https://github.com/user-attachments/assets/7a3060ce-9cb6-4e87-a8f6-99a64dee6715)

### Steps to Reproduce

1. i dont know what im doing 
2. help

### Expected Behavior

it doesn't close and i can scroll up and down with out it closing  

### Screenshots, Video & Crash Logs

![Screenshot 2024-07-15 074316](https://github.com/user-attachments/assets/62d8f6ca-a803-463f-b960-9f53bc80a685)

### OpenToonz Version

1.7

### OpenToonz Version Information

built may 10 2023

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as not having enough actionable information to proceed with.
@skyasss Any additional information you can share will be appreciated.
