### ISSUE TITLE
Line thickness is inconsistent when crossing over other lines

### ISSUE THREAD

**Issue by ArlingtonBrooks** [opentoonz/opentoonz#5545]
### Description

Drawing thin lines using the brush (or shape) tool over a transparent line with "over all" rule and "pressure" enabled causes the thickness of the line to change when intersecting the transparent line.

### Steps to Reproduce

-Create a new drawing level
-Create a new colour with alpha at 12%
-Draw random lines ("Line 1")
-Create a new colour with alpha at 100% using light pressure (or the shape tool, or thickness around 2.5 pixels)
-The new line will have the incorrect thickness when intersecting with "Line 1"
![Screenshot_20240723_211935](https://github.com/user-attachments/assets/17609d2e-b28b-46cf-89b4-4b77a3e748e6)

### Expected Behavior

The new line should not change thickness suddenly when intersecting with partially transparent lines

### OpenToonz Version

1.7

### OpenToonz Version Information

June 21, 2024 (1.7.1)

### Operating System

Linux

### GPU

NVIDIA

### Graphics Tablet

XP-Pen

**Comment by DarrenTAnims** [comment]
You didn't say which level type you created.
I'm guessing it was a Toonz Raster level.
This is an issue with using aliased lines on Toonz Raster levels.
If you want to use aliased lines, especially the MyPaint brushes (from the Raster brush list) then you're better to use the standard raster levels.

**Comment by ArlingtonBrooks** [comment]
I see, so this would be a duplicate of #4917.  I didn't notice from the title. 

Thanks for the info.
