### ISSUE TITLE
Its crashed

### ISSUE THREAD

**Issue by XFOX13** [opentoonz/opentoonz#5548]
### Description

I was drawing a channel photo and... its crashed unexpectly
Can you help us ح
![Ekran görüntüsü 2024-07-25 224018](https://github.com/user-attachments/assets/05c9f56c-f84c-4d95-98be-175985b33339)
lease

### Steps to Reproduce

1.Please dont delete what i draw
2.Fix it because im need it now

### Expected Behavior

Too many colors and too many work like 3 hours

### Screenshots, Video & Crash Logs

![Ekran görüntüsü 2024-07-25 224018](https://github.com/user-attachments/assets/449d0a4c-e5f3-4114-ac3e-3f938f0ec535)

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1,DWANGO Co.,Ltd,25.7.2024

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by XFOX13** [comment]
NO ITS CLOSED BY HIMSELF

**Comment by XFOX13** [comment]
![Uploading Ekran görüntüsü 2024-07-18 144937.png…]()

**Comment by XFOX13** [comment]
![Ekran görüntüsü 2024-07-18 144937](https://github.com/user-attachments/assets/bf49759e-eb9e-435c-813e-032c21dec264)

**Comment by XFOX13** [comment]
Why is this happening?

**Comment by Codeoloketuyi** [comment]
Try Tahoma

**Comment by RodneyBaker** [comment]
Closing as not enough information in report to be able to address the issue.
@XFOX13 If you are still having this issue please let us know more details about the problem.
