### ISSUE TITLE
Logitech webcam driver crash

### ISSUE THREAD

**Issue by actuallycharliey** [opentoonz/opentoonz#5551]
### Description

this pops up every single time. I've restarted both my pc and the application several times and nothing seems to work

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-08-02 08:08:51
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 8

Crash File: C:\Users\Owner\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240802-080851.log
Mini Dump File: C:\Users\Owner\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240802-080851.dmp

==== Modules ====
D:\OpenToonz stuff\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
D:\OpenToonz stuff\OpenToonz\Qt5Xml.dll
C:\WINDOWS\System32\GDI32.dll
D:\OpenToonz stuff\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\RPCRT4.dll
D:\OpenToonz stuff\OpenToonz\glut64.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\System32\SHLWAPI.dll
D:\OpenToonz stuff\OpenToonz\Qt5SerialPort.dll
D:\OpenToonz stuff\OpenToonz\colorfx.dll
D:\OpenToonz stuff\OpenToonz\EDSDK.dll
D:\OpenToonz stuff\OpenToonz\image.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
C:\WINDOWS\System32\cfgmgr32.dll
D:\OpenToonz stuff\OpenToonz\tnztools.dll
D:\OpenToonz stuff\OpenToonz\tfarm.dll
D:\OpenToonz stuff\OpenToonz\tnzstdfx.dll
D:\OpenToonz stuff\OpenToonz\Qt5Widgets.dll
D:\OpenToonz stuff\OpenToonz\sound.dll
D:\OpenToonz stuff\OpenToonz\toonzqt.dll
D:\OpenToonz stuff\OpenToonz\Qt5Core.dll
D:\OpenToonz stuff\OpenToonz\Qt5Gui.dll
D:\OpenToonz stuff\OpenToonz\toonzlib.dll
D:\OpenToonz stuff\OpenToonz\opencv_world451.dll
D:\OpenToonz stuff\OpenToonz\Qt5Script.dll
D:\OpenToonz stuff\OpenToonz\tnzext.dll
D:\OpenToonz stuff\OpenToonz\tnzbase.dll
D:\OpenToonz stuff\OpenToonz\tnzcore.dll
D:\OpenToonz stuff\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz stuff\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz stuff\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\OpenToonz stuff\OpenToonz\MSVCP140.dll
D:\OpenToonz stuff\OpenToonz\MSVCP140_1.dll
D:\OpenToonz stuff\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
D:\OpenToonz stuff\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.4355_none_792ecafd2442822f\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\OpenToonz stuff\OpenToonz\libmypaint-1-4-0.dll
D:\OpenToonz stuff\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
D:\OpenToonz stuff\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
D:\OpenToonz stuff\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\OpenToonz stuff\OpenToonz\libintl-8.dll
D:\OpenToonz stuff\OpenToonz\libjson-c-2.dll
D:\OpenToonz stuff\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\winmmbase.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz stuff\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\Wldp.dll
C:\WINDOWS\SYSTEM32\profapi.dll
D:\OpenToonz stuff\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz stuff\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\System32\CoreUIComponents.dll
C:\WINDOWS\System32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\system32\Oleacc.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_7b817a36f48f161e\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispsi.inf_amd64_7b817a36f48f161e\nvgpucomp64.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\dcomp.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\lvcod64.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff84f6e9b5c] <ntdll.dll>
  2> RtlRaiseException [0x7ff84f6c2376] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff84f71143e] <ntdll.dll>
  4> DriverProc [0x7f8411a9] <lvcod64.dll>
  5> ICSendMessage [0x7ff80c652b9c] <MSVFW32.dll>
  6> ICOpen [0x7ff80c652d64] <MSVFW32.dll>
  7> TSmartPointerT<TXshColumn>::operator> [0x7ff801b06212] <image.dll>
  8> TSmartPointerT<TXshColumn>::operator> [0x7ff801b04478] <image.dll>
  9> initImageIo [0x7ff801aa7ace] <image.dll>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7be0d0dae] <OpenToonz.exe>
 11> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7be0d2d41] <OpenToonz.exe>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7be4feab7] <OpenToonz.exe>
 13> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7be4fe092] <OpenToonz.exe>
 14> BaseThreadInitThunk [0x7ff84ef37374] <KERNEL32.DLL>
 15> RtlUserThreadStart [0x7ff84f6bcc91] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Huion

**Comment by RodneyBaker** [comment]
The good news is that you have a known condition.
Doctors treat the condition without medication and with a fairly simple file naming approach.

Your report mentions:  C:\WINDOWS\SYSTEM32\lvcod64.dll

That file is a problematic Logitech webcam driver.
If the file is renamed or removed then the symptoms of wontstartaplexia immediately fade and the effected program (in this case Opentoonz) will run.

See also other reports on this known condition:  #5531  (and many other reports)

**Comment by RodneyBaker** [comment]
@manongjohn has posted a potential fix for Tahoma2D to this and similar issues via a blacklisting of drivers with known problems.
REF:  https://github.com/tahoma2d/tahoma2d/pull/1562/files

We should consider implementation in Opentoonz if other solutions cannot be found.
