### ISSUE TITLE
OPENTOONZ ERROR

### ISSUE THREAD

**Issue by MayankDani** [opentoonz/opentoonz#5552]
### Description

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-08-03 12:28:43
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 4

GPU Vendor: Intel
GPU Model: Intel(R) UHD Graphics
GPU Version: 4.6.0 - Build 31.0.101.4502

Crash File: C:\Users\Hp\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240803-122843.log
Mini Dump File: C:\Users\Hp\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240803-122843.dmp

Application Dir: D:/OpenToonz
Stuff Dir: D:\

Project Name: Farmer
Scene Name: Animated Kisan
Project Path: D:\projects\Farmer\Farmer_otprj.xml
Scene Path: D:\projects\Farmer\scenes\Animated Kisan.tnz

==== Modules ====
D:\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
D:\OpenToonz\Qt5Xml.dll
D:\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\COMDLG32.dll
D:\OpenToonz\glut64.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\OLEAUT32.dll
C:\WINDOWS\System32\shcore.dll
D:\OpenToonz\Qt5SerialPort.dll
D:\OpenToonz\EDSDK.dll
D:\OpenToonz\colorfx.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\System32\SETUPAPI.dll
C:\WINDOWS\System32\WS2_32.dll
D:\OpenToonz\image.dll
D:\OpenToonz\tfarm.dll
D:\OpenToonz\tnzstdfx.dll
D:\OpenToonz\tnztools.dll
D:\OpenToonz\Qt5Widgets.dll
D:\OpenToonz\sound.dll
D:\OpenToonz\opencv_world451.dll
D:\OpenToonz\toonzqt.dll
D:\OpenToonz\Qt5Gui.dll
D:\OpenToonz\Qt5Core.dll
D:\OpenToonz\toonzlib.dll
D:\OpenToonz\Qt5Script.dll
D:\OpenToonz\tnzext.dll
D:\OpenToonz\tnzbase.dll
D:\OpenToonz\Qt5OpenGL.dll
D:\OpenToonz\tnzcore.dll
D:\OpenToonz\Qt5Multimedia.dll
D:\OpenToonz\Qt5Network.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\OpenToonz\MSVCP140_1.dll
D:\OpenToonz\MSVCP140.dll
D:\OpenToonz\VCRUNTIME140.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\SYSTEM32\WINMM.dll
D:\OpenToonz\VCRUNTIME140_1.dll
C:\WINDOWS\SYSTEM32\MF.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\OpenToonz\glew32.dll
D:\OpenToonz\libmypaint-1-4-0.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
D:\OpenToonz\CONCRT140.dll
D:\OpenToonz\Qt5Svg.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\OpenToonz\libintl-8.dll
D:\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dxcore.dll
D:\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
D:\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\OpenToonz\styles\qwindowsvistastyle.dll
D:\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_7f680e39d88878f3\igxelpicd64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_7f680e39d88878f3\igdml64.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_7f680e39d88878f3\igdgmm64.dll
C:\WINDOWS\SYSTEM32\DEVOBJ.dll
C:\WINDOWS\System32\WINTRUST.dll
C:\WINDOWS\SYSTEM32\MSASN1.dll
C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_7f680e39d88878f3\igc64.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\UIAutomationCore.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
D:\OpenToonz\imageformats\qgif.dll
D:\OpenToonz\imageformats\qicns.dll
D:\OpenToonz\imageformats\qico.dll
D:\OpenToonz\imageformats\qjpeg.dll
D:\OpenToonz\imageformats\qsvg.dll
D:\OpenToonz\imageformats\qtga.dll
D:\OpenToonz\imageformats\qtiff.dll
D:\OpenToonz\imageformats\qwbmp.dll
D:\OpenToonz\imageformats\qwebp.dll
D:\OpenToonz\bearer\qgenericbearer.dll
C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
C:\WINDOWS\System32\netprofm.dll
C:\WINDOWS\System32\npmproxy.dll
D:\OpenToonz\audio\qtaudio_windows.dll
C:\WINDOWS\SYSTEM32\MMDevAPI.DLL
C:\WINDOWS\SYSTEM32\wdmaud.drv
C:\WINDOWS\SYSTEM32\ksuser.dll
C:\WINDOWS\SYSTEM32\AVRT.dll
C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
C:\WINDOWS\SYSTEM32\msacm32.drv
C:\WINDOWS\SYSTEM32\midimap.dll
C:\WINDOWS\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\WINDOWS\system32\napinsp.dll
C:\WINDOWS\system32\pnrpnsp.dll
C:\WINDOWS\System32\winrnr.dll
C:\WINDOWS\system32\wshbth.dll
C:\WINDOWS\system32\nlansp_c.dll
C:\WINDOWS\System32\fwpuclnt.dll
C:\WINDOWS\SYSTEM32\PROPSYS.dll
C:\WINDOWS\SYSTEM32\LINKINFO.dll
C:\WINDOWS\SYSTEM32\OLEACC.dll
C:\WINDOWS\system32\winhttp.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\Windows\System32\threadpoolwinrt.dll
C:\WINDOWS\SYSTEM32\sxs.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7fffc3747f5a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7fffc36ee642] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7fffc377403e] <ntdll.dll>
  4> DumpRegistryKeyDefinitions [0x7fff5557126d] <igxelpicd64.dll>
  5> DumpRegistryKeyDefinitions [0x7fff5540fcb7] <igxelpicd64.dll>
  6> DumpRegistryKeyDefinitions [0x7fff55410453] <igxelpicd64.dll>
  7> DumpRegistryKeyDefinitions [0x7fff5540e4ee] <igxelpicd64.dll>
  8> DumpRegistryKeyDefinitions [0x7fff5539c28d] <igxelpicd64.dll>
  9> RegisterProcTableCallback [0x7fff54cda67e] <igxelpicd64.dll>
 10> DumpRegistryKeyDefinitions [0x7fff552cc94a] <igxelpicd64.dll>
 11> mergePalette_Overlap [0x7fff635ea09c] <tnzcore.dll>
 12> tglDraw [0x7fff635d27ba] <tnzcore.dll>
 13> OutlineStrokeProp::~OutlineStrokeProp [0x7fff635d1b38] <tnzcore.dll>
 14> tglDraw [0x7fff635d2ff7] <tnzcore.dll>
 15> Stage::RasterPainter::onVectorImage [0x7fff641d4a3e] <toonzlib.dll>
 16> Stage::RasterPainter::onImage [0x7fff641d237f] <toonzlib.dll>
 17> Stage::visit [0x7fff641cb0cb] <toonzlib.dll>
 18> Stage::visit [0x7fff641ca980] <toonzlib.dll>
 19> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72bfe8a] <OpenToonz.exe>
 20> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72bdda4] <OpenToonz.exe>
 21> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72c4535] <OpenToonz.exe>
 22> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72c4914] <OpenToonz.exe>
 23> TTool::pick [0x7fff701f71f4] <tnztools.dll>
 24> RasterSelection::setTransformationCount [0x7fff702aa821] <tnztools.dll>
 25> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72cb52b] <OpenToonz.exe>
 26> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72ca5f8] <OpenToonz.exe>
 27> QWidget::event [0x7fff65ae8066] <Qt5Widgets.dll>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d72c942b] <OpenToonz.exe>
 29> QApplicationPrivate::notify_helper [0x7fff65ac55c0] <Qt5Widgets.dll>
 30> QApplication::notify [0x7fff65ac34e0] <Qt5Widgets.dll>
 31> QCoreApplication::notifyInternal2 [0x7fff6490318a] <Qt5Core.dll>
 32> QApplicationPrivate::sendMouseEvent [0x7fff65ac67c5] <Qt5Widgets.dll>
 33> QDesktopWidget::workAreaResized [0x7fff65b109d2] <Qt5Widgets.dll>
 34> QDesktopWidget::workAreaResized [0x7fff65b0e96e] <Qt5Widgets.dll>
 35> QApplicationPrivate::notify_helper [0x7fff65ac55c0] <Qt5Widgets.dll>
 36> QApplication::notify [0x7fff65ac4643] <Qt5Widgets.dll>
 37> QCoreApplication::notifyInternal2 [0x7fff6490318a] <Qt5Core.dll>
 38> QGuiApplicationPrivate::processMouseEvent [0x7fff64d447c3] <Qt5Gui.dll>
 39> QWindowSystemInterface::sendWindowSystemEvents [0x7fff64d2f030] <Qt5Gui.dll>
 40> QEventDispatcherWin32::processEvents [0x7fff6494bcfa] <Qt5Core.dll>
 41> qt_plugin_query_metadata [0x7fff769c28d9] <qwindows.dll>
 42> QEventLoop::exec [0x7fff648ff64c] <Qt5Core.dll>
 43> QCoreApplication::exec [0x7fff64902164] <Qt5Core.dll>
 44> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7d71e5219] <OpenToonz.exe>
 45> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d760eab7] <OpenToonz.exe>
 46> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7d760e092] <OpenToonz.exe>
 47> BaseThreadInitThunk [0x7fffc341257d] <KERNEL32.DLL>
 48> RtlUserThreadStart [0x7fffc372af28] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
It's not quite clear what is happening from your bug report but it is fairly clear that you haven't installed the stuff directory to it's default location as some files are on the C:\drive and others are on a D:\drive.

Recommend troubleshooting first by installing to default locations.
