### ISSUE TITLE
crasheed

### ISSUE THREAD

**Issue by ismail-29** [opentoonz/opentoonz#5553]
### Description

while doing the work

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Will close as this report has no information included that can be acted upon.
We could suggest... 'don't crash' but that isn't likely to help much.

@ismail-29 Any information you can share will help.
