### ISSUE TITLE
Open toolz drawing window disappeared in animation tab

### ISSUE THREAD

**Issue by Vedankdeveloper** [opentoonz/opentoonz#5558]
### Ask a question related to OpenToonz

Opentoonz drawing window disappeared in animation tab

**Comment by DarrenTAnims** [comment]
Presumably you've closed it or moved it out of the screen.
You can reset the windows from the menu: Windows > Workspace > Reset to Default Rooms
Then, when you restart, tick the option: Windows > Workspace > Lock Room Panes, so you can't accidentally do it again.

**Comment by Vedankdeveloper** [comment]
Thank you sir
