### ISSUE TITLE
Whenever i animate save scene window pop up and its really the frustrating 

### ISSUE THREAD

**Issue by Vedankdeveloper** [opentoonz/opentoonz#5561]
### Description

Whenever I anywhere the saves in window pop up and its really frustrating 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Perhaps you haven't saved your scene and have AutoSave turned on in Preferences?
If not originally saved Opentoonz Autosave will continually prompt you for the name.

More information on the problem you are experiencing will help.

**Comment by RodneyBaker** [comment]
I'm a little confused then because before we can animate we have to create a scene.

**Comment by Vedankdeveloper** [comment]
![17229569249441859194779339445916](https://github.com/user-attachments/assets/c39fab15-55c1-4021-9824-8ead659d53c6)
This save scene window pop ups

**Comment by RodneyBaker** [comment]
What do you save the scene as at that point?

**Comment by Vedankdeveloper** [comment]
Thanks for the tip!
