### ISSUE TITLE
Crash when trying to import .WAV or .MP3 files

### ISSUE THREAD

**Issue by overworkedSeadweller** [opentoonz/opentoonz#5562]
### Description

I successfully imported one audio file a few days ago and since then I have not been able to load or import a new one into any new or existing scenes. I do have all the required software, and have both tried dragging the files from my file explorer and going through the one in app. 

I have no idea why it will not let me import an audio file, especially since I have it converted to both. I have also discovered I cannot import ANY files.

### Steps to Reproduce

1. 
2. 

### Expected Behavior

Files dragged to be imported or loaded upon clicked either button

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
If you can't import ANY file... that should help discover the problem.
I suspect it's just needing to download and connect to FFMPEG though.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@overworkedSeadweller Please let us know if you are still experiencing issues with .WAV or MP3 audio files.
