### ISSUE TITLE
Opentoonz start to crash 

### ISSUE THREAD

**Issue by redpanda-st** [opentoonz/opentoonz#5565]
### Ask a question related to OpenToonz

My Opentoonz started crash every 5 minutes. the message error is below. What does " EXCEPTION_ACCESS_VIOLATION" mean ? I download opentoonz on the official web page and have all the requirements for it in my PC. (I think I don't download the nighly build version)
Thanks for helping :) 

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-08-12 01:06:42
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.22631
CPU Threads: 12

GPU Vendor: Intel
GPU Model: Intel(R) Iris(R) Xe Graphics
GPU Version: 4.6.0 - Build 31.0.101.4255

Crash File: C:\Users\ASUS\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240812-010642.log
Mini Dump File: C:\Users\ASUS\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240812-010642.dmp

Application Dir: C:/Program Files/OpenToonz
Stuff Dir: C:\OpenToonz stuff

Project Name: sandbox
Scene Name: avion porco rosso
Project Path: C:\OpenToonz stuff\sandbox\sandbox_otprj.xml
Scene Path: C:\OpenToonz stuff\sandbox\scenes\avion porco rosso.tnz

==== Modules ====
C:\Program Files\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\Program Files\OpenToonz\Qt5PrintSupport.dll
C:\Program Files\OpenToonz\Qt5Xml.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\OLEAUT32.dll
C:\Windows\System32\bcrypt.dll
C:\Program Files\OpenToonz\glut64.dll
C:\Windows\System32\COMDLG32.dll
C:\Program Files\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\shcore.dll
C:\Program Files\OpenToonz\EDSDK.dll
C:\Windows\System32\SHLWAPI.dll
C:\Windows\System32\SETUPAPI.dll
C:\Program Files\OpenToonz\colorfx.dll
C:\Program Files\OpenToonz\image.dll
C:\Windows\System32\WS2_32.dll
C:\Program Files\OpenToonz\tnztools.dll
C:\Program Files\OpenToonz\tnzstdfx.dll
C:\Program Files\OpenToonz\tfarm.dll
C:\Program Files\OpenToonz\Qt5Gui.dll
C:\Program Files\OpenToonz\Qt5Widgets.dll
C:\Program Files\OpenToonz\Qt5Core.dll
C:\Program Files\OpenToonz\toonzqt.dll
C:\Program Files\OpenToonz\sound.dll
C:\Program Files\OpenToonz\toonzlib.dll
C:\Program Files\OpenToonz\Qt5Script.dll
C:\Program Files\OpenToonz\tnzext.dll
C:\Program Files\OpenToonz\opencv_world451.dll
C:\Program Files\OpenToonz\tnzbase.dll
C:\Program Files\OpenToonz\Qt5OpenGL.dll
C:\Program Files\OpenToonz\tnzcore.dll
C:\Program Files\OpenToonz\Qt5Multimedia.dll
C:\Program Files\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Program Files\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MF.dll
C:\Program Files\OpenToonz\VCRUNTIME140.dll
C:\Program Files\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Program Files\OpenToonz\MSVCP140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Program Files\OpenToonz\libmypaint-1-4-0.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Program Files\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Program Files\OpenToonz\Qt5Svg.dll
C:\Program Files\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\cfgmgr32.dll
C:\Program Files\OpenToonz\libintl-8.dll
C:\Program Files\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Program Files\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Program Files\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\SYSTEM32\profapi.dll
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\UMPDC.dll
C:\Program Files\OpenToonz\styles\qwindowsvistastyle.dll
C:\Program Files\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\DEVOBJ.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\SYSTEM32\MSASN1.dll
C:\Windows\SYSTEM32\directxdatabasehelper.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igc64.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\SYSTEM32\CoreMessaging.dll
C:\Windows\SYSTEM32\CoreUIComponents.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igxelpicd64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igdml64.dll
C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_9741ef1f4093481f\igdgmm64.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\ApplicationTargetedFeatureDatabase.dll
C:\Windows\system32\dwrite.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Program Files\OpenToonz\imageformats\qgif.dll
C:\Program Files\OpenToonz\imageformats\qicns.dll
C:\Program Files\OpenToonz\imageformats\qico.dll
C:\Program Files\OpenToonz\imageformats\qjpeg.dll
C:\Program Files\OpenToonz\imageformats\qsvg.dll
C:\Program Files\OpenToonz\imageformats\qtga.dll
C:\Program Files\OpenToonz\imageformats\qtiff.dll
C:\Program Files\OpenToonz\imageformats\qwbmp.dll
C:\Program Files\OpenToonz\imageformats\qwebp.dll
C:\Program Files\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\Program Files\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\SYSTEM32\resourcepolicyclient.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\System32\winrnr.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\nlansp_c.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\wintab32.dll
C:\Windows\SYSTEM32\Wacom_Tablet.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3672_none_2713b9d173822955\comctl32.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
C:\Windows\SYSTEM32\policymanager.dll
C:\Windows\SYSTEM32\msvcp110_win.dll
C:\Windows\system32\Ninput.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\System32\OneCoreCommonProxyStub.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffbdd107f5a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffbdd0ae642] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffbdd13403e] <ntdll.dll>
  4> PinchTool::getToolType [0x7ffba7744466] <tnztools.dll>
  5> PinchTool::getToolType [0x7ffba7744808] <tnztools.dll>
  6> PinchTool::getToolType [0x7ffba7748e07] <tnztools.dll>
  7> PinchTool::getToolType [0x7ffba7748cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7affabec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7affaa7ee] <OpenToonz.exe>
 10> QWidget::event [0x7ffb75d88092] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7affa942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ffb75d655c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ffb75d634e0] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ffb74e1318a] <Qt5Core.dll>
 15> QApplicationPrivate::sendMouseEvent [0x7ffb75d667c5] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ffb75db09d2] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ffb75dae96e] <Qt5Widgets.dll>
 18> QApplicationPrivate::notify_helper [0x7ffb75d655c0] <Qt5Widgets.dll>
 19> QApplication::notify [0x7ffb75d64643] <Qt5Widgets.dll>
 20> QCoreApplication::notifyInternal2 [0x7ffb74e1318a] <Qt5Core.dll>
 21> QGuiApplicationPrivate::processMouseEvent [0x7ffb752547c3] <Qt5Gui.dll>
 22> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb7523f030] <Qt5Gui.dll>
 23> QEventDispatcherWin32::processEvents [0x7ffb74e5bcfa] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ffb71b428d9] <qwindows.dll>
 25> TSmartPointerT<TXshPaletteLevel>::~TSmartPointerT<TXshPaletteLevel> [0x7ff7aff0efa8] <OpenToonz.exe>
 26> QCoreApplicationPrivate::sendThroughApplicationEventFilters [0x7ffb74e15112] <Qt5Core.dll>
 27> QApplicationPrivate::notify_helper [0x7ffb75d65502] <Qt5Widgets.dll>
 28> QApplication::notify [0x7ffb75d64643] <Qt5Widgets.dll>
 29> QCoreApplication::notifyInternal2 [0x7ffb74e1318a] <Qt5Core.dll>
 30> QGuiApplicationPrivate::processTabletLeaveProximityEvent [0x7ffb7525589d] <Qt5Gui.dll>
 31> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb7523f030] <Qt5Gui.dll>
 32> QEventDispatcherWin32::processEvents [0x7ffb74e5bcfa] <Qt5Core.dll>
 33> qt_plugin_query_metadata [0x7ffb71b428d9] <qwindows.dll>
 34> QEventLoop::exec [0x7ffb74e0f64c] <Qt5Core.dll>
 35> QCoreApplication::exec [0x7ffb74e12164] <Qt5Core.dll>
 36> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff7afec5219] <OpenToonz.exe>
 37> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b02eeab7] <OpenToonz.exe>
 38> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff7b02ee092] <OpenToonz.exe>
 39> BaseThreadInitThunk [0x7ffbdbfa257d] <KERNEL32.DLL>
 40> RtlUserThreadStart [0x7ffbdd0eaf28] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
Is Autosave set to 5 minutes in Preferences?

**Comment by redpanda-st** [comment]
Yes I set it after the first crash because I lost a part of my work.
________________________________
De : Rodney ***@***.***>
Envoyé : lundi, août 12, 2024 2:14 AM
À : opentoonz/opentoonz ***@***.***>
Cc : redpanda-st ***@***.***>; Author ***@***.***>
Objet : Re: [opentoonz/opentoonz] Opentoonz start to crash (Issue #5565)


Is Autosave set to 5 minutes in Preferences?

**Comment by RodneyBaker** [comment]
Autosave is the likely cause of your crashing.
You might test a few different settings and saving locations but the most successful users simply turn Autosave off.
This isn't to say you shouldn't use it but it's important to know what you are using and the risks involved.

If I ever feel the need to turn Autosave on (which is VERY rare) I will tend to set it to 30 minutes and use it IN ADDITION to manually saving at each point in the project where I change major tasks.  For instance, if I have to render anything... I save.  If I change from drawing line work to coloring/painting... I save.  If I start adding FX to my project... I save first.

What this means is that because I manually save at all of these logical moments Autosave never kicks in... but if I forget due to being tired etc. it will do that at the 15... 30... 60 minute point... but not 5 minutes... that's asking for problems with Autosave in my estimation.  If I'm too far into a project in which case I probably should take a break anyway... that's a great time to take a short break but before I do... to manually save.

We can explore more about why Opentoonz is not playing nice and leading to issues.
There are usually a few know things to look out for such as use of Plastic Tool and various computational expensive process.. especially with Preview turned on.  These can lead to instances where Opentoonz is calculating/processing but the user doesn't realize this and enters a multitude of additional clicks launching new processes... leading to deeper lockups and the inevitable pain.


Losing work is painful but it's better to find out more about why the work was lost than to rely on autosave.

**Comment by redpanda-st** [comment]
First of all, thank you so much for your precious answer (especially that in my time zone it’s almost 3pm 😅). I didn’t know that the autosave was so energy-consuming (sorry my english is bad 💀). By the way, I find the fact that you, the "support helper" use opentoonz too for your own project is cool ! You can give advice like you did and yeah that’s a good thing. I will save in my muscle memory the importance to save currently and I hope it will help me with my crash (I strongly believe that it will help, I couldn’t doubt) Thanks for your advice and have a great day or evening. If it interests you for the information I might update you if it works or not (I’ll go to sleep now so tomorrow).
________________________________
De : Rodney ***@***.***>
Envoyé : lundi, août 12, 2024 2:32 AM
À : opentoonz/opentoonz ***@***.***>
Cc : redpanda-st ***@***.***>; Author ***@***.***>
Objet : Re: [opentoonz/opentoonz] Opentoonz start to crash (Issue #5565)


Autosave is the likely cause of your crashing.
You might test a few different settings and saving locations but the most successful users simply turn Autosave off.
This isn't to say you shouldn't use it but it's important to know what you are using and the risks involved.

If I ever feel the need to turn Autosave on (which is VERY rare) I will tend to set it to 30 minutes and use it IN ADDITION to manually saving at each point in the project where I change major tasks. For instance, if I have to render anything... I save. If I change from drawing line work to coloring/painting... I save. If I start adding FX to my project... I save first.

What this means is that because I manually save at all of these logical moments Autosave never kicks in... but if I forget due to being tired etc. it will do that at the 15... 30... 60 minute point... but not 5 minutes... that's asking for problems with Autosave in my estimation. If I'm too far into a project in which case I probably should take a break anyway... that's a great time to take a short break but before I do... to manually save.

We can explore more about why Opentoonz is not playing nice and leading to issues.
There are usually a few know things to look out for such as use of Plastic Tool and various computational expensive process.. especially with Preview turned on. These can lead to instances where Opentoonz is calculating/processing but the user doesn't realize this and enters a multitude of additional clicks launching new processes... leading to deeper lockups and the inevitable pain.

Losing work is painful but it's better to find out more about why the work was lost than to rely on autosave.

**Comment by cutydina** [comment]
Does this issue is solved? just wondering. Still cannot open latest version.

**Comment by RodneyBaker** [comment]
> Does this issue is solved? just wondering. Still cannot open latest version.

@cutydina There are two specific known issues that will prevent startup and... no other one of that kind reported.
As such it is likely that one of these two is your problem.

Both are pinned at the top of this repo, here:

https://github.com/opentoonz/opentoonz/issues

In both cases, renaming a file or directory will resolve the issue.

When you say 'latest version'... 
If by that you mean a recent nightly release, then you likely have the following problem:  #5351

The nightly resolves many problems but unfortunately won't start until this workaround is implemented.

It's possible you could have both this Logitech driver problem AND the second (SRV - MOV quicktime) problem.
If you have the same crash report as identified here then you don't likely have this Logitech driver issue as that is easy to spot in a crash report.

It seems likely that @redpanda-st's problem can be resolved by updating to a nightly release.
BUT AGAIN... that nightly release won't start until the SRV problem is resolved.
That renaming process is outlined as mentioned above:  #5351

The Logitech webcam driver problem and it's renaming workaround can be found here:  #5551 

Both reports end in '51' so that can be a little confusing.

So... what the 'fix'?

For best path forward (for Windows users) I will recommend installing the nightly from May here:

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_10da5fb957382ac9d94612efa63ed9da216a6b8b/OpenToonzSetup.exe

This will likely have the SRV problem which will need to be addressed as outlined in #5351.


It's a less than 5 minute process from download to resolution but can be tricky when not familiar with the process of finding and renaming the proper files.  This for both the Logitech and SRV/MOV problem.

**Comment by redpanda-st** [comment]
Oh sorry I forgot to keep you informed 😅. YES THAT ISSUE IS SOLVED 😌. I still have some crash but that’s pretty rare and I have the reflex to save currently now. I even have finish my animation 🥳. Thank you so much for your help ! Have a wonderful day 😁!
________________________________
De : Rodney ***@***.***>
Envoyé : Saturday, August 24, 2024 8:56:18 PM
À : opentoonz/opentoonz ***@***.***>
Cc : redpanda-st ***@***.***>; Mention ***@***.***>
Objet : Re: [opentoonz/opentoonz] Opentoonz start to crash (Issue #5565)


Does this issue is solved? just wondering. Still cannot open latest version.

@cutydina<https://github.com/cutydina> There are two specific known issues that will prevent startup and... no other one of that kind reported.
As such it is likely that one of these two is your problem.

Both are pinned at the top of this repo, here:

https://github.com/opentoonz/opentoonz/issues

In both cases, renaming a file or directory will resolve the issue.

When you say 'latest version'...
If by that you mean a recent nightly release, then you likely have the following problem: #5351<https://github.com/opentoonz/opentoonz/issues/5351>

The nightly resolves many problems but unfortunately won't start until this workaround is implemented.

It's possible you could have both this Logitech driver problem AND the second (SRV - MOV quicktime) problem.
If you have the same crash report as identified here then you don't likely have this Logitech driver issue as that is easy to spot in a crash report.

It seems likely that @redpanda-st<https://github.com/redpanda-st>'s problem can be resolved by updating to a nightly release.
BUT AGAIN... that nightly release won't start until the SRV problem is resolved.
That renaming process is outlined as mentioned above: #5351<https://github.com/opentoonz/opentoonz/issues/5351>

The Logitech webcam driver problem and it's renaming workaround can be found here: #5551<https://github.com/opentoonz/opentoonz/issues/5551>

Both reports end in '51' so that can be a little confusing.

So... what the 'fix'?

For best path forward (for Windows users) I will recommend installing the nightly from May here:

https://github.com/opentoonz/opentoonz_nightlies/releases/download/nightly_10da5fb957382ac9d94612efa63ed9da216a6b8b/OpenToonzSetup.exe

This will likely have the SRV problem which will need to be addressed as outlined in #5351<https://github.com/opentoonz/opentoonz/issues/5351>.

It's a less than 5 minute process from download to resolution but can be tricky when not familiar with the process of finding and renaming the proper files. This for both the Logitech and SRV/MOV problem.

**Comment by RodneyBaker** [comment]
Thanks for the response and for closing the loop on your report.
Much appreciated.

Will close this report but @cutydina please let us know if you get your problem resolved as well.
