### ISSUE TITLE
errores 

### ISSUE THREAD

**Issue by jhonatannina** [opentoonz/opentoonz#5569]
### Ask a question related to OpenToonz

OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-08-16 21:30:06
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 1903
OS Kernel: 10.0.18362
CPU Threads: 20

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 531.41

Crash File: C:\Users\Capital PC®\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240816-213006.log
Mini Dump File: C:\Users\Capital PC®\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240816-213006.dmp

Application Dir: C:/diseño 2D/OpenToonz
Stuff Dir: C:\diseño 2D

Project Name: sandbox
Scene Name: waifu
Project Path: C:\diseño 2D\sandbox\sandbox_otprj.xml
Scene Path: C:\diseño 2D\sandbox\scenes\waifu.tnz

==== Modules ====
C:\dise�o 2D\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\dise�o 2D\OpenToonz\Qt5Xml.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\SYSTEM32\OPENGL32.dll
C:\dise�o 2D\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\SHELL32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\windows.storage.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\System32\profapi.dll
C:\dise�o 2D\OpenToonz\glut64.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\powrprof.dll
C:\Windows\System32\UMPDC.dll
C:\Windows\System32\SHLWAPI.dll
C:\dise�o 2D\OpenToonz\Qt5SerialPort.dll
C:\Windows\System32\kernel.appcore.dll
C:\Windows\System32\cryptsp.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\OLEAUT32.dll
C:\dise�o 2D\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\dise�o 2D\OpenToonz\colorfx.dll
C:\Windows\System32\bcrypt.dll
C:\dise�o 2D\OpenToonz\image.dll
C:\Windows\System32\WS2_32.dll
C:\dise�o 2D\OpenToonz\tnztools.dll
C:\dise�o 2D\OpenToonz\tnzstdfx.dll
C:\dise�o 2D\OpenToonz\tfarm.dll
C:\dise�o 2D\OpenToonz\Qt5Widgets.dll
C:\dise�o 2D\OpenToonz\sound.dll
C:\dise�o 2D\OpenToonz\toonzqt.dll
C:\dise�o 2D\OpenToonz\Qt5Gui.dll
C:\dise�o 2D\OpenToonz\Qt5Core.dll
C:\dise�o 2D\OpenToonz\Qt5Script.dll
C:\dise�o 2D\OpenToonz\tnzext.dll
C:\dise�o 2D\OpenToonz\tnzbase.dll
C:\dise�o 2D\OpenToonz\opencv_world451.dll
C:\dise�o 2D\OpenToonz\toonzlib.dll
C:\dise�o 2D\OpenToonz\tnzcore.dll
C:\dise�o 2D\OpenToonz\Qt5OpenGL.dll
C:\Windows\SYSTEM32\MPR.dll
C:\dise�o 2D\OpenToonz\Qt5Multimedia.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\dise�o 2D\OpenToonz\Qt5Network.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\System32\CRYPT32.dll
C:\Windows\System32\MSASN1.dll
C:\dise�o 2D\OpenToonz\MSVCP140_1.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.116_none_2a240152466d1e37\COMCTL32.dll
C:\dise�o 2D\OpenToonz\MSVCP140.dll
C:\dise�o 2D\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINMM.dll
C:\Windows\SYSTEM32\MFPlat.DLL
C:\Windows\SYSTEM32\MF.dll
C:\dise�o 2D\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\VERSION.dll
C:\dise�o 2D\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\dise�o 2D\OpenToonz\CONCRT140.dll
C:\dise�o 2D\OpenToonz\libmypaint-1-4-0.dll
C:\dise�o 2D\OpenToonz\Qt5Svg.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\System32\NSI.dll
C:\Windows\SYSTEM32\WINMMBASE.dll
C:\Windows\SYSTEM32\MSACM32.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\dise�o 2D\OpenToonz\libintl-8.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\dise�o 2D\OpenToonz\libjson-c-2.dll
C:\dise�o 2D\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\dise�o 2D\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\dise�o 2D\OpenToonz\styles\qwindowsvistastyle.dll
C:\dise�o 2D\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\WINTRUST.dll
C:\Windows\System32\imagehlp.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\System32\TextInputFramework.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\System32\iertutil.dll
C:\Windows\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_50916785244854f2\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\SYSTEM32\wldp.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\RMCLIENT.dll
C:\Windows\system32\dwrite.dll
C:\dise�o 2D\OpenToonz\imageformats\qgif.dll
C:\dise�o 2D\OpenToonz\imageformats\qicns.dll
C:\dise�o 2D\OpenToonz\imageformats\qico.dll
C:\dise�o 2D\OpenToonz\imageformats\qjpeg.dll
C:\dise�o 2D\OpenToonz\imageformats\qsvg.dll
C:\dise�o 2D\OpenToonz\imageformats\qtga.dll
C:\dise�o 2D\OpenToonz\imageformats\qtiff.dll
C:\dise�o 2D\OpenToonz\imageformats\qwbmp.dll
C:\dise�o 2D\OpenToonz\imageformats\qwebp.dll
C:\dise�o 2D\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
C:\dise�o 2D\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\System32\winrnr.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\system32\wshbth.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\SYSTEM32\apphelp.dll
C:\Windows\system32\DeviceCenter.dll
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.116_none_e6c4ac41130f2c3a\COMCTL32.dll
C:\Windows\system32\DUI70.dll
C:\Windows\system32\Windows.Storage.Search.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
C:\Windows\SYSTEM32\WindowsCodecs.dll
C:\Windows\System32\thumbcache.dll
==== End ====

==== Backtrace ====
  1> RtlIsGenericTableEmpty [0x7ffbb8cf85d6] <ntdll.dll>
  2> RtlRaiseException [0x7ffbb8cea076] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffbb8d1fe0e] <ntdll.dll>
  4> computeRegionFeature [0x7ffb4a4eb63e] <tnzcore.dll>
  5> TVectorImage::moveStrokes [0x7ffb4a518cb4] <tnzcore.dll>
  6> TVectorImage::notifyChangedStrokes [0x7ffb4a518f82] <tnzcore.dll>
  7> ToolOptions::showEvent [0x7ffb84bb0177] <tnztools.dll>
  8> PinchTool::getToolType [0x7ffb84acd2b4] <tnztools.dll>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77dc0b4fd] <OpenToonz.exe>
 10> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77dc0a5f8] <OpenToonz.exe>
 11> QWidget::event [0x7ffb527c8066] <Qt5Widgets.dll>
 12> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77dc0942b] <OpenToonz.exe>
 13> QApplicationPrivate::notify_helper [0x7ffb527a55c0] <Qt5Widgets.dll>
 14> QApplication::notify [0x7ffb527a34e0] <Qt5Widgets.dll>
 15> QCoreApplication::notifyInternal2 [0x7ffb4e8d318a] <Qt5Core.dll>
 16> QApplicationPrivate::sendMouseEvent [0x7ffb527a67c5] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ffb527f09d2] <Qt5Widgets.dll>
 18> QDesktopWidget::workAreaResized [0x7ffb527ee96e] <Qt5Widgets.dll>
 19> QApplicationPrivate::notify_helper [0x7ffb527a55c0] <Qt5Widgets.dll>
 20> QApplication::notify [0x7ffb527a4643] <Qt5Widgets.dll>
 21> QCoreApplication::notifyInternal2 [0x7ffb4e8d318a] <Qt5Core.dll>
 22> QGuiApplicationPrivate::processMouseEvent [0x7ffb521547c3] <Qt5Gui.dll>
 23> QWindowSystemInterface::sendWindowSystemEvents [0x7ffb5213f030] <Qt5Gui.dll>
 24> QEventDispatcherWin32::processEvents [0x7ffb4e91bcfa] <Qt5Core.dll>
 25> qt_plugin_query_metadata [0x7ffb4a0a28d9] <qwindows.dll>
 26> QEventLoop::exec [0x7ffb4e8cf64c] <Qt5Core.dll>
 27> QCoreApplication::exec [0x7ffb4e8d2164] <Qt5Core.dll>
 28> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff77db25219] <OpenToonz.exe>
 29> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77df4eab7] <OpenToonz.exe>
 30> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff77df4e092] <OpenToonz.exe>
 31> BaseThreadInitThunk [0x7ffbb77e7bd4] <KERNEL32.DLL>
 32> RtlUserThreadStart [0x7ffbb8cece71] <ntdll.dll>
==== End ====

**Comment by RodneyBaker** [comment]
You have a lot of special characters in file names which might lead to problems.
I would first remove those and see if that doesn't help.

**Comment by gab3d** [comment]
@jhonatannina 
Hola, ¿podés explicar con palabras lo que te está psando?
sólo con el reporte que genera el programa no va a ser suficiente.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@jhonatannina Please let us know if you are still experience this problem.
