### ISSUE TITLE
"Toonz" here is not refer to [/toonz](https://github.com/opentoonz/opentoonz/tree/master/toonz) , right? 

### ISSUE THREAD

**Issue by liaodalin19903** [opentoonz/opentoonz#5570]
### Ask a question related to OpenToonz

When I browse the [README.md](https://github.com/opentoonz/opentoonz/blob/master/README.md?plain=1#L55)

> This Open Source Program is developed from Toonz

"Toonz" here is not refer to [/toonz](https://github.com/opentoonz/opentoonz/tree/master/toonz) , right?

**Comment by RodneyBaker** [comment]
No, it refers to the Toonz software created by Digital Video, from Italy.

REF: https://en.wikipedia.org/wiki/Toonz
