### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION no lvcod64 or lvcode64 in system32. First time opening.

### ISSUE THREAD

**Issue by Yoyoguel** [opentoonz/opentoonz#5571]
### Description

Tried reseting the pc, unninstaling the program and changing the compatibility mode to windows 8 and opening as administrator, all didn't work. There's no lvcod64 or lvcode64 in my computer.

### Steps to Reproduce

1. Clicking the icon on desktop and original folder. (same result)
2. 

### Expected Behavior

To Open

### Screenshots, Video & Crash Logs

OpenToonz 1.7.1  (Build May 16 2024)

Report Date: 2024-08-19 01:31:18
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 8 Version 6.2 (Build 22631)
OS Kernel: 6.2.9200
CPU Threads: 12

Crash File: C:\Users\COMPUTADOR\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240819-013118.log
Mini Dump File: C:\Users\COMPUTADOR\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20240819-013118.dmp

==== Modules ====
D:\Jogos\Opentoonz\OpenToonz\OpenToonz.exe
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\Program Files\Bitdefender\Bitdefender Security\bdhkm\dlls_267023968712520337\bdhkm64.dll
C:\Program Files\Bitdefender\Bitdefender Security\atcuf\dlls_267312708619262074\atcuf64.dll
C:\WINDOWS\SYSTEM32\apphelp.dll
C:\WINDOWS\SYSTEM32\AcLayers.DLL
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\System32\SHLWAPI.dll
C:\WINDOWS\SYSTEM32\SortWindows61.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\SHELL32.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\OLEAUT32.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Xml.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5PrintSupport.dll
C:\WINDOWS\System32\COMDLG32.dll
C:\WINDOWS\System32\shcore.dll
C:\WINDOWS\SYSTEM32\OPENGL32.dll
C:\WINDOWS\System32\ADVAPI32.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\bcrypt.dll
D:\Jogos\Opentoonz\OpenToonz\glut64.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5SerialPort.dll
C:\WINDOWS\System32\SETUPAPI.dll
D:\Jogos\Opentoonz\OpenToonz\EDSDK.dll
C:\WINDOWS\System32\WS2_32.dll
D:\Jogos\Opentoonz\OpenToonz\colorfx.dll
D:\Jogos\Opentoonz\OpenToonz\image.dll
D:\Jogos\Opentoonz\OpenToonz\tnztools.dll
D:\Jogos\Opentoonz\OpenToonz\tnzstdfx.dll
D:\Jogos\Opentoonz\OpenToonz\tfarm.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Widgets.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Gui.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Core.dll
D:\Jogos\Opentoonz\OpenToonz\toonzqt.dll
D:\Jogos\Opentoonz\OpenToonz\sound.dll
D:\Jogos\Opentoonz\OpenToonz\opencv_world451.dll
D:\Jogos\Opentoonz\OpenToonz\toonzlib.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Script.dll
D:\Jogos\Opentoonz\OpenToonz\tnzext.dll
D:\Jogos\Opentoonz\OpenToonz\tnzbase.dll
D:\Jogos\Opentoonz\OpenToonz\tnzcore.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5OpenGL.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Multimedia.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Network.dll
C:\WINDOWS\System32\CRYPT32.dll
C:\WINDOWS\SYSTEM32\MPR.dll
C:\WINDOWS\SYSTEM32\GLU32.dll
C:\WINDOWS\SYSTEM32\dbghelp.dll
D:\Jogos\Opentoonz\OpenToonz\MSVCP140.dll
C:\WINDOWS\SYSTEM32\MFPlat.DLL
C:\WINDOWS\SYSTEM32\MF.dll
D:\Jogos\Opentoonz\OpenToonz\VCRUNTIME140.dll
D:\Jogos\Opentoonz\OpenToonz\VCRUNTIME140_1.dll
D:\Jogos\Opentoonz\OpenToonz\MSVCP140_1.dll
C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.3527_none_b43b7f4b638cc64f\COMCTL32.dll
C:\WINDOWS\SYSTEM32\WINMM.dll
C:\WINDOWS\SYSTEM32\VERSION.dll
C:\WINDOWS\SYSTEM32\MSVFW32.dll
C:\WINDOWS\SYSTEM32\AVIFIL32.dll
D:\Jogos\Opentoonz\OpenToonz\libmypaint-1-4-0.dll
D:\Jogos\Opentoonz\OpenToonz\glew32.dll
C:\WINDOWS\SYSTEM32\UxTheme.dll
C:\WINDOWS\SYSTEM32\dwmapi.dll
C:\WINDOWS\SYSTEM32\d3d11.dll
C:\WINDOWS\SYSTEM32\dxgi.dll
C:\WINDOWS\SYSTEM32\USERENV.dll
C:\WINDOWS\SYSTEM32\NETAPI32.dll
D:\Jogos\Opentoonz\OpenToonz\Qt5Svg.dll
D:\Jogos\Opentoonz\OpenToonz\CONCRT140.dll
C:\WINDOWS\SYSTEM32\DNSAPI.dll
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
C:\WINDOWS\SYSTEM32\cfgmgr32.dll
C:\WINDOWS\SYSTEM32\MSACM32.dll
D:\Jogos\Opentoonz\OpenToonz\libintl-8.dll
D:\Jogos\Opentoonz\OpenToonz\libjson-c-2.dll
C:\WINDOWS\SYSTEM32\dbgcore.DLL
C:\WINDOWS\SYSTEM32\dxcore.dll
D:\Jogos\Opentoonz\OpenToonz\libiconv-2.dll
C:\WINDOWS\SYSTEM32\NETUTILS.DLL
C:\WINDOWS\SYSTEM32\MFCORE.DLL
C:\WINDOWS\SYSTEM32\SRVCLI.DLL
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\SYSTEM32\LOGONCLI.DLL
C:\WINDOWS\SYSTEM32\SAMCLI.DLL
C:\WINDOWS\SYSTEM32\WKSCLI.DLL
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\NSI.dll
C:\WINDOWS\SYSTEM32\kernel.appcore.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\SYSTEM32\RTWorkQ.DLL
D:\Jogos\Opentoonz\OpenToonz\platforms\qwindows.dll
C:\WINDOWS\SYSTEM32\WTSAPI32.dll
C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
C:\WINDOWS\SYSTEM32\windows.storage.dll
C:\WINDOWS\SYSTEM32\wintypes.dll
C:\WINDOWS\SYSTEM32\profapi.dll
C:\WINDOWS\SYSTEM32\powrprof.dll
C:\WINDOWS\SYSTEM32\UMPDC.dll
D:\Jogos\Opentoonz\OpenToonz\styles\qwindowsvistastyle.dll
D:\Jogos\Opentoonz\OpenToonz\iconengines\qsvgicon.dll
C:\WINDOWS\system32\d3d9.dll
C:\WINDOWS\SYSTEM32\msasn1.dll
C:\WINDOWS\SYSTEM32\cryptnet.dll
C:\WINDOWS\System32\wintrust.dll
C:\WINDOWS\System32\imagehlp.dll
C:\WINDOWS\SYSTEM32\CRYPTSP.dll
C:\WINDOWS\system32\rsaenh.dll
C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
C:\WINDOWS\System32\MSCTF.dll
C:\WINDOWS\SYSTEM32\textinputframework.dll
C:\WINDOWS\SYSTEM32\CoreMessaging.dll
C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
C:\WINDOWS\System32\clbcatq.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_de8e1115ac61e38a\nvoglv64.dll
C:\WINDOWS\SYSTEM32\drvstore.dll
C:\WINDOWS\SYSTEM32\devobj.dll
C:\WINDOWS\SYSTEM32\wldp.dll
C:\WINDOWS\SYSTEM32\ntmarta.dll
C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_de8e1115ac61e38a\nvgpucomp64.dll
C:\WINDOWS\system32\nvspcap64.dll
C:\WINDOWS\SYSTEM32\WINSTA.dll
C:\WINDOWS\system32\dataexchange.dll
C:\WINDOWS\system32\twinapi.appcore.dll
C:\WINDOWS\system32\dwrite.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\SYSTEM32\ff_vfw.dll
C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3672_none_2713b9d173822955\COMCTL32.dll
C:\Program Files (x86)\K-Lite Codec Pack\Filters\ffdshow64\ffdshow.ax
C:\WINDOWS\SYSTEM32\DINPUT.dll
C:\WINDOWS\SYSTEM32\SspiCli.dll
C:\WINDOWS\SYSTEM32\inputhost.dll
==== End ====

==== Backtrace ====
  1> RtlGetLengthWithoutLastFullDosOrNtPathElement [0x7ffa17807f5a] <ntdll.dll>
  2> RtlFindCharInUnicodeString [0x7ffa177ae642] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ffa1783403e] <ntdll.dll>
  4> DriverProc [0x7ff9939152e3] <ff_vfw.dll>
  5> ICSendMessage [0x7ff9ae18413e] <MSVFW32.dll>
  6> TSmartHolderT<TXshSimpleLevel>::set [0x7ff98affbb98] <image.dll>
  7> TSmartHolderT<TXshSimpleLevel>::set [0x7ff98aff91c6] <image.dll>
  8> initImageIo [0x7ff98af97bd4] <image.dll>
  9> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff786c0200e] <OpenToonz.exe>
 10> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff786c03f41] <OpenToonz.exe>
 11> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff78703cc97] <OpenToonz.exe>
 12> TSmartPointerConstT<TXshSoundTextLevel>::~TSmartPointerConstT<TXshSoundTextLevel> [0x7ff78703c272] <OpenToonz.exe>
 13> BaseThreadInitThunk [0x7ffa156d257d] <KERNEL32.DLL>
 14> RtlUserThreadStart [0x7ffa177eaf28] <ntdll.dll>
==== End ====

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Lastest

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
This line from your crash report suggests to me that you have a codec problem:

C:\Program Files (x86)\K-Lite Codec Pack\Filters\ffdshow64\[ffdshow.ax](http://ffdshow.ax/)

**Comment by Yoyoguel** [comment]
What do you suggest to fix it?

**Comment by Yoyoguel** [comment]
I fixed! 
Unninstaled the codec pack and VLC and reinstalled VLC. Then a error with t32bitsrv.exe started happening, renamed to t32bitsrv.exe.old and the program is going strong!
