### ISSUE TITLE
Crash Reason: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by liopui** [opentoonz/opentoonz#5573]
### Description

Crash Reason: EXCEPTION_ACCESS_VIOLATION

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
Closing as a duplicate of #5574
