### ISSUE TITLE
drawing requirements

### ISSUE THREAD

**Issue by VedankCartoonist** [opentoonz/opentoonz#5582]
### Ask a question related to OpenToonz

hi i am new in opentoonz can any one suggest me brushes for sketching and lineart or give me brush presets to download

**Comment by DarrenTAnims** [comment]
I tend to use one of the pencil brushes (in the Raster tab, near where you choose your colour).
These are for Raster & Toonz Raster levels only, not vector.
Also, I recommend creating your level before you draw, so you know exactly what level type you're drawing on. You can also set the size in that popup, if you want a larger area. I think it's a good habit to get into.

**Comment by VedankCartoonist** [comment]
can you give me vector brush presets to download and thanks for the advice

**Comment by DarrenTAnims** [comment]
There are no presets I can recommend.
It depends on your art style, your drawing technique and what you're drawing.
You'd use more smoothing for longer, smooth lines an less for shorter lines.
The accuracy specifies how accurate to your drawn line, the final line will be, but that will add more control points, which will slow down your computer and make them harder to edit.
However, the first thing to consider is, do you really need to use vector? There's so many problems new users have with vector that I try to discourage its use.

**Comment by VedankCartoonist** [comment]
Actually I was thinking about using raster for rough sketching and vector for lineart  but i was kind of struggling to draw that is why I asked for presets

**Comment by VedankCartoonist** [comment]
Thanks alot 🤩
