### ISSUE TITLE
bugssss

### ISSUE THREAD

**Issue by MISHTHI812** [opentoonz/opentoonz#5584]
### Description

it gets hang easily and can not save files quickly

### Steps to Reproduce

1. increase the smoothness
2. 
e

### Expected Behavior

nothing

### Screenshots, Video & Crash Logs

no
*

### OpenToonz Version

1.7

### OpenToonz Version Information

ex.september 5

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

XP-Pen

**Comment by MISHTHI812** [comment]
thank you

**Comment by MISHTHI812** [comment]
hello

**Comment by RodneyBaker** [comment]
Hi,
You may want to join one of the (many) Opentoonz venues such as on discord where others can help you troubleshoot problems.

Invitation link:  https://discord.gg/hvVj44K4ee
