### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by Rdr544** [opentoonz/opentoonz#5587]
### Description

crashed

### Steps to Reproduce

1. .
2. .

### Expected Behavior

.

### Screenshots, Video & Crash Logs

.

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

AMD

### Graphics Tablet

None

**Comment by DarrenTAnims** [comment]
Please fill in the details of the report, if you wish to make one.
Just saying "Crashed" will not get anything fixed and the reports will only be closed.
