### ISSUE TITLE
[question] What data persistence technologies and databases does OpenToonz use? 

### ISSUE THREAD

**Issue by liaodalin19903** [opentoonz/opentoonz#5612]
### Ask a question related to OpenToonz

Excuse me, during the use of OpenToonz, a large amount of data and files will be generated. 

What data persistence technologies and databases does OpenToonz use? 

I only searched for sqlite-related code:   
https://github.com/search?q=repo%3Aopentoonz%2Fopentoonz+sqlite&type=code.

**Comment by DarrenTAnims** [comment]
Q. What data persistence technologies and databases does OpenToonz use?
A. Saving to files on disk.
