### ISSUE TITLE
complaining about opentoonz performance with big projects

### ISSUE THREAD

**Issue by yuyuhakuch** [opentoonz/opentoonz#5618]
### Description

when im animating and press play to see my drawing the software crushes and say you need to restart the soft and the reason is : Crash Reason: EXCEPTION_ACCESS_VIOLATION 

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

Wacom

**Comment by DarrenTAnims** [comment]
You've added no steps to reproduce the issue and haven't completed some of the fields, so there's not a lot that can be done.

**Comment by RodneyBaker** [comment]
Closing this report as lacking sufficient information to diagnose and troubleshoot the problem.
@yuyuhakuch If you have additional information you can share related to the performance issues you are expriencing that will be appreciated.

Something that has helped many users, especally if using older systems or limited RAM (and even where systems are newer and RAM is plentiful) is to break down scenes into individual shots as this will make eash scene/shot perform more optimally and release resource more easily.
