### ISSUE TITLE
opentoonz unexpectedly failed

### ISSUE THREAD

**Issue by Silverhand414** [opentoonz/opentoonz#5627]
### Description

Opentoonz crashes after a while
OpenToonz 1.7.1  (Build Mar 14 2023)

Report Date: 2024-10-26 22:46:59
Crash Reason: EXCEPTION_ACCESS_VIOLATION

Build ABI: x86_64-little_endian-llp64
Operating System: Windows 10 Version 2009
OS Kernel: 10.0.19045
CPU Threads: 6

GPU Vendor: NVIDIA Corporation
GPU Model: NVIDIA GeForce RTX 3050/PCIe/SSE2
GPU Version: 4.6.0 NVIDIA 566.03

Crash File: C:\Users\TEST\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20241026-224659.log
Mini Dump File: C:\Users\TEST\AppData\Local\OpenToonz\OpenToonz\crash\Crash-20241026-224659.dmp

Application Dir: A:/OpenToonz
Stuff Dir: A:\OpenToonz stuff

Project Name: Milk outside a bag 
Scene Name: Choise meme
Project Path: A:\OpenToonz stuff\projects\Milk outside a bag \Milk outside a bag _otprj.xml
Scene Path: A:\OpenToonz stuff\projects\Milk outside a bag \scenes\Choise meme.tnz

==== Modules ====
A:\OpenToonz\OpenToonz.exe
C:\Windows\SYSTEM32\ntdll.dll
C:\Windows\System32\KERNEL32.DLL
C:\Windows\System32\KERNELBASE.dll
C:\Windows\System32\USER32.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\GDI32.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\SHELL32.dll
A:\OpenToonz\Qt5Xml.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\RPCRT4.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\OLEAUT32.dll
A:\OpenToonz\glut64.dll
A:\OpenToonz\EDSDK.dll
C:\Windows\System32\SETUPAPI.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\WS2_32.dll
C:\Windows\System32\ADVAPI32.dll
C:\Windows\System32\sechost.dll
A:\OpenToonz\colorfx.dll
A:\OpenToonz\image.dll
A:\OpenToonz\tnztools.dll
A:\OpenToonz\tnzstdfx.dll
A:\OpenToonz\tfarm.dll
A:\OpenToonz\Qt5SerialPort.dll
C:\Windows\SYSTEM32\OPENGL32.dll
A:\OpenToonz\Qt5PrintSupport.dll
C:\Windows\System32\COMDLG32.dll
C:\Windows\System32\shcore.dll
C:\Windows\System32\SHLWAPI.dll
A:\OpenToonz\Qt5Widgets.dll
A:\OpenToonz\Qt5Core.dll
A:\OpenToonz\sound.dll
A:\OpenToonz\toonzqt.dll
A:\OpenToonz\Qt5Gui.dll
A:\OpenToonz\opencv_world451.dll
A:\OpenToonz\toonzlib.dll
A:\OpenToonz\Qt5Script.dll
A:\OpenToonz\tnzext.dll
A:\OpenToonz\tnzbase.dll
A:\OpenToonz\Qt5OpenGL.dll
A:\OpenToonz\tnzcore.dll
A:\OpenToonz\Qt5Multimedia.dll
A:\OpenToonz\Qt5Network.dll
C:\Windows\System32\CRYPT32.dll
C:\Windows\SYSTEM32\dbghelp.dll
C:\Windows\SYSTEM32\GLU32.dll
C:\Windows\SYSTEM32\MPR.dll
C:\Windows\SYSTEM32\MFPlat.DLL
A:\OpenToonz\MSVCP140.dll
C:\Windows\SYSTEM32\MF.dll
A:\OpenToonz\VCRUNTIME140.dll
C:\Windows\SYSTEM32\WINMM.dll
A:\OpenToonz\VCRUNTIME140_1.dll
C:\Windows\SYSTEM32\VERSION.dll
A:\OpenToonz\MSVCP140_1.dll
C:\Windows\SYSTEM32\AVIFIL32.dll
C:\Windows\SYSTEM32\MSVFW32.dll
A:\OpenToonz\libmypaint-1-4-0.dll
A:\OpenToonz\glew32.dll
C:\Windows\SYSTEM32\WINSPOOL.DRV
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.4355_none_792ecafd2442822f\COMCTL32.dll
C:\Windows\SYSTEM32\UxTheme.dll
C:\Windows\SYSTEM32\dwmapi.dll
C:\Windows\SYSTEM32\USERENV.dll
C:\Windows\SYSTEM32\NETAPI32.dll
C:\Windows\SYSTEM32\d3d11.dll
C:\Windows\SYSTEM32\dxgi.dll
A:\OpenToonz\Qt5Svg.dll
A:\OpenToonz\CONCRT140.dll
C:\Windows\SYSTEM32\DNSAPI.dll
C:\Windows\SYSTEM32\IPHLPAPI.DLL
C:\Windows\SYSTEM32\MSACM32.dll
A:\OpenToonz\libintl-8.dll
A:\OpenToonz\libjson-c-2.dll
C:\Windows\SYSTEM32\NETUTILS.DLL
A:\OpenToonz\libiconv-2.dll
C:\Windows\SYSTEM32\dbgcore.DLL
C:\Windows\SYSTEM32\winmmbase.dll
C:\Windows\SYSTEM32\MFCORE.DLL
C:\Windows\SYSTEM32\SRVCLI.DLL
C:\Windows\SYSTEM32\powrprof.dll
C:\Windows\SYSTEM32\ksuser.dll
C:\Windows\SYSTEM32\CRYPTBASE.DLL
C:\Windows\SYSTEM32\kernel.appcore.dll
C:\Windows\System32\IMM32.DLL
C:\Windows\System32\NSI.dll
C:\Windows\System32\bcryptPrimitives.dll
C:\Windows\SYSTEM32\RTWorkQ.DLL
C:\Windows\SYSTEM32\UMPDC.dll
A:\OpenToonz\platforms\qwindows.dll
C:\Windows\SYSTEM32\WTSAPI32.dll
C:\Windows\SYSTEM32\windows.storage.dll
C:\Windows\SYSTEM32\Wldp.dll
C:\Windows\SYSTEM32\profapi.dll
A:\OpenToonz\styles\qwindowsvistastyle.dll
A:\OpenToonz\iconengines\qsvgicon.dll
C:\Windows\system32\d3d9.dll
C:\Windows\SYSTEM32\msasn1.dll
C:\Windows\SYSTEM32\cryptnet.dll
C:\Windows\System32\wintrust.dll
C:\Windows\System32\imagehlp.dll
C:\Windows\SYSTEM32\CRYPTSP.dll
C:\Windows\system32\rsaenh.dll
C:\Windows\System32\MSCTF.dll
C:\Windows\SYSTEM32\textinputframework.dll
C:\Windows\System32\CoreMessaging.dll
C:\Windows\System32\CoreUIComponents.dll
C:\Windows\SYSTEM32\ntmarta.dll
C:\Windows\SYSTEM32\wintypes.dll
C:\Windows\system32\Oleacc.dll
C:\Windows\system32\UIAutomationCore.dll
C:\Windows\SYSTEM32\PROPSYS.dll
C:\Windows\System32\clbcatq.dll
C:\Windows\SYSTEM32\sxs.dll
C:\Windows\System32\AppXDeploymentClient.dll
C:\Windows\System32\DriverStore\FileRepository\nvmdi.inf_amd64_8de72197f4c7fa03\nvoglv64.dll
C:\Windows\SYSTEM32\drvstore.dll
C:\Windows\SYSTEM32\devobj.dll
C:\Windows\System32\DriverStore\FileRepository\nvmdi.inf_amd64_8de72197f4c7fa03\nvgpucomp64.dll
C:\Windows\SYSTEM32\dxcore.dll
C:\Windows\system32\nvspcap64.dll
C:\Windows\SYSTEM32\WINSTA.dll
C:\Windows\system32\dataexchange.dll
C:\Windows\system32\dcomp.dll
C:\Windows\system32\twinapi.appcore.dll
C:\Windows\system32\dwrite.dll
A:\OpenToonz\imageformats\qgif.dll
A:\OpenToonz\imageformats\qicns.dll
A:\OpenToonz\imageformats\qico.dll
A:\OpenToonz\imageformats\qjpeg.dll
A:\OpenToonz\imageformats\qsvg.dll
A:\OpenToonz\imageformats\qtga.dll
A:\OpenToonz\imageformats\qtiff.dll
A:\OpenToonz\imageformats\qwbmp.dll
A:\OpenToonz\imageformats\qwebp.dll
A:\OpenToonz\bearer\qgenericbearer.dll
C:\Windows\SYSTEM32\dhcpcsvc6.DLL
C:\Windows\SYSTEM32\dhcpcsvc.DLL
C:\Windows\System32\netprofm.dll
C:\Windows\System32\npmproxy.dll
A:\OpenToonz\audio\qtaudio_windows.dll
C:\Windows\SYSTEM32\MMDevAPI.DLL
C:\Windows\SYSTEM32\wdmaud.drv
C:\Windows\SYSTEM32\AVRT.dll
C:\Windows\SYSTEM32\AUDIOSES.DLL
C:\Windows\SYSTEM32\msacm32.drv
C:\Windows\SYSTEM32\midimap.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\rasadhlp.dll
C:\Windows\system32\napinsp.dll
C:\Windows\system32\pnrpnsp.dll
C:\Windows\system32\wshbth.dll
C:\Windows\system32\NLAapi.dll
C:\Windows\System32\winrnr.dll
C:\Program Files\Bonjour\mdnsNSP.dll
C:\Windows\System32\fwpuclnt.dll
C:\Windows\SYSTEM32\LINKINFO.dll
C:\Windows\system32\winhttp.dll
C:\Windows\SYSTEM32\SspiCli.dll
==== End ====

==== Backtrace ====
  1> RtlDeleteAce [0x7ff995e69b4c] <ntdll.dll>
  2> RtlRaiseException [0x7ff995e42376] <ntdll.dll>
  3> KiUserExceptionDispatcher [0x7ff995e913ce] <ntdll.dll>
  4> PinchTool::getToolType [0x7ff912bd4466] <tnztools.dll>
  5> PinchTool::getToolType [0x7ff912bd4808] <tnztools.dll>
  6> PinchTool::getToolType [0x7ff912bd8e07] <tnztools.dll>
  7> PinchTool::getToolType [0x7ff912bd8cd1] <tnztools.dll>
  8> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff68618bec7] <OpenToonz.exe>
  9> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff68618a7ee] <OpenToonz.exe>
 10> QWidget::event [0x7ff912088092] <Qt5Widgets.dll>
 11> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff68618942b] <OpenToonz.exe>
 12> QApplicationPrivate::notify_helper [0x7ff9120655c0] <Qt5Widgets.dll>
 13> QApplication::notify [0x7ff9120634e0] <Qt5Widgets.dll>
 14> QCoreApplication::notifyInternal2 [0x7ff9115d318a] <Qt5Core.dll>
 15> QApplicationPrivate::sendMouseEvent [0x7ff9120667c5] <Qt5Widgets.dll>
 16> QDesktopWidget::workAreaResized [0x7ff9120b09d2] <Qt5Widgets.dll>
 17> QDesktopWidget::workAreaResized [0x7ff9120ae96e] <Qt5Widgets.dll>
 18> QApplicationPrivate::notify_helper [0x7ff9120655c0] <Qt5Widgets.dll>
 19> QApplication::notify [0x7ff912064643] <Qt5Widgets.dll>
 20> QCoreApplication::notifyInternal2 [0x7ff9115d318a] <Qt5Core.dll>
 21> QGuiApplicationPrivate::processMouseEvent [0x7ff911a147c3] <Qt5Gui.dll>
 22> QWindowSystemInterface::sendWindowSystemEvents [0x7ff9119ff030] <Qt5Gui.dll>
 23> QEventDispatcherWin32::processEvents [0x7ff91161bcfa] <Qt5Core.dll>
 24> qt_plugin_query_metadata [0x7ff9127f28d9] <qwindows.dll>
 25> QEventLoop::exec [0x7ff9115cf64c] <Qt5Core.dll>
 26> QCoreApplication::exec [0x7ff9115d2164] <Qt5Core.dll>
 27> TSmartPointerT<TXshSoundLevel>::~TSmartPointerT<TXshSoundLevel> [0x7ff6860a5219] <OpenToonz.exe>
 28> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6864ceab7] <OpenToonz.exe>
 29> TSmartPointerT<TXshSoundTextLevel>::~TSmartPointerT<TXshSoundTextLevel> [0x7ff6864ce092] <OpenToonz.exe>
 30> BaseThreadInitThunk [0x7ff995857374] <KERNEL32.DLL>
 31> RtlUserThreadStart [0x7ff995e3cc91] <ntdll.dll>
==== End ====

### Steps to Reproduce

1. 
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
As is the case with similar reports I'll recommend updating to a more current nightly release although that will require an adjustment to a file/folder to get the program running.

For that adjustment after installing a nightly release please see:  https://github.com/opentoonz/opentoonz/issues/5351

**Comment by Silverhand414** [comment]
Thank you very much!
