### ISSUE TITLE
OpenToonz closes after installation.

### ISSUE THREAD

**Issue by EmptyVoid-Radio** [opentoonz/opentoonz#5638]
### Description

OpenToonz closes after installation. Once installed OpenToonz when opening the program it closes, run the windows compatibility troubleshooter and the error that appears is "t32bitsrv.exe" (The code execution cannot continue because glut32.dll was not found. This problem can be solved by reinstalling the program), I have already reinstalled the program and nothing, also, "glut32.dll" is in the OpenToonz files and still does not open, now I see an OpenToonz background screen that says "Initializing Toonz environment..." What do I do to solve the problem?

### Steps to Reproduce

1. 
2. 

### Screenshots, Video & Crash Logs

![Captura de pantalla (16)](https://github.com/user-attachments/assets/8ad39975-7e76-4a38-b087-af57e91b8c7b)
![Captura de pantalla (18)](https://github.com/user-attachments/assets/b2119e8d-7f5f-46b2-8ce7-56fcec7f299d)

### OpenToonz Version

1.7

### OpenToonz Version Information

1.7.1

### Operating System

Windows

### GPU

Intel

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
The good news is that this is a known issue.
Please see #5351 for specifics on how to rename/remove a file or directory.
Once that is done Opentoonz should run as expected.

**Comment by EmptyVoid-Radio** [comment]
> La buena noticia es que este es un tema conocido. Por favor vea #5351 para detalles sobre cómo cambiar el nombre/eliminar un archivo o directorio. Una vez hecho esto, Opentoonz debe funcionar como se esperaba.

**Comment by EmptyVoid-Radio** [comment]
I deleted each of those files separately (SRV, server.exe or QTGui.dll) and the program does not continue, the most the program does is show that image that you saw in the capture that says: Starting or something like that.

**Comment by RodneyBaker** [comment]
The QTGui.dll is actually missing if I recall correctly so you wouldn't want to remove that.
The SRV error is well known however and since that file/directory is only there to support the .MOV video format... which is now supported (in part) by FFMPEG... the dircectory can safely be removed/renamed without concern.  It has been pointed out that certain features of MOV aren't supported through the FFMPEG process but the format itself will still work.

Short of suggesting you join one of the Opentoonz discords where we can do a one on one session and walk through the issues I'm not sure what to suggest. If missing some DLL files you might consider the following advice from @konero:

```You could also try checking for system integrity, open a CMD window as administrator and type: sfc /scannow

If it says it found and fixed a problem, restart your machine, then run it again. Keep doing it until it says it could find no violations.

And lastly, you can install a small utility called Autoruns: https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

Run it as administrator, select driver tab, find anything for your Logitech camera, right click and delete it.```

**Comment by EmptyVoid-Radio** [comment]
And... can't I download an older version that doesn't have that problem?

**Comment by EmptyVoid-Radio** [comment]
We will have to make an individual section on discord, I have like 2 hours available today for it, I will use the translator for the section as I have been doing to ask lol.

**Comment by RodneyBaker** [comment]
Most who would answer here hang out there as well.

**Comment by EmptyVoid-Radio** [comment]
Do you know if OpenToonz has these functions: "Rigging", "Frame By Frame"? That is, can you make a project with "Rigging" and then polish the project with "Frame By Frame" for transition frames and so on?

**Comment by RodneyBaker** [comment]
Opentoonz has some basic rigging tools (mostly parenting and expressions) although no direct scripting that generally is required for complex rigging.

Frame by Frame... Opentoonz excels at frame by frame animation and that is one of its major strengths.

You likely will need to define your terms a little more as `"Frame by Frame" for transition frames and so on` isn't quite specific enough to address.  If I interpret that to mean 'animation of control points over frames' for vector lines then no, Opentoonz currently does not support automatic interpolation of control points over frames.  Opentoonz instead uses a number of manual methods to autoinbetweening as well as abstactions such as Plastic Tool which allows those control points to be manipulated secondarily.
