### ISSUE TITLE
Opentoonz weird crash

### ISSUE THREAD

**Issue by whypaper** [opentoonz/opentoonz#5643]
### Description

Every time I write a bug report and go back to opentoonz, it just somehow works again.

### Steps to Reproduce

1.
2. 

### OpenToonz Version

1.7

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by RodneyBaker** [comment]
That's great news.  You should file more bug reports.  :)

**Comment by RodneyBaker** [comment]
Will close as this report doesn't have any actionable information.
@whypaper If you run into any persistent problems please let us know.
