### ISSUE TITLE
Displaying previous versions of my frames

### ISSUE THREAD

**Issue by JamesPuso** [opentoonz/opentoonz#568]
Hi there, I'm making a "traditional" animation in OpenToonz and I erased background noise on every frame in an external editor. In the "Cleanup" section it shows the updated frames but in the xsheet it renders the previous versions of the frames and does so even when I start a new project and import them again.

**Comment by artisteacher** [comment]
After making changes to external files, there is a “reload” command which should get the level to display properly. To access the command you can right-click on a cell in the Xsheet/Timeline and go to “Replace Level” and then “Reload”.
