### ISSUE TITLE
feature: playback loop - ping pong mode

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#569]
Ping pong is A looping playback mode that when gets to the last frame - it plays backwards until getting back to the first frame and so forth. It goes forth and back.

This is available in some other animation software.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
