### ISSUE TITLE
 Hi from Argentina , Saludo desde Argentina

### ISSUE THREAD

**Issue by open-toonz** [opentoonz/opentoonz#57]
before all
           thanks to Dwango and Studio Ghibli and others who are involved in this program will surely open source.

I hope to contribute to the project, with translation or what you can.

greeting Cristian R. Arias

contact me :

E-Mail : opentoonz @ gmail.com

whatsapp: +54 9 11  3262 0075

-------------------------------------------------------------------------------------------------

Antes todos 
          gracias  a  Dwango y Studio Ghibli y otras personas que seguramente estan  involucrada en este programa de codigo abierto.

espero poder contribuir con el proyecto, con traduccion o en lo que se pueda.

saludo Cristian R. Arias 

contacteme :

E-Mail : opentoonz @ gmail.com

whatsapp: +54 9 11  3262 0075

**Comment by odysseywestra** [comment]
@open-toonz I'm glad you want to help with translation, but this isn't the place to share contact information or start general conversations. You are better off going to their Google Groups forum and post there. The Github Issue tracker is for reporting bugs and developmental use.

Here a link to the openToonz Google Groups Forum:
https://groups.google.com/forum/#!forum/opentoonz_en
