### ISSUE TITLE
feature: X-Sheet command to make frames unique copies

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#570]
Lets say you need to itterate on a sequence of drawings in the xsheet. Here is a scenario:
![clonecommand](https://cloud.githubusercontent.com/assets/6495061/16543385/d454d7a8-40c9-11e6-8e06-7e07a583dc5a.PNG)

As you see drawings 40 to 44 are repeated twice. Lets say that I need to make changes to the second sequence (yellow), while keeping the first sequence (red) in tact.

 The only way to do that currently is to go to each drawing in the level strip and copy and paste it to the end, then replace them one by one in the yellow sequence.

We need a command for the x-sheet that automates this process like this:
1. Select cells that have drawings in them in the xsheet
2. Right click > make unique

Opentoonz automatically creates copies of the selected frames in the cells and pushes them to the bottom of the queue in the level strip (50-55) . Then it automatically assigns them to the selected cells so:
40-->50
41-->51
42-->52
43-->53
44-->54

Toonboom already has this command and it is very very very useful. Huge time saver.

**Comment by digimikeh** [comment]
Like in flash... 

agreed with this...  it saves a lot of time..

**Comment by blurymind** [comment]
Flash, toonboom, tvpaint - they all have this feature

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
