### ISSUE TITLE
feature: X-Sheet - Sticky keyframes

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#571]
At the moment when you extend the time stretch of a cell - all the keyframes on the cells after it don't move - while their cells get pushed down.

As a result the keyframes on cells get out of sync every time those cells are pushed.
![stickykeyframes](https://cloud.githubusercontent.com/assets/6495061/16545313/408bfec4-411f-11e6-9ae7-2c796ec4e03b.gif)

It would be good to have the option to keep the keyframes sticky - so they move with their cells.
Right now this problem creates a lot of annoying work - having to manually select and move all the keyframes every time you want to extend a drawing.

**Comment by NuxGamedev** [comment]
Seconded.

**Comment by pculli** [comment]
This is totally necessary for working smartly with keys.

**Comment by blurymind** [comment]
perhaps @shun-iwasawa or @turtletooth  could look into it? :)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by 2dvision** [comment]
Toon boom have a solution "[Dragging and Pasting Modes](http://docs.toonboom.com/help/animate-pro/Content/HAR/Stage/003_Interface/018_H3_Timeline_View.html#Dragging)"

![anp_showcurrenthideallothers](https://user-images.githubusercontent.com/16509592/27302232-754c1130-554b-11e7-9ce6-f97deddd810b.png)

Yes, It is really necessary.

**Comment by jpturcotte** [comment]
@2dvision Please post and discuss feature requests in the Google Group, as @turtletooth indicated. The GitHub tracker is now exclusively for reporting bugs. Thank you!
