### ISSUE TITLE
Crash on undo

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#574]
1.  Open OpenToonz
2.  Draw something
3. Undo
4. Crash

**Comment by animking** [comment]
yes it is.

**Comment by ideasman42** [comment]
Please always note what operating system you're using.
(Confirmed on Linux)

**Comment by animking** [comment]
same on windows 8.1

**Comment by blurymind** [comment]
this must be a regression in the newest buld - because it doesnt happen on the 23th of june build - which i am running.

**Comment by ideasman42** [comment]
Should just be a matter of bisecting then.

Heres output from asan:
[crash_undo.txt](https://github.com/opentoonz/opentoonz/files/347009/crash_undo.txt)

**Comment by shun-iwasawa** [comment]
Confirmed on Win7. I'll investigate this.

**Comment by turtletooth** [comment]
Fixed with #579
