### ISSUE TITLE
Bug: OpenToonz doesn't recognize .jpeg file extension (1.0.3)

### ISSUE THREAD

**Issue by cyaoeu** [opentoonz/opentoonz#576]
Tiny issue but OpenToonz doesn't recognize the .jpeg file extension in Load Level. It's basically .jpg with a non-standard (?) file extension so it should work. Renaming the file in explorer or whatever makes OpenToonz recognize the file again.

**Comment by animking** [comment]
it's alright here win 8.1. Just rename(may be your file include complected name with lots of "_") it and load.

**Comment by cyaoeu** [comment]
The point is that you shouldn't have to rename the file for it to work. Here's a screenshot:

![opentoonzbug](https://cloud.githubusercontent.com/assets/3804162/16582599/1db6317a-42b0-11e6-8cce-31a51e609ef0.jpg)

Both files should show but only the .jpg one is showing.

**Comment by turtletooth** [comment]
#656
