### ISSUE TITLE
Feature request: Value editing by mouse input in the Function Editor (and elsewhere?)

### ISSUE THREAD

**Issue by cyaoeu** [opentoonz/opentoonz#577]
It would be nice if you could edit values directly with the mouse instead of inputting values numerically when you don't want to move/scale the object in the actual viewport.

In Houdini (a 3d software) there's a thing called the value ladder where you can middle mouse click a value and a menu with different values appear. You can then move the mouse to the right to increase the value or to the left to decrease the value. A video example here: https://youtu.be/5HtNcD2mrJY?t=1m43s

Maybe the whole ladder is overkill but I would like a way to increase/decrease values like this. Even if middle mouse is used for panning in OpenToonz this could be used with shift/ctrl/alt+middle mouse since these aren't used in the Function Editor.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by turtletooth** [comment]
This is added #1362
