### ISSUE TITLE
Please bring back .swf file output 

### ISSUE THREAD

**Issue by psychoanima** [opentoonz/opentoonz#582]
I am a game developer and I am using swf for my character animations all the time because it's a memory saver (compared to spritesheets). Toonz had this option, but in OpenToonz it's missing. 

swf format is not abandoned and it's still widely used for web and game development.

**Comment by blurymind** [comment]
What game engine uses swf?

**Comment by psychoanima** [comment]
GameMaker: Studio is the one that I am using and has swf support.

**Comment by blurymind** [comment]
game maker imports swf files?
That is impressive.

**Comment by psychoanima** [comment]
Yes, since 2014 and it's working flawlessly on all platforms (especially mobile devices): http://www.yoyogames.com/blog/25

**Comment by blurymind** [comment]
@shun-iwasawa might be able to bring it back. I am not sure in which version they dropped it.

**Comment by blurymind** [comment]
Nowadays it's more popular to save memory by using cut out animation data - exported as json - kind of like what spine2d, spriter, dragonbones and other applications do.

Spine2d has a run time for game maker.

I suggested support for exporting keyframes as jason earlier:
https://github.com/opentoonz/opentoonz/issues/173

By using the open source dragonbones data structure model - to avoid any possible licensing issues.
That would make opentoonz great for the pipeline in game development with any game engine that supports the dragonbones runtime.

:) 
Hey, its much cheaper than swf and you can get away with some pretty big sprites.

**Comment by psychoanima** [comment]
yes, json is now widely popular but Spine is unlikely expensive and limited to games only. Other json exporters like Spriter are lacking in some features like mesh deform/warping, and not all game engines are trying to make API for these packages (dragonbones for example).

Swf in my opinion is still good, cuz it's cheap (in opentoonz would be free, in Anime Studio Pro works great but costs money) it gives size/memory freedom, and it's not limited to games only.

**Comment by turtletooth** [comment]
There are a couple of options here. It looks like at least some of the code
is still in there.

If ffmpeg can get brought in, it can do set along with h264, gif, webm
etc...

I'm pretty close, but need some help. I'm struggling with the last parts
but I think ffmpeg support would answer a lot of problems.

**Comment by blurymind** [comment]
@psychoanima Yes I am aware that Spine's license is very expensive and that spriter lacks mesh deformation.

Thus why I believe that there is a need for an open source tool with an open license and an open json data structure file to be created.
Dragon bones recently added FFD and mesh deformation to their editor and their runtime. The json file specification and runtime for dragon bones is open and it allows for other software to export to it.
Thus why I suggested it in #173 
We can use the dragonbones runtimes - as their license does not require you to buy anything or to be bind to one software - unlike what spine does.
Opentoonz has mesh deformation via mesh levels. It supports all of the features of spine and dragon bones. The only missing thing is the ability to write the data to a properly structured json file and export an image atlas.

**Comment by psychoanima** [comment]
@blurymind I support your json idea but I am afraid that there is no one who can do that task since they are all focused on bug fixing and retrieving lost/hidden Toonz features. It will be nice to have two groups here, one for fixing bugs and second for upgrading the OT with new features.

**Comment by yamisama** [comment]
There used to be flash export, but it was handled through a commercial third party library as far as I can tell. I think the corresponding sources are still somewhere in GIT history.

I can't imagine that ffmpeg's flash output would be vector, I assume that it's just capable of outputting raster video in a flash container. It might also be able to read and render SWF as raster images as long as there is no complex scripting going on, but actual vector i/o through ffmpeg seems extremely unlikely to me.

As far as exporting things like JSON files to game engines, I think pipeline-type tasks like this would be the perfect use case for scripting, rather than building an exporter right into the application. That way it's easy to fix small bugs and also to write and maintain the exporters without extensive knowledge of C++ and the complex internals of the main software. Blender also handles most exporters it that way. 

While the current scripting API in (Open)Toonz unfortunately seems to be based on QT script/JavaScript and not Python like in most serious post production software (Maya, Fusion, Nuke, Hiero, Blender, Toxik, Mari etc.), it still looks quite usable to me. Question is if it is currently capable of opening and writing to text files.

**Comment by blurymind** [comment]
we would also need to export an atlas image - which i explained at   #173

**Comment by blurymind** [comment]
@yamisama do you know any open source swf libraries that can be used instead?

**Comment by psychoanima** [comment]
I found this in Toonz 7 user manual:

> Rendering in Flash SWF Format
> When the SWF format is selected as output format, the Options button
> opens a dialog containing the following options:
> • Curve Quality sets the quality of the vectors drawn in Toonz; the higher
> the quality, the larger the size of the file produced. Low sets a constant
> thickness for all the lines, even those drawn with a very strong thickness
> variation; the constant thickness is assigned to each vector according to
> the medium thickness of the vector itself. Medium sets a constant
> thickness for most of the lines, but those with a very strong thickness
> variation are preserved. High preserves the original thickness variation
> for all the vectors.
> • File Compression generates files with a smaller size; the files
> produced with this option are compatible only with a Flash player from
> version 6.0 on.
> • Looping sets if the animation has to be played back continuously once
> viewed.
> • Autoplay sets if the animation has to start automatically once viewed.
> • Insert Preloader defines a loading image to be displayed while the
> animation is being loaded, for example from a Web page. The first frame
> of the scene will be used as preloader; when the animation is loaded, the
> first frame will not be visible anymore, even if the animation is looping.
> • URL sets a URL address and transforms the animation into a button
> linked to that address, for example to an Internet Web site.
> • JPEG Quality controls the quality and file compression of raster
> images contained in your scene; the higher the quality, the larger the
> size of your exported animation.
> Note: Some limitations apply to the scene rendered in SWF format:
> all the special FX, some


So, with this exporter vector is staying as a vector, and rasters are compressed into jpeg's.

**Comment by psychoanima** [comment]
Hold your horses, there is still hope :)

**Comment by walkerka** [comment]
Here's a LGPL one (libming). Pencil2d(GPL) is using it.
http://www.libming.org/

**Comment by animking** [comment]
Is there any hope to get it back?

**Comment by kogaki** [comment]
FFMpeg might has ability to export  as swf

**Comment by animking** [comment]
no :(

**Comment by kogaki** [comment]
`ffmpeg -i test.mp4 test.swf` works on my PC.

**Comment by animking** [comment]
how to use ffmpeg? I just downloaded and put it on c drive and link the path where ffmpeg.exe located in opentoonz. 
mp4 working but there is no swf in dropdoen menu :(

**Comment by kogaki** [comment]
Sorry, to use from OpenToonz, we need more implementations. Now we are discussing which library can export swf. If `ffmpeg` has ability to export swf, it's easier to implment the function than other libraries.

**Comment by blurymind** [comment]
I think using ffmpeg just puts the compressed video file in the swf, so
none of the file's vector advantages get lost. The resolution independence
and the small file size will not be present in that swf

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
The Flare fork of Opentoonz has implemented .flv and f4v output.
Perhaps Flare might be the best place to request support for .swf formatte output.

Link:  https://github.com/Flare-Animate/Flare/releases
