### ISSUE TITLE
On Brush Tool Crash

### ISSUE THREAD

**Issue by paulorobertocruz** [opentoonz/opentoonz#59]
In the "Cleanup" window, when the brush tool is selected opentoonz crash on alt+left click
Windows 8 
Intel i5
Sorry for my bad english.

**Comment by harrisonkuo** [comment]
I can confirm that this problem exists. I could reproduce it on a Windows 10 64-bit with an nVidia card. By going to any environment (Cleanup, PltEdit, InknPaint) and pressing alt (without even clicking or scrolling), OpenToonz crashes. This only occurs when using the Brush tool.

**Comment by ZackCasey** [comment]
I've had a similar crash with the alt+ functions. Alt+scroll causes 1.0.1 to crash.

**Comment by kogaki** [comment]
It sould be fixed in `nightly build`. Thanks.

**Comment by adamearle** [comment]
i know this must  be really obvious. but where do I find the nightly build page or how do i navigate to there.

**Comment by kogaki** [comment]
@adamearle You can find every versions here, https://github.com/opentoonz/opentoonz/releases :)
