### ISSUE TITLE
Lag on canvas. Linux.

### ISSUE THREAD

**Issue by ebarranco** [opentoonz/opentoonz#590]
I am experimenting lag on canvas with the majority of tools, especially in full screen mode, I'm running the arch Linux repository opentoonz git version with Manjaro Linux 16.06.1. Here a video showing you the behavior.

https://dl.dropboxusercontent.com/u/69554201/OpentoonzLinuxLagBug.mp4

**Comment by ideasman42** [comment]
Can't redo, seems likely OpenGL related (driver performing poorly seems a likely cause).

What graphics card + driver are you using?

**Comment by ebarranco** [comment]
AMD Radeon HD 5700 Series, Proprietary drivers 15.201.1151-150908a-188977E.  The interesting is, that I did believe someone fixed it because after update my source code and rebuild yesterday, the problem is gone.
