### ISSUE TITLE
Inverted colors in raster level. Linux.

### ISSUE THREAD

**Issue by ebarranco** [opentoonz/opentoonz#592]
Adding a raster level, and use the brush, some colors are inverted: 

https://dl.dropboxusercontent.com/u/69554201/OpentoonzLinuxWrongColorsBug.mp4

**Comment by blurymind** [comment]
@ideasman42 might know whats causing it :)

**Comment by ideasman42** [comment]
Fixed 83caeb2eb52d65e96f6f33706eecddeb6e24ed23

**Comment by blurymind** [comment]
@ideasman42 that was fast! Thank you for the fix :)

There are two more linux related bugs - but they might not be as simple as this one
https://github.com/opentoonz/opentoonz/issues?q=is%3Aissue+is%3Aopen+label%3ALinux
