### ISSUE TITLE
bug regression - wasted horizontal space in tool options bar - cap and join menus

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#593]
This is the tool options bar in the latest nightly:
![wastedspace-optionsbar](https://cloud.githubusercontent.com/assets/6495061/16662256/7f71876a-446e-11e6-8704-c29877d25404.JPG)

marked in yellow is all the wasted space.

this is the same options bar in harlequin:
 
![optionsbarharle](https://cloud.githubusercontent.com/assets/6495061/16662313/d38aeb20-446e-11e6-9176-5dbe929c2ca9.JPG)

As you can see the drop down menu is as wide as the icons that it holds - not more.

This issue affects the brush and the geometric tool

**Comment by blurymind** [comment]
@ideasman42 You closed the inverted colors bug. This issue is for the wasted horizontal space on the drop down list

**Comment by shun-iwasawa** [comment]
Please see my comment on #584 :

> Please check if the style sheets in $TOONZCONFIG/qss are updated. Note that they will NOT be overwritten if they already exist (since they might be customized by users).

**Comment by blurymind** [comment]
@shun-iwasawa thank you - updating the qss files fixed this issue! I am closing it now
