### ISSUE TITLE
bug regression - tool options bar - unused horizontal space on some tools

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#594]
In the latest nightly build

![unusedspace-tooloptions](https://cloud.githubusercontent.com/assets/6495061/16662417/7f875c10-446f-11e6-8d3a-05caa6feea6c.JPG)

Marked in yellow is the wasted horizontal space
Marked in red is the slider that could use that extra space 

This affects the - eraser; tape ; pinch ; pump ; magnet; tracker - tools.

The idea is basically the following: If There are sliders on the tool options bar (marked in red in the example) - use whatever space is left to distribute it between them.
Sliders need horizontal screen estate - they need to be as wide as they possibly can be. That makes them easier to use

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
