### ISSUE TITLE
increase and decrease numeric values by click+dragging on them

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#595]
This will greatly help workflow with a stylus. Right now we can only change numeric values by entering a new number. Numeric values in the tool options bar for example.

It would be much easier to increase and decrease them with a stylus by just click (mouse or stylus) dragging on them. It will also alleviate the problem of the sliders not getting enough horizontal space.

This feature exists in other animation software - such as Maya and Blender.
![u0gult](https://cloud.githubusercontent.com/assets/6495061/16662961/0ea68324-4472-11e6-88ae-0b3f0407e7da.gif)

its incredibly useful

**Comment by blurymind** [comment]
It would actually be better if there is no need to middle click. Just click and drag on the title of the input box to increase or decrease it's value - as demonstrated in the gif image.

**Comment by shun-iwasawa** [comment]
Is this issue related to #577 ?

**Comment by blurymind** [comment]
It is similar - but it is different approach to the same problem.

He is requesting a new popup to appear. I am requesting no extra pop up - just click and drag. Single click and drag - not multiple clicks.
Dragging to the left decreases - dragging to the right increases.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by turtletooth** [comment]
I'm working on this.

**Comment by turtletooth** [comment]
The way OpenToonz is built, clicking on the label would be a very challenging.  I have it working now with middle mouse + drag on the value itself.  It could also be done with a keyboard modifier like ctrl.
