### ISSUE TITLE
[Feature] Line Blur for Raster Level

### ISSUE THREAD

**Issue by digimikeh** [opentoonz/opentoonz#596]
Has anyone used Gimp or Photoshop?.. there is a tool that blur lines,, this is very useful if your drawing has a lot of dents...

![0](https://cloud.githubusercontent.com/assets/11097819/16669466/a6520bd0-4463-11e6-90da-b8c27fc7d553.jpg)

**Comment by blurymind** [comment]
You can achieve it via nodes in the gx schematic view.

**Comment by digimikeh** [comment]
does that applies to lines only?

I will give a try, thanks ..

**Comment by blurymind** [comment]
learn the compositing system . Its very flexible! :)

**Comment by blurymind** [comment]
Another way you can get blurred lines is via the toonz raster layer - where the brush tool has a 'hardness' value. Just reduce the hardness. 

I think you can close this bug. OT already has the feature you request.

**Comment by digimikeh** [comment]
Thanks so much!
