### ISSUE TITLE
Changing Default Location of openToonz stuff During Instalation Causes Error

### ISSUE THREAD

**Issue by paulorobertocruz** [opentoonz/opentoonz#60]
when installing opentoonz, if the default location of the folder "opentoonz stuff" is changed opentoonz will crash every time.

I first installed opentooz on "/application/opentoonz-1.0" and the "stuff" folder in "/application/opentoonz-1.0/opentoonz stuff" and that generated error.
After i reinstalled opentoonz with all default locations it worked. 
Sorry for my bad english.

**Comment by odysseywestra** [comment]
Is this still persistent with the current version of openToonz?

https://github.com/opentoonz/opentoonz/releases/tag/v1.0.1

**Comment by turtletooth** [comment]
Closing. No new info on this for a while.
