### ISSUE TITLE
[feature] style editor - refresh resources

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#605]
it would be nice to have a command to refresh the resource folder - so when we import a new texture to it - we dont have to restart opentoonz in order for it to become available.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
