### ISSUE TITLE
Crash: Assert fails in keepChannels() in toonzlib/imagepainter.cpp

### ISSUE THREAD

**Issue by yamisama** [opentoonz/opentoonz#606]
OpenToonz asserts when pressing one of the channel control buttons in the Flipbook window with a raster level loaded via the "View Level" command from the XSheet. 

OpenToonz Version: 1.0.3, July 9th nightly build
Platform: Mac OS X 10.9.5
Hardware: late 2008 silver MacBook 13" (RAM extended to 8 GB)
Graphics: NVIDIA GeForce 9400M 256 MB
Can be reproduced multiple times: yes

All OpenToonz windows were placed on an external Eizo monitor connected via DisplayPort (main screen). The Flipbook window was floating. I don't believe they are related, but there were render issues (the Flipbook is blank and completely white when a raster level is loaded, but works fine for vector levels. The regular main viewer displays either level type just fine, but is completely black when the application is first launched and needs to be undocked and re-docked every time in order to display correctly. Both level strip and XSheet column thumbnail render correctly).

This is the assertion info and the relevant call stack from the crash report:

**Assertion failed: (channel & Trop::MChan), function keepChannels, file /Users/keisuke_ogaki/.jenkins/jobs/opentoonz/workspace/toonz/sources/toonzlib/imagepainter.cpp, line 40.**

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff8757d866 **pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff86d2435c pthread_kill + 92
2   libsystem_c.dylib               0x00007fff8c64bb2e abort + 125
3   libsystem_c.dylib               0x00007fff8c6159d3 __assert_rtn + 321
4   libtoonzlib.dylib               0x000000010395cebd (anonymous namespace)::keepChannels(TSmartPointerT<TRaster> const&, TPalette_, unsigned char) + 541
5   libtoonzlib.dylib               0x000000010395c1d5 (anonymous namespace)::Painter::doFlushRasterImages(TSmartPointerT<TRaster> const&, int, TPointT<double> const&) + 4773
6   libtoonzlib.dylib               0x000000010395abb0 (anonymous namespace)::Painter::flushRasterImages(TRectT<int> const&, double, double, bool) + 4416
7   libtoonzlib.dylib               0x0000000103958d92 ImagePainter::paintImage(TSmartPointerT<TImage> const&, TDimensionT<int> const&, TDimensionT<int> const&, TAffine const&, ImagePainter::VisualSettings const&, ImagePainter::CompareSettings const&, TRectT<int> const&) + 1346
8                                   0x000000010248b55c ImageViewer::paintGL() + 2060
9   org.qt-project.QtWidgets        0x000000010551bf4a 0x105486000 + 614218
10  org.qt-project.QtWidgets        0x00000001054f61bb QWidget::event(QEvent_) + 2123
11  org.qt-project.QtWidgets        0x00000001054b74bb QApplicationPrivate::notify_helper(QObject_, QEvent_) + 251
12  org.qt-project.QtWidgets        0x00000001054ba89e QApplication::notify(QObject_, QEvent_) + 8318
13  org.qt-project.QtCore           0x000000010637b983 QCoreApplication::notifyInternal(QObject_, QEvent_) + 115
14  org.qt-project.QtWidgets        0x00000001054ef970 QWidgetPrivate::drawWidget(QPaintDevice_, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 3152
15  org.qt-project.QtWidgets        0x00000001054f02ba QWidgetPrivate::paintSiblingsRecursive(QPaintDevice_, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 1226
16  org.qt-project.QtWidgets        0x00000001054efd26 QWidgetPrivate::drawWidget(QPaintDevice_, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 4102
17  org.qt-project.QtWidgets        0x00000001054f02ba QWidgetPrivate::paintSiblingsRecursive(QPaintDevice_, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 1226
18  org.qt-project.QtWidgets        0x00000001054f0140 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice_, QList<QObject_> const&, int, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 848
19  org.qt-project.QtWidgets        0x00000001054efd26 QWidgetPrivate::drawWidget(QPaintDevice_, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 4102
20  org.qt-project.QtWidgets        0x00000001054f02ba QWidgetPrivate::paintSiblingsRecursive(QPaintDevice_, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 1226
21  org.qt-project.QtWidgets        0x00000001054efd26 QWidgetPrivate::drawWidget(QPaintDevice_, QRegion const&, QPoint const&, int, QPainter_, QWidgetBackingStore_) + 4102
22  org.qt-project.QtWidgets        0x00000001054c3d06 0x105486000 + 253190
23  org.qt-project.QtWidgets        0x00000001054c4043 0x105486000 + 254019
24  org.qt-project.QtWidgets        0x00000001054e665c QWidgetPrivate::syncBackingStore() + 236
25  org.qt-project.QtWidgets        0x00000001054f6484 QWidget::event(QEvent_) + 2836
26  libtoonzqt.dylib                0x00000001044636be DockWidget::event(QEvent_) + 206
27  org.qt-project.QtWidgets        0x00000001054b74bb QApplicationPrivate::notify_helper(QObject_, QEvent_) + 251
28  org.qt-project.QtWidgets        0x00000001054ba89e QApplication::notify(QObject_, QEvent_) + 8318
29  org.qt-project.QtCore           0x000000010637b983 QCoreApplication::notifyInternal(QObject_, QEvent_) + 115
30  org.qt-project.QtWidgets        0x00000001054c07b4 0x105486000 + 239540
31  org.qt-project.QtWidgets        0x00000001054c12c4 0x105486000 + 242372
32  org.qt-project.QtWidgets        0x00000001054f97e9 QWidget::repaint(QRect const&) + 185
33  org.qt-project.QtWidgets        0x00000001054f9724 QWidget::repaint() + 52
34                                  0x000000010248a8b5 ImageViewer::setImage(TSmartPointerT<TImage>) + 213
35                                  0x00000001024c813e FlipBook::onDrawFrame(int, ImagePainter::VisualSettings const&) + 190
36                                  0x00000001024c82b5 non-virtual thunk to FlipBook::onDrawFrame(int, ImagePainter::VisualSettings const&) + 53
37  libtoonzqt.dylib                0x0000000104494f65 FlipConsole::doButtonPressed(unsigned int) + 4917
38  libtoonzqt.dylib                0x0000000104497688 FlipConsole::onButtonPressed(int) + 40
39  libtoonzqt.dylib                0x000000010479b8e9 FlipConsole::onButtonPressed(QAction_) + 73
40  libtoonzqt.dylib                0x000000010479b1b9 FlipConsole::qt_static_metacall(QObject_, QMetaObject::Call, int, void__) + 297
41  org.qt-project.QtCore           0x00000001063ac2e2 QMetaObject::activate(QObject_, int, int, void**) + 2994
42  org.qt-project.QtWidgets        0x00000001054b083c 0x105486000 + 174140
43  org.qt-project.QtCore           0x00000001063ac2e2 QMetaObject::activate(QObject*, int, int, void**) + 2994
44  org.qt-project.QtWidgets        0x00000001054ae5af QAction::activate(QAction::ActionEvent) + 271
45  libtoonzqt.dylib                0x000000010449a5aa QAction::trigger() + 26
46  libtoonzqt.dylib                0x000000010449c7b5 DoubleButton::mousePressEvent(QMouseEvent_) + 149
47  org.qt-project.QtWidgets        0x00000001054f5fb7 QWidget::event(QEvent_) + 1607
48  org.qt-project.QtWidgets        0x00000001055a1fa3 QAbstractButton::event(QEvent_) + 179
49  org.qt-project.QtWidgets        0x000000010566b744 QToolButton::event(QEvent_) + 324
50  org.qt-project.QtWidgets        0x00000001054b74bb QApplicationPrivate::notify_helper(QObject_, QEvent_) + 251
51  org.qt-project.QtWidgets        0x00000001054baced QApplication::notify(QObject_, QEvent_) + 9421
52  org.qt-project.QtCore           0x000000010637b983 QCoreApplication::notifyInternal(QObject_, QEvent_) + 115
53  org.qt-project.QtWidgets        0x00000001054b7e4b QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget*_, QPointer<QWidget>&, bool) + 987
54  org.qt-project.QtWidgets        0x0000000105516600 0x105486000 + 591360
55  org.qt-project.QtWidgets        0x000000010551580f 0x105486000 + 587791
56  org.qt-project.QtWidgets        0x00000001054b74bb QApplicationPrivate::notify_helper(QObject_, QEvent_) + 251
57  org.qt-project.QtWidgets        0x00000001054ba89e QApplication::notify(QObject_, QEvent_) + 8318
58  org.qt-project.QtCore           0x000000010637b983 QCoreApplication::notifyInternal(QObject_, QEvent_) + 115
59  org.qt-project.QtGui            0x0000000105af6f79 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent_) + 2185
60  org.qt-project.QtGui            0x0000000105af5e03 QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 131
61  org.qt-project.QtGui            0x0000000105ae29da QWindowSystemInterface::sendWindowSystemEvents(QFlagsQEventLoop::ProcessEventsFlag) + 346
62  libqcocoa.dylib                 0x00000001084961a1 0x108473000 + 143777
63  com.apple.CoreFoundation        0x00007fff8a1165b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
64  com.apple.CoreFoundation        0x00007fff8a107c62 __CFRunLoopDoSources0 + 242
65  com.apple.CoreFoundation        0x00007fff8a1073ef __CFRunLoopRun + 831
66  com.apple.CoreFoundation        0x00007fff8a106e75 CFRunLoopRunSpecific + 309
67  com.apple.HIToolbox             0x00007fff895e1a0d RunCurrentEventLoopInMode + 226
68  com.apple.HIToolbox             0x00007fff895e1685 ReceiveNextEventCommon + 173
69  com.apple.HIToolbox             0x00007fff895e15bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
70  com.apple.AppKit                0x00007fff84e8424e _DPSNextEvent + 1434
71  com.apple.AppKit                0x00007fff84e8389b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
72  com.apple.AppKit                0x00007fff84e7799c -[NSApplication run] + 553
73  libqcocoa.dylib                 0x000000010849508d 0x108473000 + 139405
74  org.qt-project.QtCore           0x000000010637907d QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) + 381
75  org.qt-project.QtCore           0x000000010637bf5a QCoreApplication::exec() + 346
76                                  0x0000000101fee175 main + 11573
77  libdyld.dylib                   0x00007fff879395fd start + 1

**Comment by RodneyBaker** [comment]
I'm fairly sure this problem has been resolved.
I do note a few familiar patterns in this report; Nvidia cards and multiple monitors for instance.

Can these issues be reproduced with current nightly builds?

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@yamisama Please let us know if you are still experiencing the issue.
