### ISSUE TITLE
[feature] x-sheet /selection tool - preserve line selection when moving between frames

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#611]
It would make it much easier to edit a line across multiple cells if the line's selection was kept when you move to another frame where the line exists.

Lets say that you want to change the style or the thickness or the shape of a line across multiple drawings.
Currently you have to reselect the line every time you move to the next frame.

Here is a mockup to illustrate:
![selectionacrossframes](https://cloud.githubusercontent.com/assets/6495061/16707734/054b3fee-45d1-11e6-83ab-addbee1fe2d9.gif)

This could of course be an optional behavior.

**Comment by turtletooth** [comment]
That would be nice.  On a totally side note, what did you use to make the gif.  I dig it.

**Comment by blurymind** [comment]
just some basic editing in camtasia :)

**Comment by blurymind** [comment]
This behavior will be most advantageous in cases where you have selected a number of lines that you want to alter between frames - by transforming them , changing their style or their thickness.
It can save hours of work imo. I found myself doing that a lot and re-selecting the lines on every frame change is the thing that took the most of the time.

**Comment by blurymind** [comment]
I wonder if @shun-iwasawa could look into it :)
Is it a technically difficult feature to implement? Preserving vector line selection between frames?

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
