### ISSUE TITLE
[BUG] Shortcut Window: List Doesn't Update After Using Remove

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#617]
**Location**

Open **Configure Shortcuts** window and assign a shortcut to something, then try to remove that shortcut, the list does not update to reflect the change, a restart is required.

![t1](https://cloud.githubusercontent.com/assets/19820721/16713041/f86a15e4-4692-11e6-9afd-745bcf27ede7.PNG)

**Version**

[nightly_534c9edc8878537acdca714f81dc04ca0b1a2533](https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_534c9edc8878537acdca714f81dc04ca0b1a2533)

**Comment by turtletooth** [comment]
Confirmed.  Submitted PR #620

**Comment by shun-iwasawa** [comment]
Merged. @konero and @turtletooth thank you very much for reporting and modifying the bug!
