### ISSUE TITLE
Plastic Tool, Erratic behavior and crash. Linux.

### ISSUE THREAD

**Issue by ebarranco** [opentoonz/opentoonz#623]
Plastic Tool creates bad mesh, a box mesh #406, and crash in animate mode. Here is the video:

https://dl.dropboxusercontent.com/u/69554201/OpentoonzPlasticToolCrash.mp4

**Comment by brunotribst** [comment]
I couldn't see ur video... everytime when I have some animation using the plastic tool, the software crash right after I put it in sub-xsheet (Win)... its not always in the same way but is 99% sure that OT gonna stop working... the worse thing is that if you save your file and the software stop working you can't open the same file again.

**Comment by underdoeg** [comment]
I can confirm this bug

**Comment by ideasman42** [comment]
Thanks for the comprehensive report.

Confirmed: a6cacc8cf1d5c31aeb21235cccad59c68c1b915a,

Heres a stack trace from asan: [plastic_crash.txt](https://github.com/opentoonz/opentoonz/files/461774/plastic_crash.txt)
Although this only shows that a bad address is being accessed in superlu, will need more investigation to fix.

**Comment by RodneyBaker** [comment]
@ebarranco 
@brunotribst 
Can you give us an update on this issue.
There have been a number of fixes in the past three years and parts of this issue have likely been addressed while other parts still need attention.  Your feedback will be appreciated.

**Comment by ebarranco** [comment]
@RodneyBaker  I'm sorry for the delay but I didn't have install Opentoonz, I don't even have the same system since I file this issue. This particular behavior don't exist anymore, that doesn't mean that The Plastic Tool works now, just present different problems so I'm closing this issue.

**Comment by RodneyBaker** [comment]
Thanks for the feedback @ebarranco.
If you run across any other issues please let us know.
