### ISSUE TITLE
[Feature]  Camera preview

### ISSUE THREAD

**Issue by digimikeh** [opentoonz/opentoonz#630]
Hi everyone
What about a mini view that shows you how the camera is focusing the scene?.. 

Currently you can drag and give Z depth to your levels (including camera) but you are not in first person view (in camera) 

Image attached.

![multicamera22](https://cloud.githubusercontent.com/assets/11097819/16781750/a55da26c-484a-11e6-9602-eb17328fda55.jpg)

**Comment by digimikeh** [comment]
Here is a more direct example


![multicamera22](https://cloud.githubusercontent.com/assets/11097819/16781730/9198bb68-484a-11e6-8a48-b563e48de7b4.jpg)

**Comment by shun-iwasawa** [comment]
Hi @digimikeh , thank you for your post.
Have you tried "Camera View" mode of the Viewer which can be activated by clicking a small camera icon in the title bar of Viewer/Combo Viewer? In "Camera View" mode you can see the scene in first person view from the current camera. Hope this helps.
<img src="https://cloud.githubusercontent.com/assets/17974955/16790274/7ae7d354-48ef-11e6-898e-ce1605c0165f.png" width=650>

**Comment by digimikeh** [comment]
fool you are.. (you telling this to me )  
 ... how did not see that button before?

Thanks my friend.
