### ISSUE TITLE
[bug] plastic tool animation converted to or loaded as sub-Xsheet crashes OpenTOonz

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#641]
Create a plastic tool animation (two levels: the content level and the mesh), and save all the data (level, mesh level, and scene).

Open a new scene, and loading the plastic animation scene as a sub-Xsheet immediately causes OT to crash.
Open the original plastic animation scene, and select the columns. Collapse to a sub-Xsheet: OT instantly crashes.

This used to work properly in a previous version. It is now no longer possible to use plastic tool animations as sub-Xsheets in any way. 

Related to  #623

**Comment by brunotribst** [comment]
I have here the same problem (Win)

**Comment by Rayek** [comment]
No response yet? It makes it impossible for me (and possibly many others) to use OpenTOonz in its current state.

**Comment by blurymind** [comment]
@tomosu or @shun-iwasawa  might know whats wrong. They tackled previous related bugs
https://github.com/opentoonz/opentoonz/pull/398
https://github.com/opentoonz/opentoonz/issues/198

**Comment by manongjohn** [comment]
I reported #459 when 1.0.3 was released. It has to do with the column icons for sub xsheets with meshes. Was able to reproduce consistantly. Turning off the auto loading of the column icons is a small work around until this is fixed.

**Comment by shun-iwasawa** [comment]
@Rayek  Please check if the modification by @skitaoka fixes this problem. Thanks.

**Comment by Rayek** [comment]
Tested this, and it works as expected now. It seems fixed! :-)

Many thanks!

**Comment by manongjohn** [comment]
FYI, I pulled the latest nightly and verified #459 was also corrected with thia fix.
