### ISSUE TITLE
[Bug] Adjusting Brush Size (via "Alt") Creates a "Dot" on the Canvas

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#648]
The current method for adjusting Brush Size (in the Canvas) requires the user to hold down the "Alt" key, left click once on the Canvas, release the left mouse button - and drag the mouse left or right to obtain the desired size.

This first click in the Canvas should NOT produce any kind of graphic element on the Canvas - requiring a "Ctrl-Z" operation to remove it.

Greg Smith

**Comment by Rayek** [comment]
I am able to adjust the Brush size while holding down <alt> without the need to use the left mouse button. (Windows and Wacom tablet).

**Comment by turtletooth** [comment]
As long as there is layer selected, there is no need to click.  Holding down Alt and moving the mouse changes the brush size.  Just tested - Windows 10, Nightly.

**Comment by turtletooth** [comment]
No response in half a year.  Closing.
