### ISSUE TITLE
[Bug] Windows (1.0.3) Crashes After Building Skeleton and Saving (Scene) or Saving (All)

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#649]
My Scene file contains a Vector Level with multiple filled shapes.  I successfully created a single Mesh Level containing individual meshes for each shape.

I designated "Rigid" areas for each individual mesh.

I am able to "Save Scene" after performing the above tasks.

Setting the Root Bone node within the "Head" shape - I placed secondary nodes in each other Mesh shape. (originating with the "Root" node), with the purpose of "dragging" these shapes into the main "Head" mesh.

Upon clicking "Save All" or "Save Scene", OpenToonz crashes - losing all skeleton additions.

Greg Smith

**Comment by turtletooth** [comment]
Is this still an issue?  I just tried this and couldn't get a crash.

**Comment by turtletooth** [comment]
Closing as abandoned.
