### ISSUE TITLE
Add UI scaling

### ISSUE THREAD

**Issue by SafariMonkey** [opentoonz/opentoonz#65]
There seems to be no UI scaling option at present. On my Surface 3, the current scale means that buttons are about 2x2mm, which is far too small to easily tap with a pen. Compare to Clip Studio in large UI mode, where they're 9x9.

Good UI scaling would likely require redesigning (or "remastering") most icons and replacing all hardcoded pixel values, as well as some other things I'm not aware of. However, in this age of ever increasing resolutions, I think it will be necessary in order to remain competitive.

Current appearance on the 10" Surface 3:
![image](https://cloud.githubusercontent.com/assets/2837174/14063355/95d58dde-f3c5-11e5-8e41-d0e8e80a75cc.png)

**Comment by msorvig** [comment]
There is actually support for automatic scaling in Qt. With version 5.5 you can enable it with an environment variable:

`set QT_SCALE_FACTOR=auto`

Qt 5.6 onwards supports enabling scaling from application source code:

`QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);`

**Comment by tofarley** [comment]
Unfortunately, setting this environment variable (at least on Windows, which is my only high DPI device available to test) does not work properly. It does make the UI and icons proper size, but the cursor becomes "offset" from the mouse pointer on the canvas.

When the mouse is positioned in the center of the canvas it works well, but as you move toward the edge of the canvas the mouse pointer and software cursor drift further and further apart.

**Comment by carolbeck** [comment]
Just to say that I have this issue of pointer/cursor drift too after making the environment variable change (Spectre x360 high DPI laptop).

**Comment by turtletooth** [comment]
Fixed in #1132
