### ISSUE TITLE
Feature:  Allow Plastic Bone Node Depth Sorting .  .  .  by Using "Alt" and Scroll Wheel

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#650]
OpenToonz Plastic Bone Node depth sorting (on the fly) is one of the most brilliant 2D animation features ever included in 2D animation software.  It makes all sorts of "3D" turns for complex characters possible and fast to implement.

What would make this brilliant feature better?

Provide the user with a way to instantly adjust Plastic Bone Node "depth" right on the Canvas.

That's right - by selecting a Plastic Bone Node, while animating, a user could hold down the "Alt" key and move the Scroll Wheel forward or backward (with screen readout) - instantly adjusting the Plastic Mesh Z-Depth for that character part.

Such speed and facility would greatly increase the value of OpenToonz for animators.

Greg Smith

**Comment by blurymind** [comment]
it already has z sorting... :)

**Comment by PsmithG** [comment]
Your mind must truly be blurry.  Read again the above post from me and see if you can recognize the difference between the 1st and the 4th paragraph of my post.

Greg Smith

**Comment by blurymind** [comment]
yeah it kinda is at 2 am xD

Well it would be nice to have a keyboard command to increase and decrease the SO value of selected bone(s)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
