### ISSUE TITLE
Allow The Use of Hooks in Plastic Mesh Modes

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#651]
Currently, one cannot use Hooks with Plastic deformed meshes.

It would be convenient to provide Hooks that will work with Plastic meshes - for character animation and the firm placement of feet (without sliding) upon the ground.

It would also be convenient to allow a character made with Plastic meshes and bones to be able to pick an object up and carry it.

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
