### ISSUE TITLE
Cannot compile with Qt 5

### ISSUE THREAD

**Issue by scribblemaniac** [opentoonz/opentoonz#66]
The makefile uses qt version 5.5 but there are some locations that use features not available in 5. For example, there are [some files](https://github.com/opentoonz/opentoonz/search?utf8=%E2%9C%93&q=qhttp) that use QHttp, but this was [removed in Qt 5](https://doc.qt.io/qt-5/sourcebreaks.html#changes-to-qt-network).

**Comment by scribblemaniac** [comment]
I decided I'd try to figure this out on my own, and now realized that I jumped to the wrong conclusion. I was surprised to find that all the version specific code was handled properly with definitions. Here's the errors just for reference:
```
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:100:77: error: 
      too many arguments to function call, expected 1, have 2
  ..._t->httpRequestFinished((*reinterpret_cast< int(*)>(_a[1])),(*reinterpret_cast< bool(*)>(_a[2]))...
     ~~~~~~~~~~~~~~~~~~~~~~~                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/../../../../../sources/include/toonzqt/updatechecker.h:52:2: note: 
      'httpRequestFinished' declared here
        void httpRequestFinished(QNetworkReply *);
        ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:101:21: error: 
      no member named 'readyReadExec' in 'UpdateChecker'
        case 2: _t->readyReadExec((*reinterpret_cast< const QHttpRespons...
                ~~  ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:101:82: error: 
      expected '>'
  ...2: _t->readyReadExec((*reinterpret_cast< const QHttpResponseHeader(*)>(_...
                                                                         ^
                                                                         >
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:101:53: note: 
      to match this '<'
        case 2: _t->readyReadExec((*reinterpret_cast< const QHttpRespons...
                                                    ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:102:21: error: 
      no member named 'readResponseHeader' in 'UpdateChecker'
        case 3: _t->readResponseHeader((*reinterpret_cast< const QHttpRe...
                ~~  ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:102:87: error: 
      expected '>'
  ...const QHttpResponseHeader(*)>(_a[1]))); break;
                                ^
                                >
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:102:58: note: 
      to match this '<'
        case 3: _t->readResponseHeader((*reinterpret_cast< const QHttpRe...
                                                         ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:111:8: error: 
      use of undeclared identifier 'QHttp'
    { &QHttp::staticMetaObject, qt_meta_stringdata_UpdateChecker.data,
       ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:126:12: error: 
      use of undeclared identifier 'QHttp'
    return QHttp::qt_metacast(_clname);
           ^
~/git/opentoonz/toonz/build/toonzqt/__/include/toonzqt/moc_updatechecker.cpp:131:11: error: 
      use of undeclared identifier 'QHttp'
    _id = QHttp::qt_metacall(_c, _id, _a);
```

I manually deleted the code for qt 4 and now this part compiles (still more errors elsewhere though, why does this stuff always happen to me?). I am honestly clueless as to why this would make a difference and I would love it if anyone would share their ideas on the subject. It probably has to do something with how qt's moc processing things, but I don't know the lower level details of it well enough to say.

Related question: are we planning to maintain support for qt 4?

**Comment by mmuman** [comment]
Could it be that cmake doesn't find all it wants for Qt5 and so falls back to Qt4 at some point? Did you check the cmake result?

**Comment by scribblemaniac** [comment]
Yes cmake correctly links to qt 5, in fact I went as far as to uninstall qt 4 just to be sure. I've actually got this to compile now, but I'm waiting for some of the PRs to get merged before requesting my changes (especially #45, since this relies on that change). My changes break support for qt < 4.4 though, I hope that isn't going to be an issue. If you want to see my changes, you can check them out [here](https://github.com/scribblemaniac/opentoonz/commit/56e65d4b708054a8a925b1951dcc1d44002eb0ee).

**Comment by Goofybud16** [comment]
@scribblemaniac The only officially supported version of Qt 4 is 4.8, and that is currently marked as Legacy. Version 4.4 was released in 2008, and AFAIK OpenToonz doesn't support any OS older than Windows 7 (released in 2009). 4.8 (the only currently supported version of Qt 4) was released in 2011, which is 5 years ago. 4.6 is the first version with proper Windows 7 support.

Even Debian Wheezy (oldstable) has Qt 4.8, so I don't think it will be a problem.

In reality, since the software supports Qt 5, I am not sure why effort is put into maintaining Qt 4 compatibility [if any is]. Qt 4 is going to be unsupported sooner than later, and Qt 5.6 is the Long Term Support version.

**Comment by scribblemaniac** [comment]
@Goofybud16 Thanks for the information!

**Comment by scribblemaniac** [comment]
@Goofybud16 Thanks for the infomation :smile:

**Comment by odysseywestra** [comment]
@scribblemaniac is this problem still persistent for you? If so, I would go ahead and close this issue.

**Comment by scribblemaniac** [comment]
I will close this issue when I changes I have made are merged. Until that time the problem still persists and therefore this issue should not be closed.

**Comment by roentgen** [comment]
moc_* are auto generated files by Qt.
First, you may need to clear your build directory's content. (moc, caches and objects)
Once you built this with Qt 4.8, then old moc files are still remain there.

**Comment by scribblemaniac** [comment]
@roentgen Yes, I was aware of that, and can assure you that I deleted all build files to do full rebuilds multiple times. It is not an issue with caching.

Since nobody else seems to be having this issue, I'll probably just close this. If you do happen to experience this issue, check out the branch I linked, I'll leave it online quite a while.
