### ISSUE TITLE
Support Multitouch Gestures 

### ISSUE THREAD

**Issue by SafariMonkey** [opentoonz/opentoonz#67]
Many devices used by artists nowadays, such as Cintiq and Surface, have models with multitouch capabilities. Being able to use touch gestures such as pan and pinch-to-zoom without changing tool would be very useful. 

As an example, in Clip Studio, there is an option (on by default I believe) to use touch on the canvas for pan/zoom/rotate only, so effectively the fingers are used for navigation and the pen is used for tools. UI elements treat them equally.

**Comment by TheoXD** [comment]
Thumbs up for this one, I was a bit disappointed when they've spoken about paperless drawing in toonz videos but do not have basic multitouch gestures, nor even an undo/redo button easily accessible.

**Comment by odysseywestra** [comment]
Could you provide code examples of how we could accomplish this in QT?

**Comment by relgukxilef** [comment]
There is the [MultiPointTouchArea](http://doc.qt.io/qt-5/qml-qtquick-multipointtoucharea.html) ([example code](http://doc.qt.io/qt-5/qtquick-touchinteraction-example.html)) available in QML. I don't know how useful this is for this project.

**Comment by metellius** [comment]
Incoming mouseevents are in SceneViewer, which is a qwidget. Handling basic gestures with qwidget is not hard, using the gestures framework: http://doc.qt.io/qt-5/gestures-overview.html

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature.  Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by turtletooth** [comment]
Added in #1437
