### ISSUE TITLE
Add UHD 1.78 (16:9) Preset

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#671]
As far as I can see it's not in the resolution presets, either in Output or Cleanup Settings.

`UHD 4K, 3840x2160, 16/9`

I'd place it at the top with the following three directly below it. I doubt anybody uses those old PAL and NTSC formats anymore so they could be bumped down and allow the modern TV standards pride and place.

`HD 1080, 1920x1080, 16/9`

`HD 720, 1280x720, 16/9`

`HD 480, 853x480, 16/9`

`DCI 2K` and `DCI 4K` are also missing from `\projects\cleanupreslist.txt`.

**Comment by turtletooth** [comment]
Agreed.
