### ISSUE TITLE
IRC for OpenToonz Developers and Users

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#678]
It would be great to have a way to discuss with other users and developers about issues and needs in IRC or some other messaging way.

**Comment by Fweeb** [comment]
It's not difficult to set up a (for example) #opentoonz channel on freenode. That's where most FOSS projects have an IRC presence anyhow. Just need to get a couple devs/users to agree to be there.

**Comment by RodneyBaker** [comment]
There was someone in the main forum that posted information about an IRC channel.  I briefly visited there but no one was present.  If I recall correctly I posted to that topic with a suggestion that folks could post a note about when they planned to be on IRC and/or to schedule a weekly session.

I found the topic.

Here's the channel:

http://webchat.freenode.net/?channels=opentoonz

**Comment by Fweeb** [comment]
I'll add it (#opentoonz on freenode) to my rotation of regularly-connected channels as well.

**Comment by turtletooth** [comment]
@RodneyBaker Thanks!

I'll close this.
