### ISSUE TITLE
Shortcuts 

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#679]
I am going to try and make the shortcuts more complete.  
Here is a list of EVERY possible thing that can be made a shortcut along with the current shortcut if there is one.  If I missed something let me know.

[OpenToonz Keyboard Shortcuts.docx](https://github.com/opentoonz/opentoonz/files/380829/OpenToonz.Keyboard.Shortcuts.docx)
[OpenToonz Keyboard Shortcuts.pdf](https://github.com/opentoonz/opentoonz/files/380830/OpenToonz.Keyboard.Shortcuts.pdf)

Please give your feedback about what you think should be made a shortcut and what it should be.  

The request has been made to make a dropdown where users can select from the shortcuts from other programs (Harmony, Flash. . .).  I think that is a good idea, but right now, I think a complete shortcut set is a good place to start.  I think making it familiar (Harmony, Flash, Premiere, Blender) is useful.  I also think making the main items for the left hand is useful for tablet users - (and I'm left handed).

This has been discussed earlier but I wanted to create a new issue so more people will see it since it will affect so many.  I will pull in the comments from the previous issue.

Notes:
- I know there will be many strong opinions on this, I'm going to try and meet the needs as much as possible, but compromise will be needed.
- The mac shortcuts are empty right now, but will get filled in when this document becomes the real shortcut list.
- Ignore the mac icon on the first row- it is there to give me something to copy and paste when needed.
- The order is weird I know- I just copied them from the shortcut window.   The order will be optimized when this is finalized.

**Comment by turtletooth** [comment]
@blurymind posted:
I agree on the brush size. The brushes in OT seem to be resized in a similar fashion to what blender has with the F key (texture mode). I need to think about the shortcuts for a while. This is a really good topic to bring out,as OT currently doesnt have a complete keymap! 

to extend hold - use R,
to decrease Hold - use E

That is what toonboom studio used at least :)

harmony has different keys:
http://docs.toonboom.com/download/harmony/12/HAR12_Keyboard_Shortcuts.pdf

One thing that both harmony and flash have are keyboard layouts. Blender has them too.

The software has its own keyboard layout, but it however offers to new users the option to use layouts of other competitive products:
![toonboomsets](https://cloud.githubusercontent.com/assets/6495061/15949455/9288287a-2e9f-11e6-9adc-a509616f039f.PNG)

I suggested this feature in another post here at the issue tracker. Perhaps I should split it into it's own issue? What do you think :)

**Comment by turtletooth** [comment]
@konero posted
OpenToonz current shortcut list appear to be from the stone age, it is illogical beyond belief and takes in no account for left-handed use, a default shortcut set list should in the most part have its core functions accessible to both. We got to test OpenToonz in a real pipeline and quite literally everybody changed the following shortcuts straight away:

Previous Frame (**Shift+S**) to (**,**)
Next Frame (**Shift+A**) to (**.**)
Prev Drawing (**Shift+Z**) to (Right-Handed: **F** | Left-Handed: **H**)
Next Drawing (**Shift+X**) to (Right-Handed: **G** | Left-Handed: **J**)
First Frame to (**<**)
Last Frame to (**>**)
Save All to (**Shift+S**)

How on earth is a left-handed user supposed to use Shift+Z/X for arguably the most useful two shortcuts?

I agree with @blurymind about a shortcut set list. :+1: 

I would still argue making the Toon Boom Harmony layout the default, it's more logical in most aspects and professional OpenToonz users will likely couple it with Toon Boom Storyboard Pro; but at least if the option is there it reduces the frustration greatly.

> **Shortcut Sets**
> Toon Boom Harmony (right-handed)
> Toon Boom Harmony (left-handed)
> OpenToonz (right-handed)
> OpenToonz (left-handed)
> Custom 1
> Custom 2

**Comment by turtletooth** [comment]
Adobe Shortcuts:
https://helpx.adobe.com/animate/kb/animate-keyboard-shortcuts.html
Harmony Shortcuts:
http://docs.toonboom.com/download/harmony/12/HAR12_Keyboard_Shortcuts.pdf

**Comment by AyameLee** [comment]
> Previous Frame (Shift+S) to (,)
> Next Frame (Shift+A) to (.)
> Prev Drawing (Shift+Z) to (Right-Handed: F | Left-Handed: H)
> Next Drawing (Shift+X) to (Right-Handed: G | Left-Handed: J)
> First Frame to (<)
> Last Frame to (>)

Absolutely, 'tis the standard old bean. :+1:

**Comment by turtletooth** [comment]
@AyameLee There isn't a right handed/left handed option right now.  Would you default to the right handed?

**Comment by AyameLee** [comment]
> There isn't a right handed/left handed option right now. Would you default to the right handed?

I think only 10% of the global population is supposed to be left handed, I think right handed default is fine, no problem.

**Comment by turtletooth** [comment]
@blurymind I've got the shortcut dropdown for choosing between Harmony, Flash etc. . . working.  I just need to enter the actual correct shortcuts for each program.

If anyone has time to help, let me know- no coding, just typing in shortcuts.

**Comment by konero** [comment]
Toon Boom has a comparison chart from 2009 for both Harmony and Flash: http://docs.toonboom.com/download/harmony/7.8/harmony_stage_keyboardshortcuts.pdf

I don't think anything has changed.

Harmony 14: http://docs.toonboom.com/download/harmony/14/PRM/HAR14_Premium_Keyboard_Shortcuts_Guide.pdf

Adobe Animate (incomplete?): https://helpx.adobe.com/animate/kb/animate-keyboard-shortcuts.html

**Comment by blurymind** [comment]
@turtletooth  Thank you for developing the preset menu

Konero has supplied the required list already.
I will add toonboom studio's
http://docs.toonboom.com/download/toon-boom-studio/8/TBS8_Keyboard_Shortcuts.pdf
Since that is what I used to have before toonboom decided to discontinue it

**Comment by turtletooth** [comment]
Merged #691
