### ISSUE TITLE
Feature Request - Fill tool sample from all levels

### ISSUE THREAD

**Issue by Vader667** [opentoonz/opentoonz#682]
Hello,

Would it be possible to implement an option (tick box maybe?) that make the fill tool sampling from all levels? In order to have the outlines on one level and be able to colorize using the fill tool on another level.

Here a quick fill example on Gimp with the "sample merged" option activated.
![samplesalllayers](https://cloud.githubusercontent.com/assets/17130425/17114016/67447f88-52ad-11e6-8232-e80028a23f17.gif)

Thank you

**Comment by turtletooth** [comment]
Unfortunately, this is not how OpenToonz fill works.  There have to be lines on the same level in order for the fill to have something to fill.  OpenToonz has no concept of a filled area that isn't bounded by lines and adding that would require a rewrite of how vector and toonz raster levels work.

**Comment by Vader667** [comment]
Aw that's a shame... But thank you for the answer :)
