### ISSUE TITLE
Consider avoiding to store binaries in the source code repository

### ISSUE THREAD

**Issue by andreygursky** [opentoonz/opentoonz#69]
Please consider removing all the prebuilt libraries/binaries/object files (*.exe, *.dll, *.lib, *.a, *.obj, *.o, ...) and avoid adding them in the future. Additionally I would suggest to rewrite the history in order to purge them from the repository history to ensure the git repository remains small and quick.

*.exe:

> thirdparty/lzo/2.03/dict.exe
> thirdparty/lzo/2.03/precomp.exe
> thirdparty/lzo/2.03/simple.exe
> thirdparty/lzo/2.03/tools/lzocompress.exe
> thirdparty/lzo/2.03/tools/lzodecompress.exe
> thirdparty/lzo/2.03/lzotest.exe
> thirdparty/lzo/2.03/testmini.exe
> thirdparty/lzo/2.03/lzopack.exe
> thirdparty/lzo/2.03/precomp2.exe
> thirdparty/Lz4/Lz4_131/vs2010/CMakeFiles/2.8.12.2/CompilerIdC/CompilerIdC.exe

*.dll:

> thirdparty/lzo/2.03/lzo2.dll
> thirdparty/glut/3.7.6/lib/glut64.dll
> thirdparty/glut/3.7.6/lib/glut32.dll
> thirdparty/glew/glew-1.9.0/bin/32bit/glew32mx.dll
> thirdparty/glew/glew-1.9.0/bin/32bit/glew32.dll
> thirdparty/glew/glew-1.9.0/bin/64bit/glew32mx.dll
> thirdparty/glew/glew-1.9.0/bin/64bit/glew32.dll

*.lib:

> thirdparty/superlu/SuperLU_32.d.lib
> thirdparty/superlu/SuperLU_4.1/lib/libsuperlu_4.0.lib
> thirdparty/superlu/SuperLU_64.d.lib
> thirdparty/superlu/SuperLU_64.lib
> thirdparty/superlu/SuperLU_32.lib
> thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3.lib
> thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_64.lib
> thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3d.lib
> thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_64d.lib
> thirdparty/lzo/2.03/LZO_lib/lzo2_64.lib
> thirdparty/lzo/2.03/LZO_lib/lzo2.lib
> thirdparty/lzo/2.03/lzo2.lib
> thirdparty/glut/3.7.6/lib/glut64.lib
> thirdparty/glut/3.7.6/lib/glut32.lib
> thirdparty/openblas/libopenblas_32.lib
> thirdparty/openblas/libopenblas_64.lib
> thirdparty/LibJPEG/jpeg-9/lib/LibJPEG-9.lib
> thirdparty/LibJPEG/jpeg-9/lib/LibJPEG-9_64.lib
> thirdparty/Lz4/Lz4_131/lz4_32.lib
> thirdparty/Lz4/Lz4_131/lz4_64.lib
> thirdparty/glew/glew-1.9.0/lib/glew32mxs.lib
> thirdparty/glew/glew-1.9.0/lib/glew32mx.lib
> thirdparty/glew/glew-1.9.0/lib/glew32s.lib
> thirdparty/glew/glew-1.9.0/lib/glew64.lib
> thirdparty/glew/glew-1.9.0/lib/glew64mxs.lib
> thirdparty/glew/glew-1.9.0/lib/glew64s.lib
> thirdparty/glew/glew-1.9.0/lib/glew64mx.lib
> thirdparty/glew/glew-1.9.0/lib/glew32.lib
> thirdparty/zlib-1.2.8/lib/zlib-1.2.8_64d.lib
> thirdparty/zlib-1.2.8/lib/zlib-1.2.8d.lib
> thirdparty/zlib-1.2.8/lib/zlib-1.2.8_64.lib
> thirdparty/zlib-1.2.8/lib/zlib-1.2.8.lib
> thirdparty/libpng-1.6.21/lib/libpng16.lib
> thirdparty/libpng-1.6.21/lib/libpng16_64.lib
> thirdparty/libpng-1.6.21/lib/libpng16_64d.lib
> thirdparty/libpng-1.6.21/lib/libpng16d.lib

*.a:

> thirdparty/superlu/SuperLU_4.1/lib/libsuperlu_4.0.a
> thirdparty/superlu/libsuperlu_4.1.a
> thirdparty/LibJPEG/jpeg-9/lib/libjpeg.a

*.obj:

> thirdparty/lzo/2.03/lzo_str.obj
> thirdparty/lzo/2.03/lzo1b_99.obj
> thirdparty/lzo/2.03/precomp2.obj
> thirdparty/lzo/2.03/lzo1c_7.obj
> thirdparty/lzo/2.03/lzo_util.obj
> thirdparty/lzo/2.03/lzo1c_8.obj
> thirdparty/lzo/2.03/lzo1b_6.obj
> thirdparty/lzo/2.03/lzo1b_d1.obj
> thirdparty/lzo/2.03/lzo1b_5.obj
> thirdparty/lzo/2.03/lzo1y_1.obj
> thirdparty/lzo/2.03/lzo1x_1.obj
> thirdparty/lzo/2.03/lzo1f_1.obj
> thirdparty/lzo/2.03/minilzo.obj
> thirdparty/lzo/2.03/lzo1y_d1.obj
> thirdparty/lzo/2.03/lzo1b_xx.obj
> thirdparty/lzo/2.03/lzo1c_xx.obj
> thirdparty/lzo/2.03/lzo1c_d2.obj
> thirdparty/lzo/2.03/lzo_crc.obj
> thirdparty/lzo/2.03/lzo1x_d3.obj
> thirdparty/lzo/2.03/lzo1b_3.obj
> thirdparty/lzo/2.03/lzo1y_9x.obj
> thirdparty/lzo/2.03/lzotest.obj
> thirdparty/lzo/2.03/lzo1a.obj
> thirdparty/lzo/2.03/tools/lzodecompress.obj
> thirdparty/lzo/2.03/tools/lzocompress.obj
> thirdparty/lzo/2.03/lzo_ptr.obj
> thirdparty/lzo/2.03/lzo1z_d3.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1y_s1.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1f_f2.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1x_s1.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1x_s2.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1y_s2.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1y_f2.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1y_f1.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1c_s1.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1x_f1.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1c_s2.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1x_f2.obj
> thirdparty/lzo/2.03/asm/i386/obj/omf32/lzo1f_f1.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1y_s1.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1f_f2.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1x_s1.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1x_s2.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1y_s2.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1y_f2.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1y_f1.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1c_s1.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1x_f1.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1c_s2.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1x_f2.obj
> thirdparty/lzo/2.03/asm/i386/obj/win32/lzo1f_f1.obj
> thirdparty/lzo/2.03/lzo1f_9x.obj
> thirdparty/lzo/2.03/lzo1b_9x.obj
> thirdparty/lzo/2.03/lzo1x_1o.obj
> thirdparty/lzo/2.03/lzo2a_9x.obj
> thirdparty/lzo/2.03/lzo1x_d1.obj
> thirdparty/lzo/2.03/lzo1z_d2.obj
> thirdparty/lzo/2.03/lzo1y_d2.obj
> thirdparty/lzo/2.03/lzo1c_2.obj
> thirdparty/lzo/2.03/testmini.obj
> thirdparty/lzo/2.03/lzo1c_4.obj
> thirdparty/lzo/2.03/lzo1_99.obj
> thirdparty/lzo/2.03/lzo1b_7.obj
> thirdparty/lzo/2.03/lzo2a_d2.obj
> thirdparty/lzo/2.03/lzo1y_d3.obj
> thirdparty/lzo/2.03/lzo1x_o.obj
> thirdparty/lzo/2.03/lzo1c_d1.obj
> thirdparty/lzo/2.03/lzopack.obj
> thirdparty/lzo/2.03/lzo1x_9x.obj
> thirdparty/lzo/2.03/lzo1c_9x.obj
> thirdparty/lzo/2.03/lzo1z_d1.obj
> thirdparty/lzo/2.03/lzo2a_d1.obj
> thirdparty/lzo/2.03/dict.obj
> thirdparty/lzo/2.03/lzo1c_99.obj
> thirdparty/lzo/2.03/lzo1f_d1.obj
> thirdparty/lzo/2.03/lzo1c_5.obj
> thirdparty/lzo/2.03/precomp.obj
> thirdparty/lzo/2.03/lzo1c_6.obj
> thirdparty/lzo/2.03/lzo1a_99.obj
> thirdparty/lzo/2.03/lzo1c_rr.obj
> thirdparty/lzo/2.03/lzo1c_3.obj
> thirdparty/lzo/2.03/simple.obj
> thirdparty/lzo/2.03/lzo1b_cc.obj
> thirdparty/lzo/2.03/lzo1x_1k.obj
> thirdparty/lzo/2.03/lzo1z_9x.obj
> thirdparty/lzo/2.03/lzo1b_1.obj
> thirdparty/lzo/2.03/lzo1b_rr.obj
> thirdparty/lzo/2.03/lzo1b_d2.obj
> thirdparty/lzo/2.03/lzo1.obj
> thirdparty/lzo/2.03/lzo1b_8.obj
> thirdparty/lzo/2.03/lzo1c_1.obj
> thirdparty/lzo/2.03/lzo_init.obj
> thirdparty/lzo/2.03/lzo1b_9.obj
> thirdparty/lzo/2.03/lzo1x_1l.obj
> thirdparty/lzo/2.03/lzo1f_d2.obj
> thirdparty/lzo/2.03/lzo1y_o.obj
> thirdparty/lzo/2.03/lzo1c_cc.obj
> thirdparty/lzo/2.03/lzo1b_4.obj
> thirdparty/lzo/2.03/lzo1b_2.obj
> thirdparty/lzo/2.03/lzo1x_d2.obj
> thirdparty/lzo/2.03/lzo1c_9.obj

*.o:

> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1f_f1.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1f_f2.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1y_s1.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1y_f2.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1x_f1.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1x_f2.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1c_s1.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1x_s1.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1x_s2.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1c_s2.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1y_s2.o
> thirdparty/lzo/2.03/asm/i386/obj/coff32/lzo1y_f1.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1f_f1.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1f_f2.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1y_s1.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1y_f2.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1x_f1.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1x_f2.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1c_s1.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1x_s1.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1x_s2.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1c_s2.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1y_s2.o
> thirdparty/lzo/2.03/asm/i386/obj/elf32/lzo1y_f1.o

**Comment by odysseywestra** [comment]
Okay, how would we accomplish this so that it will not only still build for Mac and Windows(and Linux soon), but stay stable as well? In other words what is your plan(s) to accomplish this?

**Comment by janisozaur** [comment]
Use services like travis-ci (for Linux and OS X) and appveyor (for windows) to provide continuous integration.

**Comment by janisozaur** [comment]
I'd also recommend a rewrite of history with blobs purged, while this repository is still fresh.

**Comment by janisozaur** [comment]
In case you would like to pursue that option, you will find these links most helpful:

* https://help.github.com/articles/remove-sensitive-data/
* https://help.github.com/articles/removing-files-from-a-repository-s-history/

I've also made a [fork with the files mentioned above stripped away](https://github.com/janisozaur/opentoonz), using `bfg`:
```
for i in exe dll lib a obj o ; do bfg --delete-files \*.$i ; done
```

**Comment by andreygursky** [comment]
> In other words what is your plan(s) to accomplish this?

I suggest to move thirdparty into a separate repository, since ideally (or hopefully in the near feature) MacOS (brew) and GNU/Linux users will not need this at all. But also for this new opentoonz-thirdparty repo I recommend not to add binaries, only source code (git is for sources in the first place). On the one hand you'd like to provide users with a comfort of prebuilt libraries, but why not then to provide a prebuilt git, cmake, compiler, binutils, libc,.. Xcode,.. OS :) So one must admit, you require some things and compared to the complexity of OpenToonz, building per hand of libtiff, libpng, libjpeg is much easier. Thus if someone decides to build OpenToonz, building of these thirdparty libraries (if at all) will be the smallest issue, I'm sure.

Since you have altered only libtiff, you would need only this in your thirdparty repo. You could put references where to get original tarballs for other libraries. Also you could put these tarballs on your site under "Download sources for thirdparty libraries" and you can still offer prebuilt ones under "Download prebuilt thirdparty libraries". They can be archived on your site, just like on sourceforge (but not in git).

Another problem with managing thirdparty libraries for you is to be sure to update them instantly once some security issue is discovered. This is one more argument to rely on that, what brew and GNU/Linux Distribution packages offer. The only important thing would be nice, if you just document that you could successfully build OpenToonz with particular versions of thirdparty libraries. And it would be even better, if you would do it from time to time, once new releases come out.

By the way, do you know, are the programmers of 64bit TIFF support still reachable? It would be great, if one could talk to the upstream to find an acceptable solution to integrate this feature in upstream. The problem that I see is the code duplication. Maybe upstream could find a nice solution for this?

So I propose:
 - create opentoonz-thirdpary repository with libtiff
 - document exactly the versions of used thirdparty libraries and place thirdparty libraries tarballs (sources and prebuilt ones) on the main site as downloads
 - add into howto_build an additional instruction to download and unpack the required thirdparty libraries from the download section of the main site (or better: specifying direct links) (e.g., like it is already done for boost)
 - rewrite history for opentoonz to get rid of thirdparty (I'm testing this now)

In case you have already negative experience with some suggestions, maybe a compromise would solve them?

**Comment by andreygursky** [comment]
@janisozaur: thanks for infos.

**Comment by odysseywestra** [comment]
There's also the Github release page as a place we could store them as well. That way they can be downloaded with the source code zip files when it comes to release time.

**Comment by JosefMeixner** [comment]
It is not that easy. As I built the VS 2015 versions (#307) I saw, that there are local changes and in part special instructions to build the libraries. So you can't use the tars of the original packages, but it would be possible to create a repository will all the sources and a zip-archive with the binaries. I definitely agree, that the binaries should be removed from the repository.

So perhaps it would make sense to leave the sources in the tree and only remove the binaries?

**Comment by turtletooth** [comment]
Closing this - Git LFS seems to be the solution decided upon by the developers.
