### ISSUE TITLE
Set start/stop markers in 1 room, visible but ignored in others

### ISSUE THREAD

**Issue by manongjohn** [opentoonz/opentoonz#692]
I animated something over a number of frames, say 20 frames, and set start and stop markers  at 4 and 12, for example. 

In the room I set it in, it works normally when playing in the viewer and only runs between 4-12.  The First frame button brings me to 4 and Last frame button to 12. 

If I switch to another room, I can see the start/stop markers at 4 and 12 where I set them.  However, when I play in the viewer in that room, it completely ignores them.  First frame button takes me to 1 and Last frame button to 20.

Additionally, if I reset one of the markers to where it already is, then it recognizes both 4 and 12, but only in that room.

If I change one of the markers in the 2nd room (changed 4 to 2), when I go back to the 1st room where I set the markers originally, it still only recognizes 4-12 but the start marker is clearly set to 2.

I don't recall it working that way in prior versions and only noticed it on the Nightly build I installed.

Using Windows version 1.0.3 (built Jul 30 2016 11:03:49)

**Comment by Rayek** [comment]
I can confirm this behaviour. Start/stop markers between rooms are broken.

**Comment by turtletooth** [comment]
Fixed in #709

**Comment by manongjohn** [comment]
I'm guessing this didn't make it into 1.1.0? Which nightly should I check this in?

**Comment by turtletooth** [comment]
It's hasn't been merged yet.  Hopefully soon.
