### ISSUE TITLE
The style editor goes black

### ISSUE THREAD

**Issue by RoHazanki** [opentoonz/opentoonz#693]
Hello, I need help with the style editor, when I try to use plain color, all of the square goes black. The same happens to color model when selected.

**Comment by RodneyBaker** [comment]
@ideasman42 tagged this as a bug but that was well over a year ago.
@RoHazanki are you still experiencing this problem?

**Comment by artisteacher** [comment]
I used to have issues with the color model displaying strangely & black overriding certain areas in the style editor but they were resolved a while ago.

**Comment by artisteacher** [comment]
This sounds like an old OpenGL issue that’s been fixed. No response from the OP in 2 years so this can probably be closed.

**Comment by RodneyBaker** [comment]
Agreed.  Closing.
@RoHazanki If you have any updates please let us know.
