### ISSUE TITLE
Scrub timeline in view

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#695]
In Maya holding down k+middlemouse and dragging in the viewport to scrub is really nice, and I would like to add this as a request.

It can be taxing on the arm, and an additional option to use the a shortcut key (k?) + scroll-wheel ought to be implemented as well.

Similar to Mscrub for 3dMax:

mScrub allows you to easily scrub the timeline and navigate thru keyframes with the mousewheel.

Only for 3dsmax 2013+
Press and hold SPACEBAR

Wheel – Moves back and forth 1 frame

CTRL + Wheel – Moves 10 frames forward or backwards

SHIFT + Wheel – Moves to next or previous keyframe.

Release SPACEBAR and you’re done.

**Comment by turtletooth** [comment]
#994
