### ISSUE TITLE
[Qt] QDockWidget::title is hard coded

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#696]
I may be missing something, but I can't use QDockWidget::title to style the widget titlebars using a stylesheet.

```
QDockWidget
QDockWidget::title
QDockWidget::close-button
QDockWidget::close-button:hover
QDockWidget::close-button:pressed
QDockWidget::float-button
QDockWidget::float-button:hover
QDockWidget::float-button:pressed
```

Why is this?

**Comment by konero** [comment]
Opening again.

We use specifically calibrated monitors and we're having terrible issues with contrast on the title bars in the widget windows. Basically, there is a sharp white line that is "doing heads in".

Even with a typically calibrated/consumer setup it is still quite striking when staring at a Cintiq monitor for extended periods.

Can a class be added to Qt widgets so we can override the title bar styling using the stylesheets?

**Comment by shun-iwasawa** [comment]
As you guessed, the title bar for each panel is hard-coded for now.
(In the function TPanelTitleBar::paintEvent() in pane.cpp line 340)
I think I can bring them out to the stylesheets.
