### ISSUE TITLE
How to get access to current Scene object with script console?

### ISSUE THREAD

**Issue by kawaiicreature** [opentoonz/opentoonz#697]
How to get access to current Scene object with script console?
Does the current opened scene have any connection with script console?

**Comment by RodneyBaker** [comment]
I haven't really dug in to scripting but...

A Scene's object is a Level so with a script we'd use something like:

scene.setCell(row, col, {level:a, fid:1})

This is and example from the scripting manual at:  http://www.toonz.com/htm/support/scripts/ToonzScript.pdf

**Comment by RodneyBaker** [comment]
Regarding your question about accessing the resources of a current Project.  I believe the means to get at them is through relative paths (as opposed to absolute paths that have all of the path specified)

From the scripting manual:

> If the path is relative scenes of the current project are used.

Disclaimer:  I am not able to get much of any response from the console at this moment.  I'll have to brush up on my scripting.

**Comment by kawaiicreature** [comment]
> Edit/Update: It looks like pasting into the console wasn't working but typing commands in does.

Script console has symbol limit to paste. So you can type in .js file and run File -> Runs Script.

**Comment by jorgedelcampo** [comment]
Hi everyone. I came here looking for documentation about ToonzScript. The reference page in http://www.toonz.com/ is not available anymore. Do you know if there's another official page to learn about this topic?

For now, this is the only reference I've found: https://opentoonz.readthedocs.io/es/latest/toonzscript.html

This are all existing commands for ToonszScript or there's more information in other place? 

Kind regards!
