### ISSUE TITLE
Feature Request:  Allow for Scaling of Individual Plastic Nodes

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#698]
Please provide a simple way to scale a Plastic Node - (along with it's associated and affected Mesh portion).  

For this to work properly, all Child Nodes would need to scale up or down along with the selected Node.

I suggest simply holding down the "Alt" key while Left Clicking and Dragging left and right.

This will allow a quick way to produce animated foreshortening. 

Thank you,

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
