### ISSUE TITLE
Allow the Sorting Order of Plastic Nodes to Affect Child Nodes.

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#699]
It is a tedious process to change the Sorting Order of all Child Nodes (of a chain of Nodes) - in order to move, for example, an arm and hand that starts in front of a body - to a position behind that body.

A great speed and efficiency improvement could be realized if, for example, by setting the Sorting order of an "Elbow" Node, all Child Nodes down the arm and into the Hand would also be moved to the same Depth as the Elbow.

This functionality could be enabled simply by adding the "Ctrl" key modifier when selecting a Plastic Node while in "Animate Mode".

The software would then be instructed to adjust all Child Nodes to the same depth as the selected Parent Node.

Thanks,

Greg Smith

**Comment by animking** [comment]
Agreed.

**Comment by blurymind** [comment]
What you request here should be optional imo.

Some times you do want to have that control.

**Comment by blurymind** [comment]
the ctrl key sounds good. I think spine 2d has a key to select children nodes - that would be another way to tackle it.

**Comment by blurymind** [comment]
ideally It would be nice if we can set specific nodes to be affected by the z sorting of their parent.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
