### ISSUE TITLE
Version 1.1.0 Mac Still Creates a "Blanket" Plastic Mesh, Not Shape Based

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#705]
I do realize that the Mac version of nearly every application in existence is the "red headed step child" - regarding current updates - but this is a bug or design flaw that makes the software unusable to me on my native and preferred platform.

Draw any shape and fill it.  Select "Create Mesh" from the Plastic Tool Options.  See the resulting Plastic Mesh that is produced - a rectangle surrounding your shape - thus making the Plastic Tool completely unusable on the Mac.  (Go ahead and try placing Nodes and Animating them - what a mess).

The Plastic Tool is probably the number One innovation that sets OpenToonz apart from any other application.  Why not fix this?

Greg Smith

**Comment by Dragularos** [comment]
I guess there are not many people working on mac based problems. Maybe we can build up a specific Mac-Crew?

**Comment by turtletooth** [comment]
Duplicate of #780  That one has more comments.  Closing
