### ISSUE TITLE
Feature Request:  Allow the Creation of Independent Plastic Nodes (Not Linked)

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#706]
Many animation situations require the distortion of a Plastic Mesh in "Non-Skeletal" fashion.

Sometimes you simply need to Move, Rotate or Scale a portion of a Plastic Mesh - without affecting any other "skeletal" or "linked" set of Plastic Nodes - all within the same Plastic Mesh.

This would be particularly useful when animating a photo or a bitmapped piece of art produced externally or internally.

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
