### ISSUE TITLE
Linux version repo

### ISSUE THREAD

**Issue by fthamura** [opentoonz/opentoonz#72]
where will be the tags for linux version,

or will opentoonz under 1 repo, but follow the operating system to compile the code

**Comment by blurymind** [comment]
read before posting :)
https://github.com/opentoonz/opentoonz/issues/34
https://github.com/opentoonz/opentoonz/issues/49

This is being worked on at the moment

**Comment by odysseywestra** [comment]
Closing since this is a duplicate of #34 and #49 like @blurymind mentioned.
