### ISSUE TITLE
Improve direct inputting feature in Xsheet

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#721]
OpenToonz has a feature for defining animation level directly in xsheet cell.

> **To define an animation level directly in xsheet:**
> 1. Double-click a cell, then type a name and a number; the name and the number must be separated by a space.
> 2. Press enter to add a new drawing, and type a different number that will be assigned to the new drawing.
> 3. Go on adding all the drawings you need.
> 4. Click a different cell to end the process.
> 
> _(Toonz Harlequin 7.1 User Manual p.39)_

Improve this feature and gain usability as follows:
- Enable to input multiple frames at a time. For instance, type frame numbers with selecting 3 cells can make 3-step animation.
- When inputting number (without level name) into the empty cell, if the next upper cell is empty, search upper cells and use the nearest level rather than do nothing.
- Enable to type '0' which makes the target cell empty.

**Comment by RodneyBaker** [comment]
I am very interested in this aspect of xsheet usage especially as it touches such a core element of OpenToonz; the xsheet.  Enhancing direct user interaction with the xsheet (as proposed) is exciting news.
