### ISSUE TITLE
Crashes when saving, loading scene, loading level...

### ISSUE THREAD

**Issue by aaaa46** [opentoonz/opentoonz#724]
... doing just about anything. No problems with startup, though, curiously.
Everything was working fine for weeks; everything saved and loaded properly at every attempt. But just a couple days ago, I went to load a scene, and OpenToonz stopped responding, then crashed. I rebooted it, tried to load a level, and the same thing happened. Attempting to save a blank scene does the same, and basically every option in the File menu causes OpenToonz to stop responding and crash.
I'm using Windows 10, and at the time of the first crash, I was using OpenToonz 1.0. I then updated to 1.0.1, to the same result. I'm now using 1.1.1, and I'm still having the same difficulty. I've tried restarting my computer, uninstalling and reinstalling OpenToonz, but nothing has worked. I haven't been able to find any examples of others having the same issue anywhere.

**Comment by lordadamson** [comment]
could you please try to tell exacts steps that if you do the program will crash every time?
example:
1- click file menu
2- click load scene
3- click on <insert something that causes crash here>
4- program crashes
make sure these steps will crash the program every time, that will help fix it.

**Comment by lordadamson** [comment]
are #1156 #1157 related?

**Comment by turtletooth** [comment]
If this is still an issue, could you give us the steps to reproduce and we can reopen this and explore it.
