### ISSUE TITLE
Undo palette additions yields bad color ListView

### ISSUE THREAD

**Issue by astraldata** [opentoonz/opentoonz#728]
After undoing color additions (and possibly running out of undo operations), color "ListView" gets wonky in Drawing tab. Not sure if this happens in other tabs.

I'm in Windows 10 running in Compatibility Mode for Windows 7, since OpenToonz crashes constantly otherwise.

**Comment by turtletooth** [comment]
Can you give steps that consistently cause this problem?

**Comment by astraldata** [comment]
Doesn't seem to happen like it used to -- however, if you start a new project, new scene, save it, close open toonz, then re-open it, then make three new styles with default names, etc., but the last two styles must be colors (be sure to set them to any color besides black) and then undo them, only the third (index 3) is kept intact -- number 2 becomes black when you Redo adding them both.

**Comment by RodneyBaker** [comment]
Closing as likely resolved and/or abandoned.
@astraldata Please let us know if you are still experiencing similar issues.
