### ISSUE TITLE
Feature Request: ability to export for game (asset)

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#730]
I use [Spriter](https://brashmonkey.com/), but in Spriter you can not drawing directly. toon boom can export animation for game too, you can read [here](https://www.toonboom.com/industry/games) about that.

at the moment in OT you can export animate GIF for use in your game, but animate GIf do no support transparency and trim now. #729

I am beginner in game developing, I hop professional game developer expand this request. :)

**Comment by 2dvision** [comment]
https://github.com/opentoonz/opentoonz/issues/729

**Comment by TheoXD** [comment]
related to this https://github.com/opentoonz/opentoonz/issues/173

**Comment by blurymind** [comment]
This is not the first time it's raised as a duplicated request - seems to be a highly desired feature :D 
Too bad opentoonz devs are not into game development like us
