### ISSUE TITLE
Qt5Script is no more?

### ISSUE THREAD

**Issue by TheoXD** [opentoonz/opentoonz#731]
After reinstalling windows and Qt I've noticed that Qt5Script lib is no longer present in 5.6, so now I can't compile opentoonz from source as I can't find it anywhere. Are there plans to remove this dependency completely or add extra step to documentation? It was deprecated for quite some time as I understand, and a lot of Qt developers are not happy of it's removal.

**Comment by walkerka** [comment]
You can install QtScript as an optional module. There's still an option in 5.7's installer. But it's better to upgrage old QtScript to QJSEngine (in qml). The API is very similar.
http://doc.qt.io/qt-5/qjsengine.html

**Comment by turtletooth** [comment]
I think this is resolved?
