### ISSUE TITLE
Project Roots (again)

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#736]
I wanted to have a discussion about project roots and see if there is a way to find a solution that will work for everyone.  

I have built a version that places the main project root in the My Documents folder along with the sandbox.  This is needed for my work as a teacher, but may be a behavior that many people would expect from a program.  I know that it is possible right now to store everything except the project xml file anywhere you want, but I prefer for my students to have every project related file in the same location.  I realize that this may not be ideal in some situations/studios.

Is there a solution for project roots that the team at Dwango would be open to that allows for either the main project root, or at least one project root to be in the documents folder?

Maintaining that second version means creating two versions of my changes in some cases and I would much rather be able to focus on the main OpenToonz.

**Comment by blurymind** [comment]
I will continue to stand by the idea that project folders should be capable of being moved to different locations and opened without issue.
As such - and as before - Autodesk Maya's design is an example of a correct way to do that.

and that is - allow the user to specify the project root location when opening a project and creating a project.
All of the project resources can then be automatically located and loaded relative to that path.

As a result when moving the project to a new path, all the user has to do to open it again is to specify where that new path is.

And this can be an optional behavior. Any resource path could still be set to a static location that is not relative to the project root
