### ISSUE TITLE
Export to WAV

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#737]
@turtletooth 
Currently it is not possible to export the sound track only in OpenTOonz. With FFmpeg already supporting the export of MP4, WEBM, and GIF, it should be a relatively simple task to add WAV export/

This would tremendously simplify editing later on in an external video editor when combining exported image sequences.

Ideally the user would be able to control the stereo left and right amount, or even dolby-surround options for each sound column somehow - but this is probably a bit too much to ask at this point.

**Comment by turtletooth** [comment]
I've got wav export working, but its pretty hacky.  I'm going to see if I can make it cleaner, but it's totally doable (I'm going to add mp3 export also).

**Comment by turtletooth** [comment]
Do you think that the soundtrack should also include the time before and after there are sounds on the xsheet, such as sound not starting until frame 42- should there be silence in the wav file until frame 42, or should the wav file start at frame 42.

I'm leaning toward including blank space to make dropping the sound file and syncing in a video editor as easy as possible.

**Comment by turtletooth** [comment]
#744
