### ISSUE TITLE
Problem with the red color in the cleanup- bug

### ISSUE THREAD

**Issue by qtoonz** [opentoonz/opentoonz#738]
Actually could be any color, but let me simplify it. This is for scanned images...

When we have a intersection of lines, reds and black lines, the red predominates, but this no have sence, by contrast the black should be the choose one.

This issue complicates the inking and painting process after the cleanup.

I leave you a video with the problem if I was not clear enough.
https://youtu.be/gqLAZDhUZy4
go to the secound 0:55 to see directly the problem

I hope you can fix it, reguards

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
