### ISSUE TITLE
Compilation error on linux 64bits

### ISSUE THREAD

**Issue by obiwankennedy** [opentoonz/opentoonz#740]
Hi, 

Sorry if my question is answered somewhere but I find no indications in the readme for compilation.
I got error about wrong type of file for opentoonz/thirdparty/superlu/libsuperlu_4.1.a.
I run «file» on it, and it says it is a 32bits binaries. 
Does opentoonz support to be compiled on 64bits computer ?
I have install the libsuperlu from my system (Ubuntu 16.04).
There is a way to tell him to take the one from my environment ?

I try to recompile libsuperlu (form thirdparty source) but it does not work straightforward. 
If you have any clue. 

Thanks.

**Comment by ideasman42** [comment]
As for exactly why this happens, Im not sure, I've built opentoonz of Ubuntu just by following the instructions and didn't get this problem.

In the CMakeCache.txt file, make sure the superlu library used is your systems and not the one thats bundled with opentoonz.

Closing.
