### ISSUE TITLE
Preview not update when entering or exiting the group

### ISSUE THREAD

**Issue by arh2009** [opentoonz/opentoonz#741]
when entering a group, the preview still not update, (the other group or shapes not semi transparent)
it happen too when i able to enter a group (with other group or shapes semi transparent), the preview still not update when i try to exit the group (preview still semi transparent)

**Comment by arh2009** [comment]
![bug group](https://cloud.githubusercontent.com/assets/20434396/17727279/7a9792f0-6482-11e6-8679-3aef76e39041.png)

when entering a group, the preview still not update...

**Comment by artisteacher** [comment]
@arh2009 are you still having this issue? Preview is updating just fine for me when entering a group.

**Comment by RodneyBaker** [comment]
Closing as this issue appears to be resolved.
