### ISSUE TITLE
Native look and feel for GUI

### ISSUE THREAD

**Issue by ShalokShalom** [opentoonz/opentoonz#750]
Hi there, is it possible to let OT look like any other qt program here?

I mean, this is one thing for what qt becomes popular, what force currently this old look?

**Comment by blurymind** [comment]
I agree - the current theme is clunky and not very efficient in terms of use of screen estate.
It is a regression from Toonz Harlequin's theme.

@shun-iwasawa  Shouldnt we strive to be better instead? Why was the theme downgraded that way

**Comment by konero** [comment]
@blurymind Could you be specific? I never liked the Harlequin UI.

**Comment by blurymind** [comment]
The gui controls  (buttons,labels,etc) in harlequin are smaller - as a result there is more screen estate for the canvas.

The biggest offender for GUI regression for me personally is the curves/keframes editor. I already filed a bug report about it several months ago.

#159

**Comment by turtletooth** [comment]
Here's what I have been using.  It's probably too aggressive on flattening out the UI, but I like it.

![theme](https://cloud.githubusercontent.com/assets/4576381/17958286/c1b94f06-6a55-11e6-8aff-9635321cc1bd.jpg)

**Comment by blurymind** [comment]
You should commit it. Its way better than the current theme. Most gui
nowadays goes for flattening as it is less visually distracting :)

**Comment by turtletooth** [comment]
#759 I tweaked it a bit more and unflattened some areas I had originally flattened because they made some buttons unintuitive (hard to tell they were buttons).
![slate2](https://cloud.githubusercontent.com/assets/4576381/17993729/8a3ab384-6b0f-11e6-9bda-2f7c5bff62e9.jpg)

**Comment by turtletooth** [comment]
Working on a dark theme:
![darktheme](https://cloud.githubusercontent.com/assets/4576381/17994419/97f1a77a-6b15-11e6-855a-9ef743a3eee8.jpg)

**Comment by blurymind** [comment]
@turtletooth  it looks much more professional than the current one! Can we make it the new default please :)

**Comment by ShalokShalom** [comment]
My complete operating system is based on Qt and KDE:

All looks like the same. 

Again, its one of the strengths by Qt, to look native on each platform: GTK, Windows, OS X and so on.

Why not simply use the native, default theme of each platform?

Is this much effort now?

**Comment by konero** [comment]
I used to do UI design a long time back, when Macromedia had Fireworks MX. This "slate" theme is nice, but the original has slightly better accents, so I'm not too sure about it being a new default, but definetely add it in, Blender-wise. I was thinking of building one with a colleague who works with Qt/C++ but the current source is a little bit too blotchy in places and neither of us have time to understand it.

Here's our design intent though if you want to have a bash. The Tool Options bar was meant to incorporate something @blurymind mentioned awhile back about using Blender style icon buttons for the axis controls, here it's used for Type/Mode controls for the Fill Tool.

([click here for full-size](https://cloud.githubusercontent.com/assets/19820721/18026992/33f79b4a-6c4f-11e6-94ec-276045eb28a9.jpg))
![toonz_ui_full_992](https://cloud.githubusercontent.com/assets/19820721/18026992/33f79b4a-6c4f-11e6-94ec-276045eb28a9.jpg)

Widgets.

![toonz_ui_clean](https://cloud.githubusercontent.com/assets/19820721/18026999/48192738-6c4f-11e6-8805-e795b357ac3d.jpg)

Palette close-up.

![palette](https://cloud.githubusercontent.com/assets/19820721/18027040/6241808c-6c50-11e6-820c-a751a6d10bb5.jpg)

Tool options.

![blenderbuttons](https://cloud.githubusercontent.com/assets/19820721/18027061/d1b8e270-6c50-11e6-961d-09c5fc4078a5.jpg)

Titlebar controls.

![camcontrol](https://cloud.githubusercontent.com/assets/19820721/18027046/8d005d0c-6c50-11e6-8c40-93087c318906.jpg)

**Comment by turtletooth** [comment]
That looks great!  Would you mind sharing those icons so I could start incorporating them?  They look amazing!

**Comment by blurymind** [comment]
Yes please! This would make the interface much better!

**Comment by konero** [comment]
Thanks! I'll package the icons up and post them in batches as I come across them, I'll be able to look better tomorrow morning.

These are the **Combo Viewer, Scrollbar, Title Pane and Close Pane** icons.

ZIP: [OpenToonz_Icons_ComboViewer.zip](https://github.com/opentoonz/opentoonz/files/440757/OpenToonz_Icons_ComboViewer.zip)


![safe_normal](https://cloud.githubusercontent.com/assets/19820721/18028643/8210232e-6c7c-11e6-81f4-4fdafed9e257.png) ![safe_active](https://cloud.githubusercontent.com/assets/19820721/18028644/839893ca-6c7c-11e6-9672-f41e474d36cf.png)
![grid_normal](https://cloud.githubusercontent.com/assets/19820721/18028646/903721e6-6c7c-11e6-9f87-2a0613e8ef41.png) ![grid_active](https://cloud.githubusercontent.com/assets/19820721/18028647/9227409e-6c7c-11e6-8fbc-dc3b1a6bae5f.png)
![3dcam_normal](https://cloud.githubusercontent.com/assets/19820721/18028649/99c0868a-6c7c-11e6-93e8-3f207036154c.png) ![3dcam_active](https://cloud.githubusercontent.com/assets/19820721/18028650/9cca905a-6c7c-11e6-813e-11e0499811d5.png)
![cam_normal](https://cloud.githubusercontent.com/assets/19820721/18028652/a744d252-6c7c-11e6-9356-884ef16969dc.png) ![cam_active](https://cloud.githubusercontent.com/assets/19820721/18028653/a8f4e2cc-6c7c-11e6-90e6-a5c5cf2bbbf1.png)
![freeze_normal](https://cloud.githubusercontent.com/assets/19820721/18028655/afcf3214-6c7c-11e6-8ca3-5a25a3dc7b3a.png) ![freeze_active](https://cloud.githubusercontent.com/assets/19820721/18028656/b2074684-6c7c-11e6-96eb-41e767fb8850.png)
![table_normal](https://cloud.githubusercontent.com/assets/19820721/18028662/c64276f0-6c7c-11e6-9863-6d536dd2cfa6.png) ![table_active](https://cloud.githubusercontent.com/assets/19820721/18028663/c78c4004-6c7c-11e6-8c96-c6b47148b7a7.png)
![preview_normal](https://cloud.githubusercontent.com/assets/19820721/18028658/b7eadd22-6c7c-11e6-8c05-3906533ca087.png) ![preview_active](https://cloud.githubusercontent.com/assets/19820721/18028659/b971bbde-6c7c-11e6-8c8c-22b8f5d5d511.png)
![subcamera_normal](https://cloud.githubusercontent.com/assets/19820721/18028660/bf01d8c2-6c7c-11e6-978d-ac56b12e96f0.png) ![subcamera_active](https://cloud.githubusercontent.com/assets/19820721/18028661/c0f24a72-6c7c-11e6-820a-124fc36edfb6.png)
![close_pane_normal](https://cloud.githubusercontent.com/assets/19820721/18028668/ddd8ba18-6c7c-11e6-88e3-abf5ed1f2624.png) ![close_pane_active](https://cloud.githubusercontent.com/assets/19820721/18028669/e01ed23a-6c7c-11e6-90cd-4e460177183f.png)
![tpaneltitlebar_border_active](https://cloud.githubusercontent.com/assets/19820721/18028671/e5a4a3e2-6c7c-11e6-8ac2-3ef84588a28d.png)
![scroll_arrow_up](https://cloud.githubusercontent.com/assets/19820721/18028716/877249cc-6c7d-11e6-802e-d9d6a9326668.png) ![scroll_arrow_up_pressed](https://cloud.githubusercontent.com/assets/19820721/18028717/89255f48-6c7d-11e6-9ea7-0d0b00614c49.png)
![scroll_arrow_down](https://cloud.githubusercontent.com/assets/19820721/18028720/8cdd0c08-6c7d-11e6-95c6-4c8ea4ad5c4b.png) ![scroll_arrow_down_pressed](https://cloud.githubusercontent.com/assets/19820721/18028721/8e151d90-6c7d-11e6-9fe7-6d7e1dde2b18.png)
![scroll_handle](https://cloud.githubusercontent.com/assets/19820721/18028722/9275cea2-6c7d-11e6-8aab-0b73068a7b52.png)

**Comment by ShalokShalom** [comment]
Yeah, this looks professional.

**Comment by konero** [comment]
Here's the icons from the palette window, also includes the lock icon and the chain icon for the dpi link.

ZIP: [OpenToonz_Icons_Palette.zip](https://github.com/opentoonz/opentoonz/files/441151/OpenToonz_Icons_Palette.zip)

The lock icon I remember we changed later because the one used in the mock above got buggy when it was used in the tool options bar, so I shortened it.

In respect to the key icons, since I don't use keys I'm not one hundred percent sure as to what they mean, so I just gave them different color codes for each state and cleaned up the original key icon.

![key_no](https://cloud.githubusercontent.com/assets/19820721/18034229/56643266-6d2f-11e6-8fdc-67fce4c1d6ef.png) ![key_partial](https://cloud.githubusercontent.com/assets/19820721/18034233/5b6bccc4-6d2f-11e6-8767-c1ceae90c1ef.png) ![key_total](https://cloud.githubusercontent.com/assets/19820721/18034236/5ec2082a-6d2f-11e6-9ee4-5021fdae5696.png)

I'll zip up the button images and code that was used for QPushButton/QlineEdit/QComboBox/CheckButton etc and the icons in the tool options bar for type and mode soon.

**Comment by ShalokShalom** [comment]
OK, i try it one more time: Is it possible, to give this app its native look and feel?
Where is the code, which change that one with the custom theme?

**Comment by blurymind** [comment]
@konero pleae keep going! These are epic :+1:

**Comment by turtletooth** [comment]
@ShalokShalom The themes are in the stuff/config/qss folder.  You can modify the qss files - they are almost css.

**Comment by ShalokShalom** [comment]
Ok, thanks. Since all this themes overlay the actual native qt skin should it be enough to delete them all.
Where is this /stuff folder placed usually?

**Comment by turtletooth** [comment]
Some items are set in the code and not in the qss, but you can get a feel how it would look by removing the text from the files.  (I don't know how it would handle not having any themes in the folder).  It looks like you are on linux, so I don't know where the stuff folder is.  It is inside the OpenToonz_1.1 folder, wherever that is.  (/?)

**Comment by ShalokShalom** [comment]
ok, thanks a lot. How change the default GUI now? Get any of this proposals included in a upcoming release?

**Comment by ShalokShalom** [comment]
Are there any news?

**Comment by ambethia** [comment]
This great. One thing that initially put me off on OpenToonz was the UI. It was definitely an unfair judgement, but I can't imagine I'm the only one. Those last screenshots that @konero shared look amazing! I look forward to something along those lines becoming the default.

**Comment by Agnyy** [comment]
![image](https://cloud.githubusercontent.com/assets/25137502/22667260/18026100-eccd-11e6-93cb-5b54034724cb.png)

**Comment by Agnyy** [comment]
![image](https://cloud.githubusercontent.com/assets/25137502/22667356/80972746-eccd-11e6-854d-1d7c63256ff2.png)

**Comment by ShalokShalom** [comment]
I am still interested into a native look and feel - all the apps here look the same, even GTK based stuff follows the system internal theme

**Comment by turtletooth** [comment]
@ShalokShalom I don't think that I've seen anyone with the same request.  Nearly every media application has a unique theme and interface.  I personally don't care for the look of a plain old light gray application.  I much prefer a dark themed interface.

**Comment by ShalokShalom** [comment]
Nearly each single qt based programm offer that.

**Comment by ambethia** [comment]
I would happily settle for "professional" and "not ugly", whether that's a native look, or just something more refined, I don't care.

**Comment by ideasman42** [comment]
Is there any point to keeping this issue open?

Further are any developers interested to work on this?

**Comment by ShalokShalom** [comment]
Since this thread get misused for another issue from the very first answer and my suggestions ignored and blocked anyway; yeah fine, thanks.

**Comment by ideasman42** [comment]
@ShalokShalom, no need to be sarcastic.

UI issues are very subjective and tend to get *noisy* when nobody takes responsibility for them.

If you do continue to contribute issues to the tracker, suggest to have smaller focused issues to avoid lots of discussion with no outcome.
If a an active UI developer becomes involved, I'm sure topics like this wont be forgotten simply because the issue is closed.

**Comment by ShalokShalom** [comment]
"UI issues are very subjective and tend to get noisy when nobody takes responsibility for them (planning and developing, beyond the suggestion its self)."

So let the underlying OS decide. 

Qt is designed for the goal to provide a nice looking UI on all platforms by default and support the use of native themes/icons and so on - why break this functionality, especially since it works fine for 97% of all projects, who use Qt as their platform - why count to these 3% who like to destroy the user experience and the overall look and feel?

I can choose here between dozens of themes, icon sets et cetera and the underlying OS cares about all that. So, to support the native Qt UI means to support this whole range of - like you call it yourself - very subjective issues - why force everybody to one interface?

**Comment by ideasman42** [comment]
> And why maintain this own interface, while Qt can do that for you?

This simplifies things by ensuring only a fixed number of themes need to be usable.
By following system UI, its quite possible someone loads OpenToonz and can't  see some part of the interface because of low contrast for example.

That can be fixed of course... just noting that supporting this comes at *some* cost.

**Comment by ShalokShalom** [comment]
You can set this fixed theme as the default option and give us the chance to use the internal theme. 

By the way: Your argument counts for 97% of all Qt apps - Windows and OS X use a defined theme (Aero/Aqua) and the open source operating systems test their theme before they apply it. 

Our system here is complete designed for Qt and KDE, each and every preinstalled GUI use this set of toolkits. Its the job of every packager and release manager of a distribution, to ensure that the themes fit.

With this attitude can you state 'i dont use any external package, since i dont know if the package maintainer of my app is sane'

**Comment by gab3d** [comment]
I do tend to favor standard looking UIs (i.e. I like them more) over non
standard ones.

Let's face it, in its current state, OT's interface looks (if anything)
like an "old" program. It reminds me to the short-lived Autodesk Toxik -
good functionality living under an ugly, old-looking and sometimes clumsy
interface...
Result: nobody liked it. Very few used it, even when it was finally free.
Program died.

I hope that's not the path of OT. :-/



2017-02-10 20:52 GMT-03:00 ShalokShalom <notifications@github.com>:

**Comment by turtletooth** [comment]
I just submitted a PR for an updated theme.  It still doesn't go native (see my preference above), but it is cleaner:

![theme_window](https://cloud.githubusercontent.com/assets/4576381/22999311/f2ac2432-f397-11e6-998d-55cab9a160fb.PNG)

![theme_style_with_change](https://cloud.githubusercontent.com/assets/4576381/22999316/f73a05aa-f397-11e6-9f36-b7cc672ed2e9.PNG)

![theme_cleanup](https://cloud.githubusercontent.com/assets/4576381/22999324/fdfa393c-f397-11e6-9666-fd06993be7e5.PNG)

![theme_output](https://cloud.githubusercontent.com/assets/4576381/22999326/00ffe4b0-f398-11e6-82eb-53a55f1b6c63.PNG)

Thanks to @konero for the input and basic look.  This is mostly his style with a few small tweaks.

**Comment by Shadoworker** [comment]
Can you guys show me how to setup OT with QtEditor please... I 'am trying since days but i 'am not making it .
