### ISSUE TITLE
[Qt] Fix Scrollbar BG, TabPage Underline, Palette Border (List Mode) and Move TPanel CloseButton to Stylesheet

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#754]
_@shun-iwasawa | In reference to #696 and #719._

We've been looking at reducing 'glare' on bright objects that take the focus away from the content. Since we use professionally calibrated displays users cannot alter the color for their preference.

The palette window contains all the issues, so we'll use this to example. Here is how it currently looks...

![elem](https://cloud.githubusercontent.com/assets/19820721/17928046/ccfa3a20-69f0-11e6-8d38-dc2caa806d29.png)

And this is what we're trying to do...

![elem_f](https://cloud.githubusercontent.com/assets/19820721/17928069/e38d160e-69f0-11e6-9c5d-67965c2d833b.png)

For our case, we're simply trying to push the UI to the back and make it as invisible as possible.

### What Are The Issues?

- [x]  **Scrollbar BG**
When there is no content to scroll or when there is it's only displayed on half the bar, the scrollbar displays a check board pattern, on our monitors which display a very sharp image, its a little awkward to look at and when you move your eyes across the screen it generates a '[moire](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern)' effect in vision.

![2](https://cloud.githubusercontent.com/assets/19820721/17928648/9e4f12d8-69f3-11e6-80a3-89ac11218439.PNG)

- [ ] **TPanel CloseButton**
It seems everyone is using floating windows a lot of the time, so there are bright blue close buttons all over the screen, is it a remnant of the old Harlequin titlebar?

![1](https://cloud.githubusercontent.com/assets/19820721/17928622/7ee4048a-69f3-11e6-97ef-4401b5887fdc.PNG)

- [ ] **TabPage Underline**
This is a strange one. We're able to style right/bottom/left sides of this element but not the top, could it be an alignment issue with another element? It's the 'underline' you see under tabs. We don't know whether it's to do with the body element under it (the color swatches) or the TabPage container.

![3](https://cloud.githubusercontent.com/assets/19820721/17928752/2ec14926-69f4-11e6-9083-87378a4ce7c2.PNG)

- [ ] **Palette (List View) Selected Swatch Border**
It's more obvious what's selected when the entire row BG is highlighted. Currently there is a strange outline, look at it close up...

![5](https://cloud.githubusercontent.com/assets/19820721/17928974/543921e6-69f5-11e6-837b-ff67b8abf2f1.PNG)

And compare...

![7](https://cloud.githubusercontent.com/assets/19820721/17928992/781b1466-69f5-11e6-9b7a-9a7feeea4cd3.PNG)

With...

![6](https://cloud.githubusercontent.com/assets/19820721/17928994/7b589a90-69f5-11e6-98f1-2e8d315af0ec.PNG)

### Final Word
Can we propose to move these elements into the stylesheets? This issue is not intended to be a replacement to the core UI but simply allow the user the option to configure.

Thanks, I appreciate the work done on TPanelTitle. :+1:

**Comment by turtletooth** [comment]
There are also some scroll buttons that seem to not be accessible in the styleshsheet.

**Comment by turtletooth** [comment]
I got the scroll bars working

**Comment by turtletooth** [comment]
I've got the scrollbars working well.
