### ISSUE TITLE
Translating UI into Spanish?

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz#76]
Hi,

My name is Gabriel Gazzán, and I'd like to translate Toonz UI into Spanish.
I'm currently the main translator for the UIs of Blender and Kdenlive and I think I could tackle this great new open sourced software too!
If anybody could tell me how and from where to update-my-local-repo / commit I would be grateful. (I'm used to work with SVN, not GIT, but I think it should be fairly easy too. I'm on Windows).

Thank you in advance.

**Comment by scribblemaniac** [comment]
First you'll want to fork this repository. The button to do that should be in the upper right corner of this webpage. You'll want to clone the new repository you made (gab3d/opentoonz). You'll make all you're updates, commit, and push to there. When you've finished the translating, you can use the web interface to make a pull request to here. That's the most basic setup, but it should be sufficient for your purposes.

I'm pretty sure this project uses Qt Linguist, and the files are all in `toonz/sources/translations`. You'll have to look up more information on how to use that on your own because I have no experience with it.

**Comment by gab3d** [comment]
Great!
Thank you!
Tha should be enough. :)

I've already downloaded and tested Qt Linguist with the italian translation file and it works OK.

**Comment by scribblemaniac** [comment]
No problem, good luck!

**Comment by ToonCo** [comment]
Por favor! Maneja el concepto de "frame" y "Keyframe" en lugar de "Fotograma" y "Fotograma clave"

**Comment by gab3d** [comment]
@ToonCo La idea es tratar de hacer una traducción completa de la interfaz.
Los conceptos se mantienen, diga Frame, Fotograma o Cuadro; Keyframe, Fotograma clave, Cuadro clave o Punta de animación. 
Creo que a veces es más un tema de que cada uno internamente siempre desea preservar lo que "tanto trabajo le costó" aprender. Es lógico, pero es interesante también pensar en los usuarios nuevos y especialmente en aquellos que quieren animar y no conocen otro idioma más que el español. Para ellos, tener una interfaz con términos que remitan a cosas que se puedan razonar y no a cosas que haya que aprender de memoria, es mucho más productivo.

Los profesionales, de todas formas, van a usar la interfaz en inglés y eso lo sabemos todos. ;)

Saludos!

p.s. Sorry for the Spanish in there. :-/

**Comment by NestorAntonio** [comment]
Hola Gabriel. Recientemente acabo de abrir una comunidad en español de OpenToonz, sería fantástico si pudieses compartir con nosotros algún avance en relación a la traducción de la interface. Saludos y gracias de antemano. 

OpenToonz - Comunidad en Español:
https://groups.google.com/forum/#!forum/open-toonz--comunidad-en-espaol

**Comment by gab3d** [comment]
@NestorAntonio 
Hola: 
Es una buena iniciativa! :)

Con respecto a la traducción, va viento en popa.
Si bien aún no he atacado el archivo más pesado, que contiene el grueso de las traducciones de la interfaz, los demás archivos vienen a buen ritmo y calculo que mañana o pasado quedarán listos.

El archivo principal, sí que va a llevar algunos días más, porque contiene bastantes cadenas de texto; de todas maneras, afortunadamente, Toonz parece ser bastante más chico que Blender (uno de los otros programas que traduzco), así que no creo que demore mucho completarlo y que podamos tenerlo andando en español. :)

Saludos!

**Comment by NestorAntonio** [comment]
Excelente! avisame si necesitas algo de ayuda. Claro, no conozco los aspectos técnicos pero tengo un buen dominio del inglés.

**Comment by mospina** [comment]
Hola, ¿alguien ha comenzado a traducir la documentación? Me gustaría participar

**Comment by gab3d** [comment]
@mospina 
Hola, no que yo sepa.
Sería muy bueno! :)
