### ISSUE TITLE
[feature idea] day and night theme

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#761]
I though of a cool idea with theming - its not really a must have - perhaps just for fun way to spoil the users.

During the day we tend to need a screen that emits more light - because our surrounding tends to be lit with natural light.
During night time we need the screen to emit less light - because light from it is then too tiring to the eyes.

So what if we had the ability to set a theme for daytime and one set for night time. Opentoonz when starting could check the computer's hardware clock and start with the day theme or the darker night theme.

**Comment by tGuMedia** [comment]
i'd rather not, i want to be able to stay in controll of whatever theme OT is using.

**Comment by blurymind** [comment]
you will stay in control :)
You can basically set the night and day themes to be any theme.
Also night theme could be optional - so if disabled OT could stay only at one theme

**Comment by ShalokShalom** [comment]
You can use Redshift for that.

**Comment by blurymind** [comment]
@ShalokShalom I know about redshift - unfortunately it will also shift the colors of your work

**Comment by ShalokShalom** [comment]
You can also switch the color temperature, its maybe possible to adjust that one in a way, that you are happy. :)
![screenshot_29082016_013545](https://cloud.githubusercontent.com/assets/6344099/18037598/f018b3ec-6d88-11e6-843d-76088fe2a71a.png)

**Comment by blurymind** [comment]
@ShalokShalom My suggestion is about making the software feel more alive - like the world around us - with a day and night mode reflected in the theme it starts with.
It's a for a second drop down menu in preferences that could enable that.

As noted - I already know about redshift, I like it too - but please note that redshift will tint the entire screen - not just the interface. So you will end up with a tinted color palette :)

**Comment by ShalokShalom** [comment]
> note that redshift will tint the entire screen - not just the interface.

Ah, ok. That makes sense.

+1

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
