### ISSUE TITLE
Proposal: New Startup Page before loading the Program

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#765]
I would like to propose a new window that opens before the main window for the purposes of:
- Allowing the user to choose between opening a previous scene and opening a new scene
- Presenting a list of previous scenes
- Allowing the user to name their new scene and choose its location
- Upon selecting a new scene, the new scene is saved immediately- this would allow autosave to be turned on by default and save in the correct location.

This is similar to what happens in Premiere, ToonBoom, DragonFrame

The downside would be one more step before jumping right in and animating, and that rough sketches that don't need to be saved would be an issue.  This window could be made optional in preferences, but I would like to see it on by default.

**Comment by blurymind** [comment]
good idea! I think for the downside - blender is an example of this being done well - where if you click away, you close the startup dialog and are back to the default empty scene where you can start working on new stuff

**Comment by turtletooth** [comment]
Yeah- I realized that I could make it that if you close the popup or click away it would have the default behavior.  I will see if I can build something this weekend.

**Comment by PsmithG** [comment]
Please - no startup pages.  All this does is slow down the opening of the application and irritate users.  Only a small segment of the audience will find this useful or entertaining.

One thing that sets apart OpenToonz from all the rest is its speed and its small download size.

Don't we wait long enough for everything we attempt to do using a personal computer?

Now, you propose to make us wait even longer?

Some of us are running out of that trivial commodity called "Time".

As a compromise - please allow this to be a toggle - available from within the Preferences for OpenToonz - "Opening Screen - OFF, ON".  Do not, if you value my friendship, make this a default setting.

Greg Smith

**Comment by blurymind** [comment]
I disagree, a start up page on the contrary can reduce the number of clicks needed to get back to an existing project - just by having a list of recently opened files you can click on.

It can also be optional (add tick box to not show startup to preferences), so people like @PsmithG don't have anything to complain about :)

**Comment by turtletooth** [comment]
Here is the window I'm about to submit a PR for:
![newstartup](https://cloud.githubusercontent.com/assets/4576381/18300652/503482be-7488-11e6-9472-8e4c45e3298f.jpg)

**Comment by RodneyBaker** [comment]
@turtletooth Thanks for your efforts to streamline project management.
I think Rayek asked a few pertinent questions over in the Pull Request related to this.

My question would be how to proceed if I didn't want to start a new project/scene but also didn't see the project/scene I wanted to open in the recent files listing.  In answering myself I will guess that I'd simply close this dialogue and use the File menu to open the scene.  Please correct me if wrong.

**Comment by blurymind** [comment]
A simple tickbox to optionally disable the startup window should solve all
doubt :)

**Comment by RodneyBaker** [comment]
> A simple tickbox to optionally disable the startup window should solve all
> doubt :)

I see he's already got that covered with the tickmark that says 'Don't show this again.'  That's always a good option to have.  Some programs have the tickbox on by default with the words like "Show this menu on startup".  That might be more appropriate as tickmarks generally turn things on and not off. (?)  Then if the user turns the startup menu off they have to turn it back on in the preferences or open it via the Help menu.

Another question that will answer itself when we get to try this out is how the listing handles paths and files that are wider than the field.  I find myself wondering if those listings will be truncated, wrap or something else if too long.  We'll see soon enough.  :)

**Comment by blurymind** [comment]
use pixels as the default unity in Opentoonz - does that set the default unit to be pixels or does it simply create a new project with the unit set to pixels :)

**Comment by turtletooth** [comment]
>  does that set the default unit to be pixels or does it simply create a new project with the unit set to pixels :)
It actually turns on pixels only mode in the settings.  There isn't currently a way to have an individual scene have its own settings.

**Comment by turtletooth** [comment]
Here's the new UI that takes care of most of the problems mentioned.  I just need to double check it and I will submit.
![newstartup](https://cloud.githubusercontent.com/assets/4576381/18324043/c098a926-74f7-11e6-9c98-1277c996fa38.png)
