### ISSUE TITLE
Files with name_number.ext format crash on load if not an image sequence

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#767]
Files with a name of mygif_0001.gif, mymp4_0001.mp4 crash OT when attempting to load.  

It doesn't see it as an individual file, but part of an image sequence.  Renaming the file works.  But I need to tell opentoonz not to attempt to load video files as an image sequence, no matter how it is named.

Most videos off of a camcorder/camera have a naming convention like this, and this would cause issues.

**Comment by konero** [comment]
I thought OpenToonz had a way of adding your own file formats using regex, but I haven't been able to get it to work, unless I misunderstand this option. (#644)

So I assume no matter what OpenToonz is hard-coded to recognize `*0001.*`?

As opposed to `*0001.tga/jpg/png/exr` so it won't affect `gif/mp4`.

**Comment by turtletooth** [comment]
I'm not sure what's happening in the code yet.  I just know that trying to load a mp4 named x_0234.mp4 crashes OT because it is searching for a image sequence.  

I will make sure my fix only affects mp4, webm and gif files and doesn't affect the workflow for other image formats.
