### ISSUE TITLE
Bone Rig with onion skin on goes crazy after modifying a few frames

### ISSUE THREAD

**Issue by NuxGamedev** [opentoonz/opentoonz#768]
As the title implies. After I modify a bone using the Inverse Kinematics setting on the Bone Tool, the next few frames of my animation start going crazy, often rotating and moving out of its previous position. Probably a bug, hopefully will be fixed.

**Comment by turtletooth** [comment]
Can you give more detail or steps to reproduce the bug?

**Comment by jpturcotte** [comment]
@NuxGamedev Can you provide an update, please? Else, recommend closing.
