### ISSUE TITLE
ffmpeg export to mp4 issue

### ISSUE THREAD

**Issue by tjoen** [opentoonz/opentoonz#779]
I noticed that if I render to mp4 and I DON'T start the render at keyframe 1 to 4, the finalizing progressbar does NOT appear, and the file just gets deleted, It does make the tempfile and the png's while rendering, but at the end, the png's and the mp4 get deleted,

It seems to happens with several ffmpeg builds I tried.
Rendering the whole movie from one of the first four keyframes does work.

I'm on windows 10 with OT 1.1.1

**Comment by turtletooth** [comment]
I'll look into it.  Thanks for pointing that out.

**Comment by turtletooth** [comment]
Fixed in #828.  Thanks @tjoen for pointing it out.
