### ISSUE TITLE
Bug:  Version 1.1.1 Mac - Plastic Tool Set is Still Completely Broken and Unusable.

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#780]
As of the Nightly Build, c6e7000, The Plastic Tool is completely broken on the Mac version.

When the user creates a vector shape, selects the Plastic Tool from the Tool Panel - and then clicks "Create Mesh" - the software produces a rectangular "blanket" of triangles surrounding the desired shape.

This cannot be used, since the Plastic Nodes distort the entire blanket - ignoring the boundaries of the shape, itself.  Working this way produces an uncontrollable result - thus rendering all of the Plastic Tool functions unusable.

How can the developers ignore this for so long?  

Plastic is one of the best innovations that is found in OpenToonz.  Without it, OpenToonz is just a good frame by frame animation tool set (with simple CutOut tools).

Please support the Mac platform.

Greg Smith

**Comment by PsmithG** [comment]
It looks like it is the Plastic Mesh display only, now, which is a detriment to the Plastic Tool Set on Mac, as of the Nightly Build   e7667a0.

Though the display does not follow the vector shape boundaries, it still functions properly.

Greg Smith

**Comment by Rayek** [comment]
I wonder why the Mac platform is proving to be such a hassle - could it have something to do with Apple deprecating the older OpenGL functionality?

**Comment by falls2lawrence** [comment]
from the start, the plastic tool has worked in the app with a few workarounds regarding the rectangular mesh.
1) raster levels make normal meshes (not a rectangle), so copy your vector shapes from your vector level and paste them into a raster level, create your mesh for that raster level, and then parent the original vector level to the newly created mesh level.

orrrrrr as of recently I've notice

2)collapse your vector level/levels into a subsheet and make a mesh from that....... it works and it's easy.

**Comment by artisteacher** [comment]
Using the sub-x-sheet looks great, until previewing or rendering video!

**Comment by opntnzcmmntr** [comment]
falls2lawrence's solution works for me.  istill get a blue background on export though.

**Comment by artisteacher** [comment]
It looks like the plastic tool (on a single vector level) when making the plastic mesh (like several of the special styles) ignores the vector parametric coordinates and uses the parameters of the bounding box instead. 

On OS X 10.12.3, I now get the blue background when previewing/rendering.  On computers with 10.11.6, the background still has the transparency issue with strange fragmentation which so far cannot be keyed out in the fx.

**Comment by artisteacher** [comment]
This is resolved, recommend closing.
