### ISSUE TITLE
Typo: lenght

### ISSUE THREAD

**Issue by mcccs** [opentoonz/opentoonz#787]
Where? [Here, here, here...](https://github.com/opentoonz/opentoonz/search?q=lenght&type=Code)

So you want to change them with what? [These](https://github.com/opentoonz/opentoonz/search?q=length&type=Code)

If you confirm, I can open a Pull Request.

**Comment by RodneyBaker** [comment]
A few more typos...

Looking at @mcccs search results I see another typo with 14 occurrences.
The typo'd word is 'simmetric' which should be 'symmetric'.
It is often preceded with with another word such as 'Not_' or appended with 'index'.

There are 174 instances of the correctly spelled 'symmetric'.

https://github.com/opentoonz/opentoonz/search?p=2&q=simmetric&type=Code&utf8=%E2%9C%93
