### ISSUE TITLE
Modern color whele

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#791]
**UPDATE**

[Coolorus](https://coolorus.com/) is a color wheel plugin for Adobe Photoshop:

![cooloruse color wheel](https://cloud.githubusercontent.com/assets/16509592/24871113/1b67459c-1e08-11e7-99b8-4a866e16f49d.png)

TVPaint Color whele:

![tvpaint_colorwheel](https://cloud.githubusercontent.com/assets/16509592/24871217/6b04d4de-1e08-11e7-9753-b7ba2f5e42c8.png)

Toon Boom Color picker:

![toonboom_colour_picker](https://cloud.githubusercontent.com/assets/16509592/24871419/0a32e6c2-1e09-11e7-8f2e-6dd725db183a.png)

In krita you can Choose Color wheel like this:

![screenshot from 2016-09-05](https://cloud.githubusercontent.com/assets/16509592/18250979/ba0033a2-739b-11e6-9370-67863f5e23a0.png)

MyPaint:
![mypaint-color](https://cloud.githubusercontent.com/assets/16509592/25784831/5b467e42-3363-11e7-8b9f-c93d7a7b441d.gif)

**Comment by turtletooth** [comment]
![color_wheel](https://cloud.githubusercontent.com/assets/4576381/22915768/ced3fa7e-f236-11e6-9316-129feac861b9.JPG)

I found this hanging out in the code.  You can change the modes between R, G, B, H, S and V.  I think it would be neat to have the option of which one to use.

**Comment by turtletooth** [comment]
@artisteacher What do you think?

**Comment by artisteacher** [comment]
I think having options is always a good thing. I'm all for it!

**Comment by ideasman42** [comment]
[Options don't come for free](http://enterprise-dashboard.com/img/cockpit-dashboard.jpg), more buttons for users, more code for devs to maintain - am not really against, just there *is* some cost in adding options and spending some of the [complexity budget](http://scattered-thoughts.net/blog/2015/10/25/complexity-budgets/).

**Comment by artisteacher** [comment]
Good point. I definitely wouldn't add all of the options displayed in the example - the style editor is certainly complex enough. I do still think adding the regressed mode back in could be helpful.

**Comment by 2dvision** [comment]
In [Toonz](http://www.toonz.jp/) we have a nice color selector, Can we have it in OpenToonz?

![](http://www.toonz.jp/images/immagini%20interfaccia%20Toonz/o1.png)

**Comment by turtletooth** [comment]
The one in Toonz is the one I uncovered last night.  The UI needs some tweaking, but it's the same functionality.  

I was playing with it last night and I think the hex shaped one we have now is actually more usable.  Bringing the old one back as an option wouldn't be hard, but will it actually make the program more functional?  

I agree with @ideasman42 - I don't want to add features just because I can, but don't mind if it actually adds value to the program.

**Comment by artisteacher** [comment]
What appeals to me in the old color selector is the size. I like the hexagon, but wish it took up more space horizontally. There can be a lot of wasted space on the sides of the hexagon color picker - dependent on how much space you can afford to give the style editor & how many of the options are active.
![image](https://cloud.githubusercontent.com/assets/21159116/22954112/a344e448-f2e2-11e6-841c-e7340e987934.jpeg)
I think what would be most helpful would be making the use of space in the style editor as efficient as possible. .

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
