### ISSUE TITLE
Feature: Provide a Way to Hide "Plastic" Node Connecting Lines - Color Code Nodes Instead

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#792]
Working with Plastic Tools in OpenToonz is really rewarding and quick - once you master the basic techniques.

To new learners, they become something that looks very complicated and incomprehensible - because of the resulting network of lines between the Nodes.

Please, consider providing an option which allows the user to Hide any or all connecting lines (alt-left click on lines to hide).  A command could be placed in the Right-Click menu to "unhide" all lines.

To make Node Control recognizable under the circumstance of hidden connecting lines - provide a means to associate any Node with the Region or Object that it influences.  A simple command like "Show Influence" would toggle these associations (Colors) On or Off while animating - thus making the Influence of every Node recognizable.

Thank You,

Greg Smith

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
