### ISSUE TITLE
[Enhancement] Flag "Premultiply" by default when importing 32bit transparent PNG (and TGA?) files

### ISSUE THREAD

**Issue by Rayek** [opentoonz/opentoonz#794]
Currently semi-transparent pixels in 32bit PNG files are not premultiplied by default, and the user must open the level settings to turn this on. It is quite confusing to new users, and requires extra unnecessary clicks.

I would like to suggest that this level settings is automatically flagged (activated) when placing 32bit (semi) transparent PNG files (and perhaps for other file types such as TGA as well).

**Comment by artisteacher** [comment]
I agree, having premultiply on by default for pngs, gifs, and psd layers would be really helpful. My students always think something is wrong with the image - or with OpenToonz when they see the white border around a drawing that they have loaded from Photoshop or etc.

**Comment by turtletooth** [comment]
I don't fullly understand premultiplied, but thanks to a recent PR by @shun-iwasawa I know how to implement this.  Should this only be applied to 32bit pngs?  or all pngs?  psds are already implemented.
