### ISSUE TITLE
Usability Bugs : Confusing Default Room Layouts

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#80]
The default layouts that the software comes with are confusing and hiding vital features by default. Many people are scratching their heads over how to use it.

Some people have come up with solutions:
https://vimeo.com/160517233

So I believe that request number one is to have the DEFAULT toonz harlequin room included in opentoonz layouts.

I know that Toonz harlequin had room editing (creation of new room, deletion of existing room) exposed to the gui. Opentoonz does not - So I guess my second feature request is to bring this back  to opentoonz, so people dont have to dig through folders and use a text editor to do it.

shortcuts.ini is empty - we need to create a proper default one! :) The one that toonz harlequin used to have at least could have been preserved.

I know that this is all just polish, but remember that a lot of the end users are not programmers or just plain lazy and their first impressions will be confusion

**Comment by blurymind** [comment]
Here are the default layouts of Toonz Harlequin - for anyone who would like to use them instead
[OpenToonz.harlequin.zip](https://github.com/opentoonz/opentoonz/files/191808/OpenToonz.harlequin.zip)

They make much more sense to new users!

**Comment by blurymind** [comment]
I made a few tweaks to the 'drawing' and 'ptedit' rooms. I also added The cleanup (scanning) and xsheet rooms from the original ghibli setup.
I added a viewer to the xsheet room.

Here is the updated version of my room setup:
[OpenToonz.betterRoomsLayout-ver1.zip](https://github.com/opentoonz/opentoonz/files/192301/OpenToonz.betterRoomsLayout-ver1.zip)

**Comment by blurymind** [comment]
I made a few tweaks to the 'drawing' and 'ptedit' rooms. I also added The cleanup (scanning) and xsheet rooms from the original ghibli setup.
I added a viewer to the xsheet room.

Here is the updated version of my room setup:
[OpenToonz.betterRoomsLayout-ver1.zip](https://github.com/opentoonz/opentoonz/files/192301/OpenToonz.betterRoomsLayout-ver1.zip)

**Comment by blurymind** [comment]
On default shortcuts - I have started adding some!
https://docs.google.com/spreadsheets/d/1-taUohoRrFXnaNUcey8fvu3LKaFmDToydxga-jqBJy0/edit?usp=sharing

This is the progress so far:
[shortcuts.zip](https://github.com/opentoonz/opentoonz/files/192349/shortcuts.zip)

I will see if I can merge harlequin's default keyboard layout into it.

**Comment by blurymind** [comment]
On default shortcuts - I have started adding some!
This is the progress so far:
[shortcuts.zip](https://github.com/opentoonz/opentoonz/files/192392/shortcuts.zip)

- I merged harlequin's default keyboard layout into it. I also added a number of much needed ones!

- Added delete key to the delete command. This solves this bug:
https://github.com/opentoonz/opentoonz/issues/82

- Added a shortcut to go to next and previous drawings / frames

- Added shortcut  for panning and rotating and zooming the canvas, this solves this bug:
https://github.com/opentoonz/opentoonz/issues/83

`
[shortcuts]
MI_NextDrawing=Shift+X
MI_PrevDrawing=Shift+Z
A_ToolOption_AutoSelect%3APegbar=
MI_NextFrame=Shift+S
MI_PrevFrame=Shift+A
T_Hand=Space
T_Rotate=Ctrl+Space
T_Zoom=Shift+Space
A_ToolOption_FrameRange=F6
A_ToolOption_SegmentInk=F8
A_ToolOption_Selective=F7
A_ToolOption_Type%3ARectangular=F5
MI_BringForward=[
MI_BringToFront=Ctrl+]
MI_Clear=Del
MI_Duplicate=D
MI_Group=Ctrl+G
MI_OpacityCheck=1
MI_SendBack=Ctrl+[
MI_SendBackward=]
T_ActualPixelSize=N
T_Brush=B
T_ControlPointEditor=C
T_Edit=E
T_Eraser=A
T_Fill=F
T_Geometric=G
T_Pinch=P
T_StylePicker=K
T_Tape=T
T_Type=Y
T_ZoomReset=0
T_Zoomin="="
T_Zoomout=-

`

**Comment by m48** [comment]
Here are screenshots of the layouts, if anyone wants to evaluate them without installing them:

- [Clean](https://cloud.githubusercontent.com/assets/7158216/14099030/c72e3e18-f536-11e5-864e-032fce3229bd.png)
- [Drawing](https://cloud.githubusercontent.com/assets/7158216/14099043/ebe7a154-f536-11e5-999b-bae35bd72029.png)
- [Animation](https://cloud.githubusercontent.com/assets/7158216/14099044/ebfd82e4-f536-11e5-8e7e-951beab9596f.png)
- [Pltedit](https://cloud.githubusercontent.com/assets/7158216/14099045/ec109776-f536-11e5-8251-8197e6200a40.png)
- [Xsheet](https://cloud.githubusercontent.com/assets/7158216/14099046/ec13f952-f536-11e5-80b0-3ab36633a5a1.png)
- [Browser](https://cloud.githubusercontent.com/assets/7158216/14099047/ec17825c-f536-11e5-8550-54fd51fb78b0.png)
- [Farm](https://cloud.githubusercontent.com/assets/7158216/14099048/ec1a0eb4-f536-11e5-869c-8388eafd7350.png)

How set are these on being used as the new defaults?

Also, this seems like a good place to mention this: on Windows, and *only* on Windows, the [menu bar has different options based on hardcoded room names.](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/menubar.cpp#L65) This is why the "Drawing," "Animation," "Pltedit," and "Farm" rooms in this layout have a menubar that offers every option in the program—because their names don't match the hardcoded ones. 

Any thoughts on whether this is a problem worth addressing? I personally think it's a bit counterintuitive that the menubar is changing constantly, and that customizing the rooms breaks this functionality, but some people might like not having to deal with every option at once.

**Comment by blurymind** [comment]
There is some wasted space on this flipbook in the drawing window. I dont know why, but toonz makes it wider every time the application is restarted. Could this be a bug?

**Comment by blurymind** [comment]
On the layouts - these are the ones that harlequin toonz uses - i modified them a little to have more canvas space.

**Comment by odysseywestra** [comment]
@blurymind could you provide those layouts on the google groups forum. It probably be a great help to those learning about opentoonz. Plus it might help prevent duplicates bug reports.

**Comment by blurymind** [comment]
@odysseywestra already did. The forum is a mess btw - as it has no categories and people create new threads like crazy at the moment. It is hard to find anything.

**Comment by blurymind** [comment]
I updated the room layouts. It is now slightly better:
[OpenToonz.betterRoomsLayout-ver2.zip](https://github.com/opentoonz/opentoonz/files/194081/OpenToonz.betterRoomsLayout-ver2.zip)
- the autokey button in the animation room was hidden by default, now it is visible
- The first room when the software is opened is now the cleanup room
- added the film strip window to the animation room - as i found out that it is necessary to have it next to the x-sheet for dragging drawings from it onto levels in the xsheet.

I also discovered a GUI bug in the film strip window. If you close opentoonz while in a room where the film strip window is docked, next time you open opentoonz, the filmstrip is 2 times wider and is wasing screen estate. See  https://cloud.githubusercontent.com/assets/7158216/14099043/ebe7a154-f536-11e5-999b-bae35bd72029.png

**Comment by geloescht** [comment]
Wouldn't it be better to actually create some rooms that are not based on original files from Harlequin? IMO, for copyright reasons anything that's not explicitly open-sourced does not belong into a open-source repository. Veterans and people who like the layouts from Harlequin can still use them. It shouldn't be too hard to come up with some sensible defaults without looking at those files from Harlequin.

**Comment by blurymind** [comment]
They are based on, but not exactly the same :)
I think the best approach would be to put what makes the most sense. Right
now we have something that doesnt make much sense at all. It is not suited
for welcoming new users either.

**Comment by AnimatorDave** [comment]
Hello I'm an animator struggling with shortcuts, specifically Tool Modifiers.
I've been trying to set  a which a consider a vital shortcut,  the "increase or "decrease" Brush size.
And even though it changes in the shortcut editor window, if does not function at all while using the Brush Tools. Do you think it could be fixed ?.

**Comment by blurymind** [comment]
@AnimatorDave > I can look into it. What shortcuts do you use to increase and decrease your brush size?

Btw someone made a tutorial on how to install the room layouts in this thread:
https://youtu.be/jPhpUUL1aCE?t=3m9s

**Comment by blurymind** [comment]
Unsurprisingly people at newgrounds found the default ui setup very confusing
http://www.newgrounds.com/bbs/topic/1406896/5

The other big complain was saving your progress. I opened another bug report for that

**Comment by shun-iwasawa** [comment]
Editing rooms feature was reverted & merged.

**Comment by blurymind** [comment]
@shun-iwasawa thank you! 
Will you consider including more user friendly default layouts to opentoonz stuff folder?

It's not a big problem for me as it is atm, because I can just paste them whenever i install a new version of OT. But it might help make the software more user friendly for new users - easier for them to discover it's features.

**Comment by turtletooth** [comment]
I'm going to post this in two places to get some feedback: What do you think of a toggle in preferences that will let you choose between the Studio Ghibli rooms and the standard rooms?  That way the folks who brought this amazing product open source don't lose the layouts they are used to, but the folks who are new to OT have a better chance of catching on.  I think the default rooms should be the standard rooms, but I want to hear from other folks.  I will start looking in the code for the best place to add it.

**Comment by blurymind** [comment]
@turtletooth Toonz harlequin used the same menus in all rooms. I sat down and created a setup that can revert the old room menus from harlequin, while also adding the new toonz ghibli added features:
[room1_menubar.zip](https://github.com/opentoonz/opentoonz/files/294019/room1_menubar.zip)

To revert the default toonz harlequin menu layout, just use this menubar for all the rooms. You are of course free to further edit it and remove some of the entries on some of the rooms. That is something I am doing myself on further edits.

The toggle is awesome. Thank you for this pull request. It will make open toonz much more user friendly.
