### ISSUE TITLE
Please Provide A Way to Make Selected Nodes of Polyline Smooth

### ISSUE THREAD

**Issue by Motogpmania48** [opentoonz/opentoonz#801]
I have a suggestion for the developer,, Please add a feature to make selected nodes of polyline smooth , like Inkscape has. It would make drawing more clean, smooth, and fun. Thank you very much in advance.
![polyline smooth](https://cloud.githubusercontent.com/assets/22128395/18416156/fffda95e-7835-11e6-9832-f6cc930b71d3.jpg)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
