### ISSUE TITLE
Change position "Preferences..." and "Configure Shortcuts.." from File menu to Edit menu

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#802]
I think these are edit function, And file menu becomes thinner.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
