### ISSUE TITLE
Feature: Protect color in palette

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#807]
By right click on a color and choose "Protect color", this color will be Protected and is not possible to change it.

**Comment by blurymind** [comment]
you can lock the entire palette already, but this would give more granular control

**Comment by blurymind** [comment]
Instead of adding minor features, how about fixing a huge regressions that makes life very difficult 
https://github.com/opentoonz/opentoonz/issues/520

:)

**Comment by RodneyBaker** [comment]
Nice suggestion.  It would be useful to be able to lock settings down and know they won't change.

I like the descriptive words "Protect Color" but with regard to being able to lock down other settings in the software in the future wonder if such as setting might simply be named "Lock".  This would aid later with scripting too as only a short word would need to be used as 'Locked' also technically will allow for 'read only' access.  I suppose that could be what is going on underneath the scenes with "Protect Color" but for the programmers it might represent an additional layer of complexity.

Workflow-wise I do find myself wondering what the UX will be when a user encounters a locked style and doesn't immediately realize they can easily release it.

#blurymind said:

> Instead of adding minor features, how about fixing a huge regressions that makes life very difficult 
> #520 

I know yours was mostly a rhetorical question but...   :)
Assigning priorities is largely in the eye of the beholder and may I say, largely the choice of the programmer who will champion that feature but I can think of several reasons why minor features can rise to the top and perhaps should do so.  One would be that in the process of implementing the minor feature programmers get familiar with the code that surrounds the huge and very difficult ones that may break other things if not more carefully considered.

Another might be that regressions may be best handled by programmers with more thorough knowledge and understanding of that regression as well as ready access to the code of that earlier implementation.

**Comment by blurymind** [comment]
I guess the problem is that the regression is very difficult to fix.
@turtletooth gave it a shot a while ago and failed

But it is a fundamental feature that is missing at the moment
I am mentioning this now in case that the fix requires a refactor that
might break minor features that are being added on top at the moment

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
