### ISSUE TITLE
Feature: Select object by "select with the current color"

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#808]
if user right click on a color and choose "select with the current color", every object drawing by this color will be selected.

**Comment by blurymind** [comment]
I was going to ask for the same thing, but then I found out that you can already select by style already

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
@2dvision This is a review of... in this case very old... feature requests.

A few assumptions here regarding this feature set:
- This feature would be for vector levels only (how best to implement given other level types)
- The Right Click menu for color styles would gain the current capability of Selection Tool options to select objects/strokes with specific colors.  It isn't entirely clear what options would be made available but the assumption would be that users would likely want access to as many as possible.

![image](https://user-images.githubusercontent.com/2576432/154768581-ce5269f3-fad4-4adf-9005-7f4f3435fe27.png)

I'm adding the workaround label as we can get the results of the proposed feature but with the additional use of Selection Tool and dropdown menu options.
