### ISSUE TITLE
[Feature] Plugin system

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#809]
Ability to add additional functionality and GUI to the software without need to recompile it - via a plugins system similar to the one found in blender.

Ability to install and remove  plugins that touch upon different parts of the workflow.

OT already has a basic scripting system, but it is extremely limited and not very useful atm.

Ideally the plugin system would use an easy to pick up language like python - this is something that Krita is adopting for their plugin system as well at the moment.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
