### ISSUE TITLE
[UI] New Viewer Icons

### ISSUE THREAD

**Issue by konero** [opentoonz/opentoonz#810]
### Update to V2

After some feedback, I made some alterations to some of the icons. If these icons are used, please use the pack labelled V2 below.

These are new icons for buttons that appear in the Viewer, Combo Viewer and Flipbook.

**Original**

![original_viewericons](https://cloud.githubusercontent.com/assets/19820721/18482897/e174ac62-79d9-11e6-85ec-a221cf04d7f5.png)

**New** _(superseded)_

![new_viewericons](https://cloud.githubusercontent.com/assets/19820721/18482962/256a70c8-79da-11e6-898a-da0eaa5f8ac1.png)

**New (V2)**

![newv2_viewericons](https://cloud.githubusercontent.com/assets/19820721/18554204/5cfeae0a-7b5b-11e6-8cbc-2705b1cee7f3.png)

ZIP contains **SVG** and **16px PNG**.

**Comment by blurymind** [comment]
These are much better, much clearer!
Thank you
