### ISSUE TITLE
Show frame length of GIF / MP4 files in File Browser

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#811]
For now the frame length of GIF/MP4 files are always displayed as "1" in File Browser.
Showing correct frame length of them will be helpful.

**Comment by turtletooth** [comment]
Also applies to webm videos.

**Comment by turtletooth** [comment]
@shun-iwasawa I will delete this comment tonight- but I wanted to ask again- Is there any chance of getting the project roots change accepted into OT?  Right now I am trying to make all my changes work on both OpenToonz and MotionMonster but I don't have as much time as I did over the summer and will have to dedicate more time to one code base.  I would prefer not to even need MotionMonster, but for my classroom it is necessary to have all project files stored in my documents folder.

**Comment by shun-iwasawa** [comment]
@turtletooth Sorry for not being enabled to respond your latest update of #664. I understood your situation and will review it with the first priority. Could you please reopen it or post another PR for this?

Meanwhile, it is much appreciated if you could briefly review my PRs such as #764, #782 etc..

**Comment by turtletooth** [comment]
@shun-iwasawa 
I have already started looking at #782.  Thank you for considering my situation.
