### ISSUE TITLE
(FEATURE) Requesting a sub-option with the Pinch Tool to modify ONLY the ends of a line, or the middle of the line.

### ISSUE THREAD

**Issue by NuxGamedev** [opentoonz/opentoonz#816]
As the title says. Whenever I use the Pinch Tool to extend or drag over an end portion of a line in Vector, it often grabs the part just BEFORE the end, and it often the ruined part of the line caused by the mishap Pinch, ending with me removing the section altogether with the Cutter Tool, and even then it sometimes bugs out. 

Requesting for a sub-option for the Pinch Tool, to only select either the ends, or the middle, hopefully with varying degrees of strength on the point of origin for the pinch (ie. a slider on how strong I can change a line, using the Pinch Tool.)

Thank you so much for the work being done on OpenToonz. Bugs aside, it's been working phenomenally!

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
