### ISSUE TITLE
Feature:  Provide a Raster Smear or Smudge or Blend Brush

### ISSUE THREAD

**Issue by PsmithG** [opentoonz/opentoonz#818]
Many more varieties of environments, paintings and characters can be created, far more quickly and stylistically, with the aid of a Raster Brush which smears, smudges or blends the colors and textures of an image created in OpenToonz.

Could we please have such a Brush?

Thank you,

Greg Smith

**Comment by turtletooth** [comment]
I think if the MyPaint brushes are added - that will take care of this request.  The bounty is currently at $95 out of $150

**Comment by blurymind** [comment]
@PsmithG  here is the proposal for mypaint brush lib
https://github.com/opentoonz/opentoonz/issues/417
You will find the bounty page there

**Comment by turtletooth** [comment]
I'm going to close this since it will be added when the MyPaint brushes are added.
