### ISSUE TITLE
Feature: navigator (mini map) for Schematic window

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#819]
Toon boom harmony network window:

![har11_network_view_navigator](https://cloud.githubusercontent.com/assets/16509592/18608888/74184870-7d0a-11e6-9f98-ca76c2469c39.png)

Ability to:
- show/hide
- change position (Top Left, Top Right, etc)
- Change size (1x, 2x, etc)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
