### ISSUE TITLE
Is QuickTime export still needed on Windows?

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#822]
QuickTime on Windows is a security risk (yes I know that if you don't install the player, it is supposedly fine, but how many people actually know/do that?)  OpenToonz now has other options for video export. Is QuickTime still needed?  I don't use it personally and don't care if it stays or goes except that there have been several bugs over the time OT has been out related to the QuickTime component and often the solution has been deleting/renaming t32bitsrv.exe

**Comment by Rayek** [comment]
My answer: the death of QuickTime on Windows is long, LONG overdue. It is insecure, unstable on newer systems, and no longer supported by Apple. 32bit only. A relic from the nineties.

I say: kill it, bury it, and forget about it.

**Comment by RodneyBaker** [comment]
I'm not a fan of less options (under the hood) although I generally prefer
less on the menu side of things (as too many options can make picking one
format harder to choose).
Practically speaking any format probably shouldn't disappear until a better
format is readily available and although I know several should be appearing
with the next official release of OpenToonz they aren't in the wild yet.

It would make it easier if the removal of a format like .MOV coincided with
the introduction of another format that made it easy for the user to let it
go.
That could be MPEG but I'm not sure that quite fits the bill as a
replacement format.
It's more of another option.
.

**Comment by RodneyBaker** [comment]
I thought of another reason not to jettison the MOV format...

While there might come a proper time to remove the MOV format for use with rendering. MOV files that have already been created in the past (in Toonz or elsewhere( and those still being created will very likely be grabbed by users with a desire to import them into OpenToonz.  If the format isn't there an extra conversion step will have to take place (outside of OpenToonz) to get the MOV file into a format that can be imported.

**Comment by Amadhia** [comment]
If there were an MP4 format with default settings that would have ultra-minimal artifacting, I could part ways with QuickTime on Windows.

(I do prefer QuickTime to AVI, personally.)

**Comment by RodneyBaker** [comment]
@Amadhia Good news!  There is now MP4 support via FFMPEG (which needs to be
downloaded separately).
In the preferences on the Import/Export tab point OpenToonz to the
directory where FFMPEG is located (C:\Program Files\ffmpeg\bin on my
computer) and away we go.  :)

**Comment by Amadhia** [comment]
Oh, that's awesome!  Thanks so much for the info! :)
