### ISSUE TITLE
32 bit Windows version?

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#823]
I noticed that there have been a handful of requests on the Google Group for a 32 bit version.  I thought I would take a look.  I managed to get it to compile by ripping QuickTime out, but it errors on running.  Is  there any interest in supporting 32bit?  It would help make OpenToonz a more accessible program although most machines are 64bit nowadays.  

If anyone wants to take a look, I have a 32 bit branch in my fork that compiles, but doesn't run.

**Comment by RodneyBaker** [comment]
There is definitely interest in a 32bit release even if it's missing a lot of the bells and whistles of the full (64bit) release.  I've fielded several of these quesiton in the OpenToonz forum and recently saw a need for 32bit flavored OpenToonz myself.

An example of this is an older laptop I recently acquired.  There is a limit to what that laptop can be used for but it would be nice to be able to launch OpenToonz... draw images... organize projects... setup xsheets... convert from raster to vector... clean up... adjust color palettes... things that should be appropriate for 32bit machines with limited memory.  And that last part is the element that I think encourages us all to move toward 64bit.  The limited amount of memory available via 32bit is a constraint that we should all be more than will to put aside in favor of accessing better performance via 64bit.  But then the quesiton remains... what to do with those older computers that could be put into service using OpenToonz *if* it could run on a 32bit platform.

I"ll be checking out your 32bit branch... although there isn't much hope for me understanding why it's not running.  Thanks for giving 32bit a try and making it available.

**Comment by konero** [comment]
Just my opinion, but I'd say there's no need, it's such a small denominator to worry about. Is it really worth putting the resources into another edition when the only one available for porting still has a lot of kinks and bugs?

There is a plethora of animation software out there these days, both free and affordable, so home users on very old computers or tablets shouldn't feel left out.

**Comment by Eweie** [comment]
most machines can run a 64 bit OS but that doesn't mean they do, there are several reasons why an individual or organization would chose or need to run a 32bit os. so yes there is a need for 32 bit version.

**Comment by turtletooth** [comment]
Closing

**Comment by morevnaproject** [comment]
32bit builds for Windows are available on our website now - https://morevnaproject.org/2017/06/05/opentoonz-32bit-available-download/

**Comment by RodneyBaker** [comment]
@morevnaproject   Thanks for the 32bit build.  That is sure to be useful, especially on systems that don't support 64bit.
