### ISSUE TITLE
(BUG)Rearranging Windows does not work / does not refresh the Style Editor Window

### ISSUE THREAD

**Issue by Dragularos** [opentoonz/opentoonz#825]
Hi folks,

I've made a video you can get here to describe the problem ...

https://dl.dropboxusercontent.com/u/85554828/StrangeWindowBehaviour.mp4

... a video is worth more than thousand words :)

I guess it's a Mac specific problem but since it hasn't been solved since the beginning of OT i keep on posting about it ;)

Have a good time animating,

Thanx, Phil

**Comment by turtletooth** [comment]
Video is missing.  Closing for now.  I'll reopen if needed.
