### ISSUE TITLE
Investigation:  Feasibility of adding MOX format to OpenToonz

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#829]
I've convinced myself the MOX format would be an ideal format for use with OpenToonz and as such I'd like to explore that possibility further.  I've posted a link to the OpenToonz github over at the MOX  discussion group in hopes they might agree that OpenToonz would be a great platform to showcase the benefits of the format.

Here's the link to the MOX and related source:

https://github.com/MOXfiles

I suppose the primary question might be whether the OpenToonz infrastructure can support a MOX port/plugin.

**Comment by blurymind** [comment]
Why are you convinced?
This is the first time I hear of this format.
What would be the advantages of adopting it?

**Comment by RodneyBaker** [comment]
Why are you convinced?

I've used the product.  :)
If you have Adobe Premiere and/or After Effects you can use the format too.
OpenToonz lacks a similar format  and know users would benefit from being able to use the format.

>  This is the first time I hear of this format.
That's why I mention it here in the development forum.

> What would be the advantages of adopting it?
Please see here:  http://www.fnordware.com/downloads/MOX_Proposal.pdf
I link to that document because it's fairly concise and will also expose you to the basic credentials of its creator Brendon Bolles.  The proposal is no longer a proposal though so don't let that fool you.  After crowdfunding working plugins were developed for Adobe Premiere and After Effects.  The next plugin is planned for Nuke.

There are other efforts afoot by industry leaders that will eclipse that of MOX.  Getting MOX up and running though would be a start and prep developers for emerging formats.  Unlike MOX which   focuses on production the Alliance for Open Media's effort specifically is targeting online distribution of video.  Companies such as Microsoft, Adobe, Cisco, Google, Netflix, etc. are involved in that effort.  The advantage would be that developing for MOX would likely help in development efforts for formats that (at least in theory) will become standard in the future. Unlike MOX, I haven't used anything produced by the Alliance for Open Media but they have a github as well.  I've not cloned it so can't comment on the status of their project but you can find out more here:  http://aomedia.org/

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by RodneyBaker** [comment]
As a follow up to this... the MOX format was abandoned by its creator so... not much use of adding it to Opentoonz.
This is too bad because it was a useful container format.
