### ISSUE TITLE
feature request: A way to set a Modifier Key to rotate canvas

### ISSUE THREAD

**Issue by blurymind** [opentoonz/opentoonz#83]
Very often, while cleaning up, the artist needs to constantly rotate the canvas. Opentoonz has a tool for that - the rotate tool. However there is no way to set the rotate tool to be active WHILE you hold a key. So when you release the key, you can go back to whichever tool you were using prior.

The idea is to draw, hold a key to rotate canvas, release the key and continue drawing.

Currently its cumbersome - you have to switch to the draw tool manually (two clicks, since its hidden), then rotate, then switch manually to your brush tool. It takes away from the flow and slows down work.

In comparison both tvpaint and toonboom have made this a modifier which you hold to rotate the canvas and pan it. So in tvpaint it's crl+alt, but really if the user can set it up - that would be enough for me! :)

Please add this feature or let me know if there already is a way!

**Comment by blurymind** [comment]
nevermind, there is a way to do this - by default its not set. :)

**Comment by blurymind** [comment]
I have started making a default keyboard layout here:
https://github.com/opentoonz/opentoonz/issues/80

**Comment by bigjko** [comment]
Just curious, what is the command you set to get this? I can't find any of these.

**Comment by blurymind** [comment]
I created a keyboard shortcut ini file that has it set to ctrl+space.

Grab it here:
https://github.com/opentoonz/opentoonz/issues/56

**Comment by bigjko** [comment]
Ah, thanks! I didn't realise that holding the button down reverts to the previous tool afterwards, just like I want! :D
