### ISSUE TITLE
Feature Request: Double click on shape select will bring to control point editor

### ISSUE THREAD

**Issue by arh2009** [opentoonz/opentoonz#833]
is it possible to make Double click on a shape select then it will bring the tool (selection tool) to control point editor ?

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
