### ISSUE TITLE
Error while making in Linux (Ubuntu 64 bit)

### ISSUE THREAD

**Issue by lindathadeus** [opentoonz/opentoonz#834]
Hi,
I am trying to install OpenToonz to my Ubuntu machine but I have issues while making. I am getting the below error.

/home/user/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp: In member function 'virtual void QtOfflineGL::getRaster(TRaster32P)':
/home/user/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp:228:63: error: no matching function for call to 'QOpenGLFramebufferObject::toImage(bool)'
                           (TPixelRGBM32 *)m_fbo->toImage(false).bits(), false));

Could you guys help me figure it out to install in Linux?

**Comment by ideasman42** [comment]
Not sure why this would happen, building on Ubuntu 16.04 worked last I checked.
Be sure to follow all steps in our instructions *exactly*.

Please always give details about your system when reporting this kind of information.

- Full build log (attach txt)
- System version
- Qt Version

**Comment by lindathadeus** [comment]
Sorry, 
I tried installing on Ubuntu 14.04.5 LTS, Qt version 5.2.1.
Build log is below:

linda@jose:~/opentoonz/toonz/build$ cmake ../sources
-- SDK Root:/home/linda/opentoonz/thirdparty
-- Thirdpary Library Search path:/home/linda/opentoonz/thirdparty
-- Unix System
-- Qt Core Location:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.2.1
***** libtiff Header path:/home/linda/opentoonz/thirdparty/tiff-4.0.3/libtiff
***** libtiff Library path:/home/linda/opentoonz/thirdparty/tiff-4.0.3/libtiff/.libs/libtiff.a
******* libpng:/usr/lib/x86_64-linux-gnu/libpng.so
***** SuperLU Header path:/home/linda/opentoonz/thirdparty/superlu/SuperLU_4.1/include
***** SuperLU Library path:/usr/lib/libsuperlu.so
**************** lz4 lib:
OpenBLAS:/usr/lib/libblas.so
***** LZO Header path:/home/linda/opentoonz/thirdparty/lzo/2.03/include/lzo
***** LZO Library path:/usr/lib/x86_64-linux-gnu/liblzo2.a
LZO:/home/linda/opentoonz/thirdparty/lzo/2.03/include/lzo
-- Boost version: 1.54.0
subdir: tnzcore
subdir: tnzbase
Bin: /home/linda/opentoonz/toonz/build/tnzbase
subdir: tnzext
Bin: /home/linda/opentoonz/toonz/build/tnzext
subdir: toonzlib
Bin: /home/linda/opentoonz/toonz/build/toonzlib
subdir: tfarm
Bin: /home/linda/opentoonz/toonz/build/toonzfarm/tfarm
subdir: tnzstdfx
Bin: /home/linda/opentoonz/toonz/build/stdfx
subdir: sound
type:.so
Bin: /home/linda/opentoonz/toonz/build/sound
ToonzCore: tnzcoretnzbasetoonzlib
subdir: colorfx
type:.so
Bin: /home/linda/opentoonz/toonz/build/colorfx
FIND_FILE:tnzcoretnzbase
subdir: image
Bin: /home/linda/opentoonz/toonz/build/image
subdir: toonzqt
type:.so
Bin: /home/linda/opentoonz/toonz/build/toonzqt
subdir: tnztools
Bin: /home/linda/opentoonz/toonz/build/tnztools
subdir: toonz
Bin: /home/linda/opentoonz/toonz/build/toonz
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linda/opentoonz/toonz/build
linda@jose:~/opentoonz/toonz/build$ make
[  4%] Building CXX object tnzcore/CMakeFiles/tnzcore.dir/__/common/tvrender/qtofflinegl.cpp.o
/home/linda/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp: In member function ‘virtual void QtOfflineGL::createContext(TDimension, std::shared_ptr<TOfflineGL::Imp>)’:
/home/linda/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp:180:36: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘Qt::HANDLE {aka void*}’ [-Wformat=]
          QThread::currentThreadId());
                                    ^
/home/linda/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp: In member function ‘virtual void QtOfflineGL::getRaster(TRaster32P)’:
/home/linda/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp:228:63: error: no matching function for call to ‘QOpenGLFramebufferObject::toImage(bool)’
                           (TPixelRGBM32 *)m_fbo->toImage(false).bits(), false));
                                                               ^
/home/linda/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp:228:63: note: candidate is:
In file included from /usr/include/qt5/QtGui/QtGui:51:0,
                 from /usr/include/qt5/QtOpenGL/QtOpenGLDepends:3,
                 from /usr/include/qt5/QtOpenGL/QtOpenGL:3,
                 from /home/linda/opentoonz/toonz/sources/include/qtofflinegl.h:8,
                 from /home/linda/opentoonz/toonz/sources/common/tvrender/qtofflinegl.cpp:3:
/usr/include/qt5/QtGui/qopenglframebufferobject.h:101:12: note: QImage QOpenGLFramebufferObject::toImage() const
     QImage toImage() const;
            ^
/usr/include/qt5/QtGui/qopenglframebufferobject.h:101:12: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [tnzcore/CMakeFiles/tnzcore.dir/__/common/tvrender/qtofflinegl.cpp.o] Error 1
make[1]: *** [tnzcore/CMakeFiles/tnzcore.dir/all] Error 2
make: *** [all] Error 2

**Comment by RodneyBaker** [comment]
@lindathadeus  Please advise if you are still having any issues building Opentoonz on Linux.
