### ISSUE TITLE
Outdated translation (.ts) files 

### ISSUE THREAD

**Issue by jcome** [opentoonz/opentoonz#835]
[Those .ts files](https://github.com/opentoonz/opentoonz/tree/master/toonz/sources/translations) are outdated, can anyone help to re-sync the translation file with the source files? 
see [Using lupdate](http://doc.qt.io/qt-5/linguist-manager.html#using-lupdate).

**Comment by jcome** [comment]
It seems that updating/syncing these .ts files are handled manually? 

If possible, I would propose to setup a mechanism to do it automatically and regularly. and then use [lrelease tool](http://doc.qt.io/qt-5/linguist-manager.html#using-lrelease) to produce .qm files instead of asking a translator to push them, so they (translators) always just submit .ts files.

What do you think?

**Comment by shun-iwasawa** [comment]
Translation files updated.

> If possible, I would advise to setup a mechanism to do it automatically and regularly. 

@jcome It's nice idea. I'll try to do so. Thanks!

**Comment by gab3d** [comment]
@shun-iwasawa 
@jcome 
@masafumi-inoue 

Can somebody give me a good and safe lupdate command usage, so I can use it to regularly update the translatable strings for my language?
Thanks! :)

**Comment by jcome** [comment]
Hi @gab3d 

What OS do you prefer? I am using Fedora, and the following steps to update my Chinese ts files:

0) open your terminal  

1) go into Japanese translation folder:
`$ cd ~/opentoonz/toonz/sources/translations/japanese/
`
2) update one of ts file from Japanese version
`$ lupdate-qt5 toonz.ts -ts ../chinese/toonz.ts 
`
3) more detailes about lupdate usage, 
`$ lupdate-qt5 --help
`

**Comment by gab3d** [comment]
@jcome
I did this already (with a slight addition to the options, by the way, and I'm on Windows):
**lupdate .\toonz.ts" -ts "..\spanish\toonz.ts" -no-obsolete -disable-heuristic sametext -disable-heuristic similartext -disable-heuristic number**
...and in fact it seemed to correctly update my ts files from the Japanese ones, removing obsolete strings, and without trying to automatically guess the translations of such new strings.

So, this is an improvement.
Thank you! :)

But,
what I was originally asking, and what I'd really like to know is which opentoonz source files 'lupdate' might scan to obtain the new translatable strings from.

Also, I've learned lupdate can make use use of .pro files to configure its behaviour.
Perhaps someone can provide us with such a .pro file and we can run lupdate on our side beforehand, to know what's new for translating?

**Comment by jcome** [comment]
@gab3d 
> which opentoonz source files 'lupdate' might scan to obtain the new translatable strings from

you can simply update a ts file accordingly by using sub-folder of source code as following

`$ lupdate-qt5 ../../toonzqt/* -ts toonzqt.ts`

I tested it works, but I am not sure it is **safe or not**.

I agree with you that .pro file would be nice, and even better to have an automatic mechanism.

**Comment by gab3d** [comment]
@jcome my bad. thank you for pointing it out!
Until now I haven't realized each .ts file corresponded to a individual folder in the sources.
I'll try that and see what comes out.  :P

**Comment by gab3d** [comment]
well, I tried to update the .ts files from their correspondent folders, but
the results we're not 100% good (it did update the ts files, but it changed
some things inside them, that I just simply couldn't avoid, no matter what
lupdate options I tried).

I think I'll have to wait for some sound advice on this matter :)
