### ISSUE TITLE
Add additional file called as "log.txt" when program crashed

### ISSUE THREAD

**Issue by phamvinh** [opentoonz/opentoonz#837]
Please add additional log file when exceptions or errors happen. I will give you this file because I frequently see program is crashed but I don't know why.

Error happens when I use brush tool, draw and switch frames (flip back and forth). If program writes log, I think it will help you detect error better. Thanks.

Example: 
- Exception "abc", happens at 2016-09-26 02:31 PM, more information: ... detail ...

**Comment by phamvinh** [comment]
Unhandled exception at 0x000007FEE4FCDEA4 (tnztools.dll) in OpenToonz_1.1.exe: 0xC0000005: Access violation reading location 0x0000000000000010.

I copy shape on a frame, then move on next frame, paste it and program is crashed.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
