### ISSUE TITLE
Opentoonz 1.1.1 Crashes when I preview with mesh level !

### ISSUE THREAD

**Issue by Mandea13** [opentoonz/opentoonz#838]
Opentoonz 1.1.1 crashes when I preview the scene with a mesh level and has key frames attached...

What is going on? Does it have to do with the type of settings?

**Comment by turtletooth** [comment]
What are the system specs you are working on?  OS? etc. . .

**Comment by Mandea13** [comment]
HP ENVY 17 Notebook
Processor: Intel Core i7-4710HQ CPU @ 2.50GHZ
RAM: 12GB
System:  Windows 10 64-bit OS
Graphics: Intel HD Graphics 4600

If you need more info let me know..

**Comment by artisteacher** [comment]
I have had the same issue with Mac OS X.

**Comment by turtletooth** [comment]
Are there any steps you can give that will make this repeatable.  I just tried it and couldn't crash it.

**Comment by turtletooth** [comment]
@artisteacher Can you repeat this?

**Comment by artisteacher** [comment]
I just tried and didn't have any issues. I think this may be all set.
