### ISSUE TITLE
AppImage does not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by probonopd** [opentoonz/opentoonz#839]
The AppImage from https://gumroad.com/l/opentoonz-linux# does not run out-of-the-box:

```
me@host:~$ '/home/me/Downloads/OpenToonz-1.1.1-2016.09.26-64bit.AppImage' 
./../bin/OpenToonz_1.1: error while loading shared libraries: libglut.so.3: cannot open shared object file: No such file or directory
```

Please include `libglut.so.3` inside the AppImage.

Also, you might want to use the [desktopintegration](https://github.com/probonopd/AppImageKit/blob/master/desktopintegration) script to place OpenToonz in the menu.

**Comment by ideasman42** [comment]
The app-image is not part of this repository, best contact the Morevna Project directly.

It's possible the app-image build files could be included in the open-toonz repo, but I'm not sure where they're maintained, a brief search I wasn't able to find a repository for them at least.

**Comment by ideasman42** [comment]
@probonopd forwarded your repo upstream https://github.com/morevnaproject/morevna-builds/issues/1

**Comment by morevnaproject** [comment]
@probonopd Please try latest version from https://gumroad.com/l/opentoonz-linux - OpenToonz-1.1.1-2016.09.29-64bit.appimage
The issue should be fixed there.

**Comment by morevnaproject** [comment]
@ideasman42 I suggest to add "linux" and "appimage" labels, so we can track the relevant issues.

**Comment by probonopd** [comment]
Thanks @ideasman42 for pointing me to the correct GitHub project and thanks @morevnaproject for making the AppImage!
