### ISSUE TITLE
Clone Levels/drawings not saving/working correctly

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz#843]
I'm getting some strange results with cloned columns.

Working in latest nightly release.  Steps to Reproduce:
Create New Project
Draw something
Select cell in xsheet that has drawing
Clone that cell/column via Menu>Cells>Clone
Save the Scene/Save All/Save Level... (I'm still exploring differences in results here)*
Create New Scene or Project (to flush old project)
Open the Old Project and note the cloned drawing is missing.

*In the case of saving a level OT will notify me that a previous level already exists (if I've previously attempted to specifically save a cloned level) although I don't see the file anywhere on the harddrive.

**Comment by shun-iwasawa** [comment]
Confirmed in my Windows7 environment and fixed. Thank you for report the bug!

**Comment by RodneyBaker** [comment]
I confirm clone levels are now being saved correctly.
Nice sleuthing and thanks for the quick turn around!  :)

This issue can be closed.
