### ISSUE TITLE
i can't export my work as a .avi file

### ISSUE THREAD

**Issue by Israro** [opentoonz/opentoonz#846]
![screen1](https://cloud.githubusercontent.com/assets/22494303/18907820/7780d4bc-856d-11e6-90b8-9facd4ff488a.png)
![screen2](https://cloud.githubusercontent.com/assets/22494303/18907821/77995078-856d-11e6-8b7a-37b58b477198.png)

Once finished rendering, the preview appears all in black and not see anything.
If I try to reproduce the player tells me that the file is damaged.
Can you think may be going on?

My computer specifications are as follows:

Intel core quad q6600 2.40 ghz, 4 gb ram, windows 7 64 bit

**Comment by turtletooth** [comment]
Are you rendering with a avi codec or as uncompressed?  BTW- rendering as mp4 will be a much smaller file size.

**Comment by turtletooth** [comment]
Closing as abandoned.
