### ISSUE TITLE
I need to edit mesh?

### ISSUE THREAD

**Issue by DukeOfWellington** [opentoonz/opentoonz#848]
So I imported a drawing, I want to animate it but when I create mesh it appears above the drawing, here is a screenshot http://i.imgur.com/KAJxtyk.png any solutions?

**Comment by RodneyBaker** [comment]
I take it the mesh cannot be moved down?

**Comment by DukeOfWellington** [comment]
@RodneyBaker Thanks, for some reason I didn't think of that.

**Comment by RodneyBaker** [comment]
I believe this can be closed.
