### ISSUE TITLE
Improve convert command for color adjustment work in Japanese animation production

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#852]
This feature is requested from some Japanese animation studio.

They are making an animated feature and would like to improve quality in character colors as well.
Usually (in TV series), characters are painted with specific color charts and are identical through sequence. But they decided to add extra work; they would like to adjust character colors **for each scene** in order to fit the background image.

Actually it is the same approach as Studio Ghibli. Ghibli also adjusted character colors for each scene.
Adjusting colors can be easily done in Toonz since Toonz can handle drawing data and palette data separately. However, they differ from Ghibli in that their ink&paint work was done with PaintMan and composition work will be done with AfterEffects.

Based on the situation above, we made a new workflow plan as follows:
[Color adjustment workflow using OpenToonz.pdf](https://github.com/opentoonz/opentoonz/files/510305/Color.adjustment.workflow.using.OpenToonz.pdf)
<img src="https://cloud.githubusercontent.com/assets/17974955/19104973/969134ca-8b1a-11e6-8d2f-afcd34efb1a6.png" width=300>

In order to realize this workflow, some features are needed to implement:
- Enable to specify input palette when convert raster images to TLV with "Painted tlv from non AA source" mode.
- Add option to remove unused styles from input palette.

**Comment by turtletooth** [comment]
I think this is complete.
