### ISSUE TITLE
Can not build against SuperLU_5.2.1 on Linux

### ISSUE THREAD

**Issue by jcome** [opentoonz/opentoonz#854]
Hello, I am trying to build OpenToonz.flatpak, [the new framework for desktop applications on Linux](http://flatpak.org). When compiling tlin_superlu_wrap.cpp, I got the following error:

> ...
> /run/build/opentoonz/toonz/sources/tnzext/tlin/tlin_superlu_wrap.cpp:312:36: error: cannot convert ‘SuperLUStat_t_’ to ‘GlobalLU_t_’ for argument ‘12’ to ‘void dgstrf(superlu_options_t_, SuperMatrix_, int, int, int_, void_, int, int_, int_, SuperMatrix_, SuperMatrix_, GlobalLU_t_, SuperLUStat_t_, int*)’
>           F->L, F->U, &stat, &result);
>                                     ^
> 
> tnzext/CMakeFiles/tnzext.dir/build.make:734: recipe for target 'tnzext/CMakeFiles/tnzext.dir/tlin/tlin_superlu_wrap.cpp.o' failed
> ...

more details: 
[build-log.txt](https://github.com/opentoonz/opentoonz/files/514252/build-log.txt)

the flatpak Manifest and patch used
[OpenToonz Flatpak.zip](https://github.com/opentoonz/opentoonz/files/514263/OpenToonz.Flatpak.zip)

Thanks for your help.

**Comment by ideasman42** [comment]
Resolved in master
