### ISSUE TITLE
rendering issues with the plastic tool

### ISSUE THREAD

**Issue by falls2lawrence** [opentoonz/opentoonz#856]
renders glitch out after adding the plastic tool and transparent backgrounds are lost. https://youtu.be/OWy9-qhaCTE  this is a video of a loop animation with a transparent background and no plastic tool followed by the same animation with the plastic tool. 

v 1.1.1 on a mac el capitan 10.11.6    i also tried the nightly build from 10/6 same result.

love this software, keep up the great work.

**Comment by artisteacher** [comment]
I'm having the same issue on Macs with 10.11.4 and the latest nightly build. The background in the render shows patches from other open programs like Preview on the computer. The previous frames continue to display as the animation progresses.

Also, I want to second that you all are doing great work!
![screen shot 2016-10-28 at 11 26 53 am](https://cloud.githubusercontent.com/assets/21159116/19811910/7f48a32c-9d01-11e6-965e-0ea61aa7051d.png)
![screen shot 2016-10-28 at 11 27 10 am](https://cloud.githubusercontent.com/assets/21159116/19811920/85621482-9d01-11e6-8534-2fc3b55a041e.png)

**Comment by falls2lawrence** [comment]
artisteacher,

i went pretty far back through the issues posted and found that someone posted about this issue three months back :(

if this helps you, oracle makes a free app called virtualbox that lets you run windows right on your mac simultaneously and effortlessly and mircosoft lets you download windows 10 for free. in windows, opentoonz panels turn black when i draw or when i do ANYTHING with the style editor and on mac, opentoonz renders strangely soooooooo, i make my animation on mac and open the scene in windows to render. a few extra steps but in the end i have a perfect animation. 

https://www.microsoft.com/en-us/software-download/windows10ISO

http://www.oracle.com/technetwork/server-storage/virtualbox/overview/index.html

wish opentoonz worked perfectly in either windows or mac but it's still a better choice than toonboom harmony or flash/animateCC.

**Comment by artisteacher** [comment]
Thanks falls2lawrence. A virtual machine is not going to be possible on the student computers. I agree that OpenToonz is definitely a better choice then the other animation software I've tried. I'm really looking forward to when all of the major bugs are worked out!

**Comment by artisteacher** [comment]
I think the issue with the background is due to the skeleton that is part of the plastic tool. When previewing directly in the viewer, the background looks as expected until I add the root of the skeleton.  The distortion in the background shifts as more bones are added.

![screen shot 2016-12-13 at 11 30 50 am](https://cloud.githubusercontent.com/assets/21159116/21149138/7e47449c-c128-11e6-82c7-0e0420fbef51.png)
![screen shot 2016-12-13 at 11 31 06 am](https://cloud.githubusercontent.com/assets/21159116/21149144/83dc5d34-c128-11e6-85c6-3a56efcc7920.png)
![screen shot 2016-12-13 at 11 31 17 am](https://cloud.githubusercontent.com/assets/21159116/21149151/896f155c-c128-11e6-9aa5-24481713e649.png)

**Comment by artisteacher** [comment]
I can use a Matte HSV key to remove the worst of the background distortion, but there is still a good deal of unwanted fragmentation. The HSV key doesn't help with the plastic level's previous frames continuing to show. 
![screen shot 2017-02-08 at 1 07 12 pm](https://cloud.githubusercontent.com/assets/21159116/22750901/789bfc5e-ee00-11e6-8ac5-dac2211ccc0f.png)

Using Mac OS 10.12.3 instead of 10.11.6, results in the blue background mentioned in #939. In that case, the HSV key removes all of the blue background - except for a small edge around the drawing and there is not an issue with old frames displaying.

**Comment by falls2lawrence** [comment]
I dont know, I'm also on 10.12.3 but seem to have different results from what you're describing. In 1.1.2 and the nightly release from 2/9/17, opentoonz renders a perfectly clean alpha channel but still displays multiple frames from the timeline in the rendered frames when the plastic tool is involved.

**Comment by artisteacher** [comment]
Interesting, I had thought that the OS version was having an impact on how levels using the plastic tool display.  Maybe there's still an underlying common issue but it actually impacts different hardware in different ways...

I just took a look on my old macbook pro which still runs 10.9.5, with the build from 2/9/17, to see what would happen. I can't preview plastic modified levels at all. The drawing disappears completely and there is a fairly even scattering of pixels. 
![image](https://cloud.githubusercontent.com/assets/21159116/22795874/37312444-eec6-11e6-9d19-6fdfd68439fa.jpeg)

**Comment by falls2lawrence** [comment]
https://youtu.be/ZSXU8i1gAQs   a video of a loop using the plastic tool rendered on windows and then on mac. I don't have a blue background. I wonder why we have different render results.

V1.1.2 feb 9th nightly build on mac 10.12.3

**Comment by hvfrancesco** [comment]
I have the same rendering problem with plastic tool on linux. it works perfectly in the working area, but I get superimposed multiple frames and bacground artifacts both on preview and on rendering. tested all of available rendering formats, but the result is always the same
![test 0013](https://cloud.githubusercontent.com/assets/614123/23177055/c50a2d44-f865-11e6-87a3-f32193cf3a21.png)

**Comment by artisteacher** [comment]
When previewing while using the plastic tool, this error comes up on console. It could be related. 
<img width="920" alt="image" src="https://cloud.githubusercontent.com/assets/21159116/24087071/355db89c-0cf0-11e7-824f-76f01bb771a0.png">

**Comment by artisteacher** [comment]
So yesterday I updated my old mac from 10.9.5 to 10.12.4. Fortunately the pixelated background issue has stopped. Unfortunately previous frames remain visible. It looks like the different graphics cards have a big impact.

**Comment by matitanimata** [comment]
same issue for me on a mac pro (2013) with yosemite, OT runs even better than the commercial toonz premium 7.3, but with plastic elements the render is a real disaster.
Same scene on a chinese tablet pc and the render is perfect...
Also the preview is much better and almost in real time in windows while on yosemite is really slow (about 8/25 fps).

**Comment by artisteacher** [comment]
Solved in the latest nightly build - at least in OS X 10.13. Thanks @shun-iwasawa!

**Comment by jpturcotte** [comment]
@falls2lawrence, @hvfrancesco & @matitanimata Can you confirm this is working: https://github.com/opentoonz/opentoonz/releases/tag/nightly?

**Comment by morevnaproject** [comment]
Here is the testing build, which includes fix #1726 by @shun-iwasawa - https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-18.01.24-linux64-466fc.appimage

For my hardware (Intel video card) the problem got fixed. Please test.

**Comment by falls2lawrence** [comment]
This particular issue and black halos being rendered around plastic levels seems to have been fixed in the latest nightly build but subxsheets still vanish when plastic skeleton is applied. #1676 is the only thing keeping me using 1.1.3 .

Leaps and bounds on the plastic tool; thanks for the amazing work.

**Comment by matitanimata** [comment]
@jpturcotte , I was far from my mac in the last days, now I've just tested the nighlty build and it works fine, thanks! thanks @shun-iwasawa !
