### ISSUE TITLE
Floating point exception in Control Point Editor Tool.

### ISSUE THREAD

**Issue by jabarrera** [opentoonz/opentoonz#858]
Hi.

When I use the **control point editor tool** I always get a crash (**floating point exception**). I'm trying to reproduce an operation that always throw the error, but I can not. Anyway, I just make a simple draw with vector brush, just start clean Opentoonz, select the control point editor tool, make some operations (to move vertex or spline controls) and I get the error randomly, aparently.

I'm using an appimage compilation (thanks to Morevnaproject) for 32 bits in a GNU/Linux Debian. Opentoonz version 1.1.1. I think it is nigthly builds compilation, but I'm not sure.

Thanks.  :)

**Comment by Scheherazade** [comment]
I've been having the same problem on my Mac for a long time now. It works fine on Windows 10 for some reason.

**Comment by Xenobus** [comment]
I can reproduce it consistently. Looks to be related to control point initialization and only occurs when trying to manipulate a curve by clicking on it or dragging it directly. Using the knobs and moving the control points themselves doesn't seem to ever crash, but it's very easy to misclick on the curve itself.

If you have a completely straight-lined shape, like something made with the geometric tool, you can click or drag the line without crashing. It will spawn the little curve-editing handles upon the first click and remain non-crashing, even after saving, restarting and reloading.
Curves made in other fashion seem to always crash when clicked, including those to which additional control points have been added by any method.

**Comment by Xenobus** [comment]
I thought I'd build it from the source and try to pinpoint the issue, but I could not get this bug to occur in my own build.
Seems to only be an issue specific to Morevna Project's AppImage releases, which I was also using before. Currently persists to their latest build - at the time of writing, 2016.11.13-5bb68, both 32 and 64-bit releases.

Probably something worth taking up with them instead, then.

**Comment by ideasman42** [comment]
Possibly FPE's are handled differently depending on the build options, I don't get crashes here but there are quite a few divide by zeros when using painting tool (just dragging the cursor)

- toonz/sources/toonzqt/icongenerator.cpp:221:45: runtime error: division by zero
- toonz/sources/common/tvectorimage/cornerdetector.cpp:134:61: runtime error: division by zero
- toonz/sources/common/tvectorimage/cornerdetector.cpp:136:61: runtime error: division by zero

Would be good to resolve these.
