### ISSUE TITLE
Plastic tool: error with draw with transformations

### ISSUE THREAD

**Issue by jabarrera** [opentoonz/opentoonz#859]
Hi.

I think that it is an error.

To get it, just make a simple draw. Use the **Edit Tool** and make some transformation to the draw: translate, scale, etc.

After that, select **Plastic Tool** and **Create Mesh**. The mesh will be created in the original draw (not the transformed) and when the skeleton is created and try to animate it the transformed full draw vanish.

Thanks!  :)

**Comment by automated-reckoning** [comment]
Unless I am misunderstanding your report, I believe this is not a bug. The Edit Tool works on _keyframes_, while the plastic tool works on a _Level_. Transforms to drawings should be done with the Selection Tool.

**Comment by jabarrera** [comment]
@automated-reckoning , thanks for the answer and point. After testing what you said, you are absolutely right.

I thought **Edit Tool** was a similar **Selection tool** tool.

I close this not issue. :)
