### ISSUE TITLE
OpenToonz crashes after using the raster brush

### ISSUE THREAD

**Issue by NestorAntonio** [opentoonz/opentoonz#861]
Hello guys, after using OpenToonz (the Windows version) for a while, using just the raster brush it crashes. Some times it takes a while to do it.  I've tried on different specs and OS versions but the problem persists.  

I uploaded a couple of images with the error message. 

Thanks in advance, and keep up the good work.

![screen shot 2016-10-12 at 13 31 20 2](https://cloud.githubusercontent.com/assets/18132742/19320795/b79da52a-9080-11e6-9ce9-7ab2acbc63ed.png)

![screen shot 2016-10-12 at 13 31 25 2](https://cloud.githubusercontent.com/assets/18132742/19320816/c5b7ac28-9080-11e6-8e6b-203f8d29e391.png)

**Comment by turtletooth** [comment]
If there was something that was consistently reproduce-able - I think we could work on it.  It's hard to fix bugs that are intermittent.  Are there any steps you can do to consistently trigger this?

**Comment by BrundleThwaite** [comment]
With my system the raster levels will crash when you use the hand tool.

 It usually happens when you are zoomed in. It happens consistently at higher resolutions and intermittently at HD resolution (1980X1080). If is save before using the hand tool it will not crash.

**Comment by NestorAntonio** [comment]
Hello, thanks for the answers! Yes Brundle, the same happens to me often. I tried saving the project before using the hand tool, but still got the same results. I added a compressed video for you to see.

Thanks in advance. 

[Opt_crash_raster.mp4.zip](https://github.com/opentoonz/opentoonz/files/839236/Opt_crash_raster.mp4.zip)

**Comment by turtletooth** [comment]
I tried recreating this tonight, but I couldn't.  Perhaps it has something to do with Windows 7?    I was using 4k levels and no crash.

**Comment by BrundleThwaite** [comment]
I am using windows 10. The crash happens on both my laptop (Intel)  and desktop (AMD). The crash happens a lot more at 4k but also happens at 1080p (Although it is less consistent). I am not completely sure if the crash get is the same as NestorAntonio's

**Comment by turtletooth** [comment]
@BrundleThwaite does it only happen on raster levels or on all level types?  Do you think it might be related to #860 - OT will crash if the hand shortcut is released before the mouse or pen finishes the panning.

**Comment by turtletooth** [comment]
With the MyPaint brushes introduced, the raster brush has received a lot of changes.  I'm going to close this and if there are still problems that can be reproduced, please open a new issue.
