### ISSUE TITLE
Software Architecture Document

### ISSUE THREAD

**Issue by automated-reckoning** [opentoonz/opentoonz#865]
It might be useful to generate a basic overview document for new contributors to the project.

**Comment by RodneyBaker** [comment]
@automated-reckoning and others   As this is a very old request... do you have any more thoughts on this request that might move a Software Architecture Document forward in development?

**Comment by RodneyBaker** [comment]
Over two years with no commentary or feedback.
If anyone has thoughts or discussion on a/the Software Architecture Document please feel free to post it here.  Well reopen as appropriate.

In the meantime if someone can point to what they consider an ideal example for a Software Architecture Document please do so.
