### ISSUE TITLE
Load scene popup fails to initialize if the "+scenes" project folder path is relative 

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#867]
When opening the Load Scene popup for the first time, the initial folder position should be set to "+scenes" project folder*.  But it fails to locate a correct position if relative path (such as "scenes") is set to the project folder path. 

*For some specific rooms in "StudioGhibli" room set, the initial position changes in order to separate working data for each workflow.

**Comment by turtletooth** [comment]
merged
