### ISSUE TITLE
Issue with Custom Textures on Mac

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#871]
In OS X El Capitan, new custom textures cannot be loaded in the "Style Editor" through the load new texture icon. Clicking on the icon does nothing. 
![customtexture](https://cloud.githubusercontent.com/assets/21159116/19483040/e80e406c-9520-11e6-95a8-be36df633244.png)

**Comment by artisteacher** [comment]
This is still an issue with 1.1.2.

**Comment by turtletooth** [comment]
Have you gone to the palette settings tab and selected "Load from File"

**Comment by artisteacher** [comment]
Thanks, I guess I had the wrong idea on how the custom texture works. I expected to be able to load the texture by clicking on the icon - not clicking on the icon and then going to settings. I wonder if perhaps the settings could open in a pop-up menu when you select the icon. But since this is functional, I'll close the issue.
