### ISSUE TITLE
Exporting as avi

### ISSUE THREAD

**Issue by Lode25** [opentoonz/opentoonz#88]
This feature seems to be disabled under render settings.  Am I missing something?  Perhaps a setting that needs to be changed?

**Comment by odysseywestra** [comment]
Thank you for your bug report, however I do need more information. One of is what operating system are you running? Plus if you can provide a 15-30sec video illustrating your problem that would be great as well.

**Comment by Lode25** [comment]
I'm running windows 10 64 bit.  After completing an animation, I go to file > convert file and the convert button at the bottom is always greyed out.  Below is a youtube video of another user with the same problem.  The problem is described at 5:29-5:52.   http://www.youtube.com/watch?v=PvczYcWL-GU&t=5m29s

**Comment by odysseywestra** [comment]
To be honest, this issue is probably better suited for the Google Group Forums, because so far it doesn't look a bug. Plus you may get better help there from those who learning to use it as well.

https://groups.google.com/forum/#!forum/opentoonz_en

**Comment by odysseywestra** [comment]
Closing since this sounds more like a user support which is better suited for our Google Groups Forums.
