### ISSUE TITLE
Linux Installer

### ISSUE THREAD

**Issue by fthamura** [opentoonz/opentoonz#880]
I has compile the opentoonz in linux (ubuntu) and yes, it work well :0

any idea to make it installer? so i dont have to recompile, just install it

**Comment by morevnaproject** [comment]
There is an AppImage package of OpenToonz - https://morevnaproject.org/opentoonz/
You can run it directly, without the need to install.

**Comment by probonopd** [comment]
What would need to happen for the opentoonz project to "adopt" it?

**Comment by morevnaproject** [comment]
I don't know. Some time ago I have submitted a pull request to add links to Linux version to official OpenToonz website - https://github.com/opentoonz/opentoonz.github.io/pull/11

**Comment by Dioclends** [comment]
@morevnaproject Hello, thanks for the build, I'm using it but there's no audio scrubbing, I'm on Fedora, any ideas? Thanks!

**Comment by plinnell** [comment]
We have the package natively done with rpm for openSUSE and it will be available soon.
