### ISSUE TITLE
Can't Save Levels on Mac

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#882]
My students are frequently running into a serious bug in OS X El Capitan (on iMac computers), with the latest release (1.1.1).  The entire menu system regularly greys out midway through working on a scene, so that that it is impossible to save work, or use any of the menu items. 

The biggest issue is the levels. Even with auto-save enabled, new levels are not saving.  I know this is related to issue #618. I've tried having students right-click each level in the Browser to save manually. Occasionally that works, but often there is no impact. In the case of a tween, it might just save the first frame. Today while dealing with this issue, a student and I tried to cut and paste a level and there was a warning message that said there was no data to paste...

This is a major issue in terms of functionality. We can work around scenes not saving since levels can be reloaded. However to lose an entire class period of drawings/levels on a regular basis makes it impossible for my students to make progress on even a basic animation. Using PC's or virtual machines are not a possibility. I hope there is a Mac expert that can help resolve this!

**Comment by ideasman42** [comment]
How is this a different bug to #618? (looks like the same issue)

- Did this ever work properly, if so what version?
- Please give *exact* steps to reproduce the bug.

**Comment by artisteacher** [comment]
I think the difference to #618 is that manually saving levels in the browser has no effect. Should this have been reported under #618 anyway? I'm new to Github and am still figuring out how this all works.
 We have only used 1.1.1. I'm working on figuring out how to consistently reproduce this issue. It is currently looking like it might be related to using wacom's bamboo tablets and autosave.

**Comment by artisteacher** [comment]
At this point I have been unable to produce the issue consistently, however as long as autosave is enabled and the tablet is connected to the computer:

- OpenToonz is opened with autosave previously enabled (not necessarily set to the 15 minute default)
- A new scene is opened and saved
- A new vector level is created (either through selecting the first frame and drawing or through rob-clicking)
- The level is animated with either tweens or cel animation
- Around 15 minutes, give or take, the menu greys out and is inaccessible

**Comment by artisteacher** [comment]
It looks like auto-save may not be a factor. There is definitely an incompatibility issue with the wacom tablets though.

**Comment by artisteacher** [comment]
I wonder if the issue may be caused by an interrupted/incomplete signal from the pen/tablet. While the menu be becomes inaccessible in other circumstances, the greyed out menu can be consistently reproduced with the following:

1. Wavom Bamboo tablet is connected to the computer 
2. A scene is open and autosave  is set to 1 minute 
2. Create or continue drawing on a vector level
3. Use the brush to draw a frame
4. Press the down arrow key with the hand that is holding the pen (the pen is pulled away from the tablet)
5. Repeat steps 3 and 4
6. By the time autosave runs once or twice, the menu is greyed out
