### ISSUE TITLE
OpenToonz_1.1.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by tombricks** [opentoonz/opentoonz#884]
The procedure entry point K32GetProcessMemoryInfo could not be located in the dynamic link library KERNEL32.dll.

I'm running Windows Vista.

**Comment by automated-reckoning** [comment]
Is this a build or using the installer?

**Comment by tombricks** [comment]
Dont Worry! Fixed!

**Comment by automated-reckoning** [comment]
Good to hear @tombricks. For future reference (and google searchers), what was the issue? Feel free to close the issue ticket as well.

**Comment by turtletooth** [comment]
Closing since this is resolved, but I would like to hear the solution as well.
