### ISSUE TITLE
[Feature Request] Ability to export vector levels to a well supported graphics format

### ISSUE THREAD

**Issue by pocketviz** [opentoonz/opentoonz#885]
This is the one feature I feel is stopping me from using this program for everything. I can import vector images from Inkscape (with varying levels of success), but if I make changes and want to take the image back out, I can only do it as a raster image even though I'm on a vector level.

Currently, the export feature (File > Export Level) allows these formats: BMP, JPG, PNG, TGA, TIF, and TLV.

**Comment by RodneyBaker** [comment]
This might be related to this request (or not) but I'm curious if the .AI format (Adobe Illustrator) is a near enough format to tag along on this Feature Request. It's my understanding that PDF and AI are much the same these days but earlier versions of AI (circa v8) mainly concerned themselves with the bezier curves and is a well known and well documented format.  Or... because both are substantial efforts, it may be that this FR needs to split into two requests... one for SVG and one for PDF.  I do think that SVG has been requested before however so elements of this request might be duplicate.

As for PDF I'd imagine finding a way to add Ghostscript to OpenToonz might be the means of getting to that format.  It's worth noting there are types of PDF that just store the raster data as well as the type that stores the curvature/vector data.  It's obvious the latter is the one this feature request is after.

**Comment by ideasman42** [comment]
SVG is a nice interchange format and can be converted to PDF... other vector formats using external tools.

However unlikely this would be production quality since opentoonz has many features not supported by SVG/PDF/AI... etc.

**Comment by RodneyBaker** [comment]
I agree.  PDF and SVG can certainly be created via external programs.

For the record;  Outside of OpenToonz and general curve editing of vector lines my interest of these formats (particularly in the AI format which is not in this topics original request) relates to ability to transfer those bezier curves back and forth between 3D programs.   

@ideasman42 - I'm sure you are familiar with Howard Trickey who has a history with vector conversions.  Many years ago he wrote a True Type Font (TTF) and Adobe Illustrator (AI) plugin for Animation:Master which converts those formats to splines used in 3D modeling.  I think the code for his Font plugin is still online.  Howard later went on to write similar plugins for Wings 3D and and Blender and as far as I know spends time advising Blender programmers on subjects related to his area of expertise.

The point here being that I don't think it's the end product (final SVG or PDF) that @pocketviz is after via this request but rather the editable data that can be transferred from one program to another.

I suppose in a perfect world there would be some form of buffer that would store the coordinates of a vector line in anticipation of being 'released' for use in or translation to another format.  It is my understanding that most copy/paste buffers are very particular in what they store and for good reason as we don't want that data corrupted.  (And I believed you have commented on the pitfalls of this particular process before).

**Comment by ideasman42** [comment]
@RodneyBaker, re: *"The point here being that I don't think it's the end product (final SVG or PDF)"*

Right, thats what I meant by sayinug *"SVG is a nice interchange format"*. 

Not sure how much time its worth to discuss unless someone plans to work on it though.

**Comment by RodneyBaker** [comment]
Agreed.  I always appreciate your insight and attention to priorities.

I could only wish I had the know-how to work on something like this.  If you have suggestions for how someone like me might align themselves to be able to take on coding projects such as these I'm there.  I can devote the next four years to learning how to program (I have some very minor experience) but currently lack a dedicated target to hit.  

Note that I'm not suggesting SVG/PDF should be this focus but am sure those formats are  documented well enough).  

To attempt to answer my own question:  building OpenToonz from source is a logical starting point so I should do that first.

It might be worth adding that I'm keenly aware that once this feature is implemented another feature will immediately take it's place from the list of things that keep us from using this program.  ;)

**Comment by ideasman42** [comment]
@RodneyBaker, exporting paths is fairly trivial on its own. So if someone likes to look into it, thats fine.

Example writing SVG paths, under 100 lines.
- https://github.com/ideasman42/curve-fit-nd/blob/master/tests/tests.py#L83
- https://github.com/ideasman42/curve-fit-nd (the library this is the test for)


Since OpenToonz is geared towards creating content for rendered output, as opposed to a vector editing tool - I don't think its such high priority.

**Comment by turtletooth** [comment]
@ideasman42 - on a mildly related note.  Do you know how hard it would be to turn a vector line with variable width into a vector shape with 0 stroke?

**Comment by ideasman42** [comment]
@turtletooth, just fit a new curve to the variable width outline between segments of varying width,
there are also some hacks people have done with SVG to support it (search svg variable width online).

**Comment by pocketviz** [comment]
Yes, I meant any vector format, with SVG and PDF as examples. Sorry if that wasn't clear.

I prefer to do my artwork in OT itself because it screws up importing from Inkscape and I have to spend time fixing it, but then I can't put the work in say, Illustrator, unless I know exactly how big it has to be, etc. because I can only export as raster. At the very least, fixing the vector import function would be nice.

I'd be interested in helping myself, but I'm only just now taking introductory programming, so I'm not sure I'm capable enough even if @ideasman42 says it's easy.

**Comment by ideasman42** [comment]
By easy, I mean theres nothing inherently complex in writing out paths to an SVG file.
It still takes time to fit everything together and figure out how to use the API's.

My concern is, once this is added - developers would get many bug reports about various opentoonz features not showing up in the SVG. It may be misleading to add a feature which only works for the most basic cases.

**Comment by pocketviz** [comment]
I think that's a pretty good way to handle it. "Write paths to SVG" would make sense to me.

Incidentally, do you happen to know why imported SVGs end up so weird in OT? The lines are super thin... _except_ for the ends, where the line thickness changes to a giant blob. Not a huge deal (you can just select all and set the line width to 1 or whatever), but kind of puzzling. The colors disappear, too, but remain in the palette, so it's all good.

Thanks for your responses, btw.

**Comment by Rayek** [comment]
This is already possible: in the file browser, right-mouse click on a vector PLI file, and select "Convert". SVG is the only option. An animation will be converted to numbered SVG files.

**Comment by Rayek** [comment]
Just to be clear about this (since no-one seems to realize what I said): OpenTOonz can already convert and export to SVG. 

This request can be closed - or at least, changed in that the functionality ought to be more obvious in the GUI.
