### ISSUE TITLE
Dragging a Studio Palette's tree item may delete palette

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#887]
**PLEASE NOTE** : the following operation will remove palette file and THERE IS NO WAY TO RECOVER. Please make sure to keep backup before you try to reproduce this problem.
 
How to reproduce:

1. On Studio Palette, left-click any item in the tree.

1. Hold mouse button and drag a few pixels. Release the button as soon as the mouse cursor changes to <img src="https://cloud.githubusercontent.com/assets/17974955/19717505/e3764564-9b9b-11e6-975e-96a85dcf8777.png">(cursor with small arrow).

With this operation, the selected item unexpectedly disappears. A correspondent palette file is deleted and cannot be restore.

**Comment by turtletooth** [comment]
Confirmed.  Will check the fix tonight or tomorrow.

**Comment by turtletooth** [comment]
merged
