### ISSUE TITLE
Crash when drawing using Raster Brush Preset

### ISSUE THREAD

**Issue by AyameLee** [opentoonz/opentoonz#89]
**Problem**

Drawing while using a **raster brush preset** will cause instant crash.

**Event Information**

Log Name: Application
Source: Application Error
Date: 28/03/2016 22:38:22
Event ID: 1000
Task Category: Application Crashing Events
Level: Error
Keywords: Classic

Description:
Faulting application name: OpenToonz_1.0.exe, version: 0.0.0.0, time stamp: 0x56f42d87
Faulting module name: tnztools.dll, version: 0.0.0.0, time stamp: 0x56f42d84
Exception code: 0xc0000005
Fault offset: 0x000000000002fb26
Faulting process ID: 0xff8
Faulting application start time: 0x01d189380a71ae9b
Faulting application path: C:\Program Files\OpenToonz 1.0\OpenToonz_1.0.exe
Faulting module path: C:\Program Files\OpenToonz 1.0\tnztools.dll

**Notes**

Does not appear to happen with vector brush presets, only raster brush presets.

**Reproduce Steps**

After saving a brush preset you must change the brush settings so they are not the same as the preset otherwise nothing will happen when selecting the preset.

**Specs**

Windows 10 x64 1511
CPU: i7-6700
GPU: Intel iGPU HD 530
Perif: Wacom Intuos Pro Large (Driver VER 6.3.15-3)

**Comment by odysseywestra** [comment]
Thank you for your bug report. Could you provide us a 15-30 second video illustrating this problem?

**Comment by AyameLee** [comment]
I've attached a video of the problem in the zip file.

[2016-03-28_OpenToonz1-0-0_BrushPreset_Crash_MP4.zip](https://github.com/opentoonz/opentoonz/files/192525/2016-03-28_OpenToonz1-0-0_BrushPreset_Crash_MP4.zip)

Updated opening post with additional information.

**Comment by shun-iwasawa** [comment]
We couldn't reproduce the instant crash neither in Windows nor OS X in our environment.

BTW I found another minor bug from your video: When selecting some brush preset, the preset combo box immediately turn to "<custom>". This behavior was not what we expected and I included the fix in the following pull request.
https://github.com/opentoonz/opentoonz/pull/193

**Comment by AyameLee** [comment]
Thanks @shun-iwasawa 

I'm running the latest nightly of which I'm unable to reproduce the preset crash this time. Well done noticing that other preset bug!

If you're satisfied this issue can now be closed.
