### ISSUE TITLE
Overflowing Special Styles on Mac

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#891]
Many of the special styles for fills overflows out of the closed vector object and fills a larger rectangle - both for shapes made with the geometric tool and manually drawn with the brush. The styles that are overflowing are: 
- Polka dots
- Square
- Chessboard
- Banded
- Linear gradient
- Radial gradient
- Concentric
- Stained glass
- Beehive

Sometimes this happens in the viewer/work area though a restart of the computer or clean install seems to resolve the overflowing there. The overflowing styles are always an issue in the levels window, the x-sheet, and exported renders all still show the styles overflowing (in 1.1.1 and the latest build). 

Steps: 
1. Open OpenToonz on Mac
2. Load an existing scene (or create and save a new scene)
3. Create a vector level in X-sheet (select frame and RMB-click —> new level)
4. Draw a closed shape with the brush or geometric tool
5. Add a new style (RMB-click in level palette —> new style)
6. Double-click the new style to edit
7. In Specials tab select linear gradient or any of the above styles
8. Use paint bucket and click twice to fill shape
9. File —> output settings - set to file type .mp4
10. File —> render
![levels](https://cloud.githubusercontent.com/assets/21159116/19805412/3fb0e5f4-9ce2-11e6-8493-cbce4fae7cdf.png)
![xsheetspecials](https://cloud.githubusercontent.com/assets/21159116/19805415/4481c8be-9ce2-11e6-8928-666c371428d4.png)
![viewer](https://cloud.githubusercontent.com/assets/21159116/19805416/483ddec0-9ce2-11e6-8057-93d09fa34bff.png)
![render](https://cloud.githubusercontent.com/assets/21159116/19805419/4a513374-9ce2-11e6-9344-a5b6c865bf67.png)

**Comment by artisteacher** [comment]
I'm wondering if this is related to #780?

**Comment by artisteacher** [comment]
This is still an issue in 1.1.2.

**Comment by artisteacher** [comment]
So I'm assuming that if this was working properly, it would be similar to using a clipping mask in a graphics program. Except in this case,  there's no clipping occurring. I can set a gradient as a fill and then a rectangle overrides the shape I am applying the style to. I can make adjustments in the settings to change the angle or etc. and the entire rectangle shifts.  

Thanks for all of the hard work! I'm really loving the program and looking forward to further progress. 

![image](https://cloud.githubusercontent.com/assets/21159116/21830330/ef7fbe1c-d769-11e6-9dd0-ef4c31be0ecb.jpeg)
![image](https://cloud.githubusercontent.com/assets/21159116/21830332/ef96cb8e-d769-11e6-8632-4f75eda29983.jpeg)
![image](https://cloud.githubusercontent.com/assets/21159116/21830331/ef9696c8-d769-11e6-9263-0a4f0693f21c.jpeg)

**Comment by artisteacher** [comment]
So what these styles should be doing is using the vector parametric coordinates for the mapping (according to Harmony's manual). In actuality, they are using the coordinates of the level's bounding box. 

This level has two shapes with gradients placed far apart. 
![image](https://cloud.githubusercontent.com/assets/21159116/22411880/8a0a01e8-e676-11e6-9305-080af009f9a6.jpeg)

This shows the preview. 
![image](https://cloud.githubusercontent.com/assets/21159116/22411885/92f43f44-e676-11e6-80d6-5e47ba3e326b.jpeg)

This level shows the two shapes closer together. 
![image](https://cloud.githubusercontent.com/assets/21159116/22411888/a277d566-e676-11e6-8218-1183d5750c51.jpeg)

This shows the preview. 
![image](https://cloud.githubusercontent.com/assets/21159116/22411890/ac4c2696-e676-11e6-8a06-c32baf4ea03c.jpeg)

**Comment by artisteacher** [comment]
In case anyone else is having this issue, I've found a work around to use until this is resolved. 

First select and clone the relevant cells (do not copy and paste). Then one level (let's say the first level) can be given the special style while the other level (ie. the cloned level) is given a normal style that is just a solid color. In FX, add a "Matte In" node. The "special style " level should be connected to the source socket. The "normal style" level should be connected to "matte". 
![image](https://cloud.githubusercontent.com/assets/21159116/22870932/2e61722c-f17a-11e6-94db-d7b598b6b88f.jpeg)

**Comment by artisteacher** [comment]
This is still an issue in 1.1.3.

**Comment by artisteacher** [comment]
This overflow also occurs in the Viewer when "Visualize Vector as Raster" is on.

**Comment by jpturcotte** [comment]
@artisteacher If I understand you correctly, this is related to #406, and still is not fixed, is that correct? Maybe @shun-iwasawa could have a look at it?

**Comment by artisteacher** [comment]
I think they seem pretty similar. This does still need to be fixed.
