### ISSUE TITLE
Feature Request: New Level Buttons in XSheet Corner

### ISSUE THREAD

**Issue by turtletooth** [opentoonz/opentoonz#894]
I think one of the great features of the software is to have a variety of level types.  Currently it is a handful of clicks to create a new level and change the type to a format other than the default format.  Buttons in the xsheet could speed up the workflow.  It currently looks like this:
![new_level](https://cloud.githubusercontent.com/assets/4576381/19864706/061780b2-9f5f-11e6-9f44-462c418f93c9.PNG)

What do you think about something like this:
![add_new_level](https://cloud.githubusercontent.com/assets/4576381/19864714/155d8652-9f5f-11e6-8c4c-131c418d81a7.png)

One click for the various level types.

**Comment by artisteacher** [comment]
I think it is a great idea! Would clicking one of the buttons pull up the new level menu or would it create a level automatically?

**Comment by turtletooth** [comment]
@artisteacher I think it would be better to bring up the new level popup so you can name your levels.  Many of my students get lazy and use levels named a, b, c . . and then get confused when their scenes get complex.

**Comment by pculli** [comment]
I was thinking of a similar idea lately.

Maybe you could set it to automatic or "name" mode.
In automatic, it would create a level and name it. In "name" mode, it could bring up a name popup only, just to give it a name and apply it by pressing Enter. That would be pretty fast and useful.

**Comment by shun-iwasawa** [comment]
In the traditional production workflow, most of levels are scanned from papers and the "New Level" command is rarely used. I understand that these buttons are somewhat convenient for paperless workflow or in educational use, but IMO it should be optional ( as an item in Preferences ) in order to keep the interface simple.

**Comment by 2dvision** [comment]
Is this possible add a toolbar on top xsheet window, like toon boom? user can add/remove buttons and show/hide toolbar.

![har11_custom_marks](https://cloud.githubusercontent.com/assets/16509592/19932546/c23e4fba-a125-11e6-804e-dc811496d5a4.png)

similar feature requests 325

**Comment by artisteacher** [comment]
Name mode would be amazing!

**Comment by turtletooth** [comment]
I'm combining this with #906.  Any ideas on what an icon would look like for differentiating new level types?  Also any other thoughts on buttons you would like in the toolbar?

**Comment by artisteacher** [comment]
These would need plenty of adjustment but could be a direction to go in. Not sure what to do about toonz raster. I do think that a traditional layer icon is a good base. 
![image](https://cloud.githubusercontent.com/assets/21159116/22316112/f3486b5e-e338-11e6-8690-e4208ac8e37e.jpeg)

**Comment by artisteacher** [comment]
Maybe like this?
![image](https://cloud.githubusercontent.com/assets/21159116/22318070/a4699b40-e345-11e6-9971-8206484d99c7.jpeg)

**Comment by turtletooth** [comment]
I like it - now it needs to fit in 18 x 18 pixels.

**Comment by turtletooth** [comment]
#989 Is the implementation of the XSheet Toolbar.  Please take a look and see what you think
