### ISSUE TITLE
Customizing menubar in non-English environment  loses English (original) menu titles

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#897]
**NOTICE**: The following process will overwrite your menu bar settings. Please make sure to keep backup before trying to reproduce.

To reproduce this problem:

1. In Preferences->Interface, set "Language" to non-English. For example, set to "日本語"(Japanese). 

1. Restart OpenToonz.

1. Right click room tab and select "_RoomName_ ワークスペースのメニューバーをカスタマイズ" (Customize Menu Bar of Room "_RoomName_" )

1. Customize Menu Bar Popup opens. Click "OK" and close the popup.

1. Set the Language back to "English". (In 環境設定->インターフェイス->言語)

1. Restart OpenToonz again.

In my test, the menu bar displays translated (Japanese) menu title even in English environment and loses original (English) titles.

**Comment by turtletooth** [comment]
Merged
