### ISSUE TITLE
Onion Skinning only shows previous frames

### ISSUE THREAD

**Issue by bigjko** [opentoonz/opentoonz#90]
Maybe I'm not using it correctly, but it seems onion skinning only shows previous frames not forward frames.

Anyone else having this issue?

**Comment by blurymind** [comment]
This is not a bug . Open your Flipbook window and there you need to extend it  down by dragging its little handle (beneath the current frame).
![opentoonz-flipbook-onionskin](https://cloud.githubusercontent.com/assets/6495061/14086215/e2b1339a-f51b-11e5-8fd0-f274ec1e6b55.png)

**Comment by bigjko** [comment]
Ohhh nice! Thanks!
