### ISSUE TITLE
OpenToonz is quitting on the main window. 

### ISSUE THREAD

**Issue by SimbadaPP** [opentoonz/opentoonz#903]
So opentoonz up until 2 days ago had been working fine, but now I when I try to open it, it loads all the way up to the main window and then encounters an error forcing it to quit.  Downloaded the latest version after first encountering the problem. Same problem.

i have windows 10 and Intel HD graphics 530 

![whatdo1](https://cloud.githubusercontent.com/assets/23242222/19974388/95648b64-a1a5-11e6-9d8a-c10edc067656.PNG)

![problem](https://cloud.githubusercontent.com/assets/23242222/19974399/a238cf4e-a1a5-11e6-95f0-80b28177f2b6.PNG)

**Comment by turtletooth** [comment]
Is this still an issue?  Have you tried the portable version?

**Comment by SimbadaPP** [comment]
the issue i found was because of provider connection. by that, i mean, when
att limited the available sites i could visit because of my delay in paying
a bill, it affected opentoonz on startup.

if you should know too. there was a teacher that replied to my thread of
the same issue whom worked with a public school network on reddit

the problem was resolved by going offline.

but to answer the other question, i don't know if i tried the portable
version

**Comment by turtletooth** [comment]
@shun-iwasawa Should there be a change made to how OpenToonz handles network connections when checking for updates?

**Comment by SimbadaPP** [comment]
yes.however, as stated before, if can be handled by turning off connection
of internet. but for further progress, there can be changes in how
opentoonz operates when limited connection is available.

**Comment by SimbadaPP** [comment]
i do not know about updates

**Comment by RodneyBaker** [comment]
Perhaps this issue can be refined, refocused or closed?

**Comment by RodneyBaker** [comment]
Closing as this issue should be resolved in part or whole.
@SimbadaPP If you continue to experience any problems with current releases please let us know.
