### ISSUE TITLE
Feature Request: Toolbar on Top XSheet Window

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#906]
![opentoonz xsheet toolbar](https://cloud.githubusercontent.com/assets/16509592/20099184/7ecff35e-a5cc-11e6-8a7d-3df5ca5b4725.png)

I think this is useful, Because it allows us to add buttons (or make new buttons #894 , #325 ) and working with XSheet will be faster and easier.

**Comment by adamearle** [comment]
I like it

**Comment by Dragularos** [comment]
Yes, this would be very useful and maybe not so hard to get it coded ? :)

**Comment by turtletooth** [comment]
I'm combining this with #894.  Any ideas on what an icon would look like for differentiating new level types?  Also any other thoughts on buttons you would like in the toolbar?

**Comment by shun-iwasawa** [comment]
Please note in advance that for now the Xsheet and the Function Editor have column areas of the same height, which is intended to be put side-by-side for compositing work and to show cell areas of both panels being synchronized.
If you add some toolbar on top of the Xsheet it would better to make it enable to hide as needed.

**Comment by turtletooth** [comment]
Good call @shun-iwasawa.  I have already made it hideable.  Do you have any other thoughts for location?  I think the features will be useful, but there is already a lot going on in the UI.

**Comment by shun-iwasawa** [comment]
Very nice! If you make it hideable, for now I think it would be reasonable to put it on top of the panel as @2dvision suggested.

**Comment by artisteacher** [comment]
Here are some smaller buttons. Let me know if they need adjusting or if they should be a different file type. If you want to go in a different direction, that's fine too. 

![image](https://cloud.githubusercontent.com/assets/21159116/22489931/362501ea-e7e8-11e6-9074-e04130904f3b.png)
![image](https://cloud.githubusercontent.com/assets/21159116/22489932/36393d7c-e7e8-11e6-9950-8d2ea10ecfb3.png)
![image](https://cloud.githubusercontent.com/assets/21159116/22489933/363b473e-e7e8-11e6-83ee-12a92a26a5e4.png)

**Comment by turtletooth** [comment]
Calling all artists - I could use some icons for the following buttons:

Load level...
Replace Level...
Autorenumber
Reverse
Open Sub-xsheet
Close Sub-xsheet

I am going to try out the ones @artisteacher shared for new levels above.

**Comment by turtletooth** [comment]
Here's what I have so far:

![xshtoolbar2-9](https://cloud.githubusercontent.com/assets/4576381/22815058/cbe75fd2-ef15-11e6-898a-d3b21440eca4.JPG)

The xsheet is collapse xsheet, the arrows are enter and exit sub xsheet.  I am open to better ideas- I just took those from the current icons already in OpenToonz.

**Comment by artisteacher** [comment]
Here's a go at the enter and exit sub-xsheet buttons. 
![image](https://cloud.githubusercontent.com/assets/21159116/22847200/751db120-efb9-11e6-9bc1-b705ca100b94.png)
![image](https://cloud.githubusercontent.com/assets/21159116/22847201/752f2ab8-efb9-11e6-9a53-06bc048d0c86.png)

**Comment by 2dvision** [comment]
I am not icon designer but it is my suggestion:

![all](https://cloud.githubusercontent.com/assets/16509592/22847575/10f94b4c-f003-11e6-9a58-8b5e89023c77.png)

SVG and PNG:
[new icon.zip](https://github.com/opentoonz/opentoonz/files/767992/new.icon.zip)

**Comment by turtletooth** [comment]
@artisteacher I like the idea.  With the arrows getting thicker at both ends, it is hard to tell at a quick glance which one is which.

@2dvision I like the simplicity.  But with the transparency, they don't read as well on the lighter theme.

I'm definitely not saying let's keep mine, but I think there might be some tweaks to implement.

I think I'm going to hold off on adding the additional buttons for now.  The toolbar is getting somewhat long and I want to get the basics added first.  But if you have different sub-xsheet buttons, I would be glad to look at those.  

There is also a timeline view PR to be reviewed that could affect how long this toolbar could reasonably be.

Thanks for the help.  I appreciate the feedback.

BTW- here is the toolbar with the new theme I'm testing:

![toolbar_themed](https://cloud.githubusercontent.com/assets/4576381/23008430/d93a99fe-f3cc-11e6-9165-aae8344046dd.JPG)

**Comment by artisteacher** [comment]
I made a few new versions of the open & close buttons.

I've worked on making my original design more clear. 
![image](https://cloud.githubusercontent.com/assets/21159116/23049401/c241f5d6-f489-11e6-8cb9-3664569a482d.png)
![image](https://cloud.githubusercontent.com/assets/21159116/23049402/c2569f68-f489-11e6-80c4-d7dceec223ff.png)
I've also made a simplified version. 
![image](https://cloud.githubusercontent.com/assets/21159116/23049433/08d14f24-f48a-11e6-865e-a448ee895745.png)
![image](https://cloud.githubusercontent.com/assets/21159116/23049434/08e77736-f48a-11e6-9a77-d48c183852d0.png)

**Comment by 2dvision** [comment]
![open_close_sub-xsheet](https://cloud.githubusercontent.com/assets/16509592/23078669/cf64c90c-f55e-11e6-8e0c-306d1c43623d.png)

![open sub-xsheet](https://cloud.githubusercontent.com/assets/16509592/23078584/91a95830-f55e-11e6-84ba-571c46177cb7.png)
![close sub-xsheet](https://cloud.githubusercontent.com/assets/16509592/23078591/9527af20-f55e-11e6-9c11-968d25408790.png)

**Comment by RodneyBaker** [comment]
Icon-wise, I'm liking where this is going. 
This last one is simple, easily readable and (I think) very intuitive.
I can't quite say that about the previous as they are a bit hard to read/interpret.

The toolbar above the xsheet will be a nice addition.

**Comment by turtletooth** [comment]
I think right now I prefer @2dvision icons for simplicity and quick glance-ability (that's a word right :) 
@2dvision Would you mind giving collapse into sub-xsheet a go?

**Comment by artisteacher** [comment]
Those look great! Definitely the right choice.

**Comment by 2dvision** [comment]
![collapse_sub-xsheet](https://cloud.githubusercontent.com/assets/16509592/23092444/52bcdd22-f5e0-11e6-90e4-bc790bc4b1e2.png)

![collapse_sub-xsheet2](https://cloud.githubusercontent.com/assets/16509592/23092447/58b2cd54-f5e0-11e6-9bbf-f20f5707adc0.png)

**Comment by turtletooth** [comment]
Here is the new look.  @2dvision Would you mind darkening the icons just a touch if you have time?  BTW - I stole your arrow for the repeat icon.  :)

![xshtoolbar](https://cloud.githubusercontent.com/assets/4576381/23281946/707655aa-f9dc-11e6-8e69-aec734c25ba6.PNG)

**Comment by 2dvision** [comment]
5% Gray:
![open sub-xsheet 5 gray](https://cloud.githubusercontent.com/assets/16509592/23314533/9e1d8d88-fad7-11e6-8a97-8b959f1b8f42.png)
![close sub-xsheet 5 gray](https://cloud.githubusercontent.com/assets/16509592/23314541/a3593bb2-fad7-11e6-9e1e-9aaa05157749.png)
![collapse_sub-xsheet 5 gray](https://cloud.githubusercontent.com/assets/16509592/23314546/ab8d94ea-fad7-11e6-8731-466deca86efc.png)

10% Gray:
![open sub-xsheet 10 gray](https://cloud.githubusercontent.com/assets/16509592/23314567/bb22206a-fad7-11e6-9a7d-428ac1826fc5.png)
![close sub-xsheet 10 gray](https://cloud.githubusercontent.com/assets/16509592/23314571/bf9065da-fad7-11e6-8c11-29f5285e855d.png)
![collapse_sub-xsheet 10 gray](https://cloud.githubusercontent.com/assets/16509592/23314577/c41d0aae-fad7-11e6-875b-0a5160f6b236.png)

**Comment by turtletooth** [comment]
I'm going to close this since there is an active PR for it.  Any needed discussion can be had there.
