### ISSUE TITLE
No audio scrubbing 

### ISSUE THREAD

**Issue by Dioclends** [opentoonz/opentoonz#907]
Hello, I'm using fedora 24 AppImage provided by morevnaproject and I'm not getting audio scrub even though I can import my wavs. Is there any specific library that should be intalled or could it be a problem of the package. I will try to build from source, please do tell me if there's an specific way to avoid this problem during-after build. Thanks!

**Comment by jabarrera** [comment]
You don't have any audio?

You don't need anything for WAV reproduction (as a level) in GNU/Linux (audio goes throw SDL).

But there is a problem with it (#863). I just have publish a pull request #930 that fix that. You can test it if you want or wait it'll enter in Opentoonz.

**Comment by jpritikin** [comment]
I found similar issue with morevna appimage 1.2.0.1 (Debian linux). Scrubbing might work for a few seconds but crashes promptly. It's very unstable.

**Comment by jpritikin** [comment]
CC @morevnaproject @blackwarthog

**Comment by morevnaproject** [comment]
This is the same as #1097. We're testing the solution right now.

**Comment by morevnaproject** [comment]
Okay, the fix is here! Our developer @blackwarthog fixed an appimage and also rewrote some part of code to achieve better playback quality. Please test this build - https://dev.icystar.com/downloads/OpenToonz-1.2.0.3-morevna-18.01.26-linux64-9a70a.appimage
