### ISSUE TITLE
Problems with coloring and filling

### ISSUE THREAD

**Issue by iJassar** [opentoonz/opentoonz#909]
Both vectors and rasters fill with the wrong color, don't change with changes in style editor (whether I click apply or use the auto apply button). I cannot fill in a simple rectangle at the moment!
Also, everything gets colored by red, randomly!
Thank you.

Edit: rendered scenes are colored correctly, the issue is limited to editing.

System: Windows 10 64-bit

**Comment by shun-iwasawa** [comment]
@iJassar 
Please check if any of options "Ink Check", "Ink#1 Check" or "Paint Check" is activated.
With such options being activated, regions painted with the current style turn into red color.
"Ink Check", "Ink#1 Check" and "Paint Check" are in "View" menu in the menu bar by default. 
Thanks.

**Comment by iJassar** [comment]
Perfect!
Thank you so much.
Do you mind explaining why this happens?

**Comment by shun-iwasawa** [comment]
AFAIK these options are disabled by default and will be activated only by clicking them in menu bar or by pressing shortcut key (if assigned).
Please post another issue if you find a situation that these options are  unexpectedly enabled by any other operations.

**Comment by shun-iwasawa** [comment]
Problem solved. I'll close this.

**Comment by iJassar** [comment]
Thank you very much
