### ISSUE TITLE
Easy input feature for the Style Name Editor

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#910]
In animation production, it is important to set appropriate name to styles in order to manage color design, but inputting style name is one of the burdensome tasks.
At least in Studio Ghibli's production, there were frequently-used keywords for style name; every human characters have colors for "eye", "skin", "hair" and "mouth" etc. In addition, every styles for shade parts have "_K" suffix. ("K" stands for "KAGE(影)", which means "shadow" or "shade" in Japanese)
In consideration of the above, I think it will improve efficiency if there is a way to input frequently-used keywords by just clicking the buttons.

**Comment by pculli** [comment]
Very cool!

**Comment by turtletooth** [comment]
Merged. Closing
