### ISSUE TITLE
[Question] About roadmap, milestones and future.

### ISSUE THREAD

**Issue by jabarrera** [opentoonz/opentoonz#914]
First off, thanks to **Dwango** for put this into open source.

I know that this question could be too soon to do it but I think they could be interesting to chat about that. :)

**Has Dwango a roadmap for Opentoonz?**

I see that some issues are fix and some new features are entering, but I really miss a roadmap with some milestones.

I don't know if Dwango wants to refactor things or it is enough fixing some things and entering a few new features.

Seeing the success of **Blender** it will be really cool see that with Opentoonz in the next future. :D

**Comment by shun-iwasawa** [comment]
@jabarrera 
Thank you for having interest in OpenToonz.
As OpenToonz team in Dwango, we're sorry but we still do not have any concrete roadmap for now.
We are being focused on fixing bugs reported here and dealing with requests from Japanese animation studios. We still do not have full perspective of such tasks and not yet able to estimate the time needed to complete them.

**Comment by jabarrera** [comment]
Thanks for the answer @shun-iwasawa .

Don't worry,  I understand that it's too soon to have a roadmap. :)

Please, feel free to close this issue/question if you prefer to maintain clean the issue list.
