### ISSUE TITLE
Camera Capture popup doesn't open

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#915]
This issue was reported from some Japanese animation studio.

This problem occurs if the popup position (position of the top-left corner) was near the bottom edge of the screen on the previous launch of the software. 
All the dialogs (inheriting `DVGui::Dialog`) remember its geometry and reproduce it on the next launch. But the popup with `Qt::WindowMaximizeButtonHint` such as Camera Capture popup seems to offset to bottom-right direction on being shown (for reasons unknown to me). 
Therefore, the popup get out of the screen and seems not to open.

**EDITED**: They also demanded the Camera Capture popup to be enable to put behind the main window.
Since this popup is space-consuming, they would like to switch back and forth between the popup and the main window by `Alt+Tab` (switching the active window shortcut).

**Comment by turtletooth** [comment]
Merged
