### ISSUE TITLE
OSX 10.11.3: Level strip is black

### ISSUE THREAD

**Issue by trondarild** [opentoonz/opentoonz#92]
The level strip doesn't show any images of drawings, it is only coloured black.

![skjermbilde 2016-03-28 kl 21 01 20](https://cloud.githubusercontent.com/assets/4227647/14087082/9f148300-f528-11e5-9c53-e6cf3f7b6fa6.png)

**Comment by odysseywestra** [comment]
Is this still persistent with the current version of openToonz?

https://github.com/opentoonz/opentoonz/releases/tag/v1.0.1

**Comment by trondarild** [comment]
I can test it, but I would need someone to build a mac pkg file of the release unfortunately.

**Comment by trondarild** [comment]
@odysseywestra I have tested now with the latest mac build, and the problem is still there unfortunately.

**Comment by Goofybud16** [comment]
This effects #51 as well.

**Comment by tomosu** [comment]
Thank you for your report.
We fixed this problem, so please try the latest nightly-build below.
https://github.com/opentoonz/opentoonz/releases

**Comment by trondarild** [comment]
Closed
