### ISSUE TITLE
hi-dpi support: Screen Size Problem

### ISSUE THREAD

**Issue by EmeraldEelEntertainment** [opentoonz/opentoonz#920]
Hello; I recently downloaded OpenToonz after having it be recommended to me. However because my laptop's pixel density is quite large it has caused all of the icons and such to be super small, and it is very hard on my eyes to see.

Is there a way to increase the UI size? The picture attached to this post shows how it looks on my end.

![opentoonz screen size](https://cloud.githubusercontent.com/assets/21361440/20350981/e34c263a-ac08-11e6-80b9-f23f4abfbed6.png)

**Comment by RodneyBaker** [comment]
There is a possible solution to this issue posted in the main forum.
You can find that here:

https://groups.google.com/forum/#!category-topic/opentoonz_en/4yWzTVQraDM

Basically, it suggests creating an environmental variable as follows:

QT_AUTO_SCREEN_SCALE_FACTOR

Then set that variable to 1

The post outlines setup of this variable as follows:

On Windows 10 you can do this by pressing the windows icon and typing
> "environment". Choose "Edit the system environment variables" (I have
> tested it and it works in both system or user environment variables).
> On the window that appears, click the "Environment Variables" button and
> then click "New". Input QT_AUTO_SCREEN_SCALE_FACTOR for the variable name,
> and 1 for the variable value.


I'm not sure this is your exact problem but it certainly sounds related.

**Comment by EmeraldEelEntertainment** [comment]
I followed the instructions and ran OpenToonz. Haha it works! Thank you so much for the solution! :D

**Comment by EmeraldEelEntertainment** [comment]
Justing bumping this thread.
