### ISSUE TITLE
Suspicious/incorrect use of `abs`

### ISSUE THREAD

**Issue by ideasman42** [opentoonz/opentoonz#923]
There are uses of `abs` in opentoonz where it seems  `fabs` was intended (without converting to int).

See: bea8195c08ccfe23284105f144c07f3ca75d0ece for an example of the problem.

Other examples:

[`float xRatio = 1.0f - abs(pos.x - p0.x)`, all inputs are floats.](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/stdfx/iwa_motionblurfx.cpp#L317)

This is almost certainly a mistake.

[`if (abs(cosf(part->flap_phi * 3.14159f / 180.0f)) < 0.03f) {`](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/stdfx/iwa_particlesengine.cpp#L881)

[`illuminant = abs(normVec.x * lightVec.x + normVec.y * lightVec.y + normVec.z * lightVec.z);`](https://github.com/opentoonz/opentoonz/blob/792dc2b6b402d622292efe815bfaa2635c43eeb9/toonz/sources/stdfx/iwa_particlesengine.cpp#L928)

**Comment by shun-iwasawa** [comment]
Great catch. @ideasman42 and @Xenobus thank you so much for pointing out the problem!

**Comment by RodneyBaker** [comment]
@shun-iwasawa  I have taken the liberty of unassigning you from this issue so that others will feel free to give it a look and take it on.  Please feel free to self assign again as you see fit.  I'd say you are still the most likely person to take it on.

**Comment by RodneyBaker** [comment]
Some of this has been addressed via #3226 but other parts still remain...

**Comment by RodneyBaker** [comment]
Closing as likely resolved by #3226.
Please feel free to open a new report on suspicious/incorrect usage that might have been missed.
