### ISSUE TITLE
Crashed by Start

### ISSUE THREAD

**Issue by Lisalol** [opentoonz/opentoonz#937]
Version 1.1.2 Win8.1 64bit
Error:
------
Das Programm kann nicht gestartet werden, da api-ms-win-crt-runtime-l1-1-0.dll auf dem Computer fehlt. Installieren Sie das Programm erneut, um das Problem zu beheben.
------
A new installation does not fix the problem

**Comment by yamisama** [comment]
After a quick google search, it looks like [this Windows update](https://support.microsoft.com/en-us/kb/2999226) for Windows versions older than 10 might fix your problem.

If that doesn't help, I'd try installing the MS Visual C++ 2015 Runtime Redistributable (make sure to get the 2015 version as it matches the version OpenToonz is being built with). It should also be a free download from Microsoft.
