### ISSUE TITLE
No option for powers of 2 on sprite sheets

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#938]
There is not option to clamp the final size of a sprite sheet to be a power of 2 (POT).

**Comment by turtletooth** [comment]
That's a good idea.  Let me think about how to do it.

**Comment by turtletooth** [comment]
I don't think I am going to add an option for power of two, but instead I will add an option to not trim white/unused space.

Adding a power of two clamp leaves a lot of potential problems.  If an animation isn't set to a power of two from the beginning of being created, clamping one dimension doesn't guarantee that the other dimension would also be a power of two.  Do you add white space to the other dimension to get it to a power of two?  (That could be a lot of added whitespace.)  Do you add it to the top or bottom. .   There are too many questions that can't be foreseen.

The easiest answer that gives the user the most control is letting them set the size of the camera settings to the dimensions they want and then making spritesheet export not trim off whitespace.  This will guarantee that users have no surprises in how the program tries to force their drawing into a power of two.

**Comment by turtletooth** [comment]
#1022 Removes the forced trimming on spritesheets so users can force a predetermined size.
