### ISSUE TITLE
blue background when exporting animation with plastic tool

### ISSUE THREAD

**Issue by opntnzcmmntr** [opentoonz/opentoonz#939]
anyone else experiencing this?  osx 10.12.1, opentoonz 1.1.1 and nightly builds.

it can be removed with a chroma keyer in post, but it would be nice to have it not be there at all.  it also gets in the way of any layer beneath it in the hierarchy and greatly compromises opentoonz as a compositor.

**Comment by artisteacher** [comment]
In 1.1.1 and the nightly builds I get a strange fragmented background that is showing bits and pieces of other open programs, instead of the actual background. In 1.1.2, I am getting an extremely pixelated blue background if I use a color card for the background. Without a color card, it is still weirdly fragmented based on other open programs/the desktop wallpaper. This is with osx 10.11.6.

**Comment by artisteacher** [comment]
This might be an issue with the plastic tool's skeleton? My background issues only start once the skeleton is added to the mesh #856.

**Comment by turtletooth** [comment]
@artisteacher Mentioned in #856:  HSV key removes all of the blue background - except for a small edge around the drawing and there is not an issue with old frames displaying.  That might be a temporary workaround for this.

**Comment by artisteacher** [comment]
A HSV key works for raster and toonz raster levels while a RGB key works better for vector levels. An Erode/Dilate node takes care of the remaining blue edge.

**Comment by falls2lawrence** [comment]
https://youtu.be/ZSXU8i1gAQs   a video of a loop using the plastic tool rendered on windows and then on mac. I don't have a blue background. I wonder why we have different render results.

V1.1.2 feb 9th nightly build on mac 10.12.3

**Comment by artisteacher** [comment]
I have regular access to 3 different macbook pros. All 3 have different versions of OS X, are different ages/models and all have a problem rendering with the plastic tool #856. All 3 display that problem differently. The one running sierra has the blue background. 10.9.5 has an even scattering of pixels and doesn't display the plastic modified level. 10.11.6 shows parts of the background but also has a super fragmented view of other open programs/documents in the background and previous frames of the plastic level display. All of the student imacs run 10.11.6 and have the same issue as the laptop that runs 10.11.6, so I had assumed the difference was based on the OS version. Maybe the graphics card has an impact?

**Comment by hvfrancesco** [comment]
I have the same rendering problem with plastic tool on linux. it works perfectly in the working area, but I get superimposed multiple frames and bacground artifacts both on preview and on rendering. tested all of available rendering formats, but the result is always the same
![test 0013](https://cloud.githubusercontent.com/assets/614123/23177055/c50a2d44-f865-11e6-87a3-f32193cf3a21.png)

**Comment by morevnaproject** [comment]
@hvfrancesco Please let me know your videocard model and driver version. I have same issue on Linux, but only with Intel videocards. Nvidia with proprietary driver works fine.

**Comment by matitanimata** [comment]
same problem with a end 2013 macpro ( carrying 2 x AMD FirePro D300 with 2gb ram) with El Capitan, the render is unusable, the background is not blue but it is full of artifacts and pieces of the desktop wallpaper... the same scene rendered with toonz harlequin 7.3 works fine.

**Comment by artisteacher** [comment]
This is now working with the latest nightly build and OS X 10.13!

**Comment by morevnaproject** [comment]
Here is the testing build, which includes fix #1726 by @shun-iwasawa - https://dev.icystar.com/downloads/OpenToonz-1.2.0.1-morevna-18.01.24-linux64-466fc.appimage

For my hardware (Intel video card) the problem got fixed. Please test.

**Comment by artisteacher** [comment]
This is resolved, recommend closing.
