### ISSUE TITLE
bypass ctrl-click to add path points on mac

### ISSUE THREAD

**Issue by opntnzcmmntr** [opentoonz/opentoonz#940]
in a motion tweening tutorial they said to ctrl-click to add points to a curve, but on the mac ctrl-click is locked to right-click.  is there a way to remap this control within opentoonz?  i've looked in configure shortcuts, but can't find a solution.  any chance the next mac build could address this important issue?  it seems impossible to do the motion tweening as described with this issue blocking the program's proper use.  are there any other possible solutions?

**Comment by artisteacher** [comment]
Cmd-click adds points to a curve on a mac. You can also use the brush tool to draw a more specific path for the motion tween if the path is selected in the schematic.

**Comment by opntnzcmmntr** [comment]
Hmm, cmd-click must be buggy, or the point-control system itself is buggy.

**Comment by opntnzcmmntr** [comment]
Nevermind, it seems to be working now :^D
