### ISSUE TITLE
Move the Show info in rendered frames to the output settings

### ISSUE THREAD

**Issue by BrundleThwaite** [opentoonz/opentoonz#946]
I think it would be more intuitive to have this setting in the output settings in the other settings tab as it is a rendering option.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
