### ISSUE TITLE
﻿Feature Request: Auto select drawing for "Selection Tool" and "Edit Tool"

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#947]
"Control Point Editor Tool" have this option.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
