### ISSUE TITLE
Feature Request: Ability to change background color column in Xsheet

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#948]
![change-background-color-column-in-xsheet](https://cloud.githubusercontent.com/assets/16509592/20867716/06b27358-ba60-11e6-8b23-412c76252042.jpg)

**Comment by blurymind** [comment]
That would be nice to have!

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
