### ISSUE TITLE
Shortcuts not working on Mac 10.12.1

### ISSUE THREAD

**Issue by comikiki** [opentoonz/opentoonz#949]
I just got OT, and I'm having a lot of issues..
Im trying to edit the shortcuts to make ⌘ + Z do the undo command (I messed it up somehow and got rid of the command after using the default shortcut didnt work until minutes / hours later). Though, when I try to change a shortcut, the program crashes and closes.

I can't use my keyboard or even the drawing tablet's buttons for shortcuts at all. The shortcuts given dont work and I cant change them.

**Comment by artisteacher** [comment]
I can use the shortcuts without issue on 10.11.6 and 10.12.4 with the recent nightly builds. I can also change the shortcuts without crashing.

**Comment by turtletooth** [comment]
@comikiki If you are still having this issue with the nightly builds I can reopen this.
