### ISSUE TITLE
﻿Feature Request: Address bar for Shematic window

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#952]
Maybe you get lost without address bar in Shematic window and Sub-xsheets.

![address-bar-for-shematic-windows](https://cloud.githubusercontent.com/assets/16509592/20989372/abfa8ba8-bce9-11e6-86c4-dfbb18d88a02.jpg)

**Comment by blurymind** [comment]
Yes please! add this feature. most other animation and vector software has
it

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
