### ISSUE TITLE
Feature Request: Ability to use "Hand Tool" (Space key) in Shematic and Xsheet window

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#953]
You can use Zoom In/Out and Reset View with shortcut in "Shematic window".

If you have mouse, you can navigate with hold middle click. But you can't do that, if you have pen tablet (Wacom, Cintiq, etc). You can set one of the two pen button on middle click, but this is not good for all user.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
