### ISSUE TITLE
Feature Request: "Fit to Window" button in Viewer

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#954]
The schematic window has a "Fit to Window" button that would be really handy in both the Viewer and the Combo-viewer. I know there is a shortcut, but having a button would be more helpful for new learners.
![screen shot 2016-12-05 at 10 28 57 am](https://cloud.githubusercontent.com/assets/21159116/21010694/853f7b72-bd1b-11e6-8ad6-217230ce0e83.png)
![fittowindow1](https://cloud.githubusercontent.com/assets/21159116/21015693/fe32d5d2-bd30-11e6-8bf4-12837ae1f5b2.png)
![fittowindow2](https://cloud.githubusercontent.com/assets/21159116/21015696/ff266756-bd30-11e6-8d55-1311aa63f923.png)

**Comment by artisteacher** [comment]
My students get lost in the viewer periodically so this button would be really helpful for them.

**Comment by turtletooth** [comment]
Personally I think there are too many buttons already.  There is a keyboard shortcut and a right click option already.

BTW - What level do you teach?  I am middle school teacher in Colorado.

**Comment by artisteacher** [comment]
You are right about too many buttons! I keep several of them hidden. It is possible that the shortcut and right click option are enough but an argument could be made for consistency. The schematics menu has this button. If it was integrated with the viewer, it could be hidden by default and individual users could enable it. 

I teach high school art classes in Massachusetts. Always nice to meet another educator!

**Comment by artisteacher** [comment]
Closing due to the already crowded menu.
