### ISSUE TITLE
Missing level causes crash when saving

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#957]
On Mac OS X 10.11.6 & 10.11.4, a missing level causes a crash every time levels are saved (this includes "Save All" and "Save All Levels"). I do know that with the proper work flow (i.e. removing unused levels  after moving/deleting a level), this would not be an issue but for new learners, it would be helpful to have this resolved. 
![screen shot 2016-12-09 at 10 22 13 am](https://cloud.githubusercontent.com/assets/21159116/21054045/08a0d7ac-bdfa-11e6-9c44-f5c4d2a17dbd.png)
Perhaps when there is a missing level, saving could prompt a warning message asking to remove unused levels before saving.
[crash3.txt](https://github.com/opentoonz/opentoonz/files/642515/crash3.txt)

**Comment by turtletooth** [comment]
Does this bug apply to all level types?

**Comment by artisteacher** [comment]
Yes, missing vector, toonz raster, and raster levels all can cause a crash. Missing mp3's as well. Deleting wav and aiff files (without removing from the xsheet and scene cast) can still cause a crash, even though saving results in a new copy of the file saved to the original location. I haven't tested other file types but expect the same results. 

Sometimes the crash seems a little inconsistent but the following steps result in a crash every time. 
1. In the browser room, delete a level
2. Save All then close OpenToonz
3. Open OpenToonz and load the scene
4. Still in the Browser room,Save All
5. Change rooms - program crashes
