### ISSUE TITLE
CMake/Linux uses thirdparty include with system library by default

### ISSUE THREAD

**Issue by ideasman42** [opentoonz/opentoonz#962]
On Linux, using a system SuperLU, running CMake will pick the thirdparty include.

This is because its looking in the thirdparty hints path first: https://github.com/opentoonz/opentoonz/blob/master/toonz/cmake/FindSuperLU.cmake#L7 

Suggest to add an option: `WITH_SYSTEM_SUPERLU` which would disable using thirdparty paths when enabled.

**Comment by jabarrera** [comment]
The solution proposed in #958 is not enough for this?

**Comment by ideasman42** [comment]
@jabarrera, that PR scanned the path for the term third-party.

Instead, I'm suggesting to make this a build option.

**Comment by ideasman42** [comment]
Fixed cead1bb2cae97c48b833bec28588646d4bc9a693
