### ISSUE TITLE
Feature Request: Ability to connect Nodes to Group in Schematic

### ISSUE THREAD

**Issue by 2dvision** [opentoonz/opentoonz#969]
![connect-nodes-to-group](https://cloud.githubusercontent.com/assets/16509592/21267148/52aa9c38-c3be-11e6-8d14-273b56e3eaf9.gif)

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
