### ISSUE TITLE
Sound doesn't play during playback

### ISSUE THREAD

**Issue by AtsusaKaneytza** [opentoonz/opentoonz#970]
System: Windows 10 64-bit
RAM: 8GB
Running OpenToonz using a Nvidia GeForce 940M processor

I'm using the latest version of OpenToonz, and I'm having an issue where pressing the "Play" button doesn't actually playback the sound. FFMpeg is installed, and I was trying to playback with an MP3 file- however, scrubbing through the X-sheet manually will play the audio fine. This makes trying to animate a little bit hard, as it'd be nice to hear the sound playback properly so that I know where to put keyframes and such.

**Comment by artisteacher** [comment]
Are you using the combo-viewer? Currently the combo-viewer does not have audio playback. In the viewer, you can enable audio playback by pressing on the music icon at the bottom of the viewer.

**Comment by AtsusaKaneytza** [comment]
Ahh, I am using the combo viewer. I will keep that in mind the next time I'm able to use OpenToonz

**Comment by turtletooth** [comment]
Note - there is a new PR that will add sound to the combo viewer when approved.

**Comment by AtsusaKaneytza** [comment]
Thank you!
