### ISSUE TITLE
Bug: Attempts at changing Keyboard Shortcuts results in crash, and then ruins the rest of my keyboard shortcuts.

### ISSUE THREAD

**Issue by NuxGamedev** [opentoonz/opentoonz#976]
I tried changing the Pinch Tool to respond to the 'P' key instead of the 'M' key. Crashed after pressing the apply button. Restarted, and every keyboard shortcut I set during version 1.1.0  was found to be unresponsive (Grab on the Space Key, Pinch on P key, etc.).  This problem did not happen in ver. 1.1.0.

**Comment by shun-iwasawa** [comment]
@NuxGamedev  Thank you for reporting the issue. The PR #963 will fix this problem.
FYI, the "Apply" button in the Shortcut dialog is for overwriting all the shortcuts with a preset specified in the combo box. If you would like to change shortcut of some command, it can be done only by selecting the command and typing preferred key.

@turtletooth It seems that the current position of "Apply" button in the shortcut key dialog may be easily misunderstood that the button is for determining the shortcut key change of some command. Do you have any idea to clarify this..?

**Comment by turtletooth** [comment]
What about putting the whole area in a QGroupBox?
