### ISSUE TITLE
Updated open toonz, will not open old .tnz files ("not possible to load scene because it does not belong to any project."

### ISSUE THREAD

**Issue by lNeoConker** [opentoonz/opentoonz#977]
I have a couple old scenes from opentoonz 1.0. I recently upgraded to the recent release open toonz 1.1.2. I transfered over the old project folder and sandbox to the new one, with the new folders on c drive keeping all old stuff. I use external directories for the extras, outputs, scene folders etc. But keep the xml files on the c drive.

However while it does open the project, when i try to open the scene file (.tnz) it gives the error
"It is not possible to load the scene F:\................\ because it does not belong to any project." This is for both of my projects.

Is there any way to fix this?
![error](https://cloud.githubusercontent.com/assets/11846381/21468378/213bfe5c-c9dc-11e6-8eb9-39e6b8c53575.jpg)

**Comment by shun-iwasawa** [comment]
@lNeoConker Please try the following:

- Find a file "scenes.xml" in the "+scenes" folder.
- Open "scenes.xml". It will be like as follows:
 > \<parentProject type="projectFolder">
 > "_RELATIVE_PATH_TO_THE_OLD_PROJECT_ROOT_\\\\_PROJECT_NAME_"
 >\</parentProject>

- Replace "_RELATIVE_PATH_TO_THE_OLD_PROJECT_ROOT_" in the second line by the new one. You can set either relative or absolute path for it. So, in this case;
>  "F:\\\\My Documents\\\\OpenToonz\\\\JTT - Bullies FWP"

will work.

- Check if the scene can be loaded.
- If you would like to  save a scene in other than the "+scenes" folder, do the same way for other folders ("+drawings", "+extras" etc.).

**Comment by lNeoConker** [comment]
Thanks! it fixed everything.
