### ISSUE TITLE
How do I copy frame to frame?

### ISSUE THREAD

**Issue by SignsofLimerence** [opentoonz/opentoonz#98]
Is there anyway to copy frame to frame without having to trace with onion skin?
I'm having a very hard time figuring this out, does anyone have a solution? ^_^

**Comment by odysseywestra** [comment]
This kind of question is more suited for our Google Groups forums since this place is mainly for developmental use and not for user support. Please post your question there. Thanks: 

https://groups.google.com/forum/#!forum/opentoonz_en
