### ISSUE TITLE
Audio issues in Linux

### ISSUE THREAD

**Issue by Dioclends** [opentoonz/opentoonz#980]
Good day, there's several bugs in new version regarding audio functions; first, playing audio from column preview button in x-sheet produces only a cacophonous noise; second, scrubbing audio works but it instantly crashes; third, enabling soundtrack and playing back yields the same outcome. I'm using version 1.1.2 from GetDeb repository in Kubuntu 15.10.

**Comment by jabarrera** [comment]
After the launch of the Opentoonz 1.1.2 version (and after the updated-date in GetDeb Opentoonz log package) was launch a fix for this issue.

Please, could you check if latest nightly build resolves this? If you are not be able to compile Opentoonz yourself, request to the maintainer of that package to update it or you can test the AppImage (download and run) that is maintained by Morevna Project: https://gumroad.com/l/opentoonz-linux .

**Comment by ideasman42** [comment]
No reply in some weeks to issue we're quite sure has been fixed - closing.

**Comment by deanmoriart** [comment]
I have the same problem in xubuntu right now. Both in latest nightly build and Appimage.

**Comment by morevnaproject** [comment]
@deanmoriart This should be fixed in OpenToonz Morevna Edition 1.2.0.3 - https://morevnaproject.org/2018/08/18/opentoonz-morevna-edition-1-2-0-3-released/
