### ISSUE TITLE
OpenToonz_1.1.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by tombricks** [opentoonz/opentoonz#981]
The procedure entry point K32GetProcessMemoryInfo could not be located in the dynamic link library KERNEL32.dll.

______________________________________________________________________________________________________________
I used the setup found here: "https://github.com/opentoonz/opentoonz/releases" and I used Windows Vista.

**Comment by turtletooth** [comment]
Have you tried the portable version:  http://turtletooth.com/OpenToonzPortable/

**Comment by turtletooth** [comment]
Are you using any Blackmagic Design products or Camtasia?  Those have been know to also cause issues.

**Comment by tombricks** [comment]
No

**Comment by turtletooth** [comment]
Is your Windows 64 bit?

**Comment by turtletooth** [comment]
Are you running Windows 7 or newer?

**Comment by tombricks** [comment]
Windows Vista 64-Bit

**Comment by turtletooth** [comment]
I think that's the problem.  I don't think OpenToonz works on Vista- Only 7 or later.
