### ISSUE TITLE
Feature request: Sound Playback in Combo Viewer

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#985]
Hi! It would be super helpful to have sound playback in the combo-viewer and not just in the normal viewer. Personally, I really prefer using the combo-viewer since I can access the toolbar when in fullscreen and you can see more of the toolbar.  However, currently the combo-viewer is not usable during audio syncing when scrubbing directly in the viewer. I also think it is confusing for new learners if most of the viewer's functionality is in the combo-viewer but not all.

**Comment by turtletooth** [comment]
This is a decision for @shun-iwasawa - I believe he created the combo viewer and would need to be the one to decide if it should be modified.

**Comment by shun-iwasawa** [comment]
Sound playback in Viewer is really nice.
Sorry to mention so lately, but could you please add it to Combo Viewer as well?

**Comment by turtletooth** [comment]
Added in #995

**Comment by artisteacher** [comment]
Thanks so much!

**Comment by artisteacher** [comment]
@turtletooth - thanks again! It is super exciting to see this implemented. The audio playback is working great. Scrubbing through the combo viewer is still silent. Will audio scrubbing functionality directly through the combo viewer be added as well?
