### ISSUE TITLE
Option to build without QuickTime

### ISSUE THREAD

**Issue by Banbury** [opentoonz/opentoonz#987]
There should be an option to compile OpenToonz without QuickTime support. I don't want to install QuickTime. I don't want to register with Apple. I do not consider QuickTime support to be essential.

Does anyone know, what I have to change to make this possible?

**Comment by turtletooth** [comment]
You don't need Quicktime to compile or run OpenToonz.  I do it all the time. So you don't have to register with apple and I agree Quicktime is not essential.

**Comment by Banbury** [comment]
How do you do it then? The build instructions clearly say, QuickTime is needed. And when I try to build, the compiler is complaining about a missing QuickTime header.
If it's possible to build without QuickTime, the documentation should be updated.

**Comment by turtletooth** [comment]
I don't build the srv folder like the instructions say- I just use the srv folder that is part of my installed version.

**Comment by Banbury** [comment]
Thanks. I'll try that.

If it works, it should be documented.

**Comment by Banbury** [comment]
@ideasman42 This isn't just for MacOS. I'm on Windows.

**Comment by turtletooth** [comment]
Did it work for you?

**Comment by Banbury** [comment]
I will try on the weekend.

**Comment by turtletooth** [comment]
>If it works, it should be documented.

It is.  This is from the build instructions:
Copy the srv folder from the previous OpenToonz installation to the same folder as OpenToonz_1.0.exe

If there is no srv folder, OpenToonz can still be used. However, various file formats such as mov cannot be used.
Creating the files for srv is discussed later.

**Comment by Banbury** [comment]
@turtletooth This part of the documentation only deals with running the program **after** the program has been successfully compiled.

**Comment by Banbury** [comment]
@turtletooth Could you provide some steps, how you compile without QuickTime.

I just tried and I can't get it to work. The projects tnzcore, image and OpenToonz_1.1 use header files from QuickTime. Without those headers I can't compile. So copying the srv folder doesn't really help.

**Comment by turtletooth** [comment]
I will try and find time to make a video walking through the steps.  I just copy the srv folder to the Release folder in order for it to work.

**Comment by turtletooth** [comment]
Based on the discussion in #1207 feature requests are going to be closed here on GitHub unless there is a developer actively working on the feature. Feature requests can be discussed at the OpenToonz Google Group: https://groups.google.com/forum/#!forum/opentoonz_en
