### ISSUE TITLE
Crash On Startup Windows 7 64 bit

### ISSUE THREAD

**Issue by 1Bluefur** [opentoonz/opentoonz#99]
Hello I'm having a problem where every time I attempt to open OpenToonz I get an immediate error message that Opentoonz has stopped working.

Before people suggest it, I do not own any Logitech webcams and I have deleted the ff_vfw.dll as those seemed to be what people were having the most problems with.

I have tried running the program as administrator.

OS: Windows 7 Home Premium 64-bit
RAM: 8 GB
Processor: Intel Core Quad CPU 2.50GHz
Graphics Card: ATI FireGL V7600

**Comment by odysseywestra** [comment]
Is your problem similar to #77

**Comment by 1Bluefur** [comment]
Nope, I don't have multiple monitors and I uninstalled then reinstalled everything (making sure to delete the stuff folder and then cleaning my computer using cccleaner). Also when I said it crashes on start up I really meant it. I click the application to open it and immediately get the error. There's no chance for it to even begin loading.

**Comment by odysseywestra** [comment]
Okay could you open up your command prompt and type in `"C:\Program Files\OpenToonz 1.0\OpenToonz_1.0.exe"` and see what it says?

**Comment by BrandonJRamirez** [comment]
I am having the same exact issue using Windows 10. Immediately after I click to open the program it has the error saying that a problem has occurred causing Open Toonz to stop working.

**Comment by 1Bluefur** [comment]
I feel as though I may be missing something obvious, but when I type that in I get an error saying that "C:\Program" is not recognized.

**Comment by jcowgill** [comment]
@1Bluefur Type in the path exactly, with the quotes, without "cd".

**Comment by 1Bluefur** [comment]
Thank you jcowgill, I didn't realize I needed to keep the quotes. I got the same exact error, I'm assuming the command attempts to open the program?

**Comment by SafariMonkey** [comment]
Could you copy the command(s) and response(s) in here exactly? Also, could you go into that directory and verify that that file exists by that name?

**Comment by 1Bluefur** [comment]
The path definitely exists and the file is there. I just screenshot what it looks like after using the command.
![errors](https://cloud.githubusercontent.com/assets/18133686/14162029/41dc339c-f6b6-11e5-97ed-5ec0a5e605b1.png)

**Comment by SafariMonkey** [comment]
Ah, I'm sorry, I misunderstood your comment – I thought you meant you had the "directory name is invalid" or similar error, not the original one. Thanks for the information!

It looks like the program is spawned by the prompt, but the .exe completes before the error, or something. I'll leave it to someone else to suggest the next steps as Windows isn't my forté.

**Comment by turtletooth** [comment]
If this is still an issue, we can reopen.

**Comment by m93a** [comment]
I had this problem too. During installation I chose a different path for the `OpenToonz 1.2 stuff` – I saved it to `Program Files (x86)` and any time I started the program, I always got the "stopped working" error. Then I tried to move that folder and when I launched the program, instead of crashing, it gave me a propper error dialogue saying that the program couldn't find `OpenToonz 1.2 stuff` folder and I should reinstall it. When I did, leaving the stuff folder in with original path, the program started working.

**Comment by shun-iwasawa** [comment]
@m93a 
Thank you for the report. The folder `Program Files (x86)` is protected by [UAC (User Account Control)](https://en.wikipedia.org/wiki/User_Account_Control) and files in such folder cannot be changed easily even by Administrators with full control.

The crash seems to occur when OT tries and fails to create a new folder in the stuff folder for storing temporary cache data on launch.
To avoid crash, you need to obtain ownership of `Program Files (x86)/OpenToonz 1.2 stuff` manually after installation or just select another path which is not protected by UAC for the stuff folder. I recommend the latter option.

**Comment by m93a** [comment]
OK, thanks for your response. Maybe it would be wise to warn the user during instalation if they choose a UAC-protected folder. And catch the file access exception to give a proper warning.
