### ISSUE TITLE
Rendering without sound & Crashing Quite OFTEN

### ISSUE THREAD

**Issue by Mandea13** [opentoonz/opentoonz#993]
Since the update my scenes renders without the sound that is attached to the Table. Also during rendering or previewing opentoonz crashes quite often...

**Comment by turtletooth** [comment]
Can you give some steps that consistently cause a crash for you?

**Comment by Mandea13** [comment]
it crashes most of the time when I try to preview or render the scene.. Almost on que it will crash when i try to render the scene... 

i will restart the program and it will work but most of the time it just  continues to crash

**Comment by artisteacher** [comment]
Are you using any FX? Can you scrub the audio without crashing?

**Comment by Mandea13** [comment]
as far as FX... In the scene I have  videos that are being blended into a still image.. If that is what you are wanting to know about using FX
![fx](https://cloud.githubusercontent.com/assets/22448738/22120888/a3736496-de4f-11e6-9d17-dbd5ed1adb17.jpg)


As far as the audio goes it works just fine in the combo viewer, preview, scrubbing on the xsheet... The only problem is when I render.. 

Also the main problem I am having when rendering is when I render the complete xsheet... I am able to preview segments but if I want to preview or render the full thing through  that is when I run into these crashing prolems...

![pre crash](https://cloud.githubusercontent.com/assets/22448738/22121758/31f04056-de53-11e6-9669-fa5e426a4179.jpg)
![crash](https://cloud.githubusercontent.com/assets/22448738/22121777/42442d8c-de53-11e6-94cf-5152a412e3ac.jpg)

Plays fine when I preview a short part..

![plays](https://cloud.githubusercontent.com/assets/22448738/22121797/5669b7be-de53-11e6-9fb6-4e12300447aa.jpg)


Renders fine as well..

![play r](https://cloud.githubusercontent.com/assets/22448738/22121818/6aeb2092-de53-11e6-998d-e82ede8a2a00.jpg)

**Comment by artisteacher** [comment]
If you are rendering short segments successfully, and using an FFMPEG format (mp4 or etc), part of the issue could be the FFMPEG timeout. I've had issues where a short timeout value causes an incomplete video file (ie. corrupted) which then crashes OpenToonz when I try to re-render #955. In my case, deleting the the corrupted file and increasing the timeout value fixed that problem. In preferences, under import/export, you can increase the timeout value.  It's worth a try, anyway!

**Comment by turtletooth** [comment]
Did extending the FFMPEG timeout work?

**Comment by turtletooth** [comment]
If this is still an issue, we will need to be able to reproduce it before we are able to help.
