### ISSUE TITLE
Utility additions for the pencil test feature

### ISSUE THREAD

**Issue by shun-iwasawa** [opentoonz/opentoonz#996]
This request was asked by some Japanese animation studio. They are using OpenToonz for pencil testing.
Since they need to increase efficiency, they would like to have options which allow them to work on xsheet without touching mouse. Moving right hand back and forth between mouse and numpad is troublesome for them.

So, the following two options would be nice to have. Both of them should be optional in Preferences.
- [x] Typing arrow key on Xsheet shifts cell selection. (For now, typing up and down arrow keys moves current frame but clears cell selection.) Also, shift + arrow key increases/decreases cell selection range. 
- [x] Enable to input number of drawing into selected cell without double click.

(UPDATE: implemented in #999)

They usually share one PC by multiple animators. So they demands following feature (again, as an option in Preferences), in order to prevent overwriting by mistake captured images taken by another user:

- [x] On launching Camera Capture window, open a dialog to specify the folder location for saving captured images.  

Actually, these features are modeled after QuickChecker (now bundled in Retas Studio) by Celsys. Staff in the studio is familiar with QuickChecker and would like OpenToonz to enhance consistency with it.

**Comment by jabarrera** [comment]
About the first, what do you think about use **ctrl** + up/down to the shifts?

With that map key, the user can work only with the right hand and the actual behavior of the arrow keys can be maintained. In fact, I think that the two options could alive together.


I like the second. It will be really useful. Now is a bit "annoying" the double-click (and the unselection of the text) to introduce just the number. It will be interesting see how to solve this. :)

**Comment by turtletooth** [comment]
> Enable to input number of drawing into selected cell without double click.
What are your thoughts on adding this to the function editor also?

**Comment by shun-iwasawa** [comment]
@jabarrera Thank you for the comments.
The main objective for this option is to make the operations of pencil test as simple as possible. Especially, the pencil test work are done by animators working on papers, and they tend to be unwilling to do complicated operations. 
Your suggestion to use `Ctrl` for the shift does have valid point, but I think it would better to make it with no modifier for the above reason. And if users find that this feature is useful, it would be nice to enable it in any case,  but only with some modifier pressed if the preference option is OFF. (Maybe in the future, as a separate PR.)

BTW I found that `Shift+Up` and `Shift+Down` keys are already reserved for ”skip holding frame”, so I will use `Ctrl` modifier for the increase/decrease of cell selection range.

@turtletooth Thank you for your suggestion. It makes sense from the perspective of consistency.

**Comment by shun-iwasawa** [comment]
The former two options are implemented. Please note that the Function Editor is not changed yet. I would like to separate it to another future PR.

**Comment by shun-iwasawa** [comment]
The last option is implemented.

**Comment by turtletooth** [comment]
#1008 merged
