### ISSUE TITLE
Deleted scenes show in startup pop-up

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz#997]
If I delete a scene (either in the browser room or directly through the stuff/projects folder) and re-open OpenToonz, the list of recent scenes in the startup pop-up still displays the names of any deleted scenes. Selecting that deleted scene opens the default, unsaved and empty scene. Then the next time I access the startup pop-up, the deleted scene's name is at the top of the list of scenes. I'm not sure if this is an issue in other OS but I've noticed this issue with OS X 10.9.5, 10.11.6, and 10.12.2.

**Comment by turtletooth** [comment]
It's going to be an issue on all OSes - I'll see if I can make a check for the scene existing before the list populates.

**Comment by ideasman42** [comment]
Would be careful attempting to fix this. IIRC Blender had this reported too & resolved too,
then people complain that the application starts slow.

Turns out if you have a bunch of files on a network drive - it can slow down startup considerably just to check they exist.

**Comment by turtletooth** [comment]
Any suggestions?  Would you leave it and let people realize - oh yeah, I deleted that?  Or something else?

**Comment by turtletooth** [comment]
I think I'm only going to check for the file once it has been clicked and if it doesn't exist, give a popup warning and refresh the list then.  What do you think?

**Comment by ideasman42** [comment]
Yeah, some way to handle the case where the file doesnt exist is nice, "This file is missing, remove from recent file list..." or similar.

**Comment by turtletooth** [comment]
Fixed in #998

**Comment by turtletooth** [comment]
Thanks @ideasman42 for the advice.

**Comment by artisteacher** [comment]
Thank you!

**Comment by ideasman42** [comment]
Any reason to keep the report open?
